### ISSUE TITLE
Support for Windows 10+

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1]
## Description ##
The solution should be available to windows users starting with Windows 10 and above.

## Acceptance criteria ##

- Container Desktop is starting on windows 10 and all its components (tray and dashboard) are properly integrated:
  - The tray is properly integrated in the windows toolbar
  - The dashboard is running as an application natively integrated
- CI is setup, configured to test the tool on windows 10

**Comment by benoitf** [comment]
binary provided for windows (exe or with nsis installer)
