### ISSUE TITLE
Heavy load trying to connect to Podman socket if socket is not reachable

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#10016]
### Bug description

Due a to bug on Podman 5.3.0 (socket can't be created if Podman is installed by scoop) I noticed a lot of errors trying to connect to the socker in the log at a very high rate.

To reproduce start a podman machine and kill the win-sshproxy

### Operating system

Win11 Pro

### Installation Method

None

### Version

1.14.0

### Relevant log output

```shell

```

**Comment by gastoner** [comment]
Duplicate of https://github.com/podman-desktop/podman-desktop/issues/8681 ?

**Comment by slemeur** [comment]
duplicate, closing in favor #8681
