### ISSUE TITLE
Minikube v0.4.0 does not show in resources

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#10038]
### Bug description

Minikube does not show in resources after installation, executable install prompt not visible in toolbar, logs show error of missing executable, but extension initializes.

### Operating system

macOS 14.5 M2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

* Install latest nightly build of Podman Desktop
* Install Podman 5.3.0 from repo dmg installer
* Install Minikube extension from Catalog

### Relevant log output

```shell

```

### Additional context

![Image](https://github.com/user-attachments/assets/f9200c98-b127-4ae3-9ea7-c1276b446bfb)
![Image](https://github.com/user-attachments/assets/574e547e-cf32-45c0-9964-81cd288269fb)
![Image](https://github.com/user-attachments/assets/7238cfab-ed6b-49a4-8473-0103a66901f2)

**Comment by odockal** [comment]
@ScrewTSW We should move issue into minikube extension repository.

**Comment by ScrewTSW** [comment]
@odockal done https://github.com/podman-desktop/extension-minikube/issues/248
