### ISSUE TITLE
Weird bottom border on DetailsPage

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#10049]
### Bug description

Due to the following line

https://github.com/podman-desktop/podman-desktop/blob/8e035466797846cc411d51c3becf60cd90dd6833/packages/ui/src/lib/layouts/DetailsPage.svelte#L26

We have this repetitive line

![Image](https://github.com/user-attachments/assets/242a276f-dbbc-4150-bddd-9ddb0e4f6805)

This is not really a problem when we have tabs, but this is a problem for DetailsPage without tabs

![Image](https://github.com/user-attachments/assets/72c60ed0-01fe-4ee2-ad71-0d45b39fac6b)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Removing it look good (IMO)

![Image](https://github.com/user-attachments/assets/841e6c78-6a38-4e0f-b6d5-afcabe6d833a)

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
adding unplanned
