### ISSUE TITLE
vscode focus border is a weird blue

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#10052]
### Bug description

We have some blue lines at top and bottom of the editor

![Image](https://github.com/user-attachments/assets/444610fa-8cfc-4583-a9cb-dafa6ac4abff)

This is controled by the `--vscode-focusBorder #007fd4` , I think we should set this to `transparent`

This is the first time I noticed it, but they seems to have some issue open on their side https://github.com/microsoft/monaco-editor/issues/4455 ?

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. goto any resource and check for a monaco editor

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
I would say this issue is not urgent, we have other bugs with an higher priority in the backlog

**Comment by axel7083** [comment]
>I would say this issue is not urgent, we have other bugs with an higher priority in the backlog

I encounter that while working on https://github.com/podman-desktop/podman-desktop/issues/8845, that's why, this is very ugly :(
