### ISSUE TITLE
Light mode issue on tasks popups

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#10071]
### Bug description

![Image](https://github.com/user-attachments/assets/de133a8a-6c78-4f58-a4aa-10844acbdd16)

Cannot read the information that's shown in light mode

### Operating system

macOS M1

### Installation Method

None

### Version

1.14.0

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
looks a dup of https://github.com/podman-desktop/podman-desktop/issues/9990, https://github.com/podman-desktop/podman-desktop/issues/9779 and https://github.com/podman-desktop/podman-desktop/issues/9869

Fixed by https://github.com/podman-desktop/podman-desktop/pull/9915 ?

**Comment by cdrage** [comment]
> looks a dup of [#9990](https://github.com/podman-desktop/podman-desktop/issues/9990), [#9779](https://github.com/podman-desktop/podman-desktop/issues/9779) and [#9869](https://github.com/podman-desktop/podman-desktop/issues/9869)
> 
> Fixed by [#9915](https://github.com/podman-desktop/podman-desktop/pull/9915) ?

Ahhh you are right, my mistake. Should of been testing against dev.
