### ISSUE TITLE
View Release Notes button links to wrong Github URL

### ISSUE THREAD

**Issue by sdemjanenko** [containers/podman-desktop#10084]
### Bug description

The UI dialog that opens when clicking to see info on the new version contains a "View release notes" button. This took me to `https://github.com/podman-desktop/podman-desktop/releases/tag/vv1.14.1` which has an incorrect tag. It should be `v1.14.1` and not `vv1.14.1`.

![Image](https://github.com/user-attachments/assets/4f37b987-1ebf-4fff-a1ac-f3c191fabb50)

### Operating system

mac OS 15.1.1

### Installation Method

Installer from website/GitHub releases

### Version

1.13.2

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
Thanks for your report @sdemjanenko 

It's a dup of https://github.com/podman-desktop/podman-desktop/issues/9447 fixed in 1.14.x
