### ISSUE TITLE
bug(ui): Update Available Now modal too wide

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#10101]
### Bug description

When I started my old podman desktop v1.13.2 today, got the following modal

![Image](https://github.com/user-attachments/assets/0222c319-1439-416d-ae4c-7652fe8ed908)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.2

### Steps to reproduce

1. start old version of podman-desktop
2. assert modal popup too wide

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
It's a dup of https://github.com/podman-desktop/podman-desktop/issues/9393 ( and a lot of others duplicated one)
