### ISSUE TITLE
Podman Desktop Connection Refused/No Running Provider for the Matching Container

### ISSUE THREAD

**Issue by PStoner3** [containers/podman-desktop#10102]
### Bug description

Podman Desktop cannot pull images, run containers, or builds. Attempting to run the troubleshooting steps, the "ping", "Check containers", and "Reconnect providers" do not work and report "Error: no running provider for the matching container".

This issue is similar to the following issues:
[#8548](https://github.com/podman-desktop/podman-desktop/issues/8548)
[#6982](https://github.com/podman-desktop/podman-desktop/issues/6982)
[#6455](https://github.com/podman-desktop/podman-desktop/issues/6455)
[#5186](https://github.com/podman-desktop/podman-desktop/issues/5186)
[#2096](https://github.com/podman-desktop/podman-desktop/issues/2096)

Suggestions in the other tickets:
* Clicking the "Reconnect providers" button
* Clicking the "Ping" button
* Clicking the "Check containers" button
* Stopping and starting the podman machine
Do not resolve the issue.

Podman Desktop shows my podman machine is running
![Image](https://github.com/user-attachments/assets/99694c08-6c93-456a-9391-237f5ba8bd72)

But the troubleshooting tool will not work
![Image](https://github.com/user-attachments/assets/548c3604-20a7-4855-859b-8299221bc035)

I've tried running:
* The podman machine from an admin terminal and desktop as a non-admin user
* The podman machine as a non-admin and desktop as admin
* Both as non-admin
* Both as admin
None of these have corrected the issue either. I've recreated the default machine several times as well as using both rootful and rootless machines. Still no luck.

Attempts to debug Podman Desktop report the following:
1:32:00 PM [main] error is AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED 127.0.0.1:2375
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 2375
    },
    Error: connect ECONNREFUSED ::1:2375
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 2375
    }
  ]
}

It looks like it is attempting to connect to the Docker Desktop connection and port.

Full logs are attached.

OS: Windows 10 version 22H2 (build 19045.5011)

WSL: 
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5011

Podman: 
Client:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.23.3
Git Commit:   4cbdfde5d862dcdbe450c0f1d76ad75360f67a3c
Built:        Thu Nov 21 08:45:23 2024
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      5.3.0
API Version:  5.3.0
Go Version:   go1.22.7
Built:        Tue Nov 12 17:00:00 2024
OS/Arch:      linux/amd64

Podman info:
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.76
    systemPercent: 0.15
    userPercent: 0.08
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "40"
  eventLogger: journald
  freeLocks: 2048
  hostname: AKRJPGFWT3
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.167.4-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 7567204352
  memTotal: 8332451840
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.18.2-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.18.2
      commit: 00ab38af875ddd0d1a8226addda52e1de18339b5
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20241030.gee7d0b6-1.fc40.x86_64
    version: |
      pasta 0^20241030.gee7d0b6-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589934592
  swapTotal: 8589934592
  uptime: 0h 17m 50.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 1158393856
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes

Podman Desktop: version 1.14.1

podman machine info (for default machine)
host:
    arch: amd64
    currentmachine: podman-machine-default
    defaultmachine: ""
    eventsdir: C:\Users\*****\.local\share\containers\podman\podman
    machineconfigdir: C:\Users\*****\.config\containers\podman\machine\wsl
    machineimagedir: C:\Users\*****\.local\share\containers\podman\machine\wsl
    machinestate: Running
    numberofmachines: 1
    os: windows
    vmtype: wsl
version:
    apiversion: 5.3.1
    version: 5.3.1
    goversion: go1.23.3
    gitcommit: 4cbdfde5d862dcdbe450c0f1d76ad75360f67a3c
    builttime: Thu Nov 21 08:45:23 2024
    built: 1732203923
    osarch: windows/amd64
    os: windows

podman machine inspect (for default machine)
[
     {
          "ConfigDir": {
               "Path": "C:\\Users\\*****\\.config\\containers\\podman\\machine\\wsl"
          },
          "ConnectionInfo": {
               "PodmanSocket": {
                    "Path": "C:\\Users\\*****\\AppData\\Local\\Temp\\podman\\podman-machine-default-api.sock"
               },
               "PodmanPipe": {
                    "Path": "\\\\.\\pipe\\podman-machine-default"
               }
          },
          "Created": "2024-11-21T13:43:26.0943048-07:00",
          "LastUp": "2024-11-25T12:26:54.7621394-07:00",
          "Name": "podman-machine-default",
          "Resources": {
               "CPUs": 4,
               "DiskSize": 100,
               "Memory": 1024,
               "USBs": []
          },
          "SSHConfig": {
               "IdentityPath": "C:\\Users\\*****\\.local\\share\\containers\\podman\\machine\\machine",
               "Port": 54583,
               "RemoteUsername": "user"
          },
          "State": "running",
          "UserModeNetworking": true,
          "Rootful": true,
          "Rosetta": false
     }
]

System Connection list:
podman-machine-default       ssh://user@127.0.0.1:54583/run/user/1000/podman/podman.sock  C:\Users\*****\.local\share\containers\podman\machine\machine  false       true
podman-machine-default-root  ssh://root@127.0.0.1:54583/run/podman/podman.sock            C:\Users\*****\.local\share\containers\podman\machine\machine  true        true

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.14.1

### Relevant log output

```shell
Podman Desktop log:
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
error : main ↪️ Error occurred in handler for 'configuration-registry:getConfigurationValue': Error: No handler registered for 'configuration-registry:getConfigurationValue'
error : main ↪️ Error occurred in handler for 'configuration-registry:getConfigurationValue': Error: No handler registered for 'configuration-registry:getConfigurationValue'
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Starting http server to handle webviews on port 44000
log : main ↪️ Delayed startup, flushing 6 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Error while fetching API groups: Error: No active cluster!
log : main ↪️ Error while fetching API groups: Error: No active cluster!
log : main ↪️ Extension (podman-desktop.compose) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.docker) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.kind) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.kube-context) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.kubectl-cli) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.lima) not activated because it is disabled
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 724.5959000000003ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 482.5077000000001ms
warn : main ↪️ [podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ Activating extension (podman-desktop.podman) ended in 18574 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 2 milliseconds
log : main ↪️ Extension (redhat.ai-lab) not activated because it is disabled
log : main ↪️ Extension (podman-desktop.minikube) not activated because it is disabled
log : main ↪️ Extension (redhat.redhat-authentication) not activated because it is disabled
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting podman-desktop.podman container engine
log : main ↪️ [podman] Podman extension: Do not start a machine as there is already one starting or started
log : main ↪️ Skipping update for extension redhat.ai-lab because installed version 1.3.2 is greater or equal to latest available version 1.3.2
log : main ↪️ Skipping update for extension podman-desktop.minikube because installed version 0.4.0 is greater or equal to latest available version 0.4.0
log : main ↪️ Skipping update for extension redhat.redhat-authentication because installed version 1.0.2 is greater or equal to latest available version 1.0.2
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
warn : main ↪️ [podman]  Can't get machine podman-machine-default resource usage error Error: no running provider for the matching container
log : main ↪️ error is Error
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events

Debugging output
1:30:30 PM [main] Debugger attached.
1:31:14 PM [main] DevTools listening on ws://127.0.0.1:9223/devtools/browser/15ce0628-8ec3-49ad-805f-bde4e3efe9a7
Development mode, skipping startup install
1:31:29 PM [main] Development mode, skipping startup install
Starting http server to handle webviews on port 44000
System ready. Loading extensions...
Error while fetching API groups: Error: No active cluster!
Error while fetching API groups: Error: No active cluster!
Fetched https://registry.podman-desktop.io/api/extensions.json in 2736.810700000002ms
Extension (podman-desktop.compose) not activated because it is disabled
1:31:34 PM [main] Starting http server to handle webviews on port 44000
System ready. Loading extensions...
Error while fetching API groups: Error: No active cluster!
Error while fetching API groups: Error: No active cluster!
Fetched https://registry.podman-desktop.io/api/extensions.json in 2736.810700000002ms
Extension (podman-desktop.compose) not activated because it is disabled
Extension (podman-desktop.docker) not activated because it is disabled
1:31:35 PM [main] Extension (podman-desktop.docker) not activated because it is disabled
Extension (podman-desktop.kind) not activated because it is disabled
1:31:35 PM [main] Extension (podman-desktop.kind) not activated because it is disabled
Extension (podman-desktop.kube-context) not activated because it is disabled
1:31:35 PM [main] Extension (podman-desktop.kube-context) not activated because it is disabled
Extension (podman-desktop.kubectl-cli) not activated because it is disabled
1:31:35 PM [main] Extension (podman-desktop.kubectl-cli) not activated because it is disabled
Extension (podman-desktop.lima) not activated because it is disabled
1:31:36 PM [main] Extension (podman-desktop.lima) not activated because it is disabled
Activating extension (podman-desktop.podman) with max activation time of 20 seconds
1:31:36 PM [main] Activating extension (podman-desktop.podman) with max activation time of 20 seconds
1:31:42 PM [main] [4972:1125/133139.812:ERROR:CONSOLE(2)] "Uncaught (in promise) Error: Error invoking remote method 'BROWSER_GET_LAST_WEB_PREFERENCES': WebContents was destroyed", source: node:electron/js2c/sandbox_bundle (2)
[podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
Activating extension podman-desktop.podman failed error:Error: Extension podman-desktop.podman activation timed out after 20 seconds
Activating extension (podman-desktop.registries) with max activation time of 20 seconds
Activating extension (podman-desktop.registries) ended in 1 milliseconds
Extension (redhat.ai-lab) not activated because it is disabled
Extension (podman-desktop.minikube) not activated because it is disabled
Extension (redhat.redhat-authentication) not activated because it is disabled
PluginSystem: initialization done.
Skipping update for extension redhat.ai-lab because installed version 1.3.2 is greater or equal to latest available version 1.3.2
Skipping update for extension podman-desktop.minikube because installed version 0.4.0 is greater or equal to latest available version 0.4.0
Skipping update for extension redhat.redhat-authentication because installed version 1.0.2 is greater or equal to latest available version 1.0.2
1:31:57 PM [main] [podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
1:31:57 PM [main] Activating extension podman-desktop.podman failed error:Error: Extension podman-desktop.podman activation timed out after 20 seconds
Activating extension (podman-desktop.registries) with max activation time of 20 seconds
Activating extension (podman-desktop.registries) ended in 1 milliseconds
Extension (redhat.ai-lab) not activated because it is disabled
Extension (podman-desktop.minikube) not activated because it is disabled
Extension (redhat.redhat-authentication) not activated because it is disabled
PluginSystem: initialization done.
Skipping update for extension redhat.ai-lab because installed version 1.3.2 is greater or equal to latest available version 1.3.2
Skipping update for extension podman-desktop.minikube because installed version 0.4.0 is greater or equal to latest available version 0.4.0
Skipping update for extension redhat.redhat-authentication because installed version 1.0.2 is greater or equal to latest available version 1.0.2
error is AggregateError
    at internalConnectMultiple (f:\code\tools\podman-desktop\lib\net.js:1118:18)
    at afterConnectMultiple (f:\code\tools\podman-desktop\lib\net.js:1685:7)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {code: 'ECONNREFUSED', stack: 'AggregateError [ECONNREFUSED]: 
    at intern…Trampoline (node:internal/async_hooks:130:17)', errors: Array(2)}
Error when handling events Error: Error in handling events
    at Object.callback (f:\code\tools\podman-desktop\packages\main\src\plugin\container-registry.ts:203:23)
    at f:\code\tools\podman-desktop\node_modules\dockerode\lib\docker.js:1441:12
    at Modem$1.buildPayload (f:\code\tools\podman-desktop\node_modules\docker-modem\lib\modem.js:375:19)
    at ClientRequest.<anonymous> (f:\code\tools\podman-desktop\node_modules\docker-modem\lib\modem.js:356:12)
    at ClientRequest.emit (f:\code\tools\podman-desktop\lib\events.js:519:28)
    at emitErrorEvent (f:\code\tools\podman-desktop\lib\_http_client.js:101:11)
    at Socket.socketErrorListener (f:\code\tools\podman-desktop\lib\_http_client.js:504:5)
    at Socket.emit (f:\code\tools\podman-desktop\lib\events.js:519:28)
    at emitErrorNT (f:\code\tools\podman-desktop\lib\internal\streams\destroy.js:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3) {stack: 'Error: Error in handling events
    at Object…CloseNT (node:internal/streams/destroy:128:3)', message: 'Error in handling events'} Will reconnect in 5s Error: Error in handling events
    at Object.callback (f:\code\tools\podman-desktop\packages\main\src\plugin\container-registry.ts:203:23)
    at f:\code\tools\podman-desktop\node_modules\dockerode\lib\docker.js:1441:12
    at Modem$1.buildPayload (f:\code\tools\podman-desktop\node_modules\docker-modem\lib\modem.js:375:19)
    at ClientRequest.<anonymous> (f:\code\tools\podman-desktop\node_modules\docker-modem\lib\modem.js:356:12)
    at ClientRequest.emit (f:\code\tools\podman-desktop\lib\events.js:519:28)
    at emitErrorEvent (f:\code\tools\podman-desktop\lib\_http_client.js:101:11)
    at Socket.socketErrorListener (f:\code\tools\podman-desktop\lib\_http_client.js:504:5)
    at Socket.emit (f:\code\tools\podman-desktop\lib\events.js:519:28)
    at emitErrorNT (f:\code\tools\podman-desktop\lib\internal\streams\destroy.js:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3) {stack: 'Error: Error in handling events
    at Object…CloseNT (node:internal/streams/destroy:128:3)', message: 'Error in handling events'}
1:32:00 PM [main] error is AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED 127.0.0.1:2375
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 2375
    },
    Error: connect ECONNREFUSED ::1:2375
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 2375
    }
  ]
}
```

### Additional context

[podman-desktop-20241125111619.zip](https://github.com/user-attachments/files/17908900/podman-desktop-20241125111619.zip)

**Comment by benoitf** [comment]
hello @PStoner3 do you any environment variables like `DOCKER_HOST` or `CONTAINER_HOST` being set ?

if yes, could you disable them ?

**Comment by PStoner3** [comment]
I do not believe there are environment variables set. I will double check and report back

**Comment by PStoner3** [comment]
@benoitf, My apologies. I did have the `DOCKER_HOST` variable set. I am now able to use Podman-Desktop after removing it.
