### ISSUE TITLE
Website: Update /extend to include links to the new extensions page

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#10114]
### Is your enhancement related to a problem? Please describe

Right now the focus of the /extend page is to how you can build new extensions. We want to improve the page so it also highlights some the current extensions we already have. We should link to the /extensions page so they can see find all extensions.

### Describe the solution you'd like

Rough page structure should be:

Highlighted extensions
Link to all extenions (https://podman-desktop.io/extensions)
The current content on the page, that explains how to add new extensions

**Comment by cdrage** [comment]
> ### Is your enhancement related to a problem? Please describe
> Right now the focus of the /extend page is to how you can build new extensions. We want to improve the page so it also highlights some the current extensions we already have. We should link to the /extensions page so they can see find all extensions.
> 
> ### Describe the solution you'd like
> Rough page structure should be:
> 
> Highlighted extensions Link to all extenions (https://podman-desktop.io/extensions) The current content on the page, that explains how to add new extensions

I see no UX/UI issue / mock up issue so I could implement this.

Unsure what UI/UX you want for "highlighted xtensions, current context on page, link to all extensions".

Unless you just want these links updated?

 ![Image](https://github.com/user-attachments/assets/44ce709e-5181-4690-957d-54d849fd3c8b)

**Comment by Firewall** [comment]
This a first version. The main goal here show of the list of extensions we already support not just how to make new ones. I would add a new `h1` and then list the last 3 or 4 updated extensions from the [/extensions](https://podman-desktop.io/extensions) page. We can re-use the tiles from that page. Then a link with `see all extensions` that takes you to the [/extensions](https://podman-desktop.io/extensions) page.

We can always do a UX pass in the future if we think it is needed.

**Comment by cdrage** [comment]
> This a first version. The main goal here show of the list of extensions we already support not just how to make new ones. I would add a new `h1` and then list the last 3 or 4 updated extensions from the [/extensions](https://podman-desktop.io/extensions) page. We can re-use the tiles from that page. Then a link with `see all extensions` that takes you to the [/extensions](https://podman-desktop.io/extensions) page.
> 
> We can always do a UX pass in the future if we think it is needed.

The information from /extensions is an iframe, so if were to have this information in https://podman-desktop.io/extend like you say, it would require bringing over the CSS, etc.

If you want, we could just show the iframe of the last 4 last-updated.. but unsure if that's feasible.

cc @benoitf what are our thoughts / how could we implement this?

**Comment by cdrage** [comment]
Putting on hold @Firewall @benoitf until we figure out the UX/UI for this as unsure how we want to implement this.

We could use your suggestion @Firewall regarding the last 4 updated, but will have to be done in the iframe / upstream part of `/extensions`?

cc @MariaLeonova I'm not sure if you already have a mockup of this

**Comment by benoitf** [comment]
> The information from /extensions is an iframe, so if were to have this information in https://podman-desktop.io/extend like you say, it would require bringing over the CSS, etc.

> If you want, we could just show the iframe of the last 4 last-updated.. but unsure if that's feasible.

> cc @benoitf what are our thoughts / how could we implement this?

if we want to have some options here, it means the catalog page should listen to some query parameters on the URL to handle a behaviour change

it's not 100% clear (at least on my end) on how the rendering should look like.

**Comment by cdrage** [comment]
@Firewall @benoitf Discussed with Matt, created https://github.com/podman-desktop/podman-desktop/pull/10382 as a temporary measure until we can update the page with last X updated extensions after company shutodnw.

**Comment by MariaLeonova** [comment]
@cdrage I don't yet have a mock, but I can take a look. I see you've agreed to postpone till after shutdown? Let me know :)
