### ISSUE TITLE
Task for pulling image

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#10121]
### Is your enhancement related to a problem? Please describe

Related to #9536, but I found out the hard way that we don't actually have a pull image task. If you start to pull a 1.5Gb image and leave the page like I did, there's no way to see status, failure, or cancel it. You just wait and see if the image appears in the list after some period of time... or doesn't.

### Describe the solution you'd like

Pulling an image should create a task, with a goto link so that you can return to the page to see updates or cancel it.

Any sort of progress would be nice for bigger images.

**Comment by dgolovin** [comment]
It looks like duplicate or at least sub-issue of https://github.com/podman-desktop/podman-desktop/issues/8482.

**Comment by deboer-tim** [comment]
#8482 is for push image, this is pull. It's the same problem so could maybe go under an epic together, but since they'd be delivered independently I don't think this is a dup nor should either one be a child of the other.

**Comment by benoitf** [comment]
To me it's a dup of https://github.com/podman-desktop/podman-desktop/issues/9989

**Comment by deboer-tim** [comment]
They are a bit separate but agree they overlap heavily, so I've added a comment in #9989 and closing this.
