### ISSUE TITLE
Stopping a pod from the containers list

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1012]
### Is your enhancement related to a problem? Please describe

As a user, when I want to stop a Pod, I either have to go to the list of Pods or I have to individually stop each of the containers of the Pod. 

### Describe the solution you'd like

As a user, I would like the ability to stop a running pod (all its containers) directly from the list of containers

Adding an action should be good enough:
<img width="1441" alt="Capture d’écran 2022-12-12 à 10 08 04" src="https://user-images.githubusercontent.com/1636769/207007463-33199a11-3666-4db7-ba65-95b2f20a0277.png">

**Comment by deboer-tim** [comment]
You can start and stop pods from the containers list now.
