### ISSUE TITLE
When "podifying", I should be able to define the ports I want to open

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1017]
### Is your enhancement related to a problem? Please describe

As a user, I would like to define which ports from my containers I want to expose.

### Describe the solution you'd like

Adding the ability to select the ports to be opened from the selected containers

<img width="1441" alt="Capture d’écran 2022-12-12 à 10 28 08" src="https://user-images.githubusercontent.com/1636769/207010231-128d8254-2464-455c-871b-5ad27ae2c05f.png">

**Comment by benoitf** [comment]
Hi, what we would like to be able to configure is at these lines:
https://github.com/containers/podman-desktop/blob/895d031560293653cd0bdf6271b7470cce8cf6d3/packages/renderer/src/lib/pod/PodCreateFromContainers.svelte#L62-L65

PortMappings are grabbed from all containers but user should be able to only select a subset of the exposed ports.
(for example keeping a database port internally within the pod and not exposed it to the outside)
