### ISSUE TITLE
Rework the UI/UX of the form to "Podify" containers

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1018]
### Is your enhancement related to a problem? Please describe

The UI/UX for the "podify" feature should be revisited

<img width="1441" alt="Capture d’écran 2022-12-12 à 10 28 08" src="https://user-images.githubusercontent.com/1636769/207011019-3292754a-cfa6-4f83-a288-57dc1cd1568a.png">

### Describe the solution you'd like

The UI/UX for the "podify" feature should be revisited.

**Comment by benoitf** [comment]
it has been changed since the screenshot, closing
