### ISSUE TITLE
Propose alternate ports when starting a container with already used ports

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1019]
### Is your enhancement related to a problem? Please describe

When creating/starting a container, whose ports are already used, I'd like to be given an option to change the ports to other ones which should not be in use.

### Describe the solution you'd like

We should be:
- raising the error that the ports are already in use
- Suggest to use another port

Something like "Port 8080 is already in use, replace by 7070", where "replace by 7070" would be an hyperlink

**Comment by benoitf** [comment]
usually it displays to the user free port

**Comment by benoitf** [comment]
closing as won't fix as it's more than one year that issue has been created
