### ISSUE TITLE
Kube Config Error breaks starting behavior

### ISSUE THREAD

**Issue by alexanderniebuhr** [containers/podman-desktop#1022]
### Bug description

Desktop App does not start, hangs in Initialising state, after following error is thrown.
_(deleting the kubernetes config, fixes the issue, but the app should handle the error and show the user an message without the need to open dev tools)_

[cluster-config.log](https://github.com/containers/podman-desktop/files/10211690/cluster-config.log)

### Operating system

macOS Ventura 13.1 Beta (22C5059b)

### Version

0.10.0

**Comment by benoitf** [comment]
Hello, it looks like a dup of https://github.com/containers/podman-desktop/issues/951

You may try to use a pre-release version as it'll be fixed in 0.11
https://github.com/containers/podman-desktop/releases

**Comment by alexanderniebuhr** [comment]
Yeah, seems like a dup. Didn't find the other one, because it was closed. :/
