### ISSUE TITLE
Customize icon in containers list based on container image name

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#10248]
### Is your enhancement related to a problem? Please describe

Extension should be able to customize the status icon in the containers list, based on the container image

### Describe the solution you'd like

Add the container image in the context provided to the `when` part of the contribution, so this `when` is accepted.

```
"icons/containersList": [
  {
    "when": "containerImageName =~ /docker\\.io\\/library\\/my-image/",
    "icon": "${my-icon}"
  }
]
```

**Comment by benoitf** [comment]
IMHO the property name should be `containerImageName` (as containerImage could say that it's providing all the fields or is it the image Id, the name, the tags, etc

**Comment by benoitf** [comment]
adding unplanned label
