### ISSUE TITLE
Expose Socket Path to Docker Extensions

### ISSUE THREAD

**Issue by RobotSail** [containers/podman-desktop#1027]
### Is your enhancement related to a problem? Please describe

I would like to be able to access the socket path for the implementation of #460, so that I can pass it in as a command-line variable to the FetchIt container.
This is easy to do on Linux since the socket path is fairly constant, however it is a pain to do on MacOS and Windows because you are required to know information about filesystem paths which can only be accessed in the main process and must be exposed through the context bridge.

### Describe the solution you'd like

Maybe there could be an API provided within the `ddClient` or another custom client which provides a `socketPath` variable that I could read. The only problem that I can think of is that MacOS uses Podman machines, which implies multiple sockets.

**Comment by benoitf** [comment]
while we can provide additional extension points it means it'll work only for Docker Desktop extensions running on top of Podman Desktop.

**Comment by RobotSail** [comment]
That shouldn't be a problem in #460 since FetchIt was designed to only work with Podman and not Docker. Could there be a way that we could introduce this information without impairing extensions that can work with either?

Or would it be a better idea to simply have our FetchIt extension live as an extension that's built into Podman desktop, and has easier access to those APIs without needing to make any fundamental changes?
