### ISSUE TITLE
Javascript Error Popup Invalid Argument

### ISSUE THREAD

**Issue by pcartwright81** [containers/podman-desktop#10286]
### Bug description

Just going about my day not even touching Podman and it got mad at me.

![Image](https://github.com/user-attachments/assets/8667aa7b-545b-4865-a07f-4d15c8b27672)

### Operating system

Windows 11

### Installation Method

Winget (Windows)

### Version

1.14.1

### Steps to reproduce

Leave your pc running with Podman installed.

### Relevant log output

```shell
Other than the log that is in the UI output could not find the log location within 5 minutes.
```

**Comment by dgolovin** [comment]
This issue is related to watching changes in filesystem with chokidar v4 module, because ReaddirStream is part of it. It could be fixed in latest release because chokidar module was downgraded to previous release v3 with this PR https://github.com/podman-desktop/podman-desktop/pull/10150.

**Comment by pcartwright81** [comment]
Thanks for the detailed explanation. Most likely was because I have not seen it again.

**Comment by pcartwright81** [comment]
Was chokidar updated again?

Different, but similar error.

<img width="364" alt="Image" src="https://github.com/user-attachments/assets/f6429754-4252-4f77-b604-b2770eaf96d5" />

Podman Desktop 1.18

**Comment by benoitf** [comment]
we're still using the same chokidar
