### ISSUE TITLE
Docs: Running Podman and Podman Desktop without WSL2 

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1032]
### Is your feature request related to a problem? Please describe

In some situation, WSL2 is not an option for the virtualization stack.
We have an alternate solution where it is possible to use OpenShift Local (CRC) with the Podman Preset.

### Describe the solution you'd like

The goal would be to write a small documentation on how to use Podman Desktop with the Podman preset from OpenShift Local (CRC).

We should include information about:
- the virtualization stack
- requirements (system + permissions) to proceed the installation of OpenShift Local (CRC). Or link to OpenShift Local docs
- Guidance on how to start OpenShift Local from Podman Desktop

**Comment by themr0c** [comment]
ping

**Comment by themr0c** [comment]
When:

* Windows 10
* Not admin => can't use WSL

**Comment by themr0c** [comment]
Verify that CRC installs without WSL.

Look at new Podman feature, with VM based on qemu.

**Comment by themr0c** [comment]
* Use qemu in Windows to avoid WSL
* List OpenShift Local differences to inform the user choice: The Podman VM in OpenShift Local is based on a RHEL VM. Verify virtualization engine.

**Comment by themr0c** [comment]
On Windows, Podman requires running on a virtual machine.

You can choose the virtualization technology that suits your needs:

Choose your virtualization engine:

* WSL 2: 
  * Windows native virtualization with good performance, running as an HyperV virtual machine. https://learn.microsoft.com/en-us/windows/wsl/about#what-is-wsl-2
  Prerequisites
  * You have administrator privileges
  * You are not in a VPN
  * Windows 11
  Procedure
  * Use Podman Desktop default Podman installer.
* HyperV: 
	* Windows native virtualization, with full control on the virtual machine. 
	* Works with VPN.
	* Works without administrator privileges
	* Works with Windows 10
	Prerequisites
   * The user has to be a member of the Hyper-V Administrators group. This is needed to allow the user to add a VM, start or stop this VM and access the actual resources related to this VM.
	Procedure
	* Use Podman preset in OpenShift Local.
* qemu: 
   * Recent Podman feature. 
   * Avoid qemu for performance reason? 
   * Community only solution? 

Choose your Podman virtual machine operating system:

* RHEL: 
  Procedure
  * Use Podman preset in OpenShift Local
* Ubuntu
  * WSL 2 default
  Procedure
  * Use Podman Desktop default Podman installer.
* Fedora:
  * Use Podman Desktop?
* Choose your own on WSL 2?  
  * https://learn.microsoft.com/en-us/windows/wsl/install#change-the-default-linux-distribution-installed
 
cc: @gbraad
