### ISSUE TITLE
Docs: Add details about silent installation on windows

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1033]
### Is your feature request related to a problem? Please describe

Following the use case detailed in #950, it would be nice to have a mention on Installation guide for windows.

### Describe the solution you'd like

Add new chapter in this guide: https://podman-desktop.io/docs/Installation/windows-install

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/pull/974 ?

**Comment by slemeur** [comment]
Oh yes! thanks
