### ISSUE TITLE
Docs: Installation in an AirGapped Environment

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1034]
### Is your feature request related to a problem? Please describe

Following the work on #185 we would like to provide a dedicated guide for installation in an AirGapped Environment.

### Describe the solution you'd like

Guide in the installation section that explain how to manage installation of Podman Desktop in an AirGapped environment

- [x] on Linux https://github.com/containers/podman-desktop/pull/1118 https://podman-desktop.io/docs/Installation/linux-install#archive
- [x] on macOS https://github.com/containers/podman-desktop/pull/1493
- [x] on Windows https://github.com/containers/podman-desktop/pull/1422

**Comment by themr0c** [comment]
ping

**Comment by themr0c** [comment]
referencss:

* https://github.com/containers/podman-desktop/pull/1120
* https://github.com/containers/podman-desktop/issues/185

**Comment by themr0c** [comment]
Some questions, @benoitf, after looking at https://github.com/containers/podman-desktop/pull/1120

1. I understand we'll have airgap archives for major releases only. Therefore, I assume docs should not point to GitHub releases pages, but rather the downloads page. Is that correct?

2. I assume that after installing the Podman Desktop airgap archive, I have also a working Podman engine. No configuration / post-install step required?

3. To really start working, I assume I have to also either: 

   * Configure a container image registry accessible from the restricted environment
   * Import the container images required for my workload

**Comment by benoitf** [comment]
1. yes

2. yes and no. After the installation you still need to create the machine from Podman Desktop. But it won't try to fetch Fedora or Fedora CoreOS from internet, it'll use the embedded image so no internet connection will be required.

3. yes at some point if you want to pull images, you need a registry (or you do only scratch images) or you load images from the filesystem.

**Comment by themr0c** [comment]
The downloads page doesn't contain the executables / archives for restricted environment yet.

Can we plan to call them *Restricted environment installer*?

1. Download the *Restricted environment installer* for your platform from the Downloads page

**Comment by benoitf** [comment]
the download page doesn't contain the executables as there was no release since we added the production of the binaries.

about the name cc @slemeur

**Comment by themr0c** [comment]
1. Windows: run the portable executable, or run the installer, or both?
2. macOS: install the dmg (like regular install but with a different dmg, and only universal dmg is provided)?
3. Linux: like https://podman-desktop.io/docs/Installation/linux-install#archive

**Comment by benoitf** [comment]
1. for Windows I think we have two .exe
2. yes for mac there is only one archive the universal dmg installer (working on all arches)
3. for linux we're not promoting a 'podman machine/VM' on Linux so it's up to the user to have podman working.

**Comment by themr0c** [comment]
Too many steps are different for each platform, the "one procedure with tabs for operating systems" looks ugly. Abandoning that idea.
