### ISSUE TITLE
Docs: Using a different/custom WSL2 distribution

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1035]
### Is your feature request related to a problem? Please describe

In some context, certain users may want to use a different version than the fedora based image provided with Podman. It's possible to build its own podman-machine vm and use it for Qemu (on Mac) or WSL2 (windows). 

### Describe the solution you'd like

Provide How-to documentation on how one could be building his own image and configuring Podman Desktop so that it uses that image.

### Additional context

https://kenmoini.com/post/2022/05/podman-desktop-on-windows/#configuring-the-podman-desktop-wsl2-distribution

**Comment by faandg** [comment]
Looking forward to this one.
Hoping to learn a way to consolidate my 2 WSL Fedora VMs (1 for dev 1 for podman) if possible.

**Comment by raatti** [comment]
I would love to use my AlmaLinux 9 from Windows store to run podman, it's already installed there and would be fitting platform for Podman too.
