### ISSUE TITLE
docs: add guide on how to work if you used to have docker installed

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1036]
### Is your enhancement related to a problem? Please describe

People may have used docker in the past, but after installing Podman Desktop, they expect to have all the tools working or expect that some command lines work.

### Describe the solution you'd like

List all steps to ensure you can work with Podman but make it as if Docker was installed

- [x] https://github.com/containers/podman-desktop/pull/1088
- [x] https://github.com/containers/podman-desktop/pull/1135
- [x] https://github.com/containers/podman-desktop/pull/1143
- [x] https://github.com/containers/podman-desktop/pull/1144
- [x] https://github.com/containers/podman-desktop/pull/1146
- [x] https://github.com/containers/podman-desktop/pull/1152
- [x] https://github.com/containers/podman-desktop/pull/1162

**Comment by themr0c** [comment]
ping

**Comment by themr0c** [comment]
Anything missing in the list (undefined etc)?

**Comment by benoitf** [comment]
maybe something to verify the setup.

For example I'm on a laptop, I install Podman. What should I do to be sure that Podman will be used for all the tooling using Docker.

For example, should I do a curl command on /var/run/docker.sock and if it works it means it's working

on should i use `CONTAINER_HOST=/var/run/docker.sock podman ps` and see if it works
And if I don't have the file, what should I check


etc.
