### ISSUE TITLE
Nit: tabs don't maintain selection state

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1037]
### Bug description

If I click on the details for a Container and select the tabs (e.g. Logs, Inspect, Kube) then the tab stays selected even when I click within the lower window.

If I switch to Pods or Images and go to any tab other than Summary, the tab focus (purple underline) is lost whenever I click on the window below.

https://user-images.githubusercontent.com/19958075/207667652-e836bf71-5dc3-451c-8442-8dad62f418ae.mov

### Operating system

macOS 13.0.1

### Version

0.10.0

### Steps to reproduce

See video above.

**Comment by benoitf** [comment]
Looks like an easy fix
