### ISSUE TITLE
Doc:  "Remote access" start socket with --user parameter

### ISSUE THREAD

**Issue by Salzorian** [containers/podman-desktop#10465]
Please add/change start parameter for podman.socket (section Remote access)
-->
systemctl status --user podman.socket 

Otherwise Podman Desktop is showing: 
"socket hang up"

On Server side i got following error:
"error: connect to /run/user/1000/podman/podman.sock port -2 failed: No such file or directory"

thx

regards
Matthias

**Comment by slemeur** [comment]
Thank you for reporting the issue.
