### ISSUE TITLE
Port Mapping Fields are not shown in the create container from image panel

### ISSUE THREAD

**Issue by harryssuperman** [containers/podman-desktop#1046]
### Bug description

If i pull an image without Port Mapping with explicit Expose Port number like rancher/hello-world. It is an standard image with port number 80.

I cann't create a container with a mapping port number like 8080 because the fields are not shown in the panel.

### Operating system

Windows 10 21h2 19044 Intel 64

### Version

0.10.0

### Steps to reproduce

1. podman pull rancher/hello-world in console or with podman desktop
2. try to create a container from this image
3. In the Basic Menu from Create container from Image Panel ist not show the Port mapping Labels und Field and Port Forward ist not possible.

### Relevant log output

```shell
All Logs are good
```

### Additional context

Same Image when it is with the podman CLI und with parameter -p 8080:80 could be with localhost:8080 in a browser called und show the info from the Hello World Image from Rancher

**Comment by benoitf** [comment]
yes I agree that even without correct metadata we should be able to add port mapping 👍

**Comment by harryssuperman** [comment]
first temporary solution was to build a second image with a Dockerfile like this:

FROM ##Repository##/rancher/hello-world
EXPOSE 80

After that i am getting the field in the panel just to get the mapping.

![image](https://user-images.githubusercontent.com/6017066/207987258-a18d4e0e-b4de-4ba6-a918-453acacd348f.png)

and container is just working fine:

![image](https://user-images.githubusercontent.com/6017066/207987433-d85bf42a-7f60-4419-b18a-58002e6ca4c5.png)

**Comment by harryssuperman** [comment]
Thanks folks, i appreciate really your effort working in the issue at #1265 . It was not so easy to implement a wonderfull solution.

Thank you @lstocchi for the great work in my opinion and also thanks @benoitf accepting this issue.

It will be ready in 0.12.0 right?

**Comment by benoitf** [comment]
yes it'll be in 0.12.0 and it's also available in pre-releases https://github.com/containers/podman-desktop/releases

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/1265
