### ISSUE TITLE
[Window 10] Podman Desktop's images/containers cannot be shown in Podman command line.

### ISSUE THREAD

**Issue by gbgbapsps2** [containers/podman-desktop#1048]
### Bug description

I use the Podman Desktop to pull images busybox and start its container as depicted below.
![image](https://user-images.githubusercontent.com/100194896/208009353-a1d3ec9a-dbdc-4293-92ee-1c5486b3b894.png)

![image](https://user-images.githubusercontent.com/100194896/208009427-df34f10e-b3ee-4975-8ce4-cde8c81cd2cf.png)

But unfortunately, when I try to use podman to check the images and containers. I cannot see them.
![image](https://user-images.githubusercontent.com/100194896/208009828-db1aa75c-0491-4a51-ae05-845818953a6f.png)

### Operating system

Windows 10.0.19045 build 19045

### Version

0.10.0

**Comment by gbgbapsps2** [comment]
Problem is fixed. The podman machine-default is created via podman commands. So it causes the issue.
Now I just use podman desktop to create and init the machine-default. 
Both podman command and podman desktop could see the images.

**Comment by gbgbapsps2** [comment]
![image](https://user-images.githubusercontent.com/100194896/208036158-b8286578-7384-4416-8295-1cb8c5aa04ca.png)

**Comment by harryssuperman** [comment]
@gbgbapsps2 could you close the issue please?
