### ISSUE TITLE
Podman Desktop allocates console window when started from terminal.

### ISSUE THREAD

**Issue by arixmkii** [containers/podman-desktop#1050]
### Bug description

If there is a need to start Podman Desktop from terminal (for example to pass additional environment variables, so, that podman desktop will use them to call podman CLI) the application starts terminal console in addition to main window.

### Operating system

Windows 11

### Version

0.10.0

### Steps to reproduce

Install Podman Desktop on windows (from official installer). Then run from terminal.
```
set PATH=%LOCALAPPDATA%\Programs\podman-desktop;%PATH%
start cmd /C "Podman Desktop"
```

`start cmd /C` part is needed to detach this console from the calling terminal session - otherwise the input on the terminal will be just blocked by Podman Desktop console output.

**Comment by lstocchi** [comment]
Hi @arixmkii, could you confirm that by setting the env variable ELECTRON_NO_ATTACH_CONSOLE to true before starting podman desktop your issue disappear?
I'm just trying to figure out a possible solution

**Comment by arixmkii** [comment]
@lstocchi I can confirm that this fixes the issue and that there is no more diagnostic output in the console. I was able to close the terminal w/o terminating app.
