### ISSUE TITLE
Podman Desktop WSL2 image does not appear to have internet connectivity (unlike Docker Desktop's WSL2 image connectivity which is fine)

### ISSUE THREAD

**Issue by cegeka-jd** [containers/podman-desktop#1051]
### Bug description

podman pull docker.io/hello-world
Trying to pull docker.io/hello-world...
Error: initializing source docker://docker.io/hello-world: pinging container registry docker.io: Get "[https://docker.io/v2/":](https://docker.io/v2/%22:) dial tcp: lookup docker.io: Temporary failure in name resolution

### Operating system

Windows 11

### Version

0.10.0

### Steps to reproduce

podman pull docker.io/hello-world

### Relevant log output

```shell
Trying to pull docker.io/hello-world...
Error: initializing source docker://docker.io/hello-world: pinging container registry docker.io: Get "[https://docker.io/v2/":](https://docker.io/v2/%22:) dial tcp: lookup docker.io: Temporary failure in name resolution
```

### Additional context

docker pull docker.io/hello-world
Using default tag: latest
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:c77be1d3a47d0caf71a82dd893ee61ce01f32fc758031a6ec4cf1389248bb833
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

**Comment by benoitf** [comment]
hello @cegeka-jd are you behind a corporate proxy ?

**Comment by cegeka-jd** [comment]
Hi Benoit, We are, but we are not blocking any of the traffic needed for Podman. Also Docker Desktop can pull any image without issues.

We have pinpointed the issue to any WSL2 images like "podman-machine-default" not having connectivity on our Windows 11 workstations and we are not alone (see https://stackoverflow.com/questions/62314789/no-internet-connection-on-wsl-ubuntu-windows-subsystem-for-linux).

However it does seem possible as Docker Desktop's docker-desktop WSL2 image does not suffer from this issue.

Due to security our workstations are somewhat limited as to what we can do as local admin, and we cannot debug or manipulate anything inside your WSL2 image.

However we see the same issue on a standard Ubuntu image and when we switch to WSL1 connectivity is restored. We have tried switching the podman-machine-default but Podman Desktop won't run like this.

fyi:

wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.

ping google.com
ping: google.com: Temporary failure in name resolution

wsl --set-version Ubuntu 1
Conversion in progress, this may take a few minutes...
Conversion complete.

ping google.com
PING google.com (142.250.179.206) 56(84) bytes of data.
64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=112 time=42.9 ms

wsl -l -v
  NAME                      STATE           VERSION
* docker-desktop-data       Running         2
  Ubuntu                    Running         1
  podman-machine-default    Running         2
  docker-desktop            Running         2

**Comment by benoitf** [comment]
I would say it's related to the usage of https://github.com/sakai135/wsl-vpnkit

**Comment by benoitf** [comment]
@cegeka-jd  if you can try to setup wsl-vpnkit 
"This requires no settings changes or admin privileges on the Windows host."

**Comment by cegeka-jd** [comment]
I'm still checking if this is allowed here, currently I'm hearing: "not recommended"

**Comment by faandg** [comment]
You shouldn't really need wsl-vpnkit in most cases.
It is usually sufficient to get the corporate DNS server in the wsl machine's `/etc/resolv.conf` as described [here](https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2). 

If you additionally need to set a proxy server you can set global environment variables `http_proxy` and `https_proxy`, like any linux.

You would need to enter the podman-machine though.
`wsl -d podman-machine-default` doesn't let you enter from powershell?
In theory you could also `--export` podman-machine-default, edit the files and then `--import` the instance, but I haven't tested this with the podman-machine.

**Comment by cegeka-jd** [comment]
Now the "Temporary failure in name resolution" error still happens, but immediately, no delay anymore (before applying the workaround suggested above it took several seconds more):

podman pull docker.io/hello-world
Trying to pull docker.io/library/hello-world:latest...
Error: initializing source docker://hello-world:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

Even though generateResolvConf is set to false in wsl.conf, when I restart podman-machine-default resolv.conf still gets overwritten by the following link, which now points to a non-existent file:

resolv.conf -> ../run/systemd/resolve/stub-resolv.conf

fyi:

cat /etc/wsl.conf
[network]
generateResolvConf=false
[user]
default=user

**Comment by faandg** [comment]
After setting /etc/wsl.conf and removing the link /etc/resolv.conf it's not being overwritten or linked anymore for me.
You could try setting `chattr +i` on the file to make it immutable, I've seen some people do that to make sure it doesn't get overwritten.

I'm running into a different issue though, I can now `wsl -d podman-machine-default` and pull images in podman-machine
![image](https://user-images.githubusercontent.com/5772741/216957749-288e8852-4282-412b-bd6f-a79ebd65df90.png)

But for some reason the socket stops working after I do this.

> Docker Socket Compatibility: Podman is not emulating the default Docker socket path: //./pipe/docker_engine. Docker-specific tools may not work.

![image](https://user-images.githubusercontent.com/5772741/216956558-5d4d7a53-79de-4258-8fdf-ef0927b6b643.png)

Despite that, everything else seems to work. This one still has me a bit puzzled.
Tried restarting the podman-machine through both wsl cli and podman desktop but makes no difference.

@benoitf any clue?

**Comment by faandg** [comment]
You know what, I'll make a separate issue for this because I noticed my environment does not match @cegeka-jd 's (I'm on Windows 10 and podman desktop 0.0.11) and we're no longer stuck on the same point.

**Comment by byjrack** [comment]
Just wondering is there a plan to offer a built in bootstrap in the podman-machine-default distro for vpnkit/gvisor that folks can elect where their VPN provider is causing issues with layer3 on the elected WSL2 subnet?

**Comment by eidottermihi** [comment]
I no longer have this issue when I'm using `user-mode-networking` in the podman machine (introduced by podman 4.6.0).

Just initialize the machine using: `podman machine init --user-mode-networking`

**Comment by benoitf** [comment]
thanks @eidottermihi for commenting, yes for Windows users, VPN/custom dns, etc. 'user mode network' option will help them.

**Comment by faandg** [comment]
This does seem to bring me a step closer. 
Unfortunately starting the podman machine never gets the socket right, everything else seems to work though.

> API forwarding for Docker API clients is not available due to the following startup failures.
>         CreateFile \\.\pipe\docker_engine: All pipe instances are busy.
> 
> Podman clients are still able to connect.
> Machine "podman-machine-default" started successfully

I've checked out https://github.com/containers/podman/issues/15176 but none of these solutions work for me.
If I had to guess it's because we have what they call an [Always On VPN](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/overview-always-on-vpn) so it's near impossible to start podman _after_ network connectivity has been established but _before_ the VPN does.

**Comment by cegeka-jd** [comment]
Same here, I no longer have this issue when I'm using user-mode-networking. Everything seems to work despite the message saying: "Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work."

**Comment by slemeur** [comment]
cc @themr0c

**Comment by themr0c** [comment]
Does the docs and kb in #3577 address the case accurately?

**Comment by byjrack** [comment]
I need to test a bit, but the hardcode to internet DNS might help with the "after network, before VPN" crowd but once VPN is up name resolution would be broken for us since we don't route to those destinations from the internet.  I know this issue has covered a lot of ground, but what specifically which scenario the hardcoded internet DNS supposed to resolve?

**Comment by themr0c** [comment]
Do we need more than the docs that has been added? cc @benoitf @cdrage

**Comment by themr0c** [comment]
Closing as having this in the docs is what we want https://podman-desktop.io/docs/proxy/using-a-vpn-on-windows

**Comment by kid1412621** [comment]
The version 1.6.3(desktop) + 4.8.2(podman) seems to have happened again even I enabled user mode networking. must do as https://github.com/containers/podman/issues/15176#issuecomment-1442950963 to temporally resolve the issue.

> I no longer have this issue when I'm using `user-mode-networking` in the podman machine (introduced by podman 4.6.0).
> 
> Just initialize the machine using: `podman machine init --user-mode-networking`
