### ISSUE TITLE
bwrap: execvp ldconfig: Exec format error / ARM64

### ISSUE THREAD

**Issue by ymurawski** [containers/podman-desktop#1069]
### Bug description

tried to install Podman Desktop with Flatpak / it installs but with error bwrap: execvp ldconfig: Exec format error, exit status 256
It wont start the app

### Operating system

Ubuntu 22.04 ARM

### Version

0.10.0

**Comment by benoitf** [comment]
Hello, Flatpak binary is for x64
There was no demand, yet, for arm support on Linux

**Comment by ymurawski** [comment]
> Hello, Flatpak binary is for x64
> There was no demand, yet, for arm support on Linux

Ahhh OK thanks...is it in planing? 🙈

**Comment by benoitf** [comment]
@ymurawski we can try to enable it on flathub

https://github.com/flathub/io.podman_desktop.PodmanDesktop/blob/master/flathub.json

**Comment by ymurawski** [comment]
> @ymurawski we can try to enable it on flathub
> 
> https://github.com/flathub/io.podman_desktop.PodmanDesktop/blob/master/flathub.json

Would be awesome to give it a try 😅

**Comment by benoitf** [comment]
@ymurawski if you could try https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/11

(if you look at the comments there is test repository)
