### ISSUE TITLE
Ports should not auto-fill when doing container creation

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1072]
### Is your enhancement related to a problem? Please describe

When you create a container, it should not auto-fill the number and instead show as a "suggestion".

It's deceiving as it create the port for you already when sometimes you don't want to (for example, when creating a Pod from multiple containers, you may not want ports exposed)

![Screenshot 2022-12-20 at 4 34 10 PM](https://user-images.githubusercontent.com/6422176/208771713-8154e8a3-f278-4610-903a-4a83bdd31c8c.png)

### Describe the solution you'd like

Suggestion the port, not autofilling.

**Comment by benoitf** [comment]
It may overlap with https://github.com/containers/podman-desktop/issues/1017
As it seems your primary use case is for pods from containers

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.
