### ISSUE TITLE
Docs: Add more documentation on kind/lima/docker/podman, etc. support on site

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1081]
### Is your enhancement related to a problem? Please describe

We have no documentation indicating Kind (or any other "hidden" provider such as Lima..) on the site, other than a very small entry on the front page listing container engines.

We need to have a document that lists all the supported container engines as well as the capabilities of each of them (for example, we provide Podman docker socket compatibility support, we provide Kind support, we also provide being able to start/stop Lima VM's).

This can either be a matrix or table listing all the providers.

At the moment it's all "hidden" away and only enables if Podman Desktop detects the binary.

### Describe the solution you'd like

More documentation on site on each container engine / more elaborate explanation of what's happening

**Comment by afbjorklund** [comment]
The lima integration seems to be broken at the moment, it requires a custom "podman-lima" instance.

```
brew install lima
limactl start --name podman-lima template://podman
```

The default name is "podman", but for some reason it was removed in a previous commit d1b922ccbb90c0ea3394fa4e4e73770409ea2217

```ts
  const socketPath = path.resolve(os.homedir(), '.lima/podman-lima/sock/podman.sock');
  const socketAlternativePath = path.resolve(os.homedir(), '.lima/podman-lima/sock/podman.sock');

```

Bug report:
* #2547

It is also always disabled, so it doesn't show up in the list of container engines (no containers/images/volumes). Also described why, in the bug report above.

**Comment by afbjorklund** [comment]
* #2547

**Comment by afbjorklund** [comment]
To start a rootless Lima instance:

`limactl start template://podman` (or use `--name=podman`, and select it from the menu that appears)

```
? Creating an instance "podman"  [Use arrows to move, type to filter]
> Proceed with the current configuration
  Open an editor to review or modify the current configuration
  Choose another example (docker, podman, archlinux, fedora, ...)
  Exit
```

To start a rootful Lima instance:

Select the "rootful" variant of the template, like `podman-rootful` (or `docker-rootful`), to run as root.

```
limactl start --name podman template://podman-rootful
```

**Comment by cdrage** [comment]
I feel like this issue I created is way too generic so I'm going to close this for now as there has been more documentation added to lima / docker / podman on the website OR there has already been smaller issues opened regarding them.
