### ISSUE TITLE
Image/tag name in Images tab is being split incorrectly 

### ISSUE THREAD

**Issue by JoelDSmith** [containers/podman-desktop#1082]
### Bug description

My images are stored on a private GitLab repository, which is using a non-standard port number; as a result, the repository name has a colon (`:`) in it.

```
example.cqu.edu.au:1234
```

However, in the Images tab in Podman Desktop, it appears as though the image/tag names are simply being split on by colon, with the second-from-beginning segment being assumed to be the tag, which is not always true. Because of this, I cannot actually see what my images' tags are.

![image](https://user-images.githubusercontent.com/24516015/209066736-081d0dda-1bbc-46f5-9e81-8443109b4c57.png)

(The tags for each image above should be `main-latest`, `8.2-base-latest`, and `8.2-builder-latest`, respectively.)

If I understand how image tagging works correctly, then it would be better to treat the final segment as the tag, and everything else as the combined repository/image name.

### Operating system

Windows 11 22H2

### Version

0.10.0

### Additional context

As an aside, I couldn't actually see where my Podman Desktop version was from within the app; had to find the exe on disk and use the file details.

**Comment by benoitf** [comment]
should be fixed by https://github.com/containers/podman-desktop/pull/1127

**Comment by JoelDSmith** [comment]
Can confirm that this is fixed in Podman Desktop 0.11.0.
