### ISSUE TITLE
Changes to the CRC name

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#109]
Soon we will deprecate the name CodeReady Containers. For the provider/tool we will call this CRC, without a direct meaning for upstream. Although 'CRC Runs Containers' is used as a recursive 'joke'.

The method and preset for OpenShift will be called OpenShift Locsl which will be the name of the downstream offering.

Changes will be made during this sprint of CRC. We will follow-up afterwards for podman desktop.

Note: placeholder for tracking purposes

**Comment by rhatdan** [comment]
Why not call it OKD local?

**Comment by gbraad** [comment]
> OKD local

Offtopic maybe, but this would, like the downstream name, only fit a small part of what the tool does.

**Comment by rhatdan** [comment]
Ok, but what I would really like it to say is `Kubernetes Local`, since this is what users will be looking for.

**Comment by gbraad** [comment]
This issue is not about the functionality but how the providers mentions a 'product'/tool that will be renamed. CodeReady shouldn't be shown in the UI.
________________________________

**Comment by deboer-tim** [comment]
The name change happened, poking this to remind it's time to do the corresponding change.

**Comment by doehyunbaek** [comment]
Is the job just to change reference of 'Codeready Containers' to 'CRC Containers'? Then it seems to be very trivial and I'll do it quickly, or is the name to be changes undecied yet?

A quick search of codeready revealed two occurences and I found two in the UI as well.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/70570804/172760679-56a582bf-4031-489b-86fe-f7b09c90415b.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/70570804/172760707-d962adf0-5d0d-43a5-8975-72f7190f5f12.png">

**Comment by gbraad** [comment]
Just CRC, not CRC Containers
________________________________

**Comment by doehyunbaek** [comment]
I'll post a pr chaning reference of 'Codeready Containers' to 'CRC'.

**Comment by benoitf** [comment]
thanks @doehyunbaek

**Comment by rhatdan** [comment]
I thought we were changing the name to OpenShift local?

**Comment by gbraad** [comment]
OpenShift Local is a product name. Crc is the generic tool
________________________________

**Comment by gbraad** [comment]
Fixed. Thanks for your contribution. :-D
