### ISSUE TITLE
Always in initializing when start to use this App

### ISSUE THREAD

**Issue by Liaomessi** [containers/podman-desktop#1093]
### Bug description

When I install the app, click to open it, it just stays like this, no progress.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42334988/209745771-be0a992f-3576-4de5-a7c0-f5661527e36a.png">
Here is my device info 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/42334988/209745889-3adcb200-c870-4aa1-a34b-64d8566c2df0.png">

### Operating system

macOS Montery 12.6.1 (21G217)

### Version

0.10.0

### Steps to reproduce

Actually, I don't know if anyone else has the same problem as me. But for me it's still the same after uninstalling and reinstalling.

### Relevant log output

```shell
I click 'Toggle Developer Tools' and what its console print is like the additional context displayed.
```

### Additional context

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42334988/209746129-01018250-4203-49ec-a067-b1e1bcc28a72.png">

**Comment by Liaomessi** [comment]
Hope you guys can fix it or guide me how to fix it.

**Comment by benoitf** [comment]
Hello @Liaomessi it looks like https://github.com/containers/podman-desktop/issues/951

You may try with a pre-release or check the kubeconfig file

**Comment by V01D-PH03N1X** [comment]
Same issue at Windows.  Podman Version 0.11.0

**Comment by benoitf** [comment]
@DarkModz-Official could you provide the logs that you have within the console of View/Toggle Developer Tools and then Console tab of the Developer Tool

**Comment by V01D-PH03N1X** [comment]
@benoitf Sorry i could not open the Developer Tools.
