### ISSUE TITLE
Font size/scaling on container view

### ISSUE THREAD

**Issue by faandg** [containers/podman-desktop#1094]
### Is your enhancement related to a problem? Please describe

For every tab under the _Container_ view (_Logs, Inspect, Kube, Terminal, Details_), the font is a bit too tiny for my weary eyes 👀

![image](https://user-images.githubusercontent.com/5772741/210006548-4d89d1a9-ee82-4054-9cfa-aa8e324cdbcc.png)

### Describe the solution you'd like

Perhaps the base scale could be increased?
Could also just be me.

### Describe alternatives you've considered

- It does work with dpi scaling but I'd rather not enlarge everything.

- Getting a new pair of glasses.

### Additional context

I'm testing on Windows with 1440p.

**Comment by benoitf** [comment]
hello @faandg, you can increase some of the font size in the preferences of the application

**Comment by faandg** [comment]
hi @benoitf, you're right I missed that.
It increases the size of _logs_ and _terminal_ so it's already very helpful.

_inspect_ and _kube_ font sizes are still small, any way to increase them?

**Comment by benoitf** [comment]
@faandg not yet but it can be a future enhancement
