### ISSUE TITLE
Toolbox Support

### ISSUE THREAD

**Issue by ItsJamie9494** [containers/podman-desktop#110]
### Is your feature request related to a problem? Please describe

This is not related to a problem, but is a feature I think would suit this project nicely

### Describe the solution you'd like

I think Podman Desktop should have better support for Toolboxes (https://github.com/containers/toolbox). By this I mean I would like the terminal to load to the current user, instead of root, as well as the ability to create toolboxes. A graphical front-end for toolbox, if you will.

**Comment by benoitf** [comment]
probably it could be achieved by a toolbox plug-in.

**Comment by ItsJamie9494** [comment]
I'm not sure whether it would need to be a toolbox plugin or a feature in podman-desktop, but since I want the feature in podman-desktop I opened the issue here

**Comment by benoitf** [comment]
closing as won't fix. If some people are interested, a 3rd party extension could be provided
