### ISSUE TITLE
RPM package for Fedora and EPEL

### ISSUE THREAD

**Issue by Conan-Kudo** [containers/podman-desktop#112]
### Is your feature request related to a problem? Please describe

I'd like to be able to install Podman Desktop through DNF on Fedora or RHEL/CentOS, which also opens doors to being able to bundle/ship Podman Desktop in a container-focused spin or third-party remixes.

### Describe the solution you'd like

This requires the Podman Desktop software to be packaged as an RPM and reviewed for inclusion in Fedora and EPEL.

### Additional context

As this is Electron-based, Fedora needs to package and ship an Electron runtime. Fortunately, @cryptomilk [has gone through the effort of figuring that out and merely needs co-maintainers before he submits it for review](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/Q4ZYYBTEP2ODUI6KV77JUOB4QZG2BTPD/). @thunderbirdtr noted on Twitter he'd help here, but more folks would be welcome. 😄 

This ticket was suggested by @gbraad on Twitter to ensure we have this on the roadmap and prioritized properly.

**Comment by benoitf** [comment]
electron builder can provide RPM out of the box so we could enable this option but I'm not sure if it's the RPM you would expect ?

https://www.electron.build/configuration/linux

We could provide AppImage or Snap as well

**Comment by onuralpszr** [comment]
> electron builder can provide RPM out of the box so we could enable this option but I'm not sure if it's the RPM you would expect ?
> 

We would like to able install via "dnf" from Fedora repository. That's the RPM we looking for.

**Comment by rhatdan** [comment]
We will be packaging it for Fedora, but right now, it is being updated on a daily basis.
I would figure when it is declared 1.0.

**Comment by gbraad** [comment]
Packages can be generated from our builds if needed
... Or package as flatpak? @benoitf WDYT?

**Comment by benoitf** [comment]
For sure flatpak or Snap packages can be added. It seems lot of people are interested by the GUI on Linux as well.

**Comment by rhatdan** [comment]
I want a standard RPM, so users can just do.

dnf -y install podman-desktop

And end up with Podman-desktop and podman installed on their box.

**Comment by gotmax23** [comment]
@rhatdan:

> I want a standard RPM, so users can just do.
> 
> dnf -y install podman-desktop

That would be great.

@benoitf:

> electron builder can provide RPM out of the box so we could enable this option but I'm not sure if it's the RPM you would expect ?
> 
> https://www.electron.build/configuration/linux

You can use Electron Builder to build a binary RPM, but not to ship it in the Fedora repositories. RPMs built like this are in no way compatible with Fedora's packaging guidelines or build system.

**Comment by cryptomilk** [comment]
I've packaged nodejs-electron and other dependencies to build electron apps in the openSUSE Build Service for Fedora:

https://build.opensuse.org/package/show/devel:languages:nodejs/nodejs-electron
https://build.opensuse.org/package/show/devel:languages:nodejs/app-builder

Here is an example how to build an electron app:
https://build.opensuse.org/package/show/network:im:signal/signal-desktop

**Comment by benoitf** [comment]
@cryptomilk are you interested in contributing RPM for Podman Desktop ?

**Comment by cryptomilk** [comment]
I don't have the time for it. But the work for electron is already done. A fedora maintainer is needed ...

**Comment by rhatdan** [comment]
@jnovy @lsm5 PTAL

**Comment by lsm5** [comment]
@rhatdan do we have anyone in the podman-desktop team that would like to become fedora maintainers? I can work with them, but I'd rather not be the point person for this.

**Comment by gotmax23** [comment]
Just to be clear, nodejs-electron isn't packaged in Fedora, either. Perhaps you can reach out on the Fedora `devel` mailing list to see if anyone is interested in helping out with that.

**Comment by lsm5** [comment]
> Just to be clear, nodejs-electron isn't packaged in Fedora, either. Perhaps you can reach out on the Fedora `devel` mailing list to see if anyone is interested in helping out with that.

so nodejs seems to be cool with bundling afaict. https://docs.fedoraproject.org/en-US/packaging-guidelines/Node.js/ . Can't electron be bundled into podman-desktop or does it need to live in a separate package?

**Comment by Conan-Kudo** [comment]
Electron needs to be built as a shared dependency because it's a nodejs runtime platform extension. It's not pure JavaScript. The _rest_ of Podman Desktop's dependencies can and should be bundled, but we definitely don't want to do that for Electron.

**Comment by lsm5** [comment]
> Electron needs to be built as a shared dependency because it's a nodejs runtime platform extension. It's not pure JavaScript. The _rest_ of Podman Desktop's dependencies can and should be bundled, but we definitely don't want to do that for Electron.

ack, makes sense. Thanks @Conan-Kudo

**Comment by lsm5** [comment]
I see another response on a [different thread](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/BO2RYQSWMJ26GKCUU46H5QNYCY72H2FI/) that electron depends on fetching prebuilt blobs at build time.

@rhatdan If that's still the case, we might be better off with a copr or continuing with obs, unless someone is really willing to invest time into this.

**Comment by Conan-Kudo** [comment]
Electron can be built entirely from source, as @cryptomilk has done.

**Comment by cryptomilk** [comment]
We build electron completely from source for Fedora:

https://build.opensuse.org/package/show/devel:languages:nodejs/nodejs-electron

The OBS build runners don't have any network connectivity!

**Comment by jhoblitt** [comment]
+1 for flatpak

**Comment by jhoblitt** [comment]
It seems that flatpak already exists: https://podman-desktop.io/docs/Installation/linux-install

**Comment by benoitf** [comment]
yes it exists https://flathub.org/apps/details/io.podman_desktop.PodmanDesktop

**Comment by jhoblitt** [comment]
Confirmed the flatpak as working on F36.
![Screenshot from 2022-10-25 10-27-24](https://user-images.githubusercontent.com/948901/197841870-203f9ea6-fc4f-432e-aee2-c2a452a2ed34.png)

**Comment by lsm5** [comment]
not an official package but I got a copr setup in case anyone wants to try: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-desktop/

**Comment by shivdhar** [comment]
I'm interested in being able to `dnf install podman-desktop` as well; it was rather surprising to see it hasn't landed yet. What are the steps I can can help out with to make this happen?

**Comment by tjanez** [comment]
Has there been any progress on packaging Podman Desktop in Fedora (as an RPM)?

A quick search uncovered two active COPR repos:
- https://copr.fedorainfracloud.org/coprs/curtisy/podman-desktop/
- https://copr.fedorainfracloud.org/coprs/sentry/podman-desktop/

Any thoughts?

**Comment by benoitf** [comment]
Hello, for Linux distributions the main distribution channel is with flatpak and flathub https://flathub.org/en/apps/io.podman_desktop.PodmanDesktop

for RPMs there is a RPM for RHEL https://podman-desktop.io/docs/installation/linux-install/install-on-rhel10

**Comment by cryptomilk** [comment]
As I mentioned before, the starting point is to package nodejs-electron for Fedora.

https://src.opensuse.org/nodejs/nodejs-electron is the git tree for the package which is building for opensuse **and** fedora.

**Comment by tjanez** [comment]
> Hello, for Linux distributions the main distribution channel is with flatpak and flathub https://flathub.org/en/apps/io.podman_desktop.PodmanDesktop

I can imagine, but there are still big security and integrity benefits to building and installing packages through RPM rather that solely rely on Flatpaks.

> for RPMs there is a RPM for RHEL https://podman-desktop.io/docs/installation/linux-install/install-on-rhel10

Are the SPEC files for this public? Could this be reused for Fedora?

**Comment by benoitf** [comment]
> Are the SPEC files for this public? Could this be reused for Fedora?

as it's in the extension channel, it's only wrapping the existing binary into an RPM (so not built from sources)

**Comment by tjanez** [comment]
> > Are the SPEC files for this public? Could this be reused for Fedora?
> 
> as it's in the extension channel, it's only wrapping the existing binary into an RPM (so not built from sources)

Ok, got it. So the path towards a compiled from source Fedora RPM package would be:
1. Package [nodejs-electron](https://src.opensuse.org/nodejs/nodejs-electron) that @cryptomilk created in Fedora.
2. Create a Podman Desktop RPM package that relies on nodejs-electron.

**Comment by cryptomilk** [comment]
Yes, exactly. [element-desktop](https://src.opensuse.org/nodejs/) is an example which uses nodejs-electron or [signal-desktop](https://build.opensuse.org/package/show/network:im:signal/signal-desktop).

**Comment by tjanez** [comment]
> Yes, exactly. [element-desktop](https://src.opensuse.org/nodejs/) is an example which uses nodejs-electron or [signal-desktop](https://build.opensuse.org/package/show/network:im:signal/signal-desktop).

Thanks for the pointers to concrete examples!

BTW, is the correct element-desktop link to https://src.opensuse.org/nodejs/element-desktop?

**Comment by cryptomilk** [comment]
Yep.

**Comment by curtisy1** [comment]
Hey, maintainer of one of the active coprs for podman-desktop here!
Just wanted to chime in and say that I'm also currently relying on nodejs-electron in my copr which is gladly provided and built in copr by Sergio (who I believe was once part of the NodeJS SIG?) [here](https://copr.fedorainfracloud.org/coprs/sergiomb/electrons/package/nodejs-electron/)

My spec files are hosted on [Codeberg](https://codeberg.org/curtisy/podman-desktop-rpm), so feel free to reuse them or make them align more with Fedora's packaging standards (this was hacked together at 3am on a weekend as my first ever spec file, so they're definitely far from perfect but they do their job).
I'd also be more than happy to submit them for review whenever nodejs-electron is ready, however the last [Bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2128011) I found in regards to that didn't see any activity for 2+ years. Not sure if that's still the status quo or something changed in the meantime
