### ISSUE TITLE
Podman Desktop should read connection info from machine first (Mac, Windows hosts)

### ISSUE THREAD

**Issue by arixmkii** [containers/podman-desktop#1128]
### Is your enhancement related to a problem? Please describe

Sometimes there is a need to have customized build of podman machine (like this experiment of QEMU support on Windows https://github.com/containers/podman/issues/13006), in this case socket where API is exposed could differ (for example no to clash with production version). A more detailed example would be that QEMU version of podman machine doesn't need to use named pipes and could use unix domain sockets.

### Describe the solution you'd like

Instead of immediately guessing the socket path in this place https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/extension.ts#L116, podman-desktop should first try to read it from CLI using `podman machine inspect --format {{.ConnectionInfo.PodmanSocket.Path}}` Currently this API would respond with empty value for WSL, but there is an issue registered to address this https://github.com/containers/podman/issues/16860

### Describe alternatives you've considered

Using netcat/nmap/nc/socat/gocat or any other possible relay to forward socket to the one, which podman-desktop could understand, but this is a workaround and can't be used to run multiple instances of the machine simultaneously.

### Additional context

Tested this only for Podman machine on Windows and Mac. And from code it is not clear if Linux Podman machine is a supported scenario for Podman Desktop.

**Comment by benoitf** [comment]
maybe allow to register a socket path manually ?

**Comment by arixmkii** [comment]
> maybe allow to register a socket path manually ?

Manual setting override with fallback to previous logic also solves this issue. 👍

**Comment by pears-one** [comment]
I have recently noticed an issue similar to this. When creating the socket for a podman VM on MacOS, the default path for that socket will be `/Users/<user-name>/.local/share/containers/podman/machine/<machine-name>/podman.sock` . However, if this path is [too long](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars), the socket will [get created](https://github.com/containers/podman/blob/main/pkg/machine/config.go#L311) at `/User/<user-name>/.podman/podman.sock`. 

So there should at least be some check on the socket path length, falling back to `~/.podman/podman.sock` when the generated path is longer than 104 chars.

**Comment by benoitf** [comment]
thanks @evanfpearson 👍

**Comment by arixmkii** [comment]
@cdrage I disagree with closing this issue. I started it specifying more generic issue with Windows hosts, but now this issue is closed because of an implemented workaround for specific case with macOS

It is not even close to the proposed solution by @benoitf https://github.com/containers/podman-desktop/issues/1128#issuecomment-1373451163

If this issue is now designated to this specific macOS scenario https://github.com/containers/podman-desktop/issues/1128#issuecomment-1373913133, then I could recreate it being more specific.

Edited: original message sounded a bit offensive. It was not meant to be so. I'm sorry.

**Comment by pears-one** [comment]
Hey, I can confirm that this merge only fixes the MacOS scenario mentioned in my comment. For a more complete solution you'd need to make a call to `podman machine inspect` within the code.
