### ISSUE TITLE
Provide deb packages

### ISSUE THREAD

**Issue by Drugoy** [containers/podman-desktop#1132]
For Linux users this project is currently available only in 2 forms:
- archive with a binary (and stuff)
- flatpak package

It would be nice to have deb packages as well.

p.s.: rpm and AppImage builds are covered by #112 and #524 respectively.

**Comment by benoitf** [comment]
hello @Drugoy could you please use the templates that we're providing to create issues ?

**Comment by benoitf** [comment]
also we provide a binary without flatpak at https://github.com/containers/podman-desktop/releases/download/v0.10.0/podman-desktop-0.10.0.tar.gz

just an archive to expand and launch the binary from the unpacked directory

**Comment by Drugoy** [comment]
> hello @Drugoy could you please use the templates that we're providing to create issues ?

I tried, but GitHub consistently responds with <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422">status 422</a> to those (the reason might be a misconfig on your side, I tried to debug, I tried switching off all of my extensions - nothing helped).

> also we provide a binary without flatpak at https://github.com/containers/podman-desktop/releases/download/v0.10.0/podman-desktop-0.10.0.tar.gz

Oh, I would've never assumed that the archive with such a name contains a binary for linux. You might want to rename the files then (or add description) to indicate what the contents of those packages are.
Just take a look at the names of the files <a href="https://github.com/containers/podman-desktop/releases?q=0.10&expanded=true">here</a>: one can only guess by rules like 'oh, it's an .exe - this gotta be for windows, .dmg - for apple, .flatpak - linux'.
But .zip, .tar.gz - who knows what's there?
Luckily, some of the files mention arch they are built for (like arm64), so I, as a  user of amd64 device can just exclude those without thinking what OS they are for.
Some of the files also contain the word 'universal' - what does that even mean?

**Comment by benoitf** [comment]
for AppImage, rpm, etc
it's duplicating https://github.com/containers/podman-desktop/issues/524 and https://github.com/containers/podman-desktop/issues/112

I've also created https://github.com/containers/podman-desktop/pull/1133 to better highlight the alternate amd64 binary for linux

**Comment by Drugoy** [comment]
@benoitf only .deb doesn't seem to be covered then, should I alter this ticket to be only about providing *.deb packages?

**Comment by benoitf** [comment]
@Drugoy yes probably
