### ISSUE TITLE
On windows support qemu with accel whpx

### ISSUE THREAD

**Issue by hgkamath** [containers/podman-desktop#1134]
### Is your enhancement related to a problem? Please describe

Run pods on windows without being dependent on hyperv/wsl/wsl-linux

podman is getting an updates to specify virtual-machine machine provider with ```set CONTAINERS_MACHINE_PROVIDER=QEMU```, 
so supporting qemu-with-whpx should soon be possible. https://github.com/containers/podman/pull/16872 

**Wrt host-folder-mounts**: A proposal for windows-qemu 9pfs(v9fs) support (https://gitlab.com/qemu-project/qemu/-/issues/974 ) for folder mounts exists, but it is still under design/development. and has challenges. So the feature may not be available any time soon. This probably only affects allowing 9pfs host-folder mounts. It would still be desirable to use podman to run pods from a virtual-disk (raw/qcow2/vhdx) without 9pfs-host-folder-mounts. 
What if, instead of 9pfs-host-folder-mounts, podman could attach 
- mount specified partitions/filesytems in host-virtual-disks (vhdx/qcow2) , i.e. Don't bother with concurrent-access/host-sharing, If a user on host needs access, temporarily stop the podman machine and use some mechanism to directly attach/browse the virtual-disk's contents for the duration of need.
- or attach smbfs network-shares instead? 
- or mount nfs shares?
- or mount nbd (network-block-device), specifying nbdpartition/nbd-name/nbd-port and using a nbd-server like qemu-storage-daemon
- or sshfs 

The qemu-vm(s) running the pod(s) should not prevent/interfere running of other qemu VMs.
One might also want to provide custom arguments to the qemu virtual machine.

### Describe the solution you'd like

run/manage pods on windows using qemu virtual machine with accel whpx (hyperv)

### Describe alternatives you've considered

NA, mine is a dual boot machine, currently when booted into Linux I run pods on kvm/Linux

### Additional context

so far, On Windows, I just installed podman-desktop using scoop, the GUI interface seems good. Did not find any place in settings to change the target machine provider.

**Comment by afbjorklund** [comment]
Support for qemu/whpx in Lima (planned, not done)

* https://github.com/lima-vm/lima/issues/909

Using sshfs, before virtfs (or virtiofs) is available.

**Comment by benoitf** [comment]
closing as upstream issue has been closed https://github.com/containers/podman/pull/16872 so there is no support in podman
