### ISSUE TITLE
MacOS universal installer

### ISSUE THREAD

**Issue by jawnsy** [containers/podman-desktop#116]
### Is your feature request related to a problem? Please describe

Users sometimes need a container runtime, but do not know the architecture of their computer (x86_64 vs Apple silicon).

### Describe the solution you'd like

A single binary that includes native support for both architectures, or a [Universal macOS Binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary), allows users to avoid the need to decide between an appropriate download.

### Describe alternatives you've considered

The existing process (choose between x86_64 and Silicon) during download is fine, and also has the advantage that it results in smaller binaries. In some environments, IT admins may want to centrally manage (push) application installs of Podman Desktop, and in that case, universal installers are often helpful.

**Comment by benoitf** [comment]
I'll add universal dmg as extra choice for dmg 👍
