### ISSUE TITLE
Podman Desktop should read connection info from machine first (Mac, Windows hosts)

### ISSUE THREAD

**Issue by arixmkii** [containers/podman-desktop#1168]
### Is your enhancement related to a problem? Please describe

Sometimes there is a need to have customized build of podman machine (like this experiment of QEMU support on Windows https://github.com/containers/podman/issues/13006), in this case socket where API is exposed could differ (for example no to clash with production version). A more detailed example would be that QEMU version of podman machine doesn't need to use named pipes and could use unix domain sockets.

### Describe the solution you'd like

Instead of immediately guessing the socket path in this place https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/extension.ts#L116, podman-desktop should first try to read it from CLI using `podman machine inspect --format {{.ConnectionInfo.PodmanSocket.Path}}` Currently this API would respond with empty value for WSL, but there is an issue registered to address this https://github.com/containers/podman/issues/16860

### Describe alternatives you've considered

Using netcat/nmap/nc/socat/gocat or any other possible relay to forward socket to the one, which podman-desktop could understand, but this is a workaround and can't be used to run multiple instances of the machine simultaneously.

### Additional context

Tested this only for Podman machine on Windows and Mac. And from code it is not clear if Linux Podman machine is a supported scenario for Podman Desktop.

Reopen of https://github.com/containers/podman-desktop/issues/1128 which was closed by mistake taking a workaround for related, but not the same issue as a solution.

**Comment by arixmkii** [comment]
I waited for someone to re-open the original, but it didn't get any attention. Here is a comment from the contributor, that their commit didn't address the original issue fully https://github.com/containers/podman-desktop/issues/1128#issuecomment-1379269537

**Comment by arixmkii** [comment]
Did some experiments and it looks like this will still require client side workarounds on Windows for QEMU machine provider, because of this issue https://github.com/nodejs/node/issues/35008

Some background. QEMU provider is built around Unix domain sockets to share as much code as possible with non-Windows versions, so, it is logically to expose endpoint in a form of Unix socket, but the current data structure of machine info allows only single endpoint being reported (even, when multiple are implemented, like Unix domain socket + named pipe in test builds of QEMU provider on Windows).

This is still is a nice to have for machines on non-Windows platforms.

**Comment by benoitf** [comment]
if you're able to report named pipe location in the machine info output, then we could connect

**Comment by arixmkii** [comment]
> if you're able to report named pipe location in the machine info output, then we could connect

This is my next point in TODO list :) Just requires more changes to the Podman codebase.

**Comment by arixmkii** [comment]
My current idea is to have on all platforms:
```
podman machine inspect --format {{.ConnectionInfo.PodmanSocket.Path}} my-machine
```
Keeping it empty for WSL machine as it is now.

And adding something like
```
podman machine inspect --format {{.ConnectionInfo.PodmanNamedPipe.Path}} my-machine
```

Which will report named pipe for the machine, both for WSL and QEMU.

**Comment by benoitf** [comment]
that would be cool for clients 😎
