### ISSUE TITLE
"No connection could be made because the target machine actively refused it." after a fresh install on Windows 11

### ISSUE THREAD

**Issue by CarlosDomingues** [containers/podman-desktop#1173]
### Bug description

After a fresh install, I'm getting: 

`Error: failed to connect: dial tcp [::1]:51632: connectex: No connection could be made because the target machine actively refused it.` 

when using `podman` from Powershell.

1. `which podman` tells me I'm using the binary installed by `podman-desktop`

2. `podman machine list` shows a single machine, which is also the default:

```
NAME                     VM TYPE     CREATED      LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  wsl         2 hours ago  Currently running  8           585.5MB     697.3MB
```

3. I tried executing `podman system connection default podman-machine-default`, but I still get the same error.

4. I tried opening a terminal in the `podman-desktop` managed vm and `podman run quay.io/podman/hello` executes correctly.

5. When using `podman-desktop` from the UI, I get the following error when trying to build a container: `Error:Error: connect ENOENT //./pipe/podman-machine-default`

### Operating system

Windows 11 Business 22H2

### Version

0.10.0

**Comment by daviewales** [comment]
I had this. I fixed it by opening Podman Desktop and clicking the update button a couple of times.

**Comment by benoitf** [comment]
not reproducible with latest Podman versions

**Comment by oold** [comment]
I just had this happen:
<img width="1050" height="700" alt="Image" src="https://github.com/user-attachments/assets/e494d042-3bf8-43dc-9ac6-6bde52560601" />
