### ISSUE TITLE
Container Log is truncated

### ISSUE THREAD

**Issue by myfear** [containers/podman-desktop#1174]
I've installed a fresh version of podman desktop via brew and started a container from the podman/hello image from the UI. Clicking on the container shows the log truncated on the left (see screenshot).
Starting a container from the same image from the terminal shows the full log without truncation. 

<img width="1171" alt="truncated_log" src="https://user-images.githubusercontent.com/1358554/212478765-c625ab3a-4b8b-4280-aacb-2386665ebcde.png">

Using latest podman 4.3.1 with desktop version v0.10.0 (installed via brew) on Mac M1.

**Comment by benoitf** [comment]
will be fixed by https://github.com/containers/podman-desktop/pull/1197
