### ISSUE TITLE
Tabs like Inpect should set focus on pane below

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1184]
### Is your enhancement related to a problem? Please describe

It's really handy that panes like Container > Inspect and Kube are interactive and I can scroll and search within them. However, I have to select the 'tab' and then click within the pane to enable this behaviour, which is both annoying (2 clicks vs 1) and meant it was harder to discover that keyboard actions worked in the first place.

### Describe the solution you'd like

When you click on the tab it should automatically set focus on the pane below.

**Comment by deboer-tim** [comment]
Found a few references where they explicitly suggest not doing this as it will break accessibility - users do not expect focus to be shifted automatically. I'm not sure what the correct behaviour is but I still think we can improve this. Maybe it'd be enough to forward key events from the tab to the pane?

**Comment by themr0c** [comment]
I can confirm this is annoying in terms of docs too.

**Comment by deboer-tim** [comment]
Keeping this open - I would still like to (e.g.) click on Terminal tab and start typing.
