### ISSUE TITLE
Initialize Podman process never completes

### ISSUE THREAD

**Issue by benemon** [containers/podman-desktop#1198]
### Bug description

On a clean install of Podman Desktop / Podman, when attempting to "Initialize Podman" from the UI, the process never completes

The following screen is presented and never resolves:

<img width="648" alt="Screenshot 2023-01-18 at 12 38 55" src="https://user-images.githubusercontent.com/4622553/213173572-8d3b4de1-077f-4858-b0fc-3668c822252d.png">

If Podman Desktop is restarted, then the "Initialize Podman" option state is reset to uninitialised. 

<img width="854" alt="Screenshot 2023-01-18 at 12 45 09" src="https://user-images.githubusercontent.com/4622553/213174951-5d0955a4-c9c9-489e-ad7b-ed98647e01af.png">

Note that executing this process via the Podman CLI works as expected - a Podman Machine is created and succesfully started.

```
benjaminholmes@benjaminholmes-HMX933964V ~ % podman machine init
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

benjaminholmes@benjaminholmes-HMX933964V ~ % podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users/benjaminholmes:/Users/benjaminholmes

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command: 

	podman machine set --rootful

API forwarding listening on: /Users/benjaminholmes/.local/share/containers/podman/machine/podman-machine-default/podman.sock

The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it run the
following commands:

	sudo /opt/homebrew/Cellar/podman/4.3.1/bin/podman-mac-helper install
	podman machine stop; podman machine start

You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

	export DOCKER_HOST='unix:///Users/benjaminholmes/.local/share/containers/podman/machine/podman-machine-default/podman.sock'

Machine "podman-machine-default" started successfully
```

### Operating system

macOS Monterey 12.6.1 - Apple Silicon - M1 Pro

### Version

0.10.0

### Steps to reproduce

- Ensure no Podman Machine is present on device - a MacBook 16" with Apple Silicon M1 Pro
- Install Podman Desktop from Brew
- Open Podman-Desktop
- Follow instruction to "Initialize Podman"

### Relevant log output

```shell
N/A - not sure how to extract Podman Desktop logs as none are explicitly shown or presented during the process
```

**Comment by benemon** [comment]
Update: executing `sudo /opt/homebrew/Cellar/podman/4.3.1/bin/podman-mac-helper install, restarting Podman Desktop, and rerunning the Initialisation Process fixed the initial issue.

This may be coincidental however, as now the 'Run Podman' option does not complete successfully.

**Comment by benoitf** [comment]
hello @benemon if you refresh the UI using View/Reload menu does it refresh or not ?

**Comment by benemon** [comment]
Hey @benoitf - if I do a View->Reload on the UI window, it resets the toggle switch for 'Initialize Podman' or 'Run Podman' (whichever state the UI is in) back to its inactive state.

If I then hit the button again, it seems to complete (and references Podman Machine), and the UI is left in the following state:

<img width="1041" alt="Screenshot 2023-01-18 at 15 59 10" src="https://user-images.githubusercontent.com/4622553/213224622-ce64efc4-6633-44c7-b0a1-090491c08f13.png">

I assume the following Container screen should update when the process is sucessful?

<img width="425" alt="Screenshot 2023-01-18 at 16 00 28" src="https://user-images.githubusercontent.com/4622553/213225052-72409a12-c080-475e-aeee-05265242b6e7.png">

**Comment by benoitf** [comment]
hi @benemon could you try with a pre-release build like https://github.com/containers/podman-desktop/releases/tag/v0.0.202301180943-7da772b ?


you need to click on File/Quit or on the tray icon Exit before launching another instance

**Comment by benemon** [comment]
Certainly @benoitf - let me give that a go and get back to you.

**Comment by benemon** [comment]
Hi @benoitf - I can confirm that the issue appears to be resolved in the pre-release build, and pulling the 'podman hello' image completes succesfully:

```
lo Podman World ...!
 .--"--.           
 -     - \         
(O)   (O) \        
-=(,Y,)=- |         
. /`  \   |~~      
o \~~~~.----. ~~   
= |~  / (O (O) \   
~~  ~| =(Y_)=-  |   
  ~~~|   U      |~~ 
   https://github.com/containers/podman
   https://podman.io
s: https://docs.podman.io
   @Podman_io
```

**Comment by benoitf** [comment]
ok thanks for trying the new build (and that it's fixing your issue)
probably we can close the issue
