### ISSUE TITLE
Build an image from local dockerfile

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#12]
## Description ##
As a user, I should be provide a dockerfile and build it from the list of containers.

## Acceptance criteria ##
- On the list of containers, the user has a button that allows to create a new container.
- When clicked, it gives the option to the user to provide a dockerfile
- The user can select a dockerfile from is local environment and provide a name for the image
- The user can select which container engine to use to build the image.
- When building the image, the user will get access to the outputs.

**Comment by benoitf** [comment]
implemented
