### ISSUE TITLE
Please add digital signatures to exe 

### ISSUE THREAD

**Issue by yoursmanish** [containers/podman-desktop#120]
### Is your enhancement related to a problem? Please describe

Without digital signatures, its blocked by windows defender

### Describe the solution you'd like

Without digital signatures, its blocked by windows defender

**Comment by kenmoini** [comment]
This would be very helpful for customers who like signed assets - currently it does not give the good feels.
![image](https://user-images.githubusercontent.com/1857778/168188323-8000b390-223d-447b-990f-d7d188e8885c.png)

**Comment by benoitf** [comment]
sure, there is an ongoing work to get certs for Windows binaries. For now we got it only for macOS but for sure we want tov have it for Windows as well.
