### ISSUE TITLE
pods tab: list and start stop pods

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman-desktop#121]
### Is your feature request related to a problem? Please describe

it's a missing feature. the problem it tries to solve when having an entire stack of apps running as a pod (ex. a pod of mysql with its UI phpmyadmin)

### Describe the solution you'd like

a list pods similar to

```
podman pod ps
podman pod stats
```

and when a pod `mypod` is selected

```
podman pod start mypod
podman pod stop mypod
podman pod restart mypod
podman pod top mypod
podman pod logs --tail=20 -f mypod
```

**Comment by benoitf** [comment]
It looks like a subtask of https://github.com/containers/podman-desktop/issues/87
