### ISSUE TITLE
Connect to remote using podlib API

### ISSUE THREAD

**Issue by rahbari** [containers/podman-desktop#1212]
### Is your enhancement related to a problem? Please describe

I installed podman desktop on my mac to remotely manage several linux hosts. but it seems it only connects to the single local machine using CLI. for now i'm using intellij docker plugin which can do this.

### Describe the solution you'd like

It's nice to be able to add several machine using api.

**Comment by benoitf** [comment]
hello @rahbari it looks a duplicate of https://github.com/containers/podman-desktop/issues/279

**Comment by mmm8955405** [comment]
> hello @rahbari it looks a duplicate of #279

#279 How long will it take？
