### ISSUE TITLE
Malicious Object Detected on podman desktop via winget by kaspersky

### ISSUE THREAD

**Issue by arthurcaccavo** [containers/podman-desktop#1222]
### Bug description

I downloaded podman-deskotp via winget and could not initialize it as kaspersky identified it as a trojan malware.

### Operating system

windows

### Version

0.10.0

### Steps to reproduce

download podman-desktop

`winget install -e --id RedHat.Podman-Desktop`

kaspersky will announce Malicious object detected when trying to start

### Relevant log output

```shell
Result description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
User: AzureAD\ArthurCaccavo (Initiator)
Object: C:\Users\ArthurCaccavo\AppData\Local\Programs\podman-desktop\Podman Desktop.exe
Reason: Behavior analysis
Database release date: 19/01/2023 13:54:00
SHA256: 5F2BD4ADF649F42CA23830BE95D502562E073F1452BCFB7D44622510B0702BD1
MD5: CA8F0AECD174E25D6D8F7371D544C819
```

**Comment by cdrage** [comment]
> 

Hi @SemnoSao unfortunately this is an ongoing issue https://github.com/containers/podman-desktop/issues/700 as Kaspersky has flagged it as a false-positive. 

If you're able to report is as a false-positive within your Kaspersky software it would really help us reverse the issue. We've been submitting new reports every couple of weeks but unfortunately it hasn't resolved yet.

I'm going to close this issue as we have an open ongoing one right now: https://github.com/containers/podman-desktop/issues/700
