### ISSUE TITLE
UI Component: Dashboard Message (Simple)

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1229]
### Epic
This is part of the Dashboard Revamp epic (https://github.com/containers/podman-desktop/issues/4020).

### Related Components
https://github.com/containers/podman-desktop/issues/1230 UI Component: Dashboard Message (Multi)

### Preview
![Screenshot from 2023-01-23 20-43-15](https://user-images.githubusercontent.com/799683/214195922-7a1fdc23-b9aa-40d8-9b31-aa83e7f50c83.png)

### Link to Penpot file with inspectable fonts/colors/css/etc:
https://design.penpot.app/#/view/c1a43240-198d-11ed-817f-f940e3befd53?page-id=f89df008-0194-80f6-8001-9a648b96f00b&section=handoff&index=3&share-id=2a21f5ae-60ee-8151-8001-f3985b0d35fe

[Note: You don't need a Penpot username to view the mockups if you don't have one, you can log in using your GitHub account. It should then show you a code inspector for the mockup.]

## Specification

There are four main parts to this dashboard message component:

* **Headline** [required]: Should be a slug. Here you can see it's using an emoji. Ideally this would be one-line, short, to the point: What does the user need to do?
* **Description** [required]: Explain what the user needs to do in more detail, and why, and if applicable provide pointers to relevant areas in the UI. (The underlined "Settings > Resources" is meant to be a link to that screen.)
* **Call-to-Action Button** [optional]: A button that describes - ideally as a verb or verb + object - the action (if any) that the user needs to take with a button to bring them to where they need to do it.
* **Dismiss button** [required]: X in the upper right. Once the user clicks this, the dashboard message should go away and not reappear [unless triggered by a new instance of the action / status / situation that triggered the one that was dismissed.]

**Comment by mairin** [comment]
I am adding this to sprint 247 / planned since it is needed for Onboarding.

**Comment by nichjones1** [comment]
Decided we do not need this.  Closed
