### ISSUE TITLE
UI Component: Dashboard Message (Multi)

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1230]
### Epic
This is part of the Dashboard Revamp epic (https://github.com/containers/podman-desktop/issues/4020).

### Related Components
https://github.com/containers/podman-desktop/issues/1229 -  UI Component: Dashboard Message (Simple) 

### Preview
![Screenshot from 2023-10-10 11-48-50](https://github.com/containers/podman-desktop/assets/799683/6c5293f3-a08e-4fef-bfb1-3ec53ea0b225)

### Link to Penpot file with inspectable fonts/colors/css/etc:
https://design.penpot.app/#/view/c1a43240-198d-11ed-817f-f940e3befd53?page-id=f89df008-0194-80f6-8001-9a648b96f00b&section=handoff&index=4&share-id=2a21f5ae-60ee-8151-8001-f3985b0d35fe

[Note: You don't need a Penpot username to view the mockups if you don't have one, you can log in using your GitHub account. It should then show you a code inspector for the mockup.]

## Specification

There are main parts to this dashboard message component:
* **Overall Message Headline** [optional]: Should be a slug that ideally unifies the messages contained within the dashboard multi message block (if they are thematically related.) If the messages aren't related, this could just default to reading "Notices" or could be omitted. It can use an emoji, ideally short, one-line, to the point. 
* **Individual Message Headline** [required]: Each message has its own headline. It should be a slug. Here you can see it's using an emoji. Ideally this would be one-line, short, to the point: What does the user need to do?
* **Individual Message Icon** [optional]: Per message contained in the multi message block. Icon or emoji that relates to the action item or content of the message. Here in the example we have green checkboxes to indicate something has been detected, and a red empty checkbox to indicate something is missing.
* **Individual Message Description** [required]: Per message contained in the multi message block. Explain what the user needs to do in more detail, and why, and if applicable provide pointers to relevant areas in the UI. (The underlined "Settings > Resources > Podman" is meant to be a link to that specific screen.)
* **Individual Message Call-to-Action Button** [optional]: Per message. A button that describes - ideally as a verb or verb + object - the action (if any) that the user needs to take with a button to bring them to where they need to do it. [Note this mockup has no example buttons.]
* **Individual Message Dismiss button** [required]: Per message. X in the upper right. Once the user clicks this, the dashboard message should go away and not reappear [unless triggered by a new instance of the action / status / situation that triggered the one that was dismissed.] If there is one message left and the user clicks X on it, the entire multi message block should fade from view and not reappear unless any of the messages contained within it are retriggered.
* **Overall supplemental information** [optional]: This is the "Podman Desktop supports multiple container engines" text in the lower right. This is small supplemental information, that could be used to point to docs or broader area about the topic of the multi message block.

**Comment by mairin** [comment]
I am adding this to sprint 247 / planned since it is needed for Onboarding.

**Comment by nichjones1** [comment]
design only.  Implementation is track in another issue.  Closed
