### ISSUE TITLE
When building a containerfile, if user leaves the page with the details, it is impossible to get back to it

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#125]
### Bug description

When building a containerfile, if user leaves the page with the details, it is impossible to get back to it

### Operating system

mac OS

### Version

0.0.2

### Steps to reproduce

1. Go in "Images" and start building an image with a containerfile or dockerfile
2. Then click on containers in the left sidebar

Result:
The context is lost and it's not possible to get back the details about the image which was built.

Proposal solution:
We should look at introducing a way so that the users can get back to the currently running and previously executed action.
Maybe, we can introduce a status bar, from which the user can see if something is running and click on it to display a dedicated screen.

**Comment by benoitf** [comment]
removing the on-hold, needs to use the task manager

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/1602

it'll be integrated into the task manager in https://github.com/containers/podman-desktop/issues/1343
