### ISSUE TITLE
Kind: Provide ability to "Play Kubernetes YAML" with different providers

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1261]
### Is your feature request related to a problem? Please describe

From Podman Desktop, a user has the ability to generate kubernetes manifests for containers and pods. There are also capabilities that enables a developer to run kubernetes manifests directly with Podman. 

It would be nice to have the ability to run kubernetes manifests to a local cluster setup with Kind from Podman Desktop.

### Describe the solution you'd like

Providers should be able to register for certain capabilities they are able to accomplish (or not). For example, a provider could register that it can run kubernetes manifests. 

When a user selects a kubernetes manifest file, Podman Desktop should be able to determine if there is one or more provider that can run the manifest. If there is, Podman Desktop should be providing the choice on where to run the kubernetes manifests. 

<img width="1002" alt="Capture d’écran 2023-04-13 à 14 12 20" src="https://user-images.githubusercontent.com/1636769/231754623-8d9a3d30-1f34-4c18-bdb5-b3eefc3d151c.png">

(note this is different from deploying the manifest to a cluster, which is a different feature request, here we are in the context of doing a `kubectl apply -f <manifest>`)

Maybe, it would be nice that the user can get the option to define the default provider for certain actions.

**Comment by jeffmaury** [comment]
The fact that the Kubernetes cluster is implemented by a container provider is an implementation detail.
So I think the Deploy to Kube is enough for the developer.
I think we should better add option to Kubernetes providers so that they would accept to push the image before we created the deployment
