### ISSUE TITLE
Kind: Share images between Podman and Kind

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1262]
### Is your feature request related to a problem? Please describe

When a developers are using Podman Desktop, they may build images locally but want to try them onto a local kubernetes cluster setup with Kind. 
It would be nice to have the ability to share images from Podman Desktop to Kind. 

### Describe the solution you'd like

As a user, I would like an option to share all my images with Kind --> `kind load docker-image`

As a user, I should be able to select one or more images to share with Kind --> https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

**Comment by deboer-tim** [comment]
I don't want to get in the habit of architecting things for scenarios we don't have yet :) , but worth noting that it's likely we'll want to move images between other container engines/Kubernetes systems in the future, so let's try to learn while doing this and not make it too hard-coded to this specific use case.

**Comment by benoitf** [comment]
so while the `kind load docker-image` can't be used we can use the `kind load image-archive` command

Podman Desktop can achieve what is performed there https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/load/docker-image/docker-image.go using REST API of the container engines.

(sanitize image, tag, dump to a tar file, etc)

**Comment by benoitf** [comment]
removing `blocked` status as we have other ways

**Comment by jeffmaury** [comment]
Duplicates #1448
