### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#127]
## Description
As a developer who is using Podman Desktop behind a corporate proxy, I should be able to configure the proxy to be used and propagated automatically to containers.

It should be possible to configure:
- HTTP Proxy
- HTTPS Proxy
- FTP Proxy
- and configure certain hosts/domains to not use any proxy (no_proxy option)

CF: https://docs.podman.io/en/latest/markdown/podman-create.1.html#http-proxy

## Acceptance Criteria
- [x] When configured, the proxy settings are properly used when pulling images
- [x] When running the container, the proxy settings are properly pass to it

## Nice to Have
Would be nice, if there is a detection of existing configuration for another tool (like Docker), to smooth the configuration/onboarding.

**Comment by rhatdan** [comment]
These can currently be configured in containers.conf

**Comment by slemeur** [comment]
Sure thing - here we'd like the ability to configure that from Podman Desktop.

**Comment by rhatdan** [comment]
Agree, this would be a good idea, eventually this GUI should probably allow you to customize many of these default fields.

**Comment by benoitf** [comment]
@rhatdan is that podman on macOS is using system wide proxy configuration automatically ?

**Comment by rhatdan** [comment]
On a MAC we attempt to transfer the proxy settings into the VM.
