### ISSUE TITLE
Cannot add or login to nexus hosted registry using ports (aka: 5443, etc)

### ISSUE THREAD

**Issue by jamjon3** [containers/podman-desktop#1272]
### Bug description

From Podman desktop, I cannot 'add' a registry hosted on nexus as it states it's invalid. This may be due to appending the port 5443 in the registry location.

This works just fine from the commandline:

podman login nexus.something.com:5443

I can pull images fine from the command line but podman-desktop doesn't seem to like a registry with a port number. If I pull images from command-line, I can 'see them' listed in images. I just can't use the podman-desktop itself to interact with my Nexus Repository.

### Operating system

Fedora 37

### Version

0.11.0

### Steps to reproduce

Click on Settings => Registry => Add registry

put in your Nexus Repository Docker repo running on port 5443 (which is using a valid Let's encrypt, certificate) with your username and password and click 'Login'. You get 'not a valid registry'.

To test: podman CLI, just do a podman login with that same nexus registry with port 5443 with your user name and password. Works fine. No problems running building or whatever from the command line.

**Comment by benoitf** [comment]
thanks for the report @jamjon3 
we lay have a bug with a custom port number.

but for
> If I pull images from command-line, I can 'see them' listed in images

we collect images from the same location so we should see the images

for example do you see your images if you do a curl operation like (`$XDG_RUNTIME_DIR/podman/podman.sock` being the path to the podman socket)
```shell
curl --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock "http:/v1.41/images/json"
```

also, do you see errors in the console (in the menu bar, click on View/Toggle Developer tools and then Console)
if menu is hidden, pressing the <kbd>Alt</kbd> key should display it

**Comment by jamjon3** [comment]
@benoitf I ran that curl command and got this

`curl --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock "http:/v1.41/images/json"
[{"Id":"sha256:1abb5798988e605cf87d943fdf7f5e739dd548436d0becaf1d0711908cb84731","ParentId":"dd068cd3306d206b931664360bed76ab6d679e175a807107461a12d1b34e0729","RepoTags":null,"RepoDigests":[],"Created":1669578068,"Size":568596121,"SharedSize":0,"VirtualSize":568596121,"Labels":{"io.buildah.version":"1.28.0"},"Containers":2,"Dangling":true,"Digest":"sha256:cff6dd097db28ad0f6132ce2494614c631c2cc4602bc20b2e62727812dbac9bc","History":["docker.io/library/d9bf4af614ccd6e62bb814cab6b4c8228e859c2ad3970f2a33cbe2786e89041d-tmp:latest"]},{"Id":"sha256:dec77c231532d86ebfe9e3f8f482aac633161b112ae59f762f81b695d876f098","ParentId":"b11194893056f4c126a2c15185df290634bf227cc2060b3b4d43230f8bd71283","RepoTags":null,"RepoDigests":[],"Created":1669579167,"Size":568595969,"SharedSize":0,"VirtualSize":568595969,"Labels":{"io.buildah.version":"1.28.0"},"Containers":1,"Dangling":true,"Digest":"sha256:8b7d5a27a7d81d8836142674bd74c2095a42331f88bc9316197c7d6e0e987213","History":["docker.io/library/ad2b4317aa5fedc0a42d97a817f59e8ceda113a28f56acd9c8e90f01a28b9bdd-tmp:latest"]},{"Id":"sha256:7750b995e394351dbe6bb1c79d1e16dd3bf46e6d25a1f62ad5511e8c21e71dc2","ParentId":"","RepoTags":["quay.io/podman/stable:latest"],"RepoDigests":["quay.io/podman/stable@sha256:209522d21fd7040c8f7ae6da53828da3bfc20bf7f20afeeb1efc53909b6c5842","quay.io/podman/stable@sha256:aabebeb7ef3405f5e7fb175a7f1fbee7747bd72ef201c675acbf1e34410b8eca"],"Created":1672856450,"Size":342247908,"SharedSize":0,"VirtualSize":342247908,"Labels":{"io.buildah.version":"1.27.2","license":"MIT","name":"fedora","org.opencontainers.image.created":"2023-01-04T18:19:42+00:00","org.opencontainers.image.revision":"49075c3813a617961b24f322f79e73c7725ed0dd","org.opencontainers.image.source":"https://github.com/containers/podman.git","org.opencontainers.image.version":"4.3.1","vendor":"Fedora Project","version":"37"},"Containers":0,"Names":["quay.io/podman/stable:latest"],"Digest":"sha256:209522d21fd7040c8f7ae6da53828da3bfc20bf7f20afeeb1efc53909b6c5842","History":["quay.io/podman/stable:latest"]}]`

I do see some errors in the console

![image](https://user-images.githubusercontent.com/907953/215230137-df6f6410-629c-47a6-bda6-ae78d843ddcc.png)

**Comment by lstocchi** [comment]
Hi @jamjon3 ,
could you give it another try by using the main branch/a newer version? Or do you have any nexus repo free to access to test it? I tried with one nexus3 repo i have but it works fine for me. Thanks!!

**Comment by jeffmaury** [comment]
I set up a Nexus locally with a self signed certificate and added a Docker repository listening to an HTTPS port.
I was able to add it with the only trick that I add to tweak the code so that self side certificates are accepted when verifying the authentication to the registry.

So closing
