### ISSUE TITLE
Feedback form is not user friendly

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1275]
### Is your enhancement related to a problem? Please describe

The feedback form does not allow the send data if the rating part has not been set but there is no feedback for the user why the Send feedback is not available

### Describe the solution you'd like

Provide feedback

**Comment by benoitf** [comment]
@jeffmaury what do you expect to see when you're not able to click ?
- asterisk on the rate choice indicating it's required ?
- hover on the button displaying a text for what you need to do
- another suggestion ?

**Comment by jeffmaury** [comment]
Hover on the button or a status space within the form that is updated according to validation errors that are triggered
