### ISSUE TITLE
Registry integration

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#128]
### Is your feature request related to a problem? Please describe

Today I had to do three registry-related things where I had to 'drop down' to the cli:
- Pull a specific image.
- Push a local image.
- See details on openjdk:8. The docker hub tag filtering is awful, there are 145 pages of tags that include "8": "8-jre", "8-u332" "19-ea-oraclelinux8", etc. Good luck finding just "8".

Could I accomplish all of these from the cli? Absolutely. (I pulled openjdk:8 and inspected it, not sure if there was a better way) However, I had to use help to confirm syntax of one command and all of them would have been quicker with a UI.

### Describe the solution you'd like

This could easily be broken up or staged in multiple deliveries. I'd start with basic support for pulling a known image or pushing. Having the ability to browse and filter a registry (especially with some advanced options) would be nice later.

**Comment by benoitf** [comment]
@deboer-tim you may try a CI build of https://github.com/containers/podman-desktop/pull/138
