### ISSUE TITLE
docs: Unable to navigate to some pages using mobile view

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1294]
### Is your enhancement related to a problem? Please describe

When I'm viewing the website using a mobile view there is no sidebar so I only see 'Intro' and 'Troubleshoothing' pages

Nothing is linking me to Install part

### Describe the solution you'd like

Add links to the footer (to the existing Introduction/Troubleshooting or make links to a TOC of the documentation)
as I'm unable to get it

### Describe alternatives you've considered

Something allowing to browse the documentations
if I click on the 'house' I go back to the landing page of the website, not the 'root documentation page'

### Additional context

to reproduce 'mobile view' just reduce the width of the screen

**Comment by themr0c** [comment]
* The navigation is accessible from the (top left) Burger menu.
* The "Documentation" footer links are statically set in docusaurus.config.js.
