### ISSUE TITLE
Error on inspect

### ISSUE THREAD

**Issue by nitinkale** [containers/podman-desktop#1297]
Receiving following error on executing inspect command

podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}'

Error : 
template: inspect:1:28: executing "inspect" at <.ConnectionInfo.PodmanSocket.Path>: nil pointer evaluating *machine.VMFile.Path

**Comment by benoitf** [comment]
Hello @nitinkale it seems you by-passed the templates

What is your operating system and your podman version ?

**Comment by benoitf** [comment]
and you read this command from the documentation, correct ? It's not something reported by the tool.

**Comment by nitinkale** [comment]
Operating System : Windows 10
Podman Version : 4.3.1
Issue is reported on executing "podman inspect" command in windows terminal. I was trying to execute commands suggested in this document 
  https://podman-desktop.io/docs/migrating-from-docker/using-the-docker_host-environment-variable

**Comment by benoitf** [comment]
ok thanks I suspect podman machine on Windows is not providing the path to the npipe

**Comment by nitinkale** [comment]
Yes . Podman machine start is failing on my machine. How to fix this?

podman machine start
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: The system cannot find the file specified.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully

**Comment by benoitf** [comment]
>>  Podman machine start is failing on my machine. How to fix this?
>> CreateFile \.\pipe\docker_engine: The system cannot find the file specified.

do you have Docker Desktop installed AND running ? if it's running probably it can replace the file managed by Docker


Also could you try
```
set DOCKER_HOST='npipe:////./pipe/podman-machine-default'
docker ps
```

it should list and connect to the podman socket

**Comment by benoitf** [comment]
https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md#using-api-forwarding

**Comment by nitinkale** [comment]
Thanks @benoitf . I was able to resolve initial issue with following steps
1. Disable and Enable WSL 
2. Uninstall all distros
3. Install Podman 
I was able to run basic docker test however docker build is failing with following error

Sending build context to Docker daemon  17.41kB
request returned Bad Request for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.41/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=FuncApp%2FDockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&target=&ulimits=null&version=1, check if the server supports the requested API version

**Comment by benoitf** [comment]
I think it's related to https://github.com/containers/podman/issues/15928 and https://github.com/containers/podman/pull/16380

**Comment by nitinkale** [comment]
@benoitf [Issue](https://github.com/containers/podman/issues/15928) is reproducible with podman 4.2.0 as well.
Is there any workaround available ?

**Comment by benoitf** [comment]
you may downgrade the docker cli if possible

**Comment by nitinkale** [comment]
Tried Docker version 20.10.18, build b40c2f6 and Podman 4.3.1 with same error

**Comment by benoitf** [comment]
closing as not reported anymore in newer podman versions
