### ISSUE TITLE
Display list of providers and allow start/stop of container VM from the dashboard

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#13]
## Description ##
As a user, I should be able to get the list of all the different "container providers" I'm using and start/stop their VM.

## Acceptance criteria ##
- On the dashboard, a new tab should be available to display the list of provider
- For each of the providers, we will display the name of the provider and its status.
- Buttons will allow the user to either start or stop the VM of the "container provider"

**Comment by benoitf** [comment]
already done in intial import
