### ISSUE TITLE
chore: allow redirections in docusaurus site

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#1305]
### Is your enhancement related to a problem? Please describe

Currently, this is not possible to rename a page without generating a 404.

### Describe the solution you'd like

After renaming a documentation page, the old URL should redirect to the new page.

It seems the *plugin client redirects* plugin is the way to achieve that feature with Docusaurus: https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-client-redirects

* Add the plugin
* Add boilerplate configuration docusaurus.config.js

Unfortunately:

* This plugin is always inactive in development and only active in production because it works on the build output.
* The redirections must be handled in a central place (docusaurus.config.js), rather than the renamed page.

### Describe alternatives you've considered

Ideally, we would define redirections in the renamed page, but I couldn't find how to achieve it.

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/3731
