### ISSUE TITLE
Telemetry Foundations

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#131]
## Description
In this epic, we want to put in place the foundations for being able to get telemetry from podman-desktop usage.

We want to do that in a way

## Integration in the settings
In the Settings of the application, we are going to add a new section which for "Privacy Settings". 

We'll have a text which describe why we are doing telemetry and what are the data collected and how we are doing it.
"To improve your experience using Podman Desktop, we use third party tools for telemetry enabling us to understand how the product is performing, being used and where improvements are needed. All data collected are completely anonymized.

[switch to enable/disable] Usage Data"

## What would we like to capture
- Platform used (OS and Version)
- Version of Podman used
- Configuration
  - Machines 
    - Add one podman-machine
    - Add more than one podman-machine
    - Delete podman-machine
  - Registries
    - Add one registry
    - Add more than one registry
    - Remove a registry
  - Extensions Catalog
    - Enable one extension (with extension name)
- Containers
  - Access to container's details
  - Start a new container (from the UI) from an existing image
  - Build a container from a (container/docker-file)
  - Access to logs of a container
  - Access to terminal in a container
  - Stop of a container
- Images
  - Access to Images tab
  - Pull an Image
  - Build an image

**Comment by benoitf** [comment]
closed by https://github.com/containers/podman-desktop/pull/197
