### ISSUE TITLE
Kubify: Have the option to deploy a Deployment

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1320]
### Is your feature request related to a problem? Please describe

I should have the option to deploy a Deployment. Pods are immutable / disposable and if a Pod is evicted from the Node, it will not be recreated.

Deployment is the most common resource for deploying apps / pods / containers in Kubernetes (the other two are StatefulSet and DaemonSet).

It also ensured that the Pod will be restarted / recreated if it gets evicted / a node shuts down.

### Describe the solution you'd like

Implementation of the option of Deployment on the Kubify page.

**Comment by slemeur** [comment]
cc @vyasgun
