### ISSUE TITLE
Registries Management

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#133]
## Description
As a developer who is using Podman Desktop, I should have a UI to allow me configure different registries I might interact with. 

Right now, if I need to configure registries, I need to manually edit `/etc/containers/registries.conf` config file for Podman, but providing a UI to do that would be handy. 

We would like to provide the ability to the user to manage his registries by:
- viewing all the registries configured
- defining define which registry is the default
- adding/deleting a registry
- editing a registry
- managing the authentication to a registry
  - With all the different options (TLS, certificate)

In this epic, we'd be looking at providing coverage for the following commands:
- https://docs.podman.io/en/latest/markdown/podman-login.1.html
- https://docs.podman.io/en/latest/markdown/podman-logout.1.html

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/128
