### ISSUE TITLE
Implementation of Resource Settings

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1337]
The design ticket / specification is here:
https://github.com/containers/podman-desktop/issues/1338

**Comment by lstocchi** [comment]
@mairin a question about this. In the mockup there are only 2 podman machines and they are both visible. How do you think i should handle the case when there is a number greater than the space available? 
E.g i'm in this situation
![immagine](https://user-images.githubusercontent.com/49404737/221911523-71ffe55f-98e4-4e85-8b40-6cb2ee6982b6.png)

it's like there is space for 4 different machines... what happens if the user have 5 of them? Should i add a button on the right that opens up an extra space somewhere or i keep adding stuff to the right and the user has to scroll horizontally?

I am not even sure this will ever happen, just to know if you thought about this use case.

**Comment by benoitf** [comment]
I asked the question during the design and idea was to have the following:
![image](https://user-images.githubusercontent.com/436777/221913537-3d920184-5201-4369-8b32-499906065602.png)


being reactive (so if you have a large window we could display 3 columns, on smaller screen only one column, etc)

**Comment by lstocchi** [comment]
What about the loading after executing an action or if there is an error?
e.g I click on start machine, where the spinner should be? 
If there is an error i have to show the error below the buttons?

**Comment by lstocchi** [comment]
for the loading i was thinking to have something similar to the linear indeterminate progress https://mui.com/material-ui/react-progress/#linear-indeterminate just up the buttons rack (or whatever it's the name of that widget :) )

**Comment by benoitf** [comment]
I would say that for progress it should use withProgress API
so all progresses can be collected and be displayed inside the 'tasks manager' widget

**Comment by mairin** [comment]
@lstocchi Ah good questions :) 

1. **Visual / spinner for clicking action buttons** - @deboer-tim has some work-in-progress on animating the status icons in the container list, I had been thinking we could do something similar with the pressed button itself, so the spinner is as close as possible to where the user initiated the action. Like a circle spinner kind of like this (the basic tailwind one) around the play button and maybe the play button pulsing as well:

https://tailwind-elements.com/docs/standard/components/spinners/

I'll try to do a codepen mockup with what I'm thinking (Penpot doesn't have an animation support yet unfortunately)

2. **For errors** - I think we hope to have some error messages in the notification bar at the bottom of the app if it's using the withProgress API; I think if there is a short error message (eg a simple "failed to start" it could be displayed next to the status under the machine name, and if you click it or hover it maybe a tooltip with more info if we can't bring them to a notification item that has the info. ) Here is what that could look like:

![Group (4)](https://user-images.githubusercontent.com/799683/221934718-d154066a-6f22-46a3-9589-3c00fbcfbabe.png)

Does this make sense @benoitf ^?

**Comment by mairin** [comment]
https://codepen.io/mairindubh/pen/NWLdYvo  

This is the idea I had for progress... it's a hack job but you see what I was thinking anyway :)

**Comment by mairin** [comment]
@lstocchi (I do like the linear indetermine loaders too though - I'm not sure which would work best! The placement you're suggesting along the button bar block sounds reasonable too.)

**Comment by deboer-tim** [comment]
I just noticed that we effectively have a single start/stop button in the containers list but separate buttons here. I prefer the single button (although I'm pretty sure someone will say that it isn't very accessible), but either way I think we should be consistent.

Sticking with the 'consistency' theme, in the lists we're only planning to show 'starting' by animating the status icon (which yes, I am late at following up on). I'm wondering if that's enough here as well? i.e. animate the circle beside a starting status at the top.

**Comment by lstocchi** [comment]
Closing this. All PRs related to the resource settings refactoring have been merged.
