### ISSUE TITLE
add 'view logs' action in kebab menu of container list

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1346]
### Is your enhancement related to a problem? Please describe

We have access to the logs of a container when we click on the details of a container.
But we should have a way to see logs from the kebab menu as well.

![image](https://user-images.githubusercontent.com/436777/216262220-51d159f9-35ae-4faf-925d-121743a214fe.png)

### Describe the solution you'd like

Add entry 'View Logs' in the kebab menu as a quick action

**Comment by deboer-tim** [comment]
Merged.
