### ISSUE TITLE
Inconsistency behavior for logs visibility

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1356]
### Bug description

This issue is to clarify how and when the logs should be displayed.

When I stop a container, the logs view gets cleared but if i switch tab and then I get back to the logs tab i can see them.
What's the expected behavior? When a container is stopped the user should see logs or not?

### Operating system

Windows 10

### Version

0.11.0

### Steps to reproduce

1. Start a pod/container with logs
2. go to the logs tab
3. stop the container
4. the logs are cleared
5. switch tab and then get back to the logs tab
6. you see logs again

### Relevant log output

```shell
N/A
```

### Additional context

![logs_visibility](https://user-images.githubusercontent.com/49404737/216317992-60825142-32e7-4b73-b7fd-dbca02ad6b28.gif)

**Comment by benoitf** [comment]
container stopped, you should still see the logs

issue somehow also related https://github.com/containers/podman-desktop/issues/1346
