### ISSUE TITLE
Volume is not carried to pod

### ISSUE THREAD

**Issue by Keyvan-rh** [containers/podman-desktop#1358]
### Bug description

I have 2 images that need to run in a pod. simple php and a mariadb. i have create these as separate container which each one has a volume to make it persistent and easier to change value as container is running. when i create a pod from these 2 container the volume is not carried over so none of the containers in side the pod has any volume. and to make things worse there is no way to update container inside the pod and re-add volumes.

the only way i was able to do it is to create the kubernetes yaml file edit it and use the play kub yaml option, but this is defeat the purpose of helping developers move faster and decouple kube and yaml and ...
 

### Operating system

fedora 37

### Version

0.11.0

### Steps to reproduce

just create any container with volume attach and try to create a pod from it.

**Comment by benoitf** [comment]
there is an ongoing work to add more selection/stuff when 'Podifying containers' like being able to select a network, review ports.

It should include as well volumes.

**Comment by Keyvan-rh** [comment]
Thanks for the quick respond and update. Is there a time line as when we will see these changes?

**Comment by benoitf** [comment]
For sure it's in 1.7.0

closing
