### ISSUE TITLE
Integrate Container Security tools in podman desktop

### ISSUE THREAD

**Issue by Akasurde** [containers/podman-desktop#136]
### Is your enhancement related to a problem? Please describe

As a developer, I would like to integrate third-party tools like aqua trivy to identify and report container vulnerabilities in podman desktop UI.

### Describe the solution you'd like

need a plugin-based solution to integrate any third-party security solution with podman desktop

**Comment by Akasurde** [comment]
I took this idea from - https://www.aquasec.com/news/aqua-security-trivy-integrates-with-docker-desktop/

**Comment by benoitf** [comment]
@Akasurde you want to use trivy or you're thinking of another tool ?

**Comment by Akasurde** [comment]
I use trivy but I am thinking this feature in podman-desktop should be pluggable.

**Comment by benoitf** [comment]
@Akasurde you can now use the trivy Docker Desktop extension inside Podman Desktop

**Comment by Akasurde** [comment]
Awesome work !!! @benoitf Thanks for working on this. Really appreciate the efforts you put in.
