### ISSUE TITLE
Cross-platform installation and configuration flow for Podman provider

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#139]
Allow to start the installation of podman depending on the different platform

Preflight checks:

- [x] [Windows](https://github.com/containers/podman-desktop/issues/326)
- [x] [macOS](https://github.com/containers/podman-desktop/issues/410)
- [ ] [Linux](https://github.com/containers/podman-desktop/issues/411)

Installation:
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by slemeur** [comment]
Linking to #395

**Comment by slemeur** [comment]
Closing as solved - the pre-flight checks on linux installation will be addressed separately.
