### ISSUE TITLE
Improve delete action visibility for extensions

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1392]
### Is your enhancement related to a problem? Please describe

It's not easy to delete an extension. After installing an extension to do a test, i wanted to delete it and I was a bit lost. I would have expected to find the delete button in the extension settings but it was not there. 
Then i went to the extensions list page and its width was so large that i could not see the delete button on the right of each row.

![delete_extension](https://user-images.githubusercontent.com/49404737/217219349-d6acb3a0-c5f4-4566-8e10-720fa3d79b80.gif)

### Describe the solution you'd like

- Add a delete button in the extension settings
- Fix the width in the extensions list page

**Comment by deboer-tim** [comment]
+1. Let's keep the changes simple and move on though, we haven't done a design for this screen yet and it could change quite a bit.
