### ISSUE TITLE
Error icons shouldn't move

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1404]
### Bug description

If you try to start a container and it fails, there's an error icon that shows you what the problem was. However, this icon moves if you start another container:

https://user-images.githubusercontent.com/19958075/217557762-68773b43-1862-4f27-b317-5ab386859864.mov

Recommendation: error icon should be right-aligned or moved into the actions column (i.e. always in a fixed position to the left of the start action).

### Operating system

macOS 13.2 M1

### Version

0.11.0

### Steps to reproduce

Try to start a container that will fail (in above example: docker.io/redis/redis-stack:latest), then start a second container.

**Comment by benoitf** [comment]
closing as fixed as error icon is no longer moving
