### ISSUE TITLE
!!! VIRUS with podman desktop !!!   WTH - This does not appear to be a false positive

### ISSUE THREAD

**Issue by candeo911** [containers/podman-desktop#1406]
Please tell me there is a simple explanation for this?

I just decided to try containers for the first time.  Spun up a linx box, installed podman with no issues, however when I used this link https://github.com/containers/podman   to install the windows podman desktop, I was led to this link https://podman-desktop.io/downloads/Windows

The second I installed podman desktop, kaspersky went into full red alert safe mode, found a trojan, sanboxed my computer with a full scan and reboot in order to disinfect.  Full log attached, screen shots for reference.

[podman virus.xlsx](https://github.com/containers/podman/files/10687351/podman.virus.xlsx)
![virus](https://user-images.githubusercontent.com/112725157/217580087-6d208437-d052-4739-af8d-fe012424ad54.PNG)

**Comment by Luap99** [comment]
I transferred the issue to the podman-desktop repo because these builds are created here.
@benoitf @slemeur PTAL

**Comment by benoitf** [comment]
This is a dup of https://github.com/containers/podman-desktop/issues/700

There is no virus or trojan, this is a false positive. We're also digitally signing the Windows binaries.
