### ISSUE TITLE
Bug: Failure when trying to install a valid amd64 desktop extension on arm / macOS M1

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1407]
### Bug description

I tried installing an image that uses amd64 architecture only:

![Screenshot 2023-02-08 at 3 39 24 PM](https://user-images.githubusercontent.com/6422176/217645861-fab6bca2-6862-4ec6-8f24-11abd669f164.png)

And the only error is: `Image quay.io/fbenoit/podman-desktop-quickpick is not a Docker Desktop Extension`

In reality, it *is* a valid extension, but there is no arm64 image available, see the below `podman` command:

```sh
▶ podman pull quay.io/fbenoit/podman-desktop-quickpick
Trying to pull quay.io/fbenoit/podman-desktop-quickpick:latest...
Getting image source signatures
Copying blob sha256:e530172ce56f66fe1ce256c82a35089ebd560f7d195275c69ff38c1715623ea1
Copying blob sha256:03288c496ea166f1695219fa402270fa7179992c5a0b03d474adcc092c10de41
Copying blob sha256:48fb7f411f61c9351180fccdbd91b05315a933296aefdf9dd59d8ea11159929d
Copying config sha256:f0bb259bd16080dac3abb5df64b0ed83d58ced7f0e30a729a5b95322f8849ea2
Writing manifest to image destination
Storing signatures
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
f0bb259bd16080dac3abb5df64b0ed83d58ced7f0e30a729a5b95322f8849ea2
```

### Operating system

macOS Ventura M1

### Version

0.11.0

**Comment by benoitf** [comment]
now Podman Desktop is not using a container engine to pull the content of the image, so it works
