### ISSUE TITLE
Docs: Document guide to designing a UI/UX feature + checking with the design team

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1408]
### Is your enhancement related to a problem? Please describe

No outline on UI/UX design

### Describe the solution you'd like

We should add a brief step-by-step numbered outline to CONTRIBUTING.md regarding UI/UX design.

For example:

1. File an issue
2. Check GitLab?
3. Ping @mairin and others
4. Update issue with final design
5. Implement change from PR.

**Comment by mairin** [comment]
More ideas:
- Getting access to the Podman team in Penpot
- Layout of the Podman team workspace in Penpot
- Patternfly aesthetic inspiration // GNOME HIG inspiration
- Where to chat about design
