### ISSUE TITLE
Over 600 releases?

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1410]
### Is your enhancement related to a problem? Please describe

From here: https://github.com/containers/podman-desktop/releases we have over 600 releases, making it hard for someone to browse the GitHub releases / each tag of what we've released.

I see that they are generated from PR's for testing, but this fills up the releases page / makes it hard to navigate. 

### Describe the solution you'd like

- Remove the non-release-related releases (I see they are generated from each PR / test)
- We should modify github-actions to not show these / publish.

**Comment by benoitf** [comment]
Intermediate releases are flagged as pre-releases

Latest release is always the latest tag as well

**Comment by deboer-tim** [comment]
As this is 'normal' and no plan to change, I am closing.
