### ISSUE TITLE
UI: Hook various tasks up to Task Manager bar

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1412]
We need to hook up various long-running tasks into the Task Manager bar so that they display there. Here is a non-exhaustive list to start with:

- [x] Container builds
- [ ] Podify
- [ ] Deploy to K8s
- [ ] Pulling image
- [x] Creating VM
- [x] Starting VM

When devsandbox lands, waiting for the sandbox to become available is another long running task.

**Comment by deboer-tim** [comment]
Container builds and provider creation/start/stop (VMs) have already been switched to the task manager, so marking them off.

**Comment by benoitf** [comment]
closing this item as we didn't continue
