### ISSUE TITLE
Cannot identify telemetry state

### ISSUE THREAD

**Issue by lethargosapatheia** [containers/podman-desktop#1416]
### Bug description

When I go to Settings, it says that Telemetry is enabled, but at the same time the box is unchecked. Checking/unchecking the box and clickling update doesn't seem to have any effect whatsoever. At least not visually in any case.

### Operating system

macOS Ventura 13.1 (arm)

### Version

0.11.0

**Comment by hadrabap** [comment]
Hello, it seems I'm facing the same issue in Linux (flatpak). There, the telemetry window shows up with the checkbox selected irrelevant to what is in settings. This also triggers https://github.com/containers/podman-desktop/issues/664 at least for me.

**Comment by lstocchi** [comment]
Thanks for your feedback guys!! 
Just tried and i can see the telemetry state correctly displayed in the settings/preferences page. Maybe it was fixed somehow when refactoring it with https://github.com/containers/podman-desktop/pull/1913 . 
You should see the correct behavior from next release (end of next week).
I'm gonna close this issue but if you still face it in future, feel free to reopen it. Thanks for your help!! 🙏
