### ISSUE TITLE
Update Buttons in Settings are not displayed properly

### ISSUE THREAD

**Issue by lethargosapatheia** [containers/podman-desktop#1417]
### Is your enhancement related to a problem? Please describe

There are two problems here that I'd like to describe, but they're related to one another, so I didn't think it necessary to open two issues.
1) The Update button have different sizes for different sections in settings and it doesn't look good. For instance, the Kubeconfig section has a bigger button than the Telemetry one.

2) When any Update button is pressed, it looks as if it remained pressed (the darkening effect), which wouldn't normally make any sense here, because it's supposed to run once and the recover after you click on it.

### Describe the solution you'd like

1) Make buttons the same size.
2) Restore button visually after clicking.

### Additional context

MacOS Ventura 13.2 (arm)
podman desktop 0.11.0

**Comment by benoitf** [comment]
Thanks for the report @lethargosapatheia 
There is a task assigned to UX team to redesign the settings/preferences page.

**Comment by deboer-tim** [comment]
Settings > Preferences has been redesigned and no longer has the Update buttons, closing.
