### ISSUE TITLE
show podman desktop version near podman's

### ISSUE THREAD

**Issue by lethargosapatheia** [containers/podman-desktop#1418]
### Is your enhancement related to a problem? Please describe

In the Dashboard only the podman's version is displayed.

### Describe the solution you'd like

I would think it equally important (for symmetry's sake) that the podman desktop's version is also displayed along it. After seeing this, it takes a while to realise that you need to go to the main menu to be able to see podman desktop's version too.

### Additional context

MacOS Ventura 13.1
podman desktop 0.11.0

**Comment by cdrage** [comment]
Version will show on the upgrade / update button: https://github.com/containers/podman-desktop/pull/1386

I will take up this issue to show it on the homescreen as well / somewhere near Podman / somewhere else (help page maybe).

**Comment by cdrage** [comment]
So having it beside the Podman version on the Dashboard wouldn't be feasible as it's modular / gets provider information per-each-extension.

What do you think @slemeur @benoitf adding it to the help menu as well? Would be beneficial for when submitting issues, etc. Simple and the user can copy-and-paste their OS and Version information:


![Image](https://user-images.githubusercontent.com/6422176/220808612-288e03c1-d99d-4e49-9aaf-8f17af5602a8.png)

**Comment by benoitf** [comment]
> So having it beside the Podman version on the Dashboard wouldn't be feasible as it's modular / gets provider information > per-each-extension.

@cdrage the idea is to display the version in the status bar, as when there is an update 
no update: you see: 'v0.12.0' (tooltip just display the version and no command associated)
update: you see an icon like the warning/download etc before the version and tooltip is to fetch the new version


We could display it as well in the help but I would wait https://github.com/containers/podman-desktop/issues/431

**Comment by cdrage** [comment]
> > So having it beside the Podman version on the Dashboard wouldn't be feasible as it's modular / gets provider information > per-each-extension.
> 
> 
> 
> @cdrage the idea is to display the version in the status bar, as when there is an update 
> 
> no update: you see: 'v0.12.0' (tooltip just display the version and no command associated)
> 
> update: you see an icon like the warning/download etc before the version and tooltip is to fetch the new version
> 
> 
> 
> 
> 
> We could display it as well in the help but I would wait https://github.com/containers/podman-desktop/issues/431

Got it. We'll always have the version displayed. I can update my current PR to add that functionality to always display the version / when there is an update there is the icon.
