### ISSUE TITLE
Kind extension is not bundled

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1421]
### Bug description

When you run the production binary, the kind extension is not there

### Operating system

Win11 Pro

### Version

0.11.0

### Steps to reproduce

1. Launch Podman Desktop
2. Go to Settings -> Extensions
3. The kind extension should be listed

**Comment by benoitf** [comment]
it's done 'on purpose'

Goal is to have an extension working before rolling out to the default set of extensions

cc @slemeur

**Comment by deboer-tim** [comment]
Agreed. I think in this case we could start to ask whether it is 'ready/useful enough' to get feedback though, or could it start by being installed but disabled by default?
