### ISSUE TITLE
Provide a mechanism for collecting application logs

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1423]
### Is your feature request related to a problem? Please describe

When a user is facing an issue, we heard that getting the logs is often a struggle. 
In order to help users and ourselves to better understand the issue, we should make it easier to gather the logs in a file.

### Describe the solution you'd like

As a user, when I have an issue with Podman Desktop, I would like the ability to easily get the logs of the application.

There should be a way in the application so that a user can download the logs of the application to attach them to issues on github.

**Comment by cdrage** [comment]
Docker / Podman logs are usually present at: `/var/lib/docker/containers/<container-id>/<container-id>-json.log`

We could add a "Download log file" from the log screen where Podman Desktop will go retrieve it from the API / provide a file.

**Comment by benoitf** [comment]
I think it should not only be about logs but also about actions to check some settings/tools/commands

'diagnostics page'

**Comment by deboer-tim** [comment]
+1. Over time it would be good to bring these diagnostic things in one place - the ability to find logs, diagnose simple things yourself, and find the answers to anything we'd ask if you opened a ticket.

**Comment by mairin** [comment]
At the moment I'm trying to debug something setting up a containerized app with nginx and was thinking it would be really nice if, we could detect i'm using nginx....

It would be nice under the "Logs" tab of the container to have some automatic bookmarks based on that, e.g. for me in my current debugging process i need to bounce between /var/log/nginx/access.log, /var/log/nginx/error.log, and /etc/nginx/nginx.conf.  Maybe for Red Hat family base images theres some journalctl functions... etc.

[How would we detect the app uses nginx? I am not sure how, maybe if there was some field in the Containerfile I could add if im building it, or a tagging system, or maybe it would be like a linter that can't auto-detect the syntax you're using you can manually select say your app uses nginx from a dropdown.]

**Comment by benoitf** [comment]
log is in the troubleshooting page now (light bulb)
