### ISSUE TITLE
Error message when installing Podman with the Windows installer for restricted environments

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#1424]
### Bug description

After installing Podman Desktop and Podman with Windows installer for restricted environments, Podman Desktop displays an error message when initializing Podman.

This is the procedure to reproduce: https://github.com/containers/podman-desktop/pull/1422 

### Operating system

Windows 10 Professional

### Version

0.11.0

### Steps to reproduce

Procedure in: https://github.com/containers/podman-desktop/pull/1422 

1. Fresh Windows 10 Professional virtual machine.

2. Install WSL

    ```
    > wsl --install --no-distribution
    ```

3. Download the Windows installer for restricted environments, and copy the downloaded file to the Windows host in a restricted environment. At this point, the user has no `.local` directory in his home directory.

4. Run the Windows installer for restricted environments to install Podman Desktop. At this point, the user has a `.local\share\containers\podman-desktop` directory but no `.local\share\containers\podman` directory.

5. Open Podman Desktop and click on the Install button to install Podman. At this point, the user has still a `.local\share\containers\podman-desktop` directory but no `.local\share\containers\podman` directory.

6. Click on Initialize Podman. The process creates an empty `.local\share\containers\podman\machine\wsl\cache` directory and fails with an error message

### Relevant log output

On last step, Podman Desktop displays the following message:
 
```
Error: Error: open: c:\Users\Fabrice\.local\share\containers\podman\machine\wsl\cache: is a directory
```

### Additional context

![Screenshot from 2023-02-10 12-08-23](https://user-images.githubusercontent.com/243761/218112862-7d5274f9-96c8-48fe-a2b9-c74d9bbb7cdd.png)

**Comment by themr0c** [comment]
I could reproduce the problem after resetting the Windows virtual machine to a clean state.

**Comment by benoitf** [comment]
closing, no comment since one year
