### ISSUE TITLE
Support customizing the location of `.podman-desktop` folder

### ISSUE THREAD

**Issue by maxsxu** [containers/podman-desktop#1429]
### Is your feature request related to a problem? Please describe

I noticed that after starting Podman Desktop, a `~/.podman-desktop` folder is automatically created in the Home directory, but I didn't find a way to customize the location of this folder in Setting.

BTW, this folder is empty and I don't know what it is for.

### Describe the solution you'd like

Provide a setting item in Settings to customize the location of the `.podman-desktop` folder and explain the purpose of this folder.

**Comment by benoitf** [comment]
this folder is for storage directory for extensions but no extension are using it.

We should move it anyway to the proper .local or .config folders

**Comment by maxsxu** [comment]
> this folder is for storage directory for extensions but no extension are using it.
> 
> We should move it anyway to the proper .local or .config folders

@benoitf Thanks for clarifying. The folder's location follows the [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) standards would be great.

And I think the underlying code is here: https://github.com/containers/podman-desktop/blob/c34ea0bb47226e7e50a45a0f17396bbda451b2a6/packages/main/src/plugin/extension-loader.ts#L170-L173

**Comment by cdrage** [comment]
I've updated this here, was a quick fix: https://github.com/containers/podman-desktop/pull/1551

I don't think it's worth it to create configuration settings to be able to change where the configuration directory is located.

IMHO changing it to the normal .local directory is fine.

**Comment by jeffmaury** [comment]
Reopening as extensions are not given this new location as storage folder but the current directory + extension id
