### ISSUE TITLE
Lots of remaining node processes left after yarn watch on Windows 

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1434]
### Bug description

When running `yarn watch` on Windows, some Node processes are launched. But when the main application is stopped, some of those Node processes are still alive: seems it is there processed that are launched to watch extensions so there is one per extension.

This causes the developer workstation to be overloaded after a couple of debugging sessions.

### Operating system

Win11 Pro

### Version

0.11.0

### Steps to reproduce

1. Monitor node processes running (should be 0)
2. Run `yarn watch`
3. Stop application
4. Monitor node processes running (should be 0 but is greater)

**Comment by benoitf** [comment]
stop application = <kbd>CTRL</kbd>+<kbd>C</kbd> ?

**Comment by jeffmaury** [comment]
> stop application = CTRL+C ?

Not click the upper right cross

**Comment by jeffmaury** [comment]
Can't find a way to fix it so I wrote a small Powershell script to clean those processes after the Electron process has been stopped:

`foreach($p in  Get-CimInstance Win32_Process -Filter "CommandLine LIKE '%yarn%'" | Where-Object { $_.CommandLine -match 'extensions' }) { taskkill /t /f -pid $p.ProcessId }`

**Comment by deboer-tim** [comment]
I don't know if the same fix would apply, but on M1 I have a similar problem. It doesn't seem to matter how I close (e.g. Electron > Quit) but I get the system "Electron quit unexpectedly" dialog, and processes are left around, e.g.:

```
52271 ttys000    0:01.46 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/crc watch
52272 ttys000    0:01.45 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/docker watch
52273 ttys000    0:01.42 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/kube-context watch
52274 ttys000    0:01.53 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/lima watch
52275 ttys000    0:01.46 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/podman watch
52276 ttys000    0:01.48 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/kind watch
52277 ttys000    0:01.47 /usr/local/bin/node /usr/local/bin/yarn --cwd /Users/deboer/git/podman-desktop/extensions/registries watch
52279 ttys000    0:01.61 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/rollup --bundleConfigAsCjs --config rollup.config.js -w
52280 ttys000    0:03.48 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/rollup --bundleConfigAsCjs --config rollup.config.js -w
52281 ttys000    0:01.38 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/tsc -w
52282 ttys000    0:02.22 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/rollup --bundleConfigAsCjs --config rollup.config.js -w
52283 ttys000    0:01.35 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/tsc -w
52284 ttys000    0:05.96 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/tsc -w
52285 ttys000    0:03.49 /usr/local/bin/node /Users/deboer/git/podman-desktop/node_modules/.bin/rollup --bundleConfigAsCjs --config rollup.config.js -w
```

**Comment by deboer-tim** [comment]
Forgot to mention, I just do `sudo killall node` periodically.

**Comment by afbjorklund** [comment]
Same here on Linux, just without the sudo (I don't run PD as root)

**Comment by benoitf** [comment]
closing as won't fix
