### ISSUE TITLE
Docs: Kubernetes Documentation

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1449]
### Is your feature request related to a problem? Please describe

Podman Desktop enables various capabilities for a developer to more easily work with Kubernetes. We would like to cover that with documentation

### Describe the solution you'd like

A new Kubernetes section on the documentation.
Content on:

- [x] Using Kind to setup a local kubernetes environment https://github.com/containers/podman-desktop/pull/1998
- [x] Building an image, and testing it in Kubernetes https://github.com/containers/podman-desktop/pull/2302
- [ ] Generating Kubernetes Manifest https://github.com/containers/podman-desktop/issues/3223
- [ ] Playing Kubernetes YAML https://github.com/containers/podman-desktop/issues/3224
- [x] Viewing and changing current Kubernetes Context https://github.com/containers/podman-desktop/pull/2303
- [x] Deploying to Kubernetes https://github.com/containers/podman-desktop/pull/2026
- [x] Configuring access to Kubernetes clusters https://github.com/containers/podman-desktop/pull/2486

**Comment by themr0c** [comment]
For the "Building an image and testing it on Kubernetes" story:
* Aborting a build: https://github.com/containers/podman-desktop/issues/1655

**Comment by afbjorklund** [comment]
The current documentation is very specific to "kind", rather than for generic Kubernetes

This means most of it needs to be duplicated, when adding another provider like "minikube"

**Comment by themr0c** [comment]
Closing this very generic issue. Next content to be addressed in more specific issues.
