### ISSUE TITLE
Kind: Indicates images loaded into Kind in Images page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1450]
### Is your feature request related to a problem? Please describe

Images loaded in a Kind cluster should be visible in the list of images.

### Describe the solution you'd like

Images displayed in the images pages should display images loaded into kind clusters with the label on the kind cluster. 

### Describe alternatives you've considered

**Comment by benoitf** [comment]
so while the `kind load docker-image` can't be used we can use the `kind load image-archive` command

Podman Desktop can achieve what is performed there https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/load/docker-image/docker-image.go using REST API of the container engines.

(sanitize image, tag, dump to a tar file, etc)

**Comment by afbjorklund** [comment]
You can use `crictl` (over `podman exec`) for this, then it would also work when you start supporting CRI-O for the cluster...

```
podman exec kind-control-plane crictl images --output json
```

```json
    {
      "id": "sha256:221177c6082a88ea4f6240ab2450d540955ac6f4d5454f0e15751b653ebda165",
      "repoTags": [
        "registry.k8s.io/pause:3.7"
      ],
      "repoDigests": [
      ],
      "size": "311278",
      "uid": {
        "value": "65535"
      },
      "username": "",
      "spec": null,
      "pinned": false
    }
```

Alternatively if you only want images (and pods) I think they might be available over `kubectl` as properties of the node?

```
kubectl get node kind-control-plane -o json | jq .status.images
```

``` json
  {
    "names": [
      "registry.k8s.io/pause:3.7"
    ],
    "sizeBytes": 311278
  }
```

**Comment by afbjorklund** [comment]
The documentation is slightly misleading about this:
> Kind does not enable you to list loaded images.

It is true that kind makes it _hard_ for you to list images...
* https://github.com/kubernetes-sigs/kind/issues/2425

----

But it is not impossible. See above (`crictl images`), and also:

https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

If you have multiple nodes, you need some kind of for loop...

If you need more image details, you can use `crictl inspecti`.

**Comment by afbjorklund** [comment]
The images from the kubernetes cluster should probably only be properties on the node, not listed under "images".

When working with kubernetes (as opposed to with containers), they don't really add anything and can be hidden.
