### ISSUE TITLE
Docs: Compose Support

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1451]
### Is your feature request related to a problem? Please describe

Documentation on the support of Compose with Podman Desktop

### Describe the solution you'd like

We should have documentation on the support of Compose provided by Podman Desktop
- [ ] How does it work
- [ ] How to enable/disable
- [ ] How does it work for a user who already have Compose on his environment
- [ ] How Compose will get updated

**Comment by cdrage** [comment]
` How Compose will get updated` = we don't support this yet and we are still having discussions whether we ship the compose CLI with podman desktop (@benoitf is implementing that)

But I've opened up a PR with documentation to answer all the other questions @slemeur : https://github.com/containers/podman-desktop/pull/1550
