### ISSUE TITLE
allow extensions to submit telemetry events

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1455]
### Is your enhancement related to a problem? Please describe

extensions could contribute additional telemetry metadata

For example if there is something that is failing, it could report the error

### Describe the solution you'd like

adds extra telemetry API in the extension list

**Comment by deboer-tim** [comment]
This API should also allow an extension to tell if the user has accepted the telemetry agreement. Why? OpenShift Local extension uses the CRC CLI, which sends its own telemetry to the same backend as Podman Desktop. The same telemetry agreement applies (same backend, same privacy agreement, etc) so only a single acceptance is required, but without knowing if someone has accepted it the extension needs to prompt again.

**Comment by gbraad** [comment]
Since there is a telemetry prompt already, all we need if a way to see if this has been given a consent.

**Comment by benoitf** [comment]
telemetry is a configuration so extension can already know if it has been accepted or not

**Comment by slemeur** [comment]
That works when the telemetry events are built with the same tool/source and with the same privacy agreement. 
There could be a need in the future, where extensions will point to a different telemetry destination and in this case the consent might be needed as well - but I believe this is something we can work on later on.

At the moment, extensions need the ability to submit their own events 👍 as the issue has been described.
