### ISSUE TITLE
Search (filter) bar support for type-ahead/code assist

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1457]
### Is your enhancement related to a problem? Please describe

Most filtering is based on simple things like the name of an image, which container engine it runs on, or one of the last few terms I used. It should be easy to get to these common things without typing the full search term out.

### Describe the solution you'd like

Type ahead or code assist options for common terms people are likely to use. The user should still be able to type an entire term like today, but also:
- If the search term has focus, the past few terms I've used should be visible for quick selection.
- If I start typing the top few likely terms should be visible (i.e. recent history + common search items, filtered by what I've typed so far).

For example, if you start typing 'po' there should be a quick action (e.g. tab) to complete it to 'podman'.

**Comment by benoitf** [comment]
closing as won't fix, no vote/new comment in 1+ year
