### ISSUE TITLE
Release note automation

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1458]
### Is your feature request related to a problem? Please describe

Currently, release notes are generated after a sprint. Someone needs to manually pull the list of PRs, decide on text and/or images for each one, then clean up or organize them. This is time consuming and disconnected since it isn't done at the time of each PR, and puts pressure on doing this quickly so that we can declare a release.

### Describe the solution you'd like

Automation! We should allow a tagged section to be created in any PR that contains the text and optional image for a release note, along with a GitHub action that pulls each of these for the current sprint together in one document.

Some additional requirements:
- Release notes are often grouped, maybe we can do this by label or tagging.
- Add a section to the PR template.
- We need a simple way to opt out ('no release note necessary for this').
- Some PRs (chores? any others? maybe under a certain # lines?) clearly don't need release notes and can be ignored.
- PRs that don't contain a release note and haven't opted-out should fail PR check.
- We need to be able to update, e.g. add another comment or edit to fix a typo or improve the note.
- A simple workflow figured out. e.g. I assume PR author is responsible for doing this, but can committers override?

To start with the purpose is to build this into our workflow and automate 90% of the work of creating release notes, leaving just cleanup or consistency fixes. Once we've proven that this works we could take it a step further and fully automate the process.

**Comment by lstocchi** [comment]
FYI - in the adapters team me and jeff worked on a gh action (`lstocchi/simple-conventional-changelog@0.0.11`) to automate the creation of the release note (example of the outcome https://github.com/redhat-developer/intellij-tekton/releases/tag/1.1.0 ). Everytime a new tag was created, it triggered the workflow that fetched all commits, grouped them by tag, create a  new release and append the content to it. 
We also had a sub-tag (skip-release) to define which commit not to include (e.g `chore(skip-release):`, `whatever(skip-release)`).

**Comment by deboer-tim** [comment]
Excellent, I guess we know who to assign when we prioritize this. ;-)

**Comment by benoitf** [comment]
also please note that `Release Notes` are different than a `Changelog`
