### ISSUE TITLE
Error message text of the detection check is not well aligned in the message box

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1466]
### Bug description

Error message text is misaligned. 

### Operating system

Windows 10 Professional 

### Version

0.11.0

### Steps to reproduce

1. install podman desktop on windows without podman
2.  run it
3. Open View detection check

**Comment by odockal** [comment]
![podman-error-message](https://user-images.githubusercontent.com/19164299/219025650-9efa047a-3bbb-4ed5-9f9d-4ffd9a3febdc.png)

**Comment by rohit-rambade** [comment]
Hello @odockal I'll like to work on this

**Comment by benoitf** [comment]
closing as won't fix
