### ISSUE TITLE
Display cluster context for Kubernetes pods

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1467]
### Is your enhancement related to a problem? Please describe

As part of #1263 Kubernetes Pods are displayed in the Pods window. It would be nice to add context relative to Kubernetes:

- namespace
- context ?

### Describe the solution you'd like

Augment the displayed information for pods with this Kubenetenes specific information

**Comment by cdrage** [comment]
@jeffmaury At the point that were starting to add namespaces / context to the screen. I think it may be time to move the Kubernetes information into its own tab as we'll quickly start filling it with *a lot* more information.

**Comment by benoitf** [comment]
this issue is probably a dependency of https://github.com/containers/podman-desktop/issues/1340

**Comment by deboer-tim** [comment]
We (you?) recently added the context, and separate design for Kubernetes pages is starting. I think this is either completed or redundant at this point - ok to close?

**Comment by jeffmaury** [comment]
OK to close as it has been implemented would be good to add the link to pr

**Comment by deboer-tim** [comment]
Fixed via PR #2634, closing.
