### ISSUE TITLE
Increase code coverage with adding another batch of unit tests

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1476]
### Is your enhancement related to a problem? Please describe

Code coverage with unit tests is low and we would like to increase coverage.

### Describe the solution you'd like

Consider simple classes in the codebase and add unit tests for such classes. Get familiar with vitest testing framework.

**Comment by benoitf** [comment]
closing as we're now asking people to write unit tests when submitting new code/bug fixes
