### ISSUE TITLE
docs: podman-mac-helper is not installable from brew

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1477]
### Bug description

documentation is saying that podman-mac-helper can be installed from brew
but it's installed with Podman

so the install step should be removed
https://podman-desktop.io/docs/migrating-from-docker/using-podman-mac-helper#procedure

there is no
```
brew install podman-mac-helper
```

### Operating system

macOS

### Version

0.11.0

**Comment by tomaszkrzyzanowski** [comment]
Why removing instead of adding it to Homebrew? What is the point?

**Comment by kquinsland** [comment]
> Why removing instead of adding it to Homebrew? What is the point?

It's already in Homebrew, but you have to:

```shell
❯ brew install podman
```

In addition to 

```shell
❯ brew install podman-desktop --cask
```

If you install _just_ the `-desktop` you get the nice GUI to manage things but the docker helper and the VM ... etc won't be setup until you install `podman`. The Desktop app will DL/open the `pkg` installer for you if you don't `brew...` it ahead of time.
