### ISSUE TITLE
Registry UI layout issues

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#148]
### Bug description

The new registry UI has some issues with overlapping tiles and layout, especially when width is at a premium.

e.g. here the tiles overlap and X buttons are not accessible:
<img width="546" alt="Screen Shot 2022-05-16 at 9 20 00 AM" src="https://user-images.githubusercontent.com/19958075/168602449-25cdace4-8f50-4209-84bc-c5f708953854.png">

Here the same problem, plus second row is indented:
<img width="302" alt="Screen Shot 2022-05-16 at 9 21 19 AM" src="https://user-images.githubusercontent.com/19958075/168602475-a197b9bc-c30c-4bae-8a31-e8768a9fdfda.png">

Also, no right margin.

### Operating system

MacOS 12.3.1 M1

### Version

next (development version)

**Comment by benoitf** [comment]
hello, do you reproduce it with https://github.com/containers/podman-desktop/releases/tag/v0.0.202205160640-12bda29 ?

**Comment by deboer-tim** [comment]
Yes, I just pulled the latest build.
