### ISSUE TITLE
Selection highlight broken when selection an extension

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1480]
### Bug description

If i click on an extension, another entry is highlighted. The selection works fine, it's a problem with the ui.
it can be a new game, catch the extension 😆 

![extensions_selection_broken](https://user-images.githubusercontent.com/49404737/219106084-753fcb6b-6a7d-457f-90b5-23fb0e22acd5.gif)

### Operating system

Windows 10

### Version

next (development version)

### Steps to reproduce

1. go to the extensions list
2. click on entry and see if another one gets highlighted

**Comment by benoitf** [comment]
do not reproduce it now, closing
