### ISSUE TITLE
After installing, "Podman Desktop was not able to find an installation of Podman"

### ISSUE THREAD

**Issue by dudash** [containers/podman-desktop#1485]
### Bug description

I did a fresh install of Podman Desktop today on a new Mac (Monterey 12.6.3). Podman CLI didn't exist either so I clicked the button from the UI and installed it from the Podman Desktop. The install completed successfully, but the UI didn't fully recognize this state change and give me an option to init/start the machine. 

Check the screenshot below to see the weird state where it knew podman was installed but also said it wasn't found:

<img width="1052" alt="Screen Shot 2023-02-15" src="https://user-images.githubusercontent.com/116840/219173651-15694400-bffb-4890-9d9e-87d68795bb03.png">

### Operating system

macOS Monterey 12.6.3

### Version

0.11.0

**Comment by odockal** [comment]
@dudash Hello there, sorry for getting into this that late. We have proposed a fix and verified it recently. Could you please try to install newer version (ideally 1.3.1) of podman desktop to see if that helps? Thx.

**Comment by odockal** [comment]
I am closing the issue now as we should have it fixed. It was also mentioned in #1498 and fix should have been merged for both. @dudash Feel free to reopen or comment if you encounter the issue again.

**Comment by dudash** [comment]
this morning I deleted podman desktop and podman cli, then did a clean install of 1.3.1, then podman from the UI.
Everything looks good, nice work!
