### ISSUE TITLE
Docs: Create document regarding release process

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1497]
### Is your enhancement related to a problem? Please describe

No documentation on how to compile / make a release

### Describe the solution you'd like

Should have a short document outlining the release process / any changes we need to make externally as well (brew, chocolately, etc.)

**Comment by benoitf** [comment]
I've created a RELEASE.md this morning when cutting v0.12 release so other people should perform releases.
PR will happen soon :-)
