### ISSUE TITLE
podman dashboard still proposes to update after podman installation

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1498]
### Bug description

I had Podman 4.4.0 installed:

![image](https://user-images.githubusercontent.com/695993/219419835-e619e74e-5b99-4ca8-9ab1-392d388fd9ba.png)

So I clicked on Update to 4.4.1 and once the installation is done, the page is updated but the Update button is still there

![image](https://user-images.githubusercontent.com/695993/219420295-78027dad-728b-4585-9149-06a4cb33d2cc.png)

### Operating system

Win11 Pro

### Version

0.12.0

**Comment by benoitf** [comment]
I think https://github.com/containers/podman-desktop/issues/1485 is around the same issue (maybe not) but working on a fix for the other one we should check also #1485
