### ISSUE TITLE
How do I build an install this package on a Linux box so that I can play with it?

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#15]

**Comment by benoitf** [comment]
I would be interested to know what is your favorite way of installing it on Linux ? For now there are .tgz

I setup CI yesterday, so it's publishing some artifacts https://github.com/containers/desktop/releases

Linux version is the .tgz 

Windows and macOS have been tested but not yet Linux

So I would wait a little as it may probably not work as it's checking for socket on the host right now

**Comment by benoitf** [comment]
@rhatdan it's now possible to try it on Linux
Go on latest release
https://github.com/containers/desktop/releases/latest

Download the .tar.gz, unpack it and launch 'container-desktop' binary from the unpacked folder

example of direct link: https://github.com/containers/desktop/releases/download/v0.0.202203141438-918397d/container-desktop-0.0.202203141438-918397d.tar.gz
