### ISSUE TITLE
Notify the user after an update

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1503]
### Is your enhancement related to a problem? Please describe

Currently, updates are automatic and happen on the first restart after a release. Even once we release #395 and let the user know that a new release is available, there is no indication that the update was successful (or that it even happened) without looking for the release number (if you remembered the previous one) or noticing a change.

### Describe the solution you'd like

The first time starting on a new release (other than the initial install) there should be a "welcome to release 0.x" notification, ideally along with a link to our release notes.

**Comment by benoitf** [comment]
0.12 does not have yet the notification
It's not yet merged

**Comment by deboer-tim** [comment]
Good catch, fixed the description.
