### ISSUE TITLE
Improve error feedback when pulling images

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#151]
### Is your enhancement related to a problem? Please describe

The ability to pull an image is awesome. However, error feedback when something goes wrong is really poor, e.g.:
`initializing source docker://abc/xyz:latest: reading manifest latest in docker.io/abc/xyz: manifest unknown: manifest unknown` (I didn't specify a tag, and the image doesn't have a 'latest')
or:
`initializing source docker://xyz/def:latest: reading manifest latest in docker.io/xyz/def: manifest unknown: manifest unknown` (not a multi-platform image; doesn't have arm platform)
or:
```
initializing source docker://notanimage:latest: reading manifest latest in docker.io/library/notanimage: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
 (image doesn't exist)
```
I tried this directly from the terminal to confirm the poor error output is 'normal' for podman. What's especially troubling is cases like the last one that are flat out wrong and will cause users to check authentication instead of fixing a typo.

We need to bring this up with the podman team (I will), but I'm worried similar behaviour could exist in other container engines as well, and the user will have problems and view desktop as the problem instead of the underlying engine. I'm wondering if we should be doing our own inline validation to provide consistently useful feedback to the user.

### Describe the solution you'd like

Error messages should be helpful and indicate to the user what the problem might be or how to fix it.

**Comment by benoitf** [comment]
@deboer-tim I think here idea (but not yet implemented) and as you suggested is to fetch images in registry and provide completion as long as we type to validate

**Comment by mairin** [comment]
I went to pull an image today and had copied the url from the quay page:

`podman pull quay.io/smissaertj/fedora_wordpress`

Of course I should have trimmed the `podman pull` bit but i wasn't paying attention... I got an error about this on the "Pull Image from a registry" page:

`Could not connect to Podman: (HTTP code 500) server error - normalizing image: normalizing name for compat API: invalid reference format`

I realized the mistake and removed the `podman pull` bit and tried again, and it worked, but the error message never cleared, so I didn't realize the pull actually worked and got into a bit of a confused state for a couple of minutes there.

Probably, if the user tries something differently a second time, it's better to clear the old error?

![Screenshot from 2023-05-29 14-29-34](https://github.com/containers/podman-desktop/assets/799683/af969396-e877-4059-8dc5-8e41093571fd)
