### ISSUE TITLE
Kubify: Add additional step for publish the images on a registry

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1510]
### Is your enhancement related to a problem? Please describe

When working a developer want/need to test an image built locally on a remote kubernetes environment, the developer may require to publish the image on a registry.

### Describe the solution you'd like

It would be nice that during the kubify flow, the developer is getting asked about the publication of the image:
- Podman Desktop would detect if the image is already available on a registry (and if there is a tag for it)
- if not, then propose to the developer to tag the image and publish it on a registry

The developer should have the ability to also pick an choose which registry to use.
An option to automatically push the image could also be added.

**Comment by cdrage** [comment]
Ran into this problem again.

I want to be able to build and pull an image, and then push it to the registry within the Image tab of Podman Desktop.
