### ISSUE TITLE
Start the UI minimized 

### ISSUE THREAD

**Issue by orpiske** [containers/podman-desktop#1515]
### Is your enhancement related to a problem? Please describe

On MacOS, I am always frustrated when I login on my account and I have to close the Dashboard UI. 

### Describe the solution you'd like

Please, can you add an option so it does not show the Dashboard UI on start up / when I login?

**Comment by benoitf** [comment]
Hello @orpiske with 0.12 version it should behave like this
https://github.com/containers/podman-desktop/issues/868

**Comment by orpiske** [comment]
> Hello @orpiske with 0.12 version it should behave like this #868

Thank you!!! 👍
