### ISSUE TITLE
Add documentation links for CRC extension

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1519]
### Is your enhancement related to a problem? Please describe

We need to add link for CRC documentation/installation in CRC dashboard widget.
Derived from  https://github.com/containers/podman-desktop/pull/1487 PR

### Describe the solution you'd like

Something like 
<img width="1049" alt="Screenshot 2023-02-16 at 10 36 09" src="https://user-images.githubusercontent.com/929743/219313141-685c4069-7ea1-4136-bbc1-78cc86205985.png">

But with proper links, when we decided which one we should use.

**Comment by evidolob** [comment]
cc @gbraad

**Comment by deboer-tim** [comment]
The OpenShift Local extension was moved to https://github.com/crc-org/crc-extension, and these links have been added.
