### ISSUE TITLE
Poor progress pulling images

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#152]
### Is your enhancement related to a problem? Please describe

When pulling an image the progress output is pretty meaningless and you have no idea how long it will continue:
```
Pulling fs layer
Pulling fs layer
Download complete
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Download complete
Download complete
Downloading
Downloading
Downloading
Download complete
Pulling fs layer
Pulling fs layer
Download complete
Pulling fs layer
Download complete
Downloading
Pulling fs layer
Download complete
Download complete
Downloading
Download complete
Downloading
Download complete
Pulling fs layer
Download complete
Download complete
```

I tried this directly from the terminal and podman output is slightly better since it outputs less lines and you can at least see different layers being pulled:
```
Resolving "zhengzepeng/openliberty" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/xyz/abc:1.8...
Getting image source signatures
Copying blob sha256:0d374f860fdc126617a75927532e035a42dfdc2b26fb22410ebc99562fa8e225
Copying blob sha256:d4ba87bb7858f0dd4a60003f011338f3a58b87d0add985652856007fe5ca5034
Copying blob sha256:0ce33c7cb386794b97371bf23d6db512379e04036ae033b076a599f51f6416b6
...
Copying config sha256:ca09cd9d93a7ad58fcda51641a76885eeaefcae3ecf20222b52d58a3b6b79762
Writing manifest to image destination
Storing signatures
ca09cd9d93a7ad58fcda51641a76885eeaefcae3ecf20222b52d58a3b6b79762
```

### Describe the solution you'd like

In an ideal world I'd love a little graphic that appeared showing all the layers as bars, which filled up as they downloaded and then changed color when complete. :)

In a more realistic world, can we ask podman for better output?

**Comment by benoitf** [comment]
here there are several people asking for progress events
https://github.com/containers/podman/issues?q=is%3Aissue+is%3Aopen+push+progress

**Comment by benoitf** [comment]
about the output, yes we have IDs to match the line to update but still no percentage from podman

**Comment by deboer-tim** [comment]
So we get a list of IDs and then they just complete with no progress in between? I think we could still build a simple UI that shows the list of layers and marks them complete (e.g. green or checkmark) to start providing some progress, and always add in completion percentages or size as we get them later.
