### ISSUE TITLE
add contribution points for menus

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1523]
### Is your enhancement related to a problem? Please describe

An extension should be able to contribute menu items for example for a container that will appear in the container list or in the container details page.

### Describe the solution you'd like

We should have a way to declare those contributions in the package.json of an extension

like

```json
{
  "contributes": {
    "menus": {
      "dashboard/image": [
        {
          "command": "my.scanner",
        }
      ]
    }
  }
}

```

so the scan item will be added on the image list view or image details page.

we could have like `dashboard/image` and `dashboard/container` (or a better name for those)

**Comment by jeffmaury** [comment]
I was thinking something similar but from the API POV.
So an extension could register an action linked to a command that may span several contexts.

Something like: RegisterAction(commandID, contextCallback) where contextCallback is a method that takes the context (ex dashboard/containers) as input and return a boolean

**Comment by benoitf** [comment]
I think it would be like for vs code, the command will receive as argument something to identify the resource based on the context 


so you register the command, expose the menu addition and command in package.json, then for example if you contribute to a container you'll probably receive a resource targeting the container ( like container id, engine Id)
Either a json object or an uri (like the one we use in navigating)
