### ISSUE TITLE
add contribution for icons

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1525]
### Is your enhancement related to a problem? Please describe

an extension should be able to provide icons that can be used

For example inside a status bar element (or somewhere else)

### Describe the solution you'd like

extension should define a new contribution in the package.json file:

```
{
  "contributes": {
    "icons": {
      "my-icon": {
        "default": {
          "fontPath": "./iconfile.woff",
          "fontCharacter": "\\E001"
        }
      }
    }
  }
}

```

to generate font file from SVG file, extensions can use tools like
https://github.com/itgalaxy/webfont#usage

**Comment by deboer-tim** [comment]
Can we just directly support SVGs? This sounds like an extra packaging step for most extensions.

**Comment by benoitf** [comment]
it's doing a mimic of VS Code extensions
the reason is that you should be able to use `Here is my $(iconName)` or `my $(icon) appears there`

It'll display the message and the font using the exact same size. And a font can embeds all icons
https://code.visualstudio.com/api/references/contribution-points#contributes.icons
https://code.visualstudio.com/api/references/icons-in-labels#icons-in-labels

**Comment by deboer-tim** [comment]
Sorry, that makes sense. For some reason I thought you were including something like the extension icon (e.g. equivalent would be https://code.visualstudio.com/api/references/extension-manifest)
