### ISSUE TITLE
podman desktop 0.12.0 is slow and stuck - Linux

### ISSUE THREAD

**Issue by zakaria-chahboun** [containers/podman-desktop#1533]
### Bug description

I just installed the latest version of podman and it's taking a long time to start up or work, consuming a lot more resources than the previous version. As you can see in the screenshot below, it seems to be stuck:

![image](https://user-images.githubusercontent.com/18173275/220604495-d9d0f014-f0f9-4fe4-bfd4-8ca2db661d2e.png)

Also, it takes time to quit, and if I check the system monitor, the child process still running even if I close it.
![image](https://user-images.githubusercontent.com/18173275/220605007-767aafd0-1184-4dc1-9d6f-1b66f3e7b5d6.png)

> It's good to use https://wails.io/ instead of electron since podaman is created with Go. Please take a look at wails project!
 

### Operating system

Pop!_OS 22.04 LTS x86_64 

### Version

0.12.0

### Steps to reproduce

Run it on a new Ubuntu distro or based on it like Pop_os

**Comment by lstocchi** [comment]
maybe https://github.com/containers/podman-desktop/issues/1435 could be the problem  .
@zakaria-chahboun could you please try by running the pre-release at the bottom of https://github.com/containers/podman-desktop/actions/runs/4232352553 ?

**Comment by zakaria-chahboun** [comment]
@lstocchi 
Yes i tried it!
The dashboard may take some time to start up and be ready for use, but once it is up and running, it works without any lag.

Can you tell me if you've taken a look at the [WailsApp](https://wails.io/) Project?

**Comment by lstocchi** [comment]
> Can you tell me if you've taken a look at the [Whiz](https://wails.io/) Project?

@benoitf i guess it's for you

**Comment by benoitf** [comment]
I already looked at Wails, NeutralinoJS, React Native, Tauri, etc.

Then, it's not only about the 'go' vs 'javascript'

We've extensions/plugins with fine-grained javascript API, we want to be compliant with the Docker Desktop extensions as well (UI extensions)
There is all the hidden stuff. Automation about the code signing for Windows, for macOS, generating installers, specific packages for all arches, specific package managers etc that is done by default using electron.
This is why there are still most of the apps that are using electron.

**Comment by benoitf** [comment]
For the specific case of Wails, a quick overview shows that it doesn't implement (and also other lot of other stuff missing)
- https://github.com/wailsapp/wails/issues/1521
- https://github.com/wailsapp/wails/issues/1178

which are 2 pre-requisites by Podman Desktop

**Comment by benoitf** [comment]
fixed as a dup https://github.com/containers/podman-desktop/issues/1435
