### ISSUE TITLE
Containers: Ability to edit containers / update entrypoint after creation

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1534]
### Is your enhancement related to a problem? Please describe

After creating the container, I'd like to update the ports, entrypoints, volumes, etc.

### Describe the solution you'd like

UI / ability to edit the container after creation / update it.

**Comment by benoitf** [comment]
It's a dup of https://github.com/containers/podman-desktop/issues/958

**Comment by Basssiiie** [comment]
Hi @benoitf , the referenced issue has been resolved but the issue described here was not part of the fix, as far as I can see. Or am I missing something? Would it be possible to re-open this issue?
