### ISSUE TITLE
Pods: Show engine label when there is more than one provider (Podman vs Kubernetes)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1549]
### Is your enhancement related to a problem? Please describe

When viewing the Pods, I see all of my pods displayed from Kubernetes, but there is no label that they are from Kubernetes.

![Screenshot 2023-02-23 at 2 00 26 PM](https://user-images.githubusercontent.com/6422176/221005014-66bafc84-bca4-415b-8ba0-7150edd77a5b.png)

### Describe the solution you'd like

We should always show that it's from Kubernetes even if it's the only engine being displayed.

**Comment by mairin** [comment]
Idea to display a short name for the active k8s context in the status bar.... maybe on hover or click you could get the full k8s context (which can be quite long / complex for openshift local or devsandbox)

**Comment by deboer-tim** [comment]
See issue #2309 for that.

**Comment by slemeur** [comment]
We are already showing if the pod is running in podman or kubernetes. But unfortunately, if you have only one pod (or pods running into the same provider), it does not indicate where those are running. 
We should be indicating the provider, if there are multiple kubernetes (and pods) providers
But we need to differentiate which provider too: #2154
