### ISSUE TITLE
Pushing images feedback

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#155]
### Is your enhancement related to a problem? Please describe

- The title "Pushing image" should probably be something like "Push image to a registry" to match image pull dialog.
- Pull has a button to manage registries, push doesn't. Although it's maybe less likely to need it during push, I had a problem and needed to manage mine and I think it would be good from a consistency standpoint.
- The pull image screen is inline in the window, but pushing is a separate 'dialog'. I think I prefer the inline screen, which also gives a little more screen real estate.
- The 'Push image' button animation goes over the text (see below). Matching the wide button on the pull screen would solve this.

<img width="286" alt="Screen Shot 2022-05-16 at 10 15 22 AM" src="https://user-images.githubusercontent.com/19958075/168613252-fddfe6be-5751-4179-bc72-460e050bd97e.png">

### Describe the solution you'd like

Suggestions were inline in the description.

**Comment by benoitf** [comment]
I did like A/B testing for modal/screen for pull/push, it seems you prefer inline

**Comment by deboer-tim** [comment]
Sorry, I don't follow - what do you mean by A/B testing in this context? To me this screen was 90% of the UI, so seemed better to just make it 100% and be consistent between the two.
