### ISSUE TITLE
Error in Kube tab when pod only has an infrastructure container

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1555]
### Bug description

If a pod only has an infrastructure container, clicking on its Details > Kube tab is blank and the following error appears in the log:
`Uncaught (in promise) Error: (HTTP code 500) server error - generating YAML: pod 2fd115034494dac008f911a0e23f6bc8a56654dcac57b7fe1bbd013cc772b19b only has an infra container `

### Operating system

macOS 13.2 M1

### Version

next (development version)

**Comment by benoitf** [comment]
closing, no upvote or comment in the last year
if it becomes a major issue, we can reopen
