### ISSUE TITLE
Ability to edit registry

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#156]
### Is your enhancement related to a problem? Please describe

I tried to push from within desktop and it failed (looked like credentials). I tried from the command line since I had successfully pushed from there last week and it worked.

In desktop I assumed the password wasn't correct (is the docker.io registry automatic? does it reuse password from podman cli?) so I had to:
- exit the push screen
- go to registry preferences
- couldn't confirm password or edit, so had to delete the existing registry and add it again

After this the push worked.

### Describe the solution you'd like

I've already commented in another issue on getting to the registry preferences from the push dialog. What I'd like is the ability to edit a registry and change the username or password so I don't have to delete it and create a new registry.

If we can show the password, maybe we can add a Show Password button too?

**Comment by benoitf** [comment]
Fixed by https://github.com/containers/podman-desktop/pull/198
