### ISSUE TITLE
Current main branch broken when starting it on linux

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#1584]
### Bug description

When starting the current main branch on Linux using `yarn watch` Podman Desktop results in a white screen

![image](https://user-images.githubusercontent.com/49404737/222085609-a8e3641b-cb36-476b-b3a5-5d146a2b1634.png)

### Operating system

fedora 37

### Version

next (development version)

### Steps to reproduce

1. execute yarn watch on the main branch 

### Relevant log output

```shell
(node:16196) UnhandledPromiseRejectionWarning: HttpError: fetch failed
    at /podman-desktop/node_modules/@octokit/request/dist-node/index.js:110:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:16196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by benoitf** [comment]
@lstocchi what is your node version ?

**Comment by lstocchi** [comment]
16.19.0

**Comment by benoitf** [comment]
do you have the same error with nodejs18 for example ?

**Comment by lstocchi** [comment]
No, same issue with
```
Now using node v18.14.1 (npm v9.3.1)
```

**Comment by benoitf** [comment]
so first issue, I think we're missing a catch block there:
https://github.com/containers/podman-desktop/blob/main/extensions/kind/src/kind-installer.ts#L87-L91

**Comment by benoitf** [comment]
then it would be interesting to know the root cause of the exception
From what I'm reading it could be a network/dns issue

**Comment by lstocchi** [comment]
The problem is `<InlineSVG src="{contribution.icon}" width="24" height="24" class="mr-4" />`. By removing this, everything works as before.

**Comment by lstocchi** [comment]
can't we just have `<img src="{contribution.icon}"`? Any reason to use the InlineSVG component?

**Comment by benoitf** [comment]
can you remove the whole node_modules folder and do again a `yarn` step ?

**Comment by lstocchi** [comment]
Same broken view after
```
delete node_modules
yarn cache clean/install/build/watch
```

**Comment by benoitf** [comment]
in your screenshot anyway, there is still an Unhandled error in Octokit usage

**Comment by lstocchi** [comment]
yeah but it's not the cause of my issue. Opened a new PR for that -> https://github.com/containers/podman-desktop/pull/1587

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/1586
