### ISSUE TITLE
Add 'env' extension API

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1585]
### Is your enhancement related to a problem? Please describe

Most of extensions uses some copied/similar code, like OS type detections( `isWindows`, `isMac`, `isLinux` functions)
and code which allow to run CLI binary’s.

I propose to add new `env` namespace in to extension API, which will contain useful function to interact with environment.

### Describe the solution you'd like

New namespace could look like: 

```typescript

  export interface Dict<T> {
    [key: string]: T | undefined;
  }

  export interface RunOptions {
    /**
     * Environment variables
     */
    env?: Dict<string>
  }


  export interface RunResult {
    exitCode: number;
    stdOut: string;
    stdErr: string;
  }

  export namespace env {
    export function isMac(): boolean;
    export function isLinux(): boolean;
    export function isWindows(): boolean;

    /**
     * Run provided command, return object which contains exit code, stdout and stderr content,
     * douse not reject if exit code not 0
     * @param command the command to execute
     * @param args the command arguments
     * @param options options, like environment variables
     */
    export function runCliCommand(command: string, args: string[], options?: RunOptions): Promise<RunResult>;

    /**
     * Execute provided command, return stdout content, reject promise if exit code not 0.
     * @param command the command to execute
     * @param args the command arguments
     * @param options options, like environment variables
     */
    export function execCliCommand(command: string, args: string[], options?: RunOptions): Promise<string>;
  }

```

### Describe alternatives you've considered

Instead of having separate functions, for each OS, we could have one function `getPlatform()` which return enum value:

```typescript

export enum Platfrom {
 WINDOWS,
 MACOS,
 LINUX,
}
export function getPlatform(): Platfrom;
```

**Comment by evidolob** [comment]
cc @benoitf @jeffmaury @gbraad

**Comment by benoitf** [comment]
env for the helper is?? looks fine
but maybe for run we need an exec namespace (docker desktop extensions have `exec` namespace)

**Comment by benoitf** [comment]
and also think it's a good idea I think it was discussed on several github issues, so thanks for filing the issue

**Comment by jeffmaury** [comment]
Regarding the run/exec helpers there are extensions that needs to specify PATH augmentations (kind, compose,...) so I think it should be reflected in the options

**Comment by gbraad** [comment]
@jeffmaury Is this something that can be scheduled? Although, at the moment, @evidolob is waiting on #1487 to be merged. I prefer to unblock him first.
