### ISSUE TITLE
Build Dockerfiles with any name

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#16]
**Is your feature request related to a problem? Please describe.**
Most dockerfiles have the default name of Dockerfile, but some don't. Need to add support for building files like build.Dockerfile or myproject.Dockerfile.

**Describe the solution you'd like**
The current UI and defaulting to simple case is good, it just needs a way to override and select a specific file.

**Comment by rhatdan** [comment]
This tool should default to Containerfile as well. Please don't use the Docker adjective unless absolutely necessary.
