### ISSUE TITLE
Settings/Registry Username/Password not aligned

### ISSUE THREAD

**Issue by nick-adair** [containers/podman-desktop#1603]
### Is your enhancement related to a problem? Please describe

The username and password fields are not aligned with the form.

![image](https://user-images.githubusercontent.com/66796598/222811804-7713150c-bdcb-442e-a263-9604ce08df32.png)

### Describe the solution you'd like

Align username and password elements to form

### Describe alternatives you've considered

None

### Additional context

Windows 11 Pro, Build 10.0.2261
Podman Desktop 0.12.0

**Comment by deboer-tim** [comment]
Thanks for the report - alignment fixes have been done to this page, PRs were linked to other issues. Should now be fixed.
