### ISSUE TITLE
arm64/aarch64 Version for Linux!

### ISSUE THREAD

**Issue by sallyhaj** [containers/podman-desktop#1606]
### Is your feature request related to a problem? Please describe

Due to the Linux well supportive of containers, I think the need of getting such an app "podman-desktop" for the main architectures would bean amazing idea, especially if we consider ARM64 as servers/SBCs.

### Describe the solution you'd like

Adding an ARM64 architectures version for application.

**Comment by benoitf** [comment]
Hello @sallyahaj 

you can grab an arm64 flatpak binary from https://flathub.org/apps/details/io.podman_desktop.PodmanDesktop
we're building there both amd64 and arm64 versions

**Comment by sallyhaj** [comment]
I installed the flatpak binary as your suggestion, and it's working fine, thank you so much @benoitf
