### ISSUE TITLE
Unexpected v2 completion into image url

### ISSUE THREAD

**Issue by jrmanisme** [containers/podman-desktop#1612]
### Bug description

Trying to pull an image into podman desktop I can t and get this issue:
Setting in the field:
repository.ddd.xxxxx.net/docker-dbaas/dbaas-python:1.0.1

The pull is failing with this error
initializing source docker://repository.ddd.xxxxx.net/docker-dbaas/dbaas-python:1.0.1: pinging container registry repository.ddd.xxxxx.net: Get "https://repository.ddd.xxxxx.net**/v2/**": dial tcp: lookup repository.ddd.xxxxx.net: Temporary failure in name resolution

There is an unexpected /v2 appearing in the url

Please note that it's doing the same when clicking manage registries and trying to simply login my repo

it's blocking issue I can't pull any image

### Operating system

windows 10 build 19044.2604

### Version

0.12.0

### Steps to reproduce

Not sure you can reproduce but probably you can have a look in your code relating the manipulation of the url for image you probably introduce this string "v2" somewhere for some other good reason and I'm falling in this use case for unknown reason.
My windows system had been installed last week it's not poluted by any other install.
Maybe something should be done in your install so that your function is not completing my url with this "v2"

**Comment by benoitf** [comment]
hello @jrmanisme 

the `/v2` is the REST API of registry https://docs.docker.com/registry/spec/api/#api-version-check

what kind of registry are you using ?

**Comment by jrmanisme** [comment]
Hello,
Thanks for your fast response.
Our repository is an Artifactory but not sure being able providing too much details on it because as a simple user I can't see much more.
I can see my files in a file system format and login an jfrog platform.
Thanks

**Comment by benoitf** [comment]
I found https://www.jfrog.com/confluence/display/JFROG/Using+Docker+V1
and https://www.jfrog.com/confluence/display/JFROG/Using+Docker+V1#UsingDockerV1-MigratingaV1repositorytoV2

Are you trying to pull the image using the command line ?
like `$ podman pull repository.ddd.xxxxx.net/docker-dbaas/dbaas-python:1.0.1`

are you connected to a VPN ?
if that the host of the registry is only resolved with the VPN ?

what happens if you try to do a curl request on `https://repository.ddd.xxxxx.net**/v2` (not from the WSL machine but from your machine)

https://github.com/sakai135/wsl-vpnkit might help depending on the result of the previous attempts

**Comment by jrmanisme** [comment]
I'm not connected to a vpn, the url is resolved by Windows from its dns/nameserver, I don't know exactly what Windows do to resolve the name but it does without issue from any of my browsers.

I'm running from Podman Desktop with the "Podman is running Version 4.4.1"
Clicking images menu, then "Pull an image" button

I set the url "repository.ddd.xxxxx.net/docker-dbaas/dbaas-python:1.0.1" and it fails because it is adding "/v2" like you can see in the logs I pasted.

I understand the difficulties in reproducing this issue but actually maybe if you know it you could describe a bit what is really making Podman Desktop with the url and the reason of this "/v2"

curl https://repository.ddd.xxxxxxx.net/v2
{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}

curl https://repository.ddd.xxxxxx.net <= No issue without /v2
<!doctype html><html lang=en><head><meta charset=utf-8><meta http-equiv=
...
We're sorry but jfrog webapp doesn't work properly without JavaScript enabled. Please enable it to continue.
...
a9e8d1.js></script><script src=/ui/js/app.def1fe3f.js></script></body></html>

On top I manipulate this url since year and never encountered any context where we must set "/v2".

Now I guess I can work without the gui and directly with wsl and command lines. Probably I'll do that at the end.

Thanks

**Comment by jrmanisme** [comment]
For info actually I'm getting the same issue on wsl command line so it's not linked to podman desktop, at least I hope it's not introducing the issue.

docker login docker-dbaas.xxx.dockerhub.ddd.xxxxx.net
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Username: xxxxxx
Password:
Error: authenticating creds for "docker-dbaas.xxx.dockerhub.ddd.xxxxx.net": pinging container registry docker-dbaas.xxx.dockerhub.ddd.xxxxx.net: Get "https://docker-dbaas.xxx.dockerhub.ddd.xxxxx.net**/v2/**": dial tcp: lookup docker-dbaas.xxx.dockerhub.ddd.xxxxx.net: Temporary failure in name resolution
