### ISSUE TITLE
UI: More documentation / information regarding Docker Desktop extensions

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1619]
### Is your enhancement related to a problem? Please describe

The page to install Docker Desktop applications is bare and doesn't contain the following information:

* How do I find the "OCI" image? For example... as a new user, I would actually have to find the image from Docker Hub and then install it via that way, but that's not documented. 

For example, in Docker Desktop I simply type into "search" and it'll appear. 

For Podman Desktop, it's unwritten that we have to actually *find* the image on Docker Hub and install it.

Example:
1. Podman Desktop says to go on the trivy-docker-extension GitHub to install it
2. I go on https://github.com/aquasecurity/trivy-docker-extension and only find instructions on how to install it to Docker Desktop.
3. ????

### Describe the solution you'd like

We need to tell the user that they need to check Docker Hub for the OCI image in order to install it.

**Comment by cdrage** [comment]
Suggestion during F2F: Maybe merge both docker desktop as well as podman desktop "extensions" pages? List what is Podman compatibility and what is only Docker Desktop compatible?

**Comment by benoitf** [comment]
What do you mean by Docker Desktop applications ?
is is the extensions ?

**Comment by cdrage** [comment]
> What do you mean by Docker Desktop applications ? is is the extensions ?

Yes, updated 👍
