### ISSUE TITLE
Modal should close when outside is clicked.

### ISSUE THREAD

**Issue by doehyunbaek** [containers/podman-desktop#162]
### Is your enhancement related to a problem? Please describe

I'm not sure exactly where this idiom comes, but in the web it seems pretty standard for modal to close when background of modal is clicked. My brain is pretty hard-wired to this behavior and I found it inconvenient that 'Create a new container' and 'Add a new registry' Modal did not close when I pressed outside of it. Browing through the code I found out that I could close 'Create a container' modal with escape key(I didn't know this functionality existed for many other websites. TIL something goood!). But it does not work for 'Add a new registry'.

### Describe the solution you'd like

In fact, There is a [Modal component](https://github.com/containers/podman-desktop/blob/6a2624357fe429159410b0e0f79ee5700d1aa32d/packages/renderer/src/lib/dialogs/Modal.svelte) which is used by [PreferencesProviderRendering component](https://github.com/containers/podman-desktop/blob/4f00f64fb430dc0dbaeb0c66c5bc0d5d0f5e1319/packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte), which seems to work well with both escape key and click outside. Utiling that component with existing components('Create a new container' and 'Add a new registry' Modal) and future components would provide great UX and unified UI in my opinion.

### Additional context

I actually cooked up a branch showcasing my suggestion. If you like my suggeestion, I will make a PR out of it, possibily applying the suggestion to 'Add a new registry' modal as well. I'll do style modifications if needed as well.

Here is [link to branch](https://github.com/doehyunbaek/podman-desktop/tree/modal-outside).

Here is a little demo showcasing modal

https://user-images.githubusercontent.com/70570804/171340379-6a2d0044-78cd-4320-b9ec-1a390c794ade.mov

**Comment by benoitf** [comment]
hello @doehyunbaek 
Thanks for the feedback (and the wonderful explanation/deep research in the source code)
The behaviour that you expect is an expected one so feel free to provide the PR as you suggested.

**Comment by doehyunbaek** [comment]
Thanks for quick reply!

I will work on a PR which brings this behavior to both two existing components('Create a new container' and 'Add a new registry' Modal) using Modal component in this week.

For css styling, I do not think it is necessary nor desirable to preserve existing style(as that might not blend well with existing components utilizing Modal component), and I am not aware of any design guide so I will adjust adequately and post screenshot before and after the update.

**Comment by slemeur** [comment]
That's a great feedback @doehyunbaek ! Thanks for reaching out and contributing to the project !

**Comment by doehyunbaek** [comment]
Cooked up a PR!

I also wanted to contribute some patches to existing issues. But I was not sure about two things, whether 1. they are deemed to need a PR or not worthy of one, 2. you are planning to finish them on your own or welcome contribution.

So, @benoitf, if you don't mind, could you tag issues which satisfy both conditions as 'help wanted'? I think i'm gonna be a busy this to next week with day job stuffs but after them can help in once a while. Would be much more willing to help if i can be certain that my PR is likely to be accepted.

**Comment by benoitf** [comment]
@doehyunbaek contribs are always welcomed especially because it comes from feedback/input from other users.

I'll try to tag some with 'good first issue'
About help wanted, I'm not sure as it's up to you to figure out what you like to see in the project.

But usually if there is no assignee, it means issue is `available`

**Comment by doehyunbaek** [comment]
> About help wanted, I'm not sure as it's up to you to figure out what you like to see in the project.

Oh, I've seen some projects which are pretty strict about the scope of the project and reject some features based on the critreia. Then among the existing issues or when interesting issue comes out I will ping you and suggest my opinions. Thanks for your reply.

**Comment by benoitf** [comment]
I would say that it's preferable to create an issue first to discuss it before going in the implementation details with a PR.

**Comment by doehyunbaek** [comment]
Yeah, if something new comes out from me then I'll create a new issue. For issues by other people I will participate in a discussion.
