### ISSUE TITLE
UI: Central location for "Podman Extensions" / repo? 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1620]
### Is your enhancement related to a problem? Please describe

I have all these awesome Podman Desktop extensions I want to try (the Red Hat one that's being worked on #1388 ) as well as other private ones.

But there's no central location of where they are?

### Describe the solution you'd like

Hub? Website? "marketplace"?

**Comment by mairin** [comment]
I think this is the same as: 
https://github.com/containers/podman-desktop/issues/2363

Which is to support:
https://github.com/containers/podman-desktop/issues/1902

Should we close?

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/issues/2363 is for the 'registry' website. (https://registry.podman-desktop.io) so it's not a dup

https://github.com/containers/podman-desktop/issues/1902 was to have an online JSON file that Podman Desktop can fetch to display extensions (it is now done it was a pre-req for #1620 and #2363)

**Comment by mairin** [comment]
@benoitf thanks :-)
