### ISSUE TITLE
Improve support for extensions in external repositories

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1624]
### Epic domain

In order to support external extensions in a first class way we need the following:

- #1651 - Document workflow.
- #1468 - Publish API.
- Merge or improve Podman and Docker extension installation (confusing that there are two paths today).
  - #1619 - Docker Desktop extensions.
  - #1618 - Podman Desktop extensions.
- #1620 -  Improve how to find extensions.
- Additional future API:
  - exec/flatpak-spawn
  - command context
  - icon contributions
  - telemetry contributions
  - rework dialog box
  - rework progress
- Write full documentation.
- Support for extension packs (multiple extensions, one install).
- Recommendations API (e.g. cli installed -> recommend corresponding extension).
- Ability to label/categorize extensions (e.g. container provider vs other extensions).
- Check for updates for extensions + update without restart.
- Display activation/startup time, or other work to ensure fast startup.
- Do what we can to ensure robustness even with unstable extensions.

**Comment by evidolob** [comment]
We also need to document/create development flow for external extension.

The issues that I faced during work on crc extensions, in addition to missing Extension API:

- How to run podman-desktop with external extension
- How do debug external extension

**Comment by deboer-tim** [comment]
Many of the things on this list have been done (including extension packs, documenting how to develop an extension, additional API, featured extensions, extension catalog, API docs [although not linked in yet], etc), but we never came back to link here, so I've closing and we can create a new/up-to-date one if required.
