### ISSUE TITLE
Add feedback mechanism

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#163]
## Description

As a user, I should be able to quickly know how and where I can share a feedback about the tool. 
We would like to add in the UI of Podman Desktop different options to engage on the repository.

### System Tray
We would like to add one "Give Feedback" submenu item in the system-tray. When clicking on this item in the menu, it will redirect to https://github.com/containers/podman-desktop/issues/new/choose 

### Left Sidebar
We would like to add one item at the bottom of the left sidebar, which would provide the ability to the user to get Help.
We add "Help" tab, which will provide guidance to the user on the following areas:
- Access to Documentation
- Report a bug
- Share a Feedback
- Discuss with us (link to discord)

**Comment by rhatdan** [comment]
I think you might want to allow this to report to either podman or podman-desktop, perhaps a tick box to differentiate.
