### ISSUE TITLE
UI: "Run" container button for example not "copy and paste podman command"

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1634]
### Is your enhancement related to a problem? Please describe

When I'm on the main screen, it tells me to do a CLI command when I expect it to be a "Run" button.

### Describe the solution you'd like

When there are no containers, we should have a "Run" command that will launch an example container, rather than specifying `podman run helloworld` instead.

**Comment by deboer-tim** [comment]
To me this is a dup of issue #1264.

**Comment by cdrage** [comment]
Ah yeah, you're right! @deboer-tim thanks
