### ISSUE TITLE
Examples: Showcase guestbook-go kubertnetes example on website / docs / gif

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1637]
### Is your enhancement related to a problem? Please describe

When I use Kubernetes I often have guestbook-go as a goto example. 

I don't see one for Podman Desktop.

### Describe the solution you'd like

Have documentation / videos / gifs / etc showcasing the "guestbook-go" example on the podman desktop website / make sure it works.

**Comment by cdrage** [comment]
We could use other examples too from: https://github.com/kubernetes/examples such as mysql, cassandra, etc.

Steps for this to accomplish this is:

1. Creating a container from scratch (using create container button)
2. Converting it to Pods
3. Being able to "Kubify" it.

Making sure all three steps it works 👍

**Comment by cdrage** [comment]
To accomplish this:

- [ ] Making sure when converting from Container -> Pods it works
- [ ] Making sure when going from Pods -> Kubernetes that it uses 'Deployment' kind not using Pods.

**Comment by themr0c** [comment]
Related: 
* https://github.com/containers/podman-desktop/issues/1323
* https://github.com/containers/podman-desktop/issues/1985
