### ISSUE TITLE
Example: Documentation on building images.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1639]
### Is your feature request related to a problem? Please describe

Building images is pretty important and it was hard to find documentation on how to actually build an image and what steps to go through / debugging / etc.

### Describe the solution you'd like

Separate page / information on how to build containers.

**Comment by ashley-cui** [comment]
You do have [this](https://podman-desktop.io/docs/getting-started/getting-started) but it might be useful to actually provide the containerfile used

**Comment by cdrage** [comment]
> You do have [this](https://podman-desktop.io/docs/getting-started/getting-started) but it might be useful to actually provide the containerfile used

I agree! I think we should have a separate page for the building part including the containerfile used too.

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.

Docs were added
