### ISSUE TITLE
Remove DCO requirement and replace by DCO document

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1643]
### Is your enhancement related to a problem? Please describe

We've seeing community contributions whose first comment is to amend because of the missing Signed-Off-By

### Describe the solution you'd like

Replace by a DCO document and document it in the contributing guide

See https://github.com/redhat-developer/intellij-quarkus/pull/606 or ask @fbricon for comments

**Comment by benoitf** [comment]
@jeffmaury the requirement is at the organization level (Containers)

**Comment by benoitf** [comment]
closing as it's not possible
