### ISSUE TITLE
CRC extension - add option where user can select path to crc binary

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1647]
### Is your enhancement related to a problem? Please describe

I am usually picking up custom location where I install crc (linux, windows), it would be nice to offer a user a way to setup crc which is not on PATH.

### Describe the solution you'd like

Provide a input field in CRC extension page for crc binary.

**Comment by deboer-tim** [comment]
Please open this against https://github.com/crc-org/crc-extension.

**Comment by odockal** [comment]
@deboer-tim Yes!

**Comment by odockal** [comment]
Moved to proper repo: https://github.com/crc-org/crc-extension/issues/5.
