### ISSUE TITLE
Remove badge/numbers from the nav in the UI

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1648]
The little purple numbered badges next to each category (See below) - 
We should just drop them. :) They kind of come across like notifications and provide a little tension to the user and there's not way to clear them. (Idea to pull from @ashley-cui)

![Image](https://user-images.githubusercontent.com/799683/224025497-c55895d0-6e49-451d-a54c-e7a9817ca7c6.png)

**Comment by cdrage** [comment]
Agreed with regards to the UI change and the new update looks more modern / cleaner / opens up the main navigational page for more information. The PR looks great: #2173

**Comment by deboer-tim** [comment]
As Charlie said we're simplifying the main nav using issue #2167. The first PR #2173 has been merged, which means we've removed these badges the best way - by removing them. :)

Closing this issue as fixed, we'll complete the rest of the redesign as part of #2167.
