### ISSUE TITLE
Enable starting compose pods as a group the same way you can with podman pods

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1649]
If I have a pod that was created via compose I can only individually start/stop the containers in the pod, it takes 6 clicks here to start... would it be possible to provide actions at the compose pod group level so I can start/stop all at once? It's my understanding this is possible for podman pods and not compose pods.

![Image](https://user-images.githubusercontent.com/799683/224028973-591fe878-dabb-4cf9-ab8c-53648b1a3abd.png)

**Comment by benoitf** [comment]
there is no REST API to manage compose from Docker/Podman.
If there are options, it could be done through the `compose` extension (by execution compose commands)
