### ISSUE TITLE
Nightly releases / publishing master releases to flatpak hub

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1650]
### Is your enhancement related to a problem? Please describe

When I encounter an issue with the newest release, I'd like to test the latest main branch with either a nightly binary, or whatever has been built against master.

### Describe the solution you'd like

On Linux, I should be able to access a nightly / main branch flatpak image.

On macOS or Windows it would be nice to have a central location to download the binaries (right now we just do numbered pre-release / draft releases)

**Comment by benoitf** [comment]
you can already grab a flatpak binary at each commit. 

example from the 2minutes ago release:
https://github.com/containers/podman-desktop/releases/download/v0.0.202303091231-4025ec9/podman-desktop-0.0.202303091231-4025ec9.flatpak

That said, It's not provided through flathub

**Comment by cdrage** [comment]
@themr0c and I would like to:

- [ ] rename the random numbers to something else / more easier to read, maybe instead of 20230309 we do 2023.03.09.sha256hashnumber or something like that.
- [ ] published to flathub nightly

**Comment by benoitf** [comment]
and without flatpak:
https://github.com/containers/podman-desktop/releases/download/v0.0.202303091231-4025ec9/podman-desktop-0.0.202303091231-4025ec9.tar.gz

**Comment by themr0c** [comment]
When you install the Flatpak from a file, then you don't receive updates. If we have a nightly Flatpak channel, then you could install from that channel and receive daily updates

**Comment by benoitf** [comment]
there is no nightly flatpak channel and they ask people to not use flathub for that
https://github.com/flathub/flathub/issues/2975#issuecomment-1087266934

closing then
