### ISSUE TITLE
Cannot add insecure registry

### ISSUE THREAD

**Issue by ghost** [containers/podman-desktop#1653]
### Issue Description

After installing podman-desktop on Windows 10, it asked me to install podman. That's what I did, so far so good,

Then I tried to add a local registry that comes without a certificate. I tried that in the GUI in Settings -> Registries -> Add registry, which resulted in the error message `Unable to find auth info for https://server.net.local/v2/. Error: RequestError: certificate has expired`.

Then I tried to add the registry within the WSL container `podman-machine-default` in `~/config/containers/registries.conf`, `/etc/containers/registries.conf` and `/etc/containers/registries.conf.d/001-myreg.conf` like this:
```
[[registry]]
location = "server.net.local"
insecure = true
```
But with no luck.

I also added the server in the `/etc/hosts` file. Also, no change there. The error is still shown. Even after restarting podman-desktop.

The server works fine in docker-desktop (which is currently not running) with the URL being stated in the insecure-registries entry in the settings, so I guess the server would be alright.

Any idea what I am doing wrong?

### Steps to reproduce the issue

see above

### Describe the results you received

see above

### Describe the results you expected

see above

### podman info output

```yaml
$ podman version
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.5
Git Commit:   34e8f3933242f2e566bbbbf343cf69b7d506c1cf
Built:        Wed Feb  8 22:08:06 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.18.10
Built:        Fri Feb 17 11:31:22 2023
OS/Arch:      linux/amd64



$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.1
    userPercent: 0.02
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: avah-frsc-lt
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 26235785216
  memTotal: 26602029056
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 1h 12m 36.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  server.net.local:
    Blocked: false
    Insecure: true
    Location: server.net.local
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: server.net.local
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 827060224
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676629882
  BuiltTime: Fri Feb 17 11:31:22 2023
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
I think this is more of a podman-desktop issue

**Comment by benoitf** [comment]
Hello @fschwa 
In docker desktop are you enabling some special flags to make it working or it works by default ?

Podman desktop is using the certificates installed on your computer ( which seems to be Windows)
So probably you should update the certificate on the server side to make it still valid ( non expired) and add the certificate authority if it is self signed on your Windows

Or you're suggesting that we should have in podman desktop a way to trust invalid certificates?

**Comment by ghost** [comment]
Hi, yes, I think there should be a way to add a registry and ignoring the validity of the certificate.

What we have here is an internal server and we are not going to get a certificate for it. That's bad but it is how it is. :(

docker-desktop can do it and if I understand it correctly, podman has that possibility as well as shown above.
Or is podman-desktop not using the config files in /etc/container/?

I am very new to both docker-desktop and podman-desktop and also only a bit familiar with docker on the command line. So maybe I am thinking in the wrong direction.

**Comment by deboer-tim** [comment]
> there should be a way to add a registry and ignoring the validity of the certificate.

+1. There should be a warning or action to accept it, but it shouldn't be blocked. I've been in similar situations where the certificate is bad or expired, and you're aware of it but still need to connect.

**Comment by ghost** [comment]
I think, it would be fine to not have that in the UI. But if I add it to the config file, it should be available to use.

For me the issue is that it is hard to find out what config file is used. I added the registry in three different config files but it still does not show up. Does docker-desktop not use any of the ones I used?

**Comment by Thadir** [comment]
1+ I have similar problems, our internal nexus is still running on HTTP only and currently cannot migrate to HTTPS just yet. But this means on my windows machine I cannot locally build which is a big problem if you want to analyse and test docker file changes. A Microsoft-like prompt are you sure you want to do this insecure action? would be already fine.

**Comment by cdrage** [comment]
To clarify as I start the implementation, in this issue, there are two things that are to be implemented:

1. When adding an HTTPS registry with an expired certificate, we should have a way to accept / ignore the expired certificate
2. Be able to add an insecure registry (HTTP only) as per @Thadir 

For both, we will make sure to issue multiple warnings when adding the insecure registry.

**Comment by deboer-tim** [comment]
IMHO multiple warnings would be annoying, we just need one good warning for each path that clearly explains the risk and allows you to continue.

**Comment by ghost** [comment]
From my point of view, it would be enough if I was able to add the insecure registry in a config file manually. I tried that but without success as described above.

Also: Thanks for working on this. :)

**Comment by cdrage** [comment]
Just an update:

- Wont be adding just "http" connections. Must be https / but the cert can be invalid
- Podman Desktop will add the connection but prompt the user "hey, it's insecure, are you sure you want to add it?"

Discovered from: https://docs.docker.com/registry/insecure/ that in order to add plain http / insecure registries, there is no authentication. So we're obviously not going to do that :)

**Comment by sprior** [comment]
Not so obvious at all, it's still perfectly reasonable for a group to have an http registry without authentication in a dev environment that is on an isolated network (not accessible from the Internet).

**Comment by Thadir** [comment]
And in corporate networks, you often see the use of non-existing top-level domains that show that its internal.
Examples:

- intranet
- internal
- private
- corp
- home
- lan
- echonet

etc. I know it's not fun but the fact is it happens in a professional environment they really don't think about security bc the mantra is "it's internal and not accessible through the internet".  We could add resolve if its a network IP or an internet IP but I think the user should decide.

**Comment by cdrage** [comment]
Thanks @sprior and @Thadir for the insight. I'll split this up into two separate PR's. One for the "invalid certificate" when user's haven't setup TLS / Let's Encrypt / etc.

And another for plain-old http without authentication.

**Comment by cdrage** [comment]
@benoitf

So middle of implementing this I'm realizing we call / check for cert a lot throughput PD.

There are multiple parts of Podman Desktop where the "invalid" cert will appear:
1. Pulling an image
2. Adding a registry
3. Getting image config labels
4. Getting a token

Essentially, the equivalent of when running `podman pull` with `--tls-verify=false`.. but everywhere in PD code.

Notifications, how should we handle them?

Security-wise, we should always notify the user if we're trying to pull / authenticate and there is an invalid certificate.. But give an option to ignore it for the rest of session if they wish. 

I was thinking of:

1. Notify / prompt with a dialog that asks: "Invalid cert. Try again, ignore, etc?". Give the user to try again while ignore invalid cert. Ignore will not show the notification for the rest of the time that PD is running. 

2. When adding the registry, give an option to mark it as having an invalid certificate (this however, will never prompt / notify the user).

WDYT?

**Comment by Thadir** [comment]
Or for the cert thing, Just my 2 cert created a trust store way of working. Self signed cert are quite common in corporate set up s not very one can be a authority ;). So adding it to a trust store, and pop up once a week. Have this a list so you do not implement --tls-verify=false

Sort of what we all do in linux world when we want our internal systems work nice and trust each other:
$ sudo apt-get install -y ca-certificates
$ sudo cp local-ca.crt /usr/local/share/ca-certificates
$ sudo update-ca-certificates

**Comment by sprior** [comment]
I agree with Thadir except maybe for the once a week part - once I've made the decision to accept an invalid (self signed) cert or create an unauthentcated connection and you popped up a confirmation warning once during the creation you've done everything you can and should do, your user has decided what they want.  No need to annoy anyone every time they use the program or even weekly.  In fact that's building the muscle memory to just ignore such warnings and I'd say that's a far bigger problem.

**Comment by benoitf** [comment]
AFAIK we're reading the system certificates from the OS trustore so if you add the certificate on your mac or windows or Linux it should already read it. (but we're not adding something here)

**Comment by deboer-tim** [comment]
To me the basic requirement is that if you connect to a registry with an invalid certificate _or_ over http you get an appropriate warning, and if you accept we'll remember for that specific registry and all future interaction with it, even after restart. If you delete the registry and create a new one you'd be prompted again.

Users can add the certificate to their trust store if they want to do it permanently. It'd be nice if we could do that from within Podman Desktop too, or provide options for 'prompt again after restart/next week', but IMHO those are refinements for another time.

**Comment by cdrage** [comment]
> To me the basic requirement is that if you connect to a registry with an invalid certificate _or_ over http you get an appropriate warning, and if you accept we'll remember for that specific registry and all future interaction with it, even after restart. If you delete the registry and create a new one you'd be prompted again.
> 
> Users can add the certificate to their trust store if they want to do it permanently. It'd be nice if we could do that from within Podman Desktop too, or provide options for 'prompt again after restart/next week', but IMHO those are refinements for another time.

The problem with adding it to the trust store is being able to do it within mac os / across 3 different OS' will be cumersome.

I do agree though with your point of adding a registry and then saying "hey, this certificate is invalid, do you want us to ignore it? you should add it to your truststore though".

and not prompt the user for whenever we want to do `podman pull` `podman push`, authenticate, etc if PD detects that the certificate is self-signed / expired / etc.

**Comment by ghost** [comment]
Overall there seems to be some confusion about what Podman Desktop does and what it does not do.

For me (as the thread starter) it would be totally fine if PD read the Windows Certificate Store. But it either does not do it or I added the certificates in an unproper way (which is totally possible, since I am not a Windows user outside of my work place).

I now asked the IT department for support in adding the certificate to the store ... Maybe it will work after that. ... But then again, I am not sure if PD actually reads the certificate store. It would be nice if we could have kind of a summary about what PD is doing. Maybe then we do not even need a new feature to ignore bad certificates.

**Comment by benoitf** [comment]
@fschwa Podman Desktop reads the 'host' store (in your case Windows root store) when trying to add a registry.

**Comment by ghost** [comment]
@benoitf Thanks for the clarification. I added _a_ certificate to many folders in that store but it still does not work. ... I might have the wrong certificate, though. I just fetched it with
```
openssl s_client -showcerts -connect HOST:PORT </dev/null 2>/dev/null|openssl x509 -outform PEM >mycertfile.pem
```

But well, problems like these are outside the scope of this ticket. :)

What I am wondering is, why adding the host to some registries.conf file (as described in the initial post) does not work. Are those Podman files and PD does not read them?

**Comment by benoitf** [comment]
@fschwa you added the certificates into Windows ?
I think there are utilities or command line to browse your WIndows certificates

**Comment by ghost** [comment]
I used mmc, added the certificates snap-in and added the certificate to half of the folders listet there. :D
Not sure what "folder" is used by PD. No idea how that certificate store actually works either. :(

**Comment by vl-twinsec** [comment]
Hi, I am not quite sure if my post is here correct. I am having the same issue but not with sites having an not trusted CA. 

I am having this with Let's Encrypt / Amazon / Google signed Sites.
With our own hub. But even with https://docker.io hhttps://quay.io and https://gcr.io

![image](https://github.com/containers/podman-desktop/assets/97439577/a40a6080-7bfd-4190-b2d8-599a58badb64)

![image](https://github.com/containers/podman-desktop/assets/97439577/f71ffbb3-fa60-4bd2-8054-7acb72ab440b)

![image](https://github.com/containers/podman-desktop/assets/97439577/e10fcd00-d3a6-4c52-b93f-19ed46cf3b50)

I verified all Urls in Edge on my Windows Host. They are all working fine.

So there might be a general Problem with the CA retrieving? Any idea how to get a closer look to this problem?

**Comment by Thadir** [comment]
@vl-twinsec I do think you need to keep in mind that your Windows has another cert store than the WSL instance podman is running on. If there are custom certificates that are pushed to your system through Network admin config or someone like that.

So if there given or confined like that you should also configure that in the WSL like that.

**Comment by vl-twinsec** [comment]
@Thadir 
In my understanding (as @benoitf) mentioned above, podman ist taking the certificate from Windows. But I don't know. 

But even if Podman ist taking the Cert from WSL the Root CA Certs of Lets' Encrypt, Amazon and Google should be included? 
Anyway I had a look into the WSL did a curl to the sites I mentioned above.

With non of them I got an certificate issue.
Even our own hub answered like this:

`<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Not a Docker request</title>
</head>
<body><h2>HTTP ERROR 400 Not a Docker request</h2>
<table>
<tr><th>URI:</th><td>/</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Not a Docker request</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.51.v20230217</a><hr/>

</body>
</html>`


For me it looks like a general Problem. First I thought it might be a proxy issue but the registration with "https://ghcr.io" works.

Any Idea from anybody?

**Comment by cdrage** [comment]
@vl-twinsec 

I'm trying to replicate this on Windows 10 (Downloaded Windows 11 VM too which I'll be testing later).

I'm at loss the problem unfortunately since I'm copying my cert over and podman picks it up correctly.

Does this only specifically happen on one machine / a corporate machine vs a VM / personal machine?

The odd thing too is suddenly you're unable to retrieve the docker.io cert's, etc now too.

**Comment by vl-twinsec** [comment]
@cdrage 

thanks for your test.

My OS is Windows Server 2022 in a Domain. So a corporate machine as VM. And so far only one machine. But I will try a different system, too. The problem is that my host is ARM so virtualisation a test VM is a little bit difficult.
For the fact that our HUB is public, I didn't add any certificate to my host. It is included in the windows and wsl store. CA is Let's Encrypt.

Yes, I have this problem with the the already included hubs like docker.io, too. But not with https://ghcr.io/

The difference is that ghrc.io is signet by DigiCert.

The others I am trying, by Amazon, Google or Let's encrypt.
Maybe the CA of DigiCert is included in podman and the others not. And podman can't retreive the CAs form Windows Server 2022?

**Comment by cdrage** [comment]
@vl-twinsec Did some more testing and I believe that's exactly what's happening. I don't think the podman VM is accurately grabbing the CA's from the host machine. I *was* able to re-produce it, but after restarting it suddenly worked?

I encountered a DNS issue as well which may be unrelated, where I updated the IP pointing to one of my private servers propagated to my local machine, but not my podman VM.

After performing a restart, the CA cert was grabbed and the DNS issue resolved, which was odd because I followed the same steps as @benoitf above and it only propagated after restart.

Talked to @benoitf and had an internal discussion on what we should do going forward with insecure registries.

We are able to add registries using ~/.config/containers/auth.json but we cannot specify them as insecure unless we edit the registries.conf on the podman machine (in this case, the VM). The code to implement this would be complex as it's going to use the podman CLI to SSH into the machine, edit the configuration file, make sure it's valid, and then restart the VM. The same needs to be done when removing the registry as well. 

After discussion we've decided to do the following tasks:

- [ ] Adding the ability to add an insecure registry but warn the user that pull / push images will not work correctly unless podman is setup that way.
- [ ] Lots of documentation on the main site on how to edit registries.conf within the podman VM in order to correctly use an insecure registry with no errors.
- [ ] Open up an issue upstream with Podman requesting the ability to specify using an insecure registry from a local configuration file rather than having to SSH into the VM and edit registries.conf

**Comment by vl-twinsec** [comment]
@cdrage 
I did an update to 1.1.0 Now I have a different error message:

"Not a valid registry."
The other HUBs are now working. So somebody fixed something in the last version.

For the "Not a valid registry." error we had a look in the source code:

Code-Block from line 669:
`
try {
      await got.get(registryUrl, this.getOptions());
    } catch (requestErr) {
      if (requestErr instanceof HTTPError) {
        const wwwAuthenticate = requestErr.response?.headers['www-authenticate'];
        if (wwwAuthenticate) {
          const authInfo = this.extractAuthData(wwwAuthenticate);
          if (authInfo) {
            const url = new URL(authInfo.authUrl);
            scheme = authInfo.scheme?.toLowerCase();
            // in case of basic auth, we use directly the registry URL
            if (scheme === 'basic') {
              return { authUrl: registryUrl, scheme };
            }
            if (authInfo.service) {
              url.searchParams.set('service', authInfo.service);
            }
            if (authInfo.scope) {
              url.searchParams.set('scope', authInfo.scope);
            }
            authUrl = url.toString();
          }
        } else {
          throw new Error(`Unable to find auth info for ${registryUrl}. Error: ${requestErr.message}`);
        }
      } else {
        throw new Error(`Unable to find auth info for ${registryUrl}. Error: ${requestErr}`);
      }
    }`

Our assumption is the the `if (scheme === 'basic')` does not match to our HTTP-Header-Response: `WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"`

in File: In File `podman-desktop/packages/main/src/plugin/image-registry.ts`

Do you like me to create a new issue? Let me know.

**Comment by cdrage** [comment]
> @cdrage I did an update to 1.1.0 Now I have a different error message:
> 
> "Not a valid registry." The other HUBs are now working. So somebody fixed something in the last version.
> 
> For the "Not a valid registry." error we had a look in the source code:
> 
> Code-Block from line 669: ` try { await got.get(registryUrl, this.getOptions()); } catch (requestErr) { if (requestErr instanceof HTTPError) { const wwwAuthenticate = requestErr.response?.headers['www-authenticate']; if (wwwAuthenticate) { const authInfo = this.extractAuthData(wwwAuthenticate); if (authInfo) { const url = new URL(authInfo.authUrl); scheme = authInfo.scheme?.toLowerCase(); // in case of basic auth, we use directly the registry URL if (scheme === 'basic') { return { authUrl: registryUrl, scheme }; } if (authInfo.service) { url.searchParams.set('service', authInfo.service); } if (authInfo.scope) { url.searchParams.set('scope', authInfo.scope); } authUrl = url.toString(); } } else { throw new Error(`Unable to find auth info for ${registryUrl}. Error: ${requestErr.message}`); } } else { throw new Error(`Unable to find auth info for ${registryUrl}. Error: ${requestErr}`); } }`
> 
> Our assumption is the the `if (scheme === 'basic')` does not match to our HTTP-Header-Response: `WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"`
> 
> in File: In File `podman-desktop/packages/main/src/plugin/image-registry.ts`
> 
> Do you like me to create a new issue? Let me know.

Yes please, we should have a separate issue for this as this the first time I'm seeing this (because it's using a Sonatype Repo Manager http header response) from a custom image registry.

**Comment by cdrage** [comment]
As an update, I have:

- Opened up a PR to allow adding an insecure registry, but this does not apply to pulling an image / pushing: https://github.com/containers/podman-desktop/pull/2896

- Created an issue so we can keep track / add documentation on how to edit registries.conf within a podman VM: https://github.com/containers/podman-desktop/issues/2928

**Comment by cdrage** [comment]
Both have been closed / merged #2896 and #2928 so this issue has been completed (as the add insecure registry is reliant on upstream / podman)

**Comment by ghost** [comment]
Hi,

today I found some time to test this ... and did so on the Podman side (ignoring Podman Desktop for a start).

The new documentation that was added
https://github.com/containers/podman-desktop/commit/b6d1bd77b51d4628bde82037fc78c3a8253c400d#diff-32fcd5d744c9a49f128923566256cc09f1232bf17f3f9e1e114586af2037d21dR46

mentions to add
```
[registries.insecure]
registries = ['example-registry.com']
```

to `/etc/containers/registries.conf`

After I do this, I get an error message:
`Error: loading registries configuration "/etc/containers/registries.conf": mixing sysregistry v1/v2 is not supported`

Reding into this a bit, I think `registries.insecure` is the old way of doing this and 
```
[[registry]]
location = 'foo.bar'
insecure = true`
```
would be better since the rest of the file already uses the new way.

Is this correct or am I missing something here?

**Comment by slemeur** [comment]
cc @themr0c

**Comment by vrothberg** [comment]
> would be better since the rest of the file already uses the new way.

@fschwa yes, that is correct.  The snippet you posted will do the trick.  You can find the man page [here](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md) but feel free to ask any question.

**Comment by ghost** [comment]
> > would be better since the rest of the file already uses the new way.
> 
> @fschwa yes, that is correct. The snippet you posted will do the trick. You can find the man page [here](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md) but feel free to ask any question.

I guess what I am aiming at was that the "old" way was just merged into the documentation for this new feature.
