### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by kdubois** [containers/podman-desktop#1660]
### Is your enhancement related to a problem? Please describe

The font size of the logs is very small (at least on my Fedora instance).  

I did in the end find in the Settings > Editor|Terminal > Integrated: Font Size how to change the font size but that was not very intuitive to find.  

Also, in the 'Inspect' tab for a container, when I right click I see a command palette where I can change the font size for that particular view.  It's a bit strange that this only applies to the Inspect view. 

### Describe the solution you'd like

 It would be nice if the default font size was larger and/or if I could use ctrl + '+' or '-' to change the font size.   

 It would be nice if the command palette of the Inspect view would apply to the other views as well; and if I could set keyboard shortcuts for eg. changing the font.

**Comment by benoitf** [comment]
Hello @kdubois 
It is possible to change the size of terminals and editors in the settings
There is an ongoing work to make the UI more user friendly so it should be more intuitive.

It's also possible to use shortcuts to increase the whole UI
You have zoom menu in view menu. If menu is not displayed you can display it using the left alt key

**Comment by kdubois** [comment]
Hi @benoitf thanks for the feedback.  The zoom function from the view menu doesn't seem to do anything for me, fyi... maybe because I've now hardcoded the font-size in my settings?

**Comment by benoitf** [comment]
AFAIK it's a global zoom so it's independent of the font size

https://user-images.githubusercontent.com/436777/224680778-4963d0c1-918d-4df7-b7bb-bee5dd8eea82.mp4

**Comment by kdubois** [comment]
This is what it's (not) doing in my instance:  
(same on the inspect view)

[Screencast from 2023-03-13 12-56-29.webm](https://user-images.githubusercontent.com/373537/224695349-34db7e77-bbab-4c93-9b48-4d7148ce98c6.webm)

**Comment by lstocchi** [comment]
@kdubois what if you do `View -> Zoom in`?
![zoomin](https://user-images.githubusercontent.com/49404737/224699208-6b70722b-56fb-4487-a81b-8aab14046115.gif)

**Comment by kdubois** [comment]
@lstocchi Yes that works.  (the Ctrl ++ or - does not, however)

**Comment by benoitf** [comment]
ah yes I talked about View/'Zoom In'/'Zoom out'

**Comment by kdubois** [comment]
Sorry, my bad 😅

**Comment by kdubois** [comment]
Has the ctrl++ not working bug already been raised in another issue?

**Comment by ivanbarczak** [comment]
On Windows, the + on Numpad doesn't work, so the actual command for a US keyboard ends up being Ctrl + Shift + =/+ (because you have to access + not = )
Would be simpler if numpad + would work for sure, or even ctrl + =

**Comment by ghost** [comment]
Still happening in the latest flatpak version. The only way to zoom in is to open Devtools and use the zoom feature provided there to adjust your UI size. 

Tedious, but it does what <kbd>Ctrl +</kbd> and <kbd>Ctrl -</kbd> have been doing for ages.
