### ISSUE TITLE
Podman VM not always stops when exiting Podman Desktop

### ISSUE THREAD

**Issue by MajorBreakfast** [containers/podman-desktop#1661]
### Bug description

When exiting Podman Desktop, the expected behavior is that the Podman VM is stopped. This seems to only be partially implemented. I have Podman in autostart. It seems to work the first time after a reboot, but on subsequent times I open and exit Podman Desktop, the VM is not stopped. This is unexpected. I'd like the tray status icon to indicate whether Podman is running or not. If the VM is not stopped reliably, then I cannot be sure that it is actually not running. Instead I need to check via the CLI or in the Activity Monitor.

I have included a screen recording to illustrate the problem:
(the part in the middle when I'm not moving the cursor is me waiting for the VM to full start)

https://user-images.githubusercontent.com/340142/224550517-ed51b014-f3ac-4012-b92d-6a0c6ffcb9e6.mp4

### Operating system

macOS Ventura 13.2.1

### Version

0.12.0

**Comment by cdrage** [comment]
Correct me if I'm wrong @benoitf but I believe it's intentional to keep the Podman VM running even when Podman Desktop is closed.

Podman Desktop helps the trickiest part of running `podman` and that's starting it up and getting it running. Having it run in the background allows users to use podman with docker-like CLI tools such as docker-compose or other CLI tools.

I believe this could be a feature request to implement a way an option to stop the podman GUI on exit.

**Comment by MajorBreakfast** [comment]
@cdrage Part of the issue I'm describing is the inconsistency in behavior: Under certain conditions it stops the VM, under others it doesn't stop the VM.

My preference to always stop the VM make it more beginner friendly. Both Docker Desktop and Rancher Desktop behave that way.

**Comment by benoitf** [comment]
> Correct me if I'm wrong @benoitf but I believe it's intentional to keep the Podman VM running even when Podman Desktop is closed.
> Podman Desktop helps the trickiest part of running podman and that's starting it up and getting it running. Having it run in the background allows users to use podman with docker-like CLI tools such as docker-compose or other CLI tools.
> I believe this could be a feature request to implement a way an option to stop the podman GUI on exit.

I miss the thread.

Idea is to start the VM when we start Podman Desktop (if not already started) and to stop the VM when we stop Podman Desktop (but only if we started at startup)

so for example:
- if your VM is active before launching Podman Desktop: Podman Desktop should not start or stop the VM
- if you do not have active VM before launching Podman Desktop: Podman Desktop should start and stop the VM
