### ISSUE TITLE
Define a way to run and debug external extension

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1663]
### Is your enhancement related to a problem? Please describe

During work on external extension, I face problem with launching and debugging extension.

### Describe the solution you'd like

I'd would like to have a defined way to launch and debug extension.

I would propose to have a way to point podman-desktop a folder where my extension placed during startup(like having dedicated command line argument). And have a way to start debug session for my extension(like providing debug port number).

**Comment by evidolob** [comment]
cc @gbraad @jeffmaury @benoitf @dgolovin

**Comment by themr0c** [comment]
- [ ] https://github.com/containers/podman-desktop/issues/1774
- [ ] https://github.com/containers/podman-desktop/issues/1775
