### ISSUE TITLE
Invalid preference only when characters added to start of numbers

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1672]
### Bug description

In the preferences page, adding a character to the front of a number will cause an error, e.g.setting font size to "x10" will cause the error "x10 is not a number". If you enter "10x" there is no error.

### Operating system

macOS 12.3.1 M1

### Version

0.12.0

**Comment by benoitf** [comment]
'10x' is a valid number on the parseInt() method of JavaScript
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseInt

it'll be interpreted as `10`

**Comment by deboer-tim** [comment]
I know parseInt() considers many of these valid, but users don't know what language we're using and it's not immediately obvious what values "10jfdhgj", "10..2", "10or20", or "10x10" represent. IMHO we should give errors for these even if parseInt() works.

**Comment by benoitf** [comment]
closing as won't fix. no vote/others complaining
