### ISSUE TITLE
UI: Still shows dropdown selection for extensions / dropdown doesn't work

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1678]
### Bug description

In the UI, there is still an option to click for dropdown for extensions:

https://user-images.githubusercontent.com/6422176/224758541-fd372cbb-0936-4f89-88a3-08b62b871e2f.mov

### Operating system

m1

### Version

0.12.0

### Steps to reproduce

Install main branch / run `yarn watch` and test it out.

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/1684
