### ISSUE TITLE
unable to start with corrupted .config/containers/auth.json file

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1679]
### Bug description

When doing 'yarn watch' on Mac OS I've started seeing the following error:

<img width="372" alt="Screenshot 2023-03-13 at 7 46 36 AM" src="https://user-images.githubusercontent.com/19958075/224772946-9bf18bfe-f810-4ed8-8648-56ab3cad49a2.png">

I've confirmed that this happens on a fresh clone, and took a quick look but couldn't figure out the cause or recent PR that might have caused it.

### Operating system

macOS 13.2.1 M1

### Version

next (development version)

**Comment by benoitf** [comment]
you did a 'yarn' command before ?

**Comment by deboer-tim** [comment]
Yes, `yarn install`. This happens on 2nd and 3rd `yarn watch` too.

**Comment by benoitf** [comment]
would be nice to edit the .js file on your filesystem with the line/column and see which json is being read at this time.

**Comment by benoitf** [comment]
line 386/ column 34 of podman extension.js

**Comment by deboer-tim** [comment]
Well, that led to a pretty random debugging session. I eventually found out that my <home>/.config/containers/auth.json was corrupt (see below), causing this error.

I know I haven't edited this file directly, nor AFAIK triggered any change recently. Without knowing how it got into this state I think we can assume it was an odd corruption or caused by something external, but I think we should still make things more robust and log this error instead of showing the dialog.

Failing auth.json:
```
{
        "auths": {
                "docker.io": {
                        "auth": "..."
                }
        }
}       }
}
```

**Comment by benoitf** [comment]
sure it should be more robust. Just wanted to know the root cause
Thanks for the report
