### ISSUE TITLE
Move from podman-desktop discord server to podman discord server

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1688]
### Is your feature request related to a problem? Please describe

There is an existing podman discord server with more people.

plan is to move to podman discord server under a separate channel: `#podman-desktop`
We should redirect people from the current server to the new one

### Describe the solution you'd like

 - [x] Create `#podman-desktop` channel on the podman discord server
 - [x] Update/Promote the new location
 - [ ] Make read-only podman-desktop discord server
 - [x] Ensure bridge on fedora.im/matrix is linked to the new #podman-desktop channel on the podman discord server

**Comment by cdrage** [comment]
- [X]  Ensure bridge on fedora.im/matrix is linked to the new #podman-desktop channel on the podman discord server

Has been confirmed working by @mairin 

PR opened here for updating the links: #2186
