### ISSUE TITLE
Do not show always docker socket compability

### ISSUE THREAD

**Issue by Durus-R** [containers/podman-desktop#1698]
### Is your enhancement related to a problem? Please describe

In my opinion, the "⚠️ Docker Socket Compatibility: Podman is not emulating the default Docker socket path: /var/run/docker.sock. Docker-specific tools may not work." warning on the dashboard should be moved somewhere else.

I don't think, that this is a very important warning and must catch always the user's eye, and this compability cant be given on systems on which podman doesn't has a own virtual machine or /var/run/ belongs to root. 

### Describe the solution you'd like

Maybe the warning could be only shown once the user starts podman first and after that, only in the settings, but with e. g. a hyperlink to the troubleshooting page.

**Comment by benoitf** [comment]
FYI it's being reworked as part of the onboarding screen

**Comment by cdrage** [comment]
> 

Agreed and we've began on the UX/UI change starting with here: https://github.com/containers/podman-desktop/pull/1697 in putting the information in the status bar. 

We're going to put the warning into a notification / dismissable section instead of having the warning appear very annoyingly all the time.

**Comment by Durus-R** [comment]
Great! When do you think, will it be released?

**Comment by Durus-R** [comment]
Also, another suggestion, maybe you should make a new issue for this.... But is a internal editor for kubernetes .yml and Dockerfiles / Containerfiles planned? That would be nice (and a lot of work)

**Comment by deboer-tim** [comment]
@Durus-R could you please open a new feature request to make sure this doesn't get lost?

**Comment by Durus-R** [comment]
Okay. Also, I'll close this issue since there is a pr on this.
