### ISSUE TITLE
Nit: Icon doesn't change to match container status

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#17]
**Describe the bug**
If you start and stop containers the icon doesn't change even though status changes to 'running' and 'exited', but if you switch to another page and come back you see that the icon has a running (coloured) and stopped (grey) states.

**To Reproduce**
Start and stop containers, see the status label change but not the icon. Leave it in the opposite state as it was when you started, then switch to another tab and back to see the icon change.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS M1

**Comment by benoitf** [comment]
I've noticed that as well

Fixed by https://github.com/containers/desktop/commit/f5ed7eea7e3ce5edeb1282494a15179aa970d85e
