### ISSUE TITLE
Adds a UI section in Podman Desktop to see all authentication providers / sign-in

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1705]
### Is your enhancement related to a problem? Please describe

It will be possible to hook external authentication providers
- #1702 

And to signup for register
- #1704 

### Describe the solution you'd like

Authentication providers should be listed in the UI of Podman Desktop.
- Have a way to remove sessions (logout) for a given Authentication Provider

we should also have a way to Signup using a form

Let say we want to signup for 'FooBar' provider (if supported)

We collect all contributed properties with the `SignupProvider` scope
We display them in a nice way (if email type, display it as email with expected format, etc)

Once we have the data, we send the JSON with the name of the fields and their values to the `signup` method of a provider (if supported)

**Comment by benoitf** [comment]
cc @mairin we'll need mockups where User accounts will be displayed and how to login/logout/signin etc

**Comment by mairin** [comment]
@benoitf In this case the Authentication Provider would be used to log into a remote container/kube provider, right? Can they also be used for container registry credentials or are we limiting to remote containers/kube?

**Comment by benoitf** [comment]
for now registries are not plugged into the authentication provider as in fact it uses the same logic across all the vendors (it uses a Registry protocol so we use the same protocol but change the endpoint)
But we could imagine having a quay.io authentication provider (using specific quay.io endpoints) and then the registry screen can discuss with the quay.io provider to grab a 'token' that you'll be able to use inside the registry part as your 'personal token'

**Comment by dgolovin** [comment]
@benoitf Could we reduce the scope a little bit for this:
1. Keep Settings/Registries UI and API as it is right now
2. Create Settings/Authentication Providers UI which would support only single session per provider for the first release (Red Hat SSO does not support multiple sessions anyway)
 
UI would look similar to Registries 

![image](https://user-images.githubusercontent.com/620330/226534587-afb12f36-d212-44bb-aba6-d45c5d180366.png)

Authentication API implementation would be much simpler considering there would be no need to implement addiditonal code to support multiple sessions per provider.

**Comment by benoitf** [comment]
Looks like I forgot to hit the send button on my comment

> Keep Settings/Registries UI and API as it is right now
yes

About the UI, it will be the outcome of https://github.com/containers/podman-desktop/issues/1721

AFAIK about multiple sessions per provider I think @mairin talked about some people requiring to log-in under different account into some providers so design should reflect that.

**Comment by deboer-tim** [comment]
The first pass of this was delivered, closing.
