### ISSUE TITLE
docker socket compatibility link/action ?

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#1709]
### Is your enhancement related to a problem? Please describe

I'm always frustrated when I use podman - all is good, but then I docker desktop for something and come back to podman and see:

"Docker Socket Compatibility: Podman is not emulating the default Docker socket path: /var/run/docker.sock. Docker-specific tools may not work. See troubleshooting page on podman-desktop.io for more information."

I then go to podman-desktop.io and it requires several minutes of digging to find https://podman-desktop.io/docs/troubleshooting#warning-about-docker-compatibility-mode

### Describe the solution you'd like

I wish that at a minimum it would link to https://podman-desktop.io/docs/troubleshooting#warning-about-docker-compatibility-mode rather than having me manually find that info.

optimally simply just provide the commands to run...

right now the page assumes I even know how to restart the podman machine...if i used podman desktop that is never something I needed to do/care about.

so what is the commands?

**Comment by maxandersen** [comment]
also it tells me to run: "sudo podman-mac-helper install"

but that tells me: `Error: helper is already installed, uninstall first`

...how? can't we have one command that does this?

**Comment by cdrage** [comment]
There's an open PR for this to add that button to use `podman-mac-helper` automatically for macOS: https://github.com/containers/podman-desktop/pull/1697

We also plan to remove the compatibility mode warning to a "notification style" screen that is dismissible, as right now it's a bit annoying seeing it all the time.

You can restart the machine under "settings" -> resources -> Podman.
