### ISSUE TITLE
Contributed menus should not be returned if no command is registered

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1711]
### Is your enhancement related to a problem? Please describe

Commands and menus can be contributed through package.json but the command handler needs to be registered through code.
So if a contributed menu has no command handler registered it will be shown but error will pop up when execution is performed

### Describe the solution you'd like

Filter out those menus who don't have a command handler registered

**Comment by benoitf** [comment]
it's a workaround waiting for https://github.com/containers/podman-desktop/issues/1703

as an extension could be activated when we invoke a command (and then it's normal that there is no command handler)
