### ISSUE TITLE
Design: Design for integrating onboarding dialogs into the Settings panel

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1716]
If the user skips onboarding or wants to configure a step they skipped in onboarding... they need to be able to access the same config in settings later. We need a plan / design for how this will work.

**Comment by deboer-tim** [comment]
It's probably the wording more than anything else, but I think about this the opposite way: onboarding is picking up a subset of all the things that you can do in the settings/dashboard pages and presenting it in a simplified and organized flow. I hope the reality is that we're doing both at once or trying to minimize having two different UIs - e.g. trying to build UI components that are clean/simplified enough for onboarding but also work for changing the settings or doing the same action several days later.

**Comment by mairin** [comment]
Here's the idea I've had brewing on this:
https://user-images.githubusercontent.com/799683/227017735-4a135275-dd6f-41d2-9728-641516bfe16e.webm

The clickthru mockups shown in the video are here:
https://design.penpot.app/#/view/d5fc0283-ef1c-80fa-8002-3243c19ca388?page-id=5d1865cd-8afa-80f5-8002-3d9cecb03827&section=interactions&index=0&share-id=d5fc0283-ef1c-80fa-8002-3df9944e1d0e


Other bits not covered here:
- listing categories (eg like the kubernetes onboarding step that gives you cards each for openshift local, kind, devsandbox) - that'd probably be done via the dropdown to add a new provider at the bottom? but we could also be opinionated and by default present cards for setup here that we want to expose / promote to the users
- I think the same settings can be under the Preferences tab, so the users have an "all in one" page that has every setting they can grep thru, so theres some duplication. i dont think that the duplication is necessarily an issue UX wise (it's nice to be able to have one place where you can control all settings) but maybe this is a funky idea

**Comment by deboer-tim** [comment]
The first pass of this was delivered, closing.
