### ISSUE TITLE
Allow to refresh the UI

### ISSUE THREAD

**Issue by pigiax** [containers/podman-desktop#1734]
### Is your enhancement related to a problem? Please describe

Happens on Windows-
Sometimes the UI (Dashboard, Containers, Pods and all other sections) remains empty, even if the podman machine has started and there are available elements into the sections. It's seems to be random.
If I remember well, in previous version a "Refresh" button was present on the menu, and it will be useful to bring it back.
As "workaround" actually I need to close and reopen podman desktop

### Describe the solution you'd like

Show a refresh button (or context menu with right click) that force the refresh of whole UI

**Comment by benoitf** [comment]
@pigiax you can still bring the menu using the left ALT key on Windows or Linux
on macOS menu is in the top bar of the system

**Comment by pigiax** [comment]
@benoitf I hadn't noticed that, thanks.
I don't know if there is any way to make the menu more evident or immediate to access.

**Comment by benoitf** [comment]
we could add menus items in the tray icon.

Global menu was always there before but people wanted to hide it to make a better UI/look'n feel.
We could also have an option to hide/show it but then by default it won't be displayed, users should opt-in

Or we could have a button to reload UI as well, I don't know what is the best.

**Comment by pigiax** [comment]
> we could add menus items in the tray icon.

I think also this could be a good solution: `better UI/look'n feel` isn't lost cause it's not touched, but the functionality it's easily reachable cause everyone open at least once the tray icon context menu

**Comment by assyrus-favolo** [comment]
Is this menu still available? I'm using v1.25.1 Flatpak on Ubuntu and I don't see it, only workaround I've found for this specific use case is the shortcut <kbd>Ctrl</kbd> + <kbd>R</kbd>
