### ISSUE TITLE
Copy button doesn't work in containers section on Windows

### ISSUE THREAD

**Issue by blueelvis** [containers/podman-desktop#1736]
### Bug description

When there are no containers, I am presented with the following screen -
![image](https://user-images.githubusercontent.com/6985763/226160622-3b44c089-13ae-410a-bb3a-3c1306eb90b7.png)

When I click the copy button to copy the command `podman run quay.io/podman/hello`, it doesn't work. After pasting it, the clipboard doesn't contain anything.

### Operating system

Microsoft Windows 10 Pro 10.0.19045 N/A Build 19045

### Version

0.12.0

### Steps to reproduce

1. Install Podman desktop on Windows
2. Open Podman Desktop
3. Go to Containers.
4. Click on Copy output

### Relevant log output

```shell
N/A
```

**Comment by benoitf** [comment]
@jeffmaury @lstocchi does it work on your side on Windows ? on macOS it's copying the content to the clipboard

**Comment by benoitf** [comment]
@blueelvis : could you open the developer console. View menu (if not shown, you can display it pressing the left <kbd>ALT</kbd> key) and then Toggle Developer Tools and then look at the console. Do you see any error ?

**Comment by blueelvis** [comment]
@benoitf - Yep, I am getting the following -

![image](https://user-images.githubusercontent.com/6985763/226286582-d272ee8e-78f5-40b5-b920-4d1128498e2a.png)

`Uncaught (in promise) DOMException: Write permission denied.`

Just fyi, I tried this with both normal permissions and then running as Administrator. Both times, same error as above.

**Comment by benoitf** [comment]
thanks for the feedback

**Comment by lstocchi** [comment]
Tried, it doesn't work for me as well. Thanks for letting us know @blueelvis

**Comment by jeffmaury** [comment]
Broken on 0.12 and main branch in production mode (binary). Works on main branch when run through `yarn watch`
