### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by telometto** [containers/podman-desktop#1737]
### Bug description

I'm not too familiar with the technical jargon, but I think the application is having a memory leak or similar.
I'm using the application through Flatpak and it suddenly crashes. This has just recently started happening, so I'm guessing it's some change in the latest update that causes this.

### Operating system

Fedora Linux 37

### Version

0.12.0

### Steps to reproduce

1. Open the application.
2. Wait for a couple of minutes.
3. Crash

### Relevant log output

```shell
~$ flatpak run io.podman_desktop.PodmanDesktop
[3:0319/100435.034409:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 10:04:35.705: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:04:35.705: Failed to load module "window-decorations-gtk-module"
[3:0319/100435.715098:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0319/100435.715136:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0319/100435.774375:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-3-1: org.freedesktop.DBus.Error.ServiceUnknown
Kubeconfig path /home/MYUSER/.kube/config provided does not exist. Skipping.
Activating extension (crc)
[crc] Can not find CRC binary!
Activation extension (crc) ended
Activating extension (docker)
Activation extension (docker) ended
Activating extension (kube-context)
[kube-context] starting extension kube-context
Activation extension (kube-context) ended
Activating extension (lima)
[lima] Could not find podman socket at /home/MYUSER/.lima/podman-lima/sock/podman.sock nor /home/MYUSER/.lima/podman-lima/sock/podman.sock
Activation extension (lima) ended
Activating extension (podman)
Activating extension (registries)
Activation extension (registries) ended
[podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
PluginSystem: received dom-ready event from the UI
Activation extension (podman) ended
PluginSystem: initialization done.
Delayed startup, flushing 9 events
Autostarting container engine

<--- Last few GCs --->

[3:0x18800a2c000]    91876 ms: Mark-Compact (reduce) 2319.8 (3970.6) -> 2319.8 (3901.4) MB, 2020.10 / 0.00 ms  (average mu = 0.384, current mu = 0.000) last resort; GC in old space requested
[3:0x18800a2c000]    94110 ms: Mark-Compact (reduce) 2319.8 (3901.4) -> 2319.8 (3851.1) MB, 2234.15 / 0.00 ms  (average mu = 0.227, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
/app/bin/run.sh: line 3:     3 Aborted                 (core dumped) zypak-wrapper.sh /app/main/podman-desktop "$@"
```

**Comment by lstocchi** [comment]
Closing it as i think it was fixed. Tried to run podman desktop 0.13 on fedora 37 and didn't crash after 5 mins. The log output is also clean. 
Please re-open it if you face this issue again. Thank you!! 🙏

**Comment by telometto** [comment]
@lstocchi Yes, seems to work fine now! Much obliged!

**Comment by ssbarnea** [comment]
Is this the same memory leak that I seen this morning with 0.13 on macos?

![](https://sbarnea.com/ss/Screen-Shot-2023-04-06-09-38-50.51.png)

It was keep growing visible while looking at the task monitor. For the first time I seen my M1 with 64GB RAM running out of memory, and I was not even running any containers!

**Comment by briggsyj** [comment]
> Is this the same memory leak that I seen this morning with 0.13 on macos?
> 
> ![](https://camo.githubusercontent.com/0e823d2810307796e5af29ca7eeb5c296a83707f676ae079229c880936784a5c/68747470733a2f2f736261726e65612e636f6d2f73732f53637265656e2d53686f742d323032332d30342d30362d30392d33382d35302e35312e706e67)
> 
> It was keep growing visible while looking at the task monitor. For the first time I seen my M1 with 64GB RAM running out of memory, and I was not even running any containers!

Encountered this exact case multiple times, weeks apart. Haven't found a discernable workaround aside from rebooting and hoping it resolves it.

![image](https://github.com/user-attachments/assets/91bbf1aa-18c2-411e-b5e2-8fa52fabe73b)
