### ISSUE TITLE
Enhance Task manager with do not disturb mode / notifications

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1744]
### Is your enhancement related to a problem? Please describe

For now there is a simple Task widget.

We discussed at
https://github.com/containers/podman-desktop/pull/1724#issuecomment-1472721123

that we could have a "purple dot shows up" when there are new tasks
Also a notification could be displayed on the bottom right corner

And a DND (Do Not Disturb) mode should be there 

### Describe the solution you'd like

Continue the work by using https://github.com/containers/podman-desktop/pull/1724#issuecomment-1472721123 as design spec

**Comment by deboer-tim** [comment]
Adding comment here since the original design spec is closed - IMHO the task manager also needs a 'something is running' animation by default. Subtle is ok, but when there's a long running job there should be something that draws your eye to whether it's still going or not.

**Comment by deboer-tim** [comment]
Original design: Issue #1254
