### ISSUE TITLE
kind extension: move image broken

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1745]
### Bug description

When move image feature is called, the command is wrong and the return code is not check correctly leading to confusion

### Operating system

Win11 Pro

### Version

0.12.0

### Steps to reproduce

1. Create a kind cluster
2. Create an image on podman
3. Move that image to the Kind cluster
4. On the kind container (called kind-cluster_name), open a terminal and issues the command: `crictl images`. You should see an images called xxx/import-date)

**Comment by benoitf** [comment]
should the workflow works also with a Kind cluster on top of Docker ? (I've not tried, just asking)

**Comment by jeffmaury** [comment]
> should the workflow works also with a Kind cluster on top of Docker ? (I've not tried, just asking)

Yes ideally we should try with 2 kind clusters: one on Podman and one on Docker but the fix is targeting these 2 envs
