### ISSUE TITLE
Podman desktop hung on "Initializing..." screen

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1760]
### Bug description

When extension try to use `showInputBox` API function in it's `activate` function, podman desktop is not able to finish load, and hung on `Initializing...` loader screen:

<img width="800" alt="Screenshot 2023-03-21 at 16 19 12" src="https://user-images.githubusercontent.com/929743/226635052-e3123876-a0a6-4060-b32a-1cb4c0b23f82.png">

There are no error logs/messages, app just hung on that screen.

### Operating system

 macOS 13.2.1 Intel

### Version

0.12.0

### Steps to reproduce

Create an extension with this code:
```typescript
export async function activate(extensionContext: extensionApi.ExtensionContext): Promise<void> {
  const result = await extensionApi.window.showInputBox({
    prompt: 'Provide something',
  });
  await extensionApi.window.showInformationMessage(result, 'OK');
}
```

And try to start podman desktop with that extension.

**Comment by odockal** [comment]
I got a duplicate which basically extends reproducibility to e2e tests and linux system: #1780.
