### ISSUE TITLE
Compose button is clickable, but no popup comes up

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1768]
### Is your enhancement related to a problem? Please describe

https://user-images.githubusercontent.com/6422176/226721423-181d138a-09c6-4579-9003-4e79832d98f3.mov

Compose button is clickable, but there is no popup / explanation.

### Describe the solution you'd like

When clicking I expect information about what "Compose" is about, what to do, etc.

**Comment by slemeur** [comment]
Won't it be more natural that it points to the setting, into a dedicated
section on this?

**Comment by GiorgioG** [comment]
Same problem here, Podman Desktop v1.0.1, Windows 11

**Comment by benoitf** [comment]
I think it means it's installed. Hovering it should provide some information

But of course we could make it clickable ( but I suppose here status bar entry should not make it being clickable)

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.
