### ISSUE TITLE
Incorrect podman socket path used for root user on Linux

### ISSUE THREAD

**Issue by baodrate** [containers/podman-desktop#1771]
### Bug description

When podman is running as a system service w/ systemd, the socket path (as specified in https://github.com/containers/podman/blob/main/contrib/systemd/system/podman.socket) is `%t/podman/podman.sock`. `%t`, per `systemd.unit(5)`:

| Specifier | Meaning | Details |
| --- | --- | --- |
| "%t" | Runtime directory root | This is either /run/ (for the system manager) or the path "$XDG_RUNTIME_DIR" resolves to (for user managers). |

i.e. `/run/podman/podman.sock`

Currently it assumes `/run/user/${uid}/podman/podman.sock`, which is correct but only for systemd user services (i.e. `systemctl enable --user podman.socket`):

https://github.com/containers/podman-desktop/blob/de1aa71c47570437a44ce99f36b4b22742601e6b/extensions/podman/src/extension.ts#L218-L228

### Operating system

Arch Linux 6.2.7

### Version

0.12.0

### Steps to reproduce

1. Open `podman-desktop` as root (`--no-sandbox` might be required).
2. existing containers/pods/images/volumes are not shown

**Comment by baodrate** [comment]
this issue still seems to be relevant

**Comment by ismailsimsek** [comment]
+1 having same problem. 
docker compatibility is linking `/run/podman/podman.sock`
but actual file created here:  `/run/user/1000/podman/podman.sock`

**Comment by baodrate** [comment]
still relevant (i believe)
