### ISSUE TITLE
docs: testing an extension locally 

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#1774]
### Is your enhancement related to a problem? Please describe

With current docs, to test an extension, you need to pass a complete build-publish cycle.

### Describe the solution you'd like

Describe in the docs where you can copy the extension code without the need of a complete build-publish cycle.

**Comment by cdrage** [comment]
I agree, I feel though that this should be added to CONTRIBUTING.md instead of the website FYI!
