### ISSUE TITLE
Implement preferences look & feel revamp

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1779]
Implementation for design here:
https://github.com/containers/podman-desktop/issues/183

This is to update the look & feel of the prefs screen

**Comment by lstocchi** [comment]
I'll split this issue in 3 PRs:

- [x] refactor the existing preferences page https://github.com/containers/podman-desktop/pull/1913
- [x] implement the search bar to filter https://github.com/containers/podman-desktop/pull/2128
- [x] refactor the tree view https://github.com/containers/podman-desktop/pull/1945

**Comment by lstocchi** [comment]
Closing it as all three PRs have been merged
