### ISSUE TITLE
Podman machine actions misaligned in preferences

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1788]
### Bug description

This is a nit, but I noticed that if I have a Podman machine whose name spans two lines then the action bars don't line up vertically:

<img width="871" alt="Screenshot 2023-03-22 at 5 22 01 PM" src="https://user-images.githubusercontent.com/19958075/227045914-478b47fa-efbd-4b6a-aaa4-6fc3ccc14650.png">

Hopefully there's a simple fix like allowing the name div to expand vertically so the sizes and action bar are always aligned.
FYI @lstocchi 

### Operating system

macOS 13.2.1 M1

### Version

next (development version)

**Comment by benoitf** [comment]
won't fix
