### ISSUE TITLE
Design: Custom titlebar design refinement

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1802]
We need two updated designs for the application titlebar:

- A titlebar design for Windows/Linux with -/+/x buttons
- A titltebar design for Mac with no buttons (the stoplights will be added via electron)

We should then make the window frameless on Linux so that we don't have a double titlebar, which we have right now running on Linux.

Ref: https://ourcodeworld.com/articles/read/287/how-to-create-a-custom-frameless-window-without-title-bar-with-minimize-maximize-and-close-controls-in-electron-framework

**(NOTE: Updated 28 Apr 2023)**
![Screenshot from 2023-04-28 06-09-20](https://user-images.githubusercontent.com/799683/235120015-c66a910c-f7e8-482b-bcf6-49ff9b522a30.png)

Mac titlebars dont appear to have icons typically, so on Mac we would drop the icon + the right aligned buttons in favor of the left-aligned stoplight buttons.

Some spacing specs:

# MacOS stoplights

![Gabháil Scáileáin ó 2023-04-28 08-16-33](https://user-images.githubusercontent.com/799683/235145277-81d3507f-6d93-4d0a-9f8b-36e4e7b7c057.png)
![Gabháil Scáileáin ó 2023-04-28 08-15-57](https://user-images.githubusercontent.com/799683/235145278-10bc877f-2360-4a9a-972a-1e887cbd6563.png)

# Windows / Linux

![Gabháil Scáileáin ó 2023-04-28 07-13-37](https://user-images.githubusercontent.com/799683/235145339-d0a35ba0-08ef-497f-9865-4ecaa1e71556.png)

# Icons

## Maximize
https://fontawesome.com/icons/square?f=classic&s=regular

## Minimize
https://fontawesome.com/icons/minus?f=classic&s=solid

## Close
https://fontawesome.com/icons/xmark?f=classic&s=solid

**Comment by mairin** [comment]
I wanted to document a little bit some thinking on the titlebar.

# Proposal

I'm going to modify the titlebar design above to land around 38 px wide on Windows and Linux, to be within range of what other apps are using and also to boost the ease of use in grabbing the bar.


# Tradeoffs on titlebar width
- **Ease of use:** Wider titlebars have a larger targeting area, meaning they are easier physically / human factors-wise to grab
- **Screen area:** Wider titlebars take up more vertical screen real estate
- **Aesthetics:** Wide titlebars, if too wide, aesthetically can come off a little bit childish looking

# What other apps do for titlebar width
## Windows
(Windows 10)
- Native titlebars vary from 32px to 42px depending on app.

![00-windows](https://user-images.githubusercontent.com/799683/234675806-b6e7e788-0d72-470a-8070-8c889edd1faa.png)

## Mac
(Monterey)
- Native titlebars vary from 28 - 52px... (Slack is 42px but has a bunch of fancy decorators)

![00-mac](https://user-images.githubusercontent.com/799683/234685287-0e519dc8-3015-48e9-a163-e7337f15402d.png)

## Linux

(GNOME default desktop on Fedora Workstation 38)
- Native titlebars are 48px tall; electron app titlebars are 38px tall

![00-linux](https://user-images.githubusercontent.com/799683/234675804-f88b6ce2-40d0-4abe-83b1-d43e44114389.png)

**Comment by mairin** [comment]
## Icons for Windows:

**preview:**
![Screenshot from 2023-05-04 17-43-57](https://user-images.githubusercontent.com/799683/236336533-e16bb2f8-5bd5-48d6-94fb-ec936f021087.png)

github doesn't let me upload SVG so I have these zipped:

## [icons-for-win-titlebar.zip](https://github.com/containers/podman-desktop/files/11401815/icons-for-win-titlebar.zip)

## Palette

##### Basecolor
![basecolor](https://user-images.githubusercontent.com/799683/236337431-7cba5385-6ebd-475b-a0af-3610a6b383be.png)

`#202020`

##### Gray Highlight (non-x icon hover)
![highlight](https://user-images.githubusercontent.com/799683/236337401-4d71cb89-3e91-4748-a617-1f2e0ba2bd5a.png)

`#2d2d2d`

##### Red Highlight (x icon hover)
![red](https://user-images.githubusercontent.com/799683/236338427-a34f1a75-392b-4064-838a-1f6d7ef775c3.png)

`#be4425`

##### White (icon strokes)

![white](https://user-images.githubusercontent.com/799683/236337563-9d1b6eca-ac00-4a58-8296-9e38d45933f1.png)

`#ffffff`

**Comment by mairin** [comment]
Crisp 18px x 18px icon for titlebar
![podman-desktop_18](https://user-images.githubusercontent.com/799683/236345611-b4fdc1a7-7c3c-4034-80a5-558ab66cd737.png)

(svg source: 
[podman-desktop_18.zip](https://github.com/containers/podman-desktop/files/11402135/podman-desktop_18.zip) )

**Comment by mairin** [comment]
Windows titlebar / measurements / spacing

![Screenshot from 2023-05-04 19-27-23](https://user-images.githubusercontent.com/799683/236350904-69798cdf-5760-47bf-bfcf-cd57fe8fc79c.png)

**Comment by mairin** [comment]
Updated icons (hopefully scaling is correct on these. Max icon is 10 x 10px now)

# [win-titlebar-icons_rescaled.zip](https://github.com/containers/podman-desktop/files/11406808/win-titlebar-icons_rescaled.zip)

**Comment by benoitf** [comment]
implemented in https://github.com/containers/podman-desktop/pull/2373

**Comment by alexojegu** [comment]
I preferred the old design. Better a native title bar though double than this. It does not integrate with Gnome.

Podman Desktop is the only window with minimize and maximize buttons. As you can see in the screenshot showing the title bars of Gnome-Console, Chrome, VSCode and Podman Desktop:
![Captura desde 2023-05-25 20-56-22](https://github.com/containers/podman-desktop/assets/63747287/a976089f-b87c-420c-bedc-9059e4648c20)

Please, add config option for native title bar.

**Comment by benoitf** [comment]
created https://github.com/containers/podman-desktop/issues/2647 to keep track
