### ISSUE TITLE
Podman machine extension does not error out when start fails

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#1809]
When an error occurs during start of the podman machine, like missing disk file (inconsistency between WSL and podman machine), out of disk space, out of memory, or other WSL related issues, the user will not see this.

![image](https://user-images.githubusercontent.com/1894/227443579-502158c3-76ce-49e0-a5e3-daa3f3d0d860.png)

the button remains in a start state, so this can be pressed multiple times and no feedback is given.

**Comment by benoitf** [comment]
cc @lstocchi do not know if it's a regression with the new resources or was there before

**Comment by benoitf** [comment]
@gbraad please use github templates when creating issues: https://github.com/containers/podman-desktop/issues/new/choose

We're missing some informations with your blank report
