### ISSUE TITLE
Icons and animations for system tray menu

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#181]
### Is your enhancement related to a problem? Please describe

We would like to improve the system tray icons and provide some animations that are reflecting the state of the providers.
<img width="354" alt="Capture d’écran 2022-06-09 à 10 24 51" src="https://user-images.githubusercontent.com/1636769/172801723-f6fa42e3-ed10-488b-976f-5a274130bf1a.png">

### Describe the solution you'd like

We would like to explore the following behaviors:
- When the user is starting a podman-machine, it can take some time and it would be nice to reflect that state in the tray icon.  - The icons that are used to display the state of the machines/providers are just a basic "circle" at the moment and we should be able to find something better which could eventually be provided by each provider too, so that it will be easier to differentiate them.
- Icons for start/stop.

**Comment by mairin** [comment]
Hi @slemeur - I don't know that these are perfect, but they certainly have distinctive shapes so they can be differentiated that way (these are from the container list mockups that @benoitf implemented in 0.0.5):

![Screenshot from 2022-07-06 15-47-27](https://user-images.githubusercontent.com/799683/177631033-f4f48578-ea13-44ab-8410-58d1c55d8bcf.png)
![Screenshot from 2022-07-06 15-47-19](https://user-images.githubusercontent.com/799683/177631036-bf7c5336-f40a-4865-8c5d-ab73bee77bd4.png)

The green barchart is 'chart-simple' from font awesome in #64ad6c, and the red power icon is 'power-off' from font awesome in #f86847.

**Comment by mairin** [comment]
For the animation when the machine is starting... I don't know what format would be best to provide that in, but patternfly has a spinner component that might be good here (maybe override the color with a purple?) 

https://www.patternfly.org/v4/components/spinner/

**Comment by benoitf** [comment]
@mairin for animation, we just require different png images

you can look at https://github.com/containers/podman-desktop/tree/main/packages/main/src/assets the step*** images

**Comment by slemeur** [comment]
@slemeur : provide gif

**Comment by deboer-tim** [comment]
This has been complete for a while (and there is even a current issue for future enhancement) so closing this.
