### ISSUE TITLE
Extensions can be started multiple times

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#1810]
The start button on the extension can be pressed multiple times in quick succession.

![image](https://user-images.githubusercontent.com/1894/227444290-1d3b9240-323d-49d6-b5bf-6dd9f0a19e67.png)

Since there is no feedback, the user does not see something is happening. As the button is not locked, this most likely will happen and results in the following:

```
14:12:26 [main] Delayed startup, flushing 21 events

14:24:27 [main] [crc] stopping crc extension

14:24:29 [main] Activating extension (crc)

14:24:33 [main] Activating extension (crc)

14:24:42 [main] Activating extension (crc)

14:24:43 [main] Activating extension (crc)

14:24:43 [main] Activating extension (crc)

14:24:43 [main] Activating extension (crc)

14:24:43 [main] Activating extension (crc)

14:24:43 [main] Activating extension (crc)

14:24:45 [main] Activation extension (crc) ended

14:24:53 [main] Activation extension (crc) ended

14:25:16 [main] Activation extension (crc) ended

14:25:16 [main] Activation extension (crc) ended

14:25:17 [main] Activation extension (crc) ended

14:25:17 [main] Activation extension (crc) ended

14:25:17 [main] Activation extension (crc) ended

14:25:19 [main] Activation extension (crc) ended
```

A clear visible sign of this is the tray menu:

![image](https://user-images.githubusercontent.com/1894/227444595-d66da65b-9efd-4148-8c79-3715322fb41a.png)

I suggest the button should be locked (prevented to register again, until unlocked) and provide some form of feedback, so the user knows an action is happening. Especially as the start of the extension could take some time.

**Comment by benoitf** [comment]
it's somehow related to https://github.com/containers/podman-desktop/issues/1789 where a new design will come for extensions

**Comment by benoitf** [comment]
@gbraad bug report should use the github template: https://github.com/containers/podman-desktop/issues/new/choose

**Comment by deboer-tim** [comment]
Confirmed the bug, and that the same things exists for (e.g.) Podman VMs. The root problem is that there are only two states (active and inactive for extensions). We could fix this by disabling buttons when an action starts, but that has drawbacks (e.g. other pages aren't aware, or when navigating away & back) so my preference would be to add two more states.

**Comment by deboer-tim** [comment]
It may have taken three PRs to get there :), but PR #2190 finally fixed this problem and updated the last of the UI. Closing.

**Comment by gbraad** [comment]
Thanks. Will verify this next week as part of manual e2e tests.
