### ISSUE TITLE
Use extension icon for 'window.show*Message'

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1811]
### Is your enhancement related to a problem? Please describe

Now when I use one of `window.showInformationMessage`, `showWarningMessage` or `showErrorMessage` extension API functions, dialog which shown is use electron icon.
Example:
<img width="798" alt="Screenshot 2023-03-24 at 09 26 25" src="https://user-images.githubusercontent.com/929743/227459712-e362cca0-e329-42c9-acdf-eea89efcbe53.png">

### Describe the solution you'd like

 It would be nice if podman desktop use extension icon with that dialogs, to indicate which extension open/show dialog.

**Comment by benoitf** [comment]
we're replacing Electron dialogs by our own: https://github.com/containers/podman-desktop/issues/1807

Note that with production builds it's not showing the electron icon but Podman Desktop icon

**Comment by gbraad** [comment]
Would it be possible to replace the icon with a OpenShift logo. In that case we can avoid using the command palette prompt to have people select the preset.

**Comment by benoitf** [comment]
AFAIK it should/would display the name of the extension that is the source of the prompt
And if we should display an icon, it would be the extension icon

**Comment by deboer-tim** [comment]
See https://github.com/containers/podman-desktop/pull/1808 for what the incoming (non-Electron) dialog design looks like. When an extension uses the API it puts the extension display name on top, no logo or info/warn/error icon. As always we're open to feedback.

**Comment by gbraad** [comment]
it might bd helpful if the logo can be toggled for display. in our case it is start if the startup/onboarding flow and in that case being more explicit about the origin of the message can help

**Comment by benoitf** [comment]
AFAIK onboarding flow is started from a request from the user so user should be aware that it's about the extension he just clicked or I am missing something ?

**Comment by gbraad** [comment]
> so user should be aware that it's about the extension

so, in that case a logo should be toggled (to not display, as the PD logo actually confuses).

---

Looking at #1808

**Comment by deboer-tim** [comment]
> Looking at #1808

Yeah, I think it would help to see this problem in context (i.e. video/demo to show the users actions and where the confusion is), or see if it's still as big of a problem post-1808 where the Podman Desktop/Electron icon will be gone and the extension name is the title of the dialog.

**Comment by deboer-tim** [comment]
@gbraad @evidolob Ok to close this one? The extension name has been the dialog title for a while now, and I think it is sufficient.
