### ISSUE TITLE
Podman Desktop prevent Mac Reboot

### ISSUE THREAD

**Issue by mmornati** [containers/podman-desktop#1812]
### Bug description

Being surprised to see nobody report this... so it is maybe something related to what I've on my MacBook but I'm not able to find what exactly.

If I run a MacBook restart, the operation is "blocked" waiting for Podman Desktop Quit. Stopping the VM has not effect at all.
Today I noticed that even the "Quit" function, manually selected, is not able to stop Podman Desktop. The only thing unblocking this situation is a "Force Quit" of Podman desktop.

FYI I installed Podam Desktop using Homebrew. And I've exactly the same problem on both MacBook I've

### Operating system

macOS Venture 13.2.1 (Intel)

### Version

0.12.0

### Steps to reproduce

- Install podman desktop using homebrew `brew install podman-desktop`
- configure and use the app. Activating the docker.sock / API
- run a Mac restart

**Comment by benoitf** [comment]
thanks for the report @mmornati 
we may have to listen to some events to do a smooth exit.

**Comment by vzhukovs** [comment]
I found out, that this issue reproduces, when there is any ad blocker is installed in the system.
Requests to the telemetry block, because the requested telemetry service is not accessible.

@mmornati do you have any ad blocker installed on your system?

**Comment by mmornati** [comment]
> I found out, that this issue reproduces, when there is any ad blocker is installed in the system. Requests to the telemetry block, because the requested telemetry service is not accessible.
> 
> @mmornati do you have any ad blocker installed on your system?

Not installed on the MacBook. On the pro one I have got an antivirus but the problem is the same on the personal one where I've thing.
But I'm using a DNS AdBlocker (nextdns.io) on the whole local network... not sure it is related but as you are talking about it maybe it could help.

**Comment by vzhukovs** [comment]
> > I found out, that this issue reproduces, when there is any ad blocker is installed in the system. Requests to the telemetry block, because the requested telemetry service is not accessible.
> > @mmornati do you have any ad blocker installed on your system?
> 
> Not installed on the MacBook. On the pro one I have got an antivirus but the problem is the same on the personal one where I've thing. But I'm using a DNS AdBlocker (nextdns.io) on the whole local network... not sure it is related but as you are talking about it maybe it could help.

@mmornati Open, please, `View` -> `Toggle Developer Tools`, and if there are messages like `Error: getaddrinfo ENOTFOUND api.segment.io`, then it will prove the theory about blocking connections to the telemetry. It can cause this problem.

**Comment by mmornati** [comment]
> > > I found out, that this issue reproduces, when there is any ad blocker is installed in the system. Requests to the telemetry block, because the requested telemetry service is not accessible.
> > > @mmornati do you have any ad blocker installed on your system?
> > 
> > Not installed on the MacBook. On the pro one I have got an antivirus but the problem is the same on the personal one where I've thing. But I'm using a DNS AdBlocker (nextdns.io) on the whole local network... not sure it is related but as you are talking about it maybe it could help.
> 
> @mmornati Open, please, `View` -> `Toggle Developer Tools`, and if there are messages like `Error: getaddrinfo ENOTFOUND api.segment.io`, then it will prove the theory about blocking connections to the telemetry. It can cause this problem.

Yeah good catch... Did not check the Podman Desktop log, but the DNS is blocking the segment.io URL. I can whitelist it to check if it is working. 
I will test it this evening... Keep you informed.

![Screenshot_20230509-162651.png](https://github.com/containers/podman-desktop/assets/139323/bec47e7c-6479-407c-8e37-b6cf316ea9e3)


What this service is doing ?

**Comment by vzhukovs** [comment]
> > > > I found out, that this issue reproduces, when there is any ad blocker is installed in the system. Requests to the telemetry block, because the requested telemetry service is not accessible.
> > > > @mmornati do you have any ad blocker installed on your system?
> > > 
> > > 
> > > Not installed on the MacBook. On the pro one I have got an antivirus but the problem is the same on the personal one where I've thing. But I'm using a DNS AdBlocker (nextdns.io) on the whole local network... not sure it is related but as you are talking about it maybe it could help.
> > 
> > 
> > @mmornati Open, please, `View` -> `Toggle Developer Tools`, and if there are messages like `Error: getaddrinfo ENOTFOUND api.segment.io`, then it will prove the theory about blocking connections to the telemetry. It can cause this problem.
> 
> Yeah good catch... Did not check the Podman Desktop log, but the DNS is blocking the segment.io URL. I can whitelist it to check if it is working. I will test it this evening... Keep you informed.
> 
> ![Screenshot_20230509-162651.png](https://user-images.githubusercontent.com/139323/237126994-bec47e7c-6479-407c-8e37-b6cf316ea9e3.png)
> 
> What this service is doing ?

Thanks! It's telemetry service for the Podman Desktop. Collecting the statistic of app usage, also used for feedback processing. So, I'm pretty sure, that this is the main cause. Working on that.
