### ISSUE TITLE
volumes view doesn't update when deletability changes

### ISSUE THREAD

**Issue by TeFiLeDo** [containers/podman-desktop#1829]
### Bug description

After manually removing the last container using a volume, the volumes view doesn't update to reflect that the volume can now be deleted. The issue can be resolved by restarting the application, deleting an already removable volume or (I guess) everything else that causes the page to update.

### Operating system

Arch Linux (Linux 6.2.7) x86_64

### Version

0.12.0

### Steps to reproduce

1. Open Podman Desktop
2. Run `podman run -it -v vol:/vol alpine sleep 3` on the command line.
3. After it stops, go to the containers view and delete the container. Or do it from the command line, makes no difference.
4. Go to the volumes view.
5. `vol` is not removable

### Additional context

Podman version: 4.4.2

**Comment by benoitf** [comment]
thanks for the report @TeFiLeDo.
