### ISSUE TITLE
Javascript error when opening AppImage Podman Desktop on arch linux

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1842]
### Bug description

When testing an AppImage on archlinux (Steam Deck) I'm encountering an error with nothing outputted to dev console.

![](https://i.imgur.com/cK4Uofx.png)

This is a complete bare-bones setup without podman installed either. 

TBH this is a bit of an edge-case, but other developers could be encountering this as well.

### Operating system

steamdeck (archlinux)

### Version

0.13.0-next

### Steps to reproduce

1. yarn compile --linux=AppImage
2. Try to run it on arch / steamdeck

**Comment by benoitf** [comment]
we do not publish any AppImage version

I would say it's a dup of https://github.com/containers/podman-desktop/issues/524

because providing an AppImage would mean that we check it's working

**Comment by cdrage** [comment]
Whoops! You're right. I'll close this as it's unsupported.
