### ISSUE TITLE
Contributing guide for documentation

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1861]
### Is your enhancement related to a problem? Please describe

We have a fairly thorough guide on how to contribute source code, test, lint, and run tests locally, but nothing equivalent for the docs.

### Describe the solution you'd like

Contributing guide for docs that covers the basics:
- `yarn website:dev`
- pointers to Vale and VS Code extension
- `vale sync`
- `vale website`
- `yarn format:check`
- `yarn format:fix`
- `yarn markdownlint:check`
- `yarn markdownlint:fix`

**Comment by cdrage** [comment]
I agree, we should add this to CONTRIBUTING.md with regards to any new features / pull requests for documentation.

Especially the `website:dev` part and the fact that we can also click on Netlify to preview it.

**Comment by deboer-tim** [comment]
Still relevant.
