### ISSUE TITLE
Vale build task makes it extremely difficult to contribute to the website

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1862]
### Bug description

I agree with improving our writing style, but the changes introduced in #1520 make it nearly impossible for new users to contribute to documentation. If someone could make it happy the writing would likely be very bland.

Here are some of the problems I've found:

- No documentation about how to contribute. Opened #1861 to cover this.
- Errors and warnings are flagged on things like user names, paths, or terms that will regularly appear in issue titles like 'typo'. Taking the time to 'fix' these is annoying, wasted time, and doesn't make sense if you're referring to something external. Using `quotes` changes the formatting and that doesn't always work.
- Info messages still appear to fail the build, and since some of them are `Verify your use of 'X' with the word usage guidelines.` the only way to fix them appears to be using a different word. Try writing release notes (#1845) without using the words 'we', 'new', 'please', or 'latest', 'display', 'check', 'usage', 'complete'...
- Some words like 'usage' aren't in the public Red Hat guidelines, and the IBM guidelines require a login.

Case in point: the short 0.12 release notes that we put out last month trigger 6 errors, 11 warnings, and 46 suggestions.

### Operating system

macOS 13.2.1 M1

### Version

next (development version)

### Steps to reproduce

`vale sync` then run `vale` against any recent doc or blog post.

**Comment by themr0c** [comment]
AI for the Vale style:

* https://github.com/redhat-documentation/vale-at-red-hat/issues/500
* https://github.com/redhat-documentation/vale-at-red-hat/issues/501
* https://github.com/redhat-documentation/vale-at-red-hat/issues/502
* https://github.com/redhat-documentation/vale-at-red-hat/issues/503
* https://github.com/redhat-documentation/vale-at-red-hat/issues/504
* https://github.com/redhat-documentation/vale-at-red-hat/issues/505
* https://github.com/redhat-documentation/vale-at-red-hat/issues/141

**Comment by aireilly** [comment]
Hi, we took this feedback onboard and tried to make the Red Hat Vale style better and less annoying :) 

1. All quick-fix suggestions should now be meaningful and correct.
2. Terms with vague or misleading guidance have been removed.
3. Terms that are correct in certain contexts are removed or moved to the Suggestion rule.
4. Terms that do not have a straightforward replacement are now added to the [DoNotUseTerms rule](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/DoNotUseTerms.yml). Context is provided in the error message.
5. Usage rule is retired. See https://github.com/redhat-documentation/vale-at-red-hat/pull/585

If you find errors or terms that don't make sense please holler :)

**Comment by themr0c** [comment]
@deboer-tim I believe we can close this issue now. Please reopen if you do not agree.

**Comment by deboer-tim** [comment]
There were 4 problems listed at the top:

 1. No info on how to contribute to docs/regular process doesn't work.
 2. Errors and warnings flagged on regular/appropriate terms.
 3. Info messages fail the build.
 4. Explanations hidden behind a firewall.

For each of these:

 1. Ok, I had opened issue #1861 for this so we can track it separately. The remaining comments are based on following the process listed there, which I assume is still the correct one to contribute to docs.
 2. I updated and ran vale and there were still a whopping 169 errors and 43 warnings on our website. e.g. last month's release notes have 8 errors and 2 warnings (how did we ever release??) And yes, many of these are still annoying (we shouldn't have to modify titles of GitHub issues opened by users) or just plain wrong in context (e.g. we can't be happy to release? I am!).
 3. It looks like we dropped info messages, but one of the ones I flagged above ('we') has been made into an error instead. 🤦🏼‍♂️
 4. It looks like we dropped this. 👍🏼

So out of the 4, one is tracked separately, one is fixed, one is fixed but actually worse, and the main one still exists. If the problem still exists and our own docs still fail our tests, why would we close this?

**Comment by aireilly** [comment]
Thanks for the feedback @deboer-tim. I made some changes and corrections to the Vale rules in https://github.com/redhat-documentation/vale-at-red-hat/pull/629

This should hopefully clear up the above problems. With the update in the above PR, I see the following errors in the podman-desktop repo:

```cmd
$ vale . --output=line --minAlertLevel=error
website/docs/kubernetes/openshift/configuring-access-to-a-developer-sandbox.md:25:58:RedHat.TermsErrors:Use 'log in to' rather than 'Log into'.
website/docs/troubleshooting/index.md:24:55:RedHat.TermsErrors:Use 're-create' rather than 'recreate'.
website/docs/troubleshooting/troubleshooting-podman.md:233:34:RedHat.TermsErrors:Use 're-create' rather than 'recreate'.
CONTRIBUTING.md:270:13:RedHat.TermsErrors:Use 'open source' rather than 'open-source'.
CONTRIBUTING.md:347:35:RedHat.Spacing:Keep one space between words in 'e.J'.
```

**Comment by deboer-tim** [comment]
Thanks, that would be much more manageable, and scanning the remaining ones quickly these all look like things that we should absolutely fix. Is the recommendation that we use `MinAlertLevel = error` in builds?

When I ran this I noticed a few more errors, in `website/node_modules/prism-react-renderer/README.md`. I'm assuming we just need some kind of .valeignore to skip that folder.

**Comment by aireilly** [comment]
`MinAlertLevel = error` in builds would be my preference yup.

Not sure how to configure a folder ignore directly tbh. We do this kind of indirectly in OpenShift docs: https://github.com/openshift/openshift-docs/blob/main/scripts/check-with-vale.sh

**Comment by deboer-tim** [comment]
The vale build task is still raising a lot of issues and noise IMHO, but since this issue is old and marked done I am closing, and we can create a new issue if this is still a problem.
