### ISSUE TITLE
Website: simplify default install flow

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#187]
### Is your enhancement related to a problem? Please describe

In my experience most users just want one download button with the preferred/default version for their platform, and a 'more options' link with any other options or other platforms. Here are a few random examples: https://adoptium.net or https://slack.com/downloads.

The website correctly detects my platform (M1 - great!), but clicking the download button goes to a page with 'Using Brew' highlighted first, then there are three buttons for Universal, Intel, and Arm. I had to read all the options to decide that Universal or Arm was what I wanted.

Also, 'Version' appears to be missing the actual version string.

### Describe the solution you'd like

The download button on the main page should just install the preferred installer for that platform, and for M1 I think that's Universal or Arm. Bonus points if the button text updates (e.g. 'Download Mac Installer').

**Comment by slemeur** [comment]
The download page has been redesigned by @mairin and is looking simpler now.
But I do agree with Tim, we may be able to make it even simpler if we had a single CTA download button on the page.

**Comment by deboer-tim** [comment]
The website is simpler and recommends the default install; there has been no updates here is a while so closing.
