### ISSUE TITLE
title for new provider should not be hardcoded to 'machine'

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1877]
### Bug description

Following https://github.com/containers/podman-desktop/pull/1582 the title for the creation is hardcoded to 'name of the provider' machine

It should not be hardcoded, machine being only for podman provider.

### Operating system

macOS

### Version

next (development version)

### Steps to reproduce

just try to create a kind cluster, it will say 'Create Kind Machine"

**Comment by lstocchi** [comment]
What should it be? Provider? I see in the main' creation page we have `Podman Provider` `Kind Provider`

**Comment by benoitf** [comment]
maybe the extension should provide the (optional) name ?

so we can display 'Podman Machine' for Podman, and 'Kind cluster' for Kind

**Comment by deboer-tim** [comment]
Too simplistic to add 'machine' for container providers and 'cluster' for Kube providers?
