### ISSUE TITLE
allow extensions to customize icons in container list (or image list, etc)

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#1899]
### Is your enhancement related to a problem? Please describe

Kind cluster is contributing a container (the controller plane)

it should be possible to tell to Podman Desktop to draw this icon differently

### Describe the solution you'd like

- kind extension provide an icon https://github.com/containers/podman-desktop/issues/1525
- kind extension register icon for containers with the filter

could be like a contributing option

where we could have:
name of the view like `icons/containersList` ,
 - the filter to apply on a container like using the when clause `"io.x-k8s.kind.cluster" in containerLabelKeys`
 - `icon: "$(kind)`

**Comment by afbjorklund** [comment]
The label for the container from the minikube extension is called `name.minikube.sigs.k8s.io`

**Comment by benoitf** [comment]
pre-requisites is https://github.com/containers/podman-desktop/issues/1525

**Comment by afbjorklund** [comment]
Yeah, the icon / font itself will be a separate journey. Apparently needs some kind of B/W original.

![fontdrop-webfont](https://github.com/containers/podman-desktop/assets/10364051/79b5c0b1-3fa8-47da-82b8-c2f38a4bfad0)

https://github.com/kubernetes/minikube/blob/master/images/logo/logo.svg

**Comment by lstocchi** [comment]
@benoitf in the title you were mentioning image list as well. Do you want to add support for that view now? Or we close this issue and we work on the image list when there is something to customize?

**Comment by benoitf** [comment]
we can close the issue for now 
Thanks @lstocchi

**Comment by lstocchi** [comment]
Closing. https://github.com/containers/podman-desktop/pull/3131 resolves this
