### ISSUE TITLE
gioui

### ISSUE THREAD

**Issue by gedw99** [containers/podman-desktop#1907]
### Is your enhancement related to a problem? Please describe

the web gui is pretty bad. even scrolling dont work.

### Describe the solution you'd like

[gioui](https://github.com/gioui/gio) can build fast gui with golang with web, desktop and mobile.
it also can run as wasm..

### Additional context

Examples: https://github.com/gioui/gio/network/dependents

**Comment by benoitf** [comment]
It is electron for now that you may dislike and I respect your choice but it won't change for the short term, so closing the issue
