### ISSUE TITLE
Error: spawn podman ENOENT when running PD 0.13.0 from released tarball on linux without podman

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1908]
### Bug description

I got Java script uncaught exception when starting podman desktop 0.13.0 (or when binary is built from main branch - 0.14.0-next version) on linux when there is **no** podman installed on the system:
![Screenshot_20230331_132642](https://user-images.githubusercontent.com/19164299/229121661-c468572d-98e2-49f1-b06a-38c00a26d632.png)

After I click OK, app is spawn eventually.

### Operating system

Fedora 37

### Version

0.13.0

### Steps to reproduce

1. Download tarball for linux
2. extract
3. run
4. ASSERT: app is started properly
Actual result: error dialog is shown first

### Additional context
The same can be reproduced when podman-desktop is built locally from main branch (0.14.0-next) and run.

Since I had podman installed for some time before, I decided to experiment with its removal, not sure that process was correct, I followed this guide [here]. Cannot exclude some system misconfiguration. 

[here]: https://www.ibm.com/docs/en/eam/4.2?topic=questions-troubleshooting-tips#uninstall_podman

**Comment by afbjorklund** [comment]
Fixed:

* https://github.com/containers/podman-desktop/pull/3034

**Comment by benoitf** [comment]
@odockal is it still actual ?

**Comment by odockal** [comment]
It was resolved. Closing.
