### ISSUE TITLE
Strange horizontal sliders when resizing the pod's details view

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1910]
### Bug description

The pod's detail view does not resize well, as it adds horizontal sliding.

See:

https://user-images.githubusercontent.com/1636769/229158816-e0f66dc9-4ddc-46d4-b6e3-282e92fa86d3.mp4

### Operating system

mac OS 13.2

### Version

0.13.0

**Comment by fatelei** [comment]
assign to me

**Comment by fatelei** [comment]
in the video, it display pod's id, it is too long, so the right action display outsize view. i check the code, now it use pod short id, currently it display well.

![image](https://github.com/containers/podman-desktop/assets/961094/033b80c6-3768-488d-97a3-8528baae6985)

![image](https://github.com/containers/podman-desktop/assets/961094/f15b4f87-578d-4203-9723-f18779591cd0)

**Comment by benoitf** [comment]
@fatelei we can close the issue then ?

**Comment by fatelei** [comment]
> @fatelei we can close the issue then ?

yes，close it
