### ISSUE TITLE
Add API for text input dialog (eg. as used for Pull-secret input prompt)

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1920]
### Is your enhancement related to a problem? Please describe

In case of OpenShift Local we need to ask user to provide pullsecret, which is a bug string, now we use `showInputBox` function which is not convenient for entering long string data.

### Describe the solution you'd like

It would be nice if podman-desktop provides an API for extension to create such dialog.
API should provide a way to configure title, has ability to validate input before confirmation button, and ability to provide textual description of required data, with links to external documentation when user could read more.

Example of UI:

![](https://user-images.githubusercontent.com/799683/226679581-f5cbd9c0-6615-4caf-815e-9df940f96a88.png)

Mockup from https://github.com/containers/podman-desktop-internal/issues/84

**Comment by evidolob** [comment]
сс @gbraad

**Comment by benoitf** [comment]
It'll be still the same API showInputBox that has already validation
Optional description should be a markdown string (so it allows links)

**Comment by gbraad** [comment]
Additionally:

  * https://github.com/containers/podman-desktop/issues/1992

**Comment by gbraad** [comment]
@benoitf Is the following now possible?

> Optional description should be a markdown string (so it allows links)

Since this issue is not scheduled and very important for our flow, we now have to look at an alternative approach, but all of this is dependent on the ability to have a 'clickable' link in a dialog, as this is the way the pull-secret needs to be obtained.

**Comment by cdrage** [comment]
See the following implementation: https://github.com/containers/podman-desktop/pull/2253

You can now implement it by using the `<Markdown>` UI component for front end.

But you are correct, we need to add this as an accessible API call from within Podman Desktop.

**Comment by gbraad** [comment]
Thanks @cdrage. This is currently our biggest hurdle to move forward. If this can be implemented we can remove the `showInputBox` usage and also fix the Preset dialog. Is there a possible ETA?

**Comment by gbraad** [comment]
> https://github.com/containers/podman-desktop/pull/2418

I see markdown support is added for the InputBox, but this issue was about a possible Input Dialog. Not sure why this got closed. This is to resolve the intermediate step that is now necessary: https://github.com/containers/podman-desktop/pull/2418#issuecomment-1547287543
