### ISSUE TITLE
Can't delete an unused image

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#1921]
### Bug description

I create my own image from an existing image with a single FROM instruction and build it. Once it's built, I can see it in the images but if a container is running on the base image I cannot delete my own image because Podman Desktop says it's in use.
The Podman CLI allows me to delete my own image.

### Operating system

Win11 Pro

### Version

0.13.0

### Steps to reproduce

1. Take an image (nginx:1.23.3)
2. Run a container from it
3. Create a Containerfile with content `FROM nginx:1.23.3`
4. Build that image
5. Go to the Images panel and see the newly create image and try to delete that image

**Comment by benoitf** [comment]
closing as a duplicate of https://github.com/containers/podman-desktop/issues/1504
