### ISSUE TITLE
Linux: Compatibility warning never goes away on Linux even after enabling.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1928]
### Bug description

Even after running:

```sh
systemctl enable --now podman.socket
ln -s /run/podman/podman.sock /var/run/docker.sock
```

The compatibility mode still appears.

I believe this is an issue with the "compatibility mode" warnings not picking up the correct socket in a flatpak-like environment on Linux.

![Screenshot 2023-04-03 at 4 10 41 PM](https://user-images.githubusercontent.com/6422176/229616929-2cd25563-5b49-4a83-96a0-b2b5ebc9adee.png)

Possibly due to electron builder passing in:

```
      // Read docker socket
      '--filesystem=/run/docker.sock',
 ```
 
 And not /var/run/docker.sock  as compatibility mode checks /var/run/docker.sock rather than /run/docker.sock within a flatpak-like program

### Operating system

Fedora 39

### Version

0.13.0

### Steps to reproduce

1. Linux (Fedora 39 I used)
2. Run `systemctl enable --now podman.socket`
3. Create a symlink `ln -s /run/podman/podman.sock /var/run/docker.sock`
4. Compatibility mode warning should go away, but it does not.

**Comment by benoitf** [comment]
do not need anymore this issue as there is https://github.com/containers/podman-desktop/issues/5789

**Comment by Malix-Labs** [comment]
@benoitf:
> do not need anymore this issue as there is #5789

#5789 is a mitigation, that issue along with #5135 are still needed, but justified to be [closed as not planned](https://github.com/containers/podman-desktop/issues/1928#event-11738315402) due to them being unfixable on your end
