### ISSUE TITLE
Max-width & center on preferences pages

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#1937]
### Is your enhancement related to a problem? Please describe

This screenshot doesn't quite capture it, but basically if you've Podman Desktop fullscreen on a large monitor, the reset to default value icon is a few miles away from the right-aligned controls (eg the switches and number spinners.) 

![229568502-92dc718a-f10e-4e5a-be13-327162f68670](https://user-images.githubusercontent.com/799683/229827872-e1c1a3fc-5a6a-41da-a813-99ac3807125b.png)

### Describe the solution you'd like

I want to stick with right-aligned controls if we can, but I think we should probably have a max width on the rows in the prefs screen and just pad out beyond that max-width on large monitors.

This is the strategy other tools follow for similar screens such as vscode and GNOME Settings:

![Screenshot from 2023-04-04 10-41-32](https://user-images.githubusercontent.com/799683/229828641-bdfdedc9-375a-4a7b-91ee-19f1cc843687.png)

I would suggestion a max-width of 1200 px? Maybe smaller? 

### Describe alternatives you've considered

We could also align the reset to default icons next to the controls. To be honest, we could probably do both.

**Comment by deboer-tim** [comment]
I didn't know this issue existed, opened #3230, and then fixed via #3232. Closing this one.
