### ISSUE TITLE
podman-mac-helper binary not found.

### ISSUE THREAD

**Issue by steveoh** [containers/podman-desktop#1940]
### Bug description

I'm trying to use build pack but it's failing

```
===> ANALYZING
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed to create 'analyzer' container: Error response from daemon: container create: statfs /var/run/docker.sock: permission denied
```

The docker.sock error makes me thing docker compatibility is not working. I check the compatibility button in desktop and try to toggle it. But desktop can't find it.

### Operating system

macOs 13.2.1

### Version

0.13.0

### Steps to reproduce

click docker compatibility

<img width="243" alt="image" src="https://user-images.githubusercontent.com/325813/229889840-82ced8d6-a194-4a84-a71a-6454fe17f18b.png">

click disable

<img width="242" alt="image" src="https://user-images.githubusercontent.com/325813/229889942-f8e57fcb-542b-46b9-83f6-7b2f6365de40.png">

```sh
$ which podman-mac-helper
/usr/local/bin/podman-mac-helper
```

### Additional context

<img width="552" alt="image" src="https://user-images.githubusercontent.com/325813/229890320-70783249-a733-4bac-8b79-7f07e0bdc3f6.png">

**Comment by benoitf** [comment]
Hi @steveoh and thanks for your report

As a workaround could you open a terminal and enter

```
sudo podman-mac-helper install
```

and restart podman desktop and your podman machine

**Comment by steveoh** [comment]
Hey @benoitf, doesn't make a difference.

**Comment by benoitf** [comment]
well at least the compatibility mode should be enabled. 
Then about the permission denied it looks to be an issue with the tool trying to do something on the docker socket at /var/run/docker.sock

**Comment by benoitf** [comment]
For buildpack there are some comments there https://github.com/buildpacks/pack/issues/966

**Comment by steveoh** [comment]
Once I made the macOS updates provided from https://buildpacks.io/docs/app-developer-guide/building-on-podman/ it worked. 

```sh
ssh-add -k "$HOME/.ssh/podman-machine-default"

podman system connection default podman-machine-default-root

export DOCKER_HOST="$(podman system connection ls --format="{{.URI}}" | grep root)"
```

**Comment by benoitf** [comment]
ok so you need a rootful machine and not a rootless machine

podman machine set --rootful

**Comment by steveoh** [comment]
i think it was more of an ssh key issue? and the docker_host value wasn't set.

**Comment by steveoh** [comment]
@benoitf are these two commands equivalent 

`podman machine set --rootful`

`podman system connection default podman-machine-default-root`

**Comment by benoitf** [comment]
@steveoh 
so it's not directly equivalent.

Podman machine command will setup the host/local socket (and then the /var/run/docker.sock as it points to the local host podman socket) and hide all ssh stuff


so I would say that
```
ssh-add -k "$HOME/.ssh/podman-machine-default"
podman system connection default podman-machine-default-root
export DOCKER_HOST="$(podman system connection ls --format="{{.URI}}" | grep root)"
```

is equivalent to
```
podman machine set --rootful
```
(assuming podman-mac-helper is installed/enabled)

**Comment by steveoh** [comment]
I didn't put anything in my dotfiles so it's all gone after last nights reboot. Trying with no commands today which may or may not be completely fresh is working.

I'm assuming the ssh key is a permanent change to the machine? It seems that may have been the fix?

But we are digressing. We should sort out why the helper binary can't be found or where it's looking vs where brew put it.

**Comment by benoitf** [comment]
it cannot be found due to a bug/feature that on macOS binaries have not the visibility of user PATH env variables defined by terminals/shells

But we handle it already elsewhere. Just a bug to fix and this is reproducible.

**Comment by steveoh** [comment]
it wasn't found in 0.15 last time i tried. what version is this fix in?

**Comment by benoitf** [comment]
fixed in v0.16.0+

**Comment by benoitf** [comment]
or in upcoming intermediate/preview releases that are provided after each commit to the main branch

**Comment by fride** [comment]
I just tried to install it and all I get is this.
> ❯ sudo podman-mac-helper install
> sudo: podman-mac-helper: command not found

What did I do wrong?

**Comment by coby** [comment]
> I just tried to install it and all I get is this.
> 
> > ❯ sudo podman-mac-helper install
> > sudo: podman-mac-helper: command not found
> 
> What did I do wrong?

Same here. Did you ever find a solution? Thanks!

**Comment by benoitf** [comment]
if installed by podman pkg on macOS it's in /opt/podman/bin

**Comment by coby** [comment]
@benoitf Thank you. Initially I downloaded the .dmg from podman.io and got the "podman-mac-helper binary not found" error when switching on Docker compatibility mode.

Installing via homebrew seemed to solve the problem.
