### ISSUE TITLE
Provide ability to start/stop/delete for kubernetes connections in resources page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1953]
We should have the ability to start/stop/delete from the resource page for a Kind cluster, similarly to the podman-machine

![Image](https://user-images.githubusercontent.com/1636769/230093182-56084474-d858-483e-8209-b572d9c6f2cf.png)

**Comment by gbraad** [comment]
This affects the OpenShift Local extension too. This will be available to external extensions?

**Comment by benoitf** [comment]
Kind is an extension (builtin or externals have the same access)

It'll add the lifecycle widget for the connections registered by a Provider that are providing a Kubernetes endpoint

Podman engine provides 'ContainerEngine connections/ podman/docker socket") and Kind extension is providing a (Kubernetes cluster connection (endpoint URL)

**Comment by deboer-tim** [comment]
Said another way: capability is for all extensions (builtin or external) that provide a Kubernetes endpoint. If OpenShift Local does, it will also get the controls.
