### ISSUE TITLE
Docs: Working with Kind and Podman Desktop

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1955]
We should provide documentation on how to use Kind for a Podman Desktop user.
- [x] ability to setup a cluster https://github.com/containers/podman-desktop/pull/1998 
	- [x] installing kind https://podman-desktop.io/docs/kubernetes/kind/installing-kind 
	- [x] configuring Podman for kind on Windows https://podman-desktop.io/docs/kubernetes/kind/configuring-podman-for-kind-on-windows 
	- [x] Creating a kind cluster https://podman-desktop.io/docs/kubernetes/kind/creating-a-kind-cluster 
	- [x] Working with yourlocal kind cluster https://podman-desktop.io/docs/kubernetes/kind/working-with-your-local-kind-cluster
	- [x] Restarting your local Kind-powered Kubernetes cluster https://github.com/containers/podman-desktop/pull/2124
	- [x] Deleting your local Kind-powered Kubernetes cluster https://github.com/containers/podman-desktop/pull/2121
- [x] deploying a container or a pod to kubernetes https://github.com/containers/podman-desktop/pull/2026
- [x] Build an image (on Podman), then start a container using this image on Kind to test the image (using `kind load`, see https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/ or better with the UI:https://github.com/containers/podman-desktop/issues/1448 https://github.com/containers/podman-desktop/issues/1562)
- [x] Running Kubernetes objects on Kind (see:https://github.com/containers/podman-desktop/issues/1261)
- [x] Pushing an image to Kind https://github.com/containers/podman-desktop/pull/2076
- [ ] Mention about experimental support for Kind

**Comment by themr0c** [comment]
@slemeur @jeffmaury Anything to add?
