### ISSUE TITLE
Setup pipeline for automated verifiction of installation process on windows platform

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#1966]
### Is your enhancement related to a problem? Please describe

Setup a pipeline for automated verification of installation processes described in #1961 

### Describe the solution you'd like

We will use Jenkins or GHA to automate this scenario.

**Comment by benoitf** [comment]
workflow is here https://github.com/containers/podman-desktop-e2e/actions/workflows/windows.yaml
