### ISSUE TITLE
Kubernetes connection lifecycle object is not show in resources page

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1981]
### Bug description

As it described there https://github.com/crc-org/crc-extension/issues/40 
Podman-desktop doesn't show start, stop, delete buttons on resource page for OpenShift Local extension:

<img width="805" alt="Screenshot 2023-04-06 at 12 42 13" src="https://user-images.githubusercontent.com/929743/230338870-b1bc5d12-4846-4907-bfbb-3da6fdd3d221.png">

### Operating system

 macOS 13.2.1 Intel

### Version

0.13.0

### Steps to reproduce

Install and run OpenShift Local extension, open resource page and see that there are no controls to start/stop openshift instance.

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/1953

@lstocchi thoughts ?

**Comment by lstocchi** [comment]
This should have been fixed by merging https://github.com/containers/podman-desktop/pull/2008 
@evidolob just let me know if you still face any issue

**Comment by evidolob** [comment]
That works, thx!
