### ISSUE TITLE
Blog Post: Setting up and running a Kubernetes cluster locally with Podman Desktop

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#1985]
... and running https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

**Comment by cdrage** [comment]
We have this covered now with the entire Kind section on the website: https://podman-desktop.io/docs/kubernetes/kind

**Comment by themr0c** [comment]
Requirements:
* Ability to scale the redis followers: https://github.com/containers/podman-desktop/issues/1323
* Ability to expose the frontend: https://github.com/containers/podman-desktop/pull/2149
