### ISSUE TITLE
Allow typing numbers in preferences fields

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#1986]
### Is your enhancement related to a problem? Please describe

New Preference UI does not allow typing in input field number, I can only change value by clicking on `-` and `+` buttons, which is fine when field contains relatively small number, but in OpenShift Local extension we have field, which configures memory for VM. And thous field in MiB, with default value `9216` (9GiB). The problem is, when I want to change that value to 12GiB or 16 GiB, I need to perform `3072` or `9216` clicks on `+` button, which is far from ideal UX.

<img width="1048" alt="Screenshot 2023-04-06 at 17 11 19" src="https://user-images.githubusercontent.com/929743/230406471-79ec145e-fe4b-41f5-86cc-56fd8c7bbb06.png">

### Describe the solution you'd like

Allow to type value in number preference field.

### Describe alternatives you've considered

Maybe extension could configure increment/decrement value for preference number field.

**Comment by evidolob** [comment]
cc @gbraad

**Comment by benoitf** [comment]
cc @mairin

**Comment by benoitf** [comment]
@mairin suggested that the component should allow editable value here so for example selecting 9216 and replacing by the value you would like

**Comment by deboer-tim** [comment]
+1. Should just be a text field where you can e.g. select all and replace or just edit.

**Comment by gbraad** [comment]
This should be able to allow values to be changed in increments/decrements. Memory, you do not want to change in small steps, but rather something like `0.5 GiB` or `512`. Patternfly was able to do this for us.

**Comment by deboer-tim** [comment]
Agreed, but let's accept a fix in increments. PR #2368 unblocks the problem by allowing the user to type a value, we can make it more usable with +/- increments separately.
