### ISSUE TITLE
Improve ability to customize preferences

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#1989]
### Is your enhancement related to a problem? Please describe

Two related issues (could be separated into different issues/PRs):

1. If you have a preference like telemetry.enable the UI shows the direct capitalized key, e.g. "Enable". Although this is 'correct', it looks odd in the UI and doesn't add anything to what's already a boolean property with "Enable" on the right.
2. Telemetry should really link to the privacy agreement, and maybe the description should be in two paragraphs.

### Describe the solution you'd like

1. Add an (optional) property like 'name' where the provider can customize what's shown in the UI. For telemetry, that might be something like "Anonymous telemetry" instead of just "Enable".
2. Allow some basic customization of the description, e.g. ability to provide a link to documentation or simple formatting.

**Comment by benoitf** [comment]
for 1. I would keep the behavior of name based on the property name. You might want rename the property to `Enabled`

for 2. we should include/use `markdownDescription` 

![image](https://user-images.githubusercontent.com/436777/230480283-7f677b71-c53f-4d51-a3f8-278ac45ca21d.png)

**Comment by deboer-tim** [comment]
2 is fixed (allows markdown). 1 is still an issue IMHO (e.g. Exit On Close > Exit on Close or Telemetry's Enabled / Enabled, but since this is an old issue I'm closing for now.
