### ISSUE TITLE
Allow to control the modality of dialogs

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#1992]
### Is your enhancement related to a problem? Please describe

For the setup flow, we have to ask about the preset and pull-secret, which are both mandatory for the setup to succeed. At the moment, the dialogs can be cancelled by using escape. It would be nice if the modality of a dialog can be set and therefore the user has to make a decision of the options given (which can include 'cancel').

### Describe the solution you'd like

modality option

### Describe alternatives you've considered

Controlled flow of dialogs for onboarding, although this timeline will probably take much longer. Hopefully, modality in the long-term is not a necessity.

**Comment by benoitf** [comment]
AFAIK if user click on ESC you'll receive 'undefined' as a response so if you really need something you can prompt again the user as well (so ESC won't do anything)

**Comment by gbraad** [comment]
Undefined is not wished for (no ability to use ESC). We can continue in that case with a 'default' preset, but after this there is no way to determine initialization and the user will not be asked again about the preset to choose.
