### ISSUE TITLE
Podman Desktop seems unresponsive due to hidden telemetry dialog

### ISSUE THREAD

**Issue by rolfedh** [containers/podman-desktop#1995]
### Bug description

After installing Podman Desktop (PD), when I run it for the first time, the splash screen and app windows are unresponsive: clicking links and buttons in PD-related windows has no effect. When I rebooted my machine and restarted PD to see if this solved the problem, while PD was starting, I caught a _very brief_ glimpse of a dialog in the background before the main PD window covered it. When I slid the PD window out of the way, I found a _hidden PD telemetry dialog that blocks all other user interactions with PD until it is closed_.

Proposed solution: Make the telemetry dialog appear in front rather than first or make it non-blocking.

POV: What the user experience looks like:

|![Screenshot from 2023-04-07 08-00-55](https://user-images.githubusercontent.com/350907/230608639-28e4605c-89c9-4869-9544-3828000b6dd7.png)|
|:--:|
| <b>Clicking "Settings" and "Go to Podman Desktop" doesn't work, so I close this Get Started with Podman Desktop dialog.</b>|

|![Screenshot from 2023-04-07 08-01-15](https://user-images.githubusercontent.com/350907/230608640-1e10464f-c1e7-40af-b05d-79fead82041f.png)|
|:--:|
| <b>None of the UI elements in PD seem to respond so I reboot my machine.</b>|

|![Screenshot from 2023-04-07 08-04-48](https://user-images.githubusercontent.com/350907/230608642-44609556-7244-47d2-b424-1495adee73bb.png)|
|:--:|
| <b>When I restart PD, I see a flicker of a dialog before the main PD window opens. When I slide PD out of the way, I find the blocking dialog.</b>|

### Operating system

RH Fedora CSB

### Version

0.13.0

### Steps to reproduce

Install and run a fresh instance of Podman Desktop.

**Comment by benoitf** [comment]
closing as a dup of https://github.com/containers/podman-desktop/issues/664

Good news we've moved it to the new Welcome screen so no dialog box behind a Window for Linux Users

it'll land in v0.14
