### ISSUE TITLE
Make nav counts less prominent

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2001]
### Bug description

At the F2F someone mentioned that the container/image/pod/volume counts in the nav column look too much like notifications. They suggested removing them entirely, but I think if we changed the shape and/or used a different colour than purple they wouldn't stand out so much.

### Operating system

MacOS 13.3 M1

### Version

next (development version)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/1648

**Comment by deboer-tim** [comment]
Agreed, closing.
