### ISSUE TITLE
Missing tooltips in 'Images' view

### ISSUE THREAD

**Issue by cfergeau** [containers/podman-desktop#2016]
### Is your enhancement related to a problem? Please describe

If you go to the "Images" tab, there are "Prune images", "Pull an image" and "build an image" buttons. "Prune images" has a tooltip, but it only says "Prune images" which is not useful. The other 2 buttons don't have a tooltip.

### Describe the solution you'd like

I'd either remove the tooltip, or add more detailed ones.

**Comment by nishipy** [comment]
Hi team, can I work on this? Thanks.

**Comment by slemeur** [comment]
Hi @nishipy, if you want to work on this issue, feel free to jump on it. We very much appreciate contributions and let us know if you need guidance too!
Thanks for the proposal!

**Comment by jzfraser** [comment]
Was looking around for good first issues and it looks like this has been implemented and is ready to close!

**Comment by benoitf** [comment]
closed by https://github.com/containers/podman-desktop/pull/2602
