### ISSUE TITLE
Creating a Kind cluster with an error is not reporting the error

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2029]
### Bug description

Creating a Kind cluster while a podman-machine is not running result in a "successful operation". 

https://user-images.githubusercontent.com/1636769/231217570-6d13186e-ce7e-43f9-9a8c-6a3887838273.mp4

### Operating system

Ventura 13.2

### Version

next (development version)

### Steps to reproduce

1. Get a stopped podman-machine
2. create a kind cluster

**Comment by benoitf** [comment]
It seems to be the case for all the errors

**Comment by lstocchi** [comment]
Maybe this is solved by merging https://github.com/containers/podman-desktop/pull/2008 I had an issue with errors not handled correctly when deleting. It also impacts the creation https://github.com/containers/podman-desktop/pull/2008/files#diff-1657d17ab8aa92ebd5f291ee529cc9f2a8842b97ce5f865ea63da79f1c2dfadfR145-R167

**Comment by benoitf** [comment]
I confirm that error is now correctly displayed as part of https://github.com/containers/podman-desktop/pull/2008
