### ISSUE TITLE
Pods from Kind are not visible in Podman Desktop

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2030]
### Bug description

Following: https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

Pods are not visible in Podman Desktop.

![capture_d___e__cran_2023-04-11_a___16 59 07_720](https://user-images.githubusercontent.com/1636769/231217894-e3d10272-f63a-482c-a65a-58d7d63739a0.png)

### Operating system

Venture 13.2

### Version

next (development version)

**Comment by jeffmaury** [comment]
This is caused by current namespace not being set we should use the first namespace or default in that case
