### ISSUE TITLE
Kind cluster port selection not respected

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2045]
### Bug description

When I create a Kind cluster and modify the ports it still uses the default set (9090/9443).

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Modify the ports while creating a kind cluster, then look at the created container to see the default values.

**Comment by benoitf** [comment]
it's a dup of https://github.com/containers/podman-desktop/issues/2013
fixed by https://github.com/containers/podman-desktop/pull/2032

**Comment by deboer-tim** [comment]
Closing.
