### ISSUE TITLE
podman-compose in Windows not recognized in CLI

### ISSUE THREAD

**Issue by lgonzalezsa** [containers/podman-desktop#2055]
### Bug description

After following the installation steps for podman and podman-compose, podman desktop indicates is installed and DOCKER_HOST is reachable but in CLI I was not able to invoke `podman-compose`

What am I missing?

![image](https://user-images.githubusercontent.com/704686/231642119-df4fea67-68b5-427a-bd27-450fdf42f900.png)

### Operating system

Windows 10

### Version

0.13.0

**Comment by benoitf** [comment]
Hello, the compose that is being fetched is docker-compose

so running 'compose' from the path displayed by the 'compose' status bar item should work


if you want to use python podman-compose you'll need to use https://github.com/containers/podman-compose#installation
