### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by ssbarnea** [containers/podman-desktop#2057]
### Bug description

Morning after resume from sleep popup:
```
Error: net::ERR_NAME_NOT_RESOLVED
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49386)
at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

### Operating system

macos ventura arm64

### Version

0.13.0

### Steps to reproduce

- sleep
- resume later

**Comment by benoitf** [comment]
it looks like a dup of https://github.com/containers/podman-desktop/issues/2046

If Podman Desktop is not able to check if there is a new version it reports the error but network being not there should not be reported to the user

**Comment by benoitf** [comment]
anyway, thanks for the report !
