### ISSUE TITLE
No background on Podman Provider when first starting 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2070]
### Bug description

When starting Podman Desktop with Docker already running and Podman is in-progres, there is no background on the Podman provider.

![Screenshot 2023-04-13 at 9 40 22 AM](https://user-images.githubusercontent.com/6422176/231777111-77db304a-0f95-45ba-b68e-85d5e3d20204.png)

### Operating system

M1

### Version

0.13.0

### Steps to reproduce

1. Stop Podman Machine
2. Exit Podman Desktop
3. Turn on Docker Desktop
4. Start Podman Desktop again (it will fail to load the background of the other provider).

**Comment by benoitf** [comment]
probably a leftover from https://github.com/containers/podman-desktop/pull/2007
