### ISSUE TITLE
Better information when finishing creating a Podman Machine

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2071]
### Is your enhancement related to a problem? Please describe

After creating a Podman machine I get this prompt:

![Screenshot 2023-04-13 at 9 45 41 AM](https://user-images.githubusercontent.com/6422176/231778499-8a6284d7-c186-48a4-86e4-614dffa1dd84.png)

Which I find generic / not useful.

### Describe the solution you'd like

More information with regards to what to do after creating the Podman Machine.

Sometimes it takes so long to create I walk away from the computer and come back, forgetting what I was doing. (example scenario, not actually what happens haha)

"Successful: Podman Machine created"

Or something similar to that. 

Maybe even a second button saying: "Click here to go to Containers" or something.

**Comment by slemeur** [comment]
Similar UX issue for the creation of a Kind cluster
