### ISSUE TITLE
Kind: Uses an unconventional port 9090  / describe why

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2073]
### Is your enhancement related to a problem? Please describe

When using Kind, people wont know why we are using port 9090

Usually this is port 8080 when non-root, should we default to that instead?

And also explain why that's needed and why we can't use just port 80 and 443 on localhost.

### Describe the solution you'd like

Being able to use port 80 / 443 or if it's a non-default, explain why.

This is because most Kind examples simply use `localhost` but obviously we can't do that we are running kind within a podman machine.

**Comment by benoitf** [comment]
One reason was also to avoid to conflict with lots of apps already running on 8080 port

And the other reason is that rootless machines can't use 80/443 as it's below 1024 port range
