### ISSUE TITLE
Kind: Ingress example file does not work on Contour deployment

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2075]
### Bug description

Using the default example from https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress does not work on our Contour ingress setup.

### Operating system

M1

### Version

next (development version)

### Steps to reproduce

1. Setup the ingress with Kind
2.  Run `kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml`
3. Try to curl the endpoint (`curl localhost:9090/foo/hostname`)

**Comment by jeffmaury** [comment]
This example uses NGINX specific rules and is not standard

**Comment by benoitf** [comment]
closing as won't fix

using ingress example with contour looks like an expected failure
