### ISSUE TITLE
When I leave a kind cluster creation page I have no way to return to see the logs or outcomes

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2079]
### Is your enhancement related to a problem? Please describe

I was creating a kind cluster and left the page where the process was shown. I could not get back. I could monitor a task, but once the task was finished, it disappeared. I could assume all went well, but no option to check logs or whatever.

### Describe the solution you'd like

It would be nice to have a way to actually get back to a page where something was happening. 
Ie. I start creating a king cluster, go to Images and then I could return back to the same page of Kind cluster creation.

**Comment by deboer-tim** [comment]
We should move it to use the task manager - I think that's the intention just requires work.

**Comment by benoitf** [comment]
It was working when I introduced the task manager, probably a regression when the new design of creation page landed

https://github.com/containers/podman-desktop/pull/1742
