### ISSUE TITLE
Kind clusters are not shown on Resources page on Windows when using podman-machine-default-root connection

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2080]
### Bug description

I got an issue viewing a kind clusters on Resources page. 
![Screenshot_20230413_173401](https://user-images.githubusercontent.com/19164299/231810972-b5f883cd-af25-450b-b22e-823ef2ec3958.png)

### Operating system

Windows 10

### Version

0.14.1 and next development version

### Steps to reproduce

On Windows 10, without podman, kind and WSL installed
1. Open Podman Desktop
2. Install podman
3. Initialize and start podman machine
4. Assert: Podman machine is running
5. Install Kind
6. Create new Kind cluster 
7. Assert: Kind cluster is created -> Actual result is that It `fails to create kind cluster` due to `Error: failed to create cluster: running kind with rootless provider requires cgroup v2, ...`
8. (Assumption) we want to make use of `rootfull` podman system connection that is using root user in podman machine 
9. Go to powershell and check podman system connections
10. Change default connection to rootfull one: `podman system default podman-machine-default-root`
11. get back to podman desktop and restart podman machine in Settings -> Resources
12. Try again to create Kind cluster, go through the form and press create button
13. Assert: Kind cluster is created successfully -> `Operation successful` page appears, powershell show cluster exists: `kind get clusters`
14. Verify that kind cluster details are present in Resources page
**Actual result: There is nothing in resources page. On dev. console there is error**

### Relevant log output

```
index.ts:1259 main ↪️ Kube event error Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)
(anonymous) @ index.ts:1259
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

### Additional context

It could be a regression #1818. 
What is also interesting is that If I try to make use of the rootfull connection of the podman machine before running it with default rootless mode, I cannot start the machine at all.

**Comment by benoitf** [comment]
I am not able to reproduce the issue. We did several fixes in last couple of days as well
if you could try again

**Comment by odockal** [comment]
@benoitf Yeah, reproduced again on the same machine (remote dell laptop, windows 10 Pro) and on the one i have at home windows 10 Pro. Run from `yarn watch` with latest commit: `1d2351f7dd3891750008f61b7f44610617304687`

**Comment by odockal** [comment]
I managed to get an error on developer console:
```
index.ts:1259 main ↪️ Kube event error Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)
(anonymous) @ index.ts:1259
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

**Comment by odockal** [comment]
Description updated. Added steps to reproduce, also there is an issue with rootful connection when creating a podman machine. It fails to create a machine with such connection.

**Comment by odockal** [comment]
Although! If I try to use `podman machine set --rootful` thing seems to start working again.

**Comment by slemeur** [comment]
Will be fixed by https://github.com/containers/podman-desktop/issues/2141

**Comment by odockal** [comment]
@slemeur I think that in #2141 we demonstrated that we can use rootless connection. Problem here is with our docs. if we follow them: https://podman-desktop.io/docs/kubernetes/kind/configuring-podman-for-kind-on-windows then the bug appears - at least for me.

**Comment by odockal** [comment]
we need either fix the bug if docs are alright or update docs with right information how to setup kind in windows with rootfull machine.

**Comment by harima130193** [comment]
Cluster still not showing although use 2 commands:  `podman machine set --rootful` and ` podman system connection default podman-machine-default-root`
![image](https://github.com/containers/podman-desktop/assets/105222183/ed28f651-b0eb-4817-947b-3c08382f1b10)

**Comment by Cyb3rDudu** [comment]
I have the same behavior on MacOS
Podman Desktop Version 1.3.1
After restarting my Computer, I don't see the Kind Clusters in the Resources View anymore. I get them back, when I disable and reenable the kind extension.
After that, the Kind Clusters are listed again.

Having the Podman machine rootfull does not change the behavior.

Edit: Same for Minikube Clusters
