### ISSUE TITLE
Check podman machine and system connections

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2096]
### Is your enhancement related to a problem? Please describe

When playing with podman machines (creating, deleting, etc), the podman CLI is running quickly out of sync and you see 'connection refused' errors

Usually it's because the system connections of podman are not matching the active machine

Usually, you can do

```
podman machine ls
```
grab the machine being alive

```
podman system connection list
```

check what is the default connection

and set the default to the machine (usually it's on the rootless connection)
```
podman system connection default <machine-name>
```

### Describe the solution you'd like

Podman could verify that and report an issue and a way to fix the connection.

**Comment by cdrage** [comment]
FYI for anyone else trying, I manage to replicate this while Podman Desktop was open:

```
# Create the default Podman machine if it hasn't already been created
podman machine init
podman machine start

# With Podman Desktop open, you should see the default appear / start / run
# Start the second VM
podman machine init test-vm

# Stop the initial VM (podman-machine-default)
podman machine stop

# You'll see connection error refused since `podman-machine-default` is down
# Start the other VM, should show it correctly.
podman machine start test-vm
```

Doing these steps will show connection refused errors for KUBERNETES when stopping the VM and Podman is trying to reach it.

**Comment by cdrage** [comment]
Following diagnosing this issue, the `connect ECONNREFUSED` errors are actually coming from https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/stores/pods.ts#L26

Where we checking Kubernetes pods without checking to see if there is even a connection available yet. 

Following the output when closing / opening the podman machine, making it look like we've lost connection.

In reality, Podman Desktop appears to be picking up podman machine just fine. I close podman machine / start / stop and it's detected.

I can modify the code like so:

```
export async function fetchPods() {
  let result = await window.listPods();
  try {
    const pods = await window.kubernetesListPods();
    result = result.concat(pods);
  } catch(e) {
    console.log('No Kubernetes provider found: ', e);
  } finally {
    podsInfos.set(result);
  }
}
```

And it'll show that it's all coming from fetchPods from Kubernetes that shows the connection refused errors.

**Comment by benoitf** [comment]
@cdrage the issue that I created is about the synchronization between `podman` CLI and the podman system connections

At some points, you have a default connection that is not referencing the current machine
so podman cli says 'connection refused' because it tries to connect to an old machine (not the active one)

sometimes people may want to connect to external systems but here the usecase is with local machines being not refreshing the current system connection

**Comment by cdrage** [comment]
> 

Yes, there's two issues here, one semi-related (showed connection refused errors in the console).

When you said: 'connection refused' errors I thought you also meant console.

This issue: The one about CLI synchronization I was unable to replicate. Each time I set the `podman machine` as default, and then switch, as well as delete / create / stop, I'm unable to see any connection refused errors.

The second issue (unrelated, but still shows connection refused errors in console): https://github.com/containers/podman-desktop/issues/2202
