### ISSUE TITLE
Terminal Font Size Contextual Zoom Component

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2110]
### Is your enhancement related to a problem? Please describe

@themr0c noted having difficulty reading the default terminal font size in the window where the kind install logs show up on Windows:

![screenshot_from_2023-04-14_17-08-25](https://user-images.githubusercontent.com/799683/232088636-6c50138e-a3a7-4231-9e21-62546fe382c5.png)

The terminal font size is something that can be adjusted under Settings > Preferences > Terminal Font Size, however, when you're in the prefs screen you cant visually assess if the size you're changing to is optimal, so you might have a lot of flipping back and forth between the screens OR change it, not be satisfied, but be lazy and stop pursuing the perfect font size for your terminals/logs :)

### Describe the solution you'd like

The idea is to have an optional transparent overlay ( - ) / ( + ) button set in the upper right of any logs or terminal components. This could be another way to set the terminal font size instead of having to go to preferences. 

I think it's important the controls are transparent (50% opacity maybe) so if there is text underneath that they obscure, it's still partially readable.

**Scope:**
I think this might be best if it was not be one-off, but would update the preference setting globally. But I'm not sure. Maybe one-off would make more sense. If it was done one-off, I would suggest adding a reset button next to the -/+ buttons to return the size to the default from Settings.

### Additional context

Quick mock up of what this could look like. Button on right is in hover state.

![Screenshot from 2023-04-14 11-29-08](https://user-images.githubusercontent.com/799683/232089517-1db84810-c39e-47ee-a1bd-20ae8e66a1b6.png)

**Comment by vancura** [comment]
FYI, I wanted to connect this issue with our ongoing discussion in Issue #12580 regarding terminal font family selection. Both represent complementary dimensions of the terminal typography accessibility strategy.

We're exploring font family options that accommodate specialized reading needs (including fonts like OpenDyslexic Mono), which would pair naturally with the contextual zoom component proposed here. The zoom idea is now considered in #12598.
