### ISSUE TITLE
Issue doing cluster creation on Linux flatpak

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2113]
### Bug description

When trying to create a Kind cluster, the follow issue appears when running a compiled version of Linux flatpak.

```
Portal call failed: Failed to start command: Failed to execute child process “undefined” (No such file or directory)

Error: Failed to create kind cluster. Portal call failed: Failed to start command: Failed to execute child process “undefined” (No such file or directory)
```

https://user-images.githubusercontent.com/6422176/232099029-47e00e19-5994-4871-8fb8-bbc4c253994b.mov

### Operating system

Linux Fedora 39

### Version

0.14.1

### Steps to reproduce

1. Compile as flatpak
2. Install
3. Try to create a `kind` cluster.

**Comment by themr0c** [comment]
Hi, this morning with the 0.14.1 released Flatpak on Fedora 38, I could create a first kind cluster, but for the second I get this error:

```
Error: Failed to create kind cluster. enabling experimental podman provider Creating cluster "second-kind-cluster" ... • Ensuring node image (kindest/node:v1.26.3) 🖼 ... ✓ Ensuring node image (kindest/node:v1.26.3) 🖼 • Preparing nodes 📦 ... ✗ Preparing nodes 📦 Deleted nodes: ["second-kind-cluster-control-plane"] ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

logs:

```

enabling experimental podman provider
Creating cluster "second-kind-cluster" ...
 • Ensuring node image (kindest/node:v1.26.3) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦 
Deleted nodes: ["second-kind-cluster-control-plane"]
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"

Error: Failed to create kind cluster. enabling experimental podman provider
                                                                           Creating cluster "second-kind-cluster" ...
                                      • Ensuring node image (kindest/node:v1.26.3) 🖼  ...
          ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
                                                         • Preparing nodes 📦   ...
   ✗ Preparing nodes 📦 
                       Deleted nodes: ["second-kind-cluster-control-plane"]
                                                                           ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"

```

```
.local/share/containers/podman-desktop/extensions-storage/kind/kind-linux-amd64  version
kind v0.18.0 go1.20.2 linux/amd64
``

**Comment by lstocchi** [comment]
@themr0c https://github.com/kubernetes-sigs/kind/issues/2972 
Can you give a look at your logs and see if it's related to one of the problems listed there? https://github.com/kubernetes-sigs/kind/issues/2972#issuecomment-1360412253
`kind export logs` after you see your error

**Comment by themr0c** [comment]
I believe my issue might be related with this: I can't run the website when a Kind cluster is running:

```
[SUCCESS] Docusaurus website is running at: http://localhost:3000/
[ERROR] Error: EMFILE: too many open files, watch '/home/ffloreth/src/gh/themr0c/podman-desktop/website/sidebars.js'
```

**Comment by themr0c** [comment]
`kind export logs` doesn't work: as the second Kind cluster creation fails, `kind` has no cluster to export from.

**Comment by metal3d** [comment]
Exactly the same problem with the flatpak version on Fedora 38. Using Podman Desktop latest release works.

**Comment by benoitf** [comment]
no recent report, closing

**Comment by christoph-jerolimov** [comment]
I have the same issue with Podman Desktop 1.8.0 on Fedora 39

This happened when I installed kind and Minikube via Podman Desktop but said NO when it asks me to install the CLI tools "globally" into my system.

When I try to create a kind or minikube cluster it shows the same errors as mentioned above:

> Portal call failed: Failed to start command: Failed to execute child process “undefined” (No such file or directory)
> 
> Command execution failed with exit code 1
> 
> Error: Failed to create kind cluster. Command execution failed with exit code 1

Kind and Minikube are shown as not installed when I restart Podman Desktop!

And when I install kind and minikube and accept the global installation of the CLI tools the creation of the kubernetes clusters works fine!

/reopen

**Comment by vrutkovs** [comment]
Same issue on Podman Desktop 1.10, Fedora 40. If the tools are not installed globally the kind cluster will fail to start
