### ISSUE TITLE
Windows POPUP with Error Network_IO_SUSPENDED

### ISSUE THREAD

**Issue by cforce** [containers/podman-desktop#2117]
### Bug description

Below eror juts occours - no idea what is the context, but at least it worked somehow before and i assume its realted with suspend/hibernate

<img width="407" alt="image" src="https://user-images.githubusercontent.com/393286/232232913-51e8f426-2f1b-4380-83a4-9f0b7411361a.png">

### Operating system

Windows 10

### Version

0.14.1

**Comment by benoitf** [comment]
Hello @cforce 
Are you on 0.14.1 ?
Issue was in 0.13.0 but it should be fixed now with https://github.com/containers/podman-desktop/issues/2046

**Comment by cforce** [comment]
ok-i will update
