### ISSUE TITLE
use podman system connections

### ISSUE THREAD

**Issue by eveerman** [containers/podman-desktop#2118]
### Is your enhancement related to a problem? Please describe

(On windows heavily and less so on linux...) I have multiple connections configured in the podman windows config eg:
`PS C:\Users\qdo0obp> podman system connection list
Name                         URI                                                            Identity                                         Default
coreos                       ssh://core@192.168.157.10:22/run/user/1000/podman/podman.sock  C:\Users\qdo0obp\Documents\KEYS\id_fedoreCoreOS  true
podman-machine-default       ssh://user@localhost:31785/run/user/1000/podman/podman.sock    C:\Users\qdo0obp\.ssh\podman-machine-default     false
podman-machine-default-root  ssh://root@localhost:31785/run/podman/podman.sock              C:\Users\qdo0obp\.ssh\podman-machine-default     false`

However I do not see that podman desktop can utilise these even if, as above, the podman default connection is changed.

Primarily this is useful for remote access (as above) and whilst there is an option to create new podman-machine these appear to be local only.

### Describe the solution you'd like

I guess is really a two stage or two option solution?
- add option to create "new" machines that link to remote hosts
- CRUD of the connections configured directly via podman cli

### Describe alternatives you've considered

At this stage I do not have any alternative

**Comment by slemeur** [comment]
Thanks for the report @eveerman, we don't support podman remote hosts at the moment https://github.com/containers/podman-desktop/issues/279.

I'm going to close your issue in favor of the previously created one, but please feel free to jump in, upvote or even contribute if that could be interesting you ;)
