### ISSUE TITLE
support for port forwarding and host volume mount

### ISSUE THREAD

**Issue by djnotes** [containers/podman-desktop#212]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Support port forwarding and host bind mount like docker desktop. 

### Describe alternatives you've considered

The heavy Docker Desktop

### Additional context

Will Podman Desktop be able to support port forwarding to host and bind mount, just the way installing Docker Desktop adds these?

**Comment by benoitf** [comment]
Hello @djnotes there is already Host exposure. If you start a container using port arg it's exposing the port locally

About bind mount, latest podman 4.1 allow mount exposure from home directory for now

**Comment by djnotes** [comment]
Thanks @benoitf. How do I access those shared files in the container? I don't see any shared files inside the home directory after I ssh into the vm with `podman machine ssh podman-machine-default`.

**Comment by rhatdan** [comment]
podman machine supports host volume shareing into the VM which can then be shared into the container.


podman v4.1 automatically share $HOME:$HOME into the container.  You can add containers.conf to customize the volumes.  podman-desktop does not yet allow you to customize this file.  Similarly ports shared from the container are shared on the host via gvproxy tool.

**Comment by djnotes** [comment]
Is it possible to successfully run docker-compose on Mac with this backend too?
I tried setting DOCKER_HOST with the following, but docker-compose won't work. 
`unix:///Users/mehdi/.local/share/containers/podman/machine/podman-machine-default/podman.sock`

**Comment by rhatdan** [comment]
You would probably be better off asking these questions on podman not podman desktop.

**Comment by rhatdan** [comment]
@ashley-cui @baude PTAL

**Comment by slemeur** [comment]
Since 4.2 when you start a podman-machine it automatically mount your $home folder. 
Enhancements coming to also include the /tmp folder : https://github.com/containers/podman/issues/16447
