### ISSUE TITLE
[Linux Flatpak 0.14.1] Compose status should change after installation

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2120]
### Bug description

"Docker Compose v.2.17.2 installed" but the "Install Compose" status stays.

### Operating system

Linux

### Version

0.14.1

### Steps to reproduce

1. Click **Compose** in the status bar.
2. Select any version.
3. Close the **Docker Compose v.2.17.2 installed** dialog
4. The **Compose** item in the status bar still prpoposes to install Compose.

### Additional context

![Screenshot from 2023-04-17 11-12-30](https://user-images.githubusercontent.com/243761/232440055-577ba3d9-3385-4a83-9adb-d860cb0e4b60.png)

**Comment by benoitf** [comment]
compose has been reworked since this bug
