### ISSUE TITLE
Compose dialogue indicates installation completed when escaped/canceled.

### ISSUE THREAD

**Issue by komish** [containers/podman-desktop#2126]
### Bug description

The compose modal prompting for a version to be installed still indicates that compose was installed successfully when escaped/canceled. 

### Operating system

RHEL 8.7

### Version

0.14.1

### Steps to reproduce

- Click "Compose" in the bottom left-hand corner. Observe the version prompt pop-up asking which version should be installed
- Hit escape to leave the prompt
- Observe "Compose Version <version> has been installed" (Expected nothing to happen because I hit escape).

**Comment by slemeur** [comment]
Thanks for the report @komish.
