### ISSUE TITLE
Process of updating the podman desktop to the newer version has no progress

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2127]
### Is your enhancement related to a problem? Please describe

I tried to update to the latest version (0.14.1) through the UI (click on version/exclamation mark icon in system tray), system native dialog appeared if I want to download and install new version, which is alright, but the I closed/accepted the dialog and nothing... No task, no progress, no background process. It took quite a long time and I do not know what was happening.

### Describe the solution you'd like

It would be nice to have this background operation visible somewhere. Tasks or something. Eclipse IDE has concept of Jobs for example. Tasks would do in our case.

**Comment by deboer-tim** [comment]
We have a task manager now, can use this issue to start using it for update download.

**Comment by deboer-tim** [comment]
I'm currently on what can only graciously be called a shared 3G cellular connection. +1 to this as I have no idea if the download is working or how long until it completes. Should be in the task manager.
