### ISSUE TITLE
macOS: podman machine init and start from Desktop UI fails

### ISSUE THREAD

**Issue by fc7** [containers/podman-desktop#2129]
### Bug description

I installed Podman Desktop on macOS with `brew install podman-desktop` (which also brought podman 4.5.0 as dependency). Instead of doing `podman machine init` on the console, as I have always been doing until now, I did it from the UI. The result was this:
```
Error: Extracting compressed file
Error: key generation failed, unable to read from stderr: exit status 1
```
![Screenshot 2023-04-17 at 13 46 35](https://user-images.githubusercontent.com/85877/232552582-e7a4aa28-5c1a-4f07-b81a-fb244fafff4f.png)

Going to the console instead suggests that the ignition file for the VM is missing: 
```
podman machine list
NAME                     VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        3 minutes ago  3 minutes ago  1           2.147GB     107.4GB
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/Users/xxx/.config/containers/podman/machine/qemu/podman-machine-default.ign: can't load /Users/xxx/.config/containers/podman/machine/qemu/podman-machine-default.ign: Failed to open file “/Users/xxx/.config/containers/podman/machine/qemu/podman-machine-default.ign”: No such file or directory
```

I can remediate the situation by deleting the VM and initializing a new one:
```
$ podman machine rm podman-machine-default

The following files will be deleted:

/Users/xxx/.ssh/podman-machine-default
/Users/xxx/.ssh/podman-machine-default.pub
/Users/xxx/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/xxx/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-37.20230401.2.0-qemu.x86_64.qcow2
/Users/xxx/.local/share/containers/podman/machine/qemu/podman.sock
/Users/xxx/.config/containers/podman/machine/qemu/podman-machine-default.json


Are you sure you want to continue? [y/N] y
$ podman machine init
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
```

### Operating system

macOS Monterey 12.6.5 (Intel)

### Version

0.14.1

### Steps to reproduce

On a fresh system (macOS):
```
brew install podman-desktop
```
Open the Dashboard. 
It says "Podman v4.5.0 is installed but not ready".
Click on "Initialize and Start".

**Comment by slemeur** [comment]
Thanks for the report @fc7 !

**Comment by cdrage** [comment]
> 

Hey @fc7 I tried reproducing this on my Mac (M1):

https://user-images.githubusercontent.com/6422176/234610903-78dcf151-b171-4070-9d3c-c061d6d2f51c.mov

I completely uninstalled podman as well as podman-desktop and reinstalled it via brew like your steps showed (hence why initializing took so long, it also downloaded the new image).

I also tried removing the `.local/share/containers` folder and trying it again with a fresh configuration, and still couldn't reproduce.

Maybe it's because I'm on M1 and not Intel...

Let me know if you experience this issue again. At the moment I'm assuming this error occurred from a messed up qemu configuration, see: https://github.com/containers/podman/issues/12379 Fixes range from qemu reinstall, to `podman machine rm and init` again.

It honestly looks like more of a `podman` issue :(. Let's keep an eye on this though if it occurs again.

**Comment by fc7** [comment]
Hi @cdrage thanks for reporting back. Well, in my case this happened following a fresh install, after I cleaned up my system more or less as you did. But it could be that some garbage from an older qemu setup was still standing in the way. Also, the issue happened on an Intel Macbook, so it does differ from https://github.com/containers/podman/issues/12379 ... Anyway, this is probably not a Podman Desktop issue, I agree. We can agree to close this issue for now. If someone else encounters the same thing, it can be reopened.
