### ISSUE TITLE
Selection of the extension items in the list in settings is misplaced

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2130]
### Bug description

When I select the extension item in Settings -> Extensions the selection tile is placed on different extension item.
![pd-extensions-select](https://user-images.githubusercontent.com/19164299/232681681-ec4c9253-3d86-4228-beef-3cc6c85f5ea1.gif)

### Operating system

Windows 10 Professional

### Version

0.14.1

### Steps to reproduce

See the recording. Condition is that windows is not maximized.

**Comment by deboer-tim** [comment]
Fixed via PR #2221, extensions are now sorted alphabetically and selection works correctly.
