### ISSUE TITLE
Kube context usability issues with Play Kube YAML

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2136]
### Bug description

I didn't realize that my Kube context wasn't set (I had deleted the Kind cluster that it pointed to), and when I tried to Play Kube there was no option to deploy to my running cluster... or any of my other Kubernetes clusters. It was not obvious that I needed to leave, set the context, and try again. We should allow you to change the context here or provide some indication that it's only looking at the current (unset) context.

Likewise, I set the context to a stopped cluster and there's no indication until I click Play and get "Error: connect ECONNREFUSED 127.0.0.1:64424". We should warn the user earlier and likely disable the button when we know it's going to fail.

### Operating system

macOS 13.3 M1

### Version

0.14.1

**Comment by dgolovin** [comment]
There is another use-case, when authentication token used in context expired. That can happen for sandbox cluster, because token is valid for 24 hours.
