### ISSUE TITLE
Error printed when Playing Kubernetes yaml on kubernetes runtime (kind), even though I got it applied

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2137]
### Bug description

I got `error playing kube file Error: the server could not find the requested resource` when trying to choose a yaml file via `Play Kubernetes Yaml`. When I try again -> It says that my deployment already exists suggesting that is was actually applied. First error would point out the problem that file did not exist on the provided path, but that was not true obviously. 

### Operating system

Fedora 37

### Version

0.14.1

### Steps to reproduce

1. Install kind extension
2. Create Kind cluster
3. try to play kubernetes yaml and choose kubernetes runtime

**Comment by slemeur** [comment]
HI @odockal, Do you have the yaml file you tried?

**Comment by odockal** [comment]
![Image](https://user-images.githubusercontent.com/19164299/233103334-1c47c37c-3cb3-4d40-8058-e6f1ab684bb2.gif)

**Comment by odockal** [comment]
@slemeur Should be this one: `https://projectcontour.io/examples/httpbin.yaml`
