### ISSUE TITLE
Prevent creating a Kind cluster on a rootless machine

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2141]
### Is your enhancement related to a problem? Please describe

Creating a Kind cluster on Windows WSL requires rootful mode so we should check before instead of dumping an error from Kind

### Describe the solution you'd like

Refuse the creation of the Kind cluster with a clear explanation of steps that user must follow

**Comment by lstocchi** [comment]
The title says that PD has to prevent users from creating a machine on rootless mode and then the description says that you need rootless. WDYM?
BTW i can create a machine on both rootful and rootless so i don't get this

**Comment by jeffmaury** [comment]
> The title says that PD has to prevent users from creating a machine on rootless mode and then the description says that you need rootless. WDYM? BTW i can create a machine on both rootful and rootless so i don't get this

Description updated

**Comment by lstocchi** [comment]
I still don't get this as you are somehow guided by the logs. Atleast for me, when i tried to use rootless the first time there was a warning regarding the use of cgroup2. After enabling it, it told me to set `Delegate=yes`. With a quick search i found the page on the official kind website -> https://kind.sigs.k8s.io/docs/user/rootless/ . Maybe it's more about adding some documentation.
But by reading the issue what i get is `tell users to switch to rootful when they are rootless`

**Comment by jeffmaury** [comment]
Maybe the title is misleading on Windows/WSL there is no way to make it work in rootless and there are a bunch of errors on Telemetry

**Comment by lstocchi** [comment]
How do you know it doesn't work? I didn't test it much as i was just testing the creation, but i remember that i also pushed a simple deployment/job and i could see the logs.

**Comment by lstocchi** [comment]
If you enable cgroup2 on wsl by creating a `.wslconfig` with
```
[wsl2]
kernelCommandLine = cgroup_no_v1=all
```
then ssh in your machine and follow
```
Create /etc/systemd/system/user@.service.d/delegate.conf with the following content, and then run sudo systemctl daemon-reload:

[Service]
Delegate=yes
(This is not enabled by default because [“the runtime impact of [delegating the “cpu” controller] is still too high”](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZMKLS7SHMRJLJ57NZCYPBAQ3UOYULV65/). Beware that changing this configuration may affect system performance.)

Create /etc/modules-load.d/iptables.conf with the following content:

ip6_tables
ip6table_nat
ip_tables
iptable_nat
```

it worked

**Comment by jeffmaury** [comment]
> If you enable cgroup2 on wsl by creating a `.wslconfig` with
> 
> ```
> [wsl2]
> kernelCommandLine = cgroup_no_v1=all
> ```
> 
> then ssh in your machine and follow
> 
> ```
> Create /etc/systemd/system/user@.service.d/delegate.conf with the following content, and then run sudo systemctl daemon-reload:
> 
> [Service]
> Delegate=yes
> (This is not enabled by default because [“the runtime impact of [delegating the “cpu” controller] is still too high”](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZMKLS7SHMRJLJ57NZCYPBAQ3UOYULV65/). Beware that changing this configuration may affect system performance.)
> 
> Create /etc/modules-load.d/iptables.conf with the following content:
> 
> ip6_tables
> ip6table_nat
> ip_tables
> iptable_nat
> ```
> 
> it worked

Will have to test it on my machine as I was unable to make it work when I tested it.

**Comment by odockal** [comment]
After some tries out and with @lstocchi help I made it run:
* wsl installed on the system with default version 2, we do not need to have distro installed (podman will do that)
* create `.wslconfig` file in your home with this content:
```sh
[wsl2]
kernelCommandLine = cgroup_no_v1=all
```
* Update wsl: `wsl --update`
* Initialize and start podman machine using podman desktop
* in powershell: `podman machine ssh`
* Run with `sudo`:
*   `mkdir /etc/systemd/system/user@.service.d/`
*   Insert this content into `/etc/systemd/system/user@.service.d/delegate.conf`
```sh
[Service]
Delegate=yes
```
* run `systemctl daemon-reload`
* Create `mkdir /etc/modules-load.d`
* Insert content into `iptables.conf`
```sh
ip6_tables
ip6table_nat
ip_tables
iptable_nat
```
* exit the machine
* You probably need to restart podman machine (using podman desktop)
* Now you should be able to create kubernetes cluster using kind with rootless podman machine

**Comment by tqq1994516** [comment]
> After some tries out and with @lstocchi help I made it run:
> 
> * wsl installed on the system with default version 2, we do not need to have distro installed (podman will do that)
> * create `.wslconfig` file in your home with this content:
> 
> ```shell
> [wsl2]
> kernelCommandLine = cgroup_no_v1=all
> ```
> 
> * Update wsl: `wsl --update`
> * Initialize and start podman machine using podman desktop
> * in powershell: `podman machine ssh`
> * Run with `sudo`:
> * `mkdir /etc/systemd/system/user@.service.d/`
> * Insert this content into `/etc/systemd/system/user@.service.d/delegate.conf`
> 
> ```shell
> [Service]
> Delegate=yes
> ```
> 
> * run `systemctl daemon-reload`
> * Create `mkdir /etc/modules-load.d`
> * Insert content into `iptables.conf`
> 
> ```shell
> ip6_tables
> ip6table_nat
> ip_tables
> iptable_nat
> ```
> 
> * exit the machine
> * You probably need to restart podman machine (using podman desktop)
> * Now you should be able to create kubernetes cluster using kind with rootless podman machine

Following your steps, my local wsl 2 can indeed be used.✔️
But the following problem occurred when starting the cluster
```
Command Output: Your kernel does not support pids limit capabilities or the cgroup is not mounted. PIDs limit discarded.
Error: crun: cgroups in hybrid mode not supported, drop all controllers from cgroupv2: OCI runtime error
```
