### ISSUE TITLE
Kind clusters not cleaned up when stopping podman machine

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2143]
### Bug description

When I stop the podman machine that's hosting my Kind clusters, they don't get cleaned up. I thought I saw several left one time, but when testing repeatedly there seems to always be one Kind cluster remaining, and it's the one my Kube context points to.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create a couple Kind clusters on podman, then stop the machine. (my Kind clusters were all stopped first, I assume that shouldn't make a difference) I always have one Kind cluster still listed; seems to be whatever is on the Kube context.

**Comment by benoitf** [comment]
reopening as it caused a regression (fix has been reverted)

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/2439
