### ISSUE TITLE
DevSandbox: Add API to customize resource provider button

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2147]
It would be nice to be able to customize the button label on the buttons that appear on the left hand side of provider rows on the Settings > Resources screen.

For Developer Sandbox, semantically it makes more sense to label the button "Connect" than "Create New." The user won't actually create the DevSandbox inside of the Podman Desktop UI, that is something they would (for now) create externally on the Developer Sandbox website. In Podman Desktop they will be simply connecting that pre-existing resource to Podman Desktop.

Filing this as an enhancement to Podman Desktop since other extensions could make use of this feature to customize the button.

Relevant code is here:
https://github.com/containers/podman-desktop/blob/30b5d120d97090bcbe2aafcc0ddf80f4e7037432/packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte#L253

![Image](https://user-images.githubusercontent.com/799683/232869892-d4527e8b-31c7-4ea8-b0b2-a40a4b4c5457.png)

**Comment by deboer-tim** [comment]
I'm onboard with changing/customizing the button, but not entirely sure what I think it should be long term. I'm wondering if extensions that need authentication could indicate it and this would start as a `Log in` button. Then once you've logged in we'd detect any existing sandbox, and if there are none we'd keep it as `Create new`.
