### ISSUE TITLE
podman-desktop sees a single machine

### ISSUE THREAD

**Issue by chevdor** [containers/podman-desktop#2150]
### Bug description

I started with a podman machine setup close to the default one with 2GB memory.
I then created a second, this time with 3GB in order to see the issue.

After the creation of the second, the new machine is seen with the specs of the 1st. Starting ONE machine will appear to start both.

I attach a screenshare that shows the issue in action.

![IssuePodmanDesktop mov](https://user-images.githubusercontent.com/738724/233003535-fb81d3f7-0557-4e4e-b9bc-78769c9f1c13.gif)

What is not show in the screenshare is that after start, I switched tabs again and then BOTH machines were shown with 3GB of memory.

### Operating system

macOS ventura 13.3.1

### Version

0.14.1

### Steps to reproduce

I guess the issue does not show up by default and I provided a screenshare. I am not sure how to get a new system in this state.

**Comment by chevdor** [comment]
Here we see that podman itself does see the machines correctly:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/738724/233005459-10615ab3-f3b8-4460-a657-3fc37c5fd022.png">

**Comment by chevdor** [comment]
I uninstalled and reinstalled `podman-desktop` without success.
I see the issue also when the machines are created via `podman machine` instead of `podman-desktop`.

I just created 3 machines:
```
$ podman machine ls
NAME                     VM TYPE     CREATED             LAST UP             CPUS        MEMORY      DISK SIZE
tmp                      qemu        About a minute ago  About a minute ago  1           2.147GB     107.4GB
no-tmp                   qemu        2 minutes ago       2 minutes ago       1           2.147GB     107.4GB
podman-machine-default*  qemu        3 minutes ago       3 minutes ago       4           33.55GB     107.4GB
```

They wrongly show up as:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/738724/233018514-d57ee16c-dbc5-4a11-8ea9-93f46710cbe5.png">

So it looks like it shows only the cpu/memory (and probably uses the ID) of the LATEST created machine instead of the proper one.

**Comment by chevdor** [comment]
Starting a machine from the UI does work and it starts the right machine but the UI ends up looking wrong again:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/738724/233020284-00a573c6-3d81-4a28-9490-4f6e4ea92b7e.png">

NOTE: I did not re-create the machines. Notice however that now the number of CPUs and the Memory changed!

**Comment by chevdor** [comment]
Also, only one machine, obviously, is running:
```
podman machine list
NAME                     VM TYPE     CREATED         LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        12 minutes ago  Currently running  4           33.55GB     107.4GB
tmp                      qemu        9 minutes ago   9 minutes ago      1           2.147GB     107.4GB
no-tmp                   qemu        10 minutes ago  10 minutes ago     1           2.147GB     107.4GB
```

despite what the UI is showing.

**Comment by slemeur** [comment]
probably linked to #2096

**Comment by chevdor** [comment]
That seems close but unrelated to me. I have tested `podman system connection list` a few times and the `podman` cli seems to remain in sync properly. A small delay in the Desktop app is understandable and I can see the App picking up updates but the data it gets or how they are used to refresh the UI is wrong.

**Comment by odockal** [comment]
I have reproduced the issue. When I have one podman machine running and I create a new one and start it, the former "takes over" the values (cpu, memory) from second one and now they appear almost the same, except the name in the UI. The cli confirms that this is podman desktop issue.

**Comment by jeffmaury** [comment]
Can't reproduce on Windows/WSL ? @cdrage can you give it a try on MacOS ?

**Comment by cdrage** [comment]
> Can't reproduce on Windows/WSL ? @cdrage can you give it a try on MacOS ?

I'm unable to reproduce it either on M1. 

Could you take a video @odockal ?

**Comment by EgorPopelyaev** [comment]
I could also reproduce it. Running on MacOs Ventura 13.3.1. Exactly the same behaviour, after the second machine has started, the first one took over it's settings.
<img width="817" alt="Screenshot 2023-04-24 at 18 11 02" src="https://user-images.githubusercontent.com/6053182/234054679-dea8a694-c306-460d-8936-763cd06bab7a.png">

**Comment by odockal** [comment]
@cdrage yep: It is an intel chip.
![macos-ventura-two-podman-machines](https://user-images.githubusercontent.com/19164299/234280962-c7b6562d-17df-4f3f-8e23-3981ea44e16c.gif)

**Comment by odockal** [comment]
Other symptoms with probably the same root cause can be seen in #2178.

**Comment by cdrage** [comment]
@odockal are you still experiencing this issue?

I've tried:
- Mac M1 (unable to reproduce)
- Linux VM Fedora 36 (unable)
- Windows 10 Enterprise (unable)

However, I ran into a really odd different issue where PD was able to stop, but `podman machine list` still shows it running.

When running `podman machine stop` as well with the Podman CLI, it *still* showed it was running, pointing to an upstream issue:

```
▶ podman machine stop
Machine "podman-machine-default" stopped successfully

~
▶ podman machine list
NAME                      VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*   qemu        4 days ago     Currently running  1           2.147GB     107.4GB
podman-machine-default-2  qemu        2 minutes ago  2 minutes ago      1           2.147GB     107.4GB
```

@odockal from the screenshot it shows you are running `0.14.1`, can you try again with podman 4.5 and our newest podman desktop?

**Comment by odockal** [comment]
@cdrage On it.

**Comment by odockal** [comment]
@cdrage Still can be seen on Mac OS 13 intel using 0.15.0. Do not forget this is Mac only issue - maybe even Mac OS Intel specific.

**Comment by benoitf** [comment]
should be fxed by https://github.com/containers/podman-desktop/pull/2441

**Comment by chevdor** [comment]
I did test with #2441 and that looks good now 👍
