### ISSUE TITLE
Resources: Provider API should let to show explanation with links/buttons for the 'Create new ...' form

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#2152]
### Is your enhancement related to a problem? Please describe

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/620330/233011011-e391026c-44c6-4aea-b9d6-00ef0a14cd49.png">

### Describe the solution you'd like

package.json configuration/properties section should have attributes to define documentation text and link/buttons for the the specific scope

**Comment by benoitf** [comment]
@dgolovin it's correct to assume you'll register a Kubernetes Connection Factory ?

**Comment by benoitf** [comment]
what is the button link that you'll need to open ? is it an external link or a command of the extension to invoke ?

**Comment by jeffmaury** [comment]
> what is the button link that you'll need to open ? is it an external link or a command of the extension to invoke ?

External link to login into Sandbox

**Comment by benoitf** [comment]
ok I assumed that.

**Comment by dgolovin** [comment]
It should be https://developers.redhat.com/developer-sandbox
