### ISSUE TITLE
Support extensions with dependencies

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2160]
### Is your enhancement related to a problem? Please describe

Some extensions require another extension, or need to be installed along with another for full support. If you don't install the other extension there is no feedback or easy way to find the dependency.

### Describe the solution you'd like

One of two solutions:
1. Extensions can declare dependencies (other extensions) and both are pulled in when you do the install.
2. Extension packs - allow extensions that are really just a container for a set of extensions.

- [x] https://github.com/containers/podman-desktop/issues/2814
- [x] https://github.com/containers/podman-desktop/issues/2828
- [x] https://github.com/containers/podman-desktop/issues/2829

**Comment by benoitf** [comment]
There is no catalog/marketplace for now so we can't automatically pull dependencies for now

For now we could report that a missing dependency is not there or start the extensions in the expected order as well
