### ISSUE TITLE
No feedback from 'Push image to Kind', and fails

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2166]
### Bug description

Going to an image and selecting `Push image to Kind cluster` provides zero feedback. It should probably use the task manager (which I know is not available to extensions yet).

If I have more than one Kind cluster, it's not clear which it would act on. Probably needs a selection or prompt.

In my case I was able to confirm it was doing _something_ via log events, but it looks like it does a save and then fails on an exec against Kind.

### Operating system

macOS 13.3 M1

### Version

0.14.1

**Comment by benoitf** [comment]
I think there is a feedback but only on Windows (notifications) 
I thought we've already an open issue for that but I don't find it again

**Comment by cdrage** [comment]
I've created https://github.com/containers/podman-desktop/pull/23612 to add a form of error / success notification until we have taskbar added to our extensions API.
