### ISSUE TITLE
Persistent icon bar for main nav

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2167]
This idea came from the discussion on: https://github.com/containers/podman-desktop/pull/1945

<img width="359" alt="normal" src="https://user-images.githubusercontent.com/19958075/233139066-57fffb66-1695-46bb-b856-dbc8f3c99454.png"> <img width="359" alt="settings" src="https://user-images.githubusercontent.com/19958075/233139130-17c2d5d6-51a3-4244-8984-8198719a5813.png">

Right now when you are in Settings, you lose the ability to hop back into the main nav. It would be better when you are in settings to have the main nav in iconified form on the far left of the screen. This would mean less clicks to navigate out of Settings.

**Comment by deboer-tim** [comment]
I just want to be clear - are you ok with removing the main nav labels entirely (i.e. always iconified with tooltips), or just when using settings/narrow window?

**Comment by mairin** [comment]
@deboer-tim Yep! As long as they have tooltips!

**Comment by mairin** [comment]
We reviewed https://github.com/containers/podman-desktop/pull/2173 in the UX call this morning, some feedback:

- [x] We should have a separator for the extension icons vs. the main nav icons
- [x] Add to the tooltip, the number of items in each component (e.g., for containers, "Containers (15)" w/ the number of containers)
- [ ] Change the background color of the currently-open nav item to the same bg color as the content area canvas (which is right now charcoal-600)
- [ ] Better contrast between the currently-open nav item and other items (colorize active icon purple maybe?) Extension icons are colored vs the default icons being one color, so the extension icons draw the eye too much 
- [ ] Improve scaling for extensions (eg maybe limit to 5-7 icons and then require a pop out submenu to access more.) And not have a scrollbar in the nav.

**Comment by deboer-tim** [comment]
Marked off the first two items as done via PR #2173.

**Comment by deboer-tim** [comment]
@mairin updated the colors in recent PRs in 0.15, which provided an alternative to the third item. There are two items left, which have been split out into their own issues:
- Issue #2229
- Issue #2353 

Since the remaining points are covered in other issues, I'm going to close this issue as delivered in 0.15 and we can track the remaining work there.
