### ISSUE TITLE
Compose: Compose extension should ask to create a symlink to ~/.docker/run/docker.sock

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2169]
### Is your enhancement related to a problem? Please describe

Compose is one of the few clients that still checks and runs from `~/.docker/run/docker.sock` by default rather than `/var/run/docker.sock`

When using `docker-compose` and Podman Desktop with compatibility enabled, you still won't be able to run `docker-compose` by default:

```
~/Downloads                                                                                                                                                                                       ⍉
▶ docker-compose up
Cannot connect to the Docker daemon at unix:///Users/cdrage/.docker/run/docker.sock. Is the docker daemon running?
```

You must make a symlink from /var/run/docker.sock which is created with `podman-mac-helper`.

And only then will it work.

### Describe the solution you'd like

Add a prompt to ask the user if we want to create a symlink from `/var/run/docker.sock` (or the podman socket depending on OS) to ~/.docker/run/docker.sock`.

**Comment by fc7** [comment]
Just a side-note: the above issue does not appear to occur on macOS when using `sudo podman-mac-helper install`. In my case the symlink was automatically created:
```
$ ls -la /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  61 Apr 17 13:46 /var/run/docker.sock -> /Users/xxx/.local/share/containers/podman/machine/podman.sock
```

**Comment by cdrage** [comment]
> Just a side-note: the above issue does not appear to occur on macOS when using `sudo podman-mac-helper install`. In my case the symlink was automatically created:
> 
> ```
> $ ls -la /var/run/docker.sock
> lrwxr-xr-x  1 root  daemon  61 Apr 17 13:46 /var/run/docker.sock -> /Users/xxx/.local/share/containers/podman/machine/podman.sock
> ```

What version of compose are you running? 

```
~/Downloads                                                                   ⍉
▶ docker-compose version
Docker Compose version v2.17.3

~/Downloads
▶ docker-compose up
Cannot connect to the Docker daemon at unix:///Users/cdrage/.docker/run/docker.sock. Is the docker daemon running?
```

Is my version and by default it will always check `.docker/run/docker.sock`.

**Comment by benoitf** [comment]
I would expect to have that managed by the podman Mac helper client, not podman desktop
https://github.com/containers/podman/issues/16548

**Comment by cdrage** [comment]
> Just a side-note: the above issue does not appear to occur on macOS when using `sudo podman-mac-helper install`. In my case the symlink was automatically created:
> 
> ```
> $ ls -la /var/run/docker.sock
> lrwxr-xr-x  1 root  daemon  61 Apr 17 13:46 /var/run/docker.sock -> /Users/xxx/.local/share/containers/podman/machine/podman.sock
> ```

Ah, it may be because you're running `podman-compose` instead of `docker-compose` ?

By default if docker-compose is unable to find a docker daemon, it'll try the local socket rather than the global `/var/run/docker.sock` first. This occurs on both macOS and Linux platforms.

**Comment by fc7** [comment]
> Ah, it may be because you're running podman-compose instead of docker-compose ?

Yes, I have both podman-compose and docker-compose. So you mean the symlink was created by podman-compose, not by the podman-mac-helper?

**Comment by cdrage** [comment]
> > Ah, it may be because you're running podman-compose instead of docker-compose ?
> 
> Yes, I have both podman-compose and docker-compose. So you mean the symlink was created by podman-compose, not by the podman-mac-helper?

Nope, not symlink. 

It's because `podman-compose` by default checks /var/run/docker.sock. But `docker-compose` checks ~/.docker/run/docker.sock.

podman-compose works fine, but the issue is docker-compose does not work correctly at the moment / you require to create a symlink.

**Comment by fc7** [comment]
Funny, I do not have `~/.docker/run/docker.sock` but docker-compose works perfectly fine in my case.

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.
