### ISSUE TITLE
Items appear duplicated in the UI when more than one podman machine exists

### ISSUE THREAD

**Issue by fc7** [containers/podman-desktop#2178]
### Bug description

After I created a second podman machine, I noticed that all objects appear duplicated in the UI.
Also even though only the default VM is running, both VMs are displayed with status "running":
<img width="886" alt="Screenshot 2023-04-20 at 07 47 40" src="https://user-images.githubusercontent.com/85877/233320254-0a9fb861-44b3-4386-b8f5-700fb2388eec.png">
In such a scenario, all containers, pods, images and volumes are duplicated in the UI lists.

I have not tested this, but I suspect that if I had created a third VM, each object would appear three times!

### Operating system

macOS Monterey 12.6.5 (Intel)

### Version

0.14.1

### Steps to reproduce

Initialize a second machine with `podman machine init foo`, but leave the default one running.

Then all objects should appear duplicated in the UI.

**Comment by odockal** [comment]
I have reproduced the issue. When I have one podman machine running and I create a new one and start it, the former "takes over" the values (cpu, memory) from second one and now they appear almost the same, except the name in the UI. The cli confirms that this is podman desktop issue.

**Comment by odockal** [comment]
Looks like duplicate of #2150.

**Comment by fc7** [comment]
The thing is, in my case I created a second machine but did NOT start it. Only the default podman machine was running at any time. Still the PD UI mistakenly displays both podman machines with a status of "Running".

**Comment by fc7** [comment]
@odockal you are right, but issue #2150 does not raise the main issue I brought up here, namely that all objects are duplicated in the lists.

First I only have one podman machine:
```
podman machine list
NAME                     VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        3 days ago     Currently running  1           2.147GB     107.4GB
```

and the UI looks like this:
<img width="831" alt="Screenshot 2023-04-20 at 18 04 33" src="https://user-images.githubusercontent.com/85877/233424114-8bb07b27-f822-4096-aa30-3d254ee7d620.png">

Then if I do 
```
podman machine init dummy
```
but without starting the vm, the UI will suddenly look like this:
<img width="825" alt="Screenshot 2023-04-20 at 18 06 05" src="https://user-images.githubusercontent.com/85877/233424325-7689c01b-a9c3-46c0-a825-e0baa26f2d59.png">

Note that the number of items has doubled!

**Comment by odockal** [comment]
I see, my bet will be the same root cause. So the fix should solve both symptoms.

**Comment by benoitf** [comment]
fixed
