### ISSUE TITLE
Design: updated design for podify form

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2183]
The podify form is a bit behind the current design and looks a little out of place, need some design tweak options / quick fixes so it looks more integrated.

WIP for context (WIP on left, current screenshot from main on right)

![Image](https://user-images.githubusercontent.com/799683/233415266-b7a2c765-4665-41f9-8725-fbf00bf9d933.png)

**Comment by mairin** [comment]
Nit to address on this one.... it always suggests "my-pod" for the name of the pod, which after the first pod you create causes it to fail since it already exists 🤦🏻‍♀️ We should put more entropy into this

**Comment by mairin** [comment]
(unfocused input)
![Podify](https://user-images.githubusercontent.com/799683/234391066-060a954f-97bd-4815-a9a3-2898ea1709f5.png)

(focused input)
![Podify (1)](https://user-images.githubusercontent.com/799683/234391069-fdaa1821-987f-4616-9b17-4ae7b43ee791.png)

@lstocchi do you think this is doable?

**Comment by lstocchi** [comment]
@mairin done at #2232 👍

**Comment by lstocchi** [comment]
@mairin i think we can close this. ??
