### ISSUE TITLE
Updating external extensions

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2184]
### Is your feature request related to a problem? Please describe

Currently the Podman extension is built in and auto-updated along with Podman Desktop, but there is no notification or auto-update for external extensions.

### Describe the solution you'd like

We need to decide on a mechanism, e.g. either:
- notifying the user when there is a new extension version and allowing them to update extensions individually
- automatically installing newer versions of extensions, maybe on restart
- using a similar update mechanism to Podman Desktop itself, or updating at the same time

**Comment by mairin** [comment]
**"automatically installing newer versions of extensions, maybe on restart"** <= this could be a good setting to have in preferences.

**Comment by themr0c** [comment]
Related: using the **Install a new extension from OCI Image** to update an image fails https://github.com/containers/podman-desktop/issues/2626
