### ISSUE TITLE
Dashboard not refreshing podman detection.

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [containers/podman-desktop#2192]
### Bug description

Fresh install, no podman, dashboard notified couldn't find. So downloaded and installed it. Dashboard still displays after install it was not able to find installation. Yet, if you click "View detection checks" then it says it's installed.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/12997114/233733862-0cf7bde9-1700-4e2d-a4d7-195d9fc1d6a1.png">

It should switch to the initializing after installation and detection of podman.

### Operating system

Mac OS Ventura 13.3.1

### Version

0.14.1

### Steps to reproduce

Fresh install from website.

**Comment by slemeur** [comment]
Thanks for the report.
I'm seeing similar issues too. with version 0.15-next
<img width="1162" alt="Capture d’écran 2023-04-28 à 11 50 58" src="https://user-images.githubusercontent.com/1636769/235146000-6dcdfc27-6fff-4a82-99cf-e85a86196cc8.png">

**Comment by slemeur** [comment]
might be related to #2268

**Comment by slemeur** [comment]
related to #1498

**Comment by benoitf** [comment]
@ST33LDI9ITAL you may restart Podman Desktop to fix the issue or press <kbd>Command</kbd>+<kbd>R</kbd> to reload client side
