### ISSUE TITLE
OCI permission denied

### ISSUE THREAD

**Issue by francoism90** [containers/podman-desktop#2193]
### Bug description

I cannot open terminals of containers when using Podman Desktop:
```bash
Error: crun: setns(pid=***, CLONE_NEWUSER): Operation not permitted: OCI permission denied
```
Sometimes it works fine, sometimes I get this error.
Any idea what could cause this?

I can enter the container's shell just fine:
```bash
$ podman exec -it container_name /bin/sh
```

Thanks

### Operating system

Fedora Silverblue 38

### Version

0.14.1 (Flatpak)

### Steps to reproduce

1. Run containers with `podman-compose up -d`
2. Launch Podman Desktop
3. Open Terminal tab of the container

### Relevant log output

```shell
Error: crun: setns(pid=***, CLONE_NEWUSER): Operation not permitted: OCI permission denied
```

**Comment by jeffmaury** [comment]
Does it happen with every image / container ?

**Comment by francoism90** [comment]
@jeffmaury Yes, it seems closing the application (without minimize to tray) and re-opening it, brings it back to live and I can access the terminals again.

I'll close this ticket for now, maybe I did kill a process or something?
Will keep an eye on this one.

Thanks for your reply.

**Comment by jeffmaury** [comment]
Thank you for helping us making podman desktop better
