### ISSUE TITLE
Images not refreshing automatically

### ISSUE THREAD

**Issue by kdubois** [containers/podman-desktop#2198]
### Bug description

The images view doesn't automatically show newly created images (I have to hit ctrl+r to refresh).  

(Here's a demo where this happens -> https://youtu.be/3V4H3mwCrWs?t=282)

### Operating system

Linux Fedora 37 (6.1.14-200.fc37.x86_64)

### Version

0.14.1

### Steps to reproduce

start podman desktop, go to images view.  Create a new container image somewhere else (in my case in the CLI), go back to podman desktop and notice that the new image is not showing up until you manually refresh with ctrl + r.

**Comment by benoitf** [comment]
hi @kdubois is it possible to get the events that you have in your dev console (menu View/Toggle Developer tools, console)
when you're creating your container elsewhere ?

**Comment by kdubois** [comment]
Interestingly enough now it seems to work correctly ...  let's see if I can reproduce it again

**Comment by benoitf** [comment]
@kdubois yep, as soon as you're able to reproduce, look at the logs so we may see if there was an error handling all events

**Comment by kdubois** [comment]
FYI - I haven't been able to reproduce it anymore.  I'll go ahead and close the issue and reopen if I do run into it again.

**Comment by slemeur** [comment]
linking to #2321 and #2310
