### ISSUE TITLE
Unable to install OpenShift Local extension due to missing podman environment to pull/extract the external extension

### ISSUE THREAD

**Issue by phillipstr** [containers/podman-desktop#2200]
### Bug description

I am running Podman on Openshift local, installed following [these](https://podman-desktop.io/docs/Installation/windows-install/installing-podman-with-openshift-local) instructions. WSL2 is not allowed in this environment.

Podman CLI works as expected, however, Podman Desktop v0.14.1 does not show any references to CRC. In Desktop v0.11.x the CRC extension was installed by default, and I could start a Desktop provider on it. 

I found the CRC extension [here](https://github.com/crc-org/crc-extension/pkgs/container/crc-extension), but I cannot install it because no provider is running. Feels a bit like a chicken/egg situation where I can't start a provider because I don't have the CRC extension, but I can't install the CRC extension because I don't have a running provider.

I believe that including the CRC extension with the Podman Desktop install would resolve this.

CRC Details:
```powershell
PS C:\WINDOWS\system32> crc version
CRC version: 2.17.0+44e15711
OpenShift version: 4.12.9
Podman version: 4.4.1
PS C:\WINDOWS\system32> crc config get preset
preset : podman
```

### Operating system

Windows 10.0.19044

### Version

0.14.1

### Steps to reproduce

1. Install Podman Desktop and Openshift Local, following [these](https://podman-desktop.io/docs/Installation/windows-install/installing-podman-with-openshift-local) instructions
2. Launch Podman Desktop
3. Go to Settings > Extensions
4. Attempt to install [CRC](https://github.com/crc-org/crc-extension/pkgs/container/crc-extension)

### Additional context

Installation screenshot:
![image](https://user-images.githubusercontent.com/38966430/234002236-1d028924-4c51-412c-b8f0-47866cc44133.png)

v0.11.x Default Extensions:
![image](https://user-images.githubusercontent.com/38966430/234001950-507a94b9-5422-40e5-8ccf-925bca6a3d18.png)

**Comment by gbraad** [comment]
What you see is a known extension installation issue. To install PD extensions, the end user should have a running and working podman. This will be addressed, but I can not provide an ETA.

---
**As the CRC Team lead**: as I notice you are using the `podman` preset; The CRC-extension will at this moment not 'support' the podman preset. We made this decision to focus on OpenShift first, with a possible Microshift option. At a later moment, we might be able to add more around podman.

Podman Machine is looking into supporting Hyper-V instead (besides WSL2). We are currently testing this for them.

**Comment by gbraad** [comment]
The problem

**Comment by gbraad** [comment]
@phillipstr This has been addressed.
