### ISSUE TITLE
Kube: Show in UI connection errors

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2204]
### Is your enhancement related to a problem? Please describe

If we're unable to connect to our Kubernetes cluster given a kubecontext, we should show in the UI a warning that we're unable to connect as well as show an error.

Brought up in: https://github.com/containers/podman-desktop/pull/2171#pullrequestreview-1397526747

### Describe the solution you'd like

A warning in the statusbar with the error of why we cannot connect to the Kubernetes cluster.

**Comment by deboer-tim** [comment]
It's possible that this should be in more places or UI will evolve, but this was fixed by #6102.
