### ISSUE TITLE
Kind: Open Browser error: Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2217]
### Bug description

**Pods > Open Browser** opens a link to the browser prefixed by http when it should be https.

### Operating system

Linux

### Version

next (development version)

### Steps to reproduce

1. Start a kind cluster.
2. Go to **Pods > Open Browser**.
3. The link opens http://localhost:43829/ or similar in the browser.
4. The browser displays the error 
   ```
   Client sent an HTTP request to an HTTPS server.
   ```

**Comment by benoitf** [comment]
closing as won't fix
Also it might no longer be the case anymore and nobody reported the issue
