### ISSUE TITLE
Dashboard is empty when there are no providers

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2218]
### Bug description

When there are no providers (e.g. stop the Kind, Podman extensions) the Dashboard is completely blank. We should implement an 'empty screen' as in other places.

### Operating system

macOS 13.3 M1

### Version

next (development version)

**Comment by slemeur** [comment]
not sure how often that case will appear - but once the onboarding sequence is implemented, we could default to restart that sequence?

**Comment by deboer-tim** [comment]
Agreed, this is minor. In my case I think I was testing start/stop extensions and just happened into a case where there were no providers running and things were oddly blank. Not a case where onboarding would have been appropriate, but by the time we do some other widgets on the dashboard maybe this will be irrelevant.

**Comment by mairin** [comment]
Oh there is a design for this one (apologies for the outdated nav):

![Empty List Message Scratch (1)](https://github.com/containers/podman-desktop/assets/799683/e798b1b4-4393-46f6-bc98-faf17a98edbd)

Then, depending on which one you choose, you run through the onboarding wizard screens embedded in the Settings area, eg here is how it could look if you selected Podman and clicked on the "I already have Podman" link:
![Podman Not Installed (2)](https://github.com/containers/podman-desktop/assets/799683/75e15403-b8fc-4d20-bcb9-cae4b00fbb3a)

**Comment by benoitf** [comment]
closing as won't fix
it looks like a corner case that was not reported by anyone else since the creation of the issue
