### ISSUE TITLE
Pull image with trailing spaces fails

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2227]
### Bug description

If you specifiy an image name with trailing spaces it fails

![image](https://user-images.githubusercontent.com/695993/234506847-1be62d70-a16c-45dd-aadf-0cba16dc8e9f.png)

### Operating system

Win11 Pro

### Version

0.14.1

### Steps to reproduce

Use "registry.access.redhat.com/ubi8/ubi-minimal:latest "

**Comment by deboer-tim** [comment]
Fixed via PR #2244.
