### ISSUE TITLE
`Play Kubernetes Yaml` doesn't honor the runtime selection

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2228]
### Bug description

I have a simple k8s deployment file https://github.com/praveenkumar/simple-go-server/blob/main/kubernetes/deploy.yaml which consist of core k8s component like namespace, pod and service. I select `Pods` => `Play kubernetes Yaml` and chose the runtime as `kind` but when I chose the runtime it by default select the `namespace` and there is no option to deselect it. Since my resource create a demo namespace first time it fails and then I again try it doesn't use the `kind` runtime.

<img width="941" alt="Screenshot 2023-04-26 at 1 58 52 PM" src="https://user-images.githubusercontent.com/410007/234516866-05f718be-ee57-4e98-acdd-0aa37ca7f674.png">

### Operating system

13.3.1 (22E261) (M1)

### Version

0.14.1

**Comment by praveenkumar** [comment]
In case using the different context like microshift I am hitting following.

<img width="1157" alt="Screenshot 2023-04-26 at 4 08 19 PM" src="https://user-images.githubusercontent.com/410007/234550756-b5da427c-adf9-4d5b-a9e1-c57e615848ef.png">

**Comment by benoitf** [comment]
@praveenkumar do you still reproduce the issue ?

Connection refused issue has been fixed

**Comment by praveenkumar** [comment]
@benoitf https://github.com/containers/podman-desktop/issues/2228#issuecomment-1523201199 is fixed but I have to check if the yaml content the namespace resource does it work or not, will try latest build and comment.

**Comment by praveenkumar** [comment]
@benoitf so the original issue still present if the k8s yaml have namespace resource it fails with following error message.

<img width="1024" alt="Screenshot 2023-05-16 at 9 02 33 AM" src="https://github.com/containers/podman-desktop/assets/410007/09259dfb-c0f4-49cd-b528-0f2af7384911">

And when I again try it says that `demo` namespace already exist.

<img width="1009" alt="Screenshot 2023-05-16 at 9 04 25 AM" src="https://github.com/containers/podman-desktop/assets/410007/4ba47c21-3578-4ffc-ad45-829fd9a3f0d7">

And there is no resource in the demo namespace.
```
✗ oc get all -n demo
No resources found in demo namespace.
```
