### ISSUE TITLE
`Push Image to kind cluster` is not working

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2231]
### Bug description

I have an image `registry.access.redhat.com/ubi8/go-toolset:latest` and I wanted to use it in kind cluster so I use that `push image to kind cluster` button but I didn't get that image to the kind cluster, Also there is not feedback around any error.
<img width="966" alt="Screenshot 2023-04-26 at 2 27 34 PM" src="https://user-images.githubusercontent.com/410007/234524558-57a62174-10fc-48ec-98f2-dc61ac68c03f.png">

```
 podman exec kind-cluster-control-plane crictl images
IMAGE                                                     TAG                 IMAGE ID            SIZE
docker.io/envoyproxy/envoy                                v1.25.2             8663724adc98f       51.7MB
docker.io/kindest/kindnetd:v20230330-48f316cd             <none>              43ef1c5209cd9       25.3MB
registry.k8s.io/coredns/coredns                           v1.9.3              b19406328e70d       13.4MB
docker.io/kindest/local-path-helper:v20230330-48f316cd    <none>              e5f9a0a1ed364       2.92MB
docker.io/kindest/local-path-provisioner:v0.0.23-kind.0   <none>              9eda906092e57       16.6MB
ghcr.io/projectcontour/contour                            v1.24.2             a8894204792ae       13.4MB
registry.k8s.io/etcd                                      3.5.6-0             ef24580282403       80.5MB
registry.k8s.io/kube-apiserver                            v1.26.3             92e90fc362928       78MB
registry.k8s.io/kube-controller-manager                   v1.26.3             96fd77e7825a4       66.7MB
registry.k8s.io/kube-proxy                                v1.26.3             53df69d2174ba       63.4MB
registry.k8s.io/kube-scheduler                            v1.26.3             9c689f0fff925       56.3MB
registry.k8s.io/pause                                     3.7                 e5a475a038057       268kB
```

### Operating system

13.3.1 (22E261) (M1)

### Version

0.14.1

**Comment by jeffmaury** [comment]
Adding that it seems to be MacOS specific as I did not face the issue on Windows 11 Pro

**Comment by odockal** [comment]
On linux this works as well. I pulled image `docker.io/redis` via podman desktop, and run "Push image to Kind".

**Comment by deboer-tim** [comment]
Is this just a dupe/another case of issue #2166?

**Comment by praveenkumar** [comment]
On the mac when I try with dev console, I see following error. 

<img width="541" alt="Screenshot 2023-05-03 at 12 46 10 PM" src="https://user-images.githubusercontent.com/410007/235853124-d4b7e8bc-ca2f-46c8-bfcc-fcecfe09fc6b.png">

**Comment by cdrage** [comment]
Unfortunately I wasn't able to reproduce on M1.

However, I created this PR: https://github.com/containers/podman-desktop/pull/2361 in order to refactor as well as add a notification for when it has successfully pushed the image or failed.

Can you pull the PR @praveenkumar and try again?

I have a weird suspicion it *may* be a `kind` binary issue since we're running the CLI straight from podman desktop, and the PR helps create some additional logging to figure out why it may be going wrong.

**Comment by benoitf** [comment]
duplicate of https://github.com/containers/podman-desktop/issues/2447
