### ISSUE TITLE
List of extensions hide action with reduced application width

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2238]
### Bug description

In the case of a reduced with, the actions on the list of extensions are getting hidden.

<img width="1033" alt="Capture d’écran 2023-04-24 à 16 53 36" src="https://user-images.githubusercontent.com/1636769/234572608-6bb189bc-0533-4c59-8ec6-75751ebb4a4a.png">

And there is no way to horizontaly scroll eventually.

With enough width, it's properly  showing the actions on the right of each extensions:
<img width="1366" alt="Capture d’écran 2023-04-24 à 16 53 41" src="https://user-images.githubusercontent.com/1636769/234572890-2504a96f-5143-4c3f-a371-006831fe2665.png">

### Operating system

Ventura

### Version

0.14.1

### Steps to reproduce

reduce width of the application when on the list of extensions

**Comment by deboer-tim** [comment]
This has already been fixed for 0.15 via PR #2098.

**Comment by slemeur** [comment]
👍
