### ISSUE TITLE
Containers created inside pod are exposing ports from all containers

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2240]
### Bug description

I create 2 containers (docker.io/kennethreitz/httpbin) mapping ports 9000 and 9001 to 80 respectively

Then I created a pod from those 2 pods, the pod gets created but each of the created container is having both ports 9000 and 9001 mapped to 80 

As a consequence one of them can't start

### Operating system

Win11 Pro

### Version

0.14.1

**Comment by benoitf** [comment]
Containers inside a podman pod share the same network stack so I don't see why it is a podman desktop bug ?
You can't listen twice on the same port on the same network interface

**Comment by lstocchi** [comment]
I think this is related to the question i added in my PR https://github.com/containers/podman-desktop/pull/2232

> What should it happen when the user selects two containers with the same port? Only one container is displayed in the list and an error message explains what happened?? Only show the warning??

It's not a direct problem with PD but it should help the user when this happens

**Comment by jeffmaury** [comment]
> I think this is related to the question i added in my PR #2232
> 
> > What should it happen when the user selects two containers with the same port? Only one container is displayed in the list and an error message explains what happened?? Only show the warning??
> 
> It's not a direct problem with PD but it should help the user when this happens

Yes I agree we should detect it and prevent such use cases or inform the user
