### ISSUE TITLE
Update on dialog boxes

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2241]
### Is your enhancement related to a problem? Please describe

I noticed some items that might be changed on our dialog boxes

### Describe the solution you'd like

- I find that there is too much padding (compare to usual dialog boxes), for example the top right icon seems to be far away to be a close icon
- I don't see any feedback hovering the close button (it seems there should be like a small light grey change but I would expect background change or turning it into a circle)
- The main text seems to be too bright (I would expect a darker color than white/#fff
- I would expect info icon to be like the icons of the navbar (added image at the bottom) (so instead of a plain white circle with a dark i inside, a thin white circle and the i being white, inside of the circle being dark)
- icon on the top right looks a big larger than expected one (seems it's all over Podman Desktop but I think xmark (or circle-xmark on hovering as we're using a lot now circle to provide feedback) icon is better suited than times icon) https://fontawesome.com/icons/xmark?f=classic&s=solid https://fontawesome.com/icons/circle-xmark?f=classic&s=regular vs the current one https://fontawesome.com/v4/icon/times

Information icon could look like:
![image](https://user-images.githubusercontent.com/436777/234580679-3dc9ec6e-326b-41f3-bcc9-484b4769c295.png)

The issue is to discuss items as some of the items are personal feeling.

**Comment by deboer-tim** [comment]
I agree with most of the issues and willing to try the rest to see how it looks, will work with @mairin and propose a PR.

**Comment by deboer-tim** [comment]
Out of the 5 points to discuss, the first 4 have been addressed by PR #2284. For the last one I went through the FA times/xmark options with Mairin - she was on the fence, but leaned slightly toward the current one because it was a bit more solid and looked clickable. Took a look through a few other tools today and they go both ways.

Thoughts? We can try to convince Mairin or defer for now.

**Comment by benoitf** [comment]
I think xmark is the way to to go just because of the name of the icon

**Comment by benoitf** [comment]
discussion is there https://github.com/containers/podman-desktop/issues/2352

https://github.com/containers/podman-desktop/pull/2284 fixed the main issues

closing

**Comment by deboer-tim** [comment]
This was actually done in 0.15, so I moved it 'back'.
