### ISSUE TITLE
Option to autostart Podman Machine with Windows/macOS Startup

### ISSUE THREAD

**Issue by rcsilva83** [containers/podman-desktop#225]
### Is your feature request related to a problem? Please describe

It would be great to have Podman ready to use after Windows startup instead of always having to run `podman machine start` before. Docker Desktop makes Docker ready to use right after system startup.

### Describe the solution you'd like

Autocofigure Windows to run `podman machine start` on Windows startup.

**Comment by benoitf** [comment]
it's definitely an option we want to add

**Comment by n1hility** [comment]
@benoitf  does this issue cover Mac as well, or should we create another issue?

// cc  @holly-cummins was interested

**Comment by benoitf** [comment]
It will handle macOS as well
Editing the issue

**Comment by n1hility** [comment]
cool thanks!

**Comment by kartas39** [comment]
this does not work with current version (Windows)

**Comment by ieris19** [comment]
I am also experiencing issues with this with this. Whenever I login, going to Podman Desktop shows the Podman machine is not started and has to be manually started through Podman Desktop or the CLI.

Currently running v1.19.2 of Podman Desktop and v5.5.2 of Podman which are the latest options for Windows 11 24H2 (Windows Update does not report available updates so I'm assuming it's also latest). 

Podman Desktop reports both "Start on login" and "Autostart Podman engine" as enabled.

**Comment by Tsanfer** [comment]
As of now, containers still fail to autostart on boot in Windows. Current environment: Podman Desktop v1.24.2 and Podman v5.7.1.
