### ISSUE TITLE
Transparency and colors are broken in the push image dialog

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2250]
### Bug description

Transparency and colors are broken in the push image dialog

<img width="1419" alt="Capture d’écran 2023-04-26 à 18 00 04" src="https://user-images.githubusercontent.com/1636769/234639464-eecef8f1-24ed-44f8-bae4-0e2d9bb3721c.png">

### Operating system

Ventura

### Version

next (development version)

### Steps to reproduce

- Make sure to configure your quay registry
- Build an image and name the image with `quay.io/username/imagename`
- Once built, click on the kebab menu in the image list, for the image you just built
- it'll open the popup

**Comment by deboer-tim** [comment]
Checked the other modal dialogs quickly and this seems to be the only one that's having a problem. I can see some 'unique' styling in 0.14 and the palette update seems to have tipped it over the edge. Fixing.

**Comment by deboer-tim** [comment]
Fixed via #2252.
