### ISSUE TITLE
Improve instructions on build image form to better enable pushing images

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2251]
If you use the default suggested name for an image when you go to build an image "`my-custom-image`", you won't be able to push it once it's built. You need to have the registry url in the name to get the option, like so:

`http://quay.io/mairin/my-image`

![Image](https://user-images.githubusercontent.com/799683/234653238-f7c1bdfd-b013-4269-9305-6e565770ff15.png)

If you go with the default type of name you just get the `show history` option from the kebab menu:
![Image](https://user-images.githubusercontent.com/799683/234653635-29bcec65-8e4e-4200-8be8-1344f7cd6348.png)

If you have a registry url prepended to the name then you get the push option in the kebab:

![Image](https://user-images.githubusercontent.com/799683/234653799-4fa795cb-d76e-458c-9189-6f9b9a7e9b2a.png)

It might be nice to have some tool tip text or maybe some kind of dropdown selector for intended push target to make this requirement more obvious?

[I am not sure though if someone would want to push the same image to more than one registry? Right now this seems limited to pushing to the registry you embedded in the image name only?]

**Comment by slemeur** [comment]
As this is more of a naming convention, I think it would be nice to show that convention in the form to build an image, the placeholder could information the user about providing a fully qualified name to be able to push the image on a registry. 
That would be a quickfix. 

Another way to look at it, is to make the button "push image" always available and if the user has not defined a regristry in the image name, we invite the user to give it a name. Would use the `podman rename` command: https://docs.podman.io/en/latest/markdown/podman-rename.1.html

**Comment by slemeur** [comment]
linking to #2269
