### ISSUE TITLE
On Windows after I run update of podman fom 4.4.4 to 4.5.0 the update button did not disappear

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2254]
### Bug description

I have run podman desktop 0.14.1 and installed podman 4.4.4. then I quit the app and run podman desktop executable nightly (v0.0.202304261521-38e9abe). It offered to update podman, which I did - performed the update. all looks ok, although I still see an option to update podman to 4.5.0. Thus I would say that detection and update offering is buggy.

![Screenshot 2023-04-26 222545](https://user-images.githubusercontent.com/19164299/234694410-c250f57d-944a-4c22-a8db-8ad3cdd3b87a.png)

### Operating system

windows 10

### Version

next (development version)

### Relevant log output

```shell
podman --version
podman.exe version 4.5.0
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
Looks like a dup of https://github.com/containers/podman-desktop/issues/1498

**Comment by odockal** [comment]
@benoitf Yes, it truly is. Closing as dupe.
