### ISSUE TITLE
microshift/crc api server not detected during runtime selection and throw error `ECONNREFUSED ::1:6443`

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2255]
### Bug description

I installed the crc-extension to podman desktop and started without any issue I can also see there is `microshift` context in the `tray => kuberenetes => contexts` when I switch to `microshift` context and try following commands on the terminal everything looks good.
```
$ oc config get-contexts | grep microshift
*         microshift                 microshift               user                   default

$ oc get ns
NAME                                 STATUS   AGE
default                              Active   113s
kube-node-lease                      Active   115s
kube-public                          Active   115s
kube-system                          Active   115s
openshift-dns                        Active   87s
openshift-infra                      Active   113s
openshift-ingress                    Active   87s
openshift-kube-controller-manager    Active   113s
openshift-ovn-kubernetes             Active   87s
openshift-route-controller-manager   Active   92s
openshift-service-ca                 Active   87s
openshift-storage                    Active   87s
```

But as soon as I use the `Play Kubernetes YAML` under `Pod` section I see that it is not able to connect to API because it is not able to list the namespace like it do for other contexts (kind, dev-sandbox ..etc.)
<img width="811" alt="Screenshot 2023-04-27 at 2 36 42 PM" src="https://user-images.githubusercontent.com/410007/234815112-317c1059-4f3a-4ebc-bdca-e9afe6173b45.png">

And as soon as I hit `Play` I get connection refused error. 
<img width="740" alt="Screenshot 2023-04-27 at 2 37 28 PM" src="https://user-images.githubusercontent.com/410007/234815312-0359f07a-a57a-4608-9a84-252305d9fe15.png">

### Operating system

13.3.1 (22E261) (M1)

### Version

0.14.1

**Comment by praveenkumar** [comment]
Bit more details to figure out issue, I tried to send request to curl and if you check it also failed for `[::1]:6443` which is  localhost address in case of ipv6 but it succeed for `127.0.0.1:6443` so does the logic we have in the podman desktop can we disable lookback for ipv6?

```
 curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json" -H "User-Agent: oc/4.10.0 (darwin/amd64) kubernetes/daed147" 'https://api.crc.testing:6443/api/v1/namespaces?limit=500'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying [::1]:6443...
* connect to ::1 port 6443 failed: Connection refused
*   Trying 127.0.0.1:6443...
* Connected to api.crc.testing (127.0.0.1) port 6443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Request CERT (13):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2

```

**Comment by jeffmaury** [comment]
Isn't it an issue with the DNS resolver as api.crc.testing is used to contact the cluster ? Is this only microshift ?

**Comment by praveenkumar** [comment]
> Isn't it an issue with the DNS resolver as api.crc.testing is used to contact the cluster ? Is this only microshift ?

@jeffmaury No, if the DNS resolver was issue then with `oc` client or our sample go-code also we should've faced same issue but that is not the case.

So I tried the same library which we are using for podman desktop https://github.com/kubernetes-client/javascript (as @benoitf pointed)
```javascript
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromFile("/Users/prkumar/.kube/config");

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNamespace().then((res) => {
    res.body.items.forEach(i => {
          console.log(i.metadata.name);
    });
   // console.log(res.body);
});
```

And able to get the required result for microshift preset. So I think there is something in our codebase which is causing this issue? 

```
$ node index.js
default
demo
kube-node-lease
kube-public
kube-system
openshift-dns
openshift-infra
openshift-ingress
openshift-kube-controller-manager
openshift-ovn-kubernetes
openshift-route-controller-manager
openshift-service-ca
openshift-storage
```

**Comment by benoitf** [comment]
@praveenkumar what is your Node.js version ?

**Comment by praveenkumar** [comment]
> @praveenkumar what is your Node.js version ?

I installed using brew (on mac) and tested this script with help of @evidolob ( since I don't have much knowledge around node/javascript side). Do let me know if any other info required to pin point this bug.

```
➜  test node --version
v20.0.0
```

**Comment by benoitf** [comment]
electron includes Node.js 18.14 (so maybe something has also changed in the network stack)
I know that in v17 they changed the default prefered stack from ipv4 to ipv6 as well

**Comment by jeffmaury** [comment]
So looks like this is the issue. I still believe that the DNS provider should not return an IPv6 address if it's not supported. I don't think client are supposed to look over all returned addresses. Maybe we could set Electron to prefer IPv4
Will test on Windows

**Comment by praveenkumar** [comment]
FYI I tested same script with node-18.16 and got similar failure, isn't a way to update the node version in the electron?
```
node -v
v18.16.0
➜  test node index.js 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED ::1:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 6443
}

Node.js v18.16.0
```

> Maybe we could set Electron to prefer IPv4, Will test on Windows

Yes, that would be nice.

**Comment by benoitf** [comment]
no, Electron is tied to a given version of Node.js

also Node.js 18 is the current LTS version of Node.js (20 is not expected as being the LTS before end of october)

**Comment by benoitf** [comment]
https://releases.electronjs.org/release/v24.1.3

**Comment by jeffmaury** [comment]
Please note that I don't have the issue on Win11 Pro I was able to deploy a container to OpenShift Local

**Comment by benoitf** [comment]
@jeffmaury what is the version of Node.js on your Windows ?

**Comment by benoitf** [comment]
@praveenkumar I found https://nodejs.org/api/dns.html#dnssetdefaultresultorderorder

are you able to check with that flag being set to ipv4first ?

```
order [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) must be 'ipv4first' or 'verbatim'.
```

**Comment by jeffmaury** [comment]
> @jeffmaury what is the version of Node.js on your Windows ?

I'm using 16.14.2

**Comment by praveenkumar** [comment]
@benoitf Following works ( Thanks to @evidolob for pairing) can you make change to the code so that it wouldn't affect any other functionality of the application.  

```js
const dns = require('node:dns');
dns.setDefaultResultOrder('ipv4first')

const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromFile("/Users/prkumar/.kube/config");

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNamespace().then((res) => {
    res.body.items.forEach(i => {
          console.log(i.metadata.name);
    });
   // console.log(res.body);
});
```

**Comment by benoitf** [comment]
yes this is what I was expecting. Just wanted to check if it was working for you
thanks for the report.
