### ISSUE TITLE
Slow at retrieving containers

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#2259]
### Bug description

PD is very slow at loading the containers page.
After debugging it looks like this is the bottleneck, in my case it took 29sec to retrieve the list. 
The problem is that it's not large, like 20-30 containers.
Is it just me or someone else is facing this issue?
![image](https://user-images.githubusercontent.com/49404737/234842675-9a8a6a39-4634-4c71-8ed9-832586eba75b.png)

### Operating system

Windows 11

### Version

next (development version)

### Steps to reproduce

1. Open the containers page

**Comment by deboer-tim** [comment]
Currently 15 containers, still fast for me.
If nothing else, it might be worth making sure there is a good log message in case anyone else hits this, maybe even a telemetry event so we can see outliers across the fleet.

**Comment by benoitf** [comment]
are you able to reproduce on another machine ?
or after a restart of the podman machine
if yes, can you export your containers and import them in another machine and compare/try to isolate the one that is failing

on my side I don't reproduce for now

**Comment by jeffmaury** [comment]
Tried with 15 containers on Win11Pro and noticed that the containers count (on 0.14.1) is displayed a long time after the images count.

**Comment by benoitf** [comment]
should be fixed by https://github.com/containers/podman-desktop/issues/2375
