### ISSUE TITLE
Kind installation button doesn't reappear after removing kind.exe

### ISSUE THREAD

**Issue by silopolis** [containers/podman-desktop#2261]
### Bug description

Hi,

First time here so, first, huge thanks for this beautiful tool 🙏 

I just had a click convulsion and installed Kind via podman-desktop. While it's no big deal, I prefer to manage packages using Chocolatey.

Wanting to remove it, I couldn't find a relevant action into Podman-Desktop.

After looking for it and manually removing the `kind.exe` binary from path, the 'Kind' button doesn't reappear into the status bar.

### Operating system

Windows 10

### Version

0.14.1

### Steps to reproduce

1. Install kind using the built-in installer available in the status bar
2. close podman-desktop
3. *No uninstall action is available*
4. Browse, search and manually remove the `kind.exe` binary
5. Launch podman-desktop
6. *Install button does not reappear* in the status bar

### Additional context

Going a step further, it would be nice to have an 'Uninstall Kind' button in the Kind settings page, maybe with another 'Install Kind' one or a text indicating the one in the status bar.
Having everything related to the extension's setup and activation in the dedicated settings page feels easy and natural.
The same applies for other extensions depending on external components like Compose.

**Comment by jeffmaury** [comment]
By default the kind extension checks for the presence of the binary when the Podman Desktop process starts. Please note that the default settings don't stop the Podman Desktop process when the main window is closed you should either change the setting or go to the system icons tab, locate the one for Podman Desktop and select Quit

**Comment by silopolis** [comment]
@jeffmaury hi, yes, skimmed over the code to understand what was happening 👍 I'm also well aware of that "remain in tray" potential issue and indeed tested several times ensuring Podman Desktop was actually closed.
Thanks for the info warning.

**Comment by benoitf** [comment]
now there is a Cli Tools section in preferences and detection mechanism has changed
