### ISSUE TITLE
Add `Push Image to OpenShift Local cluster` as option for image

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2263]
### Is your enhancement related to a problem? Please describe

As of now we have option `Push Image to kind cluster` which works with `kind` cluster. We also need an option for `Push Image to OpenShift Local cluster` which sync image from podman machine instance to OpenShift Local instance.

<img width="1225" alt="Screenshot 2023-04-28 at 8 59 51 AM" src="https://user-images.githubusercontent.com/410007/235047719-7f5271b1-640b-4399-a116-5aba4d960edb.png">

### Describe the solution you'd like

Same as description.

**Comment by benoitf** [comment]
@praveenkumar it's the responsibility of the extension ( OpenShift local) to provide this command

**Comment by jeffmaury** [comment]
Moved to https://github.com/crc-org/crc-extension/issues/61
