### ISSUE TITLE
Space in front of image name make the pulling fail

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#2264]
### Bug description

I copy/paste the name of an image i wanted to pull and i didn't notice there was a space in front of it.
After clicking on `pull image` i saw this error, not very helpful but i noticed the problem.
It would be good if the extra space was removed automatically

![image](https://user-images.githubusercontent.com/49404737/235067023-234b566c-e264-47e6-8383-63f21c0b5253.png)

### Operating system

Windows 11

### Version

next (development version)

### Steps to reproduce

1. Images
2. Pull an image
3. add ` centos/redis-5-centos` to image to pull textbox
4. click pull image

**Comment by benoitf** [comment]
@lstocchi https://github.com/containers/podman-desktop/issues/2227 and https://github.com/containers/podman-desktop/pull/2244

**Comment by lstocchi** [comment]
Ops, i didn't see it. Closing
