### ISSUE TITLE
Error in extension start leads to starting state, impossible to stop or delete

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2265]
### Bug description

When an error is raised during extension start (see https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/21) then extension is in the starting state and then cannot be stopped or removed

### Operating system

Win11 Pro

### Version

0.14.1

### Steps to reproduce

1. Install ghcr.io/redhat-developer/podman-desktop-sandbox-ext:latest
2. Check the extension state

**Comment by benoitf** [comment]
Needs a proper state for extensions so they can be reported as being in an error state, not only logging exceptions and thinking it has been started

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/2209
