### ISSUE TITLE
Ability to rename an image

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2269]
### Is your feature request related to a problem? Please describe

It would be nice for a user to easily be able to rename an image: https://docs.podman.io/en/latest/markdown/podman-rename.1.html

### Describe the solution you'd like

Kebab menu in the list of images, to provide an option to rename an image.

**Comment by tuckerrc** [comment]
Can I work on this issue?

**Comment by deboer-tim** [comment]
Sure! We'd welcome a PR.
