### ISSUE TITLE
kind: Allow to view and customize kind cluster config

### ISSUE THREAD

**Issue by csantanapr** [containers/podman-desktop#2270]
### Is your enhancement related to a problem? Please describe

I would like to see the kind cluster config being used when creating kind cluster from UI. And have the ability to adjust the config for example adding more worker nodes.

### Describe the solution you'd like

Allow to view and edit in kind cluster create

### Describe alternatives you've considered

document how to create a kind cluster from CLI that uses same defaults as UI

**Comment by slemeur** [comment]
Thanks for the report @csantanapr !

**Comment by csantanapr** [comment]
A workaround is welcome on how to create a multi worker node kind with podman, is there somewhere in this git repo the config file use to create the kind cluster in Podman UI?

**Comment by csantanapr** [comment]
is cool that contour is installed 
I found this https://github.com/containers/podman-desktop/blob/main/extensions/kind/src/templates/create-cluster-conf.mustache
But it doesn't include contour ingress

**Comment by csantanapr** [comment]
Do I need to specify `KIND_EXPERIMENTAL_PROVIDER=podman` ?

**Comment by jeffmaury** [comment]
No but work on creating ingress when deploying a container is in progress see #2149

**Comment by csantanapr** [comment]
Hi @jeffmaury 
I meant that today when I create kind cluster with podman UI it installed contour
```
kube-system          coredns-565d847f94-dkl52                             1/1     Running     0          116m
kube-system          coredns-565d847f94-pq7gt                             1/1     Running     0          116m
kube-system          etcd-kind-cluster-control-plane                      1/1     Running     0          116m
kube-system          kindnet-k2kcz                                        1/1     Running     0          116m
kube-system          kube-apiserver-kind-cluster-control-plane            1/1     Running     0          116m
kube-system          kube-controller-manager-kind-cluster-control-plane   1/1     Running     0          116m
kube-system          kube-proxy-rmvck                                     1/1     Running     0          116m
kube-system          kube-scheduler-kind-cluster-control-plane            1/1     Running     0          116m
local-path-storage   local-path-provisioner-684f458cdd-s7db9              1/1     Running     0          116m
projectcontour       contour-5c4cdc9cf-dj82z                              1/1     Running     0          116m
projectcontour       contour-5c4cdc9cf-m2sdg                              1/1     Running     0          116m
projectcontour       contour-certgen-v1.24.2-hbl7x                        0/1     Completed   0          116m
projectcontour       envoy-wl42t                                          2/2     Running     0          116m
```

**Comment by jeffmaury** [comment]
> Hi @jeffmaury I meant that today when I create kind cluster with podman UI it installed contour
> 
> ```
> kube-system          coredns-565d847f94-dkl52                             1/1     Running     0          116m
> kube-system          coredns-565d847f94-pq7gt                             1/1     Running     0          116m
> kube-system          etcd-kind-cluster-control-plane                      1/1     Running     0          116m
> kube-system          kindnet-k2k"cz                                        1/1     Running     0          116m
> kube-system          kube-apiserver-kind-cluster-control-plane            1/1     Running     0          116m
> kube-system          kube-controller-manager-kind-cluster-control-plane   1/1     Running     0          116m
> kube-system          kube-proxy-rmvck                                     1/1     Running     0          116m
> kube-system          kube-scheduler-kind-cluster-control-plane            1/1     Running     0          116m
> local-path-storage   local-path-provisioner-684f458cdd-s7db9              1/1     Running     0          116m
> projectcontour       contour-5c4cdc9cf-dj82z                              1/1     Running     0          116m
> projectcontour       contour-5c4cdc9cf-m2sdg                              1/1     Running     0          116m
> projectcontour       contour-certgen-v1.24.2-hbl7x                        0/1     Completed   0          116m
> projectcontour       envoy-wl42t                                          2/2     Running     0          116m
> ```

Yes but I'm not sure I understand "But it doesn't include contour ingress"

**Comment by csantanapr** [comment]
Hi @jeffmaury I want the exact command line for kind that I can reproduce the same cluster I created with the UI. and having the same result including the namespace `projectcontour`

**Comment by jeffmaury** [comment]
Create a kind cluster with the following configuration:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9090
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP

```

Then install the Contour controller:

`kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/v1.24.2/examples/render/contour.yaml`

**Comment by odockal** [comment]
Related/dupe request of https://github.com/containers/podman-desktop/issues/2215
