### ISSUE TITLE
Wsl/Service/WSL_E_DISTRO_NOT_FOUND 

### ISSUE THREAD

**Issue by cforce** [containers/podman-desktop#2276]
### Bug description

Error: Starting machine "podman-machine-default" There is no distribution with the supplied name.  Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND  There is no distribution with the supplied name.  Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND   Error: the WSL bootstrap script failed: exit status 0xffffffff

### Operating system

Windows	10.0.19045 Build 19045

### Version

0.14.1

### Steps to reproduce

Just somewhere in the middle of successful operation it suddenly broke. BTW WSL works fine at the same time

**Comment by cforce** [comment]
https://github.com/docker/for-win/issues/13128
However it shall not depend on docker in any way and docker4desktop runs also fine at this time as wsl does - juts podman (desktop) is broken

C:\temp>podman machine init
Error: podman-machine-default: VM already exists

C:\temp>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2

**Comment by benoitf** [comment]
try 'podman machine rm' and then again 'podman machine init' ?

**Comment by cforce** [comment]
yes, workaround fixed it - howver why did it broke?

I got now  the warning "Docker Socket Compatibility: Docker-specific tools may not work" i had not before.
