### ISSUE TITLE
Change (default) sort for container images

### ISSUE THREAD

**Issue by jberkus** [containers/podman-desktop#2283]
### Is your enhancement related to a problem? Please describe

Currently, container images are sorted in the UI in order of age, oldest to newest.  This is possibly the least useful potential sort, and leads to bad UX:

1. Build a new image using PD
2. Scroll a whole bunch to find that image

### Describe the solution you'd like

I'd like to just change the current non-alterable sort.  Here's my preferences for a better sort order:

1. age, ascending (as in, newest images first)
2. Name+Tag, alphabetically

### Describe alternatives you've considered

Clearly #659 is the real solution to this.  But while folks work on that, just changing the current static ordering should be easy to add to an update, a 1-line fix.   And, once #659 is implemented, the better order could be come the new default order.

**Comment by benoitf** [comment]
I think we're waiting UI design for the sorting but yes changing the 'raw data' to newest first could be done easily 👍
