### ISSUE TITLE
Form UI for building an image is inconsistent

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2290]
### Is your enhancement related to a problem? Please describe

<img width="1162" alt="Capture d’écran 2023-05-02 à 11 28 39" src="https://user-images.githubusercontent.com/1636769/235630843-d77fd623-c70a-4574-848d-f549a4370b45.png">

### Describe the solution you'd like

Should be aligned with other forms (ex resources)

**Comment by lstocchi** [comment]
This will be fixed by https://github.com/containers/podman-desktop/pull/2285

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/2285
