### ISSUE TITLE
Provide an option to configure the podman-machine to be rootless or rootful

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2305]
### Is your enhancement related to a problem? Please describe

When working with Compose, it happens oftenly that errors are happening because of the default security constraints given to a podman machine.

This is an example
````
Error response from daemon: rootlessport cannot expose privileged port 80, you can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024), or choose a larger port number (>= 1024): listen tcp 0.0.0.0:80: bind: permission denied
````

In order to go over the issue, one would have to flex the security of the podman-machine, but Podman Desktop does not provide a way to do that.

### Describe the solution you'd like

In the form to create a podman machine, it would be nice if the user would be given an option for rootless or rootful mode.
We would like to differentiate that in the list of resources (maybe with an icon)

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/2078
