### ISSUE TITLE
Show Kube context on the status bar

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2309]
### Is your enhancement related to a problem? Please describe

I've been caught a couple times where I forgot what my current context was and the pod or action I was expecting wasn't there. I've seen a couple demos recently where people were on one of the pages and then went all the way to the system tray to check the context or switch it.

### Describe the solution you'd like

IMHO we need to have a larger discussion about how we handle the current context vs someone trying to (e.g.) use a local cluster while also deploying to a remote one. One basic fix though would be to start showing the current context on the status bar so that it's easily seen, and ideally making that a menu so that I can easily switch without going back to the system tray.

**Comment by odockal** [comment]
@deboer-tim I have to strongly agree with this enhancement, seems nice and will make e2e test implementation easier. I am not sure about playwright support for native objects outside electron app.
