### ISSUE TITLE
Slider for disk size of podman-machine does not allow to go beyond 76GB

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2318]
### Bug description

When creating a new podman machine, the default disk size given is 100GB.
But once the user slides on the disk size sliders, it's note possible to get back to that value, and impossible to go beyond 76GB
![create-machine-sliders](https://user-images.githubusercontent.com/1636769/235865039-379d46d5-d814-4ab3-ac57-14828a768b8b.gif)

### Operating system

Ventura

### Version

next (development version)

### Steps to reproduce

- go to create a new podman machine
- try to slide on the disk size slider

**Comment by benoitf** [comment]
we discussed that user should be able to enter its own value for some component so maybe it should also be the case here
https://github.com/containers/podman-desktop/issues/1986

**Comment by lstocchi** [comment]
the other problem is also how to define the max value allowed to enter. I think that it only shows 76GB after the first slide as it's the max free space available when the page is opened. So there is a problem when showing it the first time in the current implementation.
But if we allow users to add their own value, we need to set a sort of limitation. Can they add a huge number even if the space is not real? I mean it's a vm so you can give it the space you want but if the max disk space on the machine is 200gb it's useless to allow creating a machine of 300gb.

**Comment by benoitf** [comment]
define the value does not mean it can be accepted if it's outside the range

On the Stevan's issue I think the initial display should say 76GB ( current disk space) and not 100Gb and move to 76Gb once we clicked
