### ISSUE TITLE
Sliders for adjusting the settings of a podman-machine are not convenient to use

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2319]
### Is your enhancement related to a problem? Please describe

While the sliders are quite easy way to interact with the settings of the podman machine, it's super tricky to adjust the value to a precise one.
If somebody, just want to create a podman-machine with 4GB of RAM, most likely, the user will get "around it": 3.96, 4.07 ...

### Describe the solution you'd like

We should make the sliders having better "graduations".
For Disk: I believe a single digit unique would be enough 
For Ram: Maybe 0.5 increments

Also it would be nice to display the scales (from which min value it starts, to which max value it goes)

**Comment by slemeur** [comment]
linking to #1986

**Comment by maxandersen** [comment]
Also just having text editable would help.

**Comment by benoitf** [comment]
@jeffmaury https://github.com/containers/podman-desktop/pull/2368 won't fix this issue as it's not used for cpu/memory or disk

**Comment by BlaineEXE** [comment]
I wholeheartedly agree with this. There is no need to edit disk usage or memory to the 0.01 GB, and it's just annoying IMO to have it do so. IMO, memory should be able to be modified only to 256MB or 512MB resolution, and disk usage to the 0.5GB.
