### ISSUE TITLE
Left sidebar does not resize properly while in settings

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2320]
### Bug description

The left sidebar does not resize properly while in settings.

<img width="1543" alt="Capture d’écran 2023-05-03 à 10 27 36" src="https://user-images.githubusercontent.com/1636769/235866882-0ca7314c-69e8-4c74-875e-a509d675c389.png">

### Operating system

Ventura 13.3.1

### Version

next (development version)

### Steps to reproduce

- Display the settings of Podman Desktop
- Create a new machine
--> At this stage the left sidebar is properly displayed.
- Hit the button "create"
--> If you scroll a little bit, you'll see the leftsidebar with an empty area.

**Comment by lstocchi** [comment]
I can see the same issue when having a long list of containers
![setting-height](https://user-images.githubusercontent.com/49404737/235867666-b543e558-4d6c-4aa1-aa8e-36afb61eeff1.gif)

**Comment by benoitf** [comment]
don't know if it has been addressed by https://github.com/containers/podman-desktop/pull/2223#issuecomment-1529751527 as the same issue was already reported
