### ISSUE TITLE
Does not show images, containers 

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2321]
### Bug description

This might happened because I'm building running locally?

<img width="1689" alt="Capture d’écran 2023-05-03 à 10 43 39" src="https://user-images.githubusercontent.com/1636769/235870812-dc0b9169-5856-4793-a6bb-0fb3dba072e7.png">

<img width="1435" alt="Capture d’écran 2023-05-03 à 10 40 56" src="https://user-images.githubusercontent.com/1636769/235870397-2703bf54-1425-4b7f-a560-1e81caf7c5de.png">

### Operating system

Ventura 13.3.1

### Version

next (development version)

### Steps to reproduce

- created a podman machine
- started a Kind cluster
- run preload.sh from https://github.com/redhat-developer/podman-desktop-demo/tree/main/primary-podify-demo 

Nothing displayed in the UI, while images and containers are properly started in the CLI

### Additional context

For reload does not work around the issue

**Comment by benoitf** [comment]
it looks like a dup https://github.com/containers/podman-desktop/issues/2310 or other dup issues having the same report (lack of data from the connections)
This is not related to a local custom build
