### ISSUE TITLE
Task manager needs progress status

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2328]
### Is your enhancement related to a problem? Please describe

I started an OpenShift Local instance, which takes a bit to start. As long as I stay on the Resources page I can see that something is happening, but if I leave there, there is no visual indication that something is still running in the background, or when it has finished.

### Describe the solution you'd like

The tasks bell should have some minor ongoing animation to indicate when there is a running task, and ideally a slightly stronger indication when a task finishes.

FYI @mairin

**Comment by benoitf** [comment]
AFAIK I think there are issues already discussing the topic
and AFAIK it should provide a notification when it's completed

**Comment by benoitf** [comment]
closing as I found issue it's https://github.com/containers/podman-desktop/issues/1744
