### ISSUE TITLE
MessageBox seems to truncate text

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2335]
### Bug description

Go this with installing OpenShift Local:

![image](https://user-images.githubusercontent.com/695993/235966133-328d1b87-6af7-418c-a918-75e3248c4b65.png)

### Operating system

Win11 Pro

### Version

next (development version)

**Comment by benoitf** [comment]
https://github.com/crc-org/crc-extension/blob/dcf5f11e64c6acf1095248a18337668d6cf86c07/src/crc-setup.ts#L40

**Comment by benoitf** [comment]
It's what extension is setting...
