### ISSUE TITLE
Docker Compose Install should be less prominent, cancellable

### ISSUE THREAD

**Issue by jberkus** [containers/podman-desktop#2343]
### Bug description

1. I was trying to click Settings and I accidentally clicked on the "Install Compose" link in the bottom left corner, since it's very close to Settings.
2. Got a dialog of "Select which version of Compose to install".  There was no "OK" or "Cancel", just a version selector
3. Try hitting ESC to exit
4. Got dialog "Docker Compose v2.17.3 Installed"

### Operating system

Fedora Silverblue 38

### Version

0.14.1

### Steps to reproduce

See above

### Additional context

So there's actually two issues here.

1. The "install compose" link is in a very prominent position (anchoring the bottom left corner) that's way too easy to click accidentally.  It should really be under Settings or somewhere else; installing compose is something a user does *once*, and with a very specific plan in mind.  The bottom-left-corner position should be reserved for things a user does every day, or even several times a day.
2. ~~If you do click it accidentally, it should be possible to cancel it, via ESC key or otherwise.~~ **RESOLVED IN 1.15.0**

**Comment by benoitf** [comment]
esc key is now correctly handled
looks like a dup of https://github.com/containers/podman-desktop/issues/2126

**Comment by jberkus** [comment]
@benoitf  updated the report to indicate that the cancellable status has been resolved.  There's still a pretty major UX issue, though.
