### ISSUE TITLE
Nav bar: improve handling of extensions

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2353]
### Is your enhancement related to a problem? Please describe

Follow up from issue #2167.

If there are a lot of docker extensions installed, the settings icon will be pushed down enough for a scroll bar to be required. These icons are also in colour, which makes them draw the eye more than the other icons.

### Describe the solution you'd like

1. We already have some design proposals for a different styling for extensions, e.g. putting them on a different background bar.
2. Limit the # of extensions shown and have a pop out for any additional ones, so that there is never a scroll bar for the navigation.

**Comment by benoitf** [comment]
For the settings icon we could move it to the title bar as well

**Comment by mairin** [comment]
I made a design for this here:
https://github.com/containers/podman-desktop/issues/2677

**Comment by deboer-tim** [comment]
We have an updated design (Mo will post details in the design issue) where these extensions or other categories of nav items will show up as an icon, which can be expanded to show related nav items.

**Comment by deboer-tim** [comment]
I came up with a proposed component and showed an initial version to @mairin. I'll clean it up and put a PR up for review (but given holidays, possibly not immediately).

**Comment by ekidneyrh** [comment]
Can this be closed as a duplicate of https://github.com/containers/podman-desktop/issues/6774?

**Comment by deboer-tim** [comment]
Yup, or #7763. Closing.
