### ISSUE TITLE
Dialog boxes usability with keyboard

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2356]
### Is your enhancement related to a problem? Please describe

From time to time I like to close dialogs with the keyboard

But I'm unable to close the buttons of the dialog box using the <kbd>Enter</kbd> key
or to switch the buttons using the tab key

It's an overall issue as it may apply to other parts where keyboard could be used but dialog boxes are the one I'm missing to use the keyboard.

### Describe the solution you'd like

I can use <kbd>ESC</kbd> but I would like to use <kbd>Enter</kbd> as well :-)

**Comment by deboer-tim** [comment]
PR #3227 up for review - it limits tabbing to within the message box dialog, identical to what the Modal was already doing.

Florent, `Enter` was already working for me on both message box and modal, it was just super annoying to tab until you got to the dialog controls. Can you confirm if that was the only issue (waiting until 3227 is merged is fine) or there is something else? Or, I think the quickpick has the same issue and we can list the specific things that need fixing here.

**Comment by deboer-tim** [comment]
Now that I knew quickpick had the same tabbing problem I couldn't leave it... PR updated to fix both.
