### ISSUE TITLE
Add a message and/or an icon telling user what operations is being performed

### ISSUE THREAD

**Issue by bdattoma** [containers/podman-desktop#2369]
### Is your enhancement related to a problem? Please describe

I found not very user friendly my experience with listing and deleting images in the "Images" page. I wasn't sure if the software was actually doing something or there was something wrong. 

2 example scenarios:
1) When I first accessed the page, I faced the text saying "No images, etc": 
![image](https://user-images.githubusercontent.com/88311595/236441448-c0b09b4d-4ab3-4714-83dd-af4ca608928c.png)

I gave it some time, and went doing other tasks outside podman desktop. When I came back, the list of images appeared.

2) I selected many images (around 200) and clicked on "Delete <number> selected items" button. After that, I faced again the "No images" message, until the image list is fetched again (minutes later). The deletion operation seems to be completed successfully. 

### Describe the solution you'd like

I would suggest to add a message or a loading icon (or whatever else) to make user is aware that podman is actually doing something, e.g., "I'm fetching your images..." or "I'm deleting the images, after this I will fetch all the images once again..please be patient"

### Additional context

I might have many images stored, in fact also `podman images` takes much time to list all the images. So maybe with fewer images the issue doesn't exist. I'm not aware of how many images the average podman user has.

**Comment by deboer-tim** [comment]
Thank you for the feedback Berto! Yes, I suspect that most of us don't notice this because UI updates are fast with a modest number of image, but this is something we'll need to consider going forward.
