### ISSUE TITLE
Remove vale sync from build

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2370]
### Bug description

Vale should not be updating on PRs and potentially surprising the user with new rules. Existing rules should be checked into git, and only updated (along with fixes to any affected files) via PR.

### Operating system

macOS 13.3 M1

### Version

next (development version)

**Comment by benoitf** [comment]
@themr0c @deboer-tim should we close the issue as I think vale check is not anymore a problem ?

**Comment by themr0c** [comment]
I agree
