### ISSUE TITLE
Validate and update upper and lower limits of our settings

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#2371]
### Is your enhancement related to a problem? Please describe

This issue is based on Mo's comment at https://github.com/containers/podman-desktop/pull/2368#issuecomment-1536192925

> Also - does the UI work with an 100px font? 😬 I wonder if something like 36 or 48 would be a better upper limit. In testing them out, 36 seems a pretty reasonable upper limit although 48 is readable. (see screenshots below)

The font size setting accepts a value between 6 to 100 but 100 is a large value. Should this be decreased?

# 100px
![Screenshot from 2023-05-05 08-28-54](https://user-images.githubusercontent.com/799683/236457967-bc3c0951-06a6-4402-b9e7-eb8506457819.png)
# 24px
![Screenshot from 2023-05-05 08-29-10](https://user-images.githubusercontent.com/799683/236457975-6783737a-2692-4ab1-beee-1e1ebf856d63.png)
# 36px
![Screenshot from 2023-05-05 08-29-40](https://user-images.githubusercontent.com/799683/236457980-b5b5ccc7-04af-46ea-84d1-94cafd6d0cc0.png)
# 48px
![Screenshot from 2023-05-05 08-29-28](https://user-images.githubusercontent.com/799683/236457977-ecfe51f8-63a3-49f3-9d4c-e9a7c41f9669.png)

We should also check if other settings have a reasonable upper and lower limit.

### Describe the solution you'd like

Each setting should have a reasonable upper and lower limit.

**Comment by deboer-tim** [comment]
I like having strict bounds when the user can shoot themselves in the foot, but this is a call on when it becomes less usable, which is harder to judge and somebody out there has poor eyesight and an 8k monitor. I'd maybe switch to 96 (or 72) just because those are common/multiple font sizes, but otherwise leave it large.
