### ISSUE TITLE
Podman Desktop is not automatically refreshing pages with images, container and pods

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2372]
### Bug description

I am on Windows 10, testing 0.15.0, but I have to manually refresh the page `CTRL+R` in order to get actual state of any of my actions done in any of images, containers or pods pages.

### Operating system

Windows 10

### Version

0.15.0

**Comment by benoitf** [comment]
please provide the log of podman desktop to see if there are some traces

**Comment by jeffmaury** [comment]
Can  you check with 1.0.0 as I cannot reproduce on Win10 as well. I tried to pull and image and the list of images is updated accordingly

**Comment by odockal** [comment]
All seems alright now! Images, container, pods are being shown quite fast.
