### ISSUE TITLE
Idea: console access to container engine VMs

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2377]
Not sure if this would be generally useful, but:

As a user trying to run tests on a Mac, it would be mighty convenient if there was a button on the Podman virtual machine to be able to get a console into the VM. (In my case, I'm trying to run a specific build of podman in the machine to debug something.)

**Comment by afbjorklund** [comment]
* #889

**Comment by mairin** [comment]
Ah thanks @afbjorklund ! I will close this as a duplicate of #889
