### ISSUE TITLE
Extension Settings is using confusing terms

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#2379]
### Bug description

When I select the Settings -> Extension Settings I am shown the following:

![image](https://user-images.githubusercontent.com/1894/236735041-d6bed832-56cb-4484-b9c3-187df41343e1.png)

This is confusing, as the Status: Running looks like to refer to the environment/instance it offers, but is, like in all the other extensions related to the extension state. I find this very confusing.

But what is even mroe confusing is that "Kube Context" gets selected. Selecting "Kube Context" highlights "Lima", so it loosk like there is an index off by 2.

Since none of the extensions has any settings, perhaps this detailed view is not necessary.

### Operating system

Windows, macOS

### Version

0.15.0

### Steps to reproduce

Open Settings, select Extensions (unfold)

**Comment by gbraad** [comment]
It might help to not say `Status`, but instead use `Extension status`

**Comment by deboer-tim** [comment]
> But what is even mroe confusing is that "Kube Context" gets selected. Selecting "Kube Context" highlights "Lima", so it loosk like there is an index off by 2.

Double-check that you're on a clean main from 0.15 or beyond, this was fixed via PR #2221 and I see other changes missing from your screenshot as well.

Perhaps we should use enable/disable instead of start/stop. We're revisiting the extension pages soon and will take this into account.

**Comment by gbraad** [comment]
running the development target as used by the PR/extension. Will verify this soon.

However, as said using "Extension status" and "Enable"/"Disable" might avoid confusion, though the pictographic use is a play and stop button on the previous Extension page
