### ISSUE TITLE
Docs: Instructions on how to undo docker compat

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2388]
### Is your enhancement related to a problem? Please describe

I've noticed over the past few weeks a few Podman Desktop users in the community chat wanting to "undo" the Docker compat mode and not knowing how. 

### Describe the solution you'd like

It might be nice to add a section to [the "Migrating from Docker" doc](https://podman-desktop.io/docs/migrating-from-docker) that explains how to undo the changes suggested in the doc.

**Comment by Tanguille** [comment]
I had problems today trying to revert the podman compatibility config. Resulting in following error with each docker command : `Cannot connect to the Docker daemon at unix:///run/user/1000/podman/podman.sock. Is the docker daemon running?`

I tried: 
```shell
$ podman system reset - This reset the Podman configuration.
$ unset DOCKER_HOST - This unset the DOCKER_HOST environment variable that was pointing to the Podman socket.
$ sudo nano /usr/lib/systemd/system/docker.service - This opened the Docker service configuration file in the nano text editor.
You modified the ExecStart line in the Docker service configuration file to include -H fd:// to tell Docker to listen on the default Unix socket instead of the Podman socket.
$ sudo systemctl daemon-reload - This reloaded the systemd configuration.
$ sudo systemctl restart docker - This restarted the Docker daemon service with the new configuration.
```

In the end, modifying the docker config via `sudo systemctl edit docker.service` was the solution that worked to get Docker listening on the default Unix socket. However this solution seems very hacky. I added 
```
[Service]
Environment="DOCKER_OPTS=--host=unix:///var/run/docker.sock"
```

Suggestions for a better way of doing this are welcome and adding an undo section seems vital to me.

**Comment by ThomasVitale** [comment]
Do you have any suggestion on how to fix this when using Docker Desktop?

**Comment by jeffmaury** [comment]
> Do you have any suggestion on how to fix this when using Docker Desktop?

On which OS ?

**Comment by ThomasVitale** [comment]
macOS (aarch64)

**Comment by cdrage** [comment]
Now we have the compatibility button added in preferences, I'm assuming we can move forward with this and simply create some screenshots / documentation for the site? https://github.com/containers/podman-desktop/pull/4093
