### ISSUE TITLE
Desktop Extension: add support for backends

### ISSUE THREAD

**Issue by alban** [containers/podman-desktop#2390]
### Is your feature request related to a problem? Please describe

Docker Desktop extensions using a [backend](https://docs.docker.com/desktop/extensions-sdk/architecture/#the-backend) are not supported in Podman Desktop. This is the "vm" section of metadata.json:

Example of metadata.json with a "vm" section:
```json
{
  "icon": "icon.svg",
  "vm": {
    "composefile": "docker-compose.yaml",
    "exposes": {
      "socket": "my-desktop-extension.sock"
    }
  },
  "ui": {
    "dashboard-tab": {
      "title": "My Extension",
      "src": "index.html",
      "root": "ui",
      "backend": {
        "socket": "my-desktop-extension.sock"
      }
    }
  },
  "name": "my-extension"
}
```

Podman Desktop's source reading metadata.json:
https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/docker-extension/docker-desktop-installation.ts#L45-L46
It is reading the `icon`, `ui`, `host` sections but not the `vm` section.

### Describe the solution you'd like

I would like Podman Desktop to create the containers in the backend as described in the `vm` section like Docker Desktop.

In particular, I would like the following features:
- Possibility to give a docker compose file
- Support for various docker compose fields:
  - privileged: true
  - network_mode: host
  - userns_mode: host
  - pid: host
  - volumes
  - environment

### Describe alternatives you've considered

I don't see alternative solutions.

### Additional context

I would like this feature because I would like to develop a desktop extension for Inspektor Gadget that would work both in Docker Desktop and Podman Desktop:
https://github.com/inspektor-gadget/inspektor-gadget/issues/1604

**Comment by benoitf** [comment]
was fixed by https://github.com/containers/podman-desktop/pull/3435, already available in v1.3.1
