### ISSUE TITLE
Allow launching backend containers with Extension

### ISSUE THREAD

**Issue by doppleware** [containers/podman-desktop#2397]
### Is your enhancement related to a problem? Please describe

Similar to Docker Desktop extensions, where it is possible to specify a Docker Compose file that specifies additional background containers needed for the extension to run (database, server etc.)

### Describe the solution you'd like

Specifying which containers to run, maybe via Podman Compose

### Describe alternatives you've considered

I tried importing my Docker Extension but its compose file was just ignored

**Comment by benoitf** [comment]
might be a subtask of https://github.com/containers/podman-desktop/issues/2390

**Comment by benoitf** [comment]
@doppleware could you please tell which Docker Desktop extension you tried ?

**Comment by doppleware** [comment]
Hi @benoitf it is this extension:
https://hub.docker.com/repository/docker/digmaai/digma-docker-extension/

(I'm the author)
