### ISSUE TITLE
Automated website usability testing

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2402]
### Is your feature request related to a problem? Please describe

We have lots of automated testing in the project, but none that verify that the website is actually usable. Besides changes directly to the website, there are cases where changes to common things (e.g. tailwind config) can inadvertently break the site.

### Describe the solution you'd like

We should have more automated testing of the website, e.g. basic a11y or link checking to confirm that there are no major regressions.

**Comment by cdrage** [comment]
We can do `yarn build` in the CI? If there are any dead links / broken configuration, it wont proceed.

**Comment by benoitf** [comment]
@cdrage AFAIK we already build/check the website when we update the website but there is no rendering test

**Comment by deboer-tim** [comment]
Sorry, I wasn't thinking of what we already do check in the build either. I've edited the title and description to try to make it more clear the specific regression I caused (via PR #2360), and which I think we could figure out how to automate tests to avoid in the future. It's probably still not 100% clear, but I think good enough for planning purposes.
