### ISSUE TITLE
Dashboard doesn’t store state of buttons

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#2403]
### Bug description

When any button appears on dashboard and it launch some UI changes or process(like install or initialise) that state doesn’t stored. For example, if I click on `Initialize` button and then open `Settings` page and go back to dashboard, it will show me same `Initialize` button, like I never click on it:

https://github.com/containers/podman-desktop/assets/929743/ba98e663-ab8a-4184-9eb5-9b75796fccf8

Similar issue https://github.com/crc-org/crc-extension/issues/73 

### Operating system

 macOS 13.2.1 Intel

### Version

next (development version)

### Steps to reproduce

Delete podman vm, launch podman-desktop, click on `Initialize and start` button on podman dashboard widget, then click on `Settings` button, and return back to dashboard.

**Comment by gbraad** [comment]
According to the state given to our issue; this is `summit-critical`. Please mark it as such.

/cc: @nichjones1
