### ISSUE TITLE
brew uninstall podman-desktop leaves `~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist`

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2404]
### Bug description

trying to reset my machine to do some more testing and noticed `~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist` is still on my machine after having run `brew uninstall podman-desktop`

shouldn't that clean it up?

### Operating system

macos silicon

### Version

0.14.1

**Comment by benoitf** [comment]
fixed by https://github.com/Homebrew/homebrew-cask/pull/147666
