### ISSUE TITLE
podman docker compatability warning/text misleading/confusing

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2406]
### Bug description

I run podman desktop on clean machine.
Then on startup asks to install podman. all good.

Then shows me this screen:

![2023-05-09_16-15-36](https://github.com/containers/podman-desktop/assets/54129/03bd7eab-c3a2-4aaf-8a7b-6c12bd2c55c9)

Telling me "Warning: Docker Socket Compatability." - cool. Docker socket compatibility is on.

"Docker -specific tols may not work. Press 'Docker compatability' button to enable"

Wait - it just said "Docker socket compatibility" ...maybe it should be:
"Warning: Docker Socket Compatability is disabled. Docker specific tools may not work...."
?

So okey - I press docker compatibility despite it showing a plug as if already on and I get:

![2023-05-09_16-15-41](https://github.com/containers/podman-desktop/assets/54129/ce12fec1-6cab-4bad-9deb-40931a3cf6b4)

"Do you want to automatically disable Docker socket compatibility mode for Podman? The podman mac helper binary will be run.This requires administrative privileges."

So:

A) what does "automatically disable Docker socket" mean ? if it requires me to manually do something it is not automatic.

B) reading this dialog it is very ambiguous if docker socketcompatablity is on or not - but I *think* its on?

If it is on it should say "Do you want to disable automatic Docker socket compatibility mode for Podman? This will require administrative privileges" (no need to talk about implementation detail upfront. show it when actually clicking disable" 

Now I click "Disable" even though I'm trying to enable it.

I get asked for password (all good)

Then I get:

"Docker socket compatibility mode for Podman has been disabled. Restart your Podman machine to apply the change"

...I haven't even made it to realizing what podman machine is here. What is I as new user supposed to do ?

Why is it not just restarting it for me - or in this case not talking about it as podman machine is not running yet.

### Operating system

macos silicon

### Version

0.15.0

**Comment by maxandersen** [comment]
note, I tehn went and clicked "restat" under settings > resources (really hard to know) and i get "restart failed"..

```
Error: dial unix /var/folders/mm/z7zzmyl15bd8byr8vsdxf1740000gn/T/podman/podman-machine-default_ready.sock: connect: no such file or directory
```

**Comment by maxandersen** [comment]
also - when clicking enable - it does not tell me to restart podman machine. expected?

**Comment by cdrage** [comment]
@maxandersen I've added a PR to update the wording. https://github.com/containers/podman-desktop/pull/2818

I'm going to work on adding a button to actually restart the active podman machine after enabling / disabling the compatibility mode.
