### ISSUE TITLE
Kubernetes suite 1: on Windows, the pod list needs to be manually refreshed.

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2407]
### Bug description

Kubernetes suite 1: on Windows (installer), the pod list needs to be manually refreshed.

### Operating system

Windows 10 Professional

### Version

next (development version)

### Steps to reproduce

1. Run the latest binary from the repository prereleases.
2. Start a container
3. Deploy to Kubernetes
4. Open the **Pods** page: the pod is absent.

Workaround: refresh the Pods page with Ctrl + r.

Expected: the pod is in the list without a manual refresh.

**Comment by odockal** [comment]
Possibly duplicate of #2372.

**Comment by nichjones1** [comment]
Closing as it is a duplicate of 2372
