### ISSUE TITLE
be able to specify rootfull when doing init or restarting

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2408]
### Is your enhancement related to a problem? Please describe

due to #1771 we still need to run with rootful when using testcontainers but with podman desktop that is not easy.

### Describe the solution you'd like

would be great when creating or restart podman machine that there is a "rootfull" checkbox to change that setting without having to manually stop/start.

**Comment by slemeur** [comment]
duplicate of https://github.com/containers/podman-desktop/issues/2078

**Comment by benoitf** [comment]
closing as dup of https://github.com/containers/podman-desktop/issues/2078
