### ISSUE TITLE
podman desktop create UI is too fine grained

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2410]
### Is your enhancement related to a problem? Please describe

![2023-05-09_16-38-50](https://github.com/containers/podman-desktop/assets/54129/28574eed-9670-41c4-8131-f11f6ed60e6b)

Those sliders are bad UI imo as makes it super hard to do what corresponds to:

`podman machine init --cpus 4 --memory 8192 --disk-size 250`

### Describe the solution you'd like

provide text fields to edit the values and possibly add some "locking" of values to standard boundaries.

i.e.1024, 2048, 4192, 8192, ... for memory.

**Comment by benoitf** [comment]
closing as duplicate of https://github.com/containers/podman-desktop/issues/2319
