### ISSUE TITLE
Compose onboarding: Improve update / version information

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2411]
### Is your enhancement related to a problem? Please describe

I install podman desktop and see Compose download button.

I click it and is shown:

![2023-05-09_16-45-54](https://github.com/containers/podman-desktop/assets/54129/64bc970c-771d-415a-bf6d-fae3ea7522b5)

what is the user supposed to do/know?

### Describe the solution you'd like

a) explain why user would want/need to install docker compose.
b) provide reasonable default version to install
c) don't show dropdown list with 5 different 2.17's unless user really want/need to change it.

**Comment by slemeur** [comment]
Linking to https://github.com/containers/podman-desktop/issues/2523

**Comment by cdrage** [comment]
Hey @maxandersen I've changed the title of this issue to better reflect what's going on + I've assigned it for this sprint planning.

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop/assets/6422176/ae9e87b2-f387-45e8-83da-d03f1fc7e33f


Sept 8th update on the progress so far (as part of the onboarding for Compose)

Will start to implement other parts of your suggestion (not include rc, etc.)
