### ISSUE TITLE
Nginx pod throws an error when deployed on OpenShift Local using its microshift preset

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2416]
### Bug description

I have nginx container or pod, and if I try to deploy it on kubernetes when the context is set to OpenShift local microshift preset, I got an error `Error: pods "nginx-pod-kube" is forbidden: violates PodSecurity "restricted:latest"`.

### Operating system

Fedora 37

### Version

0.15.0

### Steps to reproduce

In progress.

### Relevant log output

```shell
Error: pods "nginx-pod-kube" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-podified" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-podified" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-podified" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-podified" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
```


### Additional context

_No response_

**Comment by rostalan** [comment]
Same issue on Fedora 38, trying to deploy a python-redis pod, get this error on microshift context.
![Screenshot_20230815_103322](https://github.com/containers/podman-desktop/assets/75624842/e2d238e2-d792-457c-86ee-abd3e3f572e5)

**Comment by jeffmaury** [comment]
You need to select the restricted profile option otherwise 80 port will not be allowed

**Comment by nichjones1** [comment]
FYI @praveenkumar

**Comment by praveenkumar** [comment]
@jeffmaury already answered https://github.com/containers/podman-desktop/issues/2416#issuecomment-1697117664 for microshift user need to select `Restricted Security Context` option.

**Comment by jeffmaury** [comment]
@odockal closing as it's not a bug to me. Feel free to reopen if you don't agree
