### ISSUE TITLE
Podman Desktop does not properly see what's in a podman machine

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2417]
### Bug description

I've got into a state where I have images listed from the CLI, but nothing displayed in Podman Desktop.

<img width="1753" alt="Capture d’écran 2023-05-09 à 17 17 29" src="https://github.com/containers/podman-desktop/assets/1636769/7e5f5af1-82e6-4580-a8ca-8cb980ee165d">

Things experimented:
- uninstall extension: no result
- create a new podman machine: no result
- changing the default connection of the podman machine: no result

Starting the podman machine from the CLI, before starting podman machine worked.

Here we are suspecting that Podman Desktop server code receive information about the socket when starting. But once the podman machine is effectively running, there might be something changing that Podman Desktop does not properly catch. 

### Operating system

Ventura

### Version

next (development version)

**Comment by benoitf** [comment]
bug has been introduced by https://github.com/containers/podman-desktop/pull/2306
reverting this PR make it works
