### ISSUE TITLE
Creation k8s connection page has multiple glitches

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#2420]
### Bug description

With https://github.com/crc-org/crc-extension/pull/98 we introduce creation of k8s connection.
But UI page has multiple glitches:

- It double `Start`, `Stop` and `Show log` buttons:
<img width="1000" alt="Screenshot 2023-05-10 at 10 52 26" src="https://github.com/containers/podman-desktop/assets/929743/36020f21-8256-464d-9860-a715070b7ad2">

- `Show logs` UI seems broken:

![237138581-01766f0a-2e02-4993-b1be-666cd3a65a87](https://github.com/containers/podman-desktop/assets/929743/e6bb9ef1-32d3-4853-b52d-3c68a0b148d4)
And it never show any logs, it is always empty.

- Creation log text, sometimes overflows it widget:
<img width="798" alt="Screenshot 2023-05-10 at 10 47 15" src="https://github.com/containers/podman-desktop/assets/929743/fe3ef04a-5211-4daf-b872-740cdb42445b">

### Operating system

 macOS 13.2.1 Intel

### Version

next (development version)

### Steps to reproduce

Use OpenShift Local extension from https://github.com/crc-org/crc-extension/pull/98
Go to resource page, and try to create new connection.

**Comment by gbraad** [comment]
/cc: @nichjones1 This one is a blocker for us.

**Comment by jeffmaury** [comment]
Need to check with kind provider
