### ISSUE TITLE
No option to create pod resource in case only openshift-local is running

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2421]
### Bug description

I am testing the extension installation without running any container engine and that works as expected to install OpenShift-Local extension and I am now following state (openshift local running and podman is not initialise or running)

<img width="1022" alt="Screenshot 2023-05-10 at 1 55 27 PM" src="https://github.com/containers/podman-desktop/assets/410007/95b3dcbf-e813-4973-93e5-a73ca12d2b8a">

Since Now I have running cluster I should able to experiment `pod` resource because that resource can be directly created using k8s api and doesn't need a container runtime like `containers` and `images` required but I get blank response from Pod view side. 

<img width="1044" alt="Screenshot 2023-05-10 at 1 59 04 PM" src="https://github.com/containers/podman-desktop/assets/410007/72f1fb79-26d2-4f1f-b9a7-2ecfce26bf99">

### Operating system

13.3.1 (22E261) (M1)

### Version

next (development version)

**Comment by gbraad** [comment]
Reproducible; reported as https://github.com/crc-org/crc-extension/issues/134 too.

**Comment by benoitf** [comment]
it has been fixed by https://github.com/containers/podman-desktop/pull/2929
