### ISSUE TITLE
Podman machine status in podman desktop is out of sync with podman machine on windows when OpenShift Local is running

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2429]
### Bug description

I am seeing quite a problematic behavior in podman desktop. I am not able to get state of podman machine on the system into podman desktop.
In PD it says OFF or does not show the machine at all. But in the cli I can see macine running.

![pd-machine-no-in-sync](https://github.com/containers/podman-desktop/assets/19164299/e38a1f93-bde5-4e8a-833b-d1f9d53eb001)

### Operating system

Windows 10

### Version

0.15.0

### Steps to reproduce

I am not sure about reproducer, but I talked to two other people experiencing something similar. 
For me it was installation of OpenShift Local, which also requires restart, that I suspect to be the initiator of the behavior.

### Relevant log output

[console.log](https://github.com/containers/podman-desktop/files/11442205/-1683724265937.log)

**Comment by odockal** [comment]
While the dashboard shows correct state:

![pd-podman-running](https://github.com/containers/podman-desktop/assets/19164299/05b9f8a9-88ed-48bd-9e1b-d82b5627c93c)

**Comment by odockal** [comment]
what helped was removing all existing podman machines and creating a new one using podman desktop.

**Comment by odockal** [comment]
Problem is that once I crate new machine and try to pull an image I get `Could not connect to Podman Machine: No provider with a running engine`. I have to restart podman desktop in order to make it work.

**Comment by themr0c** [comment]
Same as @odockal,on Windows 10 Pro: I installed CRC, started a Microshift instance, and I have the same ` Could not connect to Podman Machine: No provider with a running engine` error message when pulling the `nginx` image.

I restarted the podman machine without success.

I exited Podman Desktop and restarted it. Then I could pull the image.

**Comment by themr0c** [comment]
With v0.0.202305110927-542741c:
After reboot:
* Podman machine is running.
* OpenShift Local (MicroShift) is off / started (I tested both situations).
* Docker desktop is running.
* Image pull is failing on Podman, successful on Docker.

Deleting the Microshift isntance didn't help.
Stopping the extension didn't help.
Removing the extension without stopping Podma Desktop didn't help.
Removing the extension, Stoping Podman Desktop, Restarting Podman Desktop helped.

**Comment by themr0c** [comment]
Using version v0.0.202305111142-99fecee it seems fixed.

**Comment by odockal** [comment]
I have not encountered the issue lately with 1.0. I would say this has been resolved. Will close the issue for now.
