### ISSUE TITLE
Smaller Podman tile in the dashboard

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2430]
### Is your enhancement related to a problem? Please describe

With the new **Featured extensions** tile in the Dashboard, the **Podman** tile is taking to much space in the screen.

With the **Featured extensions** tile, you already need to increase the default window size to see all the content.

If you start the installation of one of the extensions, you need to scroll or increase even more the window size.

### Describe the solution you'd like

Reduce the size of the **Podman** tile.

### Describe alternatives you've considered

Increase the default size of the screen.

### Additional context

![Screenshot from 2023-05-10 14:42:24 Selection 1485x1035 01](https://github.com/containers/podman-desktop/assets/243761/7a1a1cdb-d3d9-4b8f-9a98-261f696e001d)
![Screenshot from 2023-05-10 14:44:34 Selection 1479x1034 01](https://github.com/containers/podman-desktop/assets/243761/1556ad1c-1423-4dc7-8dfe-8146fdcc6ac5)

**Comment by deboer-tim** [comment]
It's not just the Podman tile, it's an accumulation of all provider's tiles. IMHO this should just feed into a general redesign of the dashboard.

cc @mairin

**Comment by benoitf** [comment]
there is already issues on the new design: https://github.com/containers/podman-desktop/issues/1230
you can comment out there

**Comment by mairin** [comment]
I actually did a quick redesign of this a while back
![Board](https://github.com/containers/podman-desktop/assets/799683/76310bc6-2a5d-4680-a244-1ed3abe04801)
 to slim it down and started trying to implement it and gave up :sweat:

But that was meant as an interim thing, agreed with @deboer-tim this really needs a dashboard redesign.
