### ISSUE TITLE
System tray menu for all providers

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2432]
### Is your feature request related to a problem? Please describe

Fabrice pointed out that the Kind extension has no system tray menu.

### Describe the solution you'd like

Instead of adding a menu specifically for this extension, I think we should automatically generate a menu for all providers, basically exposing the same actions that are available in Settings > Resources. Why? Consistency (don't need to worry about one provider doing something slightly different) and one less thing for each provider to do. If we follow a pattern, providers can add any additional items like opening a console.

**Comment by benoitf** [comment]
AFAIK every provider that provides lifecycle have their tray icon automatically registered
