### ISSUE TITLE
Building an image adds docker.io to the beginning?

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2433]
### Bug description

When you build an image, I expect the image name to *not* have docker.io added to it.

![Screenshot 2023-05-10 at 10 07 34 AM](https://github.com/containers/podman-desktop/assets/6422176/a7c98857-8856-4558-a24d-b8d191921f7c)

### Operating system

Mac M1

### Version

next (development version)

### Steps to reproduce

1. Build an image, set the name to `my-python-app:1.0`
2. On image screen, I expect `my-python-app` but I get `docker.io/library/my-python-app` instead.

**Comment by jeffmaury** [comment]
Seems to be upstream as running podman build . -t myimage on a Linux box generates the same image tag
