### ISSUE TITLE
Nginx app has permissions problems when deployed on sandbox cluster

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2438]
### Bug description

I am following the kubernetes testing suite with nginx image/app to be deployed on a cluster. This time I am using sandbox extension. Pod is running, but in the log one can see permission denied errors.

### Operating system

Fedora 37

### Version

0.15.0

### Steps to reproduce

1. Have podman installed
2. Install sandbox extension (ghcr.io/redhat-developer/podman-desktop-sandbox-ext:latest)
3. try to create new sandbox instance (Settings -> Resources -> Developer Sandbox -> Create new)
4. Login to the sandbox account and copy login command (as advised)
5. Set context name, ie. `my-sandbox`
6. Paste login command
7. Create sandbox
8. Check in system tray the new context is available, switch to it
9. Pull an `nginx` image
10. Start a container from `nginx` image
11. Verify it is running (localhost:9000)
12. Stop the container
13. Deploy container to the kubernetes, select to `Create Openshift route` and `Use kubernetes services`, context: `my-sandbox`
14. Assert: Pod is deployed (`pod is running`) and the app is available through the link provided in `Deploy generated pod to Kubernetes` page (link by the pod creation status)
Actual result: Pod is in Terminated state, app is not reachable:

![Screenshot_20230510_175652](https://github.com/containers/podman-desktop/assets/19164299/12acf48b-3f4d-44cb-a6b7-1f3508ccf527)

although pod is shown running, logs says there are some permission issues.

### Relevant log output

```shell
nginx-con  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-con  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-con  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-con  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
nginx-con  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-con  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx-con  | 2023/05/10 15:57:21 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2023/05/10 15:57:21 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx-con  | nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

```
```


### Additional context

_No response_

**Comment by jeffmaury** [comment]
This is not a bug, OpenShift is preventing root thus port 80

**Comment by odockal** [comment]
Alright, so what I have to do in order to use Sandbox as a cluster where can I deploy app. from podman desktop?

**Comment by jeffmaury** [comment]
Use another image see https://github.com/redhat-developer/podman-desktop-demo/pull/5

**Comment by odockal** [comment]
thanks. `httpd-24-centos7` works nice.
