### ISSUE TITLE
Report success or failure on Push image

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2457]
### Is your enhancement related to a problem? Please describe

When you *Push image to Kind cluster*, *Push image to OpenShift Local cluster*, *Push image to Kubernetes cluster*, you don't receive a success or error message. This is confusing: you don't know if the image was successfully pushed to the cluster or not.

### Describe the solution you'd like

Display a success or failure message.

### Describe alternatives you've considered

On the *Images* screen, display next to the image the list of registries that have the image (container engine with name, kubernetes cluster with name). The user could then rely on the image list to find the information.

**Comment by benoitf** [comment]
it is not handled by https://github.com/containers/podman-desktop/pull/2361 ?

**Comment by benoitf** [comment]
and a dup of https://github.com/containers/podman-desktop/issues/2166

**Comment by themr0c** [comment]
Oh, indeed, there was a notification hidden in the system notifications. This is confusing: for all other workflows, the feedback is happening in the application itself. I was not expecting a system notification and not monitoring the system tray for notifications.

**Comment by themr0c** [comment]
Closed as the planned taskbar is a better idea.
