### ISSUE TITLE
'select' and 'stop' square icons are too similar

### ISSUE THREAD

**Issue by cfergeau** [containers/podman-desktop#2458]
### Is your enhancement related to a problem? Please describe

If you look at the list of running containers, on the left there's a gray square to select the container, and on the right there's another gray square to stop the container. 
These icons are used in other places, for example in the extension list, I always think the square will select the extension. When I click on it, it stops it, then I realize I confused the 2 icons.

### Describe the solution you'd like

Icons which are easier to differentiate for these 2 things.

**Comment by deboer-tim** [comment]
FYI @mairin

**Comment by mairin** [comment]
A couple of thoughts on this one... This is a really good observation, I never noticed how close they are right now.

- We could darken the selection boxes on the left side and have the checkboxes defined primarily via the outline rather than the fill
- We could bring back the circle background on the action icons on the right side (they appear on hover, we dropped them being persistent a few weeks back)
- We could use a different version of the stop icon but we'd probably have to modify the play one too. We could maybe look at other icon libraries too but it'll probably involve having some sort of backdrop shape to the basic rectangle.

Open to other ideas too!

**Comment by deboer-tim** [comment]
A square for stop is pretty common, and especially if we're using solid icons it's going to be hard to find something else that works as well. I also prefer the flat look we have now and don't think a background would change the stop button enough.

So I prefer the first option - I think removing/reducing the fill could make the checkboxes look less like actions and different enough.

**Comment by mairin** [comment]
So I started going thru some of my containers screen mockups and noticed 😄 that they use the outline checkbox (and a purple checked checkbox, it's a font awesome glyph.) So I think this would be sufficient differentiation from the solid stop icon square:

![Screenshot from 2023-05-31 10-47-06](https://github.com/containers/podman-desktop/assets/799683/edcb7c6d-cab4-4413-b666-48db833e7e48)

Here's how it looks superimposed on a current screenshot:
![Screenshot from 2023-05-31 10-53-55](https://github.com/containers/podman-desktop/assets/799683/cdd016f3-b329-4f36-95c8-3cc771645bd6)

**Comment by cfergeau** [comment]
Yep, they are much easier to differentiate this way!

**Comment by deboer-tim** [comment]
@mairin I only see two states above, but we have disabled (e.g. can't delete an image being used), unselected, and selected. I assume 'disabled' is the missing one, maybe just a darker version of the outline?

Edit: oh, and 'indeterminate', e.g. the status of the one in the header when 2/3 are selected.

**Comment by mairin** [comment]
@deboer-tim oh whoops let me mock those up. The disabled btw is very annoying lol. I'd rather it delete the container along with the image if need be (but my containers are cattle not pets.) 

sec and ill get those posted

**Comment by mairin** [comment]
![Screenshot from 2023-06-01 13-18-15](https://github.com/containers/podman-desktop/assets/799683/aa1a9496-07bf-40aa-a41f-253c272194ad)

- **selected** fa-square-check - purple-500
- **mixed** - fa-square-minus - dusty-purple-500
- **unselected** just using a square with stroke 1, rounded 2, gray-400 stroke
- **disabled** just using a square with 0 stroke, rounded 2, charcoal-300 fill
