### ISSUE TITLE
Add a **rootful** option in **Settings > Resources > Create a Podman machine**

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2460]
### Is your enhancement related to a problem? Please describe

Starting a Kind cluster on Windows requires rootful mode.

This requires the user to do an additional CLI step to modify the Podman machine connection.

The user could use the `podman machine init` `--rootful` option to create a Podman machine that has correct connection setup out of the box.

However, this option is not available in the **Settings > Resources > Create a Podman machine** dialog.

### Describe the solution you'd like

Add a **Rootful** option in **Settings > Resources > Create a Podman machine**.

Name: **Rootful**

Description: Set the default connection to rootful. Required to run Kind on Windows.

**Comment by benoitf** [comment]
closing as dup of https://github.com/containers/podman-desktop/issues/2078

**Comment by themr0c** [comment]
Merged yesterday? Too bad I didn't update first. Updating now.
