### ISSUE TITLE
document creating a custom Podman machine

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2461]
### Is your enhancement related to a problem? Please describe

Since https://github.com/containers/podman-desktop/issues/2078 is merged, the **Settings > Resources > Create a Podman machine** has a new **Rootful** option.

The documentation for Kind doesn't mention this option.

### Describe the solution you'd like

Document creating a custom Podman machine.

Explain why you would want to do this.

* Rootful: required to create a Podman machine for Kind on Windows
* Image path: to specify a custom Podman machine image source.

Simplify the getting started with Kind with this new feature.

**Comment by cdrage** [comment]
Looks like this was forgotten to be closed via https://github.com/containers/podman-desktop/pull/2466
