### ISSUE TITLE
nit: previous error persists in extensions view after a successful download

### ISSUE THREAD

**Issue by sympatheticmoose** [containers/podman-desktop#2463]
### Bug description

If a user tries to download an extension, but the image can't be found they get an error. 

If they then are able to successfully download and install an extension, the error from the previous attempt remains visible and cannot be dismissed, making it less whether the second attempt is actually successful and generally getting in the way.

To get rid of the error, they need to navigate to a different view and then back to the extensions view.

### Operating system

macOS Ventura 13.3.1 (m2)

### Version

0.15.0

### Steps to reproduce

See description 

### Additional context

<img width="774" alt="Screenshot 2023-05-11 at 11 51 23" src="https://github.com/containers/podman-desktop/assets/19860021/ed945afe-5bd2-4000-8326-11e29834f8f3">

**Comment by deboer-tim** [comment]
Good to hear from you again, David! Hope things are going well; this fix will be in the next release.

**Comment by sympatheticmoose** [comment]
Thanks @deboer-tim ! Hope you're doing well 😄
