### ISSUE TITLE
Error after closing main window

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#25]
**Describe the bug**
If I open container desktop and then close the window immediately, I get a popup window with "A JavaScript error occurred in the main process":
```
Uncaught Exception:
TypeError: Object has been destroyed
at Timeout._onTimeout (/Applications/container-desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:1:1973)
at listOnTimeout (node:internal/timers:557:17)
at processTimers (node:internal/timers:500:7)
```

**To Reproduce**
1. Launch container-desktop.
2. Click on the red X to close the window.
3. Wait 3-4s and notice the popup.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 12.2.1

**Comment by benoitf** [comment]
@deboer-tim it might be fixed now that we're hiding the Window (implementation of https://github.com/containers/desktop/issues/24)

It you could check with a recent build. Thanks.

**Comment by deboer-tim** [comment]
Fixed.
