### ISSUE TITLE
Extension Installation fails with invaild media type for config manifest

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#2505]
### Bug description

I wanted to test a PR from `crc-extension` and I built the image locally using podman desktop and uploaded it to ghcr.io but when I try to use same image for extension installation it fails like

<img width="1026" alt="Screenshot 2023-05-16 at 4 18 27 PM" src="https://github.com/containers/podman-desktop/assets/410007/a57b9d5f-9f00-49a6-bc67-d88e27c3c432">

Do we have any document around how to verify a extension image before pushing it to make sure it doesn't fail during the installation steps?

Same image works with podman pull
```
podman pull ghcr.io/praveenkumar/crc-extension:test
Trying to pull ghcr.io/praveenkumar/crc-extension:test...
Getting image source signatures
Copying blob sha256:6d5381dd727a0cfaffa5a769cbe85fd72c7bd72efd8212e424c8b2b555833d45
Copying blob sha256:3c796a7491093e6b91e8595194e56127d47b5d34ba2e8c039425aecdb5fee92d
Copying blob sha256:18146313dae1eaf6a35d5806c2333c0668be2b619eae5dab6a5863621cadfed5
Copying blob sha256:4a9dfcbb99774cf42d5166cbf0fea85b51579b35876509a344be8adfc9e52e60
Copying blob sha256:809e6c4a6ccc2f5aa0d289467cddfaffa0b323c07f0c5d766024e44065e33bf9
Copying config sha256:5c46888c76ccc61ae6ac9c2502107771647029420f37b0ff7bb82a36dcc73342
Writing manifest to image destination
Storing signatures
5c46888c76ccc61ae6ac9c2502107771647029420f37b0ff7bb82a36dcc73342
```

### Operating system

13.3.1 (22E261) (M1)

### Version

next (development version)

**Comment by jeffmaury** [comment]
To test an extension without image build and publish

Go to podman desktop source code and run `yarn watch --extension-folder your_extension_source_folder`

**Comment by praveenkumar** [comment]
> Go to podman desktop source code and run yarn watch --extension-folder your_extension_source_folder

I know the dev guide but sometime it is good to follow user-flow because in the past pushing image to kind or openshift local work with dev flow since the env path are taken from you current dev environment and it failed on installed version. I usually test the PR (both PD or extension side) using user-flow.

**Comment by praveenkumar** [comment]
It is fixed now with https://github.com/containers/podman-desktop/pull/2506 one. Closing the issue.
