### ISSUE TITLE
Deploy to Kind stopped Podman Desktop

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2507]
### Bug description

I have deployed a pod from podman desktop to Kind once. Deleted it and then tried to deploy it again.

https://github.com/containers/podman-desktop/assets/1636769/62e811d5-463b-4f8b-b833-4c91c6e0fac8

Getting an error:
<img width="1127" alt="Capture d’écran 2023-05-16 à 14 51 34" src="https://github.com/containers/podman-desktop/assets/1636769/75c05a15-86ee-4348-a123-01c3d397a97b">

### Operating system

Ventura 13.2

### Version

next (development version)

### Steps to reproduce

Used this sample app: https://github.com/redhat-developer/podman-desktop-demo/tree/main/primary-podify-demo

1- Get the app setup and running as a pod in Podman
2- Deploy for the first time to Kind (using the deploy to Kubernetes feature)
3- Delete the pod from the list of pods
4- Do another deploy of the pod using the deploy to Kubernetes feature

**Comment by jeffmaury** [comment]
I tried using the production bits on Windows and could not reproduce as the second time I deployed on the Kind cluster I got an error because the service already existed

**Comment by slemeur** [comment]
On my side, I've deleted the pod from the "Pods" List view.

**Comment by deboer-tim** [comment]
FWIW, I tried on dev build and had the same behaviour as Jeff - just service already exists error.

**Comment by slemeur** [comment]
I'm able to reproduce it with a fresh Kind cluster.
Note: I'm also pushing the image (python-app) to the Kind cluster.

**Comment by jeffmaury** [comment]
Can't reproduce on 1.1.0
