### ISSUE TITLE
When I try to pull an image and press an enter instead of clicking on the Pull button I am pointed to a strange uri

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2512]
### Bug description

![pullimage-enter](https://github.com/containers/podman-desktop/assets/19164299/e1667cae-b93f-4922-9412-674146085eff)

### Operating system

Fedora 37

### Version

next (development version)

### Steps to reproduce

1. Open Pull image page
2. insert image to pull
3. press enter

### Relevant log output

```shell
URI leads to: `file:///home/user/git/podman-desktop/dist/linux-unpacked/resources/app/packages/renderer/dist/index.html?serverUrl=nginx&providerChoice=%5Bobject+Object%5D#/images/pull`
```

**Comment by deboer-tim** [comment]
Are you on the latest/build from today? I am not able to reproduce and I think it was fixed by PR #2498.

**Comment by odockal** [comment]
@deboer-tim Well, I might have something from the earlier today. Will try again.

**Comment by odockal** [comment]
Aaand it is gone. thx for a hint.
