### ISSUE TITLE
"Failure" to create Kind cluster on HTTP request failure

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2515]
### Bug description

I have received the following error twice while creating a Kind cluster. When I exit the page, the cluster appears to exist and be running fine though, and you can see the success message above the error. I haven't found anything that isn't working.

```
...
Set kubectl context to "kind-kinder-cluster"
You can now use your cluster with:

kubectl cluster-info --context kind-kinder-cluster

Have a nice day! 👋

Error: Failed to create kind cluster. HTTP request failed
```

### Operating system

macOS 13.3 M1

### Version

next (development version)

**Comment by jeffmaury** [comment]
Blocker for 1.0.0
