### ISSUE TITLE
When using a FROM directive without designating a repository, a GUI does not reset.

### ISSUE THREAD

**Issue by IllusionaryX** [containers/podman-desktop#2517]
### Bug description

Used a docker file without repository designation (as is allowed if you have "unqualified-search-registries" set in conf). The problem is that after an error, Podman will not reset to allow the Containers->Create Containers->Containerfile or Dockerfile base screen with options to create a new container or try again after a fix. It sits stuck on a now blank output screen, and the build process remains in the "Running Tasks" window even though it has terminated.

Either an option to terminate the open task should be offered, or a the workflow should reset after build failure.

This may occur on other build issues as well, but have only documented this one.

NOTE: To fix must exit Podman Desktop and restart. Restarting Podman Machine does not resolve.

### Operating system

Windows 10 Pro Verion 22H2

### Version

0.15.0

### Steps to reproduce

As listed above 

- Include a FROM directive in a Dockerfile without clear repository indication.
- Build fails (If "unqualified-search-registries" is not set with baseline alternatives.)
- Fix Dockerfile
- Attempt to build again via "Containers"->"Create Containers"->"Containerfile or Dockerfile".
- Base Create Container screen is not available, and only blank output window exists.
- Also Build task still listed even with failure.

### Additional context

![Podman_error_No_Reset](https://github.com/containers/podman-desktop/assets/32284540/9aa9a5a5-8e5c-423c-bca4-ad74c21590ee)

**Comment by benoitf** [comment]
You might hit reload command to refresh the UI as well as workaround
