### ISSUE TITLE
Preferences: More information regarding compose status (version, update, compatibility)

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2523]
Create a Compose section in the podman desktop preferences so the user can:
- Know what is the version of compose used by Podman
- Have Update mechanism of the binary
- Know how to use the compose library (if compat mode is enable VS if compat mode is disable)
- Enable of disable the compose support

**Comment by cdrage** [comment]
I will assign the block label until we figure out the correct way of implementing the UI aspect / mockups.

**Comment by mairin** [comment]
For a first cut, to show the version number and provide a path to update the CLI tool, we should update the **Settings > Extensions** page to revamp the cards to have more features (similar to the Settings > Resources page's cards) to help enable this.

Here is the proposed mockup for the version number / update path:

![Screenshot from 2023-07-12 10-02-15](https://github.com/containers/podman-desktop/assets/799683/66e0a0d9-4239-49c8-8639-e7d99ae36d24)

Notes on the markings:

**(1)**: Listing for the version number of the installed CLI compose tool
**(2)**: If an update is available, notification to let you know and a link to allow update (via a pop-up, provided in another mockup.) **Also note, if an update is available, would be nice for it to display as a message in the task manager too.)**
**(3)**: Link to settings screen for Compose
**(4)**: Link to docker compat screen

**Comment by deboer-tim** [comment]
FWIW, I like the idea of being able to see what CLIs or container engines each extension has installed and see the details here... but I have 11 extensions installed, not sure how long and usable the page would be or if we need a place similar to Resource to see CLIs in one place. We can discuss on UX call.

**Comment by cdrage** [comment]
Reference the compose UX issue here: https://github.com/containers/podman-desktop/issues/2811 which is what we'll be implementing (the UX compose install improvements)

**Comment by cdrage** [comment]
![Image](https://github.com/containers/podman-desktop/assets/6422176/e2a17056-3b29-47e4-942a-c2b8fe166e17)



Progress so far (had to implement a few other buttons + way to get the functionality working).

https://github.com/cdrage/podman-desktop/tree/onboarding-compose

**Comment by cdrage** [comment]
I have opened up three issues that will cover the functionality of this "epic":

- [ ] https://github.com/containers/podman-desktop/issues/3707
- [ ] https://github.com/containers/podman-desktop/issues/3708
- [ ] https://github.com/containers/podman-desktop/issues/3709

**Comment by afbjorklund** [comment]
I closed the issues for showing Docker version and Lima version, in the same way as Podman version today.

At some point it would be nice to show the server version and not just the client version, instead of that info...

```
Client:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

Server:
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.20.8
Built:        Wed Sep 27 20:24:38 2023
OS/Arch:      linux/amd64
```

So the CLI list could show the `--version`, and the Dashboard could show the `version` - when it is running...
