### ISSUE TITLE
Podman Desktop not showing containers

### ISSUE THREAD

**Issue by lucasleon2107** [containers/podman-desktop#2532]
### Bug description

I ran a container using podman, and Podman Desktop does not show it. I see the container by running `podman ps`

<img width="1073" alt="image" src="https://github.com/containers/podman-desktop/assets/4566949/8eff29c6-2511-42e1-a231-6c5f6313419a">

<img width="1202" alt="image" src="https://github.com/containers/podman-desktop/assets/4566949/f5216c5d-5b20-44e6-9214-8d9e976d3955">

<img width="1044" alt="image" src="https://github.com/containers/podman-desktop/assets/4566949/6206e34f-a15e-4df2-a6f2-f56f9823e3cf">

### Operating system

macOS Ventura Version 13.3.1 (a) (Intel)

### Version

1.0.0

**Comment by slemeur** [comment]
Hi @lucasleon2107. Thanks for the report.

Would you be able to tell us what you have when you run the command: `podman version` and `podman machine info` ? 

Also, would be interesting to see if when you restart the application, it changes anything? 
If it does not, maybe we need to investigate the connections: `podman system connection list` 

Thanks for your help!

**Comment by slemeur** [comment]
Also, did you created the podman machine from the CLI or directly from Podman Desktop?

**Comment by lucasleon2107** [comment]
I think I fixed the issue by reinstalling podman on my machine. Another issue I noticed is that I couldn't pull images from the UI, and that was because the podman-desktop app couldn't find the podman.sock inside the `qemu` folder. The file was located in the `machine` folder, so I had to copy and paste the file for it to work

**Comment by johnnykang** [comment]
i believe i have the issue with Podman-Desktop not showing the containers on the UI, but the podman ps shows the running containers fine.

I created the podman machine via the CLI though.

**Comment by benoitf** [comment]
closing as not reported since and it was fixed by reinstalling podman on the user side
