### ISSUE TITLE
After uninstalling Kind, Podman Desktop still believes it is available

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2534]
### Bug description

After uninstalling Kind, Podman Desktop still believes that it is there. 
<img width="1162" alt="Capture d’écran 2023-05-18 à 11 22 44" src="https://github.com/containers/podman-desktop/assets/1636769/0a9f7956-fa91-4948-b637-10b4b2aefc46">

### Operating system

Ventura 13.3

### Version

1.0.0

### Steps to reproduce

- Hard uninstall from mac with `rm -rf /usr/local/bin/kind` 
- Restart Podman Desktop

Result:
- Does not see that Kind is not present anymore
- Raise an error when creating a kind cluster
- Does not propose to re-install

**Comment by deboer-tim** [comment]
This image above is just showing that the Kind _extension_ is running, not Kind itself. Issue #2379 is already open to track using a different term for extensions.

Not trying to downplay the real problem here, just making sure nobody gets confused by the image.
