### ISSUE TITLE
Loader not part of the dashboard's UI container

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2535]
### Bug description

When initializing and starting podman, a loader is getting displayed. That loader is not part of the "Podman dashboard UI container" and you can see it, if you scroll down.

### Operating system

Ventura 13.3

### Version

1.0.0

### Steps to reproduce

https://github.com/containers/podman-desktop/assets/1636769/2ef87fa3-c95a-400e-ada4-c99884ed206b

**Comment by lstocchi** [comment]
Closing as #2959 was merged
