### ISSUE TITLE
Changing the OpenShift local preset in preferences shows a warning dialog with last opened URL via link in PD

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2541]
### Bug description

I was deploying an app to the dev sandbox, then I started to play with openshift local.
When I am changing openshift preset in preferences I got a warning dialog "to apply changes you need to create new instance" and under that there is an sandbox route I used before:

![sandboxroute-openshiftpresetchange](https://github.com/containers/podman-desktop/assets/19164299/9263bac9-2e42-421b-b0e3-f100b9f792ac)

### Operating system

Fedora 37

### Version

1.0.0

### Steps to reproduce

1. Install OpenShift local
2. go to preferences OpenShift local ext.
3. Click on a link under pull secret file section - download from the ...
4. Try to change preset
5. ASSERT: Message contains correct text only
Actual result: correct text + last url visited in podman desktop

**Comment by deboer-tim** [comment]
I found this last night as well, any detailed message is not cleaned up. I have a fix, will PR shortly.

**Comment by odockal** [comment]
@deboer-tim nice!
