### ISSUE TITLE
Windows podman machine creation does not respect number of CPUs choosen

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2558]
### Bug description

On windows, I am creating new podman machine and choose ie. 4 CPUs. When the machine is created there is 8 CPUs.
Same result can be observed when I check the command line `podman mahcine ls`.

When I try to create a machine on cli, the result is the same, so I would sum this up to be upstream issue. I have not found this issue here, so I will fill it in anyway.

 

### Operating system

Windows 10

### Version

1.0.0

**Comment by jeffmaury** [comment]
I think it's related to WSL. Can you try from the CLI

**Comment by odockal** [comment]
The same. manually initiating a machine with random number of cpu and starting it ends up with maximum number of cpus dedicated for the machine. So it is upstream issue.

**Comment by cbr7** [comment]
Issue still present in Podman Desktop 1.8 with podman 4.9.3, the podman machine is not created with the indicated values and the values differ when checked in Podman Desktop and podman CLI.

![image (1)](https://github.com/containers/podman-desktop/assets/106525396/5bd0463b-870b-4dd8-96e1-8872435b200a)

The podman machine from the image was supposed to be created with 2 CPUs, 5 GB of RAM and 100 GB disk space.

**Comment by odockal** [comment]
I was not able to reproduce with podman v5 (using cli) and hyperv, which seems to be the difference.

**Comment by odockal** [comment]
Seems like upstream issue (https://github.com/containers/podman/issues/19443) was closed.

**Comment by odockal** [comment]
After reading some man pages for podman-machine-set, I think that podman desktop should be able to notify uset about the fact, that adjusting any of CPU/DiskSize/Memory wont work in podman desktop Create New Machine. 
We could either disable the buttons, or print out a warning in the UI and provide an explanation or a link.

**Comment by jeffmaury** [comment]
CPU, memory and disk size are not relevant for WSL, they should not be available for the user
