### ISSUE TITLE
Plenty of EINVAL errors appearing in the console log on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2559]
### Bug description

I am seeing a lot of `Unhandled promise rejection warning` errors in the console log. I have podman machine with a rootful connection, kind created. That is all I can say about how to reproduce.

### Operating system

Windows 10

### Version

1.0.0

### Steps to reproduce

1. Podman desktop running (1.3.0-next) and podman installed (4.6)
2. Initialize and start podman machine via dashboard (by default rootless)
3. Watch dev console log for errors.

### Relevant log output

```shell
dex.ts:1327 main ↪️ (node:4620) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, stat '//./pipe/'
(anonymous) @ index.ts:1327
emit @ VM14 sandbox_bundle:2
onMessage @ VM14 sandbox_bundle:2
index.ts:1327 main ↪️ (node:4620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 477)
(anonymous) @ index.ts:1327
emit @ VM14 sandbox_bundle:2
onMessage @ VM14 sandbox_bundle:2
```

**Comment by benoitf** [comment]
@odockal wondering why `extension/kind` has been added, I don't see any kind error in the issue ? is it more `extension/podman` ??

**Comment by odockal** [comment]
@benoitf No idea. Probably a mistake. sorry. I might see the problem in the past when kind was installed.

**Comment by odockal** [comment]
On Windows 10 this is happening almost all the time when I have a podman machine up (rootless/full). Now even with podman 4.6.2
