### ISSUE TITLE
`Build Image from Containerfile` form cannot be used after 'Error:(HTTP code 400)' reported in log

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#2568]
### Bug description

After the error is reported, the form always looks like on image below. 

![image](https://github.com/containers/podman-desktop/assets/620330/11e733cb-1a52-4d87-90ac-ea1192a16b5c)

### Operating system

macOS M1 13.3.1

### Version

1.1.0-next (development version)

### Steps to reproduce

There is no exact steps to replicate. 

### Relevant log output

```shell
See screenshot above:


LogService.ts:60 xterm.js: Parsing error:  
Object
_log	@	LogService.ts:60
error	@	LogService.ts:83
(anonymous)	@	InputHandler.ts:374
parse	@	EscapeSequenceParser.ts:661
parse	@	InputHandler.ts:485
(anonymous)	@	CoreTerminal.ts:145
_innerWrite	@	WriteBuffer.ts:164
(anonymous)	@	WriteBuffer.ts:124
```
```


### Additional context

_No response_

**Comment by dgolovin** [comment]
Cannot replicate it anymore.

**Comment by dgolovin** [comment]
This error is back for me. After starting podman-desktop with 'yarn watch' first build of image from https://github.com/dgolovin/httpd-24-demo/blob/main/Containerfile works fine. Then second attempt fails with error above.

**Comment by DonSchenck** [comment]
I had this error. I went into Settings --> Registries and deleted my registries and this error went away. FWIW.

**Comment by dgolovin** [comment]
Cannot replicate it. Even connectivity issues handled correctly and don't block from building another image.
Closing.
