### ISSUE TITLE
Podman machine created with root privileges is not respected when there are more than one machine

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2582]
### Bug description

I am assuming that creation of a podman machine with root-privileges on will choose root system connection as a default, so once started, root connection is used. 

this is true when there is no machine on the system and we are creating a new one. When there is a machine (with system connections) already, root system connection of the newly created machine is not set.

![rootfulmachine](https://github.com/containers/podman-desktop/assets/19164299/9e3bc6dc-408b-490f-a04d-342161b7546a)

### Operating system

Windows 10

### Version

1.0.x

### Steps to reproduce

1. Start podman desktop on the windows. 
2. Install, initialize and start podman machine on it (rootless by default)
3. Create new machine, where we want root privileges to be applied.
4. Start the new machine and check whether is has root privileges
5. Ie. One can create new kind cluster connection
Actually, kind cluster creation says I have to use rootful connection or setup rootless (workaround)
Cli shows that root system connection of the new machine was not set as default and thus new machine is using old (rootless) connection of the old machine.

**Comment by jeffmaury** [comment]
This is a behavior of Podman when a default connection already exists it is not overriden. Podman desktop does not uses the connection but uses the socket so can you ensure that the newly created machine as root privileges from Podman Desktop ?

**Comment by odockal** [comment]
@jeffmaury I am not really sure what exactly should I do, can you please help me bit more ?

**Comment by jeffmaury** [comment]
Deploy a privileged container on that machine and check it runs successfully

**Comment by themr0c** [comment]
I can confirm in this scenario on Windows 11 Pro:

1. Initialize and start default Podman.
2. Stop Podman.
3. **Settings > Resources > Podman > Create new** Enable root privileges
4. The default connection is still on the first machine:

```
podman.exe system connection list
Name                         URI                                                          Identity                                                  Default
podman-machine-default       ssh://user@127.0.0.1:54826/run/user/1000/podman/podman.sock  C:\Users\Podman Desktop User\.ssh\podman-machine-default  true
podman-machine-default-root  ssh://root@127.0.0.1:54826/run/podman/podman.sock            C:\Users\Podman Desktop User\.ssh\podman-machine-default  false
podman-machine-rootful       ssh://user@127.0.0.1:49517/run/user/1000/podman/podman.sock  C:\Users\Podman Desktop User\.ssh\podman-machine-rootful  false
podman-machine-rootful-root  ssh://root@127.0.0.1:49517/run/podman/podman.sock            C:\Users\Podman Desktop User\.ssh\podman-machine-rootful  false
```

5. Start the new Podman machine.
6. Message: "Podman Machine 'podman-machine-rootful' is running but not the default machine (default is 'podman-machine-default'). This will cause podman CLI errors while trying to connect to 'podman-machine-rootful'. Do you want to set it as default?". Click Yes.
7. Message: "Podman Machine 'podman-machine-rootful' is now the default machine on the CLI."
8. The Podman machine that you created rootful is rootless:

```
podman.exe system connection list
Name                         URI                                                          Identity                                                  Default
podman-machine-default       ssh://user@127.0.0.1:54826/run/user/1000/podman/podman.sock  C:\Users\Podman Desktop User\.ssh\podman-machine-default  false
podman-machine-default-root  ssh://root@127.0.0.1:54826/run/podman/podman.sock            C:\Users\Podman Desktop User\.ssh\podman-machine-default  false
podman-machine-rootful       ssh://user@127.0.0.1:49517/run/user/1000/podman/podman.sock  C:\Users\Podman Desktop User\.ssh\podman-machine-rootful  true
podman-machine-rootful-root  ssh://root@127.0.0.1:49517/run/podman/podman.sock            C:\Users\Podman Desktop User\.ssh\podman-machine-rootful  false
```

**Comment by jeffmaury** [comment]
Looks like an upstream Podman issue

**Comment by jeffmaury** [comment]
So this is not an upstream issue but this is being blocked by https://github.com/containers/podman/issues/18479

As we can know if the machine is rootless or rootful, we are setting the connection to the non root one.
