### ISSUE TITLE
Unable to start OpenShift Local extension on Fedora SIlverblue

### ISSUE THREAD

**Issue by pacificera** [containers/podman-desktop#2603]
### Bug description

Openshift Local is not addressable after installing due to an error.

### Operating system

Fedora 38 Silverblue

### Version

1.0.x

### Steps to reproduce

Installed podman and then pressed the install button for openshift local.  The top screen shows changes its icon from the "download" icon to "installed."  

Went to the settings -> extensions -> openshift local and discovered this error:

```
Error: Unable to find extension API at e._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:83:25897) at Module.require (node:internal/modules/cjs/loader:1120:19) at require (node:internal/modules/cjs/helpers:103:18) at Object.<anonymous> (/var/home/david/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:1:31) at Module._compile (node:internal/modules/cjs/loader:1241:14) at Module._extensions..js (node:internal/modules/cjs/loader:1296:10) at Module.load (node:internal/modules/cjs/loader:1096:32) at Module._load (node:internal/modules/cjs/loader:937:12) at f._load (node:electron/js2c/asar_bundle:2:13330) at e._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:83:25740)
```

Openshift local is not addressable inside the app due to this.

**Comment by pacificera** [comment]
Also should mention that I have the latest podman and that it is otherwise working:

podman version 4.5.0

**Comment by benoitf** [comment]
Hello @pacificera thanks for the report

how did you install Podman Desktop ? (from flathub or using the binary or ? )

**Comment by praveenkumar** [comment]
@pacificera Also can you check if  latest `crc` cli is installed on the system and try to run `crc setup --log-level debug`?

**Comment by gbraad** [comment]
Take note that this is run on `Fedora 38 Silverblue`. We should check again if CRC actually works on this platform. We used to have issues with KVM and the user enablement.

**Comment by gbraad** [comment]
Also: `Unable to find extension API` sounds like an issue with the plugin and Podman Desktop not being able to communicate or figure out the usage/correct location?

How was PD installed or run?
