### ISSUE TITLE
Add minikube provider for choosing CRI-O container runtime

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#2610]
### Is your feature request related to a problem? Please describe

The kind provider allows any container runtime, as long as it is containerd

`KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster`

### Describe the solution you'd like

With minikube provider, it is possible to use CRI-O (or docker, or containerd)

`minikube start --driver=podman --container-runtime=cri-o`

* Driver:
  - Docker
  - Podman
* Container Runtime:
  - Docker
  - containerd
  - CRI-O

https://kubernetes.io/blog/2016/07/minikube-easily-run-kubernetes-locally/

https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/

### Describe alternatives you've considered

It is possible to swap the CRI implementation after installation, but it has problems:

1) It has a lot of little pitfalls, even if it is documented how at k8s.io and cri-o.io

2) It bloats the container, since you get both the containerd and the cri-o images

3) The kind `load` command is hardcoded to `ctr`, so it only works with containerd

### Additional context

The upstream documentation is located at: https://minikube.sigs.k8s.io/docs/start/

There is also an older copy under https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by benoitf** [comment]
from what I understand, you want to be able to create a k8s cluster using minikube ?

**Comment by afbjorklund** [comment]
> from what I understand, you want to be able to create a k8s cluster using minikube ?

yes, it would be a separate extension. rather similar, but slightly different (other SIG)

Note: only for the "podman" and "docker" drivers, not for the VMs or on the host

The main reason would be for the runtime, and the other features (autopause, addons)

**Comment by benoitf** [comment]
we already support CRC and kind and suggested minikube in other issues so yes I don't see any problems of not letting people use that alternative

**Comment by afbjorklund** [comment]
I would be willing to contribute this, most of the code would be the same as the existing "kind" provider...

You can run both them individually, similar to how you can use both Podman and Docker at the same time.

![podman-desktop-resource-providers](https://github.com/containers/podman-desktop/assets/10364051/f6fb3db1-a30b-41e7-8fac-2b2b2808e8aa)

Here in this screenshot, kind is running with containerd in docker and minikube is running with cri-o in podman.

As usual, the cluster containers show up in the containers view and pods from both clusters in the pods view:

![podman-desktop-cluster-containers](https://github.com/containers/podman-desktop/assets/10364051/f8ff2f9a-b02c-462b-85fd-774209cb6ea7)

**Comment by benoitf** [comment]
Assigning to you

**Comment by afbjorklund** [comment]
> I would be willing to contribute this, most of the code would be the same as the existing "kind" provider...

The extensions/minikube is done, left to do is to copy/modify the docs: website/docs/kubernetes/minikube

**Comment by afbjorklund** [comment]
The website/docs/kubernetes/minikube is done too, most of the docs as the existing "kind" provider....

**Comment by afbjorklund** [comment]
Being moved to separate repo: https://github.com/containers/podman-desktop-extension-minikube

**Comment by afbjorklund** [comment]
This is the OCI image to use for install: `ghcr.io/containers/podman-desktop-extension-minikube`

**Comment by afbjorklund** [comment]
How does an extension get listed as available for download, under "Featured extensions" in the UI ?

![podman-desktop-1 1-welcome](https://github.com/containers/podman-desktop/assets/10364051/7d9c5c96-9c47-42a2-a286-f4b43377cca7)

![podman-desktop-1 1-extensions](https://github.com/containers/podman-desktop/assets/10364051/c0f46e75-5d31-492c-8934-2d68e457d324)

It would be nice if "minikube" extension was listed next to the "kind" extension, both are Kubernetes

**Comment by benoitf** [comment]
There is the room for 6 extensions, if we add one we exclude one in the featured list.

**Comment by afbjorklund** [comment]
See https://podman-desktop.io/docs/kubernetes/minikube
