### ISSUE TITLE
"Error: No provider with a running engine" when trying to play a kube yaml

### ISSUE THREAD

**Issue by fc7** [containers/podman-desktop#2611]
### Bug description

When trying to play a kube yaml file from the UI with version 1.0.1, the following error appears preventing the action

<img width="969" alt="Screenshot 2023-05-24 at 07 38 43" src="https://github.com/containers/podman-desktop/assets/85877/d5c2a1cd-73c7-4b3f-839b-a7d5cab75cfe">

This did not happen with v0.15.0

### Operating system

macOS Ventura 13.3.1

### Version

1.0.x

**Comment by jeffmaury** [comment]
Fixed by 0ab9ffd4fb24c0eab16d3ed5c75d96d3b29fc92d

**Comment by ziad-saade** [comment]
when the fix will be released?

**Comment by ziad-saade** [comment]
> Fixed by [0ab9ffd](https://github.com/containers/podman-desktop/commit/0ab9ffd4fb24c0eab16d3ed5c75d96d3b29fc92d)

when the fix will be released? 

the issue is blocking..

**Comment by tppalani** [comment]
I'm also getting same error, right now i'm using podman version 4.51, can you pls tell me when this https://github.com/containers/podman-desktop/commit/0ab9ffd4fb24c0eab16d3ed5c75d96d3b29fc92d has been released.
![image](https://github.com/containers/podman-desktop/assets/6921037/946d1e1f-462e-451b-9d6f-228e0d6ab629)

**Comment by benoitf** [comment]
it will land in 1.1.0 version of Podman Desktop

note: you can always use a 'development version' using the 'build after each commit' from https://github.com/containers/podman-desktop/releases
it already includes the fix

**Comment by tppalani** [comment]
Hi @benoitf https://github.com/containers/podman-desktop/releases these are pre-release desktop version can we use this ?

**Comment by benoitf** [comment]
@tppalani yes you can use them. You try. They should all work. It allows you to test a fix. You can always go back to a release

**Comment by tppalani** [comment]
Hi @benoitf  thanks for response, 

![image](https://github.com/containers/podman-desktop/assets/6921037/4b444972-a8b9-474c-b655-e33ecf6709d6)
