### ISSUE TITLE
show rootful and allow setting it on restart?

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#2612]
### Is your enhancement related to a problem? Please describe

with https://github.com/containers/podman-desktop/pull/2427 I can now create new machines with rootful - nice.

But in resources you can't see if it is on or off:

![2023-05-24_08-34-55](https://github.com/containers/podman-desktop/assets/54129/6fa0c8a3-1377-4ba9-871f-e95d1485e688)

and when clicking restart no option to turn on/off. For this I'm forced to go to the terminal.

### Describe the solution you'd like

show the rootfull or not mode in the overview.

on restart have option to tweak the parameters that are changeable between restarts (i.e. rootfull)

**Comment by benoitf** [comment]
It depends on https://github.com/containers/podman/issues/18479

**Comment by afbjorklund** [comment]
I had similar issues when connecting to the local socket, since the location was hardcoded.

```diff
--- a/extensions/podman/src/extension.ts
+++ b/extensions/podman/src/extension.ts
@@ -270,7 +270,7 @@ function getLinuxSocketPath(): string {
   const userInfo = os.userInfo();
   const uid = userInfo.uid;
 
-  return `/run/user/${uid}/podman/podman.sock`;
+  return '/run/podman/podman.sock';
 }
 
 // on linux, socket is started by the system service on a path like /run/user/1000/podman/podman.sock
```

It could use this rootful boolean as well, to pick the socket. Same goes for the docker socket.

```diff
--- a/extensions/docker/src/extension.ts
+++ b/extensions/docker/src/extension.ts
@@ -147,7 +147,11 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
   if (isWindows) {
     socketPath = '//./pipe/docker_engine';
   } else {
-    socketPath = '/var/run/docker.sock';
+    // grab user id of the user
+    const userInfo = os.userInfo();
+    const uid = userInfo.uid;
+
+    socketPath = `/run/user/${uid}/docker.sock`;
   }
 
   // monitor daemon

```

**Comment by maxandersen** [comment]
Still relevant afaics
