### ISSUE TITLE
Layout broken for a "Play pod or Container from a Kubernetes YAML" after sucessfull pod creation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2621]
### Bug description

I got broken layout, almost endless json response editor under "Done" button after "Play Kubernetes YAML".
![broken-playout-play-kube-yaml](https://github.com/containers/podman-desktop/assets/19164299/346ef580-163d-4728-9f57-e16d04fb0d7c)

### Operating system

Fedora 37

### Version

1.0.x

### Steps to reproduce

1. Pull httpd-24 (quay.io/centos7/httpd-24-centos7) image
2. Start container
3. Create a kube from httpd container
4. Play Kubernetes YAML with create yaml, choose podman runtime

My configuration is that I also have openshift local, kind and sandbox resources started. kube context is `crc-admin` right now. 

### Relevant log output

```shell
I am not sure if those console log are relevant:

97 index.ts:1327 Uncaught Error: Cannot read properties of undefined (reading 'log')
    at EventEmitter.<anonymous> (<anonymous>:2:7777)
    at EventEmitter.emit (VM159 sandbox_bundle:2:35718)
    at Object.onMessage (VM159 sandbox_bundle:2:47921)
(anonymous) @ index.ts:1327
emit @ VM159 sandbox_bundle:2
onMessage @ VM159 sandbox_bundle:2
```

**Comment by odockal** [comment]
The issue is also visible in the comment in the PR here: https://github.com/containers/podman-desktop/pull/2594

**Comment by cdrage** [comment]
Looks like play kubernetes YAML is broken in a few parts because this part is also broken too: https://github.com/containers/podman-desktop/issues/3033

I've marked this in-progress and I'll knock out both issues.
