### ISSUE TITLE
Updating an extension by using **Settings > Extensions > Install a new extension from OCI Image**

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2626]
### Bug description

Podman Desktop failed to update an extension by using **Settings > Extensions > Install a new extension from OCI Image**.

I would expect this to update the extension and not fail.

### Operating system

Linux

### Version

1.0.x

### Steps to reproduce

With the OpenShift Local extension example:

1. Install an extension old version:
	1. Go to **Settings > Extensions**
	2. **Install a new extension from OCI Image**: enter `quay.io/redhat-developer/openshift-local-extension:v1.0.1`.
	3. Click **Install a new extension from OCI Image**.
1. Install the new version:
	1. Go to **Settings > Extensions**
	2. **Install a new extension from OCI Image**: enter `quay.io/redhat-developer/openshift-local-extension:v1.0.3`.
	3. Click **Install a new extension from OCI Image**.
4. See the error message: `Extension openshift-local is already installed`.

### Additional context

![Screenshot from 2023-05-25 10:45:14 Podman Desktop 1920x1032 01](https://github.com/containers/podman-desktop/assets/243761/4b7a8ac3-4fe7-4322-9d77-d5db4a6d7a7d)

**Comment by benoitf** [comment]
It's to install a fresh new extension so message is accurate

To update, you'll have buttons to update the extension.
