### ISSUE TITLE
Not sure what "Leave blank to generate a name" means in the feedback form

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#2628]
https://github.com/containers/podman-desktop/blob/22a2e2c18d9f7a66776eeea6b5d087bb97391cc0/packages/renderer/src/lib/feedback/SendFeedback.svelte#L102
![image (14)](https://github.com/containers/podman-desktop/assets/1894/42c7c034-d0b1-490e-a5c8-9b84605a663e)

**Comment by benoitf** [comment]
thanks for the report. I think it's a bad copy/paste.
https://github.com/containers/podman-desktop/pull/2641 will remove that placeholder
