### ISSUE TITLE
Podman machine init and start failed silently on Mac OS with user without admin rights

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2635]
### Bug description

Issue reported by an user from the summit. Need to take a look if that is something we can reproduce and then figure out if it is on podman desktop or coming from upstream.

CC: @mairin 

### Operating system

mac OS ventura 13.2 (Intel)

### Version

1.0.x

### Steps to reproduce

0: User account without admin rights on Mac OS.
1. Install podman desktop (dmg or brew)
2. Start podman desktop
3. Open Developer's console -> (CTRL+SHIT+I on linux)
4. Install podman
5. Initialize and start podman.
Assert: machine is successfully started. 
Actual result: machine is not started nor there is an error appearing in the log/dialog. Maybe in console?

**Comment by lgrossma** [comment]
Tried on MacOS 13.4 with Podman Desktop 1.1.0 on a non-admin account and it works for me without any errors.

**Comment by benoitf** [comment]
closing as last comment was it was working
