### ISSUE TITLE
mac m1 - Error: spawn podman ENOENT on podman machine creation

### ISSUE THREAD

**Issue by DimamoN** [containers/podman-desktop#2638]
### Bug description

Issue during Podman Machine creation - `Error: spawn podman ENOENT`

### Operating system

macOs 13.3.1 (Apple silicon M1) 

### Version

1.0.x

### Steps to reproduce

1. Install Podman Desktop
2. Open Podman Desktop
3. Try to create a Podman Machine

### Relevant log output

```shell
`Error: spawn podman ENOENT`
```

### Additional context

<img width="1415" alt="image" src="https://github.com/containers/podman-desktop/assets/14595706/a429fda1-4388-4ee9-846f-c4af043a0386">

Maybe it can be related: I have a docker desktop installed, the issue is reproducible in both cases when Docker Desktop is enabled and disabled.

**Comment by benoitf** [comment]
hello @DimamoN and thanks for the report

could you please tell where your 'podman' binary is installed ?
do you have used the podman installer to setup it in `/opt/podman/bin/podman` or using brew or an alternative method ?

thanks

**Comment by benoitf** [comment]
@DimamoN Also did you install first Podman (on the Dashboard page) ?

**Comment by benoitf** [comment]
I think issue is related to https://github.com/containers/podman-desktop/issues/2553
closing as a duplicate

**Comment by DimamoN** [comment]
> @DimamoN Also did you install first Podman (on the Dashboard page) ?

no, there were no `podman` installed. 
I've installed podman from on the Dashboard page and `Error: spawn podman ENOENT` error has gone. 
thank you.
