### ISSUE TITLE
No tray icon on RHEL 8.7

### ISSUE THREAD

**Issue by Ferenc-** [containers/podman-desktop#2640]
### Bug description

Among the advertised [features](https://podman-desktop.io/features) there is "Management from the tray icon".
Which is unavailable on `Red Hat Enterprise Linux 8.7` because there is no tray icon appearing after starting `podman-desktop`.
I have tried the [latest flatpak](https://github.com/containers/podman-desktop/releases/download/v1.0.1/podman-desktop-1.0.1.flatpak) and the latest [tar.gz](https://github.com/containers/podman-desktop/releases/download/v1.0.1/podman-desktop-1.0.1.tar.gz) as well, none of them works.

### Operating system

Red Hat Enterprise Linux 8.7

### Version

1.0.x

### Steps to reproduce

1. Install either from flatpak or tar.gz
2. Start either with `flatpak run io.podman_desktop.PodmanDesktop` or `./podman-desktop`

### Relevant log output

```shell
Nothing relevant is logged.
```

**Comment by benoitf** [comment]
hello @Ferenc- thanks for the report

I suppose that you're using gnome and you don't have the tray icon support there.

for example these extensions can add tray icon support:

https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by afbjorklund** [comment]
The same thing happens on elementary OS, at least in version 6.

The application seems to work just fine without the tray, though...

But it _could_ be a nice feature with a dock menu and some badges:

https://blog.elementary.io/developer-tips-backgrounding-system-integration/

**Comment by Ferenc-** [comment]
> hello @Ferenc- thanks for the report
> 
> I suppose that you're using gnome and you don't have the tray icon support there.
> 
> for example these extensions can add tray icon support:
> 
> https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ https://extensions.gnome.org/extension/615/appindicator-support/

On RHEL 8.7, the Gnome version is `3.32.2`.
The `tray-icons-reloaded` needs a minimum of `3.36`.
The `appindicator-support` is interestingly considered unsupported by the extension manager,
but installable from the EPEL repo.
The `dnf install gnome-shell-extension-appindicator`, installs `gnome-shell-extension-appindicator-1:29-8.el8.noarch`, which unfortunately still doesn't help whatsoever. Neither does manually installing from the `appindicatorsupportrgcjonas.gmail.com.v29.shell-extension.zip`

**Comment by afbjorklund** [comment]
https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

**Comment by Ferenc-** [comment]
> https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

I have tried the suggested `topicons` too with `dnf install gnome-shell-extension-top-icons gnome-shell-extension-topicons-plus`, I haven't seen any change.

**Comment by afbjorklund** [comment]
Just saying that both desktops have removed tray icons, and encourage developers to use other communication methods:

* _Ensure that all application functionality can be accessed from the application's windows, and that no actions or options are only in the status icon menu._
* _Don't refer to the status icon in your user interface. This includes references to "minimize to tray" behavior._

(from https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines)

And that Podman Desktop is considering some additional status information, in the main window:

* https://github.com/containers/podman-desktop/issues/2589

**Comment by agibson2** [comment]
I found another gnome extensions that works properly with Remmina when displaying the tray-icon sub-groups.  'AppIndicator and KStatusNotifierItem Support' .

**Comment by benoitf** [comment]
you can almost do all the stuff of the tray icon in other places so if you don't have the tray icon it's not an issue
