### ISSUE TITLE
Design: Sort by column

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2645]
[I am opening this issue to track the design work; the implementation could be tracked via this other issue here: https://github.com/containers/podman-desktop/issues/659 ]

## The issue
We cannot sort the tables in the interface by column, which could be handy in finding items in the UI. Users have requested this and it would make the UI more friendly. We need a design for how it would work.

**Comment by deboer-tim** [comment]
Just (re)found this design placeholder, but I have already implemented this for Images and Volumes pages with sort indicators and default sort column. Maybe review the current status of these pages? Can either close this issue, use it to update the style guide, or open up issues if there are any concerns with the implementation.

**Comment by deboer-tim** [comment]
Closing. Column sorting has been in for months now, #4843 will be used to update Containers table and new issues can be opened if we want to change the behaviour.
