### ISSUE TITLE
On Windows, when the user name contains spaces, the command to copy the Kind binary is failing

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2653]
### Bug description

On Windows, when the user name contains spaces, the command to copy the Kind binary is failing because it is missing quotes to protect the spaces in the path name.

### Operating system

Windows 11 Pro

### Version

1.0.x

### Steps to reproduce

1. Work with a user name containing spaces, such as `Podman Desktop User`
2. Click on Kind
3. Download: OK.
4. Reply yes to system wide install.
5. The install command failed. `Unable to install kind binary: Error: Command failed: copy C:\Users\Podman Desktop User\.local\share\containers\podman-desktop\extensions-storage\kind\kind-windows-amd64.exe C:\Users\Podman Desktop User\AppData\Local\Microsoft\WindowsApps\kind.exe`
6. The link in the status bar to install Kind is gone.
7. I cannot create a Kind cluster.
I tried the copy command: it is missing some "  quotes to protect the spaces in the path. 

### Relevant log output

```shell
Command failing:


copy C:\Users\Podman Desktop User\.local\share\containers\podman-desktop\extensions-storage\kind\kind-windows-amd64.exe C:\Users\Podman Desktop User\AppData\Local\Microsoft\WindowsApps\kind.exe
```

Command successful:

```
copy "C:\Users\Podman Desktop User\.local\share\containers\podman-desktop\extensions-storage\kind\kind-windows-amd64.exe" "C:\Users\Podman Desktop User\AppData\Local\Microsoft\WindowsApps\kind.exe"
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
I guess a command is not using runCliCommand and https://github.com/containers/podman-desktop/blob/main/extensions/kind/src/util.ts#L106
