### ISSUE TITLE
Add Options to disable Minimizing to Systray and Running on Startup

### ISSUE THREAD

**Issue by DaveWK** [containers/podman-desktop#2657]
### Is your enhancement related to a problem? Please describe

It's a bit presumptuous of the podman desktop installer to assume I want podman-desktop to run when I log in on windows. Additionally, now that a lot of task bars in windows and linux hide some of the icons of running services, it has the potential to launch a fairly resource intensive set of processes if the user happens to have a lot of containers that are also i their environment

### Describe the solution you'd like

There should be a way to disable podman desktop from minimizing to the tray so it's easier to know if it's running and when it's stopped. A checkbox/switch in the preferences menu would work fine.

There should be a checkbox/switch in the preferences for whether to enable launching podman desktop on login.

The installer should prompt the user to ask if they want podman to start on login or not rather than assume.

### Describe alternatives you've considered

Remove all auto-start code and let users set up their own task to start podman desktop automatically. Setting up a windows scheduled task (or setting up a systemd service) to start a process on login isn't terribly hard and doesn't have the potential to cause a resource intensive process during startup of the system without the user's consent.

**Comment by benoitf** [comment]
Hello @DaveWK we have the preferences
preferences.login.start ( to not start Podman Desktop) on boot

And we have a property to not minimize it on start

One to not run a machine on start

And we have ExitOnClose to not minimize to tray but exit

So it looks like we already have the preferences in place that you're asking for

Just toggle the preferences and it'll do what you want

Closing the issue as your requests are already supported
