### ISSUE TITLE
Podman Desktop states missing podman or need to initialize without user guidance

### ISSUE THREAD

**Issue by worldofgeese** [containers/podman-desktop#2658]
### Is your enhancement related to a problem? Please describe

Podman Desktop lacks guidance when user state is not configured appropriately, such as when podman is installed but not initialized or when Podman is missing from a user's system. This extends to extensions like OpenShift Local, which I'll cover in another issue.

### Describe the solution you'd like

Podman should offer easy 1-click solutions to common issues a new user is likely to face such as a missing Podman binary, Podman not in expected path, or Podman uninitialized. The "curse of knowledge" applies here where developer assumptions don't match with new user expectations.

### Describe alternatives you've considered

1. If Podman is missing, offer a 1-click solution to download then initialize. This is also an opportunity to offer a file directory picker if the user has Podman but it is not in `PATH`.
3. If Podman is uninitialized, simply initialize Podman without user intervention required.
   - If Podman is uninitialized but missing required dependencies, expose this directly to the user in the UI e.g.
   - `Error: exec: "qemu-system-x86_64": executable file not found in $PATH`
4. Alternatively, simply ship or install all binaries with Desktop (kind, Podman) <- this is probably the *most* user-friendly option at the cost of total download size.

### Additional context

No solution provided when Podman is not installed:

![image](https://github.com/containers/podman-desktop/assets/59834693/e707fb89-c35c-4d65-a48a-16f665b8742a)

No solution provided when Podman is installed but not ready:

![Podman Desktop is installed but not ready](https://github.com/containers/podman-desktop/assets/59834693/ebd55547-2a25-4d77-8f05-4f9d4f119c46)

**Comment by jeffmaury** [comment]
Which platform are you on ? 

When Podman installed but not initialized, I have this:

![image](https://github.com/containers/podman-desktop/assets/695993/02514fcc-3bcb-41ec-8647-af6c36147628)

**Comment by worldofgeese** [comment]
@jeffmaury I'm on Intel's Clear Linux using the latest Podman Desktop Flatpak.

**Comment by cforce** [comment]
Same here . windows 11
![image](https://github.com/containers/podman-desktop/assets/393286/74fe3244-6c77-447d-b356-f20ecff23ae1)
![image](https://github.com/containers/podman-desktop/assets/393286/d7eb6af6-0ca3-4c08-8504-1dce50edfe13)
![image](https://github.com/containers/podman-desktop/assets/393286/6fdcde70-5366-4b3e-acef-60645d483cf2)
