### ISSUE TITLE
OpenShift Local extension should offer to download `crc`/`microshift` when missing and custom `PATH`

### ISSUE THREAD

**Issue by worldofgeese** [containers/podman-desktop#2659]
### Is your enhancement related to a problem? Please describe

Podman Desktop's default `PATH` is minimal and even conflicts with the suggested `PATH` for "Code Ready Containers" (what's Code Ready Containers? New users likely are unaware it was renamed) in Troubleshooting (`/usr/local/bin`). 

### Describe the solution you'd like

1. The OpenShift Local extension should offer a 1-click binary download of `crc` when missing.
2. It should also offer a custom `PATH` option just like the Podman extension does. 

### Additional context

CRC not found message:

![image](https://github.com/containers/podman-desktop/assets/59834693/020f8b65-cb40-4161-96cb-9636b952c648)

Troubleshooting section of the Podman Desktop docs which refers to "Code Ready Containers" not OpenShift Local. Additionally, it advises the user to make sure `crc` is in `/usr/local/bin` but this is not part of the `PATH` checked by Podman Desktop on Linux.

![image](https://github.com/containers/podman-desktop/assets/59834693/e642eb72-ebfe-4b6e-8c5a-f93eceb4d87a)

**Comment by benoitf** [comment]
Moved to https://github.com/crc-org/crc-extension/issues/146
This repository does not include source code of the Open shift local extension
