### ISSUE TITLE
Website missing (very dark blue on black) title

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#266]
### Bug description

I noticed this last week but then couldn't reproduce, doesn't seem to happen every single time (?). The main title is missing when using Safari in dark mode. If you select the area you can read it, and toggling dark mode off and back on via the toolbar fixes the problem.

<img width="1331" alt="Screen Shot 2022-07-05 at 9 16 12 AM" src="https://user-images.githubusercontent.com/19958075/177337659-fafe8f4a-68e4-4c05-a692-8dc2af7b934c.png">

### Operating system

macOS 12.4 M1

### Version

next (development version)

**Comment by deekay2310** [comment]
Thanks for pointing this out @deboer-tim! It works just fine for me and I am unable to reproduce the error. I will have a look at it whenever that happens.

**Comment by deboer-tim** [comment]
Used the Safari web inspector to check the difference. On the first load of the element
`<h1 class="title-font sm:text-4xl text-3xl lg:text-6xl mb-4 font-medium text-gray-900 dark:text-white">Containers and Kubernetes for application developers</h1>`
the text color is coming from `.text-gray-900` and the color is `rgb(17, 24, 39)`.

When reloading or opening another tab, the color comes from `.dark:text-white` and is `rgb(255,255,255)`.

Looks like some kind of race condition with applying the dark theme on load in Safari.

**Comment by deekay2310** [comment]
This is exactly what I wanted to check. Thanks for checking this @deboer-tim. I also observed the same error in Google Chrome and it does seem like the wrong class is being applied. I don't think it is because of a particular browser but the mechanism responsible for applying dark theme classes.
