### ISSUE TITLE
Can't use locally built latest images on Kubernetes clusters

### ISSUE THREAD

**Issue by leepa** [containers/podman-desktop#2661]
### Bug description

I can't seem to pull a local image into the local kubernetes. The image appears as 

<img width="963" alt="Screenshot 2023-05-29 at 08 18 57" src="https://github.com/containers/podman-desktop/assets/9469/4d4dd1e8-f49f-4736-94f4-e0996653547e">

Yet when I 'upload KIND cluster' and then try and use the image name I get...

```ImagePullBackOff```

### Operating system

macOS Ventura 13.4

### Version

1.0.x

**Comment by leepa** [comment]
The solution appears to be to set an ImagePullPolicy of never and then all is right with the world - might need more detail for helping people finding their way with k8s local development.

**Comment by afbjorklund** [comment]
Using a tag also works.

https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
