### ISSUE TITLE
Scaling the display of desktop extensions in nav

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2677]
### Is your enhancement related to a problem? Please describe

If you have more than a few desktop extensions, it can make the main nav scroll, putting the settings icon "below the fold" which kind of sucks. 

The desktop icons also tend to be more colorful, drawing more attention than the main application navigation icons, which breaks the visual hierarchy of the UI (the main nav items are more frequently used and more primary than the extension icons.) 

![Screenshot from 2023-05-29 20-27-36](https://github.com/containers/podman-desktop/assets/799683/bb5b812d-7a4c-45ef-b16e-0ab0f2b451ff)

### Describe the solution you'd like

We could limit the max vertical height of the desktop extension and allow for that block to have its own scrolling or spillover menu. The visual design of this block could maybe help readjust the visual hierarchy to be more accurate. 

So here's a little demo of an idea I mocked up for this. Basically: you have 13 icons, and the height allotted for the extensions icons block allows for max 5 icons, so they get paged across 3 "pages" within the block. 

The top of the block has an icon I intend to bring users to settings > desktop extensions so the users can get more detailed information about the extensions in the block and have the opportunity to install additional ones or remove any of the ones they have that way right from the block.

OK, so then after this top special icon, you have 4 extension icons, and a double down chevron. Click the double down chevron, you get to page 2 which has a double up chevron to go back to "page 1" and a double down chevron to go to page 3.... once on page three, there is just the double up chevrons to go back to page 2. 

I am guessing it would really be rare to have more than one page anyway, in which case you just wouldn't have any double directional chevrons, but for someone who is really a fan of installing lots and lots of extensions... I wouldn't consider it a common case to have more than 3 pages. (Surely some user will prove me wrong though 😂 ) 

Anyway:

[Screencast from 2023-05-29 20-25-02.webm](https://github.com/containers/podman-desktop/assets/799683/ba5ca243-c70e-428b-92ff-56e484781842)

(Penpot file: https://design.penpot.app/#/workspace/88d87192-d205-8007-8002-9588f748f1b7/88d87192-d205-8007-8002-958902199140?page-id=88d87192-d205-8007-8002-95890219d016&layout=layers )

**Comment by deboer-tim** [comment]
Sorry, starting changing this issue before I noticed #2353, will continue there.
