### ISSUE TITLE
Age column is ambiguous across screens

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2678]
### Is your enhancement related to a problem? Please describe

In the container and pod tabs, the age column shows the uptime, or the elapsed time since the contact last started running.
In the image tab, the age column shows the age of the image, or the elapsed time since the image was built.
(I'm not sure about the volumes tab but I believe it's based on time elapsed since the volume was created.) 

### Describe the solution you'd like

I think there's maybe 3 age-related pieces of data we might want to think about for these objects:

- **uptime** // time elapsed since the container/pod was most recently started
- **age** // time elapsed since the container/pod/image was initially created/built
- **last updated** // time elapsed since the object was most recently modified

I think the long-term fix would be to address all of this metadata and make these columns (optional in some cases certainly).

I think the short-term fix would be to re-label the age column on the containers and pods screens as "uptime."

**Comment by deboer-tim** [comment]
Just a clarification: the pod age already is age (time since creation), but because it is cleared when stopped in some cases it looks like uptime (see issue #2341).
