### ISSUE TITLE
Extensions automatically reenable

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#268]
### Bug description

If I disable an extension, it is automatically re-enabled the next time I start. These preferences should be saved across restarts.

### Operating system

macOS 12.4

### Version

next (development version)

**Comment by slemeur** [comment]
Cannot reproduce it.

**Comment by benoitf** [comment]
I'm not sure this can be closed

**Comment by deboer-tim** [comment]
Confirmed, I can still reproduce on 0.8.0.

**Comment by EricLarge** [comment]
Still an issue on 0.9.1 MacOS.  I disable the kubernetes-context extension because I really don't want to accidentally deploy some local test pod to my company's production kubernetes cluster.

**Comment by benoitf** [comment]
Telemetry events should report extensions that are enabled/disabled when implementing the feature

**Comment by Malix-Labs** [comment]
Has this issue been dropped as stale?
