### ISSUE TITLE
PR #2563 broke the README image

### ISSUE THREAD

**Issue by wolf99** [containers/podman-desktop#2684]
### Bug description

#2563 converted the website static PNG images to WEBP for better compression.
The website seems fine, but this repo's README is broken as it still points to the PNG.
GitHub does not (yet) support rendering WEBP.

If the maintainers are happy to wait for a solution I could find time to look into a PR for this myself at some point.
But dont hold your breath!

### Operating system

N/A

### Version

1.0.x

### Steps to reproduce

View https://github.com/containers/podman-desktop/blob/main/README.md

**Comment by benoitf** [comment]
thanks @wolf99 for the report
I've created https://github.com/containers/podman-desktop/pull/2685 to fix the problem.
