### ISSUE TITLE
Podman Desktop completely consumes internet connection without any reason

### ISSUE THREAD

**Issue by k1s** [containers/podman-desktop#2690]
### Bug description

After updating to the recent Mac Os Podman Desktop started to behave very strangely, after starting up it downloads gigabytes of data consuming all available internet connection. This behaviour is not reproducible with console version of podman and seems a little bit malicious, podman was installed via brew, please see screenshot attached

<img width="1068" alt="Screenshot 2023-05-30 at 15 53 28" src="https://github.com/containers/podman-desktop/assets/11160683/da9f03b0-2604-41f5-817b-f6081d8bfd3a">

### Operating system

macOs Ventura 13.4

### Version

1.0.x

**Comment by benoitf** [comment]
hello @k1scould you display the extensions that you have ?
Also did you try to do install from within Podman Desktop ?
like creating podman machine, etc ?

Podman Desktop is only downloading extensions/ installing them

do you have a proxy ? you could add a proxy to check what is being downloaded in your case ?

**Comment by kgalli** [comment]
I experience that exact same thing. Once Podman Desktop is started the network usage is insane. Just ofter a couple of seconds is has already downloaded hundreds of MB.

Maybe it ends up in a loop and downloads extensions again and again?

Extensions:
![Screenshot 2023-08-16 at 14 27 55](https://github.com/containers/podman-desktop/assets/144402/36b798c2-e392-491a-b743-17d693c1be98)

Network traffic after couple of seconds:
![Screenshot 2023-08-16 at 14 29 23](https://github.com/containers/podman-desktop/assets/144402/1b3a713c-5c3d-452b-a0fb-8c48184978ae)

**Comment by benoitf** [comment]
@kgalli could you open the dev tools console and check the network tab

Select <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>i</kbd> on Windows/Linux or <kbd>Command</kbd>-<kbd>Option</kbd>-<kbd>i</kbd> on macOS.

**Comment by kgalli** [comment]
How can I mimic the open of the app. I open the dev tools console but there is nothing going on in the network tab. If I just reload using C-R the site / app reloads pretty quickly but only some index doc the js and css plus some image are loaded. Nothing indicates to an actual download. But if I look at the network monitor (Activity Monitor of Mac OS) I can see that Podman Desktop is recieving a lot of data.

**Comment by benoitf** [comment]
@kgalli hit the refresh Command+R Control+R or view Menu of devtools and then reload

**Comment by kgalli** [comment]
That is what I did. There is nothing going on which indicates network usage more then loading the files needed to render the view/app. Is there a way to see what the app is doing on start. I can see the network traffic in the Activity Monitor so Podman Desktop is responsible for the traffic. But it is not visible in the dev tools. At least not when the app is already opened and I open the dev tools and just use CMD-R to reload.

**Comment by benoitf** [comment]
@kgalli I will see how I can trace all network calls and I will keep you informed.

**Comment by kgalli** [comment]
@benoitf many thanks for looking into this. Much appreciated!

**Comment by benoitf** [comment]
@kgalli could you try https://github.com/containers/podman-desktop/pull/3588

you can find prebuilds artifact there: https://github.com/containers/podman-desktop/actions/runs/5892768893?pr=3588
(you need to be logged in into GitHub)

Then run the binary.

They're not signed on PR so you might need to do for example on macOS `xattr -r -d com.apple.quarantine /Path/to-the/app`

Then you can follow instructions of the PR
> Click on the light bulb in status bar

> search for main ↪️ Net-logs written to ..../.local/share/containers/podman-desktop/extensions-storage/net-logs/net-logs.json in the Logs section

> Then you can open this file with tooling or with https://netlog-viewer.appspot.com/ application


let me know if it displays something or still nothing

**Comment by kgalli** [comment]
@benoitf unfortunately I do not have the time to do that right away but will do tomorrow and give feedback. Thanks for the effort so far.

**Comment by kgalli** [comment]
@benoitf I could not figure out much. I ended up uninstalling `podman` and `podman-desktop` and now all seems working perfectly fine. I also realised the issue was with version `1.0.1`. 

I even tried with the old version but it is now all working. The challenge now is I have no way to reproduce the issue anymore.

**Comment by benoitf** [comment]
ok thanks @kgalli 
I'll close the issue if it does not reproduce with the latest versions

Feel free to reopen in case issue appears again
