### ISSUE TITLE
Mac error: qemu exited unexpectedly with exit code 1

### ISSUE THREAD

**Issue by djnotes** [containers/podman-desktop#2696]
### Bug description

Podman Desktop does not always start successfully on mac (Intel), when it's set to launch at log-in. Sometimes, it fails, sometimes it succeeds. 

### Operating system

12.6.3

### Version

next (development version)

### Steps to reproduce

Launch Podman Desktop on mac, or set it to launch at start-up.
Many times, I face the error:  
>Error: Error: cannot start VM podman-machine-default: VM already running or starting
It seems to be stuck at starting the VM.
And sometimes, it gives me error:
>Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable
No matter I try to start VM from the app or from the terminal. 
In the terminal:
- Run podman machine stop
- Run podman machine start
- Wait and bit for VM to start, it doesn't and the error is shown.
Repeating the process (stop and start) does not help.

### Relevant log output

```shell
# podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable
```

### Additional context

I think Podman Desktop is not very reliable on Mac. 
I might get a better result by running the stable version of PD, though. So, I'll give it a try and update the thread here.

**Comment by benoitf** [comment]
hi and thanks for the report

The related issue is https://github.com/containers/podman/issues/16054 

you may try to manually kill the qemu process

closing as it's a podman upstream issue but I've added label 'podman-desktop' on the podman issue
