### ISSUE TITLE
Podman CLI was not found inthe PATH : Windows 10

### ISSUE THREAD

**Issue by ksingh7** [containers/podman-desktop#270]
### Bug description

trying to install podman-desktop on windows. Initially it prompted that "podman is missing and you should installed it". 

Once i installed podman , i am getting this error "unable to locate podman cli". If you review the screen shot, you can see that podman is installed and the cli is present in the right folder.

![image](https://user-images.githubusercontent.com/9701902/177377062-e79259fb-5b1d-4637-95b5-072ab80c3fdb.png)

![image](https://user-images.githubusercontent.com/9701902/177377424-f339c894-8392-4f39-ac89-40f1194ae5a9.png)

### Operating system

Windows 10

### Version

next (development version)

### Steps to reproduce

- Get a windows 10 machine
- Download podman desktop v0.0.5

**Comment by ksingh7** [comment]
On first place, the podman-desktop UI should detect podman cli as soon as user installs podman.

As a workaround, i had to go to podman-deskop > preferences > resources > podman > podan machine > create

**Comment by benoitf** [comment]
you may try to restart Podman Desktop after the install
