### ISSUE TITLE
Creating a podman machine is not straightforward for some workflows

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2706]
### Is your enhancement related to a problem? Please describe

As a new user, I see the welcome page.
Then I can click on 'Go to resources' page

And from the preferences, I see resources page where we can create resources.

But from there, I should be able to install podman if it's not yet installed.

### Describe the solution you'd like

Option 1 could be to have the 'create new..' button being enabled but if Podman is not installed, Podman extension should ask the user if he wants to install and then proceed the creation of the podman machine at the end.

Also a text needs be displayed on the right if there are no container/kubernetes factory (like we did for OpenShift Local and DevSandbox extension)

### Describe alternatives you've considered

Less voted option is to have a 'install...' button instead of 'create new...' button but it will require from user more clicks to achieve a 'ready to use runtime for containers'

**Comment by mairin** [comment]
I mocked up how this might work with the "create new..." button:
![Podman Not Installed (1)](https://github.com/containers/podman-desktop/assets/799683/74e84b44-29e5-4790-802a-4ad9034e4c5f)

In doing so, I reviewed the mockups we already have, and remembered this little dropdown guy, which is in the mockups but I don't think we've implemented:

![Screenshot from 2023-05-31 12-29-33](https://github.com/containers/podman-desktop/assets/799683/679976da-88c4-4411-a40f-f73689123709)
![Screenshot from 2023-05-31 12-29-19](https://github.com/containers/podman-desktop/assets/799683/6a08b9cc-0b53-45d8-9adc-ee3a008654b1)

Which reminded me - I think that was how I had thought about how we achieve "install" vs "create new".... if you don't have the provider installed, you use this "Create New Provider" dropdown to launch the onboarding flow for installing that provider (eg, if I selected Podman from that drop down then the next screen could be (where you click on i already have podman:)
![Podman Not Installed (2)](https://github.com/containers/podman-desktop/assets/799683/02daded1-c06c-480c-a0e9-435730cd08ff)

We talked today about implementing  the onboarding designs as the long-term solution though so I think this is ok.

**Comment by lstocchi** [comment]
I am a bit confused. So when users click on `Create new` and there is no podman installed we show the page/design below and then (after clicking on next and have podman installed) we redirect them to the actual `create new page`?
![image](https://github.com/containers/podman-desktop/assets/49404737/e6e4693f-8340-4621-b097-c379634b2eb9)

**Comment by benoitf** [comment]
I'm also confused by the 'Location of Podman' UI. If you don't have podman installed you won't find Podman binary in any case.
I would expect a dialog box 'Podman is not installed do you want to install it first and it launches the installer. At the end of the install, it continues with the creation of the podman machine

**Comment by mairin** [comment]
@lstocchi No lol, let me fix it that... I think the screen I picked to show as an example here is too confusing. Will update.

@benoitf I think I mocked that up that way bc when I did all the onboarding designs, I looked thru the config available for the extension and tried to account for each option, and I think path to binary was one of them? It can totally be dropped tho. Do you think custom VM image would be useful to keep?

**Comment by benoitf** [comment]
binary path is a great option but mainly on Linux. On macOS or Windows using the installers, podman is always installed at known location. (that said we saw people wanted to customize the path by adding some env variables before, etc on Windows/macOS)

VM Image is more an advanced feature (but we use it for example for airgap mode)
