### ISSUE TITLE
Include ARIA based elements (roles, attributes) into Navigation bar to improve accessibility of the application

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2708]
### Is your enhancement related to a problem? Please describe

Improve accessibility of the DOM structure, especially navigation bar. It could also help when testing the components.

### Describe the solution you'd like

Insert ARIA based roles and attributes into navigation bar items.

**Comment by deboer-tim** [comment]
Maybe we can tie this/do it at the same time as replacing PF classes? We should do both, and worried that independent changes on either could affect the other.

**Comment by odockal** [comment]
I will gladly tie this to any of more conceptual work. But right now I would like to continue with this as it kinda blocks me on e2e test side.

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/pull/2742
