### ISSUE TITLE
Running from Flatpak: "/var/run/docker.sock is not enabled. Need to use wrapper script"

### ISSUE THREAD

**Issue by devurandom** [containers/podman-desktop#2709]
### Is your enhancement related to a problem? Please describe

When I open Podman Desktop (Flatpak), I see an exclamation mark and the word "Compose" in the lower left corner:
![image](https://github.com/containers/podman-desktop/assets/63082/e4aacb56-e020-491a-b926-f8f726730caf)

When I hover over it, it shows a tooltip: "/var/run/docker.sock is not enabled. Need to use wrapper script"

When I click it, a dialogue opens with the text:

> Please add the compose wrapper bin folder to your PATH environment variable. Value is /home/[REDACTED]/.local/share/containers/podman-desktop/extensions-storage/compose/bin. The script /home/[REDACTED]/.local/share/containers/podman-desktop/extensions-storage/compose/bin/compose will setup for you the DOCKER_HOST environment variable.

Now since Podman Desktop is installed as a Flatpak, I have no reasonable way to set the `PATH` (I could override it using `flatpak override --user io.podman_desktop.PodmanDesktop --env=PATH=$HOME/.local/share/containers/podman-desktop/extensions-storage/compose/bin`, but that makes Podman Desktop fail to start).

Podman Desktop also seems unable to show any services brought up by Docker Compose. It shows the containers, but not the "bundle" (my words) of services. This does not change when starting the services with `podman-compose up` instead of `docker-compose up`. Also "switching" `docker-compose` for `podman-compose` by means of `ln -s /usr/bin/podman-compose ~/bin/docker-compose` (`$HOME/bin` is on the `PATH`) does not make a difference: Podman Desktop does not "see" the services, only the containers.

### Describe the solution you'd like

Podman Desktop should probably set the `PATH` by itself however it needs it. Especially since it appears to know what directories should appear in the `PATH`.

### Additional context

```
❯ flatpak info io.podman_desktop.PodmanDesktop

Podman Desktop - Manage Podman and other container engines from a single UI and
tray.

          ID: io.podman_desktop.PodmanDesktop
         Ref: app/io.podman_desktop.PodmanDesktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.1
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 317.4 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: f1593d5326ef731271913a269b8b731d25520ff4374427682def6b99b1227b6f
      Parent: 674017a96e9795bd388d2a9e28373d393599e1e500ad68ed4c6cf46289086362
     Subject: feat: bump to v1.0.1 (a0671171)
        Date: 2023-05-22 10:29:22 +0000


❯ flatpak info -m io.podman_desktop.PodmanDesktop
[Application]
name=io.podman_desktop.PodmanDesktop
runtime=org.freedesktop.Platform/x86_64/22.08
sdk=org.freedesktop.Sdk/x86_64/22.08
base=app/org.electronjs.Electron2.BaseApp/x86_64/22.08
command=run.sh

[Context]
shared=network;ipc;
sockets=x11;
devices=dri;
filesystems=home;xdg-run/podman:create;/run/docker.sock;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.freedesktop.Notifications=talk
org.freedesktop.Flatpak=talk

[Extension io.podman_desktop.PodmanDesktop.Debug]
directory=lib/debug
autodelete=true
no-autodownload=true

[Build]
built-extensions=io.podman_desktop.PodmanDesktop.Debug;io.podman_desktop.PodmanDesktop.Sources;


❯ dnf info docker-compose podman-compose
Last metadata expiration check: 0:00:11 ago on Wed May 31 17:31:55 2023.
Installed Packages
Name         : docker-compose
Version      : 1.29.2
Release      : 7.fc38
Architecture : noarch
Size         : 1.1 M
Source       : docker-compose-1.29.2-7.fc38.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Multi-container orchestration for Docker
URL          : https://github.com/docker/compose
License      : ASL 2.0
Description  : Compose is a tool for defining and running multi-container Docker
             : applications. With Compose, you use a Compose file to configure your
             : application's services. Then, using a single command, you create and
             : start all the services from your configuration.
             :
             : Compose is great for development, testing, and staging environments,
             : as well as CI workflows.
             :
             : Using Compose is basically a three-step process.
             :
             : 1. Define your app's environment with a Dockerfile so it can be
             :    reproduced anywhere.
             : 2. Define the services that make up your app in docker-compose.yml so
             :    they can be run together in an isolated environment:
             : 3. Lastly, run docker-compose up and Compose will start and run your
             :    entire app.

Name         : podman-compose
Version      : 1.0.6
Release      : 1.fc38
Architecture : noarch
Size         : 300 k
Source       : podman-compose-1.0.6-1.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : Run docker-compose.yml using podman
URL          : https://github.com/containers/podman-compose
License      : GPL-2.0-only
Description  : An implementation of docker-compose with podman backend.
             : The main objective of this project is to be able to run docker-compose.yml
             : unmodified and rootless.
```

**Comment by benoitf** [comment]
hello @devurandom https://github.com/containers/podman-desktop/issues/1974 should help you (basically compose will be installed in your user path)

**Comment by devurandom** [comment]
> hello @devurandom #1974 should help you (basically compose will be installed in your user path)

Thanks!

`docker-compose` is already installed and it is on my path. The same with regards to `podman-compose`.

I also put `$HOME/.local/share/containers/podman-desktop/extensions-storage/compose/bin` on my `$PATH`, but Podman Desktop cannot know that, since it is running inside a (Flatpak) container with its own filesystem and env vars. If the `compose` script is supposed to be used by another application (not Podman Desktop): Which one? And why?

Outside of Podman Desktop starting services with `docker-compose up` seems to work and the services also detected and correctly "bundled together" by e.g. JetBrains IntelliJ IDEA.

**Comment by devurandom** [comment]
@cdrage https://github.com/containers/podman-desktop/commit/cdecbfb90fb8628da13f6ba6f2be5009b9213e36 accidentally closed this issue. GitHub does not understand negations such as "does not close #issue-number".
