### ISSUE TITLE
Design: Onboarding Wizard Menu Spec

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2711]
# Onboarding Menu 

This is the specification for the onboarding menu screen which appears on the first run of Podman Desktop welcome wizard. It allows you to select which container engine / kubernetes extensions you would like to configure when first starting the app.

Last updated: 31 May 2023
Penpot file: https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/d5fc0283-ef1c-80fa-8002-3243c19ca388?page-id=d6ee6431-8fa5-80b1-8002-3f4486f91c86  (Onboarding Design File > Onboarding Opener)

## Changelog:

- Draft / 31 May 2023
  - Initial transfer of design content from Penpot to GitHub in specification form.
  
## TODO / Questions
  
Any todos for updating the design will be noted here based on the comments / discussion.

- Do we call it an extension repository or an extension catalog? I kind of like "catalog" better. ~m

# Extension Metadata

This is the extension metadata I think will be needed to realize this mockup; I know some exists already, I am not sure what the gap might be.

- **Extension title:** E.g., "OpenShift Local"
- **Extension detail:** E.g., "Experimental support"
- **Extension icon:** (Roughly 48x48, full color. If needed, grayscale version as well if grayscale can't be done as a CSS filter (but I think it can.) 
- **Extension badges:** "Remote" "Featured" "Detected" (but detected is more of a state of the user's system than the extension itself so this one would not be part of the extension's static metadata)
- **Extension description:** What pops up in the info box when you click on the name of the extension. E.g., "Linux virtual machines, typically on macOS, for running containerd." (for Lima)
- **Dependencies:** I am not sure how /what format we want to store this, but some kind of area to state what dependencies need to be in place for the extension to be able to be installed/set up (think the RHT auth extension for DevSandbox) so the ordering of the setup can be optimized.

# Obtaining Extension Metadata

To be able to display data about extensions to offer them to users, we need to actually be able to retrieve data about those extensions.

## Stages to configuring an extension via onboarding

There's a few stages to configuring an extension through the onboarding process:

- The user understanding that the extension exists (if it wasn't bundled with their Podman Desktop install)
- Downloading + installing the extension
- Activating / turning on the extension
- Configuring the extension

We get into a chicken-and-egg issue with the first two steps, if the user doesn't have an extension present, they can't set it up, but if they don't have it present, they won't know about it and that it exists.

## Remote extension catalog

It would be quite nice if we could set up a remote service somehow/somewhere, from which metadata could be obtained about the extensions that are available, so that the extension need not be installed / bundled with Podman Desktop in order for the user to be aware of it. (And extensions could be browsed without requiring that Podman Desktop be installed yet.)

### Flatpak / Flathub example

If I think about other services that work this way, I think about how the Flatpak catalog (Flathub) works... Flathub uses the AppStream & AppData specs for storing individual application metadata including application name, description, icons, etc.:

- https://docs.flatpak.org/en/latest/freedesktop-quick-reference.html
- https://github.com/flathub/flathub/wiki/AppData-Guidelines
- https://www.freedesktop.org/software/appstream/docs/

They also have a recommended system for setting up your own repository (similar to flathub):

- https://docs.flatpak.org/en/latest/publishing.html

I think this could be a good route to distributing and getting metadata about Podman Desktop extensions. [Note: I'm not going to dictate this is what we should do, just that it is a well thought-out set of tooling that solves the same problem we have and worth looking it.]

## UX requirements

From a user experience perspective, in short, we need:

A method of listing a catalog of available Podman Desktop extensions that doesn't require the extension to be installed or bundled with Podman Desktop for it to be displayed to the user.

Additional considerations:

- **Preferred/Highlighted extensions:** Allowing as part of the repository functionality, the ability to highlight specific extensions as preferred, or supported, which will allow them to display differently in the UI. We can provide a lot of value in the user's experience by sharing our expertise via an opinionated display of tooling.
- **Restrictive Network Environments:** In a corporate environment, the Podman Desktop user may be behind a firewall and unable to download extensions directly from a public repository. Some possibilities for making them available otherwise:
- **Downloadable bundles:** Allowing user to make selections on a website for the repository / catalog, download them as a bundle (similar to how Google Fonts lets you make a font selection and produces a zip bundle for you), and install them in an airgapped fashion.
- **Internal self-hosted extension catalogs:** Allowing enterprises to easily run their own internal catalog (maybe this is too much. But I think about RH Satellite / Proxy serving a similar function for RPMs / errata updates for the OS.)
  
## Onboarding Menu Full Screen

![Screenshot from 2023-05-31 21-04-04](https://github.com/containers/podman-desktop/assets/799683/ceb6711b-72c5-4941-b36e-da9181e56a32)

Let's walk through the elements of this mockup:

### Screen Header

![Screenshot from 2023-05-31 15-12-24](https://github.com/containers/podman-desktop/assets/799683/c7bef454-025a-42cb-8402-c6a10217666d)

We have a few elements in the screen header:

- **Wizard Title:** "Get started with Podman Desktop" - this just sets the stage and lets the user know what the screen/window is all about.
- **Skip All Link:** "Skip this entire setup" - clicking on this immediately exits the onboarding wizard and takes the user to the Dashboard. (Note: I would really like the >> chevrons to animate gently just once or twice for awareness on this screen.)
- **Podman Desktop Logo:** SSIA
- **Screen Title:** "tada Welcome! Let's finish setting up Podman Desktop." - names the current step of the wizard the user is on.
- ** Screen Details:** "You can always skip set up now and pick it up later under Settings > Resources. " - Additional information that applies to the entire screen.

### Menu

![Screenshot from 2023-05-31 15-16-40](https://github.com/containers/podman-desktop/assets/799683/b42d815d-42b6-4096-a540-f50f2dbdcf95)

This is the real meat of the screen :) There's a lot here so let's go through step-by-step:

#### Unselected menu item

![Screenshot from 2023-05-31 15-18-25](https://github.com/containers/podman-desktop/assets/799683/df32b6bd-ae97-4026-84b7-07fcbb54d50b)

This is an extension that the user hasn't selected it to set it up (yet). Note that it's displayed in grayscale. (If/when the user selects it by checking off the checkbox, the icon should display in full color.)

#### Selected / menu item

![Screenshot from 2023-05-31 21-09-07](https://github.com/containers/podman-desktop/assets/799683/8b11f1da-f11e-4f96-8da0-90240635d9c8)

This item was selected by checking on the checkbox in the upper right. The card gets a purple-500 ring, and the icon goes to color (from grayscale.) Any screens associated with the extension will be added to the queue of screens the user will see when they hit next.

#### Menu items that have been detected

![Screenshot from 2023-05-31 21-14-17](https://github.com/containers/podman-desktop/assets/799683/0c826b56-2750-4745-963e-7d0d7834fcbc)

If we detect the associated tool running on the system (this may not be realistic, but let's say we detected Kind on the system above), then a "Detected" badge will be displayed on the menu item below the title/detail. Just because we detected Kind, doesn't mean the Kind Podman Desktop extension is installed on the system, and it doesn't mean the user will select it for configuration. (doesn´t necessarily have to mean the Kind Podman Desktop extension is installed on the system, and it doesn't necessarily have to mean the user will select it for configuration. That being said, we should probably auto-select extensions for container engines/tooling we auto-detect on the system.

#### Menu items for remote K8s platforms

![Screenshot from 2023-05-31 21-31-35](https://github.com/containers/podman-desktop/assets/799683/6a72e9ba-734f-4f7b-88e0-1d9f5aba399f)

A "remote" badge will display on remote K8s platforms, which Developer Sandbox is.

#### Menu item elements

The elements here, then:

- Extension icon
- Extension name The dotted underline under the name of the extension is a hint that you can click the name of the extension to get a description of it. (see below)
- Extension detail (optional) (e.g. for OpenShift Local: "OCP or Microshift"))
- Checkbox - if checked, we'll add the setup screens to the wizard queue, if not, we'll skip it.
- Badge - (e.g. "Featured" and "Detected" and "Remote")

#### Extension description bubble

![Screenshot from 2023-05-31 21-12-23](https://github.com/containers/podman-desktop/assets/799683/abbea002-f7ed-4657-ad9e-7f311dca90f4)

(This shows what the description bubble looks like when triggered by clicking on the extension name. It's extra space to describe what the extension does, in case the user isn't familiar with, for instance, what Developer Sandbox is.)

#### When extension install happens

"Okay," you might be thinking, "so if these extensions aren't necessarily installed, where is the install button for them? When do they get installed?"

Good question. :) If the user selects an extension that is not installed for configuration, they're implicitly indicating they would like to have it installed, so I think we should just silently install it when they press on this menu screen.

I would not suggest installing the extension when they click the checkbox to select the extension, because they still might change their mind and unselect that. Clicking the "Next" button on the window has more of a commitment to it, so I would suggest at that point we start installing any needed extensions in the background.

This might mean we need to insert a "Downloading extensions..... installing extensions...." type of progress bar screen after this.

### Telemetry Block

![Screenshot from 2023-05-31 21-33-05](https://github.com/containers/podman-desktop/assets/799683/8435ea01-66c3-4ebc-a175-36f40f95ac5a)

This is already present in the welcome screen :) So no new work there.

### Wizard navigation block

![Screenshot from 2023-05-31 21-36-51](https://github.com/containers/podman-desktop/assets/799683/58566c6d-c42f-4dcf-8b56-7d536933f3a0)

So three elements here:

#### Next button

Clicking on the next buttons allows the user to proceed to the next screen. 

**If the user hasn't selected anything**, we bring them to the dashboard. 

**If they have selected menu items**, we will display the associated onboarding screens for the selected menu items in an order. 

##### Selected menu item ordering

There may be dependencies between extensions. For example: if we detect Docker, and the user selects both the Docker plugin and the Podman plugin - I think enabling Docker emulation on Podman is going to probably result in a bad experience for the user trying to work with their Docker containers? The optimal ordering to avoid dependency loops should override any other notions of ordering.

Given there are no dependencies: the extension setup screen order should mirror the order on the page (reading the page as rows, so left-to-right first row, left-to-right second row.) So if Docker appears first, and Podman appears second, and the user selects both, the Docker screens will appear first, then the Podman screens. (This way, the user has some hint at what order things will appear when they hit next.)

#### Cancel button

When the user is on this menu screen, if they hit cancel, it will close the entire wizard. (This might not be the behavior on other screens though, e.g. if you're 3 screens in.)

#### Instruction / messaging area

In the center of the wizard navigation block is an area for a short message that lets the user know clearly what to do to proceed.

Here we have at least one menu item selected, so it says: "Press the [Next] button below."

If we had no menu items selected, it could say: "Please select what you would like to set up above."

**Comment by afbjorklund** [comment]
If you really want to go all in on containerd, not just with "kind" but also with "lima", it _could_ be done...

It would require either growing CLI support (beyond API), or deploying some middleware like `nerdctld`.

But maybe it is just an old mockup image, using a non-official CNCF Lima logo and the official tagline ?

https://user-images.githubusercontent.com/799683/242455351-abbea002-f7ed-4657-ad9e-7f311dca90f4.png

**Comment by mairin** [comment]
@afbjorklund I think that is honestly old mockup filler. I think I found that logo in Lima's GitHub repo somewhere. And I came up with the text as filler based on wikipedia or smtg. I can absolutely fix it - I'll pull together an update and run it by you to check over for correctness?

**Comment by afbjorklund** [comment]
Actually I was more curious if there were any plans to support containerd (directly, not through docker) in the future, or if it was just placeholder text from the home page - and it looks more like the project description than any major changes.

For the icon, I was also a fan of the "bean" - but the word logo was the one that became the official one. Only problem is that it doesn't really work in small places (like this one), so I'm not sure what the best advice is - until a new one is up...

**Comment by mairin** [comment]
I'm gonna close this because I think we've basically already implemented this.
