### ISSUE TITLE
Allow Image Name field for Build Image from Containerfile to auto-generate

### ISSUE THREAD

**Issue by cedricclyburn** [containers/podman-desktop#2713]
### Is your enhancement related to a problem? Please describe

When visiting **Containers** -> **Build Image from Containerfile** and selecting my Containerfile path, I wish the _Image Name_ field would auto-generate using the name of the folder as an image name. 

<img width="1109" alt="image" src="https://github.com/containers/podman-desktop/assets/54345140/3f8afd35-0aa1-4609-b390-7775ad917d2d">

When trying to copy-paste from the Build context directory or Containerfile path, it opens up the new folder directory.

<img width="1108" alt="Screen Shot 2023-05-31 at 6 19 42 PM" src="https://github.com/containers/podman-desktop/assets/54345140/8e7585a5-8aeb-4523-b678-e3ff04d4bc6f">

### Describe the solution you'd like

Auto-completion of folder name as default image name. Not a huge enhancement, but would save users like me small amounts of time that add up!

**Comment by benoitf** [comment]
hi @cedricclyburn thanks for the report

is this something you would be interested to contribute ?

**Comment by cedricclyburn** [comment]
For sure, I can take a shot! @benoitf

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte is the file to look at

**Comment by dark-developer15** [comment]
Hey @benoitf, is the issue solved, I see the PR linked to this issue, but still, this is open.

**Comment by benoitf** [comment]
Hello @dark-developer15 pr was closed but not merged so it's still open

**Comment by dark-developer15** [comment]
Ok.

**Comment by jannikbertram** [comment]
I'd like to work on this and already submitted a PR :)
