### ISSUE TITLE
improve loader sequence

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2732]
### Is your enhancement related to a problem? Please describe

When we launch Podman Desktop, there is an initialization step where we need to wait that plug-ins have been started, etc.

During that phase we display a 'Loader screen'

This screen is the same than the beginning (done really quick) and I feel we can improve it ;-)

https://github.com/containers/podman-desktop/assets/436777/b8f4284b-62f2-4b78-8096-0f7c412fe4b0

### Describe the solution you'd like

Make it more fancy

**Comment by deboer-tim** [comment]
+1. Even some simple logo animation would be better, but agreed we could do much fancier/cooler.

IMHO we could also use some tricks to make the startup appear faster (e.g. making main UI start to appear before it is actually clickable) or be useable faster (e.g. deferred loading of bits that aren't used often/immediately).

**Comment by mairin** [comment]
![rocketseal03](https://github.com/containers/podman-desktop/assets/799683/2943713b-ed4f-434a-84b6-a0b4aa2bec38)

**Comment by mairin** [comment]
![rocketseal05 plain](https://github.com/containers/podman-desktop/assets/799683/c636eccb-9504-4212-8fbe-d9473eb4367d)

that one big star in the top row is fighting me but otherwise... :)

**Comment by mairin** [comment]
![rocketseal06 plain](https://github.com/containers/podman-desktop/assets/799683/9c366501-c257-46be-8551-810afdcfa3f0)
Here's a version without the black circle backdrop

**Comment by mairin** [comment]
![rocketseal08 plain](https://github.com/containers/podman-desktop/assets/799683/8e3789e1-8ad7-457f-9349-6f0cc7839967)

**Comment by mairin** [comment]
![rocketseal09 plain](https://github.com/containers/podman-desktop/assets/799683/691f8c73-fb89-4353-84a4-e83548a0c2c0)

**Comment by TomSweeneyRedHat** [comment]
Love it!
Given that we're on the ISS, very appropriate too!

**Comment by slemeur** [comment]
Excellent! :)
