### ISSUE TITLE
Misc terminal enhancements

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2739]
### Is your enhancement related to a problem? Please describe

A discussion came up in the podman-desktop chat today from a user wanting to customize the terminal we offer for containers to display the current working directly on the prompt. Another idea was for color syntax highlighting (TERM=xterm-256color). Maybe customize the terminal emulator used?

### Describe the solution you'd like

Ideas would be:
- add a preference for the terminal to display current working directory on prompt
- add preference to change terminal emulator
- turn on color or make it an option

**Comment by mairin** [comment]
(might be more relevant for the VM term than the container terms in case the containers dont have a shell?)

**Comment by afbjorklund** [comment]
* #889

**Comment by jberkus** [comment]
There's a general problem that the terminal window is not any kind of a full-featured terminal emulator.  Desktop doesn't even need to provide a choice, as long as some kind of real terminal emulator is provided instead of the limited-feature, graphically challenged one that is currently offered.  This would solve the following problems:

- Terminal font can't be changed, is small and hard to read, no antialiasing
- Terminal does not scroll correctly
- Line wrapping does not work in terminal

**Comment by benoitf** [comment]
FYI you can change the font size

**Comment by jberkus** [comment]
How?

**Comment by benoitf** [comment]
in settings preferences there is terminal font size setting

**Comment by jberkus** [comment]
aha.  It's still weirdly small though.  Much smaller than its "point" size would indicate.  Also, you can't change the actual font, and you can't change it without exiting the terminal.  All of these things would be fixed by embedding a full-featured terminal emulator.

**Comment by benoitf** [comment]
It's a full featured terminal emulator

**Comment by jberkus** [comment]
so I should be filing all of these issues separately then?

**Comment by benoitf** [comment]
yes please. We're using xterm.js which is the defacto standard 
If you're facing bugs, please report them and if possible with a reproducible case

**Comment by vancura** [comment]
Our current accessibility initiatives around terminal typography (Issue #12580 for font family selection and Issue #2110 for font sizing) align well with this broader terminal enhancement vision.

I recommend we consider an integrated approach that addresses both visual presentation (typography, colors) and functional capabilities (prompt customization, terminal emulation).

This would allow us to implement a cohesive architecture that supports progressive enhancement of the terminal experience while maintaining accessibility as a core design principle throughout the system.
