### ISSUE TITLE
Using microshift on Mac leads to an error at startup 

### ISSUE THREAD

**Issue by vietk** [containers/podman-desktop#2741]
### Bug description

Hello, 

I am using podman 1.0.1 with podman version 4.5.1 
I want to use OpenShift local backed up by microshift, so I choosed the proper extension.

```
OpenShift Local is stopped
Version 2.20.0 (MicroShift)
```
Once installed, the extension is failing when started with the following error

```
Red Hat OpenShift Local

OpenShift Local start error: Error: Bundle 'crc_microshift_vfkit_4.13.0_amd64' was requested, but the existing VM is using 'crc_hyperkit_4.7.5'. Please delete your existing cluster and start again
```

Regards
Kevin

### Operating system

macOS ventural (Intelbased)

### Version

1.0.x

### Steps to reproduce

Install podman-desktop
Install openshift local extension 
Run openshift local cluster extension

**Comment by cfergeau** [comment]
Looks like you have/had a very old crc installation around. If you can't delete the existing crc instance from podman-desktop UI, running `crc delete` from the command line should unblock you.

**Comment by gbraad** [comment]
Related to this is: https://github.com/crc-org/crc-extension/issues/37
This needs to be resolved.

**Comment by vietk** [comment]
> Looks like you have/had a very old crc installation around. If you can't delete the existing crc instance from podman-desktop UI, running `crc delete` from the command line should unblock you.

Hello, thanks for suggestion, I will try that and get back to you

**Comment by vietk** [comment]
> Looks like you have/had a very old crc installation around. If you can't delete the existing crc instance from podman-desktop UI, running `crc delete` from the command line should unblock you.

So actually it fixes the issue 
Many thanks !
