### ISSUE TITLE
Quickpick issues

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2754]
### Is your enhancement related to a problem? Please describe

I found a number of related issues while trying to use a quickpick:
1. If I want to cancel a quick pick I need to use the keyboard (esc).
2. The API has a 'picked' property when using showQuickPick(), but it doesn't appear to do anything.
3. When a quick pick is visible you can still click on the navbar. If the quick pick is as wide as your window it partially goes under the nav bar.

### Describe the solution you'd like

1. Clicking outside the quickpick should exit it.
2. The picked item should be selected by default.
3. Quickpick should be 'on top'.

**Comment by benoitf** [comment]
for the 3rd point I suppose it's when z-order has been changed on navbar

**Comment by deboer-tim** [comment]
Likely, yes. Same fix as MessageBox is easy, was just checking if any of the others are quick too.
