### ISSUE TITLE
Status bar item duplicated after change

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2756]
### Bug description

I've tried to start narrowing this down, and I _think_ I've confirmed it's not the extension causing this, but it is a bit bizarre... :)

If you have a status bar item and register it via the extension context subscription, it correctly gets cleaned up when the extension is stopped (and recreated when the extension starts). This works fine for simple items.

If the status bar item changes its text, it is duplicated after stopping and restarting, or in the case below, changing the text will 'bring back' instances of the status bar item from previous runs (and change the text of all of them).

https://github.com/containers/podman-desktop/assets/19958075/082b2557-0a68-4ba8-ba20-a603750ac959

### Operating system

macOS 13.3 M1

### Version

next (development version)

**Comment by deboer-tim** [comment]
Took me a while to realize the obvious: if the old statusbaritems are being updated, it means that there is a listener hanging around. Confirmed that onDidUpdateKubeconfig() is never unregistered, so the kube-context extension continues to receive events even after it is stopped.

This should be addressed after PR #2755.

**Comment by benoitf** [comment]
it has been fixed by https://github.com/containers/podman-desktop/issues/3528
