### ISSUE TITLE
Podman desktop GUI not able to see running container

### ISSUE THREAD

**Issue by tppalani** [containers/podman-desktop#2759]
### Bug description

I have installed podman desktop version 4.5.1 in windows VM, Using podman desktop not able list any existing image, running container.

### Operating system

windows

### Version

1.0.x

### Steps to reproduce

$ podman machine list
NAME                    VM TYPE     CREATED     LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  wsl         7 days ago  Currently running  12          1.464GB     9.394GB

$ wsl -l -v
  NAME                      STATE           VERSION
* podman-machine-default    Running         2
  wsl-vpnkit                Running         2

### Relevant log output

```shell
$ podman ps -a
CONTAINER ID  IMAGE                                                                                           COMMAND               CREATED        STATUS                     PORTS                                                                                        NAMES
e8fb7a5bf87f  docker.io/selenium/standalone-chrome:latest                                                     /opt/bin/entry_po...  17 hours ago   Exited (143) 12 hours ago  0.0.0.0:4444->4444/tcp, 0.0.0.0:5900->5900/tcp                                               jovial_davinci
ce0454afe62c  docker.io/kindest/node@sha256:c44686bf1f422942a21434e5b4070fc47f3c190305be2974f91444cd34909f1b                        5 minutes ago  Up 5 minutes               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:1111->1111/tcp, 127.0.0.1:57208->6443/tcp  kind-control-plane
```

![image](https://github.com/containers/podman-desktop/assets/6921037/a5000702-bb11-4488-9f67-27ac5f2291c4)
![image](https://github.com/containers/podman-desktop/assets/6921037/9944999b-076e-49aa-825c-74b0efc7185e)

**Comment by benoitf** [comment]
thanks for the report
@tppalani do you see some logs on Podman Desktop (<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd> shortcut) and then console view ?

**Comment by tppalani** [comment]
> thanks for the report @tppalani do you see some logs on Podman Desktop (Alt + Shift + i shortcut) and then console view ?

I'm not seeing anY output when I'm doing Alt + shift + i, Can u pls help me.

**Comment by odockal** [comment]
@tppalani I believe that the shortcut for developer console on windows is actually (`CTRL` + `SHIFT` + `I` or `F12`). 

In any case, this could be similar to: #3196, which was resolved and patch is in latest stable release 1.2.1.

We have two options now, either we can try to find a culprit (if it is similar or the same as mentioned resolved issues), or you could try to install latest stable release if the issues was resolve there.

For the first option, sometime force reload of the podman desktop helped: `CTRL` + `R`, you can try that.

Or please try to install newest version of podman desktop.

**Comment by slemeur** [comment]
@tppalani do you still have the issue?

**Comment by odockal** [comment]
I am closing the issue as there is likely a fix already released in a newer version. @tppalani Feel free to reopen if you are still seeing the issue and we could continue here. thx.
