### ISSUE TITLE
Can't install extensions on Windows 10

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#2761]
### Bug description

The extensions can't be installed and are marked N/A on the featured extensions panel.

Seems to be related with root certificates

![image](https://github.com/containers/podman-desktop/assets/695993/621162a6-03db-4ed0-bc03-342593d8e3b3)

### Operating system

Win10 Pro

### Version

1.0.x

### Steps to reproduce

1. Install on Win10
2. Launch
3. See the featured extensions panel

**Comment by gbraad** [comment]
I am running Win10 and I do not have this issue. Yes, it complains about:

```
14:13:15 [main] Error while retrieving Windows certificates <ref *1> Error: spawnSync C:\Users\gbraad\Projects\podman-desktop\packages\main\dist\roots.exe ENOENT
```

but this seems unrelated. Can you run `systeminfo` to see more about the version of your Win10?

**Comment by jeffmaury** [comment]
This applies to production bits

**Comment by gbraad** [comment]
I see from the PR no root certificates were included. That explains it.
Was this previously tested wih release builds?
