### ISSUE TITLE
New shells are created each time the terminal window of a container is opened

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#2763]
### Bug description

A new shell is created when I switch between tabs of the container. This means that a process needs to be explicitly killed as it remains active/'backgrounded'.
![image](https://github.com/containers/podman-desktop/assets/1894/827bcc71-6e47-4002-ab80-8344c4691a88)

### Operating system

n/a

### Version

1.0.x

### Steps to reproduce

Switch from summary to terminal a few times.

**Comment by benoitf** [comment]
I'm pretty sure we already had this issue reported but as I don't find it, I'll not flag as duplicate

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/3725 (related to https://github.com/containers/podman-desktop/issues/502)
