### ISSUE TITLE
Impossible to close error message when the message is long

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2771]
### Bug description

Error popup window shown with a long message.
Impossible to close it from the UI
workaround: press "esc"

<img width="1424" alt="Capture d’écran 2023-06-08 à 10 25 51" src="https://github.com/containers/podman-desktop/assets/1636769/882af86e-bfcb-4a3a-9239-8ef98021ba05">

### Operating system

Ventura 13.4

### Version

1.0.x

**Comment by deboer-tim** [comment]
I'll set a max-height on the message with autoscroll to avoid this.
