### ISSUE TITLE
Add a documentation on how people can write a blog post on the website

### ISSUE THREAD

**Issue by lbocinco** [containers/podman-desktop#2790]
### Is your enhancement related to a problem? Please describe

Podman Desktop Website includes [Blog page](https://podman-desktop.io/blog), but it is not clear who can contribute to it and if so, how someone can contribute by writing a blog on Podman Desktop topic. 

### Describe the solution you'd like

Write a documentation on who can write a blog post to the page, and what steps people should follow when they want to write a blog post. Add the link into the blog page, something like "Do you have any tips on how you use Podman Desktop? Write a blog".

**Comment by deboer-tim** [comment]
IMHO #1861 is a prerequisite for this - I have to refer to it every time I write a blog to remember the commands.

**Comment by lbocinco** [comment]
Yes, I agree! I was looking at the contributing guide and it doesn't mention other than coding contributions.
