### ISSUE TITLE
Podman installation is not automatically detected on Mac OS

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2791]
### Bug description

I have installed podman via podman desktop, but I was expecting automated detection of podman installation in the dahsboard. I had to refresh page or restart manually in order to have podman-desktop correctly detected podman.

![macos-podman-install-detection](https://github.com/containers/podman-desktop/assets/19164299/a79265cf-a481-4f0e-a073-18919db7219e)

### Operating system

macOS 13

### Version

1.1.0

### Additional context

It is related to https://github.com/containers/podman-desktop/issues/2192

**Comment by benoitf** [comment]
I think it was fixed by @jeffmaury

**Comment by benoitf** [comment]
@odockal could you check if it's still an issue ?

**Comment by odockal** [comment]
Seems fixed on Mac OS 12 as of Podman Desktop 1.3.1. After installation of podman Podman Desktop correctly detects installed podman. No restart needed.
