### ISSUE TITLE
Kind cluster creation ended with error: Failed to create kind cluster. No active cluster

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2795]
### Bug description

Kind cluster creation on Mac os 1.1.0 ended up with a "Cannot create kind cluster: No Active cluster". Cluster was eventually created on the filesystem. Can be verified by kind binary. But podman desktop did not detected it.

![Screenshot_20230609_182650](https://github.com/containers/podman-desktop/assets/19164299/6c109bfa-f832-4c79-b5e7-f37cd535aec6)

No kind cluster present:
![Screenshot_20230609_182901](https://github.com/containers/podman-desktop/assets/19164299/3f84afb2-5cbe-41dd-a8fe-d2bd777ea5a0)

Cli output:
![Screenshot_20230609_183017](https://github.com/containers/podman-desktop/assets/19164299/20ff2c6f-a956-4f6b-85b4-caf3092b941f)

### Operating system

macOS 13 (Intel)

### Version

1.1.0

### Steps to reproduce

Create rootfull podman machine, download a kind and try to create kind cluster.

### Additional context

I have seen the issue multiple time. I recall it was something unstable. I failed to find an issue reported, so here it is.

**Comment by jeffmaury** [comment]
Looks like a sync issue on the kubeconfig file

**Comment by odockal** [comment]
I am betting that the issue was with a "wrong" connection that was used by the podman. It was not root connection but the default one for given machine. ~~Probably caused by https://github.com/containers/podman-desktop/issues/2582~~

**Comment by jeffmaury** [comment]
No I was able to reproduce seems to happen when you have no kubeconfig before you create the Kind cluster

**Comment by odockal** [comment]
Nice catch! Should we overcome this error (since error is there, but follow up actions will create proper kubeconfig) or keep this as know issue/feature coming from kind/kube context client?

**Comment by JurrianFahner** [comment]
> No I was able to reproduce seems to happen when you have no kubeconfig before you create the Kind cluster

What @jeffmaury  wrote, is exactly also the case for me. Solution would be:
1. automatic install of kubectl (in case there ~\.kube\config file does not exist)
2. documentation to ask the user to install `kubectl`, on installation the ~\.kube\config file will be automatically created. 

The issue can be reproduced by removing the kind cluster and the .kube folder from the user folder.

**Comment by Blaimi** [comment]
this happens, when no `~/.kube/config`-file exists when podman Desktop starts and the ingress controller shall be installed. If the file is missing, the `kube-context`-plugin somehow disables itself. There is also no context or "no context" lower left. The problem does not occur if at least an empty `~/.kube/context`-file exists _before_ starting podman Desktop.

The `kind` command works as it should: creates the cluster and sets up the context in `~/.kube/context`. But `kubernetes-client#createResources(…)` cannot create the resources for contour because the `kube-context`-plugin has already disabled itself.

As a workaround execute the following commands in _bash_ respectively _PowerShell_

```bash
mkdir -p ~/.kube && touch ~/.kubeconfig
```
```powershell
If(-Not (Test-Path ~\.kube)) {New-Item -Path ~\.kube -ItemType Directory}
If(-Not (Test-Path ~\.kube\config)) {New-Item -Path ~\.kube\config -ItemType File}
```

**Comment by jeffmaury** [comment]
@odockal I cannot reproduce with 1.8.0 on Win11Pro. Is it MacOS specific ?

**Comment by Blaimi** [comment]
cannot reproduce this with version 1.8.0 on fedora 39 either. The cluster gets created and contour gets installed. #6406 still occurs but I think this bug can be closed as fixed.

**Comment by nichjones1** [comment]
@odockal can you retest this issue?

**Comment by odockal** [comment]
Seems like the issue was fixed. I got no error. @Blaimi seems about right, context was not updated as in mentioned issue. Still closing.
