### ISSUE TITLE
Podman Desktop not able to detect the list of images present in local computer

### ISSUE THREAD

**Issue by tppalani** [containers/podman-desktop#2806]
### Issue Description

I have installed podman desktop latest version 4.5.1 in windows OS and status of the machine is active, but when I'm doing pull the image using using windows vm CLI like power shell i can able to pull the image but after pulling the images not able to find the pulled images from podman GUI desktop.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

```
podman images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
docker.io/library/alpine  latest      5e2b554c1c45  4 weeks ago  7.62 MB
```

![image](https://github.com/containers/podman/assets/6921037/7be9f567-fcd0-4094-9058-c10bdf1ba0de)

### Describe the results you expected

Describe the results you expected

windows CLI and podman desktop GUI should be in sync.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
This looks like a podman-desktop issue not podman, I am moving it the issue there.

**Comment by jeffmaury** [comment]
Was the podman machine created from CLI or from Podman Desktop ?

**Comment by tppalani** [comment]
Hi @jeffmaury podman machine is created from CLI.

**Comment by jeffmaury** [comment]
Can you give the steps you followed to create and start your rootful machine ?

**Comment by tppalani** [comment]
Hi @jeffmaury 
```
podman machine init
podman machine start
podman machine set --rootful
```

**Comment by jeffmaury** [comment]
I can reproduce on my machine. Machine my be restarted as the win-sshproxy is still using the old machine connection

**Comment by tppalani** [comment]
Hi @jeffmaury sorry not getting it.

**Comment by jeffmaury** [comment]
That's fine as the message issued by Podman when the machine is started is misleading

**Comment by tppalani** [comment]
Please let me know if any details required from my side

**Comment by jeffmaury** [comment]
No that's an issue on the podman side. When you switch the machine to rootful, the machine needs to be restarted.

**Comment by tppalani** [comment]
Hi @jeffmaury  I have restarted the podman machine using GUI desktop, but still not showing it.

**Comment by lstocchi** [comment]
@tppalani if you run `podman system connection ls` which is the default machine? What if you set the rootful one as default with `podman system connection default podman-machine-default-root`? Once the root one appears to be the default, try again to pull an image. You should see it in the GUI.

**Comment by tppalani** [comment]
Hi @lstocchi PS C:\Users\username> podman system connection ls
Name                         URI                                                          Identity                                      Default
podman-machine-default       ssh://user@127.0.0.1:55725/run/user/1000/podman/podman.sock  C:\Users\username\.ssh\podman-machine-default  false
podman-machine-default-root  ssh://root@127.0.0.1:55725/run/podman/podman.sock            C:\Users\username\.ssh\podman-machine-default  true

**Comment by tppalani** [comment]
Hi @lstocchi I have set podman system connection default podman-machine-default-root as default machie but still in GUI i can see machine name is different


![image](https://github.com/containers/podman-desktop/assets/6921037/fde40f41-5b81-4efe-85cd-47e52a750798)

**Comment by lstocchi** [comment]
@tppalani that's normal. The machine is always the podman-machine-default, it just changes the way you interact with it. As a root user or not. So the name won't change.

**Comment by jeffmaury** [comment]
Can you stop and start the machine and see if there's an error message ?

**Comment by tppalani** [comment]
I don't see any error message for stop and start

**Comment by lstocchi** [comment]
If you ssh in your machine `podman machine ssh` and execute `ls -l /var/run/docker.sock` what's the outcome?

**Comment by tppalani** [comment]
Hi @lstocchi 

PS C:\Users\username> podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Warning: Permanently added '[localhost]:64913' (ECDSA) to the list of known hosts.
Last login: Wed Jun 14 08:08:26 2023 from 127.0.0.1
[root@LDD4C42 ~]#
[root@LDD4C42 ~]#
[root@LDD4C42 ~]# podman system connection list
Name        URI         Identity    Default
[root@LDD4C42 ~]# ls -l /var/run/docker.sock
lrwxrwxrwx 1 root root 23 Jun 14 07:55 /var/run/docker.sock -> /run/podman/podman.sock

**Comment by tppalani** [comment]
But still this purpose of this ticket is not able to list images which is listed in my vm from GUI but still i don't get any solution for this

**Comment by lstocchi** [comment]
@tppalani we are trying to get what's wrong and apparently everything is how it should. My idea was that maybe you were using the rootless socket (`/run/user/1000/podman/podman.sock`) but it is not. I still don't see the reason why it doesn't work for you.

I've tried your same steps and it works for me. Can you give a quick look at the video and tell me if you do something differently?
https://drive.google.com/drive/u/1/folders/19u8WVlg-KOkq7dVZy3m6AIayHQMbj6j-

**Comment by tppalani** [comment]
Hi @lstocchi  thanks for the help i will keep you posted.

Adding one note here.

```
$ podman machine ls
NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  wsl         11 hours ago  Currently running  12          2.569GB     5.401GB

 podman pull nignix
Error: failed to connect: dial tcp 127.0.0.1:64913: connectex: No connection could be made because the target machine actively refused it.
```

Mutiple application teams are facing same issue (more than 300 people) not sure why and what we are missing it,

**Comment by tppalani** [comment]
Hi @lstocchi  i don't have access for this page can u pls provide the access https://drive.google.com/drive/u/1/folders/19u8WVlg-KOkq7dVZy3m6AIayHQMbj6j-

**Comment by lstocchi** [comment]
> Hi @lstocchi i don't have access for this page can u pls provide the access https://drive.google.com/drive/u/1/folders/19u8WVlg-KOkq7dVZy3m6AIayHQMbj6j-

I sent the wrong link apparently 😓 try with https://drive.google.com/file/d/1kZec0iPO1yaJrdPp1nxYaearJh6_LStN/view?usp=sharing

**Comment by lstocchi** [comment]
> Hi @lstocchi thanks for the help i will keep you posted.
> 
> Adding one note here.
> 
> ```
> $ podman machine ls
> NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
> podman-machine-default  wsl         11 hours ago  Currently running  12          2.569GB     5.401GB
> 
>  podman pull nignix
> Error: failed to connect: dial tcp 127.0.0.1:64913: connectex: No connection could be made because the target machine actively refused it.
> ```
> 
> Mutiple application teams are facing same issue (more than 300 people) not sure why and what we are missing it,

Here it seems you have a different issue and you already replied about it on https://github.com/containers/podman/issues/19554 . Unfortunately I don't have any other thing to suggest other than what it was told in that issue though :( . Tomorrow i'll try to investigate more.

**Comment by tppalani** [comment]
Hi @lstocchi did you find the any solution for the above error.

**Comment by lstocchi** [comment]
@tppalani still not ... i tried to replicate your issue and i was able to achieve your same exact error by uninstalling podman, reinstall it and trying to build an image. I solved the `failed to connect` error by switching to the rootful instance.
```
podman system connection default podman-machine-default-root
podman machine set --rootful podman-machine-default
``` 
Then it never happened again. I'm still trying once in a while while working on other things but it's quite stable on my machine :/ 
I'm sorry but i don't have any solution so far

**Comment by tppalani** [comment]
Hi @lstocchi thanks lot for your help.

Just one question when I need execute below two commands, after the podman machine init command?

podman system connection default podman-machine-default-root
podman machine podman-machine-default set --rootful

**Comment by lstocchi** [comment]
@tppalani yes. Basically i already had my machine created. I uninstalled podman and reinstalled it. My machine was there but podman was not able to reach it `(No connection could be made because the target machine actively refused it`), so i run those two commands, i think they kinda restored the connection and it worked. But as i am not able to reproduce it consistently i don't know if it just worked in that case. Let me know if it does the magic for you as well.

**Comment by tppalani** [comment]
@lstocchi  is there any typo in this command 

```
podman machine podman-machine-default set --rootful
Error: unknown flag: --rootful

PS C:\Users\username> podman machine podman-machine-default set --help
Manage a virtual machine

Description:
  Manage a virtual machine. Virtual machines are used to run Podman.

Usage:
  podman.exe machine [command]

Available Commands:
  info        Display machine host info
  init        Initialize a virtual machine
  inspect     Inspect an existing machine
  list        List machines
  os          Manage a Podman virtual machine's OS
  rm          Remove an existing machine
  set         Sets a virtual machine setting
  ssh         SSH into an existing machine
  start       Start an existing machine
  stop        Stop an existing machine

```

**Comment by lstocchi** [comment]
> @lstocchi is there any typo in this command
> 
> ```
> podman machine podman-machine-default set --rootful
> Error: unknown flag: --rootful
> 
> PS C:\Users\username> podman machine podman-machine-default set --help
> Manage a virtual machine
> 
> Description:
>   Manage a virtual machine. Virtual machines are used to run Podman.
> 
> Usage:
>   podman.exe machine [command]
> 
> Available Commands:
>   info        Display machine host info
>   init        Initialize a virtual machine
>   inspect     Inspect an existing machine
>   list        List machines
>   os          Manage a Podman virtual machine's OS
>   rm          Remove an existing machine
>   set         Sets a virtual machine setting
>   ssh         SSH into an existing machine
>   start       Start an existing machine
>   stop        Stop an existing machine
> ```

`podman machine set --rootful podman-machine-default` 
or if you only have one machine 
`podman machine set --rootful`

**Comment by themr0c** [comment]
I am happy to add an entry in our troubleshooting section. I understand it is Windows specific, when using the rootful mode, happens only from time to time, and that we do not have a workaround. Is that correct?
