### ISSUE TITLE
Images created in command line are not shown in podman desktop

### ISSUE THREAD

**Issue by cgx-system** [containers/podman-desktop#2807]
### Issue Description

When I build an image using `podman build` in command line, the image is build with success but I can't find it in podman desktop.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman build -t my-image`
2. `podman images` shows the image in the local registry
3. open podman desktop and look into images tab, the image is not there

### Describe the results you received

The image can be seen in the local registry in command line, but not in podman desktop

### Describe the results you expected

The built image should be available in podman desktop

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.91
    systemPercent: 0.06
    userPercent: 0.03
  cpus: 12
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: Accueil
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 7631065088
  memTotal: 8274423808
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 1h 33m 15.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 1110740992
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 24
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486976
  BuiltTime: Fri Apr 14 17:42:56 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Windows 11 with WSL2

### Additional information

Closing and restarting podman desktop or podman machine doesn't help

**Comment by cgx-system** [comment]
Just tested on another station with same versions of **podman** and **podman desktop** : the images appear in podman desktop but if I run one of them, the container list stays empty.
`podman ps` shows the running container, so it's definitely a podman desktop or podman remote issue...

**Comment by Luap99** [comment]
podman-desktop issues should be reported in the desktop repo: https://github.com/containers/podman-desktop/
I am moving the issue there.

**Comment by benoitf** [comment]
hello @cgx-system are you using a rootful podman or a rootless podman ?

**Comment by cgx-system** [comment]
> hello @cgx-system are you using a rootful podman or a rootless podman ?

The default one... rootless I guess

**Comment by benoitf** [comment]
Podman Desktop will try to connect to a socket at `/run/user/${uid}/podman/podman.sock` path

do you have such a file ?

you can do a curl request like
```
 curl --silent --unix-socket /run/user/<REPLACE WITH YOUR USER_ID>/podman/podman.sock "http://v1.41/containers/json?all=true"
 ```

**Comment by cgx-system** [comment]
I'm on Windows, this path doesn't exist

**Comment by jeffmaury** [comment]
Can you show the output of `podman system connection ls`

**Comment by cgx-system** [comment]
Just updated to podman 4.5.1 and now it seems to work as expected

**Comment by guillaume154a** [comment]
I experience the same issue using Podman 5.2.4, which I recently updated from a previous version. 

`podman system connection ls` shows the following: 

```
Name                         URI                                                          Identity
                                             Default     ReadWrite
podman-machine-default       ssh://user@127.0.0.1:50766/run/user/1000/podman/podman.sock  C:\Users\USERNAME\.local\share\containers\podman\machine\machine  false       true
podman-machine-default-root  ssh://root@127.0.0.1:50766/run/podman/podman.sock            C:\Users\USERNAME\.local\share\containers\podman\machine\machine  true        true
```

The GUI dashboard says on top "podman-machine-default", and besides there's a warning message:
> ⚠ Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.

**Comment by seriouspoop** [comment]
@benoitf 
> you can do a curl request like
> 
> ```
>  curl --silent --unix-socket /run/user/<REPLACE WITH YOUR USER_ID>/podman/podman.sock "http://v1.41/containers/json?all=true"
> ```

I'm getting  an empty json response on curl
```bash
harshit@fedora:~$  curl --silent --unix-socket /run/user/1000/podman/podman.sock "http://v1.41/containers/json?all=true"
[]
harshit@fedora:~$ 
```

Also when I run `podman system connection ls` that is also empty
```bash
harshit@fedora:~$ podman system connection ls
Name        URI         Identity    Default     ReadWrite
harshit@fedora:~$ 
```

**Comment by benoitf** [comment]
@seriouspoop it looks like you're on Linux, so I'm wondering if you execute rootful containers

as Podman Desktop will print only user/rootless containers

**Comment by seriouspoop** [comment]
@benoitf I didn't build any containers yet, I just build images and the images are also not visible on the podman-desktop

**Comment by benoitf** [comment]
@seriouspoop how do you build these images

**Comment by seriouspoop** [comment]
@benoitf I've built a custom bash script to build all the images for services, the bash script is below
```bash
#!/bin/bash

BLUE='\e[34m'
GREEN='\e[32m'
RED='\e[31m'
RESET='\e[0m'

timestamp=$(date +%y%m.%d.%H%M)

#set relative project root path
projectDir=`cd ../..;pwd`

declare -a arr=(
    # "user-ms"
    "template"
    )

count=1

for i in "${arr[@]}"
do
    echo -e "${BLUE}[$count/${#arr[@]}] Building $i$RESET"
    podman build --file "$projectDir/$i/Containerfile" --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_TOKEN=$GITHUB_TOKEN --build-arg IS_PROD_ENV=$IS_PROD_ENV --tag "$i-local" "$projectDir/$i/"
    EXITCODE=$?
    if [ $EXITCODE != 0 ]; then
        echo -e "${RED}Build failed with exit code $EXITCODE$RESET"
        exit
    fi
    ((count++))
done
echo -e "${GREEN}[DONE] Building service images"

 ```

**Comment by seriouspoop** [comment]
> [@seriouspoop](https://github.com/seriouspoop) it looks like you're on Linux, so I'm wondering if you execute rootful containers
> 
> as Podman Desktop will print only user/rootless containers

how do we differentiate between rootful and rootless? and how to i specify in which mode i want to run?

**Comment by seriouspoop** [comment]
@benoitf anything on this?
