### ISSUE TITLE
Remove menu bar

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#281]
### Is your enhancement related to a problem? Please describe

On Mac I almost don't notice that Podman Desktop has a menu bar; it's up at the top of the screen and the fact that a lot of the options are standard or a little odd doesn't really matter.

Using Windows today I really noticed the menu bar. It takes up extra space, and since the styling is different it really stands out compared with the rest of the window.

### Describe the solution you'd like

Most other system tray apps don't have a menu bar at all, so I think it should be removed. Add any options we really need to keep into the dashboard.

**Comment by benoitf** [comment]
Menu bar will stay across all platforms (macOS/Windows/Linux)
https://github.com/containers/podman-desktop/issues/323#issuecomment-1191477276
