### ISSUE TITLE
Compose UX improvements

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2811]
### Problem statement

We've received user feedback that how compose works with Podman Desktop is confusing. (I didn't really understand it either. ;-) ) We should improve how we present it in the UI so it's more clear what it does and doesn't do.

### What is Compose

- Compose isn't "docker compose" or "podman compose" it's a spec, see [https://compose-spec.io/](https://compose-spec.io/)
- Difference between pods and compose:
  - compose is more developer-oriented and simple way to group containers together with network…. 
  - Pods a little more complex but more featureful. 
  - Pods written in yaml; yaml harder to read than compose files. 
  - Compose is portable
  - Compose has broad adoption

### How compose works in Podman Desktop right now:

Whether or not you have the Podman desktop compose extension, you will see compose containers in the container list grouped together. You cannot stop/start the compose (is there an issue to request this? put link here), and you can't see details at the compose/group level like you can with pods (link to issue if exists here).

When you click on the compose button, it installs docker compose for you. Note: Docker compose does not require docker. It works with Podman as the backing container engine. It's an easy way to get compose functionality.

### Ideas

Charlie thinking about feature to use [kompose](https://kompose.io/) to enable user selection of docker compose files to create pods.

### Approach
- Mo will do an audit (on Linux + Mac) of how compose set up works with Podman Desktop today 
- Wireframe/mockup proposed changes

(note to self, this was discussed at June 8 2023 and the 15 June 2023 UX calls ~m)

# Design

## Discussion Thread

[https://github.com/containers/podman-desktop/discussions/2881](https://github.com/containers/podman-desktop/discussions/2881)

## WIP

Penpot file:
https://design.penpot.app/#/view/c86728dd-89fd-8169-8002-a2594e3e4ba5?page-id=e28e7abb-3208-808c-8002-aae6038746ab&section=interactions&index=0&share-id=7bde5548-9bcb-8041-8002-ab25006f688d

**Comment by mairin** [comment]
Notes from today's UX review call:

## Compatibility mode
Mo needs to revisit the mockups with the variable of compatibility mode under consideration:
- If compatibility mode is on, regardless of how compose is configured, docker compose will use podman
- Compose can set up the socket too?? (?)
- Are there users who do not want compatibility mode but want compose support? Maybe but we will treat it as an edge case. (For example, Eric Deandrea had cases for Quarkus where he needed to use Docker for the engine and not podman, iirc related to storage handling.) 

## Onboarding
- TODO Mo needs to show mockups in the onboarding flow as well
- This is a one click in Docker Desktop onboarding, we need to think similarly and not over complicate it

## System Tray handling
- Persistent system tray Compose item goes away… we only display if:
  - not installed? (Mo thinks no)
  - installed but needs attention (eg need to set up wrapper)

## Uninstalling the extension
- The extension cannot be uninstalled, it is core
- TODO Mo needs to update language in mockups to handle extension "disable" rather than "uninstall"

## Uninstalling Compose binary
- And generally, uninstalling other resources like kind (not clusters, kind itself)
- Mo suggests either uninstall on the left side of resources column or in the details screen
- How to access details screen? Need to implement gear icon as shown here:
![Screenshot from 2023-06-15 10-23-03](https://github.com/containers/podman-desktop/assets/799683/eb9121ab-4114-4126-908c-d7b255784397)

## Some main points / decisions:
- The main use case for Compose is using podman with docker-compose.
- We don't install compose by default, so it's opt-in for the user. (Remember that we try to encourage usage of kube and not compose.)

# First (rough, incomplete) draft of mockups

The general approach I took here was to treat Compose like the other "Resources" we have. So it's a bit of an odd duck in that sense since it's not a container engine or a K8s platform, but for the short term I think this approach could work.

### Compose listed alongside other extensions

- Could appear like this in onboarding flow, dashboard, and in extensions screen

![Screenshot from 2023-06-15 12-15-29](https://github.com/containers/podman-desktop/assets/799683/7ba46be9-2cfc-4b14-8915-542b4c6b69d4)

### Compose listed in Settings > Resources 

#### Extension installed, Compose not set up

Would appear like this if you skipped setting it up in onboarding

![Screenshot from 2023-06-15 12-22-11](https://github.com/containers/podman-desktop/assets/799683/06639c4d-1573-4cb1-bfe5-458522b338e3)

#### Extension installed, Compose set up

![Screenshot from 2023-06-15 12-22-26](https://github.com/containers/podman-desktop/assets/799683/43aa7c1e-5dbc-4b06-bfee-c6b36f409f9d)

#### Extension Set up screen 

Accessed via clicking "Set up" button on the Compose card on Settings > Resources

![Screenshot from 2023-06-15 12-24-13](https://github.com/containers/podman-desktop/assets/799683/7f0cd229-1170-4069-b750-11e9c59d8b2e)

#### Extension Progress for compose install process

Should register as a task in the task manager, and if user visits another page, should be able to re-access this page via the task manager entry.

![Screenshot from 2023-06-15 12-25-09](https://github.com/containers/podman-desktop/assets/799683/aa493e9b-1ced-46c0-a00d-fe26181113f0)

#### Error handling for install process
![Screenshot from 2023-06-15 12-25-50](https://github.com/containers/podman-desktop/assets/799683/de4ff24a-e852-4fb4-937c-6b1cfd8d3a99)

#### Compose install complete / Settings screen

Accessed via clicking "Compose" name or logo or the settings icon in the left col of the Compose card on Settings > Resources OR from a completed task manager item click.

![Screenshot from 2023-06-15 12-26-19](https://github.com/containers/podman-desktop/assets/799683/bcb73d59-ca78-4866-a932-bdd711c428de)

## Onboarding sequence TBD

**Comment by cdrage** [comment]
Quick update

![Image](https://github.com/containers/podman-desktop/assets/6422176/e2a17056-3b29-47e4-942a-c2b8fe166e17)



Progress so far (had to implement a few other buttons + way to get the functionality working).

https://github.com/cdrage/podman-desktop/tree/onboarding-compose

Luca's PR's #3673 

Obviously more improvements as we add more markdown functionality.

**Comment by mairin** [comment]
![Screenshot from 2023-11-03 08-27-26](https://github.com/containers/podman-desktop/assets/799683/ca0558ab-70ad-48cc-8dd5-67e3eb465a62)
![Gan Teideal](https://github.com/containers/podman-desktop/assets/799683/77ba0fb2-5cb0-41de-a7cf-1a3d6400fd89)


I know it's weird but I'm uploading these here so I can use the image urls for the release notes 😆
