### ISSUE TITLE
Windows: add to Start menu

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#282]
### Is your feature request related to a problem? Please describe

On Mac the installer adds Podman Desktop to the Launchpad. This is standard, and means if I close it I can easily find it again.

On Windows I launched PD directly from the browser download bar the first time. By the time I needed to start it the second time, the browser had cleared the download bar. This meant I had to open up a file browser to find and launch PD - and of course closed the file browser immediately to reduce clutter. This means I have an extra step to launch PD every time, and I may move and forget where I installed it.

### Describe the solution you'd like

There are a few ways we could improve this, but my first thought it to prompt the user on first startup and ask if we can add to the Start menu. If so, we move the executable and restart, or maybe copy it and then delete the existing copy on exit.

**Comment by slemeur** [comment]
On the website, we should promote the installer (setup.exe) instead of the exe. it would make the installation experience more integrated.

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/issues/898
