### ISSUE TITLE
Deleting a non-running Podman Machine 'breaks' running machine

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2820]
### Bug description

If you have a running podman machine working correctly within Podman Desktop, and then delete another/non-running machine, the first machine's data disappears. You have to restart the machine to keep using it.

https://github.com/containers/podman-desktop/assets/19958075/e642ee1b-4ce0-4c12-8813-29c70102c761

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create two podman machines. Start one and use it, then delete the second. All images/containers from the first machine 'disappear'. Reload doesn't help, you need to stop and restart the first machine to see images/containers again.

**Comment by lstocchi** [comment]
@deboer-tim can you please try again? I'm not able to replicate it. So either this was solved somehow or it's only a problem related to Mac so it would be better to assign it to a mac user.

**Comment by deboer-tim** [comment]
I have no clue what changed in the last 2 weeks, but I can't replicate now either. There is an error in the log (below) but everything else is fine. Closing.

```
[kind] error in engine Podman Error: connect ENOENT /Users/deboer/.local/share/containers/podman/machine/qemu/podman.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```
