### ISSUE TITLE
Microshift cluster is showing an error: Error: connect ECONNREFUSED 127.0.0.1:6443

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2834]
### Bug description

I tried to start up microshift openshift local preset. all seems alright, cluster is in started state but changing the context show erorr in console log: Error: connect ECONNREFUSED 127.0.0.1:6443.

### Operating system

Fedora 37

### Version

1.1.0

### Relevant log output

```shell
index.ts:1335 main ↪️ Kube event error Error: connect ECONNREFUSED 127.0.0.1:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
(anonymous) @ index.ts:1335
emit @ VM26 sandbox_bundle:2
onMessage @ VM26 sandbox_bundle:2
index.ts:1335 main ↪️ Error while fetching API groups: Error: connect ECONNREFUSED 127.0.0.1:6443
```

**Comment by jeffmaury** [comment]
Can you reproduce each time cluster is started ? Does it affect also Windows and MacOS ?

**Comment by odockal** [comment]
@jeffmaury I just encountered on Linux. Have to take a look at other platforms.

**Comment by odockal** [comment]
@jeffmaury I have not encounter this concrete error on Windows 10. (I have seen another one, but it did not prevent starting it up).

**Comment by slemeur** [comment]
I had it on mac os
<img width="1424" alt="Capture d’écran 2023-06-08 à 10 25 51" src="https://github.com/containers/podman-desktop/assets/1636769/f078b13d-2669-4350-a399-cf3e87063314">
