### ISSUE TITLE
Add empty container/kubernetes resources message for podman and kind

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2839]
### Is your enhancement related to a problem? Please describe

We added in the API 'empty message'

But for example it's only used by DevSandbox extension
![image](https://github.com/containers/podman-desktop/assets/436777/b48678a7-d251-4d49-b5ec-0055470e4bf2)

### Describe the solution you'd like

Add message in Podman and Kind

**Comment by mairin** [comment]
Would be good to use this area for displaying a warning if we cannot contact network for extensions that require network access including:
- Kind (https://github.com/containers/podman-desktop/issues/2794)
- OpenShift Local
- DevSandbox
