### ISSUE TITLE
Implement UI test for the running application covering pull image scenario

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#2848]
### Is your enhancement related to a problem? Please describe

As a part of extending e2e tests, I would like to add test coverage for the pulling image feature.
Related issue: https://github.com/containers/podman-desktop/issues/1474

### Describe the solution you'd like

Test cover pulling image and checking whether it was successful in the running application.

**Comment by xbabalov** [comment]
I created PR for this issue https://github.com/containers/podman-desktop/pull/3008

**Comment by odockal** [comment]
Merged. thx.
