### ISSUE TITLE
typo: Home Page of Podman Desktop

### ISSUE THREAD

**Issue by deekay2310** [containers/podman-desktop#285]
On the Home page, it says "Joing the Podman Community" instead of "Join the Podman Community" 
<img width="904" alt="Screen Shot 2022-07-12 at 9 46 56 PM" src="https://user-images.githubusercontent.com/29257773/178635893-74fcd68b-8b39-4427-95f5-5a187455c417.png">

**Comment by benoitf** [comment]
already fixed by https://github.com/containers/podman-desktop/pull/267
