### ISSUE TITLE
Impossible to edit the URL of a registry

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#286]
### Bug description

After adding a custom registry, it's not possible to edit the name.

### Operating system

mac OS

### Version

next (development version)

### Steps to reproduce

1. add a registry
2. go on the list of registries and click on the edit button on one of them
3. try to edit the name

--> not possible, while the username/password are editable

**Comment by benoitf** [comment]
It's by design. URL is read-only

**Comment by deekay2310** [comment]
I was facing the same issue today. Wondering if it should be kept read-only or not (in terms of UX).

**Comment by deboer-tim** [comment]
I just hit the same problem. The text field for URL looks identical to the text field for user/password, so I assumed I could edit it.

Although I can see why it might be designed as read-only, I made a typo in mine and would have been nice to fix it.
