### ISSUE TITLE
When installing an extension that has an undefined displayName the extensions section gets broken 

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#2871]
### Bug description

If an extension does not have a display name the extensions section is broken.
 
![extension-tree-broken](https://github.com/containers/podman-desktop/assets/49404737/eb0c4973-ce67-48bd-8f0b-abca6edb29d2)

It fails at 

```
export async function fetchExtensions() {
  const result = await window.listExtensions();
  result.sort((a, b) => a.displayName.localeCompare(b.displayName));
  extensionInfos.set(result);
}
```

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. install quay.io/lstocchi/sample-podman-extension:v1
2. check that your extensions section is broken

**Comment by benoitf** [comment]
maybe we should prevent the loading of the extension (or the installation)

**Comment by deboer-tim** [comment]
I was just going to give extensions a default name like "Unknown", and maybe a description too b/c the UI looks odd. But yes, we could refuse to install extensions unless they have a default set of configuration. Maybe name/displayName/description/version/publisher?

**Comment by lstocchi** [comment]
Yeah better, another problem was that i could not stop/remove the extension. And i guess it was due to another missing property.

**Comment by benoitf** [comment]
yes, let's avoid any unexpected behaviour. Fail fast (no load or install)

**Comment by benoitf** [comment]
created also https://github.com/containers/podman-desktop/issues/2880

**Comment by deboer-tim** [comment]
Stopping extension install when there are missing attributes: easy, 1 min. UI gives no feedback if the install fails: may take slightly longer. :)
