### ISSUE TITLE
The Help screen does not the option to "x" out of it

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#2878]
### Bug description

After clicking on the help option in the bottom right I was able to view the information however I was not presented with the option to close it out.  I had to make another selection to remove it from view rather than x'ing it out.

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

**Comment by jannikbertram** [comment]
I would like to work on this and already submitted a PR :)
