### ISSUE TITLE
Provide a UI that allows a user to connect to a remote kubernetes cluster

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2888]
### Is your feature request related to a problem? Please describe

Users have been reporting that they would like to be able to configure the connection to a remote kubernetes cluster directly from the UI of Podman Desktop

### Describe the solution you'd like

Build a dedicated UI, in the settings that allows the user to easily manage connections to kubernetes clusters, add them and remove them.

**Comment by jeffmaury** [comment]
We need to understand which provider and authentication mecanisms we need to support here as it's a wide open area
