### ISSUE TITLE
Background help for image coordinates and registry URLs

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#291]
### Is your enhancement related to a problem? Please describe

Every time I add a registry I wonder if the Server URL should be an actual URL or if just the hostname will work.
If I'm less familiar with pulling images I might struggle to remember the format.

### Describe the solution you'd like

Desktop should provide hints for fields like these. My preference would be to have greyed out text with samples or suggestions that disappear when you start typing.

For example, registry server URL field might initially contain "docker.io" and pull image field might say "e.g. docker.io/redhat/ubi8-micro".

Longer tooltips would be nice too.

### Describe alternatives you've considered

We could include longer descriptions in the UI, but I think that makes the UI less pretty, and cumbersome once you know what you're doing.

**Comment by benoitf** [comment]
I think it's addressed by pre-filled registries, closing
