### ISSUE TITLE
Pods view shows No Container Engine beside Kubernetes pods

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2923]
### Bug description

When viewing Pods with no container engine, but Kubernetes setup, there is "No Container Engine" that appears.

![Screenshot 2023-06-19 at 9 28 46 AM](https://github.com/containers/podman-desktop/assets/6422176/30bad5ab-9af5-46f5-b5f8-744c47ee0651)

### Operating system

M1

### Installation Method

None

### Version

1.1.0

### Steps to reproduce

1. Remove your Podman machine / docker / make sure you have no container engine
2. View Pods with a valid Kubernetes connection
3. Will show "No Container Engine".

**Comment by afbjorklund** [comment]
Probably same as #2800, it should not show "no container engine" when it has containerd

(main difference would be that the containers and images from Kubernetes are missing)

**Comment by benoitf** [comment]
closing as a dup of https://github.com/containers/podman-desktop/issues/2421
