### ISSUE TITLE
Fo

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2924]
### Is your enhancement related to a problem? Please describe

When you create a Podman machine with root privileges, you expect that it will be permanent. But it is not the case. It is not a property of the podman machine, but of the default connection. And the default connection can be changed at any moment. Example: https://github.com/containers/podman-desktop/issues/2582. It would make much more sense to have the option available when starting the machine, rather than when creating the machine.

Moreover, having the option in the "Create a Podman machine" screen is leading users to have a wrong behavior: rather than using one single Podman machine, and switch the default connection back and forth, it *seems* smarter to create one Podman machine for each type of workloads. Podman Desktop is proposing the connection switch anyway, but the rootful machine will become rootless after the first iteration of changes.

### Describe the solution you'd like

1. Remove the option from the "Create a Podman machine" screen.

2. Add a new option to start a machine: "Start", "Start with root privileges"

Clicking the "Start" option would:
1. Set the default connection to the Podman machine in rootless mode.
2. Start the Podman machine.

Clicking the "Start with root privileges" option would:
1. Set the default connection to the Podman machine in rootful mode.
2. Start the Podman machine.

### Describe alternatives you've considered

1. Remove the option from the "Create a Podman machine" screen.
2. Add a **Root privileges** enabled/disabled slider next to the start icon.

**Comment by benoitf** [comment]
State is when you create and then you're able to toggle this state (running or not) (not yet exposed as there is a missing contribution in podman to notify the current state)

There are other issues already discussing that, closing this one
