### ISSUE TITLE
Podman Desktop should use the default system connection when connecting to a Podman machine

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#2925]
### Bug description

When you change the default system connection, Podman CLI uses it, but Podman Desktop continues to use the connection it used before. Therefore, you don't see the images and containers that you would expect.

### Operating system

Windows 11 Pro

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Start a new Podman machine in rootless mode.
2. Pull an image, such as `nginx`.
3. Start a container.
4. Set the connection to rootful `podman.exe system connection default podman-machine-default-root`
5. Restart the Podman machine.
6. Install Kind
7. Go to Images: you expect to see the Kind image, but you see only the image you pulled in the rootless machine.
8. Go to Containers: you expect to see the kind container, but you see only the container you created in the rootless machine.
9. Podman CLI behavior is correct: You can see the kind image:
  
    ```
    $ podman.exe image list
    REPOSITORY              TAG         IMAGE ID      CREATED      SIZE
    docker.io/kindest/node  <none>      3da3ccb2a738  5 weeks ago  931 MB
    ```
10. Stop and start Podman Desktop
11. Iter on 7, 8, 9.

**Comment by benoitf** [comment]
AFAIK @cdrage implemented something that notifies you that you're bypassing socket and then podman connection should be reverted.

Podman Desktop connects to the host socket. There is only one host socket (bound to rootless or rootful)
You've to chnage the configuration of your machine. (Dialog box should be issued in your case)

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/issues/2096
