### ISSUE TITLE
Really slow launching on Windows

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#293]
### Bug description

When I launch Desktop on my Windows machine there is a ~14s delay until the window appears, even if I've just exited it. By this time I'm already second-guessing whether I really clicked on it or if the mouse is working.

The original podman install partially failed, so I'm guessing a bunch of this time is being spent confirming that podman is installed but not reachable (socket timeout?). Although I'd love to reduce the time it takes to do this, I'm opening this bug specifically to request that it's done in the background - i.e. I should see Podman Desktop as soon as physically possible, then the checking can be done in the background. It's ok if we need to show a 'loading' screen or some kind of splash screen in the meantime, it's the delay before anything appears that's most concerning.

### Operating system

Windows 10 Home (21H2)

### Version

0.0.5

### Steps to reproduce

Happens every time I launch Desktop.

### Additional context

The machine isn't the latest, but it's no slouch either: i5-10400, 16Gb RAM, 1Tb SSD. For comparison, here are launch times for some other applications on the same machine:

- Epic Games: first screen appears in 2s, done loading in 4s.
- Steam: first screen appears in 1s, loaded in 4s. Quit and reloads next time in 1s.
- Chrome: 2s.

**Comment by deboer-tim** [comment]
I noticed a couple times I had forgotten to exit Desktop when testing this; the system tray was still running. In these cases I can open the dashboard in 1s, but clicking on the executable takes 15s to get to the same place - i.e. same as if I had completely quit. I assume this is a separate problem (and maybe an Electron behaviour?), but if Desktop is already running then ideally we'd just trigger opening the dashboard instead of starting from scratch.

**Comment by benoitf** [comment]
Hi @deboer-tim it’s slow as the exe is unpacking the content to a temporary directory 'each time' (it's how the portable exe is done by electron-builder)

If you use the setup / https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5-setup.exe file you should have a faster experience as basically all the files are already extracted to a given directory during the install.

**Comment by hansmbakker** [comment]
Assuming the podman-desktop developers prefer web technology to build this app - would it be an idea to look into React-Native to make it faster than using Electron?

**Comment by benoitf** [comment]
I'm not sure it would be faster. Also electron is bringing ecosystem tooling

**Comment by deboer-tim** [comment]
Normal installs avoid this issue, so closing.
