### ISSUE TITLE
Design update for task flow screens

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2936]
The "task flow" screens (I made this word up, but it's basically the forms you get when you do a select+action, like the podify or deploy to k8s screens) aren't all consistent and also don't have a common component to help with stuff like alignment/responsiveness/etc. 

So for this issue, we need some solid UI mockups to show how these screens should generically work so a common component could be created. That should make it easier to create new additional such screens or update the existing ones without worrying about consistency / breakage (hopefully.)

## examples

![Image](https://user-images.githubusercontent.com/799683/247140069-d96c8fa4-9bc4-4756-8ce8-d4f019226454.png)
![Image](https://user-images.githubusercontent.com/799683/247140068-e1b294af-df1f-44ad-9c15-952602638bad.png)

**Comment by deboer-tim** [comment]
Keeping this one open.
