### ISSUE TITLE
Not possible to completely delete pods from the containers list

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2954]
### Bug description

When deleting pods (selecting the "pod grouping item" from the containers list, all containers of the pod are not properly deleted and it remains "infra" container `podman-pause`. It even raises an error.

<img width="1500" alt="Capture d’écran 2023-06-22 à 09 53 27" src="https://github.com/containers/podman-desktop/assets/1636769/1826d512-65c5-415c-862d-f79218e723f1">

The other containers are eventually deleted, but then the pods are still remaining:
<img width="1249" alt="Capture d’écran 2023-06-22 à 10 06 55" src="https://github.com/containers/podman-desktop/assets/1636769/4ab8033b-0b76-48c9-abc0-3e801360ea58">

### Operating system

macOS Ventura 13.4

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

### Steps to reproduce

- Run the preload.sh script from https://github.com/redhat-developer/podman-desktop-demo/tree/main/primary-podify-demo 
- Stop the pods
- Try to delete them

**Comment by benoitf** [comment]
not sure why it's flagged as a bug.
You need to delete the pod (pod view or on the pod line), not the container

**Comment by benoitf** [comment]
won't fix

**Comment by slemeur** [comment]
That's what I've tried to do, I've selected the "pod line" and hit the button delete. The pod and all its containers was not properly deleted.

**Comment by slemeur** [comment]
https://github.com/containers/podman-desktop/assets/1636769/48b07de8-93d2-461f-b75b-0b988abf8c6c

**Comment by slemeur** [comment]
Then, if I go to the list of pods, I then have the pod, displaying that there 3 containers in my pod, while 2 of them have been deleted.

Going to the list of pods, deleting the pod, works from there, but not from the list of containers - despite having choose the "pod grouping item" from the list.

https://github.com/containers/podman-desktop/assets/1636769/40ad78d0-8712-4303-a7e2-7ddb502541bc

**Comment by benoitf** [comment]
I think you're not using an up-to-date version
it was already fixed by https://github.com/containers/podman-desktop/issues/2413

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/assets/436777/fde502da-76db-438b-b64d-42884b99beef

**Comment by slemeur** [comment]
Not the same issue than #2413 
I can reproduce the issue with 1.2.0-next

https://github.com/containers/podman-desktop/assets/1636769/9bdbf2a8-c13f-4192-9d8d-041cf05cc53e

I'm not using the button you are using in the list, but the "bulk delete", next to the search bar.
