### ISSUE TITLE
Incompatible node version

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#2955]
### Bug description

In the package.json the minimum node engine version is set to 16.13 `"node": ">=v16.13",` but it should be `">= 18"`.
If you use an older version you get this incompatible error
```
error @octokit/graphql@6.0.1: The engine "node" is incompatible with this module. Expected version ">= 18".
error Found incompatible module.
```

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
yes, correct we require Node.js 18+ (as the one used by Electron)
should fix the package.json property

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/2989
