### ISSUE TITLE
Actions for selected containers

### ISSUE THREAD

**Issue by shinjiikari256** [containers/podman-desktop#2982]
### Is your enhancement related to a problem? Please describe

It doesn't seem very convenient to me that you can't start and stop multiple containers.

### Describe the solution you'd like

1. Adding a start/stop button to a line of actions for the selected.
2. Adding actions for a groups.
![image](https://github.com/containers/podman-desktop/assets/39000784/4e53b4a6-e325-4e26-a34b-de85784fae98)``

**Comment by cedricclyburn** [comment]
+1 would also like this feature, will start looking into the feasibility next week
