### ISSUE TITLE
DockerHub incompatibility

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman-desktop#2991]
### Bug description

From: https://twitter.com/dengolius/status/1672185541125718018

[Denys Holius ](https://twitter.com/dengolius)🇺🇦
[@dengolius](https://twitter.com/dengolius)
facepalm #1
Podman desktop can't login to dockerhub, because dockerhub works now via token and not via password. But podman desktop can't recognized it and just say that there is an issue with my credentials...WHAT?!

### Operating system

unknown

### Installation Method

None

### Version

1.1.0

### Steps to reproduce

unknown, asking in Twitter

### Relevant log output

```shell
unknown, asking in Twitter
```

### Additional context

unknown, asking in Twitter

**Comment by cdrage** [comment]
@denisgolius

Created the token, logged in successfully and I also able to pull an image. I'm unable to replicate? Could it be that 2-factor authentication is enabled too / blocking it?

Let me know if you can recreate this on the latest release of Podman Desktop

https://github.com/containers/podman-desktop/assets/6422176/5b995f29-f3be-4cfc-9d04-2a0569a7503c

**Comment by cdrage** [comment]
(Ive also replied on twitter)

**Comment by cdrage** [comment]
I'm going to temporarily remove this from the sprint planning / backlog as we haven't received a reply / unreproducible.

**Comment by slemeur** [comment]
Let's close the issue as we have not been able to reproduce the error.

**Comment by slemeur** [comment]
It can be reopened anytime in case new information are provided
