### ISSUE TITLE
Allow usage of Touch ID for admin actions on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2998]
### Is your enhancement related to a problem? Please describe

Today, I'm asked for a password when requiring admin privileges but I have Touch ID so I would expect to have Podman Desktop working with my Touch ID

### Describe the solution you'd like

It looks like that when using sudo, we can tune some pam modules

```
Edit /etc/pam.d/sudo
Add a new line under line 1 (which is a comment) containing:
auth       sufficient     pam_tid.so
```

but I don't like that as it's a user action

It looks like we should use `osascript` instead of `sudo` on macOS

example:  

```shell
osascript -e 'do shell script "echo podman" with prompt "Podman Desktop requires admin privileges " with administrator privileges'
````
 will provide something like 
![image](https://github.com/containers/podman-desktop/assets/436777/f08115bd-d211-43ad-bddd-286d7b3a7056)

where I can use Touch ID or my password

**Comment by ravicious** [comment]
Did you have to set up anything extra for osascript to allow Touch ID? I swear that [in our app it used to just work](https://github.com/gravitational/teleport/blob/f211d78134a563eadf18f346db788207b6171024/web/packages/teleterm/src/mainProcess/mainProcess.ts#L279) and your screenshot clearly shows that osascript did accept Touch ID.

However, now I'm working on another feature which utilizes osascript and I found that it no longer allows me to use Touch ID. I found a couple of posts mentioning [modifying `/etc/pam.d/sudo`](https://apple.stackexchange.com/questions/327025/touch-id-when-wants-to-make-changes). Perhaps the macOS update to Sonoma changed this?

* https://stackoverflow.com/questions/77247149/script-editor-no-longer-asks-for-touchid-when-running-apple-script-with-admin-pr
* https://derflounder.wordpress.com/2023/10/14/enabling-touch-id-authentication-for-sudo-on-macos-sonoma/
* https://old.reddit.com/r/MacOS/comments/168wxx8/in_amphetamine_when_always_starting_or_stopping/k500xn4/

**Comment by benoitf** [comment]
@ravicious I think it's no longer working since macOS sonoma
