### ISSUE TITLE
Display container engine(s) status in system tray

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3]
## Description ##
As a user, I should be able to easily get access to the status of my container engines from the system tray.

## Acceptance criteria ##

- When no container engines are installed/configured, a message is displayed in the system tray's menu
- When the user clicks on the system tray, for each detected container engines (and their VMs) there is an entry in the menu. An icon is showing the state of the VM, if it's running or not.

**Comment by rhatdan** [comment]
This should be displaying the status of the VM being used for container engines.

**Comment by gbraad** [comment]
I suggested @evidolob to have a look at this from CRC's perspective.

For us it is used to display the state of the VM + enablement; in case of Podman this is the VM started and the socket activation for the API is in place. For OCP this would be the VM state + cluster API alive.
