### ISSUE TITLE
Impossible to access old image build failure

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3026]
### Bug description

There is a "View" error button that does not work properly
![view-error-build](https://github.com/containers/podman-desktop/assets/1636769/6fd5eec3-65a9-4f8c-9df8-fcabd22359bf)

### Operating system

Ventura 13.4

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Build an image with a failure
- Build another image
- Open the list of tasks
- See the error for the previously failed image build
-> try to access the error logs

**Comment by deboer-tim** [comment]
It looks like it's not showing the error because we don't record any error in the task object.
