### ISSUE TITLE
Podman Desktop - macOS Installer

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#303]
### Epic domain

All Podman Desktop issues relating to the macOS installer will be linked to this epic

### Additional context

###Subtasks

- [x] #187 
- [x] https://github.com/containers/podman/issues/14738
- [x] https://github.com/containers/podman-desktop/issues/370
_No response_

**Comment by slemeur** [comment]
Closing as completed
The website improvement will be done separately
