### ISSUE TITLE
Grey background on Kubernetes deploy section

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3032]
### Bug description

![Screenshot 2023-06-27 at 2 15 08 PM](https://github.com/containers/podman-desktop/assets/6422176/719a882f-255f-420e-9e56-84c76e564372)

vs.

![Screenshot 2023-06-27 at 2 15 14 PM](https://github.com/containers/podman-desktop/assets/6422176/11d30a8b-595b-4fac-93ea-3d63a477e506)

See above, there is an odd grey background compared to the "Play Pods" design choice 

### Operating system

Mac M1

### Installation Method

None

### Version

1.1.0

**Comment by deboer-tim** [comment]
The top one is the correct/newer design. In the sprint that's just ending I created a FormPage component to get some consistency and make it easier to roll out to other pages, and added the breadcrumb/close button.

I can roll this out to the other pages in the coming sprint, which will make the header and background color match. Note that there are further differences between these pages and the others (e.g. slight color differences, font size, button size, ...) that'll require more work.

**Comment by deboer-tim** [comment]
Main problems fixed via PRs #2977 and #3162.
