### ISSUE TITLE
Kube event error on switch kube contexts

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3035]
### Bug description

I am seeing errors in dev console when switching among for example, kind, crc-admin and sandbox contexts. Although these do not seem to influence the functionality, are they expected?

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Relevant log output

```shell
main ↪️ Kube event error Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)
console.<computed> @ index.ts:1395
(anonymous) @ index.ts:1395
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

**Comment by jeffmaury** [comment]
Each time a current context is detected, if the cluster can be reached, a waiting request is sent to the cluster to listen for changes on pods. So each time the current context is changed, this request is cancelled and generates this error message. This can be ignored.

**Comment by deboer-tim** [comment]
Can we catch and avoid logging the error, or output a friendlier message instead? It seems likely someone else will see it and open a similar bug in the future.

**Comment by jeffmaury** [comment]
Maybe we can record that we asked for cancellation and not trace the error in that case
