### ISSUE TITLE
DOCKER_HOST env var not being set

### ISSUE THREAD

**Issue by mlanner** [containers/podman-desktop#3036]
### Bug description

When setting up Podman Desktop I get the little exclamation point for "Compose". Hovering over it provides a message "/var/run/docker.sock is not enabled. Need to use wrapper script." Then, clicking on it provides the following message:

Please add the compose wrapper bin folder to your PATH environment variable. Value is $HOME/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin. The script $HOME/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/compose will setup for you the DOCKER_HOST environment variable.

If I run `$HOME/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/compose`, it just runs the compose output and all its options. It doesn't actually set the DOCKER_HOST env var like the message suggests it will. I've looked in my env vars and it's not there.

### Operating system

Linux (Fedora 38)

### Installation Method

Flathub (Linux)

### Version

1.1.0

### Steps to reproduce

See above.

### Additional context

Also, with the Flatpak installation, setting the path ` $HOME/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin` does nothing. I guess it's because of the containment that Flatpak itself mandates?

**Comment by benoitf** [comment]
hello @mlanner thank you for your feedback

I think there is no DOCKER_HOST set as compatibility mode is enabled (so it means Podman is listening as docker socket path)

Anyway we're trying to revisit the compose support to make it more user friendly/ understandable/usable.

**Comment by mlanner** [comment]
Thanks for the clarification @benoitf. Yes, indeed it is confusing. Perhaps if certain configs are set, it would be best to have a config page that shows the config and maybe some checks to verify the setup? With the current "indicators" it does give you the impression that things are not set up properly.
