### ISSUE TITLE
Improve pulling of amd64 images on M1 machines

### ISSUE THREAD

**Issue by cfergeau** [containers/podman-desktop#3046]
### Is your enhancement related to a problem? Please describe

https://quay.io/repository/jpacker/nodejs-pacman-app?tab=tags has only an amd64 image, if I pull this image from Podman Desktop UI, it works fine, no warning, ... and then I can create a container from it.

On the other hand, https://quay.io/repository/powercloud/nodejs-pacman-app?tab=tags has a manifest with an amd64 image and a ppc64le image. If I try to pull this image with Podman Desktop UI, I get an error, and no obvious way to use the amd64 image.

### Describe the solution you'd like

Fallback to the amd64 image even when there is a manifest ?
Ask/warn in both cases that an amd64 image is going to be used?

No strong opinion on the exact behaviour, but I'd expect a consistent behaviour between the 2 cases, especially as the concept of manifests is a technical detail, not visible in Podman Desktop UI.

### Additional context

podman has the same behaviour on the cmdline for docker compat, I've also asked for consistent behaviour in the past, but was told they could not because of docker compat, and old images.

**Comment by benoitf** [comment]
We can do things:

- after user enters image in the search field (say if image exists, which tags are there, arches, etc)
pro: early feedback, user can see the arches of the image, if image exists as long as he types the image name, etc.
cons: lot of queries (might be cases where we are unable to to the queries while the engine has different auth stuff)

- before delegating to the engine when clicking on "pull image" and notify the user
pros: user is prompted first
cons: might slow done the hit on 'pull images'

- after delegating to the engine and analyzing error and have a retry step
pros: lazy check so we check only in case of errors
cons: need a retry option so might be painful from user experience


cc @mairin if you think one workflow is better
