### ISSUE TITLE
Default podman-machine creation (rootful, 2CPUs, 4GB RAM)

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#3047]
Rootful required because of Kind on WSL2
2CPUS because 1 seems not enough depending of the workloads
4GB required as 2GB may cause errors if running a Kind cluster

Make sure the same default are also contributed to podman-machine.

**Comment by afbjorklund** [comment]
The issue seems a bit low on reasons behind the change?

**Comment by afbjorklund** [comment]
These are the defaults for the Lima instances:
- 4 cpus
- 4 GiB memory
- 100 GiB disk
- rootless

`limactl start template://podman`

It doesn't support Windows (yet), and not WSL.

----

https://podman-desktop.io/docs/Installation/creating-a-lima-instance-with-podman-desktop

`limactl start --set='.cpus = 2 | .memory = "4GB"' --name=podman template://podman-rootful`

**Comment by benoitf** [comment]
hello @afbjorklund 
I would say the background/reasoning is the following:

1. Tuning cpu/memory/disk should be something that can be changed in the UI (for now it's only at creation time but podman machine allow to resize values after a restart of the machine)

2.  default are sometimes too low as people may want to start a kind/minikube cluster and of course 1CPU and 2GiB is too low to have good performance

3. Improve monitoring/reporting in the UI of the usage of cpu/memory/disk on the VMs. So user can clearly see if his machine is running out of something.

4. rootful/rootless: on macOS/Windows you have a VM and for example on Windows kind is not working well with rootless mode. So idea is to change default to rootful so 'first experience' would be that it works. But defaults are defaults so toggle would be there, people can change it.

HTH

**Comment by afbjorklund** [comment]
I think that both rootless and daemonless is what people has come to expect from Podman, so it is a _little_ strange that Podman Desktop would default to run as root and to "ping" the service...*

But thanks for explaining the choices considered.

----

\* did exactly this (run a daemon as root) for `podman-machine`, because it was matching `docker-machine` and because the OS didn't have systemd to run the rootless containers with

https://github.com/boot2podman/machine

**Comment by afbjorklund** [comment]
Monitoring is something that is missing from Lima today, but it's in the backlog.

* https://github.com/lima-vm/lima/issues/835

**Comment by afbjorklund** [comment]
The values are still slightly "off", due to the unit errors in the params:

* #3062

![podman-machine-before](https://github.com/containers/podman-desktop/assets/10364051/ee8cefe9-3007-48ff-9c49-16c2668aab3f)

```
NAME                    VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        2 minutes ago  2 minutes ago  2           4.194GB     10.74GB
```

**Comment by jeffmaury** [comment]
> The values are still slightly "off", due to the unit errors in the params:
> 
>     * [Size units wrongly processed #3062](https://github.com/containers/podman-desktop/issues/3062)
> 
> 
> ![podman-machine-before](https://user-images.githubusercontent.com/10364051/251219009-ee8cefe9-3007-48ff-9c49-16c2668aab3f.png)
> 
> ```
> NAME                    VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
> podman-machine-default  qemu        2 minutes ago  2 minutes ago  2           4.194GB     10.74GB
> ```

But that's on Podman size of `podman init` expect MB (for memory)(At least on my Windows workstation)

**Comment by afbjorklund** [comment]
> But that's on Podman size of `podman init` expect MB (for memory)(At least on my Windows workstation)

It expects to receive MiB, it just spells it as "MB" according to the older standard. Ditto with disk, GiB vs "GB".

https://github.com/containers/podman-desktop/issues/3062#issuecomment-1613563653

So you are expected to send in params in one unit, and then list the results in another unit.

Even though both of them have the _same_ spelling in the documentation and in the header:

`podman machine init --help`

```
      --disk-size uint         Disk size in GB (default 100)
  -m, --memory uint            Memory in MB (default 2048)
```

`podman machine init`
`podman machine list`

```
NAME                    VM TYPE     CREATED         LAST UP         CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        27 seconds ago  27 seconds ago  1           2.147GB     107.4GB
```

**Comment by jeffmaury** [comment]
Reopening then to change the default values and display as GiB

**Comment by afbjorklund** [comment]
I thought there was a different issue to fix the units ? It's OK to have decimal, as long as it is consistent 

* https://github.com/containers/podman-desktop/issues/3062

**Comment by afbjorklund** [comment]
> Reopening then to change the default values and display as GiB

Made a PR for podman, to do the same: https://github.com/containers/podman/pull/19146

**Comment by afbjorklund** [comment]
This breaks the older podman versions: (v3)

`Error: unknown flag: --rootful`

**Comment by afbjorklund** [comment]
@jeffmaury : did you change your mind, regarding the units?

i.e. to switch from the "GB" (1000-based) to the "GiB" (1024-based)

![pd-podman-machine-linux](https://github.com/containers/podman-desktop/assets/10364051/a41b62bd-c7ad-45db-b866-fe29b485edc8)

To get more even numbers, with the default podman machine...

**Comment by cdrage** [comment]
Re-opening this as there is more activity / we should have a discussion again regarding the disk / memory size being different than podman machine.

**Comment by benoitf** [comment]
it needs to be a separate issue. 
Original issue is about incrementing the default

**Comment by afbjorklund** [comment]
We only fixed the calculation (from GB to bytes), we didn't change the actual units used.

* https://github.com/containers/podman-desktop/issues/3062
