### ISSUE TITLE
Warning message is red not yellow

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3049]
### Is your enhancement related to a problem? Please describe

When implementing a new feature, I used WarningMessage.svelte

But it's a bit confusing as it's red text, but with a triangle exclamation. So it at first glance it leads me to think it's an error unless I explicitly look at the icon. 

### Describe the solution you'd like

Shouldn't it be yellow?

https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/ui/WarningMessage.svelte#L18

### Additional context

Screenshot:

![Screenshot 2023-06-28 at 11 58 59 AM](https://github.com/containers/podman-desktop/assets/6422176/905ac270-ce5a-430c-ae9a-c30446fe9028)

**Comment by benoitf** [comment]
cc @mairin

**Comment by mairin** [comment]
Yep! It should be amber-500. I'd also recommend align-top for the col the icon is in!

**Comment by deboer-tim** [comment]
Fixed by #3153.
