### ISSUE TITLE
Can't start podman

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#305]
### Bug description

Had Podman installed but not WSL distributions.
Desktop told me that podman is not started but when asked to start it it never completes

### Operating system

Win10 Pro

### Version

next (development version)

**Comment by benoitf** [comment]
Hello @jeffmaury what is your podman version ?

it requires podman 4+ (with local mounted socket)

**Comment by jeffmaury** [comment]
![image](https://user-images.githubusercontent.com/695993/179506101-9142f4d7-9dd5-4998-8e95-ef18b6b6c4a4.png)

**Comment by benoitf** [comment]
Hello, can you try with a command line:

```
$ podman machine start
```

**Comment by jeffmaury** [comment]
```
Starting machine "podman-machine-default"
Il n’existe aucune distribution avec le nom fourni.
Error: WSL bootstrap script failed: exit status 0xffffffff
```

**Comment by benoitf** [comment]
could you try:

```
podman machine rm
podman machine init
podman machine start
```

**Comment by jeffmaury** [comment]
I ran:
```
podman machine rm
podman machine init
```

But if I try to start from desktop I have this error now:
![image](https://user-images.githubusercontent.com/695993/179516120-ed0257e9-3f8d-4014-a6be-c47c6734f5dd.png)

**Comment by deekay2310** [comment]
@jeffmaury not sure if it could be of any help, but check [this](https://podman-desktop.io/docs/troubleshooting#fixing-corrupted-podman-machine-in-windows) out.
