### ISSUE TITLE
How to handle user-mode networking for Podman machine/WSL2

### ISSUE THREAD

**Issue by gbraad** [containers/podman-desktop#3052]
For podman machhine using WSL2 it is possible to set user-mode networking, however this is something that happens during the machine's creation phase (`podman machine init`). Therefore this has to be a question during the installation phase, or the user has to delete/recreate when this is a configuration option from the Podman Desktop settings.

Ideally, this should be something that can be set on `podman machine start` instead. For this I created: https://github.com/containers/podman/issues/19022

This issue is to track and discuss the needed changes to the Podman Desktop flow.

Note: version check is necessary, as this is not available for older versions of `podman machine`.

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/2865

**Comment by gbraad** [comment]
Since https://github.com/containers/podman/commit/230ddbe0caf6f2ad7d88346b0f862bb17f011a30 is only expected in the Podman 4.6 timeframe (according to https://github.com/containers/podman/issues/19022#issuecomment-1612950560), this should probably not be implemented now.
