### ISSUE TITLE
Prompt to change default machine doesn't work for rootful machines

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3065]
### Bug description

If the podman machine is rootful, we prompt and connect the cli to `<machine>`, but it should be `<machine>-root`. As a result anything done via the cli (like following our empty-screen prompts, which is what I blindly did...) does not appear in the UI.

Using `podman system connection default <machine>-root` fixed the problem, but since that I have not been prompted to fix the problem again when switching machines. Results in "Error: failed to connect: dial tcp 127.0.0.1:54041: connect: connection refused" when using the command line. Not sure if it is related.

Future thought: if the user declines the prompt once, there is no way to get it back/do the action later. We should likely have a warning somewhere (e.g. Resources or Dashboard) where you can trigger the change.

### Operating system

macOS 13.3 M1

### Installation Method

None

### Version

next (development version)

**Comment by jeffmaury** [comment]
Dup of #2582

**Comment by lstocchi** [comment]
Closing. This is fixed by https://github.com/containers/podman-desktop/pull/3364
