### ISSUE TITLE
Browser/URL links not opening or even calling the browser

### ISSUE THREAD

**Issue by rh-jelabarre** [containers/podman-desktop#3073]
### Bug description

Downloaded the podman-desktop-1.1.0.tar.gz package from this site, and extracted it to a local directory in my Home directory.

In trying to open any of the external URL links in the application, the great majority of the links (such as any in the Help section) respond at all.  They do not load the web page or even make a call to the browser (the browser never moves to the foreground as if it had received a call to open anything).
Under the "OpenShift Local" section the five links ('Website', 'Installation Guide', etc) will pop up a message to copy link or open the site, but the sites won't open from there either.  It does copy valid URLs if you select the 'copy link' button.

Running Fedora 38, Cinnamon Desktop, Firefox 108.0.1 browser.

### Operating system

Linux (Fedora 38)

### Installation Method

Other

### Version

1.1.0

### Steps to reproduce

1. Download podman-desktop-1.1.0.tar.gz
2. extract to subdirectory under Home directory
3. change directory to podman-desktop-1.1.0
4. run ./podman-desktop to start application
5. click on any external link

### Relevant log output

```shell
[jlabarre@p50-jlabarre podman-desktop-1.1.0]$ ./podman-desktop 

(podman-desktop:4162511): Gtk-WARNING **: 12:01:19.810: Theme parsing error: gtk.css:8:11: Expected a valid selector
Kubeconfig path /home/jlabarre/.kube/config provided does not exist. Skipping.
System ready. Loading extensions...
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Activating extension (podman-desktop.compose)
Activation extension (podman-desktop.compose) ended
Activating extension (podman-desktop.docker)
Activation extension (podman-desktop.docker) ended
Activating extension (podman-desktop.kind)
Activating extension (podman-desktop.kube-context)
[kube-context] starting extension kube-context
Activation extension (podman-desktop.kube-context) ended
Activating extension (podman-desktop.lima)
[lima] Could not find podman socket at /home/jlabarre/.lima/podman/sock/podman.sock
Activation extension (podman-desktop.lima) ended
Activating extension (podman-desktop.podman)
Activating extension (podman-desktop.registries)
[kind] kind extension is active
Activation extension (podman-desktop.kind) ended
[podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
Activation extension (podman-desktop.registries) ended
Fetched https://registry.podman-desktop.io/api/extensions.json in 272.1015958786011ms
Activation extension (podman-desktop.podman) ended
Activating extension (redhat.redhat-sandbox)
[redhat-sandbox] starting extension openshift-sandbox
[redhat-sandbox] Configfile location /home/jlabarre/.kube/config
Activation extension (redhat.redhat-sandbox) ended
Activating extension (redhat.openshift-local)
Activation extension (redhat.openshift-local) ended
PluginSystem: initialization done.
Autostarting container engine
PluginSystem: received dom-ready event from the UI
Delayed startup, flushing 39 events
[kind] kind extension is active
[kind] kind extension is active
[kind] kind extension is active
[kind] kind extension is active
Fetched https://registry.podman-desktop.io/api/extensions.json in 173.0666539669037ms
Skipping update for extension redhat.redhat-sandbox because installed version 0.0.1 is greater or equal to latest available version 0.0.1
Skipping update for extension redhat.openshift-local because installed version 1.0.3 is greater or equal to latest available version 1.0.3
```

**Comment by benoitf** [comment]
It seems the code to open is using https://github.com/electron/electron/blob/499d893040b5590bf88bd7f3d4e3685d1e95a272/shell/common/platform_util_linux.cc#L332

It's using xdg-open  
Is that xdg-open is working on your side
I also found 
https://bbs.archlinux.org/viewtopic.php?id=265049

**Comment by benoitf** [comment]
hi @rh-jelabarre could you check if xdg-open works for you ?

like `xdg-open https://www.podman-desktop.io`

**Comment by rh-jelabarre** [comment]
(odd, my reply didn't make it here)

yes, xdg-open is working correctly (opens the URL into a Firefox tab)

[edit] And a recent package update seems to have fixed xdg-open.
