### ISSUE TITLE
Ability to interact with a compose group of containers

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3074]
## Goals

Provide the ability for a developer to more easily interact with a `compose` group of users. 
When a developer is interacting with a compose file, it's mainly done from the terminal, in external tools, especially an IDE. It's indeed a convenient way to start an application. 
But once an application is running and up, Podman Desktop can be used to more easily interact with the containers. 

The initial set of actions we would like to propose would be around these use cases. 

- [X] https://github.com/containers/podman-desktop/issues/3102
- [x] https://github.com/containers/podman-desktop/issues/3103
- [x] https://github.com/containers/podman-desktop/issues/3104
- [x] https://github.com/containers/podman-desktop/issues/3105
- [x] https://github.com/containers/podman-desktop/issues/3106
- [x] https://github.com/containers/podman-desktop/issues/3107
- [x] https://github.com/containers/podman-desktop/issues/3192
- [x] https://github.com/containers/podman-desktop/issues/3191

### See logs of a `compose` group of containers. 
Similarly to the ability to see the logs of a group of containers running into a pod, the goal would be to display an aggreated view of the logs of all the containers of the application running from compose. 

### Restart all containers
At the moment, from the list of containers, for a compose group of containers it's not possible to restart all the containers from a single click action. We would like to add that action.

### Stopping one container and restarting
Provide the ability to the end-user to stop only one container in a `compose` group of containers, along with the ability to restart it. 

## Out of the scope

At the moment, we'll not provide the ability to start a compose file from the ui, there will be no initial "play" of a compose file as we understand most users are not doing this from the UI. (we could obviously add that button is users are asking it).

**Comment by cdrage** [comment]
> Stopping one container and restarting
Provide the ability to the end-user to stop only one container in a compose group of containers, along with the ability to restart it.

That's already integrated as well as deleting / starting:

https://github.com/containers/podman-desktop/assets/6422176/5ef043a5-e25d-4901-a92c-e2779119e5c6

I will integrate the other requested features

**Comment by cdrage** [comment]
I've opened up separate issues to keep track of this:

- [x] https://github.com/containers/podman-desktop/issues/3102
- [x] https://github.com/containers/podman-desktop/issues/3103
- [x] https://github.com/containers/podman-desktop/issues/3104
- [x] https://github.com/containers/podman-desktop/issues/3105
- [x] https://github.com/containers/podman-desktop/issues/3106
- [x] https://github.com/containers/podman-desktop/issues/3107
- [x] https://github.com/containers/podman-desktop/issues/3192
- [x] https://github.com/containers/podman-desktop/issues/3191

**Comment by cdrage** [comment]
Closing as all tasks have now been merged & completed.
