### ISSUE TITLE
Summary shouldn't end with fullstop

### ISSUE THREAD

**Issue by razzeee** [containers/podman-desktop#3077]
### Is your enhancement related to a problem? Please describe

Summaries shouldn't end with fullstops

### Describe the solution you'd like

Remove the fullstop from https://github.com/containers/podman-desktop/blob/ab31a708ff5af373a22a9e5127668bafb58bcc67/.flatpak-appdata.xml#L7

### Describe alternatives you've considered

Not caring? :)

### Additional context

Stuff should be nice :sparkle:

**Comment by benoitf** [comment]
@razzeee it's for the display on flathub.org ?

**Comment by razzeee** [comment]
That's mostly why I open this, yes

**Comment by benoitf** [comment]
@razzeee would you mind opening a pull request ?

**Comment by razzeee** [comment]
I would prefer not to do that (I can go into reasons, but probably doesn't matter)
