### ISSUE TITLE
Podman desktop starting podman machine without interaction

### ISSUE THREAD

**Issue by ghost** [containers/podman-desktop#3092]
### Bug description

Podman Desktop is immediately restarting podman machine on my m2 mac after I explicitly stop the machine through right clicking on the tray icon and clicking stop.

The only vaguely related setting I could find is "Autostart container engine when launching Podman Desktop" But A. I am not launching Podman Desktop, it was already running which is how I was able to click start, and B. that setting is disabled anyway.

### Operating system

macOS Ventura 13.4 (arm)

### Installation Method

Brew (macOS)

### Version

1.1.0

### Steps to reproduce

As soon as I open PD, It tries to run podman, and if I stop podman, podman-desktop immediately starts podman again.

**Comment by benoitf** [comment]
hello @heksview I think it's duplicating https://github.com/containers/podman-desktop/issues/2799

it should be solved now (and in the upcoming release)

could you check with a 'nightly' release like picking up one from https://github.com/containers/podman-desktop/releases (on mac you can try a dmg)
