### ISSUE TITLE
Does wsl-vpnkit is mandatory for Podman desktop on windows to connect outside network ?

### ISSUE THREAD

**Issue by Bharath-vi** [containers/podman-desktop#3132]
### Is your enhancement related to a problem? Please describe

Do we need to use wsl-vpnkit for Podman in corporate network ?

Without wsl-vpnkit podman is not connecting with internet/quay/dockerhub.

### Describe the solution you'd like

podman should work without wsl-vpnkit

**Comment by benoitf** [comment]
hello @Bharath-vi in the upcoming Podman 4.6 there will be a new user network option
https://github.com/containers/podman/pull/18303

I think it should solve your problem
