### ISSUE TITLE
Onboarding: fresh machine - you open PD for the first time without having podman installed

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3172]
### Is your feature request related to a problem? Please describe

This issue follows the discussion we had about the onboarding. 

The first use case to work on is when the user opens PD for the first time and there is no podman/docker installed.

### Describe the solution you'd like

The user should be guided through a series of step to set up podman

**Comment by afbjorklund** [comment]
Was there a problem with the current approach, where it shows a screen and links to documentation ?

<img alt="podman-desktop-without-podman" src="https://github.com/containers/podman-desktop/assets/10364051/e584d07a-dcc8-4ce0-8707-9e2e74d96003" width="600" />

`❌ podman cli was not found in the PATH`

**Comment by lstocchi** [comment]
@afbjorklund the idea is to provide an onboarding workflow to guide the user to set up everything needed by an extension to work smoothly. Imagine having multiple steps (like a wizard) that install all tools needed by the extension and/or guide the users to set the most important options. For podman it could be 1° step check system -> 2° step install podman -> 3° step set some settings .... At the end of the onboarding the user should have PD fully set to work with it.

Even external extensions could create their own onboarding.
This is the "first" issue to implement a simple workflow for podman. Then we'll iterate on it.

**Comment by afbjorklund** [comment]
Yeah, I suppose that would be an improvement to the current wall of text (especially if you end up with no options).

https://podman.io/docs/installation#installing-on-linux

**Comment by lstocchi** [comment]
Closing, this workflow is covered
