### ISSUE TITLE
Refactor existed extensions to use the new process execution API

### ISSUE THREAD

**Issue by vzhukovs** [containers/podman-desktop#3174]
In a favour of #1585 there is a need to refactor existed codebase to use the new process execution API.

- [x] https://github.com/containers/podman-desktop/pull/3315
- [x] https://github.com/containers/podman-desktop/pull/3483
- [x] https://github.com/containers/podman-desktop/pull/3636

**Comment by afbjorklund** [comment]
Tried using the new API in the docker extension, but it failed to compile (also failing in podman extension?)

`Property 'env' does not exist on type 'typeof process'.`

**Comment by afbjorklund** [comment]
Seems like the import is shadowing the global process, making `process.env` fail. No idea how it worked for podman.

`import { process as pdprocess } from '@podman-desktop/api';`

**Comment by afbjorklund** [comment]
Also needs to be done in the minikube extension.

* ~podman~
* docker
* ~kind~
* minikube

https://github.com/containers/podman-desktop-extension-minikube

**Comment by vzhukovs** [comment]
> Tried using the new API in the docker extension, but it failed to compile (also failing in podman extension?)
> 
> `Property 'env' does not exist on type 'typeof process'.`

Hi @afbjorklund , yep, this is the same case as I had before, just need to use proper import, for example:
```
import * as extensionApi from '@podman-desktop/api';
```
and after that system process will not be shadowed by the process namespace from the extension API.

**Comment by afbjorklund** [comment]
Yeah, copied the podman code before it was "ready"

**Comment by afbjorklund** [comment]
Added the new API also to the lima extension, still todo for minikube

*  #2997

* #3748
