### ISSUE TITLE
Provide ability to configure default registry to be use

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#318]
### Is your enhancement related to a problem? Please describe

When a user has multiple registries configured, it might be helpful to allow a user to chose which one should be the default one when pulling/pushing.

### Describe the solution you'd like

In the list of Registry, we should consider having a way to select the registry which will be the default one.
Could be in the add/edit page of a registry, with a switch.

**Comment by benoitf** [comment]
Hello, are you talking about unqualified name images ?

Else all images have the registry in their names. And by convention usually the one without registry is coming from docker.io
