### ISSUE TITLE
Toggle to enable/disable proxy settings

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#319]
### Is your enhancement related to a problem? Please describe

In some case a user might switch from one network to another one (or connect, disconnect from a VPN) and in this case would like to simply disable the proxy configuration without loosing it.

### Describe the solution you'd like

It would be nice to add a toggle in the proxy settings to enable/disable the proxy configured.

**Comment by benoitf** [comment]
I think you'll need to open an enhancement in upstream Podman as the machine is keeping the proxy parameters.

**Comment by slemeur** [comment]
OK, could we also envision handling that client side? 

I can also see that, in the future some users might have multiple proxy configuration profiles

**Comment by slemeur** [comment]
https://github.com/containers/podman/issues/15005
