### ISSUE TITLE
Adding support for range port mappings

### ISSUE THREAD

**Issue by harryssuperman** [containers/podman-desktop#3204]
### Is your enhancement related to a problem? Please describe

Not a problem at all. I couldn't define in podman-desktop for a container a range port mapping.

Currently is only possible to add a single port mapping. This is possible to add multiple times but when we try in podman CLI -p 30000-32000:30000-32000 it is possible to define ranges but not in podman-desktop.

### Describe the solution you'd like

I would like, near to the current portmappings settings, the posibillity to add port mapping ranges.

### Describe alternatives you've considered

I tried also to add in the single port mapping but with the range values like 30000-32000 for the host and the container like 30000-32000 but the sintax was not working.

Maybe instead to create new fields in the settings for the container in order to support port mapping ranges, it will be helpfull if the sintax for ranges will be possible to set.

**Comment by benoitf** [comment]
hello @harryssuperman thanks for this suggestion. It could improve user experience 👍

**Comment by harryssuperman** [comment]
@benoitf as well for some other issues, i would like to apprecciate all your Team and efforts to bring us and the community the best software product. Thanks folks! ;-)

**Comment by benoitf** [comment]
thanks
