### ISSUE TITLE
Podman Stuck on Starting

### ISSUE THREAD

**Issue by jtworm96** [containers/podman-desktop#3215]
### Bug description

Using Podman 4.5.1

When trying to start my Podman machine, it just sits in the starting stage, and cannot finish starting up.

### Operating system

MacOS Ventura 13.4.1 (c) Intel Core i9

### Installation Method

Brew (macOS)

### Version

1.2.0

### Steps to reproduce

Install Podman with Homebrew
Install Podman Desktop with Homebrew
In the UI, Create a Podman machine
click the start button, and it will continue to try to start indefinitely.

**Comment by benoitf** [comment]
Hello @jtworm96 

Maybe the machine is corrupted then try to delete it.
Another issue could be that you're behind a proxy / network firewall and podman is not able to fetch the files

In that case you could the 'airgap file' of podman desktop ( from the website of podman-desktop.io)
Or try to configure proxy in Podman Desktop

**Comment by JamesWiley** [comment]
I have the same behavior with podman desktop 1.2.1 and podman 4.5.1.  on MacOS 12.6.7  I've used both brew installed versions and image download versions of podman desktop and podman with the same behavior.  "podman machine start" results in the machine getting stuck in "machine starting".  Even after a "podman machine stop" command says it executes successfully, "podman machine ls" shows that the machine is still starting.

**Comment by benoitf** [comment]
@JamesWiley hello, podman 4.6.0 has been released with a lot of fixes around machine start.

depending on your arch:
https://github.com/containers/podman/releases/download/v4.6.0/podman-installer-macos-amd64.pkg
or
https://github.com/containers/podman/releases/download/v4.6.0/podman-installer-macos-arm64.pkg

then, could you try with this new version and recreate the podman machine


`podman machine rm`
`podman machine init`


then start it
`podman machine start`

**Comment by fulldecent** [comment]
I upgraded, then did rm/init/start as advised above and it worked for me.

![Screenshot 2024-03-18 at 10 24 31](https://github.com/containers/podman-desktop/assets/382183/380de48a-3b11-4156-ab85-3ba5337693a6)

![Screenshot 2024-03-18 at 10 24 23](https://github.com/containers/podman-desktop/assets/382183/5e6feb05-2951-4b13-a6df-2e224558034d)
