### ISSUE TITLE
Un-responsiveness or slowness of the UI not triggering changes in podman-machine

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#322]
### Bug description

Sometimes it seems that the UI of Podman Desktop is not properly catching the changes in the podman-machine.
So when a user is starting a containers from the CLI, Podman Desktop needs to be refreshed so that it shows it in the list of containers.

### Operating system

mac OS, Windows

### Version

0.0.5

### Steps to reproduce

Unfortunately, no way to really reproduce it.
This happened from time to time.

I noticed it when the machine is running since long time.

**Comment by deekay2310** [comment]
Can we create an epic for slowness and unresponsive UI? I also have a fair share of issues to report regarding this. @slemeur @benoitf

**Comment by benoitf** [comment]
I think most of the missed events are related to the following issue
https://github.com/containers/podman/issues/15037

**Comment by radboudp** [comment]
For me Podman Desktop does not update the view at all unless I use the explicit Reload or Force Reload commands through the menu. It should absolutely reload automatically on changes. 

% podman version
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.3
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 15:28:20 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Built:        Fri Apr 14 17:41:12 2023
OS/Arch:      linux/arm64

Podman Desktop
Version 0.15.0 (0.15.0)

**Comment by deboer-tim** [comment]
Just dropping a note in here since this this issue was closed months ago - glad to see you've opened new issue #2560 to track this. There is a performance improvement for startup in the 1.0 release (PR #2419), but the UI should be refreshing automatically either way.
