### ISSUE TITLE
Document: Generating Kubernetes Manifest

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#3223]
### Is your feature request related to a problem? Please describe

The documentation is missing a _Generating Kubernetes manifest_ page.

### Describe the solution you'd like

Document: Generating Kubernetes Manifest

**Comment by cdrage** [comment]
Bit confused, what do you mean by manifest? The YAML?

**Comment by themr0c** [comment]
Yes, I believe "Kubernetes manifest" is the correct technical term to name the "Kubernetes YAML file".

It is widely used in Kubernetes docs.

See: https://kubernetes.io/docs/reference/glossary/?all=true#term-manifest 

> Manifest
>
> Specification of a Kubernetes API object in JSON or YAML format.[[-]](javascript:void(0))
>
> A manifest specifies the desired state of an object that Kubernetes will maintain when you apply the manifest. Each configuration file can contain multiple manifests.

**Comment by cdrage** [comment]
Ah, I see what you mean, I'm so used to people informally referring to them as configuration files and/or resources. I'm okay with naming it Generating Kubernetes manifests.
