### ISSUE TITLE
On linux, no titlebar and app ignores close signals

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#323]
### Bug description

In Linux (e.g. Fedora 36, flatpak install) there is an issue where the application window has no titlebar. This means there is no easy way to close it. Worse, at least in gnome, both clicking the close icon on the window in the overview and right clicking the icon in the dash and selecting quit are also ignored. So right now the only way I can see to close the application on Linux is to grep for podman spawn in the process list and kill -9 the pid. 

I am not sure what is causing this issue but I'd guess it's some kind of electron issue? I tried running it through strace to see if it was receiving any SIGTERM or SIGKILL signals but it doesn't seem to be. It may not support these signals and the fallback of exiting via the close button in the titlebar won't work since the titlebar is non-existent.

Note this isn't a new issue, I just forgot to file it before.

### Operating system

Fedora 36 / x86_64

### Version

next (development version)

### Steps to reproduce

1. Install podman desktop on a Linux system (eg F36)
2. Run podman desktop
3. Notice how there is no titlebar, closing via the desktop app kill options doesn't work

### Additional context

![Screenshot from 2022-07-20 21-10-14](https://user-images.githubusercontent.com/799683/180108289-ea25ae4c-40a1-460d-bb1e-b0964339a21d.png)

**Comment by mairin** [comment]
Dr. Google suggests this might be because the "frameless" option for electron is enabled - it seems maybe electron frameless mode doesn't work on Linux:

https://github.com/logseq/logseq/pull/2335

**Comment by mairin** [comment]
Potentially could also try, if frame is set to false, to set it to true and then use the titleBarStyle hidden option - https://www.electronjs.org/docs/v14-x-y/api/frameless-window

I don't know if this is relevant but this has some info on titlebar support in wayland
https://github.com/electron/electron/issues/27016

**Comment by slemeur** [comment]
Reviewed during sprint planing:
- On Linux, we will have the close/maximize buttons
- On Windows, Mac, we will hide those buttons

For the titlebar:
- We will have it on Windows and Linux

**Comment by benoitf** [comment]
problem on Linux is that it's not really possible to know if tray icon is visible or not (or even supported)
so usually the exit action is only performed when clicking on the menu of the tray icon


It means that if we quit on Linux when clicking on close instead of hiding, we can't have only the tray icon without the window being displayed
