### ISSUE TITLE
UI Tweak: Registries page

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3233]
### Is your enhancement related to a problem? Please describe

I think the visual styling on the Registries page is a little out of step with the rest of the app. It would be nice to update it for consistency / to better match styles established elsewhere in the app. 

Here is a screenshot of how it looks in main today:

![Screenshot from 2023-07-14 15-01-06](https://github.com/containers/podman-desktop/assets/799683/7e8fc391-5c84-4cba-b2ef-c018e65b2b9a)

Two main issues stand out to me:

- The table styling (both the header styling and the use of lines instead of space to delinate rows particularly)
- The placement of the "Add Registry" action button, which on pretty much every other screen is placed in the upper right. I think it's easily missed on the bottom here.

### Describe the solution you'd like

I would suggest something that looks like this:

![Screenshot from 2023-07-14 15-01-06__@](https://github.com/containers/podman-desktop/assets/799683/c85ce3e2-2c32-4449-a3b2-c6955d792c47)

This moves the action button to the upper left (vertically centered along the same line as the page headline "Registries") and it also changes the visual styling of the table to be more consistent with other tables (like the pods/containers/images tables.) 

### Additional context

Note I changed the "Configure" button on suggested registries in the list to be the secondary "outline" form of the button, beacuse the "add registry" button should be the primary button on the page imo.

**Comment by deboer-tim** [comment]
#3245 moved the New button to the header, and #5965 would clean up several alignment issues. Long term I think we need this issue still open to move this page to a Table, to solve these issues and for consistency.
