### ISSUE TITLE
UI Tweak: Consistent text inputs

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3234]
### Is your enhancement related to a problem? Please describe

There's some variants in how we use text inputs and we have some standalone ones. (For instance, right now when active on the text input on Desktop Extensions is a white border, whereas on the preferences search text input the active version has a purple border.) The color palette for these I don't think is 100% consistent either. 

### Describe the solution you'd like

Here is a spec for creating a consistent component for text inputs (including search text inputs.) 

https://design.penpot.app/#/view/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=42e69059-b409-807e-8002-d0b98cda8446&section=interactions&index=0&share-id=c65f3168-697c-808c-8002-d0c926187cdf

Via the link above, make sure you click on the </> icon at the top/center of the page, and you can inspect individual elements like so:

![Screenshot from 2023-07-14 16-31-33](https://github.com/containers/podman-desktop/assets/799683/6a928e7b-509a-4602-8a69-e46b4f6ec703)

Posting screenshot of the spec above, but the penpot link above will always have the most updated/latest, these are a snapshot in time (updated 17 Jul 2023):

![Text Input](https://github.com/containers/podman-desktop/assets/799683/072c14ad-321f-4bd2-952b-f0cfb1908905)

**Comment by deboer-tim** [comment]
Could you give an example of user entered text that is not-active/disabled, or confirm the color? Not clear to me if it should remain white, dim to the same level as default (placeholder) text, or stay somewhere between.

**Comment by mairin** [comment]
> Could you give an example of user entered text that is not-active/disabled, or confirm the color? Not clear to me if it should remain white, dim to the same level as default (placeholder) text, or stay somewhere between.

Oh sure. I updated the screenshot in the issue description with color names (from top to bottom, (1) accent/border line, (2) text /icon color, (3) input background color).

Let me try to think through the case... so the user navigates to a text field:

![Screenshot from 2023-07-17 15-10-05](https://github.com/containers/podman-desktop/assets/799683/87d49fa2-0111-4a68-b218-43a93a2faaec)

They hover over it:
![Screenshot from 2023-07-17 15-10-37](https://github.com/containers/podman-desktop/assets/799683/fe8495a6-df98-4f44-900f-8cb48cad5cb3)

They click into it which focuses it (border color is slightly darker):
![Screenshot from 2023-07-17 15-11-13](https://github.com/containers/podman-desktop/assets/799683/6c512c42-03f3-4ad9-8583-4c7ed7bd38fa)

They start typing and the default text is replaced with the text they enter, and their new text is white while the field is active & focused:
![Screenshot from 2023-07-17 15-11-56](https://github.com/containers/podman-desktop/assets/799683/ad99f97b-ec60-41d7-8278-06b223aa8bdf)

So I think what you're asking is what happens to the text when the user removes focus from this text input to elsewhere, making this text input inactive, right?

I would say the user-entered text should stay white, but since the field is inactive, it goes back to that non-rounded, single bottom accent line color version like this:

![Screenshot from 2023-07-17 15-16-09](https://github.com/containers/podman-desktop/assets/799683/58b2cb7f-5d3e-48de-b67c-523a5f003026)

Does that make sense?

**Comment by deboer-tim** [comment]
Yup, that does. How about if the user text gets disabled? e.g. Proxy settings today you can enter values and then disable the whole form.

**Comment by mairin** [comment]
> Yup, that does. How about if the user text gets disabled? e.g. Proxy settings today you can enter values and then disable the whole form.

I would just use the same styling as disabled.... because I think the fact that the field is disabled overrides whether or not the user entered text into it, and I'd not want to muck with the coloring too much on that to call into question whether or not it's really disabled.

**Comment by mairin** [comment]
Here's a link to the penpot file for this:
https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=42e69059-b409-807e-8002-d0b98cda8446

**Comment by deboer-tim** [comment]
A progress update: the Input component is in, along with customized SearchInput and PasswordInput components. These support the majority of inputs, and over 45 uses have been switched over to the new components.

There are 7 places that still use a regular text/number <input> (a couple of which might not need to change):

- CommandPalette
- QuickPick
- SendFeedback (email)
- BuildImageFromContainerfile (the platform build card)
- RunImage (# of retries)
- NumberItem/FloatNumberItem

Given the number of places where we have an Input + Browse button, we will also need to create a composite FileInput.

**Comment by deboer-tim** [comment]
NumberInput was released via #7143, moving NumberItem/RunImage to the Input component. 

#7197 opened to track a common FileInput.

The remaining cases are minor, maybe don't need to change, or can be handled as individual bugs, so I'm going to close this overall tracking issue.
