### ISSUE TITLE
Unable to add custom registry

### ISSUE THREAD

**Issue by jdelker** [containers/podman-desktop#3252]
### Bug description

When adding a custom registry via Settings -> Registries -> Add registry, podman-desktop responds with "Not a valid registry."

Registry is a private Sonatype Nexus Repository (auth required), which works just fine with native docker as well as podman.

Some debugging already revealed the probable cause for this error:
Querying the registry via `curl -v https://my.nexus.registry/v2/` responds with the following header:
```
< HTTP/1.1 401 Unauthorized
< Date: Tue, 18 Jul 2023 15:43:13 GMT
< Server: Nexus/3.52.0-01 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< Docker-Distribution-Api-Version: registry/2.0
< Content-Type: application/json
< Content-Length: 113
< WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
```
Looking at the particular podman-desktop code (`packages/main/src/plugin/image-registry.js`, Method `extractAuthData`) shows a mismatch for the "WWW-Authenticate" header.
Expected is "Basic" rather than "BASIC".
According to RFC 7617, this may in facts be more a problem on the Sonatype side, using a non-standard scheme name...

However, the problem doesn't end here yet.
I managed to tweak the WWW-Authenticate header to "Basic" on the registry side.
Unfortunately, this only changes the error from "Not a valid registry" to "Invalid URL".

Please advise how to further analyze the problem.

Note: This problem was mentioned before in #1653 where @cdrage requested to have this adressed in a new issue.
(see https://github.com/containers/podman-desktop/issues/1653#issuecomment-1597635888)

### Operating system

macOS Ventury 13.4.1 (Intel)

### Installation Method

Brew (macOS)

### Version

1.2.0

### Steps to reproduce

1. Properly prepare a Sonatype Nexus Repository as a custom container registry. (Accessible via https, with valid certificate and basic authentication).
2. Validate that the registry is performing ok, by pushing/pulling images via docker or podman.
3. Try to add the registry to podman-desktop by providing
  - FQHN as "Repository Location"
  - Username and Password
4. Press "Login" and notice the error "Not a valid registry" to "Invalid URL" (depending on whether you tweaked the "www-authenticate" header).

### Relevant log output

```shell
No console output is shown in developer mode when performing this action.
```

**Comment by cdrage** [comment]
> ### Bug description
> When adding a custom registry via Settings -> Registries -> Add registry, podman-desktop responds with "Not a valid registry."
> 
> Registry is a private Sonatype Nexus Repository (auth required), which works just fine with native docker as well as podman.
> 
> Some debugging already revealed the probable cause for this error: Querying the registry via `curl -v https://my.nexus.registry/v2/` responds with the following header:
> 
> ```
> < HTTP/1.1 401 Unauthorized
> < Date: Tue, 18 Jul 2023 15:43:13 GMT
> < Server: Nexus/3.52.0-01 (OSS)
> < X-Content-Type-Options: nosniff
> < Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
> < X-XSS-Protection: 1; mode=block
> < Docker-Distribution-Api-Version: registry/2.0
> < Content-Type: application/json
> < Content-Length: 113
> < WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
> ```
> 
> Looking at the particular podman-desktop code (`packages/main/src/plugin/image-registry.js`, Method `extractAuthData`) shows a mismatch for the "WWW-Authenticate" header. Expected is "Basic" rather than "BASIC". According to RFC 7617, this may in facts be more a problem on the Sonatype side, using a non-standard scheme name...
> 
> However, the problem doesn't end here yet. I managed to tweak the WWW-Authenticate header to "Basic" on the registry side. Unfortunately, this only changes the error from "Not a valid registry" to "Invalid URL".
> 
> Please advise how to further analyze the problem.
> 
> Note: This problem was mentioned before in #1653 where @cdrage requested to have this adressed in a new issue. (see [#1653 (comment)](https://github.com/containers/podman-desktop/issues/1653#issuecomment-1597635888))
> 
> ### Operating system
> macOS Ventury 13.4.1 (Intel)
> 
> ### Installation Method
> Brew (macOS)
> 
> ### Version
> 1.2.0
> 
> ### Steps to reproduce
> 1. Properly prepare a Sonatype Nexus Repository as a custom container registry. (Accessible via https, with valid certificate and basic authentication).
> 2. Validate that the registry is performing ok, by pushing/pulling images via docker or podman.
> 3. Try to add the registry to podman-desktop by providing
> 
> * FQHN as "Repository Location"
> * Username and Password
> 
> 4. Press "Login" and notice the error "Not a valid registry" to "Invalid URL" (depending on whether you tweaked the "www-authenticate" header).
> 
> ### Relevant log output
> ```shell
> No console output is shown in developer mode when performing this action.
> ```
> 
> ### Additional context
> _No response_

Hi @jdelker I've been working on this issue.

I've setup a basic Nexus repo locally and I've been able to add the registry no problem after changing the code within Podman Desktop to also accept BASIC instead of Basic.

Are you able to email me on my profile / reach out to me on our Discord? I was wondering if there happens to be a test registry that I can help test remotely and 100% fix the issue.

**Comment by cdrage** [comment]
Working through this I also found this issue: https://github.com/containers/podman-desktop/issues/3457 where I'm unable to test locally on a normal "localhost" domain..

**Comment by jdelker** [comment]
Hi @cdrage, I need to check, if I can provide you with a test account on that particular repository.

Meanwhile, maybe this helps:
After the repository now repsonds with `Basic` instead of `BASIC`, I'm stuck with the "Invalid URL" message show in the UI. Here again the recap

1. I click "Add registry" and enter the FQHN as well as username and password in the dedicated fields.
2. When pressing "Login", the message "Invalid URL" appears.
3. For reference: A manual `curl -v https://<FQDN>/v2` works fine via CLI. The repository has a valid LetsEntrcypt certificate, which validates ok.

I tested this with and without HTTPS proxy.
While using the latter, I catched the following requests when clicking the "Login" button.
Two (!) identical GET requests were send:

```
GET /v2/ HTTP/1.1
user-agent: got (https://github.com/sindresorhus/got)
Accept-Encoding: gzip, deflate
Host: hub.<redacted>.de
Connection: close

HTTP/1.1 401 Unauthorized
Date: Wed, 09 Aug 2023 09:02:01 GMT
Server: Nexus/3.58.1-01 (OSS)
X-Content-Type-Options: nosniff
Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
X-XSS-Protection: 1; mode=block
Docker-Distribution-Api-Version: registry/2.0
Content-Type: application/json
Content-Length: 113
WWW-Authenticate: Basic realm="Sonatype Nexus Repository Manager"
Connection: close

{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
```
To see this for the first request is ok, but I would expect the second request to carry the auth data for the actual login. But that's not the case.

This was tested with podman-desktop v1.2.1.

**Comment by cdrage** [comment]
> Hi @cdrage, I need to check, if I can provide you with a test account on that particular repository.
> 
> Meanwhile, maybe this helps: After the repository now repsonds with `Basic` instead of `BASIC`, I'm stuck with the "Invalid URL" message show in the UI. Here again the recap
> 
> 1. I click "Add registry" and enter the FQHN as well as username and password in the dedicated fields.
> 2. When pressing "Login", the message "Invalid URL" appears.
> 3. For reference: A manual `curl -v https://<FQDN>/v2` works fine via CLI. The repository has a valid LetsEntrcypt certificate, which validates ok.
> 
> I tested this with and without HTTPS proxy. While using the latter, I catched the following requests when clicking the "Login" button. Two (!) identical GET requests were send:
> 
> ```
> GET /v2/ HTTP/1.1
> user-agent: got (https://github.com/sindresorhus/got)
> Accept-Encoding: gzip, deflate
> Host: hub.<redacted>.de
> Connection: close
> 
> HTTP/1.1 401 Unauthorized
> Date: Wed, 09 Aug 2023 09:02:01 GMT
> Server: Nexus/3.58.1-01 (OSS)
> X-Content-Type-Options: nosniff
> Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
> X-XSS-Protection: 1; mode=block
> Docker-Distribution-Api-Version: registry/2.0
> Content-Type: application/json
> Content-Length: 113
> WWW-Authenticate: Basic realm="Sonatype Nexus Repository Manager"
> Connection: close
> 
> {"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
> ```
> 
> To see this for the first request is ok, but I would expect the second request to carry the auth data for the actual login. But that's not the case.
> 
> This was tested with podman-desktop v1.2.1.

If you can that'd be great! Right now I have it configured as using an insecure certificate, so it'd be good to test it against Let's Encrypt / your setup as well. 

I've pushed #3468 as well as #3470 to fix the other bugs that have been brought up (being able to test it with a local registry such as `localhost:5000` as well as allowing BASIC authentication.

**Comment by cdrage** [comment]
Hi @jdelker I'm going to close this issue for now, but feel free to re-open if it hasn't been fixed.

I've pushed #3468 as well as #3470 to fix the issue, but wasn't able to completely determine 100% that it resolved it. I tested it locally with a sonatype registry and was able to succesfully add the custom registry / push / pull, but cannot confirm that your registry issue was resolved.

Closing this for now, but re-open if it doesn't work!
