### ISSUE TITLE
Implement preflight checks for podman on Windows

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#326]
Preflight checks:
- Windows 64bit (hyper-v/wsl2 works only on x64)
- Windows version 1903 or later, with Build 18362 or later.(To be able to use wsl2)
- 4gb total RAM, as hyper-v/wsl2 requires 4gb, but for comfort work user should have more ram, could be a warning if user has less then 8gb RAM
- hyper-v enabled, use PS command `(Get-Service vmcompute).DisplayName`, which output `Hyper-V Host Compute Service` if hyper-v enabled and error if not.
- WSL2 enabled, use `wsl -l -v` command, it output:
```
Usage: wsl.exe [Argument]

Arguments:

    --list, -l [Options]
        Lists distributions.

        Options:
            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

```

We need to perform them before start of podman installation.

**Comment by gbraad** [comment]
@evidolob perhaps we can lay out some of the checks here in more detail, and the permissions needed?

> We need to perform them before start of podman installation.

How to determine if the podman installation is needed?

**Comment by evidolob** [comment]
@gbraad We already implement podman detection and show 'install' button only when not podman.

As for permissions we don't need to have escalated right for all checks.
