### ISSUE TITLE
Configure verbose and junit e2e test reporter into e2e tests

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3292]
### Is your enhancement related to a problem? Please describe

Test results/output is very hard to read, a lot of stdout is mixed with test reporting by vitest. 

### Describe the solution you'd like

Include verbose test reporter in vitest.config.js file and add also junit test reporter with outputFile option for an xml test report.

**Comment by benoitf** [comment]
please do not change the default output of tests

if you need an additional output, please use options, env var, etc.

**Comment by odockal** [comment]
When CI env. var is present, we create junit test report file at `tests/output`. Collected now by PR check archive artifacts step.
