### ISSUE TITLE
Design: Single-color icon artwork for kind

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3296]
### Is your enhancement related to a problem? Please describe

Better design for https://github.com/containers/podman-desktop/pull/3131 at 16x16 pixel-snapped level (in the style of https://www.nerdfonts.com/#home), approved by kind upstream. (I have been in contact and they are open to it.) The icon will be used in the status bar and other places in the UI (lists, dialog prompt (quick input, etc))

ideally kind project would add final icon to https://github.com/kubernetes-sigs/kind/tree/main/logo (i could potentially submit as a pr)

### Describe the solution you'd like

Icon should probably be enclosed the way other container list icons are for the kind container entry:

![image](https://github.com/containers/podman-desktop/assets/799683/96202f21-f28f-495b-b27b-d2522ad14e4d)

use this to convert svg to font
https://www.npmjs.com/package/webfont#command-line-interface

use this to test font
https://fontdrop.info/#/?darkmode=true

### Describe alternatives you've considered

current icon font is ok in the short term but doesn't scale well at 16x16 (it's not legible at that size)

![Screenshot from 2023-07-20 16-02-55](https://github.com/containers/podman-desktop/assets/799683/9bec5a07-f7a5-4fd0-9385-58d8dae7090f)
![Screenshot from 2023-07-20 16-01-52](https://github.com/containers/podman-desktop/assets/799683/9bb231a4-70e9-4e4a-b9c1-ea4f5964fe6c)

**Comment by afbjorklund** [comment]
Freel free to do the same for https://github.com/kubernetes/minikube/tree/master/images/logo :-)

![](https://raw.githubusercontent.com/kubernetes/minikube/master/images/logo/logo.svg)

https://github.com/kubernetes/minikube/blob/master/images/logo/logo.svg

EDIT: never mind, converted it

![minikube-icon](https://github.com/containers/podman-desktop/assets/10364051/e63176bb-5076-4ac4-9638-542bbf129737)

* https://github.com/containers/podman-desktop-extension-minikube/pull/8

**Comment by deboer-tim** [comment]
> Icon should probably be enclosed the way other container list icons are for the kind container entry:

I'm assuming we'd use the same 'status icon' (outline, bg colors, etc) and just replace the inner image the same way we do for containers/pods/images/volumes.
