### ISSUE TITLE
Demo: Seal icon for demos / easter egg

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3307]
### Is your enhancement related to a problem? Please describe

With https://github.com/containers/podman-desktop/pull/3131 being merged in, let's add a hidden easter egg using a demo extension that will add the seal icon for containers containing a certain label. It'll be nice to show the "example" feature.

### Describe the solution you'd like

Seal icon + demo extension + documetation.

**Comment by deboer-tim** [comment]
I was learning what we had done for contexts by trying to mark the infra/pause container, when I realized I had basically implemented this already...

Any suggestion on what the label should be? We only look at the key (not value), so was thinking something like `LABEL io.podman.demo=awesome`?

**Comment by cdrage** [comment]
> I was learning what we had done for contexts by trying to mark the infra/pause container, when I realized I had basically implemented this already...
> 
> Any suggestion on what the label should be? We only look at the key (not value), so was thinking something like `LABEL io.podman.demo=awesome`?

I think that'd be a good label name! It's be "unique" enough someone won't accidentally use it.

**Comment by deboer-tim** [comment]
Fixed via https://github.com/redhat-developer/podman-desktop-demo/pull/37.
