### ISSUE TITLE
Installing docker-compose system wide fails on macOS 13

### ISSUE THREAD

**Issue by Krinkle** [containers/podman-desktop#3309]
### Bug description

> Unable to install docker-compose binary: Error: Command failed:
> `cp /Users/krinkle/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose /usr/local/bin/docker-compose`
> ```
> cp: /usr/local/bin/docker-compose: No such file or directory
> ```

I assume the reason is that on latest macOS, `/usr/local/bin` no longer exists by default. Having said that, it is still listed in `/etc/paths` and in the default `PATH` variable, so if the directory were to be created first, that should work and would require the same permissions.

### Operating system

macOS 13.4 Ventura

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Install.
2. Click "Compose" button.
3. Click "Yes" to installing the binary system-wide.

**Comment by benoitf** [comment]
@Krinkle thank you for the report 👍
