### ISSUE TITLE
Container Statistics

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#331]
### Is your feature request related to a problem? Please describe

As a user, I'd like to be able to see some statistic about the container:
- Memory usage
- CPU

### Describe the solution you'd like

We could display the statistics at the top of the container's details:
<img width="704" alt="Capture d’écran 2022-07-21 à 14 18 54" src="https://user-images.githubusercontent.com/1636769/180211916-e9a54637-c123-45bb-aa63-fbfd1bbc4423.png">

**Comment by benoitf** [comment]
Fixed by https://github.com/containers/podman-desktop/pull/473
