### ISSUE TITLE
Rewrite app in Tauri (https://github.com/tauri-apps/tauri)

### ISSUE THREAD

**Issue by SamTV12345** [containers/podman-desktop#3318]
### Is your enhancement related to a problem? Please describe

As a developer I hate that everyone is building an Electron app which itself contains a light Chrome browser. With Tauri you can build apps as small as a native app with around 5 MB. It does a lot of tricks but it starts up way faster than an Electron app, requires only a few MB RAM when running and also the CPU utilization is close to 0%

### Describe the solution you'd like

Migrate the app to Tauri https://github.com/tauri-apps/tauri

### Describe alternatives you've considered

I think there is nothing that performant and small  than Tauri.

**Comment by benoitf** [comment]
thanks @SamTV12345 for the report

I think we received as well comments about moving to https://wails.io/, then others to React native, and also Neutralino/NWjs etc

For now we've extensibility model 'server-side' with 3rd party plug-ins being written in JavaScript so it won't fit well with Tauri.

closing for now but it could be revisited in the future.

**Comment by iMonZ** [comment]
> thanks @SamTV12345 for the report
> 
> I think we received as well comments about moving to https://wails.io/, then others to React native, and also Neutralino/NWjs etc
> 
> For now we've extensibility model 'server-side' with 3rd party plug-ins being written in JavaScript so it won't fit well with Tauri.
> 
> closing for now but it could be revisited in the future.

Any other option?
The electron app is awful from design, usability and resource management. It would be so great if we could get this behind us
