### ISSUE TITLE
Switching Docker Compatibility on/off requests for Podman machine restart even when it is stopped or does not exists

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#3321]
### Bug description

When switching Docker compatibility on/off podman desktop asks to restart podman machine when it is stopped or has not even been created yet.

![Screenshot 2023-07-24 at 11 01 19 AM](https://github.com/containers/podman-desktop/assets/620330/2a46beb4-45d1-4c22-b679-4b519b06965b)

### Operating system

macOS Ventura 13.4 (Apple M1)

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Stop or delete podman machine
2. Enable or disable docker compatibility
3. Watch request being made to restart 'undefined' podman machine
4. Click 'Yes' button and see error reported in console
![image](https://github.com/containers/podman-desktop/assets/620330/86a58511-b4e2-4fe7-ba4c-d342b03f1938)

### Relevant log output

```shell
'''
Uncaught (in promise) Error: Error: undefined: VM does not exist

await (async)
click_handler @ StatusBarItem.svelte:36
```

**Comment by benoitf** [comment]
cc @cdrage
