### ISSUE TITLE
Wrong podman engine version installed or reported

### ISSUE THREAD

**Issue by fangpenlin** [containers/podman-desktop#3322]
### Bug description

After upgrade to podman desktop 1.2.1, I realized that the version running shown on the UI is `4.6.0`. As shown in the screenshot below:

![image](https://github.com/containers/podman-desktop/assets/201615/5eae6145-f639-484a-a95c-19691a728024)
![image](https://github.com/containers/podman-desktop/assets/201615/28819301-4ef4-4e49-aebe-a5227c900198)

But I realized something really odd, not sure why my podman version, the one running is WSL is now `4.5.0` instead of `4.6.0`.

```
podman version
Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.20.3
Git Commit:   38e6fab9664c6e59b66e73523b307a56130316ae
Built:        Thu Jul 20 15:21:54 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 08:42:56 2023
OS/Arch:      linux/amd64
```

Not sure if this is a bug, but I thought that the version reported on the UI suppose to be the engine version instead of the client?   Also, any idea how to upgrade the podman inside WSL machine? I tried to remove the machine and start a new one, it still stay with 4.5.0.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

Install podman desktop 1.2.1 on windows. Open the dashboard to see the version number. Open Powershell and run `podman version` to see the actual version of WSL.

**Comment by benoitf** [comment]
hello @fangpenlin the version reported for now is the client version like if you do `podman --version`

the server version is depending on when the VM is updated. Podman 4.6.0 is out since only a few days, so it needs time before Fedora packages are integrated into Fedora. 


https://packages.fedoraproject.org/pkgs/podman/podman/

Fedora 37 | 4.5.0-1.fc37 stable | 4.6.0-1.fc37 testing

you could connect into the machine and bump to the testing version of podman to get the 4.6.0 but until it is not promoted to stable channel, all machines will use 4.5.0 on Windows

And Podman Desktop 1.2.1 comes with Podman 4.5.0 installer (so both client and server version are '4.5')

**Comment by afbjorklund** [comment]
I asked the same question in the channel, if it was possible to install 4.6.0 without Fedora and without building from source. But there is not, it needs a couple of days to get to Fedora testing and then some weeks to CoreOS testing.

**Comment by benoitf** [comment]
@afbjorklund you could use custom repositories like https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/ to pull current dev version (or use another repo)

then build a custom OCI image and then apply ostree on top of the machine using also `podman machine os apply` command but it's still not easy

**Comment by afbjorklund** [comment]
Right, but that would be more for accessing CI builds or developer versions? So more like building my own binary.
Not for getting the actual vendor release faster, without having to wait for it to get adopted by the distributions...

**Comment by fangpenlin** [comment]
Hmm, okay, now that I understand it's by design to display 4.6.0 instead of the engine version 4.5.0. Just however, IMHO I think the UI should display the engine version instead of the client version. Because for a newer version of client, you get the update for the client, but it's still the engine the end-users are using. I assume almost nothing really changed with a newer client. Say if there's a new feature or bugfix pushed out in 4.7.0 for podman, but people install podman via podman-desktop, it shows 4.7.0. When they try to use the new feature from 4.7.0, they cannot see it. It's going to cause confusing down the road.

Maybe there's a valid reason to do that I didn't know. Regardless, it's just my feedbacks 😅

**Comment by benoitf** [comment]
@fangpenlin thanks for your feedback. we have new UI mockups where we want to display client and server/engine version so you should have all the information.
