### ISSUE TITLE
Pod: No indication that containers are clickable in Summary section

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3329]
### Is your enhancement related to a problem? Please describe

When browsing the summary section of a Pod, there's no indication that the container ID's are clickable unless you put your cursor over it.

I discovered that it is clickable by looking at the code and seeing it, rather than within the interface.

### Describe the solution you'd like

Coloured differently / indication it is clickable. 

### Describe alternatives you've considered

https://github.com/containers/podman-desktop/assets/6422176/eaca8332-8728-4bf5-afb5-fcd8c6ef745a

**Comment by afbjorklund** [comment]
If you click the containers in a Kubernetes pod, that leads to a dark place (black screen).

* https://github.com/containers/podman-desktop/issues/2800
