### ISSUE TITLE
UI of the pods' summary should be consistent with other screens

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3330]
### Is your enhancement related to a problem? Please describe

The UI of the summary of the pods is looking less practical and inconsistent with the rest of the application.
For example, as a developer new to the tool, it's really difficult that it is possible to click on one of the container to get into its details.

### Describe the solution you'd like

Maybe, for consistency and simplicity, we should just re-display the containers as we do in the list of containers. 
We could also keep the quick actions which would make it handy.

### Additional context

should also be aligned for a compose group of containers

**Comment by deboer-tim** [comment]
This is the same as issue #2980 you previously opened.
