### ISSUE TITLE
GH Workflow: WinGet not run for version 1.2.1

### ISSUE THREAD

**Issue by leeuwe** [containers/podman-desktop#3336]
### Bug description

Version 1.2.1. is not pubished to WinGet repository.
The manual workflow to publish Podman-Desktop to winget is forgotten to run after publishing the release.

### Operating system

Windows

### Installation Method

Winget (Windows)

### Version

1.2.1

### Steps to reproduce

`winget search Podman-Desktop`

### Relevant log output

```shell
Name           Id                    Version Match       Source
---------------------------------------------------------------
Podman         RedHat.Podman         4.6.0               winget
dive           wagoodman.dive        0.10.0  Tag: podman winget
Podman Desktop RedHat.Podman-Desktop 1.2.0               winget
```

**Comment by benoitf** [comment]
@leeuwe thanks for the report

I've triggered the job 
https://github.com/microsoft/winget-pkgs/pull/113208

**Comment by benoitf** [comment]
closing as PR has been merged on winget
