### ISSUE TITLE
Provide ability to init & start podman

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#334]
### Is your enhancement related to a problem? Please describe

When the user is starting for the first time Podman Desktop, the setup is in 2 stages:
- Init: to create the podman-machine
- Start: to start the created podman-machine

### Describe the solution you'd like

It would be nice if there was a button to "init and start" maybe as dropdown to choose what to do. 

### Describe alternatives you've considered

We may not need to give the choice to the end-user as 99% of the time, when they will want to do the init and start all together. We would then catch, by ourselves if the machine is there or stopped and do the proper actions on behalf of the user.
In the outputs, we would then display multiple steps. (inspiration could be https://material.io/archive/guidelines/components/steppers.html)

**Comment by benoitf** [comment]
it depends on https://github.com/containers/podman/issues/14738 but it's still not fixed

**Comment by lstocchi** [comment]
@slemeur @benoitf  I was thinking about using a split button for this (similar to https://mui.com/material-ui/react-button-group/#split-button). Does it makes sense for you or you were expecting something different?

![splitted_button](https://user-images.githubusercontent.com/49404737/218080723-5bd746be-e67b-4b73-82d0-b5a7f17d7ecb.gif)

**Comment by lstocchi** [comment]
@slemeur @benoitf a quick demo how it's evolving. Thoughts?

![installation_demo_short](https://user-images.githubusercontent.com/49404737/218808003-d8136912-e1c8-4d16-81df-19d6d0887140.gif)

**Comment by benoitf** [comment]
I think this issue was flagged on hold as there will be a rewrite of the onboarding screen. 
But what you're showing is what was intended.

**Comment by lstocchi** [comment]
Oh i didn't know. As it was assigned to me last week i assumed the blocker has somehow been fixed. Do i stop it for the moment? I need to ping someone?

**Comment by slemeur** [comment]
Let's get it in. I think it's still a nice and useful improvement for end-user until we have a larger effort on the onboarding screens.
