### ISSUE TITLE
Design: Mockups for OpenShift compat image quality checker

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3343]
(We moved #3341 to Sprint 244, since it is dependent on some mockups which will be aligned to Sprint 243.)

Luca has written a tool that examines images for compatibility with OpenShift and assigns a grade with hints on how to improve them:
https://github.com/lstocchi/docker-openshift-analyzer

In sprint planning today we talked about how this might look:

- Having badges to reflect the image grade quality that would show up in the images list in the UI
- Have a mockup for a tab in the image details screen to list out the image quality details + the hints on how to improve the image

**Comment by mairin** [comment]
Note to self: clone docker-openshift-analyzer repo then build and run by using
```
go build -o doa[.exe]
doa[.exe] analyze /your/local/project/path[/Dockerfile_name]
```

**Comment by benoitf** [comment]
closing as it was flagged as done
