### ISSUE TITLE
no logs for compose group

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#3349]
### Bug description

From https://github.com/containers/podman-desktop/pull/3253#issuecomment-1651160907

I have compose project but going to the logs tab, everything is empty

It should display logs of all containers of the compose application

### Operating system

macOS Ventura

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

I used
https://gist.githubusercontent.com/benoitf/a94cff3545cb0992007dd1fc58287816/raw/d0b33311834d84ec1d6830b32a167af80c84926e/docker-compose-example.yaml

**Comment by cdrage** [comment]
I'm unable to reproduce. I followed these steps:

1. Downloaded https://gist.githubusercontent.com/benoitf/a94cff3545cb0992007dd1fc58287816/raw/d0b33311834d84ec1d6830b32a167af80c84926e/docker-compose-example.yaml
2. Ran `export DOCKER_HOST=unix:///var/run/docker.sock docker-compose up -d`
3. I'm able to view the logs.



https://github.com/containers/podman-desktop/assets/6422176/c04b00f8-3e48-4159-8b67-3339789def9e



I am running this against the podman / not docker.

**Comment by benoitf** [comment]
it seems to be while the first container is not having any log output, it blocks all the remaining calls

Here is an example

https://github.com/containers/podman-desktop/assets/436777/e5ec3f73-58db-4b4f-8447-8d53deb1cea1

I have some logs, then I make sure podman-desktop-socket container is the first one in the list of containers (and this container does not output anything)

Then I have nothing and if I remove this container, again I have logs

Issue is around packages/renderer/src/lib/compose/ComposeDetailsLogs.svelte and the

```
    await window.logsContainer(container.engineId, container.id, logsCallback);

```


here we're blocking the loop until this instruction finished (but it doesn't finish as we don't have logs)
