### ISSUE TITLE
Migrating automation tests in testcontainers from docker to podman

### ISSUE THREAD

**Issue by stitchik** [containers/podman-desktop#3353]
### Bug description

I have automation tests in testconteiners that used to be running in docker.
Now I'm trying to migrate from docker to podman.
While running tests I got an error
`023-07-27 09:05:35.226  INFO 11352 --- [           main] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-07-27 09:05:36.703  INFO 11352 --- [           main] o.t.utility.RegistryAuthLocator          : Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2023-07-27 09:05:37.144  INFO 11352 --- [ream-1335806995] org.testcontainers.DockerClientFactory   : Starting to pull image
2023-07-27 09:06:07.145 ERROR 11352 --- [pull-watchdog-1] org.testcontainers.DockerClientFactory   : Docker image pull has not made progress in 30s - aborting pull` 

I was wondering how I can fix it, please? What setting should I do?

### Operating system

Windows11

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Relevant log output

```shell
PS C:\WINDOWS\system32> podman --version
podman.exe version 4.6.0

[System.IO.Directory]::GetFiles("\\.\\pipe\\")
\\.\\pipe\\dockerBackendV2
\\.\\pipe\\docker_engine
\\.\\pipe\\podman-machine-default
```

**Comment by benoitf** [comment]
Hello @stitchik and thanks for your report

I know that for test containers and podman, `TESTCONTAINERS_RYUK_DISABLED=true` env variable should be added at some point.

How your image is being named ? if it doesn't include a registry prefix could you try with it

like instead of `httpd`, `docker.io/library/httpd`


Could you also run with `DEBUG | testcontainers*` env variable ?

**Comment by stitchik** [comment]
I tried to run it in debug but there is no other additional information in log
`2023-07-27 15:37:31.378  INFO 992 --- [           main] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-07-27 15:37:34.546  INFO 992 --- [           main] o.t.utility.RegistryAuthLocator          : Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2023-07-27 15:37:34.991  INFO 992 --- [ream-1335806995] org.testcontainers.DockerClientFactory   : Starting to pull image
2023-07-27 15:38:05.006 ERROR 992 --- [pull-watchdog-1] org.testcontainers.DockerClientFactory   : Docker image pull has not made progress in 30s - aborting pull`

docker image name `rabbitmq:3.7.25-management-alpine`

**Comment by benoitf** [comment]
@stitchik could you try to pull the images by command line first ?

docker.io has some restrictions on the number of hits, which image are you using ?

**Comment by stitchik** [comment]
I found out that docker commamds didn't work as it is.
```
docker login docker-local.xxx.com
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: login attempt to docker-local.xxx.com failed with status: authenticating creds for "docker-local.xxx.com": pingi
ng container registry docker-local.xxx.com: Get "https://docker-local.xxx.com/v2/": dial tcp: lookup docker-local.xxx.com: i/o timeout
Username (user): yyyy
Password:
Error response from daemon: login attempt to docker-local.xxx.com failed with status: authenticating creds for "docker-local.xxx.com": pinging container registry docker-local.xxx.com: Get "https://docker-local.xxx.com/v2/": dial tcp: lookup docker-local.xxx.com: i/o timeout
```


I tried to set alias `Set-Alias -Name docker -Value podman` but there is no use. I got `Error response from daemon:`
The same error I got trying to pull image in command line ( docker pull ...)

**Comment by benoitf** [comment]
Hello @stitchik 

are you behind an http proxy ?

**Comment by stitchik** [comment]
no
If I use `podman login` to the same repository it works perfectly but docker commands don't work at all
