### ISSUE TITLE
When deleting a containers all pods are getting deleted too

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3374]
### Bug description

From the list of containers, when deleting a containers it also delete all pods, even if they are not selected;

See:

https://github.com/containers/podman-desktop/assets/1636769/ff4c84b3-0c73-4337-98b4-72047067c06c

### Operating system

macOS Ventura Intel

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. start multiple containers and pods
2. go on the list of containers
3. Select one container
4. Click delete

--> all pods are getting deleted too

**Comment by rostalan** [comment]
Had the same bug, can confirm it has been fixed in the latest tag.
