### ISSUE TITLE
Podman Desktop becomes out of sync when mounting large volume

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#3376]
### Bug description

On my environment I'm getting a strange behavior where podman desktop is becoming out of sync with the podman machine. This seems to be related to the volume mounted.

When using podman machine, I used to create podman machine directly from the UI. In this situation the default volume mounted with the VM is `$HOME:$HOME`. It used to work seamlessly and I was able to use my podman environment with great performances. 
Since few days, it does not behave the same and I'm experimenting very weird behaviors where podman desktop is not able to properly show the containers. 
Looking at the stores, I can see those values:
![capture_d___e__cran_2023-07-26_a___22 22 58](https://github.com/containers/podman-desktop/assets/1636769/2b6d4117-782e-43cb-8975-48b0c869b66a)

I've observed that in the podman machine, the podman service is consuming a lot of CPU and never stabilizing to something normal. (it stayed around 30% CPU usage)

I think this happened after I created a tar file by doing a "save images" and then trying to load them into a fresh podman machine.

I did tried number of things:
- reinstalling qemu
- reinstalling podman
- checking between rootless and rootfull podman machines
- checking the network
- upgrading to podman 4.6.0
- cleaning the vm image
Nothing helped.

The only thing that did improve the situation was creating a temporary empty folder on my system and initializing the podman machine by mounting only this empty folder. In this case, I was back to something normal. 

### Operating system

macOS intel 13.4 

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

**Comment by slemeur** [comment]
Corresponding issue on podman repo: https://github.com/containers/podman/issues/19467

**Comment by benoitf** [comment]
On Podman Desktop side here are improvements that could be made as REST API of Podman has no cache:

- reduce the number of calls (if I have 5 calls in a row, apply a throttle/limit, skip some the calls (skip for read operations like 'list of containers)

- avoid usage of the heavy `/system/df` command on Podman (for volumes maybe do in two steps: first get volumes and then fetch /system/df and update volumes data when df is called. And refresh if there is no calls for a long time to the backend, etc)

**Comment by benoitf** [comment]
here are the improvements that have been made:
- debounce (only perform one call if multiple requests are happening in a short amount of time)
- still let one call passing every 5s to have UI being more "responsive"
- do not call /system/df, volumes are now always displayed but you don't have the usage size until you ask for it
- refactor calls to avoid the need to call an extra inspect call on each container when listing containers
