### ISSUE TITLE
Exec terminal should be able to persist when changing focus

### ISSUE THREAD

**Issue by jberkus** [containers/podman-desktop#3381]
### Is your enhancement related to a problem? Please describe

The way it is now:

1. Start a container
2. Select the running container in the Containers list
3. Click on the terminal tab
4. Do stuff in the terminal
5. Click on the Logs tab
6. Click back on the Terminal tab
7. It's a new terminal session; the prior one exited

### Describe the solution you'd like

The way I'd like it to be:

The terminal session should persist until I specifically exit it.

Basically, the way it's designed now is great in terms of not allowing us to accidentally have dozens of exec terminals open to different containers that we've forgotten about.  However, it's prohibitive towards using Desktop for actual troubleshooting.  For example, I frequently want to switch back and forth between logs and terminal because I'm trying to debug something I saw in the logs.

### Describe alternatives you've considered

I end up using podman from the command line and not using Desktop.

### Additional context

Podman Desktop 1.2.0

**Comment by benoitf** [comment]
thanks @jberkus for the report


I'm closing this one as a dup of https://github.com/containers/podman-desktop/issues/2763

**Comment by benoitf** [comment]
Reopening as it differs

**Comment by deboer-tim** [comment]
But this is a dup of #502 though, isn't it?

**Comment by benoitf** [comment]
yes, I was pretty sure there was a dup but didn't find it. Thanks @deboer-tim 
Closing as a dup of https://github.com/containers/podman-desktop/issues/502
