### ISSUE TITLE
Allow more than one kubeconfig file, including generated from provisioners

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#3385]
### Is your enhancement related to a problem? Please describe

Currently the interface is hardcoded to a single KUBECONFIG, defaulting to ~/.kube/config

But it is possible to have more than one, that will be merged before presenting contexts...

### Describe the solution you'd like

The "kind" and "minikube" clusters are editing the user config, while k3s and k8s do not.

So for those clusters, running in Lima, they generate a file that can be passed like a socket.

### Describe alternatives you've considered

The workaround is to copy and paste the path location, which "hides" the other contexts

So while overriding the kubeconfig, it is not possible to use any other cluster in the config

### Additional context

* https://github.com/containers/podman-desktop/issues/3258

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by afbjorklund** [comment]
Example of `kubeConfig` field, for the Lima provisioner:

commit https://github.com/containers/podman-desktop/commit/b54bb4b29eb258a951ee9422146839670b44e5d9

```diff
--- a/packages/extension-api/src/extension-api.d.ts
+++ b/packages/extension-api/src/extension-api.d.ts
@@ -223,6 +223,7 @@ declare module '@podman-desktop/api' {
   }
   export interface KubernetesProviderConnection {
     name: string;
+    kubeConfig?: string;
     endpoint: KubernetesProviderConnectionEndpoint;
     lifecycle?: ProviderConnectionLifecycle;
     status(): ProviderConnectionStatus;
```

It contains the path of the file, to be appended to KUBECONFIG.

**Comment by benoitf** [comment]
your suggestion in API looks like a good move.
Just wondering if we provide the string or the JSON object and how [kubernetes-client ](https://github.com/kubernetes-client/javascript) handle that (as it should fit with that lib)

**Comment by afbjorklund** [comment]
A missing value (null), means that the context is only in the default (~/.kube/config) and that no config is needed...

A string value, means that the path of the file is merged with the existing $KUBECONFIG using the path separator.

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#append-home-kube-config-to-your-kubeconfig-environment-variable
There were some examples in the Lima provisioner, but it does not handle JSON objects at all - only kubeconfig files:

```
KUBECONFIG=~/.kube/config:~/.lima/k3s/copied-from-guest/kubeconfig.yaml:~/.lima/k8s/copied-from-guest/kubeconfig.yaml
```

It is similar to modifying the PATH variable, instead of having to copy files to the global (or user) default paths ?

**Comment by afbjorklund** [comment]
It seems that the javascript library does not fully handle kubeconfig configuration files yet, unfortunately:

https://github.com/kubernetes-client/javascript#known-issues
"Multiple kubeconfigs are not completely supported. Credentials are cached based on the kubeconfig username and these can collide across configs. Here is the related https://github.com/kubernetes-client/javascript/issues/592."

The current user names for the local clusters are quite random, but they don't seem to be colliding:

```
CURRENT   NAME                          CLUSTER             AUTHINFO            NAMESPACE
*         default                       default             default             
          kind-kind-cluster             kind-kind-cluster   kind-kind-cluster   
          kubernetes-admin@kubernetes   kubernetes          kubernetes-admin    
          minikube                      minikube            minikube            default
```
