### ISSUE TITLE
Pods: Starting / stopping status does not show

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3400]
### Bug description

Because we have not implemented inProgressCallback, the status "STARTING" and "STOPPING" is not shown when deleting a pod.

Same issue as: https://github.com/containers/podman-desktop/issues/3123

### Operating system

mac M1

### Installation Method

None

### Version

1.2.1

### Steps to reproduce

Start / stop a group of containers via a Pod, STOPPING / STARTING does not show.

https://github.com/containers/podman-desktop/assets/6422176/33ea066e-f934-4828-904c-1e2abf44afa4

**Comment by dgolovin** [comment]
I cannot replicate the issue


https://github.com/containers/podman-desktop/assets/620330/e0e9661e-f218-4f63-ae29-7f685f8bb67b

**Comment by dgolovin** [comment]
@cdrage could it possibly was fixed when #3123 is fixed?

**Comment by cdrage** [comment]
Yup! Sorry, this should of been closed.
