### ISSUE TITLE
Can only see one machine in Resources > Podman details

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3401]
### Bug description

The new screen to show details for a Podman machine is great, but no matter which machine/link I use I only see the details for one machine.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Create multiple podman machines. Use the new link action to open details, the same one opens every time.

**Comment by benoitf** [comment]
I think it was fixed during the PR review as it was already the case but then maybe another issue/regression appeared

**Comment by lstocchi** [comment]
Just an update, everything seems working fine on Windows

**Comment by benoitf** [comment]
I reproduce (on macOS)

https://github.com/containers/podman-desktop/assets/436777/3e71d175-a55a-4e8d-aaa1-a2c518475e8b

**Comment by deboer-tim** [comment]
FWIW, I did try to see what the fix prior to merge was, but there was a force-push so I couldn't see what changed. ;-)

**Comment by lstocchi** [comment]
@deboer-tim that time i fixed the issue by rebasing and using your enhancement `navigation=root/tab/...`.
The code was out of sync with the main branch when Florent detected your same issue, but after rebasing and updating to the new routing way it seemed to be solved.

**Comment by benoitf** [comment]
it comes from Podman 4.5.0 where socketPath is now the same across all machines. We had to fix in a lot of different places as we were using that before as 'primary key'

**Comment by benoitf** [comment]
here is an example on how we could fix it https://github.com/containers/podman-desktop/pull/3436 (just set draft as there is no test)
