### ISSUE TITLE
UI: Refactor callback calls (multiple calls to refresh)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3403]
### Is your enhancement related to a problem? Please describe

We do multiple calls to the UI to refresh by using callbacks with ComposeActions, ContainerActions, PodActions, etc.

@deboer-tim brought up a good point here: https://github.com/containers/podman-desktop/pull/3390#issuecomment-1662445299 that we should refactor that part of the UI so that calls are minimal.

I'm thinking more event-based so we do not have to do the call-backs as often?

### Describe the solution you'd like

Refactor of callbacks to actions.

**Comment by benoitf** [comment]
Maybe svelte Context API could help

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.
