### ISSUE TITLE
Podman installation with WSL requires page refresh to install

### ISSUE THREAD

**Issue by cedricclyburn** [containers/podman-desktop#3421]
### Bug description

When trying to install Podman Desktop on a fresh Windows machine, going through the process to install WSL and coming back to Podman Desktop, users have do one of these steps to continue through the Podman installation process:
1. Quit Podman Desktop and restart
2. Head to another page in Podman Desktop and return to the Dashboard

### Operating system

Windows Server 2022

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Select install without enabling WSL beforehand
<img width="1057" alt="Screen Shot 2023-08-03 at 10 31 50 AM" src="https://github.com/containers/podman-desktop/assets/54345140/a75c101e-4df9-417c-9bde-1b4fce5e2fd0">
2. Go through process to install WSL
<img width="1012" alt="image" src="https://github.com/containers/podman-desktop/assets/54345140/4aecec49-a0ad-477a-99c0-f652cb8293e5">
3. Return to Podman Desktop where there's no option to restart the Installation process for Podman
<img width="1053" alt="Screen Shot 2023-08-03 at 10 46 40 AM" src="https://github.com/containers/podman-desktop/assets/54345140/edc2a85d-4011-49b9-a9a8-8395774af9f2">

**Comment by cedricclyburn** [comment]
Just realized I hadn't made it yet to the actual WSL installation, this is just a blocker at the VM enablement part.

**Comment by benoitf** [comment]
@cedricclyburn is it possible to record a video ?
or could you describe the part
> Just realized I hadn't made it yet to the actual WSL installation, this is just a blocker at the VM enablement part.

**Comment by cedricclyburn** [comment]
Yes no problem @benoitf:


https://github.com/containers/podman-desktop/assets/54345140/891b406f-7b42-497f-8841-883fbd04fad2

After installing VM, or even WSL, users have to either close and reopen Podman Desktop, or head to another page (like I did with the Containers page), in order to get access to continue on with the installation.

**Comment by benoitf** [comment]
understood @cedricclyburn 

thanks for the report

**Comment by benoitf** [comment]
We're transforming these flows to 'onboarding flows'
you can take a look at mockups there https://github.com/containers/podman-desktop/discussions/3244 

it should improve your experience

**Comment by cedricclyburn** [comment]
Ah gotcha that will be very helpful! I'm working on a "Setting up Podman Desktop for Windows" article for RHD right now, should I still publish or wait for the onboarding flows? @benoitf @slemeur

**Comment by benoitf** [comment]
I would not hold the article

**Comment by cedricclyburn** [comment]
Okay I submitted for editorial review yesterday 👍
