### ISSUE TITLE
Confusion with WSL installation command

### ISSUE THREAD

**Issue by cedricclyburn** [containers/podman-desktop#3422]
### Bug description

When trying to install WSL for the Podman Container engine, I'm prompted to install via the [Microsoft docs](https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command) which say `wsl --install`, just as the Podman Desktop UI says, but the [Podman Desktop docs](https://podman-desktop.io/docs/installation/windows-install/installing-podman-with-podman-desktop) say to enable WSL without installing the default Ubuntu distro using `wsl --install --no-distribution`. Which way is the recommended path? 

### Operating system

Windows Server 2022

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Go through the Podman install process through Podman Desktop
<img width="1070" alt="image" src="https://github.com/containers/podman-desktop/assets/54345140/200501e7-30e8-4cd2-bcaf-a21dbf40af30">

- Follow either the instructions from Podman Desktop
<img width="1058" alt="image" src="https://github.com/containers/podman-desktop/assets/54345140/0f12fe35-35ae-4ddc-a799-70056bf6a264">
- Or from the online documentation
<img width="779" alt="Screen Shot 2023-08-03 at 11 22 28 AM" src="https://github.com/containers/podman-desktop/assets/54345140/018675d3-ca6d-4293-8166-92ce7d003c37">

### Additional context

Also, to keep consistency with the Podman Desktop docs and actual desktop application, the Windows [documentation](https://podman-desktop.io/docs/installation/windows-install/installing-podman-with-podman-desktop) should be in this order:

1. The Home screen displays Podman Desktop was not able to find an installation of Podman. Click on Install.
2. Podman Desktop checks the prerequites to install Podman Engine. When necessary, follow the instructions to install prerequisites.
3. Enable the WSL feature without installing the default Ubuntu distribution of Linux.
4. Podman displays the dialog: Podman is not installed on this system, would you like to install Podman?. Click on Yes to install Podman.
5. Click on Initialize Podman.

<img width="852" alt="image" src="https://github.com/containers/podman-desktop/assets/54345140/47ad32a9-0e69-4e39-b29d-de66874b0199">

**Comment by cedricclyburn** [comment]
Happy to help out with this (if it's a good idea lol)

**Comment by benoitf** [comment]
thanks for the report @cedricclyburn 

I think `wsl --install --no-distribution` is preferred as it does not install like an additional ubuntu instance if people don't need it. (which might be the case if you just need podman). But it does not harm to have this extra distribution (except disk space usage, etc).

**Comment by cedricclyburn** [comment]
Ah yes, but for users just trying to install Podman, should the instructions on both the docs and podman desktop be the same for the command?

**Comment by gbraad** [comment]
this is something that needs to be resolved in the podman repo for the windows machine setup.

**Comment by slemeur** [comment]
This is should be fixed in the documentation cc @themr0c

**Comment by themr0c** [comment]
The --no-distribution is preferable, because it avoids installing for no purpose the default Ubuntu WSL.

It's better to keep it first in the docs: that way the check is directly passing.

It would be better to have the onboarding screen proceed to the installation automatically (and propose reboot if necessary).
