### ISSUE TITLE
nit: sort Podman machines

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3423]
### Is your enhancement related to a problem? Please describe

Every time I restart Podman Desktop and open Resources, my machines are in a different order, which means it takes marginally longer to figure out where one is or if the same one is running.

### Describe the solution you'd like

It would be nice to sort them alphabetically, either directly in this page, or the API that feeds it so that they're naturally sorted elsewhere too.

**Comment by benoitf** [comment]
> or the API that feeds it so that they're naturally sorted elsewhere too.

API (podman machine ls) sort them by 'last up', but on Podman Desktop side I think it's coming in an unknown predictable order
