### ISSUE TITLE
nit: remove Podman Machine prefix

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3424]
### Is your enhancement related to a problem? Please describe

The prefix on every Podman Machines is extraneous, and makes machines harder to find and identify. For instance, if created three machines, instead of seeing the names I gave them (work, test, demo), it shows Podman Machine work, Podman Machine test, Podman Machine demo. This makes it harder to read, or to find the right machine in Resources.

### Describe the solution you'd like

Remove the default prefix, so that the machines are shown with their real names in the Dashboard and Resources. If there are other place where the context is less obvious (system tray?) it can be added (left on) there.

**Comment by benoitf** [comment]
There is only one name for providers, so if you change the name it will be same displayed in Resource tab or in System tray (there won't be a prefix here)

**Comment by deboer-tim** [comment]
Yes, I expected that but I guess my suggestion wasn't clear - to start with I think we should remove the prefix so that from an API perspective and all views it is gone. If I name a podman machine 'Fred', it is always just 'Fred'.

In my case everything is named uniquely so there would be no confusion/no need to do anything else, but that won't be the case for all users/all views. If the context isn't clear within a specific UI like the system tray, we would need to add something else to differentiate. e.g. the view itself adds the prefix, uses header or grouping, icon, etc.
