### ISSUE TITLE
Podman screen not updated after podman is installed

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#343]
### Bug description

I had podman 4.0.2 installed. Desktop told me 4.1.1 was available, I clicked on Update, then podman is updated but after it completes the screen is not updated, misleading the user.

![image](https://user-images.githubusercontent.com/695993/180479939-a845671c-238d-4b35-9901-64684e851fc1.png)

### Operating system

Win10 Pro

### Version

next (development version)

**Comment by benoitf** [comment]
agreed 👍

**Comment by jeffmaury** [comment]
Tried on a brand new W10 VM so once I started desktop it told me that podman was not installed so I installed it but once installation finished screen is not updated and once I restart the desktop home screen is empty

**Comment by benoitf** [comment]
@jeffmaury I noticed that as well and submitted https://github.com/containers/podman-desktop/pull/358

**Comment by jeffmaury** [comment]
Still happening with 0.0.7

**Comment by jeffmaury** [comment]
Still happening with 0.9.1
