### ISSUE TITLE
Stopping an alpine container on GHA ubuntu (22.04) runner shows an error during e2e test implementation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3434]
### Bug description

There is a visible error when stopping an alpine container via playwright tests which prevents container transition into EXITED state. It is visible in the video from one of the GHA runs for e2e tests.

[5a43ec560fc711b3ca6b3c2e69b85a02.webm](https://github.com/containers/podman-desktop/assets/19164299/8e90ae8d-8bcb-421c-b5d0-271e5ef604ad)

### Operating system

Ubuntu 22.04

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

This part is tricky itself. We need to either spawn ubuntu in VM on our own machine and have somehow similar setup to test this. 
Or we could improve e2e tests to get actual error message when it appears, which will require another PRs for improvement of e2e tests and adding some ARIA wise elements into the UI. 

### Additional context

In order to figure out what is going on on the GHA runner, one could use a custom workflow in own fork and use workflow dispatch event to trigger the GHA runner and connect to it using `mxschmitt/action-tmate@v3` action. Then it is possible to check the same or similar workflow using podman cli. I tried also a compat API to reproduce the workflow, but it seems to work. This suggest problem in podman desktop.

**Comment by benoitf** [comment]
@odockal do you have the dev console video (with the log console) or the troubleshooting page (where logs are displayed)

maybe we could have something

also I think we can get error hovering the icon

**Comment by odockal** [comment]
@benoitf Dev console is not usable, there is just collapsed HTML on Elements Tab right now. But good idea as well, we could catch output of console, if it can be switched to appropriate tab.

**Comment by odockal** [comment]
Something similar reported on podman side [1] (might be resolved in newer podman). Here we are talking about podman 3.4.4. Thx @benoitf for finding.

[1]: https://github.com/containers/podman/issues/17142

**Comment by odockal** [comment]
The Error in GHA ubuntu 22.04 is: `Error text: Error: (HTTP code 500) server error - given PIDs did not die within timeout`.

**Comment by benoitf** [comment]
@odockal could you try with these lines before launching the tests (bump podman version installed in the runner)
```
$ sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
$ curl -L https://build.opensuse.org/projects/devel:kubic:libcontainers:unstable/signing_keys/download?kind=gpg | sudo apt-key add -
$ sudo apt-get update -qq
$ sudo apt-get install -y podman
```


I tested on a Github runner and I'm able to have podman 4.6.0

```
runner@fv-az339-454:~/work/gh-linux-runner/gh-linux-runner$ podman --version
podman version 4.6.0
```

**Comment by odockal** [comment]
@benoitf Like a charm:
```
0s
Run podman version
Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.18.1
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Comment by odockal** [comment]
With podman update to 4.6 the stopping scenario now passes on GHA. Although there are another issues right now to have full suite stable. still looking at it.
