### ISSUE TITLE
insecure registries configuration example has become invalid

### ISSUE THREAD

**Issue by GrimmiMeloni** [containers/podman-desktop#3439]
The configuration described in

https://podman-desktop.io/docs/getting-started/insecure-registry

no longer works as it uses an old configuration format. Applying the currently documented change will lead to a broken system, as the config file becomes invalid.

An example of the new v2 configuration snippet required for insecure registries is:

```
[[registry]]           
prefix = "localhost"   
location = "localhost" 
insecure = true      
```  

(source: https://github.com/containers/podman/issues/16486#issuecomment-1396644503)

**Comment by benoitf** [comment]
hello @GrimmiMeloni this is currently being discussed at https://github.com/containers/podman-desktop/pull/3406 and https://github.com/containers/podman-desktop/issues/1653#issuecomment-1660703365

closing this one as a dup
