### ISSUE TITLE
Doc: document how the onboarding works/how to create an onboarding workflow

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3440]
### Is your enhancement related to a problem? Please describe

First implementation of the onboarding has been merged but it does not contain any description about the different components used/how to create an onboarding workflow. 

### Describe the solution you'd like

 We should add some documentation.

**Comment by cdrage** [comment]
FYI this is something @lstocchi and I will have to document as there are some new improvements to onboarding such as the `micromark` custom markdown that will need to be documented / added (probably as a detail) on how to correctly use onboarding in your extension.
