### ISSUE TITLE
Windows Arm build

### ISSUE THREAD

**Issue by AquaBx** [containers/podman-desktop#3443]
### Is your enhancement related to a problem? Please describe

Today I built Podman Desktop for my Surface Pro X to run natively (Arm64).
It seems to work well, despite some build errors related to 7zip-bin not reaching a file. (For info, I ran npm run compile:current)

### Describe the solution you'd like

If I see something that does not work properly, I will send it back.
And if you want to do some testing in it before release, I can do that.

**Comment by benoitf** [comment]
Hello @AquaBx thanks for the reminder, this is something we were planning.

More and more users on Windows are now using arm chips.
