### ISSUE TITLE
Featured extension icons disappear from Extension page after resizing app's window

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#3460]
### Bug description

https://github.com/containers/podman-desktop/assets/620330/3a140cbd-863d-45a9-b330-60b64348f054

### Operating system

macOS Ventura 13.4 (Apple M1)

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Open Settings/Extensions page 
2. Increase width of the window slowly until number of rows gets increased

**Comment by deboer-tim** [comment]
Same basic issue as #2760
