### ISSUE TITLE
Can not run hello world

### ISSUE THREAD

**Issue by DaRealCapz** [containers/podman-desktop#3464]
### Bug description

Fresh install of podman desktop on Windows, tried the command "podman run quay.io/podman/hello" and the output is,  "Trying to pull quay.io/podman/hello:latest...
Error: initializing source docker://quay.io/podman/hello:latest: pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io: Temporary failure in name resolution"

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

podman machine stop
podman machine rm
y
podman machine init
podman machine start
podman run quay.io/podman/hello

### Relevant log output

```shell
podman run quay.io/podman/hello
Trying to pull quay.io/podman/hello:latest...
Error: initializing source docker://quay.io/podman/hello:latest: pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io: Temporary failure in name resolution
```

**Comment by benoitf** [comment]
Hello @DaRealCapz are you using a VPN or proxy or something like that ?

could you check the DNS used by the podman machine (`podman machine ssh` command and then inspect `/etc/resolv.conf`

try with a custom DNS like
```
echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
```

**Comment by DaRealCapz** [comment]
Hello, no I am not using VPN. I ran the command but it did not recognize sudo

**Comment by DaRealCapz** [comment]
Hello, tried the command but it only printed the nameserver part.
<img width="308" alt="image" src="https://github.com/containers/podman-desktop/assets/71236784/8e54e2cf-31ef-40fd-a399-aab7c3e86f36">

**Comment by benoitf** [comment]
if you can edit with like `vi /etc/resolv.conf`

**Comment by benoitf** [comment]
and check from the machine doing `podman run quay.io/podman/hello` from the machine

**Comment by DaRealCapz** [comment]
it worked!

<img width="246" alt="image" src="https://github.com/containers/podman-desktop/assets/71236784/6eae3e1f-2338-429d-b561-fec481c0fc59">

**Comment by benoitf** [comment]
so, somehow the DNS used in your WSL configuration are not working inside VMs

**Comment by DaRealCapz** [comment]
So I am only able to perform commands after using ssh?

**Comment by benoitf** [comment]
@DaRealCapz no I think your environment has some DNS entries not working (and then it's propagated to WSL machines)

**Comment by DaRealCapz** [comment]
Ah I see, do you know how I might solve it?

**Comment by benoitf** [comment]
I think issue is related to https://github.com/microsoft/WSL/issues/8365

**Comment by DaRealCapz** [comment]
Will check it out, thank you for your help!
