### ISSUE TITLE
Can't build image if containerfile is not at root on Windows

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#3465]
### Bug description

I wanted to build an image for a Quarkus application generated from code.quarkus.io.
The Containerfile is located at src/main/docker/Dockerfile.jvm

When building from Podman Desktop it fails

### Operating system

Win11Pro

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Generate application from code.quarkus.io
2. run mvnw package
3. Try to build from Podman Desktop (make sure the build context directory is the root of the application

### Additional context

![image](https://github.com/containers/podman-desktop/assets/695993/dc60032d-1034-40d9-9644-7fc5fd4f725c)

**Comment by benoitf** [comment]
looks like a Windows specific issue with backslash/slash path
