### ISSUE TITLE
Make all font properties configurable for terminal

### ISSUE THREAD

**Issue by jberkus** [containers/podman-desktop#3472]
### Is your enhancement related to a problem? Please describe

Currently, the only property for the terminal font which is configurable is size. xterm.js should support other font properties, and exposing them to the user would allow folks to set their terminal to something which is clearly readable to them.

### Describe the solution you'd like

Two phases of enhancement:

1. Expose additional font properties, including font family, weight, and antialiasing in Config UI.
2. Make it possible to access terminal config with the terminal currently open.

**Comment by vancura** [comment]
@jberkus: The font property configuration vision you outlined is now being considered through our Terminal typography enhancement epic (#12572). This specific enhancement focuses on font family selection while preserving the consistency of existing font size and line height controls.

Your two-phase enhancement approach (exposing additional properties first, then enabling dynamic configuration) has guided our UX strategy to ensure backwards compatibility while expanding the feature set.

Thank you.
