### ISSUE TITLE
Missing done button text

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#3485]
### Bug description

After playing Pod/Container from a Kubernetes YAML file, selecting runtime and clicking play, the Done button has no inscription inside it.

![Screenshot_20230810_155238-1](https://github.com/containers/podman-desktop/assets/75624842/6e7a7d8f-e5fe-4a8a-b3ef-2fd4235141ed)

### Operating system

Fedora 38

### Installation Method

Flathub (Linux)

### Version

Next

### Steps to reproduce

Have a container or pod and corresponding YAML file ready. 
Click Play Kubernets YAML.
Select YAML file and runtime.
Click the Play button.
The done button has no text inside it.

### Relevant log output

```shell
N/A
```

### Additional context

N/A

**Comment by benoitf** [comment]
thanks @rostalan for the report

**Comment by benoitf** [comment]
related to this commit
https://github.com/containers/podman-desktop/commit/d70c2c0913eb1642ecd792fc01f8ef32695bb8ce#diff-e6e70c7d38e89fc482cc3ce675e1310c3514e802a4897e3dfa8fcd993134b924

**Comment by benoitf** [comment]
will be closed by https://github.com/containers/podman-desktop/pull/3487
