### ISSUE TITLE
Retina ready icon assets

### ISSUE THREAD

**Issue by bukitoka** [containers/podman-desktop#3493]
### Is your enhancement related to a problem? Please describe

Hi, podman desktop is cool! I think the UI will be much better if the icon updated to be more retina ready (especially on mac, the icon still looks blurry)

<img width="194" alt="Screenshot 2023-08-11 at 11 28 51" src="https://github.com/containers/podman-desktop/assets/47457477/2a62bbbd-5a69-4ff8-8cc9-3c2452233d00">
<img width="972" alt="Screenshot 2023-08-11 at 11 30 05" src="https://github.com/containers/podman-desktop/assets/47457477/90a10aa7-dd6e-4c78-82bf-3a11da75160e">

### Describe the solution you'd like

retina ready icons
Apple design guidelines:
https://developer.apple.com/design/human-interface-guidelines/icons

**Comment by deboer-tim** [comment]
cc @mairin

**Comment by mairin** [comment]
I have these, let me make a fresh separate PR to fix. I had all the OSes in one PR and hit a windows snag, probably better to separate them.

**Comment by mairin** [comment]
@fokusuma https://github.com/containers/podman-desktop/pull/3511 just got merged, so that will address the extension icons. The system tray icon is something I've been working on a bit for a while but it's a little more complex (namely bc I have limited access to Windows for testing atm due to various circumstance.) I have a draft mac-specific PR that I put together quick, would you mind taking a look? It's here:

https://github.com/containers/podman-desktop/pull/3512

Let me know if you need help getting it running to test it.

**Comment by bukitoka** [comment]
Hi Mairin, thanks for the update! the new extension icon looks great!!! 

the systray looks great too, but i can't find the indicator (green when its started, and gray when its not) in you draft ?
screenshot below is from podman-desktop v0.0.202308150015-9556984 and the gray indicator still blurry

🤔🤔

<img width="183" alt="image" src="https://github.com/containers/podman-desktop/assets/47457477/b2a42b9e-d9f9-4f0a-9eaa-7ab192a61ef7">

**Comment by mairin** [comment]
@fokusuma Hm, I didn't touch those, you can see they're still there in my PR branch: https://github.com/mairin/podman-desktop/tree/tray-icons-mac/packages/main/src/assets

Is the circle indicator not showing up at all on your system using my PR branch?

**Comment by bukitoka** [comment]
I just check it, I think thehse circle indicator need to be updated to higher res

<img width="278" alt="image" src="https://github.com/containers/podman-desktop/assets/47457477/658cdf4d-a535-46aa-9dd3-27cbb931a307">

**Comment by mairin** [comment]
@fokusuma Ah ok! I'll work on updating them too :) Thanks for checking!
