### ISSUE TITLE
Uncaught TypeError when pulling an image

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3495]
### Bug description

When **sometimes** try to pull an image, I got this typeError in devconsole. Image is downloaded though...

![image-pull-typeError](https://github.com/containers/podman-desktop/assets/19164299/b7dcb690-4f6d-4878-b91c-d65ca71b7e5d)

### Operating system

windows 10, Fedora 38

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Podman installed and running
2. Do following steps fast
3. Open images -> Pull image
4. type/paste 'alpine' into an input
5. switch to Pull image button using tab, press enter
6. Check console

### Relevant log output

```shell
PullImage.svelte:86 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at b (PullImage.svelte:86:70)
b @ PullImage.svelte:86

```
```


### Additional context

_No response_

**Comment by vzhukovs** [comment]
Tried to reproduce this issue during last several days and didn't see that error message. Feel free to re-open this issue if the problem exists.
