### ISSUE TITLE
podman desktop crashes at startup on Fedora 36 

### ISSUE THREAD

**Issue by kdubois** [containers/podman-desktop#350]
### Bug description

I installed Podman Desktop with Flatpak.  The install succeeds, but when I start the application, it crashes.  The 'normal' podman cli works fine though.  

I also noticed that the information UI is blank on the flatpak dialog (see screenshot below)
![Screenshot from 2022-07-26 11-43-04](https://user-images.githubusercontent.com/373537/180976621-67ded337-122e-4887-9e6e-a9e06c0ff178.png)

### Operating system

Fedora 36 

### Version

0.0.5

### Steps to reproduce

Download latest podman flatpak https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5.flatpak 
Install 
Run

### Relevant log output

See screenshots 

![Screenshot from 2022-07-26 11-22-48](https://user-images.githubusercontent.com/373537/180974278-d06e6878-cd41-4247-b469-474edc62dcf2.png)
![Screenshot from 2022-07-26 11-23-17](https://user-images.githubusercontent.com/373537/180974289-b06cfbda-8e77-4ee1-9eb2-c9854da187f9.png)
![Screenshot from 2022-07-26 11-29-44](https://user-images.githubusercontent.com/373537/180974298-63ef638a-f9d5-448e-8d28-a87bb3def4ec.png)

**Comment by benoitf** [comment]
Hello @kdubois 
thanks for the report

We fixed the issue with wayland in the latest 'intermediate builds'

You should try a pre-release like https://github.com/containers/podman-desktop/releases/tag/v0.0.202207251140-95501ba from  https://github.com/containers/podman-desktop/releases

**Comment by benoitf** [comment]
Duplicate https://github.com/containers/podman-desktop/issues/273

**Comment by benoitf** [comment]
It'll be included in 0.0.6 release
