### ISSUE TITLE
Uncaught in promise Error coming from dev console in preferences

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3503]
### Bug description

I am seeing this error, although nothing seems to be broken. It pops up when I do something in preferences, creating, stopping and starting podman machine.

### Operating system

Windows 10 Professional

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Play around podman machine resources. But it is not exact.

### Relevant log output

```shell
Uncaught (in promise) Error: The provider does not support audit for connection parameters
await (async)
w @ PreferencesRenderingItemFormat.svelte:66
m @ PreferencesRenderingItemFormat.svelte:97
ee @ PreferencesRenderingItemFormat.svelte:366
```

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/3478
