### ISSUE TITLE
Cannot reach ubi8/httpd-24 app endpoint on localhost:8080 with rootless machine on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3504]
### Bug description

I cannot reach the localhost:8080 endpoint of the given image running in container through podman desktop. 

I tried the same in rootful, it worked. 
I tried another httpd image (from docker.io) that runs on port 9000 and it worked on rootless.

### Operating system

Windows 10 Professional

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Create rootless podman machine (default) on windows
2. Pull an image: `registry.access.redhat.com/ubi8/httpd-24`
3. Create a container
4. Open In Browser
5. ASSERT: you can see httpd server index.hml page
Actual result: page is not reachable. 

### Relevant log output

```shell
In the container log output there is this line:

[Fri Aug 11 11:06:24.501600 2023] [cgid:crit] [pid 1:tid 140129240124864] AH01238: cgid daemon failed to initialize
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
is it working with command line ?

**Comment by odockal** [comment]
I tried to change port mapping to 8080:9000, which works. It is like 8080 port has some restriction on my machine. Will try to debug this more.

**Comment by odockal** [comment]
Inside VM I can reach localhost:8080 of the httpd-24 app. Seems like problem is in routing the request through port 8080 from host to VM.

**Comment by odockal** [comment]
Works on another machine as reported by @xbabalov.

**Comment by odockal** [comment]
It is a firefox thing. Edge works nice. Not a bug, local misconfiguration.
