### ISSUE TITLE
Adding a button for copying the kubeconfig of kind clusters

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#3513]
### Description

![image](https://github.com/containers/podman-desktop/assets/42176370/aac0a657-f1c3-4e86-aae8-423c04ad0841)

Adding a copy or view button for kubeconfig.

Current way is to run in terminal `kind get kubeconfig --name {cluster-name}`, would be interested to simplify this and directly offer it in the UI. A lot of people are using OpenLens or other tools to visualize Kubernetes resources.

**Comment by afbjorklund** [comment]
Or why not add it for all kubernetes clusters, instead of just kind clusters ?

* minikube clusters
* lima clusters
* etc

**Comment by axel7083** [comment]
> Or why not add it for all kubernetes clusters, instead of just kind clusters ?

Where do you list all Kubernetes clusters ? It would be in fact a better solution !

Does it need to be implemented by each extension ? Or you want some kind of abstraction and future extension would have to declare a way to get the kubeconfig ? I am not really following

**Comment by afbjorklund** [comment]
Probably using `kubectl config`

**Comment by axel7083** [comment]
![image](https://github.com/containers/podman-desktop/assets/42176370/3fe7bb2c-2f7c-4c5f-bce9-5ab07d6864d3)

Something like here ? In the list of Kubernetes context ?

**Comment by afbjorklund** [comment]
> Or you want some kind of abstraction and future extension would have to declare a way to get the kubeconfig ?

It is somewhat related to other issues, just that it would be good to have the same "button" for all provisioners

* https://github.com/containers/podman-desktop/issues/3385

Instead of a special case just for `kind`

**Comment by afbjorklund** [comment]
> Something like here ? In the list of Kubernetes context ?

Under "Resources" would be fine, the other is just a selection.

Just added a text path in the mockup, a "Copy" button also works

![](https://user-images.githubusercontent.com/10364051/255326155-a42079d6-cd41-4849-82e3-59faae9d6cdc.png)

> Adding a copy or view button for kubeconfig.

**Comment by axel7083** [comment]
> > Something like here ? In the list of Kubernetes context ?
> 
> Under "Resources" would be fine, the other is just a selection.

Yeah but for kind it is not really the same ? And this make it specific to extension ?

![image](https://github.com/containers/podman-desktop/assets/42176370/a5311bb7-d65b-44c4-bde5-305d4060ea72)

**Comment by afbjorklund** [comment]
The buttons are missing, since Podman Desktop doesn't know how to interact with VMs other than `podman machine`

* https://github.com/containers/podman-desktop/issues/3069

So you have to do it through the external CLI (or external GUI), and then it magically shows up (or disappears) in PD


But the "name" and "endpoint" are shared, so would "configuration" be

**Comment by axel7083** [comment]
I drafted a PR with some possible changes to allows the thing you said @afbjorklund
