### ISSUE TITLE
Rootless Podman machine can't restart when multiple machines exist

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#3526]
### Bug description

When I create multiple Podman machines in Podman Desktop, I can't restart the ones with rootless connection. When there's only one rootless machine, it can be restarted. When I swap the rootless connection to rootfull through terminal, it works properly again. 

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install Podman Desktop 
2. Download Podman
3. Initialize Podman machine from Dashboard (or create new rootless machine).
4. Go to Resources and create another machine (doesn't matter what kind of connection).
5. Try restarting the default machine.

### Additional context

![pd machine restart](https://github.com/containers/podman-desktop/assets/57829934/f1c3ee50-12da-4984-9bc5-94dcd48154c0)

**Comment by benoitf** [comment]
it's a dup of https://github.com/containers/podman/issues/16054

**Comment by xbabalov** [comment]
Should I close the issue then?

**Comment by benoitf** [comment]
yes probably as root cause is in podman
