### ISSUE TITLE
Deleting container deployed to sandbox dev context not working properly.

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#3529]
### Bug description

After deploying container to developer sandbox and than deleting it, it does not disappear. Upon force refresh, it disappears for 1 second, after that it comes back for 20 or so seconds, during which it cannot be deleted.It eventually disappears.
![Peek 2023-08-14 17-37](https://github.com/containers/podman-desktop/assets/75624842/3e0b122e-d8cf-44c2-95b1-a0ca74771fb0)

### Operating system

Fedora 38

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Have a container ready.
Press Deploy to Kubernetes button from the drop down on the left.
Press Deploy, wait, press Done.
Go to Pods, click delete on the newly created pod.

### Relevant log output

```shell
N/A
```

### Additional context

N/A

**Comment by deboer-tim** [comment]
Using other images/containers is working fine for me. After clicking delete you see them stop and disappear within a second or two.

Using alpine:latest works identically - but takes 30s. I confirmed if you delete directly from the dev console it sits in terminating state the same 30s before disappearing.

The 1s disappearance after force refresh is just the time it takes to reconnect the UI, so the only real problem on the Desktop side is that we're not showing that a delete is in progress.

**Comment by rostalan** [comment]
Ok, I see, so should I close this issue, or change it to something else (like e.g. an enhancement to show that the container is currently being deleted)?

**Comment by deboer-tim** [comment]
I think it's clear enough, we can just target a fix to show the terminating state/delete progress.

**Comment by deboer-tim** [comment]
I tried making the DELETING state clearer in the UI, which works well for a few seconds - then the pod is still in Terminating state on the cluster but API inside Podman Desktop starts reporting it as RUNNING again. Same behaviour on Sandbox or Kind, investigating further.
