### ISSUE TITLE
Migration assistant from Docker Desktop

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#353]
### Is your feature request related to a problem? Please describe

If Docker Desktop is installed on my machine, I should be able to migrate data from Docker Desktop to Podman Desktop (images,....)

### Tasks
- #1359 
- #1360
- #1361
- #1362

### Describe the solution you'd like

A migration assistant should be proposed or user should be able to launch it

### Describe alternatives you've considered

My need is for images only so I can do it manually though a sequence of:

- `docker save`
- `podman load`

**Comment by mairin** [comment]
Hi @jeffmaury - are you looking primarily to transfer (e.g. migrate the data from Docker Desktop to Podman Desktop) as a copy operation (e.g. leave data in docker but have a copy in podman too) or as a move operation (the data will be moved to podman and no longer reside in docker?) Do you have a use for either or both?

**Comment by jeffmaury** [comment]
My need is to migrate from Docker Desktop to Podman Desktop so theoretically a move operation but as a user I will not trust a provider to do the move so I would prefer a copy

**Comment by rhatdan** [comment]
You could copy images, and I guess export and import containers. Would be a fairly easy bash script to write.

**Comment by deboer-tim** [comment]
Also need to help when you switch (either way) to which you want to use as default (socket).
