### ISSUE TITLE
Compose installed by podman desktop is not working on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3535]
### Bug description

When I run `compose.bat` from the `PATH` I got: `.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/compose.bat up -d
'docker-compose' is not recognized as an internal or external command,
operable program or batch file.
`

I am trying to use podman desktop's compose integration and spin up some example application (awesome-docker/flask).
It might be either bug or I missed the concept how it works, I tried to follow the compose installation process. 

1. Have podman desktop running, podman installed and running
2. Install compose via Compose download button
![compose-install](https://github.com/containers/podman-desktop/assets/19164299/65e66dd0-914e-450a-b10b-bd23913757a0)
3. Make it system wide installation
![compose-install-success](https://github.com/containers/podman-desktop/assets/19164299/63fba459-ad52-4e47-a36c-7dc7baa9cac5)
4. Add installation folder to on the PATH
![compose-wrapper](https://github.com/containers/podman-desktop/assets/19164299/7c3c1261-c40d-4b2d-ab06-ec5a561958c9)
5. Restart the podman desktop
6. For quite a time I see a warning by compose button in status bar stating something like:
`No running container engine. Unable to write a compose wrapper script that will set DOCKER_HOST in that case. Please start a container engine first.`
7. If I wait a long enough or restart compose extension (disable-enable) I will get: 
```Compose is installed and usable with C:\Users\Ondrej\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.compose\bin\compose```
8. I expect to work now on CLI with a docker-compose which should be on a `PATH`, so I try: `$ docker-compose up -d
Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?`
9. Which leads me to the trying of the `compose.bat` executable on CLI which should be at the same folder as installed `docker-compose.exe`:  
```
$ ./../../../.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/compose.bat up -d
'docker-compose' is not recognized as an internal or external command,
operable program or batch file.
```

I am not sure If there is a bug in the `compose.bat` script, docs/guide is misleading, I am doing something wrong. 

### Operating system

Windows 10 Professional

### Installation Method

None

### Version

1.2.1

### Additional context

There is a warning in podman desktop for docker socket compatibility in podman desktop:
`⚠ Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.`

**Comment by odockal** [comment]
There are 3 issues reported on behalf of this one. We might reconsider how to handle this one, probably no need to put it in the next milestone.

**Comment by odockal** [comment]
Issues linked to this one:
* https://github.com/containers/podman-desktop/issues/3563
* https://github.com/containers/podman-desktop/issues/3560
* https://github.com/containers/podman-desktop/issues/3557

**Comment by cdrage** [comment]
Issue will be closed by:
- [x] https://github.com/containers/podman-desktop/issues/3563
- [x] https://github.com/containers/podman-desktop/issues/3560
- [ ] https://github.com/containers/podman-desktop/issues/3557

**Comment by cdrage** [comment]
I'm going to close this issue for now as we are going to update the Windows documentation via the issue https://github.com/containers/podman-desktop/issues/3557 (this issue is duplicated here and https://github.com/containers/podman-desktop/issues/3557).
