### ISSUE TITLE
Pushing local image to the OpenShift Local Cluster does nothing

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#3538]
### Bug description

Trying to deploy  pod created from image to Kubernetes using crc-admin context. For that I assume, I need to push the local image to the OpenShift Local cluster? When trying to do this with Kind/Dev Sandbox, it pops a message, that the push has been succesfull. With OS Local cluster it just doe nothing. As a result, cannot deploy pods or containers created from that image.
![Screenshot_20230815_131356](https://github.com/containers/podman-desktop/assets/75624842/9aabbc83-1a85-434b-81e0-2504f246bb1e)
![Screenshot_20230815_131251](https://github.com/containers/podman-desktop/assets/75624842/57447200-6fff-4a0e-a840-dc5e38994bf5)

### Operating system

Fedora 38

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Have an image, select drop down menu on the right, click Push image to OpenShift Local cluster.
There is no pop-up or message unlike for Kind/Dev Sanbox.

### Relevant log output

```shell
main ↪️ event is 
{status: 'save', id: 'bc80818f28f0d5acc6b4abf1c08d531506e94e1bb9e99366b4e7c52f17989e3a', Type: 'image', Action: 'save', Actor: {…}, …}
Action
: 
"save"
Actor
: 
{ID: 'bc80818f28f0d5acc6b4abf1c08d531506e94e1bb9e99366b4e7c52f17989e3a', Attributes: {…}}
Type
: 
"image"
id
: 
"bc80818f28f0d5acc6b4abf1c08d531506e94e1bb9e99366b4e7c52f17989e3a"
scope
: 
"local"
status
: 
"save"
time
: 
1692098024
timeNano
: 
1692098024497994500
[[Prototype]]
: 
Object
```

### Additional context

There are several issues opened in relation to this one:
1. https://github.com/crc-org/crc/issues/3897 does not allow to push to the OpenShift Local using podman/docker push command we use to push to OpenShift Sandbox cluster
2. https://github.com/crc-org/crc-extension/issues/185 OS specific notification that is not noticeable right away should be replaced by information message used by other extensions and there should be task added in task view to show progress on the push
3. https://github.com/crc-org/crc-extension/issues/186 there is a OpenShift Local status detection issues on linux (Fedora 38 specifically) when `crc setup --check-only` returns error code 2 when crc set up correctly but not started
4. https://github.com/crc-org/crc-extension/issues/187 form that creates new local cluster starts the cluster, but fails to finish correctly

**Comment by dgolovin** [comment]
There seems to be an issues with showing notifications in Fedora 28, whatever I did it does not show up in notification area on fedora, but it worked for me on macOS


![Image](https://github.com/containers/podman-desktop/assets/620330/ee595cff-db07-4c29-9377-bf85f6237685)

Please note, other extensions are using widow.showInformationMessage and it appears as modal message in podman-desktop widow, but crc uses notification and it appears in notification area specific for OS.

**Comment by gbraad** [comment]
> other extensions are using widow.showInformationMessage and it appears as modal message in podman-desktop widow

Are modal messages the better solution? I believe we would solve this as tasks that would show uo in a queue as 'in progress' and 'finished'.

**Comment by dgolovin** [comment]
There is no way to see that task is finished, without opening tasks view. It always the same bell icon.

**Comment by dgolovin** [comment]
When I was investigating the issue on my Fedora 38 host I found multiple other issues that should be fixed in CRC and Extension before this one can be addressed properly (see additional context in issue description).

**Comment by gbraad** [comment]
> I found multiple other issues that should be fixed in CRC and Extension 

@dgolovin Would you be willing to file those? At the moment, I am aware of a single issue; the notification not shown. If anything else, please make sure we can address those.

**Comment by cfergeau** [comment]
dgolovin said:
> (see additional context in issue description)

@gbraad aren't they these issues?

> Additional context
> There are several issues opened in relation to this one:
> https://github.com/crc-org/crc/issues/3897 does not allow to push to the OpenShift Local using podman/docker push command we use to push to OpenShift Sandbox cluster
https://github.com/crc-org/crc-extension/issues/185 OS specific notification that is not noticeable right away should be replaced by information message used by other extensions and there should be task added in task view to show progress on the push
> https://github.com/crc-org/crc-extension/issues/186 there is a OpenShift Local status detection issues on linux (Fedora 38 specifically) when crc setup --check-only returns error code 2 when crc set up correctly but not started
> [BUG]CRC Create New resource form shows empty page as a result if crc is never used before (~/.crc folder does not exist)  crc-org/crc-extension#187 form that creates new local cluster starts the cluster, but fails to finish correctly

**Comment by gbraad** [comment]
I thought he was referring to issues SPECIFIC to the action of pushing to the cluster. It seems https://github.com/crc-org/crc/issues/3897 would be the only one in that case (185 is addressed) Note: asking, as this might have been a regression for pushing an image.

**Comment by dgolovin** [comment]
those are the issues I have created in relation to this one.
