### ISSUE TITLE
Doc: update _Adding an Insecure Registry to Podman Desktop_ to use new configuration file format

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#3549]
Hi,

today I found some time to test this ... and did so on the Podman side (ignoring Podman Desktop for a start).

The new documentation that was added
https://github.com/containers/podman-desktop/commit/b6d1bd77b51d4628bde82037fc78c3a8253c400d#diff-32fcd5d744c9a49f128923566256cc09f1232bf17f3f9e1e114586af2037d21dR46

mentions to add
```
[registries.insecure]
registries = ['example-registry.com']
```

to `/etc/containers/registries.conf`

After I do this, I get an error message:
`Error: loading registries configuration "/etc/containers/registries.conf": mixing sysregistry v1/v2 is not supported`

Reding into this a bit, I think `registries.insecure` is the old way of doing this and 
```
[[registry]]
location = 'foo.bar'
insecure = true`
```
would be better since the rest of the file already uses the new way.

Is this correct or am I missing something here?

_Originally posted by @fschwa in https://github.com/containers/podman-desktop/issues/1653#issuecomment-1660703365_

**Comment by ghost** [comment]
Please see https://github.com/containers/podman-desktop/pull/3406
