### ISSUE TITLE
Add a screenshot capability into a afterAll hook

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3554]
### Is your enhancement related to a problem? Please describe

When some error appears in a beforeAll method, we do not have a screenshot of it.

### Describe the solution you'd like

Extend setup file with a after all method that would take a screen shot when an error appears in hooks.

**Comment by cbr7** [comment]
This seems like a solved problem to me, PW provides screenshots up to the moment when the pdRunner is closed in the afterAll hook so as long as the close() method is called last in the hook we should have video/screenshot/traces for the entire duration.

**Comment by cbr7** [comment]
Closing as solved.
