### ISSUE TITLE
Compose up got stuck on sending tarball with flask compose file on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3563]
### Bug description

This is a issue related to a #3560. Right now, if you switch to a rootful podman machine you will got stuck `docker-compose up` with a `#13 Sending tarball` message from a log.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Prepare everything as mentioned in #3560 except that you spin up a rootful machine.
2. Try to call `DOCKER_HOST=npipe:////.pipe/podman-machine-X docker-compose.exe up -d`
3. Assert: Containers are spin up correctly and marked in podman desktop
Actual result: It gets stuck in `sending tarball`

### Relevant log output

```shell
...
#19 [frontend stage-3 4/5] RUN rm -rf ./*
#19 DONE 0.3s

#20 [frontend stage-3 5/5] COPY --from=build /app/build .
#20 DONE 0.2s

#21 [frontend] exporting to docker image format
#21 exporting layers
#21 exporting layers 0.8s done
#21 exporting manifest sha256:74344854197fa66dfc520d79e8ef177c1ae6f33300afd6d15126af045560b7d1 0.1s done
#21 exporting config sha256:8e50c5588fcc60b7726f1615d9239d2e8fd9fd28f7cc1d0f2834ba58e7e501e6 0.0s done
#21 sending tarball
```

**Comment by benoitf** [comment]
@odockal I guess that if you reproduce without any stuff of Podman Desktop (no GUI, only CLI) probably this issue can be transferred to the podman repository

**Comment by odockal** [comment]
@benoitf Was reported upstream, I wanted to keep a track of issue here. 
@cdrage Today I manage to make it run like a charm on different machine.

**Comment by cdrage** [comment]
After a few back-and-forths troubleshooting with @odockal I'm going to close this for now as it was not re-produceable with PD only, and was only through podman CLI. 

The issue was opened upstream and @odockal was able to manage to make it work on a different machine.

**Comment by SadgeWombat** [comment]
How this issue was solved? I'm facing the same exact issue in the latest version @odockal

**Comment by odockal** [comment]
@SadgeWombat See https://github.com/containers/podman/issues/20379. It is upstream, not on Podman Desktop side. pls follow up there.
