### ISSUE TITLE
Links don't work for local hrefs (e.g. back-links)

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3565]
### Bug description

Backlinks (history) on the Details and Form pages do not work. Nothing happens in the UI when you click on them and there is an error in the log. All other use of Links (e.g. external links on Dashboard and Deploy to Pod page) work fine.

I made the Link component and replaced the <a href=... /> on these pages, and successfully tested manually. Then extended Link to work in two more cases for other pages (external links and on:click), not realizing I had broken the first. Somehow thought I had retested, and even managed to write tests to confirm the new (broken) behaviour.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Just open a page like Container Details or Image Details, and try to click the back link to Containers or Images. The close button still works.

**Comment by odockal** [comment]
I moved the video to a separate issue.

**Comment by rostalan** [comment]
The same issue as described here is on Fedora 38 in 1.3.0.
