### ISSUE TITLE
When on image/container/pod/volume detail, cannot go back to their list.

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#3575]
### Bug description

When inspecting image/container/pod/volume details, cannot return to their list by clicking the corresponding button. It's still possible to go back by clicking the Images/Containers/Pods/Volumes item in nav menu or by closing the details.
![Screenshot_20230817_115830](https://github.com/containers/podman-desktop/assets/75624842/75d33447-1eb8-4ba7-a0de-259caf4847ce)

### Operating system

Fedora 38

### Installation Method

Flathub (Linux)

### Version

1.3.0

### Steps to reproduce

After pulling an image, go to its details, then try to click the Images button on top of the site. / Run container, go to its details, click Containers, does not work.

### Relevant log output

```shell
ncaught (in promise) Error: Invalid URL
Promise.then (async)		
u	@	Link.svelte:22
f	@	Link.svelte:36
```

**Comment by benoitf** [comment]
IMHO it's a dup of https://github.com/containers/podman-desktop/issues/3565

**Comment by rostalan** [comment]
Yes, thanks, seems to be that way, should I close it and comment there, that this is present on fedora as well or has it already been fixed?

**Comment by benoitf** [comment]
close here, and comment in the other issue
