### ISSUE TITLE
Fix e2e smoke test suite instability

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3581]
### Is your enhancement related to a problem? Please describe

It is happening lately and in a huge numbers that e2e smoke testing suite is failing on particular issues. Usually rerunning the test helps. But it is annoying and confusing. 

There are four problems right now
* image not appearing in the in the list of images (could be quay.io rate limit or outage). Also an error in testing code which could have been fixed by @benoitf (thanks!).
* Images/Containers link to open particular page from dashboard not active/actionable or something:
```
 waiting for getByRole('link', { name: 'Images' })
  locator resolved to <a href="/images" aria-label="Images">…</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="flex justify-center p-2">…</div> from <div class="flex flex-col flex-auto fixed top-0 left-…>…</div> subtree intercepts pointer events
```
* Container's table row innerText not resolving and timing out.
* electron app not starting after error happening in the test

### Describe the solution you'd like

Fix these issues.

**Comment by deboer-tim** [comment]
I have zero evidence to support this :), but from the PRs I've run 'electron app not starting' seems to happen more frequently than others, or maybe just more likely that rerunning will fail again. Feels like it becomes a stuck instance until GH cleans it up.

**Comment by odockal** [comment]
@deboer-tim Some truths are out there! :)
1. I am avoiding claiming I know the right cause, since it is unclear, hence using could. 
2. This I am pretty sure is happening since it is in the log: https://github.com/containers/podman-desktop/actions/runs/5879964458/job/15945193866 and it directly leads to a 4. First test times out, next tests do not spawn electron app correctly, or it was not shot down. Why one cannot open a "Image" or "Container" link from dahboard.
3. Some ways how to avoid timeout could help here. Also improving a screenshots taken on a error in test hook could help. (#3554)

**Comment by odockal** [comment]
Seems like some of the issues were resolved by https://github.com/containers/podman-desktop/pull/3678.

I am seeing occasional new flakiness connected to a dev-sandbox e2e test:
```
  FAIL  tests/src/sandbox-installation-smoke.spec.ts [ tests/src/sandbox-installation-smoke.spec.ts ]
Error: Hook timed out in 60000ms.
```
I am suspecting that some wait could be improved.

**Comment by benoitf** [comment]
closing as it seems now it's better
