### ISSUE TITLE
Kind Install button duplicated when extension is reenabled

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3586]
### Bug description

Kind download button is replicated when kind extensions is disabled and enabled again. I would expect kind button to be removed when extensions is disabled, and button to be brought back when reenabled. 
![kind-extension-bug](https://github.com/containers/podman-desktop/assets/19164299/9d93cee7-34c1-4f99-b6cd-45cfa53ef05a)

### Operating system

Linux, windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.3.0

### Steps to reproduce

1. Have no kind on path, Open Dev console in podman desktop
2. Open Settings -> Extensions
3. disable kind extension
4. Assert: Kind install button disappear from status bar
Actual result: button stays there
5. Enable kind extension
6. Assert: button appears again in status bar
Actual result: another kind button appears.

### Relevant log output

```shell
main ↪️ Font podman-desktop.kind-kind-icon.woff2 already registered.
console.<computed> @ index.ts:1506
(anonymous) @ index.ts:1506
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

**Comment by deboer-tim** [comment]
@benoitf sounds like maybe this is the same problem as #3528 / was fixed by #3559?
