### ISSUE TITLE
Blinking screens on images/containers list

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#36]
### Bug description

As a user, when on "Images" or "Containers", I can see the screen blinking and quickly displaying the "empty state" 

### Operating system

macOS monterey 12.2.1 - Intel

### Version

next (development version)

### Steps to reproduce

1. Start podman machine
2. Start a container
3. Go into the application on screen "Images" or "Containers"
4. Wait 10s

--> You'll see the screen blinking and quickly displaying the "empty" state before the list of images/containers is getting refreshed.

**Comment by benoitf** [comment]
related to the issue on podman to get push notification
https://github.com/containers/podman/issues/13491
