### ISSUE TITLE
Winget installation

### ISSUE THREAD

**Issue by hansmbakker** [containers/podman-desktop#360]
### Is your enhancement related to a problem? Please describe

Manually installing packages is tedious.

### Describe the solution you'd like

I would like to automate my package installations on Windows

**Comment by hansmbakker** [comment]
I created a [PR for winget](https://github.com/microsoft/winget-pkgs/pull/68035) to register podman-desktop as a package, [similar to podman](https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RedHat/Podman).

**Comment by benoitf** [comment]
We were waiting to have EV certificates before distributing on Windows helpers like winget, chocolatey, etc.

**Comment by hansmbakker** [comment]
Do you want me to change the PR to draft?

**Comment by benoitf** [comment]
@hansmbakker I don't know, it's still a very valuable contribution. I just don't know if people are fine without certificates

**Comment by hansmbakker** [comment]
Yes I got a Smartscreen warning when installing (like #120) - is there any ETA on when the certificate will be there?

**Comment by benoitf** [comment]
we're in the audit letter process so we're closer but still no ETA :-/

**Comment by benoitf** [comment]
v0.0.6 and v0.0.7 have been published on Winget, closing
