### ISSUE TITLE
avast detect podman_wslkerninst as a trojan win64:evo-gen

### ISSUE THREAD

**Issue by houshym** [containers/podman-desktop#3600]
### Bug description

I installed podman desktop and I tried to install podman. Avast antivirus detect it as a trojan. 
windows installer: 1.3.1
podman version 0.9.0
Avast  version:
  23.7.6074 (build 23.7.8348.789)
virus data base version: 230817-6
UI version:  1.0.774

### Operating system

windows 10 22H2

### Installation Method

Installer from website/GitHub releases

### Version

1.3.0

### Steps to reproduce

install Avast latest version and try to deploy podman

**Comment by deboer-tim** [comment]
Had you installed previous versions of Podman Desktop or is this the first time? We've had several other anti-virus products show Podman Desktop as a false-positive over the past year, and they've been resolver after filing reports with them (see issue #700).

**Comment by cdrage** [comment]
The unfortunate solution is that you'll have to press the "false positive" button / report to avast that it's a false positive.

We've tried and tried again to drop any and all false positives under this issue: https://github.com/containers/podman-desktop/issues/700 but unfortunately the only solution is to mark it as correct.

**Comment by houshym** [comment]
@deboer-tim that was my first deployment, and I did not go through
other issues that I had: 
1- after I put the podman in exception list,  podman and crc installation and initialization was not successful. 
2- there is no way to set the crc location and it uses os disk as installation location
