### ISSUE TITLE
Filtered container list gives "no containers" message which is a bit of a lie

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3602]
### Bug description

I was working on a wordpress container. I have a lot of containers in my container list, as you can see:

![Screenshot from 2023-08-19 22-34-13](https://github.com/containers/podman-desktop/assets/799683/5842a30e-9f67-47d4-aa20-a8a464ad3075)

So I typed "wordpress" in the filter box at the top. And I deleted that wordpress container (going to recreate it with different options, I am debugging something.) Anyway, whoops, I had a minor panic attack after I deleted the wordpress container, because it now says I have no containers on my system:

![Screenshot from 2023-08-19 22-32-59](https://github.com/containers/podman-desktop/assets/799683/dbeed541-66bb-4451-974b-8418ca03ae5b)

But this is a lie :) I only have no containers that match the filter string "wordpress". 

## Suggestion

Add some logic to the empty list message, that if a filter is in place, the user can remove the filter to see their containers (rather than telling them to start a new throwaway example container.)

Here's an idea for how that could look:

![Screenshot from 2023-08-19 22-48-17](https://github.com/containers/podman-desktop/assets/799683/6d159681-f64e-4a0a-84b7-1b59b3ccd9d1)

Maybe this has a scaling feature though if the user types something reallysupercajufrajilistickexpialladocious... in which case maybe something like:

```
No containers matching filter found

No containers matched "reallysupercajufrajilistickexpialladocious"
Not what you expected? Double-check your spelling.
Just want to view all of your containers?
[ Clear filter ]
```

### Operating system

Fedora 38 (fedora-release-common-38-36.noarch) // Podman 4.6.1

### Installation Method

Flathub (Linux)

### Version

1.3.1

### Steps to reproduce

See steps above.

### Relevant log output

```shell
N/A
```

**Comment by deboer-tim** [comment]
I could work on this when I get back.

I don't want to design too much in advance, but we should think about what issue #1264 (more helpful empty states, likely not just cli options) might look like, hopefully there are just a couple patterns we need for empty screens.
