### ISSUE TITLE
Onboarding implementation: "Next" button despite failing install

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3616]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-08-21 at 3 44 47 PM](https://github.com/containers/podman-desktop/assets/6422176/b348e946-1d43-462d-955a-2aab0948a4dc)

The package I have failed to install.

When I received the "Failed installing Podman" error, I expect a "Restart" or a "Cancel" button rather than "Next button below to proceed".

Leads to confusion on what I'm doing. Am I pressing Next to exit? To Restart?

### Describe the solution you'd like

We should have. "Restart from the beginning" button or just "Cancel", no "Next" despite error.

**Comment by lstocchi** [comment]
After the discussion we had yesterday the next button should be disabled and we should add the `try again` so users can restart the onboarding
