### ISSUE TITLE
podman desktop Images pandel  unloading local images.

### ISSUE THREAD

**Issue by TinyZzh** [containers/podman-desktop#3617]
### Bug description

podman desktop Images pandel  unloading local images.

display "No images"

![image](https://github.com/containers/podman-desktop/assets/5763397/6d660bdb-756a-4a05-aa21-da271d29c1db)

Use the cmd.exe podman command. print "docker.io/jenkins/jenkins"
![image](https://github.com/containers/podman-desktop/assets/5763397/961c0ddf-0971-4c87-a450-4403c4efe301)

![image](https://github.com/containers/podman-desktop/assets/5763397/ea6c11cf-e0a7-461b-b1a6-5dab6dc5862b)

### Operating system

windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.3.1

**Comment by slemeur** [comment]
Hi @TinyZzh, thank you for your report.

Could you please run the following command:
`podman system connection ls`

**Comment by themr0c** [comment]
I guess we need to explain in https://podman-desktop.io/docs/troubleshooting/troubleshooting-podman something like:

## Podman Desktop does not display the images or containers from a rootful Podman machine

The rootful configuration for a Podman machine depends on the Podman machine default connection. The default connection can be modified by external events, or when creating a new Podman machine. Podman Desktop might then reconnect in rootless mode, and fail to display the images or containers.

#### Workaround

1. Verify the Podman machine connection:

   ```
   $ podman system connection ls
   ```
   
   If the default connection does not point to the rootful connection, then continue with the next steps.

2. Stop the Podman machine:

   ```
   $ podman machine stop
   ```

3. Set the Podman machine in rootful mode:

   ```
   $ podman machine set --rootful
   ```

4. Start the Podman machine:

   ```
   $ podman machine start
   ```

Is that correct @slemeur ?
