### ISSUE TITLE
podman-macos-helper documentaion is outdated

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#3640]
### Bug description

Current version on pdman-macos-helper is printing out help that does not have commands mentioned on documentation page

https://github.com/containers/podman-desktop/blob/f38537de95c945599d3bb6bcb54e7ffb0834120a/website/docs/migrating-from-docker/using-podman-mac-helper.md?plain=1#L45

It references `run` command that is not mentioned in help output.

https://github.com/containers/podman-desktop/blob/f38537de95c945599d3bb6bcb54e7ffb0834120a/website/docs/migrating-from-docker/using-podman-mac-helper.md?plain=1#L51

```sudo podman-mac-helper --help
podman-mac-helper is a system helper service and tool for managing docker.sock

Usage:
  podman-mac-helper [command]

Available Commands:
  help        Help about any command
  install     installs the podman helper agent
  uninstall   uninstalls the podman helper agent

Flags:
  -h, --help   help for podman-mac-helper

Use "podman-mac-helper [command] --help" for more information about a command.
```

### Operating system

macOS Ventura 13.4 (Apple M1)

### Installation Method

Installer from website/GitHub releases

### Version

1.3.1

**Comment by themr0c** [comment]
I need a macOS user to provide the correct command. Ping @benoitf
