### ISSUE TITLE
Exposing Kubernetes objects in the UI

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3681]
### Discussed in https://github.com/containers/podman-desktop/discussions/3297

<div type='discussions-op-text'>

<sup>Originally posted by **mairin** July 20, 2023</sup>
👋🏻 Hello again :)

A few weeks ago, some of the Podman Desktop contributors participated in a hack week where we worked on fun / experimental ideas. One of the ideas that I worked on with @cdrage was thinking through how we might expose Kubernetes objects in the Podman Desktop UI. We currently support Kubernetes environments through the kind, OpenShift Local, and DeveloperSandbox extensions, but we don't really expose some of the [Kubernetes objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/) in those environments, such as applications and deployments.

This is not really a complete design by any means, but a bit of brain food to start thinking about where such objects might live in the Podman Desktop UI and what bits we might expose and how. 

![Screenshot from 2023-07-20 20-07-33](https://github.com/containers/podman-desktop/assets/799683/43ab1b0b-96a8-4add-b306-4599b739c03d)

We would love to know what you think about this idea:

- Would you find it useful to be able to view Kubernetes objects for the K8s environments we support in Podman Desktop today? 
- Which types of objects do you find the most useful to know more about? 
- What kinds of workflows would you use this kind of information for?

It's also totally okay if you think this mockup is not the right approach, of course, but please share what you would like to see instead! 👍🏻 </div>

**Comment by mairin** [comment]
Next Steps ripped from https://github.com/containers/podman-desktop/discussions/3297

Here's some of the changes / additions to the design & areas for further research that I'm gathering from all this awesome feedback (thank you everybody :) ):

## Research
- [ ] Would be good to develop a list of the most 10 (or however many) common workflows and test out the visual hierarchy to make sure the most common workflows are served well by default without too much drilling down.

## Design
- [ ] Explore a label-oriented way of navigating from a list of pods (or whatever) back to the application oriented view. 
- [ ] Explore how to better integrate kube environments so they don't feel "second class;" could be a matter of rethinking navigation.
- [ ] I love this suggestion wholesale and want to wireframe it out: `"Does anyone really need to see all pods in a single list, or should we do the same there and instead of labels keep them separate with a header between each engine? Maybe have a quick filter on the status bar where you can toggle on and off display of environments, and if there's a Kube environment visible show more items in left nav?"`
- [ ] Wireframe generic / ungrouped views to support when `"deployments miss labels / correct names, or it's stuck in a half-terminating state, or you deploy a Helm chart that's not been configured correctly."`
- [ ] Add "Pods" as a top level in the tabset per cluster; data should include `"how many restarts there are, errors, any warnings, etc."`
- [ ] Add "Nodes" as an item in the list (per cluster?); understanding in most cases there will only be one. (https://github.com/containers/podman-desktop/discussions/3297#discussioncomment-6520020) One node will have details such as os image and container runtime. 
- [ ] Add "Configuration" as a top level in the tabset per cluster (ConfigMaps and Secrets)
- [ ] Add "Policies" as a top level in the tabset per cluster. (NetworkPolicy, ValidatingAdmissionPolicy, LimitRange etc) 
- [ ] Work through how to provide a namespace vs a cluster view (Wireframes needed)
- [ ] Account for how the user can see what images are loaded into a given cluster. And conversely, account for how the user can tell which cluster (or other environment / context / etc.) an image is in in the full images list. (#1450)
- [ ] Display containers and their images per pod (#2800)

**Comment by afbjorklund** [comment]
It would be good to know the main differences between this and the regular [Kubernetes Dashboard](https://github.com/kubernetes/dashboard) webapp?

* https://docs.k8s.io/tasks/access-application-cluster/web-ui-dashboard/

* https://docs.k3s.io/installation/kube-dashboard

> ... images ...

> ... containers ...

Would it be better to add support for CRI as a container engine, to be able to view containerd containers/images?

**Comment by mairin** [comment]
We'll continue this discussion on the discussion board:
https://github.com/containers/podman-desktop/discussions/3297

And open up a new epic with smaller scope issues to start implementation soon.
