### ISSUE TITLE
MessageBox not working as expected

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3692]
### Bug description

MessageBox does not work if you select the first item.

The check in 

https://github.com/containers/podman-desktop/blob/8dffab072b8e34fad504d26b98586862b8fdbdcc/packages/main/src/plugin/message-box.ts#L104

will be evaluated as false when response is equal to 0

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.3.1

**Comment by benoitf** [comment]
I think it might be a regression from my latest change to resolve typescript failures
