### ISSUE TITLE
UI: Icon issues in extensions view

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3696]
### Bug description

When viewing the extensions, the icon logo changes sizes and is hard to view at times.

https://github.com/containers/podman-desktop/assets/6422176/ca669356-702c-4480-917e-b45ac3e8b9fd

### Operating system

mac m1

### Installation Method

None

### Version

1.3.1

**Comment by benoitf** [comment]
I think there is already an existing issue

**Comment by deboer-tim** [comment]
There is already #3460 and #2760.

**Comment by benoitf** [comment]
duplicate issue
