### ISSUE TITLE
Adding new steps to better guide/inform the user in podman onboarding

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3700]
### Is your enhancement related to a problem? Please describe

Comment from Denis https://github.com/containers/podman-desktop/pull/3680#pullrequestreview-1596328759

```
Content of the page is confusing, because nothing was actually done, I already have podman installed, but page says Podman successfully installed. I would rather see the message about podman is already installed.
```

Comment from Mo https://github.com/containers/podman-desktop/pull/3680#issuecomment-1694375830

```
@dgolovin brings up a good point with the "podman successfully installed" header.

When we're saying podman is installed or not installed on these screens... noting they're not Linux 😅

Podman installed == podman client is installed but podman machine is not created?

OR

Podman installed == podman machine is created (but not necessarily running?)

We should have more accurate headings (@themr0c might have opinions too on the phrasing.) I'll try to come up with a list of scenarios and a valid header text for each.

The state reflects the state of the system post podman install via the pop up install window, not before.

Podman client is installed, podman machine is not. "Podman installed but not set up."
Podman client is installed, podman machine is installed, podman machine is not running. "Podman installed but not running."
Podman client is installed, machine is installed and running - ready to go but haven't looked at config. I think in this case we display the preferences (eg start podman on startup) below the success message.
Does this make sense? I think it would be helpful to describe both for linux,mac,win some terms:

installed (what components need to be installed for it to be installed?)
operational (otherwise, having been "set up" - what components need to be available and running)
```

### Describe the solution you'd like

adding new steps based on the state of user machine

**Comment by lstocchi** [comment]
@mairin i opened this issue as the discussion is not actually related to that PR https://github.com/containers/podman-desktop/pull/3680

In my mind `podman install` refers to only the installation of podman. The creation of a podman machine is another step

So the onboarding should also set up a podman machine? 
Should it be `install podman` -> `set some settings` -> `create the default machine` if there is none?

Showing different headers is not a problem as we can create new steps that show up for specific `when clauses`

**Comment by slemeur** [comment]
I would say the sequence should be:
`install podman` -> `set some settings` -> `create and start a podmant machine`

**Comment by lstocchi** [comment]
![image](https://github.com/containers/podman-desktop/assets/49404737/8e3cebb6-c310-4878-94b2-29f97a5e51b6)

1) normal setup: podman install -> setting -> machine creation -> start
2) The cog icon should go to the preferences screen for podman. (Which can be settings > preferences filtered to podman)
3) same as 2
4) setting -> machine creation -> start
