### ISSUE TITLE
Compose settings: Show CLI version number

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3707]
### Is your enhancement related to a problem? Please describe

As per https://github.com/containers/podman-desktop/issues/2523:

We should be able to see the CLI version number of compose.

### Describe the solution you'd like

Implement the "version" part of the UI

**August 31st update:** Awaiting finalized UI/UX to show update mechanism

**Comment by cdrage** [comment]
Progress has been made in the branch: https://github.com/cdrage/podman-desktop/tree/version-cli-api

![screenshot_2023-08-30_at_2 51 20_pm](https://github.com/containers/podman-desktop/assets/6422176/60fb999f-bb1e-4d6f-b4e0-98933dbe242b)

We retrieve the correct CLI by checking the providers and seeing if they match the same ID. We're able to show the CLI version as well as if there is an update version.

**Comment by cdrage** [comment]
Unpostponed as discussions have lead to having the versioning information located in a separate settings page:

#3781

**Comment by cdrage** [comment]
Waiting for https://github.com/containers/podman-desktop/pull/4197 to be merged in and then implementing this.

**Comment by mairin** [comment]
![Settings _ CLI Tools Update Flow](https://github.com/containers/podman-desktop/assets/799683/2e4da666-62bf-4caf-b9be-f0ba4372278a)

These are the update flow mockups and show the component to display the version number. 

Here is the version / update component details:

![Screenshot from 2023-10-19 08-48-34](https://github.com/containers/podman-desktop/assets/799683/70cc0716-e343-4841-9a87-f9a773ba5944)
