### ISSUE TITLE
Onboarding: Be able to create a hyperlink that executes a command.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3710]
### Is your enhancement related to a problem? Please describe

When defining markdown for onboarding, I'd like to make a hyperlink a command, for example:

`Your version is 2.0.0, [Click here to select a version](commandContext.compose.quickpickVersion)`

That would execute the registered command. In this case, initiate the "quickpick" screen to select a version. 

More subtle than a large button as it'll be part of the paragraph / sentence / just a link.

### Describe the solution you'd like

Micromark implementation of https://github.com/containers/podman-desktop/pull/3673 that will execute a command instead of follow a link.

**Comment by benoitf** [comment]
I guess we would need a prefix before the command name like

`[Click here to select a version](command:commandContext.compose.quickpickVersion)`
