### ISSUE TITLE
Clicking "Resources" after "Create new..." on resources should bring you back to Resources.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3719]
### Is your enhancement related to a problem? Please describe

When I am creating a new Podman machine / Kind, I except the little "Resources" on the top left of the screen to bring me back to the Resources page.

https://github.com/containers/podman-desktop/assets/6422176/f3c99678-7863-4b0c-8371-270aadfabb4f

### Describe the solution you'd like

Go back a page to Resources when clicked.

**Comment by deboer-tim** [comment]
I noticed this a couple weeks ago. Now that we have some standard components we should switch this page, likely to use FormPage.

**Comment by deboer-tim** [comment]
The page was switched via another issue, so this problem no longer exists and can be closed.
