### ISSUE TITLE
Remove "Install a new extension from OCI Image" into a new modal

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3720]
### Is your enhancement related to a problem? Please describe

The installation for an extension is out of place compared to other sections of settings.
![Screenshot 2023-08-30 at 11 28 37 AM](https://github.com/containers/podman-desktop/assets/6422176/0b60e3cd-6715-496f-b817-713cb2618844)

### Describe the solution you'd like

It should be moved into a clickable button on the top-right, similar to the new mockup:

![264118872-b564061e-fc7f-4bd6-8641-f56ad9447b47](https://github.com/containers/podman-desktop/assets/6422176/303f815c-0837-48cb-b6d5-288e86c08e70)

The new button will click to it's own modal not a dialog, similar to Desktop Extensions:
![Screenshot 2023-08-30 at 11 25 10 AM](https://github.com/containers/podman-desktop/assets/6422176/4d657691-27a2-4782-976f-980f2fc96aef)

**Comment by afbjorklund** [comment]
When you do this change, please update the documentation:

https://podman-desktop.io/docs/kubernetes/minikube

```diff
- Go to Install a new extension from OCI Image
+ Click ⇩ Install new...
```
