### ISSUE TITLE
Implement UI enhancement for extensions list

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3721]
### Is your enhancement related to a problem? Please describe

See below section:

![264118872-b564061e-fc7f-4bd6-8641-f56ad9447b47 (1)](https://github.com/containers/podman-desktop/assets/6422176/b1d49882-27bf-4d3a-9401-21e62f99207b)

### Describe the solution you'd like

After the completion of:
- [x] https://github.com/containers/podman-desktop/issues/3707
- [x] https://github.com/containers/podman-desktop/issues/3708

Implement the new UI listing the extensions.

**Comment by benoitf** [comment]
there is already an extension spec issue https://github.com/containers/podman-desktop/issues/2170

before proceeding, this one should be done

**Comment by cdrage** [comment]
This is not relevant anymore / resolved / has issue #2170 instead. Please open if anyone else still has this issue.
