### ISSUE TITLE
CLI Tools Section in the UI

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3736]
### Is your feature request related to a problem? Please describe

With many extensions now having CLI tools (kind, compose, podman), we should have a separate section in the preferences that lists all the CLI tools.

### Describe the solution you'd like

Separate tab in the preferences that lists all the CLI tools that are used, if they can updated, etc.

**Comment by afbjorklund** [comment]
Also: minikube, lima, docker

**Comment by cdrage** [comment]
Created https://github.com/containers/podman-desktop/issues/3781 without realizing we already had another issue. I'm going to close this one for now and update https://github.com/containers/podman-desktop/issues/3781 to better accomodate other tools from @afbjorklund comment.

**Comment by afbjorklund** [comment]
Never added any `docker.binary.path` preference.

* #2997

```typescript
export function getDockerCli(): string {
  if (extensionApi.env.isWindows) {
    return 'docker.exe';
  }
  return 'docker';
}
```
