### ISSUE TITLE
Image Tagging Management

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#374]
### Epic domain

Podman Desktop should support the ability to manage tags of images.

- As a user, I'd like to quickly be able to tag an image. 
- As a user I should have the ability to see the different tags of my image and also manage them. I should be able to add, delete or push.

**Comment by jberkus** [comment]
+1 on this feature.  Editing image tags is one of the most tedious tasks due to the limitations of the CLI; this is a place where having a UI would really help users.

**Comment by benoitf** [comment]
we can tag images with edit image from images, so closing as it's fixed
