### ISSUE TITLE
Provide advanced options when creating a container

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#375]
### Is your feature request related to a problem? Please describe

As a user, when I'm creating a container I would love to have the ability to get into more advanced details about the container I'm about to create, so that I can fine tune the container.

### Describe the solution you'd like

The thing that would be the most important to enable first would be:
- Ports
- Volumes
- Env variables
- Working Directory

Later on, there might be interesting option we would like to enable:
- persist bash history
- add a non-root user
- labels

**Comment by trymeouteh** [comment]
Would like to have all the options with _podman run ..._ or _docker run ..._ be available in a GUI form when creating a container. Especially volume management and env variables.

**Comment by slemeur** [comment]
Similar to #499

**Comment by benoitf** [comment]
adding requirements
![image](https://user-images.githubusercontent.com/436777/194555894-47199f4c-829e-47d0-ac7c-e4b0a9e4dfd0.png)

**Comment by dylanmtaylor** [comment]
Copying my comments from #665:

I would like to see a checkbox labelled 'Interactive', which if selected will invoke podman with these options (-it) in the command line:

-i : Keep STDIN open even if not attached
-t : Allocate a pseudo-tty

This will allow for users to interactively use containers like ubuntu:latest or archlinux:latest, through the terminal in the podman desktop app. Focus should be given to the terminal's tty if this is selected upon launching the container.
