### ISSUE TITLE
terminal's container is reporting a different output

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#3767]
### Bug description

If I execute a local terminal and launch nodejs binary the last line is truncated and it works well

but if I use the embedded terminal of Podman Desktop, the output is becoming broken

### Operating system

macOS Ventura

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Launch a node container in background

1. podman run --rm -it -d node

then, connect with Podman Desktop to the terminal

it should display a root terminal like

```
root@b5e041596fec:/# node
```

Then, type node

```
root@b5e041596fec:/# node
```

You're entering into the node interpreter:

```
Welcome to Node.js v20.5.1.
Type ".help" for more information.
> 
```

and now, enter the work `conso`

you should see output becoming like that

![image](https://github.com/containers/podman-desktop/assets/436777/a9f71ceb-59d2-4752-9a8e-ddf171701a13)

then try to end to type the word `console` by adding `l` and `e` keys

and see now the last lines are broken
![image](https://github.com/containers/podman-desktop/assets/436777/0b672fd0-010a-4595-9e73-c4cd9ad92dec)

**Comment by dgolovin** [comment]
The reason for this issue is that exec.resize({w: number, h: number}) should be called every time terminal component is resized. There is another problem with a line replicated multiple times during resize.


https://github.com/containers/podman-desktop/assets/620330/c12be4ec-bc83-41e6-bed7-8658b32e5348

**Comment by dgolovin** [comment]
Original xterm example has the same effect



https://github.com/containers/podman-desktop/assets/620330/12628252-889e-483c-b1fa-4833df045d47
