### ISSUE TITLE
Retrieve proxy configuration from the system

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#3769]
### Is your enhancement related to a problem? Please describe

The proxy configuration has to be manually configured. It may be retrieved from the system (Windows only ?). That may prevent errors reported by users.

On Windows, the Network configuration can be retrieved bu running the following command:

`reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings"`

The output is the following:

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings
    CertificateRevocation    REG_DWORD    0x1
    DisableCachingOfSSLPages    REG_DWORD    0x0
    IE5_UA_Backup_Flag    REG_SZ    5.0
    PrivacyAdvanced    REG_DWORD    0x1
    SecureProtocols    REG_DWORD    0x800
    User Agent    REG_SZ    Mozilla/4.0 (compatible; MSIE 8.0; Win32)
    ZonesSecurityUpgrade    REG_BINARY    A3AACCDDB7CCD901
    WarnonZoneCrossing    REG_DWORD    0x0
    EnableNegotiate    REG_DWORD    0x1
    ProxyEnable    REG_DWORD    0x1
    MigrateProxy    REG_DWORD    0x1
    SecureProtocolsUpdated    REG_DWORD    0x1
    LockDatabase    REG_QWORD    0x1d9cc6d40de1d54
    ProxyHttp1.1    REG_DWORD    0x1
    EnableHttp1_1    REG_DWORD    0x1
    ProxyServer    REG_SZ    http=127.0.0.1:8888;https=127.0.0.1:8888
    ProxyOverride    REG_SZ    <-loopback>
    _FiddlerDirectWrite    REG_SZ    BuggyWinShutdown at 12:23:12 2023-09-05
```

### Describe the solution you'd like

Retrieve the configuration from the system

**Comment by benoitf** [comment]
if it's automatic and defaulting to 'System', there should be still a way to toggle to 'None' or 'Manual'

If not, we could also report a connectivity issue from the tool and in the proxy menu have a 'use System proxy'

we're probably missing a network connectivity check in Troubleshooting page as well (or from the Proxy page itself (like trying to use the proxy when adding it)

**Comment by jbarwick** [comment]
when I configure http://localhost:3128 in the proxy configuration settings, it will NOT work as it doesn't understand 'localhost' as a domain name and it tries to resolve 'http' as a hostname.

**Comment by jbarwick** [comment]
make sure it pulls system proxy on Mac, too.  Not just Windows.

**Comment by jeffmaury** [comment]
In progress
