### ISSUE TITLE
Logo: Switch to septagon 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3779]
### Is your enhancement related to a problem? Please describe

All other projects use septagon within https://github.com/containers (podman, skopeo, buildah).

We are the only one that's hexagon.

I believe that septagon looks better from a design perspective (less pointy bottom that conflicts with the square change instead of the hex).

### Describe the solution you'd like

Switch to septagon.

**Comment by deboer-tim** [comment]
cc @mizmo

We would need to update both the app icon and system tray.

I was just thinking independently today that IMHO our icon is a little on the vanilla side, and not as recognizable as other apps (e.g. VS Code, Slack, Fork, or even Electron). I would love a minor update to make the core part a bit bigger or make it a little punchier/identifiable.
