### ISSUE TITLE
Feature: Add Command-Line Tools section in Settings

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3781]
### Is your feature request related to a problem? Please describe

Mockup:

![Screenshot 2023-09-05 at 2 55 48 PM](https://github.com/containers/podman-desktop/assets/6422176/fd4870bd-225b-4e53-a156-921c60a7c863)

### Describe the solution you'd like

Add a Command-Line Tools section to Podman Desktop in order to show and integrate CLI versioning as well as update indications for all CLI tools as part of the provider such as `kind`, `compose` and `podman`.

### Tools to integrate

- [ ] podman
- [ ] kind
- [ ] compose cli
- [ ] lima
- [ ] minikube
- [ ] docker

### Additional context

Issues:

* https://github.com/containers/podman-desktop/issues/3708
* https://github.com/containers/podman-desktop/issues/3707

**Comment by afbjorklund** [comment]
The list seems to be missing the Kubernetes client, `kubectl` ? (but it is in the screenshot)

Using something like `kuberlr` might help with the crazy k8s version update schedule...

**Comment by afbjorklund** [comment]
Note: the name of the binary is `limactl`

The name of the plug-in is Lima, though.

**Comment by deboer-tim** [comment]
Like the Resources page this is primarily an issue to implement the overall design and some initial CLIs. Each extension would to contribute known CLIs, how to detect versions/update, etc. So, even if some are 'missing' here we can add to continue them later (and once this is far enough along we should track via independent/another issue anyway so this issue doesn't stay open forever)

**Comment by afbjorklund** [comment]
These were just the programs used by the current providers

**Comment by axel7083** [comment]
@cdrage to continue the discussion on the implementation, I drafted an example of implementation to back the command-line tool section.

![image](https://github.com/containers/podman-desktop/assets/42176370/edae9cf9-aa5d-4da6-bee0-be4d3ea9fd97)

The cli tools, and other binaries could be stored in a folder, that would be managed by a BinaryRegistry. Having a dedicated folder, maybe split in two (one added to path for system wide tools) and another for local usage.

> It would also allow podman-desktop to handle the cleanup, and prevents issues with manual installation made by each extensions.

Extensions could register BinaryProvider, which could includes some kind of updater, here I defined an abstract class of `UpdaterProvider` and a `GithubUpdater` could be one of the implementation, handling many things that is often coded mutliple times in the extensions (fetching the releases etc.).

The `UpdaterProvider` could implement some basic method, e.g. `getVersions` returning a list of potentials release we would want to install, the way we need to handle the releases in a generic way, is to make them comparable, we need to know which one is the latest, (can be based on version, timestamp etc.)

The BinaryRegistry would be responsible to handle the events, to check for new updates through the updaters, and return some kind of infos about it that can be displayed in the frontend to let the user choose.


> This is a quick draft, of how I would see based on the requirements and some experiments on my side, I am trying to make is enough abstracted so we could plug more things on it as the needs would evolve. If any feedbacks or questions, I'm here for it :)!

**Comment by benoitf** [comment]
depends on https://github.com/containers/podman-desktop/issues/4120

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.

**Comment by afbjorklund** [comment]
@cdrage : it seems to have scoped out everything, except docker-compose and kubectl ?

**Comment by deboer-tim** [comment]
And kind :). See my previous comment though - this issue was to create the CLI Tools page and make sure it works for the first couple clis (and it has done that), not to cover every cli that we could add. We should be tracking all other cli tools to add via a separate issues.
