### ISSUE TITLE
Replace patternfly spinner with Spinner component 

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3787]
### Is your enhancement related to a problem? Please describe

As pointed out by Charlie https://github.com/containers/podman-desktop/pull/3763#discussion_r1316135442 the Onboarding is using a spinner created by using patternfly. All patternfly spinners should be replaced by the Spinner component.

### Describe the solution you'd like

use the spinner component

**Comment by deboer-tim** [comment]
Looks like pf-c-spinner is used in both Onboarding.svelte and micromark-button-directive.ts (and associated test), can you clean up both of these?

**Comment by lstocchi** [comment]
Not sure if it's feasible to clean the micromark directive as we're outside svelte and cannot inject a component in it or use any svelte command. The directive just returns html code which is not processed by svelte. Idk if there is a way to convert string into a component to render its html

**Comment by deboer-tim** [comment]
Good point. We can do #3797 (redo Spinner w/o PF) first, then likely just need to copy/paste into micromark. We can close this issue with just your Onboarding PR.

**Comment by lstocchi** [comment]
Closing as https://github.com/containers/podman-desktop/pull/3848 was merged
