### ISSUE TITLE
kind cluster does not show up in the UI

### ISSUE THREAD

**Issue by rafaeltuelho** [containers/podman-desktop#3795]
### Bug description

When I create a new `kind` cluster using Podman-desktop UI, it does not appear in the UI.

You can see the kind container created from the CLI:

```
 ❯ kind get clusters
enabling experimental podman provider
kind-cluster
```

```
 ❯ podman ps
CONTAINER ID  IMAGE                                                                                           COMMAND     CREATED             STATUS             PORTS                                                                   NAMES
933bcbc21b5b  docker.io/kindest/node@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72              About a minute ago  Up About a minute  0.0.0.0:9090->80/tcp, 0.0.0.0:9443->443/tcp, 127.0.0.1:55657->6443/tcp  kind-cluster-control-plane
```

But not in the PD UI:

Resources view

<img width="1046" alt="image" src="https://github.com/containers/podman-desktop/assets/39063/3da901d2-be1a-476d-8e13-c4e15cbc5f1f">

Containers view

<img width="1044" alt="image" src="https://github.com/containers/podman-desktop/assets/39063/466948ae-dcfe-401c-b6e0-c97687db1dd6">

### Operating system

MacOS Monterey 12.6.8 (Intel)

### Installation Method

Brew (macOS)

### Version

1.3.1

### Steps to reproduce

1. From the Settings > Resources view, create a new Kind Cluster
2. after a couple of seconds the kind cluster container gest created, but it does not appear in the PD UI.

### Additional context

MacOS Monterey 12.6.8 (Intel)
podman v4.6.1
podman-desktop 1.3.1

**Comment by odockal** [comment]
@rafaeltuelho Thanks for reporting. I managed to reproduce the issue, although there are some discrepancies.

Calling `kind get clusters` returns `No kind clusters found`.

**Comment by odockal** [comment]
Podman desktop show no running containers. There is this one image `docker.io/kindest`. 
`kubectl get pods -A` shows that all pods are up (except one expected). 
Although, I believe that the problem could be either no enough memory (it requires 6 GB of dedicated RAM in podman machine) or that I messed up with podman system connections, I switched from rootless connection to rootfull before creating a kind cluster using cli: `podman system connection default podman-machine-default`. 

So I started over, delete podman machine and create rootful one from fresh. Kind cluster was properly created (pic shows it is stopped, I stopped it. so it is alright):
![Screenshot_20230908_094818](https://github.com/containers/podman-desktop/assets/19164299/9330f7ac-e99f-446d-9952-d8cc87cb26f0)

then I cleaned up everything again and created a default (using dashboard's `initialize and start` option) rootless machine. Even with this 2 GB RAM machine I got kind cluster created:
![Screenshot_20230908_100418](https://github.com/containers/podman-desktop/assets/19164299/7825daa8-1f1a-4420-9a79-fb91178e6b64)

Could it be that If you could please try with a new rootless or with a rootfull machine with more memory?

**Comment by rafaeltuelho** [comment]
@odockal, thanks for looking at this.

So, switching the podman system connection did the trick. I had two connections configured in my podman local env here:

```
podman system connection list
Name                         URI                                                         Identity                                    Default
podman-machine-default       ssh://core@127.0.0.1:61321/run/user/501/podman/podman.sock  /Users/rsoares/.ssh/podman-machine-default  true
podman-machine-default-root  ssh://root@127.0.0.1:61321/run/podman/podman.sock           /Users/rsoares/.ssh/podman-machine-default  false
```

After I set `podman-machine-default-root` to default 
```
podman system connection default podman-machine-default-root
```

it started showing kind and other containers (created by testcontainers) as well.

<img width="439" alt="image" src="https://github.com/containers/podman-desktop/assets/39063/c7cd6d62-b1cf-456a-bed0-058cdc7c11d9">

<img width="988" alt="image" src="https://github.com/containers/podman-desktop/assets/39063/8ba03bd9-6a5f-4db7-91d1-37153b75da7c">


Idk how these system connections affect the podman-desktop UI. I would be happy to understand this better.

Also, it would be nice to have an aid on podman-desktop UI showing and allowing to switch between these system connections (maybe it is worth an RFE here?). What do you think?
