### ISSUE TITLE
Onboarding: "Cancel" button should be a secondary button not a primary button

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3818]
### Is your enhancement related to a problem? Please describe

The styling for the cancel button should be a secondary button and not look like a primary button so the focus is more on Next

![Screenshot 2023-09-07 at 8 39 52 AM](https://github.com/containers/podman-desktop/assets/6422176/ba54d774-967e-4f13-8c88-0120632d2726)

### Describe the solution you'd like

Link style for cancel / not look like a button

**Comment by deboer-tim** [comment]
FWIW, I mis-spoke on the call we were on - it should just be a _secondary_ button which is text with a button-style hover, not a link. If this is a Button component, it's just `type="secondary"`.
