### ISSUE TITLE
Load custom CA certificates from Windows trust store into Podman Machine 

### ISSUE THREAD

**Issue by ThomasVitale** [containers/podman-desktop#3821]
### Is your enhancement related to a problem? Please describe

When using Podman Desktop on Windows (WSL2) in an enterprise setup, there can be different services using a private CA (such as container registries or artifact repositories). In order for Podman to trust the certificates, they can be loaded manually into the Podman machine.

### Describe the solution you'd like

I would like Podman Desktop to take care of loading the same Windows host trust store into the Podman machine, similar to what Docker Desktop does.

### Describe alternatives you've considered

The alternative would be loading the certificates manually after creating a new Podman machine (as documented [here](https://podman-desktop.io/docs/proxy/using-a-proxy-requiring-a-custom-ca)) or asking Podman to skip the certificate verification (as documented [here](https://podman-desktop.io/docs/getting-started/insecure-registry)).

### Additional context

With some guidance, I'd be available to help out with this task.

**Comment by axel7083** [comment]
I really like this possibility since, installing manually is kinda tedious

**Comment by ThomasVitale** [comment]
One additional problem is that even after loading custom CA certificates manually into the Podman machine, builds from Dockerfiles triggered from the Docker CLI will not work because they use BuildKit by default but the CA certificates are not mounted into the BuildKit container running in Podman. Perhaps that deserves a separate issue after fixing this one (i.e. mounting CA certificates from the Podman machine into the BuildKit container).
