### ISSUE TITLE
Make input fields that open system native file explorer to pick up a file or path to accept actual user input and add browse button

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3824]
### Is your enhancement related to a problem? Please describe

It is not possible for user to insert a path into input fields that open only file explorer dialog on `onClick` event. It is also hard to work with these dialogs when writing e2e tests.

Example:
![Screenshot_20230907_162534](https://github.com/containers/podman-desktop/assets/19164299/00f4a9bf-2367-48bc-b43f-b9e591068fcb)

### Describe the solution you'd like

Make such fields accepting text from user input, also please add Browse button so the explorer can be opened and option preserved.

For example this might it look like (although the input here is set to readonly):
![Screenshot_20230907_162642](https://github.com/containers/podman-desktop/assets/19164299/d0974241-1821-4351-8c3a-0f7bf0f5f047)

**Comment by odockal** [comment]
@benoitf I do not recall exactly, but we probably spoke about it somewhere. The thing is, for example, in `Build the image` form, if I make an input field `Containerfile Path` to be editable so I can insert the path, it does not, after typing in the path of the file, trigger the function or action that "uncovers" `Build context Directory` input field. So I would have to somehow trigger this action from within the test. This makes things very complicated for us.

**Comment by deboer-tim** [comment]
This would be easier for testing, but IMHO we should do it for usability anyway. Sometimes I just want to copy/paste a path, and even if the dialog allows pasting, an editable field (shown in proposed image) is a more common pattern.

**Comment by mairin** [comment]
Just as some additional information wrt UX / patterns:

Patternfly does have a mode for file chooser components to allow for manual user input, eg.
https://pf4.patternfly.org/components/file-upload

I checked and GNOME/GTK lets you do this but in a way only available natively in GNOME... basically the browse is just a button and the OS file chooser has a ctrl+L shortcut that converts the top of the filechooser dialog to a place where you can manually enter the path. 

Which makes me wonder depending on the OS platform, do you have the ability to interact with the native OS file chooser in the test framework? If so, it may have a keyboard shortcut to do the same thing?

**Comment by odockal** [comment]
> This would be easier for testing, but IMHO we should do it for usability anyway. Sometimes I just want to copy/paste a path, and even if the dialog allows pasting, an editable field (shown in proposed image) is a more common pattern.

I also like to have two options, sometime I got something in the clipboard cause I work with it, so pasting the path is natural. Anyway, if that would be without any added value for the user I would find other way. (Not like it is not there)

> I checked and GNOME/GTK lets you do this but in a way only available natively in GNOME... basically the browse is just a button and the OS file chooser has a ctrl+L shortcut that converts the top of the filechooser dialog to a place where you can manually enter the path.

> Which makes me wonder depending on the OS platform, do you have the ability to interact with the native OS file chooser in the test framework? If so, it may have a keyboard shortcut to do the same thing?

First thing I tried. But playwright seems to not be bypassing focused system file dialog. So does nothing literally when the file chooser is opened and I try to send typing command through playwright. (Tested on Fedora only). although I know other libraries are able to do so (like selenium's web driver). 

Anyway, I find a way, instead of making the input readable (which does not really work well when other function calls are tied to an outcome of a filechooser), I can make the input of different type (type="file"), which transform input into this:
![Screenshot_20231019_092421](https://github.com/containers/podman-desktop/assets/19164299/330931b0-6e27-46d0-a42f-439b5999369e)
In playwright I can then use `locator.setInputFiles` function to pass a path. It even makes next input for a context building folder visible.  but it also requires another readonly attribute manipulation. 

This is far from ideal, but seems to work. Other option would be to use some other library to send keyboard event to the system, not tight to the browser/app. I am stopping here for now.

**Comment by odockal** [comment]
snippet of the test code to pass through `Build an image` form:
```
  test('Build an image', async () => {
    const containerfileFolder = '/home/odockal/git/podman-desktop-qe/examples/images/';
    const containerfileName = 'ubi8-httpd-24.containerfile';
    const pathContainerFile = path.join(containerfileFolder, containerfileName);

    const navBar = new NavigationBar(page);
    const images = await navBar.openImages();
    await images.buildImageButton.click();

    const input = page.getByPlaceholder('Select Containerfile to build...');
    // change input (select container file) to a file type in order allow to insert a path via `setInputFiles` of the locator
    await input.evaluate(node => node.setAttribute('type', 'file'));
    await input.setInputFiles(pathContainerFile);

    // get build context input locator - missing aria-label so that is why that much code
    const buildContextLabel = page.getByLabel('Build context directory');
    const labelParent = buildContextLabel.locator('..');
    const buildContextDirectory = labelParent.getByRole('textbox');
    await playExpect(buildContextDirectory).toBeVisible();

    // remove readonly attribute to make it editable to insert directory path
    await buildContextDirectory.evaluate(node => node.removeAttribute('readonly'));
    await buildContextDirectory.fill(containerfileFolder);

    const button = page.getByRole('button', { name: 'Build' });
    await playExpect(button).toBeVisible();

    // Workaround to enable build button - here I am bypassing form logic/validation
    await button.evaluate(node => node.removeAttribute('disabled'));
    await playExpect(button).toBeEnabled();
    await button.click();
    const buttonDone = page.getByRole('button', { name: 'Done' });
    await playExpect(buttonDone).toBeVisible({ timeout: 25000 });
    await buttonDone.click();
  });
```

**Comment by deboer-tim** [comment]
FWIW, here's what I think the form should generally look like:
<img width="635" alt="Screenshot 2023-10-20 at 1 10 30 PM" src="https://github.com/containers/podman-desktop/assets/19958075/f1a07a04-29cc-40ab-8c5c-516f605d4dc3">

This allows the current Browse operation or editing the field (including copy/paste), which would make it easier to automate for tests. The only downside atm is that there is no validation of the form, since the file dialogs were guiding you to existing files. I think we could solve this longer-term by exposing some validation from the main package, but to me it's a win even without that because of the text vs Browse and ability to do copy/paste; I can always edit the path and try again if I've made a typo.
