### ISSUE TITLE
Onboarding for podman machine is visible on linux

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3835]
### Bug description

I see new "config" option in podman resource in settings, which leads me a to an podman onboarding but that is clearly intended for a windows/mac platforms.

![onboarding-podman-machine-linux](https://github.com/containers/podman-desktop/assets/19164299/efd82ea7-7bb2-44ba-b2fe-d3eddd9ce313)

### Operating system

Fedora 38

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. build podman desktop locally on linux machine
2. Have podman installed
3. Start podman desktop - check podman is running
4. Go to Settings -> Resources
5. Open gear icon on podman tile
6. "We could not find podman machine -> let's create one" is the description, Next button is available, click it:
7. Warning: `This extension does not provide a component of type "createContainerProviderConnection"`

I guess that we should not provide this option on linux. Or I am missing something.

**Comment by benoitf** [comment]
there are isLinux, isWindows etc properties so yes need to add the steps only for these systems

**Comment by lstocchi** [comment]
Weird, something is not working with the isLinux clause as it's used in the when clause
```
"when": "onboardingContext:podmanMachineExists == false && onboardingContext:isLinux == false"
```
Thanks for the report, i'll give a look at it

**Comment by afbjorklund** [comment]
You might want to document more clearly, why it (`machine`) is not supported on Linux.

**Comment by afbjorklund** [comment]
Here was my onboarding, guess it's Priority Boarding

![pd-podman-setup-next](https://github.com/containers/podman-desktop/assets/10364051/85ccf483-60e1-449a-977a-a68b441b5b50)

I had already started the machine before. On Ubuntu.

https://github.com/containers/podman-desktop/pull/3853#issuecomment-1712914691
