### ISSUE TITLE
when deleting a container, I see start icon being in progress

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#3844]
### Bug description

Starting a container using the UI, then I click on the details and then the delete button

Stop button goes to a start button with a spinner around the start

I would expect that spinner is around the delete button until deletion occurs

### Operating system

macOS

### Installation Method

None

### Version

1.3.1

### Steps to reproduce

https://github.com/containers/podman-desktop/assets/436777/3cba4a38-3a2b-4789-bbbf-23c09cff9943

**Comment by rostalan** [comment]
I noticed that when stopping/deleting container/pod the state of that cont./pod is set to STARTING (i would expect it to be set to STOPPING), could this be related?
