### ISSUE TITLE
[Object object] string in error message when pulling an image from unauthneticated registry

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3845]
### Bug description

Similar use case for pulling an image error message #3496.
This time we got all right, expect we are pulling from from registry that requires authentication.
Error message: `(HTTP code 500) server error - [object Object]`

Another case of such message is pull from correct registry but wrong image: `quay.io/centos7/redis5-centos7`

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce
Scenario 1:
Do not have particular registry added to the available registries.
Try to pull an image from registry that requires authentication, ie: `registry.redhat.io/rhel9/cups`

Scenario 2: (Also HTTP 401 code error)
Pull `quay.io/centos7/redis5-centos7` - there is small typo, correct one is: `quay.io/centos7/redis-5-centos7`

**Comment by jeffmaury** [comment]
That is the error message that is returned in the error object thrown by Dockerode when calling the pull method

See https://github.com/containers/podman-desktop/blob/27ad5f88888d9ec83fdc1ae399e123b59aed06ba/packages/main/src/plugin/container-registry.ts#L840

**Comment by lstocchi** [comment]
As we cannot remove the `[Object object]` because it is returned by dockerode (as Jeff said) i wonder what we can do. Should we clean the error by removing [Object object] from the string?

Adding a valid custom message to an error 500 or 401 seems difficult to me. 
E.g If we add "you are pulling from a registry that requires authentication" to any error 500, it could be wrong in other situations.

So, what should we do?

**Comment by benoitf** [comment]
we could do custom error message like we did here

https://github.com/benoitf/desktop/blob/1f81acb1a2abcb276ced377b8132b849feebeac3/packages/main/src/plugin/container-registry.ts#L867-L868


to fix https://github.com/containers/podman-desktop/issues/3496

**Comment by lstocchi** [comment]
@benoitf so something like 

`access to image "${imageName}" is denied (500error). Can also be that the registry requires authentication.`?

**Comment by benoitf** [comment]
yes it's likely to say what could be the problems but not saying that it's a specific problem so user is not misleading

**Comment by benoitf** [comment]
maybe check with podman folks if we could have better report error

**Comment by benoitf** [comment]
or if we're not capturing the message from the error
