### ISSUE TITLE
Document: package.json titles are generated from key values + capitalization adds spacing

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3846]
### Is your enhancement related to a problem? Please describe

May seem like a nitpick, but there are some undocumented "hidden" features in package.json / configuration settings.

### Describe the solution you'd like

Document that the property: `podman.binary.path` becomes: Path, and if you change it to `podman.binary.pathToBinary` it becomes `Path To Binary` in the title.

```json
    "configuration": {
      "title": "Podman",
      "properties": {
        "podman.binary.path": {
          "name": "Path to Podman Binary",
          "type": "string",
          "format": "file",
          "default": "",
          "description": "Custom path to Podman binary (Default is blank)"
        },
```

**Comment by shelar1423** [comment]
would like to work on this,kindly assign it to me

**Comment by benoitf** [comment]
@shelar1423 I've assigned it to you

**Comment by shelar1423** [comment]
Hey @benoitf , I was just a bit confused so do I have a change the package.json config file and change poddam.binary.path to podam.binary.pathToBinary ?

**Comment by benoitf** [comment]
@shelar1423 here it's just a documentation issue, so append something there https://github.com/containers/podman-desktop/blob/main/EXTENSIONS.md

**Comment by shelar1423** [comment]
> @shelar1423 here it's just a documentation issue, so append something there https://github.com/containers/podman-desktop/blob/main/EXTENSIONS.md

Oh it's documentation.So I'll have to put up the description given in the issue description onto the extension.md doc ,am I right?

**Comment by shelar1423** [comment]
Oh it's documentation.So I'll have to put up the description given in the issue description onto the extension.md or where do I make changes @benoitf

**Comment by benoitf** [comment]
@shelar1423 yes correct, only amend the documentation with what is described in the issue

**Comment by shelar1423** [comment]
@benoitf sure understood,and also is podman taking part in hacktoberfest and will this issue be considered for it ?

**Comment by benoitf** [comment]
@shelar1423 yes we've the label `hacktoberfest` and I've added the label to this issue as well
