### ISSUE TITLE
Compose: Add "docker compatibility enable" button as a configurable button in preferences.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3851]
### Is your enhancement related to a problem? Please describe

Similar to https://github.com/containers/podman-desktop/issues/3810 we should be able to add "docker compatibility enable" as a toggle *button* within preferences. 

See below similar to "system wide install"
![image](https://github.com/containers/podman-desktop/assets/6422176/8cc1fb80-47fe-4fb0-a217-7c9d0d4905b6)

### Describe the solution you'd like

Compatibility enablement moved into preferences rather than through the current status-bar-like enablement that we currently have.

**Comment by cdrage** [comment]
@deboer-tim @lstocchi @benoitf 

Should we have this ONLY in onboarding, or also in settings?

Wanted to clarify as #3810 is a bit different.

I was thinking that we should have this within the extension settings as well so we can easily enable / disable freely.

**Comment by deboer-tim** [comment]
We need a way to get to this after onboarding (or even if it's in the dashboard and then initially dismissed), but to me it still feels odd to have a toggle button in preferences that triggers an install and requires admin privileges. Maybe a button would seem more natural? Might be a good topic for design call.

**Comment by cdrage** [comment]
> We need a way to get to this after onboarding (or even if it's in the dashboard and then initially dismissed), but to me it still feels odd to have a toggle button in preferences that triggers an install and requires admin privileges. Maybe a button would seem more natural? Might be a good topic for design call.

I agree on being able to access it after onboarding, so let's put it in settings as well.

I don't find it odd that the toggle button triggers an install / requires admin privileges. But I do think that we should make the "note" that says "requires admin privileges" more prevalent / bolded to not that this will do something rather than just toggle a setting on / off.

Since the design was finalized weeks ago I'll still proceed with adding tests to the implementation (only thing left to do). We could re-iterate on the design after. My suggestion that maybe we should change the colour / the "toggle" slightly so the user knows it'll be actionable?

@mairin

**Comment by mairin** [comment]
@cdrage ah this is tricky, the design pattern we use in GNOME is the toggle switch is greyed out, and we ask for admin creds before allowing it to be toggled, eg

(See switch below, unlock above)
![Screenshot from 2023-09-26 19-21-48](https://github.com/containers/podman-desktop/assets/799683/befd7e72-85da-4c9f-84a3-81c547bcdebc)

(polkit auth box in GNOME... i dont know if electron has a way to trigger the appropriate platform auth box?)
![Screenshot from 2023-09-26 19-22-45](https://github.com/containers/podman-desktop/assets/799683/4afede1f-a08d-4f62-bad0-ff620d62e25b)

(Now switch is active and usable. closing the app loses the auth and you have to re-auth to access switch.)
![Screenshot from 2023-09-26 19-21-59](https://github.com/containers/podman-desktop/assets/799683/b36b7925-01f8-4541-b2f3-f05daef81493)

Is this a workable flow? If so I can modify the mockups for a future iteration to have an unlock component? (And maybe more info on the payload involved?)

**Comment by deboer-tim** [comment]
We're going to have multiple 'admin' settings, so my only concern is whether technically we can 'unlock' using auth once and then do multiple actions (vs each one needing it independently)? If so +1.

FWIW my hesitation wasn't about admin rights, it's that 'Settings' is normally for changing behaviour (not installing things), and something like 'Install Podman' is normally a button. The two patterns I'm used to seeing are:
- only being able to select user vs system once during the installation flow, or
- separation between the initial 'install/download' flow and later 'configuration' settings.

I think we can legitimately say we're doing the latter, and for Docker compatibility we're fine 👍🏼. For Compose I think I'd be triggered less if we didn't reiterate 'install' so much, i.e. you _already_ downloaded and installed it, and this setting is more 'make available to all users'.

**Comment by cdrage** [comment]
> We're going to have multiple 'admin' settings, so my only concern is whether technically we can 'unlock' using auth once and then do multiple actions (vs each one needing it independently)? If so +1.
> 
> FWIW my hesitation wasn't about admin rights, it's that 'Settings' is normally for changing behaviour (not installing things), and something like 'Install Podman' is normally a button. The two patterns I'm used to seeing are:
> 
> * only being able to select user vs system once during the installation flow, or
> * separation between the initial 'install/download' flow and later 'configuration' settings.
> 
> I think we can legitimately say we're doing the latter, and for Docker compatibility we're fine 👍🏼. For Compose I think I'd be triggered less if we didn't reiterate 'install' so much, i.e. you _already_ downloaded and installed it, and this setting is more 'make available to all users'.

I agree!

For the compose compatibility enable button, I'll make sure that it's in settings AND onboarding.

But obviously for anything "install" related, it'll stay in onboarding. So an example like the "system wide install" button will not appear in settings.

I do agree with you that settings should be about changing behaviour (in this case, compatibility mode) rather than installation.

We should make sure that in the contributing.md doc or in future cases we have it written down somewhere not to add installation / one-time buttons within settings.
