### ISSUE TITLE
Display container's started time

### ISSUE THREAD

**Issue by sstosh** [containers/podman-desktop#386]
### Is your feature request related to a problem? Please describe

I think it would be convenient if we could check the container's started time like `docker-desktop`.

### Describe the solution you'd like

For example, add started time column.
![started-time](https://user-images.githubusercontent.com/95059708/183581704-b2b918e9-33c6-4af5-ac5c-a97f66f13bf2.png)

**Comment by slemeur** [comment]
Thanks for taking the time to report this feedback @sstosh !
