### ISSUE TITLE
Virus total flags release 1.3.1 for macOS als containing malware?

### ISSUE THREAD

**Issue by dirk68-work** [containers/podman-desktop#3861]
### Bug description

If you check the [macOS dmg download](https://github.com/containers/podman-desktop/releases/download/v1.3.1/podman-desktop-1.3.1-universal.dmg) of podman
with Google's www.virustotal.com, one engine [flags the dmg as containing the malware Trojan,OSX.psw](https://www.virustotal.com/gui/file/76aa71c11dd31e1f0c08e6c33b53ec7f8a02b7eeab74612a5885539b7c811b4f).

This may be a false positive but is not very reassuring.

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.3.1

### Steps to reproduce

Download DMG of macOS Release 1.3.1 of podma Desktop from [podman.io](https://github.com/containers/podman-desktop/releases/download/v1.3.1/podman-desktop-1.3.1-universal.dmg)

Check the file for malware by dragging it onto www.virustotal.com.

### Relevant log output

```shell
> 1 security vendor flagged this file as malicious
> Security vendors' analysis: Ikarus Trojan.OSX.Psw
```

**Comment by benoitf** [comment]
hello @dirk68-fu unfortunately we're facing random false positives from time to time from different engines

We're digitally signing the binaries and build occurs on GitHub servers.
