### ISSUE TITLE
Long image names cause problems with width

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3865]
### Is your enhancement related to a problem? Please describe

We have truncated or used other fields in order to limit the width of other views, but if you have a really long image name you need to make the window really wide in order to get to the actions.

<img width="1203" alt="Screenshot 2023-09-11 at 8 25 47 AM" src="https://github.com/containers/podman-desktop/assets/19958075/5eb38492-59ca-4c82-8961-033492c68498">

### Describe the solution you'd like

We should truncate or use some other mechanism so that by default long image names aren't shown in entirety in the Images list.

**Comment by cdrage** [comment]
![Screenshot 2023-10-31 at 6 04 22 PM](https://github.com/containers/podman-desktop/assets/6422176/b1a5c52c-1e4d-4e9e-b17e-cbdec0ee6abf)

Being hit by this in containers page, really long image names with the SHA values.

I think we should use the Tooltip.svelte modal and limit the output to 20 characters? If you hover it'll show the entire image name?

**Comment by feloy** [comment]
> ![Screenshot 2023-10-31 at 6 04 22 PM](https://user-images.githubusercontent.com/6422176/279525990-b1a5c52c-1e4d-4e9e-b17e-cbdec0ee6abf.png)
> 
> Being hit by this in containers page, really long image names with the SHA values.
> 
> I think we should use the Tooltip.svelte modal and limit the output to 20 characters? If you hover it'll show the entire image name?

It won't be very responsive. I think that it is the responsability of the container (either a grid system or a table) to set correct dimensions for the cells, and the content to adapt to these dimensions, and not the other way.

**Comment by deboer-tim** [comment]
Agreed. I have this working better in the new table component (images and volumes atm) where the cell is simply cropped instead of forcing the table to be super wide, but we still need to switch to this component for pods and containers, and I think Charlie is right that we should have tooltips to see the full name or more intelligence in cropping (e.g. using '...') for some columns.

**Comment by deboer-tim** [comment]
My original issue with long image names was fixed via #4844.

Fixing for the containers page is already tracked as part of #4843.
