### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by danny-su** [containers/podman-desktop#3876]
### Bug description

<img width="520" alt="image" src="https://github.com/containers/podman-desktop/assets/12178855/8f69059d-8d72-47d6-b556-3886ded4bdd9">

### Operating system

macOS 13.5.2

### Installation Method

Brew (macOS)

### Version

1.3.1

**Comment by benoitf** [comment]
thanks @danny-su for the report

this is a dup of https://github.com/containers/podman-desktop/issues/3754

it's already fixed in the main branch. 1.4.0 should be released this week (including the fix)
