### ISSUE TITLE
Make the docker socker path configurable (eg. to support rootless docker)

### ISSUE THREAD

**Issue by Zomono** [containers/podman-desktop#3893]
### Is your enhancement related to a problem? Please describe

I would like to use Podman Desktop with my rootless docker installation. In rootless mode the docker socket is no longer located at /run/docker.sock. In my case it is "/run/user/1000/docker.sock". The problem is that the docker socket path is hard coded here https://github.com/containers/podman-desktop/blob/main/extensions/docker/src/extension.ts

This is why Podman Desktop cannot find any docker installation.

### Describe the solution you'd like

A quick solution would be to first read from an environment variable like PODMAN_DOCKER_HOST where to find the docker socket and fallback to the hard coded path if the variable is empty.
This way, the user could define this env variable with flatpak and additional grant access to the real docker socket path.

The even better solution would be to make this path configurable in the settings like it is already done for the podman path.

### Additional context

My system: ubuntu 22.04. Kernel 6.2
Podman Desktop is stalled using Flatpak
docker is installed rootless 
podman ist installed with apt

**Comment by benoitf** [comment]
extension could also scan for `/run/user/<user-id>/docker.sock` (in addition to global socket of Docker)

how did you setup your docker installation ?

also are you using `docker context` command ?

**Comment by Zomono** [comment]
I followed these steps to setup docker: https://docs.docker.com/engine/security/rootless/
Until now I have not used docker context.

I already tried to add /run/user/1000/docker.sock to the permission list of flatpak without luck.
If i create a symlink locally from /run/user/1000/docker.sock to /run/docker.sock, it works.

> extension could also scan for /run/user/<user-id>/docker.sock (in addition to global socket of Docker)

I could not find any code searching for /run/user in the extension file https://github.com/containers/podman-desktop/blob/main/extensions/docker/src/extension.ts. What am I missing?

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/blob/main/extensions/docker/src/extension.ts#L150

here, on linux we could search for other paths if file exists

**Comment by afbjorklund** [comment]
Also discussed here, for making the podman socket path configurable:

* https://github.com/containers/podman-desktop/issues/2861

**Comment by afbjorklund** [comment]
I don't think Podman Desktop supports docker contexts or podman connections, it works directly with hardcoded `unix` paths.

It also doesn't yet support remote sockets like `tcp` or `ssh`, but I think supporting those are in the backlog (EDIT: https://github.com/containers/podman-desktop/issues/279)

**Comment by Zomono** [comment]
> Also discussed here, for making the podman socket path configurable:
> 
>     * [Implement option to view rootful containers on Linux 🐧 #2861](https://github.com/containers/podman-desktop/issues/2861)

I think my issue is a little bit different. I only have one docker installation (rootless) while the other issue has two docker installations at the same time. And my only problem is that Docker Desktop could not find the socket file.

So making this currently hard coded path configurable either by a settings entry or by an environment variable would already solve my issue.

**Comment by afbjorklund** [comment]
Choosing between "system" or "user" socket would probably be enough

It could support more (arbitrary path) for e.g. docker machine, but that is more of advanced feature and not needed for the simple Boolean scenario

**Comment by Zomono** [comment]
But Podman Desktop then still has to "find" the correct socket path, because the path depends on the user and its id.

**Comment by afbjorklund** [comment]
> But Podman Desktop then still has to "find" the correct socket path, because the path depends on the user and its id.

It already knows how to do this, but it is only enabled for Podman and not for Docker (and vice-verse for the other socket)

```typescript
function getLinuxSocketPath(): string {
  // grab user id of the user
  const userInfo = os.userInfo();
  const uid = userInfo.uid;

  return `/run/user/${uid}/podman/podman.sock`;
}
```

```go
  const isWindows = os.platform() === 'win32';
  if (isWindows) {
    socketPath = '//./pipe/docker_engine';
  } else {
    socketPath = '/var/run/docker.sock';
  }

```
