### ISSUE TITLE
Error: [object Object] error message when creating a machine which name is already used

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3898]
### Bug description

There is a `[object Object]` notation in error message. We should print concrete error message string.
![error-object-machine-exists](https://github.com/containers/podman-desktop/assets/19164299/68872b97-6e07-408a-9dc7-8219cb553cdc)

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Have a default machine created on windows in podman desktop
2. Stop the machine
3. Create new machine - use the same name
4. Check the error message

**Comment by feloy** [comment]
Fixed by #4308. @lstocchi could you confirm before I close this issue?

**Comment by lstocchi** [comment]
yes, it can be closed @feloy 👍
