### ISSUE TITLE
Website download linux installation

### ISSUE THREAD

**Issue by pacostas** [containers/podman-desktop#390]
### Bug description

Can not download the Linux file installation, from the download page of the website.  https://podman-desktop.io/downloads

### Operating system

Fedora 36, Chrome Version 104.0.5112.79 (Official Build) (64-bit)

### Version

0.0.5

### Steps to reproduce

Visit the podman-desktop download page https://podman-desktop.io/downloads -> On Linux section -> click on Zip or Flatpak buttons.

**Comment by benoitf** [comment]
hello @pacostas on my side it's working

what is the error that you get on links ?

links are https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5.flatpak or 
https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5.tar.gz

you can also found them from https://github.com/containers/podman-desktop/releases

**Comment by pacostas** [comment]
There is no error on the console or somewhere else. Buttons on the linux section for downloading the .zip file are not clickable. But now I see that the button is working properly so the issue can get closed. I guess you fixed it?

**Comment by benoitf** [comment]
@pacostas I did not touch anything, but it seems that a script is not called (the one computing the links) on some case

**Comment by pacostas** [comment]
Oh, ok. I see...

**Comment by benoitf** [comment]
I'll try to see if can reproduce but it's hard if it's not 100% reproducible

**Comment by pacostas** [comment]
I'll have a closer look these days, so if ever gonna happen again I'll let you know :) Thanks!!

**Comment by pacostas** [comment]
Ok, I found a way to reproduce it on chrome and on firefox. Visit https://podman-desktop.io/ then click on navbar the **Downloads** then the **Podman Desktop** word, then again on **Downloads** -> Scroll down to **linux** section and **flatpack** and **.zip** button will not work.

**Comment by benoitf** [comment]
thanks @pacostas for the steps, reproducing 👍 
I'll be able to look at the issue

**Comment by benoitf** [comment]
@pacostas it's gonna be fixed by https://github.com/containers/podman-desktop/pull/399
