### ISSUE TITLE
Allow to copy files into a container directly from Podman Desktop

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3903]
### Is your enhancement related to a problem? Please describe

Copying a file into a container could be troublesome in some cases. In windows you'll face some error by following the command example in the doc because of some limitation. Problem and workaroud explained here https://github.com/containers/podman/issues/14862. 

### Describe the solution you'd like

It would be awesome if there was a way to open the filesystem on PD, select the file(s) you want to copy, add the location in the container and just click a button.

**Comment by benoitf** [comment]
maybe related to https://github.com/containers/podman-desktop/issues/2801

**Comment by lstocchi** [comment]
yes let's say the #2801 would cover my issue as well. After downloading a file from the container you would have to upload it again
