### ISSUE TITLE
Provide ability to view pods' logs

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#391]
### Is your feature request related to a problem? Please describe

Along with the effort to support running pods from Podman Desktop, as a user I'd to be able to get the logs of the pods.

### Describe the solution you'd like

There are two specific options we should enable:
- the ability to see get an aggregated view of all logs
- the ability to filter for a specific container

**Comment by cdrage** [comment]
Closing this as (part) of it is implemented. Opening up another issue to discuss UX/UI elements for how to filter per-container for pod logs.
