### ISSUE TITLE
Kube context cannot be changed and is not taken into account when Deploying to Kubernetes, new record is not propagated into kube-context in status bar

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3910]
### Bug description

I need to restart the podman desktop (or reenable `kube context` extension) in order to get a new kube context record in.

![kube-context-not-updated](https://github.com/containers/podman-desktop/assets/19164299/60278a42-303c-43fc-bd45-2d641267f102)

Moreover, I cannot switch between different contexts. Also, current kube-context is not applied when I tried to deploy to kubernetes.

![kubecontext-broken](https://github.com/containers/podman-desktop/assets/19164299/e8466160-c69c-4824-8410-3fa36de5f4d2)

### Operating system

Windows 10

### Installation Method

Other

### Version

1.4.0

### Steps to reproduce

1. `rm -rf ~/.kube`
2. Start podman desktop
3. Install Kind
4. Create kind cluster
5. ASSERT: kube-context is automatically updated when I create new resource
Actual result: no kube-context is present upon creation. I need to restart OR manually disable-enable `kube-context` extension

**Comment by odockal** [comment]
A little workaround: Restart podman desktop (do not forget to enable close on exit in preferences).

**Comment by dgolovin** [comment]
Could be fixed with #6406.

**Comment by dgolovin** [comment]
It seems fixed, I cannot replicate any of the issues above after starting without ~/.kube folder and starting OpenShift Local. The context status shows up and everything works as expected.
