### ISSUE TITLE
Updating the OpenShift Local extension to 2.26.0 fails

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#3915]
### Bug description

Before or after initializing and starting the OpenShift Local extension, the option to update to version 2.26.0 fails with an error. The button stays grey unless reloaded.

### Operating system

Fedora 38

### Installation Method

Other

### Version

1.4.0

### Steps to reproduce

Oped PD, go to dashboard, click "Update to 2.26.0" button under OpenShift Local. ﻿

### Relevant log output

```shell
ProviderUpdateButton.svelte:38 Error: s is not iterable
a	@	ProviderUpdateButton.svelte:38
await in a (async)		
u	@	ProviderUpdateButton.svelte:57
(anonymous)	@	lifecycle.js:181
Rk	@	lifecycle.js:181
g	@	Button.svelte:25
```

**Comment by odockal** [comment]
seeing the same:
![Screenshot_20230915_112241](https://github.com/containers/podman-desktop/assets/19164299/e1f15ccc-e5bf-4931-b532-641eedef7966)

**Comment by odockal** [comment]
@rostalan Could you please report that to the crc-extension repo? https://github.com/crc-org/crc-extension/issues

**Comment by rostalan** [comment]
ok, done: https://github.com/crc-org/crc-extension/issues/176

**Comment by odockal** [comment]
@rostalan  please close next time if you move the issue.
