### ISSUE TITLE
KubeUI: Introduce a screen to list the context from a Kube config file

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#3919]
### Is your feature request related to a problem? Please describe

I've repeatedly created Kind servers and never cleaned up their kube config. Likewise, Sandbox has an issue where I need to recreate it and the old kube config is stale. Over time I've ended up with content that Podman Desktop created but has no way to clean up.

### Describe the solution you'd like

We should provide a basic UI to see the list of clusters and contexts, and allow deletion. It should be easy to tell what's local vs remote, and which point to Kubernetes providers within Podman Desktop (i.e. show me which contexts are my Kind or Sandbox or OpenShift Local instance vs random other contexts).

I've been meaning to open this before, but was triggered by #3914 (provide a way to overwrite a context when creating a sandbox instance) since this would be another way of getting out of that situation.

### Additional context

Design is ready in https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/18f3baa5-c6db-81d1-8002-9f756ec487eb?page-id=2419dd66-911a-807e-8003-43a20ad0ffc1

**Comment by cdrage** [comment]
![Image](https://github.com/containers/podman-desktop/assets/6422176/1e467983-a51d-4b7d-9c1a-0252fb3fb956)

To 100% make sure before implementation, it's this page to implement?

Or is it 

![Image](https://github.com/containers/podman-desktop/assets/6422176/3d8b9887-c40f-4594-b687-165b30825bc4)

?

So in order:
- [ ] Initial PR: Basic UI listing context and minor details (name, server, user)
- [ ] Follow up PR: Listing Pods, Deployments, etc.

You mention "allow deletion" but I don't see a delete button for the context.

@mairin @deboer-tim

**Comment by deboer-tim** [comment]
Sorry, that should have been clear. I didn't realize there were two designs and was only looking at the top one. @mairin which do you prefer? kubeconfig could have lots of entries. Several of these labels can be very long, but I think we should use some heuristics to show a short name like we do with ids in a couple other places, so I don't think width is an issue.

My preference would be to expand the PRs a bit :), and here's my priority for delivery:
- Initial PR as above - basic kubeconfig list. We'll already need to deal with broken/unreachable clusters with minimal/no info here.
- Delete action.
- Mapping with known PD Resources. Minimally this could be a visual difference (maybe this is how we get the non-generic icons and nicer names?) and link to Resources page.
- We're also going to have the reverse (e.g. we know about Sandbox but the kubeconfig was accidentally deleted), not sure how we should handle that - maybe we should them here disabled or have some way to add them back?
- More summary info like pod, deployment count.

**Comment by jeffmaury** [comment]
Let's try to make it incremental and simple. That shoud be an epic but the scope of this one is to be able to display the contexts (design to be choosen between the two). Other enhancements (links, delete) will be part of the epic in different issues

**Comment by slemeur** [comment]
Please make this issue an epic and split/narrow the scope with sub-issues.

**First Target**
- We'll focus on ONLY displaying the different contexts from the kubeconfig file. 
- We'll use the list approach, as it allows to better display the information and will better help the user to find a particular context (expect users to have a lot of configuration). It'll be easier to scan a list to find a 
- Navigation to this page, should not be done like in the mockups. We'll introduce this page in the settings in a first stage. "Settings > Kubernetes Contexts"
- There will be no ">" at the top right corner, as we don't have the pages where it would bring the user yet.
- Metadatas about the objects on the cluster are out of scope.

**Second Target: Add actions**
- We allow the user to choose the context he wants to use. (this should be fairly easy as, we already have it under with the kubecontext switcher)
- We introduce the ability to delete an entry from the kubecontext
- Provide an entry in the kubernetes context switcher to "Manage Kubecontext..." which will bring the user to this page.

**To be planned for future iterations**
- Displaying summary information, for pods, deployment that live on

**Comment by afbjorklund** [comment]
Note that kubeconfig is an array, not a single file (but more like PATH).

* https://github.com/containers/podman-desktop/issues/3385

> The `KUBECONFIG` environment variable is a list of paths to configuration files.
> The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows.

**Comment by cdrage** [comment]
> Please make this issue an epic and split/narrow the scope with sub-issues.
> 
> **First Target**
> 
> * We'll focus on ONLY displaying the different contexts from the kubeconfig file.
> * We'll use the list approach, as it allows to better display the information and will better help the user to find a particular context (expect users to have a lot of configuration). It'll be easier to scan a list to find a
> * Navigation to this page, should not be done like in the mockups. We'll introduce this page in the settings in a first stage. "Settings > Kubernetes Contexts"
> * There will be no ">" at the top right corner, as we don't have the pages where it would bring the user yet.
> * Metadatas about the objects on the cluster are out of scope.
> 
> **Second Target: Add actions**
> 
> * We allow the user to choose the context he wants to use. (this should be fairly easy as, we already have it under with the kubecontext switcher)
> * We introduce the ability to delete an entry from the kubecontext
> * Provide an entry in the kubernetes context switcher to "Manage Kubecontext..." which will bring the user to this page.
> 
> **To be planned for future iterations**
> 
> * Displaying summary information, for pods, deployment that live on

Sounds good! So I see that https://github.com/containers/podman-desktop/issues/4416 is opened, we will mark https://github.com/containers/podman-desktop/issues/4416 as an epic and we will use this issue as the "First Target" step that you outlined above.

**Comment by mairin** [comment]
Here is the updated contexts list mockup (disregard the grid one) (updated 26 Oct 2023):

![Screenshot from 2023-10-26 08-37-48](https://github.com/containers/podman-desktop/assets/799683/03cbc672-e46e-4155-93fd-71941d247df7)
