### ISSUE TITLE
extensions: adding tabs/actions to containers list

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#3938]
### Custom actions (command?)

I am trying to create an extension that can add actions to specific container type (pod, compose, etc.)

![image](https://github.com/containers/podman-desktop/assets/42176370/56a06ea2-aced-4a97-8fd2-013ea398b308)

### Replace/add tabs

Furthermore I would like to know if adding custom tab though an extension is possible. Even replacing an existing to enhance some features if possible.

![image](https://github.com/containers/podman-desktop/assets/42176370/1a18a939-1f7f-4aca-91c8-42c86a155dcf)

### Describe the solution you'd like

I couldn't find a way to do it using the extension api (maybe I did not investigate enough?).

Adding a declarative way in the package.json to add/replaces actions/tabs, using the `when` condition.

### Describe alternatives you've considered

The only alternative is to add manually the tab actions in the podman desktop code, which is not great.

### Additional context

I am looking to enhance the `Generate Kube` which is not working well on docker-compose. And I want to add a default extension using the [kompose](https://github.com/kubernetes/kompose) project.

**Comment by benoitf** [comment]
hello @axel7083 I don't know if it's supported for containers

but for images list, for example there is an extension point 
https://github.com/containers/podman-desktop/blob/main/extensions/kind/package.json#L70-L75

and then when rendering items, it checks
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/ImagesList.svelte#L123

I think it should match what you may want to do ?

**Comment by axel7083** [comment]
> hello @axel7083 I don't know if it's supported for containers
> 
> but for images list, for example there is an extension point https://github.com/containers/podman-desktop/blob/main/extensions/kind/package.json#L70-L75
> 
> and then when rendering items, it checks https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/ImagesList.svelte#L123
> 
> I think it should match what you may want to do ?

Yeah that match for the first part !! Thanks 

Another question, having an ui is supported when using Docker Desktop extension format, is it planned to add the possibility to have an ui in podman desktop extensions as well ?

**Comment by benoitf** [comment]
for the UI part we could imagine  a `createWebviewPanel` API but for now we didn't added it.

It's great b/c you can provide custom UI but then sometimes it doesn't feel well integrated (as it's not part of the user workflow). For example you might expect to find a button 'scan image' in the image list, not to go to a separate 'Scanning' page where you see again a list of images using a different UI/layout with only a single button `scan`

It's like a pandora box. For now we tried to enrich the API to let extension plug at different places and the extension providing metadata and Podman Desktop rendering the UI
