### ISSUE TITLE
Provide configuration option to always start Podman Desktop at startup

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#394]
### Is your feature request related to a problem? Please describe

As a user, I'd like to be able to define Podman Desktop to always start when I'm starting my computer. 

### Describe the solution you'd like

In the configuration of the application it would be nice to be able to configure the startup settings to allow a user to define:
- starting Podman Desktop at each computer startup
- starting podman-machine along with starting Podman Desktop

**Comment by benoitf** [comment]
duplicate https://github.com/containers/podman-desktop/issues/225
