### ISSUE TITLE
Self-update and Notification for Podman

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#395]
### Is your feature request related to a problem? Please describe

When there is a new version of Podman or Podman Desktop I'd like to be notified a new version is available.
At the moment, it is only at startup that we check if there is a new version that is available. 

### Describe the solution you'd like

- Check every day that if a new version is available
- Display a notification inviting the user to restart Podman Desktop

**Comment by cdrage** [comment]
https://www.electron.build/auto-update.html

**Comment by cdrage** [comment]
WDYT @mairin  ? If the software has been on / online for more than 12 hours, alert the user on the bottom UI/UX bar? We'll have to figure out a way to "nudge" the user that there is an update available without being overly intrusive.

**Comment by mairin** [comment]
@cdrage For users who start fresh, I think we notify them via a dashboard notice right? So for these users who've been running say 12h straight and haven´t restarted to see the dashboard... yes, maybe we give them a nudge on the bottom bar, and if they click on it to get more info, we bring them to the dashboard to see the notice with details / a button to start update / etc there?

Some form of content we would probably want to have for that messaging is to note to the user the impact on their workloads of restarting the podman desktop UI, if it would stop their containers or whatever. (Might not be obvious to every user.)

**Comment by cdrage** [comment]
From the standup:

- Going to implement a very simple UI / UX notification (small orange button?)
- Every 12 hours / timer / long running background task to check to see if there's an update available and turn icon to orange / etc.
