### ISSUE TITLE
Fonts: Be able to choose fonts, add OpenDyslexic, Comic Sans, B612 and Atkinson Hyperlegible.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3965]
### Is your feature request related to a problem? Please describe

We should add the ability to be able to choose what font to use within Podman Desktop.

Personally I find the default font difficult to read sometimes when there is a lot of content on the page and I'd suggest we add super-legible fonts such as B612 or Atkinson Hyperlegible.

I also personally showed Podman Desktop to a LUG (linux users group) and a user suggested adding OpenDyslexic and Comic Sans as Podman Desktop was the only program that they couldn't customize (others such as visual studio, command line and web browser they could).

### Describe the solution you'd like

Be able to choose between the:
- Default
- OpenDyslexic (open source dyslexia)
- Comic Sans (popular amongst dylexia community due to it's spacing)
- B612 (hyper legible font for aircraft interfaces)
- Atkinson Hyperlegible (recommended by hackernews comments for interface design)

**Comment by benoitf** [comment]
I guess here it should list/ be able to choose fonts from the system.

Initial implementation should let customize the global `fontFamily`

**Comment by mairin** [comment]
some notes from chat discussion:

- opendyslexic, b612 and atkinson hyperlegible are all open licensing. comic sans isn't, so we might not be able to offer that if we shipped with or pulled down from the web any fonts  (a different matter if local to the user)
- https://fonts.google.com/specimen/Comic+Neue is an OFL font that is the closest I know of to comic sans
- maybe having a special mode / flag with a font we carry (just one maybe) for these situations... in case for example you're working on a locked down system you cant install custom fonts on or having to use someone elses machine for whatever - i would pose it in terms of "accessible display mode" or something... in terms of the use case
- having them be pre-bundled as for example... "here are 5 fonts to choose from we know look good on podman desktop", and the rest system fonts would be good. (cdrage)
- I think we might over-engineer the things by bundling fonts (which of course will never match user expectation) while using the font that the user has would solve the issue (fbenoit)
