### ISSUE TITLE
https://podman-desktop.io/ docs page 404

### ISSUE THREAD

**Issue by NucleaPeon** [containers/podman-desktop#3978]
### Bug description

Not sure where this bug belongs, as I don't see source for your main website, unless this is another type of issue like "enhancement". Please forward this along to whomever needs to see it.

Using the podman-desktop webpage (from the core values page), I navigated to the Getting Started link at the bottom of the page and got a 404 page not found error. Looks like the url is incorrect.

![Screenshot_20230919_183523](https://github.com/containers/podman-desktop/assets/1475151/2cef53a4-d598-4466-92cc-91573febff68)

### Operating system

Gentoo Linux amd64

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

From https://podman-desktop.io/core-values, go to bottom of page to the "Getting started" link and click on it.
Resulting page url is https://podman-desktop.io/docs/getting-started/getting-started

### Additional context

Using Brave browser

**Comment by afbjorklund** [comment]
Now in https://podman-desktop.io/docs/intro#getting-started

**Comment by odockal** [comment]
Interesting, if I open a link in a new tab (CTRL + click), it redirects to the https://podman-desktop.io/docs/working-with-containers, otherwise it gets 404. 

Anyway, thanks @NucleaPeon  for reporting.

**Comment by themr0c** [comment]
Weird behavior indeed, clicking on the link generates a 404, but browsing directly to the URL the redirection works. The link to Compose was broken too. That might explain hits to the /404.html page, that are difficult to troubleshoot with a production on GitHub pages that does not give access to raw web server logs.

Both links fixed now.

Lessons learned: the docusaurus porduction build does not catch all broken builds. Maybe for time for proper link checks with htmltest?

**Comment by NucleaPeon** [comment]
That is a weird issue. Glad I could help! Thanks for your hard work.
