### ISSUE TITLE
Support for Mac with Silicon chips (Apple)

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#4]
## Description
The solution should be available to mac users with silicon/apple based chip. 

## Acceptance criteria
- Container Desktop is starting and all its components (tray and dashboard) are properly integrated:
  - The tray is properly integrated in the mac toolbar
  - The dashboard is running as an application natively integrated
- CI is setup, configured to test the tool on the target OS

**Comment by benoitf** [comment]
binary provided for mac M1(arm64)
