### ISSUE TITLE
UI Design guidelines

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#400]
### Is your enhancement related to a problem? Please describe

Needing consistency across screens and dialogs in visual design.

### Describe the solution you'd like

We need a set of guidelines / model screens for the visual design of Podman Desktop.

**Comment by mairin** [comment]
Note the GitLab for this work is here:
https://gitlab.com/fedora/design/community-design-team/issues/-/issues/21

**Comment by deboer-tim** [comment]
The majority of this is complete and documented, or conventions established in code. Closing this overarching issue, will open new issues for anything remaining as it comes up.
