### ISSUE TITLE
Display a command palette

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4011]
### Is your enhancement related to a problem? Please describe

it would be nice if all commands exposed internally and by extensions could be displayed so we can invoke them from a single place.

### Describe the solution you'd like

Command palette that would display all commands and let's invoke them

**Comment by deboer-tim** [comment]
Likely a follow-on feature, but it would then be nice to tie commands to keys or have a UI element to run a frequent command.

Next, macros. ;-)
