### ISSUE TITLE
image pulling progress

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4014]
### Is your enhancement related to a problem? Please describe

When dealing with medium/bad connection, the pulling of images using (ImagesList-> Pull an image) can be very long.
If we change the page of pulling, we have to way to go back checking the progress.

### Describe the solution you'd like

Adding in the ImageList, an item for the current pulling images.

**Comment by benoitf** [comment]
for long tasks, now they can register to the notification/tasks (🔔 icon in the statusbar)

so pull image should register item there so you can resume to see the status

**Comment by axel7083** [comment]
> for long tasks, now they can register to the notification/tasks (🔔 icon in the statusbar)
> 
> so pull image should register item there so you can resume to see the status

Do you have an example of the usage of the notification ? Or is it in documentation so I can look it up quickly

**Comment by benoitf** [comment]
you have that used when you do a 'build image'

Inspect https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte , then https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/image/build-image-task.ts  and https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/stores/tasks.ts

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/stores/tasks.ts#L54

**Comment by axel7083** [comment]
Does the task support indeterminate progress ? I tried experimenting with it without providing a value for the progress and get the following result:

![image](https://github.com/containers/podman-desktop/assets/42176370/84ca028b-2177-4ba7-854b-8c55e3690fa3)


It is pretty hard to calculate a `progress` when pulling an image, and having a task for each layer is too annoying and ugly.

**Comment by benoitf** [comment]
no indeterminate support I think. (as you see ;-)

so yes podman API or docker API makes the "progress" really hard to be computed while the registry API provides all the data like number of layers, size of layers, etc.

I see no issue adding support for 'unknown' progress but I still believe our ultimate goal is to provide a unified progress bar.

We have support for registries or fetching layers now so we could inspect that before asking the compat API and then have a nice progress.

**Comment by axel7083** [comment]
Okey, adding a way to return to the progress seems to be more complicated that it seems.

First, there is no unique url/identifier to go back. When pulling an image using the `window.pullImage`, it send a callback, and this callback is in the svelte component of PullImage, but even after being destroyed, it is still being called. The callback is responsible for printing the stuff to the terminal logs.

When going back to the page, a new component is created, therefore, we cannot get re-display the content. We need to find a way to use a unique identifier, maybe the one used by the `onDataCallbacksPullImageId`, and replace the old callback with the new one. (But maybe??? some data will be lost and we will not be able to get the history.. ?)

**Comment by axel7083** [comment]
Some ideas, after digging a bit in the build images and pull images.

Wouldn't make it more sense to create a subscriber/unsubscriber system when building/pulling an image, something than can be removed in onDestroy() of a component ?

What I would be thinking is, in the current implementation, they are not way, when leaving the pages, to know what is happening in background. what I think about is something like

#### Client side

```typescript
const requestIdentifier: string = await window.pullImage(...) // return before pulling the image
// We register our callback 
disposable = windows.subscriberPullingEvents(requestIdentifier, callback)

....
onDestroy() {
    disposable.dispose();
}
```

And anywhere from the code we could call some method let's say `windows.getPulling()` returning some kind of PullingInfo array with the informations about them.

> This could be also applicable to the build process.

**Comment by benoitf** [comment]
we're adding items to a store so it's persisted so other process can subscribe/display/restore to the view

**Comment by axel7083** [comment]
> we're adding items to a store so it's persisted so other process can subscribe/display/restore to the view
Do you mean the following store ?

https://github.com/containers/podman-desktop/blob/ac4b665e2013fd18bdd5bd46dc3aa372c74b2731/packages/preload/src/index.ts#L290

It does provide a way for other processes to know what images it corresponds, not from what I understand, maybe I misunderstood some stuff.

But the information (id -> callback) is not stored, but encapsulated and used by the server here to send events

https://github.com/containers/podman-desktop/blob/ac4b665e2013fd18bdd5bd46dc3aa372c74b2731/packages/main/src/plugin/index.ts#L981-L993


The only workaround I find to avoid changing too much code, is to replace the `key` of the `onDataCallbacksPullImage` by the actual image id, and add a :param in the url, that contains it. Therefore we can replace the callback when re-instanciated the new view, and get the events send by the server

**Comment by axel7083** [comment]
Closing in favour of https://github.com/containers/podman-desktop/issues/5810
