### ISSUE TITLE
blog: missing media in Release 1.4 blog post

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4027]
### Is your enhancement related to a problem? Please describe

Linkchecker spotted this 404 error: Parent URL https://podman-desktop.io/blog, line 21, col 5591 -> Real URL   https://podman-desktop.io/img/blog/podman-desktop-release-1.4.webp.

This is the image declared in the blog post front header.

The file does not exist in the repository.

### Describe the solution you'd like

Replace by an existing media.

**Comment by themr0c** [comment]
@jeffmaury as you wrote the blog post, do you know which media should replace the missing file?

**Comment by benoitf** [comment]
website/blog/img/podman-desktop-release-1.4/juggling.png
