### ISSUE TITLE
bug: building website: Cannot find module 'prism-react-renderer/themes/github'

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4033]
### Bug description

When using yarn install then yarn start, on the `website/package.json` I am getting the following error

> Cannot find module 'prism-react-renderer/themes/github'

According to the following comments https://github.com/facebook/docusaurus/issues/8940#issuecomment-1532573496 when using `prism-react-renderer` v2, the import `require('prism-react-renderer/themes/github');` need to be changed to `require('prism-react-renderer').themes.github;`

My Node version is 18.

### Operating system

Windows 11

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

```
yarn install
yarn start
```

**Comment by benoitf** [comment]
hi @axel7083 , in which folder are you executing `yarn start` , in `website` ?

**Comment by axel7083** [comment]
the website folder, is it wrong ?

**Comment by benoitf** [comment]
I tried on a fresh clone and I don't reproduce :-/

```
$ cd website
$ yarn start                                                                                                                                                                                                               yarn run v1.22.19
$ docusaurus start
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/

✔ Client
  Compiled successfully in 8.30s

client (webpack 5.76.1) compiled successfully
```

**Comment by axel7083** [comment]
I will try to reproduce again, maybe my clone is not clean

**Comment by benoitf** [comment]
I suspect to be a Windows/path issues (as I don't reproduce on macOS and CI on Linux)

**Comment by axel7083** [comment]
Okey closing as I cannot reproduce on clean clone
