### ISSUE TITLE
podman-desktop cannot find podman installed using scoop

### ISSUE THREAD

**Issue by ottuzzi** [containers/podman-desktop#404]
### Bug description

I installed podman using scoop[1] and podman-desktop cannot find it:

![image](https://user-images.githubusercontent.com/925383/184907208-83688e0e-65c0-4fee-b36a-493bc521579d.png)

It looks like it is looking for podman cli using a fixed path and not looking for it in the path :)

![image](https://user-images.githubusercontent.com/925383/184907544-2fe5af78-56d3-4835-9877-fb89d3fa3c7e.png)
Podman cli is installed and correctly working on my system.

Is there a way to configure podman-desktop to search for podman on a different path?

[1]https://scoop.sh/

### Operating system

Windows 11

### Version

next (development version)

### Steps to reproduce

Install podman using scoop and then try to manage it with podman-desktop

**Comment by benoitf** [comment]
hello @ottuzzi 
thanks for reporting the issue.

For now yes it was looking for podman.exe into `c:\Program Files\Red Hat\Podman` as it's where the official installer (msi) is installing the software.

But as it seems there is a scoop package installing somewhere else, then we need to adapt the path.

Current workaround would be to install podman with the .msi installer https://github.com/containers/podman/releases/download/v4.2.0/podman-v4.2.0.msi
