### ISSUE TITLE
Onboarding: If "when" used for configuration value, but references in onboarding, it will still show.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4055]
### Bug description

For onboarding, if you have a value for "when" for a configuration value (for example):

```json
    "configuration": {
      "title": "Compose",
      "properties": {
        "compose.binary.installComposeSystemWide": {
          "type": "boolean",
          "default": false,
          "scope": ["DEFAULT", "Onboarding"],
          "hidden": true,
          "when": "compose.isSystemWideInstalled == false",
          "description": "Install system-wide instead of just your user directory, so compose can be accessed on the command line. If you need to remove it system-wide, type 'whereis docker-compose' in the command line and remove it from that location. Note: You will be prompted for system privileges when enabling this. "
        }
      }
    }
```

And you reference in content:

```json
    "onboarding": {
      "title": "Compose Setup",
      "enablement": "true",
      "steps": [
        {
          "id": "composeSettings",
          "label": "Compose Settings",
          "title": "Compose Settings",
          "content": [
            [
              {
                "value": "${configuration:compose.binary.installComposeSystemWide}"
              }
            ]
          ]
        }
      ]
    },
```

It will still show the configuration value despite "when" being applied to the configuration. 

### Operating system

mac m1

### Installation Method

None

### Version

1.4.0

**Comment by cdrage** [comment]
@lstocchi What do you think? Is this something we should implement or too much of an edge-case.

I would assume that adding it to `content` is more of a user-error in creating the `package.json` rather than following what `when` does?

I'm debating about just closing this issue.

**Comment by lstocchi** [comment]
It makes sense to me, the onboarding should respect the when clause for the imported config...  but as you're implementing https://github.com/containers/podman-desktop/pull/4057 and we can achieve the same by adding the when clause in the item, we can give it low priority.

**Comment by cdrage** [comment]
> It makes sense to me, the onboarding should respect the when clause for the imported config... but as you're implementing #4057 and we can achieve the same by adding the when clause in the item, we can give it low priority.

I agree! I'll mark this as low priority, I've opened up https://github.com/containers/podman-desktop/pull/4108 now so we can at least use that.

**Comment by cdrage** [comment]
This is not relevant anymore / resolved. Please open if anyone else still has this issue.
