### ISSUE TITLE
Unable to install kind

### ISSUE THREAD

**Issue by JackyAnn** [containers/podman-desktop#4058]
### Bug description

Apple M2 Pro
Unable to install kind binary: Error: Command failed: ./applet /bin/sh: ./applet: Bad CPU type in executable

### Operating system

MacOS 13.5.2 (22G91) Apple M2 Pro

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

**Comment by afbjorklund** [comment]
You can also install it yourself, ahead of time: https://kind.sigs.k8s.io/docs/user/quick-start

```
brew install kind
```

**Comment by jeffmaury** [comment]
Cannot reproduce with 1.5.3, feel free to reopen
