### ISSUE TITLE
bug: podman-desktop lose connection to engine when loading very large image to kind

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4060]
### Bug description

While I was working with some large Container image (15G+), I used the `load to kind` option, and a few seconds later, podman-dekstop was not able to list contains, 

![image](https://github.com/containers/podman-desktop/assets/42176370/8e9df420-4050-4011-9f1d-b02f533ac520)

Even if I am able to run in a terminal `podman run hello-world` I get the following screen on the dashboard

![image](https://github.com/containers/podman-desktop/assets/42176370/16ac39d7-8621-47ae-bed3-e7249446fe34)

- When clicking on `Run podman` it start to load without never finishing.
- I am still able to connect and use my kind cluster. (not displayed in the list of contains)
- No image are list either 

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

**Comment by axel7083** [comment]
After waiting long enough, podman-desktop just closed itself. Now I have the following screen when I open it

![image](https://github.com/containers/podman-desktop/assets/42176370/2ff68ea4-268c-47c0-aa8d-c7e359850b70)

And I can still run `podman run hello-world` without issue.

Here is the result of `podman info`

```
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 97.82
    systemPercent: 1.14
    userPercent: 1.04
  cpus: 12
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "38"
  eventLogger: journald
  freeLocks: 2039
  hostname: Axel-Fix
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 190840832
  memTotal: 8309088256
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.9-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230908.g05627dc-1.fc38.x86_64
    version: |
      pasta 0^20230908.g05627dc-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2123182080
  swapTotal: 2147483648
  uptime: 3h 40m 21.00s (Approximately 0.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 71519555584
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 80
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 1693251588
  BuiltTime: Mon Aug 28 21:39:48 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2

```

**Comment by axel7083** [comment]
The investigation continues. I restart my computer, and still get the `Podman needs to be initialized.`
But now when I cannot use podman run.

When I try to start manually the machine, using `podman machine start` I get the following result
```
podman machine start
Starting machine "podman-machine-default"
The Windows Subsystem for Linux instance has terminated.
The Windows Subsystem for Linux instance has terminated.
Error: the WSL bootstrap script failed: exit status 0xffffffff
```

**Comment by axel7083** [comment]
I ended up having to run `podman machine rm` since I was not able to find any workaround.

**Comment by dgolovin** [comment]
While I was using big image `docker.io/sagemathinc/cocalc` to replicate the issue I have not not noticed anything like this on macOs. I saw the same podman behavior before and it was not related to image size. It happens to me usually after several cycles of sleeping/waking-up my mac.

Podman Desktop is not loosing connection to podman IMO, it is opposite. Podman does not returning REST API calls, so dockerode requests to podman for image/container/pod list never come back.

IMO the actual issue is there is no way to see what is actually going on under the hood like:
- pulling images/containers/pod list form providers
- there is no timeout for dockerode requests and notification to the user that podman/cluster is not responding

**Comment by axel7083** [comment]
I think the issue is partially hardware and related to podman rather than podman desktop, this issue was noticed on a medium old (2018) computer, with limited resources, and potentially also a WSL not updated. I am closing since now I cannot reproduce either on better hardware
