### ISSUE TITLE
UX when Podman machine doesn't have enough RAM to support kind out-of-the-box

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4062]
### Bug description

(reported by @kenrachynski in the #podman-desktop user channel)

User created a podman machine using Podman Desktop then attempted to create a kind cluster using Podman Desktop. Received an error message that they needed 6 GB RAM in their podman VM to set up kind:

![Screenshot from 2023-09-24 12-42-58](https://github.com/containers/podman-desktop/assets/799683/61d15e28-e803-4d37-84c9-da936055643a)

The podman machine that had been set up by Podman Desktop has the following specs (4GB RAM):

![Screenshot from 2023-09-24 12-44-15](https://github.com/containers/podman-desktop/assets/799683/f8e7c3dd-2039-41b5-80f6-d20634708482)

With a reboot of the VM, it should be possible to increase the RAM of the VM to 6GB, but we don't offer to do this for the user. It also seems we don't allow increasing the RAM via the UI (despite the machine being turned off):

![Screenshot from 2023-09-24 12-45-24](https://github.com/containers/podman-desktop/assets/799683/778f290e-867c-414c-9e47-b044a1370d42)

### Operating system

macOS 13.6 (Ventura)

### Installation Method

Brew (macOS)

### Version

1.4.0

### Additional context

This isn't a bug-bug; it's more of a usability enchancement, so not sure how to file. But - I think there's a few things to think about to address this awkward situation:

- **At the podman machine creation step:** When we create the podman machine, should we ask the user what resource profile they'd like to create it with? (eg if you intend to use kind, use the kind profile that gives it 6gb if available) OR do we create with the minimum needed for the core extensions OOTB?
- **At the error message step:** Can we offer to increase the RAM in the system to the required 6 for the user and warn that it will reboot the podman-machine? Can we give the users a link to the machine settings to upgrade the RAM themselves?
- [ ] **In the podman machine settings:** Can we make cpu and ram editable? https://github.com/containers/podman-desktop/issues/4113

**Comment by benoitf** [comment]
I've changed the issue to be an epic

I've added https://github.com/containers/podman-desktop/issues/4113
