### ISSUE TITLE
Please make the errors identify Podman Desktop

### ISSUE THREAD

**Issue by taspeotis** [containers/podman-desktop#4063]
### Is your enhancement related to a problem? Please describe

Logged in to Windows today and was greeted by this. I had to use Task Manager to find out it belonged to Podman Desktop.

![image](https://github.com/containers/podman-desktop/assets/1189399/494bb7f6-691e-43ae-98ae-45a931eadcfe)

### Describe the solution you'd like

Please include Podman Desktop's name in the error message.

### Additional context

Podman Desktop started up okay in the end, and the network was changing. My VPN provider is set to connect (somewhat belatedly) at log in.

**Comment by benoitf** [comment]
Hello @taspeotis thanks for the report

it looks like it's the electron's updater code that is not throwing the error as expected

https://github.com/electron-userland/electron-builder/issues/2398

we'll look how we can mitigate the error.

Thanks

**Comment by taspeotis** [comment]
It happened again while my PC was waking from sleep.

![image](https://github.com/containers/podman-desktop/assets/1189399/c9d5d8d2-6291-412d-8b75-dcd79ac3acd6)

**Comment by taspeotis** [comment]
It still happens but I've mitigated it by changing to a PC that uses less power while idle and setting it to never sleep.

Probably can be closed if a maintainer thinks it's unlikely to ever be fixed.
