### ISSUE TITLE
Onboarding on linux should inform user about the how to install podman on linux page

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#4077]
### Is your enhancement related to a problem? Please describe

Podman Desktop does not have any working installer for Linux and as the user base is small we are not going to work on implementing it atm, we'll just guide the user to the https://podman.io/docs/installation#installing-on-linux page 

### Describe the solution you'd like

When podman is not found during the onboarding on linux we should guide the user to the install linux page using a message like 
`Podman is not found. If you want to install it on Linux, please follow https://podman.io/docs/installation#installing-on-linux`

**Comment by afbjorklund** [comment]
The main issue is that you end up with running 3.4 (on ubuntu LTS) when the others get 4.6
