### ISSUE TITLE
Submit to flathub?

### ISSUE THREAD

**Issue by TimTaylor** [containers/podman-desktop#408]
### Is your enhancement related to a problem? Please describe

Flatpak is not available on flathub.

### Describe the solution you'd like

Flatpak published to flathub.

**Comment by benoitf** [comment]
hi @TimTaylor you may follow https://github.com/flathub/flathub/pull/3407

**Comment by benoitf** [comment]
it's there https://flathub.org/apps/details/io.podman_desktop.PodmanDesktop
