### ISSUE TITLE
Error: (HTTP code 500) server error - crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied  while creating container on MacOS

### ISSUE THREAD

**Issue by xkevas24** [containers/podman-desktop#4109]
### Bug description

Error: (HTTP code 500) server error - crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied 
while creating container on MacOS
<img width="1050" alt="image" src="https://github.com/containers/podman-desktop/assets/40907787/f6836b99-eb7b-4787-930b-be130af43a0b">

Full dick access has already been enabled:
<img width="715" alt="image" src="https://github.com/containers/podman-desktop/assets/40907787/b2af775e-9f92-4906-9c36-a4b363601395">

### Operating system

macOS Ventura 13.5

### Installation Method

None

### Version

1.4.0

**Comment by benoitf** [comment]
hello @xkevas24 and thanks for the report

the root cause is in podman engine and the crun component
https://github.com/containers/podman/issues/19930


you might try on Windows

```
podman machine ssh
dnf install -y https://kojipkgs.fedoraproject.org//packages/crun/1.8.7/1.fc38/x86_64/crun-1.8.7-1.fc38.x86_64.rpm
```

as reported there https://github.com/containers/podman/issues/19930#issuecomment-1727721516

**Comment by xkevas24** [comment]
thanks for reply, but how to solve this problem on macos?

**Comment by jeffmaury** [comment]
Switch the machine to rootful and restart it

**Comment by duyetpt** [comment]
I run this command `podman machine set --rootful`, after that restart podman

**Comment by duyetpt** [comment]
> Switch the machine to rootful and restart it

I run this command `podman machine set --rootful`, after that restart podman
