### ISSUE TITLE
Pre-flight checks for linux installation

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#411]
### Is your feature request related to a problem? Please describe

Similarly to the work done for [windows](https://github.com/containers/podman-desktop/issues/326), we need to provide pre-flight checks for installation of Podman on Linux distro. 

### Describe the solution you'd like

We should check for:
- Version of the OS (if supported)
- Is a previous version already installed? and potentially already running?
- Are there enough resources? 
- Are all dependencies present?

**Comment by deboer-tim** [comment]
The core work to support this and provide normal pre-flight checks is complete, closing.
