### ISSUE TITLE
Make cpu/memory/disk of Podman machine being editable

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4113]
### Is your enhancement related to a problem? Please describe

If I create a podman machine with low CPU and want to increase it after seeing the usage done in https://github.com/containers/podman-desktop/issues/3063

I can't use the UI

### Describe the solution you'd like

I should be able to edit the cpu/memory/disk, it'll restart the podman machine when applying the changes

It could be done in the details page of the machine or somewhere else

**Comment by jeffmaury** [comment]
For Podman, only a few options are available:

On Windows, only rootful and user-mode-networking are supported but requires a stopped machine

On MacOS, everything is supported but requires a stopped machine.

So I suggest:

- allow edit on stopped machine
- declare properties with a new field editable (that should be an expression)

@benoitf @deboer-tim WDYT ?

**Comment by deboer-tim** [comment]
Sorry, delayed 'yes'. I think it's really unfortunate that we have to use 'editable-when' expressions and I think we should keep it as simple (logic and code) as possible, but it's probably inevitable here. This isn't super-obvious to users either, but I think per-platform people will figure out you can edit stopped machines and what you can change.
