### ISSUE TITLE
Onboarding: make the header fixed

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#4117]
### Is your enhancement related to a problem? Please describe

Now the header gets hidden when you scroll down during the onboarding

### Describe the solution you'd like

The header should stay fixed, to be always visible

**Comment by lstocchi** [comment]
@mairin i have done it in 2 ways. Which do you prefer?

First it works the same way as the bottom buttons bar

![fixed_header_1](https://github.com/containers/podman-desktop/assets/49404737/cf17b03c-c374-44b8-8ed9-2a11c431c669)

The second is just a fixed div which do not have content flowing behind

![fixed_header_2](https://github.com/containers/podman-desktop/assets/49404737/0fdd6f1f-026e-4444-a730-606103efb1bc)

**Comment by mairin** [comment]
I definitely prefer the first one, thanks for providing options :)

**Comment by mairin** [comment]
(And the rationale... the second one doesn't *look* like a header it looks like all one page, so when you scroll it's a bit unexpected that it gets cropped)
