### ISSUE TITLE
Provide a way to install `kubectl` CLI

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4118]
### Is your enhancement related to a problem? Please describe

We're providing a lot of CLI like compose, kind, etc

but we should also provide a way to setup `kubectl` binary

### Describe the solution you'd like

Have a nice way to install `kubectl`

**Comment by aaraodeo** [comment]
yes, kubectl cli extension provider is essential. Till it is provided kindly provide a clear documentation on how to set it up.

**Comment by afbjorklund** [comment]
The (complicated) upstream documentation is available here: https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by dgolovin** [comment]
@benoitf where it should be declared. Would kube-context extension work as a place where it should be registered?

**Comment by benoitf** [comment]
@dgolovin good question, it can land there but I don't know if it's the best location.

I would opt-in for a separate extension

**Comment by dgolovin** [comment]
I have extension for it here https://github.com/dgolovin/podman-desktop-kubectl-ext

**Comment by dgolovin** [comment]
@benoitf Should it be part of podman extensions folder or we keep it as external one?

**Comment by benoitf** [comment]
separate extension probably

**Comment by benoitf** [comment]
I mean inside extensions folder of Podman Desktop, not part of Podman extension

**Comment by dgolovin** [comment]
It should not be closed yet, because only registration and detection implemented. 
Setup depends on cli extension point further development to support setup.
