### ISSUE TITLE
Add a CLI provider extension point

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4120]
### Is your feature request related to a problem? Please describe

We should be able to list all CLIs installed by 3rd party extensions and have an unified way of updating it, remove it, setup it, etc

### Describe the solution you'd like

Add a Command Line provider

These CLIs will be displayed in a CLI Tools section in settings

https://github.com/containers/podman-desktop/issues/3781

For example, it should include compose, kubectl, oc, etc

### Additional context

This feature starts with presentation only for registered tools and continue with implementation of 

* https://github.com/containers/podman-desktop/issues/4648
* https://github.com/containers/podman-desktop/issues/4650
* https://github.com/containers/podman-desktop/issues/4651

Related issues

* https://github.com/containers/podman-desktop/issues/3781
* https://github.com/containers/podman-desktop/issues/4118

**Comment by benoitf** [comment]
it differs from https://github.com/containers/podman-desktop/issues/4059 as here the CLI can be embedded in the extension as well

BinaryRegistry is an helper, not the way to register CLIs

**Comment by dgolovin** [comment]
@benoitf podman can be installed using brew on macOS, chocolate on Windows, dnf on Fedora aptitude on Debian and etc. Should CLI provider extension point cover different ways to install tools on different platforms or we just provide implementation similar to what docker-compose does?

**Comment by benoitf** [comment]
hi @dgolovin yes I think there are a lot of unknown in the current description

1. First, I think the idea is to bring awareness to the user that some CLI commands exists and are useful. So here the idea is that if `kubectl` is already found in the PATH (and that we have an extension supporting it), it'll display that `kubectl` entry in the CLI page in the UI. From here it'll display its version.

2. Then, comes the awareness of the installation of the tool. For example as you said, it can be useful to know who was responsible to install the tool. So on macOS we have already some commands checking if podman is installed by brew (to not let upgrade path continue). So it is very helpful to see the `source` or `origin` of the tool. So on macOS, to know if podman CLI that is in the PATH comes from the `podman installer` (in `/opt/podman/bin` or from `/opt/homebrew/etc` if it's coming from brew). (For example we might say it's not the recommended way, etc). If the system is Linux, for now we won't support all Linux distribution to check with apt-get, dnf, rpm-ostree, yum, etc) so source can be `N/A` or `unknown`

(The Provided by in top right corner of each tile I suppose)

![image](https://github.com/containers/podman-desktop/assets/436777/7ea727ef-274b-4084-886d-72cbe07cb9a4)

here from the design we have a setup available so we could assume here that we've like the onboarding contribution where you may have different page based on your platform, arch, etc. On Linux it can give you links to the page on how to manually install it, confirm that it's installed after manual install, etc.

4. Finally, comes the `installation` and the `update` path. If the CLI is not being detected, users may want to install it. So here, it should register a way to install a CLI based on platform and arch being supported. (Then here we could have the usage of like the GithubBinary helper where you specify some pattern and it can fetch from github releases some packages) but it can be just a copy from the extension.

so, we can have the 'installation' being supported but not the update. For the update we should have a way to say like (recommended version) but if supported we could have


Maybe you need to work first on a workflow diagram to see if we're covering all the usecases and if it can fit with the expected UI, UX experience, and how extension can contribute

**Comment by deboer-tim** [comment]
+1. IMHO we can deliver this incrementally, e.g. first pass might be just enough for extensions to register a known CLI, whether it is installed or not, and what version it's at, so we can provide a few extensions and build the initial UI. Then the extension needs to be able to install or update (or point to website), handle OS differences, etc.

I really like the suggestion about GithubBinary helper - there are likely several common patterns here where we could provide something reusable instead of every extension implementing it.

**Comment by dgolovin** [comment]
@deboer-tim that would be a huge reduction of scope for this sprint and we would provide awareness what CLI tools can be used and cover (1) from @benoitf list.

**Comment by deboer-tim** [comment]
I'm not suggesting an overall reduction in scope ;-) , just incremental delivery / don't block for everything to be solved. Better to get the first useful chunk merged and start building UI & getting feedback vs trying to figure it all out up front.

**Comment by dgolovin** [comment]
@benoitf: Considering we have now new issues related to CLI API and UI, should we close this one.

**Comment by benoitf** [comment]
if we have issues for update, removal, etc yes but I'm not sure we have an issue for all of them ?

**Comment by dgolovin** [comment]
@benoitf I created the issues for all required features (see descriptions), let me know if I forgot something.
