### ISSUE TITLE
feat: flatpak: remove --talk-name=org.freedesktop.Notifications

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4121]
### Is your enhancement related to a problem? Please describe

With 23.08 baseapp, Desktop notifications should work work without `--talk-name=org.freedesktop.Notifications`

The 23.08 baseapp includes libnotify 0.8.2 which should not require that hole.

- Follows #3966
- See: https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/31#issuecomment-1733687717

### Describe the solution you'd like

1. Remove --talk-name=org.freedesktop.Notifications
2. Test that desktop notifications work as expected.

**Comment by bbhtt** [comment]
Add, the following link as reference in the commit message if it works https://gitlab.gnome.org/GNOME/libnotify/-/blob/69aff6e5fa2842e00b409c348bd73188548828b3/NEWS#L25. Thanks
