### ISSUE TITLE
Playwright E2E tests do not work well when ElectronApp.launch() method is provided only with executablePath to the electron app

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4127]
### Bug description

Running E2E tests with Playwright using `PODMAN_DESKTOP_BINARY` seems to be problematic in some way, it start an app. but testing framework wont take over the app to manipulate it.

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

run e2e tests using `yarn test:e2e:smoke` with PODMAN_DESKTOP_BINARY.

**Comment by adrianriobo** [comment]
The `electron.launch()` is finishing with timeout, according to playwright release notes this behavior is related to electron fuse `EnableNodeCliInspectArguments`:

```
**Supported Electron versions are:**
* v12.2.0+
* v13.4.0+
* v14+

**Known issues:**

If you are not able to launch Electron and it will end up in timeouts during launch, try the following:

* Ensure that `nodeCliInspect` ([FuseV1Options.EnableNodeCliInspectArguments](https://www.electronjs.org/docs/latest/tutorial/fuses#nodecliinspect)) fuse is **not** set to `false`.
```

In fact that flag is set to to false on [the build config file](https://github.com/containers/podman-desktop/blob/8dc78b830f48490a275f18e4a34be5b82a62dd5b/.electron-builder.config.cjs#L59) 

There is no option to turn the fuse up on runtime once the bits have been built with it down.

Also beyond the general recommendation from electron to turn all fuses down unless they are required there are certain discussion around the security implications to have them activated (specially the  `EnableNodeCliInspectArguments` and the `runAsNode`)  see https://www.electronjs.org/blog/statement-run-as-node-cves

With all these we have now 2 possibles choices:

1) Set EnableNodeCliInspectArguments to true on build config 

2) Build specific debuggable versions setting the `EnableNodeCliInspectArguments` to true based on a compile parameter

If we go with version 2 we should decide where those builds should be made. There was an idea to have [something similar on podman-desktop-e2e](https://github.com/containers/podman-desktop-e2e/issues/168) or they can be added to the release / pre release actions on podman desktop project and the resulting artifacts will be published within the rest.

I would like to agree on the solution to apply as this is impacting the extensions testing strategy.

^^ @odockal @benoitf or any other who has an opinion on this
