### ISSUE TITLE
Kind support

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#413]
### Epic domain

Podman Desktop should provide the ability to enable and start [Kind](https://kind.sigs.k8s.io/) as an available provider.

Podman provides the ability to run Pods which helps developers to reproduce workloads that are running on kubernetes in a local environment.

In addition, as Podman Desktop has the ability to handle multiple providers (container engines or kubernetes distribution) it would be nice to allow users to bootstrap a "local kubernetes" with Kind. (We saw asks from the community on this regards too.)

### Sub-tasks

- Ability to setup Kind
- Ability to start/stop Kind
- Display Pods from Kind in the list of Pods

### Additional context

Additionally, we would like to enable a set of "Developer packages" that the developer could eventually enable. As mentioned by @cmoulliard in his [comment](https://github.com/containers/podman-desktop/issues/29#issuecomment-1118231429).

**Comment by cmoulliard** [comment]
FYI: This are still alpha projects but the OLM sub-projects [rukpak](https://github.com/operator-framework/rukpak) and [deppy](https://github.com/operator-framework/deppy) should be able to help us to provision the k8s cluster post creation using an approach similar to what Tanzu do using the kapp-controller and packages.

remark: A helm provisioner has been added to rukpak recently

**Comment by cmoulliard** [comment]
Is the kind resource already released as I dont see part of podman desktop 0.10 ? @slemeur 

![Screenshot 2023-01-19 at 18 40 18](https://user-images.githubusercontent.com/463790/213519999-4fff3623-7c46-4c05-87e9-bc3139825ffc.png)

**Comment by benoitf** [comment]
hello @cmoulliard for now it's only available using the development mode of Podman Desktop (running from the sources) to make sure it's working as expected.
