### ISSUE TITLE
Docs: Deploying your Compose app to Kubernetes

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4142]
Add new story: Deploying your Compose app to Kubernetes, with one example.

Try with this example:  https://github.com/penpot/penpot/tree/develop/docker/devenv

**Comment by slemeur** [comment]
Here the goal should be to show an example. We can't be prescriptive with "one solution" that will fit for all kind of compose file. We will need to provide hints on how that can be accomplished.

**Comment by cdrage** [comment]
We should be using the compose example (https://podman-desktop.io/blog/getting-started-with-compose) convert that to Kubernetes  / test that.
