### ISSUE TITLE
New button: Convert single / group of containers to Compose.  

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4143]
### Is your feature request related to a problem? Please describe

We do not currently have the ability to convert a single container or a pod to a docker compose YAML.

This could be added as a separate kompose extension for podman desktop.

With the integration of https://github.com/containers/podman-desktop/pull/3970 we have the ability to provide a custom Kubernetes generator.

For example, the Kompose kubernetes generator can only convert compose yaml files. So it can only be used on compose containers.

However, if we were to integrate https://github.com/magicmark/composerize into Podman Desktop, we could.

We should provide the ability to convert a single container to compose so custom Kubernetes generator tools such as Kompose can be used. 

### Describe the solution you'd like

1. Use `podman inspect` and get the CreateCommand such as:

```json
               "CreateCommand": [
                    "podman",
                    "run",
                    "--name",
                    "hello",
                    "-d",
                    "-p",
                    "8081:8081",
                    "cdrage/helloworld"
               ],
```

2. Convert it to Compose YAML via https://github.com/magicmark/composerize which has (luckily!) had a lot more pull requests / everything updated via this PR: https://github.com/magicmark/composerize/pull/568

3. Be able to see the group of Compose containers.

This could be integrated as a button within PD or an option when converting to "Pods"? More research needed on this part.

**Comment by cdrage** [comment]
Pinging @axel7083 as my research brought up https://github.com/magicmark/composerize which would be helpful to be able to convert containers to consumable compose yaml for `kompose` to be used.

**Comment by axel7083** [comment]
Very interesting, will look it up when I will have some time

**Comment by cdrage** [comment]
> Very interesting, will look it up when I will have some time

No problem, this is a lower priority issue / needs to be more discussed.

I was thinking however that adding this to the kompose extension would most likely be the best area.

Adding composerize to it and adding a function we can call would be great.

**Comment by benoitf** [comment]
@cdrage shouldn't it be part of a 3rd party extension ?

**Comment by cdrage** [comment]
> @cdrage shouldn't it be part of a 3rd party extension ?

Haha I meant to say `kompose` instead of compose. I'll update the original issue as well.

**Comment by benoitf** [comment]
got it 👍
