### ISSUE TITLE
Openshift Extension not working

### ISSUE THREAD

**Issue by ssnivlek** [containers/podman-desktop#415]
### Bug description

I think the podman desktop should have a interface to add extensions like the one in docker extension tab, the image name for the trivy exntesion works just fine and trivy extension is working, but the image name for the openshift extensions install the image but doesn't seem to work, leaving me with a black page when acessing the Openshift on the Contributions tab.

### Operating system

macOS Monterey 12.5

### Version

0.0.5

### Steps to reproduce

Install the Docker Desktop Extensiosn with the image name redhatdeveloper/openshift-dd-ext:latest

**Comment by benoitf** [comment]
Ok thanks for the report

could you try with `redhatdeveloper/openshift-dd-ext:0.0.1-41` as it was a version that was working fine before referencing to use latest there https://github.com/containers/podman-desktop/pull/362

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/418

available in pre-release https://github.com/containers/podman-desktop/releases/tag/v0.0.202208191456-ad8ad65
