### ISSUE TITLE
Podman Desktop 4.6.2 Windows hangs during intialization

### ISSUE THREAD

**Issue by heidenthal-gtisoft** [containers/podman-desktop#4158]
### Bug description

I had the issue reported in https://github.com/containers/podman-desktop/discussions/2056 (even though it had worked for weeks), so I followed the instructions there and the problem persisted.  I decided to reinstall Podman entirely, so I used the Windows uninstaller, then searched for and deleted every file and directory with the word podman in it's name.

I followed all the instructions of installation that I had before, but now Podman Desktop is hung during its initialization.

Any help is appreciated.

### Operating system

Windows 10 Business 10.0.19045 Build 19045

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

### Steps to reproduce

1. Start with a clean machine (nothing Podman already installed)
2. Run the podman-desktop-1.4.0-setup-x64.exe installer
3. When Desktop asks to Install/Initialize, select that
4. Hangs on initialization

**Comment by jeffmaury** [comment]
Did you had an existing Podman machine ? Can you check if there are some podman.exe processes running ?

**Comment by heidenthal-gtisoft** [comment]
Hi @jeffmaury,

I had also stopped all Podman processes and restarted after cleaning.  

I just now tried again to Initialize and Start.  It hung again.  Then, I saw your posting and ended the existing Podman processes, then again attempted to Initialize and Start.  Unfortunately, it is still hanging

**Comment by jeffmaury** [comment]
> Hi @jeffmaury,
> 
> I had also stopped all Podman processes and restarted after cleaning.
> 
> I just now tried again to Initialize and Start. It hung again. Then, I saw your posting and ended the existing Podman processes, then again attempted to Initialize and Start. Unfortunately, it is still hanging

When it hungs, can you check then running podman.exe with the full command line as I once had a kind of deadlock with them.

**Comment by heidenthal-gtisoft** [comment]
Please expand on what you mean by "check then running podman.exe with the full command line"

**Comment by heidenthal-gtisoft** [comment]
![PodmanProcesses](https://github.com/containers/podman-desktop/assets/141954982/906909fa-8a01-4b17-9162-18a5d1cbc479)

**Comment by jeffmaury** [comment]
I meant podman.exe not podman desktop.exe

**Comment by heidenthal-gtisoft** [comment]
Those are all the Podman related processes running, since initialization of Podman hasn't been successful yet.

What do you mean by check with the full command line?

**Comment by heidenthal-gtisoft** [comment]
![PodmanProcesses](https://github.com/containers/podman-desktop/assets/141954982/da308039-08e9-47c6-b967-285f4dd327f5)

**Comment by jeffmaury** [comment]
You can get it through powershell:

`Get-WmiObject Win32_Process -Filter "name = 'podman.exe'" | Select-Object CommandLine`

Or can you run

`Get-WmiObject Win32_Process >ps.txt`

and attach the file to the issue ?

**Comment by heidenthal-gtisoft** [comment]
![PodmanProcesses](https://github.com/containers/podman-desktop/assets/141954982/6472fbb6-74f1-4155-a037-81d6dddd24c4)

**Comment by heidenthal-gtisoft** [comment]
[podman_processes.txt](https://github.com/containers/podman-desktop/files/12766586/podman_processes.txt)
[ps.txt](https://github.com/containers/podman-desktop/files/12766587/ps.txt)

**Comment by jeffmaury** [comment]
So when you launch Podman Desktop, do you have an Install button like this:

![image](https://github.com/containers/podman-desktop/assets/695993/007dfb1e-2578-461d-a0eb-a4c1e34f2c25)

**Comment by heidenthal-gtisoft** [comment]
I did at one point.  I selected that button.  If I recall correctly, then there was a checklist of about 5 items, which it went through quickly (all green).  Finally, there was a button labelled "Initialize and Start", which I selected.  Now, that has been replaced with the following: 
![podmanHange](https://github.com/containers/podman-desktop/assets/141954982/31d084b6-c50b-4e41-87db-f6cb9eeb31bf)

**Comment by benoitf** [comment]
@heidenthal-gtisoft can you go instead to settings (the cog in the bottom left)

then in resources menu

then check if there is a podman machine or not and try to create a new one from there if missing, probably you should have details there

**Comment by jeffmaury** [comment]
When I click Install, after the checks are ok, I have this:

![image](https://github.com/containers/podman-desktop/assets/695993/4d556cd0-c03f-4280-a7d0-98f3544da8a0)

**Comment by heidenthal-gtisoft** [comment]
> @heidenthal-gtisoft can you go instead to settings (the cog in the bottom left)
> 
> then in resources menu
> 
> then check if there is a podman machine or not and try to create a new one from there if missing, probably you should have details there

@benoitf There were no machines already in the resources menu, so I attempted to create one.  This is the result:

Extracting compressed file

Importing operating system into WSL (this may take a few minutes on a new WSL install)...

A distribution with the supplied name already exists.
Error code: Wsl/Service/0x800700b7

Error: the WSL import of guest OS failed: exit status 0xffffffff

Command execution failed with exit code 125

**Comment by heidenthal-gtisoft** [comment]
> When I click Install, after the checks are ok, I have this:
> 
> ![image](https://user-images.githubusercontent.com/695993/271639496-4d556cd0-c03f-4280-a7d0-98f3544da8a0.png)

Yes, @jeffmaury, that looks familiar and may have been in the sequence.

**Comment by jeffmaury** [comment]
OK I understood the use case. As you delete files (with podman) now podman lost the information about the podman machine but the WSL machine is still there. If you run `wsl -l` you should see it (podman-machine-default). If this is the case can you run `wsl --unregister podman-machine-default` and restart the process within Podman Desktop

**Comment by heidenthal-gtisoft** [comment]
I followed the steps to unregister Podman, found I had to stop all the tasks in Task Manager as well and Podman Desktop presented a button to "Run Podman."  I selected that button and an error was presented


![PodmanGood](https://github.com/containers/podman-desktop/assets/141954982/cecfaa43-9c35-4521-a77c-11d041be0da1)
![PodmanBad](https://github.com/containers/podman-desktop/assets/141954982/b0bdf52b-547c-4d8b-9c39-d304e1ef4c9f)

**Comment by jeffmaury** [comment]
Can you go to the troubleshooting page and copy the content of the log file and paste it here ?

**Comment by heidenthal-gtisoft** [comment]
error : main ↪️ Kubeconfig path C:\Users\theidenthal\.kube\config provided does not exist. Skipping.
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 10 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\theidenthal\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 39 milliseconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 38 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 13 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) ended in 12 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 28 milliseconds
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 112.69070000015199ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 49.71559999976307ms
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
debug : main ↪️ [compose] Error while pinging docker Error: connect ENOENT //./pipe/docker_engine
error : main ↪️ [kind] [object Object]
log : main ↪️ Activating extension (podman-desktop.kind) ended in 180 milliseconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ Activating extension (podman-desktop.podman) ended in 776 milliseconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting container engine
log : main ↪️ [podman] Podman extension: Autostarting machine podman-machine-default
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 59.252599999308586ms
error : main ↪️ [podman] [object Object]
error : main ↪️ Failed to autostart container engine [object Object]
error : main ↪️ [podman] [object Object]

**Comment by dpoerschke** [comment]
Same here - I'm using podman Desktop 1.4.0 and Initializing runs forever. The log says this:

> error : main ↪️ Kubeconfig path C:\Users\myusername\.kube\config provided does not exist. Skipping.
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 10 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\myusername\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 43 milliseconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 42 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 14 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) ended in 12 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 49 milliseconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 193.04760003089905ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 97.26560020446777ms
log : main ↪️ Activating extension (podman-desktop.podman) ended in 311 milliseconds
error : main ↪️ [kind] [object Object]
log : main ↪️ Activating extension (podman-desktop.kind) ended in 801 milliseconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting container engine
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 75.77839994430542ms

**Comment by benoitf** [comment]
hello @dpoerschke , could you go into the `settings` then in `resources` here, try to click on the run button of the podman machine. Then you see an arrow like `↗️` in top right corner of the podman machine
click on it and go into the Logs tab

do you see any error ?

**Comment by dpoerschke** [comment]
My problem is solved: it turned out, that the "Windows-Hypervisor-Platform" was not active on my System (Settings -> Type `windows features` and check the corresponding checkbox in the appearing window). If you type `podman machine init` on the console you get an error message that tells you the cause. Unfortunately this error is not displayed in Podman Desktop. 
@benoitf Thanks for the tip, until now I only knew the option to access the logs via the light bulb at the bottom right. Learning never stops 😄

**Comment by koisurunippon** [comment]
Hi, I got the error below when running the init command, podman 4.6.2 on Windows 11, WSL installed, "Windows-Hypervisor-Platform" installed. Could you please check and advise?

C:\Windows\System32>podman machine init
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
Unspecified error
Error code: Wsl/Service/E_FAIL
Error: the WSL import of guest OS failed: exit status 0xffffffff

**Comment by koisurunippon** [comment]
When I tried with Podman 4.8.2, I got the error below:

C:\Windows\System32>podman machine init
xz: (stdin): Compressed data is corrupt

**Comment by jeffmaury** [comment]
Looks like you have a cached file that is truncated or corrupt. Can you check %USERPROFILE%/\.local\share\containers\podman\machine\wsl and %USERPROFILE%/\.local\share\containers\podman\machine\wsl\cache

**Comment by koisurunippon** [comment]
Hi @jeffmaury, in %USERPROFILE%/.local\share\containers\podman\machine\wsl\cache, there is the file fedora-podman-amd64-v39.0.12.tar.xz which I can extract with 7zip successfully, however, when running the podman machine init command, it cannot extract due to some reason.
![image](https://github.com/containers/podman-desktop/assets/142728322/7aafbfa5-1aca-42c3-a0bd-a465a2f17efb)

**Comment by koisurunippon** [comment]
When I tried to decompress with xz command manually, it could decompress without problem
C:\Windows\System32>xz -d %USERPROFILE%\.local\share\containers\podman\machine\wsl\cache\fedora-podman-amd64-v39.0.12.tar.xz

C:\Windows\System32>
