### ISSUE TITLE
Delete confirmation dialog

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4160]
### Is your enhancement related to a problem? Please describe

A user reported that they accidentally deleted their Kind cluster, and a confirmation dialog would have avoided this.

### Describe the solution you'd like

A delete confirmation dialog (at least when deleting more a sensitive thing from a list of other things).

**Comment by cdrage** [comment]
IMHO should this apply for pods / containers / etc too?

I don't know how many times I've deleted a pod off the k8s cluster by mistake and taken a site offline / had to wait for k8s to re-deploy the pod.

We could add a setting within podman desktop to enable "fast delete" to not show the prompt? Or just a "never show again" button?

**Comment by deboer-tim** [comment]
I have all the same questions. :) I can totally see the request for a confirmation dialog, but to me doing it for everything would be annoying. Maybe it's a preference and has a 'don't ask me again', or maybe it's environment-specific/depends on what you're trying to delete and the implications of it.

**Comment by Andres6936** [comment]
¡We need a confirmation modal!

**Comment by trmendes** [comment]
I would like to work on this task and implement a confirmation dialog for Volumes, Images, Pods, and Containers.

I'm new to Podman and Podman Desktop, so, if it is OK, I might need some guidance during the development of this task.

Furthermore, I spent some time looking at Docker Desktop to see how it handles the deletion and there, there is no “fast delete” option. For each time you click on the “delete” button (bulk deletion or single deletion), a dialog box will appear to make sure you know what you are doing and to make sure what are the resources to be deleted.

Such behavior adds a bit of additional clicks to the deletion flow, but it protects the user against accidentals clicks.

Looking forward to hearing more from the community.

Suggestion for deleting multiple volumes:
 
<img width="1162" alt="Screenshot 2024-01-23 at 13 11 39" src="https://github.com/containers/podman-desktop/assets/16507629/f320b92b-6d0d-4750-b623-e25cb03b398c">

Suggestion for deleting a single volume:

<img width="1162" alt="Screenshot 2024-01-23 at 13 12 00" src="https://github.com/containers/podman-desktop/assets/16507629/a4f07e68-5bdf-40c9-91c0-68f9dbec19bd">

**Comment by benoitf** [comment]
it looks like a new issue https://github.com/containers/podman-desktop/issues/5444 is duplicating/including this issue

And there is an existing PR: https://github.com/containers/podman-desktop/pull/5445

**Comment by cdrage** [comment]
Closed via https://github.com/containers/podman-desktop/pull/5445
