### ISSUE TITLE
Any plans to support Podman in Multipass?

### ISSUE THREAD

**Issue by ateska** [containers/podman-desktop#4161]
### Is your feature request related to a problem? Please describe

One elegant way of how to operate Podman on the macOS is to use [Multipass](https://multipass.run) from Canonical.
The problem is that to connect Podman Desktop to the Podman in Multipass, one needs to do following trick:

```
mkdir -p /Users/jdoe/.lima/podman/sock
ssh -L/Users/jdoe/.lima/podman/sock/podman.sock:/var/run/user/1000/podman/podman.sock ubuntu@192.168.64.6
rm /Users/jdoe/.lima/podman/sock/podman.sock
``` 

Podman Desktop then report Lima being in use - which is not true and that can be quite confusing.

### Describe the solution you'd like

Out-of-the-box support for a Podman in Multipass.
Multipass can be managed from the Podman Desktop in a similar way as a Lima.

### Describe alternatives you've considered

I tried Lima but it provides not so good experience to Multipass

### Additional context

Podman in Multipass is connected and working:

<img width="1234" alt="image" src="https://github.com/containers/podman-desktop/assets/2236975/08dcac7a-3cf0-4c4d-bc2f-9fde5cce7a06">

<img width="1162" alt="image" src="https://github.com/containers/podman-desktop/assets/2236975/39809d46-1121-4ac3-be91-c2b9a6c9e0b4">

**Comment by afbjorklund** [comment]
This would be possible to do, if the `podman.sock` location was possible to be changed...

* https://github.com/containers/podman-desktop/issues/3893

`CONTAINER_HOST=ssh://ubuntu@192.168.64.6/var/run/user/1000/podman/podman.sock`

But ultimately you would need to make a Multipass provider, and load it as an extension.

* https://podman-desktop.io/docs/extensions

Then you could use a separate location for the unix socket, and not have to use another.

**Comment by afbjorklund** [comment]
With multipass, you also need to find a way to install Podman Engine on Ubuntu...

Which can be challenging, but similar to https://podman.io/docs/installation#ubuntu

It would be similar to Docker Engine: https://multipass.run/docs/docker-tutorial

https://github.com/canonical/multipass-blueprints/blob/main/v1/docker.yaml

**Comment by ateska** [comment]
> With multipass, you also need to find a way to install Podman Engine on Ubuntu...
> 
> Which can be challenging, but similar to https://podman.io/docs/installation#ubuntu
> 
> It would be similar to Docker Engine: https://multipass.run/docs/docker-tutorial
> 
> https://github.com/canonical/multipass-blueprints/blob/main/v1/docker.yaml

I had no significant problem to install Podman into Ubuntu in the Multipass.
I'll paste a whole procedure next time I go thru that.

**Comment by ateska** [comment]
```
export ubuntu_version='22.04'
export key_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key"
export sources_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}"

echo "deb $sources_url/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
curl -fsSL $key_url | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
sudo apt update
sudo apt install podman
```
