### ISSUE TITLE
bug: inconsistent tab info when starting containers

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#4166]
### Bug description

After starting a container from image, the tab switches to Containers, but the link above container name still points to Images.
![image](https://github.com/containers/podman-desktop/assets/75624842/e049b214-f6b7-4a8b-afb1-ca8b6c89b48b)
When I switch to Images (or anywhere else) and back, the link correctly points to Containers.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1: pull an image
2: start a container
3: the link above container name points to Images

### Additional context

PD 1.5.0, Podman 4.7.0

**Comment by deboer-tim** [comment]
> When I switch to Images (or anywhere else) and back, the link correctly points to Containers.

By "and back", do you mean clicking on Containers and then selecting the container? If so, this is exactly how the breadcrumb is _supposed_ to work - i.e. it's a backlink, not showing the page hierarchy. In the screenshot you came from Images so you can click to go back there; if you came from Containers that's what is shown.

Likewise, try the Deploy to Kubernetes action. You can click it from either the Containers screen or the Container Details, and the corresponding page is in the breadcrumb.

Let us know if it wasn't working correctly, you find this behaviour confusing/don't like it, or it makes sense now.

**Comment by deboer-tim** [comment]
No response, but I'm guessing this was another instance of bug #4288, PR in review.
