### ISSUE TITLE
bug: Kind installation throws error: Unable to install kind binary: [object Object]

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#4168]
### Bug description

When installing Kind binary on windows through the pop-up in left bottom corner, 
installation throws error: "Unable to install kind binary: [object Object]".
![image](https://github.com/containers/podman-desktop/assets/75624842/34008b65-59e4-402a-9b73-a085ec3d9d84)

Kind binary is still downloaded to C:\Users\username\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.kind

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

Update: Adding dev console error log:
```
main ↪️ [compose] Failed to install 'docker-compose' binary: [object Object]
console.<computed> @ VM50:2
(anonymous) @ VM50:2
emit @ VM49 sandbox_bundle:2
onMessage @ VM49 sandbox_bundle:2
```

**Comment by odockal** [comment]
@rostalan @jeffmaury I was just testing the same scenario, I installed kind without any errors but I was not installing using system wide option. Was that the case in this issue? Or the error popped up before app was asking about if to install kind also system-wide?

**Comment by jeffmaury** [comment]
> @rostalan @jeffmaury I was just testing the same scenario, I installed kind without any errors but I was not installing using system wide option. Was that the case in this issue? Or the error popped up before app was asking about if to install kind also system-wide?

No the error is related to system wide installation

**Comment by odockal** [comment]
I have spotted the same erro r installing a docker-compose system-wide on Linux.
![Screenshot_20231003_125819](https://github.com/containers/podman-desktop/assets/19164299/bedfa2a5-653d-4560-b99f-22f2d413d2c5)
