### ISSUE TITLE
Podman Desktop does not show available images and container

### ISSUE THREAD

**Issue by pacostas** [containers/podman-desktop#417]
### Bug description

Images and containers are not visible on Podman Desktop although they appear with the commands `podman image ls` and `podman container ls -a`

Only for images, If I build an image from Podman Desktop, only then the images appear.

### Operating system

Windows 10 Pro N (Version 10.0.19041.1806)

### Version

0.0.5

### Steps to reproduce

1. Opened Podman Desktop
2. Initialized the machine (through the Podman Desktop UI - Home)
3. Ran Podman (through the Podman Desktop UI - Home)
4. Visited the Images tab and no images where available
5. From the powershell the command `podman image ls` shows me 5 available images
6. From Podman Dekstop I build a new image
7.Now I'm able to see the the images that previously werent visible.

**Comment by benoitf** [comment]
Hello @pacostas are you using the latest v0.0.6 version ?

could you provide the log that you can have when going to `View/Toggle Developer Tools` ?

**Comment by pacostas** [comment]
Yes I use [podman-desktop-0.0.6.exe](https://github.com/containers/podman-desktop/releases/download/v0.0.6/podman-desktop-0.0.6.exe)

I cant find the view/Toggle Developer Tools on Podman Desktop UI, can you please indicate me where is that located?

**Comment by benoitf** [comment]
It's in the menu bar

https://user-images.githubusercontent.com/436777/185613790-19f3b47a-8289-4f5d-a114-293ab3b1e98a.mp4

**Comment by pacostas** [comment]
Thanks! If below images are not helpful enough, Let me know to which errors you would like to see in more detail
![Screenshot_win10_2022-08-19_15:14:00](https://user-images.githubusercontent.com/10673302/185616406-055c155c-e530-4a1b-a938-0e366494246d.png)
![Screenshot_win10_2022-08-19_15:14:13](https://user-images.githubusercontent.com/10673302/185616412-e9e65cfb-ed3e-48ab-8a88-27523b57dfcd.png)

**Comment by benoitf** [comment]
ok so it seems there is a race condition bug on the startup.
It's running inside a Windows VM so it's slower and then we face the issue.

A workaround is to reload the UI using the menu View/Reload to make sure that the UI is connected to the main process.

**Comment by pacostas** [comment]
Indeed, it worked thank you very much :)

**Comment by djnotes** [comment]
I am not sure if I needed to open a new issue for this, but because of similarity, I'm putting it here. 
Here's the thing: I made a container image with buildah on the terminal, and it didn't show up in Podman Desktop after the build, until I restarted Podman Desktop.

**Comment by pacostas** [comment]
Can you try if this Podman Desktop version https://github.com/containers/podman-desktop/actions/runs/2965310263 resolves the issue?

**Comment by djnotes** [comment]
@pacostas  Just tried that. It still does not see the images created by buildah unless I restart the app.

**Comment by benoitf** [comment]
@djnotes could you share your buildah instruction and the logs from View/developper tools/console

**Comment by djnotes** [comment]
Here's the logs:

![image](https://user-images.githubusercontent.com/9320387/188314145-d0f67754-5af7-4e2f-aa9b-ee3a2d13af4a.png)

Here's my Containerfile:

```
FROM ghcr.io/djnotes/pyrogram-image:latest

RUN pip3 install pyrogram tgcrypto apscheduler

COPY . /app

WORKDIR /app


CMD ["python","bot.py"]




```

Here's my buildah command:

```
buildah build -t inspiration-bot .
```

And, back to Podman Desktop, I don't see the new image, unless I quit and open the app again.

**Comment by benoitf** [comment]
@djnotes instead of doing `buildah build` command you should use `podman build` command

We're getting events from Podman. If you use buildah, there is no event being dispatched so Podman Desktop can't be notified

**Comment by djnotes** [comment]
Right. Podman Desktop does indeed detect new image built with Podman.

**Comment by djnotes** [comment]
I've got a question: If a system does not have Podman installed, will Podman Desktop installer install the Podman engine automatically?

**Comment by pacostas** [comment]
Yes, Podman Desktop can detect if podman is installed on your system, otherwise provides you a guide to install all the prerequisites that podman requiers (hyper-v, wsl etc.) and then you are able to install podman, initialize the podman machine and use podman through Podman Desktop or through powershell with CLI.

**Comment by afrancoc2000** [comment]
this thing is still happening to me inside a VDI, and I can't open the menu bar, is there another way to view/reload?

**Comment by benoitf** [comment]
@afrancoc2000 <kbd>Control</kbd>+<kbd>R</kbd> (or <kbd>Command</kbd>+<kbd>R</kbd> on macOS)

**Comment by mixtah** [comment]
I'm finding I'm needing to run Control+R after most operations that affect the list, so I believe there is still a bug that needs to be fixed, possibly under a new issue.

**Comment by benoitf** [comment]
@mixtah what is your podman desktop version ?

also could you look at the troubleshooting page ( light bulb in bottom right status bar) and see logs and then the stores ( for example containers, images, etc and see when they're refreshed and if you click on the underline link, manually refresh them here

Could you report these statuses?

**Comment by mixtah** [comment]
Desktop Version 1.21, no clear error in the troubleshooting page and refreshing seems good. I'm attempting to reproduce the issue but it's not happening anymore. Perhaps it was just that once off or fixed itself after refreshing?

**Comment by benoitf** [comment]
@mixtah whenever you have this issue again, yes please looks at this page and send content (if you refresh stores are re-initialized so we loose history)

Also could be interesting to see the log (and failures at this time as well) b/c refreshing is also reinitializing the log content.

**Comment by mixtah** [comment]
I've come across it again, but I suspect I know the reason. I've pasted the logs below.

I have Docker installed in WSL (without docker desktop), Podman will start on startup but WSL may not have started with Docker not necessarily being ready, as such it fails to communicate with docker. Manually refreshing a short time later, docker will have started and it will find them.

```
error : main ↪️ Kubeconfig path C:\Users\michael.bauer\.kube\config provided does not exist. Skipping.
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose)
log : main ↪️ Activating extension (podman-desktop.docker)
log : main ↪️ Activating extension (podman-desktop.kind)
log : main ↪️ Activating extension (podman-desktop.kube-context)
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima)
error : main ↪️ [lima] Could not find podman socket at C:\Users\michael.bauer\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman)
log : main ↪️ Activating extension (podman-desktop.registries)
log : main ↪️ Activating extension (podman-desktop.compose) ended
log : main ↪️ Activating extension (podman-desktop.docker) ended
log : main ↪️ Activating extension (podman-desktop.kube-context) ended
log : main ↪️ Activating extension (podman-desktop.lima) ended
log : main ↪️ Activating extension (podman-desktop.registries) ended
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
error : main ↪️ (node:42540) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, stat '//./pipe/'
(Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
error : main ↪️ (node:42540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 776.0698000192642ms
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kind) ended
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.podman) ended
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting container engine
log : main ↪️ [podman] Podman extension: Autostarting machine podman-machine-default
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 409.0659999847412ms
debug : main ↪️ [compose] Error while pinging docker Error: connect ENOENT //./pipe/docker_engine
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ error is Error: connect ENOENT \\.\pipe\podman-machine-default
log : main ↪️ error in engine Podman Error: connect ENOENT \\.\pipe\podman-machine-default
log : main ↪️ error in engine Podman Error: connect ENOENT \\.\pipe\podman-machine-default
log : main ↪️ error in engine Podman Error: connect ENOENT \\.\pipe\podman-machine-default
log : main ↪️ error in engine Podman Error: connect ENOENT \\.\pipe\podman-machine-default
log : main ↪️ [kind] kind extension is active
```


After refresh, logs are normal
```
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 443.67560002207756ms
```

**Comment by Zhejing-Chin** [comment]
this is version 1.9.1. Having the same issue of :

> 1. podman desktop not showing the containers and images 
> 2. having Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.

but containers and images are showing with `cmd podman container / image ls`

tried `ctrl R` and restarting / wsl --shutdown. Nothing works.
