### ISSUE TITLE
Magical link for viewing apps in browser easily missed (for pods deployed to OpenShift)

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4178]
### Is your enhancement related to a problem? Please describe

**User task: I want to open up an app I deployed to Kubernetes from a quick access link in the Podman Desktop UI.**

Remotely-deployed pods **only** display in the pods list, **not** the containers list. This means I can't view individual containers in a pod for pods running on OpenShift Local or Developer Sandbox. The issue with that: individual containers have the "Open Browser" action, which figures out the link to view the app in the browser and lets me access the app (handy for a demo. :) ) That looks like this:

![Screenshot from 2023-10-02 14-59-29](https://github.com/containers/podman-desktop/assets/799683/ad269b2e-1d3d-47cb-b3af-2d791b447e4c)

**Both OpenShift Local and Developer Sandbox** provide routes to view apps deployed to them, but right now a user can only access those URLs on the "Deploy to Kubernetes" wizard page at the bottom after the app is deployed. If you click "Done" on that screen, you've lost the magic url forever it seems :(

Here you can see I get the magic url of http://microshift-demo-2-8088-default.apps.crc.testing for my OpenShift Local deployment of pod microshift-demo-2... I get it by clicking on the link where my arrow is pointing in the screenshot, and it pops up a dialog:

![Screenshot from 2023-10-02 15-03-19](https://github.com/containers/podman-desktop/assets/799683/7e82ea11-6bb1-4247-bfa3-24ebaae82042)

Once I click "Done" at the bottom, I cannot find ANYWHERE (even pouring thru the kube and logs for the pod) to get at that magic url again. :( This is the case for both DevSandbox and OpenShift Local deployments in my testing.

### Describe the solution you'd like

It would be very nice for that URL to be accessible after doing the deployment. I'd imagine it being one of the action icons or under the kebab menu for the applicable pods in the pods list with the same "open in browser" text and icon as is displayed for individual containers.

### Describe alternatives you've considered

Displaying OpenShift Local & DevSandbox pods and their containers in the main containers list, and having the magic urls available from there.

**Comment by deboer-tim** [comment]
Issue #2978 is tracking this for the pod details page.
