### ISSUE TITLE
When I build an image from a file or edit an image name, it always gets a prefix "docker.io/library"

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4184]
### Bug description

Is it alright that I always get a `docker.io/library` prefix for an image I build from a file or edit?

### Operating system

Windows 10, Fedora 38

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. build an image from a containerfile
2. Choose a default name `my-custom-image`
3. Check that name fits once the image is done building

Alternative: Edit image

**Comment by jeffmaury** [comment]
Duplicates #2433
