### ISSUE TITLE
One of podified containers from flask-redis example is misplaced in containers group

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4187]
### Bug description

Web container from redis-flask docker compose scenario is misplaced, when pod is created from such compose containers group.

![compose-podify-container-misplaced](https://github.com/containers/podman-desktop/assets/19164299/5278e637-2ff3-40bf-af89-9300e09af33d)

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Install Compose via Podman Desktop
2. checkout awesome-compose flask-redis example project
3. run `compose up -d` in given project
4. Assert: containers got up using compopse via cli - check the output
5. Asset: PD containers page that new containers group is present (with a `compose` label)
6. Mark all containers in the compose group and create a pod
7. Assert: Pod is created and running
8. Assert: New containers group with a new pod name is present in containers page
Actual result: There is a new containers group with a pod name, but one of the containers (web-podified) appeared under compose group and not under new pod's group.

**Comment by lstocchi** [comment]
@odockal could you please try it again when you have time?
I just tested it and it works fine for me
![image](https://github.com/containers/podman-desktop/assets/49404737/377a7dec-5d95-4f28-9b6c-1df7237a7735)

**Comment by odockal** [comment]
@lstocchi Seems it is gone! Tried on windows 10 and now it does not happen.
