### ISSUE TITLE
Resume context service

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4195]
### Is your feature request related to a problem? Please describe

There are some points during onboarding where the user will have to reboot their machine. In other cases the user might be in the middle of something and have a power failure or a crash. It would be nice if we had a simple, non-obtrusive mechanism for resuming where they left off.

### Describe the solution you'd like

An internal API where flows can register a name, callback, and token for context. For example this could just be a command id (since commands have a name) and a string token. When the API is called the data is saved to disk. It can be updated during the flow by calling the API again (maybe only updating the token), or cleared when the flow is done.

On startup, if there was a registered callback the user is prompted with something like "The last time you exited Podman Desktop you were in the middle of <name>. Do you want to resume? Yes/No". The callback is cleared in either case; if the user says yes then the command is called with the token for context.

### Describe alternatives you've considered

A string or object token would be generic enough that the caller could store as much context as necessary (e.g. the properties for fields in a form), but maybe saving the url would be enough for simple scenarios.

**Comment by lstocchi** [comment]
Sounds good to me. 

As a first implementation we just need a way to identify the running onboarding(or the set of running onboardings) so a simple string/token is enough. I don't think i would need any context for the moment, but i see it can be useful in future.

**Comment by deboer-tim** [comment]
The token is the context, so yup, that was the intent. Onboarding might just use a simple string token that said what step the user was on, but it'd be generic enough that something like (e.g.) Run Image could store an object with all the values that the user had entered.
