### ISSUE TITLE
Enhance stability/success rate of user actions

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4206]
### Epic domain

Today, when users are facing some issues, they can create issues and for those with telemetry we can grab events.

But we should be able to know more success rate of a podman machine init command, for operating system, WSL version, etc.

Look at different location of Podman Desktop and see if we're reporting correct error messages, useful properties allowing to know top 10 failures on Windows, on macOS, etc.

### Additional context

We'll add more tasks to this epic after prototyping what we can collect to enhance the overall experience.

Based on this error, we could enhance onboarding, handle more errors or add custom messages explaining how to fix this kind of problem, etc.

**Comment by deboer-tim** [comment]
Opened #4212 and #4213 as specific issues to get started with this.

**Comment by benoitf** [comment]
@deboer-tim https://github.com/containers/podman-desktop/issues/4214 instead of https://github.com/containers/podman-desktop/issues/4212 ?

**Comment by deboer-tim** [comment]
Yes, thanks for correcting 👍🏼
