### ISSUE TITLE
As a new user with no containers yet, the descriptions could be more helpful

### ISSUE THREAD

**Issue by tigert** [containers/podman-desktop#4216]
### Is your enhancement related to a problem? Please describe

@mairin this is a braindump, maybe something useful to you of how my thought process went?

Lets call this "half awake mode" that tossed me down a path I was not expecting since I had just made my first cup of coffee and attempted to wake up. I mean I do know how these things work behind the scenes, but I think my confused walkthrough the podman desktop interface is worth noting down, and might be useful for you to analyze?

## Thus, newly installed podman-desktop. 

I went to the "Containers" tab, and decided to search for Octoprint, but the "search containers" field did nothing. The app suggests that I use the command line to "podman run quay.io/podman/hello". This felt odd, having just installed a desktop app to avoid the command line..?

![image](https://github.com/containers/podman-desktop/assets/2587818/5ed6d444-3e1a-445f-b248-a4f2798fb943)

I was confused, but in my stubbornness I tried the "Create container" button. It offered a choice between a containerfile/dockerfile or an existing image. 

Ha! "Existing image" sounds good, since I know Octoprint has an official image that works fine, I dont want to rebuild it just for the sake of it.

![image](https://github.com/containers/podman-desktop/assets/2587818/1f83e32d-9fdd-495d-808f-10b9bb08839e)

Nope. Of course, because this searches my already downloaded images which would be listed below, if I had any. But I didn't, as I just installed this. Silly me. This is not a registry search for images. But my coffee deprived mind thought it would be.

OK. "Pull image" sounds good then I guess.

![image](https://github.com/containers/podman-desktop/assets/2587818/52e25172-4d6c-4aeb-8d05-ccc867c617a6)

Duh. We _really_ could do a registry search somewhere in here. And I would think the most common reason to not get any results is a query that does not match any images, rather than a real 403 Forbidden error? So if it is not possible to know for sure via the API, maybe swap those around, current behavior made me feel that my podman was not installed or working correctly.

So specifying exactly "octoprint/octoprint" seems to work. 

I know at least dockerhub is a wild west, and there are random images you have no idea what they are, but their "best match" search returned "octoprint/octoprint" (what I needed) as the first result. So maybe just return a bunch of best results from each registry that matches, and offer links to more results for that particular registry?

![image](https://github.com/containers/podman-desktop/assets/2587818/7e6efd09-252f-4af1-b7ee-17f4db27ba98)

OK! Back on track, off I went to spin this container up! That went smoothly.

Have a good day!

### Describe the solution you'd like

It would be nice to offer the search and make it easier to just get stuff going, instead of having to know essentially the same things that you would do in the commandline, but with a GUI app.

What if you have no containers, instead of suggesting the command line, you would suggest to click the "buttons above, and show a list of popular containerized apps that are likely to be interested to the target user?

A bit like an app store but for containers. And the "Create container" button could be three things:

 * From container file to build it (not likely your first choice as a new user, option 3)
 * Spin up a container from your local existing images (also not likely a first choice, option 2)
 * The top choice: Showcase and browse popular apps that are containerized and make sense to run on 
   podman desktop: Octoprint, homeassistant, file server, VPN, minecraft server, or whatever
   target personas we have? 

I am a maker/tinkerer? Making a nice pod from influxdb, grafana and Home Assistant would also be interesting, and showcasing the pod feature with some good example setup. 

Or just pick one good example that we have in the tutorials and let the user get it running with a few clicks?

**Comment by tigert** [comment]
Oh, and since I have the actual laptop running the containers, would it make sense to be able to run podman-desktop on the workstation / laptop and connect to the podman running on the "server" laptop I have? It's mostly running with the lid closed in a vertical stand, so opening it and logging in to run podman desktop would be a lot less convenient than if I could open the app on the computer I am working at?

**Comment by afbjorklund** [comment]
Seems to be a known issue, `podman search octoprint` works

* https://github.com/containers/podman-desktop/issues/971

* https://github.com/containers/podman-desktop/issues/759
