### ISSUE TITLE
Missing CPU/disk/memory info on secondary machines

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4224]
### Bug description

Issue #3111 changed the CPU/disk/memory for Podman machines to Donuts. This looks great on the primary machine, but when you have multiple machines the CPU/disk/memory which used to be grey are now missing. (not entirely sure that's due to #3111, but seems likely?) Not only would it be nice to still have this info on stopped machines, but the missing components lead to layout issues.

<img width="562" alt="Screenshot 2023-10-05 at 3 40 46 PM" src="https://github.com/containers/podman-desktop/assets/19958075/a6a87b80-5bcd-47f8-a271-d9fc74f0d65c">

### Operating system

macOS 14.0

### Installation Method

None

### Version

next (development version)

**Comment by jeffmaury** [comment]
The information is provided by the daemon so hard to get while the machine is stopped

**Comment by benoitf** [comment]
@jeffmaury I think here Tim is asking to display the value without the usage

for example before we had:
![image](https://github.com/containers/podman-desktop/assets/436777/bdcfa550-a689-43d4-8b16-0749a0e4a785)


so we had the memory, cpu, disk allocated to the podman machine

**Comment by deboer-tim** [comment]
Correct, just the data we had before. I don't know what the Donuts should look like (maybe greyed out with those values?), but we're missing this info now and the layout is messed up.
