### ISSUE TITLE
OpenShift extension: does not come up

### ISSUE THREAD

**Issue by rbaumgar** [containers/podman-desktop#423]
### Bug description

I am running on RHEL 8
Podman 4.1.1
Installed podman desktop.
Installed the OpenShift extension from redhatdeveloper/openshift-dd-ext:latest or redhatdeveloper/openshift-dd-ext:0.0.1-41 without any success.
I have only one black screen...

### Operating system

RHEL 8.6

### Version

0.0.6

**Comment by benoitf** [comment]
Hello @rbaumgar I suspect it's a dup of https://github.com/containers/podman-desktop/issues/415

using a pre-release or waiting `v0.0.7` should solve the issue

**Comment by rbaumgar** [comment]
Thanks.

Tried to install on my RHEL 8.6 ...
```
sudo flatpak install podman-desktop-0.0.202208260626-126b831.flatpak
error: The application io.podman_desktop.PodmanDesktop/x86_64/main requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found
```

**Comment by benoitf** [comment]
Hi,

the flatpak is not self-contained and requires dependencies from flathub (This is also why we're adding the flatpak directly to flathub)

could you check https://flatpak.org/setup/Red%20Hat%20Enterprise%20Linux

if a dependency is missing, you can do
```
$ flatpak install org.freedesktop.Platform/x86_64/21.08
```


Note: you can install the flatpak in user mode
flatpak install --user podman-desktop-0.0.202208260626-126b831.flatpak

**Comment by rbaumgar** [comment]
Florent,

user install works well!
OpenShift extension works as well.

**Comment by benoitf** [comment]
Thanks Robert, I'll close the issue
