### ISSUE TITLE
feat: add copy button next to title in details page

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4241]
### Is your enhancement related to a problem? Please describe

I don't like selecting manually the image name especially when it is very long

### Describe the solution you'd like

Adding a copy button next to the title on details page

**Comment by trmendes** [comment]
I would like to work on this issue, and I would like a confirmation of my understanding: The outcome of working on this issue is a copy button on the image details page that, when clicked, will copy the image name.

Please let me know if my understanding is correct or if I'm missing something.

**Comment by benoitf** [comment]
there is a draft PR there https://github.com/containers/podman-desktop/pull/4242 for this issue
