### ISSUE TITLE
not able to get pulled image

### ISSUE THREAD

**Issue by djnotes** [containers/podman-desktop#425]
### Bug description

I am trying to install Docker extensions on Fedora, like  docker/logs-explorer-extension, redhatdeveloper/openshift-dd-ext:latest , etc.

I fail often with the error: not able to get pulled image. When I first installed the app, sometimes the pull started and failed mid-way when some layers fail, causing an image re-pull. So, it kept pulling layers again and again, not often resulting in a successful pull. 
Now, I almost always face the former case, where I encounter the message: not able to get pulled image.

I already have Trivy installed. So, I guess I have had one successful installation at least.

![image](https://user-images.githubusercontent.com/9320387/186909593-ab2e17ad-f6bd-4b29-8108-407109d92bd2.png)

### Operating system

Fedora 36

### Version

0.0.6

### Steps to reproduce

Go to Preferences, Docker Desktop Extensions and enter an extension like docker/logs-explorer-extension and hit "Install extension from the OCI image"

### Relevant log output

```shell
Podman version:

Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 06:42:17 2022
OS/Arch:      linux/amd64
```

**Comment by benoitf** [comment]
your image has no `latest` tag 
https://hub.docker.com/r/docker/logs-explorer-extension/tags

you should try `docker/logs-explorer-extension:0.2.1`

**Comment by benoitf** [comment]
And I'm not 100% sure all internal docker extensions are working on Podman as they might use some specific behavior of Docker (which is not the case of 3rd party like Trivy, OpenShift, etc)

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/186920552-a0526eda-b2d3-4d05-83e9-b80193ba4be3.png)

**Comment by djnotes** [comment]
You are right. Adding the latest tag solved the issue and Podman Desktop started pulling the image. I was able to grab anchore/docker-desktop-extension:latest and docker/logs-explorer-extension:0.2.1 (but not latest).  Could Podman just default the tag to latest?
![image](https://user-images.githubusercontent.com/9320387/186929686-2bcaa43e-223c-4ccb-8f31-2135bcc148d7.png)

**Comment by benoitf** [comment]
@djnotes I think here we might need a browsable list of extensions instead of having users to provide the tag.

In your specific case, it's Docker that is not publishing the images under the `latest` alias and use only specific versions

**Comment by djnotes** [comment]
Where are the tag information for the extensions? I cannot find them on Docker Hub.

**Comment by benoitf** [comment]
If you go on https://hub.docker.com/r/docker/logs-explorer-extension/tags

You see two tabs, and one is for the tags

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/436 when using FQN
