### ISSUE TITLE
feat: opening any of the public ports available instead of just the first one

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#4258]
### Is your enhancement related to a problem? Please describe

When using the `Open browser` on a container with __a lot__ of ports, I would like to be able to select the port to use (and the type: tpc etc.).

### Describe the solution you'd like

Probably a quick pick when multiples ports are available.

### Describe alternatives you've considered

On the `Summary` page, display all the ports with public/private/type as a table, and make them clickable to open the browser on this specific port.

**Comment by benoitf** [comment]
I would say it's a dup of https://github.com/containers/podman-desktop/issues/1349

**Comment by axel7083** [comment]
Close as duplicates
