### ISSUE TITLE
docs: simplify installation guides

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4269]
### Is your enhancement related to a problem? Please describe

The pages count for the installation methods is too high.

```
├── linux-install
│   ├── index.md
│   ├── installing-podman-desktop-from-a-compressed-tar-file.md
│   └── installing-podman-desktop-from-a-flatpak-bundle.md
├── macos-install.md
└── windows-install
    ├── index.md
    ├── installing-podman-desktop-and-podman-in-a-restricted-environment.md
    ├── installing-podman-desktop-silently-with-the-windows-installer.md
    ├── installing-podman-desktop-with-chocolatey.md
    ├── installing-podman-desktop-with-scoop.md
    └── installing-podman-desktop-with-winget.md
```

### Describe the solution you'd like

```
├── installing-podman-desktop (tabs: windows, macos, linux)
│   ├── installing-in-a-restricted-environment (tabs: windows, macos, linux)
│   └── alternate-installation-methods (tabs: brew, windows-silent, chocolatey, winget, scoop, flatpak-bundle, compressed-archive)
```

**Comment by cdrage** [comment]
IMHO I think that heaving them in separate sections per OS rather than one-big-section would beneficial as each environment is getting a lot more complex (Windows with WSL, restricted vs unrestricted).

I believe having a separate page for each OS would be beneficial as it'd also help showcase any troubleshooting / known bugs as well.

**Comment by slemeur** [comment]
The expectations are that we have a single page for the installation on each of the platforms in a non-restricted environment.
- In a single page, I should be able to find all the different methods to install Podman Desktop on Windows. 
- In a single page, I should be able to find all the different methods to install Podman Desktop on MacOS. 
- In a single page, I should be able to find all the different methods to install Podman Desktop on Linux. 

Also the system requirements are lost in the content. Where for windows users, we are telling they need WSL2?

So content should start with:
- System Pre-requisites for the platform
- then one section per method
  - for each method, eventually a "note" about the solution explaining what it is in one line and a link to learn more or download
  - Description of the steps to download and install

Please use section title to provide clarity about the installation method.

The installation procedure for restricted environment must be under the restricted environment section.

**Comment by themr0c** [comment]
This requires clarification.

Do you mean something like this? Keep "Installing Podman" in the "Podman" tree, remove remaining bits from the "Installing" tree.

```
├── Installing Podman Desktop
│   ├── On Windows: sections for: Default installer / Silently / Chocolatey / Scoop / Winget
│   ├── On macOS: sections for: Default installer / Brew
│   └── On Linux: sections for: Default flatpak / Flatpak bundle
├── Restricted environment
│   ├── Installing Podman Desktop: sections for Windows Installer for restricted environments / macOS Disk Image for restricted environments / Linux compressed tar file
│   ├── Using Podman Desktop behind a proxy
│   └── etc ...
├── Podman 
│   ├── Installing Podman with Podman Desktop
│   ├── Installing Podman with OpenShift Local
│   ├── Creating a Podman machine
│   └── Setting Podman machine default connection
```

This is what makes most sense to me: Installing Podman Desktop as a Day zero activity (You do it only once). Installing Podman and creating a Podman Machine as a Day 1 activity (You need to revisit your available resources each time you start a development project). Using Podman as a Day 2 activity (You iter on it every day when working on your development project).

Or, given discussions that we had on the topic, should the installation tree contain everything you need to start a development project with Podman?

```
├── Installing Podman Desktop and Podman
│   ├── On Windows: section 1: Installing Podman Desktop, subsections for: Default installer / Silently / Chocolatey / Scoop / Winget; section 2: Installing Podman, subsections: with Podman Desktop / with OpenShift Local ; section 3: Creating a Podman machine
│   ├── On macOS: sections for: Default installer / Brew; section 2: Installing Podman, subsections: with Podman Desktop / with OpenShift Local ; section 3: Creating a Podman machine
│   └── On Linux: sections for: Default flatpak / Flatpak bundle; section 2: Installing Podman.
├── Restricted environment
│   ├── Installing Podman Desktop: sections for Windows Installer for restricted environments / macOS Disk Image for restricted environments / Linux compressed tar file
│   ├── Using Podman Desktop behind a proxy
│   └── etc ...
├── Podman 
│   ├── Creating a Podman machine
│   └── Setting Podman machine default connection
```

This will lead to more complete "installation" pages for the default Podman workload, but also more long and complex.

**Comment by themr0c** [comment]
Discussed: 

One page per OS to install Podman Desktop and Podman.
