### ISSUE TITLE
Non-updating left-pane UI after clicking on installed extensions

### ISSUE THREAD

**Issue by djnotes** [containers/podman-desktop#427]
### Bug description

In the list of installed extensions, only the Trivy one can be loaded. When I click on any other extension, it fails to load. At this time, the left-pane UI starts to act weird, and if you click on any item on the left pane, it does not work, ALTHOUGH THE UI IS NOT FREEZING. It just loses functionality. Neither the left pane or the right pane are freezing, but they apparently lose communication.

![image](https://user-images.githubusercontent.com/9320387/187012634-612febab-f377-41ac-91ec-02cabd714795.png)

### Operating system

Fedora 36

### Version

0.0.6

### Steps to reproduce

- Go to Preferences, Docker Extensions.
- Install an extension or two
- After the new extensions appear in the list of installed extensions, click on one or more (other than Trivy)
- Try to select any item on the left pane.
- It does not work, meaning the UI on the right does not reflect the left UI selection.

**Comment by benoitf** [comment]
will be fixed by https://github.com/containers/podman-desktop/pull/435
