### ISSUE TITLE
docs: more visibility for OpenShift

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4271]
### Is your enhancement related to a problem? Please describe

As OpenShift is a Kubernetes distribution among others, the documentation states "Kubernetes".

However, it is not helpful for the audience searching specifically for OpenShift.

### Describe the solution you'd like

Write "Kubernetes and OpenShift".

**Comment by slemeur** [comment]
We don't want to provide more visibility to OpenShift - we should be treating it like one of the Kubernetes distribution supported by Podman Desktop amongst the others.

**Comment by themr0c** [comment]
That was a misunderstanding.

https://github.com/containers/podman-desktop/issues/4268 is a better idea.
