### ISSUE TITLE
Design: k8s cluster list

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#4273]
Corresponding development issue:
https://github.com/containers/podman-desktop/issues/3919

**Comment by mairin** [comment]
Initial draft - needs to be moved to settings in the nav:
![K8s Contexts List 2](https://github.com/containers/podman-desktop/assets/799683/d79059ac-c291-4fa1-963b-3ce695c123c8)

**Comment by mairin** [comment]
Updated with appropraite nav and dropping tabs not needed:

![Screenshot from 2023-10-26 08-35-06](https://github.com/containers/podman-desktop/assets/799683/95b8b3a0-1bbb-41ed-b0eb-7685a29dda95)

**Comment by mairin** [comment]
Initial design complete, subsequent design changes will occur in development issue

**Comment by mairin** [comment]
(tabless version of the design for shorter term)

![Screenshot from 2023-10-26 08-37-48](https://github.com/containers/podman-desktop/assets/799683/4085ff00-6faf-497f-b0ea-3ce9780a601c)
