### ISSUE TITLE
Image pull log view too long

### ISSUE THREAD

**Issue by djnotes** [containers/podman-desktop#428]
### Bug description

The log view used for the extension images is too long. It should have a finite hight and support inner scroll. Currently, the scroll is on the window, so the user has to keep scrolling the window to see the end of the log. See the screenshot.

![image](https://user-images.githubusercontent.com/9320387/187014180-f052947d-0f02-46c3-9cfb-938a3be82804.png)

### Operating system

Fedora 36

### Version

0.0.6

### Steps to reproduce

1. Go to Preferences, Docker Extensions
2. Enter a big image name like redhatdeveloper/openshift-dd-ext:latest
3. Start pulling.
4. You will see that the pull log keeps extending to the bottom of the window.
5. Keep scrolling the window to see the end of logs
6. You see this is inconvenient. The scrolling log view, should be nested inside the main pane and have its own scroll rather than using the window's scroll.

**Comment by benoitf** [comment]
yes, agree 👍

**Comment by benoitf** [comment]
will be fixed by https://github.com/containers/podman-desktop/pull/437
