### ISSUE TITLE
Identify functionality gaps between dashboard and settings > resources for container/orchestrator blocks

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4284]
### Is your enhancement related to a problem? Please describe

**This is part of the epic: Container/Orchestrator controls in the Podman Desktop statusbar #4283** 

We need to identify what functionality on the dashboard regarding container / orchestrator setup is only present on the dashboard and not accessible from settings > resources.

For example, if you need to init OpenShift Local, the init button is on the dashboard, but it is not in Settings > Resources in the OpenShift Local card.

The end goal is to make sure all functionality is available in the Settings > Resources area for the engines/orchestrators.... so that we can remove the dashboard blocks and replace with status bar based navigation to Settings > Resources.

### Describe the solution you'd like

This issue doesn't involve any code, it's a research issue.

The assignee of this ticket should go through Podman Desktop across the platforms (Linux, Mac, Windows) and for each engine / orchestrator, test out what functionality is available in dashboard and which is available in settings > resources.

Ideal output is a list of functionality per platform per engine/orchestrator extension that is present on the dashboard that is not present in Settings > Resources.

**Comment by deboer-tim** [comment]
Still required to clean up the dashboard.
