### ISSUE TITLE
Exiting the "Pull Image from Registry" screen brings me to dashboard instead of Images screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4288]
### Bug description

I had a confusing moment and then noticed if you click the close button on the "Pull Image From a Registry" screen, you are taken to the Dashboard screen instead of back to the Images screen.

### Operating system

RHEL 9.4 installed via tarball

### Installation Method

Other

### Version

1.4.0

### Steps to reproduce

1. Click on the images tab
2. Click on "Pull Image"
3. Click "X" in the upper right just above the manage registries button
4. Find yourself on the Dashboard screen instead of the Images screen

**Comment by deboer-tim** [comment]
I was confused what was causing this but finally narrowed it down - it was regressed by PR #3679.

**Comment by benoitf** [comment]
#3679  ?

**Comment by deboer-tim** [comment]
Yup. I'm not saying the code was valid before :) , but changing:
`  detailsPage.set(undefined);`
to:
`  detailsPage.set({ name: 'Home', path: '/' });`
means that in line 56 it sets the last page to 'Home' instead of the list page.
