### ISSUE TITLE
[Design] Style Guide

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4289]
![Screenshot from 2023-10-11 15-21-01](https://github.com/containers/podman-desktop/assets/799683/bcf11863-3117-4079-b8ba-d12d111218f9)

### Epic domain

This is an epic to track the creation of style guide that will define and document the latest design patterns for Podman Desktop's UI. It will consist of the following:

- **Screens:** Implementation of key screen types in Penpot flex

- **Labels:** Labeling of components of key screen types with the corresponding components in the Podman Desktop codebase

- **Component library:** Conversion of individual flex components (e.g., a drop down, a button) into assets in this file so this file can be used as a Podman Desktop component library.

It will be implemented [as a project file in Penpot](https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=2f9ad8cb-8758-80f6-8003-43451f5b3a66) ("Podman Desktop Design System").

### Screens
- https://github.com/containers/podman-desktop/issues/4290
- https://github.com/containers/podman-desktop/issues/4291
- https://github.com/containers/podman-desktop/issues/4292
- https://github.com/containers/podman-desktop/issues/4293
- https://github.com/containers/podman-desktop/issues/4294
- https://github.com/containers/podman-desktop/issues/4295
- https://github.com/containers/podman-desktop/issues/4296

### Labels
TBF

### Component Library
TBF
- New components created for the compose + docker compat feature are in the components page of this penpot file and could be migrated to a central component library: https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/82e31d90-3829-8139-8002-c1a6267ccc6a?page-id=447b50c4-2614-80ea-8002-d2fd93169735

**Comment by ekidneyrh** [comment]
I made some progress on this. The screens can be found in the penpot file here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0

I left some comments on some aspects that I think need more clarification re:colour.

**Comment by mairin** [comment]
@ekidneyrh Awesome work!!!! I just left a bunch of comments inline on the Penpot file!

**Comment by ekidneyrh** [comment]
Closed 4290 - 4296!! Leaving this epic open for converting into light mode and creating components when penpot 2.0 is released.
