### ISSUE TITLE
[Style guide] Flexbox mockup of Dashboard screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4291]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of the latest dashboard screen design. See Dashboard epic https://github.com/containers/podman-desktop/issues/4020 for an overview of components that should be covered.

**Comment by ekidneyrh** [comment]
Completed this in the penpot file. This is what it looks like:
![image](https://github.com/containers/podman-desktop/assets/87311656/3e3df3f3-c556-4700-b9a7-0d7c989f4abe)

The file can be found [here](https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0), under `Screen Flex Mockups / #4291 Dashboard `
