### ISSUE TITLE
[Style guide] Flexbox mockup of List screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4292]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of a list page in Podman Desktop. I think the containers list might be a good one to start with. There is a start at this in the Penpot design system file:

![Screenshot from 2023-10-11 15-06-37](https://github.com/containers/podman-desktop/assets/799683/e908986a-e658-4b0c-b21f-11886a77434e)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/d95a6f82-ae53-495f-b4bc-7ee03f24d07e)

Most of this was complete in the penpot. I just adjusted the bottom bar and cleaned up the file structure a tad. The file can be found [here](https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0), under `Screen Flex Mockups / #4292 List screen`
