### ISSUE TITLE
[Style guide] Flexbox mockup of details screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4293]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of a details screen. Suggest the details screen of an image to start.

Screenshot of the relevant screen:
![Screenshot from 2023-10-11 15-10-41](https://github.com/containers/podman-desktop/assets/799683/bd4c04bf-3e09-459c-80c4-8a39f52ccde1)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/f966afe2-db5d-4aed-bf9a-fdda3c20066b)
![image](https://github.com/containers/podman-desktop/assets/87311656/348aba9d-ff58-4435-8b5d-6abf4871efa4)
![image](https://github.com/containers/podman-desktop/assets/87311656/dcbb1e02-2599-4366-b9fa-31f56a20c5c2)

These can be found in the penpot file here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0

Board names are: #4293 Details Screen 1 - 3
