### ISSUE TITLE
[Style guide] Flexbox mockup of modal dialogs

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4295]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of the modal dialogs. Should be based on the design of this modal, which is the most updated / current design:

![Screenshot from 2023-10-11 15-23-57](https://github.com/containers/podman-desktop/assets/799683/64127af8-c67b-458c-bdb6-0f6e71019346)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/a231054e-6262-4ab0-a256-a377b42dec6c)

These can be found in the penpot file here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0

Board name is: https://github.com/containers/podman-desktop/issues/4295 Modal dialog
