### ISSUE TITLE
Remove doc line "does not automatically set up resources you don't need"

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4298]
### Bug description

I've seen several places where the docs say "Podman Desktop does not automatically set up resources that you might not need." This is a bit odd to me since it's vague, doesn't say what it doesn't install, or if there is some user action to install something if or when you need it later. e.g. Maybe the thing we're not setting up that you don't need is a python compiler? Well I'm glad it didn't do that!

IMHO we should just remove these lines unless we can be specific on something we didn't do that the user needs to know about.

FYI @themr0c 

### Operating system

macOS 14.0

### Installation Method

None

### Version

next (development version)

**Comment by themr0c** [comment]
This sentence is here:

1. To clarify the user expectations: when you have installed the Podman Desktop, you don't have a running container engine. 
2. To justify this "no batteries included" choice, that the user might feel awkward.

Can you help me find a better wording?

**Comment by deboer-tim** [comment]
> This sentence is here:
> 
> 1. To clarify the user expectations: when you have installed the Podman Desktop, you don't have a running container engine.
> 2. To justify this "no batteries included" choice, that the user might feel awkward.
> 
> Can you help me find a better wording?

To me the statement doesn't actually say either of these things. If we want to be explicit I'd change:

> To run container workloads, set up at least one container engine.
> Podman Desktop does not automatically set up container engine resources that you might not need.

to something like:

> Podman Desktop does not automatically install any container engine. To run container workloads, you need to install at least one container engine from the list below.
