### ISSUE TITLE
Reduce website footer

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4299]
### Is your enhancement related to a problem? Please describe

The website footer has a Documentation column with 8 links, a Links column with 7, and then a copyright and license. In the window I was loading the website that was 40% of the page height, which to me looks too big and unpolished.

### Describe the solution you'd like

I think we should cut it down to ~4 links per side. Docs we should be able to reduce to the more common pages, and for links we could remove the Blog (already on the header), Github (also on the header), and maybe cut down on the duplicate text or merge two onto one line.

Put copyright and license on one line?

### Describe alternatives you've considered

Move some of this to a resources or community page.

**Comment by themr0c** [comment]
This is the link of links on the left side:

1. Installing Podman Desktop
2. Onboarding for containers
3. Onboarding for Kubernetes
4. Working with containers
5. Migrating from Docker
6. Working with Compose
7. Working with Kubernetes
8. Troubleshooting

The most compact  summary I can think of would be:

1. Installing Podman Desktop
2. Onboarding for containers
3. Onboarding for Kubernetes
4. Working with containers
5. Working with Kubernetes

But: Migrating from Docker, Working with Compose, and Troubleshooting are in the top 6 most viewed pages. I believe it would be a mistake to make them less visible.

On the other hand, these links only make sense when you are not in the documentation.  They could be all removed. We already have a link  to the documentation in the top navigation bar (but few people are using this link: intro is ranked 22 in the most viewed pages).


What do you suggest?

**Comment by themr0c** [comment]
I believe all links on the right side could move away:

1. Blog
2. GitHub
3. General chat (bridged): #podman-desktop on Discord
4. General chat (bridged): #podman-desktop@libera.chat on IRC
5. General chat (bridged): #podman-desktop@fedora.im on Matrix
6. Kubernetes chat: Join #podman-desktop on the Kubernetes Slack
7. Podman Desktop Planning & Roadmap

Remove 1. and 2., they are redundant: already at the page top.
Move 3. to 7. to a Community or Contact page to add in the top navigation.

**Comment by cdrage** [comment]
> I believe all links on the right side could move away:
> 
> 1. Blog
> 2. GitHub
> 3. General chat (bridged): #podman-desktop on Discord
> 4. General chat (bridged): #[podman-desktop@libera.chat](mailto:podman-desktop@libera.chat) on IRC
> 5. General chat (bridged): #[podman-desktop@fedora.im](mailto:podman-desktop@fedora.im) on Matrix
> 6. Kubernetes chat: Join #podman-desktop on the Kubernetes Slack
> 7. Podman Desktop Planning & Roadmap
> 
> Remove 1. and 2., they are redundant: already at the page top. Move 3. to 7. to a Community or Contact page to add in the top navigation.

IMHO A footer should still mention Blog and GitHub... honestly you reach the bottom of the page sometimes and you want a quick way to click on that link.

3 to 7 I do not agree regarding removing them, but I do agree on ALSO putting it on a "contact" page similar to how we do it with the Github README.md
