### ISSUE TITLE
Doc tabs should select current OS by default

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4301]
### Bug description

When I go to the Kubernetes > Selecting a context page, it defaults to Windows even though I'm on a Mac. It should preselect the current OS. (this makes me concerned that #4280 will work correctly)

### Operating system

macOS 14.0

### Installation Method

None

### Version

next (development version)

**Comment by themr0c** [comment]
- In the home page, there is OS detection: the first time you browse the page, you see the first tab corresponding to the detected OS.
- In the docs, there is no OS detection: the first time you browse the page, you see the first tab in the list. 
- In the docs, your last selection is stored, and if you selected macOS for instance, you'll see the macOS tab in nex docs pages.

AI: Add to the docs OS detection similar to what works in the home page.
