### ISSUE TITLE
Rename onboarding, flow with install

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4302]
### Is your enhancement related to a problem? Please describe

Two issues:
1. I can't find it atm, but in the last 24h someone who was likely @themr0c :) posted a question about the term Onboarding. To me, 'onboarding' is how product managers and developers talk about getting users started on a tool, but no user ever said 'I want to onboard now'. When they go to the docs they're either looking to 'install' another bit, 'configure', or 'setup' something.

2. As a user the flow is that I install Podman Desktop, and then to do anything useful with it I install a container engine or Kubernetes provider. Maybe instead I configure one I already had installed. And maybe I come back in a few weeks to install or configure a second or third provider. Currently, the docs 'end' after PD installation and it's not obvious you onboard to add another tool later.

### Describe the solution you'd like

For 1, I think we just need to pick a different term.

For 2, I think we need to do some similar reorganization to #4280:
- make the end of installing PD flow into onboarding a bit, e.g. 'what's next' is installing a container engine or Kube.
- move installing container engines and Kube providers up one level to be top-level links (easy to find later).
- normalize the options under each section a little. Kubernetes is pretty good, but options could be sorted, and maybe 'Existing Kube' should be something like 'Other Kube' and at the bottom. For Containers children the word 'Installing' should be removed, likely just have secondary options for Podman, Docker, and Lima. (i.e. custom Podman should be with Podman)

**Comment by themr0c** [comment]
For 1: "Setting up resources for container workloads" and "Setting up resources for Kubernetes workloads" are the most accurate, but are too long for navigation. What do you suggest?

**Comment by deboer-tim** [comment]
FWIW, I think it's worth looking at a few similar sites to see how they structure and what sections they use (e.g. VS Code has all initial install and configuration under a single Setup section) and we get some agreement on an overall layout before we rename or move individual pages around.

**Comment by slemeur** [comment]
I think this has been addressed with the revamp of the structure of the documentation
