### ISSUE TITLE
PatternFly cleanup

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4319]
### Epic domain

We no longer have any direct dependency on PatternFly, but removing it breaks three things:

1. Missing RedHatText font.
2. Missing Font Awesome 5 font, along with the fa and fas classes.
3. Some global CSS properties. The only two that I've found make any difference can be replaced by:
```
  color-scheme: dark;
  line-height: 0.9rem;
```

In order to remove PatternFly completely we'll need to remove it from App.svelte (and eventually the packaging) at the same time we release PR(s) to fix all of these things.

The only immediate benefits will be a slightly smaller package/load time, but this would make it easier in the future for us to do light mode/themes, and have only one copy of Font Awesome (6 vs current 5 + 6).

**Comment by benoitf** [comment]
it's somehow linked to https://github.com/containers/podman-desktop/issues/1617

**Comment by deboer-tim** [comment]
Arg, I forgot about those and was searching for the wrong PF classes. We will need to complete the three items in #1617 before we do this final switch.
