### ISSUE TITLE
Consistent unqualified-search behaviour between UI and CLI

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#4324]
### Is your enhancement related to a problem? Please describe

`podman pull hello` from the CLI is going to work out of the box and pull quay.io/podman/hello
Doing it from the UI of podman desktop does not work.

But doing it with just `redis` is working from both CLI and UI

### Describe the solution you'd like

Consistent behaviour between the CLI of podman and the UI provided in podman desktop.
Should be using the same "unqualified-search"

**Comment by jeffmaury** [comment]
Seems to be a podman issue as `docker pull hello` returns an error when compatibility mode is on.
