### ISSUE TITLE
When pulling the image that is big enough there is no way to track progress when you leave pull image page

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4338]
### Bug description

Pulling a huge image takes time. If one switches to other tasks in podman desktop before pull is over there is no way to see the progress or see that image pull is actually in progress.

https://github.com/containers/podman-desktop/assets/620330/f49a0d0d-4595-443e-8673-3ca3af623eb5

### Operating system

macOS Sonoma 14.0

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Open pull image form
2. Start pulling image docker.io/sagemathinc/cocalc
3. Switch to containers
4. Switch to images 
5. Push pull image button
6. There is no indication pull is still in progress, because pull form is empty and task view has nothing in it

**Comment by deboer-tim** [comment]
Keep open. I've hit this recently, can't tell PD is 'doing something'.
