### ISSUE TITLE
Microcks Extension fails to initialize

### ISSUE THREAD

**Issue by hguerrero** [containers/podman-desktop#4357]
### Bug description

When installing the Microcks Docker Desktop Extension on Podman Desktop there is an error that stops the containers to start.

### Operating system

macOS Ventura 13.6

### Installation Method

Brew (macOS)

### Version

1.4.0

### Steps to reproduce

Install podman desktop

Try to install the microcks extension:

hguerrero/microcks-docker-desktop-extension:0.2.2

**Comment by jeffmaury** [comment]
From my analysis, it seems that we are running `docker-compose ps --format json` and we expect a json array but a single object is returned (because a single container is running).
