### ISSUE TITLE
Kubernetes Services page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4368]
### Is your feature request related to a problem? Please describe

The podify flow creates Kubernetes services, but there is no way to view them or clean them up from within Podman Desktop, and hence rerunning the flow doesn't work.

### Describe the solution you'd like

Add a new main nav item for Kubernetes Services, a list page, and details page - similar to what we have for Containers or Pods. Users should be able to delete services.

**Comment by cdrage** [comment]
I humbly request that if I can take this up for this upcoming sprint! I'd like to finally see Services on there / port mapping. 

I've been working with https://github.com/containers/podman-desktop/issues/4576 so would like to see some of the design mockup implemented.
