### ISSUE TITLE
Allow to add additional binary search path (on Win and MacOS)

### ISSUE THREAD

**Issue by arixmkii** [containers/podman-desktop#438]
### Is your enhancement related to a problem? Please describe

When you build podman binary from sources you need to install it to the system paths, because for example on Windows PATH is always prepended by default install directory and if you have stable installation it will always use this.

### Describe the solution you'd like

Environment variable to give the highest priority search path, like it is done in other podman projects. Example here: https://github.com/containers/common/blob/72a7da3358ac8c560c0d685651e2acf53f7af074/pkg/config/config.go#L1299

Haven't checked if the problem exists in Linux.

### Describe alternatives you've considered

Instead of hardcoded binary name, use env var override if set. This will allow to add `mycustompodman` or `mycustompodman.exe` to path and use it. But this could be considered as a different feature and be used together with the one described in this issue.

**Comment by benoitf** [comment]
we have a way to customize the path of the podman binary now
