### ISSUE TITLE
Only show the log terminal for building a container when it's actually building

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4382]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-10-17 at 7 11 46 PM](https://github.com/containers/podman-desktop/assets/6422176/7df6fa87-aa2d-4547-9c25-75e8136d1967)

The blank terminal output provides no information and it looks like it's been misplaced.

### Describe the solution you'd like

Only show the terminal area when the container is building.

**Comment by deboer-tim** [comment]
I totally agree... but I also think we need some part of #4296 or there are several other form screens where we'll be doing fixes like this until we agree how they should all work.

**Comment by cdrage** [comment]
@mairin Recent discussion had started, but @deboer-tim and I had a brief discussion that maybe we should have something similar to a "Spinner saying "building" and a button saying "show details""? Which would eliminate the entire black square / console output but nothing showing.
