### ISSUE TITLE
Stop all containers at once and block container or image removal

### ISSUE THREAD

**Issue by brunomcuesta** [containers/podman-desktop#4385]
### Enhancement description

Hello!
It would be interesting to have a button or option in the three-dot action menu that would allow stopping all containers that are running.
In this example I have [DefectDojo](https://github.com/DefectDojo/django-DefectDojo) running with several containers.

![image](https://github.com/containers/podman-desktop/assets/816237/d773ba73-bf4c-4a89-b79b-f686637c7488)

When you press "play" on the main container (compose), all containers are started and the **initializer** container stops automatically after finishing its task. It is the default behavior of this container.

> 
> **Initializer**
> The Initializer setups / maintains the database and syncs / runs migrations after version upgrades. It shuts itself down after all tasks are performed.

**Source**: https://defectdojo.github.io/django-DefectDojo/getting_started/architecture/

The problem is that in Podman Desktop there is no option to stop all containers at once, I need to stop each container individually. And this problem occurs because one container has stopped and the others continue running.

![image](https://github.com/containers/podman-desktop/assets/816237/90f1d8a2-8707-4894-8570-eadf2fbbf778)

To avoid having to stop each container through Podman Desktop, I am forced to stop through the terminal with the command below:

`podman stop --all`

Another problem is that sometimes I accidentally removed a container when I wanted to start/stop it. 

![image](https://github.com/containers/podman-desktop/assets/816237/14f5a374-a80a-4741-93b9-b224c6d1d7c6)

### Possible solution

**Solving the problem of stopping all containers at once.**
The solution could be to place a button in the main container that stops all containers. Or add an option to "Stop all containers" in the "actions" menu.

![image](https://github.com/containers/podman-desktop/assets/816237/b7531d20-395f-4d2f-a259-29aa779a08f4)

**Solving the problem of removing container or image by accident.**
It would be interesting to have an option in the "actions" menu to block the removal of the container, placing an option "protect container" or "block deletion" with a lock icon. This way the user will be able to start and stop containers without the risk of deleting them by mistake.

![image](https://github.com/containers/podman-desktop/assets/816237/fc83280c-9f1d-4854-bd9a-aeae048e7ede)

Placing an icon or changing the color of the text in the container name or image would be a way of showing the user that the container is protected from accidental removal.

**Comment by slemeur** [comment]
Thanks for the feedback @brunomcuesta ! It's indeed something that could be a nice improvement.
