### ISSUE TITLE
Make action buttons on container / image / pod screens more subtle.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4396]
### Is your enhancement related to a problem? Please describe

Unsure if I'm the only one, but I find that the top right buttons on the container / pod / image list screens are very vibrant / obnoxious compared to the rest of the screen.

For example, there is:
- Prune pods (barely used?)
- Play Kubernetes YAML (I'm unsure if it's used much?)

Both are large and purple and I feel should be more "subtle"?

### Describe the solution you'd like

More subtle buttons

![Screenshot 2023-10-18 at 8 43 53 AM](https://github.com/containers/podman-desktop/assets/6422176/7c8c2089-582c-4ec6-bfc8-c026743b0bb6)

**Comment by SanchitMahajan236** [comment]
Would you like a change in colour or introducing something like opacity to the buttons ?

**Comment by cdrage** [comment]
> Would you like a change in colour or introducing something like opacity to the buttons ?

Most likely use the same styling as we do with the "Cancel" button, but we should ask @mairin first

**Comment by deboer-tim** [comment]
We should get input from @mairin. I already made the buttons a shade darker than the original designs; not sure if this should be discussed just for the lists or all buttons (which we have in Button component, a couple odd buttons, and markdown, ...).

**Comment by mairin** [comment]
Ah yeh I agree with this! I have some designs where the button outlines are dropped on the screen-wide actions (e.g. play yaml / create):

![Screenshot from 2023-10-21 21-28-24](https://github.com/containers/podman-desktop/assets/799683/59bd0496-4957-41e4-b819-e3b19037390c)

And what I did is keep the button outline on the items that applied to selections in the list:

![Screenshot from 2023-10-21 21-29-48](https://github.com/containers/podman-desktop/assets/799683/1a943f37-7c49-4896-b017-f8b130c58128)

The idea is you have only one filled purple button and only for something that's the default / recommended path (e.g., "next" on a wizard)

WDYT?

**Comment by deboer-tim** [comment]
So basically 'link' button style for general/always-there actions, 'primary' for the default/natural action in a form, and 'secondary' (outline) for other form actions? It will take some getting used to (and some time to get through every screen...), but I think it's probably better in terms of drawing your attention to the right places and reducing distraction.
