### ISSUE TITLE
Buttons on top right should be in order of least-used to most-used.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4397]
### Is your enhancement related to a problem? Please describe

On each Pods / Images / Images screen, action buttons should be from the other of least-used to most-used.

For example, on Containers is should be:

- Prune containers
- Play Kubernetes YAML
and THEN Create a container.

![Screenshot 2023-10-18 at 8 51 45 AM](https://github.com/containers/podman-desktop/assets/6422176/6cfb2d61-efb7-4bfe-9e1e-2cf6868935c6)

IMO it's a bit weird seing "Play Kubernetes YAML" as the top right button when Create a container is most likely the one used the most..

### Describe the solution you'd like

"Create" option should always be top right.

**Comment by SanchitMahajan236** [comment]
I would love to contribute to this issue. Can you please assign me this issue ?

**Comment by cdrage** [comment]
Sure! This would be an awesome contribution, assigned it to you @SanchitMahajan236

**Comment by cdrage** [comment]
@SanchitMahajan236 Hi, what's the progress on it? If not, I'm able to take it up.

**Comment by SanchitMahajan236** [comment]
I apologise for the delay, got stuck with some college submissions. I will generate a PR by today or tomorrow.
