### ISSUE TITLE
Buttons have redundant naming (Prune images, Create an image), should be just Prune and Create.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4399]
### Is your enhancement related to a problem? Please describe

Throughout the listing, the names are redundant. You click on the Image section, you expect a "Create" button.

But instead we have Create an Image, Prune Images, etc.

It should be implied that if you click on "Prune" in the Images section, it's related to images.

![Screenshot 2023-10-18 at 8 58 13 AM](https://github.com/containers/podman-desktop/assets/6422176/ea38a39d-2e1c-4c62-a0a2-ae59e0b8a108)

### Describe the solution you'd like

Should be Prune, Build, Create.

**Comment by edvardsanta** [comment]
Just for images or all sections?
For example, Container Section:
![image](https://github.com/containers/podman-desktop/assets/75655486/343476ea-e6df-457e-b4bf-cb1e7111a78e)
Images:
![image](https://github.com/containers/podman-desktop/assets/75655486/cd19046d-826d-40b2-a56f-3d01859923ce)
Pods:
![image](https://github.com/containers/podman-desktop/assets/75655486/92cbeced-b7a3-4b47-ad54-9cacce742e04)
Volumes:
![image](https://github.com/containers/podman-desktop/assets/75655486/9db2a856-4120-49b3-a6d4-a1fc24c45051)

**Comment by deboer-tim** [comment]
@mairin thoughts?

I'm ok removing the 'redundant' text, but I'd put something similar to the original title in the tooltip - some buttons have them today; some are missing.

**Comment by cdrage** [comment]
> Just for images or all sections? For example, Container Section: ![image](https://user-images.githubusercontent.com/75655486/276366675-343476ea-e6df-457e-b4bf-cb1e7111a78e.png) Images: ![image](https://user-images.githubusercontent.com/75655486/276366836-cd19046d-826d-40b2-a56f-3d01859923ce.png) Pods: ![image](https://user-images.githubusercontent.com/75655486/276366931-92cbeced-b7a3-4b47-ad54-9cacce742e04.png) Volumes: ![image](https://user-images.githubusercontent.com/75655486/276367078-9db2a856-4120-49b3-a6d4-a1fc24c45051.png)

All sections yup.

**Comment by edvardsanta** [comment]
So @deboer-tim, can i commit my changes?

Edit: Where/what is tooltip?

**Comment by deboer-tim** [comment]
Yes, please feel free to submit a PR. We can always continue discussion there, and gives everyone a chance to try it.

You can set tooltips via the `title` attribute (poorly named to match HTML button), e.g.: `<Button title="This is the tooltip">Click me</Button>`

**Comment by mairin** [comment]
@deboer-tim 👍 This is a good idea @cdrage

**Comment by deboer-tim** [comment]
@edvardsanta are you still good to create a PR?

**Comment by edvardsanta** [comment]
@deboer-tim, i will create the pr tomorrow, I did the changes related to the buttons and change the title in one test, i will create the pr and hope get some feedback what to change or improve. Thank you for your interest, I was very busy.
