### ISSUE TITLE
KubeUI: Add environment column to containers and pods lists

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4401]
### Is your enhancement related to a problem? Please describe

The environment chiclets in the pods list are not clear enough and we have feedback that a column should be used instead.

### Describe the solution you'd like

Create a new environment column in the pods list.

**Comment by cdrage** [comment]
Sorry, bit confused with regards to what you mean by environment column? As in which context / provider is being used?

Or does this mean environment variables from the pods?

Unsure if we have a mockup for this too? @mairin

**Comment by mairin** [comment]
@cdrage Oh sure. So "Environment" would be a net new column but it would have a little taggy thing for provider (for podman | docker | lima) or context (for k8s). Here is a mockup for it:

![Screenshot from 2023-10-21 20-52-41](https://github.com/containers/podman-desktop/assets/799683/3a38c8ea-1dcf-4923-816b-1c4da3cecde2)

(Do note there's an extra layer of grouping background color here behind the pod rows... you can ignore that extra layer and stick with the existing color scheme of the UI now, which is inverted from this mockup but should be the same color names.)

**Comment by cdrage** [comment]
@mairin 

So for the implementation, it's the provider OR the context for kubernetes.

So for Kubernetes it will always be a lower-case context name for it, but there's no indication that it's kubernetes, should we have it as (for example: `kind-cluster (kubernetes)` or something like that?

OR we do it similar to how we show Docker / Lima where we say Kubernetes capitalized and then (outside the little dot + provider name area) have the namespace in lighter font below it.

**Comment by cdrage** [comment]
![Screenshot 2023-10-31 at 12 08 45 PM](https://github.com/containers/podman-desktop/assets/6422176/236eb14a-c133-41d0-b4c5-23b45c79f9f2)

Something like this with the namespace outside-of-it. 

Right now we have it implemented as being shortened to 16 characters with the tool tip to show the full name.

**Comment by deboer-tim** [comment]
It would be handy to have the context in a bracket or tooltip, but I think the intention is that the environments are the Container/Kubernetes connection names (like "My Kind" and "Podman Machine 7"), not the Kube context.

**Comment by cdrage** [comment]
@deboer-tim Ah got it, so maybe just say Kubernetes and then when you hover it'll show the context name?

Luckily right now we only support one context at a time, we can tackle the idea of listing multiple Kubernetes contexts / environments at a later date.

**Comment by cdrage** [comment]
So this is being added to Pods and Containers, should we open an issue / add this to Images / Volumes etc too?

![Screenshot 2023-10-31 at 8 53 24 PM](https://github.com/containers/podman-desktop/assets/6422176/f887474c-46ba-4660-b30f-921cfe5cf5a6)
