### ISSUE TITLE
List of grouped images

### ISSUE THREAD

**Issue by brunomcuesta** [containers/podman-desktop#4408]
### Description of the improvement

Hello!
A big problem with Podman Desktop is the organization of the image list. I don't know which image belongs to which project. The main problem is generic images like library/python and library/nginx.

![image](https://github.com/containers/podman-desktop/assets/816237/4efdc863-b956-4ed0-a83a-f42406c14571)

The same happens with the volume list. They could be grouped by project.

![image](https://github.com/containers/podman-desktop/assets/816237/41880cdf-2522-4b7a-a542-d9325da1ca3a)

### Possible solution

When something is installed, all images must be grouped together, this way the user will not delete an image that belongs to another project. It could be grouped, as was done with containers. It is necessary to better highlight this separation of images with colors. Maybe put softly colored borders on this grouping of images, volumes and containers.

![image](https://github.com/containers/podman-desktop/assets/816237/b4a7d0e7-cfaf-4aea-87e2-750d9031d78b)

The improvement idea of ​​removing all items from the group at once could also be included. An option "remove all volumes" from a group and "remove all images" from a group in the "actions" menu.

Thanks and best regards!

**Comment by jeffmaury** [comment]
@brunomcuesta thanks for the enhancement proposal. However, what you mean by project ?

**Comment by brunomcuesta** [comment]
Hello @jeffmaury !
The project would be an application installed from a docker-compose.yml or Dockerfile. In the list of containers it appears as "compose".

![image](https://github.com/containers/podman-desktop/assets/816237/8d943f6b-78be-4dee-8407-e62e89e3834a)


Let's suppose I want to install two applications (projects), DefectDojo and reNgine. Podman Desktop could group the images and volumes of each one, this way the user would know which images and volumes are for each installed application.
Thanks!

**Comment by jeffmaury** [comment]
When you run a compose project, it will run containers that can be associated with the compose project. But images are lazy loaded and they cannot be associated with the compose project

**Comment by benoitf** [comment]
There is a way to know by which container the images are used so there could be a view to display it in the reverse way but you might see in that case a single dummy container using `httpd` image and then this image being used inside the `docker-compose-my-app` application

so you might think you can safely delete the image `httpd` as it was used in a dummy container but it's still used by another app (as there is 1..n relationship)

**Comment by mairin** [comment]
A lighter way to solve this might be, to allow the user to hover over the lit up icon (that indicates the image is being used) and have the list of containers / pods using the image... right now it just says "USED" - 

![Screenshot from 2023-10-21 20-24-49](https://github.com/containers/podman-desktop/assets/799683/6667638d-1c57-48dc-81b9-27691297c725)

The reason it's good to know which containers are using it, IIRC you cannot delete the image until you stop / delete the containers using it.
