### ISSUE TITLE
Pod creation button should say "Create Pod" as small icon is hard to understand.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4413]
### Is your enhancement related to a problem? Please describe

When creating a Pod from a group of containers, it's hard to understand what the icon means. 

The trash-can however is explanatory. 

So it's inline with other buttons (Create for container, Volume, Image, etc.), we should add text to the side as well saying "Create Pod".

<img width="289" alt="Screenshot 2023-10-18 at 10 19 24 PM" src="https://github.com/containers/podman-desktop/assets/6422176/1197984f-eb5f-4ca4-9d8a-d2a38ba7e5bf">

### Describe the solution you'd like

Text to be shown when creating Pod.

**Comment by ecrookshanks-rh** [comment]
Hi.  Since this is labeled as a good first issue I would like to be assigned this enhancement.

**Comment by benoitf** [comment]
OK it's now assigned to you @ecrookshanks-rh

**Comment by cdrage** [comment]
Closed via #5095
