### ISSUE TITLE
Kube context delete

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#4417]
### Is your enhancement related to a problem? Please describe

As Kube contexts are going to be first class citizen in Podman Desktop and displayed nicely, we should be able to delete them as Kubeconfig may have a lot of obsoleted contexts

### Describe the solution you'd like

On the Kubecontext UI we should be able to see a delete button/icon

**Comment by feloy** [comment]
- do we want to display a popup to explain what will happen, when clicking the Delete button and before to delete the context?
  - -> no
- In case of error (for example file not writable), how do we want to display the errror, popup, ...?
  - -> in the UI if some place is available, or in a popup, 
- do we want to update the current-context when it is removed?

**Comment by deboer-tim** [comment]
As per Ander's comment in #4812, maybe the one time we should display a confirmation popup is when you're trying to delete the current context?
