### ISSUE TITLE
Onboarding on Linux Fedora

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#4428]
### Bug description

When podman is not installed in my system, Podman Desktop does not help me install it, but indicates it is already installed instead.

### Operating system

Linux Fedora

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- uninstall podman
- rm -rf ~/.local/share/containers/podman-desktop/ ~/./podman-desktop/
- yarn watch

It is correctly detected that the podman cli is not present:

![issue-onboarding-linux-1](https://github.com/containers/podman-desktop/assets/9973512/745f032b-b1dc-4759-8e7a-eb1ce10d1e7c)

But Podman is displayed as Installed in the main page:

![linux-onboarding-2](https://github.com/containers/podman-desktop/assets/9973512/88d7310b-37a2-468d-af5f-dd230f22c445)

And in the Settings / Extensions / Podman:

![linux-onboarding-3](https://github.com/containers/podman-desktop/assets/9973512/69937ffe-f539-4ee2-b412-ca3ee6fd9a9f)

**Comment by benoitf** [comment]
I think we might not be good in what we display, but in one case it's podman CLI that is not found and in other screens it's podman extension that is enabled and running

so podman extension runs but does not find 'podman CLI'

if you in resources page, do you see a 'setup' button where you can click on podman tile ?

**Comment by feloy** [comment]
OK, yes, I can see the Setup button for Podman on the Resources page.

**Comment by feloy** [comment]
I'm getting at this point, and I have installed podman with the given command in the instructions.

But I don't know what to do next. Should I click to 'skip the entire setup >>' ?

I would expect to have a button 'Installation done. Next'

![linux-onboarding-4](https://github.com/containers/podman-desktop/assets/9973512/5a88047c-971a-4adc-a21c-a3a768538847)

**Comment by feloy** [comment]
After installing Podman, going to the Resources page again, the Compose resource is not configurable (no Setup button visible).

Idem if I stop and restart Podman Desktop.

![linux-onboarding-5](https://github.com/containers/podman-desktop/assets/9973512/209b9072-9238-423c-947d-789e4e3ae90a)

**Comment by feloy** [comment]
I have seen the button appear after some navigation (I don't know which pages), but it disappeared again when I stopped/started Podman Desktop, and I cannot make it appear again now

**Comment by feloy** [comment]
> I'm getting at this point, and I have installed podman with the given command in the instructions.
> 
> But I don't know what to do next. Should I click to 'skip the entire setup >>' ?
> 
> I would expect to have a button 'Installation done. Next'
> 
> ![linux-onboarding-4](https://user-images.githubusercontent.com/9973512/276661232-5a88047c-971a-4adc-a21c-a3a768538847.png)

Also, after this install process, it seems that I need to go to the Extensions / Podman page to Disable and Enable the extension to be able to see the containers / pods running in Podman

**Comment by feloy** [comment]
> I think we might not be good in what we display, but in one case it's podman CLI that is not found and in other screens it's podman extension that is enabled and running
> 

OK, I didn't clearly understand this difference from the beginning I'm using the Desktop :(  I think that displaying the Extensions in the main page is disturbing, I would expect to see them only when I go to a specific Extensions page (for example in VScode we need to go to the Extensions page. And see in the main page the "production" information: if the runtimes themselves are running and accessible.

**Comment by afbjorklund** [comment]
> And see in the main page the "production" information: if the runtimes themselves are running and accessible.

This is how the Docker provider works, it magically appears when the socket is there* and disappears when it is not.

\* the package is called "moby-engine" on Fedora ("docker.io" on Ubuntu)

Unfortunately, Podman Desktop tries to run `podman system service` itself.

**Comment by lstocchi** [comment]
> I'm getting at this point, and I have installed podman with the given command in the instructions.
> 
> But I don't know what to do next. Should I click to 'skip the entire setup >>' ?
> 
> I would expect to have a button 'Installation done. Next'
> 
> ![linux-onboarding-4](https://user-images.githubusercontent.com/9973512/276661232-5a88047c-971a-4adc-a21c-a3a768538847.png)

Just to clarify. You reduced the Desktop window, installed podman, then went back to the Desktop window and nothing happened even if you waited 8 secs, correct? 

Just asking because there is a loop where we check if podman is installed every 8 seconds. And we update the context value that tells the onboarding to proceed

**Comment by lstocchi** [comment]
> After installing Podman, going to the Resources page again, the Compose resource is not configurable (no Setup button visible).
> 
> Idem if I stop and restart Podman Desktop.
> 
> ![linux-onboarding-5](https://user-images.githubusercontent.com/9973512/276662587-209b9072-9238-423c-947d-789e4e3ae90a.png)

Did you remove compose, right? The setup button should be shown if `docker-compose --version` do not return any result

**Comment by feloy** [comment]
> > I'm getting at this point, and I have installed podman with the given command in the instructions.
> > But I don't know what to do next. Should I click to 'skip the entire setup >>' ?
> > I would expect to have a button 'Installation done. Next'
> > ![linux-onboarding-4](https://user-images.githubusercontent.com/9973512/276661232-5a88047c-971a-4adc-a21c-a3a768538847.png)
> 
> Just to clarify. You reduced the Desktop window, installed podman, then went back to the Desktop window and nothing happened even if you waited 8 secs, correct?
> 
> Just asking because there is a loop where we check if podman is installed every 8 seconds. And we update the context value that tells the onboarding to proceed

No, nothing happens after 10s. Here is a complete session:

https://github.com/containers/podman-desktop/assets/9973512/82205cac-5403-4b2d-a48b-7616ecfa5369

**Comment by feloy** [comment]
> > After installing Podman, going to the Resources page again, the Compose resource is not configurable (no Setup button visible).
> > Idem if I stop and restart Podman Desktop.
> > ![linux-onboarding-5](https://user-images.githubusercontent.com/9973512/276662587-209b9072-9238-423c-947d-789e4e3ae90a.png)
> 
> Did you remove compose, right? The setup button should be shown if `docker-compose --version` do not return any result

Oups, I forgot to delete it. When I delete it, I can see some problems, see session:

https://github.com/containers/podman-desktop/assets/9973512/f1491081-3d18-494e-816e-77dc42331eac

**Comment by slemeur** [comment]
@feloy : Could you check and confirm that #4455 is properly fixing the issue you faced?

**Comment by feloy** [comment]
> @feloy : Could you check and confirm that #4455 is properly fixing the issue you faced?

Yes, the installation of podman is now correctly detected on Linux during the onboarding

But I can still see the problem that Podman is not correctly restarted and we need to Disable / Enable it manually before we can see the containers/pods present in the machine.
