### ISSUE TITLE
compose onboarding works well but status bar still offers Install compose

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#4429]
### Bug description

When I ran the compose onboarding; it did download and install the docker-compose binary. After the install is done, the status bar still offers to Install compose

### Operating system

Win11Pro

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Onboard Podman
2. Onboard Compose

### Additional context

![compose-onboarding](https://github.com/containers/podman-desktop/assets/695993/a56c5d5f-b5a9-489b-ae99-f7d389ecc86e)

**Comment by cdrage** [comment]
Yup this is intentional, we need to remove Compose from the status bar #3809 when we are 100% comfortable with Compose onboarding. As the status / steps to install is a bit broken at the moment.

**Comment by jeffmaury** [comment]
Duplicates #3809
