### ISSUE TITLE
add to contextBridge.exposeInMainWorld: add the ability to load / write a YAML file with validation

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4432]
### Is your feature request related to a problem? Please describe

When implementing https://github.com/containers/podman-desktop/issues/725 I had to add functionality to load / write YAML files via `preload/index.ts`: https://github.com/containers/podman-desktop/compare/main...cdrage:podman-desktop:paste-yaml-kubernetes-play#diff-a5b4035e012308c2f43a5a17ddc2690b4f38eb98a9d42d177aa3be07d58d0d4eR1217

We shouldn't be able to load any file, but we can at least load YAML files and validate them before loading them into podman desktop.

This is useful for functionality such as loading Kubernetes YAML / Compose YAML that we will be implementing in the future. 

### Describe the solution you'd like

exposeInMain should have the ability to load / write YAML file.

**Comment by jeffmaury** [comment]
Why do you need it through the API ?

**Comment by cdrage** [comment]
> Why do you need it through the API ?

You're right, I meant to just say preload / expose in main since this functionality would only be used internally and not by extensions. So used to writing API 😄 , I'll update the titles. 

Basically implement this: https://github.com/containers/podman-desktop/compare/main...cdrage:podman-desktop:paste-yaml-kubernetes-play#diff-a5b4035e012308c2f43a5a17ddc2690b4f38eb98a9d42d177aa3be07d58d0d4eR1217

**Comment by cdrage** [comment]
Already added to API (ability to create via manifest).

Will be added file-wise with #5901
