### ISSUE TITLE
Build an image page has a blank terminal

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4435]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-10-19 at 7 16 13 PM](https://github.com/containers/podman-desktop/assets/6422176/f94c1b44-4149-4896-b761-e01a2cdcf3cc)

The "build" section (which is a monaco-editor) is blank.

### Describe the solution you'd like

We should implement https://github.com/containers/podman-desktop/issues/4434 and add a "Logs will show when building..." preview message?

**Comment by mairin** [comment]
I have some thoughts on this, adding a need-design label... (I think probably the terminal shouldn't appear until the button is submitted, and probably should not be exposed except as an additional information disclosure under a progress bar type of thing? But it needs a proper design probably, so it can be consistent with other such forms... related to https://github.com/containers/podman-desktop/issues/4296 )

**Comment by cdrage** [comment]
still valid
