### ISSUE TITLE
onboarding flow with podman make impression that podman was installed while it's not

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4439]
### Bug description

When trying podman onboarding workflow and then aborting it, going to another screen and coming back it assumes podman is installed and it displays the settings but podman is not installed at all

### Operating system

macOS Sonoma 23A344

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Here is a video recording:

https://github.com/containers/podman-desktop/assets/436777/056f89a2-880d-4b0a-bc01-a0b7a001c3df

**Comment by lstocchi** [comment]
It looks like that when the podman wizard pop up the podman extension is reloaded, so it is actually deactivated (removing the onboarding from the registry) and then reactivated (re-registering the onboarding). Sothis is why it goes to the settings, it's like the onboarding workflow do not exists at that time. Is it a known behavior on Mac?

**Comment by lstocchi** [comment]
Ok, this should not be an issue in production as it is triggered here 
https://github.com/containers/podman-desktop/blob/6bb9062acaa0590b9f7c528a7f3d51f909dc3dbb/packages/main/src/plugin/extension-loader.ts#L587-L596

Not sure if I should do something

**Comment by benoitf** [comment]
@lstocchi sorry I missed the comments.

Do you if we're writing something in the extension folder when using the onboarding ?
b/c it looks like we trigger a reload when there is a change in the source code

but I guess I'm not doing any change on my own in these files, so it might be Podman Desktop

**Comment by lstocchi** [comment]
@benoitf my guess is that the podman wizard does something. This is why i asked if it was a common behavior and if you knew about it. Because i was able to replicate it on mac but on windows it doesn't happen. So the only difference is the podman wizard.
I'll investigate more if you don't have an answer

**Comment by benoitf** [comment]
yes I don't have an answer, maybe it's the wizard that creates temporary files in the folder where it is executed and it's from the assets folder of the extension

**Comment by lstocchi** [comment]
Maybe the macosinstaller class makes something, i didn't check. The only difference with Windows is this

**Comment by lstocchi** [comment]
@benoitf looking at an issue on linux then i'll get back to this

**Comment by benoitf** [comment]
this one is not a priority as it's like not a "default flow"

**Comment by benoitf** [comment]
and production mode won't hit the problem
