### ISSUE TITLE
compose and onboarding

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4442]
### Bug description

If docker-compose binary is downloaded by the extension (but I don't have it in my PATH) I see the message that docker-compose is successfully installed but not installed system-wide

![image](https://github.com/containers/podman-desktop/assets/436777/5626a0d8-471d-4429-a6da-4a4923e7bd88)

I think it's a little bit confusing as for me it's mostly 'downloaded' but not really 'installed'

### Operating system

macOS v14.0

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

remove system-wide installation of docker-compose and launch Podman Desktop and go into the compose onboarding

**Comment by mairin** [comment]
Can we not add it to the path for them?

**Comment by benoitf** [comment]
it can be added but I think the wording 'installed' is confusing as it's not really 'installed' to me, just downloaded in a folder.

`Installed` I would hope that it's more 'ready-to-be-used' so added to a PATH, env variable or shell login script tuned (add to .bash_profile, .zprofile, etc)
