### ISSUE TITLE
compose uninstall

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4443]
### Is your enhancement related to a problem? Please describe

I would expect that after compose is installed on my system, I could see the setup menu with a way to uninstall it system wide

(as the extension is capable of installing system wide I'm expecting to see the toggle after to disable the system wide installation)

### Describe the solution you'd like

like for podman onboarding where we can see the 'autostart' property, I would expect to see the toggle to uninstall it system wide

**Comment by mairin** [comment]
(Just chiming in that I agree with this design wise in case helpful to note!)
