### ISSUE TITLE
Node is incompatible with this module

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#4445]
### Bug description

lint-staged@15.0.1: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "18.0.0"

but the engines node version is 

```
"node": ">=18",
```

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

**Comment by benoitf** [comment]
hello @lstocchi what is your Node.JS version ?

**Comment by lstocchi** [comment]
18.0.0, I updated it to the one required but the engines node version in package.json needs to be updated as well
