### ISSUE TITLE
Implement start/stop for podman machine

### ISSUE THREAD

**Issue by lethargosapatheia** [containers/podman-desktop#447]
### Is your feature request related to a problem? Please describe

It would be nice to be able to control the podman machine directly from podman desktop.
If the podman machine is stopped, podman desktop does display a button in the Home section that allows you to start the machine.

### Describe the solution you'd like

Add a button that starts/shuts down podman machine.

### Describe alternatives you've considered

Stop podman machine when podman desktop exists, like docker desktop does. I don't think this alternative is necessarily nice, as I would probably like to be able to work with podman also independently.

### Additional context

I would call this low priority, but it would be nice to have for better integration between podman and podman desktop.
This has been tested on Macbook Pro M1, MacOS Monterey on podman 4.2.0 and podman desktop 0.0.6 (installed through brew).

**Comment by lethargosapatheia** [comment]
Oh, sorry, only later did I see that there's actually such an option already in preferences - Resources - Podman - Podman Machine. Never mind :)

**Comment by slemeur** [comment]
Hi @lethargosapatheia ! 
Thanks for the feedback, we have some improvements in the preferences which are getting planed (#446). I suspect it'll get easier for you to find this option.

Alternatively, there are also options in the tray menu to control your podman machines.
<img width="256" alt="Capture d’écran 2022-09-12 à 10 38 51" src="https://user-images.githubusercontent.com/1636769/189609855-c41faaea-2545-45ac-bd8e-bf37aff0e75b.png">

**Comment by benoitf** [comment]
it's there since 0.9.0 with dashboard page
