### ISSUE TITLE
Setup a new job in pr checks in crc repository

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#4474]
### Is your enhancement related to a problem? Please describe

It would be nice to create a workflow that runs specific extension tests on pr checks for that extension repository without having to migrate and duplicate test files and models from the Podman Desktop tests. It would also run separately from the other smoke tests.

### Describe the solution you'd like

Create a pipeline and workflow that runs Podman Desktop OpenShift extension tests when creating pull request for the crc repository https://github.com/crc-org/crc-extension/.

**Comment by jeffmaury** [comment]
Active
