### ISSUE TITLE
Disable Compose onboarding for now on Linux

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4475]
### Bug description

https://github.com/containers/podman-desktop/issues/4456 is currently blocking system-wide installation on Linux machines. 

we should disable onboarding temporarily
### Operating system

mac m1

### Installation Method

None

### Version

1.4.0

**Comment by benoitf** [comment]
I think we need to fix Linux workflow so probably do not disable it on Linux for now

**Comment by deboer-tim** [comment]
Based on the discussion we just had I'm assuming we close this, as the intent is to fix and release Podman + compose onboarding on all platforms.

**Comment by cdrage** [comment]
> Based on the discussion we just had I'm assuming we close this, as the intent is to fix and release Podman + compose onboarding on all platforms.

Closing as there have been two PR's pushed to fix the issue. This was an issue to keep track of temporarily disabling Linux, but after this morning discussion it's no longer needed.

https://github.com/containers/podman-desktop/pull/4502
https://github.com/containers/podman-desktop/pull/4501
