### ISSUE TITLE
Give proper spacing in header to avoid overlapping

### ISSUE THREAD

**Issue by singodiyashubham87** [containers/podman-desktop#4485]
### Is your enhancement related to a problem? Please describe

When I selected the heading both the lines overlapped each other which is a bit unprofessional looking.

### Describe the solution you'd like

I'll introduce proper spacing to prevent the overlapping of the both lines

### Describe alternatives you've considered

![image](https://github.com/containers/podman-desktop/assets/93720428/792f6605-9f43-4288-bb64-e314e9c65880)

### Additional context

Kindly assign me this issue.

**Comment by benoitf** [comment]
@singodiyashubham87 you're assigned 🎉
