### ISSUE TITLE
Provide ability to access console / tty of podman machine

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4493]
### Is your feature request related to a problem? Please describe

(This relates to #889 and would probably be handled similarly UI-wise, but, is different since it involves access to TTYs and not just the shell since the shell may not be accessible)

Sometimes if you update your podman machine or otherwise break it, you might render it in a state where it doesn't boot such that you can access a shell. You might not understand why it's broken or if it's recoverable. You could create a new podman machine but you might lose what you had set up in the old one. 

### Describe the solution you'd like

For these situations, it would be helpful to be able to access the TTYs for the VM to try to get some output and see what is going on.

**Comment by benoitf** [comment]
something need to expose the TTY to a socket

From podman desktop, connecting to a terminal relies on something providing a socket, (like `podman machine ssh`, `podman exec <container>` or `podman attach`

in the case of podman, this tty is not exposed

**Comment by afbjorklund** [comment]
For the Lima VM, it is available in `serial.sock`

```
...
[   13.285026] cloud-init[1756]: Cloud-init v. 23.3.1-0ubuntu1~22.04.1 finished at Tue, 24 Oct 2023 13:01:52 +0000. Datasource DataSourceNoCloud [seed=/dev/sr0][dsmode=net].  Up 13.28 seconds
[  OK  ] Finished Execute cloud user/final scripts.
[  OK  ] Reached target Cloud-init target.

Ubuntu 22.04.3 LTS lima-k3s ttyS0

lima-k3s login: 
```

The actual text is recorded in the `serial.log`

**Comment by afbjorklund** [comment]
@mairin : I think the workaround for Podman Machine is that you start with `debug`, and a display magically appears

Unfortunately you can't copy the text (or get rid of the window), but you can at least make some screenshots of it.

`podman-remote-static machine --log-level debug start`

![podman-machine-qemu-debug](https://github.com/containers/podman-desktop/assets/10364051/fd2c4e92-5c19-495a-9f77-ff88add203af)

**Comment by afbjorklund** [comment]
> You could create a new podman machine but you might lose what you had set up in the old one.

Yeah, that was the nice part of having the system and the containers/images on different disks (before).

**Comment by baude** [comment]
the thought of spawning a tty in powershell makes me worry
