### ISSUE TITLE
Should be able to hit Enter when creating a container

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#4514]
### Is your enhancement related to a problem? Please describe

When I'm starting a container, when the defaults are fine or a single field to be modified, would be nice to start the container by pressing the Enter key (see #3849 for inspiration)

### Describe the solution you'd like

Handle the Enter key

**Comment by benoitf** [comment]
linking to https://github.com/containers/podman-desktop/issues/2356
