### ISSUE TITLE
the Tty terminal is not handling long line properly

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#4516]
### Bug description

When entering a very long line in the Tty tab, the behavoir is strange and CR/LF seems not to be properly handled

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Create a bash session (I used python:3.11 with bash as command)
2. Enter a very long command (keeping a key pressed)

![term](https://github.com/containers/podman-desktop/assets/695993/c4a8d2b1-42b0-4ecd-b532-dbb5ac896222)

**Comment by benoitf** [comment]
I think it's because https://github.com/containers/podman-desktop/issues/3767 was not applied to tty (probably two PRs landed in // )

**Comment by dgolovin** [comment]
There should be exec.resize calls after mounting the component and after every resize of the terminal component.

**Comment by Cisnocxie** [comment]
Could I know how this issue progress? I met it in my container terminal

**Comment by dgolovin** [comment]
This issue was fixed and cannot be replicated.

![Image](https://github.com/user-attachments/assets/de4a2970-24f7-4b59-a7ab-26ebb1963976)

**Comment by Cykyrios** [comment]
Is this actually fixed? I'm using v1.18.0 (Flatpak) on Linux Manjaro KDE (Wayland), and I'm noticing that lines are shorter (they don't use the full width of the terminal window), and there is some more weirdness when editing multiline commands, see video below, where just pressing up/down repeatedly moves the cursor up several lines, deleting characters moves the entire command up and to the side, etc.

https://github.com/user-attachments/assets/8f67e99d-746b-4b6e-8771-34ebda8daa7e
