### ISSUE TITLE
Blog post on Kubernetes features

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4520]
### Is your feature request related to a problem? Please describe

We have several Kubernetes features in Podman Desktop already - support for multiple Kubernetes providers, Podify, Deploy to Kube, etc. - and several more now in progress, e.g. Kube config viewing, more info and pages on Kubernetes objects. It's time we do a roundup and talk about where we're headed.

### Describe the solution you'd like

Write a blog post about what we have today for Kubernetes, what's in the pipe, and where we see the project going.

Possibly get the blog published at another source.

**Comment by slemeur** [comment]
https://developers.redhat.com/articles/2023/11/06/working-kubernetes-podman-desktop
