### ISSUE TITLE
Design: Extension statuts component is confusing

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#4524]
### Bug description

![Capture d’écran du 2023-10-26 10-23-41](https://github.com/containers/podman-desktop/assets/9973512/ca49af1b-caef-464a-918a-631ad2a3260c)

In the first page , appears a list of Featured extensions.

The `Installed` flag for each extension can be confusing for users. They may think it is about the service itself, and not the extension.

In this example, I understood for a while that Podman, Docker, Lime and Kind were detected as running, when I knew that some of them were not installed on my machine: confusing 

Consequently, this screen does not help knowing which service is currently running. A possibility would be to have a second flag, `Active`, to indicate which service is active.

At the end, we would have two flags:
- Installed: an extension is installed
- Active: the extension has installed or detected the service, which is running correctly.

This way, I would have understood clearly that Podman was running, but Lima, Docker and Kind were not running

 

### Operating system

Linux Fedora

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Related: #4267.

**Comment by afbjorklund** [comment]
The whole top section (with the enormous icons), is the "Active". And the bottom half is the "Install"


![lima-dashboard](https://github.com/containers/podman-desktop/assets/10364051/97363bef-dbce-4ffc-a01e-9b456d5b8dee)

----

Maybe Kubernetes providers should say "Kubernetes" ?

Like the other ones are saying "Podman" or "Docker"

Podman
Podman is running
Podman

Lima
Lima is running
Kubernetes

Docker
Docker is running
Docker

**Comment by feloy** [comment]
> The whole top section (with the enormous icons), is the "Active". And the bottom half is the "Install"
> 

When you have only one service running (see my screenhost with only Podman running), it is not obvious to understand that this is a list of running services.

Having these 2 lists merged into a single one, would help understand IMO.

**Comment by deboer-tim** [comment]
I linked to one issue above, but adding some more context:

- We know the initial cards are too big, and have some actions that really should be elsewhere. Users aren't finding out about Settings > Resources and it is causing odd workflows.
- We've started putting other content on the dashboard, like initial onboarding, notifications, and tutorials, but the large cards are hampering this.
- We know the featured extensions vs the tools they enable is confusing.

There are already separate issues open to address each of these (some for design, some implementation) and work has started, but until we start to knock out a few it is even hard to find all of them, keep things organized, or know what else we'll need to do after.

**Comment by mairin** [comment]
I don't want to merge the extension status cards and the active / running resources yet. If we keep extension status cards separate from resources, I think the status is ambiguous once installed. 

To be honest, I don't think the installation of an extension is really monumental. It feels more like an enablement or support than an installation. So what I'd propose is an intermediate status, "Needs setup" => once you install an extension, if it has setup steps, it will have a "Needs setup" status until onboarding has been completed. 

See design spec below:

![image](https://github.com/containers/podman-desktop/assets/799683/a33a096a-f667-42e6-abf1-65fc00b3b079)
