### ISSUE TITLE
cant build image

### ISSUE THREAD

**Issue by gudge25** [containers/podman-desktop#4536]
### Bug description

Uploading the build context from /Users/Anton_Satskyi/Documents/GIT/pack4help-ui...Can take a while...
Error:(HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=my-custom-image: failed to decodError:Error: (HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=my-custom-image: failed tUploading the build context from /Users/Anton_Satskyi/Documents/GIT/pack4help-ui...Can take a while...
Error:(HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=my-custom-image: failed to decodError:Error: (HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=my-custom-image: failed tUploading the build context from /Users/Anton_Satskyi/Documents/GIT/pack4help-ui...Can take a while...
Error:(HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=image: failed to decode "X-RegisError:Error: (HTTP code 400) unexpected - failed to parse "X-Registry-Config" header for /build?dockerfile=Dockerfile&t=image: failed to decode "X-Registry-Config": illegal base64 data at input byte 147 

### Operating system

MAC OS Ventura Intel

### Installation Method

Brew (macOS)

### Version

1.4.0

### Steps to reproduce

PODMAN Desktop Version 4.7.1
<img width="1001" alt="image" src="https://github.com/containers/podman-desktop/assets/2346208/efcd3e39-0a5f-4b96-9b87-4ded58503fea">

**Comment by dgolovin** [comment]
I've seen that before and that happened when X-Registry-Config header was base64 only encoded, not web-safe base64 encoded. What registry are you using?

**Comment by gudge25** [comment]
> I've seen that before and that happened when X-Registry-Config header was base64 only encoded, not web-safe base64 encoded. What registry are you using?

thanks, i reset all settings  and now it works
<img width="744" alt="изображение" src="https://github.com/containers/podman-desktop/assets/2346208/38a08392-4897-4c11-8fe5-b0eafe1e5150">

**Comment by gudge25** [comment]
thanks
