### ISSUE TITLE
Show the path to the CLI binary in the CLI Tools section. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4542]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-10-27 at 11 45 07 AM](https://github.com/containers/podman-desktop/assets/6422176/dff9f6d4-f113-4f54-8a28-c13db44aa5ed)

It was suggested that we should add the location of the binary that it's checking, so the user is able to know where it's located / where PD is picking up the version.

### Describe the solution you'd like

UI presenting the path, at the moment the path name could be very long, example: `/Users/user/local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose`

We need to figure out a way to represent it minimally without taking up too much space.

**Comment by cdrage** [comment]
@mairin will need your insight on this whenever you have time

**Comment by deboer-tim** [comment]
IMHO we don't need to show this directly in the UI by default, e.g. maybe just a tooltip, a button to copy the path, or a twisty for details would do.

**Comment by cdrage** [comment]
Stale / CLI portions have been implemented. Feel free to re-open if relevant!
