### ISSUE TITLE
Trying to connect to running  podman  "podman-machine-default" using powershell comand "podman machine ssh" and get ERROR "Error: exec: "ssh": executable file not found in %PATH%"

### ISSUE THREAD

**Issue by AntonAntonich** [containers/podman-desktop#4559]
### Bug description

1. I've installed podman.
2. Podman desktop 
3. Compose. 
4. Started podman machine default
5. Then I need to remote connect to this machine and use command "podman machine ssh"
6. getting such Error:
Error: exec: "ssh": executable file not found in %PATH% 

### Operating system

Windows 10

### Installation Method

Winget (Windows)

### Version

1.5.0

### Relevant log output

time="2023-10-31T00:10:45+04:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level trace"
time="2023-10-31T00:10:45+04:00" level=debug msg="Using Podman machine with `wsl` virtualization provider"
time="2023-10-31T00:10:45+04:00" level=trace msg="Reading configuration file \"C:\\\\Users\\\\Antony_Hruschev\\\\AppData\\\\Roaming\\\\containers\\\\containers.conf\""
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
time="2023-10-31T00:10:45+04:00" level=debug msg="Executing: ssh [-i C:\\Users\\Antony_Hruschev\\.ssh\\podman-machine-default -p 61433 root@localhost -o IdentitiesOnly yes -o UserKnownHostsFile /dev/null -o StrictHostKeyChecking no]\n"
Error: exec: "ssh": executable file not found in %PATH%
time="2023-10-31T00:10:45+04:00" level=debug msg="Shutting down engines"

### Additional context

![image](https://github.com/containers/podman-desktop/assets/71168567/39089193-2712-40b1-abd1-c442dcb3204d)
![image](https://github.com/containers/podman-desktop/assets/71168567/be5747e2-99b5-4a0b-979d-b5814aefd547)
![image](https://github.com/containers/podman-desktop/assets/71168567/c485ae24-c647-4147-8860-2d50941a763e)
![image](https://github.com/containers/podman-desktop/assets/71168567/2a845f91-f193-41fc-b8e1-aebf8dfc541c)

**Comment by dgolovin** [comment]
@AntonAntonich do you have OpenSSH Client installed? ssh is not part of Podman Desktop, follow https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui and try the command again in new powershell terminal window.

**Comment by AntonAntonich** [comment]
Thanks a million !! ) 
Everything works )

**Comment by AntonAntonich** [comment]
Thanks a milloion ) 
Everything works _)
