### ISSUE TITLE
Kubernetes context UI: Add connection information, API, # of Pods, Deployments, etc.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4562]
### Is your enhancement related to a problem? Please describe

After https://github.com/containers/podman-desktop/issues/3919 we should add non-blocking retrieval information that will load when viewing the context UI. For example.. pinging and checking the connection as well as the amount of pods, deployments, etc.

### Describe the solution you'd like

Connection / cluster information being shown other than what's provided by .kube/config

**Comment by afbjorklund** [comment]
~~Not version ?~~

Never mind, the version _was_ there - it was listed in grey-on-grey under the table with other information.

**Comment by feloy** [comment]
Fixed by #5912 and #5917
