### ISSUE TITLE
`Show logs` button in `Create Resource` page shows broken log view 

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4566]
### Bug description

Easy to replicate using OpenShift Local create form

https://github.com/containers/podman-desktop/assets/620330/f5ac0601-7f3f-427d-885a-049dce8080ef

### Operating system

macOS Sonoma 14.0

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Press 'Create' button in the for for any resource that required long time to create
2. Press 'Show logs' button

**Comment by jeffmaury** [comment]
This is caused by the extension reporting download in the status area and not in the logs
