### ISSUE TITLE
Provider starts again after stop called from tray menu

### ISSUE THREAD

**Issue by evidolob** [containers/podman-desktop#4570]
### Bug description

When I start provider(CRC) from Dashboard "Initialize and Start" button PD starts my provider. But after stopping the provider with tray menu `Stop` command, PD starts provider(CRC) again. Its an infinite loop, and I can't stop provider(CRC) with PD.

Looks like the problem in: 

https://github.com/containers/podman-desktop/blob/a0c81e26ac93211ce656658793ce040bcb2bd271/packages/renderer/src/lib/dashboard/ProviderConfigured.svelte#L16-L47

`initializationContext.mode` is never reset, and it leads to auto start of provider on each component mount.

### Operating system

 macOS 13.4.1 Intel

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Make sure that you don't have crc VM(use `crc delete` to delete existing)
Run PD with crc-extension. 
Start crc with `Initialize and Start` button from PD dashboard.
Wait for crc start then stop it from tray menu.
See that crc start again after stop.

### Additional context

Demo:

https://github.com/containers/podman-desktop/assets/929743/961e4aaf-fb1d-442a-a7f2-a339acc7da33

**Comment by gbraad** [comment]
Is this an issue that happens with other providers, or just the CRC one?
/cc: @jeffmaury @evidolob @vyasgun

**Comment by jeffmaury** [comment]
Got it reproduced with Podman machine

**Comment by vyasgun** [comment]
@jeffmaury Podman machine has the option to turn off autostart. It could be because of that.

**Comment by vyasgun** [comment]
I tried this on Kind and Minkube extensions instead of Openshift Local and wasn't able to reproduce.

**Comment by vyasgun** [comment]
This looks like the root cause of https://github.com/crc-org/crc/issues/3996

I tested and it looks like this is the special case which only happens when `InitializeAndStart` mode is used.

**Comment by gbraad** [comment]
Please have a look at: https://github.com/crc-org/crc/issues/3996#issuecomment-1978166333 as this does not seem to be a CRC issue, but rather PD interfering with the lifecycle and possibly being inconsistent.
