### ISSUE TITLE
Design for Services page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4576]
### Is your enhancement related to a problem? Please describe

We need a place to view and edit Kubernetes Services.

### Describe the solution you'd like

We need a design for an initial Kubernetes Services page, to be implemented by #4368.

**Comment by ConorC117** [comment]
Link to Services list page: 
https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/18f3baa5-c6db-81d1-8002-9f756ec487eb?page-id=28aff1ad-ce4d-807a-8003-7157ad663023 

Screenshot of initial draft: 
![image](https://github.com/containers/podman-desktop/assets/99751994/0f8fe63e-5f82-4c14-999f-c25d3998374f)

**Comment by ConorC117** [comment]
Screenshot of second draft (changed global nav icon): 

![image](https://github.com/containers/podman-desktop/assets/99751994/4af4f890-2993-4c5f-85b2-77f75d525c51)

**Comment by cdrage** [comment]
> Screenshot of second draft (changed global nav icon):
> 
> ![image](https://user-images.githubusercontent.com/99751994/284385036-4af4f890-2993-4c5f-85b2-77f75d525c51.png)

This looks awesome! Here's my suggestions:
- To keep with the theme of "labels" for types, I think Type should be a label similar to environment / your other mockup with showing Progressing, etc.
- Let's remove the "selectors"? I know other graphical tools have it, but I think it clutters is up and is not very useful for "overall" graphical viewing. I believe we are going to eventually add information on if you "click" on the service it will show the YAML / details, so we can easily show it there instead what the selectors are. 
- We should add a way to show "external IP". In your example ClusterIP wont have an external IP, but any type that has a LoadBalancer will, see: https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/ IMHO clusterIP will be the most common as well as nodeport. I think we should it that if we 'hover' over the LoadBalancer label we can use Tooltip.svelte to show the IP address of the external IP.


@deboer-tim @feloy

**Comment by ConorC117** [comment]
Current screenshot of Services List : 

![image](https://github.com/containers/podman-desktop/assets/99751994/82ddb289-8f3f-4e1a-9854-6cd5fe20e454)

I included colors for the 'Type' labels based on the color blind safe palette [here](https://lospec.com/palette-list/ibm-color-blind-safe) but can of course swap them around or use different colors if preferred

**Comment by deboer-tim** [comment]
Design is looking more useful, less packed, and better visually. 👍🏼

FWIW we have a custom palette defined here (https://github.com/containers/podman-desktop/blob/main/tailwind.config.cjs), but Mairin might have it in Penpot in a more useful form for you. I have a basic working page without most columns, we can always walk through each color when that column gets closer to PR.

**Comment by deboer-tim** [comment]
This design is complete and has responded to all feedback. I'm closing this and we'll open up new issues if there is any feedback/future improvements.
