### ISSUE TITLE
Make (pod) or (compose) grouping better in Container view

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4579]
### Is your enhancement related to a problem? Please describe

Unsure where to put it yet, but the whole (compose) and (pod) in the screen doesn't look great, where should we put it instead.

![Screenshot 2023-10-31 at 9 32 01 PM](https://github.com/containers/podman-desktop/assets/6422176/0718ec75-54d9-496a-bbb7-f5d7a73ee263)

### Describe the solution you'd like

Perhaps put it in environment?

**Comment by cdrage** [comment]
@mairin any suggestions where we can move this to / ways to incorporate this?

**Comment by mairin** [comment]
> @mairin any suggestions where we can move this to / ways to incorporate this? 

Hey @cdrage 👋

Some food for thought:

- A compose icon instead of pod icon for composes?
- A little square tag thing (similar to what we do for envs on the pods screen right now) to mark compose vs pod?
- Remove the parenthesis and make the text a darker color (i think maybe lamest solution)

**Comment by deboer-tim** [comment]
@cdrage are you sure you meant to close this? I don't think it was addressed by that PR.

We might need something else too, but a compose icon would be an appropriate change to me since the pods icon is clearly used for a Pods view where we only show pods. Maybe a similar icon but with differentiation.

**Comment by cdrage** [comment]
Nope, wasn't suppose to be closed! It was going to be solved, but we need UI mockups first instead.

**Comment by benoitf** [comment]
FYI @cdrage if not closed, the issue should not have the `Done` status

done implies a close
open implies either a backlog, planned, in-progress, whatever but not `Done`

**Comment by mairin** [comment]
should this be on backlog?
