### ISSUE TITLE
Upgrade to Docusaurus v3

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4581]
### Is your enhancement related to a problem? Please describe

Docusaurus v3 came out today with some enhancements. Opening an issue because there are a lot of underlying component upgrades so they say migration may be required (i.e. more than a dependabot), and they are already saying v2 will only get security fixes until end of January.

https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3
https://docusaurus.io/blog/releases/3.0

FYI @themr0c 

### Describe the solution you'd like

Upgrade to Docusaurus v3.

### Describe alternatives you've considered

Docusaurus v2 forever!

**Comment by themr0c** [comment]
Nice to have: Use the .mdx extension to follow the recommendations in https://docusaurus.io/docs/migration/v3#using-the-mdx-extension
> Using the .mdx extension
> We recommend using the .mdx extension whenever you use JSX, import, or export (i.e. MDX features) inside a Markdown file. It is semantically more correct and improves compatibility with external tools (IDEs, formatters, linters, etc.).

**Comment by benoitf** [comment]
yes I saw that as well. It's recommended but for now it's still working.
I wanted to avoid to mix like the update to a newer version and the change of the extension files in one PR
