### ISSUE TITLE
Getting Started Guides

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4582]
### Is your feature request related to a problem? Please describe

New users get dropped onto the dashboard, often with little idea of what to do next. We should help them get started with a link to some guided tutorials or other resources they can use to get comfortable with Podman Desktop.

### Describe the solution you'd like

Use the design in issue #3722 to implement a set of getting started guides on the dashboard.

Initially these can be fixed cards advertising existing tutorials/blog in our documentation or other sites. Clicking on the card will open a link in the browser.

### Additional context

#5072

**Comment by benoitf** [comment]
I would say, for implementation it should be like for featured extensions, tutorials are described in a local .json file

**Comment by deboer-tim** [comment]
Agreed, first pass should be local json file with icon, title, description, link rendered into the cards like the linked design.

**Comment by dgolovin** [comment]
Featured extensions has featured.json with:
```
{
  "featured": [
    {
      "extensionId": "podman-desktop.podman",
      "displayName": "Podman",
      "shortDescription": "A daemonless container engine for developing, managing OCI containers and pods.",
      "categories": ["Container Engine"],
      "builtIn": true, 
      "icon": "base64encodedicon"
    },
    ....
    ]
}
```

then https://registry.podman-desktop.io/api/extensions.json descriptor with additional meta information for each extension's release.

@deboer-tim @benoitf for first pass I just put `guides.json` next to `featured.json` with structure below

```
{
  "guides": [
    {
      "url": "https://podman-desktop.io/docs/kubernetes",
      "displayName": "From Containers to Kubernetes",
      "shortDescription": "Use Podman Desktop features for easy migration from containers to Kubernetes.",
      "categories": ["Kubernetes"], 
      "icon": "base64encodedicon"
    },
    ....
    ]
}
```

WDYT?
