### ISSUE TITLE
Improve telemetry for onboarding process (send a bundled log)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4590]
### Is your enhancement related to a problem? Please describe

Reference: https://github.com/containers/podman-desktop/pull/4572#pullrequestreview-1706816125

We should send a bundled telemetry event rather than separate ones (one for each registerCommand), so we can see a summary of the entire process rather than each individual event.

### Describe the solution you'd like

Send a single onboarding event on failure / success, as per Tim's example:

```
.logUsage('compose.onboarding.checkComposeInstalled', {
  version:
  version-default: (true/false if they modified the default value)
  download:
  download-error: (error object, or -success true/false if we can't get that)
  system-wide: (only added if they got to this part)
  system-wide-error: (only added if they got to this part. error object, or true/false if we can't get that)
```

**Comment by cdrage** [comment]
FYI we should also wrap the install / download / system wide install commands in a try / catch and make sure we `console.log` the error / the command still errors back as well as report to telemetry the error.

**Comment by feloy** [comment]
@benoitf Before to start the implementation, I would like to be sure I've found the appropriate way to implement it:

- add a new onboarding step in the `extensions/compose/package.json` file
- collect information from the different commands into some `onboardingContext` variables
- send the telemetry data from the added step, with the data collected in the context.

Does it seem ok?

**Comment by benoitf** [comment]
From what I see, the idea was to get the flow the user pickup, so probably it's part of the onboarding handling, not specific to compose.

Like, what were the steps the user took when onboarding has been displayed

for example: "onboarding.compose", user exited directly the onboarding or he clicked on next, did it called the custom version or took the default did we call installComposeSystemWide

did we display the onboarding or it's already completed ("enablement": "!compose.isComposeInstalledSystemWide",) enablement value

so I would hook it up more in the onboarding sequence/handler rather than adding a new step in

**Comment by feloy** [comment]
@deboer-tim WDYT? If we send the telemetry from the onboarding handling and not from the onboarding specific implementations, I don't think we will be able to send specific details only known by commands executed in specific implementations (versions, ...), but we will only have information provided to the handler (the content of the onboarding definition in the package.json typically).

Another solution would be to pass an Object to the commands of the implementation, so the commands can fill this object with the values they want to send to the telemetry, and the onboarding handler would be responsible for sending the data in this object at the end of the onboarding. But I'm not sure how to pass this object to the commands. Via the context? Via the return value of commands?

**Comment by feloy** [comment]
@benoitf @deboer-tim In the PR #4733, the data is collected from commands executed during onboarding (through the response of commands).

Do you think it is a clean way to collect data, or would you prefer to use a different channel?

**Comment by feloy** [comment]
@deboer-tim @benoitf 
Without involving the extension, the renderer part can send the list of steps done. The telemetry sent when the onboarding goes to the end would be (for compose):

```
"onboarding.setupDone", {
  "extensions": "podman-desktop.compose",
  "steps": [
    "checkComposeDownloaded",
    "startComposeDownload",
    "downloadComposeView",
    "composeDownloaded",
    "installComposeSystemWide",
    "composeInstalledSystemWide"
  ]
}
```

For a canceled onboarding session, it would be, if the user cancels at the `composeDownloaded` step:
```
"onboarding.cancelSetup", {
  "extensions": "podman-desktop.compose",
  "steps": [
    "checkComposeDownloaded",
    "startComposeDownload",
    "downloadComposeView",
    "composeDownloaded"
  ]
}
```

Is this information enough? Or does telemetry need to get more information?

Feel free to experiment with PR #4736 (it should also work for other onboardings, not only compose)

**Comment by benoitf** [comment]
@feloy I think the event needs to be the same to be able to correlate something

so mostly get the steps done

also probably report a generic 'skipped': false/true and completed: false/true

```
"onboarding.podman-desktop.compose" {
 skipped: false,
 completed: true,
  "steps": [
    "checkComposeDownloaded",
    "startComposeDownload",
    "downloadComposeView",
    "composeDownloaded",
    "installComposeSystemWide",
    "composeInstalledSystemWide"
  ]
}

```

so it means I can know how many people were able to complete the workflow, how many skipped the workflow for compose, the number of average steps that people do, how many people did download a custom version of compose, etc

I think that we need to think in the reverse side, like what do we want to track and then we can send the aggregate object 

so to me, skipped, completed are missing

we could imagine that we have a score for skipping like do we skipped at the beginning or just before the end (10%, 50%, etc)


And in case of error, the error should be reported (maybe for each step) and probably the duration of each step and the full flow
```
"startComposeDownload": {
duration: 500,
error: undefined | {error object},
etc.
```

**Comment by deboer-tim** [comment]
+1 to comments above. If we want to know whether (e.g.) compose installation is failing more on a particular platform we can look directly at telemetry for that command.

What we are missing and won't come from the individual commands is what set of steps the user was presented with, which they skipped, whether each step worked, and if they cancelled at any point. We want to answer questions like:
- Is the overall flow working, are we helping users get everything initially installed? Or do users prefer to defer and do it step by step later?
- Are there points where it is failing, users are giving up, or getting confused?

**Comment by jeffmaury** [comment]
May we could also record the duration for the whole workflow and for each step as well

**Comment by feloy** [comment]
Trying to send errors and `completed` status to the telemetry, I have found these 2 blocking problems:

- Blocked by https://github.com/containers/podman-desktop/issues/4766
- Blocked by https://github.com/containers/podman-desktop/issues/4785
