### ISSUE TITLE
Cannot reenable podman extension, getting Extension error: command 'podman.onboarding.installWSL' already exists

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4593]
### Bug description

I was facing a strange issue, after some time of playing around podman machines, pulling images, starting a containers, etc., I have seen a missing rootful, usermode, etc buttons in the create a new machine form. @lstocchi Also reported something similar.

I tried to disable and re-enable podman extension and got this:
```
Extension error: command 'podman.onboarding.installWSL' already exists
```

### Operating system

Windows 10 Professional

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Have podman desktop started (update: Probably we need to go through the onboarding, so podman installed is also requirement)
2. go to Settings -> Extensions -> Podman
3. Disable extension
4. Assert: all seems fine
5. Enable extension
6. Assert: all is back running/available
Actual result: It gets stuck in enabling. Console shows an error. To get full error - force reload, aka. CTRL + R

### Relevant log output

```shell
Dev console log:

main ↪️ Activating extension podman-desktop.podman failed error:Error: command 'podman.onboarding.installWSL' already exists

Error stack trace:
Extension error: command 'podman.onboarding.installWSL' already exists
Stack trace
Error: command 'podman.onboarding.installWSL' already exists at xd.registerCommand (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:14:42009) at Object.registerCommand (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:92:37250) at WSL2Check.init (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.js:1023:42) at activate (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.js:5310:31) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Sre.activateExtension (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:92:44728) at async Sre.loadExtension (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:92:36990) at async Sre.startExtension (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:92:46120) at async C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:382:16958 at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88640)
```

### Additional context

Workaround - restart podman desktop (fully)

**Comment by rostalan** [comment]
Same issue here, I'll just add some screensshots:

![image](https://github.com/containers/podman-desktop/assets/75624842/e5042150-11b4-4902-94c1-8e1c1757ab2e)

The enable button in the overview section 'Extensions' seems to be missing.

![image](https://github.com/containers/podman-desktop/assets/75624842/744c1c7d-47e5-4544-84a8-bc7db6a3e855)

After clicking the enable button in detail of Podman extension, it gets stuck enabling, as @odockal  said.

**Comment by benoitf** [comment]
@odockal I'm not reproducing this issue

**Comment by odockal** [comment]
@benoitf Just right now I was able to reproduce.

**Comment by odockal** [comment]
@benoitf Windows is expected platform.

**Comment by odockal** [comment]
@benoitf I believe that we also need to install podman since `podman.onboarding.installWSL` needs to be registered.

**Comment by odockal** [comment]
Moreover, the disable-enable action introduces duplicated Podman resource objects in Resources.

**Comment by benoitf** [comment]
ok got it, specific to windows
should be easy to fix
