### ISSUE TITLE
CLI Settings: Add "Active" / "Inactive" Status

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4595]
### Is your enhancement related to a problem? Please describe

Active / Inactive status should be added to CLI Settings portion if an extension is actually being used or not.

### Describe the solution you'd like

Active / Inactive status as per mockups:
![279599336-f2dce6e2-7975-499c-b874-04cb58cb8967](https://github.com/containers/podman-desktop/assets/6422176/43a3ffbb-39c6-45a6-bddb-8cf9221e8b72)

**Comment by dgolovin** [comment]
Should it be 'INSTALLED" rather than 'ACTIVE`?
