### ISSUE TITLE
Onboarding Dashboard notification about Podman state is not updated once Podman is installed and Podman Machine created

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4598]
### Bug description

I am still seeing this notification, after podman and podman machine were installed/created/started.
![podman-dashboard-notification-not-updated](https://github.com/containers/podman-desktop/assets/19164299/5352e3a8-a12f-4141-bb23-88da94e96c9e)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Podman desktop Dashboard
2. Setup Podman -> onboarding podman
3. Finish the workflow with podman machine created
4. Assert: Podman is installed, machine is up and running
5. Check the notification on dashboard
Actual result: Notification still offers to install podman, or says that something is not configured

**Comment by lstocchi** [comment]
I wonder if this behavior is incorrect. A notification is something that is pushed in a queue and remains there until the user removes it. 
I think it's the same on vscode. Let's say you don't have something installed, install it, the notification is still in the bottom right until you clear the queue.

**Comment by rostalan** [comment]
This might not be related, but when I delete the podman machine without first closing the notification, the notification pops up twice.
I would not consider this to be the correct behaviour:
![image](https://github.com/containers/podman-desktop/assets/75624842/fe76fa86-f184-4397-986f-a70fd788e99d)
