### ISSUE TITLE
Add FetchIt integration

### ISSUE THREAD

**Issue by cooktheryan** [containers/podman-desktop#460]
### Is your enhancement related to a problem? Please describe

Nope this would just extend features

### Describe the solution you'd like

I think this could potentially start out as an extension but GitHub.com/containers/FetchIt could allow for the lifecycling of containers running on a host and this project could allow for a visualization 

### Describe alternatives you've considered

N/A

### Additional context

We would be happy to work with you on the integration if this seems at all interesting to the maintainers

**Comment by benoitf** [comment]
Hello @cooktheryan ,

I think it could be an extension/plug-in contributing features to Podman Desktop.
We support a fine-grained extension API and introduce some high-level API (like with Docker Desktop Extensions)

We've already extensions for Podman/Docker/Lima/CRC so we could have a FetchIt integration.
We need to see how to integrate it properly and should be the extensions points.

**Comment by benoitf** [comment]
closing as won't fix until someone provides a 3rd party extension
