### ISSUE TITLE
Optional options hidden in podman machine creation page on Windows and Mac after force reload

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#4605]
### Bug description

Opening this issue to keep track of a possible bug which does not happen frequently.
When testing the new 1.5.2, I tried to create a new podman machine and all options (rootful, usernetworking) were hidden.
After a restart it started working fine.
The same happen to @odockal once.

I was not able to replicate it again. If someone has more info please post it here. Thanks!!

### Operating system

Windows 10/ 11 and Mac OS 14

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install Podman (either using onboarding, or dashboard buttons)
2. Go To Settings -> Resources
3. Verify: Open Create new ... (podman machine) form/page got all options available
4. Go back to Resources and call Force Reload (CTRL + R on windows)
5. Verify the Create new page again
6. Assert: All Buttons are present
Actual result: These optional button are not visible.

**Comment by odockal** [comment]
Updating steps to reproduce.

**Comment by odockal** [comment]
Adding Mac OS platform where it can be reproduced as well.

**Comment by feloy** [comment]
I can reproduce it (consistently) on mac. I'll have a look
