### ISSUE TITLE
Search & Start OCI image

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4606]
### Epic domain

As a user, I want to start from a different workflow, search for an image (like with most stars, suggesting some images from keyword, etc) and start a container from there

No need to provide an exact name for an image in the 'images' list with 'pull image' screen, etc

Depends on:

- [x] https://github.com/containers/podman-desktop/issues/759
- [x] https://github.com/containers/podman-desktop/issues/4216
- [x] https://github.com/containers/podman-desktop/issues/971

**Comment by slemeur** [comment]
Maybe, we should start with this: https://github.com/containers/podman-desktop/issues/4324?
