### ISSUE TITLE
Trying to start OpenShift Local throws RequestError

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#4611]
### Bug description

When trying to start/initialize OpenShift Local, it shows request error. Afterwards it shows the extension as stopped and throws the error everytime when trying to start again.

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install Podman Desktop (1.5.2).
2. Install OpenShift with OpenShift Local preset.
3. Try to start and initialize from Dashboard or start from Settings.

### Additional context

![crc sock error when initializing openshift](https://github.com/containers/podman-desktop/assets/57829934/46808d0f-9871-40a2-aeba-7d03134e7b2f)
![crc initialize bug](https://github.com/containers/podman-desktop/assets/57829934/b2d2b15d-7bba-4a09-ae5e-90243b50616a)

**Comment by odockal** [comment]
@gbraad

**Comment by jeffmaury** [comment]
Move to extension repo please

**Comment by jeffmaury** [comment]
Tried on MacOS and Podman Desktop 1.7.1,OpenShift Local extension 1.3.0, OpenShift Local 2.32.0 and I cannot reproduce.

**Comment by nichjones1** [comment]
@xbabalov can you try this again as we are unable to reproduce it.

**Comment by odockal** [comment]
@xbabalov Can you please take a look during testing of 1.9.0?

**Comment by xbabalov** [comment]
I tried it with one of the lastest pre-releases and cannot reproduce it again, so I think we can close the issue.
