### ISSUE TITLE
Not clear what are the next steps after Openshift local - CRC installation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4614]
### Bug description

I have installed OpenShift local extension and installed CRC within Podman Desktop. The steps provided a dialog, that I need to restart after installation of crc, which is expected, although, before there was an option to initialize and start (I would expect a check for a restart). now there is nothing:

![crc-install-no-initialization](https://github.com/containers/podman-desktop/assets/19164299/78d971d8-e6e1-477c-8c73-81a16e99aefc)

### Operating system

Windows 10, macOS Sonoma

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by dgolovin** [comment]
I see the same behavior on macOS Sonoma.

**Comment by dgolovin** [comment]
This is crc-extension issue (see https://github.com/crc-org/crc-extension/issues/229)

**Comment by dgolovin** [comment]
crc-extension issue was resolved.
