### ISSUE TITLE
Kube Config UI: View current context

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4618]
### Is your enhancement related to a problem? Please describe

We are imminently adding a list of Kube contexts to the Settings via #4560, but currently you can't see which context is the current one, and have no ability to change it.

### Describe the solution you'd like

The new tiles should show what the current context is, and there should be an action for selecting a different one. (yes, I could use the status bar context switcher too, but it's more natural to click on the one I can see in the list)

Switching the context via the editor or status bar should stay in sync, i.e. change in it one place and the other should update.

**Comment by cdrage** [comment]
Split this up into two issues as I'll push this in two PRs:
- https://github.com/containers/podman-desktop/issues/4618 view which one is current context
- https://github.com/containers/podman-desktop/issues/4920 add the button

Reason being is that we need a quick UI mockup on where we should put the button as we've changed it to use a "trash can" for deleting, but unsure for selection (should we just select any area?).
