### ISSUE TITLE
Warning: Not exporting file io.podman_desktop.PodmanDesktop.appdata.xml of unsupported type. Installation complete.

### ISSUE THREAD

**Issue by rolfedh** [containers/podman-desktop#462]
### Bug description

When I use the instructions here https://podman-desktop.io/downloads to install Podman Desktop on RHEL CSB, I get `Warning: Not exporting file io.podman_desktop.PodmanDesktop.appdata.xml of unsupported type. Installation complete.`

For example:

```
$ flatpak install --user flathub io.podman_desktop.PodmanDesktop
Looking for matches…

io.podman_desktop.PodmanDesktop permissions:
    ipc                   network              x11      dri
    file access [1]       dbus access [2]

    [1] home, xdg-run/podman
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.kde.StatusNotifierWatcher


        ID                                 Branch    Op    Remote     Download
 1. [✓] io.podman_desktop.PodmanDesktop    stable    i     flathub    94.7 MB / 100.4 MB

Warning: Not exporting file io.podman_desktop.PodmanDesktop.appdata.xml of unsupported type.
Installation complete.
```

### Operating system

RHEL CSB

### Version

0.0.7

### Steps to reproduce

$ flatpak install --user flathub io.podman_desktop.PodmanDesktop

### Additional context

```
$ which flatpak
/usr/bin/flatpak
$ flatpak --version
Flatpak 1.8.7
```

**Comment by benoitf** [comment]
Hello @rolfedh could it be related to https://github.com/flatpak/flatpak/issues/4800

**Comment by rolfedh** [comment]
> could it be related to [flatpak/flatpak#4800](https://github.com/flatpak/flatpak/issues/4800)

That issue seems specific to flatpacks that were **built using flatpak version 1.13.1**. Devs, which version of flatpak did you use to build Podman Desktop 0.0.7?

**Comment by benoitf** [comment]
@rolfedh it's flathub builders that is building the flatpak repository so I suppose they're using the latest version

Could be like 1.14.0
https://github.com/flathub/org.flatpak.Builder/pull/98

**Comment by rolfedh** [comment]
This issue may be what's causing issue #466 as well.

**Comment by benoitf** [comment]
I think we can close this issue as based on https://github.com/flatpak/flatpak/issues/4800 it's a warning that can be safely ignored.
