### ISSUE TITLE
Hide CLI about details once installed

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4642]
### Is your enhancement related to a problem? Please describe

On the Settings > Resources page you get a little blurb about what Podman or Kind or OpenShift Local is, but once you start to use them it goes away, making the cards smaller and focused on what I'm doing with each tool.

On the Settings > CLI page, these blurbs never go away. This keeps the cards big (which means I won't be able to see as many on the page), and the things I do care about (it's installed, version, is there an update) are dwarfed by the text.

cc @mairin

### Describe the solution you'd like

Remove the about text once the CLI is installed. If we still think the user may need to see it (I don't) then it should be on-demand, e.g. via tooltip or section.

**Comment by mairin** [comment]
Agreed... i think having the details behind an expander is a good approach. Do you need a mockup?

**Comment by deboer-tim** [comment]
I don't know who would work on this, so a quick mockup would be helpful. Not urgent though.
