### ISSUE TITLE
Reduce visual impact of unused providers and tools

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4644]
### Is your enhancement related to a problem? Please describe

This applies to Settings > Resources, but I think it's going to apply to CLI Tools soon too: when I have a provider extension installed but I'm not using it yet or at the moment, there is a big card in Settings > Resources. These cards are large, causing the page to need scrolling, and they are brighter than the cards of providers you're using. This is a visual distraction and makes the tool feel bloated.

My core thought here: Installing an extension for something but not using it yet should have no impact on my existing use.

### Describe the solution you'd like

Some thoughts on options:
- reduce the overall card size
- change text from white to grey, grey out icon a little (or add translucent grey overlay for all of them)
- cut off text after 2 lines and use hover or Read More to see the rest
- remove padding or margin from text, we don't need both
- change the layout of the cards to reduce size (they don't need to match 'used' providers)

### Describe alternatives you've considered

There are some drastic actions like putting all unused tools within a section that's closed by default.

**Comment by dgolovin** [comment]
Wouldn't that make it harder to find things related to recently installed extension? I would find it confusing if I install something and then see it for some reason looks differently from other items on the list without apparent reason.

Should we rather show them as they are right now and let user to collapse unused items and save the collapsed items between sessions? We are not going to have hundreds of items for providers or CLI Tools any time soon.
When something is installed and new resource/tool added to the page it would appear expanded and stay expanded until user decide it should be collapsed to reduce clutter.

Another option to hide them completely form the page, but then there should be indication how many unused items are hidden and there should be a way to make them visible again.

**Comment by deboer-tim** [comment]
Yeah, agreed about not wanted to hide recently installed. And manually collapsing these would be an option too, I just don't like that these are large and visually distracting indefinitely.
