### ISSUE TITLE
Podman Desktop doesn't retain autostart setting

### ISSUE THREAD

**Issue by josephgruber** [containers/podman-desktop#4647]
### Bug description

I have installed Podman on my MacOS M1 Macbook using `brew install podman` and then installed Podman Desktop using `brew install podman-desktop`. I then ran through the initial setup and created the machine/VM. When running through the initial setup, I ensured the autostart option was selected. However, the machine/VM does not autostart.

I've gone into Preferences and enabled Autostart in the Autostart Podman engine section. It shows as enabled. But if I quit Podman Desktop or reboot my computer, the setting value is not retained. And the machine/VM does not autostart.

I am currently running v1.5.2.

### Operating system

macOS Sonoma 14.0 (Arm)

### Installation Method

Brew (macOS)

### Version

1.5.0

**Comment by josephgruber** [comment]
FYI: I've went back to podman-desktop v1.5.0 and also still have this problem

**Comment by josephgruber** [comment]
v1.4.0 works as expected. Looks like a regression between 1.4 and 1.5

**Comment by rommon** [comment]
I have the same issue under windows since podman desktop 1.5.2. 

It is quite annoying as I am relying on podman desktops usermode to give my other wsl distros access to the vpn tunnel

**Comment by AuxiliumEngineer** [comment]
I am currently running version 1.5.3 and the issue remains. But it does not only effect the auto-start of the Podman machine. **No setting persists between application restart**. I tried to reinstall and installed manually and over brew to rule out a misconfiguration on my part. Also running on m1 but macOS 14.1.1

**Comment by josephgruber** [comment]
@auroraunit217 based on the pull request, looks like it's tagged for the 1.6.0 release. Not sure when that will be though.

**Comment by benoitf** [comment]
@josephgruber should come this upcoming week

**Comment by AuxiliumEngineer** [comment]
> @auroraunit217 based on the pull request, looks like it's tagged for the 1.6.0 release. Not sure when that will be though.

Thanks for the hint. Forgot to check that out. My fault.

**Comment by benoitf** [comment]
FYI you can also download 'nigthlies' that already have the fix
https://github.com/containers/podman-desktop/releases
