### ISSUE TITLE
Podman stuck at initializing (MacOS Sonomo 14.1 - Intel Chip)

### ISSUE THREAD

**Issue by sofpodev** [containers/podman-desktop#4649]
### Bug description

Despite the following recommendations from several similar issues on this repo (which were actually closed without clear resolution) this issue is still happening. And worse, sometimes Podman Desktop freezes completely during the initialization phase. (Yes I had to shut down my Mac)

No logs, nothing. Oh you wondered what I did? I just downloaded x64 dmg from and installed it. That's it. 
Okay, to be fair I also tried these:

- Performed NVRAM and SMC resets on my Mac, which did not alleviate the problem.
- Manually cleared Podman-related files from both ~/Library/Caches and ~/Library/Preferences.
- Alternated between installing the Intel (x64) and Universal binaries of Podman Desktop numerous times.

This is not an isolated incident, happened to many people and still happening. I do understand that diagnozing and resolving it might be complex but I urge you to prioritize this. I am just asking for a stable and reliable installation and initialization.

Thank you!

### Operating system

macOS 14.1 (Intel)

### Installation Method

Installer from website/GitHub releases

### Version

1.5.0

### Steps to reproduce

Download the installer from website.
Run/Open the Podman Desktop

### Relevant log output

```shell
It does freeze, so no log nothing.
```

### Additional context

It is extremely frustrating

**Comment by benoitf** [comment]
hello, could you try by renaming `$HOME/.kube` folder before launching Podman Desktop or renaming temporary `$HOME/.kube/config` to `$HOME/.kube/config-tmp`

**Comment by slemeur** [comment]
probably related to https://github.com/containers/podman/issues/20428

**Comment by spk57** [comment]
I had a similar problem on Windows 11.  I deleted .local\share\containers\podman-desktop  to resolve.
