### ISSUE TITLE
PD needs a desktop icon

### ISSUE THREAD

**Issue by rolfedh** [containers/podman-desktop#466]
### Bug description

![Screenshot from 2022-09-09 06-10-14](https://user-images.githubusercontent.com/350907/189327136-dabf3fb3-e235-49ca-a5fc-7c3ff205885a.png)

### Operating system

RHEL 8 CSB

### Version

0.0.7

### Steps to reproduce

While running Podman Desktop, press ctrl+tab.

**Comment by benoitf** [comment]
I think it may be similar to https://github.com/containers/podman-desktop/issues/462, the flatpak icon is there on all recent flatpak versions but on very old flatpak versions, metadata were different and it might explain why it's not shown.

**Comment by rolfedh** [comment]
Interestingly, the icon is visible when I start PD as shown here. (But not later, when it's running and I press Alt+Tab.)
![Screenshot from 2022-09-09 22-21-13](https://user-images.githubusercontent.com/350907/189465255-033e527c-b032-4a6f-b9dc-7207b09e32a4.png)

**Comment by benoitf** [comment]
I tried on RHEL 8.6

https://user-images.githubusercontent.com/436777/191590884-70e1a5f1-f3e9-4219-b9d9-fdd39c373ce5.mov

I can see the icon
<img width="831" alt="Screenshot 2022-09-21 at 15 15 38" src="https://user-images.githubusercontent.com/436777/191591093-16eddb72-afd6-4672-8bb7-afd6b55a1159.png">
