### ISSUE TITLE
Implement E2E  test case using Playwright to verify creation of the podman machine with user mode enabled

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4666]
Implement a test case to cover creation of a rootful/rootless Podman Machine with a user mode networking using standard (Create New workflow) in Settings -> Resources -> Create new....

Windows only.

**Comment by danivilla9** [comment]
This issue is blocked by issue #4665. @xbabalov is working on some files that are used by this test case too and we don't want to step over each other's work.
