### ISSUE TITLE
Invisible Black system tray icon on black GNOME GUI

### ISSUE THREAD

**Issue by hbelmiro** [containers/podman-desktop#467]
### Is your enhancement related to a problem? Please describe

As the icon and the GNOME bar are both black, the icon stays invisible.

![Screenshot from 2022-09-09 08-44-11](https://user-images.githubusercontent.com/11776454/189342661-56216572-b2c3-43f0-8731-1ff0a5354413.png)

![Screenshot from 2022-09-09 08-44-45](https://user-images.githubusercontent.com/11776454/189342720-b8add83f-34e1-46cd-a4be-7d2778d7d9e3.png)

### Describe the solution you'd like

Changing the icon to its color version would solve the problem. Even being dark, it has a clear board, so it would look good on both dark and clear backgrounds.

### Describe alternatives you've considered

Change the icon to black or white (?) depending on the bar color.

**Comment by benoitf** [comment]
Interesting, we're using templateImage so it can adapt the color based on the background Color for that but it seems only macOS supports it
https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image

**Comment by benoitf** [comment]
also, what are you using for tray icons in gnome ? https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ ? as it's no longer there AFAIK

**Comment by hbelmiro** [comment]
> also, what are you using for tray icons in gnome ? https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ ? as it's no longer there AFAIK

I don't remember installing anything specific for that. I thought showing tray icons was the default behavior 🤔 
I'm using Fedora 36. These are my installed extensions:

![Screenshot from 2022-09-09 09-34-09](https://user-images.githubusercontent.com/11776454/189350888-4647c06b-5c07-47dc-ba90-b9a50f0c00c4.png)

**Comment by benoitf** [comment]
@hbelmiro ok it seems it's provided by https://extensions.gnome.org/extension/615/appindicator-support/ in your case

**Comment by hbelmiro** [comment]
@benoitf Indeed. When I disable that one, the icons disappear.

**Comment by benoitf** [comment]
Thanks, I asked only to be able to reproduce it correctly.
I guess for Linux, we can't rely on ThemeImage then

Are you using a Dark theme as well ?

**Comment by hbelmiro** [comment]
Yes. I'm using the native Fedora 36 dark theme.
