### ISSUE TITLE
podman desktop fails to start with error 125 (v4.7.2 / osx 13.5 / Intel )

### ISSUE THREAD

**Issue by SeanFelipe** [containers/podman-desktop#4673]
### Bug description

Error: Command execution failed with exit code 125

Seeing this error 100% of the time when I start podman and click 'Run Podman'.

dmg installation.

### Operating system

osx 13.5 / intel chip

### Installation Method

Installer from website/GitHub releases

### Version

1.5.0

### Steps to reproduce

install 4.7.2
- observe "podman 4.7.2 is stopped"
click 'Run Podman'

Error: Command execution failed with exit code 125

**Comment by deboer-tim** [comment]
Could you try running `podman machine list` and `podman machine start` from a command prompt? If there is a `qemu` process kill it and try again.

I used to hit a similar issue on M1 Mac - it has been fixed but was due to qemu getting out of sync with the state of the machine.

**Comment by SeanFelipe** [comment]
```
NAME                     VM TYPE     CREATED      LAST UP     CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        2 weeks ago  4 days ago  1           2GiB        100GiB

Error: cannot start VM "podman-machine-default": another instance of "/opt/podman/qemu/bin/qemu-system-x86_64" is already running with process ID 84143: please stop and restart the VM
```

looks like it's a problem. Will kill and restart.

**Comment by SeanFelipe** [comment]
killed the process, restarted podman desktop, same issue / error 125. Restarted my macbook, started podman, same error.

Clicking "Run Podman" the first time started about 20 seconds of a spinner followed by the error. Subsequent clicks immediately the error flashes back.

<img width="897" alt="Screenshot 2023-11-07 at 10 25 30 AM" src="https://github.com/containers/podman-desktop/assets/5632981/37395684-398f-4432-9cfb-9e302a46ce81">

**Comment by benoitf** [comment]
@SeanFelipe go into Settings menu (the cog) then in Resources then in Podman and click on the details [↗️] and logs
and click on the start of the podman machine

you should get the error log ?

**Comment by SeanFelipe** [comment]
```
Starting machine "podman-machine-default"

Waiting for VM ...

Error: machine did not transition into running state

Starting machine "podman-machine-default"25

Error: cannot start VM "podman-machine-default": another instance of "/opt/podman/qemu/bin/qemu-system-x86_64" is already running with process ID 1636: please stop and restart the VM
```

I'm poking through settings, created a new container. Logs access is helpful, thanks !

**Comment by SeanFelipe** [comment]
Success I think !

<img width="912" alt="Screenshot 2023-11-07 at 10 48 18 AM" src="https://github.com/containers/podman-desktop/assets/5632981/319bc957-2abd-48d4-94f4-7564b499b1c7">
