### ISSUE TITLE
Podman update to 4.2.1 does not seem to work

### ISSUE THREAD

**Issue by pdaverh** [containers/podman-desktop#468]
### Bug description

I clicked on update from 4.1.1 to 4.2.1, went through the steps, and it showed successful update. But it does not look like it worked.

<img width="295" alt="Screen Shot 2022-09-09 at 8 20 57 AM" src="https://user-images.githubusercontent.com/48592473/189372387-130cbe44-94d1-4fca-a31f-21334d3e606e.png">
<img width="1032" alt="Screen Shot 2022-09-09 at 8 20 44 AM" src="https://user-images.githubusercontent.com/48592473/189372392-ca7f3a19-f58e-4f78-b3a1-58007f20b07e.png">
<img width="1029" alt="Screen Shot 2022-09-09 at 8 20 32 AM" src="https://user-images.githubusercontent.com/48592473/189372394-c9b6da83-0f5f-4526-ae19-30ad9a8e82ca.png">

### Operating system

macOS 12.5.1

### Version

0.0.7

**Comment by benoitf** [comment]
Hello @pdaverh could you check your PATH

```
$ echo $PATH
```

and: 

```
$ type podman
```

I suspect you may have a brew version of Podman installed in `/opt/` or `/usr/local`

If it's the case:

two choices:
- remove the brew version (`brew uninstall podman`)
- remove the version provided by the installer and update podman with brew
 `sudo rm -rf /opt/podman` and then `brew upgrade podman`



We added something to detect if user used brew but it has been merged post v0.0.7 version
https://github.com/containers/podman-desktop/pull/444

**Comment by slemeur** [comment]
I've tested the version providing the check from #444. It properly detected Podman was installed with Brew. 

Could we automate the update process of podman in this situation?

**Comment by benoitf** [comment]
so this issue has been fixed in 0.8.0 by https://github.com/containers/podman-desktop/pull/444
