### ISSUE TITLE
System limit for number of file watchers reached on Fedora 38 

### ISSUE THREAD

**Issue by veillard** [containers/podman-desktop#4686]
### Bug description

seems that my 1.5.2 installed on Fedora 38 is hitting issues, I'm seeing this in the log:
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/veillard/.kube/config' at FSWatcher.<anonymous> (node:internal/fs/watchers:247:19) at Object.watch (node:fs:2418:34) at createFsWatchInstance (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15) at setFsWatchListener (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15) at NodeFsHandler._watchWithNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14) at NodeFsHandler._handleFile (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23) at NodeFsHandler._addToNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21) at async /app/main/resources/app.asar/node_modules/chokidar/index.js:451:21 at async Promise.all (index 0) (Use `podman-desktop --trace-warnings ...` to show where the warning was created)
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
main ↪️ System ready. Loading extensions...
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/veillard/.local/share/containers/podman-desktop/plugins-scanning' at FSWatcher.<anonymous> (node:internal/fs/watchers:247:19) at Module.watch (node:fs:2418:34) at kre.setupScanningDirectory (/app/main/resources/app.asar/packages/main/dist/index.cjs:92:31462) at kre.start (/app/main/resources/app.asar/packages/main/dist/index.cjs:92:31950) at _xe.initExtensions (/app/main/resources/app.asar/packages/main/dist/index.cjs:384:22356) at async /app/main/resources/app.asar/packages/main/dist/index.cjs:411:3297
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
main ↪️ PluginSystem: received dom-ready event from the UI
main ↪️ Delayed startup, flushing 8 events
main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 328.99686336517334ms
main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 77.04804992675781ms
main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 77.99254131317139ms

### Operating system

Linux Fedora 38 x86_64

### Installation Method

Flathub (Linux)

### Version

1.5.0

### Steps to reproduce

Just launched it from the Application->Developement

### Relevant log output

```shell
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/veillard/.kube/config' at FSWatcher.<anonymous> (node:internal/fs/watchers:247:19) at Object.watch (node:fs:2418:34) at createFsWatchInstance (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15) at setFsWatchListener (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15) at NodeFsHandler._watchWithNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14) at NodeFsHandler._handleFile (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23) at NodeFsHandler._addToNodeFs (/app/main/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21) at async /app/main/resources/app.asar/node_modules/chokidar/index.js:451:21 at async Promise.all (index 0) (Use `podman-desktop --trace-warnings ...` to show where the warning was created)
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
main ↪️ System ready. Loading extensions...
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/veillard/.local/share/containers/podman-desktop/plugins-scanning' at FSWatcher.<anonymous> (node:internal/fs/watchers:247:19) at Module.watch (node:fs:2418:34) at kre.setupScanningDirectory (/app/main/resources/app.asar/packages/main/dist/index.cjs:92:31462) at kre.start (/app/main/resources/app.asar/packages/main/dist/index.cjs:92:31950) at _xe.initExtensions (/app/main/resources/app.asar/packages/main/dist/index.cjs:384:22356) at async /app/main/resources/app.asar/packages/main/dist/index.cjs:411:3297
main ↪️ (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by feloy** [comment]
I have made 2 changes in my system to try and limit this problem (but cannot completely resolve it for now, I still need to find the approriate numbers):

- increase the max number of watched files:
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

- increase the number of opened files:  https://access.redhat.com/solutions/60746

**Comment by odockal** [comment]
A duplicate of #2054.
