### ISSUE TITLE
CLI Update mechanism: Implement back end support

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4689]
### Is your enhancement related to a problem? Please describe

Part of: https://github.com/containers/podman-desktop/issues/3708

Implement the backend / internal support for downloading the binary based on: https://github.com/containers/podman-desktop/pull/4092

### Describe the solution you'd like

Integration of https://github.com/containers/podman-desktop/pull/4092

We have to also consider that the "cli version checking" is integrated at the extension level / checked per extension in their own mechanism, so the backed will have to be provided by the API.

**Comment by jeffmaury** [comment]
Rescoping after discussion with @benoitf 

This should be limited to having the extension a way to notify of an update and perform that update if the user ask for it through the CLI settings page. This should be handled the same way of provider notifies of an update and performs that update.

**Comment by cdrage** [comment]
So I do not forget: We should also extensively use octokit support similar to what we already have implemented, anything else (gitlab, https / internal corporate environments) would be at a later implementation.

**Comment by cdrage** [comment]
Brain dump with regards to implementation:

- [ ] Be able to reactively get the local version / have Podman Desktop API call it
- [ ] Update mechanism that checks GitHub for the latest versions and compares it too the local CLI version
- [ ] Be able to download GitHub assets through API
- [ ] Be able to install assets through API (figure out way to select an asset as each project is different for naming ex. binary-macos vs binary-darwin).
- [ ] Use apiSender to notify an update is available?
- [ ] Add UI button

**Comment by lstocchi** [comment]
Closing as https://github.com/containers/podman-desktop/pull/5064 and https://github.com/containers/podman-desktop/pull/5111 have been merged
