### ISSUE TITLE
Documentation: Emulating Docker CLI with Podman not available for Windows

### ISSUE THREAD

**Issue by fipro78** [containers/podman-desktop#4696]
### Is your enhancement related to a problem? Please describe

I noticed that the [Emulating Docker CLI with Podman](https://podman-desktop.io/docs/migrating-from-docker/emulating-docker-cli-with-podman) description is only showing the script for a Unix system (e.g. Git Bash on Windows). 

The [Podman for Windows - Using API Forwarding](https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md#using-api-forwarding) docs talk about a docker.exe, which I do not see anywhere and really wonder where it should come from, since I don't have Docker Desktop installed anymore.

For a Windows only user without Docker Desktop that wants to emulate the Docker CLI with Podman, the docs are not helpful.

### Describe the solution you'd like

I played around a bit and created the following Windows batch file, that can be used similar to the docker script in the docs:

```
@ECHO OFF
if not exist C:\Users\%USERNAME%\AppData\Roaming\containers\nodocker (
  echo "Emulate Docker CLI using podman. Create C:\Users\%USERNAME%\AppData\Roaming\containers\nodocker to quiet msg."
)
podman %*
```

Maybe you want to add this as Windows alternative in your docs to help users that want to work on Windows.

**Comment by orgcontrib** [comment]
I bumped into the same recently but I had a quick workaround for it: `winget install --id Docker.DockerCLI`. Nowadays, most CLI tools are available via either `winget`, `scoop` or both. That's how I prefer to manage the software on my Windows host(s) anyway. Later on I was confused by [this](https://podman-desktop.io/docs/kind/installing), so I did `scoop install kind`. On Mac, `brew` is king.

**Comment by fipro78** [comment]
@orgcontrib 
What you say is that you are able to install the Docker CLI without Docker Desktop on Windows. At least this is what I would assume from the command you posted. The issue here is about the documentation and how you can add a batch on Windows that forwards docker command calls to podman. There is actually no Docker CLI involved anymore.

Anyhow an interesting information. So thanks for sharing.

**Comment by fipro78** [comment]
Now I get the point of your comment. Installing Docker CLI via winget only installs the CLI but does not start a deamon etc. But using the API forwaring of Podman, VS Code devcontainers etc. are working. The missing point in in the Podman documentation is actually how to install the Docker CLI so you can make use of the API forwarding.
