### ISSUE TITLE
Add option to disable running in system tray

### ISSUE THREAD

**Issue by jgierer12** [containers/podman-desktop#471]
### Is your enhancement related to a problem? Please describe

App keeps running minimized and in system tray after closing it. This might not be desired by some users, personally I would much prefer it if clicking the close button actually quit the application. Additionally, some Linux desktop environments (eg. GNOME) ship without tray icon support by default. This means some users might not even be aware that the application keeps running after "closing" it, which is poor UX.

### Describe the solution you'd like

Add an option that disables the tray icon and quits the application when the window is closed.

**Comment by dylanmtaylor** [comment]
Working on implementing this in #671, could someone assign this issue to me?

**Comment by benoitf** [comment]
@dylanmtaylor done
