### ISSUE TITLE
Connection to /events drops sometimes

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4712]
### Bug description

Podman Desktop use events to refresh containers/images

But sometimes the `/events` connection is dropping

### Operating system

macOS

### Installation Method

None

### Version

1.5.0

### Steps to reproduce

long live running session / hivernate/suspend/restore computer

### Additional context

If I do a curl on the endpoint, I receive a failure, so Podman Desktop should be able to handle the error/reconnect/notify that there is a problem

```
 curl --unix-socket /var/run/docker.sock "http://v1.47.0/events"

...
curl: (18) transfer closed with outstanding read data remaining
```

**Comment by jeffmaury** [comment]
Got VM unresponsive today but VM console is accessible and I can see a lot of messages related to virtio

<img width="637" alt="Capture d’écran 2023-11-09 à 14 51 54" src="https://github.com/containers/podman-desktop/assets/695993/b0da71ec-3a56-47ad-ba53-e6c415be0527">

**Comment by benoitf** [comment]
I've opened https://github.com/containers/podman/issues/20639

for your message/problem, if you do `ifconfig enp0s1 down` and then `ifconfig enp0s1 up` it should restore the connection but yes it's not a good way :-)

**Comment by jeffmaury** [comment]
> I've opened [containers/podman#20639](https://github.com/containers/podman/issues/20639)
> 
> for your message/problem, if you do `ifconfig enp0s1 down` and then `ifconfig enp0s1 up` it should restore the connection but yes it's not a good way :-)

Can't tell because I restarted everything and I noticed I was using an old version of podman/qemu so I upgraded to see if I still have the issue. Will let you know

**Comment by jeffmaury** [comment]
> > I've opened [containers/podman#20639](https://github.com/containers/podman/issues/20639)
> > for your message/problem, if you do `ifconfig enp0s1 down` and then `ifconfig enp0s1 up` it should restore the connection but yes it's not a good way :-)
> 
> Can't tell because I restarted everything and I noticed I was using an old version of podman/qemu so I upgraded to see if I still have the issue. Will let you know

Reproduced it with latest qemu and podman
