### ISSUE TITLE
Initializing podman toggle button loses state while on tab toggle

### ISSUE THREAD

**Issue by pacostas** [containers/podman-desktop#472]
### Bug description

Open Podman Desktop -> Home screen ->  click on initialize podman. While Podman Desktop is initializing podman click on containers tab or any other tab and then come back to home screen on podman initialization. The state of toggle button is grey instead of purple.

### Operating system

Windows 10

### Version

0.0.7

### Steps to reproduce

Open Podman Desktop -> Home screen -> Toggle button Initialize podman -> While podman initialization -> click on any other tab on the left sidebar e.x. containers -> come back to home screen -> The state of the toggle button to initialize podman should be purple instead of grey

**Comment by benoitf** [comment]
related to https://github.com/containers/podman-desktop/issues/125 
(stateless for now)

**Comment by deboer-tim** [comment]
This was fixed via issue #2403.
