### ISSUE TITLE
View menu missing

### ISSUE THREAD

**Issue by harleydk** [containers/podman-desktop#4726]
### Bug description

I'm unable to activate the 'View' menu, as indicated here: https://github.com/containers/podman-desktop/discussions/1427#discussioncomment-4957714

I was specifically looking for the developer console, to help identify an issue with seemingly non-existing images and containers. 

This with version 1.5.3.

Many thanks in advance.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Steps to reproduce

- Install Podman Desktop 1.5.3 on Windows 11.
- Note the missing 'View' menu. 

### Additional context

![image](https://github.com/containers/podman-desktop/assets/1468788/ff788562-81a0-42a3-a58d-64c1c76641dc)

vs. 

![image](https://github.com/containers/podman-desktop/assets/1468788/dffd4f7c-47b6-4c9a-9644-bb7d0375511c)

**Comment by benoitf** [comment]
hello @harleydk the menu bar has been removed to avoid the double title bar.

that said, if you're interested in the logs, you can click on the bottom bulb 💡icon in the status bar, then you can see the logs

if you want the developer console, you can use shortcuts

<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd> shortcut (for macOS it's <kbd>Alt</kbd> + <kbd>Cmd</kbd> + <kbd>i</kbd> )

**Comment by harleydk** [comment]
Hi @benoitf , clears up the issue, too, so thanks for the reference to the logs.

Pressing alt + ctrl (not alt) + i brought up the developer console, also helpful. 

Awesome response-time, thanks a lot.

**Comment by benoitf** [comment]
thanks @harleydk let us know if you're facing other issues
