### ISSUE TITLE
Podman Desktop does not show any containers or pods in podman-machine-default

### ISSUE THREAD

**Issue by krachynski** [containers/podman-desktop#4737]
### Bug description

When I start my laptop every day, I launch Windows Terminal with PowerShell core and start the default podman machine with `podman machine start`. This results in the following message:
```
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
```
Once that's done, I start the kind-cluster-control-plane container.

If I then go to Podman Desktop, the Dashboard tells me that `Podman is running\nVersion 4.7.2` and `Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.` The Containers list is empty despite `podman container list` showing my kind-cluster-control-plane. The Pods, Images, and Volumes lists are also empty.

In Settings, I can see the podman machine, but the summary only shows name and endpoint when it used to include CPUs and RAM as well.

The Kind resourse only suggests creating a new one. I could have sworn that it used to also list the existing kind clusters

### Operating system

Windows 11

### Installation Method

Winget (Windows)

### Version

1.5.0

### Steps to reproduce

Honestly, you _might_ need to have a Windows 11 system with all the software our IT department includes for their needs.

**Comment by krachynski** [comment]
technically, my version is 1.5.3

**Comment by benoitf** [comment]
@krachynski do you have docker desktop running as well ?

**Comment by jeffmaury** [comment]
Can you run `podman system connection ls`

**Comment by dougbreaux** [comment]
I've had the same behavior, where hitting CTRL-R in the images and containers view did then show the existing objects. It did not occur just now, though. I don't run PD that often, so it's _possible_ it's only occurred on the first start after a version update.

**Comment by versionbayjc** [comment]
I had the same behavior today. I installed Podman Desktop v.1.5.3 through winget on Win11, this was a first install on a relatively new Workstation PC. This PC does not have very specific configurations, so I would assume any clean install of v.1.5.3 with the same podman (4.7.2) to show the same.

I followed the initial setup steps. Everything seemed working, but Volumes and Images were not listed in the App, but were correctly shown through podman CLI. After restarting Podman Desktop it worked ok for me.

```pwsh
PS C:\Users\%USERNAME%> podman system connection ls
Name                         URI                                                          Identity
                     Default
podman-machine-default       ssh://user@127.0.0.1:50968/run/user/1000/podman/podman.sock  C:\Users\%USERNAME%\.ssh\podman-machine-default  false
podman-machine-default-root  ssh://root@127.0.0.1:50968/run/podman/podman.sock            C:\Users\%USERNAME%\.ssh\podman-machine-default  true
```
