### ISSUE TITLE
push image to cluster should not use kebab menu icon

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4763]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/436777/33d69c46-b5da-4833-bf35-b7d13204d8b9)

this icon is being used for pushing an image but it feels that I could get a drop down menu as it's the icon for a kebab menu so it is confusing

https://github.com/containers/podman-desktop/assets/436777/d2ae73fc-2ac5-4fa1-ac73-20ac82526c05

### Operating system

macOS

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

use kind and OpenShift local extension

**Comment by salaheddine-zemmouri** [comment]
Hello , I am interested in contributing to this project and i would love to fix this issue. Is it still open ?

**Comment by jeffmaury** [comment]
> Hello , I am interested in contributing to this project and i would love to fix this issue. Is it still open ?

It was scheduled to be closed based on priorities but feel free to contribute, you're more than welcomed

**Comment by myfear** [comment]
This seems to be fixed now @jeffmaury .

**Comment by deboer-tim** [comment]
Yes, this was fixed: #5236 (and extensions can customize the icon now too).
