### ISSUE TITLE
Proxy environment code prepends "http://"

### ISSUE THREAD

**Issue by n1hility** [containers/podman-desktop#4765]
### Bug description

Ad noticed by @win5do in https://github.com/containers/podman-desktop/issues/4549#issuecomment-1806010216

```
podman machine ssh
env | grep -i proxy

ouput:
http_proxy=http://host.containers.internal:8080
https_proxy=http://host.containers.internal:8080
HTTP_PROXY=http://http://host.containers.internal:8080
HTTPS_PROXY=http://http://host.containers.internal:8080

```

The proxy env code is prepending "http://" here:
https://github.com/containers/podman-desktop/blob/2d2e5e8102d7141a2fc95ce85320478d0e3b0cb6/packages/main/src/plugin/util/exec.ts#L59

It should not be hardcoded to "http" since proxy servers may use other schemes (e.g. https). It might be ok to assume and append it if not already present, but this should be done earlier so it is consistent with the other code path which sets containers.conf (source of the lower case values). Note It might also be worth dropping the container.conf write path if this is now being set at the env point. 

### Operating system

Windows

### Installation Method

None

### Version

1.5.0

**Comment by jeffmaury** [comment]
Current version of Podman Desktop uses host:port for proxy location thus the http prefix that is appended. #4356 is changing to either host:port or full URL (thus supporting https)

**Comment by Dr-Zany** [comment]
Hey, when is this going to be fixed because it makes it almost impossible to work behind a proxy or is there a workaround I missed?

**Comment by mcarbonneaux** [comment]
i have the same problem!


in podman machine : 
```
# find /etc -type f | xargs grep https_proxy
/etc/profile.d/default-env.sh:export https_proxy="http://http://localhost:8080"
/etc/systemd/system.conf.d/default-env.conf:DefaultEnvironment=http_proxy="http://http://localhost:8080" https_proxy="http://http://localhost:8080" no_proxy="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost" HTTP_PROXY="http://http://localhost:8080" HTTPS_PROXY="http://http://localhost:8080" NO_PROXY="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost"
/etc/environment.d/default-env.conf:https_proxy="http://http://localhost:8080"
```


```
# env | grep -i proxy
no_proxy=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
https_proxy=http://http://localhost:8080
NO_PROXY=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
HTTPS_PROXY=http://http://localhost:8080
HTTP_PROXY=http://http://localhost:8080
http_proxy=http://http://localhost:8080
```

and when try to configure only the `host:port` without `<scheme>://` i got:
![image](https://github.com/containers/podman-desktop/assets/8479023/a54ec562-961c-4740-863f-6404ac49f965)

**Comment by jonathanfoster** [comment]
@Dr-Zany I was able to work around the issue by configuring proxy environment variables and starting Podman machine using the CLI. The issue only occurs when you start the machine from Podman Desktop.

```bash
export http_proxy=http://localhost:8080
export https_proxy=https://localhost:8080
export no_proxy=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
podman machine stop
podman machine start
```

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/5694
