### ISSUE TITLE
Close To Tray

### ISSUE THREAD

**Issue by trymeouteh** [containers/podman-desktop#477]
### Is your enhancement related to a problem? Please describe

Most applications that provide a tray icon behave like this...

Minimise = Minimise app
Close= Close app to tray

To close/quit the application, you will right click on the tray icon and click Quit

### Describe the solution you'd like

When you close Podman Desktop, it will not minimise the app but close the app to the tray icon.

**Comment by benoitf** [comment]
hello @trymeouteh it should behave like this already

What is your Operating system/ installation archive used ?

**Comment by trymeouteh** [comment]
Linux Mint 21 with podman

**Comment by benoitf** [comment]
thanks @trymeouteh for reporting the issue

maybe issue is https://github.com/containers/podman-desktop/issues/467 where icon is black on a dark notification bar so you don't see the tray application

**Comment by benoitf** [comment]
it has been implemented since 0.9.0
