### ISSUE TITLE
Load & Save Image

### ISSUE THREAD

**Issue by trymeouteh** [containers/podman-desktop#478]
### Is your feature request related to a problem? Please describe

The ability to load an image tar file into podman and be able to export an image from Podman Desktop and save it as a image tar file.

### Describe the solution you'd like

A Load Image button to load images into Podman Desktop next to the pull image button under the Images tab.

A Save Image button to save images from Podman Desktop next to the pull image button under the Images tab.

**Comment by elervik** [comment]
Ill stab at this.

**Comment by benoitf** [comment]
@elervik I've assigned the issue

**Comment by elervik** [comment]
I have a working load & save for podman, is there demand to extend supporting export and import also?

Initially I wanted to give the ability to select engine (ie docker), but the dockerode API load and save endpoints are misbehaving, load is even 404.. Maybe its just me? :) Is multi-engine a must have for this initial feature extension, or should I commit what is and improve later?

**Comment by benoitf** [comment]
Hello, multi-engine is a pre-requisite but it doesn't prevent to create the PR

**Comment by elervik** [comment]
I dont have time to contribute to this issue at the moment, I removed my assignment in case someone else looks at it before I can get down to business again.

**Comment by benoitf** [comment]
there should have a way to do that also from a 3rd party extension
