### ISSUE TITLE
Running/Stopped containers tabs shown as selected at the same time

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4791]
### Bug description

If I type 'is:running is:stopped' in containers list filter then both tabs 'Running containers' and 'Stopped containers' get selected. 

![image](https://github.com/containers/podman-desktop/assets/620330/73368c25-fa03-42d7-84c1-38c3b3a326dc)

Here we have two conflicting filter representations. Tabs only one can be selected and filter expression that can contain filters representing every tab at the same time. 

### Operating system

macOS Sonoma 14.1

### Installation Method

None

### Version

next (development version)

### Additional context

* #4708

**Comment by deboer-tim** [comment]
FWIW, this is the same behaviour as GitHub PR/issue filter (so at least we're in good company ;-) ). It's a bit odd, but hopefully this is a fairly rare error case and I don't know how else we'd do a similar UI (e.g. we could use checkboxes instead, but then to switch from running to stopped you'd have to click twice).

**Comment by feloy** [comment]
My 2¢ idea is we could remove the previous incompatible search tags. For example, if we have:

```
oneterm is:running is:stopped
```

this would be changed automatically to: 
```
oneterm is:stopped
```

by removing the `is:running` tag. 

This would give the user a way to overwrite previous tags without having to manually delete them.

**Comment by dgolovin** [comment]
On github IMO `Opened` and `Closed` look and behave more like toggle buttons.

![image](https://github.com/containers/podman-desktop/assets/620330/d2e142e9-ee0e-411a-9752-8e7a179be73b)

We have Tabs. Normally only one Tab can be selected to make it contents visible, we have two tabs in selected state which is odd. 

@feloy removing is:running when there is is:stopped would make it worse IMO. What if I want to filter out containers in staring state?

IMO we can close this issue, because most of the time tabs are going to be used because those tow is: filters are the only supported.

**Comment by dgolovin** [comment]
@feloy It just one line of code per each function, I would say we should wait until we have more complicated search and then we have to move it somewhere.

**Comment by nichjones1** [comment]
@dgolovin do you agree this issue can be closed based on @feloy's feedback?

**Comment by dgolovin** [comment]
Closing.
