### ISSUE TITLE
If starting container from an image takes time podman desktop window shows empty page

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4792]
### Bug description

I started podman from podman-desktop and pulled node image. When I try to run container using the node image all I see is empty screen below. It seems podman is slow for no apparent reason, and creating image takes time and command is waiting for container to start in UI thread.

![image](https://github.com/containers/podman-desktop/assets/620330/72544da1-6452-4637-bdaa-4b90bee40dd8)

after 15 minutes in terminal I get:

```
% podman ps
CONTAINER ID  IMAGE                          COMMAND     CREATED         STATUS         PORTS       NAMES
c802a809799d  docker.io/library/node:latest  node        15 minutes ago  Up 15 minutes              zealous_heyrovsky
```

but still nothing in podman-desktop

![image](https://github.com/containers/podman-desktop/assets/620330/1398ac72-ee65-4316-a225-c8dafb4de690)

### Operating system

macOS Sonoma 14.1

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Sounds like more info/dup of #3975?

**Comment by dgolovin** [comment]
Closing as duplicate.
