### ISSUE TITLE
Typing in images search filter gives unpredictable results

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4793]
### Bug description

I have three images on Images page

![image](https://github.com/containers/podman-desktop/assets/620330/c00a1cdb-1d84-4bbb-8e96-cbe303e05888)

when I type 'n' in search field I see images below, but httpd one does not have 'n' in it.

![image](https://github.com/containers/podman-desktop/assets/620330/6db1fc83-eb6f-4fef-8a01-67389b5c5e26)

when I type 'no' I don't see `<none>`

![image](https://github.com/containers/podman-desktop/assets/620330/1f173983-27b2-485e-90c2-0af1beb943e1)

when I type 'aa' I see all of them, but only one has 'aa' in checksum

![image](https://github.com/containers/podman-desktop/assets/620330/ad6a9905-d382-489f-a875-133b9bef19e9)

when I type 'aab' I see only one

![image](https://github.com/containers/podman-desktop/assets/620330/dca02bb7-defc-4f35-adcf-b1901af431c5)

it is confusing what info from image is used when search is evalueated.

### Operating system

macOS Sonoma 14.1

### Installation Method

None

### Version

1.5.0

**Comment by benoitf** [comment]
AFAIK it searches in all attributes of an image not only its id or its name

**Comment by dgolovin** [comment]
it does. it is just not obvious from the page, why some images show up, because there is no way to see what property was matched.

**Comment by benoitf** [comment]
I think it's the pattern used by Docker Desktop as well

**Comment by dgolovin** [comment]
The fact Docker Desktop using it, does not make it less confusing :) Full text search probably deserves its own page
Should it be closed or we eval it later?
