### ISSUE TITLE
The "Docker compatibility guide" link goes to the wrong place

### ISSUE THREAD

**Issue by davidlanouette** [containers/podman-desktop#4808]
### Bug description

On the main dashboard is a "Docker compatibility guide" link. It currently goes to https://podman-desktop.io/docs/troubleshooting/troubleshooting-podman#warning-about-docker-compatibility-mode.  However, that page doesn't discuss docker at all.

I think the correct link should be either 

https://podman-desktop.io/docs/troubleshooting/troubleshooting-podman#warning-about-docker-compatibility-mode

Or

https://podman-desktop.io/blog/5-things-to-know-for-a-docker-user#docker-compatibility-mode

However, neither look like they are a perfect fit.

### Operating system

macOS Ventura

### Installation Method

Brew (macOS)

### Version

1.5.0

### Steps to reproduce

Open the dashbaord.

In the "podman" section, click the "Docker compatibility guide"

A browser will open to the page listed above.

### Relevant log output

```shell
N/A
```

### Additional context

NOTE: I'm actually running podman-desktop v1.5.3.  The dropdown seems to stop at 1.5.0

**Comment by afbjorklund** [comment]
The title is a bit misleading, the page is only about the symlink and not about any actual compatibility comparison.

* https://github.com/containers/podman-desktop/issues/1709

Maybe you were more looking for something like:

https://podman-desktop.io/docs/migrating-from-docker

The link got broken here:

* #3194

**Comment by afbjorklund** [comment]
You get the same warning if you are actually running Docker, but then you can't "fix" it (since it uses docker.sock)

⚠ Docker Socket Compatibility
Docker socket is not reachable.
Docker specific tools may not work.
Docker is running

**Comment by davidlanouette** [comment]
@afbjorklund Sorry for the (very) delayed reply to your response.  

The "bug" is that when I'm in Podman Desktop, and I click on the "Docker compatibility guide" link, I would expect to be taken to a page that talks about compatibility with Docker.  However, it takes me to a page that talks about general troubleshooting.  There's nothing about Docker on that page at all.  So, that link in Podman Desktop should be updated to point to some other page - one that actually talks about Docker compatibility. IMO.

&nbsp;

Based on the URL, I _think_ there used to be something on the page about compatibility with Docker, but it's not there anymore.

This isn't about the actual content in the documentation.  Just about where that link points to.

&nbsp;

I hope that helps clear things up some.

**Comment by afbjorklund** [comment]
I don't think there is any such documentation available, and it would probably be on [podman.io/docs](https://podman.io/docs) (not the web app?)

The _only_ thing the symlink does, is so that you can run `docker` (or `docker-compose`) without setting up DOCKER_HOST...

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/issues/8337
