### ISSUE TITLE
Podman Desktop cannot see podman machine

### ISSUE THREAD

**Issue by pacostas** [containers/podman-desktop#481]
### Bug description

Podman Desktop cannot see podman machine on windows. 

### Operating system

windows 11 home

### Version

0.0.7

### Steps to reproduce 

[Updated description] Correct way to reproduce the error on this comment:
* https://github.com/containers/podman-desktop/issues/481#issuecomment-1252089933

[below steps wont reproduce the issue, follow above comment]
1. Install wsl from powershell `wsl --install`
2. On Powershell with admin rights do:
   * podman machine init
   * podman machine set --rootful
   * podman machine start
3. Start Podman Desktop
4. No containers/images/machines are available

**Comment by benoitf** [comment]
Could you provide the log that you can grab using View/developper tools/ console ?

**Comment by pacostas** [comment]
Unfortunately when I toggle developer tools I get below image.
![Screenshot (1)](https://user-images.githubusercontent.com/10673302/191070152-3127a0d3-bff1-40f7-9ada-00e81b95a13d.png)

is there any way to totally remove all Podman Desktop files?

**Comment by pacostas** [comment]
@benoitf [Update on Re-producing the error]

* podman machine init
* podman machine set --rootful
* podman machine start

Open podman desktop and everything works fine. (Below screenshot with the console)
![Screenshot (2)](https://user-images.githubusercontent.com/10673302/191221094-2d79933c-381f-47b8-9ecf-ee6d2babe2b3.png)

On powershell do:
* podman machine stop
* podman machine rm 

* Open podman desktop  (Below screenshot with the console)
![Screenshot (5)](https://user-images.githubusercontent.com/10673302/191221451-80885af9-e880-4c98-9a35-7f0e8302a73d.png)

* Click on podman run,  (Below screenshot with the console)
![Screenshot (6)](https://user-images.githubusercontent.com/10673302/191221743-1c034704-7c10-4705-a71c-43581a7b9af9.png)

Open powershell and set below command
* podman start
* Open podman desktop no machine/images/ containers are available,  (Below screenshot with the console)
![Screenshot (7)](https://user-images.githubusercontent.com/10673302/191221990-4aaa211f-e94f-4966-9048-9f42440583d6.png)

**Comment by benoitf** [comment]
we're no longer seeing this issue, closing as we fixed it
