### ISSUE TITLE
Pod does not exist in the client software

### ISSUE THREAD

**Issue by tonycody** [containers/podman-desktop#482]
### Bug description

![image](https://user-images.githubusercontent.com/6773121/191174663-28aca5c5-f8ed-48cc-b099-97efdab82ff0.png)

### Operating system

Windows 11 22H2 25201.1000

### Version

0.0.7

**Comment by benoitf** [comment]
hello @tonycody did you start or stop the podman machine after starting Podman Desktop ?
It may have been fixed by https://github.com/containers/podman-desktop/pull/475

If you could try a pre-release from https://github.com/containers/podman-desktop/releases

**Comment by tonycody** [comment]
> hello @tonycody did you start or stop the podman machine after starting Podman Desktop ? It may have been fixed by #475
> 
> If you could try a pre-release from https://github.com/containers/podman-desktop/releases

`pre-release` The Pods is now showing.
![image](https://user-images.githubusercontent.com/6773121/191397808-a855ec95-618b-4aef-b9fc-93a50ae42e13.png)

![image](https://user-images.githubusercontent.com/6773121/191397759-6090e4d8-8786-468b-92e6-d09310397b5a.png)
Can you add a version of Podman Desktop display?

**Comment by benoitf** [comment]
thanks @tonycody for the report
