### ISSUE TITLE
Error: error freeing lock for container

### ISSUE THREAD

**Issue by tonycody** [containers/podman-desktop#483]
### Bug description

![image](https://user-images.githubusercontent.com/6773121/191178490-29d2a99d-ae29-4b49-8fea-5aa16ae02e50.png)

### Operating system

Windows 11 22H2 25201.1000

### Version

0.0.7

**Comment by benoitf** [comment]
this error is due to a bug in Podman 4.2
https://github.com/containers/podman/issues/15526

it'll be fixed in Podman 4.3

**Comment by jedahan** [comment]
even after upgrading to podman 4.3, I had to `podman machine rm podman-machine-default` and start from scratch.

**Comment by benoitf** [comment]
please note that podman machine might still be in 4.2, as the machine is fetching Fedora CoreOS with an older version of Podman.
https://getfedora.org/en/coreos?stream=stable

Once Fedora CoreOS gets a new podman, new `podman machine init` call will grab this version and remote will be 4.3 at this time


if you do 'podman version' you should see that the client is using `4.3.0` while the remote is using `4.2.1`

**Comment by jedahan** [comment]
Ahh, thanks for taking the time to explain, this makes sense.

**Comment by benoitf** [comment]
fixed in 0.10
