### ISSUE TITLE
Trivy Extension Non-responsive

### ISSUE THREAD

**Issue by eric-peterson-usps** [containers/podman-desktop#484]
### Bug description

When trying to scan a container image using the Trivy extension Podman desktop displays a spinning circle and does not respond.

### Operating system

macOS Monterey v 12.5.1

### Version

0.0.7

### Steps to reproduce

1) Navigate to Contributions tab and select installed Trivy extension
2) Select docker.io.library/alpine:latest image to scan
3) Set toggle to "Only show vulnerabilities that have fixes"
3) Click scan button

### Relevant log output

```shell
podman --version
podman version 4.2.1

podman images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
quay.io/podman/hello      latest      fd6151b2e608  4 days ago   82.1 kB
docker.io/library/httpd   latest      f2789344c573  7 days ago   150 MB
docker.io/library/alpine  latest      9c6f07244728  5 weeks ago  5.83 MB

podman ps
CONTAINER ID  IMAGE                            COMMAND           CREATED     STATUS           PORTS                 NAMES
0f1469db7a92  docker.io/library/httpd:latest   httpd-foreground  4 days ago  Up 17 hours ago  0.0.0.0:8080->80/tcp  funny_cori
f7fd6de8d8e8  docker.io/library/alpine:latest  /bin/sh           4 days ago  Up 17 hours ago                        vigorous_montalcini
```

**Comment by benoitf** [comment]
thanks @eric-peterson-usps for reporting the issue, should be fixed by https://github.com/containers/podman-desktop/pull/485
