### ISSUE TITLE
Unable to read the version of the WSLcorrectly

### ISSUE THREAD

**Issue by YuHanHaHa** [containers/podman-desktop#4863]
### Is your enhancement related to a problem? Please describe

When executing entire setup, the following error message is prompted
![image](https://github.com/containers/podman-desktop/assets/50622709/d835cf67-fac5-4c79-b51c-e4b88ff00ad2)

But my local WSL version is greater than required.
![image](https://github.com/containers/podman-desktop/assets/50622709/fe847c19-0ce3-4573-b30b-55a83a50c6c1)

Can't recognize the WSL version of the machine, or is my WSL version incorrect?

### Describe the solution you'd like

Sorry, I couldn't find the feedback email, so I went to Github to create an issue. If need more detailed machine version information, I can provide it here

**Comment by benoitf** [comment]
Thanks maybe it's because we expect 'version' text and it is not provided

You should be able to manually fetch https://github.com/containers/podman/releases/download/v4.7.2/podman-4.7.2-setup.exe and run this exe manually as a workaround

**Comment by dgolovin** [comment]
On eng windows it prints out: 
```
>wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715
```

It looks like we should detect 'WSL  `*.:`  because `version` can be in any language.

**Comment by YuHanHaHa** [comment]
Sorry, there is a new situation. 
Downloaded image and containers cannot be displayed in CMD and podman desktop dashbord, but can be displayed in machine. 
Is it because I skipped the pre-check step and installed podman manually? in addition, because of GFW (Great Firewall), I also manually downloaded and imported the image of machine from Github. I don't know if that's the reason. 
But it does not affect the use, but podman desktop is almost not available, can only be used to start machine.😭
![image](https://github.com/containers/podman-desktop/assets/50622709/2469f08a-3a3d-4499-b8c8-7b074352f6a2)
![image](https://github.com/containers/podman-desktop/assets/50622709/1ae5be07-13ff-46d7-b1f0-ff70ce87b99f)

**Comment by YuHanHaHa** [comment]
sorry，Click the wrong place

**Comment by benoitf** [comment]
@YuHanHaHa could you perform the command in a CLI:

```bash
podman system connection list
```

and

```bash
podman machine inspect
```

**Comment by benoitf** [comment]
and if you go to the bottom light bulb in the status bar, do you see some errors in the log part, or if you try the 'ping command' or the 'check containers' ?

**Comment by YuHanHaHa** [comment]
@benoitf 
i perform the command 
<img width="716" alt="image" src="https://github.com/containers/podman-desktop/assets/50622709/0178535b-04cf-4a66-8aec-ec38b9832438">

I found some error messages . Is it because the wrong version of the system architecture is installed?
main ↪️ Unable to fetch the available extensions: Timeout awaiting 'connect' for 500ms
main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
main ↪️ [podman] Can't get machine podman-machine-default resource usage error Error: no engine matching this container
main ↪️ [kind] Error: Failed to execute command: spawn kind-windows-amd64 ENOENT

**Comment by YuHanHaHa** [comment]
the 'ping command' and the 'check containers'  is valid 
![image](https://github.com/containers/podman-desktop/assets/50622709/0ef3b198-9a0a-443d-886b-66599db747a2)

**Comment by YuHanHaHa** [comment]
These are the logs section after clicking the copy button

error : main ↪️ Kubeconfig path C:\Users\Yuhan\.kube\config provided does not exist. Skipping.
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 10 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\Yuhan\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 80 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 22 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) ended in 20 milliseconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 121 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 85 milliseconds
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'connect' for 500ms
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
warn : main ↪️ [podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
error : main ↪️ [kind] Error: Failed to execute command: spawn kind-windows-amd64 ENOENT
log : main ↪️ Activating extension (podman-desktop.kind) ended in 1514 milliseconds

**Comment by benoitf** [comment]
ok thanks @YuHanHaHa 

so it looks like podman machine is configured as being a rootful machine.

could you try to connect using `podman machine ssh` instead of `wsl` command to connect to the podman machine ?

When I see your podman commands (like podman ps in the shell) it seems you're connected as a user in the machine and not as root user


so either:

1. connect to wsl using `podman machine ssh` and try some `podman run httpd` image etc
2. try on your computer (not inside the wsl machine) in CMD or powershell: `podman run httpd` and `podman ps`

do you see now images being the same ?


now, if you would like to be inside your wsl machine as podman user, probably you need to change the machine to be rootless instead of rootful : `podman machine stop`, `podman machine set --rootful=false` , `podman machine start`

**Comment by YuHanHaHa** [comment]
The reason is that the default user identity used is set wrongly, I tried to switch the rootless mode with command : "podman machine set --rootful=false". Then after executing the command "podman info" many Permission denied error messages appeared. Then I recreated the podman machine with the following configuration. now it works fine, thank you very much!
<img width="545" alt="image" src="https://github.com/containers/podman-desktop/assets/50622709/1f74ec83-c7c0-4ebd-bcf0-4abe355ce64a">

**Comment by lstocchi** [comment]
Going back to the original problem, Desktop already handles different languages, it relies on the `:` position to gather the version, so if it's written in italian, french, english, whatever, it works.
Here, the issue is a bit more subtle. WSL returns the output in utf-16 and when using chinese as system language we mess everything up as we encode in utf-8. But to complicate the things even worse, WSL also uses a different symbol for `:`, so indexOf(`:`) always fails. If you're not aware (i wasn't), unicode defines vertical colon symbol, small colon symbol and full width colon symbol which are almost identical visually talking.
