### ISSUE TITLE
WSL detection reports incorrect error on Windows 11 Pro w/o wsl 2 installed

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4865]
### Bug description

An attempt to install podman shows error below about wsl version should be >=1.2.5

![image](https://github.com/containers/podman-desktop/assets/620330/0ec4bd53-7acf-4761-90b9-9becf10484e6)

But `wsl --status` prints out version 2

```
>wsl --status
Default Version: 2

The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl --update'.
```

### Operating system

Windows 11 Pro

### Installation Method

Installer from website/GitHub releases

### Version

1.5.0

### Steps to reproduce

1. Windows 11 pro with WSL enabled
2. No VMs have been created yet
3. Install Podmand Desktop using installer for Windows downloaded form https://podman-desktop.io
4. Try to install Podman after statrting Podman Desktop

### Relevant log output

```shell
>wsl -l -v
C:\Users\dgolo>wsl -l -v
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```
```


### Additional context

After running ```wsl --update``` it works. The error disappeared.

_No response_

**Comment by thomasfinstad** [comment]
Can confirm problem on win 11 pro, and solution proposed.
