### ISSUE TITLE
Can't login to registry `registry.gitlab.com`

### ISSUE THREAD

**Issue by tepene** [containers/podman-desktop#487]
### Bug description

I get an error `response code 404 (not found)` when trying to login to `registry.gitlab.com` in podman-desktop

![image](https://user-images.githubusercontent.com/54766327/192143160-7e2d0449-897e-475e-8ff6-254f2d51d367.png)

but it works from the host cli

![image](https://user-images.githubusercontent.com/54766327/192143175-1da14131-c69e-4bff-84cd-a1c1aaff6f1f.png)

### Operating system

Fedora Silverblue 36

### Version

0.0.7

### Steps to reproduce

1. Open **podman-desktop**
2. Select **Preferences**
3. Select **Registries**
4. Click **Login to a registry**
5. Type `registry.gitlab.com`in the **Server URL** field
6. Type your Gitlab username in the **Username** field
7. Type your GitLab Personal Access Token in the **Password** field
8. Select **LOGIN TO A REGISTRY**

### Additional context

Podman-Desktop installed as flatpak.

**Comment by benoitf** [comment]
thanks for the report @tepene
