### ISSUE TITLE
Collect usage data button grows when a spinner is shown.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4882]
### Bug description

Odd issue when you press Collect usage data is pressed, it grows when the spinner is shown.

### Operating system

mac M1

### Installation Method

None

### Version

1.5.0

### Steps to reproduce

Press the button:

https://github.com/containers/podman-desktop/assets/6422176/b4f16c4f-4ed5-4542-adb4-47ae2b3b6e60

**Comment by deboer-tim** [comment]
I thought this might be caused by the removal of PatternFly (change to line-height or maybe something else), but I fixed that (#5047) and this was still happening. Traced it back as a regression caused by #4600, disabled buttons now have a completely different size.
