### ISSUE TITLE
Pod list UI shows environment and containers not centered

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4883]
### Is your enhancement related to a problem? Please describe

* Environment looks odd when it's all the way to the right.
* Containers status dots also look out of place / odd underneath the column header name.

### Describe the solution you'd like

Have them centered.

**Comment by deboer-tim** [comment]
I can fix this as I switch the page to the table component.

**Comment by deboer-tim** [comment]
This was fixed by #5310.
