### ISSUE TITLE
Environment labels on Container list should be centered

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4884]
### Is your enhancement related to a problem? Please describe

See below, it looks odd / out of alignment vs the Environment header on top:

![Screenshot 2023-11-20 at 10 39 58 AM](https://github.com/containers/podman-desktop/assets/6422176/470c0c68-4b63-4041-989b-e957a83f0540)

### Describe the solution you'd like

Centered labels.

**Comment by deboer-tim** [comment]
The new table component does not allow you to align column headers and content differently, so I will fix this as I switch each page over.
