### ISSUE TITLE
Name header for Pod / Container / Volume / Image list should be left-aligned not centered.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4885]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-11-20 at 10 41 10 AM](https://github.com/containers/podman-desktop/assets/6422176/d7fe6fe3-9047-4d9c-b765-27f65cd29559)

Left-aligned name, but the header being centered looks a bit odd. 

### Describe the solution you'd like

See above, we left-align the text, the "Name" should be left-aligned too across all lists (pods, images, containers, images, etc.)

**Comment by deboer-tim** [comment]
The new table component does not allow you to align table column headers and text differently ;-) and I am good to fix this as I switch each page over.

**Comment by deboer-tim** [comment]
All pages except the Containers page now use the table component and this is fixed. Moving the container page over is tracked by #4843 and will fix this, so I'm closing this issue.
