### ISSUE TITLE
Size column in Volumes and Images should be center aligned

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4886]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-11-20 at 10 46 49 AM](https://github.com/containers/podman-desktop/assets/6422176/81975b83-2f1e-4457-a51e-14c3034ba240)

I find it odd that only size out of all the columns is right-aligned vs all the other columns.

### Describe the solution you'd like

We should have it center aligned similar to age

**Comment by deboer-tim** [comment]
Not sure I agree - in my experience sizes are usually right aligned so that the units (e.g. MB above) are all aligned and larger values are easier to scan for. e.g. I think both Mac and Windows file explorers do this.

**Comment by benoitf** [comment]
if I remember well, there was an issue asking for them to be right aligned ! :-)

**Comment by deboer-tim** [comment]
lol, took some digging but I opened an issue in May 2022 and Florent fixed: https://github.com/containers/podman-desktop/issues/130

**Comment by cdrage** [comment]
Ahhh that makes sense, thank you for clarifying. I should of searched a bit better! Closing this, thanks @deboer-tim and @benoitf
