### ISSUE TITLE
Scrollbars shouldn't be in light mode

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4888]
### Bug description

Since the PatternFly removal scrollbars are almost invisible because they're defaulting to light mode and render as black, and when you hover they go really light:

https://github.com/containers/podman-desktop/assets/19958075/3ac6736d-7465-4e47-854f-00b690a59dc8

I already proposed a possible fix via #4826, but #4887 is in this area as well.

### Operating system

macOS 14.1

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
sorry @deboer-tim I didn't replied in the PR
yes I think we need to go with the color-scheme but as you proposed in a comment, it needs to be done conditionally (don't hardcode it to dark in the css file)

**Comment by deboer-tim** [comment]
Yes, the fix proposed in #4826 was purely 'quickest path to fix regression'. Now that we have #4887 we should do something dynamic instead.

Want me to do a PR based on my comment https://github.com/containers/podman-desktop/pull/4887#pullrequestreview-1740355205, or do you have a better idea?

**Comment by benoitf** [comment]
I'll provide a PR, I'll explore different solutions
