### ISSUE TITLE
Modify Kube context mockups to allow for indicating the default kube context in kubeconfig

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4889]
What is needed here is an updated design / modification to the Kubernetes contexts / cluster dashboard mockup to show how which cluster > context is the default context.

![Image](https://github.com/containers/podman-desktop/assets/799683/bac49e8d-7d19-473c-8831-577d64e4da93)

Note that we have a way to change the default kube context in the lower purple status bar of the app window:
![Image](https://github.com/containers/podman-desktop/assets/799683/7acb38ef-e719-4a5c-a814-a096c7f8b744)

So @ekidneyrh we need a way (an icon? a difference in color? etc.) in the first screen above to show which of these is currently the default (as listed in that status bar control.) We usually use purple as a highlight color so maybe there's something there. Feel free to poke around other mockups in the team site on penpot to get ideas if you're stumped.

**Comment by ekidneyrh** [comment]
Did some work on this today - penpot file can be found [here](https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/18f3baa5-c6db-81d1-8002-9f756ec487eb?page-id=27f4d9f3-bdca-80a2-8003-563056ae5d34).

I was looking through the other mock-ups to see the style of buttons / labels. I have two variations of an initial draft.

Both involve a purple highlight around the component. The first has a 'Default' label to the right, beside the arrow. 

![Image](https://github.com/containers/podman-desktop/assets/87311656/22521ece-e9d7-463d-9ef0-3f53b2a4519c)

Second has the default labelled beside the Local / Remote label in a purple variation. 

![Image](https://github.com/containers/podman-desktop/assets/87311656/55475812-ba3d-4de7-9030-16be6eac5456)

And here's the two together for easier comparison:

![deafult-kube-context-4](https://github.com/containers/podman-desktop/assets/87311656/8421b17c-3f8f-4c5c-b582-0906921ebf82)

Let me know what you think!

**Comment by deboer-tim** [comment]
I prefer the badge on the right: it stands out more to me, and also doesn't cause the other text to shift when it's added/removed. Which could be fixed if it was to the right of the other text, but I think it stands out more on its own.

+1 to purple border too, it look on-theme to me and stands out well.

Nit: it's the Kubernetes 'current context', so I think the badge should say 'Current', not 'Default'.

**Comment by ekidneyrh** [comment]
@deboer-tim Thanks for the quick reply, here it is with fixed wording on the badge -

![Screenshot 2023-11-24 at 14-38-04 Penpot Design Freedom for Teams](https://github.com/containers/podman-desktop/assets/87311656/a951cf2c-0d65-408c-a79d-c93d5eb579e8)

![current-context-kube](https://github.com/containers/podman-desktop/assets/87311656/73efe4b7-4abd-4778-a757-dde5656d9e72)

**Comment by benoitf** [comment]
hello, let say I have 15 contexts in my kube config file, I would assume that the default context would be on top when loading the page (of course I can later select another one and it won't move the tiles) but I guess we could always see the current context being on top ?

As for my 2 cents, I think I like a mix of the two approaches. On the right but having it spelled in a purple box

**Comment by ekidneyrh** [comment]
That's a good point! 

I adjusted the mock-up accordingly and also tried out the purple label on the right:

![Screenshot from 2023-11-27 10-52-58](https://github.com/containers/podman-desktop/assets/87311656/d88ca5b4-c0ae-4508-8672-44847b258860)

**Comment by benoitf** [comment]
thanks 👍

**Comment by deboer-tim** [comment]
+1, looking good.

Two nits:
- I noticed the header. We don't have icons nor a colored border on Settings pages, so I'm assuming we're just focused on the 'pane' here.
- I still think it should be a 'Current' badge, not Default.

**Comment by ekidneyrh** [comment]
That's my mistake for the default there - I had it changed but somehow reverted. Apologies for that!

![Screenshot from 2023-11-27 13-53-39](https://github.com/containers/podman-desktop/assets/87311656/06f1563d-49df-49d7-9d6a-c5f496045bd5)

> I noticed the header. We don't have icons nor a colored border on Settings pages, so I'm assuming we're just focused on the 'pane' here.

I'm not quite sure what you mean here - are you referring to the menu on the left? But yes I've been working on just the plane of the design. :smile:

**Comment by deboer-tim** [comment]
> I'm not quite sure what you mean here - are you referring to the menu on the left? But yes I've been working on just the plane of the design. 😄

The title bar that says 'Kubernetes Context'. Assuming we're just focussed on the current context indication we're good here. 👍🏼

**Comment by ekidneyrh** [comment]
Closing as discussion surround the current kube context is taking place at #4891  - deciding how it will fit along with the delete and change actions.
