### ISSUE TITLE
Modify Kube context mockups to have an icon well bar to place delete, edit, change default icons

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4891]

**Comment by ekidneyrh** [comment]
I opted to adding the actions within an ellipse menu instead of an icon well, as I felt the cards are starting to get a bit cluttered. Also added in a darking of the rest of the contexts so it's obvious to the user what one they are editing.

((I tried to make a GIF, but Gnome won't show my cursor in the screen recordings, so I cooked up a homemade GIF instead))

![edit-menu](https://github.com/containers/podman-desktop/assets/87311656/1d165140-6b37-40a8-b22d-c61394123779)

Is this direction okay, or would we rather have the icon well? 

I think a line underneath and different background colours would be a good way to show what fields are editable.
I just wanted to check if the editable fields going to be these? 

![fields](https://github.com/containers/podman-desktop/assets/87311656/5ea6f6e1-916a-4572-be4d-9c3439853a35)

And I was wondering if this ticket ties in with #4890, as my understanding is that it's changing the name of the context, so can that be done under the editing action of the card triggered by the purposed ellipse menu?

**Comment by deboer-tim** [comment]
We already have several variations on where actions are on cards (dashboard providers, Settings > Resources, etc), so to me the actions at the bottom right seem out of place and inconsistent. My initial reaction is that they should be at the top right, as a couple frequent actions + popup.

I'm already concerned about vertical space too (e.g. I have 10 contexts and only three are visible at a time on screen), so IMHO removing that bottom line and moving the API/cluster info 'up' would be good.

For editing, we're starting a pattern in Settings > Resources where editing is kind of like going to the Details page, but we don't have details or that separate page to go to here. In Settings > Preferences, you just focus and start typing to edit. This feels like a third way to edit. I don't have a specific recommendation, but maybe more like Preferences?

For both of these I hope it's clear that my main concern is just that we keep everything to a very small set of patterns that we use consistently. I'm even ok if we decide there's a better pattern than one of the ones we've been using, but we're still cleaning up places where the patterns changed early on and aren't consistently applied.

**Comment by ekidneyrh** [comment]
Thanks for the detailed reply, Tim. I agree with everything you mentioned there. I'll have a look at that pattern in the preferences, that's my fault for not looking thoroughly at what's already there. I'll update soon.

**Comment by ekidneyrh** [comment]
https://github.com/containers/podman-desktop/issues/4890 can be merged in with this ticket given that it's editing on the same card.

**Comment by ekidneyrh** [comment]
Here is an updated mock-up:

![Kooha-2023-11-30-15-44-42](https://github.com/containers/podman-desktop/assets/87311656/91e35703-422a-43b8-8973-02889efa9872)

I changed the label style based on a suggestion by Máirín, so it's not taking up the right-hand side of the card. Also, when a context is not the current, the user can press a link to allow them to set it as so. A context will only be deselected when another context is set as the current.

I got rid of the ellipses button and instead the fields can be clicked on to edit, like some of the form patterns do already. 

For the title, I have a pencil icon that can be clicked to display the field and the user can edit that text then. 

I put the delete button on the upper right to delete a context. 

> I'm already concerned about vertical space too (e.g. I have 10 contexts and only three are visible at a time on screen), so IMHO removing that bottom line and moving the API/cluster info 'up' would be good.

There's a lot of information on the cards, so I was only able to shorten it slightly. We could minimise it more by implementing a drop-down to hide some of the info there? Let me know what you think!

**Comment by mairin** [comment]
Hey Emma!

You got the highlight / curent mockup context thing perfect, I think it looks great. I think the link to make current... seems a little too crowded. Can we add more padding to the top of the card?

**Comment by deboer-tim** [comment]
I really appreciate the changes to slim the card vertically (to fit more contexts onscreen), but I think that's probably what is responsible for Mo's crowding comment, and I worry having current context as essentially a gap along the top of every context card is both a lot of vertical space and slightly different from most of our other cards that have icon/name immediately in top left corner.

Would moving the current context badge/annotation thingy 2/3 of the way to the right be an option instead? Then it wouldn't be crowded nor require any extra vertical space. Anything else we could try?

**Comment by ekidneyrh** [comment]
![Screenshot from 2023-12-06 11-12-30](https://github.com/containers/podman-desktop/assets/87311656/c63fc4ea-e1e7-4d58-93bc-3c355ee91688)
![Screenshot from 2023-12-06 11-12-18](https://github.com/containers/podman-desktop/assets/87311656/82734139-1f70-4079-9d73-de9ad01e27ec)

> Would moving the current context badge/annotation thingy 2/3 of the way to the right be an option instead? Then it wouldn't be crowded nor require any extra vertical space. Anything else we could try?

I moved the label back over to the left and beside the icon, and the 'set as current' link there as well. I made the label text slightly bigger to balance with the delete icon. I had to detach it from the card outline as it didn't look right when not in the immediate corner.

**Comment by deboer-tim** [comment]
+1. That solves my prior concerns, but worried now that Current looks like a button. I don't think we need another mockup / don't want to spend a lot of time here, maybe there is just something minor we can do to make it look less clickable.

**Comment by mairin** [comment]
@deboer-tim are we good on this one design-wise and can close it out? do you know if we have an issue for implementation?

**Comment by deboer-tim** [comment]
Yes, I think we can close. Delete was already done without the well (#4417), but issues to add details (#4562) or adding a context (#4706) would implement this design.
