### ISSUE TITLE
Onboarding experience with Podman

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#49]
## Description

When a user downloaded and uses Podman for the first time, the user will not have any machine configured with podman.
The tools should provide the ability for end-users to quickly get a podman-machine up and running so that the end-user can start using containers. 

## Acceptance criteria

- [x] If podman-machine is not started, then the user has the ability to start the podman-machine
- [x] If podman does not have a machine initialized, the system tray allows the user to create and start a podman-machine
- [x] If the user has multiple podman machines, the user has the ability to switch to a different machine. It will stop one of the machine and start the selected one

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/244
