### ISSUE TITLE
Error in Podman Desktop Setup

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#4919]
### Discussed in https://github.com/containers/podman-desktop/discussions/4913

<div type='discussions-op-text'>

<sup>Originally posted by **Rexxrally** November 21, 2023</sup>
I installed Podman Desktop. It tells me that Podman 4.7.2 is installed but needs to be set up, and gives me a set up button.
The next screen tells me that Podman is already installed and to press the Next button to proceed, which I do.
It tells me that it couldn't find any Podman machine and to press Next to proceed to create one, which I do.
The next screen says:

This extension does not provide a component of type "createContainerProviderConnection"

I can't even find anything Googling this error message. What can I do to fix this issue?</div>

**Comment by odockal** [comment]
@jeffmaury Seems like a dupe of #4594

**Comment by jeffmaury** [comment]
Not exactly the same as this one is about the podman extension being slow to start
