### ISSUE TITLE
I cannot install External extension if not present in the featured extension table

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4930]
### Bug description

After randomizing the featured extension table, I am not able to directly click and download external extensions by other means than to search for an image name of the extension and downloading it manually.

![Screenshot_20231121_221257](https://github.com/containers/podman-desktop/assets/19164299/a5fe6ccd-deaa-47b4-aa67-378497cb3649)

### Operating system

Any

### Installation Method

Other

### Version

next (development version)

### Additional context

I would suggest to include external extensions in the list if they are not installed by default.

**Comment by benoitf** [comment]
depends on https://github.com/containers/podman-desktop/issues/2170 (to have search option, etc)

**Comment by odockal** [comment]
@benoitf Seems like this is out of date since the new extensions design.

**Comment by benoitf** [comment]
yes, closing as it's now possible
