### ISSUE TITLE
Markdown component renders links as regular text

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#4932]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/620330/abe30e57-3f8b-4826-bffe-2ee2bfb30492)

In the image above compose.io should be rendered as link. It still has a hand cursor and works as a link.

### Operating system

macOS Sonoma 14.1

### Installation Method

None

### Version

next (development version)

**Comment by cdrage** [comment]
still valid
