### ISSUE TITLE
Container stats randomly appear & disappear

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#495]
### Bug description

I saw container stats (CPU, memory) had been added and thought I'd try it out myself. I was confused when they weren't there, but then a few minutes later as I was using Desktop they appeared... then disappeared again. They repeatedly do this while I'm using Desktop, haven't figured out what's triggering it.

### Operating system

macOS 12.6

### Version

0.8.0

### Steps to reproduce

Haven't figured this out yet. After starting a container the stats aren't there. Sometimes the UI randomly appears as I'm clicking on the Terminal or Details tabs, usually it disappears after a couple seconds.

**Comment by benoitf** [comment]
you may probably attach a screencast

For now I'm not able to reproduce it

https://user-images.githubusercontent.com/436777/192883260-b7251a34-6ce4-49ee-b5c1-79047a6b2e46.mp4

**Comment by deboer-tim** [comment]
Maybe not the best video, but you'll get the idea.

https://user-images.githubusercontent.com/19958075/192886134-51ed5ed5-5964-478c-8a8f-4fb8375342bf.mov

**Comment by slemeur** [comment]
I've seen the same.
Maybe, memory and cpu should always be visible (even if the container is running or not). 
We would just have a dedicated state to show that the container is not running.

**Comment by deboer-tim** [comment]
This particular container (nginx) isn't doing much without traffic, any chance it is just disappearing when CPU and memory are both '0'?
I agree with Stevan though, aside from this issue it is probably better to show the bars in a disabled state when the container isn't running.
