### ISSUE TITLE
docs: nested virtualization is not possible (unless on intel platform)

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4950]
### Is your feature request related to a problem? Please describe

I’m running Windows 10 Pro (10.0.19045) in a VM on a Mac. I’ve installed WSL, now I’m trying to install podman in that VM. It does not work.

### Describe the solution you'd like

Explain in the FAQ / Troubleshooting guides that nested virtualization is not possible (unless on intel platform).

**Comment by afbjorklund** [comment]
Must be some kind of hat trick? :-)

Podman, in a Linux container (WSL distro) on a Linux VM on a Windows VM on a Mac OS...
