### ISSUE TITLE
Resizing terminal window causes uncaught error

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#496]
### Bug description

Maybe not a big deal, but happened to see this when resizing.

### Operating system

macOS 12.6

### Version

0.8.0

### Relevant log output

```shell
xterm.js:1 Uncaught Error: This API only accepts integers
    at h._verifyIntegers (xterm.js:1:89414)
    at h.resize (xterm.js:1:86153)
    at c.fit (xterm-addon-fit.js:1:656)
    at ContainerDetailsTerminal.svelte:70:16
```

**Comment by benoitf** [comment]
it's there since day 1 (it can be safely ignored, it's when terminal is not yet rendered)
It's a bug in xterm that should be fixed in the newer releases of xtermjs

https://github.com/xtermjs/xterm.js/issues/3118

**Comment by deboer-tim** [comment]
Excellent, we can just close this issue then since there is no additional action.

**Comment by benoitf** [comment]
I'm reopening, will fix it when using a newer xterm.js fixing that console.error bug
But moving to enhancement as it's not preventing Podman Desktop to work
