### ISSUE TITLE
Close Dev Tools window for all E2E tests

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4968]
### Is your enhancement related to a problem? Please describe

It happens that when running the e2e tests, the electron application is opened with dev tools window opened by default. Sometime it prevents to properly find elements or interact with them during the testing.

### Describe the solution you'd like

Close the dev tools as part of `podman-desktop-runner.ts` `start` method, as this functionality is useful for all e2e tests as we can get better screenshots as well.

### Additional context

Failing Smoke e2e test on PR check: https://github.com/containers/podman-desktop/actions/runs/6950062212/job/18971018336?pr=4844

Example of the test failure screenshot:
![Check_image_details_failure](https://github.com/containers/podman-desktop/assets/19164299/d4fefd1a-a2ea-4cd1-88dc-6593d3287df0)

**Comment by odockal** [comment]
@deboer-tim FYI. PR will follow asap.

**Comment by benoitf** [comment]
I would not close it, just keep it in a separate window

**Comment by odockal** [comment]
@benoitf Proper issue to handle this enhancement: https://github.com/containers/podman-desktop/issues/5031.
