### ISSUE TITLE
Need to implement real-time updating for Kubernetes stores (pods, ingress, routes, etc.)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4974]
### Is your enhancement related to a problem? Please describe

 I noticed with the k8s implementation is we do not have any real-time updating yet. In my k8s implementation I just had it update every 5 seconds, but I don't see anything in the current stores code for deployment / ingress / routes which show it's updating every X seconds. It made me dig through the PD code to realize we don't have it real-time updating either for pods at the moment, we have it under https://github.com/containers/podman-desktop/blob/fa3d78d78d8167c2b06c0323c1897538be10ac58/packages/renderer/src/stores/pods.ts#L88 grabAllPods so that it only updates on extension start or pod-event... so it's relying on a pod change to update.
 
 
 There is *so* many events happening in Kubernetes that unlike monitoring for Podman (we can just watch for podEvent), we have to either setup a watcher, or we simply have to do it every X amount of seconds. 

### Describe the solution you'd like

- [ ] Have a constant every X seconds somewhere (or watchers) in Podman Desktop to retrieve Kubernetes information
- [ ] ONLY call it if we have a valid connection ( we do not want to try hitting the API when it's invalid all the time... and back off for X amount of seconds if there is an issue).
- [ ] Implement it into Pod / Ingress / Routes / etc.

**Comment by deboer-tim** [comment]
+1. I hit this when I finally got a Deployment UI in #4931, and figured this was the case for pods but nothing else - thanks for confirming, I agree we need to do this (soon). Adding to epic #4575.

**Comment by feloy** [comment]
Using watchers or informers would be more efficient. Polling the clusters from all the developers workstations will be a pain for the cluster

**Comment by lstocchi** [comment]
Just an update on this. I'm trying to work on a store that uses informer to update itself for the ingress page. Hope to have something for today, then it can be reused for all other kubernetes stuff

**Comment by deboer-tim** [comment]
@lstocchi looking forward to it. 👍🏼 As per above the support for updating Deployments using the same pattern as pods was merged in #4987. If your informer store works better I agree we should replace #4987 and use informer for all Kubernetes types; if it takes longer we have a path we could use for a couple more types in the meantime.

**Comment by deboer-tim** [comment]
Can we close this now? Informer stores are working well in my testing. We have issues open for bugs/usability and may improve the stores in the future, but they are doing what was required here.
