### ISSUE TITLE
UI alignment between pages

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#498]
### Bug description

Ok, you're going to hate how visually picky I am, but here's something that I noticed. :)

If your Desktop window is narrow, then when switching back and forth between the Images and Containers tab the first couple columns line up. If your window is really wide both tables expand the same way, and the same thing works.

But if your window just happens to be at the right width where Images is starting to expand (as of course mine was!), then the two don't match as you flip back and forth. It makes it a bit visually jarring instead of a smooth switch.

My preference is that the first two (or maybe three or more) columns do not expand as the window width increases. I don't think they need it, it gives more space to the columns that do need more width, and it avoids this issue.

### Operating system

macOS 12.6

### Version

0.8.0

### Steps to reproduce

Switch to the Images page. Make it narrow, then slowly expand the window width until the checkboxes start to move. Now switch to Containers and back.

**Comment by benoitf** [comment]
not a bug, labelling as enhancement

**Comment by deboer-tim** [comment]
This was fixed (indirectly) via PR #1182.
