### ISSUE TITLE
E2E tests instability: electronApplication.browserWindow: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4983]
### Bug description

The patch for #4968 was merged and it introduced probably a regression. E2E main tests started to fail. It is very interesting that Smoke E2E suite is still passing without any issues. 

Error differs a bit when run locally, run the nature could be the same.

Playwright test log (this one differs)
```
Error: electronApplication.browserWindow: Execution context was destroyed, most likely because of a navigation.
```
Console output:
```
main ↪️ System ready. Loading extensions...
STDERR: Error creating window Error: ERR_FAILED (-2) loading 'file:///home/odockal/git/podman-desktop/packages/renderer/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:84559)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:84946)
    at WebContents.emit (node:events:514:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///home/odockal/git/podman-desktop/packages/renderer/dist/index.html'
}
```

### Operating system

Linux

### Installation Method

Other

### Version

next (development version)

### Relevant log output

```shell
main ↪️ System ready. Loading extensions...
STDERR: Error creating window Error: ERR_FAILED (-2) loading 'file:///home/odockal/git/podman-desktop/packages/renderer/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:84559)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:84946)
    at WebContents.emit (node:events:514:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///home/odockal/git/podman-desktop/packages/renderer/dist/index.html'
}
```

**Comment by odockal** [comment]
The problem seems to be introduced with [remove playwright dep]
and eventually partially fixed for e2e smoke tests with [add playwright install] step in gha file. Now @ScrewTSW is working on the fix for all e2e tests.

[remove playwright dep]: https://github.com/containers/podman-desktop/commit/56d7d555c2ff1851223ee6ba81a6b14e8a74ac9b
[add playwright install]: https://github.com/containers/podman-desktop/commit/466340a8fbb6bace9d16f02bf320a1c5e1c2723f

**Comment by odockal** [comment]
It might be that the fix mentioned above is not directly solving this issue. 
Instead we might adjust opening - closing developer tools window in application startup and preferences, decribed in #5031.

**Comment by odockal** [comment]
Outstanding PR could also fix an issue, but it seems that it is not a way how to properly fix the issue.

**Comment by odockal** [comment]
Solved by: https://github.com/containers/podman-desktop/pull/5274

**Comment by cbr7** [comment]
Reopened because issue is still occurring.
