### ISSUE TITLE
Some visual confirmation that a deletion of container is happening after click of trashcan icon

### ISSUE THREAD

**Issue by profetik-777** [containers/podman-desktop#4993]
### Is your enhancement related to a problem? Please describe

When deleting a container - there is no visual indication (progress bar on the bottom of podman interface or "spinner" circle loading at or near button that was clicked). 

I thought I miss-clicked or the click didn't register, and I went to click again and I almost accidentally  deleted a second container - because right before I attempted to click again -the container disappeared and the one below it took its place. 

p.s. no confirmation dialogue - but that is technically a separate ux  enhancement that is adjacent to this one. 

### Describe the solution you'd like

1. visual indication that the container is the process of deleting (progress or visual queue letting me know something is happening). 

### Describe alternatives you've considered

Confirmation dialogue "Are you sure you want to delete this container?

[ name of container ] "

Double confirmation acts as the "visual confirmation" that you clicked on the right one.

**Comment by Andres6936** [comment]
@profetik-777  We need a confirmation modal when pressing the delete button, I accidentally pressed the delete button and because there is no modal I have lost hours of work.

**Comment by Andres6936** [comment]
This issue can be closed, the functionality has been included. @profetik-777 @cdrage

**Comment by deboer-tim** [comment]
Thanks for confirming @Andres6936
