### ISSUE TITLE
Align notifications to right side of side-bar

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#500]
### Is your enhancement related to a problem? Please describe

![image (1)](https://user-images.githubusercontent.com/6422176/193026804-88954d4d-aa7f-408b-8f53-7420709810ae.png)

I find the notifications a bit odd that they aren't aligned in a row on the side bar. Perhaps we could improve the UX/UI to align to the right?

### Describe the solution you'd like

Aligned to the right side of the sidebar.

**Comment by mairin** [comment]
This is a good catch, thanks @cdrage!
