### ISSUE TITLE
Improve table column sharing

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5002]
### Is your enhancement related to a problem? Please describe

The new table component allows you to create columns for a given type (e.g. VolumeInfoUI) and apply a renderer for that type, e.g.:
`new Column<VolumeInfoUI>('Age', { renderer: VolumeColumnAge, ...`
and:
```
export let object: VolumeInfoUI;
...
  {object.age}
```

This encapsulates the volume/age combination in a nicely typed way, but it doesn't easily support sharing column renderers between types.

### Describe the solution you'd like

There are at least a couple ways we could support sharing:
1. Decide the typing is less important, and use the same pattern with `let object: any` and render whatever age property exists, e.g. VolumeInfoUI.age, ImageInfoUI.age, anything with a `.age`.
2. Let the column provide a mapping function, e.g.:
`new Column<VolumeInfoUI>('Age', { renderer: SimpleStringColumn, map: object => object.age, ...`
and:
```
export let object: string;
...
  {object}
```

**Comment by benoitf** [comment]
> Decide the typing is less important, and use the same pattern with let object: any and render whatever age property exists, e.g. VolumeInfoUI.age, ImageInfoUI.age, anything with a .age.

you can just use an object requiring an age property, then it will work if you use VolumeInfoUI, ImageInfoUi, etc
no need to use `any` you can require a specific property

**Comment by deboer-tim** [comment]
> you can just use an object requiring an age property, then it will work if you use VolumeInfoUI, ImageInfoUi, etc no need to use `any` you can require a specific property

I keep forgetting that's a reasonable option in typescript :), but I think we should reserve it for more interesting cases, e.g. where there are two properties or something special about the type. For a simple 'this column just displays a string' I think the second option is better and more reusable.
