### ISSUE TITLE
Multiple Podman Machine support

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5009]
If podman provides support for running more than one podman machine at a time in a future release, we will want to enable this in the Podman Desktop UI.

**Comment by jeffmaury** [comment]
That's already supported, what is missing ?

**Comment by mairin** [comment]
You're right, I was thinking when it lands making sure the UI we have works properly with it. But we probably don't need an issue for that. I will close 🤦🏻‍♀️
