### ISSUE TITLE
Nit: dead space under Terminal/Log should be same as background colour

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#501]
### Bug description

When there are no logs the actual log output window only goes half way down. The Terminal window looks like it resizes in increments of the text height. In either case there is a section at the bottom that's a different colour than the terminal window itself. Please set this section to the same colour as the terminal window background so that it doesn't stand out.

<img width="837" alt="Logs" src="https://user-images.githubusercontent.com/19958075/193029640-47ff68ab-0ab6-4a07-a4e9-17e1ddde6ef7.png">
<img width="837" alt="Terminal" src="https://user-images.githubusercontent.com/19958075/193029662-7b50ec44-a6aa-405d-afe3-b07774fb45af.png">

### Operating system

macOS 12.6

### Version

0.8.0

**Comment by benoitf** [comment]
labelling as enhancement
it's not preventing to use the terminal

**Comment by PatentLobster** [comment]
You can set the `status/in-progress` label, MR incoming
