### ISSUE TITLE
Provide ability to create and/or update a podman machine with a custom image

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5010]
### Is your feature request related to a problem? Please describe

Some users may want to use a custom image for their Podman machine. We should support this at podman machine creation time, or even allow rebasing the image to a different one.

### Describe the solution you'd like

- When the user goes through the Podman onboarding flow, we could offer a field for the user to indicate the location of a custom image. 
- When the user already has a Podman machine they want to convert to another image, allow a way to do that from the Settings > Resources > Podman card for that podman machine. Will also offer a field for user to indicate location of the custom image. Under the covers, would use

**Comment by benoitf** [comment]
AFAIK you can already provide a custom image

**Comment by deboer-tim** [comment]
Yes:
<img width="626" alt="Screenshot 2023-11-27 at 4 56 15 PM" src="https://github.com/containers/podman-desktop/assets/19958075/9309f3e3-174d-4949-b22f-5ffe2f7672e3">

The ability to change it later is still new. IMHO we could do things to make it more usable too, e.g. right now it's not obvious what you need to point to, there's no validation, etc.
