### ISSUE TITLE
deleting kube contexts is not working correctly

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#5014]
### Bug description

The deletion of Kubernetes contexts is not working correctly, when the cluster of the current context is not accessible.

Every time a context is deleted, the desktop checks if the cluster of the current context is accessible. If not, this can take a (very) long time. During this time, nothing is displayed in the screen and the user doesn't know what is happening.

Do we really want to do this check every time? In any case, it should not be blocking for the user, as the main purpose of the operation is to edit a file, not to test the connectivity to clusters.

https://github.com/containers/podman-desktop/assets/9973512/afd510eb-6577-4a8b-9bb7-6597f508dfe0

### Operating system

Linux Fedora

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by benoitf** [comment]
would be interesting to paste the devtools console log as well

**Comment by feloy** [comment]
After some tests, this happens when the cluster of the current context is not accessible. 

If the connection gets a very long time to finish (and to fail in this case), there is no timeout to make this time shorter.

**Comment by deboer-tim** [comment]
I have deleted contexts that are completely unaccessible or have wrong auth, but presumably they're 'failing fast' so I haven't seen this behaviour. I agree that deletion should be relatively instantaneous for the user and not dependent on connecting to the cluster.

**Comment by feloy** [comment]
I propose in #5025 to send an update event as soon as possible, so the lists is refreshed before the kube file is parsed and analyzed again.
