### ISSUE TITLE
Longer sessions in Terminal window

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#502]
### Is your enhancement related to a problem? Please describe

Sometimes I'm in the middle of doing something in the Terminal window and switch to another page/tab for a minute to check something else. When I come back, the previous output is gone and you're starting from a fresh terminal.

### Describe the solution you'd like

I'd like the ability to switch away from the terminal and back, and continue what I was doing before. I am fine if there are cases where something happened and we need to reset the terminal (or it 'loses connection'), I am only talking about cases where I've tabbed away and come right back.

If someone thinks there should be a way to reset the terminal as well, a clear/reset button within the terminal would be fine.

**Comment by mairin** [comment]
This one bit me this past week... would love to see more of a history on these
