### ISSUE TITLE
podman-desktop label in Windows notification bar is quite crypto

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#503]
### Is your enhancement related to a problem? Please describe

See picture

### Describe the solution you'd like

Something like Podman Desktop 

### Additional context

![image](https://user-images.githubusercontent.com/695993/193031620-acf0a7fe-3745-41e0-b4ca-001bb67a4ea7.png)

**Comment by benoitf** [comment]
I noticed that as well 👍

**Comment by cu8code** [comment]
Hey, I would like to solve this. Any idea how will I be able to solve this. @benoitf

**Comment by benoitf** [comment]
yes it's very easy to fix @cu8code 

Need to call setAppUserModelId in case of Windows on electron / in main package

**Comment by PatentLobster** [comment]
You can set the `status/in-progress` label, MR incoming
