### ISSUE TITLE
Extend Pod E2E testing scenario with application deployment check

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5042]
### Is your enhancement related to a problem? Please describe

Follow-up to [4279](https://github.com/containers/podman-desktop/issues/4279).
We don't actually check that the deployed application is running on given port.

### Describe the solution you'd like

Check that the deployed pod is actually running and the application is available on localhost.
Some other things to include:
A test for restarting the pod, stopping it and starting again. 
Checking the offering on context menu over pod's actions.
Check that original containers are not running anymore.

**Comment by odockal** [comment]
fixed by: https://github.com/containers/podman-desktop/pull/5143
