### ISSUE TITLE
Wizard Onboarding Sequence

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5045]
### Epic domain

# Goal
Since the version 1.5.0, we have introduced onboarding and configuration sequence that are available to the user either from the Dashboard or from the Settings. Those individual sequences, allow the end-user to easily get things up and running.

This epic is a continuation of this effort, to offer a better 1st time experience with Podman Desktop. We will introduce an onboarding wizard that welcomes and guides the user with a set of tasks - to get ready to use the tool from their first initial experience.

### Initial Scope
As we have the configuration flows for Podman and Compose, those will be the only two that will be scoped initially.

### Welcome
As a user starting Podman Desktop for the 1st time, I will be prompted a welcome window that invite me to select the different components to be installed.

As a user, I can select the components and those will be staged to be configured later during the onboarding sequence.

<img width="715" alt="welcome-condensed" src="https://github.com/containers/podman-desktop/assets/1636769/f3e75d44-3dee-4763-83aa-044f81f83dfa">

The wizard will be a modal window that will use all the space available for the application.

A user would also be able to skip the onboarding sequence by:
- "Skip/cancel" at the top of the screen
- "Cancel" button in the bottom of the wizard.
- Pressing "esc" on the keyboard

### Staged onboarding tasks

Once the items are selected by the end user and the user clicks on "Next". it stages the "onboarding tasks" for the next step
<img width="604" alt="Screenshot 2023-11-29 at 14 50 56" src="https://github.com/containers/podman-desktop/assets/1636769/69864151-dc39-4f36-ace6-72da1cb41493">

#### Podman

During the stage for Podman, we will reuse the configuration wizard we already have available from the settings.

<img width="582" alt="Screenshot 2023-11-29 at 14 51 39" src="https://github.com/containers/podman-desktop/assets/1636769/47ca56f1-a61e-4f93-baa7-5448d5db4ffc">

The user may be able to skip and go to the next onboarding tasks, from the menu.
<img width="73" alt="Screenshot 2023-11-29 at 14 53 23" src="https://github.com/containers/podman-desktop/assets/1636769/1f794937-59bf-4c2f-840d-582c6de4ddb4">

A user would still be able to skip the entire onboarding sequence by:
- "Skip/cancel" at the top of the screen
- "Cancel" button in the bottom of the wizard.
- Pressing "esc" on the keyboard

#### Compose

During the stage for Compose, we will reuse the configuration wizard we already have available from the settings.

The user may be able to skip and go to the next onboarding tasks, from the menu.

A user would still be able to skip the entire onboarding sequence by:
- "Skip/cancel" at the top of the screen
- "Cancel" button in the bottom of the wizard.
- Pressing "esc" on the keyboard

**Comment by cdrage** [comment]
Opened up three issues to cover implementing the global onboarding sequence:

- [ ] #5161 
- [ ] #5162 
- [ ] #5163
