### ISSUE TITLE
Add Memory and CPU values

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#505]
### Is your enhancement related to a problem? Please describe

I really like the new memory and CPU bars, but my reaction as a user shortly after was "50% of what?" If the values are high, as a user I want to know if it is reasonable - e.g. is the process in the container using an unreasonable amount of memory, or is the container/VM too small?

### Describe the solution you'd like

Small indicators on the right side of the bars that show the maximum values, e.g. "2Gb" or "2 cores".

### Describe alternatives you've considered

Use a tooltip instead? Or make it easy to jump to another place where I can find the data.

**Comment by benoitf** [comment]
if you hover on it, it should display the value

on design, no value were displayed https://github.com/containers/podman-desktop/issues/331

**Comment by deboer-tim** [comment]
Ah, I see it now. Due to #495 the bars were often not showing up long enough for the tooltip to appear. It seems like it's taking about 2s to appear, can we make the tooltips instantaneous (or almost) for these?

Memory shows the current value but not total (e.g. I have to do the math that "57.0% (584MB)" means it has 1Gb total). I know it's simple, but can we make this something like "57.0% (584MB of 1Gb)"?

Is there any size (esp. total) we can provide for CPU?

**Comment by benoitf** [comment]
there are two bugs in Podman
https://github.com/containers/podman/issues/15765
https://github.com/containers/podman/issues/15754

one is fixed but only in 4.3 so basically with 4.2 you don't have access to the total memory and the number of CPU

**Comment by benoitf** [comment]
about tooltip delay, this is not something we can speed up (or we don't use tooltips)
https://github.com/electron/electron/issues/12861

**Comment by deboer-tim** [comment]
As usual, you are ahead of the game. :) If newer podman releases should fix this it's no rush, happy to know it's coming. I do think we should drop the tooltip time though.
