### ISSUE TITLE
Column widths should not change with state

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#506]
### Bug description

Currently when you hover over a container that's stopped there are 4 buttons, and when you click start another button (terminal) is added. As a result the row gets wider, and unfortunately the button is on the left, so the stop button moves to the right. When I move and click stop, the terminal button disappears and the layout changes again.

I also just noticed that once the container is started the Started column updates - and also changes width as you go from (e.g.) '1 second ago' to '10 seconds ago' to '1 minute ago'. As a result, the buttons move and the layout changes slightly every second or two.

https://user-images.githubusercontent.com/19958075/193059173-2f1b7689-c32e-484e-a7cb-6e33083c635e.mov

Columns should never change width due to state. The Started column should have a fixed width (e.g. width of the longest string that it could show). The terminal button should always be there (disabled, or even hidden) so that the width doesn't change when the container starts.

### Operating system

macOS 12.6

### Version

0.8.0

**Comment by slemeur** [comment]
Along with this issue, I'm also getting this kind of resize, where the user can't see all the actions:


![Image](https://user-images.githubusercontent.com/1636769/193667924-953f2e04-21eb-48c2-a9c2-c49e0896ad57.png)

**Comment by cdrage** [comment]
> Along with this issue, I'm also getting this kind of resize, where the user can't see all the actions:
> 
> ![Image](https://user-images.githubusercontent.com/1636769/193667924-953f2e04-21eb-48c2-a9c2-c49e0896ad57.png)

Unfortunately this looks to be a limitation with using tables and tailwindcss. You can scroll to the right to view the actions. 

If we were to show to the user all the actions and available information, what we can do instead is use a table for larger screens, and a grid for smaller screens.

See: https://youtu.be/S4MhQ6peq8A?t=567

We can implement this, but we should talk to @mairin before making any large design changes like this.

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop/pull/791 partly fixes this issue as it hides the "terminal" icon behind the menu to reduce the amount of resizing of the "started" column.

**Comment by cdrage** [comment]
I'm going to say that this is *MOSTLY* fixed with the merging of: https://github.com/containers/podman-desktop/pull/878

The width changing has been reduced, but not entire removed.

I'm going to close this issue in favour of this epic issue: https://github.com/containers/podman-desktop/issues/885 which will help accomplish a more permanent fix by switching to grid / adjustable column widths / responsive design.
