### ISSUE TITLE
Add extension installation from OCI image tests 

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#5067]
### Is your enhancement related to a problem? Please describe

The existing extension installation e2e tests do not cover installation through OCI image.

### Describe the solution you'd like

Extend the extension installation e2e tests by adding the option of installation through OCI image in case the original installation button is not available. Edit the component verification cases to accommodate for this scenario.

**Comment by odockal** [comment]
The solution to this issue should very likely resolve the problem we are seeing described here: https://github.com/containers/podman-desktop-e2e/issues/74

**Comment by odockal** [comment]
And related to this one: https://github.com/containers/podman-desktop/issues/4930
