### ISSUE TITLE
Trivy Extension Non-responsive

### ISSUE THREAD

**Issue by eric-peterson-usps** [containers/podman-desktop#508]
### Bug description

When trying to scan a container image using the Trivy extension Podman desktop displays a spinning circle and does not respond.

### Operating system

macOS Monterey v 12.5.1 (Intel)

### Version

0.8.0

### Steps to reproduce

    Navigate to Contributions tab and select installed Trivy extension
    Select docker.io.library/alpine:latest image to scan
    Set toggle to "Only show vulnerabilities that have fixes"
    Click scan button

### Additional context

I'm behind a corporate proxy but have set environment vars for them, as well as, have entered values for them in the Proxies section of Podman Desktop

![image](https://user-images.githubusercontent.com/104593998/193127973-b5d0b949-1334-452d-bd2c-4dffec2b1d9f.png)

**Comment by benoitf** [comment]
I thought I fixed it...I will investigate

**Comment by eric-peterson-usps** [comment]
Does the Trivy extension scan the image that a user pulls down locally?

**Comment by eric-peterson-usps** [comment]
Just an update.  I was able to run a Trivy scan from CLI w/o issue.  It does not appear to be a proxy problem.  I have provided a screenshot from the Trivy scan below.

![image](https://user-images.githubusercontent.com/104593998/193278031-e8c30052-86dd-42c1-bd8f-4c7a7061b5fc.png)

**Comment by benoitf** [comment]
Could you please:

- go the trivy section in Podman Desktop
-  open the dev tools console (view / Toggle Developer tools and then switch to the console tab)
- enter in the console: `$("#my-webview-Trivy").openDevTools();` (it will open another console)
- click on the scan button

report errors you might see on two console

**Comment by eric-peterson-usps** [comment]
Errors:

![image](https://user-images.githubusercontent.com/104593998/193292319-a13ed015-207e-4e4f-9e96-2dfedc2ca95a.png)

**Comment by benoitf** [comment]
@eric-peterson-usps it should be fixed by https://github.com/containers/podman-desktop/pull/511

Could you check a PR build ? (it does not include certificates)
https://github.com/containers/podman-desktop/actions/runs/3174600550

click on artifacts and download mac binaries
![image](https://user-images.githubusercontent.com/436777/193599176-f0590cd6-d3dd-47af-b12b-fe7afa648a96.png)

**Comment by eric-peterson-usps** [comment]
@benoitf The proposed fix seems to be working.  Here is a screenshot from Podman Desktop to show the results of a Trivy scan that I was also able to run using CLI.  I downloaded and authorized the macos-x64-dmg file.

![image](https://user-images.githubusercontent.com/104593998/193643258-8582cb71-9d9c-481e-85b8-187114b8b831.png)

**Comment by benoitf** [comment]
thanks @eric-peterson-usps

**Comment by eric-peterson-usps** [comment]
@benoitf i have noticed a different issue with the app and will submit it.

**Comment by benoitf** [comment]
sure, thanks for reporting issues
