### ISSUE TITLE
Extensions can get from the API the value of their install directory

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#5110]
### Is your enhancement related to a problem? Please describe

Extensions may want to execute a binary or access files in their installation directory. The API should provide a function for an extension to get its installation directory.

### Describe the solution you'd like

```
namespace env {
  [...]
  export function getPluginDirectory(extensionId: string): string;
}
```

**Comment by benoitf** [comment]
hello, not sure what you need there, extension can access to its location for all read-access. (it's relative from where the main entrypoint is)

but usually an extension need to write custom stuff and then it uses ExtensionContext.storagePath for a writing directory

**Comment by benoitf** [comment]
we don't need that API

**Comment by feloy** [comment]
CC @jeffmaury

**Comment by jeffmaury** [comment]
> CC @jeffmaury

Check __dirname (https://nodejs.org/docs/latest/api/modules.html#__dirname)

**Comment by feloy** [comment]
Right, __dirname indicates the directory containing the extension script, and the extension developer knows where to find other files relative to this one.

Closing the issue as not needed
