### ISSUE TITLE
Light icon/logo support

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5116]
### Is your enhancement related to a problem? Please describe

We have support for extensions to provide simple icons, or different ones for light vs dark mode. However, since we only have dark mode we have hardcoded many of these to only use light mode: ProviderLogo, PreferencesAuthentication, possibly ExtensionIcon (#5100). 

### Describe the solution you'd like

Simple component for displaying icons in either mode, which picks up the correct theme, and is reused in these places.

**Comment by cdrage** [comment]
![Screenshot 2024-06-11 at 8 18 39 AM](https://github.com/containers/podman-desktop/assets/6422176/c5059a93-d8fc-455e-a5fa-b640fd128dc5)

Kubernetes icon is still white / no dark mode for it.

**Comment by deboer-tim** [comment]
> Kubernetes icon is still white / no dark mode for it.

This issue was created for extension icons/pngs in the files listed at the top. Light mode has been applied to the svgs in the main nav but my guess is a poor choice of color or wrong ref to color palette. But either way, can you open a separate issue to track?
