### ISSUE TITLE
Podman Desktop still running after selecting quit

### ISSUE THREAD

**Issue by eric-peterson-usps** [containers/podman-desktop#512]
### Bug description

When I go to the Podman Desktop Menu and select quit it closes the window but Podman Desktop is still running.  I have to either force quit or run podman machine stop via CLI to stop all of the Podman processes.

### Operating system

macOS Monterey v 12.5.1 (Intel)

### Version

next (development version)

### Steps to reproduce

1) Select Podman Desktop Menu
2) Select Quit from Podman Desktop Menu
3) Podman Desktop is still running and does not disappear from the app tray

I have include a QuickTime movie to show the behavior

https://user-images.githubusercontent.com/104593998/193668952-cdadda91-424e-404a-b752-48311b62ba7b.mov

**Comment by benoitf** [comment]
Hello, could you try File/Quit or right click on the tray and exit ?

**Comment by eric-peterson-usps** [comment]
@benoitf both of those worked but shouldn't Quit Podman Desktop also do the same thing?

**Comment by benoitf** [comment]
@eric-peterson-usps you're correct on the issue, just wanted to check workarounds.

**Comment by benoitf** [comment]
Fixed by https://github.com/containers/podman-desktop/pull/671

**Comment by crahan** [comment]
I don't want to open a new issue yet before first asking here, but in the most recent stable and latest nightly/test builds on macOS 12.6 I'm unable to quit the application at all. So far, I've tried:

- Podman Desktop menubar entry -> Quit Podman Desktop
- Menubar icon -> Quit
- Dock icon right-click menu -> Quit

And while they all close the Podman Desktop application Window, none of those options closes the application itself. The only way I'm able to close the app (and remove the dock and menu bar entries) is by using Force Quit on the dock icon.

**Comment by slemeur** [comment]
Hum... Sorry you are facing this issue. I can't reproduce it, either with the latest release (0.9.1) or the latest nightly. (and I'm also on 12.6)
All the option you mentioned, they are all properly exiting the application (the Podman Desktop process does not run anymore). 
What is the status of your "exit on close" option? (in settings > preferences)
<img width="1162" alt="Capture d’écran 2022-11-08 à 21 17 18" src="https://user-images.githubusercontent.com/1636769/200666473-73026b22-d938-4027-bcc3-3088ac6a2b33.png">
tings)

**Comment by crahan** [comment]
**Update**: a second reboot appears to have resolved the issue. Everything now works as it should:
- Quit options in all 3 locations
- Window close button (as configured in the preferences)

My apologies for wasting your time with this. Your prompt response was much appreciated!

~Thanks for the quick response! I did some additional testing by deleting both Podman and Podman Desktop (and any associated configuration files) and completely starting from scratch. After installing both Podman and Podman Desktop again, prior to using Podman Desktop to initialize a Podman machine, all the quit options work as expected. The preference to quit when using the close button on the Podman Desktop window works as well.~

~However, initializing Podman (using the Toggle in Podman Desktop) remains stuck on "Initializing... Please Wait...". When checking in the terminal with `podman machine list`, the required podman-machine-default instance has been created and is up and running.~

<img width="1236" alt="Screen Shot 2022-11-08 at 22 19 00" src="https://user-images.githubusercontent.com/172588/200677618-105a9f45-9db0-4ca3-987d-3923469ed075.png">

~From that point onward the quit issue is present. I need to force quit Podman Desktop to break out of the stuck initialization process and after a full system reboot, the Podman Desktop application quit issue remains present.~
