### ISSUE TITLE
Podman Onboarding Workflow is missing a restart action notification

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5128]
### Bug description

I was going through the podman onboarding on Windows on a fresh machine. I have a couple of things to report here:
* Running the `Check Requirements again` button does not reflect actual state - already [reporter](https://github.com/containers/podman-desktop/issues/4597) - one needs to leave the page to get the new state to be taken into account during check
* Install WSL2 button should be hidden after once called.
* Notification about the required restart is totally missing after "Install WSL2" action takes place and eventually shows errors
* Links to documentation/web are all the same as a text - thus not really visible to the user

![WindowsOnboardingRequirementsCheck_no_restart](https://github.com/containers/podman-desktop/assets/19164299/3383efd9-d9f7-43d8-a776-abc570ac78f9)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

```shell
Powershell wsl error: 
wsl --list
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT

Dev Console error in podman desktop:
main ↪️ [podman] Command execution failed with exit code 4294967295: Command execution failed with exit code 4294967295
    at ChildProcess.<anonymous> (C:\Users\podmanqe\AppData\Local\Temp\2Z5OVLppFIeaUmxawzQETyKydr7\resources\app.asar\packages\main\dist\index.cjs:345:13058)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
console.<computed>	@	VM5:2
(anonymous)	@	VM5:2
emit	@	VM4 sandbox_bundle:2
onMessage	@	VM4 sandbox_bundle:2
VM5:2 main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 83.35259999707341ms
```

**Comment by lstocchi** [comment]
Last point should have been fixed by https://github.com/containers/podman-desktop/pull/5108

**Comment by odockal** [comment]
@lstocchi Confirming. Links are ok now again. thx.

**Comment by lstocchi** [comment]
@odockal do you remember what you meant for the third point? Are you referring to the dashboard notification?

1. I have the notifications in the dashboard. 
2. I click on set up. 
3. The check fails bc i don't have WSL installed. 
4. Click on install. 
5. Make it fail.
6. Go back to the dashboard.
7. The notification is there.

**Comment by lstocchi** [comment]
So i checked the discussion I had with @odockal privately and the third point was the same as #5270 that has been fixed. Closing this then.

**Comment by lstocchi** [comment]
The PR that resolved this issue is https://github.com/containers/podman-desktop/pull/6173
