### ISSUE TITLE
pod actions on containers view

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman-desktop#513]
### Is your enhancement related to a problem? Please describe

no

### Describe the solution you'd like

in pods view we already have per-pod actions (a single button to start all containers in a pod)

![Screenshot from 2022-10-04 11-48-20](https://user-images.githubusercontent.com/1312683/193776645-3409a071-5ef2-4462-b9df-197fca35f19c.png)

I hope if we have it on container view where I can start the entire pod

![Screenshot from 2022-10-04 11-48-10](https://user-images.githubusercontent.com/1312683/193776696-46020537-cfa8-4b24-a87b-c87a3e6a5263.png)

```
podman pod start mypod
```

**Comment by benoitf** [comment]
Looks like a nice improvement
