### ISSUE TITLE
Error creating symlink

### ISSUE THREAD

**Issue by mbledkowski** [containers/podman-desktop#5135]
### Bug description

When I run Podman Desktop from Flatpak, I get the following error:
```
Error creating symlink: Command execution failed with exit code 1: Command execution failed with exit code 1
```

### Operating system

Fedora Workspace 39

### Installation Method

Flathub (Linux)

### Version

1.5.0

### Steps to reproduce

1. Open Podman Desktop
2. Click "Docker Compatibility"
3. "Enable"
4. "Yes"
5. An error
![image](https://github.com/containers/podman-desktop/assets/23295125/ffba0f47-c6e8-4ed1-ac9c-734e0e9f005d)

**Comment by benoitf** [comment]
I think the sandboxes environment makes some extensions failing as they execute code on the sandboxed environment.

you may use the 'binary' (not the flatpak version) as a workaround
https://github.com/containers/podman-desktop/releases/download/v1.5.3/podman-desktop-1.5.3.tar.gz

**Comment by ColdTeapot273K** [comment]
I experience the same problem with binary v1.6.4 (also on Fedora 39)

On clean reboot, toggling compatibility option in settings reports configuring symlinks is successful, but compatibility remains inactive and the option remains toggled off. 

Consequtive attempts at toggling it on produce the same error as OP.

I've run the symlink commands myself, but podman-desktop still says 
`⚠ Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.`

**Comment by pchmykh** [comment]
I have same issue, but, if I'm reinstalling podman desktop, software can do it, 
`Symlink created successfully. The Podman socket is now available at /var/run/docker.sock.`
But podman is still shows 
`⚠ Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.`

**Comment by Tazoeur** [comment]
Same here, from ubuntu22.04

**Comment by Admiralfeb** [comment]
I attempted to use both flatpak and binary and neither succeeds.

Pop_OS 22.04

Tried both of them from the terminal and no extra logging was provided there.

**Comment by fabiobraganet** [comment]
Same here, from ubuntu 23.10
![Captura de tela de 2024-01-26 08-21-28](https://github.com/containers/podman-desktop/assets/35783257/e04daab7-8b2a-4550-b3f9-1c01a0240d84)

**Comment by joezhouchenye** [comment]
Maybe this is for podman to completely replace docker? If docker is installed, this problem is normal since docker is using this socket.

**Comment by jpdias** [comment]
Having the same issue on Manjaro without docker installed.

**Comment by benoitf** [comment]
closed in favor of https://github.com/containers/podman-desktop/issues/5789

**Comment by Malix-Labs** [comment]
@benoitf:
> in favor of #5789

#5789 is a mitigation, that issue allong with #1928 are still needed, but justified to be [closed as not planned](https://github.com/containers/podman-desktop/issues/1928#event-11738315402) due to them being unfixable on your end
