### ISSUE TITLE
markdown button with href is not rendered properly

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5136]
### Bug description

reported on discord by @jeffmaury 

![image](https://github.com/containers/podman-desktop/assets/436777/f58fc0c0-6451-4036-bbd1-f7604afe3ba5)

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Additional context

looks like a regression from https://discord.com/channels/852634929845239818/1151903904804634744/1181695413800144946

**Comment by jeffmaury** [comment]
Duplicates of #5137
