### ISSUE TITLE
Start a pod from multiple kubernetes manifest file

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#514]
### Is your feature request related to a problem? Please describe

Sometime a developer can have multiple kubernetes manifest files that he/she would like to start all together. 

### Describe the solution you'd like

As a developer, I'd like that Podman Desktop provides me the ability to select multiple yaml files to be started together. 

### Additional context

As an example, this repository, where we have individual yaml for each kubernetes objects: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/guestbook 

There is also an All-in-one: 
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/guestbook/all-in-one

**Comment by mairin** [comment]
This is something that would help with the ChRIS project, right now cat-ing together the yaml files into one to run with Podman Desktop:

https://github.com/FNNDSC/miniChRIS-k8s/tree/main/podman/kube

Also note they have to be listed in a specific ordering bc of dependencies... see the 00-* => 99-* naming scheme (ordering not an issue with k8s but is an issue if running on podman)
