### ISSUE TITLE
extensions should be able to register web views

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5140]
### Is your enhancement related to a problem? Please describe

A webview will provide a dedicated UI (like Docker Desktop extensions) so you'll get a full right page UI

### Describe the solution you'd like

add methods

```ts
export function createWebviewPanel(viewType: string, title: string): WebviewPanel;
```

```ts
interface WebviewPanel {
    readonly viewType: string;
    title: string;
    readonly webview: Webview;
}
```

```ts
interface Webview {
     html: string;
     postMessage(message: unknown): Promise<boolean>;
     readonly onDidReceiveMessage: Event<unknown>;
}
```

depends on:
 - [x] https://github.com/containers/podman-desktop/issues/5359

**Comment by axel7083** [comment]
To follow up, here is the list of things that we noticed

- Connection is lost between the front and backend of the extension if we leave the webview and come back
- States is lost, everytime the webview is open it is reloaded and loses the state (E.g. current page)
> We might want to be able to configure this aspect, as keeping all the extension loaded in background would be expensive (?)

**Comment by benoitf** [comment]
I've checked and with tinro Router, component is destroyed when it's not displayed anymore, so to get it back to the location where we are we'll need to rely on the state object (for now it is not restored as you pointed it out)

**Comment by benoitf** [comment]
implemented
