### ISSUE TITLE
kubectl-cli versions shoud be ordered according to SemVer

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5149]
### Is your enhancement related to a problem? Please describe

When user chooses to select kubectl-cli version, the available versions are ordered according to the release date, should be ordered based on the version 

### Describe the solution you'd like

Add the ordering criteria when retrieving the releases

**Comment by jeffmaury** [comment]
Nice to have

**Comment by dgolovin** [comment]
Resolved in https://github.com/podman-desktop/podman-desktop/pull/9403.
