### ISSUE TITLE
Success icon displayed after podman machine restart failure

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5150]
### Bug description

When restarting a podman machine with the tasks area open, the operation is shown as succesfull even after it fails later in the execution. This is only shown for this operation afaik and is corrected once the tasks pop-up is reopened.

![image](https://github.com/containers/podman-desktop/assets/75624842/29a0d313-ceac-4088-a9d6-16f67aff1d6d)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. open resources page
2. create a podman machine
3. open its details
4. open tasks bar on the bottom right
5. click the restart button
6. the task shown as succesfull even after it fails

**Comment by slemeur** [comment]
Is it duplicated from #5129 ?
