### ISSUE TITLE
HV_DENIED error when trying to run Podman/Podman machine

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#5152]
### Bug description

When trying to run Podman through Dashboard or start a Podman machine through settings, output throws HV_DENIED error code 125. Podman version 4.8.1

### Operating system

macOS 13 Intel x86_64

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Download and install new development Podman Desktop version
- Install Podman through Dashboard
- Try run and initialize or create a new machine and run through settings

### Relevant log output

```shell
Machine log output:
Starting machine "podman-machine-default"

Waiting for VM ...

Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED


Starting machine "podman-machine-default"25

Waiting for VM ...

Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED


Starting machine "podman-machine-default"25

Waiting for VM ...

Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED


Command execution failed with exit code 125

Developer console output:
VM60:2 main ↪️ [podman] Command execution failed with exit code 125: Command execution failed with exit code 125
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:345:13058)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
console.<computed> @ VM60:2
(anonymous) @ VM60:2
emit @ VM59 sandbox_bundle:2
onMessage @ VM59 sandbox_bundle:2
VM60:2 main ↪️ Aborting reconnect due to error as connection is now stopped
PreferencesConnectionActions.svelte:47 Error: Command execution failed with exit code 125
a @ PreferencesConnectionActions.svelte:47
await in a (async)
_ @ PreferencesConnectionActions.svelte:149
(anonymous) @ LoadingIconButton.svelte:44
VM60:2 main ↪️ Aborting reconnect due to error as connection is now stopped
```

**Comment by slemeur** [comment]
Is this reproducible with Podman 4.8.0 ?

**Comment by odockal** [comment]
Reproduced with 4.8.2-dev.

**Comment by odockal** [comment]
Able to reproduce with 4.8.0 installed via pkg. 
I have also find a problem or a way to make it work. `brew uninstall qemu`.

**Comment by odockal** [comment]
I installed qemu because at some point the podman complains that x86_qemu_system is missing. So I kind puzzled about this... now it works if I uninstall qemu from brew.

**Comment by odockal** [comment]
And with 4.8.2-dev it complains about `qemu-system-x86_64` executable not on a path. Which it did not with 4.8.1 podman.

**Comment by jeffmaury** [comment]
> And with 4.8.2-dev it complains about `qemu-system-x86_64` executable not on a path. Which it did not with 4.8.1 podman.

Did you install it on top of 4.8.1 ?

**Comment by benoitf** [comment]
you could or I could compile a podman for an 'installer' version ( you need to add some flags to specify the working directory). Here I compiled a version assuming you have all others binaries on your system

**Comment by odockal** [comment]
My testing scenarios:
1. `brew install podman` (4.8.1) also installs qemu. Then I try to init and start machine which fails:

![Screenshot_20231208_181637](https://github.com/containers/podman-desktop/assets/19164299/bc3bf0d7-3665-416e-bcdc-065adb0861da)

So I uninstall podman and qemu.

3. I install podman 4.8.1 from pkg (available via github releases) - installer like, I have no qemu available. Then I do machine init and start again (works):

![Screenshot_20231208_182433](https://github.com/containers/podman-desktop/assets/19164299/833a4300-0a07-4c62-8ef6-8472eb767508)

4. With working podman 4.8.1 from pkg, I try to create a machine with a custom image ([fedoracoreos](https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/39.20231205.20.0/x86_64/fedora-coreos-39.20231205.20.0-qemu.x86_64.qcow2.xz)) - works

5. Now I replace podman 4.8.1 with a 4.8.2-dev version:
```
1. download custom podman-dev
2. sudo cp podman-dev /opt/podman/bin/
3. sudo mv /opt/podman/bin/podman /opt/podman/bin/podman_backup
4. sudo mv /opt/podman/podman_dev /opt/podman/bin/podman
5. sudo chmod +x /opt/podman/bin/podman
6. sudo xattr -dr com.apple.quarantine /opt/podman/bin/podman
7.. verify with podman info - returns 4.8.2-dev
```
Result is that is fails:

![Screenshot_20231208_183915](https://github.com/containers/podman-desktop/assets/19164299/34922773-d541-4d93-b200-1e894c8e4c53)

6. tries to install qemu: `brew install qemu` + some binary copying in proper place

![Screenshot_20231208_184433](https://github.com/containers/podman-desktop/assets/19164299/3dd2d94a-976e-42f2-91ff-bd8b3cc1fb48)

Still does not work. @benoitf  (copying these files did not help, see the pic.)

**Comment by benoitf** [comment]
you qemu brew is broken

brew update
brew upgrade qemu

**Comment by benoitf** [comment]
I don't see the version of qemu on your system but I assume it's an old one ( the one which is broken)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman/issues/19708 to me

**Comment by benoitf** [comment]
you can restart a machine as qemu path is stored in the podman machine configuration

**Comment by benoitf** [comment]
while when creating it's where it's searching for qemu

**Comment by odockal** [comment]
`brew update -> Already up-to-date`
`brew qemu upgrade` -> latest already installed 8.1.3_2

**Comment by odockal** [comment]
The suspected root cause lies in a different qemu versions used when working podman environment.

how this can happen: This scenario works with environment (gvproxy, qemu installed with podman) installed by podman installer and then replaced by a locally built podman binary (for testing purposes) that expects qemu on path instead of a path provided usually by an installer (`/opt/podman/qemu/bin`). 

This way we can basically have two different qemu binaries available which, I believe, creates such problem. This probably still needs to be verified. In case of such error as described here (`HV_DENIED`) I would try to start looking at qemu versions available on the system.

**Comment by benoitf** [comment]
with 4.8.2 the installer will pickup the qemu provided by /opt/podman (the installer)

**Comment by odockal** [comment]
This one upstream looks related: At least with a nature in common. https://github.com/containers/podman/issues/20808

**Comment by odockal** [comment]
I am tending to close this issue. the root cause seems identified and explained. I do not feel like we can do anything podman desktop side. If this happens again we can reopen or create new one.
