### ISSUE TITLE
Dev sandbox installation succeeds, displays error and is not usable before app restart

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5154]
### Bug description

After uninstalling developer sandbox extension and trying to install it again from [here](ghcr.io/redhat-developer/podman-desktop-sandbox-ext:latest), the installation seemingly succeeds:

![image](https://github.com/containers/podman-desktop/assets/75624842/e198b6bb-deaf-473c-9c96-aa656493c73e)

But the extension is displayed with state FAILED and without the option to disable/enable or delete.

Opening the extension in settings->extensions displays this error message:

![image](https://github.com/containers/podman-desktop/assets/75624842/53008872-c523-4b96-ba2b-f3cc71d719e6)

The extension is not displayed in resources or dashboard.

After restart the extension appears to function normally:

![image](https://github.com/containers/podman-desktop/assets/75624842/c8dd7bc1-01a1-45ab-bac4-fb9332b8c623)

![image](https://github.com/containers/podman-desktop/assets/75624842/822d6173-a49c-4fa7-84b4-631b8ca5fd8e)

![image](https://github.com/containers/podman-desktop/assets/75624842/6baad420-b09e-4ea6-a7f5-27fecdd5acc6)

Tested on pd 1.6.0 with podman 4.8.1.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

  1. Install external Dev Sandbox extension (via OCI image or using download button)
  2. Verify is was installed
  3. Stop the extension
  4. Remove the extension
  5. Verify it was removed
  6. Install extension again
  7. Check the extension status
  8. Assert: everything is alright, ext. should be running, no error
  9. Actual result: Error, command already exists.

### Relevant log output

```shell
Extension error: command 'sandbox.open.login.url' already exists
Stack trace
Error: command 'sandbox.open.login.url' already exists at wf.registerCommand (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:14:42009) at Object.registerCommand (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:49545) at activate (C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\dist\extension.js:11801:36) at MK.activateExtension (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:57226) at MK.loadExtension (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:49296) at C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:45770 at Array.map (<anonymous>) at MK.loadExtensions (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:45758) at lme.installFromImage (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:309:45)
```

**Comment by odockal** [comment]
I would update the steps to reproduce. This also mean that I have encountered the same.

1. Install external Dev Sandbox extension (via OCI image or using download button)
2. Verify is was installed
3. Stop the extension
4. Remove the extension
5. Verify it was removed
6. Install extension again
7. Check the extension status
8. Assert: everything is alright, ext. should be running, no error
Actual result: Error, command already exists.

**Comment by deboer-tim** [comment]
Bug should be moved to extension repo: https://github.com/deboer-tim/podman-desktop-sandbox-ext

**Comment by odockal** [comment]
It seems to me to be a generic problem on podman desktop side: https://github.com/containers/podman-desktop/issues/4593

**Comment by odockal** [comment]
We need to make sure in the extension api that extensino does not try to add existing commands. Could require fix in particular repos, though... imho

**Comment by dgolovin** [comment]
I am sure we have not released any new versions, so it should work.

I will take a look anyway.

**Comment by dgolovin** [comment]
Cannot replicate on Windows 10 Pro.

**Comment by rostalan** [comment]
I was able to replicate it on fedora 38, however if I restart the app after the initial removal of dev sandbox, the installation succeeds without error.

**Comment by slemeur** [comment]
I can reproduce it on Mac Intel.

<img width="2026" alt="Screenshot 2023-12-13 at 11 42 25" src="https://github.com/containers/podman-desktop/assets/1636769/1ace7e1f-2b78-4d5c-ad30-d39b917bb77a">

1. Install
2. Disable
3. Remove
4. Re-install

**Comment by benoitf** [comment]
it does not block release as extension can be updated on its own

**Comment by slemeur** [comment]
Yess Agreed

**Comment by nichjones1** [comment]
@odockal is this still occurring with the latest Podman release?

**Comment by odockal** [comment]
@rostalan Can you please try this?

**Comment by rostalan** [comment]
I was able to replicate this on Fedora 39 with PD 1.8.0 with podman 5.0,
![image](https://github.com/containers/podman-desktop/assets/75624842/4a10eecf-e013-4445-b216-e20fd79662d6)
however, the remove button is working now.
![image](https://github.com/containers/podman-desktop/assets/75624842/6c975271-f24d-44aa-abd3-8306bf9c7a4f)
