### ISSUE TITLE
New Podman Machine Create Form Autostart enabled option not working

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5171]
### Bug description

If I try to create a new machine with autostart enabled (which is default) it is not respected and machine created is off.

![podman_machine_autostart_not_working](https://github.com/containers/podman-desktop/assets/19164299/ac13924e-1cde-4c70-a0a2-22051da4d66c)

Logs:
[podman_machine_autostart_error.log](https://github.com/containers/podman-desktop/files/13598824/podman_machine_autostart_error.log)

### Operating system

Windows 10, Mac 13 Intel

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Just create a new machine with all default. Check that after creation it is started/Running as expected.

### Additional context

There seems to be a workaround, if you manually toggle off and on again the autostart (Start the machine now) button.

**Comment by odockal** [comment]
@jeffmaury @benoitf  I would also like to emphasize that the same applies for the rootfull vs. rootless state of the button. It seems that not only `start now` but also `Machine with root privileges` button is affected with this.

**Comment by odockal** [comment]
And it is also affecting other toggle buttons that are in Podman desktop. At least also a kind. So I expect the problem will be everywhere.

**Comment by jeffmaury** [comment]
> And it is also affecting other toggle buttons that are in Podman desktop. At least also a kind. So I expect the problem will be everywhere.

Yes the patch will affect every connection creation: Podman, Kind, Minikube,....

**Comment by odockal** [comment]
@jeffmaury It works in 1.6.0 tagged bits. thanks!
