### ISSUE TITLE
Error: No running provider for the matching container when Podman machine with `--user-mode-networking` flag enabled

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5186]
### Bug description

I have podman machine created with `--user-mode-networking` enabled but I cannot pull an image from Podman Desktop nor from the cli.

![Pulling_image_error_usermode_networking](https://github.com/containers/podman-desktop/assets/19164299/f2952517-ce06-4e19-94c2-5ca38c3c7e8d)

CLI:
```
podman pull alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Error: initializing source docker://alpine:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
```

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Build podman cli 4.8.2 with 4.8.x branch
2. Add the executable on the path
3. Install PD 1.6.0-next and start it up
4. Assert: Podman 4.8.2-dev is detected in PD
5. [Prepare a custom image for fedora base image](https://github.com/odockal/podman-desktop-qe/blob/main/docs/podman/podman-nightly-windows.md#creating-a-custom-podman-wsl-fedora-image-with-newer-podman-than-available-on-the-site) to be used in VM, name it: `podman-wsl-fedora-4.8.1-fc38.tar`
6. Create a new machine with flag `User Mode Networking`, rootfull, and use imagepath: `podman-wsl-fedora-4.8.1-fc38.tar`
7. Assert: Machine is created
8. Assert: Machine can be started
9. Pull an image, ie: `alpine`
10. Assert: Image can be pulled and container created
Actual result: Error when pulling an image: `Error while pulling image from usermode-networking: no running provider for the matching container`

Log says:
```
main ↪️ [podman]  Can't get machine usermode-networking resource usage error Error: no running provider for the matching container
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

### Relevant log output

```shell
podman machine ls
NAME                  VM TYPE     CREATED         LAST UP            CPUS        MEMORY      DISK SIZE
usermode-networking*  wsl         15 minutes ago  Currently running  8           660.5MiB    972MiB
rootfull              wsl         17 minutes ago  Never              0           0B          951MiB
rootless              wsl         16 minutes ago  Never              0           0B          972MiB

podman system connection ls
Name                      URI                                                          Identity                                  Default
rootfull                  ssh://user@127.0.0.1:57888/run/user/1000/podman/podman.sock  C:\Users\Ondrej\.ssh\rootfull             false
rootfull-root             ssh://root@127.0.0.1:57888/run/podman/podman.sock            C:\Users\Ondrej\.ssh\rootfull             false
rootless                  ssh://user@127.0.0.1:57940/run/user/1000/podman/podman.sock  C:\Users\Ondrej\.ssh\rootless             false
rootless-root             ssh://root@127.0.0.1:57940/run/podman/podman.sock            C:\Users\Ondrej\.ssh\rootless             false
usermode-networking       ssh://user@127.0.0.1:57970/run/user/1000/podman/podman.sock  C:\Users\Ondrej\.ssh\usermode-networking  true
usermode-networking-root  ssh://root@127.0.0.1:57970/run/podman/podman.sock            C:\Users\Ondrej\.ssh\usermode-networking  false

podman version
Client:       Podman Engine
Version:      4.8.2-dev
API Version:  4.8.2-dev
Go Version:   go1.21.4
Git Commit:   db3703040adcf773eb4cc7a3cc3a27af945a6e5d
Built:        Thu Dec  7 16:58:02 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.8.1
API Version:  4.8.1
Go Version:   go1.20.11
Built:        Tue Dec  5 13:02:28 2023
OS/Arch:      linux/amd64

wsl --list
Windows Subsystem for Linux Distributions:
podman-rootfull (Default)
podman-net-usermode
podman-usermode-networking
podman-rootless
```

### Additional context

Podman 4.8.2-dev executable.
Base fedora image - custom with podman 4.8.1 built locally and used for machine creation.
Windows 10 Professional 22H2.

**Comment by jeffmaury** [comment]
I can't reproduce on my Win11 machine, do you have the same error with the default image ?

**Comment by odockal** [comment]
Looking at it with defaults. In actual state, nothing works for any of the machines I have, although it throws different errors. Cleaning up the env. Thanks for info!

**Comment by odockal** [comment]
the problem laid in the fact, that I wiped out all of the podman installation and simply put podman-dev.exe on the path. so other binaries like wsin-sshproxy.exe, etc were missing and system misbehaving. 

Closing as explained. Solution was to install older version and replace podman binary with dev version.

**Comment by prafdin** [comment]
Faced with the same problem while migrated from Docker Desktop to Podman Desktop. 
The root cause was that I have DOCKER_HOST env variable with "0.0.0.0:2375" value and it somehow breaks Podman Desktop. 
After I updated DOCKER_HOST with 'npipe:////./pipe/podman-machine-default' value and reinstalled Podman Desktop it started working well.
