### ISSUE TITLE
Edit yaml of a defined Pod

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#519]
## Description

As a developer, when I'm building the definition of my kubernetes deployment, I'd like the ability to quickly edit the yaml, so I can adjust some settings/options and see the changes. 
I should be able to restart the pod, or test my changes into a new pod.

**Comment by benoitf** [comment]
The original kubernetes deployment is not kept by Podman
so what is the content that you'll edit, and where do you will edit that ?
is it a new section (in addition to containers, volumes, etc) where you create K8s deployment ?
Also we don't have the mapping from containers to the kubernetes yaml file or a way to get the pod from a yaml

**Comment by benoitf** [comment]
Also what is a "manifest yaml" ?

**Comment by slemeur** [comment]
Closing in favor of: #5937
