### ISSUE TITLE
extension installation checks architecture but no os

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5190]
### Is your enhancement related to a problem? Please describe

When an extension contains a binary it may be packaged using platform ie os and architecture.
The installation is only done using architecture and not os

See https://github.com/containers/podman-desktop/blob/ae2c861f014512522602e6739d45a4426ea7abde/packages/main/src/plugin/image-registry.ts#L630

### Describe the solution you'd like

The os should be taken into account

**Comment by feloy** [comment]
Do we want to be strict when checking the manifest's os? Or do want to get a default one, to not break previous manifests which were working?

**Comment by jeffmaury** [comment]
We should just include the os in the selection process as there is a default one if the match is not found. Maybe @benoitf may help
