### ISSUE TITLE
Add a container to a Pod

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#520]
### Is your feature request related to a problem? Please describe

As a developer, I could be iterating on building the definition of my pod. At some point, I'd like to add a new container to my pod.

### Describe the solution you'd like

- When I'm exploring details of a Pod, I'd like the ability to pick and choose from one of the containers (or images) that I have and add it to my Pod. 
  - It would either restart the pod, or propose me to start a new fresh pod
- On the list of container (and maybe on the details of a container), I'd like the action to "Add to a Pod"

**Comment by benoitf** [comment]
Adding a container to a pod is at creation time.

We can include only containers so if you select an image it means, you'll see the wizard to create a container from a given image 

What is the flow of selecting an existing container to be included in a pod ?
- we save current state of one container to recreate it within the pod 
- should we delete the current container

**Comment by slemeur** [comment]
> Adding a container to a pod is at creation time.

In this case, it means that we'll need to create a new pod: either the user should have the option to "restart" the pod (it will delete the pod and create a new one), or to create another new pod and keep the current one running.

> We can include only containers so if you select an image it means, you'll see the wizard to create a container from a given image

OK, I think we'll need to look at how to handle the flow (cc @mairin) from a UX stand point. But that's not blocking progress on this at the moment.

> What is the flow of selecting an existing container to be included in a pod ?
> - we save current state of one container to recreate it within the pod
> - should we delete the current container

Initially, we should start with: restarting the container in the new pod and let the user choose to delete the current container or not.

**Comment by benoitf** [comment]
> Adding a container to a pod is at creation time.

I meant 'at creation time of a container' so we don't need to create a new pod
