### ISSUE TITLE
Kubectl not showing correctly in CLI Tools

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5216]
### Bug description

kubectl is installed (an older version), but the UI on the CLI Tools page looks odd and doesn't show me the version #.

<img width="569" alt="Screenshot 2023-12-11 at 10 54 16 AM" src="https://github.com/containers/podman-desktop/assets/19958075/f1c6a4ca-055e-4384-937b-4f5ed862450f">

Installed (`kubectl version --short`):
```
Client Version: v1.24.1
Kustomize Version: v4.5.7
```

### Operating system

macOS 14.1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Unknown.

**Comment by afbjorklund** [comment]
This is the error I get in the logs: `[kubectl-cli-tool] Error getting kubectl version: Error: Failed to execute command: spawn /home/anders/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli-tool/bin/kubectl ENOENT`

Since I had a `/usr/local/bin/kubectl`, it never bothered to download another.

If I remove it from the path, then it "onboards" and shows the kubectl version.

**Comment by slemeur** [comment]
On my side, the kubectl tile is not even displayed, while minikube extension is installed and kubectl configured

<img width="1854" alt="Screenshot 2023-12-12 at 14 36 38" src="https://github.com/containers/podman-desktop/assets/1636769/cd4b2d5f-4d45-4a54-b392-3d1e47a28056">

**Comment by benoitf** [comment]
@slemeur what is the path to your kubectl CLI tool on your computer ?

in the extension page of kubectl is there some errors for this extension ?

**Comment by deboer-tim** [comment]
My kubectl is in /usr/local/bin/kubectl, and I found the following in the log:
`main ↪️ [kubectl-cli-tool] Error getting kubectl version: Error: Failed to execute command: spawn /Users/deboer/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli-tool/bin/kubectl ENOENT`

Seems like separate problems for slemeur (not even visible?) vs afbjorklund and I (fails detecting version because it is assuming the local copy/path).

**Comment by jeffmaury** [comment]
As the kubetl-cli is based on the compose one, I think this would also affect the compose extension

**Comment by deboer-tim** [comment]
> As the kubetl-cli is based on the compose one, I think this would also affect the compose extension

I took a quick look at the compose code and agree, so I tested and believe I've confirmed the failure there too. Should be a similar fix but I'm assuming we'll want to track as a separate issue so I've opened one: #5250.
