### ISSUE TITLE
Socket paths overflowing UI

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5218]
### Bug description

PR #5098 added socket paths to the UI, but mine aren't short. With no break they are very ugly in the UI and both overlapping and going outside of the natural space for providers.

<img width="759" alt="Screenshot 2023-12-11 at 11 17 00 AM" src="https://github.com/containers/podman-desktop/assets/19958075/c96d2a55-8a48-4087-a799-3ce395f218f5">

We need to either revert #5098 or take a step to crop/make these fit within the UI.

### Operating system

macOS 14.1

### Installation Method

None

### Version

next (development version)

**Comment by afbjorklund** [comment]
The original suggestion was to abbreviate them (either "..." or basename), but maybe they should just be removed?

I wanted to show the type, the path was just to make it similar to the Kubernetes endpoint.

But now that Kubernetes has the full context, the apiserver* is mostly noise also for those...

Could be something that is **only** available in the Details, it used to be a somewhat useful URL but now it's just a path.

----

\* normally you can't really **do** anything with the cluster anyway, without having the rest of the authinfo

* #4917

Similarly, trying to do something with the socket path risks missing to add `unix:` (or even `unix://`, for Docker)

So they can both go hide in the Details

**Comment by afbjorklund** [comment]
My interface is longer in the _other_ direction, i.e. it is more vertical than horizontal. (had to zoom out, just to list all of it)

![podman-desktop-resources-list](https://github.com/containers/podman-desktop/assets/10364051/91a76640-a928-4b89-a6c1-3587b69b6956)

Not sure why kubectl and compose want to live under Resources, and not allowed to test Podman Machine (on Linux).
