### ISSUE TITLE
Transition from Pods to Kubernetes

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#522]
### Epic domain

Along with the effort on #515 which enables a developer to transition from containers to pods, we would like to facilitate the transition from pods to kubernetes. 

As a developer, who has been experimenting locally with Podman the definition of my Pods (and potentially other kubernetes objects supported by Podman), I'd like the ability to easily test that onto a kubernetes environment. 

In this context, we would like to explore the following experiences:
- [x] #523
- [x] #521

**Comment by benoitf** [comment]
all tasks are completed
