### ISSUE TITLE
Popup menus not appearing in Images and Volumes lists

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5220]
### Bug description

The new table component sets overflow-hidden and max-width on each cell to avoid long content (e.g. >50 character volume or image names) from overlapping other columns (or as in the past, tables that are ridiculously wide). However, this means that popup menus or tooltips can't appear outside of the cell either.

### Operating system

macOS 14.1

### Installation Method

None

### Version

next (development version)

**Comment by odockal** [comment]
I am sure if this is already taken into account, @slemeur also reported that in details of the image, if one presses the kebab menu, no context menu is shown and `push to ...` action is perform instead.

**Comment by deboer-tim** [comment]
Yes, this is that issue (kebab = popup = context menu).

**Comment by odockal** [comment]
The issue I was talking about was reported here: https://github.com/containers/podman-desktop/issues/4763

**Comment by deboer-tim** [comment]
As per chat, sorry @odockal, I misread the question. This issue is only for context menu not appearing in the main list page, any problems with actions failing/no icons are separate.

**Comment by odockal** [comment]
yes. Thx for clarification.
