### ISSUE TITLE
podman load does not refresh images interface

### ISSUE THREAD

**Issue by TimothyNilsen** [containers/podman-desktop#5221]
### Bug description

When using podman load < image.tar or podman load -i image.tar the images view on podman desktop does not update.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

Save an image to a tar file: podman save -o test.tar
Remove the image: podman image rm test
Observe that the image is gone from Podman Desktop
Load the image: podman load < test.tar

UI is not updated to reflect image

### Additional context

'podman pull' and 'podman image rm' both update the image view properly 

Tried on multiple machines. 
All Windows 10 with latest updates. 
Combination of internet connected and not
Bug is present in 1.5.3 and 1.6.0.
I did not try any versions in between

**Comment by benoitf** [comment]
hello @TimothyNilsen thanks for the report and the test case ! I think we're missing an event to refresh the UI

**Comment by benoitf** [comment]
fix will be included in 1.6.1
