### ISSUE TITLE
Create pod button seems disabled

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5230]
### Bug description

When a pod is created the button seems disabled although we can click it

![image](https://github.com/containers/podman-desktop/assets/695993/768e8a38-73f0-4408-afaa-1e4d0a5c15b4)

### Operating system

Win11Pro

### Installation Method

None

### Version

1.6.0

**Comment by benoitf** [comment]
it looks like it's the same issue in extensions details (to disable/stop extensions)
![image](https://github.com/containers/podman-desktop/assets/436777/fb3354d3-6cbb-4408-bcc4-180859e7d4fc)

**Comment by odockal** [comment]
Not everywhere though...

**Comment by deboer-tim** [comment]
Looks like a conflict with text-white tab style, Button.svelte line 60. I am busy for next couple hours but could put up a fix this afternoon if nobody else has a chance.

**Comment by benoitf** [comment]
created PR https://github.com/containers/podman-desktop/pull/5232
