### ISSUE TITLE
Editing podman machine on Windows ended up with an Error (exit code 125)

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5233]
### Bug description

I have a running podman machine (rootfull) which is working fine. I am trying to edit the Podman Machine via edit option. I got an error.

![podman_machine_edit_error125](https://github.com/containers/podman-desktop/assets/19164299/428149b2-7a61-4023-a3db-1ea0199764ec)

Log: 
[podman_machine_edit_error.log](https://github.com/containers/podman-desktop/files/13649677/podman_machine_edit_error.log)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

1. Create a podman machine
2. Start it up
3. Pull an image
4. Go to Resources and try to edit a machine (I tried to change the CPU)
5. Assert: Machine is restarted and value adjusted.
Actual: An error

**Comment by jeffmaury** [comment]
This is caused by `podman machine set` to be NOP for WSL images and podman only generates an error message and code. We should probably support edit only for MacOS until HyperV is implemented
