### ISSUE TITLE
Developer Sandbox context cannot be deleted

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5237]
### Bug description

After installing the developer sandbox extension and creating a context, the context cannot be deleted afaik.
I tried switching context to kind/others, tried creating another sandbox context, but haven't been able to delete it.
The delete button is greyed in on both the Resources page a

![image](https://github.com/containers/podman-desktop/assets/75624842/bc19f3ab-3477-422f-918a-544edf97c225)

nd in the DS context details page.

![image](https://github.com/containers/podman-desktop/assets/75624842/51c92fc7-1a67-4253-a35c-fc7d2dab051f)

### Operating system

Fedora 38

### Installation Method

Other

### Version

1.6.0

### Steps to reproduce

1. Install Developer sandbox
2. Click Create New
3.  Paste login command Developer Sandbox and copying the login command
4. Click Create
5. The context is created, can be switched to
6. Assert: the context can be deleted
7. Actual: context cannot be deleted on either the resources page and the context page

**Comment by benoitf** [comment]
issues for this extension should go in https://github.com/redhat-developer/podman-desktop-sandbox-ext

and I think it's a dup of https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/66

**Comment by rostalan** [comment]
duplicate of https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/66
