### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by trymeouteh** [containers/podman-desktop#524]
### Is your feature request related to a problem? Please describe

A portable app for of podman and podman desktop.

### Describe the solution you'd like

Please package podman and podman desktop into an appimage. This way Linux users of all distros can have a portable versions of podman and podman desktop.

**Comment by benoitf** [comment]
Hi @trymeouteh there is a flatpak version. You don't want to use flatpak ?

**Comment by tazihad** [comment]
@benoitf will this be released in flathub?

**Comment by trymeouteh** [comment]
I would prefer both a flatpak and appimage.

Flatpak for installing it on any Linux distros and an AppImage to have a portable version of podman and podman desktop on any Linux distro.

**Comment by Kaffee-Junkie** [comment]
DE:
Ich unterstütze diese Idee! Ja, Appimage bitte.
EN:
I support this idea! Yes, Appimage please.

👍👍👍

**Comment by benoitf** [comment]
electron builder can generate an AppImage but I don't know if it would work or not, if podman should be part of the image or not, etc.

**Comment by RafaelLinux** [comment]
> electron builder can generate an AppImage but I don't know if it would work or not, if podman should be part of the image or not, etc.

I think including `podman` is not neccesary. After all, `podman-desktop` is a GUI, like there are AppImage programs that are GUI for `ffmpeg` and other CLI tools.

**Comment by benoitf** [comment]
closing as won't fix due to limited deman, for now flatpak/flathub is the recommended way
