### ISSUE TITLE
Podman extension fails to load on podman Desktop start with Extension error: Invalid argument not valid semver ('' received)

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5257]
### Bug description

I was having a multiple podman machines available and on of them running. I installed Kind and needed to restart due to a bug in loading up the kubeconfig. And after restart the podman desktop could not see podman machines, so I checked the extension and got into this:

![PodmanExtension_startup_error](https://github.com/containers/podman-desktop/assets/19164299/f9fe9d09-d131-4936-83c5-4604b4e17418)

I tried to enable the extension but ran into fixed issue: #4593.
I restart podman desktop, all for solved, reenabling of the podman extension did not show issue from #4593 
anymore. 

### Operating system

Windows 10

### Installation Method

None

### Version

1.6.0

**Comment by lstocchi** [comment]
>  I installed Kind and needed to restart due to a bug in loading up the kubeconfig.

What kind of error? Any way to replicate it?
I tried by making the kind creation fails, close and restart desktop, disable and enable podman extension but i don't face this error.

**Comment by odockal** [comment]
@lstocchi Happened just once. Could not reproduce again after that.
