### ISSUE TITLE
Whole Image table is refreshed (reset) every 2 seconds if there is a fresh image (with age counted in seconds)

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5263]
### Bug description

As reported on the slack, the effect of the Age being refreshed every two seconds is that scrolling is also reset and move back to the top. Also if the context menu of the image is opened, it is closed after every event change.

Happens when the image is built and the age is counted in seconds. Similar issue will happen with minutes, but the number of occurrences will get lower and lower eventually. 

https://github.com/containers/podman-desktop/assets/19164299/93a7e587-9113-4e8d-92a6-b79a03f5552b

### Operating system

Windows, Linux, Mac

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

1. Open Images table, ideally have many images available (not necessary)
2. Build an image
3. Assert: Image's age is in seconds and changes every 2 seconds
4. Scroll down
5. Assert: Scroll is not being changed
Actual result: Position of the scroll is moved back to the top
6. Alternatively, open context menu on the image (ie. kebab menu with more options/actions)
7. Assert: Context menu is opened
Actual: It closes after age is changed. (on any image row)

**Comment by slemeur** [comment]
also true on Mac OS

**Comment by benoitf** [comment]
looks like it's specific to the new table component (in containers page it's not doing the same)

**Comment by deboer-tim** [comment]
Agreed.

**Comment by lstocchi** [comment]
I was able to reproduce, giving a look if nobody started working on this

**Comment by lstocchi** [comment]
ops just saw the assignment, all yours @deboer-tim 👍

**Comment by deboer-tim** [comment]
😛. fix incoming!
