### ISSUE TITLE
Podman onboarding should be more descriptive about the requirement for a reboot

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#5270]
### Bug description

Currently the error message shown when a user tries to install WSL2 for the second time (because the UI loader just stops and the button is still active) does not point out the actual action required.

After reboot of the system, Podman onboarding passes successfully

### Operating system

Windows 10

### Installation Method

Other

### Version

1.6.0

### Steps to reproduce

* Install Podman Desktop from either the setup, or an executable binary
* Start Podman onboarding
* Install WSL -> the loader will stop and button will be enabled again
* Install WSL again -> a new section with an error will be shown

### Relevant log output

```shell
N/A
```

### Additional context

![Screenshot_20231214_202054](https://github.com/containers/podman-desktop/assets/16451875/11e20062-ab5e-47be-ac1a-deae883776b8)

**Comment by odockal** [comment]
There is also related issue: https://github.com/containers/podman-desktop/issues/4597

**Comment by lstocchi** [comment]
Just tried with https://github.com/containers/podman-desktop/pull/6173 and i guess that covers it.
After i click on install wsl, the Ui is correctly refreshed showing "you need to restart your machine". After the restart, the step is shown completed. 
Could you please give it a try with that PR whenever you have time? Thanks

**Comment by odockal** [comment]
@ScrewTSW Can you please try this one?

**Comment by ScrewTSW** [comment]
@odockal Install WSL button is now gone and instead redirects to Microsoft documentation.

After WSL was installed, the Check requirements again button still returns an error

![Podman_Desktop_BEzDAybDh5](https://github.com/containers/podman-desktop/assets/16451875/fc677be7-e796-4d09-83bf-11f292f6b91d)

**Comment by ScrewTSW** [comment]
check passes after reboot, side-effect is Ubuntu is also installed as part of `powershell wsl --install`
![explorer_XWpFqcDs2y](https://github.com/containers/podman-desktop/assets/16451875/cc495bad-1128-43d7-b1da-b5286b943878)

**Comment by ScrewTSW** [comment]
Install WSL2 button is back, but working correctly
![Podman_Desktop_BkZJ6M2f9D](https://github.com/containers/podman-desktop/assets/16451875/e5495dbd-6afe-4212-8eae-318a974ce230)

![Podman_Desktop_DNr5zN9WVM](https://github.com/containers/podman-desktop/assets/16451875/50fead5a-f707-41b9-9564-c598c99c4a54)
Verified in https://github.com/containers/podman-desktop/releases/tag/v1.8.0 , closing
