### ISSUE TITLE
unable to execute smoke tests on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5279]
### Bug description

it is failing on 5000 port number being already used when testing pods

### Operating system

macOS

### Installation Method

None

### Version

1.6.2

### Steps to reproduce

try to start a process listening on port 5000 first (on macOS it is the case)

then start the smoke tests

you should see the '5000 port already in use' issue

### Relevant log output

```shell
the process 'Control Center' of Apple is listening on that port so tests are failing
```

**Comment by odockal** [comment]
@rostalan Will take a look and adjust port mapping for the frontend pod in mac os platform.
