### ISSUE TITLE
KinD cluster max process is way too low

### ISSUE THREAD

**Issue by vietk** [containers/podman-desktop#5282]
### Bug description

In my kind cluster, when I have a lot of pods, instabilities are starting to show off.
And pods are getting killed and some pods cannot be installed anymore  ... 

On one of my JDK based pod I fall onto this error : 
> java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

Then I connected on the kind control plane and run :
> root@kind-cluster-control-plane:/# cat /sys/fs/cgroup/pids.max 
2048

So I started to kill some pods and everything was back to normal.
The kind cluster creates a lot of process and I think 2048 is a way too low and should be increased in the command that starts kind in docker desktop.

### Operating system

macOS ventural (Intelbased)

### Installation Method

Brew (macOS)

### Version

1.5.3

### Steps to reproduce

Create a kind cluster starts a lot of pods on it

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes-sigs/kind/issues/2830#issuecomment-1190546098

"Closing this issue as a user can override using containers.conf."

**Comment by vietk** [comment]
Hello 
What do you suggest that we have scripts after kind installation to update containers.conf ? 
I would prefer that we have an option in Podman Desktop to override that stuff for ourselves.

**Comment by vietk** [comment]
In order to not update containers.conf (that would affect all containers) 
The startup script should use the `--pid-limits` option
> podman run --rm -it --pids-limit 4096 ...

**Comment by afbjorklund** [comment]
> What do you suggest that we have scripts after kind installation to update containers.conf ?

Just saying that it is a known out-of-the-box issue upstream, in the kind and the podman projects...

**Comment by fabricepipart1a** [comment]
I tried to edit `/etc/containers/containers.conf` in my podman machine and then recreate my kind cluster (via UI). It did not help and I still get a kind cluster with a 2048 pid limit (check with `podman exec -it kind-cluster-control-plane cat /sys/fs/cgroup/pids.max`)

**Comment by fabricepipart1a** [comment]
I finally managed to do it. I don't know what I had missed before.
It is easy to miss to restart the podman machine after having edited the `/etc/containers/containers.conf` though

I first modified my podman machine
```
podman machine ssh
vi /ect/containers/containers.conf
```

I added the following in `/etc/containers/containers.conf`
```
[containers]
pids_limit=0
```

Now restart your podman machine
```
podman machine stop
podman machine start
```

Delete your kind cluster if you already had one
```
kind delete cluster
```

Recreate a kind cluster
```
kind create cluster --config=./kind.yaml
```

You should now be fine (it should show max and not 2048)
```
$ podman exec -it kind-cluster-control-plane cat /sys/fs/cgroup/pids.max
max
```

**Comment by fabricepipart1a** [comment]
I think I would appreciate if Podman Desktop offered either:
* the possibility to either edit the `containers.conf` of the podman machine 
* propose to edit the value (slider? checkbox to limit/not limit?) for pids_limit
* proposed a fedora podman machine that comes without that limitation (probably not very useful in local)

**Comment by benoitf** [comment]
hi,

I think using a custom ignition script should work to avoid the usage of a lot of commands `podman machine init --ignition-path ...`

Podman Desktop could expose some stuff about 'post-init' step or a way to edit machine settings, etc.

But I am wondering if it is not something for this case that should not be included by default on all machines, in the default ignition script

https://github.com/containers/podman/blob/1ce53677aafc4d51f282590a9121a10d3a583898/pkg/machine/ignition.go#L301-L307

**Comment by afbjorklund** [comment]
Seems strange that the GUI should try to work around known issues in the CLI and in the OS...

Editing configuration would be a nice feature, even if somewhat advanced (could edit the text file?)

**Comment by vietk** [comment]
> Podman Desktop could expose some stuff about 'post-init' step or a way to edit machine settings, etc.

I think it's cool, because it would allow us to streamline configuration

But, for our specific issue here, I think it goes a little bit against podman desktop goal which is (I think) to provide seamless integration through extensions. 
To me it would be possible to configure the, maxPid from the UI, in the kind integration, and start off the container with `--pids-limit _**maxPidFromUI**_, isn't it a quick way around this issue?

**Comment by vietk** [comment]
> But I am wondering if it is not something for this case that should not be included by default on all machines, in the default ignition script
> 
> https://github.com/esendjer/podman/blob/1ce53677aafc4d51f282590a9121a10d3a583898/pkg/machine/ignition.go#L301-L307

Finally I am convinced by this default :D

**Comment by fabricepipart1a** [comment]
Hello @benoitf 

> I think using a custom ignition script should work to avoid the usage of a lot of commands `podman machine init --ignition-path ...`
> 
> Podman Desktop could expose some stuff about 'post-init' step or a way to edit machine settings, etc.
> 
> But I am wondering if it is not something for this case that should not be included by default on all machines, in the default ignition script
> 
> https://github.com/esendjer/podman/blob/1ce53677aafc4d51f282590a9121a10d3a583898/pkg/machine/ignition.go#L301-L307

OK I finally understood what you meant there (it took me some time).

Do you confirm that, if I wanted to provide my own ignite script I would need it to contain almost all the entries that podman naturally puts in `~/.config/containers/podman/machine/qemu/podman-machine-default.ign`? 
I can at least say that I tried to provide a ignite.json with just the containers.conf edition... my machine could not start.

If the two ignite (podman one and mine) are not merged and mine replaces the podman one, then I think the only valid option is to have the edition of containers.conf (and increase of pids_limit) handled by podman. I now udnerstand those are the lines you pointed at.
I don't really consider the possibility to provide a partial ignite script that would be merged with podman's because, then, we would be messing up with the same containers.conf file...

Any hope to have either a higher value of pids_limit hardcoded there by podman? Or to make it configurable?

**Comment by benoitf** [comment]
opened https://github.com/containers/podman/pull/21061 yesterday
