### ISSUE TITLE
Debug not working on Windows

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#5284]
### Bug description

It looks like the debugging does not work anymore on windows.
It exits with 
```
Debugger attached.
dep-ErEj4WmL.js:13016
12:13:56 [main] DevTools listening on ws://127.0.0.1:9223/devtools/browser/9d91b78a-8310-4a17-9af0-ff275cbde026
dep-ErEj4WmL.js:13016
12:13:59 [main] [9892:1215/121359.937:ERROR:crashpad_client_win.cc(863)] not connected
dep-ErEj4WmL.js:13016
Process exited with code 4294930435
```
Not sure when it stopped working and if it only affects me, or all devs on windows or any OSes

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

**Comment by jeffmaury** [comment]
Did not face while testing 1.6.3 will check main

**Comment by lstocchi** [comment]
@jeffmaury it is actually random and i have no idea what causes it

It looks that the problem (whatever it is) is within the kubernetes-client class bc it stops there before failing. 

I commented the setupWatcher function to see if it causes the issue -> build it -> debug works -> uncommented the function body and left commented the points where the funcion is called -> build it -> debug fails -> so commented again the whole function -> build it -> i was expecting the debug working as before but it failed. So maybe something with my env

**Comment by feloy** [comment]
Did you install a version of Podman Desktop on your Windows system, using some installer?

I had the same issue after installing one, and it started to work again after uninstalling it.

**Comment by lstocchi** [comment]
Closing as not replicable
