### ISSUE TITLE
Clear filter button is useless in Images page

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5288]
### Bug description

If you click on the Clear filter button and you have a filter set, it does nothing

![clear](https://github.com/containers/podman-desktop/assets/695993/77a92168-ec13-4dd6-ac25-949781d16bc0)

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Took a quick look, was broken by #4600. Likely need to add a resetFilter listener to all pages that use FilteredEmptyScreen.
