### ISSUE TITLE
Newly pulled image does not show up on Podman desktop v1.5.3 without restart

### ISSUE THREAD

**Issue by kaizencon** [containers/podman-desktop#5292]
### Bug description

Issue Description
Newly pulled image does not show up on Podman desktop v1.5.3 without desktop restart

### Operating system

Windows 11

### Installation Method

None

### Version

1.5.3

### Steps to reproduce

1. From win 11 cmd, podman run -it alpine
2. Go to podman desktop
3. Look for alpine image, it wouldn't show
4. Restart the desktop
5. Image will show up under images section

### Additional context

Client:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.20.10
Git Commit:   750b4c3a7c31f6573350f0b3f1b787f26e0fe1e3
Built:        Tue Oct 31 10:05:03 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 11:42:56 2023
OS/Arch:      linux/amd64

**Comment by benoitf** [comment]
I think it's solved by https://github.com/containers/podman-desktop/issues/4712

**Comment by odockal** [comment]
I tried with the 1.6.0-next and on Windows 10 it worked for me. I have running podman desktop, go to the cli, pull an image and it appears in the podman desktop.

**Comment by deboer-tim** [comment]
Fix #4712 is available in the current release, 1.6.3. @kaizencon are you able to update and verify?

**Comment by kaizencon** [comment]
> Fix #4712 is available in the current release, 1.6.3. @kaizencon are you able to update and verify?

Sure, i'll give it a try.

**Comment by kaizencon** [comment]
Confirmed that fix worked for v1.6.3. 

Thanks!

-------------------------  Verification steps: -----------------

podman run -it docker.io/bitnami/kubectl
Trying to pull docker.io/bitnami/kubectl:latest...
Getting image source signatures
Copying blob sha256:e138017510995b30bed881f6e1516291cfca2b55ed06302fed30f0b24b176234
Copying config sha256:52973d2e15acc1640c56b79d7041b024f6d23ee20825cc958baa21f68b2872b4
Writing manifest to image destination
Storing signatures
kubectl controls the Kubernetes cluster manager.

Image showed up in podman desktop instantly.
------------------------------------------------------------- ENV INFO --------------------------------------------

podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.54
    systemPercent: 0.27
    userPercent: 0.19
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: yoga720
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.133.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 239796224
  memTotal: 4011831296
  networkBackend: netavark
  networkBackendInfo:
    backend: ""
    dns: {}
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 1073741824
  swapTotal: 1073741824
  uptime: 2h 58m 1.00s (Approximately 0.08 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 0
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 6140821504
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 13
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486976
  BuiltTime: Fri Apr 14 11:42:56 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
