### ISSUE TITLE
E2E smoke test on PR check are failing on starting an alpine container

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5303]
### Bug description

There are test failure on container start up. 

Ref run: https://github.com/containers/podman-desktop/actions/runs/7242857181/job/19728849964

### Operating system

Ubuntu 22.04

### Installation Method

Other

### Version

next (development version)

**Comment by odockal** [comment]
So there is a particular problem on the host machine:
```
 Error: Error starting a container: Error: (HTTP code 409) unexpected - preparing container 95c3f9ad62234037270e0209b48e35f46cc873a4bb22d043d1226705379cdcd8 for attach: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found 
```

It is interesting that the podman version installed is 4.6.2.

**Comment by odockal** [comment]
There seems to be an issue in `conmon` package in the upstream. https://github.com/containers/podman/issues/21024. Fix should get into repo and the failure should soon be fixed without our influence.

**Comment by benoitf** [comment]
but it seems we can workaround the issue with https://github.com/containers/podman/issues/21024#issuecomment-1859449360

**Comment by deboer-tim** [comment]
Can we still pin our builds to a specific version / use dependabot-style updates so that we don't automatically pick up bad builds?

**Comment by odockal** [comment]
@benoitf Did not notice. thx. I proposed a fix in PR.
@deboer-tim Yeah, I agree. Yet I am not sure how.

**Comment by odockal** [comment]
@deboer-tim Would something like this https://github.com/containers/podman-desktop/issues/5317 do?
