### ISSUE TITLE
Images' actions are not scaling

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5313]
### Is your enhancement related to a problem? Please describe

<img width="1317" alt="Screenshot 2023-12-19 at 09 23 15" src="https://github.com/containers/podman-desktop/assets/1636769/37877fdd-47d6-4364-8c2d-8ec2a36b34e4">

The icons for the actions are not scaling well.
Here, we are in a situation where we have 3 times the same icon for 3 different actions, and it's very hard for the user to understand what those are about, without waiting for the tooltip.

### Describe the solution you'd like

I think we should try to have a more minimalist way to handle the actions:
- There will be primary actions: run, delete, edit (those are pretty obvious with the 
- There will be secondary actions: "Push to" where we should have a dropdown.

similar to 
<img width="159" alt="Screenshot 2023-12-19 at 09 29 56" src="https://github.com/containers/podman-desktop/assets/1636769/b50adf51-abd3-4b43-aed9-b078f8d525ab">

This would make the obvious actions self explicit and the other ones, will be clearer with a textual description.

**Comment by mairin** [comment]
Some ideas:
![20231219_110718](https://github.com/containers/podman-desktop/assets/799683/2326be63-d5a8-48e7-a2dc-5fcd3a69b3ef)

**Comment by benoitf** [comment]
nice software to do wireframe 👍

**Comment by slemeur** [comment]
I prefer the first one, but I think that implies plugins are contributing only "Push to actions". Right now that'd work. If we could regroup the similar actions that would be nicer indeed and in this case, I would think "icon + Push to ..." label for the button could make it more understandable. 
I had the impression we would need to get back to a "kebab" icon, because extensions can be contributing all sort of different actions.

**Comment by deboer-tim** [comment]
> I had the impression we would need to get back to a "kebab" icon, because extensions can be contributing all sort of different actions.

Yes, any extension could contribute an action to do something different. We could add some simple heuristics or metadata to group them, otherwise I would expect this would look just like the kebab popup menu in the list pages.
