### ISSUE TITLE
Dashboard provider card is garbage

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5316]
### Bug description

While testing OpenShift Local extension, I noticed a garbled display:

![image](https://github.com/containers/podman-desktop/assets/695993/d7f53c68-6867-44e1-a020-bd15f7a9f164)

If the window is maximized, then it disappear

![image](https://github.com/containers/podman-desktop/assets/695993/793264b6-9b7e-490d-8287-2b0532ca95cd)

### Operating system

Win11Pro

### Installation Method

None

### Version

1.6.3

**Comment by deboer-tim** [comment]
This was fixed by #6831.
