### ISSUE TITLE
Table sorting not retained after manual changes

### ISSUE THREAD

**Issue by therealprof** [containers/podman-desktop#5322]
### Bug description

Sorting by a column in the Images table, e.g. by size is not retained after modifications to the table, e.g. removal of an image by clicking the trashcan icon.

### Operating system

macOS Ventura 13.6

### Installation Method

Brew (macOS)

### Version

1.6.3

### Steps to reproduce

* Go to the Images view which will hopefully show some images
* Click on the Size column to sort by size
* Remove one of the images via the trashcan icon
* Observe that, despite the sorting indicator, the list is now not ordered by size anymore

### Additional context

Before deletion of an image:
<img width="1388" alt="Screenshot 2023-12-19 at 11 36 35" src="https://github.com/containers/podman-desktop/assets/3321888/00e0b96a-aa44-4c77-80a2-4b5ccc16b27c">

After deletion of an image:
<img width="1390" alt="Screenshot 2023-12-19 at 11 36 54" src="https://github.com/containers/podman-desktop/assets/3321888/4e33c1fe-ef7f-4cde-b451-aab72f149222">

**Comment by deboer-tim** [comment]
Thanks for the report. The table is trying to 'resort' on some data changes but clearly this path isn't triggering it, I will investigate.
