### ISSUE TITLE
Badges to reflect image state that would show up in the images list in the UI

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5330]
### Is your enhancement related to a problem? Please describe

I could have an extension reporting grade quality, if an image has some properties like `wasm` or being from a different arch like `amd64` (if I'm using arm64)

etc.

### Describe the solution you'd like

Need design + extension API

**Comment by deboer-tim** [comment]
+1. Pattern should probably be simple/consistent enough that it could be applied to things like containers or pods in the future, if need be.

Or for that matter image (and other) details pages too.

**Comment by axel7083** [comment]
@benoitf do we want to extend this feature to containers as mentioned by Tim ? For the ai-studio extension we would probably want to add a badge to certain containers indicating they are used for example in the playground.

For now we can change the icon as the `kind` extension is doing it, but adding a badge with a label would be also a nice touch. 

cc @mairin
