### ISSUE TITLE
WSL2 Ubuntu, Can't Use Podman CLI

### ISSUE THREAD

**Issue by tonycody** [containers/podman-desktop#5331]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/6773121/25d9eb6a-f982-4c32-876d-68d358cce490)
![image](https://github.com/containers/podman-desktop/assets/6773121/1360f3fa-5c26-481e-a4b1-3b1468944d4c)
How am I going to use it?

### Operating system

Windows 11 WSL2

### Installation Method

Other

### Version

1.6.3

**Comment by tnk4on** [comment]
The operating system of the Podman machine on WSL2 is Fedora.
The WSL2 distribution name is `podman-machine-default`.
You can check with the following command.
```
PS C:\Users\user> podman machine ssh cat /etc/redhat-release
Warning: Permanently added '[localhost]:50387' (ED25519) to the list of known hosts.
Fedora release 39 (Thirty Nine)
PS C:\Users\user> wsl -l
Windows Subsystem for Linux Distributions:
podman-machine-default (Default)
PS C:\Users\user> wsl -d podman-machine-default
Windows Subsystem for Linux is now available in the Microsoft Store!
You can upgrade by running 'wsl.exe --update' or by visiting https://aka.ms/wslstorepage
Installing WSL from the Microsoft Store will give you the latest WSL updates, faster.
For more information please visit https://aka.ms/wslstoreinfo


You will be automatically entered into a nested process namespace where
systemd is running. If you need to access the parent namespace, hit ctrl-d
or type exit. This also means to log out you need to exit twice.

[user@WINGPU ~]$ podman -v
podman version 4.8.1
```

**Comment by ravinsharma7** [comment]
Does this mean the podman desktop only can setup and connect to the default fedora distro? 

If I have an existing podman installed in my WSL2 debian or ubuntu distro, there is no way to connect to those from the desktop UI?
