### ISSUE TITLE
Docs: Improve introduction page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5335]
### Is your enhancement related to a problem? Please describe

The intro documentation is not welcoming the user and enticing to user the product: https://podman-desktop.io/docs/intro

### Describe the solution you'd like

The introduction is the documentation should provide a good summary of the project and entice the user to read more. From a quick scan of the page, the user might caught interest on the product. 

For this, it’s important that we provide a short introduction of the Project:
- What it is, what it does 
- why we created it
It’s important to differentiate ourselves from the beginning and we should be reusing the talking points we have on the website.

I would add, that we could eventually show a demo of the product, by attaching a link to the youtube short overview from Aine.

Then, we want to guide the user on how to start

We should also provide another set of links:
- Issue tracker
- Troubleshooting
- Community

**Comment by themr0c** [comment]
This is a very unusual request for a documentation landing page.

Usually, the purpose of the documentation landing page is to provide a quick overview of the docs catalog, and guide the user to find quickly the documentation he needs.

Some examples:

- https://docs.docker.com/
- https://docs.ansible.com/
- https://stripe.com/docs
- https://www.twilio.com/docs
- https://quarkus.io/guides/

**Comment by themr0c** [comment]
What seems quite usual is to have a series of cards, each card representing a major user story in the documentation.

I was searching for a way to display things as cards in docusaurus docs, could not find it, until I bumped on a screenshot in #5881. Convergent minds :)

So it seems there is a way in docusaurus to define "categories" and display them as cards.

1. Define the categories and their summary https://docusaurus.io/docs/sidebar/autogenerated#category-item-metadata
2. Use this metatata in the general intro, and in each category index.

@cdrage I need to sync with you on this, you are more advanced on the topic.

**Comment by cdrage** [comment]
> What seems quite usual is to have a series of cards, each card representing a major user story in the documentation.
> 
> I was searching for a way to display things as cards in docusaurus docs, could not find it, until I bumped on a screenshot in #5881. Convergent minds :)
> 
> So it seems there is a way in docusaurus to define "categories" and display them as cards.
> 
> 1. Define the categories and their summary https://docusaurus.io/docs/sidebar/autogenerated#category-item-metadata
> 2. Use this metatata in the general intro, and in each category index.
> 
> @cdrage I need to sync with you on this, you are more advanced on the topic.

I think this would be a bad way of showing the introduction as cards create clutter / creates a sort of "table of contents".

Having it in the introductory would be overwhelming for the new user, when instead they could just look to the left and see the sidebar of relevant information.

This part of @slemeur 's comment is highly relevant: **the documentation should provide a good summary of the project and entice the user to read more. From a quick scan of the page, the user might caught interest on the product.**

IMHO introduction should just be 3-4 paragraphs detailing the project, what it does, and makes me want to crave more / use it more. Sell to the first-time user what it does.

Adding cards / huge TOC would be overwhelming and I would want to not continue.

**Comment by cdrage** [comment]
> This is a very unusual request for a documentation landing page.
> 
> Usually, the purpose of the documentation landing page is to provide a quick overview of the docs catalog, and guide the user to find quickly the documentation he needs.
> 
> Some examples:
> 
> * https://docs.docker.com/
> * https://docs.ansible.com/
> * https://stripe.com/docs
> * https://www.twilio.com/docs
> * https://quarkus.io/guides/

Sorry for the late reply.

I think this issue is different and I think what Stevan meant is "Improve introductory page".

The links you provided are kinda the "index page" of the documentation / site. The docs.ansible.com and docs.docker.com ones are subdomains / their own little web page.

**Comment by cdrage** [comment]
https://docusaurus.io/docs

This is a great example of an awesome intro page

EDIT: @slemeur I've edited the title of this issue as there was some confusion and changed this to "introduction". I opened up issue #6002 with regards to @themr0c 's comments on landing page
