### ISSUE TITLE
Doc: Improve navigation in page's section by adding an outline

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5336]
### Is your enhancement related to a problem? Please describe

When a page has a lot of sections it's difficult to see all of them and switch from one section to another one

### Describe the solution you'd like

Add the outline for the sections in the page in a right-sidebar, similar to:
https://code.visualstudio.com/docs/getstarted/themes

**Comment by themr0c** [comment]
Can you elaborate? Do you have any specific page in mind where it is missing?

I believe it is already the case. It is visible only pn pages that have sections. Examples: https://podman-desktop.io/docs/installation/macos-install, https://podman-desktop.io/docs/containers/registries

**Comment by themr0c** [comment]
It is already the case (when the pages have sections).
