### ISSUE TITLE
Doc: Improve left-sidebar navigation

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5338]
### Is your enhancement related to a problem? Please describe

When you arrive on the documentation, we have a lot of sections but it's hard to know what's in each of the section. It forces the reader to "unflod" each of the section to have an idea of what's into it. 

<img width="394" alt="Screenshot 2023-12-20 at 10 18 44" src="https://github.com/containers/podman-desktop/assets/1636769/a68a4fc4-9fcb-4ec0-8c8b-4c68f877e71c">

### Describe the solution you'd like

We would like to have 2 levels of sections unfolded by default.
Also, we would like to visually differentiate the levels of navigation.

Example:
<img width="281" alt="Screenshot 2023-12-20 at 10 21 16" src="https://github.com/containers/podman-desktop/assets/1636769/691af4c5-323d-41e1-8488-9e75c7d85994">
(link: https://ionicframework.com/docs)

**Comment by themr0c** [comment]
Let's proceed.

Note that I still believe that it looks ugly, and that when a documentation set requires keeping open the entire navigation tree, it is a clear sign that the outline needs a reorganization. In our case, the outline is feature-centric, and would benefit from migrating to a more user-centric, story-based approach.

**Comment by deboer-tim** [comment]
Reopening, since neither of the solutions are complete.

**Comment by cdrage** [comment]
Reopening this again as it's a bit of a mess right now IMHO:
![Screenshot 2024-01-31 at 10 27 10 AM](https://github.com/containers/podman-desktop/assets/6422176/aba52c8c-3640-4174-9489-f6e122ce6242)

Especially with the windows / linux sections at the top

**Comment by cdrage** [comment]
Merged https://github.com/containers/podman-desktop/pull/6125 for now.

Keep this issue open so we can fix the styling / separate component / have it use tailwindcss in the future.
