### ISSUE TITLE
extension catalog download time out on a regular basis

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#5349]
### Bug description

I noticed several times that when Podman Desktop is started, unistalled extensions have the N/A label in the Featured Extensions box. This is because the download of the extensions catalog time out on a regular basis.
We should probably retry until we got the catalog

### Operating system

Win11Pro

### Installation Method

Winget (Windows)

### Version

1.6.3

### Steps to reproduce

Start Podman Desktop and cross fingers 🥲

**Comment by deboer-tim** [comment]
How about we 'ship' with the current copy, and every time we have a successful download cache a copy as well? Simple enough, and that way this screen would never be blank.

**Comment by benoitf** [comment]
well it's not so good as you would think you can download an extension and maybe it's not there or you're not connected etc. You bring other kind of problems

**Comment by slemeur** [comment]
How one in this state can force refresh the load of the catalog file?
