### ISSUE TITLE
podman desktop running on windows is taking more than 30 min to showup

### ISSUE THREAD

**Issue by ivardu** [containers/podman-desktop#5353]
### Bug description

podman desktop goes to either not responding or doesn't show up for very long time, I have recently installed 1.6.3 on my laptop and facing issues with it. 

### Operating system

Windows 10 Enterprise

### Installation Method

Installer from website/GitHub releases

### Version

1.6.3

**Comment by ivardu** [comment]
log : main ↪️ Error while fetching API groups: Error: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GQVL99TCR to authenticate.
Error: failed to get token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired

log : main ↪️ Error while fetching API groups: Error: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GWF8GVNAD to authenticate.
Error: failed to get token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired

warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 9 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 10 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\dr\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 10 seconds
log : main ↪️ Activating extension (redhat.redhat-sandbox) with max activation time of 10 seconds
log : main ↪️ [redhat-sandbox] starting extension openshift-sandbox
log : main ↪️ [redhat-sandbox] Configfile location C:\Users\dr\.kube\config
log : main ↪️ Activating extension (redhat.openshift-local) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 2055 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) ended in 1540 milliseconds
log : main ↪️ Activating extension (redhat.redhat-sandbox) ended in 42 milliseconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 2070 milliseconds
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'lookup' for 1000ms
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'lookup' for 1000ms
error : main ↪️ [compose] Error getting compose version: Error: Failed to execute command: spawn C:\Users\dr\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.compose\bin\docker-compose.exe ENOENT
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kind) ended in 2198 milliseconds
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 1866 milliseconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 1961 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 1361 milliseconds
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ Activating extension (podman-desktop.podman) ended in 4834 milliseconds
log : main ↪️ Activating extension redhat.openshift-local failed error:Error: Extension redhat.openshift-local activation timed out after 10 seconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting podman-desktop.podman container engine
log : main ↪️ [podman] Podman extension: Autostarting machine podman-machine
log : main ↪️ [kind] kind extension is active
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 547.8805999998003ms
log : main ↪️ Skipping update for extension redhat.redhat-sandbox because installed version 0.0.2 is greater or equal to latest available version 0.0.2
log : main ↪️ Skipping update for extension redhat.openshift-local because installed version 1.3.0 is greater or equal to latest available version 1.3.0
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ [kind] kind extension is active
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
warn : main ↪️ [podman]  Can't get machine podman-machine resource usage error Error: no running provider for the matching container
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]
log : main ↪️ Telemetry request error: [object Object]

**Comment by ivardu** [comment]
When I'm troubleshooting the Details of pod store it's not responding podman-desktop freezes also I see a log 
Garb 0 items from 'provider-change' event 1 hour ago. Took 912 seconds.
Garb 0 items from 'extensions-already-stated' event 2 hour ago. Took 960 seconds.

**Comment by benoitf** [comment]
I think all connections are being intercepted/timeout by a proxy or something like that so it's delaying all http requests

**Comment by ivardu** [comment]
Hi @benoitf, I see there is no proxy configured on my laptop and I'm able to run the Docker desktop without any issues. How can I identify the right issue with the podman, any path for the logs you can suggest.. ?  Also my proxy settings were not enabled
