### ISSUE TITLE
Doc: Create a "Discover Podman Desktop in 10min" page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5369]
### Is your enhancement related to a problem? Please describe

This article is pretty interesting but largely obsolete: https://developers.redhat.com/articles/2023/03/01/podman-desktop-introduction

### Describe the solution you'd like

Have a guide enabling the developers to quickly discover "Podman Desktop in 10min" which would be part of our documentation

**Comment by themr0c** [comment]
Something like: given you have already installed Podman Desktop, Podman, and have a Podman engine running, this document will show you how to run a sample container application on your Podman engine, modify your application and see the changes?
