### ISSUE TITLE
OpenShift Local menu bar item on macOS on Arm

### ISSUE THREAD

**Issue by rhwood** [containers/podman-desktop#5380]
### Bug description

In the Podman Desktop 1.6.3 menu bar item on macOS, the _OpenShift Local_ menu differs between Intel and Arm versions of macOS. The Arm version (macOS Sonoma), contains:
* Start
* Stop
* Open developer terminal
* Delete

while the Intel version (macOS Monterey) contains:
* Start
* Stop
* Open developer terminal
* Open console
* Copy OC login command (admin)
* Copy OC login command (developer)
* Delete

Why the difference?

### Operating system

macOS Sonoma 14.2.1 (Arm), macOS Monterey 12.7.2 (Intel)

### Installation Method

Brew (macOS)

### Version

1.6.3

### Steps to reproduce

Install Podman Desktop and OpenShift Local on both an Arm and Intel MacBook and observe the difference.

**Comment by benoitf** [comment]
transferring issue to https://github.com/crc-org/crc-extension

**Comment by benoitf** [comment]
moved as https://github.com/crc-org/crc-extension/issues/198
