### ISSUE TITLE
Unable to select image path when creating machine

### ISSUE THREAD

**Issue by martin-juul** [containers/podman-desktop#5389]
### Bug description

When i create a machine, i'm unable to select a path to store the image.
The GUI expects the file to already exist.

![image](https://github.com/containers/podman-desktop/assets/11337105/9c634087-826d-48f6-809d-61af986496da)

![image](https://github.com/containers/podman-desktop/assets/11337105/56322966-5bfe-491b-bfd1-9da5bb3fbdc9)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.3

**Comment by benoitf** [comment]
@martin-juul it expects the image definition of the virtual machine (podman machine) not a path to store images

This is why it must exist

**Comment by martin-juul** [comment]
Ah okay, i misunderstood the GUI. Thank you.
