### ISSUE TITLE
Double-clicking tray should open dashboard

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5396]
### Is your enhancement related to a problem? Please describe

When you double-clicking the tray icon, nothing happens.

### Describe the solution you'd like

As requested from feedback: double-clicking the tray icon should open the dashboard.

I tried several other tray icons on my Mac: some opened their dashboard equivalents, some did nothing. As requested it seems like the double-click action should do something, and opening the dashboard seems like the logical option.

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/4500
