### ISSUE TITLE
Display kubernetes connection status

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5401]
### Is your enhancement related to a problem? Please describe

When exploring the Deployment or Service tabs, or simply when switching context, it would be nice to have information related to the cluster connection.

For example, when switching context, we will get the following log 
> [main] Error while fetching API groups: Error: connect ECONNREFUSED {host}:{port}

However, we cannot see that the connection has failed. In the Deployment and Service tabs, we are invited to chance the context, without further information

### Describe the solution you'd like

An indicator related to the connection status.
In the status bar we could imagine an indicator 🔴 🟠 🟢 next to the context name (some ideas)

**Comment by axel7083** [comment]
Here is a mockup

**connection error**
<img width="784" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/2aee5b82-a351-4056-a5df-18710eb38729">

**connected**
<img width="786" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/0c5501cc-f408-4642-a948-d5711dee12dd">

**Comment by deboer-tim** [comment]
We had a discussion with @mairin yesterday, and the recommendation for now is to re-color the Kubernetes context status bar item based on the connection. The current context is already shown, and would change color based on the connection:
- white (normal) = connected
- red = disconnected
