### ISSUE TITLE
Provide more outputs while creating a podman machine

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#541]
### Is your enhancement related to a problem? Please describe

When creating a podman machine, the process of pulling the VM Image could be taking some time - and there are other steps that a user could be interested by. 

### Describe the solution you'd like

Display more information about the status/steps of creating the podman machine, like the information displayed when doing a `podman machine init` from the CLI.

<img width="973" alt="Capture d’écran 2022-10-10 à 10 51 20" src="https://user-images.githubusercontent.com/1636769/194830188-a1fd7b6b-a5bf-4203-a4b6-8a3bb9278047.png">

<img width="655" alt="Capture d’écran 2022-10-10 à 10 54 05" src="https://user-images.githubusercontent.com/1636769/194830260-192cdef3-7262-4839-9972-8e16f3d1bfd8.png">

**Comment by benoitf** [comment]
it's now possible to see progress on podman machine creation, closing
