### ISSUE TITLE
Close button does not work in error message spawned by ImageActions

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5420]
### Bug description

As mentionned by @lstocchi in https://github.com/containers/podman-desktop/pull/5414

The click on the close icon does not work. (On Windows I can also confirmed)

<img width="497" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/bdaeae4f-a878-4716-9c47-c105dbe1cf33">

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Have an existing Kubernetes context selected (It should be unavailable)
- Push image
- The error message cannot be closed using the close icon

**Comment by gastoner** [comment]
This cannot be reproduced in version 1.12-next

https://github.com/user-attachments/assets/ed6fd128-cc7a-498c-8fa6-8964c5e3c0e8
