### ISSUE TITLE
Display `labels` from kubernetes objects

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#543]
### Is your enhancement related to a problem? Please describe

As a user, trying to run kubernetes objects, I'd like the ability to display the `labels` defined on those objects.
Especially for `labels.app` which is important to group objects all together. 

### Describe the solution you'd like

- Display by default `labels.app` in the list of containers + pods
- Eventually provide an option to show all labels

**Comment by benoitf** [comment]
closing as it's handled in other issues
