### ISSUE TITLE
Podman Desktop does not work with Podman Apple Hypervisor backend.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5441]
### Bug description

Try to use applehv with podman:

```sh
▶ export CONTAINERS_MACHINE_PROVIDER=applehv
▶ podman machine init
Downloading VM image: fedora-coreos-39.20231204.2.1-applehv.aarch64.raw.gz: done
Extracting compressed file: podman-machine-default_fedora-coreos-39.20231204.2.1-applehv.aarch64.raw: done
Machine init complete
To start your machine run:

	podman machine start


~
▶ podman machine start
Starting machine "podman-machine-default"
```

Podman Desktop does not show the podman machine or post any errors:

![Screenshot 2024-01-05 at 10 43 25 AM](https://github.com/containers/podman-desktop/assets/6422176/d95ef028-6783-4003-ac32-0269092e214e)

### Operating system

mac M1

### Installation Method

None

### Version

1.6.3

### Steps to reproduce

```sh
export CONTAINERS_MACHINE_PROVIDER=applehv
podman machine init
podman machine start
```

Try to use podman in PD.

**Comment by benoitf** [comment]
use the parameter in containers.conf file and not environment variable

**Comment by cdrage** [comment]
Ahh, that does it.

For others:

Add:

```sh
[machine]
provider="applehv"
```

to `~/.config/containers/containers.conf`


Should we add this to docs now or wait until `applehv` is default within podman?

**Comment by afbjorklund** [comment]
For lima, the syntax is `--vm-type=vz`. It uses the same image as `--vm-type=qemu`.

* #5447

**Comment by cdrage** [comment]
Closing this as it was more a documentation issue and 5.0.0 of podman will be hypervisor by default.
