### ISSUE TITLE
Dialogs should always use "Cancel" and "Yes" rather than "Yes" and "No".

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5446]
### Is your enhancement related to a problem? Please describe

When a dialog is using Cancel, it will show a different style, example:

![Screenshot 2024-01-05 at 5 07 12 PM](https://github.com/containers/podman-desktop/assets/6422176/4484a398-a257-4cca-af96-2709d88d7175)

However, throughout PD we have "No" which has a different style:

![Screenshot 2024-01-05 at 5 07 31 PM](https://github.com/containers/podman-desktop/assets/6422176/6d0ed49d-c513-490d-b784-4afe37988b14)

### Describe the solution you'd like

Go through everything that uses showMessageBox and update it to use "Cancel" instead of "No".

**Comment by trmendes** [comment]
Hi @cdrage. I will be working on this task.

I will take a different approach. Will go through all the “No” and update those that are an option for ```showMessageBox```, but, I would like to ask if you see any reason this approach could leave unwanted no’s behind.

**Comment by trmendes** [comment]
Do we also want to change from No to Cancel on ```showInformationMessage```

```js
const dialogResult = await extensionApi.window.showInformationMessage(
      `Podman is not installed on this system, would you like to install Podman ${getBundledPodmanVersion()}?`,
      'Yes',
      'No',
    );
```
