### ISSUE TITLE
Include extension-folder in extension docs

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5480]
### Is your enhancement related to a problem? Please describe

The documentation on writing extensions doesn't say anything about how to run and test your new extension.

### Describe the solution you'd like

The docs about writing extensions should tell you about
`yarn watch --extension-folder /path/extension`

**Comment by benoitf** [comment]
this one is a dup of https://github.com/containers/podman-desktop/issues/4853
