### ISSUE TITLE
ContainerCreateOptions is missing vital information such as Labels, Volumes, etc.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5482]
### Is your enhancement related to a problem? Please describe

ContainerCreateOptions is not 1-1 with what we are using in Dockerode: https://github.com/containers/podman-desktop/blob/f75dcfd8bccbd17525afb5e5ff54850cd4f5ddb0/packages/extension-api/src/extension-api.d.ts#L1862-L1863

I went to go try to add a label when create a container, but was unable to

### Describe the solution you'd like

Be able to use Labels as well as other abilities similar to dockerode code.

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/5502
