### ISSUE TITLE
Desktop doesn't work with newly rolled out OS / Browser / Networking stack in some areas (near RedHat Israel location)

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman-desktop#55]
### Bug description

After installation using downloaded from Github Windows installer Desktop does nothing 

### Operating system

Win 11 recent insider preview + Fedora34 WSL2 distro + Chrome v 100.0 dev with Privacy sandbox

### Version

next (development version)

### Steps to reproduce

1. Download and installer of Container-desktop from github
2. Ru installed desktop
3. Try to list images

### Relevant log output

```shell
journalctl from inside seems shows nothing relevant except my own Theia backend container unit. 
Does another log mechanism exists?
```

### Additional context

1. Chrome 100 breaks 50% of sites due to 3th party cookies block by the default
2. Chrome 100 breaks 100% of sites with business analytics due to problematic DNS name resolution. Windows ns lookup doesn't resolve IPV6 addresses but resolvectl query from inside WSL VM works correctly. Do not trust in Windows name resolution. IPV6 from the WSL VM doesn't work but issue is opened. Please, support this requirement
3. Possibly, Podman 4 re-installation is needed triggered by Desktop installer.
4. My own Podman service Unit starts OK
5. My Fedora 34 Distro uses systemd / genie
6. My own Podman systemd service unit starts OK.

Happy to see Florent Benoit on the board

**Comment by benoitf** [comment]
@PavelSosin-320 : could you please check that you have podman 4 being installed on Windows

using for example `cmd` terminal: 

```
C:\Users\benoitf>podman --version
podman version 4.0.2
```

Also check that you have machines

```
C:\Users\benoitf>podman machine list
NAME        VM TYPE     CREATED     LAST UP            CPUS        MEMORY      DISK SIZE
desktop     wsl         1 days ago  Currently running  8           1.22GB      857.7MB
```

And then, please check the named pipe
For example with PowerShell please enter the following command:

```
 [System.IO.Directory]::GetFiles("\\.\\pipe\\") | Select-String -Pattern 'podman'
```

if you don't see a 'podman' pipe, could you please provide the other pipes you see
```
 [System.IO.Directory]::GetFiles("\\.\\pipe\\")
```

Maybe could be linked to https://github.com/containers/podman/issues/13502

**Comment by benoitf** [comment]
closing as Podman Desktop is able to successfully connect to Podman 4 on Windows

And there is a Windows installer for Podman now
