### ISSUE TITLE
Fix Podman extension e2e test failures/errors on windows workflows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5511]
### Bug description

There are repetitive test failures/errors happening on [windows workflows](https://github.com/containers/podman-desktop-e2e/actions/runs/7498555771).

Test failures:
```
ts.Verification of Podman extension > Podman is enabled and present 
ts.Verification of Podman extension > Podman extension can be re-enabled from Settings Extension Page
```

Check the log, see test artifacts and propose a fix for test errors. In case of test failure report an issue.

### Operating system

Windows 10, 11

### Installation Method

Other

### Version

next (development version)

**Comment by ScrewTSW** [comment]
tests passed in CI https://github.com/containers/podman-desktop-e2e/actions/runs/7583348968/job/20654894426
