### ISSUE TITLE
UI is quite confusing to use

### ISSUE THREAD

**Issue by nithinbandaru1** [containers/podman-desktop#5513]
### Is your enhancement related to a problem? Please describe

1. Featured extensions are being shown but no download button there. 

![image](https://github.com/containers/podman-desktop/assets/25755972/e9117be5-550c-42c3-abbe-d4f01ef65dfd)

2. In visual contextual sense I feel this cluster switching options should be present here. It should be inside the pods tab.

![image](https://github.com/containers/podman-desktop/assets/25755972/b684f651-3816-4d8b-8a06-07368ca38fda)

3. I feel should be 2 side bars, 1. Containers (second bar with containers, images, volumes, networks etc), 2. Kubernetes (with pods, secrets, config maps etc...). I just feel its not rightly organized.

![image](https://github.com/containers/podman-desktop/assets/25755972/bc60d28d-8c0a-47b9-a178-7cfa857f61b2)

4. I really don't understand the need for Client CLI tools tabs when there is resources tab. I feel its redundant. I also fee Resources tab can be redundant if you add a settings button in extensions list in extensions tab. Cleaner and simpler because then we can handle all things related to extensions in one place,

![image](https://github.com/containers/podman-desktop/assets/25755972/70f59b54-9576-4779-ab53-7ac6334d7cc4)

### Describe the solution you'd like

1. Featured extensions are being shown but no download button there. 

Solution: Show download button.

2. In visual contextual sense I feel this cluster switching options should be present here. It should be inside the pods tab.

Solution: Move it to the pods tab.

3. I feel should be 2 side bars, 1. Containers (second bar with containers, images, volumes, networks etc), 2. Kubernetes (with pods, secrets, config maps etc...). I just feel its not rightly organized.

Solution: Add second bar.

4. I really don't understand the need for Client CLI tools tabs when there is resources tab. I feel its redundant. I also fee Resources tab can be redundant if you add a settings button in extensions list in extensions tab. Cleaner and simpler because then we can handle all things related to extensions in one place,

Solution: Remove both client cli and resources tab and add settings button in extensions list display and from there modify the settings.

**Comment by deboer-tim** [comment]
Nithin, could you please open separate issues for each suggestion? It will get difficult to respond to all of these here, nor could we close any issues if we respond to them.

**Comment by nithinbandaru1** [comment]
Sure will do that.
