### ISSUE TITLE
Javascript error after uninstalling

### ISSUE THREAD

**Issue by aolszak** [containers/podman-desktop#5529]
### Bug description

After uninstalling podman desktop and podman I still get once a day a random error alert on my Mac. How to stop the process which is generating this error?

<img width="252" alt="Screenshot 2024-01-13 at 08 09 38" src="https://github.com/containers/podman-desktop/assets/4125806/968035c2-0554-4425-a1d3-c4a392283a59">

### Operating system

MacOS Ventura 13 ARM

### Installation Method

Brew (macOS)

### Version

1.6.3

### Steps to reproduce

Install podman
Uninstall podman

### Relevant log output

```shell
Not needed
```

### Additional context

<img width="252" alt="Screenshot 2024-01-13 at 08 09 38" src="https://github.com/containers/podman-desktop/assets/4125806/6b96cb79-c963-4e34-a98d-66a3bbade182">

**Comment by benoitf** [comment]
@aolszak you might check `/Library/LaunchDaemons/*podman*` or `~/Library/LaunchDaemons/*podman*`
