### ISSUE TITLE
Expose the UI components

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#5541]
### Is your enhancement related to a problem? Please describe

An extension using the webview component will want to have a UI consistent with the core Podman Desktop interface.

### Describe the solution you'd like

To make the consistency possible, the UI components and layouts defined in Podman Desktop (`packages/renderer/src/lib/ui`) could be distributed as reusable components.

### Describe alternatives you've considered

For now, components are duplicated in the extensions, and maintenance is needed to maintain their consistency with Podman Desktop ones.

### Additional context

- [ ] Some components (`ListItemButtonIcon`, etc) depend on `/@/stores/context`.
- [ ]

**Comment by deboer-tim** [comment]
This is being tracked via epic #5757.
