### ISSUE TITLE
Improve kubeconfig path preference

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5551]
### Is your enhancement related to a problem? Please describe

I don't know how I didn't notice this before, but the kubeconfig path is in a section 'Path to the kubeconfig file' that is quite out of place compared with the other preferences entries, and ensures that it'll never be grouped with any other items.

<img width="587" alt="Screenshot 2024-01-15 at 5 41 51 PM" src="https://github.com/containers/podman-desktop/assets/19958075/a02cb5b1-baed-49c1-8dd3-6f297a770c01">

### Describe the solution you'd like

Use a more standard section and title so that it fits in better and can be grouped with other Kubernetes preferences.

**Comment by feloy** [comment]
https://github.com/containers/podman-desktop/pull/5329 should fix the issue
