### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5563]
The 1.7 release will focus on stability, and enhancements required by new extensions.

Required issues:
- #5542
- #5525
- #5140
- #5599
- At least part of #5618
  - https://github.com/containers/podman-desktop/pull/5641
- #5648
- #5643
- #5601

postponed:
- #5523
- #5505

**Comment by benoitf** [comment]
added https://github.com/containers/podman-desktop/issues/5599

**Comment by mairin** [comment]
can we add #5601

**Comment by axel7083** [comment]
Can we add https://github.com/containers/podman-desktop/pull/4369 ?

**Comment by benoitf** [comment]
@axel7083 https://github.com/containers/podman-desktop/pull/4369 should be a post 1.7 release

**Comment by lstocchi** [comment]
https://github.com/containers/podman-desktop/pull/5648 has been merged 👍

**Comment by deboer-tim** [comment]
Release process has started, release notes up for review in #5659.

**Comment by deboer-tim** [comment]
Release complete, published to all repos, and announced! Closing this issue.

In case it helps future-releasers, I checked for all PRs and put them in the basic format using a Github cli query & template: 

`gh pr list -L 1000 --search "milestone:1.7.0 is:closed author:axel7083 author:deboer-tim author:cbr7 author:benoitf author:cdrage author:dglovin author:feloy author:gbraad author:jeffmaury author:mairin author:lstocchi author:odockal author:rostalan author:ScrewTSW author:slemeur author:themr0c author:vzhukovs author:xbabalov" --json number,title,author --template '{{range .}}- {{.title}} [#{{.number}}](https://github.com/containers/podman-desktop/pull/{{.number}}){{"\n"}}{{end}}' > prs-release.txt`

and for community, the opposite filtering out known people and bots:

`gh pr list -L 1000 --search "milestone:1.7.0 is:closed -author:app/dependabot -author:axel7083 -author:deboer-tim -author:cbr7 -author:benoitf -author:cdrage -author:dglovin -author:feloy -author:gbraad -author:jeffmaury -author:mairin -author:lstocchi -author:odockal -author:rostalan -author:ScrewTSW -author:slemeur -author:themr0c -author:vzhukovs -author:xbabalov -author:podman-desktop-bot" --json number,title,author --template '{{range .}}[{{.author.name}}](https://github.com/{{.author.login}}) in [{{.title}}](https://github.com/containers/podman-desktop/pull/{{.number}}){{"\n"}}{{end}}' > prs-community.txt`
