### ISSUE TITLE
containerEngine in extensionApi should support volumes operation

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5564]
### Is your enhancement related to a problem? Please describe

containerEngine already support 
- listContainers
- listImages
- listNetworks
etc.

### Describe the solution you'd like

Adding
- listVolumes
- createVolume
- deleteVolume

**Comment by axel7083** [comment]
cc @benoitf  the `listPods` is also not included in the containerEngine, do we want them to be included?

**Comment by benoitf** [comment]
I would differentiate/split what is required at short term by an extension and what would be nice to expose as models/methods are already there
