### ISSUE TITLE
UX: need polished mockup for platform selection

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5573]
Some issues with the status quo - I think emphasizes Linux when thats the majority case; would be better to emphasize the diff between the options.

Will try rows instead of cards as well

![image](https://github.com/containers/podman-desktop-extension-bootc/assets/799683/09795f72-82a5-451a-a534-1fcb80be9d23)

**Comment by deboer-tim** [comment]
Moved to Podman Desktop since this is the regular build form.

FWIW, my main concern is that while we _need_ this option, 98% of the time users are just building for the current platform so having this option is almost a mental distraction. It would be nice to minimize the visual impact/not draw the eye to it as much. e.g. cards smaller/less pronounced, or only the current platform is visible unless you expand.

**Comment by mairin** [comment]
Just some food for thought / WIP mockup snapshots so you can see what I'm playing with, no solid proposal here just playing around

## Where the bootable container options box goes

im designing this as a box.... doesn't have to be expanded by default.... should appear only if the user checks off "containerfile icnludes bootable OS" checkbox.

![image](https://github.com/containers/podman-desktop/assets/799683/f0ffe585-a7ab-410b-979a-8868519f970e)

## card based design

here's some refinement with the card based approach we've got. note i've renamed the cards... focus is on the difference (arch / wasi platform) and not the OS (which is mostly linux, we want users to right away be able to distinguish between the differences)

maybe tux is an unhelpful distraction. not sure. or maybe should be single color. anyway. expanded card view

![image](https://github.com/containers/podman-desktop/assets/799683/5c533fe6-bab8-43ca-be9f-dbbe9354be19)

## row based view

also playing with a row based view, @slemeur had suggested this, maybe im sold, but the checkboxes on the right are weird i know. but that's how the checkboxes for the icon cards in onboarding were designed... maybe would be ok to move the checkboxes to the right. the different styles on the right are showing default platform (with the purple dot acting as tux's conscience here), the hover item (ppc), and the selected item (s390), and the rest are unselected.

![image](https://github.com/containers/podman-desktop/assets/799683/4f0d8899-b41a-4656-b9b0-1ef2c2ae310b)


Any feedback appreciated, this is still WIP and sloppy but jsut so you see where i've been playing with this so far

**Comment by deboer-tim** [comment]
FWIW, this screen is not bootable container options, just platform options for any (possibly bootable, possibly not) container.

I like the idea of a Target Platform section, or a single entry that says '<whatever the current platform is>' with an expander to see the others. Personally I prefer the rows, but I still like the checkboxes on the left. I was going to joke that maybe it could even be our Table component with removed header 😛 ... maybe a bad idea, but it confirms that left checkbox + icon can work.

**Comment by benoitf** [comment]
the last mockup fits mostly what we display when using the quickpick component (maybe icon can't be provided yet but not a big issue) but it's a scrollable list with checkboxes, description and title (but checkboxes are on the left) I think being on the right is not so convenient

for 1C image, there will be no checkbox AFAIK, as it's not a question that you prompt at build time, it depends of your Containerfile, this is why it's done at a second step

**Comment by mairin** [comment]
> for 1C image, there will be no checkbox AFAIK, as it's not a question that you prompt at build time, it depends of your Containerfile, this is why it's done at a second step

I don't follow this, what is 1C image?

(edited) oh haha - sorry!!! - the mockup labeled 1C... i put the checkbox there for the user to tell us it was bootable containerfile in case we couldn't auto-detect. can we auto-detect?

**Comment by benoitf** [comment]
![image](https://github.com/containers/podman-desktop/assets/436777/0939f1bd-94ff-4046-87ba-1ac444fe2be8)

**Comment by benoitf** [comment]
oh sorry I didn't see you got the image

For the checkbox, user would check the box for example if you do any image and it doesn't work like that, you can't say "hey I want to build this Containerfile as a bootable image'

**Comment by benoitf** [comment]
so, it's when the image is built that we know if we can do stuff with it (and convert/transform it, etc)

**Comment by mairin** [comment]
OK how about this:

## Default // single platform // not expanded

![image](https://github.com/containers/podman-desktop/assets/799683/ad780fad-e617-465e-92f5-ac7e38792959)


## Default // single platform // expanded 1 level

![image](https://github.com/containers/podman-desktop/assets/799683/1ce22e4a-d51e-4c43-aac6-e1bc17938db5)


## Default // single platform // expanded 2 levels

![image](https://github.com/containers/podman-desktop/assets/799683/d476122a-20e5-41be-9583-c7893919dadf)

## Multiple platforms // collapsed all levels

![image](https://github.com/containers/podman-desktop/assets/799683/4a356735-5cf1-4886-bd98-782e09e69b4b)

## Multiple platforms // expanded 1 level

![image](https://github.com/containers/podman-desktop/assets/799683/8924072d-4103-4219-9a6e-bc90743dd8e6)

**Comment by mairin** [comment]
> so, it's when the image is built that we know if we can do stuff with it (and convert/transform it, etc)

i suspect maaaybe then having the tux icon at this step might be confused because it might make it seem its bootable.

we could try to have icons for the platforms... or some kind of generic platform icon maybe? or no icon 🤷🏻‍♀️

**Comment by benoitf** [comment]
I've 2 quick remarks:

1. I'm finding it weird that it's taking more width than the previous lines
note sure how to explain that, but either it should be on the same width or upper fields should be aligned with the new widget
![image](https://github.com/containers/podman-desktop/assets/436777/7b43124d-91fc-476d-b61a-c38762a62754)

2.
![image](https://github.com/containers/podman-desktop/assets/436777/72bf962b-053f-4754-bb0a-aa924ea466e4)

chevron is not in a direction that I would expect


ok third one :-)
I'm not sure we need the `Multiple platforms // collapsed all levels`

**Comment by benoitf** [comment]
also do we need `Intel and AMD` or just `amd64` or `x64` and `arm64` for arm (no ® or TM or ©)

**Comment by deboer-tim** [comment]
> ok third one :-) I'm not sure we need the `Multiple platforms // collapsed all levels`

lol, I was about to say I really like that one as the initial view. ;-) It just says 'I'm going to build for the current platform' with minimal UI and you can expand to show all the options. We can talk at UX meetup.

**Comment by mairin** [comment]
We discussed at the UX call yesterday and this is what I mocked up for 1.7:
https://github.com/containers/podman-desktop/issues/5601

**Comment by mairin** [comment]
> also do we need `Intel and AMD` or just `amd64` or `x64` and `arm64` for arm (no ® or TM or ©)

These are the vetted "friendly" names we use, e.g. see https://fedoraproject.org/server/download

I suggest these because I worry with the acronyms that ARM64 / arm64 and AMD64 / amd64 are really difficult to discern between at a glance...

**Comment by deboer-tim** [comment]
I'm fine with the official names, but I would like to keep badges like x86, arm, as once I've seen the UI once that is what I'd be scanning for.

**Comment by benoitf** [comment]
some products show x64 instead of amd64 and AArch64 instead or arm64 but in that case I think it's harder with AArch64

so this is why x64 and arm64 look like good candidates

(and in addition we flag the card of the arch of the current laptop/machine)
