### ISSUE TITLE
UX: Handling different clickable row elements on hover

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5574]
### Bug description

@deboer-tim pointed this out last week - when you are hovering over a row and it's lit, you might have multiple different clickable items within the row that point to different targets. We don't handle this particularly elegantly visually, so it would be nice to refine the design of this to make it better.

### Operating system

ALL

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
+1. For getting to details it would probably be nice if the entire name cell (or multiple cells) were clickable? But in other cases (e.g. dots for containers in a pod, actions) only an area would be.

We also noted that purple text hover is used in one page, but isn't used elsewhere, would be a nice visual touch to continue.
