### ISSUE TITLE
UX: Displaying badges in image details screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5575]
### Is your enhancement related to a problem? Please describe

We're introducing more badges to the container / image / etc. objects in the UI. Right now we list them in the lists for these objects but we do not list them on the details screens for these objects. 

### Describe the solution you'd like

List any badges / tags that apply to a specific object in the UI in its details page as well as any list pages it may appear in. 

Probably somewhere in the header by the name of the object.

**Comment by benoitf** [comment]
FYI it's already in the details page

**Comment by mairin** [comment]
> FYI it's already in the details page

Oh sweet! Is the look / feel ok or could it use some tweaks? (got any screenshots?)

**Comment by benoitf** [comment]
@mairin you can find screenshot here: https://github.com/containers/podman-desktop/pull/5557

**Comment by mairin** [comment]
> @mairin you can find screenshot here: #5557

Ah i would propose a visual tweak - just bc the weight of the badges vs the "latest" tag there maybe feels a bit unbalanced. definitely not high priority but ill keep this issue open to try to address with a mockup
