### ISSUE TITLE
Minor polish for platform selection in 1.7

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5601]
### Is your enhancement related to a problem? Please describe

![Screenshot from 2024-01-19 07-49-28](https://github.com/containers/podman-desktop/assets/799683/4b146a1e-c730-45cf-bd6b-ac38431fe017)

Just some visual tweaks I am hoping are possible for 1.7. These emphasize the platform's architecture name instead of the OS, to try to make it easier to discern the differences between platforms. Here's the list from the mockup:

- Intel and AMD x86_64 systems
- ARM® aarch64 systems
- Power ppc64le systems
- IBM s390x zSystems
- WebAssembly

### Describe the solution you'd like

See mockup :)

**Comment by afbjorklund** [comment]
No RISC-V ? ;-) Maybe "New Platform"

**Comment by benoitf** [comment]
would it work like this ?

![image](https://github.com/containers/podman-desktop/assets/436777/1864c5f5-3b10-4130-9f67-2e9110b72e35)


(default circle appears for now in the top right corner and not and the end of the title)

**Comment by mairin** [comment]
@benoitf i think the (+) button placement is totally fine.

Wondering if the cards can be fills instead of outline though?

**Comment by benoitf** [comment]
ah yes I forgot for the background

I was speaking also on the default purple dot 🟣 for the default card

**Comment by mairin** [comment]
> ah yes I forgot for the background
> 
> I was speaking also on the default purple dot 🟣 for the default card

Ah whoops I misunderstood! I don't know, I don't know if the purple dot 🟣 is super clear what it means, but it's also not overly loud so I think it's ok as-is.
