### ISSUE TITLE
DOM checkbox element does not represent the actual checkbox in the application

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#5605]
### Bug description

It seems that the DOM elements that are marked as `type=checkbox` for the containers/images/pods pages in the application do not represent the actual checkboxes that the user interacts with, insteadit seems it's an 1x1 pixel element to the left of the checkbox. Please see attached video, this issue impacts e2e test development of those pages.

https://github.com/containers/podman-desktop/assets/106525396/c3d2afd2-87c1-4554-9f5e-4f7075df72c9

### Operating system

macOS

### Installation Method

None

### Version

1.6.3

### Steps to reproduce

1. Go to containers/images/pods pages that are poopulated.
2. Inspect element on the checkbox in one of the rows
3. Navigate the DOM and see that when scrolling of the `type=checkbox` element, it's not the actual checkbox.

**Comment by benoitf** [comment]
for checkboxes it's because to customize the display, it adds a new UI (else checkboxes are provided by the browser implementation)

but if you grab the input programmatically, you can click on it, etc it should work fine

**Comment by benoitf** [comment]
also there is a 1:1 binding between the real input field and the displayed div box so the states are the same

**Comment by cbr7** [comment]
@benoitf yeah the states are the same, I noticed that because I was able to check the `isChecked()` value from it, but I was not able to interact with it via clicking action programmatically.

**Comment by benoitf** [comment]
if you retrieve in your case the input checkbox with label "Toggle container" and send then a 'click' event on it, it should work as expected
