### ISSUE TITLE
Hide the endpoint path from the summary, only show it in the detail

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#5608]
### Is your enhancement related to a problem? Please describe

Currently the path is truncated, just before the name of the actual file.

![podman-desktop-resources](https://github.com/containers/podman-desktop/assets/10364051/8b6573ea-14df-4c08-aa88-9d2ca2288870)

The "podman.sock" got truncated, only root paths like "docker.sock" fit.

### Describe the solution you'd like

It should probably hide the endpoint path by default, and leave it to details ?

It was a side effect of making them more similar for containers/kubernetes.

* https://github.com/containers/podman-desktop/issues/4727

**Comment by afbjorklund** [comment]
Another idea that came up, was to convert the path into a complete URL with a "Copy" button.

```
Name         URI                                                            Identity                                                                              Default
default      unix:///run/user/1000/podman/podman.sock                                                                                                             true
lima-podman  unix:///home/anders/.lima/podman/sock/podman.sock                                                                                                    false
```

That way you can retrieve the address, and pass it to external tools to configure their host/url?

e.g. `docker --host unix:///run/user/1000/podman/podman.sock version`

Example given was Phpstorm, to use Podman Desktop's `unix:` instead of their `tcp:` example:

https://www.jetbrains.com/help/phpstorm/podman.html#tutorial-run-podman-in-a-virtual-machine

----

Similar to this, for image names:

* https://github.com/containers/podman-desktop/issues/4241

**Comment by trmendes** [comment]
I'm new to Podman and Podman-Desktop and I would like to sign myself to work with this issue.

I already have a [wip draft pr](https://github.com/containers/podman-desktop/pull/5687) for the copy button and, I would like to know what are the rules to convert the path into a complete URL based on the type of resource.

**Comment by benoitf** [comment]
I think copying the path would be enough as 'complete URL' depends on the usage or where you put that. (or it means we would need a kind of dropdown selection when you click on the copy button to transform it to a `unix://` or `npipe` link or just get the filesystem path, etc) 

if you would like to add the prefix (I'm fine with both ways) it's mostly based on the operating system (mac and linux will have the `unix:` prefix and windows the `npipe:` prefix)

**Comment by trmendes** [comment]
I would like to discuss what I have here and look for possible alternatives. :D

To read which OS I'm running Podman Desktop on, I need to make a call to ```window.getOsPlatform()```. And ```window.getOsPlatform()``` returns a ```Promise<string>```.

The solution I've found in the Svelte documentation is to use the [{#wait promise}](https://learn.svelte.dev/tutorial/await-blocks), but I can't find any usage of such on Podman-Desktop.

Is the usage of ```{#wait promise}``` something we would like to avoid? If, yes! Any suggestions?

The code will look like:

```
{#await getResourceEndpointURI(container.endpoint.socketPath)}
{:then socket}
  <div
    class="mt-1 my-auto text-xs truncate"
    class:text-gray-900="{container.status !== 'started'}"
    aria-label="{container.name} endpoint"
    bind:this="{copyTextDivElement}"
    title="{socket}">
    {socket}
  </div>
  {:catch error}
  <div
    class="mt-1 my-auto text-xs truncate"
    class:text-gray-900="{container.status !== 'started'}"
    aria-label="{container.name} endpoint"
    bind:this="{copyTextDivElement}"
    title="{container.endpoint.socketPath}">
    {container.endpoint.socketPath}
  </div>
{/await}
```
