### ISSUE TITLE
No feedback when deleting multiple instances

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5615]
### Is your enhancement related to a problem? Please describe

When you delete 1 of something (except for images, volumes - separate issues open) there is a spinner in the UI to show you that it's in progress. This stops you from trying to delete it again or wondering if your click worked.

When you delete multiple objects, there's no feedback. It's just pause, pause, pause, gone.

### Describe the solution you'd like

Deleting multiple objects should set the same deleting status that deleting a single object does, so that you know it's still in progress.

**Comment by trmendes** [comment]
One thing I notice is that when I press delete on a single image (row delete icon), the delete button turns gray, and a spin icon appears telling me the action is happening but, the play button, still clickable. If I click, I'm taken to a blank page.

Back to the description of this task.

The final expected result for a PR is to have the bunk delete button to have the same behavior that we have with the single button, correct? My first question is: beside the spinner and the gray/unclickable icons, shall the bunk deletion also present a dialog questioning the user about the “sureness” of such action?

**Comment by deboer-tim** [comment]
> One thing I notice is that when I press delete on a single image (row delete icon), the delete button turns gray, and a spin icon appears telling me the action is happening but, the play button, still clickable. If I click, I'm taken to a blank page.

This issue would correctly set the state of every selected object to 'deleting' so those other actions would have a chance to change their state, but if the actions are enabled during individual deletion the behaviour will be the same. Please open a separate issue with any action(s) are enabled when they shouldn't be, on which objects (containers, pods, images etc) and we can fix.

> The final expected result for a PR is to have the bunk delete button to have the same behavior that we have with the single button, correct?

You can see the video in the PR for the problem I was trying to fix: each object would now get marked as being deleted. If it takes a couple seconds the user still knows what's going on and other actions can change their enablement.

>  My first question is: beside the spinner and the gray/unclickable icons, shall the bunk deletion also present a dialog questioning the user about the “sureness” of such action?

The reason we added the confirmation dialog for deleting individual objects is that it is way too easy to e.g. miss the play button on the right and delete something. Since multi-delete requires clicking on individual checkboxes and then clicking delete in a different part of the screen we felt it's far less likely to be an accident, but if you think a dialog would still be useful please open up another issue.

**Comment by trmendes** [comment]
Thank you @deboer-tim for the answers.

I've checked your PR too :), and I'm going to raise a ticket to have the actions disabled when deleting is in process.

Thanks once again.
