### ISSUE TITLE
nav extension for docker desktop extensions issues

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5618]
### Bug description

- 1. it's displayed even if I don't have any Docker Desktop extensions (so I click on it and I have an empty state)

IMHO if there is none, we shouldn't display it at all

https://github.com/containers/podman-desktop/assets/436777/bf8c6910-5405-4eec-81a8-4dacafcc3a4d

- 2. if there is only extension, it should be in expanded state (why click on an item that is taking the same height)
![image](https://github.com/containers/podman-desktop/assets/436777/cdac0c49-cc17-41e6-9f2b-aa1e27430d22)

- 3. Clicking on the item is moving the height of the component

https://github.com/containers/podman-desktop/assets/436777/474bf713-6813-4c17-8849-ca80b2b2fc03

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

**Comment by axel7083** [comment]
https://github.com/containers/podman-desktop/assets/42176370/9b051b31-ea85-4133-a2be-ae8f96d26e1c

Some issue with the webview registered from the podman-extensions api not being included. 

- Is this only for `docker extension` ?

**Comment by afbjorklund** [comment]
> IMHO if there is none, we shouldn't display it at all

The new "puzzle" icon does seem a bit shy, if you click on it - it just goes away, without saying anything*.

![pd-before](https://github.com/containers/podman-desktop/assets/10364051/8183244c-d8d7-4e9a-b8c0-aaf97b7a4b8c) -->  ![pd-after](https://github.com/containers/podman-desktop/assets/10364051/caabad54-3a62-4b93-b65d-dd699e53b703)

\* OK, there was a hover effect saying "Desktop Extensions"

The behaviour doesn't match the other icons, in the panel.

**Comment by mairin** [comment]
> > IMHO if there is none, we shouldn't display it at all
> 
> The new "puzzle" icon does seem a bit shy, if you click on it - it just goes away, without saying anything*.
> 
> ![pd-before](https://github.com/containers/podman-desktop/assets/10364051/8183244c-d8d7-4e9a-b8c0-aaf97b7a4b8c) -->  ![pd-after](https://github.com/containers/podman-desktop/assets/10364051/caabad54-3a62-4b93-b65d-dd699e53b703)
> 
> \* OK, there was a hover effect saying "Desktop Extensions"

Ah I'd expect the puzzle to persist. Don't be shy little guy!

**Comment by afbjorklund** [comment]
You _could_ imagine it to go to the Settings, like the flower icon for Settings > Resources.

i.e. one icon for adding more extensions, plus one icon for each installed DD extension

![pd-icons](https://github.com/containers/podman-desktop/assets/10364051/6f8fe766-067b-4d25-8824-bfebbfcdc2cc)

**Comment by deboer-tim** [comment]
I caused this, so I can fix it. First fix: if there are none, we won't show it.

Some questions on the rest though:
- What's the correct behaviour if there is only 1 nav item in the section? IMHO having to open is odd and annoying to the user, so I would say we just show the 1 extension on its own and add the section when there are 2.
- Webviews were added while this was in review. Should they be included in this section (or are they their own future section)? If they are included, what's the new name? Just 'Extensions'? (IMHO there is only 1 webview and it doesn't fit the current section so we could always defer this to next sprint)

**Comment by benoitf** [comment]
> What's the correct behaviour if there is only 1 nav item in the section? IMHO having to open is odd and annoying to the user, so I would say we just show the 1 extension on its own and add the section when there are 2.

speaking for myself, I think I prefer expanded by default (section mechanism is there but I don't have to click to see the icon/extension)
If for example I add a new extension it's keeping the behaviour and I see all the time how it may work (that we have a toggle)
