### ISSUE TITLE
Volumes E2E Test implementation

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#5626]
### Is your enhancement related to a problem? Please describe

Implement test cases covering Volumes related functionalities.

### Describe the solution you'd like

Cover the following cases:
- TBD after exploratory testing of the feature

**Comment by trmendes** [comment]
I would like to work on this task, but I have some questions.


I'm new to Podman and Podman Desktop, so, I'll list what I understand from the task and the tests I have in mind. Please correct me if I'm going through the wrong assumptions.


# Description

Implement an e2e smoke test to cover some Volume Panel functionalities.

The e2e tests should follow the structure found in folder './tests/src'.

# Test Cases

Create a new volume.

1) Verify if there is no volume with the same name already created.
2) Create volume.
3) Verify if volume is created and listed.

## Delete volume

1) Verify if volume exists.
2) Delete volume
3) Verify if the volume is deleted and not listed.

**Comment by trmendes** [comment]
Hi @cbr7. I would like to know if I'm following the right path to implement this task. It would be helpful to me if you could share some hints and take a look at the [draft PR](https://github.com/containers/podman-desktop/pull/5697) I created?
