### ISSUE TITLE
Webview default font style

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5629]
### Bug description

From the line bellow, the podman-desktop is enforcing a specific `font-family` for the body.

https://github.com/containers/podman-desktop/blob/aac0be1cb377d39c30fc928012acc79c93afc48b/packages/preload-webview/src/webview-preload.ts#L76 

Here is the result of this line in the webview 

| `font-family: Montserrat;` | `font-family: none` |
| --- | --- |
| <img width="226" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/5e20d524-9d8d-4fe4-97da-f22d06b137fa"> | <img width="236" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/45f147c8-f53d-48d8-8aba-360311bc6923"> |

### Operating system

Windows 11

### Installation Method

None

### Version

1.6.3

**Comment by benoitf** [comment]
it's the Podman Desktop core font

**Comment by benoitf** [comment]
probably the webfont part is missing

**Comment by axel7083** [comment]
Are we sure the podman-desktop is using this one ? Because  when selecting a random title, and filtering on `font-family` I am not getting the one expected.

<img width="1043" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/3075bd6d-e881-4320-93bf-20b047592f9f">

## Small experiment

When applying manually the `font-family` on a title in the podman-desktop dashboard here are the result

| Nothing applied (default) | Using `Montserrat` |
| --- | --- |
| <img width="152" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/3a027890-a6a0-4f23-8129-866fa7af9e13"> | <img width="137" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/4bfeec2b-b754-42e2-808e-a5f6f2267774"> |
