### ISSUE TITLE
allow extensions to create CancellationTokenSource

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5651]
### Is your enhancement related to a problem? Please describe

Extensions should be able to create CancellationTokenSource.

### Describe the solution you'd like

Create CancellationTokenSource and use the corresponding id to provide it to long running tasks such as PullImage and BuildContainer

**Comment by benoitf** [comment]
Issue is around that in .d.ts CancellationTokenSource should be a class so that people can do 

```
new podmanDesktopAPI.CancellationTokenSource();
```

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/6557
