### ISSUE TITLE
Ability to apply a Kube YAML file to the cluster

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5661]
### Is your enhancement related to a problem? Please describe

We have a Play Kubernetes YAML button in the Containers and Pods views, but nothing similar in the Kubernetes nav pages.

### Describe the solution you'd like

When you're in the new Kubernetes pages it would be really handy to have a button to quickly select a YAML file and apply it to the cluster.

**Comment by odockal** [comment]
@deboer-tim Do we need to make sure to have this covered with e2e tests? I am not quite sure I understand where this new feature will land, new Kubernetes page? It is play kube yaml page or somewhere else?

**Comment by deboer-tim** [comment]
@odockal the only thing that this will surface is an 'Apply YAML' button on Deployment/Service/Ingress pages that will do the equivalent of `kubectl apply -f`. Both the button (PR #5901) and underlying logic (#5849) will have their own unit tests so I'm not worried directly about the function, but it would be good to have an E2E test that would use this button and confirm that the resources appear back in the UI.

Ideally we could include this in any cluster (kind/minikube/etc) test flow - e.g. use the button to create the Service/Deployment that you want to test next.
