### ISSUE TITLE
Minikube and Kind Cluster restart from Details page hangs and throws error in dev console (HTTP Code 304)

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5666]
### Bug description

I can setup a minikube cluster and start it. I can restart it from Resources page just fine, but If I want to restart it from Details page, it hangs there - restarting in progress, there is also an error in the dev console HTTP code 304. If one leave the details page, the state is correctly shown then.

Kind seems to have the same problem.

### Operating system

Mac OS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install minikube
2. Create minikube cluster
3. Enter minikube resource details
4. Restart the cluster
5. Assert: Restarted successfully without any errors -> It got state running
Actual result: The restart button is still in progress, The state is stuck on starting (I think), error in dev consolse

**Comment by odockal** [comment]
I have recorded the behavior, it also shows off some xterm errors when opening logs of the restarted kind cluster.
![kind_restart_details_error](https://github.com/containers/podman-desktop/assets/19164299/fd6b0cf5-dee0-435f-85a5-152d32fdab2d)

**Comment by rostalan** [comment]
present on win 10.
