### ISSUE TITLE
Deploying to Minikube cluster is missing a namespace to pick after cluster restart (or some other manipulation with its state)

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5667]
### Bug description

After some time with playing with minikube cluster and its kubecontext, it seems that once I try to deploy to Kubernetes (with minikube context set) it is missing a namespace field in the form and it throws and error: ECONRESET and I cannot deploy the container to the cluster.

### Operating system

macOS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Create and start minikube cluster
2. Switch to minikube kube context
3. Create a container
4. Deploy Container to Kubernetes
5. Assert: Kube context set is minikube
6. Assert: Namespace field offers default namespace to deploy pod/container to
7. Restart minikube
8. Assert 5 and 6 again and deploy app
Actual result: namespace is missing in the deploy to kubernetes page, deploying leads to error: ECONRESET

### Additional context

@cbr7 If you could please also add some specification of your findings.

**Comment by benoitf** [comment]
minikube extension is not in this repository so minikube issues should go to https://github.com/containers/podman-desktop-extension-minikube/issues

**Comment by odockal** [comment]
@benoitf thx.
Opened one there: https://github.com/containers/podman-desktop-extension-minikube/issues/25.
Closing here.
