### ISSUE TITLE
Podify fails if container has a mount type volume

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#5668]
### Bug description

Trying to follow the [redis-python-app](https://github.com/odockal/podman-desktop-qe/blob/main/docs/scenarios/suites/multi-container-apps.md#create-a-python-frontend-app-with-redis-backend-official-redis--demo-frontend).

Using quay.io/centos7/redis-5-centos7 and quay.io/slemeur/python-app as containers, when I try to podify them into a single application, I get a `crun mount` error and `redis` container fails to start

### Operating system

Windows 10 22H2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

* Download and install podman-desktop v0.0.202401231458-a739864
* Create a rootful machine
* Pull both images, create containers, with python-app add redis as an extra host
* Verify the application is running correctly
* In containers view, select both containers and try to podify them

### Relevant log output

```shell
Error: starting container <id1>: crun: mount '/var/lib/containers/storage/columes/<id2>/_data' to `var/lib/redis/data`: No such device: OCI runtime error
```

### Additional context

![Podman_Desktop_xOOBrVoMZy](https://github.com/containers/podman-desktop/assets/16451875/3b931fa4-bef6-47b2-b56a-d144b5eba75b)
![Podman_Desktop_jaxjAAdrZo](https://github.com/containers/podman-desktop/assets/16451875/97b1387d-6770-49b5-8bfa-b435840aba7f)

**Comment by ScrewTSW** [comment]
locally built images from https://github.com/redhat-developer/podman-desktop-demo/tree/main Dockerfiles seem to be working correctly

**Comment by benoitf** [comment]
could you try with the images `quay.io/podman-desktop-demo/podify-demo-backend:v1` and `quay.io/podman-desktop-demo/podify-demo-frontend:v1`

these one are built by the CI

**Comment by benoitf** [comment]
can it be related to https://github.com/containers/podman-desktop/pull/5640 @lstocchi or not related ?

**Comment by jeffmaury** [comment]
Don't reproduce with deployed images but I'm using Podman 4.8.3

**Comment by lstocchi** [comment]
> can it be related to #5640 @lstocchi or not related ?

it could be as that PR fixed a problem with the mounting but then even before it was not working properly because it was missing the mounting part. We have to verify

**Comment by odockal** [comment]
> could you try with the images `quay.io/podman-desktop-demo/podify-demo-backend:v1` and `quay.io/podman-desktop-demo/podify-demo-frontend:v1`
> 
> these one are built by the CI

I think that with these images it works. At least given that we are using the images in play kubernetes yaml test.

**Comment by odockal** [comment]
Pod created from above mentioned demo images is spinning up correctly.

**Comment by odockal** [comment]
@ScrewTSW It is still an issue? Or can we close as out-of-date?

**Comment by ScrewTSW** [comment]
> @ScrewTSW It is still an issue? Or can we close as out-of-date?

I don't remember seeing that during the last testing session. I'll re-test and close as out of date if appropriate

**Comment by kdubois** [comment]
it's still an issue when trying to podify containers that have a mounted volume.  This is with Podman Desktop v1.11.1.  

![image](https://github.com/containers/podman-desktop/assets/373537/43cbcaee-da9a-4328-9ba2-8d4ed948a5a8)

If I use the podman CLI directly it works. eg. 

```
podman pod create mypod
podman run -d --pod mypod \
    --name postgres \
    -e POSTGRES_DB=quarkus -e POSTGRES_USER=quarkus -e POSTGRES_PASSWORD=quarkus \
    -v pg-data:/var/lib/postgresql/data:Z \
    --replace docker.io/library/postgres:14
podman run -d --pod mypod --name quarkus-app \
    -e QUARKUS_DATABASE_USERNAME=quarkus -e QUARKUS_DATABASE_PASSWORD=quarkus -e quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus?loggerLevel=OFF \
    --replace quay.io/kevindubois/quarkus-observability:latest
```

**Comment by kdubois** [comment]
@benoitf this is the same issue I mentioned last month in slack, fyi.

**Comment by jeffmaury** [comment]
Upstream issue: https://github.com/containers/podman/issues/23337
