### ISSUE TITLE
truncate long usernames in registries page

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop#5670]
### Is your enhancement related to a problem? Please describe

Usernames of registry users can be long, especially when machine-generated such as the registry-service accounts used by the Red Hat auth plugin (see https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/26).  Since names are displayed entirely, it can mess up the interface a bit.

### Describe the solution you'd like

Truncate long usernames (maybe even long registries as well) and expand them on demand.

### Describe alternatives you've considered

I haven't considered any other alternative.

### Additional context

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/9eeec119-a729-45b1-874d-05d8d5756b84)

**Comment by vrothberg** [comment]
Wow, that was super fast.  Thanks a ton, @deboer-tim !

**Comment by deboer-tim** [comment]
You made Podman stable on my machine, fixing a minor UI issue is the least I can do. ;-)
