### ISSUE TITLE
weird hover animation of nav sections

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5671]
### Bug description

The hover animation on extension is kinda weird, it does not take the full width nor the height, and make a weird rectangle

https://github.com/containers/podman-desktop/assets/42176370/462aab1f-753d-4212-81c1-352f612c1c30

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by deboer-tim** [comment]
I've found a couple other minor issues, fixing.

**Comment by axel7083** [comment]
Fixed
