### ISSUE TITLE
Deployed pods not visible after restarting k8 clusters

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#5675]
### Bug description

If the user has a container deployed into a k8 cluster (like kind of minikube) and then turns off the clusters and afterwards starts it back up, the deployed pods will no longer be visible in the Pods page until after the user forces a k8 context change in the application.

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

1. Have kind and minikube k8 clusters available.
2. Deploy a container to kind cluster.
3. Pod should be visible in the Pods page.
4. Turn off the kind cluster either by turning off the control plane container from Containers page or from Settings -> Resources.
5. Turn the kind cluster back on.
6. Go to Pods page.
7. Notice that the deployed pods are no longer visible.
8. Switch k8 context to minikube
9. Switch back to kind cluster
10. Notice pods are again being displayed in the Pods page.

**Comment by deboer-tim** [comment]
This sounds the same as the second point in #5311. Good to track it directly here, and likely indicates it's not related to the new informers.
