### ISSUE TITLE
Cannot delete a pod from Kubernetes cluster from Pods page

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5678]
### Bug description

I am deleting a kubernetes pod from a microshift cluster (Created using Microshift Local) in Pods Page. It takes a while and the pod is not eventually deleted. There is an error in the dev console.

`Uncaught Error: Error invoking remote method 'kubernetes-client:readPodLog': Error: an object cannot be cloned`

Similar issue: #2561

### Operating system

Mac OS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Additional context

If I try to again delete the pod, it shows an error icon next to delete button saying the pods was not found. Which suggest that pod was truly deleted. Force refresh then correctly shows no pod. It seems like UI issue. 

Second time I could not reproduce this issue with deleting a pod at all. It gets delete without any issue.

**Comment by gastoner** [comment]
Cannot reproduce  


https://github.com/user-attachments/assets/cd7b10af-1a15-49cb-bef2-4b716b07a952


cc @odockal
