### ISSUE TITLE
improve kind feedback when falling to create a cluster

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5688]
### Is your enhancement related to a problem? Please describe

When something went wrong while creating a kind cluster, logs disappear, and leave the user frustrated with the only logs "exit with code 1".

### Describe the solution you'd like

https://github.com/containers/podman-desktop/assets/42176370/be435192-41e7-451c-97bf-637e8471b471

- Keeping the logs
- full logs

### Describe alternatives you've considered

Running the command manually (annoying)

**Comment by trmendes** [comment]
Hi @axel7083. I would like to take a look and be assigned to this issue.

Could you share the steps to have a kind cluster failure during its creation?

**Comment by benoitf** [comment]
probably we should as first step do not hide the logs window

**Comment by axel7083** [comment]
> Hi @axel7083. I would like to take a look and be assigned to this issue.
> 
> Could you share the steps to have a kind cluster failure during its creation?

Hi @trmendes thanks for taking some time !
Here is an easy step to make the kind cluster creation failing
- Resources > (kind) Create new > Set a random string inside the `Node’s container image` text input.

This will result in the creation failing.

> probably we should as first step do not hide the logs window

Yes that would be nice, and probably enough for the user to understand what is happening.
