### ISSUE TITLE
podman-desktop api withProgress not have failure status when report message

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5711]
### Bug description

When running 

```ts
void podmanDesktopApi.window.withProgress<void>(
  { location: podmanDesktopApi.ProgressLocation.TASK_WIDGET, title: `Pulling ${recipe.name}.` },
  progress => {
    progress.report({message: `Something went wrong.`});
  },
);
```

But inside the TaskManager the Task is marked as completed

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by benoitf** [comment]
we discussed in the initial PR


the root problem is that we can't assume that `progress.report` is to report an error
The API clearly state that it's to report a progress not to report an error.

So from an extension I can add messages like
```
progress.report({ message: 'Initializing...'});
progress.report({ message: 'Building..'});
```

it should just update the notification text.

I'm not sure as a user you should write as much as you copied in the two samples

if there is an error during the task, it needs to throw an Error (for example complicatedTask could report the error)

I think what user is expected to write should be something like this instead
```ts
await window.withProgress<void>(
      { location: podmanDesktopApi.ProgressLocation.TASK_WIDGET, title: `Running stuff` },
      async progress => {
          // might throw an error
          await complicatedTask(recipe, model);
          // mark the task as completed
          progress.report({ increment: -1 });
      },
    );
```
then it could be captured by upper error handling that would add the error to your 'own' error handling system

or if you really need for each call:
```ts
try {
podmanDesktopApi.window.withProgress<void>(
      { location: podmanDesktopApi.ProgressLocation.TASK_WIDGET, title: `Running stuff` },
      async progress => {
          // might throw an error
          await complicatedTask(recipe, model);
          // mark the task as completed
          progress.report({ increment: -1 });
      },
    );
} catch (error) {
   setError(error); // our own error system must be alerted
}
```




(error message should be extracted from the error reported by complicatedTask for example)


so if it's not working like that, need to fix the implementation side

**Comment by axel7083** [comment]
Closing in favor of https://github.com/containers/podman-desktop/issues/5730
