### ISSUE TITLE
Is it possible to switch to a different language for the GUI of this application?

### ISSUE THREAD

**Issue by MING-LI-JIANG** [containers/podman-desktop#5726]
### Is your feature request related to a problem? Please describe

Is it possible to provide different regional languages ​​for the "Podman Desktop" User Interface?

### Describe the solution you'd like

It is hoped that the language change option of the user interface can be added to the "Preferences" in the settings function.

### Describe alternatives you've considered

Using the Kubernetes Dashboard.

**Comment by benoitf** [comment]
hello @MING-LI-JIANG there is no customization of the language in Podman Desktop

you're saying Docker Desktop has one ? I thought it was also all in english.

**Comment by MING-LI-JIANG** [comment]
Hmm...sorry @benoitf  I remembered it wrong!!

**Comment by benoitf** [comment]
BTW @MING-LI-JIANG what would be the language you would expect ?

**Comment by MING-LI-JIANG** [comment]
> 順便說一句，你會期待什麼語言？

It should be Japanese.

**Comment by MING-LI-JIANG** [comment]
@benoitf 
It should be Japanese.
