### ISSUE TITLE
registry icons seems to be gone

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5742]
### Bug description

This is the current screenshot:

![image](https://github.com/containers/podman-desktop/assets/436777/4acc7392-8451-4f43-b383-3047d2d79bc9)

but at some point we got icons for registries being displayed

### Operating system

macOS 14

### Installation Method

None

### Version

1.7.0

### Steps to reproduce

go to the registry page and see it is missing

**Comment by deboer-tim** [comment]
+1. I noticed this on the weekend too and thought maybe I had remembered wrong.
