### ISSUE TITLE
Share code for bulk deletion

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5745]
### Is your enhancement related to a problem? Please describe

From discussion in #5717: there's lot of similar code for bulk deletion on every page - is it possible to share code?

### Describe the solution you'd like

At a minimum, utility function(s) for marking object status or handling the promises. Would be cool if there's a way to have some kind of 'bulk action helper' that would help with button state and act on all the objects.

**Comment by trmendes** [comment]
@deboer-tim I would like to work on sharing the code.

I'm creating a draft PR as 1st attempt so, I can do the right changes and make a better code to share.

[Would you mind reviewing it?](https://github.com/containers/podman-desktop/pull/5847) 

I would love to get some feedback and new ideas.

I wanted to give the common function the deletion callback as a parameter, but I'm not sure what would be the best way to handle function with different signatures.
