### ISSUE TITLE
Installing via link is missing install feedback

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5759]
### Is your enhancement related to a problem? Please describe

If you try to install an extension via a Podman Desktop link like podman-desktop:extension/redhat.redhat-authentication, the page allows you to install the extension, but still has an Install button afterwards, making the user think that maybe the installation didn't work.

### Describe the solution you'd like

When an extension is installed (could be already installed, or via the button) the button should disappear and be replaced with an appropriate message like 'v1.0 installed'.

**Comment by benoitf** [comment]
checked and issue only exists is if extension is registered in the catalog under a name different than the package.json name

need to add a check in the catalog probably
