### ISSUE TITLE
Website header is too wide

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#5761]
### Is your enhancement related to a problem? Please describe

Often when I go to our website my browser is not full screen and this is the first thing I see at the top:
<img width="1330" alt="Screenshot 2024-01-24 at 1 42 07 PM" src="https://github.com/containers/podman-desktop/assets/19958075/9da195b7-aa15-47c0-848a-259494ee988a">

Notice that core values wraps to two lines, and our name is cut off. :(

### Describe the solution you'd like

@slemeur @mairin how do you feel about any of these options?

- Reduce font size of the headers (they are larger than most sites I see).
- Rename 'Core Values' to just 'Values' or anything shorter.
- Remove one of 'Core Values', 'Features', or 'Extend' (embed fully in or link from another page).
- Reduce size of 'Podman Desktop' :(

**Comment by mairin** [comment]
Let me go thru one by one, just high level talk from a UX pov:

- "Documentation" could be shortened to "Docs"
- Core Values could be integrated into the front page easily
- Features is a bit redundant with the features section we have on the front page 
- Downloads - keep as is imo
- Extend - i think keep, we could eventually have an online extension catalog here + a howto make your own extensiom area with dev docs
- Blog - fine as-is but i would have latest post on front page to draw over to it

**Comment by axel7083** [comment]
I think we can _clearly_ remove the `Core values` tab as mention @mairin they can be integrated elsewhere, having a full dedicated page about that, feel kinda empty when reading it.

**Comment by axel7083** [comment]
Re-opening as still relevant
