### ISSUE TITLE
Experiment: Recommendations for extensions

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5771]
# Items
- [x] https://github.com/containers/podman-desktop/issues/6174

## Introduction
Podman Desktop supports extensions.

**The extension discoverability challenge**
The developers who are using Podman Desktop might not be able to easily discover extension which could be beneficial and helping them on their flows. Podman Desktop provides a catalog for the extensions, but the developers are not going to constantly look at the catalog and see if there are new extensions that have been added. 

**The recommendations of additional tools**
For developers, it'd convenient to have recommendations on extensions which could be helping them in their flows. This concept of extension recommendation exist in VSCode and appears to be well adopted by the developers. Indeed, it's an non-obtrusive way to interact with the developer and bring awareness about tools that might be helping exactly at the time it would be helping out. 

## Overall solution for Podman Desktop
We should be introducing recommendation API for the extensions, so they Podman Desktop could be surfacing the extension in certain flows.

#### Recommendations Notification
A simple notification popping from the bottom right corner. 
Displaying a message:
"The extension {name} would help you to achieve: {use_case}. "
There would be two buttons:
[Install] [Show Recommendations]
It would be possible to close the notification too.

#### Recommendations Summary Page
A basic page in the settings that allow to list the displayed recommendations. 

#### Recommendations Settings
Provide the ability for the end user to enable/disable the recommendations

### When pulling images from a particular URL
As a developer, I’m trying to pull from a registry that requires authentication, but I’m not authenticate and I don’t have corresponding SSO extension.
{use_case}: Pulling from registry
→ Display a notification to point the user to install either the corresponding authentication extension

Ideally, we would like to detect that, even when the user is doing the pull from a CLI command

### When willing to experiment with Kubernetes
As a developer, I don’t have a Kubernetes Environment available, but I want to try it out.
{use_case}: Getting a Kubernetes environment
→ Display a notification about the available extensions that provide a kubernetes environment local or remote for development purposes

### When interacting with certain base images
As a developer, I’m using an image that is based on a particular layer, in this case, I’m interested by recommendations that are helping me using this particular type of base image

### When interacting with certain Kubernetes Environments
As a developer, I’m deploying interacting with a certain type of Kubernetes Environment where extensions have been built to facilitate working with that environment. In this case, we should also show a recommendation notification.

**Comment by vrothberg** [comment]
> When pulling images from a particular URL

One thing I want to highlight here is how Podman resolves short names of images.  A Dockerfile or image pull may just refer to `name` as the image.  When going through the Docker-compat REST API of Podman, the image will be resolved just as Docker does and always point to docker.io.  When using the libpod API, it will resolve the image as descriped in the following blog: see https://www.redhat.com/sysadmin/container-image-short-names

That means that `podman pull name` may resolve to any registry.  All aliases are stored in `/etc/containers/registries.conf.d/000-shortnames.conf`.  I feel like the cleanest way to approach the problem is to add a new libpod endpoint for resolving an image name.  The input argument is a string (image reference) that gets resolved.  This way, Podman Desktop can just call this API.

**Comment by benoitf** [comment]
@vrothberg I think it's also missing events 

if I'm on CLI and perform `podman run registry.redhat.io/ubi9`

I will get (if unauthenticated) 
```
Trying to pull registry.redhat.io/ubi9:latest...
Error: initializing source docker://registry.redhat.io/ubi9:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

but if for example I subscribe to events (or Podman Desktop for example) using `podman events`

there is no event like `'pull-error', image: 'registry.redhat.io/ubi9', error: {unable to retrieve...}`

(and here in the event we should have the image being pulled in the FQDN form)

I think we should be event driven and not be waiting an action for a user only inside Podman Desktop

so if you go back to Podman Desktop you could have the recommendation as we detect what you're doing on the CLI. But we have events on pull only on success while we would need events on error as well.

**Comment by vrothberg** [comment]
@benoitf trying to include CLI use cases is an interesting idea!  At the moment, I am only looking at the use case to prompt _before_ things go wrong.  Parsing errors after the fact is certainly something to tackle as well.  If we can include the CLI at some (e..g, via events as you suggested) is a bit over my head at the moment.
