### ISSUE TITLE
move macOS GitHub actions runners to arm64 runners for macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5772]
### Is your feature request related to a problem? Please describe

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

### Describe the solution you'd like

use the updated runner `macos-14` instead of `macos-12`

**Comment by trmendes** [comment]
The new M1 runner took 5:49 against  ~12:30 from the old runner. <3
