### ISSUE TITLE
Once we deployed a pod to kubernetes, open pod button is not working

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5774]
### Bug description

There is a button "Open Pod" after pod is deployed to a Kubernetes cluster

the link is not working

### Operating system

macOS

### Installation Method

None

### Version

1.7.0

### Steps to reproduce

Use podify and kubify scenario

When deploying to kubernetes, 'Open Pod' button is not working

Uploading Screen Recording 2024-01-31 at 13.04.40.mov…

**Comment by axel7083** [comment]
I can't reproduce, the step I followed

(1) I created a `kind` cluster
(2) run `podman run -p 8080:80 -d dockerbogo/docker-nginx-hello-world`
(3) in Podman-Desktop, container action -> `Deploy to Kubernetes` -> Wait -> Open Pod

It open properly the pods page

**Comment by benoitf** [comment]
I think I submitted the issue before it completed the upload so it's missing the content of the video. The main issue is about url encoding as I was using dev sandbox there are / in the kube context

With default minikube or kind you won't reproduce
