### ISSUE TITLE
Remove "Docker Compatibility" button for Linux for now

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5789]
### Is your enhancement related to a problem? Please describe

The Linux "docker compatibilty" button is broken for flatpak environments due to the sandbox permissions. I'm unsure what the long-term fix is, but you are unable to remove the compatibility mode warning.

It looks like this has been an issue since April 2023: https://github.com/containers/podman-desktop/issues/1928 and https://github.com/containers/podman-desktop/issues/5135

### Describe the solution you'd like

Remove for now until we get Linux compatibility working 100% in order to remove the 'permanent' warning that is happening.

**Comment by Malix-Labs** [comment]
> for flatpak environments

Note that this is also happening with the AppImage package
