### ISSUE TITLE
Move "Play Kubernetes YAML" to Pods section only, change description (it does not create containers, only pods).

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5802]
### Is your enhancement related to a problem? Please describe

The description / how we word Play Kubernetes YAML is incorrect.

When you play the YAML, you are only ever creating Pods within Podman or the Kubernetes cluster.

We are not creating standalone containers.

See the description of containers on the Kubernetes API:

![Screenshot 2024-02-01 at 9 21 03 AM](https://github.com/containers/podman-desktop/assets/6422176/027886e0-c013-4e6e-953c-a7da38474736)

We also have the button in the Containers section which doesn't make much sense..

I'm curious if there many people even pressing it.

### Describe the solution you'd like

* Move the button to Pods section only
* Change description of the button.

**Comment by cdrage** [comment]
ping @slemeur

**Comment by slemeur** [comment]
I'm fine with the changes, especially considering the additional kubernetes features being added.
