### ISSUE TITLE
Connection to podman machine gets distrupted when deleting another podman machine

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#5820]
### Bug description

The PD connection to the active podman machine gets disrupted if the user delete an unused podman machine from the application.

https://github.com/containers/podman-desktop/assets/106525396/e3c4fa7a-264d-4f0b-ba38-c749fe867a4b

### Operating system

macOS

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Have rootful podman machine running and available.
2. From PD create another rootful podman machine but don't start it.
3. After the new machine is created, delete it.
4. Try to pull any image from the PD Images page and notice that an error is returned.

### Additional context

The connection can be reestablished if the user stops and restarts the active podman machine.

**Comment by odockal** [comment]
It would be nice to see on cli what the actual `podman system connection ls` shows during these actions. I will try on windows as well.

**Comment by cbr7** [comment]
I was able to reproduce this issue on macOS with 100% repro rate, but when I tried on windows 11 no bug is encountered.

**Comment by feloy** [comment]
When deleting a machine, the socket is removed. But, if I understand correctly, this socket is shared by all machines, so Podman Desktop cannot access anymore the first machine through this deleted socket.

I created an issue on Podman project: https://github.com/containers/podman/issues/21899

**Comment by nichjones1** [comment]
@odockal can you retest in RC7

**Comment by odockal** [comment]
@nichjones1 sorry for responding late, forgot about it. Since we have/will move(d) to podman v5 this one is about to be out of date. We will take a look during testing.

**Comment by odockal** [comment]
@cbr7 Please take a look during the testing. You gotta get the reproducer in your memory.

**Comment by cbr7** [comment]
Issue is no longer reproducible with podman version 5 and up.
