### ISSUE TITLE
Support enabling Podman Machine detection on Linux 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5823]
### Is your feature request related to a problem? Please describe

See: https://github.com/containers/podman-desktop/discussions/5762

There are cases where creating a podman machine on Linux would be beneficial, such as monitoring / viewing a "root" podman machine to be able to run root containers.

### Describe the solution you'd like

Enabling podman machine for linux.

**Comment by feloy** [comment]
We will need to be **VERY** careful that this possibility is understood to be useful for very specific use cases (and make the native experience at least as good as the machine one on Linux), or Linux users will all switch to a machine, and I'm not sure this is what we want

**Comment by cdrage** [comment]
> We will need to be **VERY** careful that this possibility is understood to be useful for very specific use cases (and make the native experience at least as good as the machine one on Linux), or Linux users will all switch to a machine, and I'm not sure this is what we want

1000% agree. This is not an ideal scenario and is only applicable for certain use cases as well (needing to run a root container).

We could even put a large disclaimer that this is *not* an ideal scenario / not recommended, but the user can go ahead and do it anyways..

The reasoning for this is being able to create a linux podman machine with root support so we can run containers that manipulates filesystems / needs the host in order to create partitions, etc.

For Linux, it would be difficult to implement native sudo / root support, so podman machine would be a better / more straight-forward way for implementation: https://github.com/containers/podman-desktop/issues/2861

**Comment by afbjorklund** [comment]
The main reason was to not make Podman Desktop _worse_ on Linux, compared to what it is on Mac and Windows.

Otherwise you read about some new feature in Podman, but then find that it is not supported in _your_ old Podman?

https://podman-desktop.io/blog/wasm-workloads-on-macos-and-windows-with-podman

The whole reason for creating podman-machine was that I wanted to try it on ubuntu...

**Comment by afbjorklund** [comment]
> The reasoning for this is being able to create a linux podman machine with root support so we can run containers that manipulates filesystems / needs the host in order to create partitions, etc.

You don't need a VM for that, there is already a `podman.sock` for root

* https://github.com/containers/podman-desktop/issues/2861

Using docker has the same issue, unless you are using the rootless socket.

As in: `dial unix /var/run/docker.sock: connect: permission denied`

**Comment by afbjorklund** [comment]
The alternative is extending the support for Podman v3, while the other users are enjoying their Podman v5.

**Comment by cdrage** [comment]
> > The reasoning for this is being able to create a linux podman machine with root support so we can run containers that manipulates filesystems / needs the host in order to create partitions, etc.
> 
> You don't need a VM for that, there is already a `podman.sock` for root
> 
> * [Implement option to view rootful containers on Linux 🐧 #2861](https://github.com/containers/podman-desktop/issues/2861)

Unfortunately doing it that way would involve changing group permissions like you mentioned with regards to the root socket since it's read only. So it won't be straight forward from a "do it via an extension" perspective.

Since we are running PD as a flatpak on Linux, I believe it wouldn't be viable to modify the flatpak permissions and have podman desktop run as root in order to get access. We wouldn't be able to automate / do it through the UI and rather have to get the user to modify through CLI the permissions, etc.

Since `podman` actually supports running a podman machine under linux, adding this would actually be super beneficial for users who have a different podman installed on their machine, like your example on ubuntu.

**Comment by afbjorklund** [comment]
Currently you can start a "podman machine", with Podman Desktop, by using the Lima provider (through the CLI):

https://podman-desktop.io/docs/lima/creating-a-lima-instance - `limactl start template://podman`

It also allows using distributions other than Fedora CoreOS, for faster updates and (optionally) smaller footprint.

* https://github.com/containers/podman-desktop/issues/1638

**Comment by cdrage** [comment]
Notes from async meeting:

- Because of dependency issues across multiple platforms (example, Ubuntu does not package qemu-kvm with podman), we should not allow the creation of a podman machine WITHIN podman desktop, but instead have documentation that shows to create it depending on OS we support (example, this works well on fedora 39, but not on ubuntu).
- Podman Desktop will still detect podman machine's running on Linux and add it / detect them automatically, as well as be able to start / stop them. But not create them.

We should also implement #5828

**Comment by cdrage** [comment]
> Currently you can start a "podman machine", with Podman Desktop, by using the Lima provider (through the CLI):
> 
> https://podman-desktop.io/docs/lima/creating-a-lima-instance - `limactl start template://podman`
> 
> It also allows using distributions other than Fedora CoreOS, for faster updates and (optionally) smaller footprint.
> 
> * [Examples: Be able to use CentOS / RHEL / other operating systems for `podman machine init / start` #1638](https://github.com/containers/podman-desktop/issues/1638)

Thank you that's exactly it, there was a brief discussions with @benoitf that there is support for creating these podman machine's, etc with other extensions, but we should allow podman desktop to at least detect these machines.

**Comment by afbjorklund** [comment]
@cdrage : probably should change the title, to "allow using (but not creating) a Podman Machine"

It seems the common issue is that Podman is _supposed_ to be hard to install on Linux, no matter how?

**Comment by afbjorklund** [comment]
This feature seems to be missing documentation (it only links to podman.io, and that is about it)
