### ISSUE TITLE
Linux: Be able to select which machine to use for creating images (between local podman and podman machine)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5829]
### Is your enhancement related to a problem? Please describe

TODO ADD SCREENSHOT.

I'd like to be able to select between the podman machine and the local socket. 

### Describe the solution you'd like

Be able to select one of them to use by default.

**Comment by afbjorklund** [comment]
The podman mechanism for this is "system connection", unfortunately it is missing connections for the local sockets.

So it sets up the connections (rootless/rootful) for the machine, but is missing the ones for the default connections...

You can add: e.g. `podman-remote system connection add default unix://$XDG_RUNTIME_DIR/podman/podman.sock`

But Podman Desktop doesn't use podman system connections yet anyway, so it would still need a new mechanism.

**Comment by cdrage** [comment]
Ah so after exploring a bit. We DO have that option when building or pulling an image..

Just no way to disable the local socket / pick which one is the first one / default.

**Comment by afbjorklund** [comment]
It is even worse, Podman Desktop will always start _another_ copy of a local podman socket:

* https://github.com/containers/podman-desktop/issues/2903

**Comment by benoitf** [comment]
you'll have two connections provider, so in that case you're able to select the one you want

it's up to you to not say 'take the first connection' but select the one you want
