### ISSUE TITLE
Exposing getContainerStats to extensions

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5840]
### Is your feature request related to a problem? Please describe

Extensions cannot get containers usage (CPU/RAM)

### Describe the solution you'd like

Exposing a similar method that the renderer has access named `getContainerStats` in the extension api.

**Comment by benoitf** [comment]
@axel7083 looks like https://github.com/containers/podman-desktop/issues/6211 was a dup of this one, close this one then ?

**Comment by axel7083** [comment]
yes
