### ISSUE TITLE
uninstall fail and install cannot close podman desktop... and abort...

### ISSUE THREAD

**Issue by mcarbonneaux** [containers/podman-desktop#5852]
### Bug description

impossible to uninstall or install new version (installed version is v1.6.4).

when try to uninstall:
![image](https://github.com/containers/podman-desktop/assets/8479023/5c95680e-63af-4191-b631-99425eb24d95)

when try to install new version (1.7.0 or last build):
![image](https://github.com/containers/podman-desktop/assets/8479023/9297b771-d4c4-4416-a352-1f70d4c38401)

they say they cannot stop podman desktop (i've try by stoping manualy and after fail again i've remove wsl podman machine without succes).

retry fail too... and if i cancel they abort the install:
![image](https://github.com/containers/podman-desktop/assets/8479023/e3f24816-18bb-4ca9-b5ef-e21f612edc5f)

### Operating system

windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

install airgap v1.6.4 version...
and try to install v1.7.0 or last build...

### Additional context

how is detecting that podman desktop is started ?
how to remove manualy or force to install event if think is started ?

**Comment by benoitf** [comment]
@mcarbonneaux are you sure it's not running in the background check if there is no tray icon for Podman Desktop and click on the icon to exit

**Comment by mcarbonneaux** [comment]
the tray icon is exited also...
and i've searched any process in process explorer.... i found none...

the installer not explaine what they found and cannot stop...

there no debug trace to troubleshoot ?

**Comment by mcarbonneaux** [comment]
there debug trace somewhere to troubleshoot uninstall problem ?

**Comment by benoitf** [comment]
hello @mcarbonneaux you're still unable to install or uninstall ?

about the traces it's managed by the default installer/uninstaller provided by electron

did you tried the portable executable (no installer ?)

also maybe you could force the uninstall ?
or edit the registry like `Software\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by mcarbonneaux** [comment]
After tracing the execution with [Procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon?ranMID=46134&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-kntxxO6Udub3Pjvjy8Y4Vw&epi=a1LgFw09t88-kntxxO6Udub3Pjvjy8Y4Vw&irgwc=1&OCID=AIDcmm549zy227_aff_7809_1243925&tduid=(ir__tpxyvg1pnkkfdxhdpimoi6wzs22x9ramaagogtgm00)(7809)(1243925)(a1LgFw09t88-kntxxO6Udub3Pjvjy8Y4Vw)()) i think the problem is because Podman Desktop store the uninstaller in `C:\Users\<windows current user>\AppData\Local\Temp\nse4E13.tmp\old-uninstaller.exe` and my organisation bloc the execution of *.exe on temp.  why not store \AppData\Programs like the reste of the application ?

**Comment by benoitf** [comment]
About the location storage, etc it's currently managed by https://github.com/electron-userland/electron-builder

**Comment by jeffmaury** [comment]
If searched the registry and the uninstall program is located at:

"%USERPROFILE%\AppData\Local\Programs\podman-desktop\"

But maybe this one is creating some stuff in TEMP

**Comment by mcarbonneaux** [comment]
> About the location storage, etc it's currently managed by https://github.com/electron-userland/electron-builder

if i understand you use ecltron-builder (sorry but i'm not familar to electron) to build package to each platform.
and when i read de electron-builder documentation, i see that have multiple option in target on windows, and you've choose to use [nsis](https://nsis.sourceforge.io/) to build the package.

you don't have many native option to instruct how to package (in comparaison to installer like installshield/innosetup)... 
to go far than electron-builder basic option i think i must read nsis documentation, because electron-builder seem to permit to [custom nsis script](https://www.electron.build/configuration/nsis#custom-nsis-script)....

i think allowToChangeInstallationDirectory in nsis section seem to permit to choose where to install the application, in that way to avoid my problem (installation in temp directory)...

https://www.electron.build/configuration/nsis
```
allowToChangeInstallationDirectory = false Boolean - assisted installer only. Whether to allow user to change installation directory.
```

https://github.com/containers/podman-desktop/blob/990281d2f7719f5776783fbcd694af8073cba11b/.electron-builder.config.cjs#L117

but i'm not suffisantly skilled on electron to test that....
