### ISSUE TITLE
When running podman machine on linux, note machine vs native podman on environment column

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5858]
### Is your enhancement related to a problem? Please describe

While working on #5823 it worked being able to not only view the podman machine, but also the native podman socket.

The only problem is that on the column list... they both say "Podman".

### Describe the solution you'd like

On Linux, be able to differentiate between native podman and a podman machine.

### Additional context

![Screenshot from 2024-02-05 17-30-38](https://github.com/containers/podman-desktop/assets/6422176/c4110747-4869-4c34-a148-f9624742a332)

**Comment by afbjorklund** [comment]
This is a bug with the provider, it only shows the connection type but not the connection name:

* https://github.com/containers/podman-desktop/issues/5609

For Kubernetes (only), it passes the information - but for the containers it "varies" between objects.

It should show the type ("Podman"), and then the name ("Podman Machine") as mouse-over...

**Comment by benoitf** [comment]
The column shows the type so it's either docker or podman, Podman machine is still a podman thing.
so we should not add a new 'podman machine' type

**Comment by afbjorklund** [comment]
_Sometimes_, it shows the type (that's the bug). It should show as "podman", but it could provide the provider?

But the "engineId" is a bit cryptic, so it would be better to also pass the "engineName" for display purposes...

**Comment by afbjorklund** [comment]
@cdrage: docker contexts have the same issue, but I suppose if you fix one type you will fix both ?

"On Linux, be able to differentiate between native docker and a docker machine."

**Comment by cdrage** [comment]
> The column shows the type so it's either docker or podman, Podman machine is still a podman thing. so we should not add a new 'podman machine' type

If I have a container on the native podman socket, and a container running on podman machine, both will say Podman and won't show which one is running on the machine. Any suggestions how we can differentiate between the two?

**Comment by cdrage** [comment]
> @cdrage: docker contexts have the same issue, but I suppose if you fix one type you will fix both ?
> 
> "On Linux, be able to differentiate between native docker and a docker machine."

Yes, this is another issue too, we cannot differentiate between multiple engines of the same type.

**Comment by afbjorklund** [comment]
> Any suggestions how we can differentiate between the two?

For the Kubernetes clusters, it shows some kind of hover text
