### ISSUE TITLE
Design: Create abstract color references to better enable theming

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#5878]
### Is your enhancement related to a problem? Please describe

We have color names mapped to color codes via tailwind, but need a higher-order level, more abstract names for color references to better support theming the UI. 

This was discussed at the Feb 6 UX call.

This will support light mode support #4914

### Describe the solution you'd like

One approach to naming colors at this level is exemplified in the Material UI color theme element names:
https://m2.material.io/design/color/the-color-system.html#color-theme-creation

**Comment by mairin** [comment]
WIP.... these are detailed names, we will probably need some higher level ones that these point to (like accent-color-primary => purple )

## Global Nav
![Global Nav Theming](https://github.com/containers/podman-desktop/assets/799683/1a7a7b5d-a298-44e3-bcab-571a52495c91)

## Secondary Nav
![Secondary Nav Theming](https://github.com/containers/podman-desktop/assets/799683/7d5d0217-31bc-4e0a-abcd-7aae280212db)

## Titlebar
![Titlebar Theming](https://github.com/containers/podman-desktop/assets/799683/3befcf7b-3953-47a3-8c57-0f5808744bd3)

**Comment by benoitf** [comment]
Hello, I have a question

I think that how it's displayed it's confusing me

I see for example `GlobalNavBg` 
![image](https://github.com/containers/podman-desktop/assets/436777/eb312d15-accf-43bc-b51b-527967aaa5be)

but when I see that

on the left we have a dark background and light font on the right we have the opposite if I click on the details

![image](https://github.com/containers/podman-desktop/assets/436777/65df5b40-848c-42df-8bb0-e849ec492f03)

so I need to think: is that the color is about the background color or the foreground color
and is that the foreground color being used is the display color just to display the text or how it should be renderer by using the foreground color

I think I lost everyone there :-)

To make it simple, could we have like only

```
property name | color for dark theme | color for light theme
```

like

![image](https://github.com/containers/podman-desktop/assets/436777/f803fdda-5fa7-4afe-a76d-827fc0e35fd8)

so if I click on a tile I only see 'one color'

**Comment by benoitf** [comment]
or display the name of the color and behind the color being used

```
Name        |  dark        | light
---------------------------------------
GlobalNavBg | charcoal-600 | gray-200
```

**Comment by benoitf** [comment]
what's the difference between
![image](https://github.com/containers/podman-desktop/assets/436777/2d7c5c51-6034-42ac-8a13-2423dacce41e)

it looks like the same name but different colors (I tried to read it several times but didn't find differences)

could help if we had some some arrows pointing to the part of the element on the left


![image](https://github.com/containers/podman-desktop/assets/436777/7affb53e-356b-4c94-a50b-f4fc40d8291d)

**Comment by ekidneyrh** [comment]
I think this ticket can be closed. The penpot document is being consistently updated with components :) 

Link ti fule is here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=b2d10cc9-d8f7-8046-8003-db40572d0468
