### ISSUE TITLE
Palette: Command titles capitalization is inconsistent

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#5890]
### Bug description

 
![image](https://github.com/containers/podman-desktop/assets/620330/987eb3a2-5fc1-4611-8b91-6b57d497ec91)

### Operating system

macOS Sonoma 14.3

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

1. Show palette
2. Notice inconsistency in capitalization

**Comment by benoitf** [comment]
changing from bug to enhancement
