### ISSUE TITLE
As a user I'd love the (kube config) current context to be set to the cluster that I started

### ISSUE THREAD

**Issue by adietish** [containers/podman-desktop#5900]
### Is your enhancement related to a problem? Please describe

When I launch OpenShift local or kind, I am always frustrated that I have to manually set my kube config to point to the last cluster that I launched. When launching crc or minikube in the terminal, they both would do that automatically for me. 

### Describe the solution you'd like

It would be very handy if I would get something similar (like I get when launch crc or minikube in the command line) in podman desktop. Either starting a cluster would automatically set it as current context in kube config or (even better), I could set the current context in podman desktop

**Comment by benoitf** [comment]
@adietish on my side kind is already doing that

**Comment by benoitf** [comment]
you can also define the context from Podman Desktop with the tray icon or with the status bar

**Comment by adietish** [comment]
> @adietish on my side kind is already doing that

wondering why it isn't for me (tested kind and crc. Starting either one wont set the current context). I'm running MacOS with an M1, does this matter or anything else I should verify?

**Comment by adietish** [comment]
> you can also define the context from Podman Desktop with the tray icon or with the status bar

oh, didnt know. This works, awesomeness, thanks!

**Comment by benoitf** [comment]
@adietish on my side it's the kind process that, when starting, updates and creates the `$HOME/.kube/config` file with 'kind-kind-cluster`

are you using some environment variables / using a different file there or you did a link to /dev/null etc for the KUBE config location ?

**Comment by adietish** [comment]
> are you using some environment variables / using a different file there or you did a link to /dev/null etc for the KUBE config location ?

nope, I have a regular config file at `~/.kube/config`, nothing special about it besides it having multiple entries already. Switching via the icon in the status bar works fine though.

**Comment by adietish** [comment]
I'd close this issue since what I was hoping for as a solution (ability to set the config) was already present, it was just me that didn't get that 😄 
I have no idea why kind would not set the current context for me and I cannot replicate it with minikube since minikube wont run with M1 currently. CRC requires me to log in via cmd-line anyhow and thus wont fit the usecase.
