### ISSUE TITLE
Color theming capabilities into Podman Desktop

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5914]
### Is your enhancement related to a problem? Please describe

UX team is doing an awesome job extracting and defining colours for the different part of the UI
https://github.com/containers/podman-desktop/issues/5878

For now we're handling dark theme and tailwind allows to handle both light and dark theme

unfornately, handling a light and dark theme with tailwind implies to use in html both values like

`bg-blue dark:bg-yellow` meaning it will reference blue color in light mode and yellow color in dark mode

but we have for example some code using the pattern:

```
  class:border-purple-500="{type === 'tab' && selected}"
```

so it means duplicating the lines for dark or reworking the full code.

### Describe the solution you'd like

I would like to reference css variable colours from tailwind colours so it means

instead of doing
```
  class:border-purple-500="{type === 'tab' && selected}"
```

I would do for example
```
  class:border-buttonBorder="{type === 'tab' && selected}"
```

and we would change the definition of the colour if we're either in light or dark mode

so it means it would be a less disruptive change

### Describe alternatives you've considered

I tried tailwind default approach there https://github.com/containers/podman-desktop/pull/4912/files

but it was not convincing especially that we're limited to only 2 choices 'light' or 'dark'

but probably we need more customization or more contrasted theme

**Comment by deboer-tim** [comment]
A big +1 from me.

My only worry is that we end up with a huge number of names (e.g. just for button there could be buttonPrimaryBorder, buttonPrimaryBackground, buttonPrimaryBackgroundHighlight, buttonSecondaryBorder, buttonSecondary, etc), but hopefully we can keep it to a reasonable number.

The following won't work, but it would be great to get to something like:
```
'buttonBorder': {
  light: purple-600,
  dark: purple-400,
},
```

**Comment by benoitf** [comment]
if the snippet is about the tailwind file, I think that yes we can group colors by component name like

```json
"button": {
  "border": ..
  "primaryColor" : ..
  "secondaryColor" ...
}
```

but then the definition will be something like
```
var(--podman-desktop-buttonPrimaryColor) (to match the color defined globally)
```

**Comment by benoitf** [comment]
completed, next steps will be by waiting the end of https://github.com/containers/podman-desktop/issues/4907
