### ISSUE TITLE
qemu exited - Error: HV_ERROR

### ISSUE THREAD

**Issue by NicoleMGF** [containers/podman-desktop#5938]
### Bug description

Installed Podman Desktop from dmg as recommended. Getting this error when running `podman machine start`: `qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_ERROR`

Clicking from `Run Podman` from the UI fails with this error `Error: Command execution failed with exit code 125`

### Operating system

macOS Catalina (intel)

### Installation Method

Installer from website/GitHub releases

### Version

1.7.0

### Steps to reproduce

Installed from website. Failed on first run.

**Comment by benoitf** [comment]
I'm wondering if it's related to qemu with macOS catalina

Could you check with the command line executing 'podman machine init --now' from /opt/podman/bin folder (deleting first any machine)

**Comment by benoitf** [comment]
I'm not sure podman or recent qemu builds are being tested with Catalina

I guess you can't update your operating system to a new one

**Comment by benoitf** [comment]
closing as no response
