### ISSUE TITLE
Extensions install broken for the flatpak package

### ISSUE THREAD

**Issue by Malix-Labs** [containers/podman-desktop#5948]
### Bug description

The flatpak package release of Podman Desktop, has bugs about installing extensions

### Operating system

ChromeOS Flex - Version 122.0.6261.30 (Official Build) beta (64-bit)

### Installation Method

Flathub (Linux)

### Version

1.7.1

### Steps to reproduce

1. Install podman desktop
2. Launch podman desktop
3. Try to install and use docker compatibility, kind, and minikube

```sh
malix@penguin:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Additional context

1. ![image](https://github.com/containers/podman-desktop/assets/76160668/f7e007de-00d7-4f02-ab90-98a52a9f9c44)
	![image](https://github.com/containers/podman-desktop/assets/76160668/cb11d6c3-8576-4721-8a34-f25edf9b4809)
2. ![image](https://github.com/containers/podman-desktop/assets/76160668/c3f5caa6-f017-4dba-b7ec-931fd54f68c6)
	![image](https://github.com/containers/podman-desktop/assets/76160668/cb08ecb9-c6b8-4c54-bf62-b3eefa4d566a)
3. ![image](https://github.com/containers/podman-desktop/assets/76160668/4ca9758e-1d8a-4d24-a664-f11aaeb071b8)
	![image](https://github.com/containers/podman-desktop/assets/76160668/21b3dfea-1ae1-46b6-a7b5-51921bdb15fe)
4. The featured extension errors disappears in the status bar and the OS announce that they had been installed successfully
	![image](https://github.com/containers/podman-desktop/assets/76160668/376c70da-a7d5-457c-ba07-615f73ebcc51)
	Yet, rebooting podman desktop makes the errors show up again
	![image](https://github.com/containers/podman-desktop/assets/76160668/43db50fe-fb59-4477-92ca-c49df4089457)

**Comment by Malix-Labs** [comment]
**I have no experience with podman desktop outside of ChromeOS**

It seems that disabling extensions enable them back at software reboot (which may be an intended behavior, but I'm logging it here for the record)

- Before rebooting podman desktop
![image](https://github.com/containers/podman-desktop/assets/76160668/acc47c67-1c95-4d24-b234-fbdc86974196)
- After rebooting podman desktop
![image](https://github.com/containers/podman-desktop/assets/76160668/e6b4f2c0-7d19-4ae7-aa5c-b67636bf5e45)

**Comment by afbjorklund** [comment]
> It seems that disabling extensions enable them back at software reboot

* https://github.com/containers/podman-desktop/issues/268

**Comment by Malix-Labs** [comment]
@afbjorklund thanks, subscribed to that issue 👍

I tried again some tests to make Crostini and Penguin work, but to no avail.

**Comment by benoitf** [comment]
hello, I think this issue should be closed as you're prompted that it will require admin privileges
kind or minikube can work without admin privileges it's just that you won't have the commands on the PATH globally

If you don't have admin rights from the user using sudo then Podman Desktop can't do more there.

and for the extension enablement, there is an existing issue

**Comment by Malix-Labs** [comment]
@benoitf

> If you don't have admin rights from the user using sudo then Podman Desktop can't do more there.

I have `sudo` perms, using `sudo` in the terminal works.
The issue is that it doesn't give podman desktop admin privileges and shows those errors.

Moreover, I don't know if that issue is caused by admin privileges rather than how Crostini and Penguin work.

This is a global issue for ChromeOS, does closing it as not planned mean that ChromeOS support isn't planned about Podman Desktop?

**Comment by benoitf** [comment]
@Malix-off could you try with the linux binary, not the flatpak one ?

unpack and launch podman-desktop binary from https://github.com/containers/podman-desktop/releases/download/v1.7.1/podman-desktop-1.7.1.tar.gz


I think there is a separate issue around flathub and nested exec commands. (as there is like a sandboxed filesystem, etc probably it's not taking the right file)

**Comment by Malix-Labs** [comment]
I'm going to test 👍

Note that packages other than debian and flatpak are notoriously not well integrated with ChromeOS

**Comment by Malix-off** [comment]
@benoitf to be honnest, I am currently trying but have no idea as of how to install from the tar.gz archive

**Comment by Malix-off** [comment]
It seems that I can only manage to make flatpak to be installed

**Comment by Malix-Labs** [comment]
Was able to start the AppImage but it required some chmod exec perm tweaks.

It's not well integrated to the GUI of ChromeOS

**Docker Compatibility is still not working**, but the error for Kind and Minikube has disapeared

## Logs

```sh
malix@penguin:~$ podman-desktop-1.7.1/podman-desktop
Kubeconfig path /home/malix/.kube/config provided does not exist. Skipping.
Starting http server to handle webviews on port 44000
System ready. Loading extensions...
Activating extension (podman-desktop.compose) with max activation time of 10 seconds
Activating extension (podman-desktop.docker) with max activation time of 10 seconds
Activating extension (podman-desktop.kind) with max activation time of 10 seconds
Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
[kube-context] starting extension kube-context
Activating extension (podman-desktop.kubectl-cli) with max activation time of 10 seconds
Activating extension (podman-desktop.lima) with max activation time of 10 seconds
[lima] Could not find socket at /home/malix/.lima/podman/sock/podman.sock
Activating extension (podman-desktop.podman) with max activation time of 10 seconds
Activating extension (podman-desktop.registries) with max activation time of 10 seconds
Activating extension (podman-desktop.minikube) with max activation time of 10 seconds
Activating extension (podman-desktop.docker) ended in 299 milliseconds
Activating extension (podman-desktop.kube-context) ended in 226 milliseconds
Activating extension (podman-desktop.lima) ended in 179 milliseconds
Activating extension (podman-desktop.registries) ended in 128 milliseconds
Activating extension (podman-desktop.compose) ended in 430 milliseconds
Activating extension (podman-desktop.kubectl-cli) ended in 317 milliseconds
[kubectl-cli] Error getting kubectl from user PATH: Error: Failed to execute command: spawn kubectl ENOENT, trying from extension storage path
[kubectl-cli] Error getting kubectl version system from extension storage path FA [Error]: Failed to execute command: spawn /home/malix/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli/bin/kubectl ENOENT
    at ChildProcess.<anonymous> (/home/malix/podman-desktop-1.7.1/resources/app.asar/packages/main/dist/index.cjs:343:12753)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  exitCode: 1,
  command: '/home/malix/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli/bin/kubectl',
  stdout: '',
  stderr: '',
  cancelled: false,
  killed: false
}
[podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
Activating extension (podman-desktop.podman) ended in 531 milliseconds
PluginSystem: received dom-ready event from the UI
Delayed startup, flushing 55 events
Fetched https://registry.podman-desktop.io/api/extensions.json in 1702.3319790000096ms
Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
[kind] kind extension is active
Activating extension (podman-desktop.kind) ended in 3013 milliseconds
[kind] kind extension is active
[minikube] minikube extension is active
[minikube] minikube extension is active
[kind] kind extension is active
Activating extension (podman-desktop.minikube) ended in 6851 milliseconds
PluginSystem: initialization done.
Unable to fetch the available extensions: Timeout awaiting 'socket' for 1000ms
Skipping update for extension podman-desktop.minikube because installed version 0.3.0-next is greater or equal to latest available version 0.2.0
[podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[podman] Error running systemctl command: Command execution failed with exit code 1: Command execution failed with exit code 1
```

**Comment by Malix-Labs** [comment]
I tried extensively, and I couldn't find a fix to the [the docker compatibility setup bug](https://github.com/containers/podman-desktop/issues/5948#issuecomment-1950274025).

Can someone reopen the issue?

**Comment by Malix-Labs** [comment]
@benoitf:
> I think there is a separate issue around flathub and nested exec commands.

Can you provide a link to that issue?
I didn't find it personally.

**Comment by benoitf** [comment]
> I tried extensively, and I couldn't find a fix to the https://github.com/containers/podman-desktop/issues/5948#issuecomment-1950274025.

we removed the compatibility part of Linux:
https://github.com/containers/podman-desktop/issues/5789

**Comment by Malix-Labs** [comment]
@benoitf

Okay about the docker compatibility part.

To separate concerns about those issues and not have a duplicate, I rebranded this one about the extension install bug for the flatpak package.

Is it the first issue about it, or is there already one filled?

If it's the first issue about it, it's not a duplicate,
If you plan on resolving it, it should be reopened;
Else, it should remain closed as not planned.

**Comment by Malix-Labs** [comment]
@benoitf ^
