### ISSUE TITLE
Add --device option when creating a container

### ISSUE THREAD

**Issue by ksazhnev** [containers/podman-desktop#5989]
### Is your enhancement related to a problem? Please describe

Podman Desktop does not have the option to add a device like --device /dev/fuse when running the container from the UI.
My requirement does not allow me to use a terminal.

### Describe the solution you'd like

 Is it possible to do so inside the Podman Desktop? Or adding this option possibly in the "Advanced" tab?

**Comment by brainbytes42** [comment]
+1 to add some way to specify custom run commands, like device (which is needed for use of GPU with CDI as well): `podman run --device nvidia.com/gpu=all ...`.
Currently, I need to start a GPU-powered container using command line for the first use - afterwards, I can restart it from podman desktop.

**Comment by slemeur** [comment]
Thanks for sharing the feedback.

We could add a "Device" section when starting a container:
<img width="1578" alt="Screenshot 2024-09-02 at 14 17 32" src="https://github.com/user-attachments/assets/809e3e17-b490-4f9e-9481-f63766bc6b9e">

Would that work for you?

**Comment by brainbytes42** [comment]
Yeah, that would be perfect. :-)

(But maybe, amongst that, an option to add _any other_ parameters would come in handy, as well... So everything not explicitly covered, could as well be started in Podman Desktop and one wouldn't have to switch to comandline, which breaks the GUI-experience.)

**Comment by feloy** [comment]
> Yeah, that would be perfect. :-)

> (But maybe, amongst that, an option to add any other parameters would come in handy, as well... So everything not explicitly covered, could as well be started in Podman Desktop and one wouldn't have to switch to comandline, which breaks the GUI-experience.)


Having a semantic output of the podman help would help for this: https://github.com/containers/podman/issues/23976

**Comment by feloy** [comment]
> (But maybe, amongst that, an option to add _any other_ parameters would come in handy, as well... So everything not explicitly covered, could as well be started in Podman Desktop and one wouldn't have to switch to comandline, which breaks the GUI-experience.)

As Podman Desktop is using the REST API to execute `podman` commands (and does not call the podman cli), it could not be possible for the user to pass CLI-related options, as they would not be applicable for the API as is.
