### ISSUE TITLE
Provide API to call podman CLI

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#5990]
### Is your enhancement related to a problem? Please describe

`podman machine ssh` command has no matching Rest API end point. If an extension needs to execute it or similar command the only way is to find podman CLI in user environment and run it using process API. 

### Describe the solution you'd like

podman extension has implementation already that should be accessible through podman desktop API.

**Comment by dgolovin** [comment]
@benoitf The PR merged has added a great feature, but that is just a foundation for implementing actual API in Podman extension. Should this issue to be reopened because there is no actual Podman extension API to use?

**Comment by benoitf** [comment]
yes
