### ISSUE TITLE
Docs / website: Improve landing page of website with docs links.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6002]
### Is your enhancement related to a problem? Please describe

Going through some docusaurus showcases, I noticed a common pattern of showing some quick and easy documentation links in the form of a "landing" page. 

For example, Redis labs does this pretty well (as shown in their showcase section):

![Screenshot 2024-02-14 at 10 57 16 AM](https://github.com/containers/podman-desktop/assets/6422176/c3fd314c-d3f5-4d4c-8c9f-8af03ebc0a00)

### Describe the solution you'd like

A categorized small section of the index page with quick links to Kubernetes / compose / etc documentation.

**Comment by themr0c** [comment]
Yes, how do they do these nice tiles?

**Comment by benoitf** [comment]
it looks like a duplicate of https://github.com/containers/podman-desktop/issues/5335

content of this issue can be moved to https://github.com/containers/podman-desktop/issues/5335

**Comment by cdrage** [comment]
> it looks like a duplicate of #5335
> 
> content of this issue can be moved to #5335

See: https://github.com/containers/podman-desktop/issues/5335#issuecomment-1944108514 comment.

This issue is about index page which @themr0c and I were looking at briefly, the other issue is about the intro page.

**Comment by benoitf** [comment]
well I think intro page is where people will land first when searching for documentation I guess

**Comment by benoitf** [comment]
https://www.google.com/search?q=podman+desktop+documentation = intro page
