### ISSUE TITLE
Dashboard shows Docker socket is not reachable, even though the socket can be reached in the troubleshooting page

### ISSUE THREAD

**Issue by archerallstars** [containers/podman-desktop#6007]
### Bug description

The dashboard shows this warning: 

> **Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work.** 

But when I troubleshooted the socket, it's reachable, as shown in the screen recording below:

https://github.com/containers/podman-desktop/assets/1403194/88780337-f674-4638-a5be-2d77c694f079

And when I tried to enable Docker compatibility mode in the app, at the end of the process, it failed to symlink with exit code 1, as shown in the screen recording below:

https://github.com/containers/podman-desktop/assets/1403194/724682e1-186b-445d-a616-61f11a578357

### Operating system

openSUSE Tumbleweed

### Installation Method

Flathub (Linux)

### Version

1.7.0

### Steps to reproduce

1. Open the app. See the warning in the app's dashboard page.
2. Go to the app's troubleshooting page and Ping the Docker socket. It will be reachable.
3. Try to enable Docker compatibility mode. It will fail with error code 1.

### Relevant log output

```shell
-
```

### Additional context

`podman`: 4.9.2
`docker`: 24.07_ce

**Comment by afbjorklund** [comment]
The question is: is it reachable **as podman**, or is it "only" reachable as docker?

----

Probe explicitly checks the `libpod` endpoint, which Docker does not implement

e.g. "Docker socket is not reachable, for the podman specific functionality".

e.g. "Docker specific tools may not work, in podman but will run in docker".

The warning is misleading, and is supposed to go away in the next release.

* https://github.com/containers/podman-desktop/pull/5903

Note: the warning only applies if you "forget" to set DOCKER_HOST (to podman)

You could also set the default docker context, for a more global change

**Comment by afbjorklund** [comment]
And I still think that Podman Desktop should also show the docker version.

* https://github.com/containers/podman-desktop/pull/2997

EDIT: rebased and reopened

* #6043

**Comment by benoitf** [comment]
I think you're getting the expected behavior as both Docker and Podman are running and podman can't emulate docker as docker is already using the socket path

Also on Linux to avoid confusion the message is no longer displayed (fixed in main branch and will be included in 1.8.0)
https://github.com/containers/podman-desktop/issues/5789
