### ISSUE TITLE
Validation / UX improvement for the"Image to Pull" flow

### ISSUE THREAD

**Issue by ibuziuk** [containers/podman-desktop#6015]
### Describe the solution you'd like

Would be nice to improve the image pull flow and add some validation.

Basically, I copied CLI instructions from the screen and pressed `Pull` button

<img width="1029" alt="Screenshot 2024-02-15 at 13 12 37" src="https://github.com/containers/podman-desktop/assets/1461122/ff1ab90d-29dd-4dfc-8065-1c79253a9741">

After pasting it in the input field and Pulling the image 500 error was thrown:

<img width="1476" alt="Screenshot 2024-02-15 at 13 11 49" src="https://github.com/containers/podman-desktop/assets/1461122/7eea46a9-526b-4098-af2d-91e926c68272">

After pasting it in the input field and Pulling the image 500 error was thrown. However, I should input just the image reference without `podman pull` command.

### Additional context

Reproduced against 1.7.1 version

**Comment by cdrage** [comment]
Side question, shouldn't we switch this to the same / similar modal as "Push Image" so "Pull" matches too?

@mairin @benoitf @deboer-tim 

As it'd fit the same pattern / check for authentication UI that I had implemented the other week for push images.

**Comment by mairin** [comment]
@cdrage maaaaaaybe? I'd feel a full screen would give more real estate if we wanted to have some kind of fancy (at some future point) selector to choose from which registry you'd want to pull it from if we find it in multiple, with some metadata to support the choice of which one (maybe even for ones that have it security rankings or something)

But it's probably doable from a dialog as well?

**Comment by benoitf** [comment]
I would not hijack this ticket that is mainly about reporting error feedback on the input field

**Comment by deboer-tim** [comment]
+1, and see my comments on the push issue, we should have a clear convention and not discuss every case.
