### ISSUE TITLE
docs: add a video reader for docusaurus

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#6018]
### Is your enhancement related to a problem? Please describe

For https://github.com/containers/podman-desktop/issues/5335, I want to add a video to the intro page.

I found an example using `react-lite-youtube-embed` on https://github.com/facebook/docusaurus/pull/7390/files.

```mdx-code-block
import LiteYouTubeEmbed from 'react-lite-youtube-embed';

<div className="video-container">
  <LiteYouTubeEmbed
    id="OeJ_cwdoQm8"
    params="autoplay=1&autohide=1&showinfo=0&rel=0"
    title="Docusaurus: Documentation Made Easy"
    poster="maxresdefault"
    webp
  />
</div>
```

However this module/plugin/extension is missing in the docusaurus installation:

```
Module not found: Error: Can't resolve 'react-lite-youtube-embed'
```

### Describe the solution you'd like

Can someone enable this video player, respecting the way we should enable something for docusaurus.

### Describe alternatives you've considered

I would be happy with any other player.

**Comment by themr0c** [comment]
I fear I will nuke the whole docusaurus setup if I try it. Who can do it? @cdrage @benoitf ?

**Comment by benoitf** [comment]
AFAIK we already have videos in docusaurus

**Comment by themr0c** [comment]
Oh! Great! Can you show me how to do that? I took an example from the docusaurus website just because I didn't find one in our website.

**Comment by benoitf** [comment]
We're using that for the release notes

https://github.com/containers/podman-desktop/blob/62d5f07f6b7ac3c271cc315b61e5da1d5b260b84/website/blog/2023-06-08-release-1.1.md?plain=1#L48


https://github.com/containers/podman-desktop/blob/62d5f07f6b7ac3c271cc315b61e5da1d5b260b84/website/blog/2023-06-08-release-1.1.md?plain=1#L11

**Comment by themr0c** [comment]
Does it work with a YT video?

**Comment by benoitf** [comment]
yes, look at the documentation: https://github.com/cookpete/react-player?tab=readme-ov-file#usage

**Comment by themr0c** [comment]
Nice, integrated into https://github.com/containers/podman-desktop/pull/5982.
I removed `width='100%' height='100%'` because it did not look good.
