### ISSUE TITLE
Remove empty black terminal screens for "Loading..." spinners & "show more details" buttons.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6020]
### Is your enhancement related to a problem? Please describe

I don't have a mock up.. but we have this in a few places within PD:

![Screenshot 2024-02-15 at 9 13 16 AM](https://github.com/containers/podman-desktop/assets/6422176/f38198b4-657c-43d0-868c-cc500015b40c)

Which are empty console screens with no information.

### Describe the solution you'd like

I see a common design pattern to instead have it as "Loading..." spinners that hide the output, with a "show details" buttons to actually show the console

**Comment by cdrage** [comment]
@mairin @ekidneyrh

**Comment by benoitf** [comment]
I think we're already tons of issues about Design, I don't think we need to go in details before the work is started

**Comment by cdrage** [comment]
This has been a common complaint in other issues / feedback from the discord, as well as UX calls, I think we should keep this open.

**Comment by benoitf** [comment]
let's reopen when flexbox design will be implemented or comment on the design issue of flexbox
