### ISSUE TITLE
UI: Edit image should be updated to match other modals

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6021]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-02-15 at 9 19 43 AM](https://github.com/containers/podman-desktop/assets/6422176/5a61a3e8-4e49-436d-99e5-83a10556a781)

Edit image is outdated vs other modals:
![Screenshot 2024-02-15 at 9 10 59 AM](https://github.com/containers/podman-desktop/assets/6422176/0950b33f-68c9-4d45-8ed0-ccce46ca5b64)

### Describe the solution you'd like

From what I can see:
Update buttons
Update spacing
Change titles (capitalized on both)

**Comment by benoitf** [comment]
there is already issue to rework the modals

**Comment by cdrage** [comment]
> there is already issue to rework the modals

I'm unable to find the issue for the modals that talks about Edit Image, should we keep this open so we can keep track?
