### ISSUE TITLE
UI: Create a volume should be a modal

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6022]
### Is your enhancement related to a problem? Please describe

Create a volume has very little information and IMHO should be a modal:

![Screenshot 2024-02-15 at 9 23 48 AM](https://github.com/containers/podman-desktop/assets/6422176/26e4b8b4-e6f5-4031-ac46-31b0686bbdd5)

### Describe the solution you'd like

Modal instead

**Comment by benoitf** [comment]
I think we're already tons of issues about Design, I don't think we need to go in details before the work is started

**Comment by cdrage** [comment]
@benoitf  I'd be good to keep this open so we can keep track of the change? Where else should I track the issue?
