### ISSUE TITLE
Add `platform` to containerCreateOptions

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6035]
### Is your enhancement related to a problem? Please describe

In dockerode we are able to define the platform to be used (arm64, amd64, etc.): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dockerode/index.d.ts#L1117

We should be able to define the platform within the PD API.

### Describe the solution you'd like

Added `platform` to https://github.com/containers/podman-desktop/blob/28a63f6650ce3acaa04c985d57c81a249bc9d14d/packages/extension-api/src/extension-api.d.ts#L2279

Which had already been done so on build create, etc: https://github.com/containers/podman-desktop/blob/28a63f6650ce3acaa04c985d57c81a249bc9d14d/packages/extension-api/src/extension-api.d.ts#L2413-L2414

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/6010

There is already a pending PR
