### ISSUE TITLE
Field for installing extensions is (too) small

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop#6037]
### Is your enhancement related to a problem? Please describe

I find the field for installing an extension too small, especially next to the button.  References to images on registries tend to get relatively long, so it's usually impossible to read the full input once copied.  Take `quay.io/redhat-developer/podman-desktop-redhat-account-ext:0.0.2-alpha.2` for example; the one I used in the screenshot below.

![image](https://github.com/containers/podman-desktop/assets/11679875/2a53248e-175e-43eb-b6db-df8148e73825)

### Describe the solution you'd like

I'd love to be able to have a larger input field. Maybe move the button to another place (e.g., below?) to give the input field some space.

**Comment by benoitf** [comment]
Hello, this is part of https://github.com/containers/podman-desktop/issues/2170

also if it's in the catalog you shouldn't have to use any input fields

For advanced mode and use an input field, I will add the concern into the revamp issue.

**Comment by vrothberg** [comment]
Sounds good to me, thank you, @benoitf !
