### ISSUE TITLE
bug(extension-api): navigate to pod does not redirect to default tab

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6071]
### Bug description

When we use the navigation.navigateToPod we are redirect to `/pods/:kind/:name/:engine/` however this page is blank because we should be redirect to `.../logs` or else just like the ContainerDetails component is doing

https://github.com/containers/podman-desktop/blob/008cc0f2da72ee093e09ca31b7e79b5c317488df/packages/renderer/src/lib/container/ContainerDetails.svelte#L53-L57

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

use navigation api for pods

**Comment by deboer-tim** [comment]
Based on what happens when you select a pod in the Pods list, /logs is actually the current 'homepage' for pods. We should probably make the internal links use the navigation api, to avoid differences and have the default tab defined in one place.
