### ISSUE TITLE
Get podman machine info from extension

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6097]
### Is your enhancement related to a problem? Please describe

From an extension, we would like to have memory/cpu information about podman machines in use.

### Describe the solution you'd like

There is a method in the api `containerEngine.info(engineId)`, which provides this information. 

To get the `engineId`, I understand that we nned to execute a `list*` command and, if there are elements returned by any of these functions, to get the engineId from this result (for example, an image returned by `listImages` conatains the engineId on which it is present.

It would be nice to have a more direct way to get the `engineId`, for example whan we have a `ProviderContainerConnection` value (obtained from `provider.getContainerConnections`).

**Comment by axel7083** [comment]
One provider (E.g. `podman`) can have multiple engine registered (E.g. on windows several Podman Machine).

What do you want to get ? The list of engineId for a given provider ? Inside the `ContainerRegistry` you use the method `protected getMatchingContainerProvider(provider: containerDesktopAPI.ContainerProviderConnection): InternalContainerProvider`

> `InternalContainerProvider` contains the desired `Id` and `name` corresponding to the engineId and engineName.

_The wording is a bit messy inside the ContainerRegistry in my opinion_.

**Comment by feloy** [comment]
> What do you want to get ? The list of engineId for a given provider ?

The goal is to select, from an extension, the best engine to use, depending on how many cpu/memory are available on each engine. 

So yes, having the list of engineIds would be necessary.

I can see that `getMatchingContainerProvider` will return only the first found provider, but I suppose a `getMatchingContainerProviders` with a `filter` instead of `find` would be what we want here

**Comment by benoitf** [comment]
from extension side, and to match the expected goal, it should accept an optional ProviderConnection object
if omitted, it should return the list of all infos object (so extension can see how many cpus, memory etc are available)

I think it should be like listImages or listContainers, etc

`listInfos({options: {provider}}: Promise<ContainerEngineInfo[]>`

and ContainerEngineInfo object should include some extra fields like the engineID, engineType, ...
