### ISSUE TITLE
Reduce informer backoff for current context

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6114]
### Is your enhancement related to a problem? Please describe

The Kubernetes informer backoff works well, but it drops off fairly fast. This is completely fine for most contexts, but the current context is a little special: it's the one I'm most likely to be interested in, and (e.g.) if I start a new kind or minikube cluster I expect it to connect fairly fast.

### Describe the solution you'd like

Add some preference/weight to the current context, so that it backs off not as fast or not as far as all other contexts.

**Comment by deboer-tim** [comment]
Still valid.

**Comment by feloy** [comment]
Fixed by #9392, #9411, #9443
