### ISSUE TITLE
Proposal: optimized informers

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6123]
### Is your enhancement related to a problem? Please describe

Optimize the listening of different resources on different Kubernetes contexts, using informers
#5311 #6094 #6100 #6113 #6114 

## Current status 

On the backend side, the `ContextsManager` (in `packages/main/src/plugin/kubernetes-context-state.ts`) starts informers for every managed resources (pods, deployemnts for the moment) on every Kubernetes contexts (in kubeconfig file) and caches the list of resources locally. Once connected, the manager listens `add`, `delete` and `update` events to update the cached resources accordingly.

In case of connection error, retries are done using a backoff pattern on each informer (for the moment using the same pattern for each informer).

On every  change, the complete set of cached resources (all resources of all kinds for all contexts) are sent to the frontend.

On the frontend side, a single store asks for the content cache when it starts, and subscribes for receiving updates every time the cache is updated.

Several `derived` stores on the first store give information about specific information on the current context.

## Proposed evolution

The `ContextsManager` continues to collect all the resources for all the contexts.

Several channels replace the current single channel:

1. status and number of a selected list of resources (pods, deployments) for all contexts (including the current one):

```
Map {
  'context1' => { reachable: true, resources: { pods: 2, deployments: 1 } },
  'context2' => { reachable: false, error: 'err', resources: { pods: 0, deployments: 0 } },
}
```

2. Status and number of a selected list of resources (pods, deployments) for current context:

```
{ reachable: false, error: 'err', resources: { pods: 0, deployments: 0 } }
{ reachable: true, resources: { pods: 2, deployments: 1 } }
```

3. Pods in the current context:

```
[ { /* pod1 */}, { /* pod2 */ } ] 
```

4. Deploymenets in the current context:

```
[ { /* deployment1 */}, { /* deployment2 */ } ] 
```

5. ..n Other resources in the current context

```
[ { /* resourceX1 */}, { /* resourceX2 */ } ] 
```

On the frontend side, a store exists for each channel. Svelte stores are created when first used, and discarded when the last user disconnects. With the same pattern, the stores can register to the ContextsManager, to indicate they need updates on the resources data:
- informers for resources other than pods and deployments are not started initially before the first registering, and are started when the store first registers (lazy-loading),
- when the store unregisters, informers can be stopped (after a few time).

## TODO

- [x] #6171
- [x] #6155
- [x] #6167
- [x] #6153
- [x] #6202
- [ ] ~~Start Deployment informer when pod informer is connected~~
- [x] #6198
- [ ] ~~#6232~~

**Comment by deboer-tim** [comment]
I'm not sure I totally follow what this would mean for the API, but 👍🏼 on the proposal and separating basic information for all contexts vs more information for watched contexts. A few things I'd like to make sure we cover in this change:
- Although the current context is special, I don't want to bake 'we only get detailed information for a single / current context' in the API. IMHO the API should just respond to whatever contexts the UI is interested in, which will almost always be only 1 context and that'll be the current one, but e.g. maybe the user is switching back and forth fast enough that we're keeping resource informers for 2 contexts.
- Informers for resource data should have less backoff, and trigger the same in reachable/resource count informers (or informers kick each other once they have a connection, etc). i.e. if I'm watching for pods and then start a cluster I expect it to show data/say connected/have correct counts fairly quickly.
- Over time we're going to extend pods and deployments to other types and we don't want to pull all of those types all the time. So the lazy-loading/lazy-stopping should be per-type. i.e. maybe the user is only looking at deployments so we only create that informer; then they look at services for a while so we start a second informer and eventually stop the deployment informer.
- A nice bonus would be info to the store on initial connection of new informers - e.g. if you open the Deployments page and it takes 5s to connect and pull the first data it would be nice to show 'connecting' status vs reachable:false.

**Comment by feloy** [comment]
> I'm not sure I totally follow what this would mean for the API, but 👍🏼 on the proposal and separating basic information for all contexts vs more information for watched contexts. A few things I'd like to make sure we cover in this change:
> 
> * Although the current context is special, I don't want to bake 'we only get detailed information for a single / current context' in the API. IMHO the API should just respond to whatever contexts the UI is interested in, which will almost always be only 1 context and that'll be the current one, but e.g. maybe the user is switching back and forth fast enough that we're keeping resource informers for 2 contexts.

There is a clear distinction between which data is 'cached' in the backend, and which information is sent to the frontend.

> The ContextsManager continues to collect all the resources for all the contexts.

I mean that we continue to run all informers and collect the complete information of the resources in the backend; this way, if the context is switched to another one, the data is available for this new context.

But I would like to limit the volume of information sent to the frontend. As there can be a lot of (non-current) contexts, there can be a lot of data to transfer every time a pod (or any other resource) changes on any of this context.
