### ISSUE TITLE
Release 1.8

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6139]
### Is your enhancement related to a problem? Please describe

Issue to create the next Podman Desktop release

### Describe the solution you'd like

if some issues are mandatory, we can list them here as well to track the progress
- [x] https://github.com/containers/podman-desktop/issues/6143
- [x] https://github.com/containers/podman-desktop/issues/6220
- [x] https://github.com/containers/podman-desktop/issues/6221 (PR: https://github.com/containers/podman-desktop/pull/6281)
- [x] https://github.com/containers/podman-desktop/issues/6256
- [x] https://github.com/containers/podman-desktop/issues/6151 (PR: https://github.com/containers/podman-desktop/pull/6262)
- [x] #6271
- [x] #6097 
- [x] https://github.com/containers/podman-desktop/pull/5271
- [x] https://github.com/containers/podman-desktop/issues/6211
- [x] #6289
- [x] https://github.com/containers/podman-desktop/issues/6344
- [x] https://github.com/containers/podman-desktop/issues/4605

Kubernetes related issues:
- [x] #6202 (PR #6250)
- [x] #6254 
- [x] #6259 (3 PRs: #6242, #6264, #6265)

**Comment by cdrage** [comment]
Should also fix https://github.com/containers/podman-desktop/issues/6151 before release or else anyone on Linux will have endless loop

**Comment by benoitf** [comment]
suggested https://github.com/containers/podman-desktop/issues/5842 from @feloy

**Comment by feloy** [comment]
> suggested #5842 from @feloy

My bad, I have given the wrong issue during meeting, here is the one which will be necessary if we want to get Podman Machine information (cpu, memory) from extensions:

https://github.com/containers/podman-desktop/issues/6097

**Comment by benoitf** [comment]
adding https://github.com/containers/podman-desktop/issues/6344 with tiny change associated PR https://github.com/containers/podman-desktop/pull/6345

and https://github.com/containers/podman-desktop/issues/4605 with https://github.com/containers/podman-desktop/pull/6343
