### ISSUE TITLE
In ContainerDetails opening Deploy to Kubernetes then going back though the breadcrumb result in empty tabs

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6140]
### Bug description

https://github.com/containers/podman-desktop/assets/42176370/46b0260e-cc0e-4b06-ae86-702d4c47e967

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

See video above

**Comment by odockal** [comment]
Reproduced on Fedora as well. All platforms are the same, I guess.

**Comment by axel7083** [comment]
Still important

**Comment by odockal** [comment]
@axel7083 I have moved the issue into next sprint (264).

**Comment by axel7083** [comment]
I do not reproduce in 1.13 

https://github.com/user-attachments/assets/db56816d-e714-4e9d-8004-1722c9537f43
