### ISSUE TITLE
Send contexts status on different channels

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6171]
See #6123 (Proposed evolution)

**Comment by benoitf** [comment]
@feloy curious to know how you create your issues as there is never the GitHub template ?

**Comment by feloy** [comment]
> @feloy curious to know how you create your issues as there is never the GitHub template ?

I'm creating a list with `- [] title of the issue` and when I save, there is an icon on the end of the line, to create an issue based on the list entry. But effectively, this does not use the template :(
