### ISSUE TITLE
Timers are causing uncaught exceptions when exiting

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6198]
The `ContextsManager` (`packages/main/src/plugin/kubernetes-context-state.ts`) allocates timers during its lifecycle, but these timers are not disposed when Podman Desktop exits, and this can lead to such error messages when exiting from Podman Desktop:

![timer-error](https://github.com/containers/podman-desktop/assets/9973512/f03a454a-fd5d-43b5-8531-b59922247e75)

**Comment by benoitf** [comment]
hello @feloy could you use the GitHub issue template when filing issues ?
