### ISSUE TITLE
Add checks for Hyper-V in Podman extension

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6207]
### Is your enhancement related to a problem? Please describe

as part of the epic https://github.com/containers/podman-desktop/issues/5113 we should have preflight checks to see if Hyper-V is installed or not

### Describe the solution you'd like

check if hyper-v is installed or not

we should check for WSL and Hyper-V and then creating the machine should be a Hyper-V or WSL depending on the supported platform

**Comment by axel7083** [comment]
Okey so, I just find out that you need Windows 11 entreprise or pro to use HyperV. And sadly I have `Windows 11 Home`. 

According to the microsoft website [enable-hyper-v#check-requirements](https://learn.microsoft.com/fr-fr/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v#check-requirements) this cannot be used on any other version.

cc @jeffmaury
