### ISSUE TITLE
Selecting multiple items to delete causes stacked text on UI

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6208]
### Bug description

https://github.com/containers/podman-desktop/assets/6422176/24223856-3091-4d87-9780-b70d16f148a8

Selecting multiple items causes a vertical stacking of text in UI.

### Operating system

mac M1

### Installation Method

None

### Version

1.7.0

### Steps to reproduce

Go to delete multiple items and see the text is "stacked" / vertical instead of horizontal.

**Comment by benoitf** [comment]
should you add 'in Deployments page' ?

**Comment by deboer-tim** [comment]
Saw this last night, I have a feeling this might be 'any page with the new connection badge'? If no one else is free I could investigate in a day or two.
