### ISSUE TITLE
Display Events attached to Kubernetes resource

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6210]
### Is your feature request related to a problem? Please describe

When exploring a pod on Kubernetes (or any other resource), we don't have access to the events attached to the resource (the ones visible in the output of tht `kubectl describe pod` command) 

- [x] Deployments: #9553 #9657 
- [x] Pods: #9664 #9672
- [x] Nodes: #9681 #9691
- [x] Services: #9692 #9733 
- [ ] Pods events on Deployment page? 
- [ ] ...

### Describe the solution you'd like

A section in the resources details page ~~tab in the resource details, to display the events attached to the resource~~

**Comment by cdrage** [comment]
When implementing Pod Events it would be nice to be able to show it on Deployments summary as "Pod Events" below the regular Deployment events IMHO. As it's easier to diagnose what is wrong.

**Comment by feloy** [comment]
Closing as done by mentioned PRs
