### ISSUE TITLE
Registry's entry created with registerRegistry call loose a name and an icon after podman desktop restart

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#6218]
### Bug description

When registry created with registerRegistry API call and use `icon` and `name` parameters, the new entry looks good

![image](https://github.com/containers/podman-desktop/assets/620330/f427e931-557b-4c29-b347-1314ad1bd49e)

After restart the entry appears without image and name

![image](https://github.com/containers/podman-desktop/assets/620330/24dd562f-6bb6-498b-8635-dc78574adc60)

### Operating system

macOS Sonoma 14.3

### Installation Method

Other

### Version

next (development version)

**Comment by benoitf** [comment]
it's expected

You should always use suggestRegistry when your extension start
