### ISSUE TITLE
"Podman needs to be setup" notification fires non-stop

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop#6224]
### Bug description

After deleting the Podman Machine on Linux, the notification that Podman needs to be setup fires non-stop. On the main window of Podman Desktop, the notification pops up and disappears making it hard (and confusing) to resolve the issue.

![image](https://github.com/containers/podman-desktop/assets/11679875/c61b48bc-17ae-43cb-97e0-7222ac1f4f47)

### Operating system

Linux

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Delete the Podman Machine in the settings menu.

**Comment by vrothberg** [comment]
After clicking on setup, I face an empty page:
![image](https://github.com/containers/podman-desktop/assets/11679875/790f4553-c2a9-41e3-92ce-327612ba88d2)

**Comment by benoitf** [comment]
maybe https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/extension.ts#L139 is missing a `!isLinux` saying that on Linux machine is optional

**Comment by benoitf** [comment]
yes I don't think onboarding exists on Linux

**Comment by vrothberg** [comment]
> yes I don't think onboarding exists on Linux

Are there plans to support it in the future?  Since I could delete machine, I expected to be able to create a new one as well.

**Comment by benoitf** [comment]
no creation is planned for Linux as we don't know if the creation can succeed. And then it'll introduce a broken feature.

**Comment by vrothberg** [comment]
> [...] as we don't know if the creation can succeed

Can you elaborate on that?  On Fedora I have no issues creating a machine but I assume I miss context.

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/issues/6151

**Comment by afbjorklund** [comment]
@vrothberg : the motivation was that the podman desktop installer (for linux) does not bundle qemu and such

* https://github.com/containers/podman-desktop/issues/5823#issuecomment-1929695510

**Comment by vrothberg** [comment]
Thanks, @afbjorklund !

I am closing this issue here as it's a duplicate of your https://github.com/containers/podman-desktop/issues/6151

**Comment by afbjorklund** [comment]
The end result is that there is no installer for podman engine, and no installer for podman machine either, on Ubuntu.

For the first there is a wall of text and outdated packages, but for the second even the documentation is missing...

**Comment by afbjorklund** [comment]
> I am closing this issue here as it's a duplicate of your #6151

The blank page seems like a new bug, mine was mostly empty - but not completely blank. Error in the log, perhaps?

![pd2](https://github.com/containers/podman-desktop/assets/10364051/67f29fdc-987e-4480-b0d1-45a779e47dc8)

Note: the only option on this page is wrong, the setting is for podman **machine** - not for podman engine

**Comment by afbjorklund** [comment]
Added a new issue, about the missing instructions for how to install podman-remote-static on Linux:

* https://github.com/containers/podman-desktop/issues/6225

After fixing podman.io, it also needs documentation on podman-desktop.io on how to configure it:

* https://github.com/containers/podman-desktop/discussions/5762
