### ISSUE TITLE
Yarn watch not working on windows

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#6228]
### Bug description

When running yarn watch on the main branch i have
```
Error: spawn C:\Users\luca\Work\github.com\containers\podman-desktop\node_modules\.bin\svelte-package ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\luca\\Work\\github.com\\containers\\podman-desktop\\node_modules\\.bin\\svelte-package',
  path: 'C:\\Users\\luca\\Work\\github.com\\containers\\podman-desktop\\node_modules\\.bin\\svelte-package',
  spawnargs: [ '-w' ]
}
```

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. run yarn watch using the main

**Comment by afbjorklund** [comment]
I had to run `yarn` by itself first, after the recent updates.

**Comment by benoitf** [comment]
introduced by https://github.com/containers/podman-desktop/pull/6172

but yes the dependency should be there if you update and then update dependencies using `yarn`

**Comment by lstocchi** [comment]
I face the error after running yarn and yarn build

**Comment by benoitf** [comment]
@lstocchi https://github.com/containers/podman-desktop/blob/main/scripts/watch.mjs#L135

do you have the file in the node_modules folder ?

also do you have Node.JS v20 ?

**Comment by lstocchi** [comment]
> @lstocchi https://github.com/containers/podman-desktop/blob/main/scripts/watch.mjs#L135
> 
> do you have the file in the node_modules folder ?
> 
> also do you have Node.JS v20 ?

yes for both

**Comment by benoitf** [comment]
and can you execute 'C:\Users\luca\Work\github.com\containers\podman-desktop\node_modules\.bin\svelte-package' from the command line ?

**Comment by deboer-tim** [comment]
FWIW on Mac I had to delete node_modules after moving to node 20 or it wouldn’t start.

**Comment by lstocchi** [comment]
> and can you execute 'C:\Users\luca\Work\github.com\containers\podman-desktop\node_modules.bin\svelte-package' from the command line ?

the output is 
```
> src\lib does not exist
    at do_build (file:///C:/Users/luca/Work/github.com/containers/podman-desktop/node_modules/@sveltejs/package/src/index.js:28:9)
    at Module.build (file:///C:/Users/luca/Work/github.com/containers/podman-desktop/node_modules/@sveltejs/package/src/index.js:16:8)
    at file:///C:/Users/luca/Work/github.com/containers/podman-desktop/node_modules/@sveltejs/package/src/cli.js:49:61
 ```
 Update:  ok my bad i was not in the ui folder. Seems to run fine, no errors.
 But when i run yarn watch it still fails. 
 
 I'll try to delete everything as Tim said

**Comment by lstocchi** [comment]
> FWIW on Mac I had to delete node_modules after moving to node 20 or it wouldn’t start.

tried by deleting node_modules but still the same error

**Comment by jeffmaury** [comment]
Workaround is to run yarn from a windows command shell and not from the git bash shell

**Comment by lstocchi** [comment]
i think i never used the git bash shell. Tried with poweshell (also as admin) and cmd shell. Same error 😞 

Have you done something to make it work? Or just yarn watch?

**Comment by lstocchi** [comment]
So i made this work by adding an error listener within the `watch.mjs` file. Something like 

`spawnProcess.on('error', err => { console.log(err) });`

By using https://github.com/containers/podman-desktop/pull/6196 and updating the style of the input, i can see it changes in real time. So it looks like it works 🤔
