### ISSUE TITLE
System notifications on Linux about "Podman Needs to be set up" are very disruptive

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6235]
### Bug description

The notification pops up every 5-10 seconds. It is very disruptive. I have system not in really clean state, but system notification is really annoying at this moment. 

![system_notifications_disruptive](https://github.com/containers/podman-desktop/assets/19164299/92d71c4f-5e69-494e-904a-7dfcaf597ea1)

I am not sure what this causes, have not found any issue to introduce this feature, nor I am sure where it can be switched off, except going to the system setup. I would prefer this option in podman-desktop.

### Operating system

Fedora 39

### Installation Method

Other

### Version

next (development version)

**Comment by odockal** [comment]
Since I am running the app from locally built binary, I cannot really stop showing notifications from the system settings.

**Comment by odockal** [comment]
I tried multiple thing to get to the root problem, but haven't been successful. Removed .kube folder, restarted podman extension (since it is coming from that extension), tried to set everything I could, but the notification is still popping up. No particular error in the stack trace to suggest the problem is.

**Comment by benoitf** [comment]
closing as dup of https://github.com/containers/podman-desktop/issues/6151

**Comment by afbjorklund** [comment]
The only way to get rid of the notifications (right now), is to run `podman machine init` from the console
