### ISSUE TITLE
bug(extension-api): containerEngine.listContainers return empty array when called in activate on startup

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6276]
### Bug description

When podman-desktop is starting, and activating the extensions, it seems that when extensions are being activating if they call `containerEngine.listContainers` they got an empty array (even if the containers exists).

This only happen in podman-desktop startup, when deactivate/re-activate an extension, there is not issue. 

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Inside any extensions add the following

```
const containers: ContainerInfo[] = await containerEngine.listContainers();
console.log(`[DEBUG] found ${containers.length} containers.`);
```

### Relevant log output

```shell
[ai-studio] [DEBUG] found 0 containers.
```

**Comment by jeffmaury** [comment]
Not sure this is a bug, probably the Podman machine connections are not yet initialized, you shoud listen to events related to them

**Comment by axel7083** [comment]
> Not sure this is a bug, probably the Podman machine connections are not yet initialized, you shoud listen to events related to them

I am making a work around by making a lazy initialization (on webview open) rather than on podman-desktop startup.

**Comment by benoitf** [comment]
It's an expected behavior that you have
You have events on being notified when new containers arrive or when new containers engine are being registered

Code should be event based and not perform only actions at the startup
