### ISSUE TITLE
Create documentation that you cannot create podman machine on Linux, only view / delete.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6278]
### Is your enhancement related to a problem? Please describe

See discussion on: https://github.com/containers/podman-desktop/issues/5823

We should add documentation that explains that you cannot create a Linux machine through the GUI, only CLI. This is intentional in order to not get users to accidentally create a podman machine, as it's not "very supported".

### Describe the solution you'd like

Documentation that to create a podman machine, it is NOT recommended, but can be detected / used.

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/issues/6225

Installing podman engine is not "very supported", either (unless we are counting v3)
