### ISSUE TITLE
Expose shell.openPath via the Podman Desktop API

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6279]
### Is your feature request related to a problem? Please describe

We have opening up an external URL.

I'd like to be able to use the Podman Desktop API in order to have a button that I can click and open a file location using the user's default file manager.

For example.. "Open output directory"

This would be implemented via: https://www.electronjs.org/docs/latest/api/shell#shellopenpathpath similar to openExternal.

### Describe the solution you'd like

Use https://www.electronjs.org/docs/latest/api/shell#shellopenpathpath and implement it to PD API so I can open a file location.

**Comment by benoitf** [comment]
no need for a new API

`window.openExternal` is doing what you need (giving a file:// URI) `api.Uri.file(file)`

**Comment by cdrage** [comment]
> no need for a new API
> 
> `window.openExternal` is doing what you need (giving a file:// URI) `api.Uri.file(file)`

Oh wow! Didn't even realize.

Thank you, i'll try that.
