### ISSUE TITLE
allow to add aliases/display name when authenticating users in registries

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6298]
### Is your enhancement related to a problem? Please describe

some providers are generating very ugly username to log-in to registries

For example, with some SSO, username could be "my-very-long-username-generated-for-podman-desktop"
but as it has been generated using SSO access, I think it would be better to display the account name used for example
`john.doe@company.com`

Of course, hovering or clicking will reveal the real username but by default it would display the alias

### Describe the solution you'd like

- Add option to register alias/display name in addition to the login name in the API
- Render display name instead of the username by default

### Additional context

need to store the alias in auth.json file, can add extra field with podman-desktop name on it.

**Comment by axel7083** [comment]
I am not sure to follow, you want to add it to the _API_ but which one ? the internal of the extensions ? From the title saying registries, and not AuthenticationProvider in the `extension-api`, but registries like quay, google container etc.

> Add option to register alias/display name in addition to the login name in the API

![image](https://github.com/containers/podman-desktop/assets/42176370/f9a7ddd9-10b3-45b4-852c-1bc77b8aafc5)

If you meant the internal you would suggest to add then that mean we should be able to set the alias from the UI, but there not really room in the current UI to add a new input

**Comment by benoitf** [comment]
thanks @axel7083 for raising the point that it's not clear enough

It's for the extension API (for the extensions)

so extension should be able to do instead of something like `addLogin('abc1234566', 'mypassword')`

`addLogin('abc1234566', 'mypassword', 'john@mycompany.com')`

so we display 'john@mycompany.com' and not 'abc1234566' which is the real login name but it might be cryptic


so in your screenshot instead of axel7083 a provider could decide to display your email address instead if you used sso with 'axel@mycompany.com'

**Comment by axel7083** [comment]
Thanks for the clarification
