### ISSUE TITLE
Kubernetes generator seems hidden / hidden feature / no docs

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#632]
### Is your enhancement related to a problem? Please describe

As a fresh user to Podman Desktop, I had no clue where to find the "Generate Kubernetes yaml" feature that people have been talking about.

Wasn't only until I hovered over a container and saw a mysterious button that I can press and generate the YAML!

From my perspective it was:
* Very well hidden
* The icon doesn't indicate anything about Kubernetes (perhaps we can actually use the k8s / a similar logo?)
* It was only until I clicked it (and found it!) did I discover it.

<img width="1083" alt="Screen Shot 2022-10-14 at 9 30 58 AM" src="https://user-images.githubusercontent.com/6422176/195859767-53dd9a9e-3170-4f05-b55b-6e5cb89ba021.png">

### Describe the solution you'd like

Some solutions I can think of:

* Actions IMO shouldn't be hidden and instead maybe be smaller / more transparent and then when you hover it's not
* Icon for generating the k8s files should be different
* Documentation on Podman Desktop

**Comment by benoitf** [comment]
notice: if you click on containers, there is also a tab with the generate kubernetes yaml

**Comment by cdrage** [comment]
> notice: if you click on containers, there is also a tab with the generate kubernetes yaml

Funny enough, I didn't even notice that it was for Kubernetes! I thought it was a "Play .YAML" for Docker or Docker Compose files so I never clicked.

I'll add that to the issue too

**Comment by cdrage** [comment]
Closing this as we've updated the documentation as well as improved the readibility of accessing the extra "actions" which actually list the intention beside it. Now we have a button that says "Generate Kube" beside it.
