### ISSUE TITLE
Remove unused Kubernetes informers

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6322]
### Is your enhancement related to a problem? Please describe

Now that we're using the per-context informers, we can remove the previous informers to clean up the codebase, and ensure we don't accidentally start using them again.

- [ ] #6323
- [ ] Remove API bridges needed to communicate between stores and informers
- [ ] Remove informers from main

### Describe the solution you'd like

Same.

**Comment by feloy** [comment]
@deboer-tim is it ok to close this issue, #6323 being merged?

**Comment by benoitf** [comment]
in 6323 it was noted "First part of https://github.com/containers/podman-desktop/issues/6322." so I guess there are next parts ?

**Comment by benoitf** [comment]
> After this, we could remove the corresponding api bridge and the informers themselves from main.

**Comment by deboer-tim** [comment]
I didn't want to drop the change right before 1.8 and PTO; PR #6465 up now that would close this.
