### ISSUE TITLE
Logs for containers do not fill entire space on first clicking on container details

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#634]
### Bug description

When clicking on the container details, the logs only fill up half the height (see scroll bar to the right):

<img width="949" alt="Screen Shot 2022-10-14 at 9 57 30 AM" src="https://user-images.githubusercontent.com/6422176/195866460-6ded300a-822d-4d08-9ad9-0fdb88821295.png">

### Operating system

macOS M1

### Version

next (development version)

### Steps to reproduce

1. Resize the Podman Desktop window under 600px wide, but make the length long
2. Simply click on the details of any container
3. The logs appear only half the screen, but other tabs appear full.

**Comment by benoitf** [comment]
interesting that you're reproducing it as I was never able to reproduce it

**Comment by benoitf** [comment]
it's a dup of https://github.com/containers/podman-desktop/issues/501
