### ISSUE TITLE
export and import containers

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6355]
### Is your enhancement related to a problem? Please describe

Add ability to export the content of a container or a group of containers and restore them

like for images https://github.com/containers/podman-desktop/issues/478

### Describe the solution you'd like

I should be able to export containers and import them later

### Additional context

Need to have the methods exported/available for extension API as well

**Comment by lstocchi** [comment]
@benoitf how should it work exactly? Do we add a button to the containers table, user click on export, we save the container filesystem into `.local\share\containers\podman-desktop\extensions-storage`, then we add an import action to the images page, user select the archive file and an image with the filesystem is created? I see that the import action also accepts some args. Do we want to support them in this first implementation?

**Comment by benoitf** [comment]
I would add an export action for each of the lines

then a button (like the delete when you select multiple rows)

and probably an 'import' button to import again the files

about the location, I would not pickup `.local\share\containers\podman-desktop\extensions-storage` as it's dedicated for extensions.

Maybe it would be easier to prompt the user to select the location (maybe as step 1 we always ask, later we could have a properties to select folders, remember last folder etc)

For now let's try without the args and see how it behave

**Comment by benoitf** [comment]
also I think that backup/restore of images is more important than the backup/restore of containers but I may be wrong

**Comment by lstocchi** [comment]
@benoitf charlie said that he preferred to work on images and we switched issues. He will work on images

**Comment by benoitf** [comment]
ok thanks for the notice 👍

**Comment by lstocchi** [comment]
Closing as an initial implementation of export/import has been merged.
