### ISSUE TITLE
Acceptance criteria to document Authentication Page feature, and also Authentication providers (in form of extension), prepare examples and steps to verify its functionality

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6362]
We need to know acceptance criteria for this feature in order to completely cover the feature with tests.

Write down the guide how to test the feature.

**Comment by xbabalov** [comment]
Cannot fully document, waiting for https://github.com/containers/podman-desktop/pull/5400 to be finished.

**Comment by odockal** [comment]
Closing for now, we can reopen if needed.
