### ISSUE TITLE
should allow to install podman v5 using an experimental flag

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6375]
### Is your enhancement related to a problem? Please describe

To make the migration from v4 to v5, it should be possible to have podman v5 embedded so we can do the tests in term of release, fetching artifacts, etc.

### Describe the solution you'd like

add an experimental flag to enable Podman v5 installer

if enabled it should allow to update to v5, do all the save/restore flow, etc.

**Comment by afbjorklund** [comment]
Be aware that testing podman v5 will upgrade configuration and suggest to destroy machines etc.

So it might not be easy, or even possible, to get back to an existing podman v4 installation afterwards...

**Comment by benoitf** [comment]
@afbjorklund yes understood, it's to be able to test the upgrade flow

'kind of downgrading' should still be possible by wiping out all config data, machines and restoring images in the podman machines

it'll be more a 'create again' than a 'revert' of course.

But here, yes it's to be able to validate if I have podman 4, if I follow all the steps in the UI, at the end I have podman 5 and my machine is able to boot/ works fine (and hopefully I can have my previous images there, etc)

**Comment by afbjorklund** [comment]
The process was similar, when podman v4 changed the configuration of existing podman v3 machines.

`Migrating machine "podman-machine-default"`

`Error: error listing vms: json: cannot unmarshal object into Go struct field MachineVM.IgnitionFilePath of type string`

```diff
- "IgnitionFilePath": "/home/anders/.config/containers/podman/machine/qemu/podman-machine-default.ign",
+ "IgnitionFilePath": {
+  "Path": "/home/anders/.config/containers/podman/machine/qemu/podman-machine-default.ign"
+ },
```

But that time I don't think you had to delete everything and start over, and that it upgraded automatically

`Error: incompatible machine config "/home/anders/.config/containers/podman/machine/qemu/podman-machine-default.json" (podman-machine-default) for this version of Podman`

Seems like some users will stay on podman v4 forever...

Just as other users will probably not get past podman v3?
