### ISSUE TITLE
publish webview api to @podman-desktop/webview-api

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6380]
### Is your enhancement related to a problem? Please describe

I see that some extensions are declaring a .d.ts file 

with

```
declare global {
  export interface PodmanDesktopApi {
    getState: () => any;
    postMessage: (msg: any) => void;
    setState: (newState: any) => void;
  }

  function acquirePodmanDesktopApi(): PodmanDesktopApi;
}

export { PodmanDesktopApi };
````

we should try to look if we can publish the declaration of this API so extensions don't need to declare it

### Describe the solution you'd like

publish the declaration if possible

**Comment by dgolovin** [comment]
@benoitf

Considering that:

* only extensions depend on it
* the PR #17961 introducing publishing of this package along with @podman-desktop/api with exactly the same version even without any changes in webview API itself

would it be better to have it as part of podman-desktop/api ui module?

The only reason to extract it to the independent package would be adoption outside of podman desktop and then being able to use that outside of extension.

I have the same problem with podman exec API here #5990 and I don't see any benefites of publishing it outside of @podman-desktop/api

**Comment by dgolovin** [comment]
Basically we add additional packaging scripts, going to publish the packages with the same content most of the time and all that in the name of only extensions using it as separate package.

**Comment by dgolovin** [comment]
@benoitf
NM my question, it is a moot now. I see that it is indeed used separately in frontend part of extension.

**Comment by benoitf** [comment]
ok

We have podman desktop ai lab extension that would require podman extension as well ( and depends on a specific .d.ts for type checking)
