### ISSUE TITLE
Podman Machine: Admin privilege handling when using hyperV on Podman Desktop

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6387]
### Is your enhancement related to a problem? Please describe

Based on the result of https://github.com/containers/podman/issues/21995 discussion, podman machine creation using HyperV hypervisor requires admin privileges. Podman Desktop needs to be prepared for this to pass/handle the request.

### Describe the solution you'd like

Handle the request for (if needed at all) the admin privilege for the user same as ie. compose system wide installation.

**Comment by odockal** [comment]
An example of how it can look like with a podman machine created from podman desktop without admin privileges using hyperv:
![podman_machine5_hyperv](https://github.com/containers/podman-desktop/assets/19164299/99a92fe4-9fe5-42da-9bca-343f6beb51cb)

**Comment by jeffmaury** [comment]
We will not handle this as admin will be a requirement to use HyperV in Podman Desktop
