### ISSUE TITLE
Port validation in the Run Image Page is not properly validating the port value until port number has 4 digits

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6390]
### Bug description

![port_already_in_use](https://github.com/containers/podman-desktop/assets/19164299/5eb7b713-c416-43ec-9b3e-433198083da6)

### Operating system

Fedora 39

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

1. Start container with a port exposed (httpd-24)
2. Try to create/start another container with exposed port
3. Assert: default port is different from first app.
4. Try to change the port number and see validation message
5. Assert: Port number is evaluated and the message fits
Actual result: port number under < 1000 shows unfitting message (`port X is already in use`)

### Additional context

Given the message here, I am assuming that port number < 1000 is not a problem. Also, not a number character should probably trigger different message, although the message is not incorrect then.

![Screenshot_20240312_165525](https://github.com/containers/podman-desktop/assets/19164299/84e51465-39b5-4109-a990-3f009facabe6)

**Comment by benoitf** [comment]
maybe a dup of https://github.com/containers/podman-desktop/issues/6364

**Comment by axel7083** [comment]
I am not reproducing on Windows

https://github.com/containers/podman-desktop/assets/42176370/99abaf76-d1f2-43f9-aa69-ce505071e2d3
