### ISSUE TITLE
Review Podman Desktop Screens for inconsistencies

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#6405]
### Is your enhancement related to a problem? Please describe

When using Podman Desktop we noticed there are multiple fonts and colors used on a single screen which makes takes away from the visual appeal.  It is also often hard to note where the focus should

### Describe the solution you'd like

I would like the screens to be more visually appealing and consistent

### Tickets logged in relation to this issue:

- [Add padding after the last card/component on a page.](https://github.com/containers/podman-desktop/issues/8073) 
- [Fix left padding on Extensions pages](https://github.com/containers/podman-desktop/issues/8074)

**Comment by ekidneyrh** [comment]
Opened the below for minor visual fixes
[Add padding after the last card/component on a page.](https://github.com/containers/podman-desktop/issues/8073) 
[Fix left padding on Extensions pages](https://github.com/containers/podman-desktop/issues/8074)

**Comment by ekidneyrh** [comment]
I feel like this can be closed as identifying inconsistencies is going to be an ongoing process. 

Tickets for fixing inconsistencies will be logged as they are seen.
