### ISSUE TITLE
Kube context is not loaded in podman desktop until restart

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6406]
### Bug description

I have no `~/.kube/config` file, thus not kube context available. I install DevSandbox extension in Podman Desktop and create a dev-sandbox resource (aka logging in and getting oc login command). At this moment I have my `~/.kube.config` filled with information about dev sandbox cluster and technically can connect to it. Podman Desktop has not information about the context until I restart it, then it works.

### Operating system

Windows 10, 11

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

0. Make sure to remove any kubeconfig file beforehand. `rm -rf ~/.kube`
1. Start up podman desktop
2. Crate and start podman machine
3. Download Kind/Minikube or install dev sandbox
4. Create a kind cluster (or any other that touches ~/.kube/config and add new kube context)
5. Assert: New kube context is available in the Podman Desktop
Actual result: No kube context added. Only after restart or reenblement of the kube-context extension

### Additional context

Kind and minikube could have the same problem, I believe.

**Comment by feloy** [comment]
related to #6307

**Comment by cdrage** [comment]
Encountered the same issue today, and with the included fix of #6307 

Mine was the fact that the Kubernetes dashboard sections did not appear until restart either.

**Comment by jeffmaury** [comment]
Cannot reproduce using 1.10.0-next

**Comment by odockal** [comment]
@jeffmaury Cleaned up all the machine. hit this again, except with OpenShift Local adjusted kubeconfig.

**Comment by odockal** [comment]
Disable+enable of Kube-context extension did the job though.

**Comment by feloy** [comment]
@odockal I cannot reproduce the issue on Windows 11 with Podman Desktop v1.10.2

Is it reproducible on your side with this version?

**Comment by odockal** [comment]
@feloy It is reproducible with 1.10.3 as well. I have update steps to reproduce.

![kube-context-not-loaded](https://github.com/containers/podman-desktop/assets/19164299/cf8411d2-d2d8-4289-bfea-bbad42136bfc)

**Comment by feloy** [comment]
Thanks @odockal. The trick was to remove the parent directory (`.kube/`), not only the kubeconfig file, as noticed by @axel7083 in https://github.com/containers/podman-desktop-extension-ai-lab/pull/1135, but I was only removing the kubeconfig file.

I tested by removing the parent directory, and it is effectively reproducible. I'll make a fix

**Comment by odockal** [comment]
@feloy Great! It is always the best to have the very precise steps to reproduce. Thanks!
