### ISSUE TITLE
UX: make featured extensions look more special than the all extensions section on catalog page

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#6420]
### Is your enhancement related to a problem? Please describe

It came up in the UX call today that the user could get confused or frustrated seeing a feature in both the 'featured extensions' section and the 'all extensions' section. This could be because both sections look similar. 

### Describe the solution you'd like

Suggest making the 'featured extensions' look more special and different than the 'all extensions' to help visually seperate them from each other. Maybe bring in use of carousel?

![image](https://github.com/containers/podman-desktop/assets/87311656/26c1f2ba-46e6-4cea-aa7d-19679acf1ede)

Carousel:
![image](https://github.com/containers/podman-desktop/assets/87311656/f154f0f5-0e13-48fa-90f0-46da0759b2be)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/acc057fb-7010-498c-b31b-efc382960d51)


Had a look at this, maybe the way to go could be using the cards like in the learning centre? This gives the user the option to hide them then also. 

Diff states for these cards can be defined / documented in the design system. I saw some already created in the penpot file:
![image](https://github.com/containers/podman-desktop/assets/87311656/6fe800a1-dc3b-4e94-8ac1-1dcb0f0cfed7)

WDYT @asamalik?

**Comment by asamalik** [comment]
That looks nice! But it hasn't removed those duplicate items.

What about this:

(And here I'm learning the tool, so this is a quick draft I made in Inkscape — the colors are horrible on purpose, all I want to communicate is the layout. You can make things way nicer than I can anyway! 😄)

![Screenshot 2024-03-15 at 13 09 58](https://github.com/containers/podman-desktop/assets/8568255/8992c4c0-f022-4146-90c6-f12c3009f7be)

![Screenshot 2024-03-15 at 13 10 01](https://github.com/containers/podman-desktop/assets/8568255/c924c5d7-5cc6-45ed-9fa8-ccf33059b7e8)

Here I merged both the **Featured Extensions** and the **Available Extensions** together to get rid of the duplicities. And then I somehow highlighted the featured ones. That would need to be done in a better way than this of course! 

What do you think about this direction?

**Comment by asamalik** [comment]
I can imagine the "Featured" designator could be many different things, like a badge, or an icon, or even slightly different background and border... anything to make it nice, distinct, and clear that it's featured. 

Maybe you can even reuse what you've done, and use the bigger cards in there.

**Comment by benoitf** [comment]
on my side I like the proposal to display featured first using almost the same layout

![image](https://github.com/containers/podman-desktop/assets/436777/45885dcf-d691-4870-8fba-a19235f4c82a)

**Comment by ekidneyrh** [comment]
I really like that idea!! I'll mock it up on penpot :p

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/c40788e7-f0bf-41b8-a196-d932f3e729da)
 something like this?
