### ISSUE TITLE
I can't compile v1.8.0 because of dependency issues. Why is ssh2@1.11.0 specified?

### ISSUE THREAD

**Issue by BurntVoxel** [containers/podman-desktop#6426]
### Bug description

I noticed the issue when I couldn't download the update from the AUR. And I tried again downloading the github source, and had the same issue. (I've attached a transcript of the terminal output, with emojis in lieu of the terminal's highlighting.) [yay-podman_desktop.txt](https://github.com/containers/podman-desktop/files/14608277/yay_podman-desktop.txt) 

Long story short, I don't know if this is the *only* reason I can't compile it, but, I narrowed *one* issue down. 

- Terminal output mentions `warning Resolution field "ssh2@1.11.0" is incompatible with requested version "ssh2@^1.15.0"`
- `package.json` includes a Resolutions entry for ssh2 at v `1.11.0`
- The dependency tree states that `docker-modem@5.0.3` requires ssh2@^1.15.0. See [yarn_list.txt](https://github.com/containers/podman-desktop/files/14608150/yarn_list.txt)

I'd test if removing that restriction to use ssh v1.11 fixes this, but I've never used Yarn 1.x.

The terminal mentioned several more issues, but maybe we should walk through this one at a time.

// Also, forgive me if this really is something wrong on my end. I'm new to Arch Linux. 

### Operating system

Endeavour OS x64 (Linux kernel 6.7.9-arch1-1, bash 5.2.26)

### Installation Method

Other

### Version

1.8.0

**Comment by BurntVoxel** [comment]
Crap, the terminal log didn't get uploaded first try. Here it is.
[yay_podman-desktop.txt](https://github.com/containers/podman-desktop/files/14608277/yay_podman-desktop.txt)

**Comment by benoitf** [comment]
There was some segmentation fault using a recent one https://github.com/containers/podman-desktop/pull/3179

Using yarn v1 it's working fine, we can compile (at least CI is building it for mac, Windows and Linux and flatpak)

based on your report error, can you check that you've the dependencies being installed

https://github.com/containers/podman-desktop/blob/main/CONTRIBUTING.md#prerequisites-prepare-your-environment

**Comment by BurntVoxel** [comment]
Looks like `pacman` automatically handled that. 
I have yarn v1.22.21, Node 20.11.1, and node-gyp 20.11.1

// Maybe I should've closed the [discussion thread](https://github.com/containers/podman-desktop/discussions/6415#discussioncomment-8792228) about the same issue.

**Comment by BurntVoxel** [comment]
Looks like `pacman` automatically handled that. 
I have yarn v1.22.21, Node 20.11.1, and node-gyp 10.0.1

// Maybe I should've closed the [discussion thread](https://github.com/containers/podman-desktop/discussions/6415#discussioncomment-8792228) about the same issue. Kinda forgot about that while I was trying to investigate the dependency issue.

**Comment by benoitf** [comment]
now we're using latest ssh version, no more resolution mechanism https://github.com/containers/podman-desktop/pull/8543
