### ISSUE TITLE
Provide visible button to push an image even when no registries are configured

### ISSUE THREAD

**Issue by apupier** [containers/podman-desktop#6428]
### Is your enhancement related to a problem? Please describe

The button to push an image is not displayed when there is no registry configured in the settings.

### Describe the solution you'd like

I would like to see the button to push an image in the UI always.

It can be disabled with a tooltip mentioning why and how to configure a registry. or it can be enabled and provide a wizard to configure the registry.

**Comment by benoitf** [comment]
hello, it looks like a dup of https://github.com/containers/podman-desktop/issues/5506

it's closed and is available in 1.8.0

**Comment by benoitf** [comment]
the PR fixing the issue https://github.com/containers/podman-desktop/pull/5857
