### ISSUE TITLE
Error thrown when trying to create podman machine from dashboard via onboarding flow on Windows

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6430]
### Bug description

If the user presses the "Initialize and Start" button from the dashboard to create a podman machine, a few seconds after an error with the message `No container connection found for provider` will be displayed to the user on Windows platform. Even though the error is thrown, in the background it seems the onboarding workflow continues to work and in the end the podman machine gets created.

https://github.com/containers/podman-desktop/assets/106525396/74a96358-9c35-4734-8942-b1e0e24c0121

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

1. Have latest Podman Desktop release installed.
2. Do not have any podman machines created on the system.
3. Press the "Initialize and Start" button from the dashboard.
4. Notice the error is thrown.

### Relevant log output

```shell
ProviderConfigured.svelte:37 Error while starting the provider Error: No container connection found for provider
c @ ProviderConfigured.svelte:37
await in c (async)
(anonymous) @ ProviderConfigured.svelte:44
sS @ utils.js:41
(anonymous) @ Component.js:47
kS @ scheduler.js:99
Promise.then (async)
$S @ scheduler.js:20
UR @ Component.js:81
(anonymous) @ Component.js:139
(anonymous) @ DashboardPage.svelte:38
i @ index.js:56
Oy @ providers.ts:58
await in Oy (async)
(anonymous) @ providers.ts:64
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

### Additional context

Podman version 4.9.3 was used.

**Comment by odockal** [comment]
Happened to me as well during testing of Podman 5 RC6. It is all about having this triggered from dashboard. I am not sure but it differs from `Settings -> Resources -> Create New Podman Machine` path.

**Comment by axel7083** [comment]
I do not reproduce on windows 11, with podman machine v5.0.1

**Comment by odockal** [comment]
@axel7083 With 5.0.2 Windows 10 I also could not reproduce. 
So I tried 4.9.4. It also was alright. I am curious whether we will see the issue during testing then. If not, we can close.

**Comment by axel7083** [comment]
Closing for now, re-open if it happen again !
