### ISSUE TITLE
Podman Crashing on startup 

### ISSUE THREAD

**Issue by response-404** [containers/podman-desktop#6457]
### Bug description

`Translated Report (Full Report Below)
-------------------------------------

Process:               Podman Desktop [3632]
Path:                  /Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop
Identifier:            io.podmandesktop.PodmanDesktop
Version:               1.7.1 (1.7.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2024-03-19 08:03:55.5072 +0530
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Bridge OS Version:     8.2 (21P2057)
Anonymous UUID:        45C4AAAB-DB3F-6801-C46D-1178BF854F29

Time Awake Since Boot: 2900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [3632]`

### Operating system

macOS Sonoma 14.2.1

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

**Comment by benoitf** [comment]
hello @response-404 do you have the full stack of the core crash ?
