### ISSUE TITLE
Podman Desktop crashing on startup

### ISSUE THREAD

**Issue by peterwwillis** [containers/podman-desktop#6458]
### Bug description

Install podman-desktop from brew, which installs 1.7.1. Configured and set up new machine with all defaults. This is the first time I've tried installing.

On upgrade (from the UI) to 1.8.0, app icon just creates the spinning wheel icon.

Trying to diagnose the problem, I was only able to reproduce the spinning wheel once, not exactly sure how. Further attempts to reproduce have failed, but some strange other bugs are observed.

### Operating system

macOS Ventura 13.6 (Apple M1 Max)

### Installation Method

None

### Version

1.8.0

### Steps to reproduce

1. Run `brew install --cask podman-desktop`
2. This installs version 1.7.1
3. Set up machine, configuration
4. Click upgrade button on Podman Desktop dashboard to upgrade to 1.8.0
5. Attempted to run Podman Desktop from Launchpad.
6. Icon appeared in top icon bar, but on mouseover, just spins.
7. `brew uninstall --cask podman-desktop`
8. Install .dmg from website
9. Try to run from Launchpad
10. Same spinning icon

### Relevant log output

```shell
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders
API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
```

```
$ docker context ls
NAME               DESCRIPTION                               DOCKER ENDPOINT                                       ERROR
colima             colima                                    unix:///Users/MYUSER/.colima/default/docker.sock
default            Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *                                              unix:///Users/MYUSER/.docker/run/docker.sock
docker-in-docker   docker-in-docker                          tcp://localhost:12345
lima                                                         unix:///Users/MYUSER/.lima/docker/sock/docker.sock
lima-docker                                                  unix:///Users/MYUSER/.lima/docker/sock/docker.sock
```

```
$ tree $HOME/.local/share/containers/podman-desktop
/Users/MYUSER/.local/share/containers/podman-desktop
├── configuration
│   └── settings.json
├── contributions
├── extensions-storage
│   └── podman-desktop.podman
├── plugins
└── plugins-scanning

7 directories, 1 file
```

### Additional context

There's actually like a half dozen different bugs I'm seeing, but the main one is the Podman Desktop icon just spinning after upgrading from 1.7.1 to 1.8.0.

I attempted to just run the helper manually but just got crashes. I guess you're not supposed to start it this way

I uninstalled the Homebrew `docker-compose` and then manually stopped and started the machine

I edited `/Users/MYUSER/.local/share/containers/podman-desktop/configuration/settings.json` to disable the Docker extension

At some point I attempted running from Launchpad again, and the dashboard started up.

I then attempted to uninstall the .dmg-installed Podman Desktop, and tried to remove all files in my home directory related to Podman.

I then installed podman desktop 1.7.1 through homebrew again, did *not* do the setup, then clicked the 1.7.1 upgrade button in podman desktop, upgraded to 1.8.0, and no crash. So I can't currently reproduce the crash.

However, even after creating a machine again, I notice the following bugs:

1. Even if I stop the docker machine, Podman Desktop's dashboard says my Podman Machine is running with a green icon.
2. The dashboard now says "Docker Socket Compatibility: Docker socket is not reachable. Docker specific tools may not work. Press 'Docker Compatibility Mode' to enable.", but if I press the button, it asks me if I want to *Disable* it. No matter how many times I click it, or if I restart the machine, it still just says it's enabled and do I want to disable it.
3. If I try to start the machine via GUI, I get "Error while starting Podman Machine: Command execution failed with exit code 125".

Because I started the desktop from command line, I got the following extra output (not output on gui):
```
[podman] Command execution failed with exit code 125: Command execution failed with exit code 125
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:304:13044)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  exitCode: 125,
  command: 'podman',
  stdout: 'Starting machine "podman-machine-default"',
  stderr: 'Error: cannot start VM "podman-machine-default": another instance of "/opt/homebrew/bin/qemu-system-aarch64" is already running with process ID 17967: please stop and restart the VM',
  cancelled: false,
  killed: false
}
```

I kill the process ID, then start the machine again, and the desktop appears to reflect the machine running.

So I quit the desktop and stop the machine.

Then I start the desktop again from Launchpad, and I get the spinning icon again.

I kill all Podman processes to get the app to die and the icon disappears.

I then start podman desktop again, and... it starts up fine.

I stop the machine, and exit the desktop app. Then start it again... and it starts fine. I can't get the spinning icon now.

I go back to trying to disable docker compatibility mode. I click button, it asks me if I want to disable, I confirm, it asks me if I want to restart machine, I say yes. I wait for machine to restart. When machine comes back up, I don't see the "it's disabled" message now, so I click docker compatibility button again, and it asks me if I want to disable. Same thing again.

It was only later that I saw the docker context selected wasn't the default, so I changed that back to default. Now that the desktop is not crashing, and the machine comes up when the desktop starts, the docker integration (`docker ps`) is working as expected.

(fwiw, I didn't have lima/colima started, so pretty sure that wasn't conflicting as the other qemu running)

I really don't know what's going on...

**Comment by benoitf** [comment]
hello @peterwwillis 

when you see the spinner, can you open the debug console with <kbd>⌥ (Option)</kbd> + <kbd>⌘ (Command)</kbd> + <kbd>i</kbd> on macOS

you should see something in the console log ?

**Comment by peterwwillis** [comment]
@benoitf I wasn't able to see anything in the console, but in the Activity Monitor the process was shown as not responsive, so I generated a sample and a spindump of the process:

[sample.tgz](https://github.com/containers/podman-desktop/files/14736897/sample.tgz)

**Comment by benoitf** [comment]
ok thanks, but it looks like it might be related to electron itself

can you try with some nightlies where electron has been updated ?

They're from https://github.com/containers/podman-desktop/releases

**Comment by peterwwillis** [comment]
@benoitf I just tried the nightlies, same hanging (this time at the opening splash screen)
[sample_nightly.tgz](https://github.com/containers/podman-desktop/files/14736998/sample_nightly.tgz)

However, I force-killed it and started it from the terminal (`/Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop`), and it started right up with no hanging.

**Comment by benoitf** [comment]
Ok so it looks like it's related to your environment variables
As by default the App is not having all the env variables that you might get as starting from a shell

do you have some env variables that you have in your user profile or some PATH being in your user profile but not for default applications ?

**Comment by peterwwillis** [comment]
I'm sure I can find different environment variables, but the problem is that the hanging doesn't happen consistently. Right now I can open up Podman Desktop from the launcher and it starts up just fine, but earlier it was hanging.

I'm not very familiar with macs; is there something like strace I can attach to the process to debug further? (Assuming the spindump doesn't help)
