### ISSUE TITLE
Improve webview navigation

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6482]
### Is your enhancement related to a problem? Please describe

Two separate but related issues:

If you want to open a webview you need to use its id. These are assigned on startup based on startup order and what else is installed (0, 1, 2, etc) so you always have to use listWebviews() first and look for the expected viewType. This is just an extra step that doesn't provide any abstraction.

There is no API to open a subpage within a webview, e.g. 'webview/models-page'.

### Describe the solution you'd like

It would be preferable if for simple cases you could call without calling listWebviews() first. For instance:
- Using viewType as the argument, since that's the only thing each webview controls, or
- Having predictable ids, e.g. based on the extension id and/or viewType (unless an extension registers two, then they'd need different ids).

For subpages, a second optional path argument could be added. It would be nice if it allowed passing parameters, e.g. 'webview/build-page?image=xyz'.

### Describe alternatives you've considered

createWebviewPanel() could return the assigned id, but that would only let each extension easily open its own webviews.

**Comment by benoitf** [comment]
> There is no API to open a subpage within a webview, e.g. 'webview/models-page'.

There won't. It's not possible. Everything that is inside the webview is up to the page. It only display an index.html file


> It would be preferable if for simple cases you could call without calling listWebviews() first. For instance:
> For subpages, a second optional path argument could be added. It would be nice if it allowed passing parameters, e.g. 'webview/build-page?image=xyz'.

it is not possible. We're not serving web pages.


I think you're not understanding how webview are working. From the Podman Desktop POV it's like a black box.
And also I'm not sure to follow the requests.

if you need to open a dedicated page, you should call the command that will set whatever you need.

like if you have a command in your plug-in: showMeBuildPage then when calling that command, in your model you update the page to be like 'BuildPage' and then when frontend check which page to display it'll tell 'BuildPage'




> It would be preferable if for simple cases you could call without calling listWebviews() first. For instance:
> Using viewType as the argument, since that's the only thing each webview controls, or
Having predictable ids, e.g. based on the extension id and/or viewType (unless an extension registers two, then they'd need different ids).

Again I think you're following some anti-patterns.

The extension owns the webview so if you need to bring back the webview, as the extension has a reference to the webview it created, it can reveal it again, no need to ask to list all webviews

**Comment by deboer-tim** [comment]
Closing. Webviews can do their own internal navigation, and listWebviews()/navigateToWebview() works fine today. reveal() would be a preferred way for a webview to open itself and isn't working today, but there is already an issue tracking that.
