### ISSUE TITLE
Review Podman Desktop screens for inconsistencies: Dashboard

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#6493]
Is your enhancement related to a problem? Please describe

When using Podman Desktop we noticed there are multiple fonts and colors used on a single screen which makes takes away from the visual appeal. It is also often hard to note where the focus should
Describe the solution you'd like

I would like the screens to be more visually appealing and consistent

This is an extension of #6405

**Comment by ekidneyrh** [comment]
I had a look at how the dashboard looks now, vs what it is meant to look like per the mock-ups.

This is what it looks like:
![Screenshot from 2024-03-22 12-08-29](https://github.com/containers/podman-desktop/assets/87311656/7317b712-5677-4f45-b4b8-5811d2e143ef)

And here's the proposed look:
![Screenshot from 2024-03-22 11-58-37](https://github.com/containers/podman-desktop/assets/87311656/c85e5cdb-f586-4d6f-8be4-37993834aae1)

There's a few things that I documented and can potentially be used across the entirety of the app. I tried to visualise them as best I could. 

## Padding:

![Screenshot from 2024-03-22 12-13-10](https://github.com/containers/podman-desktop/assets/87311656/eebb0948-4829-4479-a285-90c231e1e91d)

## Type:

![Screenshot from 2024-03-22 13-17-57](https://github.com/containers/podman-desktop/assets/87311656/43f45d84-5d9f-484c-a330-09eae18aed30)

## Alignment:

![Screenshot from 2024-03-22 17-17-57](https://github.com/containers/podman-desktop/assets/87311656/87659839-d80b-4815-b732-81ad521c74e3)

## Colour 

![Screenshot from 2024-03-22 18-16-11](https://github.com/containers/podman-desktop/assets/87311656/8bd947dc-c25e-426a-a16d-4d7b29fdcc29)

**Comment by ekidneyrh** [comment]
Also colours for light mode:

![Screenshot from 2024-03-22 18-27-12](https://github.com/containers/podman-desktop/assets/87311656/9772953f-03f7-484d-bec7-7aa2a2aa95dd)

**Comment by deboer-tim** [comment]
FYI, I don't know where the mockup is in penpot, but there's a updated design for the provider cards: https://github.com/containers/podman-desktop/issues/4395#issuecomment-1837671784

**Comment by ekidneyrh** [comment]
> FYI, I don't know where the mockup is in penpot, but there's a updated design for the provider cards: [#4395 (comment)](https://github.com/containers/podman-desktop/issues/4395#issuecomment-1837671784)

Do you think this is something that'll be implemented before summit? If it can be I'll change the above to incorporate that.

**Comment by deboer-tim** [comment]
> Do you think this is something that'll be implemented before summit? If it can be I'll change the above to incorporate that.

There are still issues and parts of the design not complete, but the basic cards have been in since at least 1.7.

**Comment by ekidneyrh** [comment]
> > Do you think this is something that'll be implemented before summit? If it can be I'll change the above to incorporate that.
> 
> There are still issues and parts of the design not complete, but the basic cards have been in since at least 1.7.

Okay thanks I'll take a look!

**Comment by ekidneyrh** [comment]
Posted a comment in regard to the ticket you mentioned above about the new provider cards: https://github.com/containers/podman-desktop/issues/4395#issuecomment-2019988778 Once a design is agreed upon, I can redo my original comments
