### ISSUE TITLE
Podman Desktop does not able to update or create new podman vm

### ISSUE THREAD

**Issue by xxTBxx** [containers/podman-desktop#6495]
### Bug description

Fresh install of Podman Desktop 1.8.0 on Windows 10 22H2, install was smooth. In my case have I have prior wsl vm for podman with version 4.1.1 which podman found. Had issues attempting to upgrade existing wsl vm. Steps taken:

1. Podman desktop found prior VM but the status of the vm differed between the dashboard and resources pages.
![2024-03-20 16_51_13-Podman Desktop](https://github.com/containers/podman-desktop/assets/65740000/7006bf06-8dd9-477a-ae97-91bbf645cf17)
![2024-03-20 16_51_06-Podman Desktop](https://github.com/containers/podman-desktop/assets/65740000/22532518-ddf2-42e6-bbb2-834b9c47a819)

2. I followed the dashboard wizard to upgrade and it reports that it was upgraded to version 4.9.3.

3. Dashboard shows notification to "set up" podman and the podman widget that shows initialize and start.
![2024-03-21 10_11_52-Podman Desktop](https://github.com/containers/podman-desktop/assets/65740000/9a0388f1-8f13-4975-ab28-7dd7d172ff02)

4. Running the notification setup wizard has an error that "podman-machine-default" already exists modifying the name of the VM in the wizard allows it to complete. (I choose "podman-machine" as name) After running setup wizard notification to set up podman does not clear. Can confirm that new wsl vm was created, but podman doesn't appear to have picked it up:
```
PS> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
podman-machine
podman-machine-default
```
No podman vm resources are shown on resources setting page.

5. Selecting "initialize" or "initialize and start" on the dashboard podman widget returns:

```
Initialization failed. Please check the error below and try again
Error: Command execution failed with exit code 125
Command execution failed with exit code 125
sh: line 1: /etc/containers/registries.conf.d/999-podman-machine.conf: No such file or directory
Error: system connection "podman-machine-default" already exists. consider a different machine name or remove the connection with `podman system connection rm`
```
As far as I can tell there does not appear to be a way to resolve this from Podman Desktop nor does Podman desktop seem to be able to register a VM with a separate name.

### Operating system

Windows 10 22H2

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

**Comment by JerryMWeeks** [comment]
If you hit this issue. Use wsl and remove the old installation:

`wsl --unregister podman-machine-default`

Then click the initialize and install button in desktop again.

It worked easily for me!

![Image](https://github.com/user-attachments/assets/b981c4db-c6a5-4da9-9d7c-e281f2070102)
