### ISSUE TITLE
Creating image on Windows fails:  Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"

### ISSUE THREAD

**Issue by torbica** [containers/podman-desktop#6497]
### Bug description

After upgrade to 5.0 I wanted to create new podman machine from UI and got following error:;

Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"

### Operating system

Windows 11

### Installation Method

Winget (Windows)

### Version

1.8.0

**Comment by jeffmaury** [comment]
Podman 5.0 support in Podman Desktop in planned as experimental in 1.9.0 and full support in 1.10.0

**Comment by torbica** [comment]
Thanks. Podman 5.0 was automatically upgraded via winget.
