### ISSUE TITLE
Refactor E2E tests podman desktop home location in PodmanDesktopRunner

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6506]
### Is your enhancement related to a problem? Please describe

Now if I run the e2e tests on CI, I got this output folders:
`tests/output/*xml`
`tests/playwright/tests/output/`

### Describe the solution you'd like

We should refactor the behavior of a relative output folders and podman desktop home folder used during e2e tests run. In respect to a option to have an extensions available on tests start mainly for PR check of the external extensions.

**Comment by cbr7** [comment]
@odockal I'm not sure I understand what this issue is about, can you please clarify and provide some specifics?

**Comment by cbr7** [comment]
I don't think this issue is relevant any longer, output files are configured in the `playwright.config.ts` both in the main repo and in the extensions repo, so each extension can have whatever custom output path it wants. Closing this.
