### ISSUE TITLE
VM disk size validation rules are mutually exclusive on macOS

### ISSUE THREAD

**Issue by jmillikin** [containers/podman-desktop#6507]
### Bug description

During the initial setup, the slider to select the VM disk size wouldn't let me select 100 GB exactly. When I try to type in 100 GB in the text entry widget, the validation reports mutually exclusive errors and forbids every value I tried to enter.

Screenshots:

<img width="504" alt="Screenshot 2024-03-24 at 13 36 26" src="https://github.com/containers/podman-desktop/assets/646128/36cf2694-6c57-4c20-8eec-6506d781da24">

<img width="516" alt="Screenshot 2024-03-24 at 13 36 33" src="https://github.com/containers/podman-desktop/assets/646128/548b6185-d56b-4be4-83fb-6ae4e2ca521e">

### Operating system

macOS Sonoma 14.4

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

**Comment by benoitf** [comment]
hello @jmillikin could you report how many free space do you have on your disk on macOS ?

because max value is computed from the available free space on the disk

**Comment by jmillikin** [comment]
I have about 1.5 TiB free space. The slider lets me select much more than 100 GB, it's only the text entry field that seems to be affected.

**Comment by jmillikin** [comment]
Screen recording of the bug, since I'm not sure my description was easy to understand.

https://github.com/containers/podman-desktop/assets/646128/082b176e-dac3-40f1-bfcd-a5ef091606ac
