### ISSUE TITLE
Packaging components

### ISSUE THREAD

**Issue by feibaihengmo** [containers/podman-desktop#6508]
### Is your enhancement related to a problem? Please describe

I hope to obtain the composite component and k8s component, but downloading them internally in the software is too slow. So can we release an installation package that comes with this component

### Describe the solution you'd like

I hope to obtain the composite component and k8s component, but downloading them internally in the software is too slow. So can we release an installation package that comes with this component

### Describe alternatives you've considered

I hope to obtain the composite component and k8s component, but downloading them internally in the software is too slow. So can we release an installation package that comes with this component

**Comment by benoitf** [comment]
hello @feibaihengmo could you be more specific about the composite component and k8s component ?

you mean the `compose` or `kubectl` binaries ? `minikube` binary , `kind` binary ? all of them ?

**Comment by afbjorklund** [comment]
Not sure why it would be faster to download them with the podman installer, instead of individually...
