### ISSUE TITLE
inconsistent / misleading info in dialogs around status

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#6513]
### Bug description

Had docker running. killed it. podman desktop was running already and it showed I needed to update. update ran for v1.8.

Now I have it telling me docker compatabilty is disabled, and I should enable it.

but dialog is asking both to disable and enable it in one go.

<img width="1050" alt="2024-03-24_19-58-20" src="https://github.com/containers/podman-desktop/assets/54129/5dc0335f-9031-44e8-903c-06db6c639bfb">

I'm assuming the last paragraph is the same no matter what -but it makes the UI very ambigous waning it needs to enable compatability, but when clickin saying its disabling it...

so i disable it, and it still tells me things are not enable...click compat - now it says it is going to enable it:

<img width="1050" alt="2024-03-24_19-59-03" src="https://github.com/containers/podman-desktop/assets/54129/d9c1390c-1ac3-45a3-9ec4-4d41fe9fed7a">

but nothing changes.

It does podman is running but if i go to settings It says "starting"...and I can neither stop, delete or anything that seem to be option to try get to a "reseted" state.

### Operating system

macOS apple silicon

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

......

### Relevant log output

```shell
.....
```

### Additional context

.......

**Comment by maxandersen** [comment]
rebooted in hope it will help things. but same issue(s).

now tried to use create... button but gets:

Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: podman-machine-default: VM already exists

...but no way to stop/delete it from the ui.

**Comment by maxandersen** [comment]
fyi I have this when running podman machine list:

```
NAME                     VM TYPE     CREATED       LAST UP             CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        9 months ago  Currently starting  1           2GiB        100GiB
```

going to try nuke it.

**Comment by maxandersen** [comment]
podman machine stop on command line worked.

should podman desktop not allow stop in UI then too?

**Comment by maxandersen** [comment]
if that stop I could click run/start in podman desktop ui and now it seems to work.

**Comment by benoitf** [comment]
`podman-machine-default*  qemu        9 months ago`

old podman machines had issues to start/stop so nuking and starting it from scratch is good. (even command line command could be stuck with these old machines)

The same if you try to upgrade to podman v5.0 you should try to start from a clean podman environment as podman v5 is not compliant with v4 machines

In case you can also click on the light bulb of the status bar and click on (Clean/Purge data) it'll remove all podman machines

**Comment by benoitf** [comment]
I think the root issue is a dup of https://github.com/containers/podman-desktop/issues/2985

**Comment by maxandersen** [comment]
And that you can't stop/remove in UI but forced to go to command Line.
