### ISSUE TITLE
running `yarn watch --extension-folder` with webview

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#6516]
### Is your enhancement related to a problem? Please describe

When running the command
```
yarn watch --extension-folder [...]
```

with an extension using a webview, the user needs to compile the frontend before to run this command.

If this is not done, this can lead to inconsistencies between extension's frontend and backend, and the fact that the frontend is not compiled can be difficult to detect. 

### Describe the solution you'd like

It would be nice if podman desktop were able to also watch the frontend directory of the extension.

**Comment by benoitf** [comment]
AFAIK the layout of the extension is up to the extension so podman desktop can't really do things there

but the extension itself can have it watch command spawing as well a watch command in its frontend.
