### ISSUE TITLE
E2E save/load images

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#6542]
### Is your enhancement related to a problem? Please describe

We should add tests for the save/load images feature.

save -> https://github.com/containers/podman-desktop/pull/6530
load -> https://github.com/containers/podman-desktop/pull/6540

The gifs inside those two PR shows how it should work.

When loading images from an archive they do not have any tag. 

### Describe the solution you'd like

E2E tests

**Comment by benoitf** [comment]
cc @containers/podman-desktop-qe-reviewers
