### ISSUE TITLE
Consistent fonts on Dashboard screen

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#6547]
### Is your enhancement related to a problem? Please describe

At the moment, the text on the dashboard screen is not following a consistent set of rules. The visual hierarchy needs to be stronger. 

This relates to https://github.com/containers/podman-desktop/issues/6405 

### Describe the solution you'd like

Go through the page and set the font to the appropriate size, setting them up to be edited later.

### Additional context

From this we can go through the other pages and make them follow this format also.

**Comment by cdrage** [comment]
I opened up issue #6747 because I couldn't find this one. Looks like it was closed by mistake.

Opening this as #6685 unfortunately did not solve the issue of font sizing throughout the dashboard screen.

**Comment by ekidneyrh** [comment]
Hi @cdrage! I read the description on the other ticket. I was trying to assign the font size eg. xs, sm, base etc. for diff components so when I edit the config file last it wont make things go funky. I was also trying to play with the font weights to make it look better in the mean time but I agree with what you're saying and I'll go back in to make changes.

For the provider card, there's this [ticket](https://github.com/containers/podman-desktop/issues/4395) that was made to change how that looks, which imo makes it cleaner / simplistic and there's less types of information on the card.

Here's a screenshot of the proposed provider card from that ticket:

![image](https://github.com/containers/podman-desktop/assets/87311656/68c231e6-2c35-4bd1-85ca-53a2c8088257)

I know time is tight so I'll try tidy up what is there atm. 

Thanks for your feedback!!
