### ISSUE TITLE
saved images don't include the tags, so when importing it again we don't know who is who

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6582]
### Bug description

We have a way to export/import images

If I manually do `podman image save`, in the tar file manifest.json includes the RepoTags while using the feature from Podman Desktop

So importing image back, I don't know the names of the images

using a command line exported image, I'm able to import it with the right name, so I would say it's the export that is failing

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

**Comment by afbjorklund** [comment]
Do you mean `save` ?

**Comment by benoitf** [comment]
@afbjorklund yes I fixed the name of the command, thx
