### ISSUE TITLE
Implement sort by column 

### ISSUE THREAD

**Issue by tanwald** [containers/podman-desktop#659]
### Is your enhancement related to a problem? Please describe

I cannot spot or select a group of images, containers,... easily because the UI does not support sorting by columns. Sorting helps to "group" images by attributes like creation date, repository, name,... 

### Describe the solution you'd like

Clicking the column headers should sort the table by the values of this column similar to `podman image ls --sort <choice>`. This should work for all table-views.

**Comment by benoitf** [comment]
thanks @tanwald. Indeed, it's a planned feature.

I think also there are some mockups to have some widgets on dashboard page to highlight some containers/images

cc @mairin @gbengaoti

**Comment by deboer-tim** [comment]
We have done this for Images and Volumes. Pods are in progress via #4842 and containers via #4843.

**Comment by benoitf** [comment]
closing as it's supported in table component that is now being used in most of the pages
