### ISSUE TITLE
Podman machine listed as running but it is stopped

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6595]
### Bug description

While testing for the V5 migration, I had Podman 4 running with a single container and wanted to test images/containers backup/restore. So I started the update to v5 got asked if I want to stop the machine, answered yes but when asked to delete all data, answered cancel. But the dashboard says Podman is running when it's now stopped

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
it looks like a regression from https://github.com/containers/podman-desktop/commit/287c15d429c1dd104c3451012ccce9e37d50da45
