### ISSUE TITLE
Update option to Podman 5 is not visible when enabling experimental flag immediatelly if no machine is present

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6598]
### Bug description

I have podman installed on my system 4.9.4 and I do not have any machine created. If I enabled the experimental podman v5 feature in preferences, I would expect that in the dashboard I will get an option to update to podman v5. This is missing until I restart podman desktop.

![Podmanv4-v5-pd_2024-04-02 15-27](https://github.com/containers/podman-desktop/assets/19164299/1f1a786c-51af-47ac-b815-df08d255e43b)

### Operating system

MacOS 14, Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Have podman desktop installed (1.9.0-next, some latest version, ie. built from main)
2. Start podman desktop
3. Remove any leftover from previous podman/podman-desktop installation at `~/.local/share/containers` and `~/.config/containers`
4. Start up podman desktop
5. Install podman via installer (ie. v4.9.4)
6. Check if update button appears (it will probably not)
7. Enable podman v5 experimental feature in preferences
8. Go to dashboard
9. Assert: option to update to podman v5 is available
Actual result: the option is not available until I hard restart podman desktop, force reload wont help

**Comment by benoitf** [comment]
on my end it's immediate

https://github.com/containers/podman-desktop/assets/436777/e482e99a-1374-4484-a028-9d0b13f5a89d

**Comment by jeffmaury** [comment]
> on my end it's immediate
> Screen.Recording.2024-04-02.at.15.57.28.mov

The issue mentions you should not have a Podman machine but I cannot reproduce on my Win11Pro laptop

**Comment by odockal** [comment]
@jeffmaury Thanks for looking at it. I had to change the reproducing steps. First two should be interchanged. So first, install and start podman desktop, and while it is running (without any machine or any leftover artifacts ie. on `~/.local/share/containers` and `~/.config/containers`) install podman. Podman desktop grabs that installation, but then even with enabling experimental podman support wont show update button -> until restart.

**Comment by jeffmaury** [comment]
Can reproduce if Podman is installed via CLI

**Comment by benoitf** [comment]
it's not clear which installer you're using `Install podman via installer`

which version of the podman installer ?

**Comment by odockal** [comment]
> it's not clear which installer you're using `Install podman via installer`
> 
> which version of the podman installer ?

Updated.
