### ISSUE TITLE
Initialize and start from dashboard on Mac OS with Podman v5 and applehv throws an error: exit code 125

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6617]
### Bug description

Podman desktop 1.9.0 with Podman 5.0.1 using applehv provider (via containers.conf file) throws an error when "Initialize and Run" from dashboard.

![Screenshot_20240403_154014](https://github.com/containers/podman-desktop/assets/19164299/5d8bbc74-a5f2-4fda-8a46-59ed7e4560c7)

### Operating system

Mac OS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Install podman desktop 1.9.0 (Airgapped universal dmg)
2. Open it up
3. Install podman offered (5.0.1) since I had not previous podman installation
4. Insert 
```
[machine]
  provider = "applehv"
```
into `~/.config/containers/containers.conf`
5. Click initialize and start on dashboard
6. Assert: Machine is created and started
Actual result: exit code 125

### Relevant log output

```shell
main ↪️ Trace: [podman] unable to check qemu version RA [Error]: Failed to execute command: spawn qemu-system-aarch64 ENOENT
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:12753)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  exitCode: 1,
  command: 'qemu-system-aarch64',
  stdout: '',
  stderr: '',
  cancelled: false,
  killed: false
}
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:21164
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by benoitf** [comment]
the airgap installer can only work with podman v4

**Comment by benoitf** [comment]
related issue https://github.com/containers/podman-desktop/issues/6360

**Comment by odockal** [comment]
@benoitf Ah, ok. thanks for info! Should we keep this one opened or is it a duplicity? I think we might keep it opened and verify it works once the related issue is fixed? we got nice reproducer here, right?

**Comment by benoitf** [comment]
you can keep it open until 1.10 but I would say it's an 'expected one' for now

**Comment by benoitf** [comment]
so I reconsidered this issue, while using podman v5 it could have been okish to have error, if you were using the airgap installer

but a user downloading and installing the airgap file will face issue of not being able to create a machine

to me it's a blocker for 1.9.0, I created a PR

**Comment by odockal** [comment]
@benoitf Ok, thanks!
