### ISSUE TITLE
Investigate a playwright support for the webview manipulation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6621]
### Is your enhancement related to a problem? Please describe

Some of the podman-desktop extension are providing a webview once installed. 

### Describe the solution you'd like

Investigate and find a way to work with the webview using playwright.

**Comment by odockal** [comment]
It was already briefly discussed by @benoitf with @ScrewTSW and suggested to look at https://github.com/microsoft/playwright/issues/9729#issuecomment-1646860598.

**Comment by axel7083** [comment]
According to the electron documentation, `webview` is implemented with Out-of-Process iframes (OOPIFs)[^1][^2]. They seems to have some stuff for OOPIFS https://github.com/microsoft/playwright/pull/1685 would it be related/useful ?


[^1]: https://www.electronjs.org/docs/latest/api/webview-tag#internal-implementation
[^2]: https://www.chromium.org/developers/design-documents/oop-iframes/

**Comment by odockal** [comment]
@axel7083 let me check. thx!

**Comment by odockal** [comment]
@ScrewTSW @cbr7 So, to get the content of the webview and to start testing inside, we need to something like this:
```
    test('Test Bootc WebView Inside', async () => {
      await navBar.openDashboard();
      // open Bootc Nav bar. Item -> loads up webview
      const bootcBar = navBar.navigationLocator.getByRole('link', { name: 'Bootable Containers' });
      await bootcBar.click();
      const webView = page.getByRole('document', { name: 'Bootable Containers' });
      await playExpect(webView).toBeVisible(); // still in the main page'
      // hard wait for webview element to fully load
      await new Promise(resolve => setTimeout(resolve, 1000));
      // get both windows available from the app
      const [mainPage, webViewPage] = pdRunner.getElectronApp().windows();
      await mainPage.evaluate(() => { 
        const element = document.querySelector("webview");
        if (element) {
          element.focus();
        } else {
          console.log(`element is null`);
        }
      });
      // print out title of the webview page
      console.log("title =", await webViewPage.title());
      // get the main element of the webview (inside of the iframe ?)
      const mainLocator = webViewPage.getByRole('main');
      await playExpect(mainLocator).toBeVisible();
      console.log(`allInnerText: ${await mainLocator.allTextContents()}`);
      
      // check welcome message
      const welcome = mainLocator.getByRole('heading', { name: 'Welcome to Bootable Containers'});
      await playExpect(welcome).toBeVisible();
      // pull image button available and visible
      // get the build button, assert it visibility, click on it.
      const buttonBuild = mainLocator.getByRole('button', { name: 'Build'});
      await playExpect(buttonBuild).toBeVisible();
      await buttonBuild.click();
      // new page should be opened - Build Disk Image
      const buildImage = mainLocator.getByRole('heading', { name: 'Build Disk Image'});
      await playExpect(buildImage).toBeVisible();
    }, 60000);
```

**Comment by odockal** [comment]
@cbr7 It is not perfect as it seems to lost focus of the main div from the webview. Also debugging gonna differs from what we know from podman-desktop. It seems like we would need to run in `yarn watch` mode to debug the extension to see its dom structure. But I think we could start testing for now.

**Comment by cbr7** [comment]
@odockal I'm going to play around with this today and try to get it to work in a more clean and stable way.

**Comment by odockal** [comment]
For now it looks like we will add webview handling code on the extensions side. It is particularly because of the how the webview is initiated (via extension's specific code), so it stays there for now. We might extract general functionality into a testing framework via new issue.
