### ISSUE TITLE
Switch from compat API to libpod API when listing images if provider is of podman type

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6622]
### Is your feature request related to a problem? Please describe

For now we're using compat listImages but we should switch to libPod listImages endpoint

depends on 
- [x] https://github.com/containers/podman-desktop/issues/6623

### Describe the solution you'd like

it will allow to list multi-arch images that are included when using the libpod list images endpoint

https://docs.podman.io/en/latest/_static/api.html#tag/images/operation/ImageListLibpod

**Comment by cdrage** [comment]
We will also add a hidden configuration property that can switch between the compat API as well as libpod API.
