### ISSUE TITLE
Add podmanListImages internal API call

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6623]
### Is your feature request related to a problem? Please describe

need to enhance our libpod endpoint to query the list of images of Podman engine

### Describe the solution you'd like

need to add code there
https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/dockerode/libpod-dockerode.ts#L356

that should call
https://docs.podman.io/en/latest/_static/api.html#tag/images/operation/ImageListLibpod

to add the `listPodmanImages` method

**Comment by cdrage** [comment]
Updated title to indicate that this will be an internal call only, and that another PR / issue will be used to update listImages API call to use libpod API when calling podman.

**Comment by benoitf** [comment]
yes it would the same approach than for listContainers (listContainers delegate to compat API on docker engine and to podmanListContainers on Podman engine)

**Comment by cdrage** [comment]
After discussion with @benoitf this call will:
1. Prefer podman API (check to see if libpodApi exists)
2. Fallback to using the compat api (example, container engine doesnt have libpodApi)
