### ISSUE TITLE
add API to add an image to a manifest endpoint

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6625]
### Is your feature request related to a problem? Please describe

need to enhance the libpod dockerode to add a method to a add an image to a manifest

### Describe the solution you'd like

enhance the dockerode

**Comment by cdrage** [comment]
In the API call, you can pass in a list of images when creating the manifest: https://docs.podman.io/en/latest/_static/api.html#tag/manifests/operation/ManifestCreateLibpod

So I do not believe we need this anymore as it's covered by the single createManifest call. 

We could close this issue, but can add this API call in the future if requested? @benoitf

**Comment by benoitf** [comment]
AFAIK when we do a multi arch image, we create the manifest first and then build the image to be included in that one

https://developers.redhat.com/articles/2023/11/03/how-build-multi-architecture-container-images#benefits_of_multi_architecture_containers

```
# First, initialise the manifest
podman manifest create <image name>

# Build the image attaching them to the manifest
podman build --platform linux/amd64,linux/arm64  --manifest <image name>  .

```

**Comment by cdrage** [comment]
> AFAIK when we do a multi arch image, we create the manifest first and then build the image to be included in that one
> 
> https://developers.redhat.com/articles/2023/11/03/how-build-multi-architecture-container-images#benefits_of_multi_architecture_containers
> 
> ```
> # First, initialise the manifest
> podman manifest create <image name>
> 
> # Build the image attaching them to the manifest
> podman build --platform linux/amd64,linux/arm64  --manifest <image name>  .
> ```

Yes, but the API is different. You are required to pass in the images to be added to the manifest when creating it.

Example:

```
▶ curl --unix-socket /var/folders/cn/pm5mgrcs5h339nphypxtvd080000gn/T/podman/podman-machine-default-api.sock -X POST \
     "http://d/v4.2.0/libpod/manifests/test?images=quay.io/bootc-extension/httpd"

{"Id":"6a105d8fe5a76e15c4687f44deb923acf62608d56ede79b74f5a9251de5e2155"}

▶ podman image ls
REPOSITORY                                TAG                IMAGE ID      CREATED             SIZE
localhost/test                            latest             6a105d8fe5a7  About a minute ago  486 B

▶ podman manifest inspect test                                                                                        
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 11516,
            "digest": "sha256:aac562fb3b23e23a9fbdbb9623ada3de75767dd40befac51a10bafdccbf1ff69",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        }
    ]
}
```

We won't need to add the "add image to manifest" API since create forces you to add it anyways.

**Comment by benoitf** [comment]
> Yes, but the API is different. You are required to pass in the images to be added to the manifest when creating it.

You are not required, when I check the calls of the podman CLI, when we create the manifest it's an empty one

```
POST /v5.0.1/libpod/manifests/hello-world?all=false&amend=false HTTP/1.1\r
```

and we do have

```
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","manifests":[]}
```

**Comment by benoitf** [comment]
moving to the following sprint

**Comment by cdrage** [comment]
Not needed for now, closing as it's not needed until manifest epic  is created, etc.

**Comment by cdrage** [comment]
As per the standup today, going to close this for now unless we really need it as part of #7041 

At the moment, we haven't had a discussion / feature request of adding images to an already created manifest (yet). We still need to get the basic functionality added (pushing manifest, deleting, etc.)
