### ISSUE TITLE
in buildImage, spawn multiple builds if multi-arch

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6626]
### Is your feature request related to a problem? Please describe

today we delegate to the build endpoint but in case of a comma separated list of arch , the call is failing

### Describe the solution you'd like

If multiple arch 'comma separated' specified, need to create a manifest using
- [x] https://github.com/containers/podman-desktop/issues/6624

then spin up one call to the build endpoint for each arch

once we have the result,

add each image to the manifest calling
- [x] https://github.com/containers/podman-desktop/issues/6625

**Comment by cdrage** [comment]
Using `podman build --platform linux/arm64,linux/amd64 --manifest quay.io/bootc-extension/httpd .` the images being built are cached / not added to image list after, becoming a singular manifest.

For our above solution of using one call for each arch, do you have a suggestion on what labeling / cleanup we should be doing?

From my understanding via the API we would have to:

1. Call for each build through the API with a specific tag (imagename:linux/arm64 or something similar?)
2. Add each image to the manifest
3. Make sure old images are cleaned up which were tagged, and only the manifest remain.

**Comment by cdrage** [comment]
So when I do:

```
podman build --platform linux/arm64,linux/amd64 --manifest quay.io/bootc-extension/httpd .
```

We actually get a bunch of <none> images that fill up Podman Desktop:

![Image](https://github.com/containers/podman-desktop/assets/6422176/8ebf7a8b-7562-4d48-a89d-9dd089bfbeb5)

Basically within podman CLI, they are creating blank images.

These images are important as they are the ones that the manifest link to, and must exist. If you delete the none image, it wont exist for the manifest...

Questions:
- Should we tag the images such as imagename : tag . platform or stick to none like the CLI?
- If we do use none, there is no resulting way for us to determine what the resulting build image ID is as we do not implement in our API a return for the resulting build image: https://github.com/cdrage/podman-desktop/blob/0dbca080202f536cd767b3b11f85fb7cd6f8b30a/packages/main/src/plugin/container-registry.ts#L2292 the only way would be to parse through the logs and look for Successfully built build-image-id which I don't think would be a good implementation. Also none fills up all the spaces and a user may accidentally delete it, not knowing it's part of the manifest.
- If we do use imagename : tag . platform then we can successfully find the images after the build, and we will not add a bunch of none containers, at least the ones built will actually have tags.


Thoughts @benoitf @deboer-tim ?

**Comment by cdrage** [comment]
As per meeting will be doing the following:

- build the <none> images similar to the CLI by passing in none
- get the ID's by examining the onFinish output log on each build, ex:

```json
[
  { stream: 'STEP 1/2: FROM redhat/ubi9-minimal\n' },
  { stream: 'STEP 2/2: ENTRYPOINT echo "hello world"\n' },
  {
    stream: '--> Using cache 358319dc584f78e98bda052c412808957eec18496c724e7f7398d0de08258284\n'
  },
  { stream: 'COMMIT docker.io/library/my-custom-image:latest\n' },
  { stream: '--> 358319dc584f\n' },
  {
    stream: 'Successfully tagged docker.io/library/my-custom-image:latest\n'
  },
  {
    stream: '358319dc584f78e98bda052c412808957eec18496c724e7f7398d0de08258284\n'
  },
  {
    aux: {
      ID: 'sha256:358319dc584f78e98bda052c412808957eec18496c724e7f7398d0de08258284'
    }
  },
  { stream: 'Successfully built 358319dc584f\n' },
  { stream: 'Successfully tagged my-custom-image\n' }
]
```

By getting `aux`: `ID:`
