### ISSUE TITLE
Kind delete fails

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#6629]
### Bug description

Created a kind cluster and tried to delete it, falis with `Delete failed`
![image](https://github.com/containers/podman-desktop/assets/75624842/9edb36a8-490c-4333-ba1b-13516afee995)

### Operating system

Fedora39

### Installation Method

Flathub (Linux)

### Version

1.9.0

### Steps to reproduce

1. `KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster`
2. stop cluster from PD
3. delete Kind cluster inside PD
4. ASSERT: kind cluster deleted
5. ACTUAL: deletion fails with `delete failed`

### Relevant log output

```shell
PreferencesConnectionActions.svelte:136 Error: Command execution failed with exit code 1
m	@	PreferencesConnectionActions.svelte:136
await in m (async)		
w	@	PreferencesConnectionActions.svelte:197
(anonymous)	@	LoadingIconButton.svelte:45
```

**Comment by axel7083** [comment]
I can't reproduce on windows.

I followed the steps you provided, but the cluster is properly deleted when I remove it from the Resources page. I tried opening the kind details page deleting from there, I am properly redirected to the resources page on deletion.

**Comment by rostalan** [comment]
> I can't reproduce on windows.
> 
> I followed the steps you provided, but the cluster is properly deleted when I remove it from the Resources page. I tried opening the kind details page deleting from there, I am properly redirected to the resources page on deletion.

I don't think I had any issues deleting kind on windows either, might be OS specific. There is also improper cleanup of previous testing from my side. Would need someone with linux to test this. Maybe @odockal could take a look?

**Comment by jeffmaury** [comment]
Cannot reproduce on Fedora 39/Flatpak with 1.9.1

**Comment by rostalan** [comment]
not reproducible anymore
