### ISSUE TITLE
Telemetry prompt spawns under main window, preventing interaction

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#664]
### Bug description

When podman desktop opens, the telemetry prompt in GNOME (X11 session) is spawned under the main podman desktop window. This was confusing at first, as I had to move around the window to find the dialog.

### Operating system

Tested on Arch Linux and Ubuntu 22.04

### Version

0.8.0

### Steps to reproduce

Open the application. Get prompted for telemetry, but it shows under the main app window.

### Additional context

One idea would be to have the telemetry prompt inside of the main window somehow so it's not a pop-up at all, avoiding this entirely.

**Comment by benoitf** [comment]
it looks like to be a problem on Linux only https://github.com/electron/electron/issues/32857

**Comment by benoitf** [comment]
needs to reimplement 'Dialogs' inside the UI instead of using external Dialog Box

**Comment by benoitf** [comment]
As we now have a good welcome page we could include telemetry setting there


![Image](https://user-images.githubusercontent.com/436777/228655794-c3412b6c-e977-42ae-b54a-000c137f9ef2.png)

or latest one:

![image](https://user-images.githubusercontent.com/436777/228824462-4bb4b746-95bd-44b0-a153-34e482deb1b7.png)

(Design by @mairin )

**Comment by dylanmtaylor** [comment]
> As we now have a good welcome page we could include telemetry setting there
> 
> ![Image](https://user-images.githubusercontent.com/436777/228655794-c3412b6c-e977-42ae-b54a-000c137f9ef2.png)
> 
> or latest one:
> 
> ![image](https://user-images.githubusercontent.com/436777/228824462-4bb4b746-95bd-44b0-a153-34e482deb1b7.png)
> 
> (Design by @mairin )

I really like this idea

**Comment by deboer-tim** [comment]
This has been fixed by moving the telemetry prompt into the new Welcome screen, and released via PR #1927. Users will see it in a couple weeks when we release 0.14.
