### ISSUE TITLE
Running a container should have a checkmark to start it with an interactive terminal

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#665]
### Is your enhancement related to a problem? Please describe

While possible via another terminal application, Podman desktop does provide its own terminal tab for containers. This could be used for images like alpine, amazonlinux, or ubuntu where someone just wants to try out a few commands inside of a container. Right now, for containers like Ubuntu, it immediately exists after it is run because it is not on a tty.

### Describe the solution you'd like

Proposed behavior:

If a user checks to run with an interactive terminal (possibly allow an entrypoint override), the container will start and focus will be changed to the terminal tab in the application. This would allow the user to use this container interactively. 

This could be implemented by adding these arguments to the command to invoke podman:
-i              : Keep STDIN open even if not attached
-t              : Allocate a pseudo-tty

**Comment by benoitf** [comment]
Hi @dylanmtaylor how do you see the 'checks to run with interactive mode' ?

it looks like an additional parameter on the "Run image" ?

**Comment by dylanmtaylor** [comment]
@benoitf I believe this should be closed and merged into #375. I would like to see a checkbox labelled 'Interactive', which if selected will invoke podman with these options (-it) in the command line:

-i : Keep STDIN open even if not attached
-t : Allocate a pseudo-tty

This will allow for users to interactively use containers like ubuntu:latest or archlinux:latest, through the terminal in the podman desktop app. Focus should be given to the terminal's tty if this is selected upon launching the container.
