### ISSUE TITLE
Migrating from podman v4 to v5 causes the delete old podman machines screen to be displayed even though the delete all option was selected during podman v5 installation

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6651]
### Bug description

During podman v5 installation the user has the option to clean up all the data from old podman v4 machines, but when the user goes to create a podman machine using the "Set up" button for onboarding is taken to a screen where the user is informed that there are still old podman machines/data on the system.

https://github.com/containers/podman-desktop/assets/106525396/92403f11-ee0e-4bd0-b63f-a1e035952719

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Have podman 4.9.4 installed with a podman machine initialized.
2. Open Podman Desktop 1.9
3. Enabled the experimental podman option from Preferences.
4. Start the podman update to 5.0.1 from the PD dashboard.
5. Navigate all the options and select to delete all the old data when prompted.
6. Finish the installation for podman 5.0.1.
7. Use the "Set Up" onboarding option to go and create a podman v5 machine.
8. Notice that you are navigated to a screen that notifies that data from podman v4 is still available in the system.

**Comment by nichjones1** [comment]
Issue should no longer be present as users have migrated to Podman v5
