### ISSUE TITLE
Migrating from podman v4 to v5 the user is able to bypass the data clean up process for old data in some scenarios

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6654]
### Bug description

After installing podman v5 from the dashboard the user is able to bypass the podman v4 data cleanup process and create podman v5 machines without it.

https://github.com/containers/podman-desktop/assets/106525396/503065d1-77b0-4d97-a490-5f5a3c282075

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Have podman 4.9.4 install on the system with a podman machine created.
2. Open Podman Desktop 1.9 and enable the experimental podman setting from Preferences.
3. From the dashboard initiate the update of podman to version 5.0.1.
4. During the prompted dialog select the "Skip" option on the dialog that requests to delete all the old data from the system.
5. Finish the installation of podman 5.0.1
6. Go to Settings -> Resources and create a podman v5 machine (Alternatively use the "Initialize and start" button from the dashboard.
7. Notice that the cleanup process for old podman v4 data is bypassed and a new podman v5 machine is created.

**Comment by benoitf** [comment]
so bypassing is ok on macOS, but you'll see a nag at the top of the dashboard if you're not doing it

on Windows as well you'll see some popup saying to resume the onboarding

**Comment by benoitf** [comment]
basically on macOS, switching from qemu/v4 to applehv/v5 there is no need to remove folders as they're using different paths

it's just for cleanup

**Comment by benoitf** [comment]
closing as won't fix, we switched to v5 since a long time so most of the people have already switched
