### ISSUE TITLE
Allow selecting a preferred platform/architecture

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#666]
### Is your feature request related to a problem? Please describe

It's common to deploy on amd64, but M1 macs are running arm64. This would also be valuable for x86 users deploying to AWS's graviton instances, for example.

A workaround is to do something like 

podman run -it docker.io/amd64/amazonlinux:2 bash

### Describe the solution you'd like

Under preferences, allow selecting the default architecture of containers to pull and run. Use qemu/rosetta to run non-native containers.

**Comment by mathstuf** [comment]
Note that I was able to pull using `podman pull --arch amd64 ubuntu:latest` and run that via podman-desktop just fine, so there is a workaround, but it requires manual interactions to get the image to show up.
