### ISSUE TITLE
Podman Machine created in Podman Desktop encounters an error using Hyperv Provider

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6668]
### Bug description

When I try to create a new machine in Podman Desktop on windows using Hyperv Provider I am seeing an error, but eventually machine appears in the Resources and can be started/used normally. Eventually it cannot be stopped then and seems to be somehow broken.

![hyperv_machine_create_error_2024-04-05 11-26](https://github.com/containers/podman-desktop/assets/19164299/b0f44842-15b1-448c-8a8f-e9875de32699)

The error:
```
Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: failed to add resource: Job failed with error code: 32768 ('podman-machine-default' failed to add resources. (Virtual machine ID 9F272F29-6DD9-4B25-A041-60296B7EE028) 'podman-machine-default' encountered an unexpected error: The specified path is invalid. (0x800700A1). (Virtual machine ID 9F272F29-6DD9-4B25-A041-60296B7EE028))
```

### Operating system

windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Install podman Desktop
2. Install Podman v4.9.4
3. Setup env. var. `CONTAINERS_MACHINE_PROVIDER="hyperv"`
4. Start up podman desktop
5. Create new machine with default values
6. Assert: Machine is created
Actual result: Machine creation throws an error: `failed to add resource`

**Comment by odockal** [comment]
Quite interesting findings done by @cbr7 suggesting that we might need to name the machine other than default `podman-machine-default`. This could be point at the problem with a clean up between using wsl machine and hyperv (assuming keeping the same name for the machine when switching).

**Comment by lstocchi** [comment]
@odockal i think this is fixed in the new podman 5 and can be closed.

Just tested with podman 5 and even if i switch to HyperV i can see the connections created with WSL previously.
This guarantees that you cannot create a machine with the same name on WSL and then hyperv. 
So now, if you try to create a default machine twice you see 
![image](https://github.com/containers/podman-desktop/assets/49404737/a3fb978c-ccfa-47be-9f2b-50642635546f)

**Comment by odockal** [comment]
@lstocchi I am gonna look at hyperv with podman 5 today. So will report back. Do we want to focus on fixing anything 4.9.x related?

**Comment by lstocchi** [comment]
@benoitf ^

**Comment by odockal** [comment]
@lstocchi Issue seems to be gone even with Podman 5.1.0 (was testing this version).

**Comment by lstocchi** [comment]
Thanks for confirming @odockal . @benoitf do we close it or do i have to check for a fix for 4.9? Which are the versions we should support?

**Comment by lstocchi** [comment]
After re-reading i'm gonna close this bc we do not actually handle hyper-v with old podman versions and using the new 5.1 works fine

**Comment by odockal** [comment]
@lstocchi Agree. thanks!
