### ISSUE TITLE
Split the `FeaturedExtensions` svelte component to make individual item reusable 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6669]
### Is your enhancement related to a problem? Please describe

In todays implementation of the `<FeaturedExtensions/>` we have the following

https://github.com/containers/podman-desktop/blob/b6f2643854665910b70ad1f7df1cfe3f06ca4bdf/packages/renderer/src/lib/featured/FeaturedExtensions.svelte#L13-L16

In the same component we have the component iterating over the items, and the item component itself.

### Describe the solution you'd like

We should create a `<FeaturedExtension featuredExtension="{featuredExtension}"/>` component inside the each block. This would allow to make the item a standalone, reusable component

### Additional context

This proposal is required to continue the work on the https://github.com/containers/podman-desktop/issues/6215 PR

**Comment by axel7083** [comment]
cc @benoitf @deboer-tim what do you think ?

**Comment by benoitf** [comment]
I'm 👍 it's just a move

**Comment by deboer-tim** [comment]
Zero concerns over this change, but I'm curious about the reason for it?

I was assuming it is to change the extensions page, but I thought the last mockup I saw had all the extension tiles identical except that featured extensions had a badge and were sorted first, i.e. it would make sense to have a single component like:
` <ExtensionTile id="" featured="true/false" />`
vs having:
` <FeaturedExtensionTile id=""/>` and
` <ExtensionTile id=""/>`
that have to keep 90% the same UI.

But maybe you're making the single component out of this, there's a new mockup, or this is for another reason?

**Comment by benoitf** [comment]
it's not for the extensions page but for the Recommendation widget

**Comment by benoitf** [comment]
> Additional context
>This proposal is required to continue the work on the https://github.com/containers/podman-desktop/issues/6215 PR

**Comment by deboer-tim** [comment]
Ah. Ok, thanks for clarifying.
