### ISSUE TITLE
[Kubernetes extension] [Airgapped installer] Missing Kubernetes pages (previously experimental features) toolbar on in the NavBar

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#6675]
### Bug description

In Podman Desktop 1.9.1 we are missing Kubernetes pages toolbar in the NavBar (deployments, services, routes, etc.)

This issue affects both airgapped installs on Windows (W10 22H2) and Mac

### Operating system

Windows 10 22H2, MacOS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

* Install Podman Desktop 1.9.1
* Complete Onboarding
* (issue should already be present)
* Try to create a default machine and start any container that provides Kubernetes context

### Relevant log output

```shell
N/A
```

### Additional context

![Podman_Desktop_NnDEtAwiSv](https://github.com/containers/podman-desktop/assets/16451875/265e790d-9b5f-4f49-9899-04e259280169)

**Comment by benoitf** [comment]
AFAIK you need to have a $HOME/.kube/config file to see kubernetes stuff/icons (you see pods that is managed by podman)

**Comment by odockal** [comment]
@benoitf I can confirm this, just one thing... If I do not restart podman desktop, and I have ie. kind cluster created and kubeconfig present, the kube context is not being refreshed from podman desktop until the restart happens.

**Comment by ScrewTSW** [comment]
@benoitf I do have the file, though it's pointing to an invalid Developer Sandbox context, trying with Minikube.

Though it's very strange that I did not notice this behavior previously in 1.8.0

![brave_yjDB7l2Wom](https://github.com/containers/podman-desktop/assets/16451875/4064a0d2-7396-4bb7-a892-63522c2a7bcf)

**Comment by ScrewTSW** [comment]
@benoitf @odockal my context was switched correctly and pages appeared, no need for restart of PD

![Podman_Desktop_p2Gne0ZXME](https://github.com/containers/podman-desktop/assets/16451875/c63ddeff-1761-4969-af3f-33f5a0ecde09)

**Comment by odockal** [comment]
We have the mention of this very issue in this comment: https://github.com/containers/podman-desktop/issues/6406#issuecomment-1998500385. This is probably a symptom of the bug referenced there.
