### ISSUE TITLE
Telemetry for navigating to webviews

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6686]
### Is your enhancement related to a problem? Please describe

When you navigate to any extension that provides a webview, it only sends a generic telemetry event:
`"name": "Home/Webview"`
regardless of which extension's Webview you navigated to.

### Describe the solution you'd like

We're not able to tell which webview you're using. It would be good if the event included the name of the webview or extension in the event. e.g. for DD Extensions we send:
`  "name": "Home/Extension/Disk usage"`

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/6692
