### ISSUE TITLE
Docs: Sample extension package.json example missing scripts

### ISSUE THREAD

**Issue by timheuer** [containers/podman-desktop#6695]
### Bug description

Following the instructions on the docs: https://github.com/containers/podman-desktop/blob/main/website/docs/extensions/write/index.md the `yarn watch` command will fail as there are no scripts in the package.json

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/6715
