### ISSUE TITLE
Migrating from Podman v4 to v5 doesn't properly delete machine on Hyperv

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#6698]
### Bug description

Stopping machine and deleting all data during migration from Podman 4 to 5 doesn't properly remove machine using Hyperv provider. The machine is not visible in Podman Desktop and CLI, but it's still visible in Hyperv manager and it's not possible to create other machine with the same name.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Install Podman Desktop (1.9.1)
- Install Podman v4
- Initialize and create Podman machine using Hyperv provider
- Assert the machine is visible in Podman Desktop/CLI and Hyperv manager
- Enable v5 Podman installation support in Preferences
- Migrate to Podman v5 from Dashboard, stop machine and agree to deletion of all data
- The old machine is not visible in Podman Desktop/CLI but still present in Hyperv manager
- Try creating Podman v5 machine (fails if old machine is still present in Hyperv manager)

### Additional context

![hyperv machine error podman5](https://github.com/containers/podman-desktop/assets/57829934/b4b3c567-4a73-476a-ad2a-30e2f0c4e2d7)

**Comment by benoitf** [comment]
won't fix, migration happened long time ago (v4 -> v5)
