### ISSUE TITLE
Run Image page have scroller inside scroller

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6711]
### Bug description

The Run Image page avec weird  y-overflow behaviour for its tabs.

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

https://github.com/containers/podman-desktop/assets/42176370/1a36d3d1-e887-4406-b010-dd7a232f4303

**Comment by benoitf** [comment]
related to https://github.com/containers/podman-desktop/issues/5926

**Comment by axel7083** [comment]
> related to #5926

This really feel weird, I understand there is other priorities as you mention in the related issue.
But here is a quick fix: remove the scroller in each tabs (remove the classes `h-96 overflow-y-auto`), what do you think? I can close/purpose if we want to see that later

**Comment by benoitf** [comment]
so no, because AFAIK by default you won't see the create container button anymore
