### ISSUE TITLE
feat(UI): FeaturedExtension should have a configurable background & border colors properties

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6718]
### Is your enhancement related to a problem? Please describe

Currently the colors of the `<FeaturedExtensions/>` (background/border) are hardcoded using tailwinds classes.

https://github.com/containers/podman-desktop/blob/1abdbfa11561ca4df44fd7201a588eb7f7bf0b45/packages/renderer/src/lib/featured/FeaturedExtension.svelte#L13-L14

### Describe the solution you'd like

As requested in https://github.com/containers/podman-desktop/pull/6708#issuecomment-2043280447 we need this background & border to be configurable.

To achieve this behaviour we could do the following

```diff
- class="bg-charcoal-800 border-charcoal-800 ..."
+ class="{$$props.class ?? 'bg-charcoal-800 border-charcoal-800'} ..."
```

### Describe alternatives you've considered

We could add a `export let background: string = 'bg-charcoal-800 border-charcoal-800'` property to the component, but the border is annoying me as, we need to define it, but it is not really a background, justifying the use of `$$props.class`. But in the other hand, I don't really like using `$$props.class` too, as if I want to add some padding, I need to set the background and border color...

We could also have two,

```
export let background: string  = "bg-charcoal-800"
export let border: string = "border-charcoal-800"
```

But it also feel weird to me, as they are classes, not colors

**Comment by benoitf** [comment]
in ideas, I think some components are using like 'inverted' flag where they switch their color depending if they're used inside the darker background color or a lighter background color

Probably it could be used to mitigate.

**Comment by axel7083** [comment]
I can't find any usage of `inverted` in Podman Desktop, you meant in other component library? I would rather avoid introducing new logics for styling components 

If you are okay with the "{$$props.class ?? 'bg-charcoal-800 border-charcoal-800'} ..." I will probably use this.

Another solution would by the `variant`. We already are using for the buttons, 'primary' 'secondary', that would work

**Comment by benoitf** [comment]
Thinking of light theme, we should not use `bg-charcoal-800` but `bg-[var(--pd-card-bg)]` and not `charcoal-600` but `bg-[var(--pd-invert-content-card-bg)]` as it's the color for cards

And cards can only be one of these 2 colors for their background

So consumer of the component should only pickup what you call the 'variant' but not be able to customize the colors.

**Comment by axel7083** [comment]
Okey so let's define the variants

`primary`: bg-[var(--pd-card-bg)] border-[var(--pd-card-bg)]
`secondary`: bg-[var(--pd-invert-content-card-bg)] border-[var(--pd-invert-content-card-bg)]
