### ISSUE TITLE
Logic in guessIsManifest incorrect

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6731]
### Bug description

Found when trying to implement guessIsManifest for the images UI... and found there are some logical errors that we missed.\

https://github.com/containers/podman-desktop/blob/db072f7219f5a3c915850c695c38021081a49375/packages/main/src/plugin/util/manifest.ts#L49

It is never `podman`, but `Podman`

And we are not passing in engineName or engineId to guessIsManifest in https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/container-registry.ts#L633

This needs to be changed to: `isManifest: guessIsManifest({...image, engineName: provider.name, engineId: provider.id})`

### Operating system

mac m1

### Installation Method

None

### Version

1.9.0

### Steps to reproduce

Unable to correctly tags manifests

**Comment by benoitf** [comment]
need to check the type, not the name

`provider.connection.type`
