### ISSUE TITLE
UI design: Four different font sizes / alignment issues / for provider information on dashboard.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#6747]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-04-10 at 10 48 26 AM](https://github.com/containers/podman-desktop/assets/6422176/757e9fe5-0cdb-4f35-a704-c03e4c8a18d6)

For the above screenshot I noticed that:

- Alignment is really odd / three different alignments (logo and information on the left side floating left, the Podman Machine and compatibility warning is kinda odd, then the bottom section with the links are centered and spaced). The alignments kind of disrupt the flow of information IMO
- 4 different font sizes from the initial look makes it really strange compared to the rest of the dashboard.

### Describe the solution you'd like

Possible redesign of how we display information? I'm unsure if there have been previous discussions about this.

**Comment by benoitf** [comment]
Looks like a dup of https://github.com/containers/podman-desktop/issues/6547

**Comment by cdrage** [comment]
Ahhh, I did not see it as it was closed. Reopening.
