### ISSUE TITLE
Change the naming pattern of the 'nightlies' release

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6758]
### Is your enhancement related to a problem? Please describe

For now after each commit, we tag and release artifacts using for example `v0.0.202404091623-ed2eb47e5fbfc2f254a42baad9f`

so the pattern is `v.0.0.<Date>-<git sha>`

But it's hard to know the release being attached/related to this nightly

for example is it part of a 1.8 development branch, a 1.9 , a 1.10, etc

### Describe the solution you'd like

After discussion, outcome is to replace the first `0.0` by the real version

so currently it's `1.10.0-next` in package.json so nightlies should use the pattern

`v1.10.0-202404091623-ed2eb47e5fbfc2f254a42baad9f` 

or maybe with short gitID

`v1.10.0-202404091623-ed2eb47` and for the date I don't know if we need to keep it like this or not

### Describe alternatives you've considered

drop the date but then it's hard to quickly know without knowing all git sha if a release is recent or not from screenshots (as for example the version is displayed in the status bar)

**Comment by afbjorklund** [comment]
If you use [git describe](https://git-scm.com/docs/git-describe), then you don't have to tag snapshots... Also avoids polluting `refs/tags`

One issue is that you don't tag on `main`, so there is nothing on that branch to compare it with.

**Comment by benoitf** [comment]
@afbjorklund but to do releases on github and publish artifacts AFAIK you still need a tag

https://github.com/orgs/community/discussions/24690

**Comment by afbjorklund** [comment]
I guess these aren't releases (in the traditional sense, that is).

I used this hack: `git tag 1.9 $(git merge-base 1.9.x main)`

----

EDIT: So it would be something like

```console
$ git tag 1.9 v1.9.0^
$ git describe --tags v0.0.202404091623-ed2eb47^
1.9-64-ged2eb476dd
```

I think the go module versions are more similar to yours.

They have next version, the commit date, and the commit

**Comment by benoitf** [comment]
I'm not sure to follow because we need 'GitHub releases' and we set the prerelease flag so we need tags to publish them

**Comment by afbjorklund** [comment]
It seems some of the new software (like passt) has dropped versions altogether, and _only_ use dates and commits.

If you want to continue to (ab)use the releases, then I think changing `v0.0` to `v1.10` sounds like the most simple

**Comment by benoitf** [comment]
it's more for hosting the binaries
where binaries should be stored if not on GitHub releases ?

**Comment by benoitf** [comment]
or should we create/use another github project to store/host these nightlies
