### ISSUE TITLE
regression in provider card after https://github.com/containers/podman-desktop/pull/6768

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6776]
### Bug description

https://github.com/containers/podman-desktop/pull/6768 introduced a regression:

![image](https://github.com/containers/podman-desktop/assets/436777/c1eb1512-0ac6-4406-914d-b44a3b67bec5)

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
reopening as I still have the first arrow issue
![image](https://github.com/containers/podman-desktop/assets/436777/f408e7a3-786e-4f30-a7f1-406d5b76a018)

Microshift is being displayed on top of the other text (default size of the window)

**Comment by axel7083** [comment]
## Solution proposal

Making the banner responsive as there is a lot going on with the flex, and the whitespace-nowrap, leading to width issues.
