### ISSUE TITLE
bug(ImageDetails): navigation to container image crashes Podman Desktop 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6801]
### Bug description

https://github.com/containers/podman-desktop/assets/42176370/997bcbc4-f28c-45d5-a91c-2c3329496e3d

After that the application became completely crashed and user cannot perform any action except restarting Podman Desktop.

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

![image](https://github.com/containers/podman-desktop/assets/42176370/b9506859-9766-4e34-8794-4e2703177e34)

**Comment by axel7083** [comment]
## Source of the issue

Some investigation later.

The `imageHref` from `ContainerInfoUI` in ContainerDetails contains an url where the image id has the `sha256:` prefix. However, when navigating inside the images page, and opening the expected image, the image Id does not have the `sha256:` prefix. As showed in the following diff

```diff
+ /images/sha256:46cb0ee37ae2a409d2827039af15936a9e677169e91125992f188487a11d9895/podman.Podman Machine/Z2hjci5pby9jb250YWluZXJzL3BvZG1hbi1kZXNrdG9wLWV4dGVuc2lvbi1haS1sYWItcGxheWdyb3VuZC1pbWFnZXMvYWktbGFiLXBsYXlncm91bmQtY2hhdDowLjMuMA==/summary
- /images/46cb0ee37ae2a409d2827039af15936a9e677169e91125992f188487a11d9895/podman.Podman%20Machine/Z2hjci5pby9jb250YWluZXJzL3BvZG1hbi1kZXNrdG9wLWV4dGVuc2lvbi1haS1sYWItcGxheWdyb3VuZC1pbWFnZXMvYWktbGFiLXBsYXlncm91bmQtY2hhdDowLjMuMA==/summary
```

In the `ImagesList` svelte component the url to open the `ImageDetails` is computed with the following line

https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/renderer/src/lib/image/ImageColumnName.svelte#L9-L11

When the container details uses the `container.imageHref` which is assigned with the following 

https://github.com/containers/podman-desktop/blob/5f1d688b9451128234d5133abb0450367b2ad888/packages/renderer/src/lib/container/container-utils.ts#L160

The problem seems to be in the difference with the `containerInfo.ImageID` which has the `sha256:` prefix where `imageInfo.Id` has not.

## Solutions proposal

(1) We could inside the ImageDetails, check for the `sha256:` prefix in the following

https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/renderer/src/lib/image/ImageDetails.svelte#L73

(2) When creating the imageHref, instead of using containerInfo.ImageID we could check for the prefix `sha256:`, and remove it if it exists.

**Comment by axel7083** [comment]
Reported by @SoniaSandler the problems seems to have risen again

**Comment by odockal** [comment]
It seems that we also have this one hidden in feature request: #6627.
