### ISSUE TITLE
Recommendation preference option should be visible

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6808]
### Is your enhancement related to a problem? Please describe

Following the merge of https://github.com/containers/podman-desktop/pull/6708 we should make visible the option in the preference to let the user hide the recommendations.

### Describe the solution you'd like

Since we are creating an hidden preference, we should remove the hidden property.

https://github.com/containers/podman-desktop/blob/74923cc173ebefbbb852f1d90d02bc83d14fce69/packages/main/src/plugin/recommendations/recommendations-registry.ts#L71-L83

**Comment by axel7083** [comment]
cc @slemeur @deboer-tim @benoitf

**Comment by benoitf** [comment]
yes
