### ISSUE TITLE
Podman Machine E2E tests that are run in the middle of the suite are breaking podman machine for the rest of the tests on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6837]
### Bug description

I am suspecting the podman machine onboarding and dashboard e2e test that are run in the middle of the suite, are not properly recovering the testing environment and this breaks or blocks other tests since podman is installed, but podman machine is not started/created and so the rest of the tests fail.

We have three options.
1. update mentioned tests so that we end up with test env. state as if was before the test started
2. Create a requirement for each tests to take care of its environment before it starts
3. Change the order of the tests and make sure these are run as last ones

### Operating system

Windows, Mac

### Installation Method

Other

### Version

next (development version)

### Additional context

Ref workflow run: https://github.com/containers/podman-desktop-e2e/actions/runs/8749122687
It seems that we might faced some timeout or other issue when running podman-machine-onbaording: https://github.com/containers/podman-desktop-e2e/actions/runs/8749122687/job/24010243174#step:8:2785.

**Comment by cbr7** [comment]
This bug has already been fixed, podman machine e2e tests are run successfully on windows now and system state is good when they end.

**Comment by odockal** [comment]
@cbr7 Perfect, thanks!
