### ISSUE TITLE
error on initialization in 0.9.0

### ISSUE THREAD

**Issue by haircommander** [containers/podman-desktop#685]
### Bug description

when I try to click the `start podman` switch, I am met with this error:
```
Error: Starting machine "podman-machine-default" There is no distribution with the supplied name.    Error: WSL bootstrap script failed: exit status 4294967295
```

I believe this is because the default in the Resources tab to create is called `my-machine`

manually removing the podman machines seems to fix the issue

### Operating system

Windows 11

### Version

0.9.0

### Steps to reproduce

I am a bit fuzzy with the exact sequence. I think I just clicked `initialize podman` and it failed OOTB. it's also possible I tried that, it took a bit, so I went to the resources tab and tried to create one manually (named `my-machine` by default)

**Comment by benoitf** [comment]
Hello @haircommander 

It looks like a WSL error
https://github.com/microsoft/WSL/issues/5092

**Comment by benoitf** [comment]
closing as it's upstream bug https://github.com/microsoft/WSL/issues/5092
