### ISSUE TITLE
Image Checker Extension always marked with `Update` tag after restart

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#6865]
### Bug description

Image Checker extension appears in list with `Update` tag after restart. Update downloads tar file and removes the tag but version stays the same after update.

https://github.com/containers/podman-desktop/assets/620330/bf063d13-1ba3-4723-b293-4e3dbd4f025c

Then after restart story repeats.

### Operating system

macOS M1 Sonoma 14.3

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Install Image Checker 
2. Restart PD
3. Open Settings/Extensions page
4. Image Checker marked with `Update` tag
5. Update Image Checker to remove the tag, but version still stays the same
6. Restart PD
7. Open Settings/Extensions page
8. Image Checker `Update` tag is back

### Relevant log output

```shell
Update downloads and install extension successfully.


...
main ↪️ Downloading sha256:dbdbac458b83979eeea6cf7ff9c63e2f4bcac085eb3510c1282589caa33ad43c.tar - 100% - (15895592/15964256)
VM5:62 main ↪️ Downloading sha256:dbdbac458b83979eeea6cf7ff9c63e2f4bcac085eb3510c1282589caa33ad43c.tar - 100% - (15922024/15964256)
VM5:62 main ↪️ Downloading sha256:dbdbac458b83979eeea6cf7ff9c63e2f4bcac085eb3510c1282589caa33ad43c.tar - 100% - (15938408/15964256)
VM5:62 main ↪️ Downloading sha256:dbdbac458b83979eeea6cf7ff9c63e2f4bcac085eb3510c1282589caa33ad43c.tar - 100% - (15954792/15964256)
VM5:62 main ↪️ Downloading sha256:dbdbac458b83979eeea6cf7ff9c63e2f4bcac085eb3510c1282589caa33ad43c.tar - 100% - (15964256/15964256)
VM5:62 main ↪️ Filtering image content...
VM5:62 main ↪️ Activating extension (redhat.openshift-checker) with max activation time of 10 seconds
VM5:62 main ↪️ Activating extension (redhat.openshift-checker) ended in 0 milliseconds
```

**Comment by deboer-tim** [comment]
This is a bug in the image checker or what's published in the catalog, can be transferred to https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext.

The catalog lists v0.1.1, but when you install it the extension says it is v0.0.1, hence there is an update available. This is likely a just a bug in the release action not updating the version in package.json.

**Comment by dgolovin** [comment]
@deboer-tim we can close it then. Thanks!

**Comment by jeffmaury** [comment]
Moved to https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext/issues/48
