### ISSUE TITLE
Update documentation on how to install extensions

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#6883]
### Is your enhancement related to a problem? Please describe

The current documentation does not reflect the details on how to install extensios 

### Describe the solution you'd like

Update existing documentation to include details on how to install extensions

**Comment by cdrage** [comment]
Notes from Tim and I:

- Update the current "installing extensions" page with screenshots
- Move installation extensions page higher up on the side-bar so it's more showable
- Rename extensions folder to something else (writing extensions is not useful, maybe development extensions)
