### ISSUE TITLE
Light mode for NavPage & FormPage

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6889]
### Is your enhancement related to a problem? Please describe

We need to support light mode on these two pages, since they're used extensively.

### Describe the solution you'd like

Define missing bg/tile/divider colors in the light mode palette and use them in these pages (bg color likely one page up).

**Comment by feloy** [comment]
@deboer-tim what do you mean by `bg color likely one page up `?

**Comment by deboer-tim** [comment]
> @deboer-tim what do you mean by `bg color likely one page up `?

I think the background color comes from App.svelte:102/3, not the pages themselves.
