### ISSUE TITLE
Implement TasksProgress UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6902]

**Comment by axel7083** [comment]
This is a very specific component only AI Lab is using, I am not sure we would want to include it in the library? Would podman-desktop have an usage ?

**Comment by deboer-tim** [comment]
Likewise, I think we have a general tasks/background issue in Podman Desktop, and we should not expose something for extensions to use and continue to work around the issue in different ways until we have a clear direction in the base.

**Comment by axel7083** [comment]
After discussing with @jeffmaury we decided to close this ticket as this component is not shared between librairies, and therefore does not need to be included in the library
