### ISSUE TITLE
Implement Modal UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6906]

**Comment by axel7083** [comment]
### Soft Requirement
- [ ] https://github.com/containers/podman-desktop/issues/7153
- [ ] https://github.com/containers/podman-desktop/issues/7152

**Comment by axel7083** [comment]
## Hard Requirement

We cannot migrate the `Modal.svelte` component without migrating first the following

- `dialog-utils.ts`
https://github.com/containers/podman-desktop/blob/731d7c495e78982940b1c08c8b345c4b32d30ea2/packages/renderer/src/lib/dialogs/dialog-utils.ts#L19

> ℹ️ This method is used by the following components: `MessageBox.svelte` and `QuickPickInput.svelte`. We either need to move those package to the ui component or find a way to remove the dependencies of this method
