### ISSUE TITLE
Implement SettingsNavItem UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6908]

**Comment by axel7083** [comment]
In some extension we are using a different version as we added icons

**Comment by axel7083** [comment]
This component is using the tinro, @deboer-tim @benoitf 

https://github.com/containers/podman-desktop/blob/5f271ef28fccd1d3e0b94f4c6f213355c4468ab0/packages/renderer/src/lib/preferences/SettingsNavItem.svelte#L2

What is the current status about tinro?

**Comment by deboer-tim** [comment]
I don't know which issue it's in, but I think @benoitf made a comment elsewhere that ideally the UI library should not have any dependency on tinro. It'd be a bit more work but we could still expose a SettingsNavItem that allows a pluggable/external mechanism to decide what is selected, and extend it with a tinro-enabled version in renderer that we use internally.

**Comment by benoitf** [comment]
yes correct, we need to get rid/never introduce tinro dependency into the UI library component

**Comment by axel7083** [comment]
Depends on https://github.com/containers/podman-desktop/issues/7279

**Comment by axel7083** [comment]
@deboer-tim @benoitf would you agree I open a PR to add the support of icon in the `SettingsNavItem` ?

In Podman AI Lab we have a requirement on having an icon property as visible in 

https://github.com/containers/podman-desktop-extension-ai-lab/blob/5a705f2f01109fcf7c65992aaf05153fa3c714a9/packages/frontend/src/lib/SettingsNavItem.svelte#L48-L51

**Comment by benoitf** [comment]
yes

**Comment by deboer-tim** [comment]
I have no problem adding icon to SettingsNavItem.

That said, I actually think this should be included in the left nav scaling/Kubernetes design discussion. :) IMHO groups like 'Podman', 'Kubernetes', 'AI Lab' should be all be addable to main nav or as children like AI Lab is today, and 'show labels' should be an option.
