### ISSUE TITLE
Attempt to install Desktop Extension redhatdeveloper/openshift-dd-ext:latest hangs

### ISSUE THREAD

**Issue by DonSchenck** [containers/podman-desktop#691]
### Bug description

Attempted to install Docker Desktop Extension "redhatdeveloper/openshift-dd-ext:latest".

Install hangs at the step where image is being pulled.

Abandoning the installation and checking the Images DOES show the image.

This DOES work in Podman Desktop 0.8.0.

Running Podman v4.3.0

### Operating system

macOS Monterey (12.6.1) Apple M1

### Version

0.9.0

### Steps to reproduce

See the initial comment by me, above.

### Relevant log output

```shell
n/a
```

### Additional context

n/a

**Comment by benoitf** [comment]
thanks for reporting the issue.
It seems @fbricon is having the same issue, I'm investigating.

**Comment by benoitf** [comment]
fix is also in 0.9.1
