### ISSUE TITLE
Implement DropDownMenuItem UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6918]

**Comment by axel7083** [comment]
IMO the `hidden` property should not exists on this component.

https://github.com/containers/podman-desktop/blob/8419cb69b7608045f2f4a96808a436335054a4e1/packages/renderer/src/lib/ui/DropDownMenuItem.svelte#L9

In this scenario, parent wanting to hide should use class:hidden={true} and the component should propagate the class to the first div using `$$props.class`
