### ISSUE TITLE
Implement StarIcon UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6923]

**Comment by deboer-tim** [comment]
IMHO this should just be used internally by StatusIcon, I don't think we're using it directly anywhere.

**Comment by benoitf** [comment]
is there an issue to move StatusIcon ?

**Comment by axel7083** [comment]
cc @jeffmaury

**Comment by benoitf** [comment]
if we don't move StatusIcon then we can close the issue, if we move it, we move this file but do not expose it

**Comment by jeffmaury** [comment]
StarIcon is used by bootc extension: https://github.com/containers/podman-desktop-extension-bootc/blob/main/packages/frontend/src/lib/BootcStatusIcon.svelte

**Comment by deboer-tim** [comment]
I guess I was't clear above, but bootc is only using StarIcon because it implements its own StatusIcon. I think it would be cleaner if a reusable form of StatusIcon was exposed (which wouldn't need to expose StarIcon).
