### ISSUE TITLE
Light mode for Dashboard

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6925]
### Is your enhancement related to a problem? Please describe

The Dashboard doesn't support light mode.

### Describe the solution you'd like

Define any missing colors in the light mode palette and get the main components of the Dashboard working in light mode.

**Comment by ekidneyrh** [comment]
Here's what I had in Penpot for the Dashboard. I know it's the old layout, but that shouldn't effect the colours. 

![Dashboard Theming](https://github.com/containers/podman-desktop/assets/87311656/f566d57f-a680-4f6b-a540-2dffaf421061)
[Dashboard Theming.pdf](https://github.com/containers/podman-desktop/files/15198625/Dashboard.Theming.pdf)

**Comment by feloy** [comment]
Missing colors for `ProviderCard`: 
<img width="973" alt="dashboard-provider-text-colors" src="https://github.com/containers/podman-desktop/assets/9973512/d67c5141-04f8-4da4-99aa-a18de88c8bf3">

- color of `Podman` (`text-gray-400` in sources for dark mode)
- color of `v5.0.2` (`text-gray-800` in sources for dark mode)

**Comment by feloy** [comment]
Missing colors for `Carousel`:

color of left / right arrows (`bg-gray-800 hover:bg-gray-600 disabled:bg-charcoal-700` in sources for dark mode)

**Comment by feloy** [comment]
Missing colors for `GuideCard`:

- color for hover card (`hover:bg-zinc-700` in sources for dark mode)

**Comment by ekidneyrh** [comment]
>color of `Podman` (`text-gray-400` in sources for dark mode)

Light mode charcoal-900

>color of `v5.0.2` (`text-gray-800` in sources for dark mode)

Light mode purple-900

> Missing colors for `Carousel`:
> 
> color of left / right arrows (`bg-gray-800 hover:bg-gray-600 disabled:bg-charcoal-700` in sources for dark mode)

Light mode bg-purple-900 hover:bg-purple-600 disabled:bg-charcoal-200. For the arrows within the circle/button can then be transparent or match the bg colour of the card, so in this case they would be gray-050

> Missing colors for `GuideCard`:
> 
>   color for hover card (`hover:bg-zinc-700` in sources for dark mode)

Is the guide card the cards within the carousel? If so, I have them for gray-300 and hover: gray-200

Thanks for this @feloy!!

**Comment by ekidneyrh** [comment]
Just re-opening this as I have some comments on the current implementation. If this would be better elsewhere, let me know.

Current implementation of the dashboard:

![Screenshot from 2024-06-25 10-18-07](https://github.com/containers/podman-desktop/assets/87311656/391e43ab-27a7-4f05-ab29-ff693818c194)

I think a few minor changes would be beneficial. I'll also have these changed in the design documentation.

### Connection Status Labels 

This could probably warrant its own ticket. I would recommend the following changes for light mode: 

![Conncetion Status](https://github.com/containers/podman-desktop/assets/87311656/78a0f90d-c710-479b-81ba-4ee494649f27)

### content-card-text

I don't think this colour is defined yet. This could be labelled the error message text. I would recommend changing this to charcoal-500 for better visibility. 

### content-card-carousel-card-text  

Also change this to charcoal-500. I know it was my decision for the purple here, but having it match the provider cards works better I think. 

With the changes above, the dashboard should look like this:
![Screenshot from 2024-06-25 11-13-49](https://github.com/containers/podman-desktop/assets/87311656/014fab4e-4910-435a-860a-4a0299857a62)

**Comment by deboer-tim** [comment]
@ekidneyrh For the connection status and carousel colors I've opened PR #8236. Please review these and note that they are shared color variables now and providers weren't using them - the connection status won't be updated until _both_ #8236 (updates to colors) and #8235 (provider should use the color vars) are merged, but you _will_ see the status colors change everywhere else they are used in the meantime (e.g. status icons on every page).

For the remaining content-card-text, it's not clear to me which text this color would be used for. Let's chat or please open a separate issue to handle this and I can update it.
