### ISSUE TITLE
Light mode for DetailsPage

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6927]
### Is your enhancement related to a problem? Please describe

We need to support light mode on DetailsPage.

### Describe the solution you'd like

Define missing bg/tile/divider colors in the light mode palette and use them on the component.

**Comment by ekidneyrh** [comment]
https://github.com/containers/podman-desktop/pull/7249#issuecomment-2120184335 left a comment here with the proposed colours
