### ISSUE TITLE
Next batch of colors in light mode palette

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6929]
### Is your enhancement related to a problem? Please describe

We need the next batch of colors for light mode.

### Describe the solution you'd like

We will meet and figure out how we want to work on this, but we need to define the next batch of colors for light mode.

The coming components/pages in rough order:

- [x] Select component → [+/- Button](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#--button) 
- [x] NavPage (main pages, mostly background colors) → [Nav page theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#nav-page)
- [x] Form pages → [Form page theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#form-page)
- [x] Details page → [Details page theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#details-pages)
- [x] Tables → [Table / Nav page theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#nav-page)
- [x] Dropdown → [Dropdown theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#dropdown)
- [x] Toggle → [Toggle theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#toggle)
- [x] Preferences tiles → [Preference page / inverted content theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#inverted-main-content)
- [x] Tooltips → [Tooltip theming](https://github.com/containers/podman-desktop/wiki/Design-System-Theming#tooltip)

**Comment by ekidneyrh** [comment]
I'm unsure what you mean exactly by NavPage, but is this what you're referring to? I refer to it as the main content theming and then the invert content theming for when you are in the settings.

Content Theming:

[Content Theming.pdf](https://github.com/containers/podman-desktop/files/15198682/Content.Theming.pdf)

![Image](https://github.com/containers/podman-desktop/assets/87311656/271eb453-3274-4a02-b3cd-bed00e7f3345)

Invert Content Theming:

[Invert Content Theming.pdf](https://github.com/containers/podman-desktop/files/15198700/Invert.Content.Theming.pdf)

![Image](https://github.com/containers/podman-desktop/assets/87311656/b11e5b48-84ce-4a36-90f1-f1281b37c7b6)

**Comment by deboer-tim** [comment]
NavPage is just the main pages like Containers, Images. Same header / major colors as Content Theming (what we call a form page) so this is likely enough for @feloy.

Today the forms (content theming) have a different bg color on the card in addition to the content-card-bg. Are we removing those? e.g. light gray here:

![Screenshot 2024-05-03 at 8 32 14 AM](https://github.com/containers/podman-desktop/assets/19958075/9c1c24a8-a94d-4d32-bf7d-bf9abb0eaa14)

**Comment by feloy** [comment]
@ekidneyrh there is also this thin line below the tabs names, used in NavPage (see first screenshot - Containers List page) and FormPage (see second screenshot - Troubleshooting page), which is not defined in the Content Theming afaik. In the sources, it is defined as `charcoal-400` for dark mode.

![nav-tab](https://github.com/containers/podman-desktop/assets/9973512/dbfe2d42-f223-4655-8cf2-0da651e096a6)
![form-tab](https://github.com/containers/podman-desktop/assets/9973512/9f7dc506-aeae-46b0-960c-4d933f58a315)

**Comment by ekidneyrh** [comment]
> NavPage is just the main pages like Containers, Images. Same header / major colors as Content Theming (what we call a form page) so this is likely enough for @feloy.
> 
> Today the forms (content theming) have a different bg color on the card in addition to the content-card-bg. Are we removing those? e.g. light gray here:
> 
> ![Screenshot 2024-05-03 at 8 32 14 AM](https://private-user-images.githubusercontent.com/19958075/327756789-9c1c24a8-a94d-4d32-bf7d-bf9abb0eaa14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4MjIsIm5iZiI6MTcxNTA3MzUyMiwicGF0aCI6Ii8xOTk1ODA3NS8zMjc3NTY3ODktOWMxYzI0YTgtYTk0ZC00ZDMyLWJmN2QtYmY5YWJiMGVhYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzY2ZGQ0OTQxNWJmZjNiZWY0NWE3OTIzODcxNWZmM2MxMzMzNWVmMDEwMjMzYzZmNmY3NzEyMmQ2MzJmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kvaU3SmDzYzo5SByzCiYrbVANVzrsF0wo9HT1I2Yu3A)

I forgot I made this change on the mock-ups when I first did this at the start of the year. IMO it looks cleaner, but that's up for debate I think.  WDYT?

**Comment by ekidneyrh** [comment]
> @ekidneyrh there is also this thin line below the tabs names, used in NavPage (see first screenshot - Containers List page) and FormPage (see second screenshot - Troubleshooting page), which is not defined in the Content Theming afaik. In the sources, it is defined as `charcoal-400` for dark mode.
> 
> ![nav-tab](https://private-user-images.githubusercontent.com/9973512/328463883-dbfe2d42-f223-4655-8cf2-0da651e096a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4MjIsIm5iZiI6MTcxNTA3MzUyMiwicGF0aCI6Ii85OTczNTEyLzMyODQ2Mzg4My1kYmZlMmQ0Mi1mMjIzLTQ2NTUtOGNmMi0wZGE2NTFlMDk2YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDkxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAwYjBiNDJlNThiMTBiNzkyNDIyZTY2YjhkZjdlNzVhMTRlYzg3ZmRkZDFiNWQ2ZjI4ZGU3M2Y2ZmM2MWI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CnJSxuIrFqs7hsB4E1NYJhKVtzadq-1BJ56Pg-Zllec) ![form-tab](https://private-user-images.githubusercontent.com/9973512/328463912-9f7dc506-aeae-46b0-960c-4d933f58a315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4MjIsIm5iZiI6MTcxNTA3MzUyMiwicGF0aCI6Ii85OTczNTEyLzMyODQ2MzkxMi05ZjdkYzUwNi1hZWFlLTQ2YjAtOTYwYy00ZDkzM2Y1OGEzMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDkxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIxODJmZmMwZmU5ZWNiZmZmM2E5Mjc5NzU2YjBjNThiMjJiM2RhNDM5ZmZkZTUxM2YzY2RkMDQ1NTk1Zjc4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IJgWc3VIm9-haVsU9G5_5dhcdLlDEbDZHe6et5YbxLI)

I still need to add this version of the screen in! But yes charcoal-400 is the way to go

**Comment by feloy** [comment]
> > @ekidneyrh there is also this thin line below the tabs names, used in NavPage (see first screenshot - Containers List page) and FormPage (see second screenshot - Troubleshooting page), which is not defined in the Content Theming afaik. In the sources, it is defined as `charcoal-400` for dark mode.
> > ![nav-tab](https://private-user-images.githubusercontent.com/9973512/328463883-dbfe2d42-f223-4655-8cf2-0da651e096a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4MjIsIm5iZiI6MTcxNTA3MzUyMiwicGF0aCI6Ii85OTczNTEyLzMyODQ2Mzg4My1kYmZlMmQ0Mi1mMjIzLTQ2NTUtOGNmMi0wZGE2NTFlMDk2YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDkxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAwYjBiNDJlNThiMTBiNzkyNDIyZTY2YjhkZjdlNzVhMTRlYzg3ZmRkZDFiNWQ2ZjI4ZGU3M2Y2ZmM2MWI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CnJSxuIrFqs7hsB4E1NYJhKVtzadq-1BJ56Pg-Zllec) ![form-tab](https://private-user-images.githubusercontent.com/9973512/328463912-9f7dc506-aeae-46b0-960c-4d933f58a315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4MjIsIm5iZiI6MTcxNTA3MzUyMiwicGF0aCI6Ii85OTczNTEyLzMyODQ2MzkxMi05ZjdkYzUwNi1hZWFlLTQ2YjAtOTYwYy00ZDkzM2Y1OGEzMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDkxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIxODJmZmMwZmU5ZWNiZmZmM2E5Mjc5NzU2YjBjNThiMjJiM2RhNDM5ZmZkZTUxM2YzY2RkMDQ1NTk1Zjc4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IJgWc3VIm9-haVsU9G5_5dhcdLlDEbDZHe6et5YbxLI)
> 
> I still need to add this version of the screen in! But yes charcoal-400 is the way to go

What would be the color for light mode?

**Comment by feloy** [comment]
@ekidneyrh In the Content Theming as defined above, some color names are not prefixed by `content-` (`action-button`, `action-button-text`, `ghost-button`, `card-checked-box-icon`). Is it on purpose? If so, does this mean that these colors are part of another theming (but displayed here for information)?

**Comment by ekidneyrh** [comment]
> What would be the color for light mode?

I haven't got to do that page up yet, but gray-700 seems like a reasonable choice.

> @ekidneyrh In the Content Theming as defined above, some color names are not prefixed by `content-` (`action-button`, `action-button-text`, `ghost-button`, `card-checked-box-icon`). Is it on purpose? If so, does this mean that these colors are part of another theming (but displayed here for information)?

I believe that bc those are colours that can be used else where / aren't unique to the content page.

**Comment by ekidneyrh** [comment]
[+ _ - Button Light.pdf](https://github.com/containers/podman-desktop/files/15234622/%2B._.-.Button.Light.pdf)
[+ _ - Button Dark.pdf](https://github.com/containers/podman-desktop/files/15234623/%2B._.-.Button.Dark.pdf)
![+ _ - Button](https://github.com/containers/podman-desktop/assets/87311656/02ec1e5d-8541-48ae-a8be-23304d1233fc)

Here's the theming for the +/- button. Added an error message underneath to aid colour-blind users

**Comment by ekidneyrh** [comment]
I've started adding the up-to-date colours to https://github.com/containers/podman-desktop/wiki/Design-System-Theming for easier filing

**Comment by ekidneyrh** [comment]
Updated the description with where to find the current theming. 

Will review tables, preferences tiles, and tooltips in coming days.

**Comment by ekidneyrh** [comment]
For tables, here are the colours:

![Table](https://github.com/containers/podman-desktop/assets/87311656/23721752-3826-4a6e-a280-5725da1f884b)
[Table.pdf](https://github.com/user-attachments/files/16020065/Table.pdf)

**Comment by ekidneyrh** [comment]
> For tables, here are the colours:
> 
> ![Table](https://private-user-images.githubusercontent.com/87311656/343921268-23721752-3826-4a6e-a280-5725da1f884b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjQ3MjMsIm5iZiI6MTcxOTU2NDQyMywicGF0aCI6Ii84NzMxMTY1Ni8zNDM5MjEyNjgtMjM3MjE3NTItMzgyNi00YTZlLWEyODAtNTcyNWRhMWY4ODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyODdlOThiNzg1MzY0Nzc4NTI4NjZiZmE0YzVjZGMyMjc1YWFlMzI2YWIyZjQ5NTAzYTI4YmJiNDc1ZTQ0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ArAJWTLrCi-kQgZ6xu_eZ7JtVHkIB5y1tiR72NNVKFs) [Table.pdf](https://github.com/user-attachments/files/16020065/Table.pdf)

[Table.pdf](https://github.com/user-attachments/files/16027349/Table.pdf)
![Table](https://github.com/containers/podman-desktop/assets/87311656/2f1a8a22-dbb1-4847-89ff-437525ce05e2)

Updated with arrows and updated in the nav page section on the wiki https://github.com/containers/podman-desktop/wiki/Design-System-Theming#nav-page

**Comment by ekidneyrh** [comment]
As I was doing the preference tiles, I came across the drop-down and the toggle buttons, so I've included them in this ticket. 

The drop-down follows the same values as the +/- button. 

[dropdown_light.pdf](https://github.com/user-attachments/files/16051045/dropdown_light.pdf)
[dropdown_dark.pdf](https://github.com/user-attachments/files/16051046/dropdown_dark.pdf)
![Dropdown](https://github.com/containers/podman-desktop/assets/87311656/fc0a20e9-b0eb-41c7-b6b2-ac2fda4680fc)

**Comment by ekidneyrh** [comment]
Toggle:

[Toggle.pdf](https://github.com/user-attachments/files/16052868/Toggle.pdf)
![Toggle](https://github.com/containers/podman-desktop/assets/87311656/0d865b9b-df93-4450-9af4-1a8a92aadbfc)

**Comment by ekidneyrh** [comment]
Preferences page
This can also be referenced as the inverted content page 

[Invert Content _ Preferences Theming.pdf](https://github.com/user-attachments/files/16054104/Invert.Content._.Preferences.Theming.pdf)
![Invert Content _ Preferences Theming](https://github.com/containers/podman-desktop/assets/87311656/001a6b95-0440-43b8-8442-d56710613803)

**Comment by ekidneyrh** [comment]
Tooltips 
What is currently implemented is good :) I documented it anyway for reference. Only change is the text for light.tooptip-text, I'd have that as charcoal-900 rather than black. 

[Tooltip Theming.pdf](https://github.com/user-attachments/files/16065655/Tooltip.Theming.pdf)
![Tooltip Theming](https://github.com/containers/podman-desktop/assets/87311656/fa9ac9d6-d827-4e00-98b9-503154eacdfa)
