### ISSUE TITLE
Readme with code not formatted well

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6930]
### Is your enhancement related to a problem? Please describe

On github, if a readme has code that is really wide it is put in its own box with a scrollbar. Inside the Podman Desktop extension page it extends very wide and make the whole page scroll.

e.g. here is the readme for the image checker:
<img width="1076" alt="Screenshot 2024-04-23 at 2 18 00 PM" src="https://github.com/containers/podman-desktop/assets/19958075/26b8f9ed-ec9d-43c0-ac55-2cd4e1aff614">

### Describe the solution you'd like

The page should stay within the main boundary as it does on GitHub.

**Comment by benoitf** [comment]
@deboer-tim from which screen is extracted this screenshot ?

AFAIK this page is now removed (the title is from the old details page if using podman-desktop:extension/extensionId

**Comment by deboer-tim** [comment]
Yes, it was from the old screen that has already been replaced. The new screen looks a little nicer, but long code snippets still go off to the right like this. Would be nicer to embed scrolling in each section (and copy/paste...) like GitHub does.
