### ISSUE TITLE
Extensions become built-in and can't be removed

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#6962]
### Bug description

This is after manually removing a DD extension from .local (see #6961), but I've double-checked the folders on disk, restarted, and I don't see how it could be related.

I can no longer remove the bootc extension because it is now built-in:

<img width="577" alt="Screenshot 2024-04-25 at 9 43 58 AM" src="https://github.com/containers/podman-desktop/assets/19958075/9f42df86-4e23-4306-b00c-d1c3ec3a659b">

### Operating system

macOS 14.4

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
@deboer-tim are you starting Podman Desktop in development mode using --extensions-folder to your bootc extension ?

**Comment by benoitf** [comment]
looks like a legit report, I assume you're using development mode of the extension so it's acting like a default extension

**Comment by deboer-tim** [comment]
Yeah, never mind 🤦🏼‍♂️. Didn't realize I hadn't fully exited the dev mode build first.
