### ISSUE TITLE
Remove isolation failure risks from Registry e2e tests

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#6972]
### Is your enhancement related to a problem? Please describe

Improve Registry tests so that failure of one of the tests wont affect the others and enhance tests reliability. 

### Describe the solution you'd like

Implement afterEach method, that will ensure the execution/progression of tests regardless of failures.

**Comment by xbabalov** [comment]
Blocked by https://github.com/containers/podman-desktop/issues/8596

**Comment by odockal** [comment]
@xbabalov Are we going to close the issue?
