### ISSUE TITLE
Dashboard podman row is misaligned to the right

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6973]
### Bug description

It seems that the Podman section on the dashboard is misaligned to the right, making all the buttons not be centered.

<img width="1721" alt="Screenshot 2024-04-26 at 10 51 36" src="https://github.com/containers/podman-desktop/assets/106525396/7736eca5-eed7-4843-acf9-344d3cc8e894">
<img width="1707" alt="Screenshot 2024-04-26 at 10 55 29" src="https://github.com/containers/podman-desktop/assets/106525396/539aba7c-7e0f-4b12-86a1-bc36b8cd4c15">

### Operating system

macOS, win

### Installation Method

Installer from website/GitHub releases

### Version

1.10.0

### Steps to reproduce

1. Install PD 1.10
2. Go to the Dashboard.
3. Notice section is not aligned to the center.

**Comment by odockal** [comment]
It is dupe of https://github.com/containers/podman-desktop/issues/6959.
But it got better pictures, so I will close the former issue.

**Comment by odockal** [comment]
![LayoutBrokenPodmanDashboard2](https://github.com/containers/podman-desktop/assets/19164299/e8f1b4af-80ef-4b2e-9edd-f980b5226940)

**Comment by lstocchi** [comment]
@odockal @cbr7  i just tried using the main branch and it works fine to me on the onboarding. Could you give this a try?

I'm looking for the design on penpot to see how the button should be positioned (for the dashboard)

![image](https://github.com/containers/podman-desktop/assets/49404737/64e634dd-d8f3-41fb-a7e8-fea7aa3ee8f9)

**Comment by cbr7** [comment]
@lstocchi reproduced on main branch:

<img width="1628" alt="image" src="https://github.com/containers/podman-desktop/assets/106525396/0aa303bb-e3fa-4638-80f3-7c9260f0992b">

The issue isn't in the onboarding, it's in the Dashboard.

**Comment by lstocchi** [comment]
> @lstocchi reproduced on main branch:
> 
> <img alt="image" width="1628" src="https://private-user-images.githubusercontent.com/106525396/326495527-0aa303bb-e3fa-4638-80f3-7c9260f0992b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDQ4OTEsIm5iZiI6MTcxNDQwNDU5MSwicGF0aCI6Ii8xMDY1MjUzOTYvMzI2NDk1NTI3LTBhYTMwM2JiLWUzZmEtNDYzOC04MGYzLTdjOTI2MGYwOTkyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNTI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWJkODBkYzlmMGM0MTQyNzYxZjhkYzBkMTIyMmI4MTUyZTU4YzBmMGQyZThhM2E2ODliMGUxOGJhYTg3YzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdsiWuAla5aWeyeYR7XmuFspsaYzyw04y5r6r1tp_7Y">
> The issue isn't in the onboarding, it's in the Dashboard.

Aaaah ok, I was able to reproduce. By looking at the image made by Ondrej it looked to me the onboarding step 🤦 . Thanks!

**Comment by cbr7** [comment]
Need to reopen this issue, the previous fix was incomplete, on the dashboard the Podman section is still misaligned to the right in PD version 1.10.1:

<img width="1721" alt="image" src="https://github.com/containers/podman-desktop/assets/106525396/e6edbb56-ed85-42a7-a0b0-3f4547caed76">

![image (1)](https://github.com/containers/podman-desktop/assets/106525396/89ae4d4f-641a-4911-b048-450c144f484a)

**Comment by lstocchi** [comment]
I'm not sure to get what's the problem. Do you think that the "initialize and start" button or the "View detection" and "install" should not be on the right?

**Comment by cbr7** [comment]
@lstocchi yes, those buttons should be centered as they were previously.

**Comment by lstocchi** [comment]
I think this change is the wanted behavior. It was made by @ekidneyrh here https://github.com/containers/podman-desktop/pull/6768 if i get it right. Could you confirm how this should work @ekidneyrh ? Thanks!!

**Comment by cbr7** [comment]
@lstocchi but even in the picture from that PR you can see the "View detection checks" button centered with the text somewhat, not isolated to the right edge.

**Comment by ekidneyrh** [comment]
Yah, ideally it would be centred within its 'cell'.  And then the cells stretch with the window, if that makes sense? So three cells across

**Comment by odockal** [comment]
Isn't it that the problem lays in the middle cell where is a text regarding podman/podman machine or a progress or machine creation (on windows when you initialize the machine from there) ? That alignment of the middle cell seems to be not in the center but on the left. Then there is too much space between the text and buttons on the right?

**Comment by lstocchi** [comment]
> Yah, ideally it would be centred within its 'cell'. And then the cells stretch with the window, if that makes sense? So three cells across

Sorry @ekidneyrh , was busy on other things.

It is not clear to me which cell should be stretched, just the central one?

Let's say i have `icon | small description | button`
On a wide screen it should look like
` icon |                                           small description                                              | button`
or 
` icon | small description | button                                                                                        `

**Comment by ekidneyrh** [comment]
I suppose I thought it could be that they all stretch, but the ratio is 1:2:1 kinda thing? So the middle column is by default larger than the other two. And then when they stretch, column 1 is aligned left, and the other two aligned to their own respective centres.

**Comment by lstocchi** [comment]
> I suppose I thought it could be that they all stretch, but the ratio is 1:2:1 kinda thing? So the middle column is by default larger than the other two. And then when they stretch, column 1 is aligned left, and the other two aligned to their own respective centres.

Ok, i'll work on the 1:2:1 ratio to see how it looks like and we can discuss on that 👍
