### ISSUE TITLE
Images that are in use are still shown as unused in images page

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6974]
### Bug description

Currently images that are in use are still shown with the status of unused in the images page.

https://github.com/containers/podman-desktop/assets/106525396/8a77ddf4-a653-43a6-8c47-b1c6277b1d11

### Operating system

macOS, windows, linux

### Installation Method

Installer from website/GitHub releases

### Version

1.10.0

### Steps to reproduce

1. Pull an image from the images page.
2. Create a container with it.
3. Go back to Images page and notice that the status of the image is still shown as unused.

**Comment by odockal** [comment]
Reproduced on Mac OS 14 M2 as well.
