### ISSUE TITLE
Switch to a Containers page after creating a container without entrypoint or command

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6981]
### Bug description

When I have an image that I want to run, and there is no name picked up, nor entry point or command, the outcome of pressing the Start the container button visually does nothing. Since the page is not switched, I have no idea that I am actually creating containers (without them being actually started). I should be led to the Container's details page so I know that I am actually doing something.

![creatingContainerPageSwitch](https://github.com/containers/podman-desktop/assets/19164299/65c41438-4e7e-4c7e-a458-653a7ceb7f63)

### Operating system

Windows 10

### Installation Method

None

### Version

1.10.0

**Comment by benoitf** [comment]
I think there is already an issue for that, searching

**Comment by benoitf** [comment]
looks like https://github.com/containers/podman-desktop/issues/6364 is similar but maybe it's not this one

**Comment by odockal** [comment]
In console log there is no error afaik, so I think it might be a bit different. We might also consider this being more enhancement than bug.

**Comment by rostalan** [comment]
can't reproduce on fedora 40
