### ISSUE TITLE
breadcrumb in extension details does not properly redirect to previous page

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6988]
### Bug description

When opening an extension details page from the extension catalog, and using the breadcrumb, to go to previous page we are redirected to the installed page, forcing us to click again to the catalog page

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/6953

**Comment by axel7083** [comment]
Closing in favour of https://github.com/containers/podman-desktop/issues/6953
