### ISSUE TITLE
Custom install of extensions should display the logs

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6998]
### Is your enhancement related to a problem? Please describe

Todays the logs are collected but not displayed

https://github.com/containers/podman-desktop/blob/b6ffdbfe0ab31924356e07bf9c67d40b5059bf68/packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte#L16

### Describe the solution you'd like

We should display a terminal to give more information of what is happening to the user (expandable maybe) like the the logs in resource creation page

![image](https://github.com/containers/podman-desktop/assets/42176370/bb3f3fca-5e62-4497-8ae4-4ec89731aea5)

![image](https://github.com/containers/podman-desktop/assets/42176370/e6e6816c-1c39-481a-be4e-d3d45c15399c)

### Additional context

cc @jeffmaury @benoitf for opinion

**Comment by deboer-tim** [comment]
Being able to easily see logs when something goes wrong is handy, but I wouldn't want to make this the default/normal experience - these are extensions in a GUI, not end-user cli tools like in the resource creation page.
