### ISSUE TITLE
Start/Stop container engine's VM from the system tray

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#7]
## Description ##
As a user, I should be able to Start/Stop the VMs of my container engines from the system tray.

## Acceptance criteria ##
- When the user clicks on the system tray, for each detected container engines (and their VMs) there is an entry in the menu. 
  - if the VM is running, the user gets a menu entry that allows to stop the VM
  - if the VM is stopped, the user gets a menu entry that allows to start the VM
 - When the VM is starting, a small indicator is visible in the system tray which indicates the VM is starting
 - If there is an error when starting the VM, then
   - an error indicator is visible in the system tray menu
   - an alert message is getting displayed, showing the details of the error
   - if the user clicks on the VM (with the error indicator), the alert with details about the error is getting displayed

**Comment by benoitf** [comment]
possible since https://github.com/containers/desktop/commit/1c5aee75c06a2f01b3d178204734fb77aed58241
