### ISSUE TITLE
Redundant title in extension catalog

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7002]
### Is your enhancement related to a problem? Please describe

The Extensions Catalog has a secondary title that says `Available extensions`, but surely that is obvious/we wouldn't have a second area showing unavailable extensions:

<img width="305" alt="Screenshot 2024-04-29 at 11 05 39 AM" src="https://github.com/containers/podman-desktop/assets/19958075/674f1ead-1514-4d59-8f03-630714a6f9ec">

### Describe the solution you'd like

Remove this line, which will also allow slightly more extensions to be shown.

**Comment by benoitf** [comment]
already included there https://github.com/containers/podman-desktop/issues/6757
