### ISSUE TITLE
Installation pack of extensions lead to performance issues

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7030]
### Bug description

When installation a pack of extension I am facing a freeze of the Podman-Desktop application of about 10-20 seconds.

This freeze is propositional to the number of extensions being installed.

<img width="766" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/ed19571c-7ba7-40d6-83ce-c012e46bc4c2">

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

I tried to profile the `extension-installer:install-from-image` listener. After filtering, here are the functions with the sum of their execution time.

<img width="742" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/7559da37-9b05-4a17-8d17-798426dbf4e8">

The top functions during the loading of extensions, are the `loadRuntime` and `activateExtension` which are called inside the `loadExtension`.

https://github.com/containers/podman-desktop/blob/1e21c883e5118bccd7a05359cf894b62a4236583/packages/main/src/plugin/extension-loader.ts#L1286

https://github.com/containers/podman-desktop/blob/1e21c883e5118bccd7a05359cf894b62a4236583/packages/main/src/plugin/extension-loader.ts#L1341

### Additional context

A direct consequence is the extensions in a `failed` state as they took too much time to start. (there is a 10s limit)

**Comment by ScrewTSW** [comment]
Not reproduced in 1.10.3 W10 22H2

**Comment by axel7083** [comment]
> Not reproduced in 1.10.3 W10 22H2

Could you precise the processor and ram ?
