### ISSUE TITLE
Provider status is too loud

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7040]
### Is your enhancement related to a problem? Please describe

I tried to ignore it, but it's still bugging me: the provider status on the dashboard is bigger than it used to be and now it always feels like it's yelling:

<img width="388" alt="Screenshot 2024-05-01 at 8 17 49 AM" src="https://github.com/containers/podman-desktop/assets/19958075/580cb14b-12f8-4229-b727-bed881ee2bc5">

Provider status on the dashboard is rarely useful to me - e.g. some are always 'running' even if they're not configured, and if I have multiple Podman machines it's not telling me which one is actually running. When the status was smaller it was just a background message that I could easily ignore, but having it in color and big it feels LIKE THIS and my eye is drawn to it more than any other text.

### Describe the solution you'd like

@ekidneyrh would you be ok if we reduced the font size closer to where it was?

**Comment by ekidneyrh** [comment]
Sorry for making it yell :smiling_face_with_tear: I think the caps makes it worse lol. Reducing it back is OK to a size smaller than what it is.
