### ISSUE TITLE
Add option to prune only untagged images

### ISSUE THREAD

**Issue by kdubois** [containers/podman-desktop#7043]
### Is your enhancement related to a problem? Please describe

It would be nice if I could **only** prune images that are **untagged** (ie. that appear as <none>) instead of pruning all images that aren't used by a container. 

### Describe the solution you'd like

An option when you click the 'prune' button in the images section to either prune "all unused images" or "only untagged images"

**Comment by kdubois** [comment]
Can we reopen this?  This is a very much needed feature.

**Comment by kdubois** [comment]
@benoitf

**Comment by benoitf** [comment]
opened https://github.com/podman-desktop/podman-desktop/pull/10400
