### ISSUE TITLE
Requirements check message on Windows differs between onboarding and dashboard podman installation offering

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7044]
### Bug description

![podman_requirements_check_windows](https://github.com/containers/podman-desktop/assets/19164299/b54dffc8-30f9-41bf-8c2c-11eefbf677de)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by benoitf** [comment]
@axel7083 @lstocchi could you check as you're on Windows ?

**Comment by lstocchi** [comment]
Most probably is just that the `docLinksDescription` is not displayed in the Provider class, gonna give it a try after the test on ai lab
