### ISSUE TITLE
Rootful podman machine gets stuck using rootless connection after another rootless machine is deleted

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#7052]
### Bug description

It seems that in some situations a rootful podman machine can get stuck using a rootless connection if the user deletes another podman machine which is rootless and is set to default at the same time.

Additionally it seems that this scenario also makes the "This machine is not set to default" prompt to be displayed at all until such time that the user manually shuts down Podman Desktop and reopens it.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.10.0

### Steps to reproduce

1. Have two podman WSL machines available on the system, one rootful and one rootless, the rootless machine should be set to default and both machines should be running at the same time.
2. Go to Settings -> Resources menu.
3. Stop the rootless podman machine.
4. A popup will be triggered during the stop action which will notify the user that the rootful machine is not set to default, select the `Ignore` option on the popup.
5. After the rootless podman machine finishes shutting down, delete it.
6. At this point the bug should have reproduced, going into CLI running the command `podman system connection list` will display the rootful podman machines's connections, but will show that the rootless connection is the one set to default, not the rootful one as it should be.
7. Additionally if the user makes anymore podman machines from PD, either rootful or rootless the "machine is not set as default" prompt will no longer be displayed until the user completely closes PD and reopens it.

**Comment by benoitf** [comment]
when you say 'get stuck' it's all about the CLI ?
if you're facing podman CLI issues, it's not a Podman Desktop issue but an upstream podman issue

**Comment by cbr7** [comment]
@benoitf most of it is CLI yes, but the fact that the popup in PD no longer gets triggered is a PD issue.

**Comment by benoitf** [comment]
but Podman Desktop should not be a tool to workaround podman CLI bugs

maybe it's another one like https://github.com/containers/podman/issues/16483 in the past

**Comment by cbr7** [comment]
@benoitf @odockal created https://github.com/containers/podman/issues/22577 in the podman repo

**Comment by cbr7** [comment]
I wouldn't describe PD's functionality of displaying a popup as a workaround, especially since it's broken until the app is restarted. For example even if the user deletes all the podman machines and creates new ones, and as such everything is perfectly ok with the podman connections, the PD popup that notifies the user about default podman machines will still not be displayed. A full app restart will be required.

**Comment by cbr7** [comment]
Was also able to reproduce this on macOS in PD 1.10.2

**Comment by ScrewTSW** [comment]
Still present in 1.10.3
