### ISSUE TITLE
Podman is not updating to 5.0.1

### ISSUE THREAD

**Issue by anunayamar** [containers/podman-desktop#7058]
### Bug description

Not able to update podman version to v5.0.1

After the update the podman rollbacks to v4.7.2 (the current version)
Podman desktop version: v1.9.1

![image](https://github.com/containers/podman-desktop/assets/15718667/debda17b-145b-4616-bf3c-625ae28c9920)

### Operating system

macOS Sonoma 14.3.1

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

Try updating the podman from v4.7.2 to 5.0.1 on podman desktop v1.9.1

**Comment by benoitf** [comment]
hello, could you check that you don't have like both a `brew` installed podman ( /opt/homebrew/bin/podman) and a podman installed by an installer

do `brew uninstall podman`

and check you only have `/opt/podman` (and `/opt/podman/bin/podman`)

**Comment by anunayamar** [comment]
thanks, I had both brew installed podman and podman installed by an installer
