### ISSUE TITLE
Podman provider settings feel unnecessarily nested on Linux

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#706]
### Is your enhancement related to a problem? Please describe

To see the socket information, you have to go to Resources > Podman > Podman.
![image](https://user-images.githubusercontent.com/277927/198125514-f5af3d6c-fedb-4c02-a01d-5c646f9cddbc.png)

### Describe the solution you'd like

Simplify this, put the socket information at Resource > Podman and drop the nested Podman item.

**Comment by benoitf** [comment]
I think 'Podman' is for the name of machine ( you can have multiple) but for sure it can be displayed differently

**Comment by dylanmtaylor** [comment]
> I think 'Podman' is for the name of machine ( you can have multiple) but for sure it can be displayed differently

So on Linux, it's not using podman machines, so it makes less sense. Perhaps we can handle this differently?

**Comment by benoitf** [comment]
sure also we can display tiles directly at the upper level

**Comment by dylanmtaylor** [comment]
> sure also we can display tiles directly at the upper level

Oh, I see what you're saying. This is what it looks like on Mac:
![image](https://user-images.githubusercontent.com/277927/198139045-f83968f7-d667-4026-9ef1-8899a9196f0e.png)
![image](https://user-images.githubusercontent.com/277927/198139139-e2b9d4f5-2a5d-4c5e-83be-223e58fbf715.png)

But on Linux, that upper menu just says "Podman Provider" and the socket info is hidden under that drop-down.
![image](https://user-images.githubusercontent.com/277927/198148759-d012de5b-735a-4e81-bccf-f5d8865c617b.png)

**Comment by deboer-tim** [comment]
Since this issue was last touched we have redone Settings in the left navigation, made Resources the default Settings page, and put tiles for each machine directly on the page instead of being a subpage. Hopefully this resolves the majority of the problem and makes it far less clicks to get to; please feel free to open a new issue if there are additional improvements you'd like based on the current design.
