### ISSUE TITLE
consider optimizing your actions usage

### ISSUE THREAD

**Issue by cgwalters** [containers/podman-desktop#7066]
### Is your enhancement related to a problem? Please describe

Looking at https://github.com/organizations/containers/settings/actions/hosted-runners right now, podman-desktop is using 10/20 open Github Action runners slots.

We are discussing making more dedicated runner capacity available for the containers github organization as a whole. 

However, can you take a look and see whether some of your jobs require a full virtual machine *on their own*, or could some of them be consolidated serially onto the same VM?

### Describe the solution you'd like

Please look at some actions consolidation.

**Comment by benoitf** [comment]
we're doing our release right now with bugfixes and many backports so it's expected to have such usage during this time.

All the jobs require VM on different OS (Linux, macOS and Windows)

**Comment by lmilbaum** [comment]
Related to https://github.com/containers/podman-desktop/issues/7066

**Comment by cgwalters** [comment]
FWIW at this very moment, this repository is using 18/20 of the available runners:

![image](https://github.com/containers/podman-desktop/assets/244096/d56d7366-0d3b-4f26-9283-3b3773b19293)

**Comment by benoitf** [comment]
I think you need to look at it during a small amount of time because 7mn after it's not the same picture

**Comment by benoitf** [comment]
![image](https://github.com/containers/podman-desktop/assets/436777/af2e7d72-63a3-4c1d-a45c-3e95ac4755a4)

**Comment by cgwalters** [comment]
Yeah fair, and right now it's back down to 3.  I think this repository just has a lot of jobs, so when we get a backlog it's very visible with jobs here. 

Some digging around turned up https://github.com/self-actuated/actions-usage - I might try it out.

**Comment by benoitf** [comment]
closing as we moved to another org
