### ISSUE TITLE
Perhaps header should be hidden on Linux/Windows

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#708]
### Is your enhancement related to a problem? Please describe

Since the native OS title bar shows the name of the app and Podman desktop does not use frameless windows, perhaps the header should be hidden on these platforms as it is redundant. 

KDE example: 

![image](https://user-images.githubusercontent.com/277927/198162045-19426959-fe7b-4c4f-bc7b-b5fdb29b983f.png)

### Describe the solution you'd like

Set display: none; on the header bar based on if (!isMac).

**Comment by dylanmtaylor** [comment]
Now that I think about it, it's not particularly useful to display the Dashboard text on the Dasboard tab or "Podman"/"Docker" in the section that clearly has the logos on them. if anything it should be alt text of the image.
![image](https://user-images.githubusercontent.com/277927/198163393-57a100d4-dcc8-4039-929e-f39afba6e592.png)

**Comment by deboer-tim** [comment]
Thank you for the input. We have completely reworked the title bar and removed text from the left nav for 1.0, so this issue is either 'done', or a new issue should be opened for any remaining ideas.
