### ISSUE TITLE
Podman Desktop Flatpak removes podman.socket on shut down

### ISSUE THREAD

**Issue by jdoss** [containers/podman-desktop#7084]
### Bug description

I enable and start `podman.socket` on boot for my workstation user. When I launch Podman Desktop via Flatpak it works as expected but when I exit the Podman Desktop it removes `/run/user/1000/podman/podman.sock` breaking the other applications that are using this socket.

### Operating system

Fedora Linux 40 (Workstation Edition)

### Installation Method

Flathub (Linux)

### Version

1.9.x

### Steps to reproduce

Start and enable the `podman.socket` for your user.

```bash 
$ systemctl --user enable podman.socket
$ systemctl --user start podman.socket
$ ls /run/user/1000/podman/podman.sock
/run/user/1000/podman/podman.sock
$ systemctl --user status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: disabled)
     Active: active (running) since Fri 2024-05-03 14:27:41 CDT; 25s ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/user/1000/podman/podman.sock (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

May 03 14:27:41 sw-0608 systemd[12081]: Listening on podman.socket - Podman API Socket.
```

Start Podman Desktop Flatpak from GNOME application launcher. You can see the socket file is still present and Podman desktop works as expected.

```bash
$ flatpak ps |grep io.podman_desktop.PodmanDesktop
1360254370	480725	io.podman_desktop.PodmanDesktop	org.freedesktop.Platform
2910334577	480757	io.podman_desktop.PodmanDesktop	org.freedesktop.Platform

$ ls /run/user/1000/podman/podman.sock
/run/user/1000/podman/podman.sock
```

After exiting Podman Desktop via closing it in the app you can see it is removing the podman.sock for some reason. The `podman.socket` systemd socket still thinks it is running.

```bash
$ ls /run/user/1000/podman/podman.sock
ls: cannot access '/run/user/1000/podman/podman.sock': No such file or directory
$ systemctl --user status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: disabled)
     Active: active (listening) since Fri 2024-05-03 14:35:53 CDT; 1min 48s ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/user/1000/podman/podman.sock (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

May 03 14:35:53 sw-0608 systemd[12081]: Listening on podman.socket - Podman API Socket.
```

### Additional context

```
$ flatpak list |grep podman
Red Hat, Inc.	io.podman_desktop.PodmanDesktop	1.9.1	stable	flathub	syste
```

```
$ rpm -qa |grep podman
podman-plugins-4.9.4-1.fc39.x86_64
podman-5.0.2-1.fc40.x86_64
podman-docker-5.0.2-1.fc40.noarch
```

```
$ cat /etc/redhat-release 
Fedora release 40 (Forty)
```

I tried this with Autostart checked and unchecked and the behavior is the same.

![image](https://github.com/containers/podman-desktop/assets/8195/9f922a01-d718-4232-a969-eee7fd4aca53)

**Comment by afbjorklund** [comment]
This is a known issue, and is due to Podman Desktop ignoring systemd and starting another daemon:

* https://github.com/containers/podman-desktop/issues/2903#issuecomment-1685323885

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/2903
