### ISSUE TITLE
Creating images automatically adds docker.io to the beginning.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7113]
### Bug description

https://github.com/containers/podman-desktop/assets/6422176/58c52054-5fc4-4282-bd97-2601adcd027a

I created an image and named it test-image-hello-world

docker.io was added to the beginning.

I expect `foobar` / the image name instead

### Operating system

mac m1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

1. Create any image
2. Name it anything without a domain
3. It defaults adding `docker.io`

I expect `foobar` / the image name instead

**Comment by benoitf** [comment]
it's a dup of https://github.com/containers/podman-desktop/issues/2433 opened by you
