### ISSUE TITLE
Use native window decorations

### ISSUE THREAD

**Issue by andreaippo** [containers/podman-desktop#7127]
### Is your enhancement related to a problem? Please describe

podman desktop doesn't use window decorations from my DE (KDE).
As a consequence, apart from the unpleasing esthetics, I cannot perform some quick actions that I can on any other app running on my system, for example middle clicking the title of a window to minimize it.

I'm using Wayland.

![image](https://github.com/containers/podman-desktop/assets/801070/bacc596e-2199-46ef-9196-0d3f2dda5771)

### Describe the solution you'd like

Podman desktop should delegate window decorations to the window manager

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/issues/2647

**Comment by benoitf** [comment]
closing as a dup of https://github.com/containers/podman-desktop/issues/2647
