### ISSUE TITLE
Missing arm64 for Linux on website and release pages.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7137]
### Is your enhancement related to a problem? Please describe

I had a lot of difficulty trying to install arm64 Podman Desktop on my linux machine and I couldn't find it.

Only to realize we do not have them on our release pages or even on the website.

### Describe the solution you'd like

arm64 linux releases on website + release pages / download links.

**Comment by benoitf** [comment]
we recommend to use flathub so even probably the flatpak file should be completely removed from the release
