### ISSUE TITLE
Release file names could be improved / say what OS

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7138]
### Is your enhancement related to a problem? Please describe

For the release file names, they should specify what OS they are, it's pretty difficult to determine which one is which without going through each filename extension.

### Describe the solution you'd like

Ex podman-desktop.1.10.2-arm64.zip should be podman-desktop.1.10.2-windows-arm64.zip 

### Additional context

![Screenshot 2024-05-08 at 9 51 19 AM](https://github.com/containers/podman-desktop/assets/6422176/f939a525-4c99-4da9-bf67-10cbb6ecc134)

**Comment by benoitf** [comment]
these are internal files, and used for the update so we can't change their names.

also it would mean that for example dmg file would be called `podman-destop-macos.dmg` and windows `.exe` like `podman-desktop-windows.exe`

which is not a rule on how to name file

closing as won't fix
