### ISSUE TITLE
Trusted CAs from the host not used by podman-desktop when connecting to k8s/ocp

### ISSUE THREAD

**Issue by bit4man** [containers/podman-desktop#7139]
### Bug description

I have a local OCP cluster that's signed with the lab's CA which is part of the ca-trust-chain on the localhost. kubectl/oc cli works in trusted mode.   But when using podman-desktop (1.10.2) fails trying to access the API with "error: self signed certificate in certificate chain".  This happens when running from the podman-desktop tar ball extracted onto Fedora40 or from the flatpak.

Expected behavior: The host's list of trusted CA should be used when doing ssl connections to the k8s/ocp API. 

### Operating system

Fedora 40, x86-64

### Installation Method

Flathub (Linux)

### Version

1.10.2

### Steps to reproduce

1. Install podman-dektop
2. Add kube/ocp extensions
3. Create api and wildcard certs, add the CA to the ca-trust, and apply certs to the openshift-api and the ocp wildcard end point.
4. Verify that oc/kubectl login works using the trusted certs
5. Add cluster api to podman-desktop
6. See errors on console, and podman-desktop does not show content from the cluster

### Relevant log output

```shell
Trying to watch deployments on the kubernetes context named "prog1/api-assist-ocp4-peterlarsen-org:6443/peter" but got a connection refused, retrying the connection in 92s. Error: self signed certificate in certificate chain)
Trying to watch ingresses on the kubernetes context named "kube-system/api-assist-ocp4-peterlarsen-org:6443/peter" but got a connection refused, retrying the connection in 93s. Error: self signed certificate in certificate chain)

(over and over again)
```

**Comment by hadrabap** [comment]
Most probably, the same applies to the "Registries" screen as well where users are supposed to add theirs registries.

I have my own registry that is signed by my own Certificate Authority. All the machines and infrastructure trusts that CA.

When I'm about to log into my registry I get 

```
Unable to find auth info for https://<REDACTED>:5000/v2/. Error: RequestError: unable to get local issuer certificate
```

Please note, this will hit almost all enterprises.

Podman Desktop v1.10.2 (Flatpak)
Oracle Linux 8.9 with UEKR7
Podman v4.6.1 (distribution)

**Comment by mauri13k** [comment]
I was able to fix the issue by explicitly specifying a certificate-authority for the cluster in the .kube/config. This ensures Podman Desktop uses the correct certificate and the connection works.

```yaml
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: path\to\certs.crt
      server: https://api.ocp-cluster.com:6443
    name: api.ocp-cluster.com:6443
```

@bit4man

**Comment by slemeur** [comment]
thanks @mauri13k for showing the following you found.
cc @shipsing : would be nice to document this.
