### ISSUE TITLE
Dependabot Vulnerabilities identified in scan of v1.10.2

### ISSUE THREAD

**Issue by shikari7** [containers/podman-desktop#7140]
### Bug description

Dependabot is reporting the attached vulnerabilities in Podman Desktop 1.10.2. 

### Operating system

all

### Installation Method

Other

### Version

1.10.2

### Steps to reproduce

Dependabot scans of install tool - see attachment for output

**Comment by shikari7** [comment]
[Podman Desktop Vulnerabilities 1.10.2.xlsx](https://github.com/containers/podman-desktop/files/15251860/Podman.Desktop.Vulnerabilities.1.10.2.xlsx)

**Comment by benoitf** [comment]
dependabot report is part of https://github.com/containers/podman-desktop/security no need to have dedicated issues for that

**Comment by shikari7** [comment]
Hey @benoitf thanks for that info - these findings from Dependabot have been present in the last several released versions of Podman Desktop - what is the process for remediating these as part of the release process?  

These findings are impeding use of Podman Desktop in highly secure environments.

**Comment by shikari7** [comment]
hi @benoitf sorry to bother you, can you help me understand how to help get these Dependabot findings remediated?  Thank you.
