### ISSUE TITLE
Unable to change configuration (phantom resets)

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7142]
### Bug description

For a while now I've noticed that every once in a while when I change a configuration value... it changes back. At first I thought maybe I'd missed the button or mis remembered, but eventually I figured out it was indeed happening.

Most of the time it's rare, but today I hit it enough that it was very annoying and it took several attempts to change some preferences. Font size is 10, I change it to 9, it goes back to 10. I try again.. it goes back to 10.

### Operating system

macOS 14.4

### Installation Method

None

### Version

next (development version)

### Additional context

I spent way too long trying to figure this out (especially since I didn't actually find a fix) but I narrowed down what's causing it: the afterUpdate() trigger in PreferencesRenderingItem is happening all the time - sometimes not for a couple seconds, but about once a second, and indefinitely. It resets the entire configuration record. If you make a change and it's saved between two of these calls, everything is fine. If it happens just when you clicked, your change is overwritten and lost.

**Comment by odockal** [comment]
@deboer-tim I am also sometimes seeing preference value going back to default, ie. this is the most common on Mac when I switch Exit on Close. I am always confused since I feel like I haven't clicked the mouse properly so I need to repeat. Sometimes even twice.

**Comment by cdrage** [comment]
Re-opening this as unfortunatley this change causes an issue where (most) of the settings no longer show up :( 

![image](https://github.com/user-attachments/assets/01f3db7a-e108-40ce-8d73-1347a7ea93fc)
