### ISSUE TITLE
Modal svelte component should have an open property

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7152]
### Is your enhancement related to a problem? Please describe

We often use the following logic while using the `Modal.svelte` component:

https://github.com/containers/podman-desktop/blob/d6b22ba8ce44ec584c4150241fc0665c31707671/packages/renderer/src/lib/container/ContainerList.svelte#L689-L693

https://github.com/containers/podman-desktop/blob/d6b22ba8ce44ec584c4150241fc0665c31707671/packages/renderer/src/lib/preferences/PreferencesProviderInstallationModal.svelte#L24-L25

etc.

### Describe the solution you'd like

Adding an `open: boolean` property to the modal component.

This is a very commun pattern in component libraries.[^1][^2]

[^1]: https://flowbite-svelte.com/docs/components/modal#References
[^2]: https://react-bootstrap.netlify.app/docs/components/modal

### Additional context

Related to https://github.com/containers/podman-desktop/issues/6906

**Comment by axel7083** [comment]
would you agree @deboer-tim @benoitf ?

**Comment by deboer-tim** [comment]
Every use is going to do this, so yes, I think it's worth doing. We've done this in EmptyScreen and ListItemButtonIcon with hidden, so precedent is already there. We should decide on open vs hidden though and be consistent in our library.
