### ISSUE TITLE
`QuickPickInput.svelte` and `CommandPalette.svelte` should have same design

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7178]
### Is your enhancement related to a problem? Please describe

| QuickPickInput.svelte | CommandPalette.svelte |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop/assets/42176370/61c2390f-a2e6-46e1-af3b-e36af8ae0a97) | ![image](https://github.com/containers/podman-desktop/assets/42176370/cff66283-5032-46f7-aea0-363174725876) |

### Describe the solution you'd like

- Both are modals, so they should uses the Modal component
> ⚠️ The current modal implementation does not support custom position (`top | bottom | center | left | right`) this should probably be added
- Both are showing searchable list of items

**Comment by axel7083** [comment]
My suggestion would be to **remove** the `CommandPalette.svelte` and make the logic in the `main` package, and uses the `QuickPickInput.svelte` component instead for the commands. The `CommandRegistry` should probably be able to handle that easily. 

## Improving the `CommandRegistry`

First I would add the `InputQuickPickRegistry` in the CommandRegistry class constructor.

I would add a `void showCommandPalette()` responsible of showing a quick pick with the commands.

cc @benoitf what do you think ? I am currently working on the modals so I can make the change

**Comment by benoitf** [comment]
@axel7083 I would not do it now, I think there is already an issue about merging CommandPalette into another component, etc.

Command Palette is still currently quite hidden, so I would prefer to focus on the light theme even and probably this one would be done at the very last.

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/issues/4111
