### ISSUE TITLE
Outline of modal dialogs doesn't stand out

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7187]
### Is your enhancement related to a problem? Please describe

See #7180 for an example of switching from our older/more hardcoded dialog styling to the correct design. I'll admit there isn't much difference, but to me the old style had just a little bit of an edge on the dialog so you could see there is a panel there, but the correct design blends into the background more - black on black. To me it looks like the menu is now just floating instead of being on a quick pick panel.

### Describe the solution you'd like

I've noticed this on regular dialogs, but with the size it is still clear that you're looking at a dialog. IMHO in both cases it would look better and stand out from the background a little more if there was a tiny border, even in dark grey.

FYI to @ekidneyrh

**Comment by ekidneyrh** [comment]
Yah I agree we could add an outlike stroke or a drop shadow to make it stand out more. We've done drop shadows on modal dialogs before:

![image](https://github.com/containers/podman-desktop/assets/87311656/88ae0775-21f1-45e7-abce-503d54fbd658)

If we go the stroke route, i'd suggest gray-600 to match the sidebar icons. Could go thinner with the stroke also

![image](https://github.com/containers/podman-desktop/assets/87311656/195ad358-cd8f-455b-88f9-99c934b34a6b)

**Comment by deboer-tim** [comment]
Thanks, I will try this - as you said, needs to be thin/minor, just enough so it's a defined edge.

**Comment by deboer-tim** [comment]
I tried gray-600 (#b4b4b4) and it seemed really light, then noticed that's not what you used in the image above. :) It looks like it is maybe #4d4d4d, which is closer to charcoal-400 (#4a4b4f). I still found that a touch bright, so I tried one darker - what do you think of this?

Current:

<img width="756" alt="Screenshot 2024-05-16 at 12 14 32 PM" src="https://github.com/containers/podman-desktop/assets/19958075/1085be06-06d2-44d6-b2ac-0097dcf17e6d">

<img width="728" alt="Screenshot 2024-05-16 at 12 16 12 PM" src="https://github.com/containers/podman-desktop/assets/19958075/10f3996b-6a70-4b4e-a225-ff2663879571">


With 1px charcoal-500 border:

<img width="756" alt="Screenshot 2024-05-16 at 12 14 10 PM" src="https://github.com/containers/podman-desktop/assets/19958075/ea1f7ca9-fecb-4400-a356-4dabaed230d1">

<img width="728" alt="Screenshot 2024-05-16 at 12 14 58 PM" src="https://github.com/containers/podman-desktop/assets/19958075/f6ec5089-ff53-4a35-bce9-dd9cb750bd62">

**Comment by ekidneyrh** [comment]
> I tried gray-600 (#b4b4b4) and it seemed really light, then noticed that's not what you used in the image above. :) It looks like it is maybe #4d4d4d, which is closer to charcoal-400 (#4a4b4f). I still found that a touch bright, so I tried one darker - what do you think of this?
> 
> Current:
> <img alt="Screenshot 2024-05-16 at 12 14 32 PM" width="756" src="https://private-user-images.githubusercontent.com/19958075/331291381-1085be06-06d2-44d6-b2ac-0097dcf17e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzkxNjYsIm5iZiI6MTcxNTkzODg2NiwicGF0aCI6Ii8xOTk1ODA3NS8zMzEyOTEzODEtMTA4NWJlMDYtMDZkMi00NGQ2LWIyYWMtMDA5N2RjZjE3ZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5NDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwN2Y4NDRjZjdjOGEzNTIzOGFlZGFlY2YxYjBhNDQyNzdiNGQ3MGYxYjRhN2RiODk4NDZkOTNjYzMxYzAwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20X6towI97SxxYIoi8l2qpQkHN86K2mJZaYMuWeOEKY"> <img alt="Screenshot 2024-05-16 at 12 16 12 PM" width="728" src="https://private-user-images.githubusercontent.com/19958075/331291409-10f3996b-6a70-4b4e-a225-ff2663879571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzkxNjYsIm5iZiI6MTcxNTkzODg2NiwicGF0aCI6Ii8xOTk1ODA3NS8zMzEyOTE0MDktMTBmMzk5NmItNmE3MC00YjRlLWEyMjUtZmYyNjYzODc5NTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5NDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNDQ1YjE2YjczNjc4YWViOTMyMWM0MDRiNWE2NmUwMjI0NTRiNjhkNjUwNTM5NjczZDQ5ZWNjOTFhYjUwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_QGTFvBegAs-_ETAlMRpQjnc10LCZzbb60LgWeRI_w">
> 
> With 1px charcoal-500 border:
> <img alt="Screenshot 2024-05-16 at 12 14 10 PM" width="756" src="https://private-user-images.githubusercontent.com/19958075/331291452-ea1f7ca9-fecb-4400-a356-4dabaed230d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzkxNjYsIm5iZiI6MTcxNTkzODg2NiwicGF0aCI6Ii8xOTk1ODA3NS8zMzEyOTE0NTItZWExZjdjYTktZmVjYi00NDAwLWEzNTYtNGRhYmFlZDIzMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5NDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZGJkYzI2ZjAzZDkyY2I1YzRiMWE0ZjU1NzIzMDI4Y2U3MjYxY2QwNDdjYjU0NDhmMzRiYTMyNWNkZjRmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f9Aj0qkYiA3c5X3VO69BSsjlQ2cEVh2ker7xLa_798I"> <img alt="Screenshot 2024-05-16 at 12 14 58 PM" width="728" src="https://private-user-images.githubusercontent.com/19958075/331291480-f6ec5089-ff53-4a35-bce9-dd9cb750bd62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzkxNjYsIm5iZiI6MTcxNTkzODg2NiwicGF0aCI6Ii8xOTk1ODA3NS8zMzEyOTE0ODAtZjZlYzUwODktZmY1My00YTM1LWJjZTktZGQ5Y2I3NTBiZDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5NDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTA0ZjY2NzI3NWZlYzE1MWUyMzFlMWM5ODc0NWUxMGZlNjM5Njc5ODdkMTFjNDgyNzg5ODM2OTIzODBkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8ySl2kdRAxkwRoZerZXWw7nemsHZsmbJJx-R0_wiz0">

ah yes it was charcoal-400 :see_no_evil: sorry for the typo. The 500 looks great! Boarder is a great thickness too. +1 from me
