### ISSUE TITLE
Tables: use ellipsis for narrow columns

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7195]
### Is your enhancement related to a problem? Please describe

The core Table component does not do a good job when columns are too narrow: when column headers are too wide they drift into other headers, and cells get cutoff at the column boundary.

### Describe the solution you'd like

Column headers, SimpleColumn, and DurationColumn should use ellipsis when they're too wide. When headers are too wide the column sorting should still be visible.

There are *lots* of custom column renderers that need to do the same, this should just cover the core/component level for now.

**Comment by benoitf** [comment]
I think this can be delayed until the next sprint with the table component is in UI library.

I'm moving the files as part of https://github.com/containers/podman-desktop/issues/6903 so it'll probably make conflicts that can be prevented delaying the work on this issue

**Comment by deboer-tim** [comment]
PR #7196 is up and fairly minor. I'm fine delaying either way - if you have code in-progress for #6903 I can rebase it after, otherwise you can merge this before starting work.
