### ISSUE TITLE
Improper detection of Virtual Machine Platform

### ISSUE THREAD

**Issue by nt-baker** [containers/podman-desktop#7211]
### Bug description

While trying to install Podman during Podman Desktop setup, it claims that Virtual Machine Platform is not enabled even though Windows itself says it is.

![image](https://github.com/containers/podman-desktop/assets/7083531/8f470c1d-ffb7-4c5b-b012-7faded9aeee0)

The setup correctly detects that WSL2 is installed and up-to-date. I'm not sure it's possible to have that without Virtual Machine Platform being enabled.

### Operating system

Windows 10 Enterprise

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Additional context

Docker Desktop is also installed, and able to use WSL2 - not sure if that could cause some kind of interference.

**Comment by benoitf** [comment]
hi @nt-baker 

the detection code is using powershell with the command

`(Get-WmiObject -Query "Select * from Win32_OptionalFeature where InstallState = \'1\'").Name | select-string VirtualMachinePlatform`

could you try on a shell and provides the response ?

**Comment by nt-baker** [comment]
From Powershell 5:
![image](https://github.com/containers/podman-desktop/assets/7083531/867c6d09-2e25-404b-a61e-55caf0bdf051)

I tried a number of more basic uses of the `Get-WmiObject` command, most of which failed. It seems like my WMI repository is corrupt. (Based on this [StackOverflow thread](https://stackoverflow.com/a/6930421)) So it fails to query classes that would ordinarily be available.

![image](https://github.com/containers/podman-desktop/assets/7083531/ebc93db2-4769-4c55-998f-794f8a44034d)

Going to try to restore my WMI repository.

**Comment by odockal** [comment]
@nt-baker Did it help? Is the issue gone?
