### ISSUE TITLE
Explore Storybook (https://storybook.js.org) for Svelte components

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#7218]

**Comment by axel7083** [comment]
Here is the showcase video, the branch https://github.com/axel7083/podman-desktop/tree/feature/storybook

https://github.com/containers/podman-desktop/assets/42176370/c34800c8-5ab3-4e17-954f-047c4b3b8554

ℹ️ There is not support for the theme, as we have a custom system which would require a bit of engineering on top of storybook.
