### ISSUE TITLE
remove tinro from ui component library

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#7235]
### Is your enhancement related to a problem? Please describe

Tab component brought the tinro component into the ui library

but the UI library should be agnostic on the routing system used by the framework.

### Describe the solution you'd like

Need to refactor the tab component and remove tinro from package.json

**Comment by lstocchi** [comment]
I was moving during the call so i didn't quite follow the discussion but what's the reasoning behind this?
For the tab the router is just used to verify if the url passed to the component is equals to the current path and it applies the style accordingly. If i have to pass the tab url + the current path it's kinda ugly imo. I expect that the component changes the style automatically without me specifying the current page i'm on.

**Comment by benoitf** [comment]
it's that you may use the component to display a Tab object but you don't use the tinro library to manage how the pages are displayed

**Comment by benoitf** [comment]
maybe there is a Tab in UI library to display something and the matching of style is done in some callbacks, helper library maintained by either a Podman Desktop Tab component (using tinro) or other ways
