### ISSUE TITLE
High file activity while running in background

### ISSUE THREAD

**Issue by schrej** [containers/podman-desktop#7237]
### Bug description

I've tested Podman Desktop on my work MacBook and noticed that it was indirectly causing a lot of CPU usage (see screenshot below). The culprit seems to be Microsoft Defender (🙄) which has on-access file scanning enabled. Whenever Podman Desktop is running, Defender is consuming a lot of CPU, leading me to the conclusion that Podman Desktop apparently is accessing a lot of files while running in background (or a few very large ones).

I'm aware the high CPU usage is not really the fault of Podman Desktop directly, but maybe the amount of files accessed while running in the background could be reduced.

### Operating system

macOS 14.4.1 (arm)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Additional context

<img width="237" alt="Screenshot 2024-05-16 at 16 46 06" src="https://github.com/containers/podman-desktop/assets/1710904/42dbd014-b2e2-4fce-af04-6e6d84f509db">

The green line indicates times Podman Desktop is running. The difference is roughly 10% CPU usage. It's enough that I don't want to run it in the background all the time.

**Comment by deboer-tim** [comment]
Do you have a Podman machine (or other provider) running? Could you check (Settings > Resources) and try temporarily stopping it? I just want to confirm if this is Podman Desktop directly vs something we're starting.

**Comment by jeffmaury** [comment]
Are you running Microsoft Defender on MacOS ?

**Comment by schrej** [comment]
> Do you have a Podman machine (or other provider) running?

It wasn't running when I took those screenshots. It didn't make a noticeable difference when I stopped it I think. I also have the kubernetes extension running.

> Are you running Microsoft Defender on MacOS ?

Yes. Not by choice 😄

**Comment by odockal** [comment]
Is it possible to add podman-desktop as an exception for the Microsoft Defender? I understand the obstacle here, but it could also be quite problematic to reduce the amount of the files being opened by podman-desktop.

@benoitf can we do something about it on our side?

**Comment by schrej** [comment]
I'm no longer observing this issue with the latest version (v1.11.1) of Podman Desktop. It should be some change to Desktop, since I was still observing the same resource usage with the old version (v1.10.2). I'll reopen in case this reappears.

**Comment by odockal** [comment]
@schrej Thanks for the update!

**Comment by piotrgwiazda** [comment]
I observe the same issue on Windows machine with Podman Desktop 1.18.0
