### ISSUE TITLE
Push/rename image dialogs not visible

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7247]
### Bug description

Something (looks like #7172) caused a regression on the Images screen. If you click the menu to push or edit an image, it doesn't appear. Looks like maybe relative position is placing it offscreen? It works from the image details screen.

### Operating system

MacOS 14.5

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Found a minor fix, as suspected MessageBox could handle arbitrary placement in the html but Modal only works if the parent is most of the screen. Fix overlaps with PR #7246 so I'll wait with PR a little.

**Comment by odockal** [comment]
The issue is still there as of podman desktop nightly (2024-05-27).

**Comment by deboer-tim** [comment]
Sorry, prior PR merged but I didn't get this up on Friday. PR #7303 up for review now.
