### ISSUE TITLE
Provide way to copy-and-paste YAML instead of from file

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#725]
### Is your enhancement related to a problem? Please describe

When playing Kubernetes YAML, it would be good to be able to copy-and-paste YAML rather than using it from a file. 

For example, when I create a pod from an online tutorial, or when I want to copy and paste from the "generate kube" page for containers, etc.

### Describe the solution you'd like

Copy-and-paste button or area when you want to play Kubernetes YAML.

**Comment by benoitf** [comment]
Podman Desktop will need to create temporary file as Podman Rest API is using a 'yaml' path rather than a 'yaml' content.

**Comment by cdrage** [comment]
Postponing this as we should get feedback on the UI first before implementation.

This was worked on via: https://github.com/cdrage/podman-desktop/tree/paste-yaml-kubernetes-play which opened up a few other issues that we should work on before proceeding.

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop/assets/6422176/35dfe33d-04f0-4a98-8d17-b2864f88f629

We should also get feedback on UI before proceeding.

**Comment by cdrage** [comment]
Going to unassign myself as well as give some context that we need to fix the following issues to implement this:
- [ ] https://github.com/containers/podman-desktop/issues/4434
- [ ] https://github.com/containers/podman-desktop/issues/4433
- [ ] https://github.com/containers/podman-desktop/issues/4432

**Comment by cdrage** [comment]
Not going to implement / you can apply via file instead.
