### ISSUE TITLE
Support ARG / passing in arguments for image building.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7250]
### Is your feature request related to a problem? Please describe

In my Containerfile I have the following:

```
FROM quay.io/centos-bootc/centos-bootc:stream9

# ARGUMENTS
ARG token
ARG sshpubkey
```

However.. I cannot using any form of argument / passing in arguments for Podman Desktop, I have to resort to using the CLI (ex: `podman build -t foobar --build-arg-file build-args.conf .`)

### Describe the solution you'd like

We should be able to pass in argument file (under advanced section maybe?) or a ARGS to the build image section of podman desktop.

**Comment by cdrage** [comment]
FYI created during "day of learning" while diving into container builds.

**Comment by evanstoner** [comment]
Red Hat partner looking for this feature to support bootc integration. CC: @rrbanda

**Comment by cdrage** [comment]
> Red Hat partner looking for this feature to support bootc integration. CC: @rrbanda

Hi Evan! I created a PR for this that should be merged in shortly: https://github.com/containers/podman-desktop/pull/7253

Let me know of any other features that can help make the bootc integration more seamless, I've been doing some back-and-forth between the extension & podman desktop to see where we can improve. Thanks!
