### ISSUE TITLE
Sections disappear when pressing "- / remove" in Create Container

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7252]
### Bug description

https://github.com/containers/podman-desktop/assets/6422176/0ca64113-83e5-4909-b96f-5e1d90420323

When pressing any of the minuses / - / remove buttons, the section disappears gone forever until you refresh the page. 

### Operating system

mac m1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

Press any of the "-" buttons on create container page.

**Comment by odockal** [comment]
The issue is not related to a specific OS. happens on all platforms. Switching pages (aka leaving Run Image page and going back) give user the option to add/remove fields again.

**Comment by cdrage** [comment]
![Screenshot 2024-06-13 at 3 49 25 PM](https://github.com/containers/podman-desktop/assets/6422176/f31d1c01-1181-47eb-af6d-112567ace177)

@benoitf I noticed in my video that "environment files" stays ontop while you are able to scroll the other forms.

Is it on purpose it is outside the div / does not scroll?
