### ISSUE TITLE
bug(ui): Button component cannot have spinner if icon is undefined

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7258]
### Bug description

https://github.com/containers/podman-desktop/blob/d6b22ba8ce44ec584c4150241fc0665c31707671/packages/ui/src/lib/button/Button.svelte#L76-L82

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

**Comment by deboer-tim** [comment]
As per PR comment, this is an intentional design choice.

**Comment by ekidneyrh** [comment]
I'm wondering if we could drop the text in the button completely when clicked and show just the spinner? Then there would be consistency across all the buttons, icon or not. Like this:

![image](https://github.com/containers/podman-desktop/assets/87311656/0a010141-837b-4e8d-b211-9c7427a8bbfb)


Could someone attach what the button looks like atm when loading? 

I do think feedback on the button is important only if the load time is greater than a second. I'm not sure if that's already the case here.

**Comment by axel7083** [comment]
> I'm wondering if we could drop the text in the button completely when clicked and show just the spinner? Then there would be consistency across all the buttons, icon or not. Like this:
> 
> ![image](https://private-user-images.githubusercontent.com/87311656/332761834-0a010141-837b-4e8d-b211-9c7427a8bbfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQ5OTIsIm5iZiI6MTcxNjM3NDY5MiwicGF0aCI6Ii84NzMxMTY1Ni8zMzI3NjE4MzQtMGEwMTAxNDEtODM3Yi00ZThkLWIyMTEtOWM3NDI3YThiYmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwNDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjA1ODE5NmExMmZhYmUxYjU2NWUxNWZkMjRmNDFkZjM5ZWIyYzdlNDg2YmY0MjVhMzFiMjA4NThmZTM1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BTwuu5yQYC5rXG_Y24PriehhsKiE0WLv2adBYJJ5IZ8)
> 
> Could someone attach what the button looks like atm when loading?
> 
> I do think feedback on the button is important only if the load time is greater than a second. I'm not sure if that's already the case here.

InProgress without icon defined

<img width="764" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/65dedc62-4e1e-411a-a65c-7952417990e0">

InProgress with icon defined

https://github.com/containers/podman-desktop/assets/42176370/0093fcdc-a4c9-46b4-88a0-0c5d8f7fc6ba


My personal opinion, is that we should have the same spinner, with the text, no matter if we defined an icon beforehand or not.

If we hide the text, the button will look like this

<img width="55" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/3259c88e-7f78-4f9f-abdb-75869a024b8a">


Because the width is dependent on the text. We cannot keep the size and hide the text without dirty hack.

**Comment by ekidneyrh** [comment]
ah okay I see! Thanks for the details. 

> My personal opinion, is that we should have the same spinner, with the text, no matter if we defined an icon beforehand or not.

I'm going to give this a +1. I agree that it's the best course of action for consistency.

**Comment by axel7083** [comment]
> I'm going to give this a +1. I agree that it's the best course of action for consistency.

I will be re-opening the closed pr thanks !
