### ISSUE TITLE
adding toast when tasks are created

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7269]
### Is your feature request related to a problem? Please describe

When we have a new task created (notification) we should have it showed up as a toast, to properly notify the user, something is happening  

### Describe the solution you'd like

<img width="348" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/641c4969-daa4-4a1a-8c53-93c927b107ad">

### Additional context

We are already using the https://github.com/zerodevx/svelte-toast library for some toaster item (rarely used)

https://github.com/containers/podman-desktop/assets/42176370/0aa0f4ff-c383-4a54-8aa5-716e96d8d4c5

We should probably extract the TaskItem component, and use it as custom toast[^1].

https://github.com/containers/podman-desktop/blob/cfeb27546799febf3383b236e5602bbcee204970/packages/renderer/src/lib/task-manager/TaskManagerGroup.svelte#L30

[^1]: https://github.com/zerodevx/svelte-toast?tab=readme-ov-file#send-svelte-component-as-a-message

**Comment by deboer-tim** [comment]
Personally, I would find this annoying. I would prefer we draw attention to the task manager (so the user knows where to look to get future task status) and have a constant indication/animation within the UI that there is a running task (e.g. on status bar).

**Comment by benoitf** [comment]
Discussed during the call, I like the toasts, also there are not so many tasks being created. And toasts can be time-based or required click. To me it does not prevent to draw attention to the task manager, but you don't want to click sometimes to the task manager, you just want to see something being created/in progress. Also it can disappear when it's done anyway

**Comment by axel7083** [comment]
cc @ekidneyrh for opinion

**Comment by ekidneyrh** [comment]
I think the toast is a good idea, I would have at the bottom of the screen however, so it makes to user look down near the task bar. I maybe wouldn't have it time based unless it's a very short message like 'file created!' etc. 

If the message is corresponding with an icon in the task bar, we could make the bubble come out of that icon to notify the user they are related, then they know to keep an eye there for further progress? 

Would there be a set amount of use cases for this? like start, error, done etc

**Comment by axel7083** [comment]
Closing as duplicates of https://github.com/containers/podman-desktop/issues/7399
