### ISSUE TITLE
For NavBar, should be Containers, then Pods, then Images

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#728]
### Is your enhancement related to a problem? Please describe

<img width="461" alt="Screen Shot 2022-10-28 at 10 12 48 AM" src="https://user-images.githubusercontent.com/6422176/198638011-5572fbb6-b025-4790-baba-ae5b10f4c5f6.png">

It's Containers => Images => Pods when from a user experience, it should be Containers => Pods => Images.

### Describe the solution you'd like

For the navbar, it makes sense that we have:

Containers (single box icon)
Pods (multiple box icon)
THEN
Images

Eventually it could possibly be:

Containers
Pods
Kubernetes
Images

From a user experience perspective, it makes sense having Images after Pods and Containers as it's more of a "background" task similar to volumes.

**Comment by benoitf** [comment]
Hi, it looks like a lot of people have different views on this topic.
Maybe it could be possible to re-order in the preferences as well.
I would slow down on the merge
