### ISSUE TITLE
Be able to set a custom theme for Podman Desktop

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7282]
### Is your feature request related to a problem? Please describe

After light mode is implemented, in theory, all the colours will be defined in an external file. 

I'd like to be able to add "custom colours" and design my own theme.

### Describe the solution you'd like

Be able to provide my own colours to override the dark / light themed colours.

**Comment by benoitf** [comment]
it's already done by https://github.com/containers/podman-desktop/issues/5914

the system is in place, just that we're missing colors

**Comment by deboer-tim** [comment]
We've done almost all the UI so there has been very little change to variables lately, and should all be available for external contribution. Can we close this now?

**Comment by cdrage** [comment]
👍 on closing this, you can modify this with color registry, etc in order to provide a custom theme.
