### ISSUE TITLE
Icon for Manifests 

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#7287]
### Is your enhancement related to a problem? Please describe

As requested in https://github.com/containers/podman-desktop/pull/7227 and at Tuesday's UX call, we need an icon for manifests on the image screen. 

Partially related to https://github.com/containers/podman-desktop/issues/6526 also.

### Describe the solution you'd like

Create an icon like we have for images

**Comment by ekidneyrh** [comment]
hi @cdrage, I'm wondering if we could use the bootable container image icon but have a cog instead of the power on symbol? Like this: 

![manifest-idea-icon](https://github.com/containers/podman-desktop/assets/87311656/3167a046-e960-4908-a14b-d4a45ca4eae8)

I hope I got the understanding of manifests right. I know there's manifest lists also.

**Comment by deboer-tim** [comment]
I think that's the right approach, but the cog doesn't trigger anything for me. A manifest is a list of related images, a parent/grouping mechanism. Maybe multiple image icons in a stack, or something other than a cog to represent the grouping? (e.g. a folder is probably wrong, but that's the kind of thing)

**Comment by ekidneyrh** [comment]
> I think that's the right approach, but the cog doesn't trigger anything for me. A manifest is a list of related images, a parent/grouping mechanism. Maybe multiple image icons in a stack, or something other than a cog to represent the grouping? (e.g. a folder is probably wrong, but that's the kind of thing)

ok I get you! I initially thought that's what manifest meant, but when I looked more into it, I got it confused with a manifest image :/

**Comment by cdrage** [comment]
> hi @cdrage, I'm wondering if we could use the bootable container image icon but have a cog instead of the power on symbol? Like this:
> 
> ![manifest-idea-icon](https://private-user-images.githubusercontent.com/87311656/334089385-3167a046-e960-4908-a14b-d4a45ca4eae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTM4OTQsIm5iZiI6MTcxNjgxMzU5NCwicGF0aCI6Ii84NzMxMTY1Ni8zMzQwODkzODUtMzE2N2EwNDYtZTk2MC00OTA4LWExNGItZDRhNDVjYTRlYWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzFjNDIwNjhlOGQzYTAyMDBhYTUyZWNhMzgyNTI4N2ZmZjg0M2Q3ZjU1ODAwNTQ0OWM4YjlkYzY3ZTgzZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0rF-JIqG6dF90bOimcvMXFbfUrIQz34Zsqwn5yfyVcI)
> 
> I hope I got the understanding of manifests right. I know there's manifest lists also.

Agreed with @deboer-tim 's points :) no cog, but multiple images in a stack works.

**Comment by ekidneyrh** [comment]
Okay, so something like this? Just stacking the container image icon on itself 

![image](https://github.com/containers/podman-desktop/assets/87311656/7efa04bb-d8a6-4f30-a625-5ba8755bb521)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/33160c65-9ceb-4c01-b0d5-2668381d9058)

**Comment by cdrage** [comment]
> ![image](https://private-user-images.githubusercontent.com/87311656/334744428-33160c65-9ceb-4c01-b0d5-2668381d9058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODY2OTgsIm5iZiI6MTcxNjk4NjM5OCwicGF0aCI6Ii84NzMxMTY1Ni8zMzQ3NDQ0MjgtMzMxNjBjNjUtOWNlYi00YzAxLWIwZDUtMjY2ODM4MWQ5MDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEyMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmNlZGMxYWI1Y2I0NGE3NzIyNGE4ZDQxY2YwODg3NmI2OGY3NWQ4YjIyYTgxYjU4OTZiYTU0Zjg0OGQ5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XU2N-jbJaX9l8tPLB1xEor2yOy3d9bWCAdO_QV-fTJo)

Looks great! Thank you!

**Comment by ekidneyrh** [comment]
![manifest](https://github.com/containers/podman-desktop/assets/87311656/7f89ce41-a641-450f-9a94-9e01e4fa8f0f)
![filled-manifest](https://github.com/containers/podman-desktop/assets/87311656/f2bd2145-22c6-4a03-8e12-cf9ab551650a)

Here's the icon files! Here's also a zip in case:

[manifest-icons.zip](https://github.com/containers/podman-desktop/files/15485497/manifest-icons.zip)

**Comment by deboer-tim** [comment]
Manifest icon up for review via PR #7366.

**Comment by ekidneyrh** [comment]
Closing as icon has been implemented
