### ISSUE TITLE
Spike at integrating libkrun

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#7296]
### Is your feature request related to a problem? Please describe

We would like to explore the possibility of integrating https://github.com/containers/libkrun with podman desktop since it's been integrated in podman: https://github.com/containers/podman/pull/22491 and would enable user to benefit from GPU acceleration on mac - for certain use cases.

### Describe the solution you'd like

An initial spike should be able providing the ability to the end-user to start a podman-machine with libkrun.

Along with the spike, we would like to identify the different needs/requirements to make the experience completely seamless: for example a developer, could start with a regular "podman machine", leveraging AppleHV, have applications component running in that environment, and then willing to extend to certain workloads which could require GPU acceleration (like running a model locally)

- [x] #8084

**Comment by cdrage** [comment]
We now have this integrated https://github.com/containers/podman-desktop/issues/8084 as well as GPU documentation regarding the libkrun feature, I believe we can close now? https://podman-desktop.io/docs/podman/gpu
