### ISSUE TITLE
Enhance download page with info about package managers for Windows

### ISSUE THREAD

**Issue by rsvoboda** [containers/podman-desktop#733]
### Is your enhancement related to a problem? Please describe

https://podman-desktop.io/downloads provides hints about package managers for Linux and macOS

Such info is not available in the section for Windows.

https://podman-desktop.io/docs/Installation/windows-install covers choco, winget, and scoop. 

### Describe the solution you'd like

https://podman-desktop.io/downloads could link https://podman-desktop.io/docs/Installation/windows-install

Something like
```
    Using package managers?
Check the Windows Install guide.
```

<img width="1488" alt="Screenshot 2022-10-28 at 21 11 38" src="https://user-images.githubusercontent.com/925259/198715724-5fc865f6-4f21-4f20-b2d2-936ff90cce28.png">

**Comment by benoitf** [comment]
yes we should add a note there for Windows as well 
Are you interested to provide a Pull Request ?

**Comment by rsvoboda** [comment]
I can try :) https://github.com/containers/podman-desktop/blob/gh-pages is used, source is in https://github.com/containers/podman-desktop/tree/main/website

is the proposed text OK-ish? Or do you have something concrete in mind?

There could be `choco` command to be a bit in sync with macOS and Linux way.

**Comment by benoitf** [comment]
@rsvoboda yes it's published on GitHub pages and source is coming from `website` directory.


Text is ok but maybe it's better to highlight one as you suggested in your comments as well. I would pickup winget as it's backed by Microsoft. 
For Choco, the package moderation is taking a huge time so we're not able yet to have latest releases published in a timely manner

**Comment by rsvoboda** [comment]
PR, created
