### ISSUE TITLE
Updating the Podman on the podman dashboard using the provider card has still broken layout

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7335]
### Bug description

We start podman desktop and get to this screen:
![Screenshot_20240528_163343](https://github.com/containers/podman-desktop/assets/19164299/2b77178b-1bdd-4c79-82c6-6e68efb95a38)

Which seems alright, then we click on update button:
![Screenshot_20240528_163407](https://github.com/containers/podman-desktop/assets/19164299/b0383bf4-dec6-4de0-b751-eade26e3ba7e)

Then once the podman is updated, it got back to a normal shape:
![Screenshot_20240528_163622](https://github.com/containers/podman-desktop/assets/19164299/1f088411-ebee-44fe-a76b-79c8ad6b363f)

### Operating system

Mac OS 14, Intel

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

**Comment by lstocchi** [comment]
Looking at the image makes me think the change made in https://github.com/containers/podman-desktop/pull/7082 has not been released yet
The position of the update button has been modified and now it is below the provider name but in the image it is on the right
![image](https://github.com/containers/podman-desktop/assets/49404737/f50d7ca0-7296-4c70-ac94-b65317e28108)

**Comment by lstocchi** [comment]
Ah yes, #7082 is in milestone 1.11, so this is probably fixed.

**Comment by nichjones1** [comment]
@odockal can you verify this is resolved in 1.11.  If so please close this issue

**Comment by odockal** [comment]
@lstocchi @nichjones1 verified. It was truly fixed. Thanks!
