### ISSUE TITLE
rosetta: Check performance between qemu and rosetta for the 

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#7340]
### Is your enhancement related to a problem? Please describe

podman 5.1 should come with rosetta support for emulating other arch

like building AMD64 image on a mac using ARM64.

### Describe the solution you'd like

check the time of a podman build using the two approaches

**Comment by cdrage** [comment]
I compiled the Linux kernel in order to benchmark the tests. 

The containerfile is located here: https://github.com/cdrage/containerfiles/tree/master/compile-test

I used a blank podman machine / no other containers or loads running other than building the container.


With rosetta enabled (rosetta=true in config settings and a podman machine restart:)
```
podman build --no-cache --platform linux/amd64 -D -t foobar .  1.01s user 1.97s system 0% cpu 12:32.15 total
```

**12 minutes, 32 seconds**

With rosetta disabled / no config setting:
```
podman build --no-cache --platform linux/amd64 -D -t foobar .  1.02s user 2.04s system 0% cpu 13:01.20 total
```

**13 minutes, 1 second**

I noticed this consistently (only a few seconds speed up), across all my containerfiles, even small ones such as https://github.com/cdrage/containerfiles/tree/master/bootc-fedora-httpd

**It's about a 3-5% speedup.**

Although I DID however notice there is less freezing / stuttering. Long builds I had to ctrl+c / cancel and then restart. I've noticed in the few hours of testing I have yet to freeze when building an amd64 image.

**Comment by benoitf** [comment]
@cdrage using podman 5.1.0 ?

**Comment by cdrage** [comment]
> @cdrage using podman 5.1.0 ?

Yup, from the releases (https://github.com/containers/podman/releases/tag/v5.1.0)

```
▶ podman version
Client:       Podman Engine
Version:      5.1.0
API Version:  5.1.0
Go Version:   go1.22.3
Git Commit:   4e9486dbc63c24bfe109066abbb54d5d8dc2489e
Built:        Wed May 29 16:27:58 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.1.0-dev-c9808e7ed
API Version:  5.1.0-dev-c9808e7ed
Go Version:   go1.22.2
Built:        Sun May 12 20:00:00 2024
OS/Arch:      linux/arm64
```

And rosetta confirmed to be enabled:
```
▶ podman machine inspect
[
     {
          "ConfigDir": {
               "Path": "/Users/cdrage/.config/containers/podman/machine/applehv"
          },
          "ConnectionInfo": {
               "PodmanSocket": {
                    "Path": "/var/folders/cn/pm5mgrcs5h339nphypxtvd080000gn/T/podman/podman-machine-default-api.sock"
               },
               "PodmanPipe": null
          },
          "Created": "2024-06-03T11:31:55.520949-04:00",
          "LastUp": "2024-06-03T11:33:54.045352-04:00",
          "Name": "podman-machine-default",
          "Resources": {
               "CPUs": 5,
               "DiskSize": 93,
               "Memory": 19073,
               "USBs": []
          },
          "SSHConfig": {
               "IdentityPath": "/Users/cdrage/.local/share/containers/podman/machine/machine",
               "Port": 63487,
               "RemoteUsername": "core"
          },
          "State": "running",
          "UserModeNetworking": true,
          "Rootful": true,
          "Rosetta": true
     }
]


▶ cat ~/.config/containers/containers.conf

[containers]

[engine]

env = [
]

[machine]
rosetta=true

[network]

[secrets]

[configmaps]
```

**Comment by cdrage** [comment]
> @cdrage using podman 5.1.0 ?

I'm going to try again by enabling the rosetta option and then removing the podman machine, and recreating a new one, rather than stop / start.

I noticed in the release notes it says: **VMs created by podman machine on macOS with Apple silicon can now use Rosetta 2 (a.k.a Rosetta) for high-speed emulation of x86 code.** (https://github.com/containers/podman/releases/tag/v5.1.0) and I cannot find any more information even in the man docs: https://github.com/containers/common/blob/ed2a5b62597ce1c35d939945c787658a3679e2f8/docs/containers.conf.5.md?plain=1#L957-L960

I'm unsure if you actually have to delete and re-create, or just start / stop (cannot find any documentation on that).


EDIT: 

No difference, this time it was 13 minutes 57 seconds with rosetta enabled, so no difference in build time enabling or disabling:
```sh
podman build --no-cache --platform linux/amd64 -D -t foobar .  1.03s user 1.98s system 0% cpu 13:57.74 total
```


Confirmed rosetta is enabled too:

```
podman machine inspect
[
     {
          "ConfigDir": {
               "Path": "/Users/cdrage/.config/containers/podman/machine/applehv"
          },
          "ConnectionInfo": {
               "PodmanSocket": {
                    "Path": "/var/folders/cn/pm5mgrcs5h339nphypxtvd080000gn/T/podman/podman-machine-default-api.sock"
               },
               "PodmanPipe": null
          },
          "Created": "2024-06-03T11:44:14.951383-04:00",
          "LastUp": "0001-01-01T00:00:00Z",
          "Name": "podman-machine-default",
          "Resources": {
               "CPUs": 5,
               "DiskSize": 100,
               "Memory": 2048,
               "USBs": []
          },
          "SSHConfig": {
               "IdentityPath": "/Users/cdrage/.local/share/containers/podman/machine/machine",
               "Port": 64258,
               "RemoteUsername": "core"
          },
          "State": "running",
          "UserModeNetworking": true,
          "Rootful": false,
          "Rosetta": true
     }
]
```

**Comment by tnk4on** [comment]
Podman machine v5.1([podman/machine-os](https://quay.io/repository/podman/machine-os)) is required to use Rosetta. 
From your information it looks like it has already been updated to v5.1.

> Server:       Podman Engine
> Version:      5.1.0-dev-c9808e7ed
> API Version:  5.1.0-dev-c9808e7ed
> Go Version:   go1.22.2
> Built:        Sun May 12 20:00:00 2024
> OS/Arch:      linux/arm64

**Comment by cdrage** [comment]
> Podman machine v5.1([podman/machine-os](https://quay.io/repository/podman/machine-os)) is required to use Rosetta. From your information it looks like it has already been updated to v5.1.
> 
> > Server:       Podman Engine
> > Version:      5.1.0-dev-c9808e7ed
> > API Version:  5.1.0-dev-c9808e7ed
> > Go Version:   go1.22.2
> > Built:        Sun May 12 20:00:00 2024
> > OS/Arch:      linux/arm64

 I'm getting `5.1.0-dev-c9808e7ed` when doing `podman machine init` while I am on the 5.1.0 release.

Although I am not noticing any speedups @tnk4on to be honest when disabling or enabling.

Am I using the correct podman machine image with rosetta support?

**Comment by tnk4on** [comment]
>  Is that the correct image?

 Yes, it is the same as mine.

 Below are the results of a simple benchmark of `sysbench cpu run`. As you can see, CPU performance is faster.
```
# arm64 container
General statistics:
    total time:                          10.0002s
    total number of events:              84075
    
# amd64 container with Rosetta
General statistics:
    total time:                          10.0006s
    total number of events:              72425

# amd64 container with qemu-user-static
General statistics:
    total time:                          10.0037s
    total number of events:              3237
```

**Comment by tnk4on** [comment]
@cdrage  I tested it using [your repository](https://github.com/cdrage/containerfiles/tree/master/compile-test).
- M2 Air: 8core(p4+e4)/24GB
- Podman machine: 4 CPU/ 10 GB RAM
- build command: `time podman build --no-cache --platform linux/amd64 -D -t foobar . `

Rosetta
```
real	15m39.832s
user	46m16.951s
sys	3m57.206s
```

QEMU
```
STEP 7/9: RUN make defconfig     && sed -i 's/CONFIG_DEBUG_KERNEL=y/CONFIG_DEBUG_KERNEL=n/' .config     && sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=n/' .config
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
make[1]: *** [scripts/Makefile.host:9: scripts/kconfig/lexer.lex.c] Error 141
make[1]: *** Deleting file 'scripts/kconfig/lexer.lex.c'
make: *** [Makefile:602: defconfig] Error 2
Error: building at STEP "RUN make defconfig     && sed -i 's/CONFIG_DEBUG_KERNEL=y/CONFIG_DEBUG_KERNEL=n/' .config     && sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=n/' .config": while running runtime: exit status 2

real	2m9.574s
user	1m47.557s
sys	0m17.846s
```

Using QEMU results in an error.
Did you use `rosetta=false`? Rosetta defaults to `true`.
```
rosetta="true"

Rosetta supports running x86_64 Linux binaries on a Podman machine on Apple silicon. The default value is true. Supported on AppleHV(arm64) machines only.
```
https://github.com/containers/common/blob/main/docs/containers.conf.5.md

**Comment by cdrage** [comment]
> @cdrage I tested it using [your repository](https://github.com/cdrage/containerfiles/tree/master/compile-test).
> 
> * M2 Air: 8core(p4+e4)/24GB
> * Podman machine: 4 CPU/ 10 GB RAM
> * build command: `time podman build --no-cache --platform linux/amd64 -D -t foobar . `
> 
> Rosetta
> 
> ```
> real	15m39.832s
> user	46m16.951s
> sys	3m57.206s
> ```
> 
> QEMU
> 
> ```
> STEP 7/9: RUN make defconfig     && sed -i 's/CONFIG_DEBUG_KERNEL=y/CONFIG_DEBUG_KERNEL=n/' .config     && sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=n/' .config
>   HOSTCC  scripts/basic/fixdep
>   HOSTCC  scripts/kconfig/conf.o
>   HOSTCC  scripts/kconfig/confdata.o
>   HOSTCC  scripts/kconfig/expr.o
>   LEX     scripts/kconfig/lexer.lex.c
> qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
> make[1]: *** [scripts/Makefile.host:9: scripts/kconfig/lexer.lex.c] Error 141
> make[1]: *** Deleting file 'scripts/kconfig/lexer.lex.c'
> make: *** [Makefile:602: defconfig] Error 2
> Error: building at STEP "RUN make defconfig     && sed -i 's/CONFIG_DEBUG_KERNEL=y/CONFIG_DEBUG_KERNEL=n/' .config     && sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=n/' .config": while running runtime: exit status 2
> 
> real	2m9.574s
> user	1m47.557s
> sys	0m17.846s
> ```
> 
> Using QEMU results in an error. Did you use `rosetta=false`? Rosetta defaults to `true`.
> 
> ```
> rosetta="true"
> 
> Rosetta supports running x86_64 Linux binaries on a Podman machine on Apple silicon. The default value is true. Supported on AppleHV(arm64) machines only.
> ```
> 
> https://github.com/containers/common/blob/main/docs/containers.conf.5.md


After doing a `podman machine reset` I was able to do the same results as you.

You are completely right, I can confirm now that it does not build when rosetta is set to false, which is normal (qemu static bug at the moment... so completely unable to try at the moment)..

We can use your CPU analysis / more actions taken as a benchmark for when we do the release / blog post? Since using `podman build`'s would not be beneficial. WDYT @benoitf 

Thanks for troubleshooting with me!

**Comment by benoitf** [comment]
I think qemu is slow with yarn project so might be interesting to see a 'yarn install' command with a small package.json file / js project

**Comment by cdrage** [comment]
> > Is that the correct image?
> 
> Yes, it is the same as mine.
> 
> Below are the results of a simple benchmark of `sysbench cpu run`. As you can see, CPU performance is faster.
> 
> ```
> # arm64 container
> General statistics:
>     total time:                          10.0002s
>     total number of events:              84075
>     
> # amd64 container with Rosetta
> General statistics:
>     total time:                          10.0006s
>     total number of events:              72425
> 
> # amd64 container with qemu-user-static
> General statistics:
>     total time:                          10.0037s
>     total number of events:              3237
> ```

To close off this issue. I am getting similar percentage difference as you in this benchmark.

I believe we can say it is a **2,142%** speed increase?

Or we could also say that with Rosetta, amd64 binaries are as fast as native ARM ones.

**Comment by tnk4on** [comment]
> To close off this issue. I am getting similar percentage difference as you in this benchmark.
>
>I believe we can say it is a 2,142% speed increase?
>
>Or we could also say that with Rosetta, amd64 binaries are as fast as native ARM ones.

Sure, that's correct based on the benchmark numbers.

However, it's unclear whether this will translate to a noticeable performance improvement in real-world usage. When presenting these figures publicly, it's important to exercise caution.

In particular, for I/O transactions, the performance gains are smaller compared to CPU improvements. While there are positive results in terms of package updates and installations during builds, quantifying this improvement can be challenging.

**Comment by cdrage** [comment]
> > To close off this issue. I am getting similar percentage difference as you in this benchmark.
> > I believe we can say it is a 2,142% speed increase?
> > Or we could also say that with Rosetta, amd64 binaries are as fast as native ARM ones.
> 
> Sure, that's correct based on the benchmark numbers.
> 
> However, it's unclear whether this will translate to a noticeable performance improvement in real-world usage. When presenting these figures publicly, it's important to exercise caution.
> 
> In particular, for I/O transactions, the performance gains are smaller compared to CPU improvements. While there are positive results in terms of package updates and installations during builds, quantifying this improvement can be challenging.

You are right, what we could possibly say is "near-native-speeds"? Or something similar to that?

Giving a percentage / exact numbers would probably start debates / comparisons, haha.

**Comment by cdrage** [comment]
I am making this as done as we could be saying "near native speed" and in this issue I believe we have gathered enough information for benchmarking.
