### ISSUE TITLE
Docker Socket Compatibility  not work 

### ISSUE THREAD

**Issue by linkoog** [containers/podman-desktop#7354]
### Bug description

error:    dockerSock does not point to the expected target:  ~/.docker/run/docker.sock
the real file location is   /var/run/docker.sock 

### Operating system

macOS Ventura 13.4 (Arm)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

**Comment by nichjones1** [comment]
Closed as this is a duplicate of 
https://github.com/containers/podman-desktop/issues/2630
