### ISSUE TITLE
Readme disappears form catalog after extension is installed

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#7363]
### Bug description

For some extensions (Sandbox for example) Readme content disappears after installation.

### Operating system

macOS M1 Sonoma 14.5

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

https://github.com/containers/podman-desktop/assets/620330/91930525-a062-49e3-9631-824d62b00f47

### Relevant log output

```shell
N/A
```

### Additional context

N/A

**Comment by benoitf** [comment]
fixed in the catalog PR check and in sandbox extension
