### ISSUE TITLE
Add Rosetta settings for Apple Silicon Mac

### ISSUE THREAD

**Issue by tnk4on** [containers/podman-desktop#7367]
### Is your enhancement related to a problem? Please describe

Rosetta support has been added in [Podman v5.1.0](https://github.com/containers/podman/releases/tag/v5.1.0).
Rosetta is enabled by default on Apple Silicon Mac Podman machines.
To disable this Rosetta and instead enable the traditional qemu-user-static-x86_64, add `rosetta=false` to containers.conf.

This RFE allows you to enable/disable the rosetta feature via GUI.

### Describe the solution you'd like

![Screenshot 2024-05-30 at 9 39 50](https://github.com/containers/podman-desktop/assets/54387703/43c6352f-873f-47c4-a859-de638dd732f0)

https://github.com/containers/common/blob/ed2a5b62597ce1c35d939945c787658a3679e2f8/docs/containers.conf.5.md?plain=1#L957-L960

### Additional context

Rosetta configuration for Docker Desktop
<img width="1235" alt="docker_rosetta" src="https://github.com/containers/podman-desktop/assets/54387703/65058fd8-34ad-478b-9804-79f090b58ca5">

**Comment by cdrage** [comment]
FYI so I do not forget, must add in description that the VM being **re-recreated** is required. You cannot just restart it.
