### ISSUE TITLE
feat: update to podman v5.1.1

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7373]
### Is your enhancement related to a problem? Please describe

New version of podman is available https://github.com/containers/podman/releases/tag/v5.1.1

### Describe the solution you'd like

update to the next release of podman

**Comment by dgolovin** [comment]
Blocked by https://github.com/containers/podman/issues/22887

**Comment by dgolovin** [comment]
https://github.com/containers/podman/issues/22887 seems to be resolved.

**Comment by dgolovin** [comment]
Fixed via https://github.com/containers/podman-desktop/pull/7433
