### ISSUE TITLE
Icon for Nodes section

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#7378]
### Is your enhancement related to a problem? Please describe

Following up from https://github.com/containers/podman-desktop/pull/7347:

> We will need a new icon for the nodes section before merging. Right now it is using the "DeploymentIcon".
> 
> From a quick google, Kubernetes uses the "three gears together" to signify a node / control plane.
> 
> ![image](https://github.com/containers/podman-desktop/assets/87311656/3b5cad39-07f8-4229-b1db-80dc8f703568)

### Describe the solution you'd like

Create an icon for Nodes section

### Additional context

This is an icon for the Nav bar.

**Comment by ekidneyrh** [comment]
I can't recall if there's an icon like this already within PD. I looked through what I could, so I believe it's not been used yet. It seems like the most recognisable icon that's used to represent nodes.

SVGs:
![nodes-filled](https://github.com/containers/podman-desktop/assets/87311656/22310b9c-fd2c-48ad-8c85-12c6516d8829)
![nodes](https://github.com/containers/podman-desktop/assets/87311656/ae30d3ec-31f4-4200-926e-bd8ae37fabd1)

nodes:
![nodes](https://github.com/containers/podman-desktop/assets/87311656/60ca6be5-34e2-4914-95b8-47f0e234c91a)
nodes-filled:
![nodes-filled](https://github.com/containers/podman-desktop/assets/87311656/dcb60bd9-3a0f-48e5-90aa-330d53bea1a6)

**Comment by cdrage** [comment]
> I can't recall if there's an icon like this already within PD. I looked through what I could, so I believe it's not been used yet. It seems like the most recognisable icon that's used to represent nodes.
> 
> SVGs: ![nodes-filled](https://private-user-images.githubusercontent.com/87311656/339716501-22310b9c-fd2c-48ad-8c85-12c6516d8829.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTksIm5iZiI6MTcxODY0Nzg1OSwicGF0aCI6Ii84NzMxMTY1Ni8zMzk3MTY1MDEtMjIzMTBiOWMtZmQyYy00OGFkLThjODUtMTJjNjUxNmQ4ODI5LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZWUyNzgzOGQyMDJhODlhZjNkNjJjZjZjNzc3NmUzNGMzODYwOTM3OTQ4YWY4ZTg3MTFlYTdmZjE5MmQyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTmaZsOLhuT3Nr9qouIvr_Q7-VTRE2shiwK7XCqLnhc) ![nodes](https://private-user-images.githubusercontent.com/87311656/339716506-ae30d3ec-31f4-4200-926e-bd8ae37fabd1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTksIm5iZiI6MTcxODY0Nzg1OSwicGF0aCI6Ii84NzMxMTY1Ni8zMzk3MTY1MDYtYWUzMGQzZWMtMzFmNC00MjAwLTkyNmUtYmQ4YWUzN2ZhYmQxLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDBjMzk5OTMyMjNiZTNkYmYyMTViMDA5YWZkNWIxZTk5MDgzZTgxMmQwYjZiZjNjNWFiNzM0YWIwYTdlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgmOaFUv5fVs92_D0qeB1TKJ4KsOXdCgcVOo_FvX_WA)
> 
> nodes: ![nodes](https://private-user-images.githubusercontent.com/87311656/339716547-60ca6be5-34e2-4914-95b8-47f0e234c91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTksIm5iZiI6MTcxODY0Nzg1OSwicGF0aCI6Ii84NzMxMTY1Ni8zMzk3MTY1NDctNjBjYTZiZTUtMzRlMi00OTE0LTk1YjgtNDdmMGUyMzRjOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NWNlZmVjNGFiODZkOWE4YWEyNzQ5NzZjYTdhNjIyZGFmOThlYzU4NmFkMTE5ZGJmNTA3ZWRmYmI0YjEzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GZ0wMX-aNVs6aDZsze3FQQzqW7kkwWPwesrhcpipa2c) nodes-filled: ![nodes-filled](https://private-user-images.githubusercontent.com/87311656/339716552-dcb60bd9-3a0f-48e5-90aa-330d53bea1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTksIm5iZiI6MTcxODY0Nzg1OSwicGF0aCI6Ii84NzMxMTY1Ni8zMzk3MTY1NTItZGNiNjBiZDktM2EwZi00OGU1LTkwYWEtMzMwZDUzYmVhMWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlY2ZjZjBlYTYwYzg5MWFkYmJkNGM5NGYzZDBiZmQwZGQ1YWZhYWU1MjE0ZjdjNWRhZDFjY2VlMmE2OTY3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sB2OGghk2ga4a2fhRulJrD9GXF6-ejL77x82xBzW1xo)

I like this and it fits the overall theme, makes it different than the other "node" icons. We have a theme recurring with regards to "link tree" looking icons, so I'm good with this unless someone else has suggestions.

**Comment by deboer-tim** [comment]
LGTM, I put a PR up (#7679).
