### ISSUE TITLE
Website: Update to site with regards to container clusters

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#738]
### Is your enhancement related to a problem? Please describe

Too much focus on OpenShift support, need to focus on Kubernetes and listing alternative container clusters such as k3s, rancher, kubernetes, etc.

### Describe the solution you'd like

Proposing changes to the site:

- [x] Update main README with screenshot similar to the first image on the "Features" tab. However, have list of plugins in the screenshot too. 
- [x] Move mentions of OpenShift to alternative tab (Extend maybe?)
- [x] Increase mention of Kubernetes 
- [ ] Add list of plugins that work (Trivy, OpenShift, etc.)
- [ ] Add list of container clusters / container engines we support (list openshift, k8s maybe k3s if we support it, kind, etc. as well as podman, lima, etc).

**Comment by themr0c** [comment]
I can work on it

**Comment by themr0c** [comment]
Can you provide me the 2 lists to add? (or a link where I can find the information)

**Comment by themr0c** [comment]
Container engines list proposal:
* Podman
* Docker
* Lima
* Kubernetes (and OpenShift as a variant)
* OpenShift with the Podman preset (we can ignore it from the list)

**Comment by themr0c** [comment]
Docker Desktop Extensions https://hub.docker.com/search?q=&type=extension, such as:
* Trivy
* OpenShift

**Comment by themr0c** [comment]
We need a reference list in the docs too I believe.
