### ISSUE TITLE
Dropdown menu hidden in tables

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7382]
### Bug description

PR #7313 uses a new div with overflow-hidden to contain parent and child table rows with rounded corners. Unfortunately this causes a regression several divs down where drop-down menus are now also hidden within the new div. 

<img width="451" alt="Screenshot 2024-05-30 at 8 13 06 AM" src="https://github.com/containers/podman-desktop/assets/19958075/8c1230dc-e3d9-47dd-98f0-68826e31bcfb">

We need to find another way to get the intended design without using overflow-hidden.

### Operating system

MacOS 14.5

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
I don't know if https://github.com/containers/podman-desktop/issues/7321 is related

**Comment by deboer-tim** [comment]
Tracked it back enough to confirm #7321 is not related, fix up for this one.
