### ISSUE TITLE
Wrong icon for ingress and routes

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7395]
### Bug description

![Screenshot 2024-05-30 at 4 53 59 PM](https://github.com/containers/podman-desktop/assets/6422176/88ad72ab-1509-42bf-adb9-dcaaa96fd020)

Uses the wrong icon

### Operating system

mac m1

### Installation Method

None

### Version

1.10.2

**Comment by odockal** [comment]
@cdrage We were going though the bugs and I see you have assigned yourself to the issue, I have added next sprint, hope it is fine, feel free to update anything to be the way you want.

**Comment by cdrage** [comment]
> @cdrage We were going though the bugs and I see you have assigned yourself to the issue, I have added next sprint, hope it is fine, feel free to update anything to be the way you want.

No problem!
