### ISSUE TITLE
Merge all tasks management in main package

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7396]
### Is your enhancement related to a problem? Please describe

Currently, tasks can be created or updated both at the API/main level and within the renderer (see tasks store). This means that things in the main package (e.g. the status bar) can't tell if there are tasks / state doesn't match up with what's shown in the UI. e.g. if the status bar changed when there was a running task, it would only work for certain tasks.

### Describe the solution you'd like

All tasks should be created/managed from main, and renderer only handles the UI. Any function related to creating/managing tasks or updating status should either be removed or delegate to API in main.

**Comment by axel7083** [comment]
Solution proposal https://github.com/containers/podman-desktop/issues/7401#issuecomment-2208497615

**Comment by axel7083** [comment]
List of tasks created on the `renderer` side

### `ContainerExport`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/container/ContainerExport.svelte#L73

### `ImportContainersImages`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/image/ImportContainersImages.svelte#L83

### `LoadImages`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/image/LoadImages.svelte#L63

### `SaveImages`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/image/SaveImages.svelte#L100

### `build-image-task`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/image/build-image-task.ts#L68

### :warning:  `preferences-connection-rendering-task`

https://github.com/containers/podman-desktop/blob/12077341a37b27f8749912e1353ec611e750891a/packages/renderer/src/lib/preferences/preferences-connection-rendering-task.ts#L70

This one has some particularity as it is divided in several elements, and is kinda an utility method serving for others

#### `cli-tool-registry:updateCliTool`

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesCliTool.svelte#L25-L29

#### `provider-registry:stopProviderConnectionLifecycle`

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte#L61-L65

#### `startProviderConnectionLifecycle`

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte#L37-L41

#### `deleteProviderConnectionLifecycle`

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte#L122

#### `editProviderConnectionLifecycle`

:warning: this one is also particular, as it provide a callback to the `packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte` file.

https://github.com/containers/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/renderer/src/lib/preferences/PreferencesContainerConnectionEdit.svelte#L52

#### `createContainerProviderConnection`

Same as the `editProviderConnectionLifecycle` 

https://github.com/containers/podman-desktop/blob/dbd7b01ac751fb41e5692bf038aeac207d17c685/packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte#L146

#### `createKubernetesProviderConnection`

Same as `editProviderConnectionLifecycle`

https://github.com/containers/podman-desktop/blob/dbd7b01ac751fb41e5692bf038aeac207d17c685/packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte#L157

**Comment by axel7083** [comment]
Not fixed yet
