### ISSUE TITLE
New task toast notification

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7399]
### Is your enhancement related to a problem? Please describe

When a task is created the status bar task icon adds a notification dot, but if you haven't clicked on it the second created task doesn't do anything. It's not very visible to the user that 'something is now running in the background'.

### Describe the solution you'd like

When a task is created there should be a toast popup at the lower right. We'll need design input on what it looks like and to decide if it stays up until the user closes it/task finishes or just for a few seconds.

**Comment by axel7083** [comment]
Might need to wait for https://github.com/containers/podman-desktop/pull/8144 to be merged
