### ISSUE TITLE
Extensions Catalog fails to render when local kube.config is excessively large

### ISSUE THREAD

**Issue by utherp0** [containers/podman-desktop#7409]
### Bug description

My kube.config file had around 2000 config endpoints in it (I had forgotten to clean it). Podman Desktop starts up OK but then will not render any entries in the extensions catalog. Also the Troubleshoot/Log panel took 10 mins+ to render the log (which was full of non-responses from the kube.config endpoints)

### Operating system

MacOS 14.5

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

Generate a 'config' file in ~/.kube with 1000+ entries, start Podman Desktop, Click on Extensions, choose Catalog

**Comment by cdrage** [comment]
@feloy @deboer-tim I got this issue too when trying to load the .kube/config a while back.

I'm curious why we ping each one in the list, and when I do, sometimes it "freezes" up / stutters a bit when retrieving other information.

I'm curious why we check each one in the list even if we're not on the page, and if we are on the page, should we just check the last X ones (5?) or whatever we can view / see?

My thoughts:
- Ping a few times then delay (10 minutes?) before trying again.
- Only ping X amount

**Comment by feloy** [comment]
I would propose to automatically test the connectivity a few times only (and never if there are more than let's say 30 contexts), then display a "check" button and an information displaying how many time ago the status has been checked; for non-selected contexts only, the selected one would be checked as it is now.

**Comment by deboer-tim** [comment]
+1 to leaving current context as-is. If I only have a small number of contexts I think it's probably ok to keep the current behaviour and check them all/less informers, but even if I have >10 I don't think it's useful to ping them all unless/until we have a reason. Similarly to how we register to get Deployment + other informers, maybe we can defer status until (e.g.) you open the Kubernetes page and then start doing it in the background, then lazily disconnect after you leave? Basically use the pattern everywhere in the UI and main package decides heuristics on which/how many to keep open.

Random thought - it would be nice if we did something similar in places like the quick pick context switcher - e.g. when you open it includes the status of the current context inline, and then pings all other contexts in the background and shows you whether they're accessible.

**Comment by jeffmaury** [comment]
Another idea filter context based on URL as you may have several contexts for a single cluster

**Comment by feloy** [comment]
> +1 to leaving current context as-is. If I only have a small number of contexts I think it's probably ok to keep the current behaviour and check them all/less informers, but even if I have >10 I don't think it's useful to ping them all unless/until we have a reason. Similarly to how we register to get Deployment + other informers, maybe we can defer status until (e.g.) you open the Kubernetes page and then start doing it in the background, then lazily disconnect after you leave?

But the Deployments page (and similar pages) displays information about the current context only. 

For non-current contexts, the concerned pages would be the Preferences Contexts page (and the context switcher).

> Basically use the pattern everywhere in the UI and main package decides heuristics on which/how many to keep open.
> 
> Random thought - it would be nice if we did something similar in places like the quick pick context switcher - e.g. when you open it includes the status of the current context inline, and then pings all other contexts in the background and shows you whether they're accessible.

**Comment by deboer-tim** [comment]
> > +1 to leaving current context as-is. If I only have a small number of contexts I think it's probably ok to keep the current behaviour and check them all/less informers, but even if I have >10 I don't think it's useful to ping them all unless/until we have a reason. Similarly to how we register to get Deployment + other informers, maybe we can defer status until (e.g.) you open the Kubernetes page and then start doing it in the background, then lazily disconnect after you leave?
> 
> But the Deployments page (and similar pages) displays information about the current context only.
> 
> For non-current contexts, the concerned pages would be the Preferences Contexts page (and the context switcher).

Yes, that's what I was trying to say. Concerned UIs always have to register for what they need, and have to assume that the data may be lazy loaded. In reality we'll use some heuristics, like current context is always live or lazy closing in case the user switches back to a UI or context, etc. But these can change over time, or based on number of contexts or other things.

**Comment by feloy** [comment]
This issue https://github.com/containers/podman-desktop/issues/7636 introduced an interesting behaviour, as contexts not reachable when Podman Desktop starts will never be rechecked, and clusters accessible at startup will be rechecked if they become unreachable.

I'm not sure we can keep it as it is (as the condition is not clear in the code), but the behaviour is interesting to consider.

**Comment by feloy** [comment]
I have created the PR https://github.com/containers/podman-desktop/pull/7657, which makes Podman Desktop check only the current context when there are too many (> 10) contexts.

This would fix this issue.

To improve the experience, next steps would be to:
- have a "check" button on a Kubernetes Context card to manually start the check of a non-current context
- have an indicator for the user to know if the context is being checked
- have a preference for the user to choose between:
  - the default behaviour (no check if # contexts > 10), 
  - to do the checks, independently of the number of contexts
  - to not do the checks, independently of the number of contexts
- optimize the Reachable detection
  - https://github.com/containers/podman-desktop/issues/7629
  - [check common server only one](https://github.com/containers/podman-desktop/issues/7409#issuecomment-2165590903)
