### ISSUE TITLE
generate and store the css for the light and dark mode

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#7439]
### Is your enhancement related to a problem? Please describe

when we're using Podman Desktop, the backend generates styles and we expose colors on the fly by injecting the content/ result of the CSS in the main page or inside the webview

### Describe the solution you'd like

As we have other places where we could reuse the styles, it will be nice if the color-registry could have a command to generate the two css so for example we could import and reuse those css as part of the stories used by storybook

**Comment by axel7083** [comment]
> if the color-registry could have a command to generate the two css

@benoitf this would mean that you would need to start podman-desktop to be able to execute the command generating the stylesheets? If we need to compile fully podman-desktop and run it to generate the stylesheets, that makes the website build a lot bigger then ?

**Comment by benoitf** [comment]
in any case we do need to have all yarn dependencies, so for the dependencies it's the same amount of time

and then, we can use `tsx` so I think it's only taking few ms to run a single file, or I am wrong ?

**Comment by axel7083** [comment]
> in any case we do need to have all yarn dependencies, so for the dependencies it's the same amount of time
> 
> and then, we can use `tsx` so I think it's only taking few ms to run a single file, or I am wrong ?

I am not sure to follow, you want to run only a single ts file inside podman desktop main package ? That's seems a bit not recommended and weird solution ?

**Comment by benoitf** [comment]
> I am not sure to follow, you want to run only a single ts file inside podman desktop main package ? That's seems a bit not recommended and weird solution ?

what's the issue ?

**Comment by axel7083** [comment]
> > I am not sure to follow, you want to run only a single ts file inside podman desktop main package ? That's seems a bit not recommended and weird solution ?
> 
> what's the issue ?

IMO that's a bit weird, by comparaisson with other project, I would feel weird to execute one java file in my java projects. I would suggest to create a dedicated package, and expose it with a proper interfaces/cli tools. Or else having it in tools folder like we have for `release-notes-generator.ts`.

Directly executing a typescript file risk to be a bit hard to test/maintain with the Github action running tsx directly on it

**Comment by axel7083** [comment]
crazy idea: let's move it to the ui package ? and expose the stylesheet generation in it

**Comment by benoitf** [comment]
it can't be in the ui package as main need it (and webview does not rely on ui as well)

**Comment by axel7083** [comment]
> webview does not rely on ui as well

Oh yeah, that's annoying...

**Comment by axel7083** [comment]
> As we have other places where we could reuse the styles, it will be nice if the color-registry could have a command to generate the two css so for example we could import and reuse those css as part of the stories used by storybook

When you say `command` @benoitf you mean CLI or command like CommandRegistry ?

> we can use tsx so I think it's only taking few ms to run a single file, or I am wrong ?

After some testing, I am not able to run `tsx` on the color-registry for example, as we import a lot of thing from everywhere, tsx raise `ERR_MODULE_NOT_FOUND` when I try to do it.

```
$: ~/podman-desktop/packages/main> tsx --tsconfig .\tsconfig.json .\src\plugin\color-registry.ts
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\@\plugin\appearance-settings.js' imported from C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\src\plugin\color-registry.ts
```

I am not really able to find a nice clean solution for this task...

**Comment by benoitf** [comment]
@axel7083 I was thinking CLI yes
