### ISSUE TITLE
enhance storybook with new stories

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#7441]
### Is your enhancement related to a problem? Please describe

this issue is a kind of a placeholder, we need to iterate after having only the button component.

subtasks need to be opened for new candidate being added as stories

### Describe the solution you'd like

complete the list by adding items to this task and assign only subtasks to a sprint, not this one

**Comment by axel7083** [comment]
Let's not redo too much work and reuse the one I already made as examples: https://github.com/containers/podman-desktop/tree/1315fa80166658046ab91f9a6c673cfdac65aa3b/storybook/src/stories
