### ISSUE TITLE
Remove namespace column in Kubernetes and put it under the name. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7474]
### Is your enhancement related to a problem? Please describe

The "name" column should be matching other parts of Podman Desktop how we put important information below it (ports, image tag id, etc.).

The namespace column is kinda useless as we can only view one namespace at a time anyways.

IMO should be putting the namespace below the name / get rid of the namespace column.

Other parts of PD:

![Screenshot 2024-06-05 at 8 52 50 AM](https://github.com/containers/podman-desktop/assets/6422176/c6305a0b-c797-4e86-9b28-fdac67f5dede)

Example Kubernetes page:

![Screenshot 2024-06-05 at 8 52 57 AM](https://github.com/containers/podman-desktop/assets/6422176/b5ed4587-480d-49a9-8132-25c64a5a1ff9)

### Describe the solution you'd like

Namespace under the name of the ingress / service / etc.

### Additional context

WDYT @deboer-tim @feloy @ekidneyrh

**Comment by cdrage** [comment]
<img width="743" alt="Screenshot 2024-06-06 at 3 44 17 PM" src="https://github.com/containers/podman-desktop/assets/6422176/39b4da1c-c64e-4ee4-92d0-399d5690b7c3">

Testing this out while implementing PVC ^^

**Comment by deboer-tim** [comment]
FWIW I'm still on the fence about whether it should move, or in general what data belongs on the second line. One downside if (when) we support multiple namespaces is that then you couldn't sort. If we do go this route, then I think the second line should be purple or gray to make it easier to scan the names.

**Comment by ekidneyrh** [comment]
+1 for having it match the styling of the other sub-descriptions of the rows. If there's no use for the namespace where it is then I'd say go for it

**Comment by cdrage** [comment]
@deboer-tim WDYT that if we implement this (for now) to have it under the name and in gray / not as "popping out" since honestly.. by default we are in whatever namespace is defined in the context.

When we implement multiple namespace selection, we could find an alternative way to sort / way to implement this. I do remember old mockups that @mairin had that had grouped the namespaces. I believe the discussion was that "kube-system" namespace would have vastly different applications than say a default namespace.

**Comment by deboer-tim** [comment]
I think at some point in the future we'll want a namespace column, if we support multiple contexts or grouping - but I guess that's also easy enough to add back later. If there's nothing else that you think will be useful for 'subtitles' on the Kubernetes objects then we could do this and revisit later.

**Comment by mairin** [comment]
in case helpful this was the latest namespace design iirc

![image](https://github.com/containers/podman-desktop/assets/799683/f201fb52-b7e9-4c16-ab11-941a8ecb1c65)
