### ISSUE TITLE
New Image name not showing  up in Podman Desktop Images list

### ISSUE THREAD

**Issue by ipbabble** [containers/podman-desktop#7481]
### Bug description

I created a new image from a Containerfile. I gave the image a name during build but the name never showed up. 

I assumed this was to do with the fact that I had a `-` (dash) in the image name. I was never prompted to remove the dash. 

So first issue is to check the validity of the image name before the build starts.

After I noticed the name as `<none>` in the images list I edited the image and changed the name. But the name change did show up in the console. 

I checked the image name using the cli and one of the edit attempts seemed to stick and it shows up correctly using the CLI `podman images`.  BUT it still shows `<none>` in the console.

I chose Version "next" below but it's actually 1.10.3. I couldn't choose that in the drop down. 

### Operating system

macOS 14.5

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

See above.

Original name I attempted was ddis-utils. That didn't work.
I edited the name to ddisutils. That didn't stick in the podman desktop images list but it shows in the cli `podman images` list correctly.

<img width="1046" alt="Screenshot 2024-06-05 at 12 20 59 PM" src="https://github.com/containers/podman-desktop/assets/1304961/d7743518-6edb-48d4-97e5-6cfac174510e">

podman images:

```
> podman images
REPOSITORY                                 TAG         IMAGE ID      CREATED         SIZE
localhost/ddisutils                        latest      5bca227dc277  11 minutes ago  1.19 kB
<none>                                     <none>      dcfa0d1dbac2  11 minutes ago  191 MB
<none>                                     <none>      d467e25048c7  17 minutes ago  213 MB
registry.fedoraproject.org/fedora-minimal  33          d8c5c2e15b20  2 years ago     119 MB

```

**Comment by ipbabble** [comment]
Let me know if you need me to test some more steps.

**Comment by ipbabble** [comment]
FYI I restarted podman desktop to see if it would somehow see the new name after a restart but it still shows '<none>'

**Comment by cbr7** [comment]
@ipbabble may I ask what container file you are using?

**Comment by cdrage** [comment]
@ipbabble I noticed that:

```
localhost/ddisutils                        latest      5bca227dc277  11 minutes ago  1.19 kB
```

Is 1.19 kB

It's a manifest right? Just to confirm.

**Comment by cbr7** [comment]
I have not been able to repro this issue unless the built image is a manifest, in which case it is expected not to be visible in Images page at this time, it's only selectable in the bootc build menu.

**Comment by cbr7** [comment]
@odockal not sure what you want to do with this one.

**Comment by odockal** [comment]
@cbr7 I have added info needed label as we need some more information. @ipbabble just a ping to get you back in the loop.

**Comment by cbr7** [comment]
@odockal recommend closing this one as likely the problem was not a problem and the image was a manifest, meaning it was not supposed to be displayed in images page, otherwise the issue was not reproduced.

**Comment by odockal** [comment]
@cbr7 I see, closing the issue as it was explained. @ipbabble Feel free to reopen in case you think this is still a problem.
