### ISSUE TITLE
add blogging capabilities on the Podman Desktop website

### ISSUE THREAD

**Issue by deekay2310** [containers/podman-desktop#751]
### Is your feature request related to a problem? Please describe

Apart from documentation, there should be a separate section on the website for blog posts

### Describe the solution you'd like

A separate section / page where all blog posts can be accessed

**Comment by baude** [comment]
hold that thought before implementing ... i may have an alternative that everyone would prefer?

**Comment by deekay2310** [comment]
@baude would be happy to discuss! :D

**Comment by benoitf** [comment]
I think here it was not 'implementing something' but just enable the flag of docusaurus that allow blog articles.

**Comment by deekay2310** [comment]
Yes, @benoitf is right. We've already tried it before and it seemed to work well.

**Comment by deekay2310** [comment]
@baude is this the alternative that you were talking about? - https://containersteam.wpengine.com/
