### ISSUE TITLE
Table is auto-sorting on status change, even if sorted by name. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7516]
### Bug description

When I sort by name or any column (environment, containers, etc.) it does not stay consistent and it "jumps" around.

I believe it has something to do with the status auto-sorting?

For example, on the pods page, if you delete a pod it will no longer respect the name sorting since the pod went from available to deleting.

https://github.com/containers/podman-desktop/assets/6422176/978b0486-b43e-4188-9910-4cb616e13490

### Operating system

mac m1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

Go to any page with the table UI and sort by name

delete / create / do something to change the status of whatever is on the page.

**Comment by cdrage** [comment]
@deboer-tim unsure if you were working on this or if there is another issue opened (couldn't find one).

**Comment by deboer-tim** [comment]
This looks like a dupe of #5322, which I started to look into but never finished. I suspect the original implementation was based on a Svelte behaviour that wasn't guaranteed and needs to be fixed, feel free to take over if you have a good test case and want to look into it.

**Comment by cdrage** [comment]
> This looks like a dupe of #5322, which I started to look into but never finished. I suspect the original implementation was based on a Svelte behaviour that wasn't guaranteed and needs to be fixed, feel free to take over if you have a good test case and want to look into it.

Sure! If I have time this sprint and it's a quick fix I'll push a PR.
