### ISSUE TITLE
Podman Desktop on macOS: "Podman needs to be set up"

### ISSUE THREAD

**Issue by Basil-Dot-Work** [containers/podman-desktop#7525]
### Bug description

After installing Podman Desktop 1.10.3 on MacOS for Apple Silicon (ARM), and running though the setup wizard, I land on the Dashboard panel. The first item there declares that "Podman needs to be set up". Panel looks like this:

![setup](https://github.com/containers/podman-desktop/assets/105256796/efecf95e-f59c-487e-a0e3-d1af149e7903)

If I press that "Set up" button, I land on this empty Settings screen with no indicator of what I should do next.

![settings](https://github.com/containers/podman-desktop/assets/105256796/3495acf1-0853-4cef-87fd-48c6aad5a6f1)

I am left wondering if this is a bug, or if there is more for me to do to prepare Podman for use.

This same issue was [reported for MS Windows OS by another person](https://github.com/containers/podman/issues/20654#issue-1988244205), but posted to the wrong subproject rather than the Podman Desktop subproject.. So no resolution was provided there.

### Operating system

macOS Sonoma 14.5

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

1. Download installer for Podman Desktop for macOS ARM.
2. Mount the DMG file, copy the contained Podman Desktop app to the Applications folder or your Mac.
3. Run Podman Desktop app.
4. Go through all the panels of the setup wizard.
5. Land on the "Dashboard".
6. Notice the first item is mysteriously stating "Podman needs to be set up"

### Additional context

Running "podman version" in Terminal.app returns:

Client:       Podman Engine
Version:      5.0.3
API Version:  5.0.3
Go Version:   go1.22.3
Git Commit:   d08315df35cb6e95f65bf3935f529295c6e54742
Built:        Fri May 10 10:58:15 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.0.3
API Version:  5.0.3
Go Version:   go1.22.2
Built:        Thu May  9 17:00:00 2024
OS/Arch:      linux/arm64

**Comment by cbr7** [comment]
This is a duplicate for issue https://github.com/containers/podman-desktop/issues/6376 which is already fixed on main and will be released in Podman Desktop 1.11
