### ISSUE TITLE
Cannot install Podman via Podman Desktop on main branch on Windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7527]
### Bug description

As discussed in #7433, I am still not able to install Podman on my machine using Podman Desktop nightly bits where Podman 5.1.1 installer is available. When tried locally as part of review of #7433, I was able to run the `podman-setup.exe` on its own, but not via Podman Desktop.

![podman511-install-error](https://github.com/containers/podman-desktop/assets/19164299/9ae77ba0-b514-4182-9621-08951e24a849)

### Operating system

Windows 10, x64

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Try to install Podman via Podman Desktop (https://github.com/containers/podman-desktop/releases/tag/v0.0.202406091508-34d0fb2).

### Relevant log output

```shell
VM5:2 main ↪️ [podman] The podman extension has not been successfully initialized
console.<computed>	@	VM5:2

VM5:2 main ↪️ [podman] Error: The podman extension has not been successfully initialized
    at hl.doInstallPodman (C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.cjs:172:1839)
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\extensions\podman\builtin\podman.cdix\dist\extension.cjs:181:3257
    at of.executeCommand (C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:95:32852)
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:338:9910
    at C:\Users\Ondrej\AppData\Local\Temp\2heFK3VUvTqJJyHz4mH21SxMgVA\resources\app.asar\packages\main\dist\index.cjs:336:20656
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82782)
    at WebContents.emit (node:events:519:28)
console.<computed>	@	VM5:2
```

**Comment by cbr7** [comment]
Issue also occurs on macOS, I've tried to install podman using PD [latest](https://github.com/containers/podman-desktop/releases/tag/v0.0.202406100733-f25dc1b) universal build. Podman fails installation from both the onboarding worklow and from the dashboard.


https://github.com/containers/podman-desktop/assets/106525396/9f76fa08-cdf5-4315-a888-6e067851ffb9

**Comment by tigert** [comment]
On Win11 I get the same, the 5.1.1 CLI installer works and podman-desktop can then see it, but trying to install podman from podman-desktop fails the same fashion.
