### ISSUE TITLE
Podman Desktops shows machine running before it is available from CLI

### ISSUE THREAD

**Issue by hguerrero** [containers/podman-desktop#754]
### Bug description

If you start podman machine from the desktop app, it will show running (removed the switch ui element). If you go to the CLI and try to use `podman` CLI, you will get an error:

```
Error: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:61516->127.0.0.1:55674: read: connection reset by peer
```

Looks like it takes longer to start the machine and processes.

### Operating system

macOS Monterey 12.6.1

### Version

0.8.0

**Comment by benoitf** [comment]
Hello @hguerrero 
Thank for the report.

Podman Desktop is relying on the status provided by the `podman machine ls --format=json` report

If `"Running": true` is reported it means, the machine is up.
But it looks like on your case the machine is reporting to be running before it's fully available.

Could you check to run `podman machine ls --format=json` command when you run your CLI command ?

**Comment by benoitf** [comment]
fixed in latest podman versions
