### ISSUE TITLE
Light mode for feedback form

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7544]
### Is your enhancement related to a problem? Please describe

The feedback form has some hardcoded colors for the text box and email address.

### Describe the solution you'd like

Would be better to have components that set the correct colors, but for now it should be enough to use existing colors from the color registry to correct this.

**Comment by SoniaSandler** [comment]
@deboer-tim the colors of the smiley faces are also hard coded (but are fairly visible in both dark and light modes), should I leave them like that for now or also change them to use the color registry?

**Comment by deboer-tim** [comment]
> @deboer-tim the colors of the smiley faces are also hard coded (but are fairly visible in both dark and light modes), should I leave them like that for now or also change them to use the color registry?

Yes please. Ideally there are existing colors in the registry that make sense to use.

**Comment by SoniaSandler** [comment]
@deboer-tim I found some colors in the registry that look good with the smiley faces, but their names are completely unrelated to the usage context here. I can add additional colors to the registry with names that make more sense for this context, but I'm not sure if this might be redundant.
