### ISSUE TITLE
Light mode for onboarding

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7547]
### Is your enhancement related to a problem? Please describe

Onboarding has hard-coded colors and does not support light mode.

### Describe the solution you'd like

Define any missing colors in the light mode palette and get onboarding working in light mode.

**Comment by lstocchi** [comment]
@ekidneyrh is there any mockup for this? Just to know because i missed the one related to the formpages when i started working on them and i don't want to miss something again. Otherwise i can start working on it taking other components as example and we can iterate on it.

**Comment by ekidneyrh** [comment]
> @ekidneyrh is there any mockup for this? Just to know because i missed the one related to the formpages when i started working on them and i don't want to miss something again. Otherwise i can start working on it taking other components as example and we can iterate on it.

No, I don't have anything for that at the moment.
