### ISSUE TITLE
Updated Summary pages

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7558]
### Epic domain

We should update all our Summary pages so it's similar to how we've implemented it for Kubernetes:

![Screenshot 2024-06-10 at 2 09 44 PM](https://github.com/containers/podman-desktop/assets/6422176/78706e19-5216-46cf-8418-4eff8212a279)

- [x] Containers #7559 
- [x] Pods (podman pods) #7559 
- [x] Images #7561 
- [x] Volumes #7562

**Comment by deboer-tim** [comment]
We've done all of these, assuming this can be closed now?

**Comment by cdrage** [comment]
@deboer-tim Yup!
