### ISSUE TITLE
Light mode for Kubernetes logo

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7579]
### Is your enhancement related to a problem? Please describe

![image](https://github.com/containers/podman-desktop/assets/6422176/8231b91d-a07d-4cde-b421-b8083a1d67e3)

Compared to the rest of the navbar:

![Screenshot 2024-06-11 at 9 14 53 AM](https://github.com/containers/podman-desktop/assets/6422176/30e3e8c8-5ba7-45cb-a452-760a5bfecd46)

### Describe the solution you'd like

Same / similar light mode icon as rest of navbar.

**Comment by deboer-tim** [comment]
Just noting this affects all closed NavSections (i.e. Extensions section is the same). Also note the ^ icon below, which as in the image above is fine when opened so likely just wrong color picked up for closed sections.
