### ISSUE TITLE
A lot of warnings on load for PreferencesConnectionRendering..

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7582]
### Bug description

![Screenshot 2024-06-11 at 10 04 19 AM](https://github.com/containers/podman-desktop/assets/6422176/d90ef334-2893-4adb-abb4-36ad316cadae)

Unsure exactly what's happening, this is happening as well on main.

When loading PD there is a lot of warnings regarding auditing the PreferencesConnectionRendering files.

### Operating system

mac M1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

`yarn watch` on main branch and open up PD / see console logs.

**Comment by odockal** [comment]
Looks like dupe or having the same solution as #3478, it might be different area. It was also reported in #3503.

**Comment by SoniaSandler** [comment]
I checked with @cdrage , and we are unable to reproduce this problem again

**Comment by jeffmaury** [comment]
Reopening as I can reproduce trying to create a second Podman machine. You should look at the DevTools console and not the output of `yarn watch`
