### ISSUE TITLE
Cannot ssh into machine with networkingMode=mirrored

### ISSUE THREAD

**Issue by damlys99** [containers/podman-desktop#7588]
### Bug description

After setting networkingMode=mirrored in .wslconfig I'm no longer able to use Podman Desktop.
That happens only after upgrading Podman Desktop version (I don't remember from what version exactly, but Podman on the machine got upgraded from 4.9.3 to 5.0.3).

I have HyperVFirewall disabled.
What's unusual, after starting other WSL distro - ubuntu in other cmd, issues are disappearing, as that somehow triggers network to mirror

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

1. Set networkingMode=Mirrored in .wslconfig
2. wsl --shutdown
3. podman machine start

Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        could not start api proxy since expected pipe is not available: podman-machine-default

Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine is not listening on ssh port
4. "Bash" in cmd (starts Ubuntu - default distro for me)
5. podman machine ssh - works

### Relevant log output

```shell
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        could not start api proxy since expected pipe is not available: podman-machine-default

Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine is not listening on ssh port

C:\Users\<user>>ssh user@127.0.0.1 -p 64324
** timeouts**
In different cmd: C:\Users\<user>>Bash
** starts ubuntu **
C:\Users\<user>>ssh user@127.0.0.1 -p 64324
** works **
```

### Additional context

64324 port is exposed by podman-machine-default
![image](https://github.com/containers/podman-desktop/assets/63010482/c72fbb0f-a475-4ff2-9877-e74cfb188209)
![image](https://github.com/containers/podman-desktop/assets/63010482/03d84edf-5c5e-4972-a105-afe6070a210d)
![image](https://github.com/containers/podman-desktop/assets/63010482/83220e86-33b9-4d0c-81f1-4c1a72dd0544)

it seems like for some reason network gets mirrored only after I start Ubuntu

.wslconfig
[wsl2]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true

[experimental]
hostAddressLoopback=true

**Comment by szarykott** [comment]
Why was it closed? I have exactly the same problem!

**Comment by damlys99** [comment]
I have opened the issue on Podman github, as its not related to Podman Desktop, and closed that one. 

https://github.com/containers/podman/issues/22975

**Comment by mcarbonneaux** [comment]
what is the image name for the 4.9.3 to be abel to downgrad before while be fixed ?
