### ISSUE TITLE
Add confirmation when bulk-deleting

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7591]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-06-11 at 4 20 38 PM](https://github.com/containers/podman-desktop/assets/6422176/f0ebfe67-1180-4d04-8524-3af586e6ecb8)

Although we can multi-select, we should really have a confirmation button when bulk-deleting since we are dealing with important concepts such as storage, etc.

### Describe the solution you'd like

Add confirmation for bulk deletion.

**Comment by benoitf** [comment]
related to https://github.com/containers/podman-desktop/issues/7832
