### ISSUE TITLE
Macos build is not signed

### ISSUE THREAD

**Issue by ssbarnea** [containers/podman-desktop#76]
### Bug description

My testing stopped right after the download.
![](https://sbarnea.com/ss/Screen-Shot-2022-04-01-12-35-54.76.png)

### Operating system

macOS any

### Version

0.0.1

**Comment by benoitf** [comment]
@ssbarnea I didn't have keys at 0.0.1 time but now all builds are signed

you might download one of the recent 'next' release from https://github.com/containers/desktop/releases or wait for `0.0.2`

**Comment by ssbarnea** [comment]
Thanks! I started it but it does not show me anything, seems decoupled from the brew installed podman 4.0.2. Still, my podman setup is being bit messed due to https://github.com/containers/podman/issues/11541#issuecomment-1085695871 --- which might explain why it did not find any containers or vms.

**Comment by benoitf** [comment]
@ssbarnea do you have a podman machine running ?

```
$ podman machine list
```

if not, create one and start one with `podman machine init` then `podman machine start`

**Comment by benoitf** [comment]
closing as 0.0.2 has been released today and it includes code signing for macOS
