### ISSUE TITLE
Plugins - Podman AI Lab extension, Bootable Container extension - Fail on Fedora Silverblue 40 (homedir is a symlink)

### ISSUE THREAD

**Issue by johwes** [containers/podman-desktop#7601]
### Bug description

When trying to install and use the plugins,
Bootable Container extension
Podman AI Lab extension

They fail with a stacktrace

### Operating system

Fedora Silverblue 40

### Installation Method

Flathub (Linux)

### Version

1.10.2

### Steps to reproduce

Install podman-desktop as a flatpak on a Fedora Silverblue system
Install Podman AI Lab extension and/or Bootable Container extension

### Relevant log output

```shell
Error: Cannot find extension for /var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist
Stack trace:
Error: Cannot find extension for /var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33696)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Module.<anonymous> (/var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist/extension.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33447)
```

### Additional context

On silverblue /home is a symlink to /var/home
It might be relevant

ls -al /home
lrwxrwxrwx. 1 root root 9 Jun 12 11:42 /home -> /var/home

**Comment by jeffmaury** [comment]
Cannot reproduce on an HyperV Fedora Silverblue 40. Did you install the extension from the catalog ? Which version

**Comment by bcrochet** [comment]
I have reproduced this. Any plugin that is not builtin fails. 

And yes, extensions installed from the catalog. For instance, tried installing the Red Hat Extension Pack extension from the catalog, and every single plugin failed in the same way as @johwes reported.

**Comment by jeffmaury** [comment]
So seems related to your settings so what do you have in $HOME/.local/share/containers/podman-desktop/plugins (including permissions)

**Comment by bcrochet** [comment]
```
❯ ls -l $HOME/.local/share/containers/podman-desktop/plugins
total 0
drwxr-xr-x. 1 bcrochet bcrochet 118 May 17 13:13 ghcriocontainerspodmandesktopextensionbootc
drwxr-xr-x. 1 bcrochet bcrochet  86 May 17 13:15 ghcrioredhatdeveloperpodmandesktopimagecheckeropenshiftext
drwxr-xr-x. 1 bcrochet bcrochet  72 May 17 13:11 ghcrioredhatdeveloperpodmandesktopredhatpackext
drwxr-xr-x. 1 bcrochet bcrochet 104 Jun 13 16:03 ghcrioredhatdeveloperpodmandesktopsandboxext
drwxr-xr-x. 1 bcrochet bcrochet  80 May 17 13:13 quayioredhatdeveloperopenshiftlocalextension
drwxr-xr-x. 1 bcrochet bcrochet 120 May 17 13:13 quayioredhatdeveloperpodmandesktopredhataccountext
```

**Comment by bcrochet** [comment]
I just installed a fresh Silverblue 40 in Boxes, and I got the same result. I made no other modifications to the box other than installing Podman Desktop.

**Comment by jeffmaury** [comment]
> I just installed a fresh Silverblue 40 in Boxes, and I got the same result. I made no other modifications to the box other than installing Podman Desktop.

Can you describe the steps to install Podman Desktop as I cannot reproduce in my HyperV VM

**Comment by johwes** [comment]
I go into Software, graphical tool in fedora to manage software and I install the podman-desktop by using the flatpak version.

![Screenshot from 2024-06-17 12-32-31](https://github.com/containers/podman-desktop/assets/4445476/819b6912-832a-4495-b635-133da7981657)

**Comment by bcrochet** [comment]
And my steps are:
```
flatpak flathub install io.podman_desktop.PodmanDesktop
```

There is nothing more to it than that.

**Comment by bcrochet** [comment]
Just tried with latest nightly. Still present.
