### ISSUE TITLE
ERR_INTERNAL_ASSERTION error when waking a 2019 intel MacBook Pro from sleep

### ISSUE THREAD

**Issue by lisa** [containers/podman-desktop#7605]
### Bug description

When I put my computer to sleep at the end of the workday I leave podman and podman-compose running. When I wake up the computer on the following workday, I receive the indicated error. The popup, in podman-desktop, occurs multiple times (read: I must dismiss it multiple times).

### Operating system

MacOS 14.5 (x86_64)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

As far as I'm aware, I need to put my Mac to sleep and then wake it up the next day and the assertion is present.

### Relevant log output

```shell
Uncaught Exception:
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

at assert (node:internal/assert:14:11)
at internalConnectMultiple (node:net:1118:3)
at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
at listOnTimeout (node:internal/timers:575:11)
at process.processTimers (node:internal/timers:514:7)
```

### Additional context

<img width="515" alt="podman-desktop js error" src="https://github.com/containers/podman-desktop/assets/18159/4bb2e9a3-123f-425d-bdcb-cb719439c67b">

**Comment by benoitf** [comment]
hello @lisa could you try with a nightly version of Podman Desktop (as we bump electron (with a newer version of Node.js)

fetch one from today at https://github.com/containers/podman-desktop/releases

**Comment by gadware** [comment]
Got this exact error MacOS 14.3.1, podman version 5.0.1

**Comment by nichjones1** [comment]
@odockal can you try and reproduce this issue?

**Comment by odockal** [comment]
@nichjones1 No, I would need to have the Mac physically. @cbr7 Could you please try?

**Comment by cbr7** [comment]
@odockal this is pretty much what I do every night and I have never seen the issue, however I will note that I have an M2 Pro Macbook, not an intel chip one as described in the issue.

**Comment by nichjones1** [comment]
@benoitf can you reproduce this issue?

**Comment by benoitf** [comment]
I tried on the latest update of macOS (14.6.1) and a podman machine 5.2.0 using an intel mac book pro 2018 and after a couple of hours using `sleep` mode and opening up again the lid, the podman compose project is still running and no Podman Desktop error.

**Comment by benoitf** [comment]
tried during one day having the computer sleeping.

wake up and everything is still working

(tried with penpot app docker compose file)
https://github.com/penpot/penpot/tree/develop/docker/devenv

**Comment by benoitf** [comment]
closing as not reproducing with podman 5.2.0, Podman Desktop 1.12.0 and macOS 14.6.1
