### ISSUE TITLE
Docs: Add webview template "full" example

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7634]
### Is your enhancement related to a problem? Please describe

We do not have any documentation on how to create a hello world webview for development purposes.

Before we do this however we should have a "helloworld" test extension that follows the similar conventions as bootc / ai lab with the proxy to do backend vs frontend communication.

This issue adds a "full" example including svelte, shared folder / rpc proxy / etc.

### Describe the solution you'd like

- [x] Helloworld example that uses separate packages / similar to bootc / ai lab
- [x] Documentation on podman desktop site.

**Comment by cdrage** [comment]
@feloy @benoitf I forget, but I believe one of you had a hello world example for web view in progress?

**Comment by benoitf** [comment]
I had long time ago converted https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample but I was told to use seals inside of cats (but I don't think I have anymore the source code)

**Comment by feloy** [comment]
> @feloy @benoitf I forget, but I believe one of you had a hello world example for web view in progress?

I have a template for a webview-based extension in this repo: https://github.com/feloy/podman-desktop-extension-webview-template
