### ISSUE TITLE
Kubernetes context not retried if not connected the first time

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#7636]
### Bug description

This PR introduced a side effect: https://github.com/containers/podman-desktop/pull/6934

When a Kubernetes context is not accessible at the first connection attempt, no more connection attempt will be done.

In the other hand, if the context is first accessible, then the context begins not accessible, then accessible again, connection attempts will be done and will detect the context is accessible again.

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Be sure that you have a Kubernetes cluster non accessible before you start Podman Desktop, and that there is a context pointing to that cluster in your kubeconfig (for example a Kind cluster for which the pod is stopped)
- start Podman Desktop
- check the logs in the console (with Verbose level selected), you will see only one entry `Trying to watch pods on the kubernetes context named "kind-kind-cluster" but got a connection refused, retrying the connection in 1s.` 
- make the cluster accessible again (for example restart the kind's pod)
- go to the Kubernetes contexts page, wait, the cluster will never be marked as Reachable

**Comment by deboer-tim** [comment]
I've hit this while testing, would be nice to fix soon.
