### ISSUE TITLE
Icon for Persistent Volume Claim for Kubernetes

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7641]
### Is your enhancement related to a problem? Please describe

We should have an icon that's different than the normal "volumes" icon for PVC. Right now in the PR it is re-using the volume icon: https://github.com/containers/podman-desktop/pull/7640

Taken from google, I was thinking something like this?

![image](https://github.com/containers/podman-desktop/assets/6422176/917bbfa5-631b-45cc-b1ad-89c39bf4a282)

It makes sense for it to be a "dashed" volume since it's "claiming".

### Describe the solution you'd like

Icon for PVC

**Comment by ekidneyrh** [comment]
SVGs:
![pvc](https://github.com/containers/podman-desktop/assets/87311656/82d01d5f-edeb-458f-b70d-840b3956ed56)
![pvc-filled](https://github.com/containers/podman-desktop/assets/87311656/84075628-57fc-40d5-b34e-cc22659e6888)

PNGs:
![pvc-filled](https://github.com/containers/podman-desktop/assets/87311656/02a80fcb-7a8f-4d16-b387-0b410f549568)
![pvc](https://github.com/containers/podman-desktop/assets/87311656/2e9dcd29-cca0-4304-85ab-b7238c88d7e9)

Here's a screenshot from inkscape for better visibility :) 

![image](https://github.com/containers/podman-desktop/assets/87311656/39065cf6-2eaf-4807-8f0a-77f2e852f662)

WDYT?

**Comment by cdrage** [comment]
> SVGs: ![pvc](https://private-user-images.githubusercontent.com/87311656/340307054-82d01d5f-edeb-458f-b70d-840b3956ed56.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTYsIm5iZiI6MTcxODY0Nzg1NiwicGF0aCI6Ii84NzMxMTY1Ni8zNDAzMDcwNTQtODJkMDFkNWYtZWRlYi00NThmLWI3MGQtODQwYjM5NTZlZDU2LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYzI4MzhhMjdlMGZiMmFmZDUwNTFiOGQ2MDFkOGRiMWNlNDIxZjNiY2UxY2RiN2M3MmMzYjZlYWQ2MzY0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3iENZcugl6YnqO62-1sJO44LEldkUiwxjCVGqgnMjro) ![pvc-filled](https://private-user-images.githubusercontent.com/87311656/340307059-84075628-57fc-40d5-b34e-cc22659e6888.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTYsIm5iZiI6MTcxODY0Nzg1NiwicGF0aCI6Ii84NzMxMTY1Ni8zNDAzMDcwNTktODQwNzU2MjgtNTdmYy00MGQ1LWIzNGUtY2MyMjY1OWU2ODg4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjM2NhOWI0MDQwMjRjYjg5NGE4ZDU2ODU4NzFlMjlhZmI3ODE0NTVmYjFlZDRiOGE0ZDZjYmJlY2UyMjFhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EOlFrwoQ5mk6n_vUWj2BEegMLLuvj6V2U-havT5izmI)
> 
> PNGs: ![pvc-filled](https://private-user-images.githubusercontent.com/87311656/340306572-02a80fcb-7a8f-4d16-b387-0b410f549568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTYsIm5iZiI6MTcxODY0Nzg1NiwicGF0aCI6Ii84NzMxMTY1Ni8zNDAzMDY1NzItMDJhODBmY2ItN2E4Zi00ZDE2LWIzODctMGI0MTBmNTQ5NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODNmZDQ5N2Y5NGM4MTFkNjBjNWNlZmVkOTU2MmEzNDBmMzUzNjZhODU2MDU1YjY0MTQwNWIyOWJkMmIxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wm_5whon_flSsTrjI_YRGPAQNQU69oRaQ_sX8-HPPfE) ![pvc](https://private-user-images.githubusercontent.com/87311656/340306574-2e9dcd29-cca0-4304-85ab-b7238c88d7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTYsIm5iZiI6MTcxODY0Nzg1NiwicGF0aCI6Ii84NzMxMTY1Ni8zNDAzMDY1NzQtMmU5ZGNkMjktY2NhMC00MzA0LTg1YWItYjcyMzhjODhkN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MjgyZmQ4YzZlNzY4ZGNkNWQwNzUyY2I5OWE3YjljOTY2ZjkwNDFlYmI5OWNmN2E0YzZiZGNlNTQ5ZWI3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-lldv4-VyTeaKTqhDJSnSgC3mIOl8r3etoLJEvppio)
> 
> Here's a screenshot from inkscape for better visibility :)
> 
> ![image](https://private-user-images.githubusercontent.com/87311656/340306771-39065cf6-2eaf-4807-8f0a-77f2e852f662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgxNTYsIm5iZiI6MTcxODY0Nzg1NiwicGF0aCI6Ii84NzMxMTY1Ni8zNDAzMDY3NzEtMzkwNjVjZjYtMmVhZi00ODA3LThmMGEtNzdmMmU4NTJmNjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NDQ4ZDY2MjljNTMzYjE4OTMxMzk2ZDk3ZWU1Yjg5YWRiNmY0MzRmOGQ0Yjg5MzdlMGEzZTkyZTZjMjBiZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtVolLWB6kVOByUvwXsqcHNW8UCcfAcTR4KADXYmizM)
> 
> WDYT?

Looks good to me (the second one)! The first one to me looks like a fancy cake since it has the black outline / white dotted inside.

**Comment by deboer-tim** [comment]
> Looks good to me (the second one)! The first one to me looks like a fancy cake since it has the black outline / white dotted inside.

LGTM, but I was assuming the first is 'solid' and the second is 'outline'? We do need both versions for nav/status icons.

**Comment by cdrage** [comment]
Ahh, that makes sense with regards to colouring. For some reason I thought it was 2 different versions for the navbar. I'm good with that, as I'm assuming the "cake" looking one will be coloured green, yellow, etc.

**Comment by deboer-tim** [comment]
Here's what it'll look like in context, I will PR as soon as #7640 gets merged:

<img width="181" alt="Screenshot 2024-06-17 at 4 09 02 PM" src="https://github.com/containers/podman-desktop/assets/19958075/689ba2b8-b54e-4862-93b9-80441b3b9bdb">

I almost want to say the dashing could be a little more pronounced - but honestly it is great as-is.

And actually @ekidneyrh , would you mind redoing the regular solid volume icon with the 'outline' like above? The solid PVC stands out so much nicer I think we should do it here too:

<img width="229" alt="Screenshot 2024-06-17 at 4 15 33 PM" src="https://github.com/containers/podman-desktop/assets/19958075/d62605ad-c0e9-4fda-aa94-e213b3ce9891">

**Comment by ekidneyrh** [comment]
Lol yah it's for the solid one! It was tricky to have the dashes still visible but also have it filled in. I can do that :) I'll add onto this ticket

**Comment by ekidneyrh** [comment]
SVG: 
![volume-filled](https://github.com/containers/podman-desktop/assets/87311656/fe7246bf-5530-468c-899d-165fae7d440f)

Preview from inkscape:
![image](https://github.com/containers/podman-desktop/assets/87311656/ac9371ff-a645-4450-9c6c-13d060d3ff63)

**Comment by deboer-tim** [comment]
Thanks! I do like this better and will PR at the same time as PVC.

<img width="229" alt="Screenshot 2024-06-18 at 7 58 35 AM" src="https://github.com/containers/podman-desktop/assets/19958075/450881e6-6078-40cd-aa98-f75367380f67">
