### ISSUE TITLE
Remove the "id" for Kubernetes pod and replace with node name?

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7646]
### Is your enhancement related to a problem? Please describe

The ID is really odd in the Kubernets pod listing because it doesn't relate to anything other than UUID which is rarely used...

IMHO. We should replace it instead with the node that the pod is located on, as well as the namespace beside it?

### Describe the solution you'd like

Instead of "67990026" have the node it is located on instead as well as the namespace beside it.

![Screenshot 2024-06-13 at 4 23 49 PM](https://github.com/containers/podman-desktop/assets/6422176/cdff5c93-e6a8-4844-bdc3-07984ae1093c)

Similar to `kubectl get pods -o wide`:

```sh
NAME                                   READY   STATUS    RESTARTS   AGE     IP           NODE   NOMINATED NODE   READINESS GATES
neko-67ff554889-c4l8m                  1/1     Running   0          11m     10.42.1.35   k8s2   <none>           <none>
git-7f6dc4f666-pqhbr                   1/1     Running   0          11m     10.42.5.38   k8s4   <none>           <none>
adguard-79b5ff976d-25wfz               1/1     Running   0          11m     10.42.5.39   k8s4   <none>           <none>
```

**Comment by cdrage** [comment]
@feloy @deboer-tim thoughts?

**Comment by afbjorklund** [comment]
I think it was asked before, why it is using "uid" for ID instead of "id" (as in kubectl)

* https://github.com/containers/podman-desktop/issues/2800

**Comment by cdrage** [comment]
> I think it was asked before, why it is using "uid" for ID instead of "id" (as in kubectl)

No idea... it should be using the ID from yaml / inspect, or something more informational.

**Comment by deboer-tim** [comment]
> @feloy @deboer-tim thoughts?

Agreed. I think this is just historical, we could display something more useful for Kube pods.
