### ISSUE TITLE
When deleting a machine, the machine detail's page stay visible

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#765]
### Bug description

When deleting a machine, the machine details page stay visible.

### Operating system

mac OS

### Version

0.9

### Steps to reproduce

1. Go in "Settings" / "Resources" and delete an existing podman machine.

Result:
Once deleted, the machine details' page is still visible. 

Proposal solution:
We could be showing a loader over the machine details' page. Once the machine is deleted, we would display the list of machine (or the create new machine)

**Comment by cdrage** [comment]
Closed via https://github.com/containers/podman-desktop/pull/831
