### ISSUE TITLE
Podman Desktop should catch the kubernetes context change from tray menu

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#766]
## Bug description

At the moment, Podman Desktop only capture the kubernetes context at startup. 
So if a user changes the default kubernetes context from the system tray, Podman Desktop will not catch the change and in the case of deploying a pod to kubernetes, it will not target the proper environment. 

### Version
0.9

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/813
