### ISSUE TITLE
Nit: left taskbar expansion

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#767]
### Is your enhancement related to a problem? Please describe

Nit of the day: when the left taskbar is minimized and then expanded, the text appears as the column expands. As a result the text goes over the border of the main page for a second, even overlapping the page title.

https://user-images.githubusercontent.com/19958075/199714309-0e342a3b-723e-4d42-a51d-b2a7d3667aa4.mov

### Describe the solution you'd like

The expansion is really cool, just delay the appearance of the text for 100ms+ so that the column has enough time to almost finish expanding first.

**Comment by benoitf** [comment]
@deboer-tim if you could try https://github.com/containers/podman-desktop/pull/771
