### ISSUE TITLE
Podman CLI won't allow machine start after Podman Desktop restarted

### ISSUE THREAD

**Issue by craulers** [containers/podman-desktop#7674]
### Bug description

I installed WSL2 and Podman recently and everything was working, until Podman desktop was restarted. Now, I cannot restart an existing machine or initialize and start a new one. 

### Operating system

Windows 10 Enterprise

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

1. Install WSL2 (wsl --install --no-distribution) and restart computer
2. Install Podman using the desktop .exe (actually version 1.10.3 - current release)
3. Confirm that podman is running and spend a day working with it, running everything from CLI, etc. 
4. Restart Podman Desktop

I've tried restarting the machine from the Desktop app: 
![image](https://github.com/containers/podman-desktop/assets/172846631/5d390bcc-c74a-4978-8952-9affee50ff37)

C:\Users\myusername>podman info
OS: windows/amd64
provider: wsl
version: 5.0.3

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:52382: connectex: No connection could be made because the target machine actively refused it.

### Relevant log output

```shell
Since that error wasn't very informative, I went to the CLI: 
C:\Users\myusername>podman machine start
Starting machine "podman-machine-default"
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND
Error: the WSL bootstrap script failed: exit status 0xffffffff

I tried initializing a new machine: 
C:\Users\myusername> podman machine init test 
Downloading VM image: v20240617031328-5.0-rootfs-amd64.tar.zst: done
Extracting compressed file: test-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
The operation completed successfully.
Configuring system...
Machine init complete
To start your machine run:

        podman machine start test

C:\Users\myusername> podman machine start test
Starting machine "test"
Logon failure: the user has not been granted the requested logon type at this computer.
Error code: Wsl/Service/CreateInstance/CreateVm/HCS/0x80070569
Error: the WSL bootstrap script failed: exit status 0xffffffff
```

### Additional context

Since this error seems related to WSL: 

C:\Users\myusername>wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.19045.4412

C:\Users\myusername>wsl --status
Default Distribution: podman-test
Default Version: 2

C:\Users\myusername>wsl --list
Windows Subsystem for Linux Distributions:
podman-test (Default)

**Comment by lstocchi** [comment]
Sorry for the late response i completely missed it.
By looking at your cli logs it seems that the old distribution was deleted by someone. Maybe your env was reset automatically?
Also the other errors seem related to this (atleast if it was working finely the day before). 
Check that you have the `Hyper-v` and `Virtual Machine Platform` options checked in `Turn Windows features on or off` view. What's their status?

**Comment by lstocchi** [comment]
Closing as we didn't receive any response. Feel free to reopen it or a new issue if you need help. Thanks!!
