### ISSUE TITLE
ConfigMaps & Secrets Icon for Kubernetes dashboard

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7680]
### Is your enhancement related to a problem? Please describe

We will need an icon that can represent both ConfigMaps and Secrets.

This is what Kubernetes uses to represent them:

![Screenshot 2024-06-17 at 4 26 37 PM](https://github.com/containers/podman-desktop/assets/6422176/11df62e4-578b-40f1-8378-53fb18ab62ed)

### Describe the solution you'd like

Perhaps an icon that looks similar with the lines?

### Additional context

Needed for #configmaps

**Comment by ekidneyrh** [comment]
Here are two ideas, one is the document page we have throughout atm but with a lock in the middle.

SVG: 
![configsecret_idea2](https://github.com/containers/podman-desktop/assets/87311656/63d2627c-b85f-44bd-b35e-25ca8b66af7f)

Screenshot:
![image](https://github.com/containers/podman-desktop/assets/87311656/e07db22e-aa69-4729-8ed9-12d6d81bcec2)

The other is similar to the one shared above on the ticket - using lines to represent a document. 

SVG:
![configsecret_idea1](https://github.com/containers/podman-desktop/assets/87311656/66226e6a-e02c-4df7-b7be-4024b47dd75e)

Screenshot:
![image](https://github.com/containers/podman-desktop/assets/87311656/b6b2e7be-c64d-45e4-b0ed-30285fe447b1)

Both combine the config data (document) with the lock icon (secret/security). 

LMKWYT :)

**Comment by deboer-tim** [comment]
If we went with the first I think I'd drop the document and just have the lock, but I think either way it gets the 'secrets' but isn't as obvious for 'config maps'.

For the second, I don't know how you'd make a solid version :) but again it conveys the secrets to me more than config maps. In the lower left of the Kube icon at the top the lines are broken up like key/value pairs or properties - maybe it would work if we broke up the lines a bit like that?

**Comment by cdrage** [comment]
Same thoughts as @deboer-tim ^^ I like how the Kube icon does the whole broken up lines as well to convey that it's a key/value, so that plus the lock would be great.

I do find the lock looks a bit like a suitcase though? / I see no keyhole?

**Comment by feloy** [comment]
Secret in Kubernetes is not about protecting the values, but about encoding the values, so you can use binaries values for secrets.

For this (and for trying to not propagate the belief that Kubernetes authors tried to protect values by encoding them), I would not use a lock in the icon

**Comment by ekidneyrh** [comment]
@deboer-tim @cdrage I can certainly change the lines to convey the key/values and make the lock less suitcase like :handbag: is smth like this better?

![image](https://github.com/containers/podman-desktop/assets/87311656/4d86c9f7-9b13-45a7-b578-b7151714d26d)

SVG:
![configsecret_5](https://github.com/containers/podman-desktop/assets/87311656/13cd3549-3e8c-4688-9b80-84e86a66f186)

In regards to @feloy's comment, if we went away from the lock.. what else would work? Would smth like this be more accurate? 

![image](https://github.com/containers/podman-desktop/assets/87311656/d6071bcf-0ca2-4e37-9b62-5c255c70ea8f)

SVG:
![configsecret_4](https://github.com/containers/podman-desktop/assets/87311656/0051ebd0-a195-4934-bd7e-dd937b6fbb5e)

**Comment by cdrage** [comment]
👍 On the binary / 0110! gives a bit of character / differentiate between others. I like it

**Comment by ekidneyrh** [comment]
nice! I'll get working on a solid version

**Comment by ekidneyrh** [comment]
Screenshots below, filled on the left and line on the right. 
![Screenshot from 2024-06-19 11-55-44](https://github.com/containers/podman-desktop/assets/87311656/0ea82c8b-573b-4a25-a7e8-5d197b161ab4)
![image](https://github.com/containers/podman-desktop/assets/87311656/bcbd50ae-ce22-4e1c-a859-14dbf29a49af)

SVGs:
![config-secret-filled-icon](https://github.com/containers/podman-desktop/assets/87311656/5df429e0-2e34-48c8-92ba-b3a3e0d6b2d5)
![config-secret-icon](https://github.com/containers/podman-desktop/assets/87311656/aacf010b-93cb-4d38-b4a7-877ddba6337e)

Think this is an effective way to make it filled without resorting to just putting in all in a square

**Comment by cdrage** [comment]
> Screenshots below, filled on the left and line on the right. 
> 
> ![Screenshot from 2024-06-19 11-55-44](https://github.com/containers/podman-desktop/assets/87311656/0ea82c8b-573b-4a25-a7e8-5d197b161ab4)
> 
> ![image](https://github.com/containers/podman-desktop/assets/87311656/bcbd50ae-ce22-4e1c-a859-14dbf29a49af)
> 
> 
> 
> SVGs:
> 
> ![config-secret-filled-icon](https://github.com/containers/podman-desktop/assets/87311656/5df429e0-2e34-48c8-92ba-b3a3e0d6b2d5)
> 
> ![config-secret-icon](https://github.com/containers/podman-desktop/assets/87311656/aacf010b-93cb-4d38-b4a7-877ddba6337e)
> 
> 
> 
> Think this is an effective way to make it filled without resorting to just putting in all in a square

Looks great! WDYT @deboer-tim @feloy

**Comment by feloy** [comment]
> > Screenshots below, filled on the left and line on the right.
> > ![Screenshot from 2024-06-19 11-55-44](https://private-user-images.githubusercontent.com/87311656/341041511-0ea82c8b-573b-4a25-a7e8-5d197b161ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcwMTUsIm5iZiI6MTcxODc5NjcxNSwicGF0aCI6Ii84NzMxMTY1Ni8zNDEwNDE1MTEtMGVhODJjOGItNTczYi00YTI1LWE3ZTgtNWQxOTdiMTYxYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjRkYWMyYjk5YzhiYjkyNDE4OTk5MGQyZDQ2YmU1NDNlOTBhZGI5NmRiODU5ZTc3Mjc3ZGQ4ZjlmYjU1N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcdePRWD1IXy5WtMtO5L1sLPEfdyFmPWDCYx-8Gu6Ns)
> > ![image](https://private-user-images.githubusercontent.com/87311656/341042543-bcbd50ae-ce22-4e1c-a859-14dbf29a49af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcwMTUsIm5iZiI6MTcxODc5NjcxNSwicGF0aCI6Ii84NzMxMTY1Ni8zNDEwNDI1NDMtYmNiZDUwYWUtY2UyMi00ZTFjLWE4NTktMTRkYmYyOWE0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NmNiOTUzZjAwODcxYzUyZDA4NjRhZDY1NzdiZmRlNDU0NDhkNGVkNTVkZTBhNjZjYjE0MzZmOTA3ZTcxOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nt-Bg65365Z_cfuyNfLs13esvCBl6XXGqXxDfQG_Mlk)
> > SVGs:
> > ![config-secret-filled-icon](https://private-user-images.githubusercontent.com/87311656/341041653-5df429e0-2e34-48c8-92ba-b3a3e0d6b2d5.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcwMTUsIm5iZiI6MTcxODc5NjcxNSwicGF0aCI6Ii84NzMxMTY1Ni8zNDEwNDE2NTMtNWRmNDI5ZTAtMmUzNC00OGM4LTkyYmEtYjNhM2UwZDZiMmQ1LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTQ0Nzk0ZTM1ZjJlZWU1MWRjYTM0NDllYWI1YzUzMTcwMzM4NjIxOWM5YjQwMDBjNDFhZmRmMjhjMjljZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Wxoo8TtDScwL7JSrW7YK-vfFgbxqX4HvAPWK6MfqhI)
> > ![config-secret-icon](https://private-user-images.githubusercontent.com/87311656/341041658-aacf010b-93cb-4d38-b4a7-877ddba6337e.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTcwMTUsIm5iZiI6MTcxODc5NjcxNSwicGF0aCI6Ii84NzMxMTY1Ni8zNDEwNDE2NTgtYWFjZjAxMGItOTNjYi00ZDM4LWI0YTctODc3ZGRiYTYzMzdlLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNWZjZGFhMDVjMDUwZDYxMjUwNTExYTdlMTE4NThkYjc4ZWUzYWJhN2NhOGU3ODY3OTc3MTMwODEyMWFmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcOpruQoJ5r_uvgxtpt1SSY9diusmKEJulLIJQbkFPI)
> > Think this is an effective way to make it filled without resorting to just putting in all in a square
> 
> Looks great! WDYT @deboer-tim @feloy

Yes, looks great for me too!

**Comment by deboer-tim** [comment]
Here's what they would look like in context:

<img width="234" alt="Screenshot 2024-06-19 at 8 01 30 AM" src="https://github.com/containers/podman-desktop/assets/19958075/5721d4b6-3f85-47b7-81f5-58254babc8f9">

I almost wonder if this is one case where we don't need a solid/filled icon:

<img width="234" alt="Screenshot 2024-06-19 at 8 03 33 AM" src="https://github.com/containers/podman-desktop/assets/19958075/300f49ae-2a14-4e0a-bf0d-3171923c94d3">

**Comment by ekidneyrh** [comment]
Yah I prefer just using the same one for both too based on that screenshot.

**Comment by cdrage** [comment]
I agree on the no fill too. Let's ship it! ⛴️
