### ISSUE TITLE
Compose setup on Windows fails to use system SSL certificates, causing issues on systems with ZScaler installed

### ISSUE THREAD

**Issue by JayDoubleu** [containers/podman-desktop#7683]
### Bug description

When running the Compose setup on a Windows system that has ZScaler installed, the setup process fails to utilize the Windows system SSL certificates. This issue prevents the successful completion of the Compose setup, hindering the ability to use Compose on the affected system.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

- Install ZScaler or similar software on a Windows system
- Attempt to run the Compose setup on the same Windows system.

### Additional context

Expected behavior
The Compose setup should automatically detect and use the Windows system SSL certificates, even in the presence of ZScaler. The setup process should complete successfully, allowing the user to utilize Compose on their Windows system.

Actual behavior
The Compose setup fails to properly detect and use the Windows system SSL certificates when ZScaler is installed. As a result, the setup process encounters errors and is unable to complete successfully. This prevents the user from using Compose on their Windows system.

**Comment by JayDoubleu** [comment]
The same issue seems to be affecting other extensions too, although minikube installed just fine:

![image](https://github.com/containers/podman-desktop/assets/40270505/74c5a89d-ee31-4e4a-ac4e-95f86d381eeb)

**Comment by jeffmaury** [comment]
For information: https://github.com/nodejs/node/issues/51537
