### ISSUE TITLE
Support multiline messages in message dialogs

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#7685]
### Is your enhancement related to a problem? Please describe

Sometimes it is better to show message using several paragraphs. Below an example of what sign out confirmation request text could look like:

![image](https://github.com/containers/podman-desktop/assets/620330/5a821f0e-4485-4cf6-9ec3-fcf7f3ad92ab)

it could be multiple extension using the same authentication session. Where you see 'OpenShift Toolkit' in our case could be list of extensions:

OpenShif Local,
OpenShift Developer Sandbox

Current implementation ignores `\n` escape and shows everything in one line.

### Describe the solution you'd like

MessageBox component should split the message on `\n` and show every part as separate p or div element with padding.

### Additional context

Related to #6632.

**Comment by gastoner** [comment]
I've tried to work on this and added some new lines with some styles to achieve a format similar to the one used in the mockup.
![image](https://github.com/user-attachments/assets/fbc85f72-2636-4d24-971a-d8f9f6ac3f97)
But I would suggest to change width of the MessageBox, like so: 
![image](https://github.com/user-attachments/assets/ace7ec4e-8ced-480f-a04d-7233c286a0b5)
Any opinion on this? @dgolovin @deboer-tim @ekidneyrh @axel7083

**Comment by deboer-tim** [comment]
> Any opinion on this? @dgolovin @deboer-tim @ekidneyrh @axel7083

This width would not work for many of our dialogs, so I assume you mean it would check the width of the content and only reduce when things are narrow?

I'm fine with it but mostly up to @ekidneyrh.

**Comment by gastoner** [comment]
> This width would not work for many of our dialogs, so I assume you mean it would check the width of the content and only reduce when things are narrow?

Yes something like this, but I'm not sure about the "correct" width for it

**Comment by ekidneyrh** [comment]
I don't think we need to make the dialog narrower, as we would have to find a way to determine why and which ones to implement that on.

We could add some formatting into the dialog and have it look something like this:

![modal-signout](https://github.com/user-attachments/assets/580ec7b1-8a41-4ef1-b431-82a339a1653a)
