### ISSUE TITLE
Remove readonly attribute of input field in Kubernetes section of Preferences page

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#7689]
### Is your enhancement related to a problem? Please describe

It will make testing the page more straight forward, ATM we have to remove it manually.
Also might be a good idea to do it for the other select fields on Preferences page.

### Describe the solution you'd like

Remove the `readonly` attribute of the input element in Kubernetes section.

**Comment by deboer-tim** [comment]
I only see one browse button in Kubernetes preferences and it doesn't look readonly - can you clarify which button you mean?

**Comment by rostalan** [comment]
I see, my bad, I meant the Input field for path, which does have readonly attribute.
