### ISSUE TITLE
Provide a way to get the version of podman-desktop

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#770]
### Is your enhancement related to a problem? Please describe

Using the UI, it's hard to tell  which version is running

### Describe the solution you'd like

Maybe `Help -> About`

**Comment by benoitf** [comment]
👍 looks like the About menu is displaying correctly the version on macOS but not on Windows

**Comment by jeffmaury** [comment]
Can't see the Help -> About on Windows

![image](https://user-images.githubusercontent.com/695993/199763115-9e892b19-e837-4455-90b8-555e03feb404.png)

**Comment by benoitf** [comment]
https://user-images.githubusercontent.com/436777/199764668-d9ea6ba8-51c5-4861-bc69-05670d50a48f.mov



Yes, need to look why it's empty on Windows

**Comment by jeffmaury** [comment]
Still can't see the menu on Windows:

![image](https://user-images.githubusercontent.com/695993/217608264-4f96131d-92a2-4254-9714-3604a02c070f.png)

**Comment by benoitf** [comment]
@jeffmaury menu is displayed using the alt key

**Comment by jeffmaury** [comment]
Not user friendly, can't we have a better way ?

**Comment by benoitf** [comment]
I will close this one as it's there and keep open https://github.com/containers/podman-desktop/issues/1418 that is about an enhancement (better way)
