### ISSUE TITLE
Light mode for Create Pod

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7717]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-06-18 at 10 32 59 AM](https://github.com/containers/podman-desktop/assets/6422176/34b87160-f895-44c8-aa83-30af9b3f2294)

Unsure if this is already covered somewhere, but no light mode available for Create Pod

### Describe the solution you'd like

Light mode for Create Pod

**Comment by deboer-tim** [comment]
This is part of #7214 (issue for all of the form pages), but no reason we can't fix separately.

**Comment by deboer-tim** [comment]
This work was completed via another issue.
