### ISSUE TITLE
Light mode for Podman edit machine screen

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7731]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-06-18 at 11 29 55 PM](https://github.com/containers/podman-desktop/assets/6422176/fa59efd2-c8d6-4aa2-80a0-83db02689b16)

No light mode in the edit screen (font colour incorrect) for resources / podman machine

### Describe the solution you'd like

Light mode

**Comment by deboer-tim** [comment]
Already covered by #7548 (when in doubt, check the epic #4914), but I hadn't realized the edit is unusable. Suggest we leave this open in case we need to fix edit now but the rest later.
