### ISSUE TITLE
Auth file getting wiped out on shutdown

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7742]
### Bug description

It's not consistent, but .share/containers/auth.json appears to be getting emptied (from valid json to a blank file), evidently on shutdown.

I think this stack trace is related:
10:32:11 a.m. [main] [podman] Error checking for update TypeError: Object has been destroyed
    at _.send (node:electron/js2c/browser_init:2:73448)
    at Object.send (/Users/deboer/git/pd/packages/main/dist/index.cjs:122337:24)
    at ProviderRegistry.registerUpdate (/Users/deboer/git/pd/packages/main/dist/index.cjs:100652:20)
    at ProviderImpl.registerUpdate (/Users/deboer/git/pd/packages/main/dist/index.cjs:100525:34)
    at registerUpdatesIfAny (/Users/deboer/git/pd/extensions/podman/dist/extension.cjs:5441:21)
    at async checkForUpdate (/Users/deboer/git/pd/extensions/podman/dist/extension.cjs:5472:24)

### Operating system

macOS 14.5

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
On startup, the Podman extension registry-setup.ts updateRegistries() gets called and it registers anything in auth.json. So far, so good!

It then gets an onDidRegisterRegistry callback and rewrites the file. Not great, but rewriting the same contents back shouldn't actually hurt anything.

On shutdown, it gets an onDidUnregisterRegistry and tries to delete the registry from the file. It looks like sometimes this succeeds and other times it doesn't, hence the error above.

**Comment by deboer-tim** [comment]
Ok, this logic has been there for a long time, it seems something has caused PR #3136 to regress.

**Comment by cdrage** [comment]
So after a bunch of troubleshooting I think I've narrowed it down to this line:

https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/extension-loader.ts#L892

Commenting it out and doing `yarn watch` a bunch of times, I am no longer getting the "re-write" of the auth file.

The dispose was calling: https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/registry-setup.ts#L129

I believe that this dispose was added incorrectly as we should not be unregistering the registry  on shut down.

Unsure why it was added there and was wondering if you can give some insight @benoitf if it should be uncommented or not.

**Comment by benoitf** [comment]
you can remove it as stated on slack 👍
