### ISSUE TITLE
port in use flakey tests

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#7747]
### Is your enhancement related to a problem? Please describe

Getting a lot of flakey tests on e2e lately:

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/plugin/util/port.spec.ts > return valid port range
Error: Port 9002 is already in use.
 ❯ Server.<anonymous> src/plugin/util/port.ts:68:18
     66|       .on('error', (error: NodeJS.ErrnoException) => {
     67|         if (error.code === 'EADDRINUSE') {

Error: Error: Port 9002 is already in use.
 ❯ Server.<anonymous> src/plugin/util/port.ts:68:18
 ❯ Server.emit ../../node:events:519:28
 ❯ emitErrorNT ../../node:net:1925:8


     68|           reject(new Error(`Port ${port} is already in use.`));
       |                  ^
     69|         } else if (error.code === 'EACCES') {
     70|           reject(new Error('Operation require administrative privilege…
 ❯ Server.emit ../../node:events:519:28
 ❯ emitErrorNT ../../node:net:1925:8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 68 passed (69)
      Tests  1 failed | 908 passed (909)
   Start at  20:33:57
   Duration  16.39s (transform 2.32s, setup 14ms, collect 7.60s, tests 24.42s, environment 22ms, prepare 6.78s)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

With regards to port being in use.

### Describe the solution you'd like

Flakey test maybe using a different non-privileged port? Unsure.

### Additional context

@cbr7 @odockal @ScrewTSW

**Comment by cbr7** [comment]
@cdrage are you sure this is an e2e test? Because it doesn't look like it to me.

**Comment by deboer-tim** [comment]
> @cdrage are you sure this is an e2e test? Because it doesn't look like it to me.

Agreed, it is not e2e. I thought there were some recent changes to try to improve this but can't find it atm, so targeting for next sprint to make sure we look at it given the number of times it is failing recently.

**Comment by odockal** [comment]
Putting this back into backlog.

**Comment by jeffmaury** [comment]
Closing as I don't see much failures this time

**Comment by benoitf** [comment]
I still saw it yesterday on my PR :-)

**Comment by benoitf** [comment]
occurred just now https://github.com/containers/podman-desktop/actions/runs/10178450844/job/28152090524?pr=8297

**Comment by deboer-tim** [comment]
FWIW I've seen it ~3 times in the last week.

**Comment by benoitf** [comment]
reopening due to https://github.com/containers/podman-desktop/actions/runs/10195925424/job/28205601127?pr=8316
