### ISSUE TITLE
Issues with Experimental Light mode for 1.11.0

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#7750]
### Bug description

It seems there are no light mode version for the pages access through buttons from the additional actions sections of the main pages (e.g Play Kubernets YAML button from Pods page), all these pages are displayed in dark mode in PD version 1.11

https://github.com/containers/podman-desktop/assets/106525396/e0674d40-ab5b-4c2a-a61d-839bc4c86ddc

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install PD 1.11
2. Turn on light mode.
3. Go to "Play Kubernets YAML" page (or any menu accessed from additional actions buttons)
4. Notice the pages will be in dark mode.

**Comment by cbr7** [comment]
Additional note: I've also noticed that the notification on the dashboard that directs the user to create a podman machine is also shown in dark mode

<img width="1226" alt="image" src="https://github.com/containers/podman-desktop/assets/106525396/0461e90f-e295-4680-be21-fc2105a929fd">

Also of note that the podman machine creation workflow/menus are all in dark mode even if light mode is enabled

<img width="1135" alt="image" src="https://github.com/containers/podman-desktop/assets/106525396/53b137af-544e-475e-8bb4-6b8cca31bba9">
<img width="1135" alt="image" src="https://github.com/containers/podman-desktop/assets/106525396/14ece428-e584-44da-aad2-b904c6b430d1">

**Comment by deboer-tim** [comment]
The dashboard supercharge section/banner is tracked via #7608.
Form pages are tracked via #7214.
Onboarding (machine creation) are covered through #7547 and #7548.
The only thing I see that isn't already tracked is the Notifications section, @cbr7 do you want to open up a separate issue so that it's not buried, or change the title to focus on that?

In general you can scan epic #4914 to see what's done for light mode and what is still being tracked.

**Comment by odockal** [comment]
@deboer-tim Idea is to track all what we find during testing here and then compare with what we already know about. Please wait a little :) We can then close in case nothing new appears - or open separated issues, wdyt?

**Comment by odockal** [comment]
My findings so far, what is missing:
* Resources
  * Create New Cluster (Connection - machine, kind, sandbox, etc)
  * Connection -> Logs
  * Onboarding (again, any, will affect global onboarding - podman, compose, kubectl)
* General
  * dropdowns
  * top Input box (aka press kube-context switch in system tray)
  * any xterm, terminal, yaml viewer, etc. is also missing
* Dashboard
  * Notifications
* Forms
  * Build Image
  * Run Image
  * Pull Image
  * Play Kube
  * Deploy to Kubernetes
  * Create Volume
* Parts of the pages
  * Export Container - also, in containers details, it is missaligned on the page, it does not have its own page
  * Import container
  * Save Image
  * Load image
* System Bar
  * Tasks
  * Feedback
  * Troubleshooting
  * Help

**Comment by odockal** [comment]
@deboer-tim We have now hopefully complete list of issue related to light mode. We need to compare that with epic for light mode.

**Comment by deboer-tim** [comment]
Epic is #4914 for reference. I did a quick comparison and I _think_ the only thing were weren't tracking is the quick pick/top input box. Luca has fixed/PRs up for most of the forms in the current sprint, and we have ~half of the remaining work targeted to the next sprint.

**Comment by odockal** [comment]
@deboer-tim thanks! I will keep this open to compare in a while what all we got fixed.

**Comment by kpiwko** [comment]
Extensions also have issues with light mode, e.g. bootc is still dark.

**Comment by deboer-tim** [comment]
> Extensions also have issues with light mode, e.g. bootc is still dark.

The current bootc extension (v1.2.0) should have a light homepage and then a dark form (similar to most of Podman Desktop in 1.11), but extension issues are tracked in their own repos, e.g.:
https://github.com/containers/podman-desktop-extension-bootc/issues/536 for bootc
and
https://github.com/containers/podman-desktop-extension-ai-lab/issues/1209 for AI Lab.

**Comment by cbr7** [comment]
@deboer-tim  I've taken a look at the light mode support as it's currently on main branch and it seems to mostly match the issues completed in https://github.com/containers/podman-desktop/issues/4914 however I have noticed that there is no issue for the `Tasks` popup in the epic and currently there is no light mode for it.


<img width="1050" alt="image" src="https://github.com/user-attachments/assets/c7c7c41c-5606-48a4-98a1-feb0f3f25bdd">

**Comment by cbr7** [comment]
I've created issue https://github.com/containers/podman-desktop/issues/8111 for the Tasks popup light support.

**Comment by cbr7** [comment]
@deboer-tim I think I found one more element that needs to be migrated to light mode which is the dropdown menus when in collapsed form:

https://github.com/user-attachments/assets/9d98bb41-6339-4e5d-b040-52d571d0babf

**Comment by cbr7** [comment]
I've created https://github.com/containers/podman-desktop/issues/8390 to track the above issue

**Comment by odockal** [comment]
Input boxes still in dark theme.

![Screenshot_20240809_120847](https://github.com/user-attachments/assets/d2113b24-40ad-4887-8f73-9bcfb89666a7)
