### ISSUE TITLE
Set as default context does not work when creating a new developer sandbox

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#7751]
### Bug description

When creating a new developer sandbox, and ticking the "Set as default context" Button, the current context is not switched and stays whatever it was before

### Operating system

Win 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by odockal** [comment]
Dupe of https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/102 ?

**Comment by rostalan** [comment]
dupe
