### ISSUE TITLE
Exposing dark/light mode in API for extensions

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#7754]
### Is your enhancement related to a problem? Please describe

Extensions may want to know which mode is in use, dark or light, to adapt the display accordingly.

### Describe the solution you'd like

Have a way to know which mode is in use through the API exposed by Podman Desktop

**Comment by deboer-tim** [comment]
Can you give an example of how this would be used? Today we only have 'light' and 'dark', but the themes are extendable so there could be 'mocha', 'star trek', or 'beach'. I'm not sure knowing this would be useful to extensions, or maybe you're asking for additional metadata with each theme?

**Comment by feloy** [comment]
> Can you give an example of how this would be used? Today we only have 'light' and 'dark', but the themes are extendable so there could be 'mocha', 'star trek', or 'beach'. I'm not sure knowing this would be useful to extensions, or maybe you're asking for additional metadata with each theme?

If we add more themes, I would expect that these themes have dark/light declinations. A good example is the integration of a terminal in Podman Desktop. When PD is in light mode, you have to also set a light mode for the terminal. But even if the theme is different ("star trek light" mode for PD vs "80s light" mode for terminal), they will be both "light". And setting the light mode for the terminal needs some parameter to be set, based on the knowledge of the dark/light mode for PD.

**Comment by benoitf** [comment]
the extension relies on the colors set by Podman Desktop

so for the terminal it's also the same, the extension need to grab the value from the CSS colors

**Comment by benoitf** [comment]
and the extension can detect if it's light or dark relying on the `prefers-color-scheme`

closing
