### ISSUE TITLE
Error popup displayed after closing PD 1.11 application

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#7756]
### Bug description

When I close the PD application 1.11 on macOS, I'm always getting the popup error from below

![image (6)](https://github.com/containers/podman-desktop/assets/106525396/c47991c4-9270-4b2a-866a-dbff2beee6ac)

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install PD 1.11 version on macOS using universal dmg.
2. Open the app.
3. Close the app (ensure that the `Close on Exit` option is enabled)
4. Notice that the error popup is displayed after PD closes.

**Comment by odockal** [comment]
Here is the crash/error report. [pd-crash-on-close-report.log](https://github.com/user-attachments/files/15915706/pd-crash-on-close-report.log)
