### ISSUE TITLE
Ability to show/hide navigation items

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7758]
### Is your enhancement related to a problem? Please describe

As we add more navigation items there are more items that are rarely used, extensions that add 2 items but you only use one of them, or cases where you want to temporarily hide the icon without uninstalling the extension.

### Describe the solution you'd like

Users should be able to right-click on the navigation bar to see a list of all navigation items in a checkbox list, and easily add or remove the visible items.

**Comment by benoitf** [comment]
here it's not clear where the state is managed/handle

**Comment by deboer-tim** [comment]
It's user state but needs to be on disk, so maybe storing a set of the hidden ids in configuration would be easiest?

**Comment by benoitf** [comment]
I wasn't clear, I mean:

- is that the frontend that read the properties and display things
- backend that read the properties and then expose methods and frontend read the data from there

**Comment by deboer-tim** [comment]
Nav items from extensions are contributed via backend, but I can't think of any reason why the backend would need to know the full list of what we display (e.g. that there is a dashboard or extensions nav item), what's currently hidden, etc., so I would say this is all in frontend.
