### ISSUE TITLE
Kubernetes Navigation: Replace nav sections by group nav item + individual items

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7759]
### Is your enhancement related to a problem? Please describe

As we grow the set of Kubernetes objects, there are too many to keep in the main nav, even with the current collapsable nav section. However, moving to a single item has the drawback of requiring two clicks to get to anything (feels like a second-class citizen). The current form will also conflict with hiding nav items as we plan in #6774. 

### Describe the solution you'd like

Nav sections should be removed/replaced. Each of the Kubernetes pages should be contributed as separate nav items, and the group should be contributed as a special 'group' nav item. Clicking on a group nav item opens a submenu identical to the look of the Settings or the AI Lab extension today, with a list of all the nav items in the group.

It is important to point out that both the group and each individual nav item are 'regular' nav items. In particular, they could each be added or removed from the main navigation individually as per #7758. Kubernetes would initially appear as just the one group nav item with a submenu, but here are some examples of what the user could do:
- Add Deployments and Services to the main nav, while keeping the Kubernetes group also visible (to get to all of the other items).
- Add Nodes to the main nav and hide the Kubernetes group, because they're only using nodes at the moment.
- Hide everything, because they're not using Kubernetes.

**Comment by feloy** [comment]
There is a `group` type for the menu entries, currently used for the `Extensions` menu entry, but it does not seem compatible with what we want to do with the `Kubernetes` menu entry, as the Extensions menu button is not displayed itself, only the children of the group are.

@deboer-tim I suppose we want to define another type, for example `submenu` (as it will open a submenu).

**Comment by benoitf** [comment]
the pre-req of this issue is to have a new navbar menu for kubernetes

**Comment by benoitf** [comment]
one icon kube that will open a new menu with all items like for ai lab menu
