### ISSUE TITLE
Migrate extension nav group to individual nav items

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7763]
### Is your enhancement related to a problem? Please describe

In order to implement #6774 we need to replace both Kubernetes and Extensions navigation sections. Kubernetes is handled through #7759 but that's not a great default/don't need to wait to do extensions.

### Describe the solution you'd like

Kubernetes will use #7759 to add a new nav group item (plus individual nav items). Although we could use the same mechanism we probably want each newly installed extension to appear in the main nav, so the recommendation is to just contribute them as individual nav items for now. If we want to add a 'extensions group' later it would be easy enough to add.

**Comment by benoitf** [comment]
Before implementing anything globally, it needs to be validated by the implementation for extensions.

As if Kubernetes is moved to an extension, it should behave the same. And then I'm not sure it can behave in the same way depending on how it's implemented

**Comment by deboer-tim** [comment]
Aside from AI Lab (and possibly Kubernetes in the future), no other extension contributes more than one 'page'. I'd prefer to use #7759/#7761 to figure out if we keep the concept of nav groups and whether extensions can (easily) provide them, and use this issue to move single-page extensions 'out' of the nav section (and using the same registry as built-in pages) so that we could start supporting things like show/hide or handling too many items.
