### ISSUE TITLE
Navigation registry

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7765]
### Is your enhancement related to a problem? Please describe

In order to support upcoming navigation improvements we need a framework to support dynamic navigation items.

### Describe the solution you'd like

A simple navigation registry that can handle a list of nav items:
- id
- icon
- label
- dynamic counters

and be structured in a way to support future features like hiding items (#7758), nav groups (list of other items - #7759), or maybe notification dot / status.

Move the core existing navigation items (containers, pods, images, volumes, extensions) to this registry and start to replace the custom code in AppNavigation using the registry.

**Comment by benoitf** [comment]
It's not clear in the description if the registry is a UI/Renderer side or a main/plugin side.

if it's a registry like the other one they are 'main/plugin' side I'm not really sure of the benefit of moving everything on the main side ? as basically the navigation is a UI side.

We only need the preferences on the UI side

**Comment by deboer-tim** [comment]
I can't think of any reason for it to be in main at the moment, so probably easier to keep it in renderer. Ids would need to be saved to disk/config later (#7758). This work is implied by most of the other issues, but I felt I should break it out to be clear and deliverable separately.
