### ISSUE TITLE
Random preference's fields with a value sometime show and error: Value type provided is number instead of boolean

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7767]
### Bug description

In preferences, in any page, if one switches between Pref's menu items quickly, it sometime thrown an error next to a button/value/field.

 
![PreferencesErrorValue](https://github.com/containers/podman-desktop/assets/19164299/a2495223-8ec6-47b3-b94f-cb0592afaa74)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

```shell
Uncaught (in promise) Value type provided is number instead of boolean.
setTimeout (async)
r.$$.update @ NumberItem.svelte:27
fU @ scheduler.js:115
VE @ scheduler.js:79
Promise.then (async)
DE @ scheduler.js:20
dU @ Component.js:81
(anonymous) @ Component.js:139
(anonymous) @ PreferencesRenderingItemFormat.svelte:46
Promise.then (async)
Tme.r.$$.update @ PreferencesRenderingItemFormat.svelte:45
fU @ scheduler.js:115
VE @ scheduler.js:79
Promise.then (async)
DE @ scheduler.js:20
xi @ scheduler.js:26
showFallbacks @ tinro_lib.js:1
match @ tinro_lib.js:1
(anonymous) @ tinro_lib.js:1
i @ index.js:56
t @ tinro_lib.js:1
go @ tinro_lib.js:1
e @ tinro_lib.js:1
Show 16 more frames
Show less
```

**Comment by deboer-tim** [comment]
Just saw this for the first time - I turned off 'Exit on Close' and things looked fine, but after restarting (no value in config file) I saw this error. I tried to reproduce and can't.

**Comment by deboer-tim** [comment]
Given how sporadic this is I wonder if it is related to #7142.

**Comment by odockal** [comment]
@deboer-tim From observations I would not say so. I have seen the linked issue before. The error icon started to appear lately.

**Comment by dgolovin** [comment]
I spend considerable time trying to replicate it on macOS and have not seen it once.
I am closing it. Please reopen it if replicated with comment what steps might causing it.
