### ISSUE TITLE
add support for zstd compression for extensions

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#7806]
### Is your enhancement related to a problem? Please describe

today it supports only gzip compression but images published for extension images could be using zstd

### Describe the solution you'd like

add support for this compression algorithm

**Comment by tnk4on** [comment]
FYI.
Podman machien v5.1 has this issue(except WSL2).
https://github.com/containers/podman/issues/22813
It is not fixed.

**Comment by benoitf** [comment]
yes this is to handle this 'bug'
