### ISSUE TITLE
Install button overfloats from the podman provider card when Podman desktop is opened in default size

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7809]
### Bug description

![Screenshot_20240625_095539](https://github.com/containers/podman-desktop/assets/19164299/2e2d238c-9b1b-4f50-9fea-e53d10d11c6d)

### Operating system

Mac OS 14.5, M2

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by rostalan** [comment]
present on win 10 as well
