### ISSUE TITLE
Docker Desktop Extension installs never timeout or quit with an error message when something is wrong

### ISSUE THREAD

**Issue by redhatrises** [containers/podman-desktop#781]
### Bug description

When you attempt to install an extension and the install fails or never completes, the install never timeouts or stops attempting an install when there is an error message. This happens every time. I haven't tested on non-macOS installs to verify if this is more of an application than OS environment issue.

### Operating system

macOS Monterrey 12.6.1

### Version

next (development version)

### Steps to reproduce

Under Desktop Extensions, enter `asdfadsf`, and click `Install extension from the OCI image`

### Additional context

![image](https://user-images.githubusercontent.com/8398836/200074555-23996284-81c3-441c-b475-08271a26f861.png)

**Comment by benoitf** [comment]
thanks for the bug report @redhatrises, it'll be fixed by https://github.com/containers/podman-desktop/pull/782
