### ISSUE TITLE
Get rid of the deprecation warning about using of the imagePath flag when start podman machine

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7811]
### Bug description

we still use `imagePath` flag when starting podman machine resulting in the deprecation warning . Please use `image` flag which is new starting podman v5.

### Operating system

mac os 14.5

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by benoitf** [comment]
dup of https://github.com/containers/podman-desktop/issues/7273
