### ISSUE TITLE
'Value type provided is number instead of string.' when changing appearance mode in preferences.

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#7819]
### Bug description

When changing the appearance using the Appearance pop-up on Preferences page, sometimes, after leaving the page and returning, an error icon shows up with message "Value type provided is number instead of string..".

### Operating system

Win 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by odockal** [comment]
Dupe of #7767
