### ISSUE TITLE
Stopping Podman machine shows cmd execution error but stops anyways 

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#7822]
### Bug description

Trying to stop running Podman machine shows "stop failed" message in UI and also "Command execution failed with exit code 125" in Tasks, but afterwards stops the machine successfully. 

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Start a Podman machine (doesn't matter if rootful or rootless)
2. Stop the machine
3. Assert: machine stops without issues
    Actual result: stop failed message shows briefly before actually stopping and the stopping task is flagged as failed.

### Additional context

https://github.com/containers/podman-desktop/assets/57829934/8ef7ecbc-684d-47a4-9e9c-a164cc32211b

**Comment by jeffmaury** [comment]
Is that still relevant. I cannot reproduce on Win11Pro.
