### ISSUE TITLE
E2E Tests are failing on GHA ubuntu with Playwright updated to 1.45.0

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7830]
### Bug description

We are seeing e2e tests failing en mass on GHA ubuntu runner when dependabot updated playwright dependency from 1.44.1 to 1.45.0. Happening on multiple repos.

Example: https://github.com/containers/podman-desktop/actions/runs/9660260892

### Operating system

Ubuntu 22.04

### Installation Method

Other

### Version

next (development version)

**Comment by benoitf** [comment]
might be related to https://github.com/microsoft/playwright/issues/31442

**Comment by cbr7** [comment]
Issue was fixed in upstream and will be available when Playwright 1.46 will be released.

**Comment by cbr7** [comment]
Fix is available in PW 1.45.1.
