### ISSUE TITLE
extensions using npm package with dependency on `http` leads to crash

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7833]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/42176370/cb63fab5-0523-4f16-bb12-480444181568)

error is raised here https://github.com/containers/podman-desktop/blob/7d997640c368bb62037bed8ed337c732d78b3484/packages/main/src/plugin/module-loader.ts#L90

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Add `@kubernetes/client-node` npm package to any extensions, import it and use it (avoid tree shaking).

### Additional context

cc @benoitf

**Comment by benoitf** [comment]
note that it works for simple extensions but not in case of development mode for extensions using multiple workspaces

for example ai-lab has node_modules in the root folder while the extension is in packages/backend folder.

so at some point we try to load `/my/folder/node_modules/request/index.js` and try to see if it's matching an extension but as the packages/backend is in a subfolder it doesn't work then it throw an error

**Comment by dgolovin** [comment]
@axel7083 Do you run extension using `yarn watch --extension-folder /path/to/extension` command?

**Comment by dgolovin** [comment]
@benoitf Extension is needed only when override is a function. What function does is returning 'ext.api' attribute. In this case ext acts like a cache. If there is no extension it should just cache module for `parent.path`.

**Comment by dgolovin** [comment]
@axel7083 What is git repo for the extension that has this problem?

**Comment by benoitf** [comment]
https://github.com/axel7083/ai-studio/tree/chore/kubernetes-client
