### ISSUE TITLE
status icon are weird in some pages

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7868]
### Bug description

| images | containers |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop/assets/42176370/705f7ca5-46df-43cc-99c1-24d125af3932) | ![image](https://github.com/containers/podman-desktop/assets/42176370/96462e4e-0b78-4c39-a27e-f8d8c416e63c) |

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

`yarn watch`

**Comment by axel7083** [comment]
Seems to be related to AI-Lab, when I install on  windows the latest version from the catalog (v1.1.2) the icons are getting weird.

Moreover, the following log appear
```
Expected contributes.icons.default.fontPath for icon id brain-icon to be included inside extension's folder (~\.local\share\containers\podman-desktop\plugins/ghcriocontainerspodmandesktopextensionailab).
```

**Comment by deboer-tim** [comment]
Can you confirm disabling/removing the extension fixes the problem? (we still need defensive code to not fail in this case, but would be good to confirm)

**Comment by benoitf** [comment]
and check with https://github.com/containers/podman-desktop/pull/7926

**Comment by axel7083** [comment]
> Can you confirm disabling/removing the extension fixes the problem? (we still need defensive code to not fail in this case, but would be good to confirm)

It does not fix the issue, it remove the weird icon when I disable AI Lab, then re-appear on re-enabling

**Comment by axel7083** [comment]
Cannot reproduce in latest version
