### ISSUE TITLE
If you create a container with the GUI, it doesn't appear under the Containers tab.

### ISSUE THREAD

**Issue by Luxvao** [containers/podman-desktop#787]
### Bug description

I created a container with the GUI and it doesn't show up under containers.

### Operating system

Windows 11 Home 21H2 22000.1098

### Version

0.9.0

### Steps to reproduce

Open Podman Desktop, click "Create container" then select an image and create a container with it. Then check the "Containers" tab.

### Additional context

If you create a container with `podman run -d --name test debian` it will show up. And if you create a container with the "Create container" button and run `podman ps -a` it will show up. So it does get created, but it doesn't show up.

**Comment by benoitf** [comment]
Hello @Luxvao , could you tell how you created the container (image selected and options) ?

Also, could you provide the log displayed in the console
`View` Menu then `Toggle Developer Tools` and then `Console`

If you see events, please send the name of events
for example it could be
```
main ↪️ event is {status: 'create', id: '2fa954d5e6234645e2866a26cfd0033648791b4df2c1ea5bfcb58ea78d4b134b', from: 'quay.io/fedora/fedora:37', Type: 'container', Action: 'create', …}
index.ts:916 main ↪️ event is {status: 'init', id: '2fa954d5e6234645e2866a26cfd0033648791b4df2c1ea5bfcb58ea78d4b134b', from: 'quay.io/fedora/fedora:37', Type: 'container', Action: 'init', …}
index.ts:916 main ↪️ event is {status: 'start', id: '2fa954d5e6234645e2866a26cfd0033648791b4df2c1ea5bfcb58ea78d4b134b', from: 'quay.io/fedora/fedora:37', Type: 'container', Action: 'start', …}
index.ts:916 main ↪️ event is {status: 'die', id: '2fa954d5e6234645e2866a26cfd0033648791b4df2c1ea5bfcb58ea78d4b134b', from: 'quay.io/fedora/fedora:37', Type: 'container', Action: 'die', …}
index.ts:916 main ↪️ event is {status: 'cleanup', id: '2fa954d5e6234645e2866a26cfd0033648791b4df2c1ea5bfcb58ea78d4b134b', from: 'quay.io/fedora/fedora:37', Type: 'container', Action: 'cleanup', …}
```

if I click on the play icon of the image `quay.io/fedora/fedora:37`

Let me know also if you're seeing some 'socket hang up' errors in the console

Also, can you try to go the Settings/Extensions/Podman and click on `disable` and then `enable`to re-establish the connection to the `events` endpoint.

And try again ?


It should work, as the following example:

https://user-images.githubusercontent.com/436777/200542144-035c14d9-5030-431d-840d-3f31f433ff4b.mp4

**Comment by Luxvao** [comment]
@benoitf If I refresh the GUI (CTRL + R) it appears, but if you close and open podman desktop it doesn't change. The events:
```
main ↪️ event is {status: 'history', id: 'cad541368aa067f115195bb9bd5208a1c64e77b7de6157de9fa8cd065d60c5fb', Type: 'container', Action: 'history', Actor: {…}, …}
index.ts:916 main ↪️ event is {status: 'create', id: 'cad541368aa067f115195bb9bd5208a1c64e77b7de6157de9fa8cd065d60c5fb', from: 'sha256:4075ad3faa28f4c352f48e56a65bfabdf728249744a99ae515606c1ad36d28b6', Type: 'container', Action: 'create', …}
index.ts:916 main ↪️ event is {status: 'history', id: 'cad541368aa067f115195bb9bd5208a1c64e77b7de6157de9fa8cd065d60c5fb', Type: 'container', Action: 'history', Actor: {…}, …}
index.ts:916 main ↪️ event is {status: 'create', id: 'cad541368aa067f115195bb9bd5208a1c64e77b7de6157de9fa8cd065d60c5fb', from: 'sha256:4075ad3faa28f4c352f48e56a65bfabdf728249744a99ae515606c1ad36d28b6', Type: 'container', Action: 'create', …}
```
There are no socket hang up errors, disabling and enabling the extension doesn't work. I run the latest debian image from the docker hub. Also I have a question. Is the popup for creating containers supposed to exit if you click "Start container"? It doesn't on windows.

https://user-images.githubusercontent.com/95533447/200585232-7b1fd80d-0bde-4c02-9c87-33df5db573c1.mp4

**Comment by benoitf** [comment]
@Luxvao thanks for the report. I'll analyse the data.

And yes the popup should disappear

There is an error in your console during the video
![image](https://user-images.githubusercontent.com/436777/200589537-4f7339e0-bcc9-4ec5-8aa8-c3d74bdfc7cf.png)

So probably there is something related

**Comment by benoitf** [comment]
@Luxvao do you have version 0.9.0 or 0.9.1 of Podman Desktop ?

**Comment by Luxvao** [comment]
@benoitf I think it's 0.9.1, but how do I check?

**Comment by lstocchi** [comment]
@Luxvao do you still have this issue? Could you please try with the latest release?

**Comment by Luxvao** [comment]
@lstocchi Not anymore. I reinstalled both podman desktop and podman and it started working.

**Comment by lstocchi** [comment]
Thank you @Luxvao . Closing it then 🚀
