### ISSUE TITLE
Podman Desktop wrongfully escapes special characters in proxy settings

### ISSUE THREAD

**Issue by TheConen** [containers/podman-desktop#7894]
#### Given:

I am a user behind a corporate proxy. To be able to access public registries, I need to go through the corporate proxy.
I also have some internal registries that cannot be accessed through the proxy. Instead, they must be accesed directly.

#### When:

I set my proxy settings in Podman Desktop with the correct HTTP Proxy, HTTPS Proxy and No Proxy values (NO_PROXY containing more than one value as a comma-separated list).
![grafik](https://github.com/containers/podman-desktop/assets/7814881/edd69a5a-f835-4062-b9c6-e4267a2ce5b1)

#### Then

Expected Result:
I can pull images from public registries and from my internal registry

Actual result:
I can pull images from public registries, but not from my internal registry.

When updating the Proxy settings in the Podman Machine, Podman Desktop escapes the commas in the `NO_PROXY` setting in `/etc/systemd/system.conf.d/default-env.conf` with a backslash. This renders the `NO_PROXY` setting useless, causing Podman to use the Proxy for all requests - including the ones to the internal registry that should not go through the proxy.

![grafik](https://github.com/containers/podman-desktop/assets/7814881/4a179119-2cfd-42b8-9977-3ed00d5f978d)

Manually removing the \ and restarting the Podman machine will have everything working as expected - Podman being able to access public and internal registries. However, when updating the proxy settings in Podman Desktop, it will recreate the file with backslashes escaping the commas again, breaking access to the internal registry.

### Operating system

Windows 10 Enterprise 22H2 19045.4529

### Installation Method

Installer from website/GitHub releases

### Version

1.11.1

### Steps to reproduce

- Setup a proxy
- Setup a registry that is not accessable through the proxy, only directly
- Setup your Proxy settings in Podman Desktop, with NO_PROXY containing multiple entries as a comma-separated list
- Apply the Proxy settings in Podman Desktop
- Restart the Podman machine
- Try to pull an image from your internal registry

### Relevant log output

`default-env.conf` that Podman Desktop currently creates:
```
[Manager]
DefaultEnvironment=http_proxy=http://proxy.mydomain.com:8080
DefaultEnvironment=https_proxy=http://proxy.mydomain.com:8080
DefaultEnvironment=no_proxy=127.0.0.0/24\,registry.mydomain.com
DefaultEnvironment=HTTP_PROXY=http://proxy.mydomain.com:8080
DefaultEnvironment=HTTPS_PROXY=http://proxy.mydomain.com:8080
DefaultEnvironment=NO_PROXY=127.0.0.0/24\,registry.mydomain.com
```

`default-env.conf` that Podman Desktop should create:
```
[Manager]
DefaultEnvironment=http_proxy=http://proxy.mydomain.com:8080
DefaultEnvironment=https_proxy=http://proxy.mydomain.com:8080
DefaultEnvironment=no_proxy=127.0.0.0/24,registry.mydomain.com
DefaultEnvironment=HTTP_PROXY=http://proxy.mydomain.com:8080
DefaultEnvironment=HTTPS_PROXY=http://proxy.mydomain.com:8080
DefaultEnvironment=NO_PROXY=127.0.0.0/24,registry.mydomain.com
```

**Comment by jochenr** [comment]
Yes, actually this issue is the root cause of what I desribed here and was closed:
https://github.com/containers/podman-desktop/issues/7129#issuecomment-2126690375

**Comment by jochenr** [comment]
It's not only in "NO_PROXY"

If you have username/password in the proxy URL that contain sepecial characters they are escaped, too:

```
...
DefaultEnvironment=http_proxy=http://myusername:myPawwordWith!inside@proxy.mydomain.com:8080
DefaultEnvironment=https_proxy=http://myusername:myPawwordWith!inside@proxy.mydomain.com:8080
...
```

results in /etc/systemd/system.conf.d/default-env.conf
```
...
DefaultEnvironment=http_proxy=http://myusername:myPawwordWith\!inside@proxy.mydomain.com:8080
DefaultEnvironment=https_proxy=http://myusername:myPawwordWith\!inside@proxy.mydomain.com:8080
...
```

**Comment by TheConen** [comment]
This completely breaks Podman in corporate environments. In my company, we are currently trying to replace Docker with Podman and this is a major blocker.

**Comment by feloy** [comment]
The issue seems related to the `podman machine` command, I've created an issue in the podman repo: https://github.com/containers/podman/issues/23277
