### ISSUE TITLE
Add tabs to Images and Volumes pages

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#7947]
### Is your enhancement related to a problem? Please describe

The tables in Containers and Pods have tabs at the top of the table that sort them into All, Running or Stopped.
![image](https://github.com/containers/podman-desktop/assets/87311656/4f721b38-917b-402f-8ab8-78c328b2a7b9)

### Describe the solution you'd like

Could we add these to the images and Volumes pages also? The names of the tabs might have to differ, maybe USED and UNUSED? Whatever is the appropriate language when talking about them.

This would add unity across the tables and enhance organisations.

**Comment by deboer-tim** [comment]
For Images and Volumes it's probably reasonable enough to add All / Used / Unused, but it does feel like a change for consistency vs utility.

However, we have 5+ similar pages for Kubernetes and I struggle to think what might be useful in most of these. Maybe in something like Ingress and Routes we could have All / Ingress / Routes but not sure about Deployments or Services? If we're really serious about this would we add All to a page if there was nothing else?

**Comment by ekidneyrh** [comment]
I won't put it in places where it's not useful. I thought it would work in the 4 main pages we have: containers, pods, images and volumes. I should've specified that in the description. I just think it's odd not to have it in the Images and Volumes pages, given I could see it being useful there. 

If it's a case where it's adding a feature on those pages for the sake of it, then I wouldn't implement it.

**Comment by deboer-tim** [comment]
Stevan and I were chatting yesterday and one idea came up: these tabs are effectively just search filters anyway, what it we used a different kind of control and moved them up to the same line as the search bar? This would give more space to the table as well, and maybe provide a common place for other table styling/filtering controls.

**Comment by ekidneyrh** [comment]
> These tabs are effectively just search filters anyway, what it we used a different kind of control and moved them up to the same line as the search bar? This would give more space to the table as well, and maybe provide a common place for other table styling/filtering controls.

That's a good idea. Maybe something like how GitHub does it, adding the filter to the search bar when chosen:

![image](https://github.com/containers/podman-desktop/assets/87311656/0fedf821-b528-4a83-96fa-585d7a86f408)

I can close this issue and open another for controls for tables.
