### ISSUE TITLE
Podman Desktop on Windows: "Podman needs to be set up" notication

### ISSUE THREAD

**Issue by raphaelquati** [containers/podman-desktop#7969]
### Bug description

Fresh install (v1.11.1). This happens with earlier versions too.

Every boot, this notification alwas appears: "Podman needs to be set up"

![image](https://github.com/containers/podman-desktop/assets/815086/b380e534-b15a-456d-ac06-5d71433b316d)

Click on notification does nothing (it dissapear, but after some seconds apears again).

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Fresh install

**Comment by lstocchi** [comment]
I've just tried using the main branch and i was not able to replicate.
By looking at the code the notification is sent when the machine check returns nothing or fails. Maybe a temporary unreachable machine could be the cause of it

**Comment by slemeur** [comment]
I've been getting it on my side this morning. started the machine from the cli. closed the notification and it never came back

**Comment by lstocchi** [comment]
> I've been getting it on my side this morning. started the machine from the cli. closed the notification and it never came back

Did you use the latest release or the main branch?

**Comment by slemeur** [comment]
I was on main branch

**Comment by deboer-tim** [comment]
This is random, but I saw a similar problem last week. In my case I eventually traced it back to a really odd configuration setting, something like `"podman.binary.path":30`. No idea how it got there, but of course removing it solved the problem. So if you do see this repeatedly, please check .local/share/containers/podman-desktop/configuration/settings.json.
