### ISSUE TITLE
Podman Engine/Machine not detected after initial install on Mac

### ISSUE THREAD

**Issue by evanshortiss** [containers/podman-desktop#7979]
### Bug description

I installed Podman Desktop on a new MacBook. No prior installation existed. After the install process completed and Podman Desktop started I was prompted to "Set Up" Podman from within the Podman Desktop UI. 

Clicking the "Set Up" button brought me to a "Podman Setup" screen where I could enable/disable autostart and click "next" or "cancel". Clicking next showed a "Podman installed" UI with a sample `podman ps` command.

The "Set Up" notification kept showing on the Podman Desktop dashboard until I restarted Podman Desktop.

### Operating system

macOS 14.5

### Installation Method

Installer from website/GitHub releases

### Version

1.11.0

### Steps to reproduce

Install Podman on a macOS machine without a prior installation. Make sure to run `podman machine init` during the install. I also disabled the kubectl CLI plugin during install since I already had it installed via brew.

### Additional context

Version 1.11.1

**Comment by rostalan** [comment]
what exactly is the issue? the 'set up' banner being present after the setup is finished?

**Comment by evanshortiss** [comment]
@rostalan yes. The only way to resolve it seems to be to restart Podman Desktop.

**Comment by rostalan** [comment]
Is there no close button present in the right upper corner? Or is the notification popping back after closing it and leaving the page? Afaik it shouldn't pop back in as soon as you close it...

**Comment by evanshortiss** [comment]
Looks like there was an icon in the upper right corner to close it. However, the fact that it keeps appearing suggests something is broken. I'd expect the notification to disappear if everything's working as expected.


![Screenshot 2024-07-16 at 12 00 54 PM](https://github.com/user-attachments/assets/6811041a-0a6e-4426-9c0a-3e8f8aa9d488)

**Comment by lstocchi** [comment]
Closing. It should be fixed by https://github.com/containers/podman-desktop/pull/8171 . Feel free to reopen if you face it again
