### ISSUE TITLE
Ability to view a basic list of all containers from the dashboard

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8]
## Description ##
As a user, I should be able to get the list of my containers running with my different container engines. 
![Containers (3)](https://user-images.githubusercontent.com/1636769/157667616-be350621-3f45-41d6-b4ff-0bcc0cff5355.png)

## Acceptance criteria ##
- The list must display containers running with each different container engines
- For each containers:
  - a small icon is displaying the status of the container
  - we display the name of the container, its image's source
  - a tag with the status of the container

**Comment by benoitf** [comment]
done
