### ISSUE TITLE
CLI Tools should support installing the binary

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8003]
### Is your feature request related to a problem? Please describe

![image](https://github.com/containers/podman-desktop/assets/42176370/deda1158-0602-401b-abae-ac1b771d9b36)

Currently we still register CLITool using the extension API 

https://github.com/containers/podman-desktop/blob/4f9e876667fe5ab48d26bd9d2d1ab728e3a89dd5/packages/extension-api/src/extension-api.d.ts#L4350

> ℹ️ I first wanna say I do not like the wording `create`, we should be using some kind of `register`, as we do not create anything.

When ~creating~ a CLI tool through the extension API we are getting a `CLITool` object

https://github.com/containers/podman-desktop/blob/4f9e876667fe5ab48d26bd9d2d1ab728e3a89dd5/packages/extension-api/src/extension-api.d.ts#L4319-L4336

On this object we can call `registerUpdate` to register an update, the following will allow a visual indication to the user, that an update is possible

![image](https://github.com/containers/podman-desktop/assets/42176370/2686cdd1-c7d4-4600-85ac-c3ea69cb0045)

Something similar should be possible to trigger the installation of the CLI Tool.

### Describe the solution you'd like

My proposal would be to change the `cli.createCliTool` signature. The CliToolOptions are not flexible enough.

First let's combine the `version` and `path` to a single **optional** property (proposal: binary, open to suggestion)

```diff
export interface CliToolOptions {
  name: string;
  displayName: string;
  markdownDescription: string;
  images: ProviderImages;

- version: string;
- path: string;
+  binary?: {
+   version: string;
+   path: string;
+  }
}
```

To avoid making too much changes to the API, we could add a new method `registerInstall` next to the `registerUpdate` in the `CliTool` interface.

**Comment by axel7083** [comment]
I made a quick branch to demo how it could be done with the change proposal above https://github.com/axel7083/podman-desktop/tree/feature/cli-install-workflow

⚠️ it does not work like it, I changed the code locally of compose and kubectl to use the new api 

https://github.com/containers/podman-desktop/assets/42176370/7ccc27ac-d966-460b-b7da-4643e94daa86

cc @deboer-tim

**Comment by deboer-tim** [comment]
I had a long response typed up, but I'm going to try shorter:
- If we need breaking changes elsewhere then `binary` is good, but I'm wondering if it's easier to just make those two properties optional.
- Having both optional might make sense anyway - e.g. it's possible that we know where the binary is, but weren't able to parse the version.
- Can we just register install/uninstall helpers the same way as registerUpdate/updateVersion? Again, might be simpler to not break the core API, and UI can react based on what actions are available & applicable.

Re: demo. I would have been happy with an interim step where Compose was visible here and it just said 'not installed' because nothing had registered that action, but you've fixed it all. Awesome! :) I don't think it's quite clear enough that Compose is not installed initially, and not clear if the X means you can uninstall, but the capability is great and we could tweak the UI.

**Comment by axel7083** [comment]
> I had a long response typed up, but I'm going to try shorter:
> 
> * If we need breaking changes elsewhere then `binary` is good, but I'm wondering if it's easier to just make those two properties optional.

Those two properties are for the same object, that can be here or not, they need to be tied up together.

> * Having both optional might make sense anyway - e.g. it's possible that we know where the binary is, but weren't able to parse the version.

I can argue that if you are not able to get the version, the binary might be broken and you should not register it.

> * Can we just register install/uninstall helpers the same way as registerUpdate/updateVersion? Again, might be simpler to not break the core API, and UI can react based on what actions are available & applicable.

This is the solution that I see, extensions can **register** a CLITool, with or without an existing binary associated, then they can either `registerUpdate` or `registerInstall` on it.

https://github.com/containers/podman-desktop/blob/60be265cb13aa63a678569b9c32fde52a46d27ac/packages/extension-api/src/extension-api.d.ts#L4341-L4345 

> Re: demo. I would have been happy with an interim step where Compose was visible here and it just said 'not installed' because nothing had registered that action, but you've fixed it all. Awesome! :) I don't think it's quite clear enough that Compose is not installed initially, and not clear if the X means you can uninstall, but the capability is great and we could tweak the UI.

I would not be very happy as a user to see not installed and not being to do anything about it. However, this could be a temporary fix.

Sadly, I did not support the `uninstall`, the cross was just a quick hack that is displayed when no action is available. But if this is the path we want to follow, I would be happy to open a PR

**Comment by axel7083** [comment]
After discussion in https://github.com/containers/podman-desktop/issues/8041 and during standup, we have a better understanding of what we want the CLI Tool to be possible.

## Requirements 

### (1) `install` / `upgrade` / `downgrade` to a specific version (not always the latest)

A user may want to install a speficic version of a tool (compatibility reasons etc.)

### (2) Sharing CliTools

Other extensions should be able to get information about installed cli tools, E.g. an extension might need a kind cluster, and requires a specific version of kind to operate.

### (3) Exising tools should not be updatable

if the user already has binary installed before podman-desktop, in places that podman-desktop would not have install it, they should be marked as `external` or not updatable.

## API Definition **proposal**

```ts
export interface CliToolRelease {
    id: string;
    version: string;
    publish: Date;
}

export interface CliToolBinaryInfo {
    version: string;
    path: string;
    // when the binary has not been installed by podman-desktop, should be in read-only
    permission: 'r' | 'rw';
}

/**
 * The options to provide when registering a CLI Tool
 */
export interface CliToolOptions {
    id: string;
    name: string;
    displayName: string;
    markdownDescription: string;
    images: ProviderImages;
    // binary info
    binary?: CliToolBinaryInfo;
    // method to get the versions available
    getVersions(logger: Logger, page?: number): Promise<CliToolRelease[]>;
    // install a given version
    // @return the path of the installed binary
    install(logger: Logger, release: CliToolRelease): Promise<string>;
    // given a binary info, should proceed to uninstall
    uninstall(logger: Logger, binaryInfo: CliToolBinaryInfo & { permission: 'rw' }): Promise<void>;
}

/**
 * The CliTool object
 */
export interface CliTool extends Disposable {
     readonly id: string;
     readonly name: string;
     readonly displayName: string;

     readonly binaryInfo: CliToolBinaryInfo;
     onDidUpdateVersion: Event<CliToolBinaryInfo>;
}

/**
 * The object returned by registerCliTool provide additional method 
 */
export interface WritableCliTool extends CliTool {
     // @remark send undefined to mark as uninstalled
     update(binaryInfo: CliToolBinaryInfo | undefined): void;
}

export namespace cli {
  export function registerCliTool(options: CliToolOptions): WritableCliTool;
  // given an id, return the corresponding CLI Tool
  export function getCliTool(id: string): CliTool;
  // All cli tools currently known to the system.
  export const all: readonly CliTool[];
  // An event which fires when `cli.all` changes.
  export const onDidChange: Event<void>;
}
```

The namespace `cli` has been enhance, strongly inspired by the `extensions` namespace, providing methods for other extensions to access object information.

The `WritableCliTool` is here to allow extensions to manually update the CliTool if they start an update/unsinstall/install process by external mean.

The CliToolOptions provided in the `registerCliTool` is way more complete than before, enforcing extensions to manage the full lifecycle of the binary (installation, unsinstall, and get versions)

The `getVersions()` here will allow the system to manage itself the update mechanism. Here is the workflow:

- (1) Extension register a binary
- (2) The core will get the versions available for this binary using the `getVersion()`
- (3) The core will find the latest version using the `publish` property, and compare the version to the binaryInfo.version installed.
- (4) If they match => the install version is the latest, otherwise a new update is available !

ℹ️ If the binary info is in permission read-write, the system offer the user the possibility to _switch version_

### Bonus 

The core will be able to define itself some kind of interval to check for updates.

cc @deboer-tim @cdrage @dgolovin

**Comment by axel7083** [comment]
Another simpler approach would be to reuse what has already been done with the Provider interface. 

They already support some methods:

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L602

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L605

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L610

We might want to move them inside the CLITool interface, and makes the Provider extend the CLITool interface
