### ISSUE TITLE
Reduce number of buttons on table pages

### ISSUE THREAD

**Issue by ekidneyrh** [containers/podman-desktop#8017]
### Is your enhancement related to a problem? Please describe

We need to reduce the visual clutter when there are more than 2 buttons. Having five call-to-action buttons that all look the same can be confusing.

### Describe the solution you'd like

Set a rule that there’s no more than 2 action buttons, and then the rest can go under an ‘Other’ or ‘More’ button, like so:
![Screenshot from 2024-07-10 11-25-08](https://github.com/containers/podman-desktop/assets/87311656/102f611e-764c-40ab-830e-f3509e739b23)
![Screenshot from 2024-07-10 11-25-01](https://github.com/containers/podman-desktop/assets/87311656/ae280896-887e-47a5-bdb1-549c33933a9b)

**Comment by axel7083** [comment]
I am wondering if the styling of the dropdown button is not a bit weird compared to the other part where we are dropdowns.

First the places concerned by this change directly would be `Images` and `Volumes`

![image](https://github.com/containers/podman-desktop/assets/42176370/57fd3eea-b210-450a-b946-f77b3a367d33)

![image](https://github.com/containers/podman-desktop/assets/42176370/ff3b11e9-c819-4c27-a3d3-18f7167eefde)

When looking at any detailed page, we switch from the button primary style to square action button 

![image](https://github.com/containers/podman-desktop/assets/42176370/6cd89523-6c4a-4205-82d3-a9300b8e1685)

And I feel like this is inconsistent ? I don't know, we might be able to say, those are actions related to the current object, so styling different. 

However, in the detailed page, a voluntary choice to display all actions compared to the action in the tables was made. So it is weird that on some page we would group some actions, and in other display all of them on purpose.

Moreover, I fear to see dropping the number of usage of those buttons as they would be hidden.

**Comment by cdrage** [comment]
I believe we should also "de-emphasize" the prune button or somehow make it not as noticeable as the others.

There's been a handful of times I've accidentally pressed that and almost wiped out my entire cluster's pods 🤣

**Comment by ekidneyrh** [comment]
> When looking at any detailed page, we switch from the button primary style to square action button
> 
> ![image](https://private-user-images.githubusercontent.com/42176370/347828028-6cd89523-6c4a-4205-82d3-a9300b8e1685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDQ2MTksIm5iZiI6MTcyMDcwNDMxOSwicGF0aCI6Ii80MjE3NjM3MC8zNDc4MjgwMjgtNmNkODk1MjMtNmM0YS00MjA1LTgyZDMtYTkzMDBiOGUxNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEzMjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZjI1Y2JiY2Q1YmY5N2MyZDRiMDZjZjlkMDFlZjExN2UwZDQzMzk2ZGJhN2FjMjVlZTlmNzgzZDM4NWUwNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_vtTk-u1wryBCZk1XeuCxc0Uum9d_rXlhGtDesGBUA)
> 
> And I feel like this is inconsistent ? I don't know, we might be able to say, those are actions related to the current object, so styling different.
> 

Yeah you're right. It would be better to have those buttons be icons i think. I can make a mock-up for this to see what it would look like. 

> However, in the detailed page, a voluntary choice to display all actions compared to the action in the tables was made. So it is weird that on some page we would group some actions, and in other display all of them on purpose.
> 

If they're different syles then I dont think it would be weird. It's a way to make more space and stop the eye scanning over all these bright purple buttons. But having them as icons instead might be the move. 

> Moreover, I fear to see dropping the number of usage of those buttons as they would be hidden.

We could put less used actions there? I'm sure the user would know to check there if an action they are looking to make isn't immediately visible.

**Comment by ekidneyrh** [comment]
![image](https://github.com/user-attachments/assets/fe766976-5d79-4f2c-b3b3-c3c478689a72)

Using images as an example, as it has a lot of buttons. We could use the icons and then have the tool tips give more info like they already do.

**Comment by ekidneyrh** [comment]
Closing as opened https://github.com/containers/podman-desktop/issues/8189 as an alternative fix.
