### ISSUE TITLE
feat: kind extension should register CLI Tool  

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8031]
### Is your enhancement related to a problem? Please describe

The `kind` binary is not listed in the `Cli Tools` page

### Describe the solution you'd like

Kind should add the binary to the cli tools listing

**Comment by axel7083** [comment]
cc @deboer-tim

**Comment by deboer-tim** [comment]
> cc @deboer-tim what do you think ?

A big +1, this would be a better place than the current Kind statusbar item.

FYI it came up during planning discussion yesterday and we don't want to rush to add it to onboarding (want to make sure everything there is simple and rock solid first), but IMHO CLI Tools should be the one place to see all CLI tools that extensions know about and whether they are installed. And over time for each be able to install, and upgrade or uninstall as appropriate.

**Comment by slemeur** [comment]
+1, will be an important improvement
