### ISSUE TITLE
Improve design for CLI Tools card to support new actions

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8041]
### Is your feature request related to a problem? Please describe

Currently the CLI Tools page only support displaying the tool, and offering the update mechanism for it if available.

Here are the two examples.

![image](https://github.com/containers/podman-desktop/assets/42176370/4a11466c-2fe9-4353-a767-a01297762a19)

### Describe the solution you'd like

We want to have more than one action/state.

Let's break it down.

- `install-available`: the tool is not installed, and we want to offer the user the action of installing it
- `update-available`: the tool is installed, and a new version is available
- `installed`: the tool is installed, and is the latest version
- `uninstall`: the tool is installed, and it can be uninstalled.

> ℹ️ Very important, we have some scenarios where the tool **cannot** be updated nor uninstalled: when the tool has not been installed by podman-desktop. If the tool has been installed in a place where podman-desktop would not place it, it is not managed by us, it can be used, but not remove/updated.

We have to consider other elements, today we do not display the `path` where the tool/binary is installed, we have access to this information, therefore we should probably display it, or at least have a tooltip ?

**Comment by deboer-tim** [comment]
+1. FWIW issue #5215 is also open to show the path. IMHO we don't need to show any 'state' here, it should be clear by what info and actions are available.

**Comment by axel7083** [comment]
Here are some ideas/mockup I made, I tried to display the different state possible, but I am not really liking the buttons

![image](https://github.com/user-attachments/assets/80939d78-c973-4ec7-99f0-6954e3062ff6)

**Comment by dgolovin** [comment]
@axel7083 @benoitf It seems that update check and update to latest version is not implemented yet. Should I implement it or improve UI only and use what we have right now?

We seems already have more than one action and path requirements implemented.

![Image](https://github.com/user-attachments/assets/84e68b41-8387-4a78-8299-f2cf615ab5f9)

**Comment by axel7083** [comment]
@dgolovin I opened https://github.com/containers/podman-desktop/issues/8838 to make a distinction between Upgrade and Change version, I think this issue can be closed ?

**Comment by dgolovin** [comment]
@axel7083 closing it then. Let's open more specific issues like #8838.
