### ISSUE TITLE
Installation of folder does not work on Windows with home folder containing spaces

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#806]
### Bug description

Installation of podman failed because my Windows user name is 'Jeff MAURY' thus the home folder has spaces

### Operating system

Windows 11 Pro

### Version

0.9.1

### Additional context

![image](https://user-images.githubusercontent.com/695993/201102891-0e0f5bf3-0c2a-4846-ad0b-1bc33f4e1cff.png)

**Comment by benoitf** [comment]
thanks for the report @jeffmaury

**Comment by anjannath** [comment]
I think this comes from podman-desktop itself, i tried using the installer stand-alone and that worked. we need to escape any whitespaces in the command string [here](https://github.com/containers/podman-desktop/blob/acb7a36cba4f60bbb8e97a3cb4ac4b87591fb618/extensions/podman/src/util.ts#L46)
