### ISSUE TITLE
Unable to find qgis rpm under EPEL 9

### ISSUE THREAD

**Issue by vgrme** [containers/podman-desktop#8065]
### Bug description

Hi Team, 

Im trying to install qgis on RHEL 9.4.
I'm unable to find qgis rpm under EPEL 9
Under EPEL 8 it is available - https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/q/qgis*
Please add or share the rpm. Thanks 

### Operating system

RHEL 9.4

### Installation Method

Other

### Version

1.11.1

### Steps to reproduce

NA

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by odockal** [comment]
@vgrme Hey, thanks for report. Can you please add more info how is this package being missing in RHL 9.4 connected to podman-desktop, I am lost a bit here?

**Comment by odockal** [comment]
Closing as unrelated.
