### ISSUE TITLE
Light mode for "Create Podman Machine"

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8077]
### Is your enhancement related to a problem? Please describe

Looked on the list but couldn't' find it #4914 ,

But light mode does not appear correctly for create podman machine.

I think we may have fixed it but this may be a regression?

![Screenshot 2024-07-15 at 10 35 20 AM](https://github.com/user-attachments/assets/e21030db-2682-41c7-8b1f-834038f3b891)

![Screenshot 2024-07-15 at 10 34 12 AM](https://github.com/user-attachments/assets/bb8b11d8-c4b2-46ec-a138-834b0a0e3129)

### Describe the solution you'd like

Light mode for create podman machine.

**Comment by cbr7** [comment]
Issue is present in all screens related to "Create new ..." like Kind cluster/Minikube/etc

https://github.com/user-attachments/assets/d5b5bfc4-080c-4671-8a30-d0b2e35ae695
