### ISSUE TITLE
Add padding to all terminal screens.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8079]
### Is your enhancement related to a problem? Please describe

![Screenshot 2024-07-15 at 10 47 59 AM](https://github.com/user-attachments/assets/a7a6e481-d115-4488-ae97-4b30ee11949c)

I've noticed throughout all our terminal outputs it's a bit hard to read as the letters go right to the edge.

This wasn't very noticeable on dark mode, but with light mode it's very noticiable.

### Describe the solution you'd like

Padding to all terminal screens.

**Comment by deboer-tim** [comment]
We have a lot of terminals, would be good to have a common parent and add this once vs modifying lots of terminals.
