### ISSUE TITLE
Notification circle now "pops" out of bottom bar

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8080]
### Bug description

![Screenshot 2024-07-15 at 10 49 29 AM](https://github.com/user-attachments/assets/bfe8e0a2-d8eb-455c-9cdb-bb3088439d96)

Unsure if this is intentional or not? @ekidneyrh @deboer-tim that it pops out of the bottom bar section?

### Operating system

mac M1

### Installation Method

None

### Version

1.11.1

**Comment by deboer-tim** [comment]
It was not intentional, but I was debating if it was a 'feature' because it does draw the attention better. :) I'll let @ekidneyrh decide what the correct behaviour is.

**Comment by ekidneyrh** [comment]
> It was not intentional, but I was debating if it was a 'feature' because it does draw the attention better. :) I'll let @ekidneyrh decide what the correct behaviour is.

I don't like it jutting out of the status bar like that, I think it should be reverted to the original size / proportion. Having the dot a different colour like red would make it stand out better, but I think that's a separate issue.
