### ISSUE TITLE
Configurable Podman install location on Mac

### ISSUE THREAD

**Issue by dansiviter** [containers/podman-desktop#810]
### Is your enhancement related to a problem? Please describe

The desktop expects Podman to be in several places but doesn't actually look in the user `PATH` which means if the laptop is locked down (i.e. corporate) it won't work.

### Describe the solution you'd like

Either respect user `PATH` or allow configuration of where Podman is installed.

**Comment by benoitf** [comment]
yes on macOS electron is not having access PATH access but would it be fine if we're able to customize the location of Podman binary within the tool ?

**Comment by dansiviter** [comment]
@benoitf Yea, customising the binary location would suffice.

**Comment by cdrage** [comment]
Some notes while I implement this:

* Implemented into `package.json` of the podman plugin for automatic loading
* Setting should appear under Preferences & not extension (as it related to podman binary not the machine created)
* There is a bug with `scope:` with `package.json` of it not appearing under Preferences and for now I'll proceed with implementing with the setting currently appearing under `Extensions > Podman`

**Comment by cdrage** [comment]
@dansiviter 

Quick clarification, when filling out the custom location, do you expect to provide the binary directory (ex. /Users/username/bin` or the actual binary? (ex. /Users/username/bin/podman).

My implementation #941 implements the "directory" not full pathname which is how I interpreted this issue.

Just wanted to clarify!

**Comment by cdrage** [comment]
Hey @dansiviter the way I interpreted this issue is adding an additional path to $PATH for your system to search.

Just for clarification, did you want Podman Desktop to add an ADDITIONAL path to $PATH, or simply: "search this dir, nothing else"?

**Comment by dansiviter** [comment]
Hey @cdrage, I would imagine it has a field which defaults to the existing paths to maintain backwards compatibility but you could set it other values to search for the binary. An extension to this could be to also set environment variables so you could put `$PATH` and it would search that too.
