### ISSUE TITLE
Create podman machine should allow image URL not only local file path

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#8109]
### Is your enhancement related to a problem? Please describe

podman machine init allows to specify a bootable image as a local file path or an URL, the implementation in Podman Desktop should allow the same

![Image](https://github.com/user-attachments/assets/3858e4e0-de33-4baa-abe1-26eb0c8415d1)

### Describe the solution you'd like

Allow to specify an URL for this field and update the descriptin

### Additional context

- [Property editor implementations](https://vscode.dev/github/dgolovin/podman-desktop/blob/main/packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.svelte#L84) 
- [Connection creation or editing form implementation](https://vscode.dev/github/dgolovin/podman-desktop/blob/main/packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte#L35)

**Comment by afbjorklund** [comment]
~~Podman Machine (v5) does not allow URL or file path anymore, it now requires a bootable image.~~

* https://github.com/containers/podman-desktop/issues/7273

Something like this (not an URL):

`quay.io/podman/machine-os:5.1`


EDIT: You can _also_ use registry

**Comment by jeffmaury** [comment]
> Podman Machine (v5) does not allow URL or file path anymore, it now requires a bootable image.
> 
>     * [Podman v5 issues a warning about a deprecated parameter #7273](https://github.com/containers/podman-desktop/issues/7273)
> 
> 
> Something like this (not an URL):
> 
> `quay.io/podman/machine-os:5.1`

Is this wrong: https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html

**Comment by afbjorklund** [comment]
> > Something like this (not an URL):
> > `quay.io/podman/machine-os:5.1`
> 
> Is this wrong: https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html

I don't think it is wrong, just not updated? Now it uses `podman machine os apply` instead.

But it could be that docker:// URL and OCI image filepath are still allowed, with the new OS?
Just that if updating the input field, it also needs to allow a plain registry-style image name.

EDIT: This still works: `--image docker://quay.io/podman/machine-os:5.1` (though not HTTP)
