### ISSUE TITLE
CRC extension is not working with Flatpak

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#811]
### Bug description

There is a CRC binary not found error

### Operating system

Linux

### Version

0.9.1

### Steps to reproduce

Use CRC + Podman Desktop on Linux with flatpak installation

### Additional context

probably, it's because we don't spawn the command with flatpak utility so it tries to run the command within flatpak scope

**Comment by mairin** [comment]
A potential workaround for this would be to use Flatseal (https://flathub.org/apps/com.github.tchx84.Flatseal) on the Podman Desktop flatpak to add the crc path to it.

**Comment by benoitf** [comment]
closing as OpenShift local extension should be on https://github.com/crc-org/crc-extension

**Comment by rsrchboy** [comment]
I'm still seeing this with the flatpak install.

![image](https://github.com/containers/podman-desktop/assets/59620/a726c194-3869-4d20-af95-e77337f05180)

`podman-desktop` reports the extension version is v1.3.0.

![image](https://github.com/containers/podman-desktop/assets/59620/b00dc948-8e70-48e2-b721-4607d9facc14)

Is this expected?
