### ISSUE TITLE
Light mode support for Tasks popup

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8111]
### Is your enhancement related to a problem? Please describe

The Tasks popup doesn't support light mode.

### Describe the solution you'd like

Define any missing colors in the light mode palette and get the Tasks popup working in light mode.

**Comment by deboer-tim** [comment]
Which tasks popup do you mean? Can you confirm you were testing on a build from this week? (#8046 should have fixed tasks at the end of last week)

**Comment by cbr7** [comment]
@deboer-tim I posted a screenshot in the main tracking issue here https://github.com/containers/podman-desktop/issues/7750#issuecomment-2232786165

I'm using latest build from main branch, so given that that PR was merged 5 days ago, yes it must be in.

**Comment by deboer-tim** [comment]
Never mind, I found the image in #7750 - when you have tasks it's fine but the 'no task'/empty screen wasn't fixed in the tasks issue #7344. We can fix it here.

**Comment by deboer-tim** [comment]
I noticed the Task icon at upper left is missing in light mode too.
