### ISSUE TITLE
Release 1.12

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#8135]
### Is your enhancement related to a problem? Please describe

Need to cut 1.12.0 release

### Describe the solution you'd like

Cut the release (see [RELEASE.md](https://github.com/containers/podman-desktop/blob/main/RELEASE.md) file).

### Additional context

- [x] #8267
- [x] #8288

**Comment by cdrage** [comment]
Blog post, updates to site as well as posting to social media has all been completed. Closing issue!
