### ISSUE TITLE
Add light mode banners for featured list

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8140]
### Bug description

Light mode:

![Screenshot 2024-07-17 at 2 29 29 PM](https://github.com/user-attachments/assets/9d2e78ed-bbca-4d5d-b4d4-f208c899551e)

Dark mode:
![Screenshot 2024-07-17 at 2 31 03 PM](https://github.com/user-attachments/assets/8a2030fd-75c8-4441-a121-ad18b9ce4270)

### Operating system

mac m1

### Installation Method

None

### Version

1.11.1

**Comment by cdrage** [comment]
@deboer-tim 

Unsure what to do with this to be honest. Is this one of the few cases where hardcoding it to be white is applicable since all the banner pages use dark backgrounds?

**Comment by deboer-tim** [comment]
Maybe a question for @ekidneyrh ? Either we could supply a text color with the image, or confirm that we'll always use dark backgrounds and hardcode it.

**Comment by ekidneyrh** [comment]
Ooo that's an awkward one, it's hard to know since we don't know what future feature images there will be. We could have them be white and then if there's one that doesn't / can't use white text, I could let you know? But I will keep that in mind going forward.

**Comment by axel7083** [comment]
A suggestion from @benoitf when implementing the recommendation banner was to supply two images, `dark` and `ligth`.

Currently we provide only an image

https://github.com/containers/podman-desktop/blob/8dc78b830f48490a275f18e4a34be5b82a62dd5b/packages/main/src/plugin/recommendations/recommendations-api.ts#L28-L29

however, we would do the same as ColorDefinition 

https://github.com/containers/podman-desktop/blob/cfeb27546799febf3383b236e5602bbcee204970/packages/api/src/color-info.ts#L21-L24

Therefore the text color would not have to change, but the background do.

We are not exposing the recommendation banner to any external, therefore the change would not break anything; If we follow this road, we would have to provide two new versions,

- a light theme `ai lab` banner
- a light theme `Red Hat extension pack` banner

ref for recommendation banner discussion https://github.com/containers/podman-desktop-internal/issues/243

**Comment by deboer-tim** [comment]
That's probably a better option, since any hard-coded text color often wouldn't match the theme. I don't think API breakage is a real concern here since the use is scoped.

@ekidneyrh what do you think of this direction and could you produce these two images with a lighter theme?

**Comment by ekidneyrh** [comment]
If that's the best thing to do, then that's no problem! Just to confirm then the text stays white?

**Comment by deboer-tim** [comment]
> If that's the best thing to do, then that's no problem! Just to confirm then the text stays white?

The text color would be picked up from the theme like everywhere else - so typically white text (dark mode) and black text (light mode), but as we've done any new theme might have slight variations. The existing banners work for dark mode with light text, we need ones that would work for light mode with dark text (e.g. replacement for first image above).

**Comment by ekidneyrh** [comment]
okay I understand now! Thanks. I'll post those here soon.

**Comment by ekidneyrh** [comment]
![rh-ext-bg-light](https://github.com/user-attachments/assets/d8fe9b16-eb92-421b-8efa-eac5c7c6497c)
![rh-ext-bg-light](https://github.com/user-attachments/assets/903d98f0-8197-4ce0-bb14-b791edf1b93a)
![ai-lab-bg-light](https://github.com/user-attachments/assets/122fda52-5cd3-40eb-8da6-9c63bde41ffb)
![AI-Lab-illustration-bg-light](https://github.com/user-attachments/assets/89e73510-c033-474a-8d6a-8aba1ecde0c7)

Let me know if these work!

**Comment by axel7083** [comment]
@cdrage do you want to rename the issue and keep it assigned ?

**Comment by cdrage** [comment]
> ![rh-ext-bg-light](https://private-user-images.githubusercontent.com/87311656/353857839-d8fe9b16-eb92-421b-8efa-eac5c7c6497c.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDQ1NDEsIm5iZiI6MTcyMjQ0NDI0MSwicGF0aCI6Ii84NzMxMTY1Ni8zNTM4NTc4MzktZDhmZTliMTYtZWI5Mi00MjFiLThlZmEtZWFjNWM3YzY0OTdjLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjAzZTEwZmRjNmVjMjI5ZTNkN2JiM2YxZGY0NThkNDc1MDkyZDM4M2IwODc1NTljNzUzY2YyODNjYmRjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EneWEa7yer7-HAUD4qsl7fQYXDHx6_5x3BdF8vgp3jY) ![rh-ext-bg-light](https://private-user-images.githubusercontent.com/87311656/353857915-903d98f0-8197-4ce0-bb14-b791edf1b93a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDQ1NDEsIm5iZiI6MTcyMjQ0NDI0MSwicGF0aCI6Ii84NzMxMTY1Ni8zNTM4NTc5MTUtOTAzZDk4ZjAtODE5Ny00Y2UwLWJiMTQtYjc5MWVkZjFiOTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYmIxNzc5MzRkOGUwNGZmOGFiOGI0MWI3ZTQ5Njc2YTJjOWNiNzZhOGQ1YzZhOTNkMTgzMjE2ZDc5MTQ4MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TRgXwp2bNdgUosvG6IT19wWZNuoKQbfJiUpDgQqA3I4) ![ai-lab-bg-light](https://private-user-images.githubusercontent.com/87311656/353858737-122fda52-5cd3-40eb-8da6-9c63bde41ffb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDQ1NDEsIm5iZiI6MTcyMjQ0NDI0MSwicGF0aCI6Ii84NzMxMTY1Ni8zNTM4NTg3MzctMTIyZmRhNTItNWNkMy00MGViLThkYTYtOWM2M2JkZTQxZmZiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4OTU0MGJjZGI2ZDkzMjIyYjYwYmRmYjVmMmExZGEzMzIxMGY0NTRkZjM3NzE2OGNiZDg5Zjc0ODljZTgzNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s2lpwOy3lnptLdIt7_INh7_sular7VELWlFa_AApaxI) ![AI-Lab-illustration-bg-light](https://private-user-images.githubusercontent.com/87311656/353858744-89e73510-c033-474a-8d6a-8aba1ecde0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDQ1NDEsIm5iZiI6MTcyMjQ0NDI0MSwicGF0aCI6Ii84NzMxMTY1Ni8zNTM4NTg3NDQtODllNzM1MTAtYzAzMy00NzRhLThkNmEtOGFiYTFlY2RlMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTI4ODdkZjE1YzIwMGJhNTRjZGJhOTA4YzE1MWIxZWRlMGY2YmJkMjhhNjRiYWZiOGFiNzMzZTczNjI4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hcu-jT3nfht57Zq9UyHzwgWx3h1Qdt9HvecVDj9lJLk)
> 
> Let me know if these work!

The pink and light blue look amazing! I like them.

I've gone ahead and renamed the issue as well.
