### ISSUE TITLE
Add ARM64 Support To publish-to-winget.yaml

### ISSUE THREAD

**Issue by marshallwp** [containers/podman-desktop#8160]
### Is your enhancement related to a problem? Please describe

The current [publish-to-winget.yaml](https://github.com/containers/podman-desktop/blob/d08425e19c463e6f84d4a84348417e0b0abc5432/.github/workflows/publish-to-winget.yaml#L65-L69) workflow only publishes the x64 installer to the [winget manifest](https://github.com/microsoft/winget-pkgs/blob/affcd3dda1ce028f4daae96ee53af37456146938/manifests/r/RedHat/Podman-Desktop/1.11.1/RedHat.Podman-Desktop.installer.yaml). This means that despite officially supporting Windows on ARM, users cannot install the ARM64 build via winget.

### Describe the solution you'd like

1. Update the winget manifest to list both installers (I'm working on this, see: https://github.com/microsoft/winget-pkgs/pull/163917).
2. Update publish-to-winget.yaml to include URL to both the x64 and ARM64 installers in space-delimited format. e.g., `wingetcreate update <PackageIdentifier> --urls "<InstallerUrl1>|x64" "<InstallerUrl2>|arm64"`

These must be done in this order as `wingetcreate update` requires the number of URLs in an update to match that in the existing manifest.

### Describe alternatives you've considered

I mean I could just update the manifest on winget...but then you wouldn't be able to publish future releases to winget using your existing pipeline.

**Comment by benoitf** [comment]
@BinaryWizard904 will you work on 2. (update publish-to-winget action) ?

**Comment by marshallwp** [comment]
@benoitf, yes, I'll go ahead and take a look at that.

**Comment by marshallwp** [comment]
I've created a pull request that makes the needed changes the publish-to-winget.yaml file.  Additionally, the dependency, https://github.com/microsoft/winget-pkgs/pull/163917 was merged, so the number of URLs being updated will match the number in the manifest.
