### ISSUE TITLE
Locator Resolution Issue in E2E Test on Windows VM

### ISSUE THREAD

**Issue by amisskii** [containers/podman-desktop#8169]
### Bug description

While running an end-to-end (E2E) test debugging workflow on a Windows Virtual Machine (VM), I encountered an issue with the resolution of locators. The following code is supposed to retrieve the title attribute of an element with the role **status**:
`const currentState = await this.page.getByRole('status').getAttribute('title')`

However, during the test execution, this locator is referring to two different elements, leading to the test failure. Despite inspecting the page, there is only one HTML element with the  **status** role.

### Operating system

Windows

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

- Run the Debugging Desktop E2E Tests with Podman workflow with the following parameters:
  -     Podman Desktop repo fork: amisskii
  -     Podman Desktop repo branch: kind-cluster-tests
- Observe the test output and inspect the page at the moment of error.

### Additional context

![Screenshot from 2024-07-19 15-51-03](https://github.com/user-attachments/assets/5b986ed7-0b3b-4440-8083-8b1685b681ba)
![Verify_that_the_deployed_Pod_is_running_failure](https://github.com/user-attachments/assets/813341b6-ab4e-42c8-ad37-ce4937c4cafb)

**Comment by odockal** [comment]
I am thinking that this is the problem with missing ARIA functionality in DetailsPages. Something like #5966.

**Comment by odockal** [comment]
Fixed by https://github.com/containers/podman-desktop/pull/8196.
