### ISSUE TITLE
notification created by extensions does does disappear after disposal 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8172]
### Bug description

When creating a Notification in an extension using `window.showNotification`, we are getting a disposal 

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L1962

however, calling `dispose` on it does not seems to clear it from the TaskManager.

### Operating system

Fedora 40

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

```ts
// in activate function
  const disposable = window.showNotification({
    type: 'info',
    title: 'I am a notification created from an extension',
  });
  setTimeout(() => {
    disposable.dispose();
  }, 2000);
```

### Additional context

=> The dipose only remove it from the Dashboard. Not the TaskManager

**Comment by axel7083** [comment]
Might be solved by https://github.com/containers/podman-desktop/pull/8144 (need to check)

**Comment by lstocchi** [comment]
fixed by https://github.com/containers/podman-desktop/pull/8171
