### ISSUE TITLE
Light mode for MonacoEditor

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8201]
### Is your enhancement related to a problem? Please describe

We use MonacoEditor in many places, complete oversight on my part that they aren't terminals (#7545) and they need to support light mode as well.

### Describe the solution you'd like

Do something similar to #7545 to add light mode (and maybe reuse same themes).

**Comment by benoitf** [comment]
for Monaco editor, probably need to change here
https://github.com/containers/podman-desktop/blob/main/packages/renderer/src/lib/editor/MonacoEditor.svelte#L39

and in case of light theme, use `vs` rather than `vs-dark`

**Comment by deboer-tim** [comment]
Related: #7596
