### ISSUE TITLE
Light mode for Docker Desktop extensions

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8217]
### Is your enhancement related to a problem? Please describe

Light mode for DD extensions.

### Describe the solution you'd like

We need to confirm that we're setting the HTML color-scheme correctly when launching DD extensions, or fix it if we aren't.

**Comment by benoitf** [comment]
for now, using system mode it's changing the colors as expected (light if operating system is using light mode and dark if OS is using dark mode) but if we force light mode only in the app, the extension is not displayed using light mode but use the dark mode
