### ISSUE TITLE
Deleting a non default podman machine cause prompt that says default machine is not the current default

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8219]
### Bug description

It seems that currently whenever the user deletes a podman machine from PD that is not set to default and the default machine is up and running the user will still get a podman machine is not default prompt to be displayed, even though the machine running is the default one.

https://github.com/user-attachments/assets/a6dc301a-d3f6-439d-9209-dac69813ca81

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Create a podman machine and start it and ensure it's the default machine.
2. Create a second podman machine from PD but do not start this one.
3. After creating the second podman machine, from Settings -> Resources delete the second podman machine.
4. Notice that you will be prompted a popup that informs that the current podman machine(the first one) is not default and to make it default, even though the first machine was always the default one.

**Comment by cbr7** [comment]
@lstocchi I think this might be a regression from https://github.com/containers/podman-desktop/pull/7627 I'm not sure.

**Comment by lstocchi** [comment]
@cbr7 i'll give this a look. Is your default machine rootful or rootless? Or the result is the same with both?

**Comment by cbr7** [comment]
The default machine was the rootful one, the one that was started first. The rootless machine was never started at all ever.

**Comment by lstocchi** [comment]
Tested on both windows and mac. On win everything works fine.
On mac it happens bc after you delete a machine, the connection of the running one is always set to the rootless connection.
E.g
i have `machine-A` running
```
podman system connection ls
NAME            | DEFAULT
machine-A       | false
machine-A-root  | true
```
i create `machine-B`
```
podman system connection ls
NAME            | DEFAULT
machine-A       | false
machine-A-root  | true
machine-B       | false
machine-B-root  | false
```
i delete `machine-B`
```
podman system connection ls
NAME            | DEFAULT
machine-A       | true
machine-A-root  | false
```

it looks a podman bug. Are you aware of this behavior @benoitf ?
i don't think we can do much on our side. Podman Desktop behaves correctly for me

**Comment by lstocchi** [comment]
Ah ok my bad memory still shows up. https://github.com/containers/podman-desktop/pull/7627 has been created as a workaround for this kind of problem https://github.com/containers/podman/issues/22993 . So it is a known behavior 😆 
I think we can close this @cbr7 . We have to wait for a fix from the upstream
