### ISSUE TITLE
logging of extension should contain a prefix

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#822]
### Is your enhancement related to a problem? Please describe

When looking at the logs, if the extension is not saying that it's for a given extension, it's hard to tell which extension is logging what

### Describe the solution you'd like

id of the extension should be added before the message being logged.

for example

instead of 
```
[main] Could not find podman socket at
```

it should be

```
[main] [extension:lima] Could not find podman socket at
```

### Describe alternatives you've considered

It could be alternative form of the `[extension:id]`

**Comment by sfrunza13** [comment]
I would like to work on this, would you accept manual concatenation of the extension name to the message to be logged?

**Comment by benoitf** [comment]
@sfrunza13 yes 
I've assigned the issue to you
Thanks for contributing

**Comment by sfrunza13** [comment]
Many logging messages have the name of the extension within the message such as `console.debug('Error while pinging docker as podman', err);` or `console.log('stopping "extension name" extension');`

Should the prefix be added to all logged messages, these included?

**Comment by benoitf** [comment]
yes, all of them. I mean, solution is to override console.* Methods to add the prefix. Then, inside the extension we don't add any I'd, it's already/automatically added

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/872
