### ISSUE TITLE
Podman desktop setup - WSL import of guest OS failed: exit status 0xffffffff

### ISSUE THREAD

**Issue by rahulbtchrya** [containers/podman-desktop#8233]
### Bug description

I have a new installation of Podman desktop 5.1.1 on Windows11. I am using the Podman desktop installer for restricted environments. When trying to setup a podman machine, I am getting the below error:

_Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: the WSL import of guest OS failed: exit status 0xffffffff_

The logs show the below messages:

_Importing operating system into WSL (this may take a few minutes on a new WSL install)...
WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
Enable "Virtual Machine Platform" by running: wsl.exe --install --no-distribution
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED
Error: the WSL import of guest OS failed: exit status 0xffffffff
Command execution failed with exit code 125
Command execution failed with exit code 125
Error: the WSL import of guest OS failed: exit status 0xffffffff_

I have enabled "Windows-Hypervisor-Platform". Have rebooted the machine. Also below is the output from the wsl and bcedit commands:

_PS C:\WINDOWS\system32> wsl.exe --install --no-distribution
The operation completed successfully.
PS C:\WINDOWS\system32> bcdedit /enum | findstr -i hypervisorlaunchtype
hypervisorlaunchtype    Auto_ 

Please help.

### Operating system

Windows11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Open Podman Desktop, click the Setup button and click Next.

### Relevant log output

```shell
_Importing operating system into WSL (this may take a few minutes on a new WSL install)...
WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
Enable "Virtual Machine Platform" by running: wsl.exe --install --no-distribution
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED
Error: the WSL import of guest OS failed: exit status 0xffffffff
Command execution failed with exit code 125
Command execution failed with exit code 125
Error: the WSL import of guest OS failed: exit status 0xffffffff_
```

### Additional context

Podman Desktop v5.1.1 on Windows11

**Comment by lstocchi** [comment]
Hi @rahulbtchrya , i didn't get what's your current state. I see you tried to install wsl and failed because `Virtual Machine Platform` was disabled. Then you enabled it and installed wsl. What's the problem you're facing now?

**Comment by rahulbtchrya** [comment]
> Hi @rahulbtchrya , i didn't get what's your current state. I see you tried to install wsl and failed because `Virtual Machine Platform` was disabled. Then you enabled it and installed wsl. What's the problem you're facing now?

Hi @lstocchi , here is what I did:
1. Installed Podman Desktop for 'restricted environments' following the documentation in the link : https://podman-desktop.io/docs/proxy
2. Opened Podman Desktop and clicked the Setup button. Got the wsl error.
3. Enabled "Windows-Hypervisor-Platform" and rebooted the machine.
4. Opened Podman Desktop and clicked the Setup button. Got the same wsl error.

**Comment by lstocchi** [comment]
@rahulbtchrya what's the output of these two commands? 
`wsl --version`
`wsl -l -v`

**Comment by rahulbtchrya** [comment]
Hi @lstocchi , please find the output of the command below:

C:\>wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3880

C:\>wsl -l -v
Windows Subsystem for Linux has no installed distributions.

Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.

Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error code: Wsl/WSL_E_DEFAULT_DISTRO_NOT_FOUND

**Comment by lstocchi** [comment]
I wanted to see which WSL version it was using. 
What if you try to install Ubuntu (i think `wsl --install` is enough, or you can use `wsl --install -d Ubuntu`) and then repeat `wsl -l -v`? Which is the output? Is it using WSL 1 or 2?

If you open `Turn Windows features on or off` view, you can see the `Virtual Machine Platform` is actually checked?
![image](https://github.com/user-attachments/assets/e370ae89-bec0-444f-bb21-bf5434341a78)

If not, check it and reboot. Then make sure you're using WSL 2. If you're on WSL 1, run `wsl --set-default-version 2`

**Comment by rahulbtchrya** [comment]
Hi @lstocchi 
I verified that the Virtual Machine Platform is enabled in Windows. 
I ran the command 'wsl --set-default-version 2' and it ran fine.

I ran the command 'wsl --install -d Ubuntu' and got the below error:

C:\Windows\System32>wsl --install -d Ubuntu
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

**Comment by rahulbtchrya** [comment]
![WindowsFeatures](https://github.com/user-attachments/assets/2910a474-b974-4be0-899b-cb6157ce93c9)

**Comment by lstocchi** [comment]
I'm out of ideas tbh, you should ask your IT dep for help setting your restricted environment.

The last proposals i have is... i went back to the first message and i read `Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED`
Enable the `Hyper-V` setting in `Turn Windows features on or off`.

If Desktop still does not detect WSL ( can you post the screenshot of the UI? ), try installing podman itself using its own binary and see if you face the same issue. 
Maybe Podman Desktop has some problem with the detection which can be skipped if podman is already installed.

**Comment by rahulbtchrya** [comment]
Hi @lstocchi , I verified that Hyper-V is enabled in windows features. I installed Podman using binary (ver 5.1.2). On running the 'podman machine init' command, I am getting the below error:

c:\Users\rahulbha>podman machine init
Extracting compressed file: podman-machine-default-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
Enable "Virtual Machine Platform" by running: wsl.exe --install --no-distribution
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED
Error: the WSL import of guest OS failed: command C:\Users\rahulbha\AppData\Local\Microsoft\WindowsApps\wsl.exe [--import podman-machine-default C:\Users\rahulbha\.local\share\containers\podman\machine\wsl\wsldist\podman-machine-default C:\Users\rahulbha\.local\share\containers\podman\machine\wsl\podman-machine-default-amd64 --version 2] failed: exit status 0xffffffff

Podman desktop is still showing the same error as earlier. Screen-shot attached.
![image](https://github.com/user-attachments/assets/ac8788ca-3e1f-488e-a4f9-2440d2ed6631)

**Comment by rahulbtchrya** [comment]
I also tried to install ubuntu distribution, getting a different error message now:

c:\Users\rahulbha>wsl --install -d Ubuntu
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...
The operation completed successfully.

**Comment by lstocchi** [comment]
@rahulbtchrya i'm a bit lost. Bc i keep seeing the error `Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.` but you said it is enabled.

If you execute `systeminfo.exe` in the powershell what do you have in the section "Hyper-V Requirements"?

In the task manager, cpu tab, do you have virtualization enabled?
![image](https://github.com/user-attachments/assets/969d86b2-2455-4d20-a46d-7b11f9d8e186)

**Comment by rahulbtchrya** [comment]
Hi @lstocchi , below is the output from systeminfo.exe

![image](https://github.com/user-attachments/assets/13cc5395-f38a-4a24-9cd9-3ef64653d294)


In my task manager cpu, I don't see the virtauklization enabled. This is a citrix vm that I am using, below is a snapshot

![image](https://github.com/user-attachments/assets/36bba5ca-fb8f-43d7-a450-9178f511e26c)

**Comment by lstocchi** [comment]
Ok, so this has to do with your citrix vm for sure. Unfortunately i don't have any exp with it so i don't have any other idea for now. I'm gonna investigate and see if i can find something. But i would suggest to ask your IT dep to enable virtualization, if possible. Let us know if you find a solution in the meantime.

**Comment by rahulbtchrya** [comment]
Hi @lstocchi , this issue indeed was due to virtualization. Our citrix machines can't have virtualization turned on. I installed Podman Desktop on a different laptop and was able to create a run a podman machine. However, I am now facing an issue with trying to pull an image:
![image](https://github.com/user-attachments/assets/039cb7d8-c805-4ebd-a773-f62e6e3e34f0)

If I try from command line, I get a different error:

 C:\Users\rahulbha>podman pull quay.io/podman/hello
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:53519: connectex: No connection could be made because the target machine actively refused it.

**Comment by lstocchi** [comment]
@rahulbtchrya which is the output of `podman system connection list`? And what if you execute `podman machine inspect <name-of-your-machine>`?

**Comment by rahulbtchrya** [comment]
@lstocchi , below is the output of the commands

![image](https://github.com/user-attachments/assets/bceee255-72f3-4961-b856-f18a80b2729e)

**Comment by lstocchi** [comment]
The output seems correct. Do you have any error when starting/stopping the machine? Can you ssh in it `podman machine ssh`?

**Comment by rahulbtchrya** [comment]
No, I am not able to ssh into the machine now. It was working fine yesterday. Getting this error

![image](https://github.com/user-attachments/assets/18e69b6a-5d4e-4963-9276-2b04e6c0a14f)

**Comment by rahulbtchrya** [comment]
Actually its worked now after restarting the machine.

**Comment by lstocchi** [comment]
> Actually its worked now after restarting the machine.

Great. Not sure why but i'm glad that restarting fixed the error 👍

**Comment by rahulbtchrya** [comment]
No, I meant after restart I was able to ssh into the machine. The pulling of the image is still not working
 
![image](https://github.com/user-attachments/assets/4e621f93-9f80-410c-a678-8b3c158c522c)

**Comment by lstocchi** [comment]
which version of podman are you using? Can you try creating a machine which is not the default and see if you still face the error?

**Comment by rahulbtchrya** [comment]
Hi @lstocchi , I worked with our network team and as per them I had to import a certificate into the podman machine for it to work. I did the same and its able to pull the image now. However I noted that it only worked from the command line and not from Podman Desktop. However, after restarting Podman Desktop a few times, it worked fine.

**Comment by lstocchi** [comment]
Ok, closing this issue then, as it was tracking the WSL error. Feel free to open a new one for any other problem you face. Thank you!!

**Comment by slemeur** [comment]
cc @baude related to the command we'd like to have to ease the install/config of certificates in the podman machine.

**Comment by shreeraamMNS** [comment]
Hi Guys. Facing the same error which @rahulbtchrya had. It's my organization laptop and I couldn't explore much. Is there a proven way to fix this so I can ask my IT dept to follow the same.
