### ISSUE TITLE
Selection in dark mode UI has no background

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8283]
### Bug description

Light mode:

![Screenshot from 2024-07-30 09-19-21](https://github.com/user-attachments/assets/f48b3b2f-4163-421b-bce2-72dad008f01f)

Dark mode:
![Screenshot from 2024-07-30 09-19-47](https://github.com/user-attachments/assets/c504ce96-75bf-4513-83e5-344a7c8ce530)

The selection background disappears / has issues showing correctly.

### Operating system

mac M1

### Installation Method

None

### Version

1.11.1

**Comment by deboer-tim** [comment]
This is working fine for me, also on M1. No idea what could cause this. 🤷🏻‍♂️

<img width="199" alt="Screenshot 2024-07-30 at 11 17 24 AM" src="https://github.com/user-attachments/assets/de933591-bff2-49cc-a58c-5b2e816924da">

**Comment by cdrage** [comment]
> This is working fine for me, also on M1. No idea what could cause this. 🤷🏻‍♂️
> 
> <img alt="Screenshot 2024-07-30 at 11 17 24 AM" width="199" src="https://private-user-images.githubusercontent.com/19958075/353517205-de933591-bff2-49cc-a58c-5b2e816924da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTM2NjUsIm5iZiI6MTcyMjM1MzM2NSwicGF0aCI6Ii8xOTk1ODA3NS8zNTM1MTcyMDUtZGU5MzM1OTEtYmZmMi00OWNjLWE1OGMtNWIyZTgxNjkyNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE1MjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NWJjYTczNTRhZDE0YjFiMGIzMWQ3NDYxOWYyYmY3OTgyNjhkYTAyYzQ2YTI2YjU3Zjc5ZjljNzE2MmYyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KpMGe2O3tiXLGFE_tcCmXrtAHJ1XWQpfZCaSpGHfwr8">

Screenshot shows an input field? The specific issue is anything drop-down. In my case would be selecting a podman provider / selection.
