### ISSUE TITLE
Extension navigation broken after item inserted or moved due to install/remove/activate/deactivate an extension

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#8291]
### Bug description

The navigation bar links are not updated correctly when navigation items for extensions move around in navbar due to update after installing/removing or activating/deactivating extension. This leads to navigation to wrong extension webview.

https://github.com/user-attachments/assets/19dcacb7-c4e5-4091-a60d-e5da0a74edac

### Operating system

macOS M1 Sonoma 14

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Install BootC from catalog page and then install OpenShift Docker Desktop Extension from docker hub using `redhatdeveloper/openshift-dd-ext`. Clicking on OpenShift Item will open BootC extension webview.

### Relevant log output

```shell
n/a
```

**Comment by ScrewTSW** [comment]
@odockal I've seen same behavior with Headlamp, restarting Podman Desktop is a workaround

**Comment by odockal** [comment]
@ScrewTSW Restart fix stuff. But I have also encountered the issue.

**Comment by odockal** [comment]
Workaround seems to be to restart the app which will then correct the extensions indexes.

**Comment by dgolovin** [comment]
Verified on latest master and it works for me.
