### ISSUE TITLE
Dark mode is very dark, for providers that don't have an icon but just a logo

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman-desktop#8305]
### Is your enhancement related to a problem? Please describe

Currently the dark logo is used, which makes the dashboard rather black:

![dashboard-dark](https://github.com/user-attachments/assets/0084d69c-480c-4afc-8be8-4e93b6c88e85)

(it is not _actually_ the logo image, but a scaled down copied version of it)

* https://github.com/lima-vm/lima/issues/268

### Describe the solution you'd like

I don't think this is easy to fix, at least not until Lima has a real (square) icon?

Previously it was using the `ProviderLogo`, but now it is using the `IconImage`

commit 50644dfdb49102417b41f57ac875c48a0fa4ecb6

### Describe alternatives you've considered

* Light mode, I suppose?

![lima-light](https://github.com/user-attachments/assets/0cf8915b-38aa-4762-93a8-e3567a4ef12c)

* Using the logo, like before

![podman-desktop-lima-name](https://github.com/containers/podman-desktop/assets/10364051/7e012bd4-2796-4b17-9a44-5431abc7e734)

* Using unofficial icons.

Official logos and icon: https://github.com/cncf/artwork/blob/main/examples/sandbox.md#lima-logos

**Comment by benoitf** [comment]
@afbjorklund is that a logo exists of Lima exists for Dark mode ? (like a one with white color for the text)

**Comment by afbjorklund** [comment]
The logos are there, but there is no white/black version of the icon - that's just a single image for all

**Comment by benoitf** [comment]
can we use https://github.com/lima-vm/lima/blob/master/website/static/images/logo-dark.svg ?

we could enhance the API to handle two versions

**Comment by afbjorklund** [comment]
There should be pre-rendered versions of it already, in extensions/lima ?

https://github.com/containers/podman-desktop/tree/main/extensions/lima

**Comment by afbjorklund** [comment]
Might go back to "logo" again, at least for the expanded view:

* https://github.com/containers/podman-desktop/issues/4395

Some of the icons are enormous, but are more or less square:

```
extensions/compose/icon.png:      PNG image data, 204 x 204, 8-bit/color RGBA, non-interlaced
extensions/docker/icon.png:       PNG image data, 1537 x 1081, 8-bit/color RGBA, non-interlaced
extensions/kind/icon.png:         PNG image data, 985 x 594, 8-bit/color RGBA, interlaced
extensions/kube-context/icon.png: PNG image data, 3600 x 3493, 8-bit/color RGBA, non-interlaced
extensions/kubectl-cli/icon.png:  PNG image data, 3600 x 3493, 8-bit/color RGBA, non-interlaced
extensions/lima/icon.png:         PNG image data, 150 x 52, 8-bit/color RGBA, non-interlaced
extensions/podman/icon.png:       PNG image data, 204 x 204, 8-bit/color RGBA, non-interlaced
extensions/registries/icon.png:   PNG image data, 824 x 824, 8-bit/color RGBA, non-interlaced

podman-desktop-extension-minikube/icon.png: PNG image data, 888 x 870, 8-bit/color RGBA, non-interlaced
```

**Comment by afbjorklund** [comment]
Adding a background to the icon, is probably the easiest fix.

Like the GitHub icon: (for e.g. https://github.com/lima-vm)

<img alt="lima-github" src="https://github.com/user-attachments/assets/2933e15e-bd13-443f-ad3a-da8e5317ebf0" width=400 />

Probably increase the size of the icon a bit too, for the border?
