### ISSUE TITLE
Add VSCode Remote Development extension

### ISSUE THREAD

**Issue by dp-sgr** [containers/podman-desktop#832]
### Is your feature request related to a problem? Please describe

Currently you can not use Podman Desktop directly with VSCode Remote Development. (At least without further configuration)

### Describe the solution you'd like

I would like to simply install an VSCode Extension for Podman Desktop Remote Development.

The best case would be a zero-configuration approach.

So only the simple Installation of the Extension should be required. (For the default case)

### Describe alternatives you've considered

I tried using to run "Container Remote Development" with a custom configuration but got an error while starting my project inside a Container. To also support docker-compose i installed podman-compose inside my podman wsl environment.

![image](https://user-images.githubusercontent.com/85862364/201890931-baf6f197-361d-4bf2-a9a0-27b67b79cd57.png)

But i got this error:
![image](https://user-images.githubusercontent.com/85862364/201891613-62899cdd-ff1a-4dc4-a582-2e1b989ea360.png)

### Additional context

This feature would drop Docker Desktop in our Company. I think the Idea of Podman Desktop is really cool. But this Problem/Missing feature is stopping us from using Podman Desktop.

We are using Windows hosts. On Linux this may be not an big Issue because i simply could install podman-compose on the Host directly.

**Comment by slemeur** [comment]
Hi @dp-sgr ! Thanks for the report. 
That is an interesting use case indeed. We will give it a try and see what we can do to simplify the configuration of other developer tools from podman desktop. 
Would you have a sample repository which you believe could be a good one to experiment with?

**Comment by dp-sgr** [comment]
Hi @slemeur,

i created a little sample project (C# Console).
With Docker Desktop this should be runable without any further configuration.

https://github.com/dp-sgr/DevContainerTest

**Comment by dp-sgr** [comment]
I still think, that this feature would be very useful. 
This still blocks us from moving to podman desktop.
