### ISSUE TITLE
Tooltips should be closed (shouldn't overlap) when opening a menu

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8335]
### Bug description

See #8322 for background. When there is a tooltip open and then you open a menu, the tooltip doesn't disappear. In #8322 it is underneath and not so distracting; in #8269 it was on top. Although we could change z-order to make it always behind, the correct fix is to make sure the tooltip always closes when opening a menu.

### Operating system

macOS 14.5

### Installation Method

None

### Version

next (development version)

**Comment by SoniaSandler** [comment]
@benoitf Is it possible that this problem is OS specific? I'm working on Linux, and when opening the context menu, the tooltip disappears.

https://github.com/user-attachments/assets/bc4edc9a-68d9-453c-aeaa-2772f36a6606

**Comment by benoitf** [comment]
@SoniaSandler it might be as on my end (macOS) it's still there

but we do not use the native tooltip but use a tooltip component so it's still managed by us (not electron)

**Comment by SoniaSandler** [comment]
@benoitf I think that adding an event listener for contextmenu in the tooltip component could help. I can create a PR with my proposed solution, but I won't be able to check it.
