### ISSUE TITLE
UX: Mockups for Docker Compatibility page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8338]
### Goal

The goal of this issue is to provide the mockups accordingly with the epic https://github.com/containers/podman-desktop/issues/8337 

In this effort, we would like to reuse some of the component/information we are already using as part of the onboarding sequence.

**Comment by ekidneyrh** [comment]
@slemeur Will this page be nested withing the resources? Eg Setting > Resources > Docker? 
![image](https://github.com/user-attachments/assets/15ae141d-4366-4547-ab4a-4366b4ba0548)

Will this be part of the set up for Docker or a separate, more info heavy page? like when you look at recipes in ai lab
![image](https://github.com/user-attachments/assets/f8924210-7771-4a97-b8f7-12c961495748)


For the Compatibility Confirguration I presume that would be displayed in the preferences like the other resources settings? 
![Screenshot from 2024-08-22 12-25-34](https://github.com/user-attachments/assets/8941d06d-9c48-47d1-84e9-3504243e23cb)

Just want to know the context :) and visualize better where / what this page is

**Comment by slemeur** [comment]
As mentioned in the epic description #8337, we should introduce a dedicated page in the settings. It should not be nested under "Resources" nor under the "Preferences".  
<img width="230" alt="Screenshot 2024-08-25 at 11 49 24" src="https://github.com/user-attachments/assets/f18d9fb1-f404-453e-be2e-58515a887bc3">

I believe, we can envision it more like the "details of recipes" from AI Lab indeed. With some mixed content, alterning descriptions, labels and links with other section where the user will actually be able to do some configuration.

**Comment by ekidneyrh** [comment]
Just an update on what I have as of right now.

I have a first draft of what the preferences might look like. I have it laid out like the preferences page. Toggles to enable / disable certain compatibilities. Socket Mapping has it’s own section with a status, a way to specify a specific path and an option to restore socket mapping. 

![docker-compatibility-preferences](https://github.com/user-attachments/assets/483916c4-9892-4595-ae36-e7ad2c970399)


I’m working on what the Summary page would look like at the moment. I’m just taking info from the docs so will hopefully have an update for this soon. 

Let me know what you think of the preferences page!

**Comment by ekidneyrh** [comment]
Heres a draft of the Docker Compatibility Summary:

![docker-compatibility-summary](https://github.com/user-attachments/assets/dcf05686-cc5e-47a1-84fb-b9c3873cf836)

The copy can be changed, it's just a first go at it. I just included questions that were on the epic.

**Comment by gastoner** [comment]
> Heres a draft of the Docker Compatibility Summary:
> 
> ![docker-compatibility-summary](https://private-user-images.githubusercontent.com/87311656/364308223-dcf05686-cc5e-47a1-84fb-b9c3873cf836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDg0NDIsIm5iZiI6MTcyNTQ0ODE0MiwicGF0aCI6Ii84NzMxMTY1Ni8zNjQzMDgyMjMtZGNmMDU2ODYtY2M1ZS00N2ExLTg0ZmItYjljMzg3M2NmODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzAzZDkzNTFhZTA1Mzk0ZmY5NTBjZjk1MTFhYzAzNTNjMmM0OWI3MWE1ZDlkNGU0NGEwNmU3OWM5MTBmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70VDXpCT4qRqfHpWpriWFrT5FUJ-AmLSyHJZ0ntlwpk)
> 
> The copy can be changed, it's just a first go at it. I just included questions that were on the epic.

Looks good! I would maybe change the order of Summary and Preferences tabs. Since you are in settings so I think that you would like to change settings (preferences tab as first/default), but you can learn more about some of those settings in the Summary page

**Comment by deboer-tim** [comment]
I think the issue is more that the Summary page above is just docs (static text). As-is I'm not sure it's worth including, we could just have a link to docs within the Preferences.

**Comment by ekidneyrh** [comment]
@gastoner @deboer-tim Thanks for the feedback re: the summary page. In terms of the preferences page - do the options seem correct / relevant to docker compatibility?

**Comment by ekidneyrh** [comment]
Had a discussion with @Firewall about this last week. https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/82e31d90-3829-8139-8002-c1a6267ccc6a?page-id=00650e59-18b2-8059-8002-cea31c5415d6 was brought to my attention and I’m going to integrate some of the components there. 

Some feedback:
Have information on what the toggles do exactly
When enabled - have feedback to show it’s working
Test button next to status
A more info button to explain actions

**Comment by gastoner** [comment]
@ekidneyrh I would say that the options are correct (but I'm not expert) + I'm looking at the Preferences and I would maybe put the Socket mapping status maybe one line up, to be in line with the title `Socket Mapping` since it does not look like you can set anything with it. But if will be added some button to test things, we can leave it as it is. 

Agree 
> Have information on what the toggles do exactly
> When enabled - have feedback to show it’s working
> Test button next to status
> A more info button to explain actions

What about add something like "test tab" ?

**Comment by slemeur** [comment]
the "test tab" is such a good idea !

**Comment by shipsing** [comment]
@slemeur, I see this setting of **Docker compose compatibility**. With this setting enabled, users would not require to install and set up the Compose extension manually and they can use podman compose commands to run a Docker application. Am i correct??

**Comment by ekidneyrh** [comment]
Another update following the comments mentioned above.

I added a test button to the right of the status card and moved the status label to be inline with the card title. 

I acknowledge the suggestion for a ‘test tab’ but I'm curious as to what would be displayed there. Would it just be the status card or would we have more components to display the testing. 

Here’s an overview of the user flow:

![Userflow](https://github.com/user-attachments/assets/f8c9e8f9-6583-47ec-95f4-ed079d375c0a)

I’ll go through each of the above screens.

### Onboarding:

Still in progress

### Settings > Resources > Podman:

![Resourcces _ Settings _ Podman](https://github.com/user-attachments/assets/a2b1f261-ddd2-4443-bdf6-50b929eb4805)

### Settings > Docker Compatibility:


![Settings_Docker_Compatibility](https://github.com/user-attachments/assets/ed6298fc-c149-4874-8db6-7653834171be)

### Modal:

![pop-up](https://github.com/user-attachments/assets/1a010fe8-2fce-4454-83b7-d6f35e6c2941)

### Docker Detected Warning:

![No_Docker_Detected](https://github.com/user-attachments/assets/a6863950-99f9-4e1f-a20e-810f248c2502)

**Comment by gastoner** [comment]
Regarding the "test tab" I got the impression that there will be a few options to test ~ 3/4+ (don't know which ones), but if there will be just one or two "test buttons" I think it is OK

**Comment by Firewall** [comment]
I have a feeling that we are repeating ourselves with the `Docker compatibility mode` and `Compose support` in `Settings > Resources > Podman:` and `Settings > Docker Compatibility:`. Don't you think this will be confusing for our users if those settings are in two places but have the same effect? 

I like that the `Test` is just a button. Very simple. Where do you see those errors if the test fails to appear, a notification? Or inline somewhere?

**Comment by Firewall** [comment]
Regarding the test "Tab" I think idea was to display what the effect would be of switching the toggles. Then adding a button to see if that is working. 

When you turn on Docker Compatibility, have a way to test if running a Docker command  it will run it with `podman` instead. (eg, `docker run ...`, or tools that use docker internally `quarkus image build ...`)

When you turn on Docker Compose, have a way to test when a `docker compose` command is run, it runs with `podman` instead.

**Comment by ekidneyrh** [comment]
> I have a feeling that we are repeating ourselves with the `Docker compatibility mode` and `Compose support` in `Settings > Resources > Podman:` and `Settings > Docker Compatibility:`. Don't you think this will be confusing for our users if those settings are in two places but have the same effect?

Would it make sense then to get rid of them from the `settings > resources > podman` page then? 

> I like that the `Test` is just a button. Very simple. Where do you see those errors if the test fails to appear, a notification? Or inline somewhere?

I was thinking having it display underneath like we usually do with our warnings / errors

![image](https://github.com/user-attachments/assets/c3f7e6dc-3e67-4e1e-8d33-3b5da1ae3250)

> Regarding the test "Tab" I think idea was to display what the effect would be of switching the toggles. Then adding a button to see if that is working.

> When you turn on Docker Compatibility, have a way to test if running a Docker command it will run it with `podman` instead. (eg, `docker run ...`, or tools that use docker internally `quarkus image build ...`)

Could this be displayed as an error instead? Like have a test run in the background anytime it's turned on and if it doesnt work have the toggle reset to disabled and have an error underneath saying 'Error: Something went wrong' or something to that effect?

> When you turn on Docker Compose, have a way to test when a `docker compose` command is run, it runs with `podman` instead.

Could this also be done automatically when the user turns the toggle on?

**Comment by Firewall** [comment]
> Would it make sense then to get rid of them from the settings > resources > podman page then?

I personally think so, yes.

> I was thinking having it display underneath like we usually do with our warnings / errors

Great, makes sense to re-use the same pattern yep. 

> Could this be displayed as an error instead? Like have a test run in the background anytime it's turned on and if it doesnt work have the toggle reset to disabled and have an error underneath saying 'Error: Something went wrong' or something to that effect?
>When you turn on Docker Compose, have a way to test when a docker compose command is run, it runs with podman instead.

Yea, I think we can add an error if it doesn't work (maybe it already does that). However the idea was more a explanation of what it is "enabling/providing" now that this feature is on. 
We could re-use the pattern we are using for the `Socket Mapping` having a `🟢 Active` with an tooltip containing an explanation "Podman will handle all `docker` commands run on the CLI" (we can improve that message).  Same for with the `Compose support` "Podman will handle any `docker compose` commands run on the CLI"

**Comment by benoitf** [comment]
hello, nice mockups

I have some comments

for 
![image](https://github.com/user-attachments/assets/c68c5976-ebbb-45ad-9e75-8e74db51d03f)

I think it's nicer if there is on the left the podman icon.

![image](https://github.com/user-attachments/assets/8a362e89-2112-4dda-b933-3d11a8cb8089)

why ?
because many providers may claim they want to use the `/var/run/docker.sock`

There could be podman, but lima, docker, etc.


Then, it's not because you enabled the toggle that it'll work as you expect. There is the rule of the 'last is the winner'.
If I start podman in compat mode and then docker, docker will replace the socket so even if we're telling 'Podman is providing the compat mode', at the end it may be docker that is winning.


Then, about docker, in the past, docker was only using `/var/run/docker.sock` file, but now they're mostly advertising to use local sockets in the home directory and it's where is coming the `docker context` in the game.

`docker` cli is mapped to a context like

```
default                 System                         unix:///var/run/docker.sock
desktop-linux *   Docker Desktop          unix:///Users/<your-name>/.docker/run/docker.sock
```

so while you may think that when you're using the docker cli, you're using podman, if your context is mapped to a home folder, `docker` cli will continue to use `docker engine`


So for the compatibility, I would emphasis that it's the `system compatibility` (and say it's for /var/run/docker.sock if running on macOS, (npipe if on Windows)

Then, we should display on this page the current `docker context` of the CLI

and then, we might display what is really running behind the system socket (is it docker engine or the podman engine as depending of the order of the launch, you'll have different results)


For the socket Path entry and restore I don't know what it will do or what it means
![image](https://github.com/user-attachments/assets/a3eaa3d3-70f7-4c15-a2c1-e325472c3962)



so to summarize,

I would expect to see first if the system socket is alive (/var/run/docker.sock) and see what is the version/operating system behind (your test button but I think at each loading of the page I should have the result, not the need to click on the test)
so as a user if I see that, it means ok I can use any classic tool, at least I have an engine that is working.

then, see the podman toggle to enable/disable the agent that is starting the socket
note: AFAIK it's only on macOS on windows as long as you start a podman machine it will try

and then have a section where I see what context docker CLI is using. (is it system or home socket)

then yes we need the compose section (but it's provided by the compose extension so if the extension is not there or disabled you won't see that)

**Comment by benoitf** [comment]
overall status first and action after while in the mockup I see first the action and then the status/test

**Comment by ekidneyrh** [comment]
Following the UX meeting we had last week, I made the following changes:

**Socket Mapping Status**
Added a provider label and changed the test button to refresh. Added in a detail section showing information about the socket. If there are no sockets or it is unreachable, the provider label will read ‘Socket not reachable’ and the detail section will not be there. 

**Third-Party Docker Tool Compatibility**
Added in that this is just for MacOS. On windows and linux this card will not be displayed.

**Compose CLI Support**
Changed the card to just display an install button and if the CLI support is already installed, display an ‘installed’ label - like we do on the extensions page.

**Deleted the Socket Mapping section and added a Docker CLI Context section.** 

**Docker Context**
Similar to the Socket Mapping Status, this card displays details of the context. I wasnt sure whether to add a label in there but that can be reused from the Socket Mapping Status card. 
If there are no contexts an error will display to let the user know and the detail section will not be there. 

**Change Context**
Here we have a dropdown that will have all the available contexts for the user to choose between. It will display the context name and the socket. This will work like the other drop downs we have, where the option is selected and changed with no additional clicks. 

@benoitf @Firewall Let me know if this makes sense / captures what we talked about last week. 

[Docker Compatibilty.pdf](https://github.com/user-attachments/files/17096169/Docker.Compatibilty.pdf)
![Docker Compatibilty](https://github.com/user-attachments/assets/e1354221-1ca9-408b-9223-954b6d53b3c5)

**Comment by benoitf** [comment]
yes thanks @ekidneyrh 


some notes:

1. Third party docker tool compatibility

I would add on the left card of the podman card to bring the system support the podman icon/widget
![image](https://github.com/user-attachments/assets/6a3ab927-9a5d-4bca-b4a1-ebaf149eac76)

(because several providers can claim this)

Note: this card anyway would appear only on macOS as on Linux there is nothing and Windows it's always trying to bind if it's not taken.

2. Compose CLI support
here in fact we're bringing `docker-compose` binary for `podman compose`
if you install docker desktop on your system you have the support of compose with `docker compose`

so maybe here, add that card to the previous group saying it's for `podman compose`

- maybe also display a status in case it's already there
like: `podman compose` supported | `podman compose` not supported

and yes if not supported, the command to install the support will help
and a sentence to explain that without the support, you can't start compose projects using podman CLI.

3. Docker CLI Context

I would merge the two cards for CLI context.
Why ? Let say I change the value in the dropdown, it means that I would need to click on the card before on refresh to get the value being refreshed.

So I would expect to have the dropdown on the left and the details on the right.

**Comment by ekidneyrh** [comment]
@benoitf Thanks for the prompt response! Implemented your feedback here: 

[Docker Compatibilty2.pdf](https://github.com/user-attachments/files/17111273/Docker.Compatibilty2.pdf)
![Docker Compatibilty2](https://github.com/user-attachments/assets/61608121-cfc4-4640-a77a-d6619ceada1e)

Does the text on the 'Podman Compose CLI Support' make sense?

**Comment by benoitf** [comment]
> Does the text on the 'Podman Compose CLI Support' make sense?

yes thanks.

(I'm wondering if the podman icon/left box with the seal should not grow more and include the compose box)

I think we could remove the last widget 'Change Context' (probably leftover)


I'll try to implement and then we can discuss it from there as well

**Comment by ekidneyrh** [comment]
Whoops I forgot to delete the last card. Here's an updated version:

[Docker Compatibilty2.pdf](https://github.com/user-attachments/files/17113008/Docker.Compatibilty2.pdf)
![Docker Compatibilty2](https://github.com/user-attachments/assets/8083d0ef-c9b8-4dea-aaa9-6fdb94ded456)

Am I ok to close this ticket?

**Comment by shipsing** [comment]
A few questions:
Now, the compatibility page does not have the options of providing a custom socket path and restore socket mapping as mentioned in the [issue description](https://github.com/containers/podman-desktop/issues/8337).
![image](https://github.com/user-attachments/assets/0b3a9ce8-f62f-4596-80f6-9f3b7392d080)

What can a user do if they have to change the default path of the socket to restrict its access? 
If the socket is not reachable, what can a user do? how can i restore to the default settings?

There is an option to select a docker context, but where would a user define those contexts so that they get reflected in the dropdown list?

**Comment by benoitf** [comment]
@shipsing 
the UI in your screenshot does not seem to be the latest one.

you won't specify a custom socket path. The path is usually inside the tool you want to connect. (like I have a tool that needs to communicate with the docker API, then I can select the path)

we could display on this page all socket path where a user could connect

like this data
![image](https://github.com/user-attachments/assets/f776890a-e87a-4557-b6e0-2a2b22ab5811)



> What can a user do if they have to change the default path of the socket to restrict its access?
you just disable the system/podman socket if you don't want a system wide access. (anyway it's a socket on your local computer, not a remote one)

>There is an option to select a docker context, but where would a user define those contexts so that they get reflected in the dropdown list?

`docker context ls` /  `docker context use <context-name>` using the docker CLI.

then any `docker ps` command for example is connecting to the socket of this selected context.

by default docker can register default contexts.

**Comment by shipsing** [comment]
Thank you, @benoitf, for the detailed clarification.

**Comment by Firewall** [comment]
This is looking great so far. I would make a couple of changes to the descriptions to describe what these settings mean to our users.


For `Socket Mapping Status` 
I would change the text to: `Displays which engine is currently listening to any commands on the `docker socket`. If Podman is listening, it will emulate and run and any Docker commands with the Podman Engine instead.`

For `Third-Party Docker Tool Compatibility` 
I would change the text to:  `Enabling this option will direct third-party Docker-compatible tools to use Podman. No changes will be needed in the tools Podman will handle the emulation once this is enabled. `

For `Podman Compose CLI Support` 
@benoitf should it be `Docker Compose CLI Support` instead? and then the description: `With Docker Compose CLI Support you will be able to run Docker Compose comamnds which will be emulated using the Podman CLI and Engine` 

For `Docker CLI Context`
@benoitf can we only show this if the user has 2 or more `Docker contexts` on their system?

**Comment by benoitf** [comment]
while implementing I notice that displaying all the information like OS/Arch APIVersion, etc while it's a 'nice to have' is putting too much information there.

I thought then maybe it needs to be displayed on hover or a show/hide

> I would change the text to: Displays which engine is currently listening to any commands on the docker socket. If Podman is listening, it will emulate and run and any Docker commands with the Podman Engine instead.

I believe it'll be too much text. I would carry some stuff behind `?` hovering

After experimenting, I think I basically need to see the path of the socket (/var/run/docker.sock if macOS/Linux and npipe:////./pipe/docker_engine if Windows) and then to know the engine behind
And if on macOS we can have a link and display the name of the connection providing the link like 'provided by Podman machine' and if you click you're redirected to the podman machine resource (or it's docker you're redirected to the docker resource also) and maybe here a toggle show/hide details where I can see some details. But probably as we're trying to redirect people to the resource page, the OperatingSystem/arch should be displayed there


> For Podman Compose CLI Support
> @benoitf should it be Docker Compose CLI Support instead? and then the description: With Docker Compose CLI Support >you will be able to run Docker Compose comamnds which will be emulated using the Podman CLI and Engine

too early on my end to provide you meaningful feedback there

> For Docker CLI Context
> @benoitf can we only show this if the user has 2 or more Docker contexts on their system?

yes, I was also thinking that we could display if `docker` CLI is found or not

**Comment by Firewall** [comment]
> I believe it'll be too much text. I would carry some stuff behind ? hovering

Are you sure? It looks to me we have quite a lot of space for text? I think there is a lot of value in also explaining to the users what this means. 

> yes, I was also thinking that we could display if docker CLI is found or not 

Good idea, we can do both?

**Comment by benoitf** [comment]
here is how following the mockup I can display things
![image](https://github.com/user-attachments/assets/f35e44ad-d04a-4d6d-8237-eb6a31d41fb7)


but then, in case of macOS, I'm able to detect which podman machine is emulating the socket
so I thought we could provide a redirect link to the podman machine providing that
![image](https://github.com/user-attachments/assets/786f4a44-32d6-4ed3-8be4-3d0923d7ea98)

on Windows it won't be possible for now to know what is the podman machine behind, so we need like multiple "right card option"

we can change the text on the left based on the provider type 'podman' or 'docker'

**Comment by ekidneyrh** [comment]
@benoitf do you mean that for Windows there wont be any info available on the right side of the card? or just that the second option wont be available on windows?

**Comment by benoitf** [comment]
@ekidneyrh on Windows, we're not able to detect (technical POV, upstream RFE filed in podman repository) which podman machine is binding the system socket so we can't provide the nice 'click here to go to the resource or the name of the podman machine providing the socket. We can only query the socket and get information like the version, etc

**Comment by ekidneyrh** [comment]
@benoitf can we have it this way then in windows? 

![image](https://github.com/user-attachments/assets/28ae07ef-db29-48d7-929c-814626117a16)

or are we looking for another way to display it?

**Comment by benoitf** [comment]
we can display this way but I don't know if we need to see all fields/values directly or like after a clicking on a toggle (minimal state / all details)

**Comment by ekidneyrh** [comment]
I'm just wondering what would we have it behind then? Maybe a 'see details' text next to the open button? I wouldnt go with the toggle as that would be more for changing something bigger than just showing more details on something.

**Comment by ekidneyrh** [comment]
@benoitf @Firewall do we need anything else from this ticket or can it be closed?

**Comment by benoitf** [comment]
I think on my side it can be closed, we might have enhancement requests, but it should be follow-ups

**Comment by Firewall** [comment]
Agreed
