### ISSUE TITLE
Change the order of elements on the dashboard page

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8339]
### Is your enhancement related to a problem? Please describe

When a user start podman desktop, the dashboard is always showing the same information at the top of the page. The section that are highlighting what's new are at the end of the page and the users might be missing them. If the user has a small window for the application, the sections with the guides and the recommended extensions are even not visible.

<img width="1653" alt="Screenshot 2024-08-02 at 14 57 44" src="https://github.com/user-attachments/assets/a1d5c681-80b6-41de-81f6-106d6b7e8542">

### Describe the solution you'd like

In this issue, we would like to change the order of the section on the dashboard.
Today, we have the following order:
1. Onboarding and error messages
2. Providers (podman and others)
3. Learning Center
4. Recommended extensions (dismissed if installed)

We would like to change the order with the following one:
1. Onboarding and error messages
2. Release Note (#8521)
3. Recommended extensions (will be dismissed if installed)
4. Learning Center
5. Providers (podman and others)

Note: Providers will be moving to the status bar.

### Additional context

_Note:_ This is a temporary change, until we are revamping the dashboard.

**Comment by afbjorklund** [comment]
> Recommended extensions (will be dismissed if installed)

Is it possible to dismiss the recommended extensions ads, _without_ installing them?

EDIT: It was hidden in the preferences, how to ignore it

* https://github.com/containers/podman-desktop/pull/6813

**Comment by cdrage** [comment]
IMHO providers should be on the top so I can see immediately what the issues are with the provider(s). 

With the temporary change in the PR I now how to scroll all the way down to see if there is a problem with open shift / docker / podman / etc. 


I believe that we should not implement this as a temporary measure unless we completely revamp the dashboard and implement it at once rather than temporary. 

Sorry for being blunt! I just don't think this is a good change at the moment and we may get complaints.

**Comment by axel7083** [comment]
> IMHO providers should be on the top so I can see immediately what the issues are with the provider(s).

I agree

**Comment by afbjorklund** [comment]
What is the difference between the providers on the dashboard and the resources in settings? Only the "details"?

* https://github.com/containers/podman-desktop/issues/4395#issuecomment-2217284713

I know that the CLI tools (compose/kubectl) are duplicated in Resources too, but I think that is another open issue

* https://github.com/containers/podman-desktop/issues/8044

**Comment by slemeur** [comment]
@cdrage and @axel7083 : I've rework the epic description related to improvements of the dashboard in order to bring more awareness to the new capabilities Podman Desktop can be providing to the user. 

@afbjorklund : You are right. Ideally, the providers should be moving to the status bar and when users wants to configure them, they'd be redirected to the appropriate section in the settings.
