### ISSUE TITLE
Kubernetes pages should have a refresh button when cluster connection is not established 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8341]
### Is your feature request related to a problem? Please describe

After seeing https://github.com/containers/podman-desktop/pull/8340 I directly saw the need for kubernetes page to have similar feature.

As we often show an empty screen when the cluster is `not reachable`

![image](https://github.com/user-attachments/assets/3f32ad38-23be-46fb-b210-6648653c8287)

But when you start manually the cluster, you often have to wait some time , or even force the context switch to trigger a refresh/connection to the cluster

### Describe the solution you'd like

Same as https://github.com/containers/podman-desktop/pull/8340 a button to refresh, retry the connection to the kubernetes cluster (current context)

**Comment by deboer-tim** [comment]
+1. However, unlike #8340 where there is only a single attempt, this is polling and likely just not frequent enough / happening when you know the Kubernetes context state or connection to it has changed. Once you actually connect to a context it should be live.

So, I'd prefer this to be implemented more like a 'will try again in 30s' with a 'try now' button that disappears when it is connected.

**Comment by axel7083** [comment]
I am assigning it myself for next sprint :)

**Comment by axel7083** [comment]
![image](https://github.com/user-attachments/assets/7625f697-ee67-4ff6-8853-ef7974488be3)

**Comment by deboer-tim** [comment]
I like the simplicity, but it's not super obvious that I can click on it to refresh. (we have lots of Labels elsewhere that look almost identical but you can't click) Maybe if the refresh icon looked more like one of the column actions? Colored and on a little circle?

**Comment by axel7083** [comment]
I moved this issue to `Postponed` because the work required is quick a lot, and the way the informer system is designed does not allow easily manual intervention.

In the `kubernetes-context-state.ts` there is a `restartInformer` method with the following signature

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L1094-L1098

However the `options: CreateInformerOptions<T>` are never saved anywhere, they are always passed down through function scope and function argument callback. Meaning, for an external caller this is never available.

Moreover this is a problem, as each options is specific to resource type `pod`, `deployment` etc.

---

Moreover, the reconnection timeout id is saved inside this option object iself

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L1118

which is never saved anywhere as mention above.

A lot of code and logic is only available in the catch block of the informer start method promise, making it difficult to be able to intervene in it.

https://github.com/containers/podman-desktop/blob/4c147ed43308839c03ac76d648fd03213f3ac8dc/packages/main/src/plugin/kubernetes/kubernetes-context-state.ts#L1104-L1107

IMO there is a rework needed for this file starting by cutting this file down (see https://github.com/containers/podman-desktop/issues/8775)

**Comment by axel7083** [comment]
![image](https://github.com/user-attachments/assets/f864daa8-e700-47be-9fe3-cd53217afbbf)

Here is a screenshot from the latest version MIT of Lens when the connection to the cluster get lost

We can see that it tries a few time, then stop

**Comment by axel7083** [comment]
Postponed until https://github.com/containers/podman-desktop/issues/8775

**Comment by axel7083** [comment]
Moving to next sprint since we need more discussion on https://github.com/containers/podman-desktop/issues/9169 to be able to implement this nicely
