### ISSUE TITLE
TLDs longer than 6 characters blocked

### ISSUE THREAD

**Issue by idjohnson** [containers/podman-desktop#835]
### Bug description

Many TLDs like .website, .foundation and .science (which affects me) exceed the normal 2-6 character TLD names.  This blocks one from adding things (such as my harbor.freshbrewed.science).  I  am able to workaround by loging in via the command line, but then I cannot edit in Podman Desktop (for password rotation).

### Operating system

Ubuntu 20.04

### Version

next (development version)

### Steps to reproduce

login to a registry on a longer domain TLD (such as `podman login harbor.freshbrewed.science`).

Then try and do the same via the Podman Desktop / Settings / Registry.  You'll be blocked by "Please Enter a Valid URL"

**Comment by benoitf** [comment]
thanks @idjohnson for the report.

**Comment by benoitf** [comment]
should be fixed by https://github.com/containers/podman-desktop/pull/838
