### ISSUE TITLE
Remote podman connection is not working

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#8351]
### Bug description

Adding a podman remote with ssh connection should list the images and pods in the podman desktop but this is not working

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

latest-nightly - https://github.com/containers/podman-desktop/releases/tag/v1.12.0-202408052012-7c3c5ee

### Steps to reproduce

- Install PD from nightly (which is available for releases)
- Run podman setup but don't start the podman machine (Just the installation part)
- Install the OpenShift Local extension
- From the `Setting => preference => Extension: podman => Enable the Remote`
- Set the microshift preset from the openshift local configuration
- Start the openshift local wait till it started

From the windows powershell
```
> podman system connection add crc-root --identity "C:\Users\rhqp\.crc\machines\crc\id_ecdsa"  "ssh://core@127.0.0.1:2222/run/podman/podman.sock"

> podman system connection add crc --identity "C:\Users\rhqp\.crc\machines\crc\id_ecdsa"  "ssh://core@127.0.0.1:2222/run/user/1000/podman/podman.sock"

> podman system connection ls
Name    	URI                                                     	Identity                              	Default
crc     	ssh://core@127.0.0.1:2222/run/user/1000/podman/podman.sock  C:\Users\rhqp\.crc\machines\crc\id_ecdsa  false
crc-root	ssh://core@127.0.0.1:2222/run/podman/podman.sock        	C:\Users\rhqp\.crc\machines\crc\id_ecdsa  true
```

From windows CLI you can get the images and running pod using `podman images` / `podman ps` command. 

Now check the PD and see if you can get those details from the UI but there is noting.

### Relevant log output

```shell
From the Troubleshooting => logs didn't get any suspicious failure logs

 ↪️ Activating extension (podman-desktop.kind) ended in 579 milliseconds
main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
main ↪️ [kube-context] starting extension kube-context
main ↪️ Activating extension (podman-desktop.kube-context) ended in 2 milliseconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 5 milliseconds
main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
main ↪️ [lima] Could not find socket at C:\Users\rhqp\.lima\podman\sock\podman.sock
main ↪️ Activating extension (podman-desktop.lima) ended in 5 milliseconds
main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
main ↪️ [kubectl-cli] Error getting kubectl from user PATH: Error: Failed to execute command: spawn kubectl.exe ENOENT, trying from extension storage path
main ↪️ [kubectl-cli] Error getting kubectl version system from extension storage path Error: Failed to execute command: spawn C:\Users\rhqp\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.kubectl-cli\bin\kubectl.exe ENOENT
main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
main ↪️ [podman] Unable to run regex on containers.conf file. Reason: Error: ENOENT: no such file or directory, open 'C:\Users\rhqp\AppData\Roaming\containers\containers.conf'
main ↪️ Activating extension (podman-desktop.podman) ended in 1068 milliseconds
main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.registries) ended in 1 milliseconds
main ↪️ Activating extension (redhat.openshift-local) with max activation time of 20 seconds
main ↪️ Activating extension (redhat.openshift-local) ended in 5687 milliseconds
main ↪️ PluginSystem: initialization done.
main ↪️ Skipping update for extension redhat.openshift-local because installed version 1.3.0 is greater or equal to latest available version 1.3.0
main ↪️ (node:11192) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\rhqp\.kube\config' at async open (node:internal/fs/promises:639:25) at async Object.readFile (node:internal/fs/promises:1249:14) at async wx.refresh (C:\Users\rhqp\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:30135) at async wx.setKubeconfig (C:\Users\rhqp\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:292:9124) at async C:\Users\rhqp\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:25984 (Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
main ↪️ (node:11192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
main ↪️ [openshift-local] Error: Value '' for configuration property 'pull-secret-file' is invalid, reason: file '' does not exist
main ↪️ [openshift-local] Error: Value '' for configuration property 'pull-secret-file' is invalid, reason: file '' does not exist
main ↪️ [openshift-local] Logs tick: RequestError: connect ENOENT //?/pipe/crc-http
main ↪️ start watching services in context [object Object]
main ↪️ start watching ingresses in context [object Object]
main ↪️ start watching routes in context [object Object]
main ↪️ start watching configmaps in context [object Object]
main ↪️ start watching secrets in context [object Object]
main ↪️ start watching nodes in context [object Object]
main ↪️ start watching persistentvolumeclaims in context [object Object]
main ↪️ Kube deployment watch ended Error: aborted
```

**Comment by afbjorklund** [comment]
I don't think it has been released yet? f7cb5a3450ee98705fb59790f3eb4fea4e377796

It also seems to be disabled by default, in the prefs.

**Comment by praveenkumar** [comment]
@afbjorklund It is not yet released but part of nightly bits and yes it is disabled by default.

**Comment by afbjorklund** [comment]
ok, didn't read fully - just saw the "1.11.1" - I think it is _supposed_ to create a named pipe

**Comment by praveenkumar** [comment]
> ok, didn't read fully - just saw the "1.11.1" - I think it is _supposed_ to create a named pipe

Ah, I updated that.

**Comment by afbjorklund** [comment]
On Linux, PD creates a ssh tunnel socket: `unix:///tmp/podman-remote-lima-podman-ssh.sock`

For some reason it shows up as "OFF" in the GUI, but it does show the containers and images...

Seems to be some kind of error in the logs, but I think it is from Lima and not from Podman ssh:

`main ↪️ Engine does not have an API or a libpod API, returning empty array Podman`

**Comment by afbjorklund** [comment]
It seems like Podman Desktop **only** monitors the default connection, not any ssh tunnels:

```go
  // Since Podman 4.5, machines are using the same path for all sockets of machines
  // so a machine is not distinguishable from another one.
  // monitorPodmanSocket(socketPath, machineInfo.name);
  containerProviderConnections.set(machineInfo.name, containerProviderConnection);
```

Probably just as well, since pinging the socket will wake the daemon (service) every 5 secs...

* https://github.com/containers/podman-desktop/issues/8352

**Comment by cdrage** [comment]
After troubleshooting a lot and adding a log of console.log / try catch outputs to our implementation, I can conclude that this is due to the ssh2 library not supporting correct `ecdsa-sha2-nistp521` implementation against crc's private key generation.

I've commented on an already opened issue that is having issues with a related algorithm `ecdsa-sha2-nistp256` error: https://github.com/mscdex/ssh2/issues/1375

If there is ANY way that crc can support ed25519 keys (even if it's adding it to ~/.crc/machine directory), it will work.

I can confirm that podman remote feature works fine against ed25519 as well as other key generation methods, but unfortunately the specific one that CRC uses (ecdsa-sha2-nistp521) is not compatible with the ssh library that we use.

Logs when using the crc private key and adding a try/catch to the ssh2 connection method:

```
2:05:52 PM [main] [podman] Error connecting to podman remote SSH connection Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (/Users/cdrage/syncthing/dev/electron/podman-desktop/node_modules/ssh2/lib/client.js:261:15)
    at PodmanRemoteSshTunnel.connect (/Users/cdrage/syncthing/dev/electron/podman-desktop/extensions/podman/dist/extension.cjs:4761:10)
    at PodmanRemoteConnections.refreshRemoteConnections (/Users/cdrage/syncthing/dev/electron/podman-desktop/extensions/podman/dist/extension.cjs:4880:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PodmanRemoteConnections.monitorRemoteConnections (/Users/cdrage/syncthing/dev/electron/podman-desktop/extensions/podman/dist/extension.cjs:4846:9)
2:05:55 PM [main] Engine does not have an API or a libpod API, returning empty array Podman
```

**Comment by afbjorklund** [comment]
Lima is using ed25519, for the generated key

**Comment by cdrage** [comment]
After a meeting with @praveenkumar we concluded that change will happen CRC-side so it will generate an openssh / ssh2 library compatible key, as right now it generates an RSA private key which does not have the necessary SSH-related metadata to work correctly.

This fortunately still works on the command line with `podman image ps` commands, but unfortunatley not with Podman Desktop as we use the ssh2 library that requires ssh keys rather than the standard non-ssh / RSA generated keys.

**Comment by praveenkumar** [comment]
I am closing this issue on PD side because the library used here not able to support ecdsa algo and we are implementing ec25519 algo on openshift local side (PR in review process). I tested that PR with latest podman nightly and it does work.
