### ISSUE TITLE
Pop up about apply changes for Openshift local need to create new instance

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman-desktop#8368]
### Bug description

If you have OpenShift local plugin installed then everytime you go to `Settings => Preference` a pop up will appear about OpenShift Local change even you don't change anything. 

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- Install podman desktop
- Install OpenShift Local extension
- Start the OpenShift local 
- Go to `Settings => Preference` and you will see the pop up even you don't do anything. 
![Screenshot from 2024-08-07 14-37-56](https://github.com/user-attachments/assets/5014be8d-a3ef-4d72-b71f-904601c1b22a)

**Comment by jeffmaury** [comment]
Moved to https://github.com/crc-org/crc-extension/issues/249
