### ISSUE TITLE
Update documentation about the Kubernetes features

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8371]
### Is your enhancement related to a problem? Please describe

We have been adding a lot of new capabilities related to Kubernetes, our current documentation is not up to date

### Describe the solution you'd like

We have the current documentation for kubernetes here: https://podman-desktop.io/docs/kubernetes 

But a lot of these should be updated:
- Interacting with a kubernetes context: we have the kubernetes context screen in the settings
- A lot of screens have been added that allow the user to interact with the kubernetes resources

It would be nice to add a documentation about how to switch to a different namespace (since this is going to be done outside of podman desktop)

**Comment by slemeur** [comment]
As an initial step, I'd recommend to analyze the gap between what's currently documented and what we have in the tool. 
Based on this, it would be nice to draft an outline for the kubernetes documentation section.

**Comment by shipsing** [comment]
Current outline: 
![image](https://github.com/user-attachments/assets/1043cbed-ce96-4f35-b887-1f370dc92dd2)

**New Outline proposed for the Kubernetes section** 

**Configuring access to your kubernetes cluster** [manual approach-- [existing Kubernetes](https://podman-desktop.io/docs/kubernetes/existing-kubernetes) ; we can place this procedure before the Selecting a context section to help users to understand how access to a Kubernetes cluster is configured manually]

**Selecting your Kubernetes context** [all three options-- using Status bar, using Podman Desktop settings, and using Podman Desktop tray icon]
In this section, we can also **document this behavior:** When deploying a pod to a Kubernetes cluster, the Kubernetes Namespaces dropdown list is automatically populated based on the current Kubernetes context. For example, If you have installed and configured minikube, kind, OpenShift Local, or Developer Sandbox extensions, a respective Kubernetes context is automatically added in the Podman Desktop application. When you select a new context as your current Kubernetes context, the dropdown list automatically shows the namespaces present in that Kubernetes context.  

**New section: Creating pods from a Kubernetes YAML file** (Pods > Play Kubernetes YAML to define and use your own customized Kubernetes YAML)

**Deploying a container or pod** (both the deploying a container and deploying a pod procedures are almost similar. The configuration is done on the `Deploy generated pod to Kubernetes` page. We can mold the procedure a bit to have a common section)

**New section: Working/Playing with Kubernetes**
	Viewing or editing Kubernetes configuration (apply yaml manifest)
	Creating an ingress path-based routing
	Creating a Persistent Volume Claim

**Pushing an image to Kubernetes** 
	pushing an image to Kind
	Pushing an image to Lima
	Pushing an image to Minikube

**Comment by shipsing** [comment]
Based on the UI analysis i did, i proposed the above outline ^^^^^

Maybe for now, I can focus on these two aspects and create a small PR and then, work on the outline proposed ^^^^:

- How to select a Kubernetes context using the Podman Desktop settings
- How to switch to a different namespace

**Comment by slemeur** [comment]
Thanks @shipsing for the outline proposition.

IMO, we need to introduce a section that explain how to setup a kubernetes cluster from Podman Desktop (with the help of the extensions we are providing), and which will link to the other sections we have bellow about kind, minikube. 

I think we are also missing a section that speaks about all the type of kubernetes objects we are now supporting. We have Nodes, Deployments, Services, Ingresses, Persistent Volumes Claims and ConfigMaps & Secrets. 

Otherwise, that seems pretty accurate to me

**Comment by shipsing** [comment]
@slemeur, I also thought of creating a new section covering details of how to set up a kube cluster using these extensions. 
But, i think the details are already covered in our doc: [Creating a local Kind-powered Kubernetes cluster](https://podman-desktop.io/docs/kind/creating-a-kind-cluster) and [Creating a local Minikube-powered Kubernetes cluster
](https://podman-desktop.io/docs/minikube/creating-a-minikube-cluster).

Maybe, we can provide a link to those procedures in the Kubernetes section. For better content accessibility, I can create a reference section named `Setting up a Kubernetes cluster`, build up some context and then, provide links to those procedures.
I mean we can create three types of content in a doc: Concept, Procedure, and Reference.

**Comment by afbjorklund** [comment]
It is possible to create a regular Kubernetes cluster using Minikube, and then use it with "existing cluster".

```
minikube start --vm
```

Similar to how you can create one using Lima, and then configure Podman Desktop to use the existing VM...

```
limactl start template://k8s
```

But the current minikube plugin does **not** allow you do it, as it only supports the two container drivers.

It is also not possible to access the container runtime of the cluster, only of the engine hosting the node.

---

Maybe there should be a such a feature in Podman Desktop, to run a regular minikube Kubernetes cluster:

* https://github.com/containers/podman-desktop-extension-minikube/issues/95

Instead of deploying a Podman Machine (or Docker Machine), and then running containerd-in-podman etc

Main downside at the moment (beyond the complex setup), is the old Podman version available in Ubuntu.

https://podman-desktop.io/blog/sharing-podman-images-with-kubernetes-cluster

https://minikube.sigs.k8s.io/docs/drivers/ shows the various hypervisors available

**Comment by afbjorklund** [comment]
Adding Podman to Kubernetes:

* https://github.com/containers/podman-desktop/issues/4345

One way forward would be to have [CRI-O](https://cri-o.io/) host a package also for podman, like they are doing for conmon and crun.

Then you could add that as an add-on, similar to how you can add nerdctld to the containerd.io package from Docker

**Comment by shipsing** [comment]
Thank you, @afbjorklund, for providing your insights here. It would be great to see this feature implented into our Podman Desktop application.

**Comment by afbjorklund** [comment]
It could also be scoped out completely, like was done for Docker Machine or for managing the Lima instances?

**Comment by shipsing** [comment]
@nichjones1 @slemeur, I am planning to create the following PRs to cover different aspects associated with this issue:

- PR1: Setting up a Kubernetes cluster 
- PR2: Configuring Kubernetes objects (Nodes, Deployments, Services, Ingresses, Persistent Volumes Claims and ConfigMaps & Secrets)
- PR3: Selecting context using the Podman Desktop settings and Selecting a namespace using command line [kubectl config set-context <name> --namespace=<name>] (https://github.com/containers/podman-desktop/issues/4990#issuecomment-1827850104). Once we provide this ability in the UI, we can capture the same later.

**Comment by afbjorklund** [comment]
Scoped out "running a Kubernetes cluster" (like: with minikube or Lima) from the Podman Desktop setup, and assume it means "running a Kubernetes cluster _on top of Podman Machine_" and that all cluster access is done through `kubectl`.

You can still access existing clusters (created outside the app), and set up remote access to the container runtime inside the cluster*. It is just not something that is available out-of-the-box, but requires some additional work - if desired...

----

\* e.g. minikube `docker-env`, lima "Socket" preference ([custom](https://podman-desktop.io/docs/lima/customizing)), etc

Podman Desktop does not support direct containerd access (for kind)
