### ISSUE TITLE
Openshift Local Release

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#8372]

**Comment by odockal** [comment]
We have conducted [testing](https://docs.google.com/spreadsheets/d/1T5c25_eV1BLH3WrDZQaegzbJxcvQh7PTM1ffqvIsShk/edit?gid=284997826#gid=284997826) of the OpenShift Local extension [2.0.0](ghcr.io/crc-org/crc-extension:2.0.0) and we have discovered/encountered these issues:

* https://github.com/crc-org/crc-extension/issues/296
* https://github.com/crc-org/crc-extension/issues/297
* https://github.com/crc-org/crc-extension/issues/206
* https://github.com/crc-org/crc-extension/issues/298

Nevertheless, we consider the state of the extension to be eligible for release. **Good to go!**

Thanks @lstocchi @dgolovin @jeffmaury and other for your work. Thanks @cbr7 and @amisskii for helping with testing the extension.

**Comment by dgolovin** [comment]
Published to catalog

![Image](https://github.com/user-attachments/assets/a65f40f3-f478-4d3a-803e-461de0587833)
