### ISSUE TITLE
Drop down menus in collapsed form are displayed only in dark mode

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8390]
### Bug description

It seems that drop down menus are only displayed in dark mode when they are in collapsed form, if the user expands them they will be shown in light mode.

https://github.com/user-attachments/assets/b976c4be-fb71-492f-805c-5c64ee1d4242

https://github.com/user-attachments/assets/8a0c0a81-8d76-4988-b61c-c1f185ee8963

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.11.1

### Steps to reproduce

1. Install PD 1.12
2. Switch to light mode.
3. Navigate to somewhere in the app where a drop down menu exists.
4. Notice that the drop down menu will be in dark mode while in collapsed form, but light mode when expended.

**Comment by deboer-tim** [comment]
Same fundamental issue as #8390 - we need a select/dropdown component.

**Comment by deboer-tim** [comment]
This was fixed via #9458 (and fix in #9498).
