### ISSUE TITLE
Podman provider status unknown

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#84]
### Bug description

On the provider tab, my Podman status says "unknown", but it says "Podman / started" below and is clearly connected and able to read images and containers. I would expect it to say started or connected.

### Operating system

macOS 12.3.1 M1

### Version

next (development version)

**Comment by benoitf** [comment]
The main question is what should be the status of the provider when there are multiple machines.

What is the status when podman is not even installed ?
What is the status when there is no machine ?
What is the status when a machine is started ?
What is the status when there are multiple machine (knowing that only one can be started)

Machine status is easier.

**Comment by deboer-tim** [comment]
Agreed, there are several more complicated cases, and I'd be happy covering the simple cases via machine status for now (i.e. 'uninstalled' could mean podman is not installed or there is no machine, 'started' means a machine is running).
