### ISSUE TITLE
Improve Kubernetes informer behaviour based on provider state 

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8400]
### Is your enhancement related to a problem? Please describe

When I start a Kubernetes provider like Kind, the informer has already backed off to a really slow ping, so I need to take manual action to get it to try again. When I stop the provider, we keep trying to ping it.

### Describe the solution you'd like

For Kubernetes contexts that we can map to known providers with a lifecycle, we should use the provider state to improve behaviour of the informer, e.g.:
- When the provider starts, automatically try to connect or reduce the backoff. A slight delay to make sure it's 'up' is fine, or maybe it doesn't connect until 2nd or 3rd attempt - just not the current 60s.
- When the provider is stopped, don't try to (re)connect.

**Comment by feloy** [comment]
After discussion on today's team meeting (11/07), we will rely on health check, which are light enough (especially locally), and don't want to rely on providers states which can be complex to get and handle.
