### ISSUE TITLE
Renaming image <none> returns error: normalizing name for compat API: parsing reference <none>

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8414]
### Bug description

Error while editing a name of image with unspecified `<none>` name.

### Operating system

Mac OS 14

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

1. Build an image locally without specifying the name (ie. https://github.com/odockal/podman-desktop-qe/tree/main/examples/images/alpine-hello)
2. It should produce `<none>` image
3. Try to edit the image name
4. Assert: image can be renamed
Actual: error while trying to rename such image

### Relevant log output

```shell
(HTTP code 500) server error - normalizing image: normalizing name for compat API: parsing reference '<none>:': invalid reference format
```

**Comment by Semo** [comment]
Same on the MacOS Beta 15

**Comment by axel7083** [comment]
Reproducing on Fedora 40

`(HTTP code 500) server error - normalizing image: normalizing name for compat API: parsing reference "<none>:": invalid reference format`
