### ISSUE TITLE
Cannot start existing containers after having long running Podman Machine

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8423]
### Bug description

I had working Podman Machine rootfull on Mac OS testing some stuff. Images, containers, etc. without any issue. I then left the machine to its fate and returned after two days to get back working with containers.

I noticed a problem when trying to start the containers, that were in the stopped state. I could not start any of them, without actually showing any issues.

[Screencast_20240812_085912.webm](https://github.com/user-attachments/assets/b2a1ac0c-d581-4c86-9df1-13c14815ed77)

I could create new container, but after stopping it, I could not get it started again. UI did not show any issue, on cli, I was able to get to error message, though.

```
% podman start httpd-24
Error: unable to start container "ad96406276bb7e930a97f922b2fa39be21f99464f84393983c65a34aebad705d": container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

### Operating system

Mac OS 14 M2

### Installation Method

None

### Version

1.12.0-next

### Additional context

After restarting the podman machine, everything started to working fine again. My bet is that something went wrong inside the running vm. Probably error message could suggest more. It would be just good that we propagate the error that we see on cli, instead of just basically doing nothing on the UI side.

**Comment by jeffmaury** [comment]
What is an Applehv machine or a libkrun one ?

**Comment by odockal** [comment]
AppleHV it was.

**Comment by keverw** [comment]
I was ran into this too with 1.12.0 updating on Mac... I restarted, even uninstalled and reinstalled. But the past version was fine. I seen some other issues with people mentioning they had startup issues on Windows too recently, so wonder if perhaps related.

Mine is also the default, Default (Apple HyperVisor). M1 Max, macOS 14.6.1 (23G93) if that helps.

**Comment by odockal** [comment]
Was not able to reproduce. This is truly hard to debug.

**Comment by benoitf** [comment]
it's an upstream issue (podman repository), not podman-desktop issue

**Comment by odockal** [comment]
I have found an upstream issue which seems at least related: https://github.com/containers/podman/issues/18230. 

I am closing our since I have not seen this for a long time.
