### ISSUE TITLE
UserModeNetworking enabled machine fails to pull any image

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#8429]
### Bug description

On Friday (09.08.2024) any image whatsoever was unable to be pulled exclusively in UserModeNetworking (WSL) enabled machine.
I've tested the pull on other machines (rootful default, rootless) and image pulling worked.
I've tried to create the UMN machine several times with the same results.

Today (12.08.2024) I've re-created the UserModeNetworking machine again, tested image pull and container creation - worked without problems.

I am suspecting two possibilities:
* Infrastructure instability (less likely)
* Issue with base image

### Operating system

Windows 10 22H2

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

* Download, install, onboard Podman Desktop
* Create a UserModeNetworking rootful machine (WSL)
* Pull any image

### Additional context

![Podman_Desktop_zvknkI1PEr](https://github.com/user-attachments/assets/eb2b56ae-59af-4dc3-81dc-8ce5f9d93da0)
![powershell_XrfjKvGFuw](https://github.com/user-attachments/assets/b8656a5f-6997-4802-b54a-e5c05721fb27)
![powershell_XQkMfjEv8h](https://github.com/user-attachments/assets/57af0e63-6840-4ab2-b745-979382939d27)
![powershell_cdt1HkPMFu](https://github.com/user-attachments/assets/8ded5d0a-6c8d-4132-a801-7da0dbb0e1f9)
![powershell_eMDs56ppGA](https://github.com/user-attachments/assets/294ea052-6ea3-4ae8-8c22-57f71207f1e8)
![Podman_Desktop_KPW34b0rY4](https://github.com/user-attachments/assets/4f551b7e-fae4-48a7-8e3c-c7cc755a7778)

**Comment by nichjones1** [comment]
@gbraad can you check to see if this is a known gvisor-tap-vsock?

**Comment by jeffmaury** [comment]
I can reproduce on my machine and I did the following investigation:

- went on WSL distribution for the podman machine  and noticed the nameserver is 192.168.127.1
- tried ping 192.168.127.1 from the same shell -> KO
- went to the podman-net-usermode WSL distribution
- ran ps -ef
- noticed a lot of gvproxy.exe defunc processes

Will stay in that configuration and not reboot my machine

**Comment by jeffmaury** [comment]
I can reproduce: this is a matter of conflict between CRC and podman in usernetworking mode

So if you start podman then crc crc will not start because the port is already taken
But if you start crc then podman then no error is reported as gvproxy is running in the user mode networking wsl distribution but the whole DNS setup is broken in the podman machine. Nothing to do on our side as it's between podman and crc
