### ISSUE TITLE
Podman autostart setting not retained

### ISSUE THREAD

**Issue by sshambar** [containers/podman-desktop#8435]
### Bug description

The podman autostart setting is changing to "on" when restarting Desktop after machine creation (with off), or when starting desktop with podman machine already running.

Expected behavior is the autostart setting should be retained, and be unrelated to the current running state of the machine.

### Operating system

macOS Sonoma 14.6.1

### Installation Method

Brew (macOS)

### Version

1.11.1

### Steps to reproduce

Remove any existing settings: 
 - ~/Library/Preferences/io.podmandesktop.PodmanDesktop.plist
 - ~/Library/Application Support/Podman Desktop
Remove any existing podman machines:
 $ podman machine rm

1. Launch Desktop
2. Create podman machine with autostart disabled
3. Stop podman machine in desktop
4. Confirm setting for autostart is off
5. Quit desktop
6. Confirm podman machine is off cli '$ podman machine info'
7. Open desktop
8. After a few seconds, podman machine is started <- BUG, autostart was disabled!
9. Check autostart setting, it is on
10. Change autostart setting to off
11. Stop podman machine in desktop
12. Quit Desktop
13. Launch Desktop
14. podman machine remains Stopped <- Correct behavior!
15. Quit desktop
16. Start podman machine with cli '$ podman machine start'
17. Launch Desktop
18. Check autostart settings, it is now on <- BUG again, autostart was disabled!

**Comment by cbr7** [comment]
I've investigated this issue and was able to reproduce it, the problem mainly comes from the fact that the relevant setting in `~/.config/containers/podman-desktop/configuration/settings.json` which is `preferences.podman-desktop.podman.engine.autostart` gets removed from the json file upon podman machine startup/shutdown in certain scenarios and as such if the setting is set to `false` once it is removed from the file the following time PD is opened it will fallback to the default value, which is `true` for this setting.

It's not clear to me why the setting is deleted from the `settings.json` when the podman machine starts, but I've even seen this happen when starting the podman machine from podman CLI as can be seen in the following screenshot from my terminal app, but this is not the only time this happens, I've seen the same behavior when starting/stopping the podman machine from Podman Desktop.

![image](https://github.com/user-attachments/assets/004cda6b-d051-4975-9218-25870f1991c0)

**Comment by axel7083** [comment]
In the podman extension first we create a Provider

https://github.com/containers/podman-desktop/blob/425afb11dafb3c34d1284eeb61ee6e5fd5c832f8/extensions/podman/src/extension.ts#L1336

Then on this provider we register an autostart 

https://github.com/containers/podman-desktop/blob/425afb11dafb3c34d1284eeb61ee6e5fd5c832f8/extensions/podman/src/extension.ts#L1435


Let's follow the path of this `registerAutostart` method

https://github.com/containers/podman-desktop/blob/61eefc784b4c191bb14242dc3ecb9cd905ca346c/packages/main/src/plugin/provider-impl.ts#L260-L262

## Provider disposable

When the provider is registered it get a disposable

https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/main/src/plugin/autostart-engine.ts#L32-L39

The interested line is the following

https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/main/src/plugin/autostart-engine.ts#L37

This probably delete the configuration value. See the configuration-registry code 

https://github.com/containers/podman-desktop/blob/cfeb27546799febf3383b236e5602bbcee204970/packages/main/src/plugin/configuration-registry.ts#L236-L242

Maybe that's not something we should be doing ? As when the podman extension is stopped we are disposing the provider

https://github.com/containers/podman-desktop/blob/82b5f37336fc0edf7b1dede109537a54367a99f6/packages/main/src/plugin/extension-loader.ts#L820-L822

You can easily make the settings bugged by enabling / disabling the podman extension and changing the settings autostart.

**Comment by jeffmaury** [comment]
Closing as no reproducable in 1.12.0

**Comment by sshambar** [comment]
/reopen

Still reproducible on 1.12.0 on MacOS.

- Open Podman Desktop
- Stop any running machine
- Nav to Settings -> Setup Podman (gear under Podman section)
- Check that Autostart is OFF
- Quit Desktop
- Re-open Desktop <- machine does not start, good so far...
- Nav to Settings -> Setup Podman
- Check that Autostart is still OFF (should be)
- Quit Desktop
- Re-open Desktop <- podman machine will start - BUG still present
- Nav to Settings -> Setup Podman <- Autostart will be ON

**Comment by sshambar** [comment]
@jeffmaury - Jeff, could you reopen this issue; it's still present in 1.12.0 (I've posting details on reproducing the bug :). Thanks, Scott

**Comment by axel7083** [comment]
@sshambar could you retry in [v1.13.2](https://github.com/containers/podman-desktop/releases/tag/v1.13.2) ?

I re-opened without checking but https://github.com/containers/podman-desktop/pull/8884 was targetting 1.13.X so it should be fixed.

I cannot reproduce with the steps you mentioned above in 1.13.2 (on linux)

**Comment by sshambar** [comment]
@axel7083 - excellent... I can confirm v1.13.2 fixes the bug... Thanks!
