### ISSUE TITLE
On boarding light theme issue v1.12

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8447]
### Is your enhancement related to a problem? Please describe

![image](https://github.com/user-attachments/assets/6f39e6cc-99bc-44e3-acb5-a2ca8385539b)

### Describe the solution you'd like

Fixing the light theme

**Comment by gastoner** [comment]
How can be this reproduced? I've swithed off the Virtual Machine Platform feature on Windows and restarted ntb. But I can't reproduce this screen (I see only enabling kind, compose and podman)

**Comment by benoitf** [comment]
@gastoner you may just change the function that performs a check returning the opposite boolean value
