### ISSUE TITLE
Warn users before deleting

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#845]
### Is your enhancement related to a problem? Please describe

I've gone ahead and accidentally deleted a container from a misclick.

### Describe the solution you'd like

When deleting a container, we should have a modal that asks: "ARE YOU SURE?" with options for yes / no.

**Comment by benoitf** [comment]
It should be probably a setting that can be turned off.

**Comment by axel7083** [comment]
Fixed by https://github.com/containers/podman-desktop/pull/5445
