### ISSUE TITLE
No light mode when Podman Desktop set to "system" and system is light.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8477]
### Bug description

Light mode isn't shown when PD is on "system theme" and system is on light mode.

### Operating system

mac m1

### Version

next (development version)

### Steps to reproduce

1. Set system to light mode
2. Set PD to "system"
3. bootc wont be light mode

**Comment by deboer-tim** [comment]
Found this issue: to fix #8217 (light mode for DD extensions) we need to set the native theme (#8289), but this breaks the next time we use `window.matchMedia('(prefers-color-scheme: dark)')` to check what mode the system is in. So if your system is in light and you go light > system it's fine, but dark > system will change extensions but not PD itself, and vice-versa. Restarting Podman Desktop fixes things either way.

On config change we will need to set the native theme before checking `prefers-color-scheme`.
