### ISSUE TITLE
Podman desktop - Unable to install compose

### ISSUE THREAD

**Issue by siddhartharoy** [containers/podman-desktop#8483]
### Bug description

I am trying to install podman compose from podman desktop. But it fails to download. Have the same error with 1.11.1 and 1.12.0 both. This is a new laptop and Docker is not installed

OS - MacBook Pro M3 - Sonoma 14.6.1

### Operating system

MacBook Pro M3 - Sonoma 14.6.1

### Installation Method

Other

### Version

1.12.0

### Steps to reproduce

1) Installed Podman desktop using - podman-desktop-1.12.0-arm64.dmg. Also tried with universal installer but same issue
2) Went to settings and tried to install compose but it fails to download and install
3) Installing with admin privileges
![failed1](https://github.com/user-attachments/assets/83a0c2c3-9df5-4b92-9d37-a7332fa57491)
![failed2](https://github.com/user-attachments/assets/9a18392d-f013-477c-bcfa-55bd871cb665)

### Relevant log output

```shell
Detailed logs and software versions are shown as an attachments in additional context section
```

### Additional context

**Logs**
![podman logs](https://github.com/user-attachments/assets/3517f72c-dcb4-4710-bed0-fd0fdc6414d3)

**Versions**
![versions1](https://github.com/user-attachments/assets/581102fa-4b77-43d2-b463-ba1f432d8ed6)

**Comment by odockal** [comment]
@siddhartharoy Hello. thanks for opening the issue.
I have seen the similar problem on Mac OS 14 with M2 chip. Although, it worked for compose, it did not work for kubectl. I believe that the cause is the same. Error seems bit different, but still similar.
I suspect this one to blame: `[compose] GET /repos/docker/compose/releases/assets/181338715 - 500 with id UNKNOWN in 940 ms`
In my case, I got this one:
`[kubectl-cli] GET /repos/kubernetes/kubernetes/releases?per_page=10 - 403 with id xxxx-yyyy`.

Then the last error as seen in your screenshot is the same, `object could not be cloned`.

I think that problem was for you that github might have had an outage or in my case it was hitting a rate limit for requesting some information/files from github via its api.

**Comment by odockal** [comment]
@siddhartharoy Probably, if you try again, it might work. In cases of http code 500, might be also that you cannot reach github api endpoint? Might there be any proxy preventing you contacting such urls?

**Comment by siddhartharoy** [comment]
Hi @odockal, Thank you for the response. I tried multiple times but have same issue. I even at different hours but no success.

**Comment by siddhartharoy** [comment]
> @siddhartharoy Probably, if you try again, it might work. In cases of http code 500, might be also that you cannot reach github api endpoint? Might there be any proxy preventing you contacting such urls?

No, there is no proxy

**Comment by cdrage** [comment]
@siddhartharoy @odockal 

Tried this again locally and was unable to re-produce.

I was able to successfully install (and not receive any 500 or 403 error) with Compose.

I also uninstalled kubectl and kind and tried the same thing with those binaries, and had no issue.

Let me know @siddhartharoy if you can try again and see if the issue resolved.

**Comment by akrueger** [comment]
I have a similar issue. I cannot install kubectl or compose from Desktop:

Apple M1 Max
Sonoma 14.6.1 (23G93)

<img width="713" alt="Screenshot 2024-09-11 at 12 12 32" src="https://github.com/user-attachments/assets/a5ce3583-e54b-4818-ba1b-0bccaf86de70">
<img width="667" alt="Screenshot 2024-09-11 at 12 12 57" src="https://github.com/user-attachments/assets/3299cc35-076f-4967-97ce-c4eb5f1ff224">

**Comment by benoitf** [comment]
@akrueger could you check if `/usr/local/bin` folder exists ?

**Comment by akrueger** [comment]
@benoitf yes, it does and it is on the PATH

I manually added kubectl using this method and it works:
https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/

Not sure where Podman Desktop is running into trouble. Are there logs I can check?

I haven't tried adding compose manually yet.

**Comment by akrueger** [comment]
@benoitf After playing around with it, I believe this happens when there are already symlinks in the bin folder for previous compose items (from Docker Desktop for example). Once I cleaned up Symlink there, it installed fine.

**Comment by slemeur** [comment]
linking to https://github.com/containers/podman-desktop/issues/5334#issuecomment-2345487340

**Comment by cdrage** [comment]
I think that we should add this to documentation under troubleshooting for Compose to check the system for symlinks, what do you think @slemeur @benoitf ?

Looks like fallout from uninstalling docker desktop / installing compose may create issues with regards to the symlinking.

**Comment by benoitf** [comment]
troubleshooting doc is great but Podman Desktop should detect that there is a symlink
if there is a symlink we could ask the user to replace it, etc.

so no error -1, just questions being asked by the user

**Comment by akrueger** [comment]
@benoitf @cdrage Would it work to namespace it such as Docker Desktop has done here with `kubectl`?

<img width="595" alt="Screenshot 2024-09-16 at 14 11 32" src="https://github.com/user-attachments/assets/c8761f8a-7e9d-48b9-88f8-c2c73579ec0d">

I think it's reasonable to assume Docker reserves the `docker-compose` command for itself. In fact if you install Docker Desktop after Podman Desktop it's just going to overwrite that symlink with its own for `docker-compose`.

`docker-compose.podman` seems like a good option

**Comment by simonmacor** [comment]
I'm facing the same problem.

**Operating system**
Windows 10

**version**
1.12.0

**Comment by cdrage** [comment]
> I'm facing the same problem.
> 
> **Operating system** Windows 10
> 
> **version** 1.12.0

Any way you can provide logs from Podman Desktop / errors that you get? As you are the first coming from Windows with this issue.

**Comment by simonmacor** [comment]
<img width="788" alt="compose setup" src="https://github.com/user-attachments/assets/4816f204-c1c2-453e-aa02-7eb68fd849c4">

<img width="793" alt="logs" src="https://github.com/user-attachments/assets/1eb15cd4-e47d-4315-9793-64e4ff008a39">

**Comment by cdrage** [comment]
> <img alt="compose setup" width="788" src="https://private-user-images.githubusercontent.com/2589203/368221229-4816f204-c1c2-453e-aa02-7eb68fd849c4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODgwMjgsIm5iZiI6MTcyNjU4NzcyOCwicGF0aCI6Ii8yNTg5MjAzLzM2ODIyMTIyOS00ODE2ZjIwNC1jMWMyLTQ1M2UtYWEwMi03ZWI2OGZkODQ5YzQuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTU0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZmNDI0ZDU1OGRjY2Y1Nzk4NmFhYTA0MjVkMzNiOGQ0YWNkMzhlZGM1YmE4MWE4NTAyYTk3MWI0Mzc0NDBlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t6OkbVi1Z98I4G5lTFIQiuxoHvcegqcKvQYuHG5JHEs"> <img alt="logs" width="793" src="https://private-user-images.githubusercontent.com/2589203/368220463-1eb15cd4-e47d-4315-9793-64e4ff008a39.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODgwMjgsIm5iZiI6MTcyNjU4NzcyOCwicGF0aCI6Ii8yNTg5MjAzLzM2ODIyMDQ2My0xZWIxNWNkNC1lNDdkLTQzMTUtOTc5My02NGU0ZmYwMDhhMzkuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTU0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA3YWExODY4MzJiNjEzYTlhNTg2NTZiN2ZlZDk4ODQ0ZDlmYzUwNTEwZjc3MjQ5MGI3MDkzNDFjZjAwMjBiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1DWrS8jjt_5Pws6uHrybTnk7NGOfGZbYoRG2KOJsx_w">

Could you do `whereis docker-compose` on Powershell and show where your docker-compose currently is?

**Comment by simonmacor** [comment]
docker-compose is not installed

**Comment by cdrage** [comment]
> <img alt="compose setup" width="788" src="https://private-user-images.githubusercontent.com/2589203/368221229-4816f204-c1c2-453e-aa02-7eb68fd849c4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODgwMjgsIm5iZiI6MTcyNjU4NzcyOCwicGF0aCI6Ii8yNTg5MjAzLzM2ODIyMTIyOS00ODE2ZjIwNC1jMWMyLTQ1M2UtYWEwMi03ZWI2OGZkODQ5YzQuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTU0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZmNDI0ZDU1OGRjY2Y1Nzk4NmFhYTA0MjVkMzNiOGQ0YWNkMzhlZGM1YmE4MWE4NTAyYTk3MWI0Mzc0NDBlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t6OkbVi1Z98I4G5lTFIQiuxoHvcegqcKvQYuHG5JHEs"> <img alt="logs" width="793" src="https://private-user-images.githubusercontent.com/2589203/368220463-1eb15cd4-e47d-4315-9793-64e4ff008a39.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODgwMjgsIm5iZiI6MTcyNjU4NzcyOCwicGF0aCI6Ii8yNTg5MjAzLzM2ODIyMDQ2My0xZWIxNWNkNC1lNDdkLTQzMTUtOTc5My02NGU0ZmYwMDhhMzkuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTU0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA3YWExODY4MzJiNjEzYTlhNTg2NTZiN2ZlZDk4ODQ0ZDlmYzUwNTEwZjc3MjQ5MGI3MDkzNDFjZjAwMjBiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1DWrS8jjt_5Pws6uHrybTnk7NGOfGZbYoRG2KOJsx_w">

if it does not show `docker-compose` existing when you do `whereis`, it could either be:

- using a VPN / proxy
- GitHub is down (500 error)

Could you double check you have nothing in your proxy settings / no VPN and try again?

**Comment by simonmacor** [comment]
Sorry for the lack of details. I already checked the VPN settings. I don't have a vpn configured.

**Comment by neverd1m** [comment]
I've faced similar issue with both kubectl and compose installation. Following the thread i tried to change my network presence and use VPN. It did work after that, so i assume the idea of github having limits is correct.


> @siddhartharoy Hello. thanks for opening the issue. I have seen the similar problem on Mac OS 14 with M2 chip. Although, it worked for compose, it did not work for kubectl. I believe that the cause is the same. Error seems bit different, but still similar. I suspect this one to blame: `[compose] GET /repos/docker/compose/releases/assets/181338715 - 500 with id UNKNOWN in 940 ms` In my case, I got this one: `[kubectl-cli] GET /repos/kubernetes/kubernetes/releases?per_page=10 - 403 with id xxxx-yyyy`.
> 
> Then the last error as seen in your screenshot is the same, `object could not be cloned`.
> 
> I think that problem was for you that github might have had an outage or in my case it was hitting a rate limit for requesting some information/files from github via its api.

**Comment by cdrage** [comment]
With the limit: "In general, no more than 80 content-generating requests per minute and no more than 500 content-generating requests per hour are allowed. " 

It could be that the limit is being reached before Podman Desktop checks due to limiting per IP.

**Comment by z-aki** [comment]
> using a VPN / proxy

In my case it was a VPN with a custom CA certificate that podman desktop did not like. Is there a way for podman to use macOS Keychain certificates? VSCode does that. Browsers also do it.

**Comment by cdrage** [comment]
> > using a VPN / proxy
> 
> In my case it was a VPN with a custom CA certificate that podman desktop did not like. Is there a way for podman to use macOS Keychain certificates? VSCode does that. Browsers also do it.

Investing this further, this MAY be fixed by https://github.com/containers/podman-desktop/pull/4356 when I tested it locally.

This will most likely appear in the next release (or 1.14)

**Comment by z-aki** [comment]
> Investing this further, this MAY be fixed by #4356 when I tested it locally.
> 
> This will most likely appear in the next release (or 1.14)

Great. I think for corporates without docker license: self-signed certificates, proxy HTTP URL, and proxy PAC file support are going to be the dealbreaker.

**Comment by cdrage** [comment]
I'm going to close this for now as https://github.com/containers/podman-desktop/pull/4356 has been merged in, after testing https://github.com/containers/podman-desktop/pull/4356 I am unable to reproduce any form of issues with Compose.

However... the issue can still be there regarding rate limiting github API calls, but unfortunatley we cannot control that.

Closing for now and please re-comment if there is an issue.

**Comment by z-aki** [comment]
In the code I don't see reference to certificates or macOS keychain.. or maybe a new issue tracking would be useful.

https://stackoverflow.com/a/22436756
https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl


For local testing, if you run your own server on localhost with a self signed cert and try to pull from it (no need to set up registry, just connection is enough) I'd expect it to fail

To make the browser connect to it, adding the cert to keychain is enough.

Running postman proxy will also work.. it installs a postman cert to system keystore, and runs a localhost server.

**Comment by NBardelot** [comment]
@cdrage 

> However... the issue can still be there regarding rate limiting github API calls, but unfortunatley we cannot control that. Closing for now and please re-comment if there is an issue.

+1 on @z-aki 's answer. Here the issue comes from not being able to configure a certificate authority for corporate proxies for podman desktop (even though the certificates have been correctly configured in the podman machine).

I see there is a `%APPDATA%\Local\Programs\podman-desktop\resources\win-ca\roots.exe` which is probably what the podman desktop uses... 

Edit: When i look at `main/packages/main/src/plugin/certificates.ts` it uses `%APPDATA%\Local\Programs\podman-desktop\resources\win-ca\roots.exe` to retrieve the certificates from the host's certificate store when running on Windows.

In our case, even if the corporate proxy's CA root certificate is correctly configured in the certificate store podman desktop does not accept it.

**Comment by Trung-Pham-Modec** [comment]
My Podman compose is downloaded but failed to install. No VPN is active and so is GitHub

**Comment by ohmydds** [comment]
> > using a VPN / proxy
> 
> In my case it was a VPN with a custom CA certificate that podman desktop did not like. Is there a way for podman to use macOS Keychain certificates? VSCode does that. Browsers also do it.

I get a 500 error when trying to install compose from the GUI app from behind Zscaler.
```
Unable to download docker-compose binary: HttpError: unable to get local issuer certificate
```

I manually installed the binary to a directory in my `$PATH` but Podman Desktop doesn't find it even though it's available with the `podman` command:
```
$ podman compose version
>>>> Executing external compose provider "$HOME/.local/homebrew/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

Docker Compose version 2.36.2
```

I get similar results when trying to install `kubectl`.

----

System Specs:
```
Apple M1 Pro
System Version: macOS 15.5 (24F74)
Kernel Version: Darwin 24.5.0
```

**Comment by odockal** [comment]
@ohmydds Is homebrew folder on your path?

**Comment by ohmydds** [comment]
> [@ohmydds](https://github.com/ohmydds) Is homebrew folder on your path?

It is (I manually replaced my home directory with `$HOME`):
```
$HOME/.local/share/mise/installs/usage/2.1.1:$HOME/.local/share/mise/installs/node/24.3.0/bin:$HOME/.local/bin:$HOME/.local/homebrew/bin:$HOME/.local/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/opt/podman/bin
```

And the path to the binaries:
```
command -v docker-compose 
$HOME/.local/homebrew/bin/docker-compose

command -v kubectl
$HOME/.local/bin/kubectl
```

Does the GUI app use a different `$PATH` than the cli?

**Comment by odockal** [comment]
@ohmydds I would open new issue and there are basically two problems here. One is that the cli binary is on PATH and Podman Desktop does not see it.

the other one is problem with downloading the cli tool when you are on VPN and certificate is not visible/valid.
