### ISSUE TITLE
podman-desktop hangs upon startup

### ISSUE THREAD

**Issue by fmuntean** [containers/podman-desktop#8486]
### Bug description

podman-desktop hangs upon startup:
not even able to get to the onboarding to install podman.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

uninstall; delete all related folders; install 1.12.0 

### Relevant log output

```shell
Checking for update
Starting http server to handle webviews on port 44000
System ready. Loading extensions...
Activating extension (podman-desktop.compose) with max activation time of 20 seconds
Fetched https://registry.podman-desktop.io/api/extensions.json in 164.96519999999998ms
Activating extension (podman-desktop.compose) ended in 117 milliseconds
Activating extension (podman-desktop.docker) with max activation time of 20 seconds
Activating extension (podman-desktop.docker) ended in 4 milliseconds
Activating extension (podman-desktop.kind) with max activation time of 20 seconds
[kind] kind extension is active
Activating extension (podman-desktop.kind) ended in 361 milliseconds
Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
[kube-context] starting extension kube-context
Activating extension (podman-desktop.kube-context) ended in 11 milliseconds
Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
```

### Additional context

with help from discord @ScrewTSW  we tried cleaning the system multiple times trying multiple installers with no luck.

**Comment by fmuntean** [comment]
we even renamed the kubectl.exe to see if it pass this step but no luck.
I have no plans to use kubectl from podman however I need ot be able to use kubectl from outside

**Comment by ScrewTSW** [comment]
Setup and onboarding works as intended on newly created Windows account

**Comment by ScrewTSW** [comment]
After full cleanup, Podman Desktop hangs before onboarding step is launched
![image](https://github.com/user-attachments/assets/65cc8e5f-17a0-494a-9024-d91124f9c02c)
logs stop at trying to activate `kubectl-cli`

**Comment by fmuntean** [comment]
I just renamed the .kube/config file and the podman proceed farther asking to install podman.
whit this file renamed the system seems to work fine. I went and disable the plugins I don't need but when I rename the file back the podman desktop hangs again:
Checking for update
Starting http server to handle webviews on port 44000
System ready. Loading extensions...
Activating extension (podman-desktop.compose) with max activation time of 20 seconds
Fetched https://registry.podman-desktop.io/api/extensions.json in 161.42280000000005ms
Activating extension (podman-desktop.compose) ended in 122 milliseconds
Activating extension (podman-desktop.docker) with max activation time of 20 seconds
Activating extension (podman-desktop.docker) ended in 4 milliseconds
Extension (podman-desktop.kind) not activated because it is disabled
Extension (podman-desktop.kube-context) not activated because it is disabled
Extension (podman-desktop.kubectl-cli) not activated because it is disabled
Extension (podman-desktop.lima) not activated because it is disabled
Activating extension (podman-desktop.podman) with max activation time of 20 seconds

**Comment by jeffmaury** [comment]
Seems related to kubecli extension that may take forever based on the output of the kubectl binary

**Comment by ScrewTSW** [comment]
> Seems related to kubecli extension that may take forever based on the output of the kubectl binary

It's very strange, that even when the extension is disabled, it still tries to parse `~/.kube/config` and causes Podman Desktop to freeze.

**Comment by fmuntean** [comment]
> Seems related to kubecli extension that may take forever based on the output of the kubectl binary

kubectl-cli extension is disabled as you can see in the logs above. 
Why is podman-desktop trying to read that file ?

**Comment by ScrewTSW** [comment]
@fmuntean Try disabling kubecontext extension as well

**Comment by fmuntean** [comment]
> @fmuntean Try disabling kubecontext extension as well

it is deactivated

**Comment by ScrewTSW** [comment]
Only place the file is touched seems to be in kubecontext extension
https://github.com/containers/podman-desktop/blob/19f61a91fee8cc8222382c8945fe7f0a952b0172/extensions/kube-context/src/extension.ts#L34

`activate()`
`updateContext()`
`getKubeconfig()`

and quite a few functions in https://github.com/containers/podman-desktop/blob/19f61a91fee8cc8222382c8945fe7f0a952b0172/packages/main/src/plugin/kubernetes-client.ts#L415

**Comment by fmuntean** [comment]
kubectl config get-contexts will retrieve all the the context and takes less than a second in my case.

**Comment by odockal** [comment]
@fmuntean thanks for reporting the issue. I was testing this on Windows 10 and I did not face the freeze problem, although I have seen some logs in the dev console, that could be related to this problem.

```
main ↪️ [kubectl-cli] Error getting kubectl from user PATH: Error: Failed to execute command: spawn kubectl.exe ENOENT, trying from extension storage path

main ↪️ [kubectl-cli] Error getting kubectl version system from extension storage path Error: Failed to execute command: spawn C:\Users\Ondrej\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.kubectl-cli\bin\kubectl.exe ENOENT
    at ChildProcess.<anonymous> (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:342:12755)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

...
main ↪️ [kubectl-cli] Error activating extension TypeError: Invalid Version: 
    at new N (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:82298)
    at Pn (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:86637)
    at Object.jn [as gt] (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:86989)
    at wu (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:9:3147)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Steps to reproduce while on Windows 11:
0. Clean machine, install podman-desktop 1.12.0
1. Have some content in `~/.kube/config`
2. Start up Podman Desktop
3. Assert: Onboarding is shown and user can go through it
Actual result: App freezes on start up. Not able to go through the onboarding

@ScrewTSW @fmuntean Are the steps correct?

**Comment by ScrewTSW** [comment]
It's more like a lot of complex content in the ~/.kube/config

Doesn't really happen on clean installs or simple deployments.

There are multiple clusters involved, set up in many different ways.

To me it seems like some issue with parsing the config, or maybe the extensions are trying to contact the clusters for health check and info.

Supposedly just leaving Podmane Desktop open does not get around the problem, it's just frozen forever, but yes, the steps are more or less correct.

The most annoying part is that there is no error in logs to bounce off of.

**Comment by fmuntean** [comment]
> @fmuntean thanks for reporting the issue. I was testing this on Windows 10 and I did not face the freeze problem, although I have seen some logs in the dev console, that could be related to this problem.
> 
> ```
> main ↪️ [kubectl-cli] Error getting kubectl from user PATH: Error: Failed to execute command: spawn kubectl.exe ENOENT, trying from extension storage path
> 
> main ↪️ [kubectl-cli] Error getting kubectl version system from extension storage path Error: Failed to execute command: spawn C:\Users\Ondrej\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.kubectl-cli\bin\kubectl.exe ENOENT
>     at ChildProcess.<anonymous> (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:342:12755)
>     at ChildProcess.emit (node:events:519:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
>     at onErrorNT (node:internal/child_process:484:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 
> ...
> main ↪️ [kubectl-cli] Error activating extension TypeError: Invalid Version: 
>     at new N (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:82298)
>     at Pn (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:86637)
>     at Object.jn [as gt] (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:3:86989)
>     at wu (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kubectl-cli\builtin\kubectl-cli.cdix\dist\extension.js:9:3147)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> Steps to reproduce while on Windows 11: 0. Clean machine, install podman-desktop 1.12.0
> 
> 1. Have some content in `~/.kube/config`
> 2. Start up Podman Desktop
> 3. Assert: Onboarding is shown and user can go through it
>    Actual result: App freezes on start up. Not able to go through the onboarding
> 
> @ScrewTSW @fmuntean Are the steps correct?

the steps are correct however I do not get any errors in the log.

**Comment by fmuntean** [comment]
I was able to continue by renaming the ./kube/config file.
however, when I rename that file back, even after disabling the plugins related to this, the app hangs immediately, as there seems to be a watch on that file.

**Comment by odockal** [comment]
@fmuntean how much stuff do you get there?

**Comment by fmuntean** [comment]
> @fmuntean how much stuff do you get there?

you mean in the kube/config file ? I reduced it to 5 clusters and still have the issue. so the problem is not with the file itself.

The biggest problem here is why that file is even accessed if I disabled the plugins ? (see logs above)

**Comment by axel7083** [comment]
> The biggest problem here is why that file is even accessed if I disabled the plugins ? (see logs above)

The Podman-Desktop core uses the kubernetes api to list the clusters and resources in it, it does not need the kubectl extensions to be running.

Podman-Desktop (core) manage the current context and this cannot be disabled. We are using the [@kubernetes/client-node](https://www.npmjs.com/package/@kubernetes/client-node) library.

Here is our workflow in podman-desktop

1. reading the kube config from the file configured (or `~/.kube/config` if none provided)

https://github.com/containers/podman-desktop/blob/49239338973f18887022b6ac00e27525f760d3a4/packages/main/src/plugin/kubernetes-client.ts#L466

2. loading the kubeconfig to the library KubeConfig object

https://github.com/containers/podman-desktop/blob/49239338973f18887022b6ac00e27525f760d3a4/packages/main/src/plugin/kubernetes-client.ts#L474

3. init everything...

https://github.com/containers/podman-desktop/blob/49239338973f18887022b6ac00e27525f760d3a4/packages/main/src/plugin/kubernetes-client.ts#L488-L490

## Probable problem

In the initialisation of podman-desktop we have a strict await on the kubernetes initialization

https://github.com/containers/podman-desktop/blob/9e77a7f6d3be727f25781aafcf069e4aea18e106/packages/main/src/plugin/index.ts#L493

which could be blocking if something is taking forever.

## Narrowing the problem

Maybe there is something in the kubeconfig that makes podman-desktop or the kubernetes client freeze. Could you try to remove all the configurations (an empty config)

```yaml
apiVersion: v1
clusters: []
```

If this is working, do the following

- stop podman
- add a cluster to the config
- start podman
- assert not freezing

## Minimal reproduction

If you have node 20 installed, you may try the following

- assert podman freeze
- install the [@kubernetes/client-node](https://www.npmjs.com/package/@kubernetes/client-node)

execute the following

```js
const kube = require("@kubernetes/client-node")
const kubeConfig = new kube.KubeConfig()
kubeConfig.loadFromDefault()
console.log(kubeConfig.contexts.length)
```

**Comment by polzka90** [comment]
I got this problem, I have 4 clusters in my ./kube/config, the problem was related to my azure session that was expired, when I entered in my OpenLens it advises me about this, when I refresh my session the podman desktop start working again

**Comment by feloy** [comment]
Thanks for this report @polzka90 this is very valuable. I'm opening the issue https://github.com/podman-desktop/podman-desktop/issues/9879 to track the problem

**Comment by feloy** [comment]
@polzka90 I'm trying to replicate your issue with an Azure cluster.
To be sure I have the same config as you, in your ~/.kube/config file, for the user concerned by the failing session, is the user defined with this form:

```
- name: clusterUser_clusterName
  user:
    client-certificate-data: <masked>
    client-key-data:  <masked>
    token: <masked>
```

or with something like:

```
- name: clusterUser_clusterName
  user:
    exec:
      [...]
```

or something else?

(please remove any certificate/key/token/... value if you want to share some content of your file)

**Comment by polzka90** [comment]
Sure, here is my config masked 
`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: masked
    server: masked
  name: masked
- cluster:
    certificate-authority-data: masked
    server: masked
  name: masked
- cluster:
    certificate-authority-data: masked
    server: masked
  name: masked
- cluster:
    certificate-authority-data: masked
    server: masked
  name: masked
- cluster:
    certificate-authority-data: masked
    server: masked
  name: kind-kind-cluster
contexts:
- context:
    cluster: masked
    user: masked
  name: masked
- context:
    cluster: masked
    user: masked
  name: masked
- context:
    cluster: masked
    user: masked
  name: masked
- context:
    cluster: masked
    user: masked
  name: masked
- context:
    cluster: kind-kind-cluster
    user: kind-kind-cluster
  name: kind-kind-cluster
current-context: kind-kind-cluster
kind: Config
preferences: {}
users:
- name: masked
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - devicecode
      - "--server-id"
      - masked
      - "--client-id"
      - masked
      - "--tenant-id"
      - masked
      - "--environment"
      - AzurePublicCloud
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: masked
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - devicecode
      - "--server-id"
      - masked
      - "--client-id"
      - masked
      - "--tenant-id"
      - masked
      - "--environment"
      - AzurePublicCloud
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: masked
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - devicecode
      - "--server-id"
      - masked
      - "--client-id"
      - masked
      - "--tenant-id"
      - masked
      - "--environment"
      - AzurePublicCloud
      command: kubelogin
      env: null
      provideClusterInfo: false
- name: masked
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - devicecode
      - "--server-id"
      - masked
      - "--client-id"
      - masked
      - "--tenant-id"
      - masked
      - "--environment"
      - AzurePublicCloud
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: masked
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - devicecode
      - "--server-id"
      - masked
      - "--client-id"
      - masked
      - "--tenant-id"
      - masked
      - "--environment"
      - AzurePublicCloud
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: kind-kind-cluster
  user:
    client-certificate-data: masked
    client-key-data: masked
`

**Comment by feloy** [comment]
Thanks @polzka90 for this information. I can now reproduce the problem on my side. I'll add more information to the issue, we should be able to work on fixing the problem

**Comment by feloy** [comment]
Hi @polzka90 I'm working on making the user experience better when using Azure cluster. 
A workaround for the moment would be to change in your kubeconfig file the lines
```
- --login
- devicecode
```

with the lines
```
- --login 
- interactive
```

This should, when you start Podman Desktop and your token for your azure cluster is expired, automatically open one (or several) browser tabs to help you authentify with Microsoft, and once you are authentified, Podman Desktop should start correctly.

**Comment by polzka90** [comment]
Thank you for the workaround @feloy

**Comment by matzegebbe** [comment]
Thanks @feloy !

The UI currently returns the error message `Error: span kubelogin ENOENT`. Perhaps we could catch this error and display a more informative message.

![Image](https://github.com/user-attachments/assets/8d694cd2-f746-42aa-9c8c-20ae7ce00eb2)
