### ISSUE TITLE
Running Podman Desktop 1.12 ssh to remote server doesn't work

### ISSUE THREAD

**Issue by ghahvebaz** [containers/podman-desktop#8487]
### Bug description

I have podman version 4.9.3 running on a remote host and Podman Desktop (1.12) on a Mac. I can connect to the host via cli fine, run a container, etc. But in Podman Desktop the host shows as OFF. And the log shows following error: 
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed

I've tried troubleshooting but I'm running out of ideas. Is this a bug, or am I missing something?

SSH keys are the regular RSA kind and present in the ssh-agent

### Operating system

MacOS 14.5 

### Installation Method

Other

### Version

1.12.0

### Steps to reproduce

Follow regular installation guide for remote access here: https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md and other places.

### Relevant log output

```shell
Podman Desktop log: 
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ Engine does not have an API or a libpod API, returning empty array Podman
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
```

**Comment by cdrage** [comment]
> ### Bug description
> I have podman version 4.9.3 running on a remote host and Podman Desktop (1.12) on a Mac. I can connect to the host via cli fine, run a container, etc. But in Podman Desktop the host shows as OFF. And the log shows following error: main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> 
> I've tried troubleshooting but I'm running out of ideas. Is this a bug, or am I missing something?
> 
> SSH keys are the regular RSA kind and present in the ssh-agent
> 
> ### Operating system
> MacOS 14.5
> 
> ### Installation Method
> Other
> 
> ### Version
> 1.12.0
> 
> ### Steps to reproduce
> Follow regular installation guide for remote access here: https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md and other places.
> 
> ### Relevant log output
> ```shell
> Podman Desktop log: 
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ Engine does not have an API or a libpod API, returning empty array Podman
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> ```
> 
> ### Additional context
> _No response_

Apologizes, we are working on our remote documentation at the moment.

ed25519 keys are the only ones supported.

You can find our guide in this PR: https://github.com/containers/podman-desktop/pull/8457

**Comment by ghahvebaz** [comment]
> > ### Bug description
> > I have podman version 4.9.3 running on a remote host and Podman Desktop (1.12) on a Mac. I can connect to the host via cli fine, run a container, etc. But in Podman Desktop the host shows as OFF. And the log shows following error: main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > I've tried troubleshooting but I'm running out of ideas. Is this a bug, or am I missing something?
> > SSH keys are the regular RSA kind and present in the ssh-agent
> > ### Operating system
> > MacOS 14.5
> > ### Installation Method
> > Other
> > ### Version
> > 1.12.0
> > ### Steps to reproduce
> > Follow regular installation guide for remote access here: https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md and other places.
> > ### Relevant log output
> > ```shell
> > Podman Desktop log: 
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ Engine does not have an API or a libpod API, returning empty array Podman
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > main ↪️ [podman] SSH connection error: Error: All configured authentication methods failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Additional context
> > _No response_
> 
> Apologizes, we are working on our remote documentation at the moment.
> 
> ed25519 keys are the only ones supported.
> 
> You can find our guide in this PR: #8457

I confirm this is working, thank you for the quick reply!
