### ISSUE TITLE
Uncaught exception: bad file descriptor when clicking on `Extension: podman` in `Settings`

### ISSUE THREAD

**Issue by vyasgun** [containers/podman-desktop#8490]
### Bug description

When I go to `Settings -> Preferences -> Extension: Podman`, the following exception occurs and the application freezes:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EBADF: bad file descriptor, lstat '/dev/fd/12'
```

### Screenshot:

<img width="525" alt="image" src="https://github.com/user-attachments/assets/3c1886b0-dd7b-4abb-ba99-028c29e8db1b">

### Installation
I tried both brew and through the installer from https://podman-desktop.io/downloads and faced the same issue.

### Operating system

macOS Sonoma (14.6.1)

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

Go to `Settings -> Preferences -> Extension: Podman`. I get the exception when I click on `Extension: Podman`

**Comment by ScrewTSW** [comment]
Tested on:
* Fedora 40, flatpak, 1.12.0
* OSX13, M2, podman-desktop 1.12.0
* OSX14.5, M2, podman-desktop 1.11.1, 1.12.0
* Windows 10, Windows 11, podman-desktop 1.12.0

Could not reproduce the error

**Comment by vyasgun** [comment]
@ScrewTSW Can you reproduce it on an intel mac? Is there a way to accumulate more detailed logs for the issue?

**Comment by ScrewTSW** [comment]
@vyasgun Hello, sorry for the delay. Tried it also on an Intel-based mac from the 1.2.0-x64.dmg, OSX 14.5, unable to reproduce

**Comment by vyasgun** [comment]
thanks for checking @ScrewTSW ! This might be specific to my laptop then. I'll update this bug if I find anything new/helpful.

**Comment by ScrewTSW** [comment]
@vyasgun  Closing for now. If there's any update, feel free to re-open
