### ISSUE TITLE
Start/stop podman machine

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#85]
### Is your enhancement related to a problem? Please describe

The only reason I dropped to the terminal today was to start Podman machine.

### Describe the solution you'd like

I'd really like to be able to start/stop Podman machine from the Providers tab, and system tray (I see CRC listed there).

**Comment by benoitf** [comment]
sure it should be done as part of https://github.com/containers/desktop/issues/49

this one and https://github.com/containers/desktop/issues/80 are kind of dup of  https://github.com/containers/desktop/issues/49
