### ISSUE TITLE
`Run ${providerName}` button on dashboard provider card does not work for kubernetes connections

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#8514]
### Bug description

When provider card on dashboard is in 'Initialize and Start' mode for provider with kubernetes connections. The button 'Initialize and Start' works fine. If it is in `Start` mode there is 'Start ${providerName}` button that throws error `No container connection found for provider`. Because ProviderRegistry.startProvider checks only for container connections.

### Operating system

macOS M1 Sonoma 14

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

https://github.com/user-attachments/assets/a4671073-2f6a-4ee3-b456-be7bccc923ac

### Additional context

https://github.com/containers/podman-desktop/blob/39005c4d180c0e5f527821016f822743c936fa3f/packages/main/src/plugin/provider-registry.ts#L558

**Comment by odockal** [comment]
@lstocchi I have assigned you since you might be the one actually working on the fix, although in the other repo. If that does not sound right, update info at your will. :)

**Comment by lstocchi** [comment]
@odockal sure 👍 My only limitation is that i'm going PTO for 2 weeks starting 1st sept... i'll try to fix it this week
