### ISSUE TITLE
Make Release Note available from the release version displayed in the status bar

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#8521]
### Is your enhancement related to a problem? Please describe

As a user I would like to be able to view the latest release note of Podman Desktop

### Describe the solution you'd like

Display the release notes behind the release version button from the status bar

**Comment by afbjorklund** [comment]
Why not have the release notes under the version button in the bottom row, that currently doesn't do anything ?

![image](https://github.com/user-attachments/assets/507a8222-4adc-47d0-85f1-a4e86c5edc48)

**Comment by slemeur** [comment]
That's a good idea @afbjorklund ! I think it'd be a good addition of also displaying it on the dashboard
