### ISSUE TITLE
Poor contrast on Supercharge your apps with Red Hat banner graphic's text on Dashboard

### ISSUE THREAD

**Issue by mattreid** [containers/podman-desktop#8526]
### Bug description

I'm running Podman Desktop 1.12 on my Mac and the graphic at the bottom of the dashboard advertising the Red Hat extension pack uses white text on a light pink background, which is very hard to read. Could something be done next version to ensure there is sufficient contrast to easily read?

<img width="993" alt="Screenshot 2024-08-20 at 12 27 42 PM" src="https://github.com/user-attachments/assets/374ade6c-4848-4661-af9f-361cadf2bd67">

### Operating system

M2 Pro MacBook 14.6.1

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

Open Podman Desktop and look at the bottom of the Dashboard area to see the graphic

**Comment by benoitf** [comment]
it looks that it is picking up the wrong file (light image rather than dark image)

press <kbd>⌘</kbd>+<kbd>R</kbd> shortcut to reload the UI that should fix the issue as workaround

**Comment by mattreid** [comment]
Exactly right! I reloaded the UI with the shortcut and got the dark image. I had closed and reopened Podman Desktop itself before filing, but that still loaded the light image. Thanks for the tip in the meantime.
<img width="1283" alt="Screenshot 2024-08-21 at 8 36 50 AM" src="https://github.com/user-attachments/assets/ca72ea3f-ae29-4fbd-9e3f-bf57db7ffeca">
