### ISSUE TITLE
Tasks Manager Panel

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8546]
### Is your enhancement related to a problem? Please describe

Our current Tasks Manager has some UX challenges:
- Its icon and position in the status bar is making it hard to find
- There is no indication of the status of the tasks which might be running in background
- When the user has multiple tasks, the "small popover" is making it hard to navigate through those.

On another hand, with the addition of more extensions, there are more needs that are surfacing:
- Identifying the extension which is the source of the tasks
- eventually being able to sort the tasks by extension, timestamp

### Describe the solution you'd like

In this issue, we would like to explore revamping the Tasks Manager Popover and move it to its own dedicated panel.

In essence, tasks are automated actions/workflows that are happening in background, to streamline the development process.

**Tasks Examples:**
- Building an image
- Pulling a model from AI Lab
- Setting up a Podman Machine, Kind environment or OpenShift

These are actions that can be done in background and should not require the user to stay on a page, to be able to know their status. 

## Tasks Manager Panel 

- The tasks manager panel, should be using the full width of Podman Desktop window.
- There should be a title bar, that indicates, the number of tasks in progress and those completed
- The clear button could be moving in the title bar on the rig

Each of the task should be divided in 3 sections:
- Title and subtitle
- Progress/status
- Actions button (including "clear" and "view")

By clicking on "view", user should be able to get back to the screen where the action has been initiated. Example: Pulling of a model file should redirect to the model list.

**Comment by gastoner** [comment]
![image](https://github.com/user-attachments/assets/8d82e396-f25b-4134-a0e1-49f2d6f54b75)
@slemeur 
Something like this (All of those are inside one button)
+ make those colors with colors? red - yellow - blue

**Comment by gastoner** [comment]
> The tasks manager panel, should be using the full width of Podman Desktop window.
1. So should it be above the left navbar, or should it stop before the navbar and keep the buttons clickable? 
2. Should it also be using the full height of PD?

**Comment by deboer-tim** [comment]
There is some overlap with #7400, I would let it deal with status of running tasks, and focus here on showing errors in the status bar and the actual panel.

-1 to color on the status bar. _Maybe_ just when there's an error you haven't seen.  We can always revisit in the future, but I think it will be too visually distracting, especially if there was more than one color.

For 1 & 2 I think @slemeur 's intention is that the panel is full size, similar to Help or Troubleshooting. I would follow the same convention (and components) and kept the left navigation visible.

**Comment by axel7083** [comment]
> The tasks manager panel, should be using the full width of Podman Desktop window.

Why ? This is not a common pattern for notification system ? TaskManager is suppose to be quickly accessible

JetBrain

![image](https://github.com/user-attachments/assets/cd712bfa-34db-46fe-92e1-44fb38e7eb5f)

VSCode

![image](https://github.com/user-attachments/assets/a8e2c03b-bc07-44cc-b497-064734c5ea75)

> Show a visual indicator, when there is a task running in background

This is probably cover by https://github.com/containers/podman-desktop/issues/7400

I feel like we would probably need some mockups before trying to start implementing. cc @slemeur  @deboer-tim ? 

There seems to be a lot of requirements in this issue, and this probably need some design iteration

**Comment by deboer-tim** [comment]
Yes, I agree there needs to be a design and some agreement before we start implementing, and maybe can do in stages.

**Comment by slemeur** [comment]
https://github.com/containers/podman-desktop/issues/8628

**Comment by slemeur** [comment]
The description of this is about creating a "Panel", not a page which would take the entire screen like "Troubleshooting" or " About" pages. 

The initial intent was an horizontal panel, but it can be a vertical one.

**Comment by slemeur** [comment]
Let's work on the mockups #8628 before starting the implementation

**Comment by slemeur** [comment]
Closed as worked splitted into sub issues
