### ISSUE TITLE
Default action on Empty States screens should be clickable

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8567]
### Is your enhancement related to a problem? Please describe

When the user is using Podman Desktop for the first time, there will be no containers, no images, no pods.
We have "Empty States" screens that are providing a message to the user, but those are enticing the user to get into a terminal and start interacting with the tool from there.

<img width="1162" alt="Screenshot 2024-08-25 at 12 19 58" src="https://github.com/user-attachments/assets/abfedf2e-ccb7-439a-86fe-fabc2be393b9">

As a user, I'd like to be able to get familiarized with the tool, without having to leave it. 

### Describe the solution you'd like

We should be providing default actions for some of the critical screens:

- [x] #8568
- [x] #8569
- [x] #8570
- [x] #8571

**Comment by benoitf** [comment]
follow up enhancement is https://github.com/containers/podman-desktop/issues/9142
