### ISSUE TITLE
cpu/memory widget inside container details is overlapping

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#8574]
### Bug description

Overlap:
![image](https://github.com/user-attachments/assets/e5cb318b-2159-45db-adec-90059f636687)

The cpu / memory widget is cropped at the bottom for the terminal

![image](https://github.com/user-attachments/assets/d8db03df-7eea-463d-bde5-8f5c6830a631)

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

go to the terminal details

**Comment by gastoner** [comment]
@benoitf How should be the widgets moved? 
1. They should be inline with `Terminal`, `Kube`,... and just add some vertical space 
2. Make them smaller to fit to the space

**Comment by benoitf** [comment]
Cc @ekidneyrh

**Comment by ekidneyrh** [comment]
@benoitf do we know what this is meant to look like? was it a recent change adding the cpu/memory widgets to the container details? Just curious what was the initial intention.

**Comment by benoitf** [comment]
it's a regression, before we were seing the whole circle

**Comment by ekidneyrh** [comment]
> it's a regression, before we were seing the whole circle

is it meant to look like this? 
![image](https://github.com/user-attachments/assets/cf73fc24-8eec-44c8-84ce-6e42c204bf78)

**Comment by benoitf** [comment]
yes (or move it to another place but yes we should see the full circle)

**Comment by benoitf** [comment]
I think before there was not the X close key at the top right (so I'm not sure also it needs to be there) so there was more space to be displayed

**Comment by ekidneyrh** [comment]
@benoitf I see! We could also bring it over the the right like this:

![Screenshot from 2024-09-05 11-23-12](https://github.com/user-attachments/assets/05da0d40-87a7-4252-a676-66a145ee79e4)

**Comment by gastoner** [comment]
Let me know which of those mockups I should implement ^^

**Comment by deboer-tim** [comment]
We've had the close button in the design and UI for a long time and it's consistent with other pages. Removing it would save space but that's a bit bigger decision to remove from all details pages (or other pages too?).

Either way, I prefer the donuts on the right since it uses less vertical space, IMHO should be closer to the design in the previous comment: https://github.com/containers/podman-desktop/issues/8574#issuecomment-2331125156

**Comment by ekidneyrh** [comment]
@gastoner go with the mockup tim linked ^^^
