### ISSUE TITLE
Podman Update Overlay weirdly formatted and can't be removed

### ISSUE THREAD

**Issue by myfear** [containers/podman-desktop#8587]
### Bug description

I've tried updating Podman via PD by clicking the "update" button underneath and the overlay "You have installed with brew.." showed up. I've updated via brew and returning to Podman the overlay is there and 
a) can't be removed (x) is not working and 
b) has a weird layout

<img width="1042" alt="Screenshot 2024-08-26 at 15 20 10" src="https://github.com/user-attachments/assets/3298dba8-dc37-47a7-853b-f31f9c2c7e54">

### Operating system

macOS 14.6.1,  M1

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

**Comment by benoitf** [comment]
thanks for the report, will investigate

**Comment by benoitf** [comment]
dark mode:
![Image](https://github.com/user-attachments/assets/3af06d04-b521-4765-b9b7-56deaf574ca6)


light mode:
![Image](https://github.com/user-attachments/assets/69b39ea6-6cd8-4fd5-a6db-ff677b5097bb)


seems it was not converted to 'light mode'
