### ISSUE TITLE
Switch Kubernetes context from the status bar does not work anymore

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#8590]
### Bug description

Try to switch Kubernetes context but context remains the same

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Have 2 Kubernetes contexts (I had kind and sandbox)
2. Switch the Kubernetes context from the status bar

### Relevant log output

```shell
Does not append on 1.12

From the log:
```

### Additional context

![image](https://github.com/user-attachments/assets/b8774b4b-f828-473b-8a1f-0e8ebb178301)

**Comment by benoitf** [comment]
it might be related to the switch of the kubernetes-client library as all methods have changed

**Comment by feloy** [comment]
This is related to the check introduced in #8572

```
      } else if (indexes[0]) {
```

When you select the first context in the list, the value is `0`, and is not taken into consideration.

I'll create a PR to fix it

**Comment by benoitf** [comment]
thanks @feloy (both candidates for the regression were my PRs !)
