### ISSUE TITLE
[extension-api] CliToolState are not enough 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8599]
### Is your enhancement related to a problem? Please describe

When getting all the `CliToolInfo` we are getting an array of object, but extensions have no way of knowing if they are installed or not.

https://github.com/containers/podman-desktop/issues/8598 could be a solution, but there is the `CliToolState` which is always `registered`. This is not a useful information, as extension may need to know if it installed or not.

https://github.com/containers/podman-desktop/blob/013552134921d5326359cff048f59576bfa699b0/packages/extension-api/src/extension-api.d.ts#L4361

### Describe the solution you'd like

We should add a new value to the `CliToolState`. My proposal would be

```
export type CliToolState = 'registered' | 'installed'
```

Therefore, extensions will be able to determine if the cli tool is installed or not.

### Additional context

cc @benoitf

**Comment by lstocchi** [comment]
If desktop detects a binary which has not been installed by us the state should be installed as well? So, isn't the version prop enough?

**Comment by benoitf** [comment]
yes I'm not sure about why Podman Desktop should give that information

**Comment by axel7083** [comment]
So let's delete the state field ? it do not bring any information

**Comment by benoitf** [comment]
move it from info to CliTool (only the registrant will provide that (to not break backward compliance))
