### ISSUE TITLE
kind should uses the CLI installer instead of the statusbar 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8609]
### Is your enhancement related to a problem? Please describe

See title

### Describe the solution you'd like

Thanks to https://github.com/containers/podman-desktop/pull/8534 we no longer need the statusbar to indicate a tool is not installed

**Comment by axel7083** [comment]
This would also apply to minikube

**Comment by lstocchi** [comment]
Thanks for opening it, i forgot 👍

**Comment by odockal** [comment]
@amisskii please take a look, we will need to adjust e2e tests.
