### ISSUE TITLE
Javascript error thrown when closing PD when ran using yarn watch command

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8613]
### Bug description

It seems that a Javascript exception is getting thrown when the user closes the Podman Desktop app if it's running using `yarn watch` command on the main branch.

https://github.com/user-attachments/assets/f0f048d0-b3e1-47e9-a189-b1b2cc40ffe1

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Clone the PD repo.
2. Pull latest changes on main branch.
3. Run PD with `yarn watch` command
4. Ensure the "Exit on Close" option is enabled.
5. Close the app.
6. Notice that a Javascript exception is thrown

### Relevant log output

```shell
Uncaught Exception:
TypeError: Object has been destroyed
at WebContents.disposable (/Users/vladimirlazar/repos/podman-desktop/packages/main/dist/index.cjs:11962:12)
at Object.onceWrapper (node:events:634:26)
at WebContents.emit (node:events:519:28)
```

**Comment by axel7083** [comment]
I am facing the same issue on Fedora 40

**Comment by benoitf** [comment]
looks like it's coming from a recent fix in context-menu library
https://github.com/sindresorhus/electron-context-menu/commit/a4be72ccadd24a2c4cf920f752dbcc49893f163d

**Comment by axel7083** [comment]
Should we open an issue on their side ?

**Comment by benoitf** [comment]
For now, no as it may be related to something that we're not doing on our end and it's only surfacing now with the bugfix

**Comment by cbr7** [comment]
It seems that this error is the cause of the failing e2e tests on windows, unlike on macOS or linux, it seems that on windows the electron process hangs while the error popup is displayed which make it impossible to open a new instance of Podman Desktop app on windows while the error message is displayed.

**Comment by benoitf** [comment]
created https://github.com/sindresorhus/electron-context-menu/pull/183
