### ISSUE TITLE
Updating podman on CI is erroring currently

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8620]
### Bug description

It seems that when the CICD pipeline that runs the e2e smoke tests tries to update podman it currently fails with the following message:

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))`

https://github.com/containers/podman-desktop/actions/runs/10591944450/job/29350309899?pr=8619

### Operating system

linux

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
usually it's temporary, it's already gone

**Comment by odockal** [comment]
@benoitf uf, nice. thanks for heads up!

**Comment by odockal** [comment]
Again, there is some problem with the download server from time to time (in this [run](https://github.com/containers/podman-desktop/actions/runs/10595522535/job/29361477791)):
```
--2024-08-28 11:11:40--  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/amd64/conmon_2.1.2~0_amd64.deb
Resolving download.opensuse.org (download.opensuse.org)... 195.135.223.226, 2a07:de40:b250:131:10:151:131:30
Connecting to download.opensuse.org (download.opensuse.org)|195.135.223.226|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-08-28 11:11:41 ERROR 503: Service Unavailable.
```

**Comment by odockal** [comment]
Seems like the instability is away now. closing.
