### ISSUE TITLE
UX for Task Manager Panel

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8628]
Issue for UI/UX for the task Manager Panel
https://github.com/containers/podman-desktop/issues/8546

**Comment by ekidneyrh** [comment]
Starting to look into designs for this now. I was wondering - is this intended to be a new page that open when you click the tasks icon? 

Would it make sense to move it to the main nav?

Or is it something that would be on the dashboard? I can try both anyway but just wondering is that decision was made

**Comment by ekidneyrh** [comment]
Here's what the task manager might look like if it was it's own page. It's quite similar to the layout of the main pages for pods, images etc. 

For the task I have it broke up into: checkbox, name, progress, current logm actions. For current log I wasn't sure what to call it, maybe current job works better? It's meant to refer to the most recent feedback from the action like you would see in the logs to let the user know what is happening at the moment.

The progress bar can be the same as the one that would be in the status bar so we can reuse that element. I also included complete and failed status.

We can add the number of tasks in progress / complete / all next to the title in the tab like below:

![Image](https://github.com/user-attachments/assets/d0a880d2-8e92-4a80-b412-cfa7f81b8d35)

We could also have them as separate panels at the top of the page to make them stand out more:

![Image](https://github.com/user-attachments/assets/151c439a-4045-4b69-9732-9d56e86fd86b)

Note I'm using different icons than we are using atm but that should be ignored for the first iteration until all the icons are converted.

**Comment by Firewall** [comment]
🔥 Looks awesome!

I have a personal preference for the first one with the `In progress (1)` in the names of the tabs. 

Some other feedback:
1. Should we hide the tabs when there is `(0)` in there? 
2. Should the `Failed` tasks be earlier? `All, In progress, Failed, Complete`. I think they are more important than `completed` tasks. 
3. Should we have a column with a timestamp? `1 minute ago`,`3 days ago`? I think that can be useful to know when that task happened. 
4. What does the 👁 icon action do?

**Comment by slemeur** [comment]
Hello @ekidneyrh.

For the tasks manager, we would like it to be integrated and related to the status bar - as it is today. So not a new panel accessible from the main navigation bar. 

Later on, we may want to improve the task section in the status bar to something like this, but this is out of scope of this issue:
![Image](https://github.com/user-attachments/assets/33db20e0-ab46-4cab-9154-714852bce44c)

> ![Image](https://github.com/user-attachments/assets/d0a880d2-8e92-4a80-b412-cfa7f81b8d35)

This mockup is more convenient and better use the space available.

Could you please rework the mockup to show it integrated with the rest of the application?

**Comment by slemeur** [comment]
A couple of other minor feedback: 
A task might come with:
- A title
- A description/message:

We'd need to display the two.

Also, we would like to explore the behaviour when the description of the task is long (and will need multiple lines).

**Comment by ekidneyrh** [comment]
The eye icon represents the ‘view’ action. This was described in the epic ticket for the task manager:

By clicking on "view", the user should be able to get back to the screen where the action has been initiated. Example: Pulling of a model file should redirect to the model list.


Here’s another mockup following the feedback above. Things that were changed include:

- Added a time stamp
- Added a description
- Got rid of the red and green colours 

![Image](https://github.com/user-attachments/assets/8972644f-a68c-4a2a-9837-56559f0421e7)


_Integration_
I think the best way for this to be integrated would be to have it open as a page when the tasks icon is clicked, much like how the help icon opens the help page. 

_Long description / logs_
For this I think shortening the message and then having the full text display as a tooltip when hovered works best. Should this also be displayed on the screen where the action has been initiated? So this can also be seen when the view button is clicked.  
I was wondering whether I have the right thing included for the description. I just described what was happening. Should this also be displayed on the page that the user will be redirected to when they click view.

We can also allow multi lines on the rows, although I think there should be a max of how long the message can be. This will look like so: 

![Image](https://github.com/user-attachments/assets/dae005bd-de45-4375-b4ce-e4350ea38693)

**Comment by axel7083** [comment]
I really like that we focus on the TaskManager, we have a powerful notification system and we need as raised by https://github.com/containers/podman-desktop/issues/8546 to address some concern with it!

Following our discussion, here are some examples of TaskManager (notifcation center) in other tools, 

**Webstorm (JetBrain IDE)**

![Image](https://github.com/user-attachments/assets/63f40160-e492-45ad-b18d-e99e4105a2ae)

**VSCode**

![Image](https://github.com/user-attachments/assets/ee37ee38-e3a2-4a46-8f01-e1e52f58318f)

They seems to have some preference for a popup to ease access without forcing the user to redirect.

**Comment by slemeur** [comment]
Thanks for the mockups @ekidneyrh . I think overall this is heading into a great direction. 

About the changes, I think they work well:
> Added a time stamp
> Added a description
> Got rid of the red and green colours

I don't think we can easily have access to the "current log". We should probably get ride of that column, which would also give more space for the name of the task/notification and its description and simplify how we can handle the long description. The tooltip could be sufficient, as there is a way to quickly access back the screen where the notifications/tasks has been triggered.

Last feedback:
I don't think we should make this "Tasks screen" an entire page. It should still remains a popover, but which would use either the full width of the podman desktop window, or the full height. (one or the other). 

Could you give a look at these two points?

**Comment by ekidneyrh** [comment]
Sure! I got rid of the current log and made the description length longer. 

Also made it a pop-up that takes up half the screen. There's an option to minimize it and close it. 

![Image](https://github.com/user-attachments/assets/af774b7d-5011-4ae5-b8da-5e9621177113)

![Image](https://github.com/user-attachments/assets/b9e4f21e-5e0f-4029-a855-efac6bef4b2d)

Could make it a bit smaller also if you think it's too big! 

![Image](https://github.com/user-attachments/assets/f4d3d209-7f05-47db-b6c4-0254618c2c9a)


@slemeur @Firewall @axel7083

**Comment by ekidneyrh** [comment]
Discussed changes / edits to make from today's UX call:

- get rid of collapsible option
- keep 'pop over' effect coming from the tasks icon as is on current task manager
- add 'clean all' button
- detail error: below the description? figure out where to place
- add colours back in to icons for success and failed

**Comment by slemeur** [comment]
Thanks for putting the feedback in the issue @ekidneyrh. 
I'll give you an example error

**Comment by slemeur** [comment]
![Image](https://github.com/user-attachments/assets/7bf071be-1320-47d2-b7e7-119ff2fa859d)

**Comment by axel7083** [comment]
Another example of an error

![Image](https://github.com/user-attachments/assets/9677d24b-e112-46b7-be48-52cbd5604c9a)

**Comment by ekidneyrh** [comment]
Here's an updated mockup following last weeks feedback:

![Image](https://github.com/user-attachments/assets/02ee8ef1-a308-49ff-aca7-19e9c48dc52f)

**Comment by deboer-tim** [comment]
A few comments seeing this the first time:
- What happens when I click on / goto a task? Does the popup disappear? If it doesn't then there's a good chance I can't actually see the output because the popup would cover it; if it does then it's annoying to get back to the task manager. (I don't know what the discussion was but to me a full width popup is odd)
- For completed tasks, text like 'Completed' or 'Finished' would probably be better than '100%'.
- It would be good to try this or mockup on a smaller window as well, I'm guessing this will take half the height on a smaller 1024x650px window.

**Comment by ekidneyrh** [comment]
> * What happens when I click on / goto a task? Does the popup disappear? If it doesn't then there's a good chance I can't actually see the output because the popup would cover it; if it does then it's annoying to get back to the task manager. (I don't know what the discussion was but to me a full width popup is odd)

When you click on the view icon (the eye) it will bring you to the related page where the action was started from and ideally automatically close the menu.
> * For completed tasks, text like 'Completed' or 'Finished' would probably be better than '100%'.
I agree - I hadn;t considered it but it makes sense given I have 'failed' there too.

> * It would be good to try this or mockup on a smaller window as well, I'm guessing this will take half the height on a smaller 1024x650px window.

Yah here's it on a 1024x650px window
![Image](https://github.com/user-attachments/assets/4121123a-21fb-42f4-8073-577b77ca018b)


Width reduced on the title and description as the window shrinks.

It does take up a lot of vertical space. Not sure what to do about it - it was a requirement that is be the page width and the smaller mockup got negative feedback

**Comment by slemeur** [comment]
I think this is looking perfect! Moving this to implementation in: Implementation task in https://github.com/podman-desktop/podman-desktop/issues/9924

**Comment by benoitf** [comment]
In the actions part, it should also display a way to cancel a cancellable task

Still not decided on what needs to be done for the display
- if all icons are there and greyed out if not possible. For example: `View Action Icon` | `Cancel icon` | `Delete icon`
- if icons are only visible if possible
- if icons are hidden but keep the place (width) so an icon like cancel icon won't be replaced by the delete icon (could happen if when we're about to click, the task is finished and the icons are only displayed if action is possible)
