### ISSUE TITLE
Allow users to change their zoom level in the settings

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#8640]
### Is your feature request related to a problem? Please describe

It is not clear how I can change the font size of the entire UI. We are able to do it by using ctrl +/- however that is not clear. 

### Describe the solution you'd like

A suggestion would to add this as an option in the `Settings > Preferences > Appearance` area. We can maybe call it `zoom level`? 

A label could also be added that mentions "Shortcut: Ctrl +/-"

**Comment by slemeur** [comment]
Linking to https://github.com/containers/podman-desktop/issues/1660
