### ISSUE TITLE
Podman Installation failed  windows - podman-desktop-1.11.1-setup

### ISSUE THREAD

**Issue by tppalani** [containers/podman-desktop#8642]
### Bug description

I'm trying to install podman-desktop-1.11.1-setup below new version in my windows system at end the installation i can see below error.

```
Initialization failed. Please check the error below and try again
Error: Command execution failed with exit code 125
Command execution failed with exit code 125
Error: system connection "podman-machine-default" already exists. consider a different machine name or remove the connection with `podman system connection rm`
```

```
$ podman system connection ls
Name                         URI                                                          Identity                                                         Default     ReadWrite
podman-machine-default       ssh://user@127.0.0.1:58785/run/user/1000/podman/podman.sock  C:\Users\viswa\.local\share\containers\podman\machine\machine  false       true
podman-machine-default-root  ssh://root@127.0.0.1:58785/run/podman/podman.sock            C:\Users\viswa\.local\share\containers\podman\machine\machine  true        true
```

Can you please somebody please help me on this because we are going to rollout new version in our development team its affected more than 100 + user system.

Note i have uninstalled previous installation, then i started the new installation again, and also i have delete .local and .config folder in my local. 

![Screenshot 2024-08-29 001107](https://github.com/user-attachments/assets/d5bb40a6-3799-4b09-beef-18c652240338)

### Operating system

windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.11.1

### Steps to reproduce

Uninstalled and restarted system

**Comment by lstocchi** [comment]
Hi, 
i think that if you execute `podman machine ls` you don't have anything, right? 
The system connections are saved in `AppData/Roaming/containers/podman-connections.json`.
I think the best would be to remove the machine with `podman machine rm ... ` before deleting all folders manually.
You can also just remove the system connections manually. `system connection rm podman-machine-default` and `system connection rm podman-machine-default-root`

**Comment by odockal** [comment]
I would suggest to try `podman machine reset -f` first of all.
Possible leftovers could be also at `~/.ssh/` something like `podman-machine-default.pub` etc.
Also, `~/AppData/Roaming/containers` and similar.

**Comment by odockal** [comment]
I would suggest to try `podman machine reset -f` first of all.

**Comment by tppalani** [comment]
> I would suggest to try `podman machine reset -f` first of all. Possible leftovers could be also at `~/.ssh/` something like `podman-machine-default.pub` etc. Also, `~/AppData/Roaming/containers` and similar.

you solution is worked perfectly. we are good close the ticket

**Comment by cceelen** [comment]
In case you found this. Open a new shell and try to delete the old connections like this and try try again
```sh
podman system connection rm podman-machine-default
podman system connection rm podman-machine-default-root
```
