### ISSUE TITLE
publish pre-releases to another repository

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#8659]
### Is your enhancement related to a problem? Please describe

we received over the past few years complaints that we've too many releases on this repository and it's hard to filter or to subscribe when a new release is out as from GitHub there is no way to easily filter out all pre-releases and keep only releases

### Describe the solution you'd like

publish our releases made after each commit to a separate repository

### Additional context

A suggestion was to also add in the details of the pre-release to add what's new in this pre-release (link to all commits / PR being merged) since the previous one

**Comment by afbjorklund** [comment]
I think one issue was that you called them "releases" (or pre-releases), when they are only snapshots of each commit

* https://github.com/containers/podman-desktop/issues/6758

**Comment by benoitf** [comment]
hello @afbjorklund I'm not sure why you're saying it's a snapshot of a commit. CI is building them, signing and publishing them like any other 'promoted' releases 1.11, 1.12

**Comment by afbjorklund** [comment]
"snapshot" is a java term, other systems call them other things. Anyway, they are **not** "release" or alpha/beta/RC/etc?

https://maven.apache.org/glossary.html

The end goal is the same as in this issue, though. Put the releases in one place, and the other builds in another one.

Just that the word itself was confusing (to some).
