### ISSUE TITLE
If I try to deploy a container to kubernetes I get an error?

### ISSUE THREAD

**Issue by Luxvao** [containers/podman-desktop#866]
### Bug description

I clicked on deploy to kubernetes and then just clicked deploy and I got this error:
`Required parameter namespace was null or undefined when calling createNamespacedPod`
I'm running a minikube cluster and have installed kubectl.

### Operating system

Windows 11 Home 22H2 22621.819

### Version

0.9.1

### Steps to reproduce

Install kubectl, minikube and set it up for podman (`minikube start --driver=podman --container-runtime=o-cri` I'm running podman rootful if it matters), then try to deploy a container to kubernetes

### Additional context

It could be that I don't know how to use kubernetes with podman desktop and I forgot to set it up or something. Please tell me if thats the case.

**Comment by benoitf** [comment]
Hello @Luxvao could you try with a nightly release 
https://github.com/containers/podman-desktop/releases

**Comment by Luxvao** [comment]
Works perfectly in nightly! Thanks!
