### ISSUE TITLE
Minimize to tray on start / start minimized

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#868]
### Discussed in https://github.com/containers/podman-desktop/discussions/867

<div type='discussions-op-text'>

<sup>Originally posted by **patstha** November 20, 2022</sup>
On Microsoft Windows, it would be nice to have an option to minimize podman desktop on start so it doesn't open a new window every time I reboot the computer. 

![image](https://user-images.githubusercontent.com/56666486/202878522-dd4927e0-4df7-4459-a43b-b1c07964e68b.png)

Microsoft Teams calls it "open application in background"

![image](https://user-images.githubusercontent.com/56666486/202878621-07a422e7-81ae-4010-80e4-a9a498181638.png)

A user question and answer that explains this flow: https://techcommunity.microsoft.com/t5/microsoft-teams/allow-teams-application-start-minimized/m-p/1124951 
</div>

**Comment by benoitf** [comment]
it may requires an additional flag to read on startup

like `--minimize`

and it could be added in the macOS wrapper and in the Windows wrapper to always start minimized

**Comment by ghost** [comment]
This would also be a nice feature for linux, especially starting minimized.
