### ISSUE TITLE
Add support for Pods from Podman

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#87]
### Is your feature request related to a problem? Please describe

A key differentiator of Podman is support for Pods. This tool needs Pods support.

### Describe the solution you'd like

Support for Pods just like you support containers and imaes.

### Describe alternatives you've considered

None.

**Comment by benoitf** [comment]
It's already planned for k8s support
https://github.com/containers/desktop/issues/29

**Comment by rhatdan** [comment]
Podman Pods and Kubernetes Pods are somewhat different.  Podman play kube and podman generate kube support would also be useful.
