### ISSUE TITLE
study the implication of using eslint rules related to vitest

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8724]
### Is your enhancement related to a problem? Please describe

There is a package for vitest https://github.com/vitest-dev/eslint-plugin-vitest and it could be nice to use it depending on the implication

### Describe the solution you'd like

Check for interesting rules / change required

**Comment by axel7083** [comment]
After some testing here are the results after adding the `@vitest/eslint-plugin` package

```bash
✖ 238 problems (238 errors, 0 warnings)
  99 errors and 0 warnings potentially fixable with the `--fix` option
```

| Error | Count |
| --- | --- |
| `vitest/valid-expect` | 25 |
| `vitest/no-identical-title` | 20 |
| `vitest/valid-title` | 89 |
| `vitest/no-import-node-test` | 10 |
| `vitest/expect-expect` | 94 |

The most important is `vitest/no-import-node-test`, as it shows we are using `node:test` as import, which is incompatible with vitest.

**Comment by axel7083** [comment]
The problem for the `vitest/expect-expect` is that some tests do not have an expect in them.

Example 

https://github.com/containers/podman-desktop/blob/7007c7314cd3cc82f9e1a3afac87cbb4ebc6f07d/packages/main/src/plugin/container-registry.spec.ts#L1586-L1588

We are probably testing that no error are raised here. So this rule could probably be disabled.

**Comment by benoitf** [comment]
I think we should not ignore it and use `await expect(() => verifyBuildImage({}));` pattern anyway

**Comment by axel7083** [comment]
Closing in favour of Epic https://github.com/containers/podman-desktop/issues/9067
