### ISSUE TITLE
playwright config file should be moved inside the playwright project

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8726]
### Is your enhancement related to a problem? Please describe

Currently the playwright config file is located in the root folder, outside the `test/playwright` project, ideally the config should be in the project folder, as such it needs to be moved.

However the config also needs to be located in the same place as where the test run script is executed, which currently is from `package.json` file in the root folder, migrating some of these scripts into the `test/playwright` `package.json` will most likely be required and potentially other adjustments in order to get the application and the tests running correctly.

### Describe the solution you'd like

It requires investigation to understand what scripts and what other adjustments  would need to be made in order to facilitate moving the config file from root folder into the project folder and having everything work correctly.

**Comment by cbr7** [comment]
@odockal I've looked into this and I'm afraid there is no straight forward way of doing this, becayse if we switch the test execution scripts to `package.json` inside `tests/playwright` as would be required in order to move the playwright config into `tests/playwright` it would mean the electron application would not open anymore since it would be looking into the wrong folder for it.

We would have to manually set `PODMAN_DESKTOP_ARGS` environment variable to make this work, just like we are doing in the extension repositories, but this will add a manual test where previously there was none.

**Comment by odockal** [comment]
@cbr7 True. Let keep it as it is now. Thanks for investigating.

**Comment by benoitf** [comment]
why it has been closed ?

it should be done, we need to avoid to add new lines in the root package.json for e2e tests

I saw it one new more today https://github.com/podman-desktop/podman-desktop/pull/10293
