### ISSUE TITLE
website(sidebar): revamp

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8729]
### Is your enhancement related to a problem? Please describe

After discussing with @slemeur and when using the podman-desktop website for reading documentation, we often feel like the sidebar is a bit weird

![image](https://github.com/user-attachments/assets/e2783a0c-81f0-4b5c-9b95-254530e86936)

It combines several different style in one, have bold text for section, has a pale purple look, which feel odd with the text of the documentation (white/black).

### Describe the solution you'd like

While navigating on the vitest website, I find out I really like their sidebar, and feel easy on the eye.

https://github.com/user-attachments/assets/19610999-7843-4121-8606-9a731c2a22d2

Their website: https://vitest.dev/guide/why.html

_Sadly_ they are not using docusaurus so we can't just copy/past their configuration.

**Comment by benoitf** [comment]
not sure how it differs from https://github.com/containers/podman-desktop/issues/5338

**Comment by axel7083** [comment]
Closing as dup of https://github.com/containers/podman-desktop/issues/5338

> Thanks @benoitf I searched `website` in the issues and coudn't find it!
