### ISSUE TITLE
bug(UI): deleting an extension glitch the extensions icon

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8758]
### Bug description

https://github.com/user-attachments/assets/75c7b731-a625-42a6-acdc-df4ca51a880f

### Operating system

windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install AI Lab
2. stop AI Lab
3. delete AI Lab
4. assert icon issue

**Comment by odockal** [comment]
It might be that force-reload (CTRL+R) of the app fixes the issue (as a workaround solution to get things right).

**Comment by deboer-tim** [comment]
It should; this is almost certainly another Svelte reactivity issue like #8456.

**Comment by feloy** [comment]
fixed by #8903
