### ISSUE TITLE
Using the concurrency option in github workflows

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8811]
### Is your enhancement related to a problem? Please describe

As per the documentation _By default, GitHub Actions allows multiple jobs within the same workflow, multiple workflow runs within the same repository, and multiple workflow runs across a repository owner's account to run concurrently. This means that multiple workflow runs, jobs, or steps can run at the same time._[^1]

This mean, if I commit first, then re-commit, the check for the first commit are running before the new one.

[^1]: https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#overview

### Describe the solution you'd like

I would expect the workflows running would be cancel when my new commit appear.

We could add something like the following to workflows running in the PR check, to only run for the last commit and cancel any existing workflows when a new one is triggered. 

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

### Additional context

Why ? 🍃 🌎 🔥

**Comment by axel7083** [comment]
`github.base_ref`: The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.

`github.ref`: The fully-formed ref of the branch or tag that triggered the workflow run. For workflows **triggered by push**, this is **the branch** or tag ref that was pushed. For workflows **triggered by pull_request**, this is the **pull request merge branch**.  For workflows **triggered by release**, this is **the release tag** created.

**Comment by benoitf** [comment]
nice enhancement 👍 

as another enhancement, I would like is to have dependabot using a single 'queue' (like only one PR at a time) but it does not seem it's something possible on concurrency settings
