### ISSUE TITLE
Kubernetes Welcome page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#8825]
### Is your enhancement related to a problem? Please describe

As part of revamping the Kubernetes menu items (#8754) it was suggested that instead of defaulting to the Nodes or Deployments page, we could have a Kubernetes welcome page as the default page.

### Describe the solution you'd like

When a user first discovered the Kubernetes extension we want to guide and show them all the features it is capable of. In the AI Lab extension we are using a Welcome/About page to do that. We can reuse that pattern. The content that would make sense of that page is:

As a new user with, no Kubernetes resources, we should explain the main concepts. 
* Explain that Podman Desktop can be set up to connect to a Kubernetes Cluster
* Explain that Podman Desktop can create a local Kubernetes cluster for you. Using Kind, Minikube etc 
* Links to docs & blogposts:
  * https://podman-desktop.io/docs/kubernetes 
  * https://developers.redhat.com/articles/2023/06/09/deploy-and-test-kubernetes-containers-using-podman-desktop# 
  * https://developers.redhat.com/articles/2023/11/06/working-kubernetes-podman-desktop 

As a user that has some Kubernetes resources, we want to show guides where they can dig deeper and learn about how Podman works together with Kubernetes & Pods

**Requirements:**
- Clicking on the `Kubernetes` item will bring you to this Welcome/About page
- As a new user, this should be the first page you see, afterwards we should remember the previous page (#9057)

Currently the AI Lab extension has a similar pattern that could work here: 
![image](https://github.com/user-attachments/assets/1190f64a-4a6b-4711-b58f-4cdd3ab07a6b)

**Comment by axel7083** [comment]
I have some doubt on this one, as I feel like user may just want to see the pods/nodes, and having this default page would make it one more click needed to access the desired page.

Some possibilities to empower the user: we could have a preference `default kubernetes page` with `Welcome` by default, and let the user choose which page would be by default.

**Comment by deboer-tim** [comment]
My intention was that this is the first page in the list and shown the first time you open Kubernetes, but afterward it should remember the last page you were on. I opened up #9057 to track that separately.

**Comment by slemeur** [comment]
@Firewall is working on the requirements for this. 
Moving this to an epic.

**Comment by cdrage** [comment]
> I have some doubt on this one, as I feel like user may just want to see the pods/nodes, and having this default page would make it one more click needed to access the desired page.
> 
> Some possibilities to empower the user: we could have a preference `default kubernetes page` with `Welcome` by default, and let the user choose which page would be by default.

I have some doubt too, as a Kubernetes power user I want to jump straight to a dashboard that shows what my cluster is doing rather than a welcome page.

Should remember where our last position was when clicking as @deboer-tim suggested with #9057 

My suggestion is that maybe the "Kubernetes" large text on the top left should go to this Welcome Page?

**Comment by axel7083** [comment]
> I have some doubt too, as a Kubernetes power user I want to jump straight to a dashboard that shows what my cluster is doing rather than a welcome page.

I also feel the same,

> Should remember where our last position was when clicking as @deboer-tim suggested with https://github.com/containers/podman-desktop/issues/9057

AI Lab is doing that, I think this can be a nice behaviour to also have on Kubernetes pages

**Comment by Firewall** [comment]
> I have some doubt too, as a Kubernetes power user I want to jump straight to a dashboard that shows what my cluster is doing rather than a welcome page.
> Should remember where our last position was when clicking as Tim

A page like that doesn't exist today, right? I like the idea though. This page is indeed more aimed for new users trying to learn about all the things you can do with the Kubernetes extension. The remembering of the last page should also happen, but in that other task you linked (#9057)

> My suggestion is that maybe the "Kubernetes" large text on the top left should go to this Welcome Page?
This is the pattern we have right now, in AI Labs, so I would keep that consistent, yep.

I'll update the initial ticket to reflect that. EDIT: ✅ please take a look
