### ISSUE TITLE
Icons on navbar / text not aligned

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#883]
### Is your enhancement related to a problem? Please describe

Align the icons / text :)

### Describe the solution you'd like

See screenshot below! The icons and text seem out of alignment to the rest of the navbar.

![Screenshot 2022-11-22 at 8 10 10 AM](https://user-images.githubusercontent.com/6422176/203325622-a0ee6454-a050-4765-b0f8-9e1a2baafde4.png)

**Comment by slemeur** [comment]
Strange we changed the icons with 0.9 and these are old ones.
See how it is now:
<img width="173" alt="Capture d’écran 2022-11-22 à 14 46 26" src="https://user-images.githubusercontent.com/1636769/203329935-4dba6530-b817-4164-b7e6-f3354827eee1.png">

**Comment by cdrage** [comment]
🤦 I haven't had enough coffee this morning... Realized after it was because I was running my `brew install` version of podman desktop.

**Comment by benoitf** [comment]
yes, in the past icons were not the same size so it was producing wrong alignment
