### ISSUE TITLE
better distinction between `upgrade` and `change version` in CLI Tools

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#8838]
### Is your enhancement related to a problem? Please describe

Given the current UI we can't know if a new version is available. This is a bit problematic IMO. 

![image](https://github.com/user-attachments/assets/cb5174cf-2806-4b84-a90e-7aa158867bcd)

On this picture for example, kubectl a new version is available, but compose I am already using the latest.

### Describe the solution you'd like

I would like to have a clear, "A new update is available" indicator, and a separate, non-intrusive option to change the current version.

**Comment by axel7083** [comment]
@dgolovin should we keep this open as an epic maybe ?

**Comment by dgolovin** [comment]
@axel7083 I need to update compose installer/updater to work correctly and that would be it. I don't think it is big enough for an epic.
