### ISSUE TITLE
Access to Release Notes for Podman Desktop from status bar

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8842]
### Epic domain

Podman Desktop is getting releases quite often and bringing new capabilities on a regular basis. Unfortunately at the moment, the users may not be aware of where they could find information on the new capabilities each version is providing.
By embedding the release notes within the product, we can get users more informed and engaged with our releases and new features

### Subtasks

- [x] https://github.com/containers/podman-desktop/issues/8521 
- [x] https://github.com/containers/podman-desktop/issues/7880

_No response_

**Comment by SoniaSandler** [comment]
All related issue are done
