### ISSUE TITLE
Tasks notification improvements

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8849]
### Epic domain

The goal of this epic is to improve the current notification system. 
Each time a tasks is getting started, there's no indication that it started, only a small "dot" is added to over the "bell" icon in the status bar. This does not drive a lot of attention, and in some cases, for certain tasks, it'd be preferable to raise more awareness to the end-user. 

We'd like to introduce the possibility for tasks to be firing a toast notification, as well as bringing more awareness as to tasks that are taking some time before being completed.

**Comment by deboer-tim** [comment]
Overlaps with #7401, we should merge and close one (I'm fine if we move to this one).

**Comment by benoitf** [comment]
Adding follow-up issues to apply cancellable to status bar element and to the new task manager panel
