### ISSUE TITLE
[AI Lab] Add the ability to choose which machine to run an AI service 

### ISSUE THREAD

**Issue by rafaeltuelho** [containers/podman-desktop#8852]
### Is your enhancement related to a problem? Please describe

When creating a service within AI Lab I would like to have the ability to pick and choose a specific podman-machine to run it. This way I can test the AI Service in different podman-machine setups (eg. with CPU or with GPUs, with more Mem, etc)

![image](https://github.com/user-attachments/assets/086fcb4e-3fca-4581-9298-26acbc4b9a5c)

It looks like it always uses the default podman-machine.

![image](https://github.com/user-attachments/assets/01da3257-c052-4902-af6c-a77e79fe220f)

### Describe the solution you'd like

have a field listing the available running podman-machines so I can pick one to run my service.

**Comment by axel7083** [comment]
Hi @rafaeltuelho thanks for reaching out.

The ai-lab project is on a separate repository. You can see that we implemented this feature recently https://github.com/containers/podman-desktop-extension-ai-lab/pull/1537, and it will be available in the next release 🚀 !

> You can try it today using the nightly image `ghcr.io/containers/podman-desktop-extension-ai-lab:nightly` but careful, as it is not a release, and might experience some bugs.
