### ISSUE TITLE
Kubernetes cluster not detected

### ISSUE THREAD

**Issue by Luxvao** [containers/podman-desktop#887]
### Bug description

I reinstalled minikube (I changed the driver from podman to hyperv) and since then the minikube cluster doesn't show up and can't be interacted with (in the GUI). Is that because it uses hyperv instead of podman?

### Operating system

Windows 11 Home 22H2 22621.819

### Version

0.9.1

### Steps to reproduce

Install a minikube cluster on hyperv with the container runtime set to containerd, then just try to deploy a container to kubernetes and it should say that the cluster wasn't found.

### Relevant log output

```shell
Error: No active cluster!
```

**Comment by benoitf** [comment]
Hello @Luxvao, did you restart Podman Desktop (file/exit) or right click on tray icon then exit)

There was no refresh of the cluster in 0.9.1. It has been fixed in recent nightlies.

So could you either restart Podman Desktop (or try with a nightly version of Podman Desktop) ?

**Comment by Luxvao** [comment]
I did restart podman deaktop. But currently I'm not home to try put the nightly build. If it helps I'm going to close the issue.

**Comment by benoitf** [comment]
let's keep it open and see what happens when you try out the new version

**Comment by Luxvao** [comment]
@benoitf It does not work in the nightly release.

**Comment by benoitf** [comment]
ok probably something with the kubeconfig file
https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L363

It looks like you don't have a current cluster being set

**Comment by benoitf** [comment]
https://github.com/kubernetes-client/javascript/issues/687

**Comment by Luxvao** [comment]
@benoitf I fixed it. I thought it was podman desktop, but it was most likely minikube. I restarted minikube and everything worked fine

**Comment by benoitf** [comment]
ok so let's close the issue 😉
