### ISSUE TITLE
Update website hero title and description

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#8873]
### Is your enhancement related to a problem? Please describe

<img width="993" alt="Screenshot 2024-09-13 at 08 21 28" src="https://github.com/user-attachments/assets/bcab3dd5-c97e-45da-9a38-1ff3f7e8c56a">

### Describe the solution you'd like

**Title:** 
Best Free & Open Source Tool for Containers & Kubernetes - Podman Desktop

**Description:**
Podman Desktop is the best free and open source tool to work with Containers and Kubernetes for developers. Get an intuitive and user-friendly interface to effortlessly build, manage, and deploy containers and Kubernetes — all from your desktop. Join the growing community of developers using Podman Desktop!

**Comment by deboer-tim** [comment]
This was delivered via https://github.com/containers/podman-desktop/pull/8874.
