### ISSUE TITLE
[0.9.1] podman installation on WSL2 on Windows 11 was not detected

### ISSUE THREAD

**Issue by aysabzevar** [containers/podman-desktop#888]
### Bug description

Podman-desktop v0.9.1 cannot detect podman installed on fedora 37 on WSL2.

![image](https://user-images.githubusercontent.com/11361528/203419661-64b6b5b3-1fee-4055-83f3-be1bcfee4a50.png)

I found a similar issue with Windows 10 [#issue 857](https://github.com/containers/podman-desktop/issues/857). However, I am using the recent versions of Windows (11), WSL (2) and fedora (37). Here are the differences:

```
C:\Users\aliy>ver

Microsoft Windows [Version 10.0.22621.819]
```
```
C:\Users\aliy>wsl --status
Default Distribution: fedora
Default Version: 2

Windows Subsystem for Linux was last updated on 3/25/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```
```
C:\Users\aliy>wsl --list --verbose
  NAME        STATE           VERSION
* fedora      Running         2
```
```
[ali@fedora go]$ podman --version
podman version 4.3.1
```

### Operating system

Windows 11

### Version

0.9.1

### Steps to reproduce

Download and execute podman-desktop-0.9.1.exe while having fedora 37 running Windows 11 using WSL2

**Comment by benoitf** [comment]
Hello, so if I understand well:
- you don't have at all podman CLI in your local environment
- you have a custom WSL fedora machine

And you expect to have Podman Desktop finding podman inside that WSL custom machine that provides podman binary in it ?

My question is: how can we connect to that WSL instance providing podman ? is that the podman socket from your fedora WSL is exposed externally to your main Windows ?

**Comment by aysabzevar** [comment]
@benoitf  I already have WSL2 installed on my system, with the latest version of Podman on it and I use this environment as my main development environment. How come instead of installing Podman.exe on Windows that needs to install wsl (if it's not installed already), we detect the WSL and see if we already have podman installed on it.

We already have the same behavior within vscode. I have vscode installed on my Windows machine. But my compiler, etc. are on the wsl running on this Windows machine. Using WSL extension on vscode I easily achieve this. Hence, I am able to compile, test and run my Linux application while I am developing it on a Windows machine.

Please look at screenshots below:

![image](https://user-images.githubusercontent.com/11361528/203523654-a0ccff0f-ddb8-412b-84b6-9d158e1d0062.png)

![image](https://user-images.githubusercontent.com/11361528/203523774-e3216245-86f9-4534-b024-7a172afc165c.png)

I don't know. Maybe it's a feature I am requesting, instead of reporting a bug.

**Comment by benoitf** [comment]
@aysabzevar I would say it's more an enhancement and let me explain something.

podman runs on Linux.
so when we install 'podman' binary on Windows or macOS, it's the 'podman-remote' binary that we install.
This binary connects to a remote socket.

so, it's the 'podman machine' command that starts the underluing WSL subsystem but it also does an important thing. It mounts locally a socket on the host that redirects to the socket inside the WSL (through ssh)

It's this part that is missing in your current setup (host<--> remote socket)

For Visual Studio, in fact, you're connected inside the WSL container, so you're using the local podman binary running inside the VM.

It requires then this extra step: 'provides a way to connect to your WSL instance', either by adding a ssh tunnel or adding a file on a shared volume.

**Comment by tapaniantonrundgren** [comment]
I have the same kind of situation. Running Fedora 37 (including podman) on WSL2. But, I'm running even the VSCode inside that Fedora distro. I have tried to test podman-desktop, but it wants to create a new podman machine, which i don't want or need. Is there any way to get the podman-desktop, that is running locally in Fedora, to recognize the installed podman, or am I missing something. Would be nice to be able to use podman-desktop in Fedora, but in my case just a nice to have feature

**Comment by odockal** [comment]
@benoitf @tapaniantonrundgren @iamaliyousefi Hey, we are going through older issues at the moment, it seems to me as not a bug, but rather enhancement. Or do we consider shared information enough to close the issue? wdyt?

**Comment by aysabzevar** [comment]
@odockal It was most of a feature request that podman-desktop (running on Windows) detects the podman installed on my WSL2 and uses it to run containers, instead of installing yet another WSL to run the docker.

**Comment by benoitf** [comment]
it's something that upstream podman https://github.com/containers/podman should handle, Podman Desktop does not manage the machine directly
