### ISSUE TITLE
Provide ability to easily get a shell in a machine

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#889]
### Is your enhancement related to a problem? Please describe

It happens sometimes that I need to check the status of my podman-machine and instruct some commands into it.

### Describe the solution you'd like

I'd like the ability to get a shell into the podman-machine so I can more easily interact with it and eventually configure/fix it.

**Comment by mairin** [comment]
This uses the older app nav but there is a mockup to show how this could work (not unlike how we do for containers):
![Details Podman (1)](https://github.com/containers/podman-desktop/assets/799683/1c29609d-6a15-4bbc-9bce-065393b3c637)

**Comment by benoitf** [comment]
@mairin I am not sure how we connect to the VM from this mockup ?
Is it the console tab ?

**Comment by mairin** [comment]
@benoitf yep, that's right! And you would get to this screen by clicking on the machine name or on this button (I think @lstocchi has a WIP PR with this function in it to at least see the cpu/mem/etc details):
![Screenshot from 2023-05-31 13-10-38](https://github.com/containers/podman-desktop/assets/799683/6c4407e5-0beb-427b-adc9-010079914029)

**Comment by mairin** [comment]
(But maybe that's too may steps, we could add a terminal icon to the action bar in the machine's card  as an alternative and it could take you straight to the console tab?)

**Comment by benoitf** [comment]
Action could be in the kebab menu as well if it's a 'more advanced feature'

**Comment by afbjorklund** [comment]
For the Lima driver this is done by `lima`, after setting $LIMA_INSTANCE:

`LIMA_INSTANCE=podman lima`

That is, get the name of the lima instance from the preferences and set it.

```ts
  const engineType = configuration.getConfiguration('lima').get('type') || 'podman';
  const instanceName = configuration.getConfiguration('lima').get('name') || engineType;
```

**Comment by rtritto** [comment]
With WSL can be implemented by this way:
```js
const { exec } = require('node:child_process')
exec('wt wsl -d podman-machine-default --cd ~')  // podman-machine-default is the default name of the WSL distro
```

**Comment by gastoner** [comment]
Here can be found current progress: 
https://github.com/gastoner/podman-desktop/commit/1edae4fb5204fe68d8590df8f0722cbb3ea52016
I won't open a draft PR since it would add unnecessary stress to CI workers.

There are still some errors that I'm trying to solve e.g. `shellInProvider` in `provider-registry.ts`
