### ISSUE TITLE
Decrease size of Kubernetes navbar / too much whitespace

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8921]
### Is your enhancement related to a problem? Please describe

With the new navbar it now makes viewing information more difficult / compact due to the large size and whitespace with it.

![Screenshot 2024-09-17 at 9 37 31 AM](https://github.com/user-attachments/assets/b97dac51-47f5-4b04-bcbf-2b8b12a4bfcf)

### Describe the solution you'd like

We should decrease the size majorly in order to limit whitespace / the large amount of space that's taking up the navbar.

**Comment by benoitf** [comment]
AFAIK it's https://github.com/containers/podman-desktop/issues/8771 ?

**Comment by cdrage** [comment]
Woops! Closing. Thanks
