### ISSUE TITLE
UX: Move the provider elements to the Statusbar

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#8923]
In order to have more space on the dashboard we want to move some of the information that takes a lot of space to the statusbar. In this step we want to put the current providers (aka resources) (podman, kubectl, kind, developer sandbox and compose) to be in the statusbar instead of the dashboard. 

More info in the [Epic](https://github.com/containers/podman-desktop/issues/8922)

**Requirements:** 
- We create a pattern that can be re-used for every provider.
  - For each provider we should have indicator for status. Possible options for status are:
      - 🟢 Healthy (All good)
      - 🔴 Unhealthy (some sort of error)
      - 🆙  Update available (There is an update for this provider available)
      - ⚠  Not setup (the onboarding for the provider is not completed, something still needs to be set up)
      - ⏹ Stopped (this provider is currently stopped)
  - Clicking (or right clicking maybe?) the icon should take the user to the resources/provider page where they can configure them
  - Depending on the plugin, clicking on the icon should also have an effect. eg. Clicking on the Kubernetes context icon lets the user switch to another kubernetes context.
- Current list of providers that should be in the StatusBar: (Podman machine, Openshift local, Kubectl, kind, developer sandbox, compose)
- idea: Make the statusbar slightly taller so that the icons are a bit bigger and thus are more clear to understand.
Masha already an exploration on that I think ![Image](https://github.com/user-attachments/assets/83b18fb0-92dd-44cb-9736-fcf1148d0384)

- idea: Currently there is [another task to clean up the right side of the statusbar](https://github.com/containers/podman-desktop/issues/9077), but it is possible that we include those changes here

**Comment by ekidneyrh** [comment]
@Firewall I just started to look at this. There was a few things I was wondering.

The list you have above for providers: podman, kubectl, kind, developer sandbox and compose - is this the full list? 

Is the order of things that would be displayed on the left side of the bar be: provider, context, extension, cluster?  would all of these have status's or just the provider? I know atm some of the other items have errors. 

I agree with making it taller and I also think we could potentially make the bar in general be a bit bigger to allow for bigger icons so they are more noticeable.

**Comment by Firewall** [comment]
> The list you have above for providers: podman, kubectl, kind, developer sandbox and compose - is this the full list?

I think there are some more that can be provided by extensions, like MiniKube and Lima. That's why I will emphazise that we need a pattern as there might be more in the future that want to appear there. 

> Is the order of things that would be displayed on the left side of the bar be: provider, context, extension, cluster? would all of these have status's or just the provider? I know atm some of the other items have errors.

The order makes sense to me, yes

Providers and extensions can have a status yes. Think AI lab for example that could show that one of the recipies that is running. 

The cluster one is more a selection where you select the cluster that you connect too. I don't think we show a status on that one at the moment but I also wouldn't be surprised if that gets added at some point.

**Comment by Firewall** [comment]
After discussing it a bit more with a couple of you. I think we should also consider removing/hiding certain other things from that statusbar.
1. The RedHat Authentication extension shows an icon. Maybe we can just move this to the `Accounts` menu in the bottom left? It is already there but maybe we need it to show errors over there. That way we can teach users, everything related to accounts and authentication is in the bottom left of the main navigation.  
2. Docker Compatibilty now has a dedicated space in the configuration settings. I don't think it is needed always show in the statusbar. Maybe we should move this to a task in the task manager instead? Maybe it only lives in the settings?
3. The Minikube extension adds an indicator to the statusbar when it is not correctly set up. This again feels like a configuration option that feels out of place on the statusbar

**Comment by benoitf** [comment]
4. AI Lab is also taking too much place to display a port number ![Image](https://github.com/user-attachments/assets/c2738b01-cee5-44b7-885b-7c6f81887ce8)

**Comment by Firewall** [comment]
Can we show the port number somewhere on the AI lab page instead? I see a port number on the `Running` page of AI lab, but its a different port.

**Comment by ekidneyrh** [comment]
Following the notes above I have a first draft of the status bar.

One of the main changes is the height. I think it should be increased to accommodate padding of 8px on the top and bottom.

The test is increased to 12px (text-medium) to make it more readable. 

Another change is the order of the items. I have it laid out as: provider, extension, cluster, context. This is keeping items that are of similar format together (provider and extension).

The layout of each item is shown below. 

For each provider I can get the relevant icons to be used and can attach here when I have them. 

[status bar.pdf](https://github.com/user-attachments/files/17493389/status.bar.pdf)
![Image](https://github.com/user-attachments/assets/9402524d-a2c0-4224-bb9d-49cdfb411e85)

Let me know what you think :)

**Comment by Firewall** [comment]
Looks amazing! 

Only one small change, after talking to Tim I realised there is no `Paused` state only a `Stopped` state. Also, there is also 2 other states that I think we can accomadate pretty quickly. 

`Starting` -> Maybe flash the green circle, whilst it is starting?
`Stopping` -> Flash a grey circle?

**Comment by benoitf** [comment]
> Starting -> Maybe flash the green circle, whilst it is starting?
> Stopping -> Flash a grey circle?

I would avoid flashing, especially if I have 4 providers starting. In the current UI most of the 'intermediate state" are with animation/spinners, no flash

**Comment by benoitf** [comment]
about the dropdown, either it will go down but using native rendering or with a custom UI but then it can only stay within the border of the Window so it can't be down at that moment.

**Comment by benoitf** [comment]
here you're using small text for provider name but the name can be 'Red Hat OpenShift Local'
if I have 2 providers like that, my status bar is full.
in that case ? icon only, ellipsis ?

**Comment by benoitf** [comment]
I forget to mention but dropdown like for switching a kubernetes context are using the quickpick to be displayed, it's not attached to the status bar. Why ? because they don't contribute a UI but a command. (3rd party contribution)

so displaying some data from the provider is possible using dropdown but not in the case of switching kubernetes context

**Comment by benoitf** [comment]
A Provider can have multiple connections

For example I can have podman provider with 2 machines

how to represent then one provider with one status ? as I can have one running and one stopped or one starting and one stopping on Windows ?

in the tray icon there is
![Image](https://github.com/user-attachments/assets/705f0a83-f485-48c1-bbc6-cfa7f7f0a466)

(one entry per machine, not per provider)

**Comment by Firewall** [comment]
>I would avoid flashing, especially if I have 4 providers starting. In the current UI most of the 'intermediate state" are with animation/spinners, no flash

Ah, sure, I don't have a preference. 

>about the dropdown, either it will go down but using native rendering or with a custom UI but then it can only stay within the border of the Window so it can't be down at that moment.

I think going up makes perfect sense.

>here you're using small text for provider name but the name can be 'Red Hat OpenShift Local'
if I have 2 providers like that, my status bar is full.
in that case ? icon only, ellipsis ?

We have a couple of options, either we make the name shorter or we truncate, and probably some more options

>A Provider can have multiple connections

On the dashboard we only show the status for 1 of them, I guess the recent one? Can we re-use that pattern?  Showing status fo each machine will get pretty messy I think

**Comment by ekidneyrh** [comment]
> I forget to mention but dropdown like for switching a kubernetes context are using the quickpick to be displayed, it's not attached to the status bar. Why ? because they don't contribute a UI but a command. (3rd party contribution)
> 
> so displaying some data from the provider is possible using dropdown but not in the case of switching kubernetes context

so would it be best to just display the current context and nothing more?

**Comment by ekidneyrh** [comment]
![Image](https://github.com/user-attachments/assets/b1d12d55-904f-48a4-b9c0-fd6ea13fa724)
[status bar.pdf](https://github.com/user-attachments/files/17523015/status.bar.pdf)

Took some of the feedback on board. For the stopping and starting states I think the same spinner would suffice as it would indicate that a state change is happening.

I got rid of the dropdown per @benoitf's comments above that it is not possible to switch the contexts here.

I also added in what the longer provider names would look like as well as two possible solutions to reduce the amount of text. 

I've contacted Red Hat brand for the proper icons to use for OpenShift and Developer Tools as there seems to be conflicting information online. 

WDYT?

**Comment by deboer-tim** [comment]
The following are just personal preferences:
- I don't love the 'icon - text - status icon'. Even with gaps between them I find it harder to find status as my eye goes to the icon first and then I have to intentionally look to the right instead of the one just to the left.
- I'm still unsure about color on the status bar. Especially red, it is an eye catcher and looks like something is wrong.
- Our default names for connections aren't great for putting the significant bits first - but maybe that's ok because most people only have one machine / one kind, or use the same one repeatedly.
- Given this, I actually find the middle option the easiest to see status, and nicely uses up the least space too.

**Comment by ekidneyrh** [comment]
> The following are just personal preferences:
> 
> * I don't love the 'icon - text - status icon'. Even with gaps between them I find it harder to find status as my eye goes to the icon first and then I have to intentionally look to the right instead of the one just to the left.

We could try status - icon - text? Here's what it would look like:

![Image](https://github.com/user-attachments/assets/6c8fe4f9-2d71-49e7-9e97-d3ae1f30dd3b)


> * I'm still unsure about color on the status bar. Especially red, it is an eye catcher and looks like something is wrong.

I though the point of the red is to indicate that there **_is_** something wrong? Is an unhealthy status on a provider critical enough to warrant the red? or is it more minor and maybe yellow or another type of icon is more suitable?

**Comment by deboer-tim** [comment]
> > The following are just personal preferences:
> > 
> > * I don't love the 'icon - text - status icon'. Even with gaps between them I find it harder to find status as my eye goes to the icon first and then I have to intentionally look to the right instead of the one just to the left.
> 
> We could try status - icon - text? Here's what it would look like:
> 
> ![Image](https://github.com/user-attachments/assets/6c8fe4f9-2d71-49e7-9e97-d3ae1f30dd3b)

That's better, but still find I look for the icon first and then less natural to look left. I personally still prefer the small icon+status, but willing to try anything or if others prefer this.

> > * I'm still unsure about color on the status bar. Especially red, it is an eye catcher and looks like something is wrong.
> 
> I though the point of the red is to indicate that there **_is_** something wrong? Is an unhealthy status on a provider critical enough to warrant the red? or is it more minor and maybe yellow or another type of icon is more suitable?

I thought that was the 'stopped' status, but if that's an error and stopped blends in that's probably ok then.

**Comment by ekidneyrh** [comment]
Going to go ahead and finalize the small icon + status option for this. 

![Image](https://github.com/user-attachments/assets/79ba144c-9156-47ed-9473-f8f28f053d8b)

Going to get the source files for the icons for Red Hat open shift as I don't believe we have those and I'll upload here.

**Comment by Firewall** [comment]
On that last one, I think we should have the order we discussed previously kept. `Podman/container providers -> Kubernetes context -> Extensions`. I think for the kubernetes context we kind of need the name label, its not very useful to have that in the statusbar otherwise? Or am I missing something?

Will we have a hover state? A tooltip that shows up? If yes, what does it look like?

What will happen when there is no space? Do we stop showing some icons? Do the collapse into a popup menu?

**Comment by benoitf** [comment]
hello, here are my very late comments

- using colors will be an issue. If someone change the color of the status bar to be green or red, it'll hide the circle of the status. Pattern was to use only 2 colors (foreground/background)
- green/red: I viewed several sessions about a11y and it seems using green/red is not so nice for people having color-blind issues
- too many colors is distracting me. (I want to get attention only if I need to pay attention) But here my eyes would be attracted by both green and red and the icons. But IMHO I should pay attention only because it's not in an 'expected/running state'

so I was wondering if the status could be reflected either by an overlay on top of the provider icon or by having the state using icons (play for running/pause if stopped/cross if error ) Spinner around pause if stopping, spinner around play icon if starting
Or overlay icon like an exclamation mark or something else only if it's not in a running state



About the spaces between all the providers, maybe a left/right separator : `| icon 1| icon 2|`

**Comment by slemeur** [comment]
> ![Image](https://github.com/user-attachments/assets/6c8fe4f9-2d71-49e7-9e97-d3ae1f30dd3b)

In general, we are trying to simplify the status bar and streamline the different ways we are leveraging it. By adding all the different providers in the status bar like the proposed solution, it's getting visually more complex. The interactions are not clear and a user will not be able to make a difference between, the information for providers and the kubernetes context switcher.
In order to save spaces, giving clarity to the end users, I'd strongly recommend to find a way to avoid displaying "all" the providers in the status bar, and make it scale properly, so there is only one part of the status bar used for the providers. As suggested by @benoitf, a separator might be helpful to help the user better identify the sections.

+1 on the following point:
> - too many colors is distracting me. (I want to get attention only if I need to pay attention) But here my eyes would be attracted by both green and red and the icons. But IMHO I should pay attention only because it's not in an 'expected/running state'

On this:
> - green/red: I viewed several sessions about a11y and it seems using green/red is not so nice for people having color-blind issues

> so I was wondering if the status could be reflected either by an overlay on top of the provider icon or by having the state using icons (play for running/pause if stopped/cross if error ) Spinner around pause if stopping, spinner around play icon if starting
Or overlay icon like an exclamation mark or something else only if it's not in a running state

It's probably important to work on the status icons. There could be a mix between color+shapes, similar to the status of the github issues, or a bit like this: 
![Image](https://github.com/user-attachments/assets/bb3e4bcd-0574-4bd8-b84a-4420a615af00)

I think the is one status that is missing: "inactive" -> when a provider is simply not running

Also details on the quick actions + the hover are important for this issue.

**Comment by ekidneyrh** [comment]
Here’s another mockup following the feedback above. Things that were changed include:

- Changed icons to white
- Different icons so each is readable in monotone. 
- Providers now include a drop-up menu with the option to pin providers from there. Maybe we can allow a max of two pins to avoid overcrowding? 
- If there is only one provider, still have the menu appear with the single provider there.
- Changed the order back to providers > kubernetes > extensions 

![Image](https://github.com/user-attachments/assets/d9ec2a87-0ff3-48d2-b450-e88e48db4142)

![Image](https://github.com/user-attachments/assets/9f3edb6a-3031-4f18-aa94-d384f85cbfad) 
_Tooltips_
For tooltips I think having the icon label displayed would be sufficient. Eg ‘running’, ‘stopping’, etc.

_Hover states_
This can be similar to the states we already have from dropdowns. I have a light and dark mode in the screenshot bc they are the same atm but can be changed in the future.  

![Image](https://github.com/user-attachments/assets/23d18a28-9fd1-496a-aba5-1ebc2fa90954)

cc: @Firewall @slemeur @benoitf @deboer-tim

**Comment by ekidneyrh** [comment]
Discussed changes / edits to make from today's UX call:

- Have an option to pin extensions also - how will this be done? given there will be more than one displayed.
- Have option to unpin everything - how will this be done?
- Have kubernetes providers as part of the providers list
- differentiate the providers  to the list button eg have them as separate 'buttons'

**Comment by ekidneyrh** [comment]
Here's an updated version following the feedback from last week:

![Image](https://github.com/user-attachments/assets/4c75a705-6dd4-4e94-b272-9127837c3a35)

**Comment by Firewall** [comment]
This looks awesome! Great job.

**Comment by Firewall** [comment]
Do we need a third option for the Kubernetes context in the dropdown? So `Providers, Kubernetes Context, Extensions`? 

I think also regarding which ones are Pinned by default, only the `Podman` one?

**Comment by ekidneyrh** [comment]
> Do we need a third option for the Kubernetes context in the dropdown? So `Providers, Kubernetes Context, Extensions`?

I think we talked about this on the UX call - I thought the providers covered the kubernetes contexts too? I have it in my notes to add kubernetes to the provider list but it can be implemented either way.

> I think also regarding which ones are Pinned by default, only the `Podman` one?

I think we can pin the first one that shows up in the list by default. In the resources page that shows Podman for me. 

If the user tries to pin more than two items we can display an error like so:

![Image](https://github.com/user-attachments/assets/ca5f8905-bd8b-46ae-af9f-8f2d49d4db57)

What do you think of the red for the error? We could go with white for that if we dont like it. 

also fixed the drop down so its aligned with the arrow button.

**Comment by Firewall** [comment]
>I think we talked about this on the UX call - I thought the providers covered the kubernetes contexts too? I have it in my notes to add kubernetes to the provider list but it can be implemented either way.

Yes, all the Kubernetes providers should also be added on that list, so it should include `Minikube`, `Kind` etc. 

The Kubernetes `context` is not the same though. This is the option that we have currently in the statusbar. This decides which context is used to connect to the Kubernetes API. It will change what you see on all of the `Kubernetes` pages. 

> If the user tries to pin more than two items we can display an error like so:

I personally don't see a benefit to adding a limit. I would not add it. If a user adds so many that it starts to bother them, that is 100% in their control.

**Comment by ekidneyrh** [comment]
ah ok makes sense.

So would something like this work then? 

![Image](https://github.com/user-attachments/assets/16269e85-c4ed-48a8-81e8-25a0372b0499)

**Comment by benoitf** [comment]
here some of my feedback about the UX:

- If I have a dropdown to list my providers, maybe I would expect to have the choice at the left of all the entries (so if I add/remove it won't move from where my cursor is because here if deselect Developer Sandbox and I want to enable it again, I will have to move to the left my cursor just after the click) 
- But I'm not sure if it should not be the icon and I would find an icon to say it's the list of providers rather than only the caret icon (because I won't really know for what it's being applied).

in short, maybe it's confusing to have a dropdown applying to many items if we don't see in the UI clearly that it's being applied to the whole group. (might think the dropdown applies to a single item)
To be consistent, making it with a right click would be more in the spirit of what is done to select/deselect menus from the main navbar
![Image](https://github.com/user-attachments/assets/a6f3740a-fb01-4b34-82e2-ceddac9acebc) but it might not be intuitive that right click on the status bar allow you to pin items...

- For the failed status, it makes me feel that it's also an icon to clear the entry (some UI are using that to delete an entry) so I might assume it will hide or remote the item from the bar while the icon is a state, not an action. I don't know if this one would be more accurate:
![Image](https://github.com/user-attachments/assets/668eab51-9f4d-4416-a666-3b7dcba2189f)

**Comment by slemeur** [comment]
How do we make this consistent with the experience and styling here: https://github.com/podman-desktop/podman-desktop/pull/9867 ?

**Comment by ekidneyrh** [comment]
> * If I have a dropdown to list my providers, maybe I would expect to have the choice at the left of all the entries (so if I add/remove it won't move from where my cursor is because here if deselect Developer Sandbox and I want to enable it again, I will have to move to the left my cursor just after the click)

Thats no problem, here's it moved to the left:

![Image](https://github.com/user-attachments/assets/41509fb7-5883-411a-bd0e-d7f107629825)

> * But I'm not sure if it should not be the icon and I would find an icon to say it's the list of providers rather than only the caret icon (because I won't really know for what it's being applied).
> 
> in short, maybe it's confusing to have a dropdown applying to many items if we don't see in the UI clearly that it's being applied to the whole group. (might think the dropdown applies to a single item) To be consistent, making it with a right click would be more in the spirit of what is done to select/deselect menus from the main navbar ![Image](https://github.com/user-attachments/assets/a6f3740a-fb01-4b34-82e2-ceddac9acebc) but it might not be intuitive that right click on the status bar allow you to pin items...
> 
I think for now we can try out the layout I have and then iterate on it in the future. I would be against the right click as we have three different drop downs that we want the user to access atm. 

I'm using the icon I am as it;s been used throughout the app with the drop down. I dont think its a major issue and can be changed if not working out once implemented. 

> * For the failed status, it makes me feel that it's also an icon to clear the entry (some UI are using that to delete an entry) so I might assume it will hide or remote the item from the bar while the icon is a state, not an action. I don't know if this one would be more accurate:
>   ![Image](https://github.com/user-attachments/assets/668eab51-9f4d-4416-a666-3b7dcba2189f)

that icon works good too - it's more clear!

**Comment by ekidneyrh** [comment]
> How do we make this consistent with the experience and styling here: [#9867](https://github.com/podman-desktop/podman-desktop/pull/9867) ?

Sure! It looks like the default drop down styling. We can go with that if it's the preferred! makes less work too 

![Image](https://github.com/user-attachments/assets/0dec2148-e83f-4b17-9f79-f42335a096b5)

**Comment by ekidneyrh** [comment]
@Firewall just wondering if there's anything else needed on this ticket?

**Comment by Firewall** [comment]
@ekidneyrh Not from my side! It looks great thank you
