### ISSUE TITLE
Stabilize podman machine onboarding e2e test case on Mac OS

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8947]
### Is your enhancement related to a problem? Please describe

We have `tests/playwright/src/specs/podman-machine-onboarding.spec.ts` failing on Mac OS.

### Describe the solution you'd like

Please take a look at particular CI runs and figure out the instability of the given test case on Mac OS.

**Comment by ScrewTSW** [comment]
Fixed by refactors from @cbr7
