### ISSUE TITLE
Provide pre-defined registries (like Dockerhub, Quay and Github registry) where users only need to provide the credentials

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#895]
We would like to make the experience of configuring a registry simpler and faster for the most popular ones:
- Dockerhub
- Quay
- GitHub

This would be possible with a pre-defined list of registry, where the user would only have to provide username/password

**Comment by benoitf** [comment]
These registries should be provided by an extension.

So, custom extension can provide other registries (and icon, etc)

**Comment by cdrage** [comment]
Duplicate of https://github.com/containers/podman-desktop/issues/317 ?

**Comment by benoitf** [comment]
one was for UI team, this one is to implement

**Comment by benoitf** [comment]
it's a "one missing step" of the implementation https://github.com/containers/podman-desktop/issues/446

**Comment by cdrage** [comment]
Going to split up https://github.com/containers/podman-desktop/issues/895 into two PR's, as I believe there's two things to implement:
1. A list of custom registry providers to add as part of the UI/UX. Implement the "finalized" UI/UX that @mizmo has developed on. The list should be a constant array within Podman Desktop that lists all major registries (dockerhub, quay, github, etc.)
2. Add the ability for a custom extension to add a custom registry / add it to the "registry" section of Podman Desktop for it to be enabled.

**Comment by cdrage** [comment]
Going to split up https://github.com/containers/podman-desktop/issues/895 into two PR's, as I believe there's two things to implement:

1. A list of custom registry providers to add as part of the UI/UX. Implement the "finalized" UI/UX that @mizmo has developed on. The list should be built-in within Podman Desktop that lists all major registries (dockerhub, quay, github, etc.)

2. Add the ability for a custom extension to add a custom registry / add it to the "registry" section of Podman Desktop for it to be enabled.

Unsure how to implement #2? List the registry URL and icon in the `package.json`? WDYT @benoitf ?

**Comment by cdrage** [comment]
Also for 1. I'll work with @mairin and implement the UI/UX first while I figure out where to read the information from correctly (for now, maybe a const array somewhere listing all the icons + registry URL's?)

**Comment by benoitf** [comment]
icon and registry URL needs to be provided through extension-api
A single extension could provide the default registries.

**Comment by mizmo** [comment]
> Going to split up #895 into two PR's, as I believe there's two things to implement:
> 
> 1. A list of custom registry providers to add as part of the UI/UX. Implement the "finalized" UI/UX that @mizmo has developed on. The list should be built-in within Podman Desktop that lists all major registries (dockerhub, quay, github, etc.)
> 2. Add the ability for a custom extension to add a custom registry / add it to the "registry" section of Podman Desktop for it to be enabled.
> 
> Unsure how to implement #2? List the registry URL and icon in the `package.json`? WDYT @benoitf ?

Hi! I think you wanted to link someone else.

**Comment by cdrage** [comment]
> > Going to split up #895 into two PR's, as I believe there's two things to implement:
> > 
> > 1. A list of custom registry providers to add as part of the UI/UX. Implement the "finalized" UI/UX that @mizmo has developed on. The list should be built-in within Podman Desktop that lists all major registries (dockerhub, quay, github, etc.)
> > 2. Add the ability for a custom extension to add a custom registry / add it to the "registry" section of Podman Desktop for it to be enabled.
> > 
> > Unsure how to implement #2? List the registry URL and icon in the `package.json`? WDYT @benoitf ?
> 
> Hi! I think you wanted to link someone else.

Indeed! My mistake, sorry about that!
