### ISSUE TITLE
After upgrading Podman Desktop from v1.11 to v1.12, I am unable to communicate with Podman Machine.

### ISSUE THREAD

**Issue by n2029-ndensan** [containers/podman-desktop#8967]
### Bug description

PS C:\Users\n2029> podman info
OS: windows/amd64
provider: wsl
version: 5.2.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:64874: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\n2029>

PS C:\Users\n2029> docker version
Client:
 Version:           27.2.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        9e34c9b
 Built:             Fri Sep  6 12:09:12 2024
 OS/Arch:           windows/amd64
 Context:           default
error during connect: Get "http://%2F%2F.%2Fpipe%2Fpodman-machine-default/v1.47/version": open //./pipe/podman-machine-default: The system cannot find the file specified.
PS C:\Users\n2029>

### Operating system

Windows11

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

**Comment by jeffmaury** [comment]
Can you check if your Podman machine is running:

`podman machine ls`

If it is not running can you give the output of `podman machine start` .

**Comment by n2029-ndensan** [comment]
PS C:\Users\n2029> podman machine ls
NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  wsl         3 months ago  Currently running  4           2GiB        100GiB

**Comment by jeffmaury** [comment]
Looks like your Podman machine is stuck. Can you restart it ?

**Comment by n2029-ndensan** [comment]
PS C:\Users\n2029> podman machine stop
Machine "podman-machine-default" stopped successfully
PS C:\Users\n2029> podman machine start
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine is not listening on ssh port
PS C:\Users\n2029> podman info
OS: windows/amd64
provider: wsl
version: 5.2.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:64874: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\n2029>

**Comment by n2029-ndensan** [comment]
PS C:\Users\n2029> podman machine stop
Machine "podman-machine-default" stopped successfully
PS C:\Users\n2029> podman machine rm
The following files will be deleted:


C:\Users\n2029\.config\containers\podman\machine\wsl\podman-machine-default.json
C:\Users\n2029\AppData\Local\Temp\podman\podman-machine-default.sock
C:\Users\n2029\AppData\Local\Temp\podman\podman-machine-default-gvproxy.sock
C:\Users\n2029\AppData\Local\Temp\podman\podman-machine-default-api.sock
C:\Users\n2029\AppData\Local\Temp\podman\podman-machine-default.log
Are you sure you want to continue? [y/N] y
登録解除。
この操作を正しく終了しました。
PS C:\Users\n2029> podman machine init
Downloading VM image: v20240919061316-5.2-rootfs-amd64.tar.zst: done
Extracting compressed file: podman-machine-default-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
インポート中です。この処理には数分かかることがあります。
この操作を正しく終了しました。
Configuring system...
Machine init complete
To start your machine run:

        podman machine start

PS C:\Users\n2029> podman info
OS: windows/amd64
provider: wsl
version: 5.2.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:50572: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\n2029>

**Comment by n2029-ndensan** [comment]
It finally moved.
