### ISSUE TITLE
Improve detection of system theme change

### ISSUE THREAD

**Issue by gastoner** [containers/podman-desktop#8978]
### Bug description

In ExtensionBanner https://github.com/containers/podman-desktop/pull/8744 and in MonacoEditor https://github.com/containers/podman-desktop/pull/8759 the change of system theme takes a long time (on Mac probably won't be system theme detection even triggered). This needs to be improved

### Operating system

Windows, Linux, Mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by feloy** [comment]
I tested on the wrong page (Terminal tab) on Mac, it works as expected. Closing the issue
