### ISSUE TITLE
Ability to start/stop/restart a container from the list of containers

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#9]
## Description ##
As a user, I should be able to start/stop/restart a container from the list of containers. 

<img width="297" alt="Capture d’écran 2022-03-10 à 14 10 45" src="https://user-images.githubusercontent.com/1636769/157668544-45d62e3f-0cbb-4cf6-9f3c-c7bb193d7bda.png">

## Acceptance criteria ##
- On hover on one of the container, we'll display a list of actions: Stop, Start, Restart.
- If the container is running, it's not possible to start
- If the container is stopped, it's not possible to click on stop or restart
- When hovering on an action, there is a small tooltip displayed to indicate what the action is

**Comment by benoitf** [comment]
missing restart for now
