### ISSUE TITLE
Add homebrew installation support

### ISSUE THREAD

**Issue by dm3ch** [containers/podman-desktop#90]
### Is your feature request related to a problem? Please describe

For some of the macOS users it would be much easier to install this if it would be added to homebrew package manager

### Describe the solution you'd like

Homebrew package added to main homebrew repository or separate tap is created.

**Comment by benoitf** [comment]
Hello, yes I agree.
Once the name of this project is settled, adding formula would help

**Comment by benoitf** [comment]
brew cask support has been added: https://formulae.brew.sh/cask/podman-desktop
