### ISSUE TITLE
Provide settings to show if Docker compatibility mode is active or not

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#905]
### Is your enhancement related to a problem? Please describe

When a developer is starting Podman/Podman Desktop the docker socket helper should be automatically handling the setup of the local podman path to the docker socket. 
The expected behavior:
- When Docker is running: the socket is pointing to Docker
- When Podman is starting and Docker is not running: the docker API socket will use podman

Tools like testcontainers or others are relying on this to communicate to the container engine.

As a user, I should be able to know the status of that configuration, directly from Podman Desktop

### Describe the solution you'd like

In the settings, we should display the status of the docker compatibility mode. We should display is the docker socket alias is set or not.

During the onboarding / start of podman-machine, we should show an information to the developer is the Docker Compatibility mode is active or not.

**Comment by cdrage** [comment]
Within settings, do you think this should go under extensions and above the "Active" section of the Docker extension? @benoitf

**Comment by benoitf** [comment]
It may be a property like the cpu/memory/ etc of a machine ( package.json) saying compatibility
So it could be displayed automatically in a generic way

**Comment by cdrage** [comment]
@benoitf I'm having troubles understanding the section:

`In the settings, we should display the status of the docker compatibility mode. `

Going through the other issues, does this mean checking to see if `/var/run/docker.sock` exists?

**Comment by benoitf** [comment]
we need to check if behind docker.sock it's podman socket ( is it listening or not, etc)

**Comment by benoitf** [comment]
you could take inspiration from https://github.com/containers/podman-desktop/blob/main/extensions/docker/src/extension.ts#L63

**Comment by benoitf** [comment]
also you should check if podman mac helper ( on Mac for example) is enabled or not

**Comment by cdrage** [comment]
Got it! It'll be nice to show on the main page whether or not compatibility mode is enabled or not. 

The second part, should we let `podman` install podman mac helper (there are still discussions on the two issues)? Or simply prompt that "podman-mac-helper" is not enabled and the user should install it?

Since it looks like from the PR: https://github.com/containers/podman/pull/16565 they'll be adding more support.

**Comment by cdrage** [comment]
Investigating this further...

```
▶ docker ps
Cannot connect to the Docker daemon at unix:///Users/cdrage/.docker/run/docker.sock. Is the docker daemon running?
```

By default, docker checks the socket at the local user directory, but with `podman-mac-helper`, we cannot specify the location for the socket install (installs to `/var/run/docker.sock` by default).

So even if we implement Podman Desktop using `podman-mac-helper` it wouldn't solve the issue because we cannot specify a location:

```
~                                                                                                                                                                                          ⍉
▶ sudo podman-mac-helper install --help
installs the podman helper agent, which manages the /var/run/docker.sock link

Usage:
  podman-mac-helper install [flags]

Flags:
  -h, --help            help for install
      --prefix string   Sets the install location prefix (default "/usr/local")
```

I assume we're blocked for the "installation" part until: https://github.com/containers/podman/issues/16548 is resolved?

**Comment by benoitf** [comment]
1. most of tools are checking for `/var/run/docker.sock` so if you don't have Docker, these tools will work
so we should display if podman container engine is bound to this path.

2. Then, we need to display if the helper is setup or not (for example some users have not that tool installed on macOS)
and display if installed if it's enabled or not

3. for the docker context searching for a local file. We can also display the `docker context` (if docker binary is on the path) but I'm not sure it's high priority as maybe you don't have docker cli at all, you just want to have the tooling working (like a maven project using testContainers)
but we could also display if docker context is being set to the podman socket or not.

**Comment by cdrage** [comment]
Thanks! For clarification, I'm going to implement visual cues as to what's happening with the socket, and some advice on what we can do:

Example:

[✔️](https://emojipedia.org/check-mark/) /var/run/socket.sock is provided by Podman
[✔️](https://emojipedia.org/check-mark/) docker context is using Podman socket

❌ ·docker context is not using Podman socket but $HOME/my-docker-local.sock
