### ISSUE TITLE
Failed tasks notification

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#9059]
### Enhancement

Provide a mecanism to bring awareness on the failed tasks. 
Example: download of a model is failing.

Following the discussion in #7400, we could envision:
- Using a toast notification
- Displaying a visual indicator in the status bar

**Comment by axel7083** [comment]
I feel like the toast are already doing a pretty good job

![Image](https://github.com/user-attachments/assets/ad2edf48-ba22-4301-a383-7b8431c6ea4b)

Closing as completed by https://github.com/podman-desktop/podman-desktop/pull/9488
