### ISSUE TITLE
Cannot install an extension with dependency on another

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#9069]
### Bug description

I tried to install OpenShift Local extension and I got the error message:

`Error: Missing dependencies for this extension: redhat.redhat-authentication`

But the extension is installed

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by odockal** [comment]
The issue was opened in crc-extension: https://github.com/crc-org/crc-extension/issues/322.

**Comment by jeffmaury** [comment]
> The issue was opened in crc-extension: [crc-org/crc-extension#322](https://github.com/crc-org/crc-extension/issues/322).

My guess is that the issue is in core. Do you have an idea ?
