### ISSUE TITLE
Hardcoded colors values

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#9080]
### Bug description

There are remaining hard-coded colors values in svelte templates:

```
% grep -rl 'bg-[^[].*[0-9]00' packages/renderer/**/*.svelte      
```
- [x] packages/renderer/src/lib/dialogs/CustomPick.svelte
- [x] packages/renderer/src/lib/task-manager/TaskManager.svelte
- [x] packages/renderer/src/lib/ui/Badge.svelte
- [x] packages/renderer/src/lib/ui/ProviderInfoCircle.svelte
- [x] packages/renderer/src/lib/carousel/CarouselTest.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderNotInstalled.svelte
- [x] packages/renderer/src/lib/dialogs/CommandPalette.svelte
- [x] packages/renderer/src/lib/dialogs/QuickPickInput.svelte
- [x] packages/renderer/src/lib/extensions/CatalogExtension.svelte
- [x] packages/renderer/src/lib/extensions/ExtensionBadge.svelte
- [x] packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte
- [x] packages/renderer/src/lib/image/PushImageModal.svelte
- [x] packages/renderer/src/lib/pod/KubernetesTerminalBrowser.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderInstallationModal.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/EnumItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/FloatNumberItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/SliderItem.svelte
- [x] packages/renderer/src/lib/recommendation/ExtensionBanner.svelte
- [x] packages/renderer/src/lib/task-manager/ProgressBar.svelte
- [x] packages/renderer/src/lib/ui/AuditMessageBox.svelte
- [x] packages/renderer/src/lib/ui/ConnectionStatus.svelte
- [x] packages/renderer/src/lib/ui/ExtensionStatus.svelte
- [x] packages/renderer/src/lib/ui/ProviderInfo.svelte
- [x] packages/renderer/src/lib/window-control-buttons/LinuxControlButton.svelte

```
% grep -rl 'text-[^[].*[0-9]00' packages/renderer/**/*.svelte 
```

- [x] packages/renderer/src/lib/dialogs/CustomPick.svelte
- [x] packages/renderer/src/lib/dialogs/QuickPickInput.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesCliTool.svelte
- [x] packages/renderer/src/lib/ui/ProviderResultPage.svelte
- [x] packages/renderer/src/lib/toast/ToastCustomUi.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/ConfigMapDetails.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/ConfigMapDetailsSummary.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/SecretDetails.svelte
- [x] packages/renderer/src/lib/configmaps-secrets/SecretDetailsSummary.svelte
- [x] packages/renderer/src/lib/container/ContainerColumnNameContainer.svelte
- [x] packages/renderer/src/lib/container/ContainerDetails.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderConfigured.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderConfiguring.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderNotInstalled.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderReady.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderStarting.svelte
- [x] packages/renderer/src/lib/dashboard/ProviderWarnings.svelte
- [x] packages/renderer/src/lib/deployments/DeploymentDetailsSummary.svelte
- [x] packages/renderer/src/lib/dialogs/CommandPalette.svelte
- [x] packages/renderer/src/lib/extensions/CatalogExtension.svelte
- [x] packages/renderer/src/lib/extensions/ExtensionBadge.svelte
- [x] packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte
- [x] packages/renderer/src/lib/featured/FeaturedExtension.svelte
- [x] packages/renderer/src/lib/feedback/SendFeedback.svelte
- [x] packages/renderer/src/lib/image/PullImage.svelte
- [x] packages/renderer/src/lib/image/PushImageModal.svelte
- [x] packages/renderer/src/lib/image/RecommendedRegistry.svelte
- [x] packages/renderer/src/lib/ingresses-routes/IngressDetails.svelte
- [x] packages/renderer/src/lib/ingresses-routes/IngressRouteDetailsSummary.svelte
- [x] packages/renderer/src/lib/ingresses-routes/RouteDetails.svelte
- [x] packages/renderer/src/lib/kube/KubeDetailsSummary.svelte
- [x] packages/renderer/src/lib/kube/KubePodDetailsSummary.svelte
- [x] packages/renderer/src/lib/node/NodeDetailsSummary.svelte
- [x] packages/renderer/src/lib/onboarding/OnboardingComponent.svelte
- [x] packages/renderer/src/lib/pod/KubernetesTerminalBrowser.svelte
- [x] packages/renderer/src/lib/pod/PodDetails.svelte
- [x] packages/renderer/src/lib/pod/PodDetailsSummary.svelte
- [x] packages/renderer/src/lib/pod/PodmanPodDetailsSummary.svelte
- [x] packages/renderer/src/lib/preferences/ExtensionIcon.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderInstallationModal.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesProxiesRendering.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesRenderingItem.svelte
- [x] packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/EditableItem.svelte
- [x] packages/renderer/src/lib/preferences/item-formats/FloatNumberItem.svelte
- [x] packages/renderer/src/lib/pvc/PVCDetails.svelte
- [x] packages/renderer/src/lib/pvc/PVCDetailsSummary.svelte
- [x] packages/renderer/src/lib/service/ServiceColumnType.svelte
- [x] packages/renderer/src/lib/service/ServiceDetails.svelte
- [x] packages/renderer/src/lib/service/ServiceDetailsSummary.svelte
- [x] packages/renderer/src/lib/troubleshooting/TroubleshootingPageStoreDetails.svelte
- [x] packages/renderer/src/lib/ui/AuditMessageBox.svelte
- [x] packages/renderer/src/lib/ui/ConnectionErrorInfoButton.svelte
- [x] packages/renderer/src/lib/ui/ConnectionStatus.svelte
- [x] packages/renderer/src/lib/ui/ExtensionStatus.svelte
- [x] packages/renderer/src/lib/ui/PasswordInput.svelte
- [x] packages/renderer/src/lib/ui/StatusDot.svelte
- [x] packages/renderer/src/lib/window-control-buttons/LinuxControlButton.svelte

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by SoniaSandler** [comment]
PRs for this issue:
- https://github.com/containers/podman-desktop/pull/9422
- https://github.com/containers/podman-desktop/pull/9423
- https://github.com/containers/podman-desktop/pull/9424
- https://github.com/containers/podman-desktop/pull/9425
- https://github.com/containers/podman-desktop/pull/9426
- https://github.com/containers/podman-desktop/pull/9427
- https://github.com/containers/podman-desktop/pull/9647

**Comment by SoniaSandler** [comment]
It was decided to keep the providers' colors hardcoded for now

**Comment by SoniaSandler** [comment]
- CustomPick: couldn't find a way to check it visually
- QuickPickInput and PreferencescliTool: didn't find any leftover hardcoded colors despite the fact that it shows up in the check
- TaskManager: the hardcoded color is in a comment (L62)
- ProviderInfoCircle: decided in UX call to leave the provider colors hardcoded
- ProviderResultPage: there are two hardcoded colors that IMHO will be a bit difficult to adjust to the color registry because their change in dark vs light will impact their visual appearance compared to the current one (gray-800 for medium and gray-500 for low):
![Image](https://github.com/user-attachments/assets/24a4b277-84d4-4a60-82d1-3864a0e056bd)
![Image](https://github.com/user-attachments/assets/6dc143ee-6ca1-42a5-a1dd-8b5a1bd50376)

**Comment by SoniaSandler** [comment]
@feloy @benoitf @deboer-tim in the comment above I added the last files (excluding those in https://github.com/podman-desktop/podman-desktop/pull/9889) that show up as having hardcoded colors.
lmk if we're okay with closing this issue after merging the last PR with those files still showing up in the check or if you have some ideas or comments regarding this.

**Comment by feloy** [comment]
> [@feloy](https://github.com/feloy) [@benoitf](https://github.com/benoitf) [@deboer-tim](https://github.com/deboer-tim) in the comment above I added the last files (excluding those in [#9889](https://github.com/podman-desktop/podman-desktop/pull/9889)) that show up as having hardcoded colors. lmk if we're okay with closing this issue after merging the last PR with those files still showing up in the check or if you have some ideas or comments regarding this.

I checked most of the remaining files, based on your message above.

For the `CustomPick` component, its display is triggered by the call of `createCustomPick().show()` from the extension API by an extension, but I cannot find an extension using it.

If you want to test it, I think the best way would be to add the code `createCustomPick()` in some existing extension.

**Comment by benoitf** [comment]
we can close it when there are no more results or false positive

```
$ grep -rl 'bg-[^[]*[0-9]00' packages/renderer/**/*.svelte
packages/renderer/src/lib/dialogs/CustomPick.svelte
packages/renderer/src/lib/task-manager/TaskManager.svelte
packages/renderer/src/lib/ui/ProviderInfoCircle.svelte

$ grep -rl 'text-[^[]*[0-9]00' packages/renderer/**/*.svelte
packages/renderer/src/lib/dialogs/CustomPick.svelte
packages/renderer/src/lib/ui/ProviderResultPage.svelte
```

4 files to fix and then we're free to close the issue

and open a follow-up to have a rule checking if we're not using hardcoded values (so nobody will try to use an hardcoded value)

**Comment by deboer-tim** [comment]
Please remove unused colors from the bottom of tailwind.config.cjs as well. Some will still be used by the website, but other zinc/violet should be removed so they aren't accidentally used again.

**Comment by SoniaSandler** [comment]
@benoitf will the rule check only bg and text hardcoded colors? I think there are also some border and shadow hardcoded colors (I think I updated some of those)

**Comment by benoitf** [comment]
you might need to provide the extra regexp you used to check

I guess then in addition to `'bg-[^[]*[0-9]00'` and `'text-[^[]*[0-9]00'` we need `border-[^[]*[0-9]00'` and others ?

**Comment by SoniaSandler** [comment]
~~If the rule will included all the hardcoded colors (not only bg and text), I think maybe we should open another issue for the other properties~~
Nevermind, there aren't a lot of hardcoded borders coming from `border-[^[]*[0-9]00`

**Comment by SoniaSandler** [comment]
`grep -rl 'bg-[^[]*[0-9]00' packages/renderer/**/*.svelte`
`grep -rl 'text-[^[]*[0-9]00' packages/renderer/**/*.svelte`
`grep -rl 'border-[^[]*[0-9]00' packages/renderer/**/*.svelte`
All return no match.
Unused colors have been removed from tailwind.config.cjs file.
Closing this as done
