### ISSUE TITLE
Task created by extension are not cancellable 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9092]
### Bug description

We have in the API, a `cancellable` option 

https://github.com/containers/podman-desktop/blob/208b2a07fc172213fc5b3ee143e463a24fbfe597/packages/extension-api/src/extension-api.d.ts#L1195

However, since the refactor, we may have lost the capabilities of cancelling a task. (did we have before ? I don't remember)

### Operating system

Fedora 40

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

In an extension

```ts
import { window, ProgressLocation } from '@podman-desktop/api';

await window.withProgress({
  location: ProgressLocation.TASK_WIDGET,
  title: `Long running task`,
  cancellable: true,
}, (progress, token) => {
  token.onCancellationRequested(() => {
    console.log('request cancel');
  });
  return // todo long running task
});
````

Even after defining `cancellable` the task do not appear to be cancellable in the TaskManager

![image](https://github.com/user-attachments/assets/c54bdac5-68dc-4f80-b6f4-33876c857d5a)

### Additional context

Potential fix

### Quick fixes

We currently have an action that extension can define, the `ProgressImpl` could create a `Cancel` action when the `withProgress` is called with `cancellable: true`.

However this would overwrite any route that the extension would have defined.

### Better fix

We could add a `CancellationTokenImpl` that we provide to the withProgress task to the `CancellationTokenRegistry` and add the cancellation token id to the task, we would add a `cancellableTokenId` or `cancelId`  or any new field, allowing the frontend to call `window.cancelToken` to cancel a given task.

This would not change any api, and would require a small change in the `TaskManagerItem.svelte` to support an additional `cancel` optional button next to the action.

**Comment by axel7083** [comment]
cc @benoitf an opinion?

**Comment by benoitf** [comment]
I don't know why there is rush on discussion for this task but what I can say for sure is that it shouldn't use quickfix provided solution

it seems also the doc is stating:
```
     * To monitor if the operation has been cancelled by the user, use the provided {@linkcode CancellationToken}.
     * Note that currently only `ProgressLocation.Notification` is supporting to show a cancel button to cancel the
     * long-running operation.
```

while I only see
```
  export enum ProgressLocation {
    APP_ICON
    TASK_WIDGET
  }
```
