### ISSUE TITLE
If `auditItems` function returns errror 'Create' button stays enabled on create resource page

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#9118]
### Bug description

An extension can provide auditItems function when setting up container connection factory. auditItems function can return records reportin problems with new container connection properties. The `Create` button meantime stays enabled and user can proceed with creating container connection.

Would we good to diable `Create` button in case when connection properties audit returns audit records with type `error`.

### Operating system

macOS M1 Sonoma 14.5

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

If Kind cluster with the same name is created there should be an error on top of the new kind cluster form, but 'Create' button should still be available.

### Additional context

Relates to #9096.

**Comment by odockal** [comment]
@dgolovin I have assigned you to the issue since it seems you have a fix already prepared.
