### ISSUE TITLE
Cannot install Podman 5.2.3 from nightly Podman Desktop - Error: Can't find Podman setup package

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9123]
### Bug description

Installing the podman via podman desktop fails. Cannot find the setup.exe package on the path. 
It is trying to find the podman-setup.exe at: `C:\Users\user\AppData\Local\Programs\podman-desktop\resources\extensions\podman\assets\podman-5.2.3-setup.exe` which does not exist.

### Operating system

Windows 

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by odockal** [comment]
There is no `extensions` folder under `resources`.

**Comment by benoitf** [comment]
cc @dgolovin might be related to the new layout for podman extension ?

**Comment by odockal** [comment]
Still not working correctly:
![Podman523InstllationFailed](https://github.com/user-attachments/assets/b24d050c-6064-402c-89ef-b3775ed45c99)
