### ISSUE TITLE
Podman extension should be initialized async

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#9124]
### Bug description

While testing a PR on my machine, I noticed the Podman extension does not start anymore because it now takes more than 20s.
It should be made async

### Operating system

Win11Pro

### Installation Method

None

### Version

1.11.1

**Comment by odockal** [comment]
@jeffmaury Is this something we want to have in 1.13?

**Comment by jeffmaury** [comment]
No will close it without merge

**Comment by jeffmaury** [comment]
Not required anymore see #10119
