### ISSUE TITLE
Kubernetes Context Page E2E Test automation

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9137]
After the test implementation of the kube-context/kubernetes e2e test case, we need to make sure that tests is beign run on all relevant platforms.

* test runs on linux
* test runs on windows
* test runs on mac os

**Comment by rostalan** [comment]
Windows run: https://github.com/containers/podman-desktop-e2e/actions/runs/11001937127
![image](https://github.com/user-attachments/assets/b3b69c41-1d42-4298-b612-6d609fd08e7e)

**Comment by rostalan** [comment]
Mac with applehv: ![image](https://github.com/user-attachments/assets/caaeb262-4bba-4a43-a2bc-13207aa67680)
https://reportportal-podman-desktop.apps.ocp-c1.prod.psi.redhat.com/ui/#podman-desktop/launches/all/807

**Comment by rostalan** [comment]
Mac with libkrun: 
![image](https://github.com/user-attachments/assets/84e5bb75-30b8-41f1-b4fc-76caa0ef9406)
https://reportportal-podman-desktop.apps.ocp-c1.prod.psi.redhat.com/ui/#podman-desktop/launches/all/809

**Comment by rostalan** [comment]
Linux:
![image](https://github.com/user-attachments/assets/08966d7c-37a2-4bb2-8eb0-7fc30ae902f6)
https://github.com/containers/podman-desktop-e2e/actions/runs/11098720268
