### ISSUE TITLE
UX: Kubernetes empty page

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#9142]
### UX Description

Discussed during the UX call on Sep 26th, we would like to improve the visibility of the links `Create new Minikube cluster...`, `Create new Kind cluster` as visible below:

![kubernetes-empty-page](https://github.com/user-attachments/assets/8b1b9337-ed73-4b96-8ac0-e195ebf2ae79)

Notes from the call:
- Reducing the visibility of the extensions list?
- Increasing the visibility of the first links (Create new …)?
- Having only one common list of extensions (remote and local in the same list)?
- Probably have a good balance between:
  - Creating new cluster with installed extension
  - Installing a new extension 

Related to https://github.com/containers/podman-desktop/issues/8571

### Request type

UX analysis/suggestions for improvement

### Primary Contact

@feloy

### Deadline for request

Targeted for Podman Desktop v1.13

**Comment by ekidneyrh** [comment]
Here’s a mockup for the Kubernetes page when there’s no clusters:

![Image](https://github.com/user-attachments/assets/7d631103-77b2-4fb0-b432-b92c22c5c6ae)


_Increasing visibility of links_
I addressed this by making the links into buttons. I also have added the relevant logos to appear above the buttons also to easier distinguish between the clusters. 

We could also do without the logos if it is making the page too busy. 

![Image](https://github.com/user-attachments/assets/0498c539-1f88-4588-9bc6-d99610dba6fc)


_Reduce extension list_
Having the extensions grouped under a ‘related extensions’ gets rid of the multiple extension lists that were present.

**Comment by deboer-tim** [comment]
This page is a choice between using any of the currently installed extensions (the most likely option - once you have the correct one installed), or installing a new one. The purple buttons are starting to draw the eye more, but related extensions (especially if there are two or more) are much bigger on screen and I don't feel a flow yet. I think the buttons need icons as an eye catcher / to be consistent, but wondering if they should be cards too, or how else we can create some balance and draw more toward these first options.

The documentation link and large 'related extensions' title in the middle also break up the choice. It's like 'For breakfast do you want eggs, pancakes, click _here_ to learn about healthy eating, Related Foods, or go to the store for cereal?' :)

Removing (or really merging) the two extensions sections helps a lot with space, but we'll still have issues on smaller screens; may not be much we can do about that.

**Comment by ekidneyrh** [comment]
Thanks for the feedback @deboer-tim 

I have two layout options. The first one is to make the 'create new' cards the same layout as the learning center cards, and then get rid of the Extensions title:

![Image](https://github.com/user-attachments/assets/9079602b-40b9-4f74-97dd-9605d1b9f32e)

Option two is using the cards from the resources page and allow them to scale up and down as they do on that page. The extension card was adjusted slightly to follow a similar format and have the action button on the same side. 

![Image](https://github.com/user-attachments/assets/0c591f4a-d467-442b-83ca-729229cd23da)

I also moved the documentation link to the bottom of the page. Let me know what you think :)

**Comment by deboer-tim** [comment]
Thanks, these are much better IMHO. I prefer the top one visually and because it makes better use of space. I think we need a little more to differentiate between the 'already installed' options and 'install a new one', e.g. maybe just a line of text to break it up like 'Or install a new Kubernetes provider via an extension'.

**Comment by Firewall** [comment]
I am a big fan of these last two options aswell. One thing I quite like about the 2nd option is that it is quite close to the actual provider page, which can help users get that fimilar feeling.

**Comment by ekidneyrh** [comment]
> Thanks, these are much better IMHO. I prefer the top one visually and because it makes better use of space. I think we need a little more to differentiate between the 'already installed' options and 'install a new one', e.g. maybe just a line of text to break it up like 'Or install a new Kubernetes provider via an extension'.

![Image](https://github.com/user-attachments/assets/bb6c47e0-0651-43fb-8260-befac1e4f91a)

**Comment by benoitf** [comment]
I have questions from a technical/implementation POV

If I understand, it's to display the same cards than in resources but with a different UI

it means that it will include also the text "More information" with the link to the provider as shown below:

 ![Image](https://github.com/user-attachments/assets/f7b5789c-5deb-46d6-8e53-6684b823ae5f)

as we only have the markdown text, we can't cut before "More information" to match the mockup.


how to handle the case with text being more or less long. Cards will always have the same height or we cut the text if too long or something else ?
depending on this answer, should we have "Create new..." button before the text being displayed so it does not move.

if we have 4 cards to display, it's always rows of 3 cards ?

**Comment by deboer-tim** [comment]
TBH I'd just remove the text, or have a 'more info' link that goes to Resources. Smaller UI and don't need to explain what (e.g.) Kind is on every screen.

**Comment by ekidneyrh** [comment]
I have the text on the cards to bulk them up. We can use the full text thats in the preferences if it is easier adn then they can follow the rules those cards follow in terms of the length of text.

Or we can go with no text as Tim suggested if that makes more sense. Is it presumed that the user would know what these are without explanation? Could this be the first time they are interacting with Kind etc?

> if we have 4 cards to display, it's always rows of 3 cards ?

In terms of this page I understood it was just those three for 'create new'. But for future proofing three in a row is good.

**Comment by benoitf** [comment]
> Could this be the first time they are interacting with Kind etc?

yes it can be the first time.
Also let's imagine we have thousands of extensions, even if you went to the extension page you might not be aware of all of the names.

It might also hard for a newcomer to understand what means "Developer Sandbox" without a way to get/read the description.

**Comment by ekidneyrh** [comment]
in that case i'd vote for keeping the descriptions

**Comment by ekidneyrh** [comment]
Is there anything else needed on this ticket?

**Comment by Firewall** [comment]
@ekidneyrh It's not clear to me which one of the two options we want to go with to be honest. Even if we keep the descriptions

**Comment by ekidneyrh** [comment]
> [@ekidneyrh](https://github.com/ekidneyrh) It's not clear to me which one of the two options we want to go with to be honest. Even if we keep the descriptions

@Firewall My understanding was that this one was the prefered:

https://github.com/podman-desktop/podman-desktop/issues/9142#issuecomment-2476013701

**Comment by Firewall** [comment]
Ok 👍
