### ISSUE TITLE
UI sending notifications despite setup

### ISSUE THREAD

**Issue by nzineer** [containers/podman-desktop#9147]
### Bug description

Despite podman UI showing that podman has been setup and is running, 

![image](https://github.com/user-attachments/assets/31f96d02-b3a9-44b6-8fe6-30506a5f8b6a)

And resources UI confirming the same,

![image](https://github.com/user-attachments/assets/2cd60cdf-23cf-41dc-be32-f532c78cef85)

Same confirmed from the cli as well

`
$ podman machine ls
NAME         VM TYPE     CREATED      LAST UP            CPUS        MEMORY      DISK SIZE
podman-rhel  wsl         9 hours ago  Currently running  4           1GiB        100GiB
`

Podman UI keeps sending notifications that Podman needs to be setup.

![image](https://github.com/user-attachments/assets/d57c37c9-4f0a-4cbd-ae2b-1e66830e230f)

### Operating system

Windows 10 Enterprise

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

On windows 10 Enterprise
Install using the [airgap installer for v1.12.0](https://github.com/containers/podman-desktop/releases/download/v1.12.0/podman-desktop-airgap-1.12.0-setup-x64.exe) and setup a [RHEL machine](https://podman-desktop.io/blog/2024/08/01/using-rhel-wsl-podman-machine).

once your machine is setup, you should intermittently observe notification pop-ups on your desktop that podman needs to be setup.

**Comment by mjknoll** [comment]
Same issue on Win 11 popping up continually every ~30s or less.

**Comment by gastoner** [comment]
https://github.com/user-attachments/assets/870d7ce5-b6dc-4587-9e8b-40a3fc33edaf

Should have the same versions and rhel image, but not able to reproduce
