### ISSUE TITLE
kind new connection properties audit should catch attempts to create clusters with the same name

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#9152]
### Bug description

From @axel7083

> Here are my existing kind clusters
>
> ![image](https://github.com/user-attachments/assets/02f5526c-21b2-4b9c-a002-31568638ecb5)
>
>But the `Create` button seems to still be active
>
>![image](https://github.com/user-attachments/assets/9e11f73c-1f96-4eb6-ac26-7ce6883738d3)
>
>After clicking on it I am getting the error (expected)
>
> ![image](https://github.com/user-attachments/assets/3767050d-7060-4b35-b443-576210c6aea3)

Instead of failing after running kind cluster create command, audit of the properties should return 'error' record about existing cluster with the same name. With #1819 fixed, that would disable `Create` button and show error message on top of the page.

### Operating system

macOS M1 Sonoma 14.5

### Installation Method

Other

### Version

1.11.1

### Steps to reproduce

See above in bug description

**Comment by odockal** [comment]
@dgolovin hey, if the issue was solved with your PR, can we close it?

**Comment by axel7083** [comment]
> [@dgolovin](https://github.com/dgolovin) hey, if the issue was solved with your PR, can we close it?

It is not fixed

**Comment by dgolovin** [comment]
it cannot be fixed. The reason is support for different providers. KIND_EXPERIMENTAL_PROVIDER can be used to create cluster, but is ignored when running 'kind get clusters'.

**Comment by axel7083** [comment]
Closing as not feasible
