### ISSUE TITLE
Cannot install podman even with Hyperv Windows feature enabled

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9158]
### Bug description

On the windows, there is now a requirement check for hyperv virtualization that allows to install podman only if podman is 5.2.0 or greater. But I do not have any podman installed and so I am stuck.

### Operating system

windows

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Have no previous podman installed on the system
2. Do not have Virtual Machine platform feature enabled
3. Have HyperV feature enabled
4. Install podman desktop
5. Click on install podman in dashboard or via onboarding
6. assert: Podman installation is allowed -> I can install podman when I have hyperv feature enabled
Actual result: The check does not allow me to continue even though I have hyperv enabled. 

Update: I cannot instal podman at all, even though I have hyperv disabled and VMP enabled. Check passes via VMP but got stuck on the: "Hyper-V is only supported with podman version >= 5.2.0"

### Additional context

I should be able to install podman with one of the virtualization providers enabled, either Virtual Machine Platform or hyperv.

**Comment by jeffmaury** [comment]
You need to run podman desktop in elevated mode

**Comment by odockal** [comment]
1. General problem is that even with hyperv feature turned off, I still get the message. So I cannot install podman at all. I will update steps to reproduce
2. User has no idea that he is supposed to run podman-desktop in elevated mode. We need to improve the message.

**Comment by lstocchi** [comment]
I guess the problem is that the hyperv check is run with the preflight when trying to install podman. In the check we see if podman 5.2 is installed to consider hyperv enabled, but during installation there is no podman so it will always fail.

**Comment by odockal** [comment]
Exactly. Also, onboarding preflight check is one part, another place would be dashboard, if there are two places that call the check.

**Comment by jankap** [comment]
> You need to run podman desktop in elevated mode

It's written in the documentation, but I overread it a couple of times. Thanks a lot for that hint!

To restate, **You need to close all instances of Podman Desktop (see taskbar) and re-open Podman Desktop as Administrator!** Then, and only then you'll have the dropdown to choose Hyper-V.
