### ISSUE TITLE
Switch eslint to work on content mode

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#9168]
### Is your enhancement related to a problem? Please describe

eslint is now very slow in cases you want to submit a PR but you previously check several PRs because a lot of files are detected as changed

### Describe the solution you'd like

Switch eslint to content mode

**Comment by deboer-tim** [comment]
+1. Even when I switch branches/commits with only a couple changed files eslint sometimes seems to revert to full scan and can take several minutes to run.
