### ISSUE TITLE
Proxy configuration - add configuration if proxy uses a custom CA certificate file

### ISSUE THREAD

**Issue by jochenr** [containers/podman-desktop#917]
### Is your enhancement related to a problem? Please describe

IMHO [Issue "Proxy configuration"](https://github.com/containers/podman-desktop/issues/127) is missing a configuration, if the proxy uses a custom CA certificate file.

### Describe the solution you'd like

Similar to CRC/OpenShift Local  (see [Chapter 5.3. Starting CRC behind a proxy](https://crc.dev/crc/#starting-behind-proxy_gsg))(If the proxy uses a custom CA certificate file), a Proxy CA file should be configurable over the UI

```
$ crc config set proxy-ca-file <path-to-custom-ca-file>
```

**Comment by slemeur** [comment]
The first way we can look at that is by providing documentation on how to handle that case in a manual way.
The second and more advanced solution would be to investigate how we could automate that configuration.

**Comment by themr0c** [comment]
Does someone can give me a hint how to handle that case in a manual way?

**Comment by themr0c** [comment]
* In `containers.conf`, add environment variable. 
* Windows, macOS: configure the cacert in the VM.
* Linux: Podman is using the host configuration.

**Comment by karstengresch** [comment]
Any update on this?
