### ISSUE TITLE
Could not find a matching machine for connection while podman compose version with HyperV machine

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9171]
### Bug description

I am seeing an error on cli when trying to run a `podman compose up -d` with some compose file. Docker compose was installed via podman desktop and machine as well. I am using Hyperv provider.

I tried cli in both standard and elevated mode.

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Install podman 5.2.3 and enable hyperv
2. Install podman desktop 1.13.0-next
3. Install compose via podman desktop system wide
4. Create a podman machine with hyperv virtualization provider
5. Option 1: on cli, both elevated and standard: try `podman compose version`
6. Option 2: on cli (may try elevated as well), try `podman compose up -d` with some compose.yaml file. ie: https://github.com/odockal/podman-desktop-qe/blob/main/examples/compose/compose.yaml.
7. Assert: Version of the compose or compose containers are up and visible in podman desktop
Actual result: `Error: Get machine connection URI: Could not find a matching machine for connection "ssh://root@127.0.0.1:51055/run/podman/podman.sock"`

**Comment by jeffmaury** [comment]
What is your default Podman connection ? Can you verify ssh://root@127.0.0.1:51055/run/podman/podman.sock is the HyperV machine VM

**Comment by jeffmaury** [comment]
At least `podman compose version` worked for me

**Comment by odockal** [comment]
@jeffmaury Yes, it is the default connection as shown via `podman system connection ls` It is named `podman-machine-default-root` and it points to the mentioned connection. If I open the podman desktop, the machine says endpoint: `npipe:////./pipe/podman-machine-default`.

**Comment by odockal** [comment]
So, I figured it out. I need to be in elevated mode, that is one of the requirements when using the compose with podman chine based on hyperv. The other one is to have set env. var. `CONTAINERS_MACHINE_PROVIDER` to `hyperv`. Then, it works.

**Comment by odockal** [comment]
Solution:
```
1. Run powershell as admin
2. Set: `$env:CONTAINERS_MACHINE_PROVIDER='hyperv'`
3. Run `podman compose version` or `podman compose up -d`

**Comment by jeffmaury** [comment]
Can we close this on as this is a requirement from Podman ?

**Comment by odockal** [comment]
@jeffmaury Yes.
