### ISSUE TITLE
Kubernetes page blank

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#9189]
### Bug description

Blank when clicking on Kubernetes icon / navbar.

We should forward to the Nodes section until #8818 is added.
![Screenshot 2024-10-03 at 10 23 10 AM](https://github.com/user-attachments/assets/cb367ee4-0061-44ce-9424-de9b625bdf4f)

### Operating system

mac M1

### Installation Method

None

### Version

latest commit

**Comment by cdrage** [comment]
IMHO should be fixed before release, so added to 1.13.0 milestone @feloy @benoitf @deboer-tim

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/8825
