### ISSUE TITLE
Provide SHA256 checksums & PGP signed files on release

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#919]
### Is your feature request related to a problem? Please describe

For secure air-gapped environments, we should be able to verify that the file downloaded is the correct one.

### Describe the solution you'd like

We should provide a way to:
* Publicly provide a SHA256 checksum
* PGP / signed and verifiable binaries with a posted public key

Both which should be posted publicly (website / github release page)

### Additional context

Inspiration / bash script to generate a table in markdown + sha256 summary: https://github.com/kubernetes/kompose/blob/master/script/release.sh#L126

Looks like:

__Checksums:__

| Filename        | SHA256 Hash |
| ------------- |:-------------:|
[SHA256_SUM](https://github.com/kubernetes/kompose/releases/download/v1.27.0/SHA256_SUM) | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[kompose-darwin-amd64](https://github.com/kubernetes/kompose/releases/download/v1.27.0/kompose-darwin-amd64) | 88f3bafcef2263af8f8c84e27255761f5d41a4e2cdff41bf1a57d4aa4c3c34ec
[kompose-darwin-amd64.tar.gz](https://github.com/kubernetes/kompose/releases/download/v1.27.0/kompose-darwin-amd64.tar.gz) | 70ab796d034b46ff365262c47ce99db6e0a144019ad8072b2c218665960fa250
[kompose-darwin-arm64](https://github.com/kubernetes/kompose/releases/download/v1.27.0/kompose-darwin-arm64) | ca04f4148d9e80d8ee71ba10085fdab199c3877f84d35069ba833a96f9cca4a9
[kompose-darwin-arm64.tar.gz](https://github.com/kubernetes/kompose/releases/download/v1.27.0/kompose-darwin-arm64.tar.gz) | 955e68e012fc3adc972c4bcc2b54424378d3fa58dab75b22334f8bee6935a07f

**Comment by benoitf** [comment]
we're signing the binaries with digital certificates for Windows and macOS, ensuring it's published from a known source.

**Comment by ghubstan** [comment]
Not being able to find release checksums is making me balk at trying out podman-desktop.

**Comment by benoitf** [comment]
@ghubstan what is the operating system that you're using for trying out podman desktop ?

Checksums are verified on the different package managers used to install also Podman Desktop 
for example brew for mac, flatpak, and winget/chocolatey/scoop etc on Windows

**Comment by ghubstan** [comment]
Ubuntu 22.04.1 LTS, installing podman via APT pkg manager.  I'm doing fine just using a terminal.

I have not tried podman desktop yet -- just waiting for a checksum.
Thanks.

**Comment by benoitf** [comment]
you could install podman desktop using https://flathub.org/apps/details/io.podman_desktop.PodmanDesktop

**Comment by ghubstan** [comment]
Ok, thanks.  I'm not used to flat pack, but I assume I can verify the pkg's checksum as well as a tarball's.

**Comment by benoitf** [comment]
SHA512 for Windows and macOS binaries are provided in the `latest.yaml` and `latest-mac.yaml` files

**Comment by benoitf** [comment]
closing as won't fix as it's not highly demanded (no vote for the issue in 1year+)
