### ISSUE TITLE
Title+icon in the left navigation bar

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#9191]
### Is your enhancement related to a problem? Please describe

we got requests that having only the icons for the left navbar is hard for beginners

we have hovers but you need to go to every icon to know what it is

### Describe the solution you'd like

have an option to display both title and icons

advanced users know what icons are and can drop the title

**Comment by slemeur** [comment]
On this issue, let's optimize for the first time experience. 
It is most likely that the users who are starting Podman Desktop for the first time will be the one who will benefit the most from displaying the labels below the icon. It indeed will provide immediate guidance and context. 

Having an option in the settings to hide them, would remain an advanced setting that the user can use. We would like to be able to measure if the users are using this advanced option, so we should also think about the telemetry.

The question will be that if we are displaying the label - should we keep displaying the tooltips as that might feel duplicating the information? (cc @ekidneyrh , @MariaLeonova )

**Comment by ekidneyrh** [comment]
@slemeur I would get rid of the tooltip when the text is displayed with the icon as it's redundant and doesn't help the user in anyway - just clogging up the page with unnecessary elements.

**Comment by deboer-tim** [comment]
I agree for the label, but tooltip also has the counter - I think we need to keep that.
