### ISSUE TITLE
clicking outside of the feedback form should not close the form

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#9192]
### Bug description

if we open the feedback form and start to fill it then click elsewhere, everything is lost

it should at least notice the user that it's gonna disappear/be closed

### Operating system

macOS

### Installation Method

None

### Version

1.11.1

**Comment by gastoner** [comment]
Should I add some text to the feedback form? e.g. "Form will be closed by clicking outside of it" 

Or should I change the behavior of the form to disable the closing dialog by clicking outside?

**Comment by benoitf** [comment]
good question, on my end I'm fine with the two proposals

I would be tempted by option 1 where it might force you to submit (or copy to clipboard, etc) while if you click outside and do something else then you may never come back to submit and it'll be lost

**Comment by deboer-tim** [comment]
I'm fine with either too, but IMHO text is easily missed or you can accidentally click outside. Our dialogs already look modal so adding an option where they actually are and using it here wouldn't be too out of place.
