### ISSUE TITLE
Experimental features in Podman Desktop

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9236]
### Is your enhancement related to a problem? Please describe

We are often using `experimental` hidden feature in Podman Desktop, and making the team enabled them to test it. It started with the light mode, now we have some with the docker-compatibility and soon with the tasks.

@deboer-tim suggested in https://github.com/containers/podman-desktop/pull/9186#discussion_r1788258411 that it would be interested to group the experimental features in a single section.

### Describe the solution you'd like

We discussed this with @benoitf and we were questioning how we can enhance the testing of such features, a nice idea was _enabling all experimental feature for nightlies version of podman destkop. 

We could have a dedicated sections experimental, and expose it also. Allowing user to enable them or not in releases.

**Comment by slemeur** [comment]
Will be solved by https://github.com/podman-desktop/podman-desktop/issues/10222
