### ISSUE TITLE
Add prune buttons to containers, pods, volumes and images.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#924]
### Is your feature request related to a problem? Please describe

Wasted disk space, difficult to figure out what disk space is currently being used and how to clean it up.

### Describe the solution you'd like

Want to prune all pods, volumes containers and images that are not in use.

An enhancement on this would be to show all of the containers that currently use an image, volume or in use within a pod.

**Comment by benoitf** [comment]
> An enhancement on this would be to show all of the containers that currently use an image, volume or in use within a pod.

If you go to the image list, if the image is used it's displayed in green and you can't remove it
And for volumes, it's the same.

**Comment by rhatdan** [comment]
Nice but not easily guessable.

**Comment by cdrage** [comment]
@rhatdan @benoitf 

To confirm, we'd add a a singular button on each page that corresponds to the following `podman` cli commands:

- Image page: `podman image prune`
- Pod: `podman pod prune`
- Volume: `podman volume prune`

Etc.

With the button having a modal that confirms yes / no to deleting and most likely positioned next to the other buttons at the top.

I'll start on the implementation.

**Comment by deboer-tim** [comment]
+1 from me. Other container engines will have prune as well, would be good to keep this at least a bit generic/extendable even if only implemented for podman.

It looks like there was originally a --dry-run option (https://github.com/containers/podman/issues/1910) but it got dropped, correct? Ideally it would be nice if we gave the user an indication of what was about to happen (e.g. a list or # of images that will be deleted), but I'm fine if that's a future item.

**Comment by cdrage** [comment]
> +1 from me. Other container engines will have prune as well, would be good to keep this at least a bit generic/extendable even if only implemented for podman.
> 
> It looks like there was originally a --dry-run option ([containers/podman#1910](https://github.com/containers/podman/issues/1910)) but it got dropped, correct? Ideally it would be nice if we gave the user an indication of what was about to happen (e.g. a list or # of images that will be deleted), but I'm fine if that's a future item.

The only thing I can think about is that when implementing these buttons, if there are multiple engines (docker and podman running) we'd have to ask the user if it's to be deleted from all engines, or selected ones.

Of course, this won't work on the eventual Kubernetes implementation either (can't ask a cluster specifically to prune images, volumes, etc.)

So this will only apply for podman and docker container engines.

**Comment by cdrage** [comment]
TODO Prune functionality:
- [X] Containers https://github.com/containers/podman-desktop/pull/1436
- [X] Pods https://github.com/containers/podman-desktop/pull/1484
- [x] Images https://github.com/containers/podman-desktop/pull/1482
- [x] Volumes https://github.com/containers/podman-desktop/pull/1481

**Comment by cdrage** [comment]
All features have been completed, closing issue 👍
