### ISSUE TITLE
Want a go back button.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#926]
### Is your enhancement related to a problem? Please describe

I am frustraded after I select an image, container, volume ... I want to go back to the list of image, containers ,volumes.
I feel like I am in a web browser and a go back button. 
Accellerator buttons that match web browsers would be added feature.

### Describe the solution you'd like

I want to go back to the list of image, containers ,volumes.
I feel like I am in a web browser and a go back button. 
Accellerator buttons that match web browsers would be added feature.

### Describe alternatives you've considered

Select the item menu

**Comment by rhatdan** [comment]
<alt><LeftArrow> to bring me back.

**Comment by benoitf** [comment]
I think you have that on the top of the page in the breadcrumb

**Comment by rhatdan** [comment]
I am running podman-desktop on Fedora, I don't see any, could you capture an image and show me what to look for.  Having accellerator would be great.

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/204554143-052c8ebf-347a-42f5-a497-1661ece82eb1.png)

it's on the 'Containers>' (if you hover the element I think it's saying go back to the list)

**Comment by rhatdan** [comment]
I guess this is fine, and as I play with the tool, becomes easier to deal with.

**Comment by rhatdan** [comment]
Although having keyboard navigation would be nice.
