### ISSUE TITLE
Error when applying Kubernetes resource changes via kube tab: "data.toISOString is not a function"

### ISSUE THREAD

**Issue by amisskii** [containers/podman-desktop#9260]
### Bug description

When trying to edit Kubernetes YAML through the kube tab in the Kubernetes resource details page, an error occurs preventing the changes from being applied. The following error message is displayed:
`Could not apply Kubernetes YAML: Error: data.toISOString is not a function
`

![Image](https://github.com/user-attachments/assets/38e2b9a5-4427-45b6-b09b-e031cb806ce1)

### Operating system

Fedora 40

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

- Create a Kubernetes cluster.
- Create any Kubernetes resource (e.g., a Pod, Deployment, Service, etc.).
- Navigate to the Kubernetes resource details page for the created resource.
- Click on the kube tab to view the YAML configuration.
- Make changes to the Kubernetes YAML.
- Click on the Apply Changes button.
- Observe the error: `Could not apply Kubernetes YAML: Error: data.toISOString is not a function.`

**Comment by cdrage** [comment]
Good catch, looks like this is universally broken as no matter what I cannot edit anything / apply it.

@deboer-tim we should add this as a blocker for kubernetes for 1.14

**Comment by jeffmaury** [comment]
> Good catch, looks like this is universally broken as no matter what I cannot edit anything / apply it.
> 
> [@deboer-tim](https://github.com/deboer-tim) we should add this as a blocker for kubernetes for 1.14

Yes as I think it's related to Svelte 5 and I'm afraid other Svelte components maybe affected as well. @dgolovin may help

**Comment by cdrage** [comment]
> > Good catch, looks like this is universally broken as no matter what I cannot edit anything / apply it.
> > [@deboer-tim](https://github.com/deboer-tim) we should add this as a blocker for kubernetes for 1.14
> 
> Yes as I think it's related to Svelte 5 and I'm afraid other Svelte components maybe affected as well. [@dgolovin](https://github.com/dgolovin) may help

Found it, looks to be upstream change to serialization when we updated our Kubernetes client: https://github.com/kubernetes-client/javascript/pull/1695
