### ISSUE TITLE
Update Kubernetes dashboard to match UX design

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9265]
### Is your enhancement related to a problem? Please describe

In [this ticket](https://github.com/containers/podman-desktop/issues/9264) we will create the basic page for the Kubernetes welcome page. This task is to update the page to match the design that will be provider in [the design issue ](https://github.com/containers/podman-desktop/issues/9263#issue-2573273119).

### Describe the solution you'd like

[See design](https://github.com/containers/podman-desktop/issues/9263#issue-2573273119)

**Comment by deboer-tim** [comment]
Design is moving along well, and I've made a call on what I thought was easily implementable in #9264. Some differences/gaps from the current design (which could still change) that need to be addressed:
- Guide cards are missing details, e.g. active counts, donut.
- Resource cards are missing images.
- List of resource cards/links should come from a json.
- Should resource cards be dynamically/remotely loaded?
- If this new dashboard design will be used in more places (even the main Podman Desktop dashboard), then guide card and resource card (or a row with a set of them) should be turned into more reusable components.
- Main dashboard already has the learning center, but has different design. Maybe these should be the same component / design?
