### ISSUE TITLE
UI implementation of Kubernetes port forwarding (start)

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#9273]
### Is your enhancement related to a problem? Please describe

Add action to start port forwading for

- pod
- deployment
- service

### Describe the solution you'd like

Depends on #9272

**Comment by axel7083** [comment]
Here is my mockup proposal for the port forward on the container, I am open to suggestion, as I do not know what would be the best way

![Image](https://github.com/user-attachments/assets/ee4efff9-196a-435f-89e2-ab1ca04a9272)

Heavy inspiration from OpenLens. Here is the workflow: 

1. You click on `Forward...`
2. It open a modal asking you to choose a port on the host machine
3. Once created, you can either open to the browser or not

**Comment by slemeur** [comment]
The proposal is looking great and I think it's a great first step.

**Comment by jeffmaury** [comment]
LGTM maybe align buttons to the right
