### ISSUE TITLE
Universal release candidate dmg build does not contain the podman installer for arm arch

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#9293]
### Bug description

Currently it's not possible to install podman from PD in the 1.13.1 release candidate using the universal build dmg installer, it seems the podman installer is missing.

![Image](https://github.com/user-attachments/assets/6037e405-41aa-48f8-848e-211e55cb2679)

### Operating system

macOs

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

1. Download PD 1.13.1 universal build dmg installer.
2. Install PD.
3. During onboarding try to install Podman 5.2.4.
4. Notice the error thrown when trying to install Podman 5.2.4.

**Comment by odockal** [comment]
The problem is that the Podman Desktop searches for `podman-installer-macos-aarch64-v5.2.4.pkg` but in the universal installer there is `podman-installer-macos-universal-v5.2.4.pkg`
