### ISSUE TITLE
Bug(ui-library) Column typing is not compatible with Svelte 5

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9313]
### Bug description

In AI-Lab I was trying to use svelte 5 component as renderer and got the following typecheck error

```
The types of info.renderMapping are incompatible between these types.
    Type ((object: ModelInfo) => Type) | undefined is not assignable to type
```

The problem is coming from the following type definition we are using

https://github.com/containers/podman-desktop/blob/fc042fef0214bb6a5e7fb001210c9fba74fb5d4c/packages/ui/src/lib/table/table.ts#L52

As per the svelte documentation `ComponentType` is deprecated _Deprecated: This type is obsolete when working with the new Component type._ [^1]

---

## Solution

From their documentation, the following is the new way of typing components.

```diff
- readonly renderer?: ComponentType<SvelteComponent<{ object: RenderType }>>;
+ readonly renderer?: Component<{ object: RenderType }>;
```

[^1]: https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes-component-typing-changes

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. use svelte 5 components for the renderer
2. assert typecheck error

**Comment by odockal** [comment]
@deboer-tim Looks like you have a PR to fix the issue, I have assigned you then. hope that is alright.
