### ISSUE TITLE
Cannot create Windows Hyperv Podman Machine with airgapped Podman Desktop with access to internet

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9314]
### Bug description

Creating podman machine with hyperv provider with airgap podman desktop with access to internet throws an error.

![Image](https://github.com/user-attachments/assets/c5ced231-5088-45f6-b4b1-d1329015ee9c)

### Operating system

Windows 10

### Installation Method

Other

### Version

1.13.0

### Steps to reproduce

0. Have HyperV enabled, no network restriction
1. Install/start podman desktop airgapped (1.13.2)
2. Create podman machine with hyperv
3. Assert: Machine is created
Actual result: Error creating the image

### Relevant log output

```
Flag --image-path has been deprecated, use --image instead

Error: failed to add resource: Job failed with error code: 32768 ('podman-machine-default' failed to add device 'Virtual Hard Disk'. (Virtual machine ID 61AF76EC-1B4F-4FFB-AFC7-7004E0283682)  Failed to open attachment 'C:\Users\Ondrej\.local\share\containers\podman\machine\hyperv\podman-machine-default-amd64.vhdx'. Error: 'The file or directory is corrupted and unreadable.'.  'podman-machine-default': Cannot get information for attachment 'C:\Users\Ondrej\.local\share\containers\podman\machine\hyperv\podman-machine-default-amd64.vhdx'. (Virtual machine ID 61AF76EC-1B4F-4FFB-AFC7-7004E0283682)  Failed to open attachment 'C:\Users\Ondrej\.local\share\containers\podman\machine\hyperv\podman-machine-default-amd64.vhdx'. Error: 'The file or directory is corrupted and unreadable.'.)
```

### Additional context

After we have fixed https://github.com/containers/podman-desktop/issues/9296. We have now regression in this issue, where we cannot create hyperv at all with airgapped installer.

**Comment by benoitf** [comment]
it was like that in previous versions

won't fix it in 1.13
