### ISSUE TITLE
Cannot start two Hyperv machines at the same time on Windows

### ISSUE THREAD

**Issue by xbabalov** [containers/podman-desktop#9319]
### Bug description

Trying to start a Hyperv machine while another one is running throws an error. 
![Image](https://github.com/user-attachments/assets/f50b269e-f4fe-4627-ac53-8b054fc02b7a)

### Operating system

Windows

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Create and start first hyperv machine
2. Create and start second hyperv machine
3. Assert: second machine can be created and started and connection switching dialog shows up
    Actual result: second machine is created but cannot be started (also cannot be started from resources nor from cli after creation as long as the first machine is running).

### Relevant log output

Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: unable to start "podman-machine-2": machine podman-machine-root: VM already running or starting

Something went wrong while starting container provider: Command execution failed with exit code 125: Command execution failed with exit code 125

**Comment by benoitf** [comment]
There is only using WSL where you can start multiple machines at the same time

on macOS or WIndows and Hyper-V you can't run multiple machines at the same time

**Comment by jeffmaury** [comment]
That's per upstream design so not an issue
