### ISSUE TITLE
Editing PVC yaml throws an error: data.io.ISOString is not a function

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9321]
### Bug description

I am getting error while trying to apply some changes like pvc name, when editing PVC in Kubernetes Pages.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

1. Create PVC, ie using yamls in https://github.com/odockal/podman-desktop-qe/tree/main/examples/kubernetes.
2. Apply volume, claim and pod
3. Check that pod is running which should be indicating that PVC was applied successfully
4. Edit Volume Name in PVC
5. Assert: Change is applied
Actual: `Could not apply Kubernetes Yaml: Error data.io.ISOString is not a function`

### Additional context

This happens when I try to change pvc name.
If I try to edit ie. Storage size, from 3 Gi to 4 Gi, it throws another error.

**Comment by cdrage** [comment]
> ### Bug description
> I am getting error while trying to apply some changes like pvc name, when editing PVC in Kubernetes Pages.
> 
> ### Operating system
> Windows 10
> 
> ### Installation Method
> Installer from website/GitHub releases
> 
> ### Version
> 1.13.0
> 
> ### Steps to reproduce
> 1. Create PVC, ie using yamls in https://github.com/odockal/podman-desktop-qe/tree/main/examples/kubernetes.
> 2. Apply volume, claim and pod
> 3. Check that pod is running which should be indicating that PVC was applied successfully
> 4. Edit Volume Name in PVC
> 5. Assert: Change is applied
>    Actual: `Could not apply Kubernetes Yaml: Error data.io.ISOString is not a function`
> 
> ### Relevant log output
> _No response_
> 
> ### Additional context
> This happens when I try to change pvc name. If I try to edit ie. Storage size, from 3 Gi to 4 Gi, it throws another error.

Looks to be normal, talked to @odockal on slack and editing the PVC once it's been bound, requires deleting and re-creating the PVC, I got this error:

```sh
Could not apply Kubernetes YAML: Error: HTTP-Code: 409
Message: Unsuccessful HTTP Request
Body: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"persistentvolumeclaims \\\"test123\\\" already exists\",\"reason\":\"AlreadyExists\",\"details\":{\"name\":\"test123\",\"kind\":\"persistentvolumeclaims\"},\"code\":409}\n"
Headers: {"audit-id":"436a190f-e590-493a-83b6-a0e765d3b36e","cache-control":"no-cache, private","connection":"close","content-length":"228","content-type":"application/json","date":"Thu, 10 Oct 2024 13:44:10 GMT","x-kubernetes-pf-flowschema-uid":"28c53efc-b64e-426e-a487-b56f33fbac71","x-kubernetes-pf-prioritylevel-uid":"3f6ea160-a281-426d-a279-a6dd9154d213"}
```

Unsure how `Could not apply Kubernetes Yaml: Error data.io.ISOString is not a function` was brought up however when it was fixed, and was unable to reproduce.

**Comment by odockal** [comment]
Since I am missing some context how we can actually edit the kube yaml on the fly (no everything can be edited), I am lowering the severity.

**Comment by benoitf** [comment]
I think it remembers me something about some fields managed by the kubernetes-client library that are date but the lib is not handling them well

from my memory I think it's about the creationTimestamp field that we delete so maybe it's another date field

**Comment by cdrage** [comment]
Looking back at previous messages, I am unable to reproduce anymore and this has been fixed by: https://github.com/containers/podman-desktop/pull/9267 3 weeks ago.

However, I discovered another issue here related to the Date not appearing correctly: https://github.com/containers/podman-desktop/issues/9719

Please re-open if this is still valid.
