### ISSUE TITLE
It is not possible to align using CRC and Podman Machine with HyperV when podman desktop is run in privileged mode

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9327]
### Bug description

I wanted to use CRC along the podman machine with hyperv provider. Although, If I can manipulate podman machine with hyperv, I cannot start crc  since its configuration fails: `crc should be run in a shell without administrator rights`.

If I want to operate crc, I cannot use hyperv and vice versa.

### Operating system

Windows 10, HyperV

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

**Comment by jeffmaury** [comment]
This is a known upstream issue: https://github.com/containers/podman/issues/20327

Closing as it's not Podman Desktop, feel free to re open
