### ISSUE TITLE
Cannot create machine with WSL provider via Podman Desktop without administrator rights when HyperV is enabled

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9328]
### Bug description

I have both WSL and HyperV windows features enabled.

If I want to create podman machine with WSL provider, I need to start podman desktop with admin rights. If I start podman desktop with admin rights I see WSL drop down (in light mode we have still dark theme here!). If I start without admin rights, I do not see drop down to choose provider, but there are no buttons to adjust memory and CPU so I assume it is WSL provider. But pressing create shows an error:
`Command execution failed with exit code 125. ..... hyperv machines require admin authority`

note: I have also crc running.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

**Comment by jeffmaury** [comment]
That is per design. We are think about asking user to run Podman Desktop in elevated more or wait until Podman removes the admin constraint

**Comment by odockal** [comment]
In situation when user has both WSL and HyperV we should not restrict him in creating a machine with WSL which is totally fine. I will try to elaborate more what is problem here.

Steps to reproduce
1. Enable Both WSL and HyperV on your machine, restart and also run `wsl --install --no-distribution`, restart again
2. Install Podman Desktop
3. Run Podman Desktop in elevated mode
4. Assert: When creating podman machine, user can pick up WSL or HyperV and create a machine
5. Close Podman Desktop and start again now in a standard way (without admin rights)
6. Assert: I Can create machine with WSL
Actual result: I am not able to create machine since it thinks I am trying to create hyperv.

I would like to be able to create WSL machine when the feature is enabled on the system and I do not run podman desktop as admin, while having HyperV enabled as well. 

We could basically have the dropdown available always, just you cannot choose hyperv (or there is only wsl and the dropdown is disabled) when it is not run in admin mode. Assumig both features are enabled.

**Comment by jeffmaury** [comment]
> In situation when user has both WSL and HyperV we should not restrict him in creating a machine with WSL which is totally fine. I will try to elaborate more what is problem here.
> 
> Steps to reproduce
> 
>     1. Enable Both WSL and HyperV on your machine, restart and also run `wsl --install --no-distribution`, restart again
> 
>     2. Install Podman Desktop
> 
>     3. Run Podman Desktop in elevated mode
> 
>     4. Assert: When creating podman machine, user can pick up WSL or HyperV and create a machine
> 
>     5. Close Podman Desktop and start again now in a standard way (without admin rights)
> 
>     6. Assert: I Can create machine with WSL
>        Actual result: I am not able to create machine since it thinks I am trying to create hyperv.
> 
> 
> I would like to be able to create WSL machine when the feature is enabled on the system and I do not run podman desktop as admin, while having HyperV enabled as well.
> 
> We could basically have the dropdown available always, just you cannot choose hyperv (or there is only wsl and the dropdown is disabled) when it is not run in admin mode. Assumig both features are enabled.

That is not possible per Podman design. So do you reopened it to keep track ?

**Comment by odockal** [comment]
If I want to create podman machine with podman desktop and I have both WSL and HyperV, I have to run Podman Desktop with admin rights.

If I try the cli we are copying the behavior of podman in podman desktop.
Opening powershell without admin rights and without settings `CONTAINERS_MACHINE_PROVIDER` env. var. says the same: `HyperV requires admin authority`.
But when I set `CONTAINERS_MACHINE_PROVIDER`='wsl' I can create the machine. that is something we should consider in Create Machine Dialog as well. We should offer user that option, imho.

**Comment by jeffmaury** [comment]
> If I want to create podman machine with podman desktop and I have both WSL and HyperV, I have to run Podman Desktop with admin rights.
> 
> If I try the cli we are copying the behavior of podman in podman desktop. Opening powershell without admin rights and without settings `CONTAINERS_MACHINE_PROVIDER` env. var. says the same: `HyperV requires admin authority`. But when I set `CONTAINERS_MACHINE_PROVIDER`='wsl' I can create the machine. that is something we should consider in Create Machine Dialog as well. We should offer user that option, imho.

What is the default configured in containers.conf. I cannot reproduce on mymachine.

**Comment by jeffmaury** [comment]
> > If I want to create podman machine with podman desktop and I have both WSL and HyperV, I have to run Podman Desktop with admin rights.
> > If I try the cli we are copying the behavior of podman in podman desktop. Opening powershell without admin rights and without settings `CONTAINERS_MACHINE_PROVIDER` env. var. says the same: `HyperV requires admin authority`. But when I set `CONTAINERS_MACHINE_PROVIDER`='wsl' I can create the machine. that is something we should consider in Create Machine Dialog as well. We should offer user that option, imho.
> 
> What is the default configured in containers.conf. I cannot reproduce on mymachine.

FTR Podman Dekstop ignores the provider configured in containers.conf. If WSL is enabled then it will set CONTAINERS_MACHINE_PROVIDER to wsl before launching the CLI. Same for HyperV.
