### ISSUE TITLE
Should the ui library component be allowed to use window event system ?

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9338]
### Is your enhancement related to a problem? Please describe

Since https://github.com/containers/podman-desktop/pull/8553 we added a store in the ui library that gets updated by window events.

https://github.com/containers/podman-desktop/blob/4d5e0a09f6770a2295bb975725b0e4d35acff03b/packages/ui/src/lib/tooltip/tooltip-store.ts#L26-L32

### Describe the solution you'd like

Here we put the ui library responsible of hidding the tooltip based on external events `tooltip-show` and `tooltip-hide`. 

We probably could add an `hideToolTip: boolean` props to the ToolTip component ?

**Comment by benoitf** [comment]
I think yes it's allowed
