### ISSUE TITLE
podman desktop pegging kube-apiserver CPU w/kind

### ISSUE THREAD

**Issue by dchapman992000** [containers/podman-desktop#9348]
### Bug description

After upgrading podman desktop and podman today, about 20 minutes later I noticed my laptop fans kick on.  I tracked it down to kube-apiserver.  I thought it was something I did.  I recreated the environment with kind and it was fine for 10-15 minutes and happened again.

I think created a vanilla control plan with kind in podman and let it sit and it ramped up too.

I was able to get the audit logs enabled and lots of these.  Because of the IP I suspect its the GUI(podman desktop) going haywire after a period of time and some combination of clicking in the UI.  Its spewing 10s of these lines a second constantly.  It looks like its setting up watchers constantly for every resource over and over again.

{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse","auditID":"724d38ef-5289-42a3-b7bb-0ffa8b06cb1d","stage":"ResponseStarted","requestURI":"/api/v1/namespaces/default/pods?watch=true\u0026resourceVersion=424","verb":"watch","user":{"username":"kubernetes-admin","groups":["kubeadm:cluster-admins","system:authenticated"]},"sourceIPs":["192.168.127.1"],"userAgent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","objectRef":{"resource":"pods","namespace":"default","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2024-10-11T20:36:00.438589Z","stageTimestamp":"2024-10-11T20:36:00.445711Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"kubeadm:cluster-admins\" of ClusterRole \"cluster-admin\" to Group \"kubeadm:cluster-admins\""}}

If I start podman and my kind control plane container from CLI and bypass GUI, I am unable to reproduce the issue and kube-apiserver stays within 5-10%.

I put 1.13.0 but its 1.13.2 because .2 doesn't exist in the version tag yet.

### Operating system

MacOS 15.0.1 (24A348)

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

1) Start podman desktop.
2) kind create cluster
3) Click through podman desktop UI
4) wait 5-20 minutes
5) watch for kube-apiserver spiking to 100% cpu

### Relevant log output

main ↪️ Trying to watch deployments on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 87s. FetchError: request to https://127.0.0.1:50653/apis/apps/v1/namespaces/default/deployments?watch=true&resourceVersion=20530 failed, reason: socket hang up)
main ↪️ Trying to watch persistentvolumeclaims on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 73s. FetchError: request to https://127.0.0.1:50653/api/v1/namespaces/default/persistentvolumeclaims?watch=true&resourceVersion=20530 failed, reason: Client network socket disconnected before secure TLS connection was established)
main ↪️ Trying to watch secrets on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 81s. FetchError: request to https://127.0.0.1:50653/api/v1/namespaces/default/secrets?watch=true&resourceVersion=20530 failed, reason: socket hang up)
main ↪️ Trying to watch pods on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 77s. FetchError: request to https://127.0.0.1:50653/api/v1/namespaces/default/pods?watch=true&resourceVersion=20530 failed, reason: socket hang up)
main ↪️ Trying to watch ingresses on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 84s. FetchError: request to https://127.0.0.1:50653/apis/networking.k8s.io/v1/namespaces/default/ingresses?watch=true&resourceVersion=20530 failed, reason: Client network socket disconnected before secure TLS connection was established)
main ↪️ Trying to watch nodes on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 87s. FetchError: request to https://127.0.0.1:50653/api/v1/nodes?watch=true&resourceVersion=20530 failed, reason: Client network socket disconnected before secure TLS connection was established)
main ↪️ Trying to watch configmaps on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 86s. FetchError: request to https://127.0.0.1:50653/api/v1/namespaces/default/configmaps?watch=true&resourceVersion=20530 failed, reason: Client network socket disconnected before secure TLS connection was established)
main ↪️ Trying to watch services on the kubernetes context named "kind-woohoosvcs" but got a connection refused, retrying the connection in 84s. FetchError: request to https://127.0.0.1:50653/api/v1/namespaces/default/services?watch=true&resourceVersion=20530 failed, reason: Client network socket disconnected before secure TLS connection was established)
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]

**Comment by dchapman992000** [comment]
In the UI, I think its the fact that it doesn't think it can reach the kind cluster (but it can).  Somehow the watch alls are making it through.

![Image](https://github.com/user-attachments/assets/84e11b7d-1196-4959-9684-9b6f6dc63793)

![Image](https://github.com/user-attachments/assets/c63e0309-1c17-4504-92b3-767b315aa8de)

![Image](https://github.com/user-attachments/assets/72c84eb1-9c07-465d-a798-2078376bec0e)

**Comment by feloy** [comment]
Thanks for creating the issue and for the complete report.

Are you seeing these errors and the 10s of watch calls in the audit as soon as you start the UI, or only after a few minutes?

**Comment by dchapman992000** [comment]
Sometimes its sooner than other times.  Its usually not immediate.  Its usually 5-20 minutes later but sometimes sooner than 60 seconds.  Clicking through the Kubernetes section in Podman Desktop seems to expedite it.  Its as if it thinks the watch requests are failing but they're making it there so it keeps calling over and over again.

**Comment by feloy** [comment]
It can be confusing, as the UI uses different watchers for listing the pods int the pods page (list of pods in screenshot 3) and for detecting if the cluster is reachable (screenshots 1 and 2, and reachable state in screenshot 3). 

It seems that the watchers for the connectivity are failing, when the ones for listing the pods are working. I'll need to make some investigation to see why

**Comment by feloy** [comment]
If you go to the Kubernetes contexts page (screenshot 2), as soon as you start the UI, are you seeing the context reachable at some point, or always unreachable?

**Comment by feloy** [comment]
Are you restarting Podman desktop completely?
(please note that on mac, closing the UI window will not stop it, you will need to quit it by right-clicking the Podman desktop icon in the tray, and select Quit)

**Comment by dchapman992000** [comment]
> Are you restarting Podman desktop completely? (please note that on mac, closing the UI window will not stop it, you will need to quit it by right-clicking the Podman desktop icon in the tray, and select Quit)

Yes, doing a quit on the tray each time.

**Comment by dchapman992000** [comment]
> If you go to the Kubernetes contexts page (screenshot 2), as soon as you start the UI, are you seeing the context reachable at some point, or always unreachable?

I would have sworn it was unreachable from the start previously but this time its reachable upon start.  It was all shut down for about 20 mins this time and when I started everything up, it showed connected immediately.  I'll leave it running to see if the issue recurrs.  Should know in another 5-20 minutes :-)  Hopefully its just a fluke local issue.

**Comment by dchapman992000** [comment]
Nearly 30 mins now and nothing.  We'll see it it comes back.  It was odd because I had upgraded and then some time later it started.  Maybe the old podman desktop wasn't fully quit.  I'll definitely report back if it happens again and try to get better details.

**Comment by dchapman992000** [comment]
It just happened again, this time I'd left podman desktop running in the background but my kind container was shut down.  I started up the kind container and it immediately started and showed unreachable and kube-apiserver started spiking.  I shutdown the podman machine and then completely closed out of podman desktop and got back in and it started working again as expected without cpu spike.

Perhaps previously I wasn't actually closing out of podman desktop.

**Comment by feloy** [comment]
Ok, it seems the same thing as https://github.com/containers/podman-desktop/issues/9156, except that we didn't see the CPU spike.

**Comment by dchapman992000** [comment]
Yes, it does seem related if not the same issue.  I wonder if its just because I have an older laptop.  I only noticed the CPU spiking because my cooling fan went crazy.  Tracing it down I saw kube-apiserver eating up 90-100% of a core.  If the fan hadn't spun up really high, I would have had no idea it caused the cpu spike

**Comment by feloy** [comment]
@dcatwoohoo ok, I can reproduce the problem, and can see the api of kind spammed with watch calls after the clusters is stopped then restarted. I'll investigate on how to fix the issue.
Thanks again for you report which is very valuable
