### ISSUE TITLE
When trying to build a container from a Containerfile, lots of issues.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#935]
### Bug description

First it prompts for a path.
1. The prompt window shows up behind the podman-desktop, meaning I have to bring it forward.
2. When I tell the tool that the Containerfile is in /tmp, it will not select the directory, it is forcing me to choose a file, I guess this is choosing /tmp/Containerfile? In Podman build, we just choose directories and rely on the Containerfile or Dockerfile to be in that path, you can actually have a separage context directory from the Dockerfile.
3. I think this should be in the image screen not the container screen, since you build image from Containerfiles and Dockerfiles, not containers.

### Operating system

Linux

### Version

0.9.1

**Comment by mairin** [comment]
Another suggestion would be to autocomplete / have a history for what containerfiles you've entered into the Containerfile path field before. Right now I'm troubleshooting some issues with a Containerfile I'm working with, so the general workflow I'm following in a bit of a loop is:

- (text editor) Edit Containerfile
- (Podman Desktop) Build Image from Containerfile
- Select file from file browser in the Containerfile path field
- Build
- Run container, test to see if issue still present, oh it is, go back to containerfile and edit it, and repeat.

It feels like a lot of work (yes, what a charmed life 😆 ) to have to select the Containerfile from the system file chooser every time I fill out the build form (although it does remember and places me in the last directory I chose a Containerfile from which makes it a little easier.) It would be nice if it had an autoselector maybe in reverse chronological order of the last few Containerfiles I built that I could just pick from... something like this:

[Screencast_29.05.23_16:42:51.webm](https://github.com/containers/podman-desktop/assets/799683/39809c5a-3f6d-4bae-86d3-3249db885685)

(static mockups below)
![Screenshot from 2023-05-29 16-44-11](https://github.com/containers/podman-desktop/assets/799683/82252f8d-04b1-4c93-b11a-7296ca822d62)
![Screenshot from 2023-05-29 16-44-01](https://github.com/containers/podman-desktop/assets/799683/1381c8e3-455b-4fa5-8621-9b3c7fb7503a)

(penpot: https://design.penpot.app/#/workspace/88d87192-d205-8007-8002-9588f748f1b7/88d87192-d205-8007-8002-958902199140?page-id=88d87192-d205-8007-8002-95890219d016&layout=layers )
