### ISSUE TITLE
Dashboard panel tells to update when there is no update required

### ISSUE THREAD

**Issue by gian1200** [containers/podman-desktop#9352]
### Bug description

![Image](https://github.com/user-attachments/assets/02326016-026f-4551-882a-654c072683fa)

![Image](https://github.com/user-attachments/assets/94ebfbf8-6806-4e53-a717-b424bab8e038)

![Image](https://github.com/user-attachments/assets/865858b6-4183-4249-aa0f-5ec107ebba96)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.2

### Additional context

When clicking the version below, it works as expected
![Image](https://github.com/user-attachments/assets/570d1cd2-a0b5-4270-a015-0b82c580dc50)

**Comment by SoniaSandler** [comment]
@gian1200 try closing/quitting Podman Desktop and reopening it. The update button on the Dashboard page should disappear, but since our auto update check is every 12 hours, it might take it some time to adjust to no update.

**Comment by gian1200** [comment]
Thanks for answering! I did exactly that yesterday and it worked. 

However I'd be nice to have it fixed. Good to know that it's in the backlog 😃 

A few suggestions:
- Given that I manually trigger the update validation, the dashboard could use that information, too (instead of relying only on the auto update)
- The message/button could be omitted if recommended version equals current version 😅
