### ISSUE TITLE
Can't install podman on Windows

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#936]
### Bug description

While testing https://github.com/containers/podman-desktop/pull/908 I can't install podman. Got this error message:

![image](https://user-images.githubusercontent.com/695993/204751612-7cd8d60a-0152-42eb-8509-8e8e887f4c7b.png)

### Operating system

Win10 Pro

### Version

next (development version)

### Steps to reproduce

1. Uninstall podman
2. Run podman desktop from https://github.com/containers/podman-desktop/suites/9557685407/artifacts/454842098
3. Install podman from UI

**Comment by benoitf** [comment]
There was a glitch in the SHASUM file on podman release making the file unavailable in Podman Desktop
It has been fixed on podman side but there was no commit on podman-desktop so no new releases occured.
On the next commit being merged issue should be solved.
And to prevent that in the future there is https://github.com/containers/podman-desktop/pull/931

**Comment by benoitf** [comment]
Using https://github.com/containers/podman-desktop/releases/tag/v0.0.202211301024-e0d7096 should be ok now
