### ISSUE TITLE
podman wants to update to same version

### ISSUE THREAD

**Issue by maxandersen** [containers/podman-desktop#9365]
### Bug description

![Image](https://github.com/user-attachments/assets/c5b98f03-72ec-47db-a82b-62d81389c3ad)

### Operating system

macos silicon

### Installation Method

None

### Version

1.13.0

### Steps to reproduce

got notice about update availalbe - ran it and now podman desktop shows up asking to update v.1.13.2 to v.1.13.2 ...and when clicking update it reports error and to look in dev console.

under thebell icon I have:
`Unable to download v1.13.2 update: Error: Please check update first`

**Comment by SoniaSandler** [comment]
@maxandersen try closing/quitting Podman Desktop and reopening it. The update button on the Dashboard page should disappear, but since our auto update check is every 12 hours, it might take it some time to adjust to no update.

**Comment by maxandersen** [comment]
@SoniaSandler sure - I  can ignore the dialog - just reporting that somehow podman wants to update to same version so some version comparison seems off?
