### ISSUE TITLE
After upgrading to v1.13.2, podman extension remains in Activating state and dashboard does not display podman status

### ISSUE THREAD

**Issue by kenbarnettpt** [containers/podman-desktop#9370]
### Bug description

After upgrading from Podman Desktop v1.12.x x64 on Windows 10 to Podman Desktop v.1.13.2 x64 and creating a podman machine, Podman Desktop's podman extension does not leave the Activating status.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

(from working v1.12.x version)

From PowerShell

```
podman machine stop
podman machine rm
wsl --shutdown
wsl --unregister podman-machine-default
```

Uninstall Podman Desktop via control panel
Uninstall podman v4.x
Install podman v5.2.4 using https://github.com/containers/podman/releases/download/v5.2.4/podman-5.2.4-setup.exe installer
Install Podman Desktop v1.13.2 x64

From Powershell

```
podman machine init
podman machine set --rootful     ## For Kind (bug occurs with rootful=false as well)
podman machine start
```

Verify podman running state via **_podman info_**
Reboot

Launch Podman Desktop

- Note that dashboard does not show podman status
- In the Extensions menu, note that the podman extension is in the Activating state (and does not leave this state during a 60 minute period)

### Relevant log output

PS C:\podman> podman info
host:
  arch: amd64
  buildahVersion: 1.37.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.12-2.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.82
    systemPercent: 0.1
    userPercent: 0.08
  cpus: 24
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "40"
  eventLogger: journald
  freeLocks: 2046
  hostname: dinm5CG3292TKX
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.153.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 15780728832
  memTotal: 16562806784
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.17-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc40.x86_64
    version: |
      pasta 0^20240906.g6b38f07-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 0h 4m 37.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 5112844288
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.2.3
  Built: 1727136000
  BuiltTime: Mon Sep 23 17:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.3

**Comment by symplrdudley** [comment]
I also experience this. Any one else experiencing this should emoji the initial post.

**Comment by Vitaly-Work** [comment]
Same problem, and after some time Podman extension is in a Failed state. 
On error tab:
```
Error: Extension podman-desktop.podman activation timed out after 20 seconds
Stack trace:
Error: Extension podman-desktop.podman activation timed out after 20 seconds
    at Timeout._onTimeout (C:\Users\Vitalii_Adoievtsev\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:151:67168)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```

**Comment by axel7083** [comment]
Hey @symplrdudley and @kenbarnettpt thanks for reporting the problem, a few question:

- Does restarting podman-desktop clear the issue ? Or is it something always happening ? 
- If this is always happening, could you try restarting your PC, we have tons of problem with the WSL, and sometime only restarting the machine solve them.
- Are you able to use podman from the CLI, like `podman run hello-world` ?
- Do you have multiple connections registered ? `podman system connection ls` ?

## Collecting logs

If the problems occurs again, could you provide us the logs, here is a step by step

1. Inside the status bar click on the lamp icon

![Image](https://github.com/user-attachments/assets/f757ea1e-4d4c-44ee-914c-b8ac01567f9d)

2. Go to the Gather Logs tab

![Image](https://github.com/user-attachments/assets/2b2e3ca5-6438-469f-8080-618067a004a8)

3. Collect logs when the problem is occurring
 
![Image](https://github.com/user-attachments/assets/772a2b90-7993-4626-b805-552de8df29fd)

**Comment by symplrdudley** [comment]
[podman-desktop-20241017080643.zip](https://github.com/user-attachments/files/17412947/podman-desktop-20241017080643.zip)

**Comment by axel7083** [comment]
In the logs, we have the following lines which are a important

```
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
...
log : main ↪️ Activating extension podman-desktop.podman failed error:Error: Extension podman-desktop.podman activation timed out after 20 seconds
...
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
```

There is a possibility the timeout is too short, and the extension enter a failed state,

![Image](https://github.com/user-attachments/assets/12ed52bd-f1e2-43f2-b1b7-04fae6379c70)

Could you try increasing the timeout (let's put something enormous for the sake for testing like 120), and restart podman-desktop ?

**Comment by kenbarnettpt** [comment]
@axel7083 After increasing the timeout to 100 seconds (the maximum allowable), the problem is resolved for me.

**Comment by axel7083** [comment]
> [@axel7083](https://github.com/axel7083) After increasing the timeout to 100 seconds (the maximum allowable), the problem is resolved for me.

Thanks for the feedback, we are aware of potential performance issue. Closing this issue as resolved.
