### ISSUE TITLE
Proxy Settings stucked in "System" mode

### ISSUE THREAD

**Issue by rv2931** [containers/podman-desktop#9379]
### Bug description

I have installed tje 1.13.2 podman desktop version with 5.1.1 podman version (not the latest) and I use my machine sometimes with VPN&Proxy sometimes without
I have to switch of Proxy States. With new versino the Proxy Settings pannel has changed. As previous version of Desktop (1.12) seems to detect proxy configuration from OS I tried to switch to "System" Proxy settings but now it is impossible de switch back to "Manual" or "Disabled".
I got to settings, proxy settings, switch to manual for example, graphically the menu shows "manual" but no widget to enter proxy settings appears and if close settings and come back, "system" is still selected

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.2

### Steps to reproduce

- Go to settings
- Go to "Proxy"
- Set Proxy setting to "System"
- Close "Settings"
- Maybe you have to restart padman
- Go to settings
- Go to "Proxy"
- Set Proxy setting to "Manual"
- You can see that nothing change in the panel, no widget added to enter proxy settings
- Close settings pannel
- Go to settings
- Go to "Proxy"
- The settings is still "System" instead of manual

### Additional context

![Image](https://github.com/user-attachments/assets/0077223f-5497-4bf0-956b-02df44e41aca)

**Comment by FrCornaire** [comment]
Hello
After some digging, found the culprit

The TLDR is a value not being updated ,hence the app looking "stuck"

A quick fix would be to update your podman-desktop settings at 

`%userprofile%\.local\share\containers\podman-desktop\configuration\settings.json`

and add the value proxy.enabled: 

```json
{
... //Your current settings

"proxy.enabled" : 1
}
```

Made a PR at #9442  for a fix
