### ISSUE TITLE
Kubernetes Welcome page Phase 2

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9386]
### Epic domain

During [this Epic](https://github.com/containers/podman-desktop/issues/8825) we created the basic shell for Welcome page for the Kubernetes but we did not have the UX design yet. This Epic is to continue that work and to match the page to the [UX design](https://github.com/containers/podman-desktop/issues/9263).

**Comment by slemeur** [comment]
Should we think about telemetry for this before closing the epic?

**Comment by Firewall** [comment]
Yea that makes sense @slemeur

**Comment by Firewall** [comment]
created a task for that https://github.com/podman-desktop/podman-desktop/issues/10204
