### ISSUE TITLE
podman initialization fails when behind corporate proxy

### ISSUE THREAD

**Issue by eidottermihi** [containers/podman-desktop#939]
### Bug description

After installing Podman Desktop and configuring my corporate proxy in Settings -> Proxy:

![grafik](https://user-images.githubusercontent.com/2780736/204805581-33237b9f-d2db-4cd5-bb99-0be1fab17679.png)

"Initialize podman" fails:

![grafik](https://user-images.githubusercontent.com/2780736/204805095-69ca4738-7e71-4ddc-abad-7333938557d0.png)

Error: Error: head request failed: https://github.com/containers/podman-wsl-fedora/releases/latest/download/rootfs.tar.xz: Head "https://github.com/containers/podman-wsl-fedora/releases/latest/download/rootfs.tar.xz": dial tcp: lookup github.com: no such host

This looks to me as the configured proxy is not used.

### Operating system

Windows 21H2

### Version

0.9.1

**Comment by benoitf** [comment]
Thanks for the report.

I think we're missing proxy information :-(

Is it possible to run on a powershell on your windows:
```
$env:http_proxy="<corporate-proxy"
$env:https_proxy="<corporate-proxy"
podman machine init
```

**Comment by benoitf** [comment]
also, are you able to check that the proxy settings is correct at `%HOME\.config\containers\containers.conf`

thanks @eidottermihi 👍

**Comment by eidottermihi** [comment]
@benoitf manually initializing podman with the given commands works:

```powershell
PS C:\Users\michael.prankl> $env:http_proxy="http://<corporate-proxy>"
PS C:\Users\michael.prankl> $env:https_proxy="http://<corporate-proxy>"
PS C:\Users\michael.prankl> podman machine init
Downloading VM image: fedora-podman-v36.0.86.tar.xz: done
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Configuring system...
Generating public/private ed25519 key pair.
Your identification has been saved in podman-machine-default
Your public key has been saved in podman-machine-default.pub
The key fingerprint is:
SHA256:kChnFacouyX5Dq/uhqFjAcBgEg0ij/Hzm1lPOiy4mLQ root@nbo00327808
The key's randomart image is:
+--[ED25519 256]--+
|@=    o..        |
|**.  + +         |
|o * = +          |
|.  X   .         |
|. + o . S        |
|.. * * +         |
|.+= * + .        |
|=+o= . .         |
|+E=.o            |
+----[SHA256]-----+
Machine init complete
To start your machine run:

        podman machine start
```

After that "Run podman" from Podman Desktop works flawlessly.

**Comment by benoitf** [comment]
thanks a lot, so we need to propagate proxy on the init part, probably it's not reading from the configuration

**Comment by eidottermihi** [comment]
> also, are you able to check that the proxy settings is correct at `%HOME\.config\containers\containers.conf`

Actually, there is no file called containers.conf in that directory. Should it be written when I'm configuring the proxy through the Podman Desktop UI?

**Comment by benoitf** [comment]
ah sorry, on Windows it's in `%HOME%\AppData\Roaming\containers` directory

**Comment by benoitf** [comment]
@eidottermihi are you able to test https://github.com/containers/podman-desktop/actions/runs/3584419671 from Pull Request https://github.com/containers/podman-desktop/pull/940

(go to `Artifacts` then windows and then launch the windows binary)

**Comment by benoitf** [comment]
On my side it worked, proxy is being called

**Comment by eidottermihi** [comment]
@benoitf thanks, I tried the version from #940 - and can confirm the fix!

**Comment by benoitf** [comment]
Thanks @eidottermihi !
