### ISSUE TITLE
update dialog contains button with long description making it unreadable without scrolling

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#9393]
### Is your enhancement related to a problem? Please describe

![Image](https://github.com/user-attachments/assets/ec042ff9-2114-4fb8-92f6-108b5905a526)

### Describe the solution you'd like

I should be able to see 4 button's text without scrolling

so maybe reduce "View Release Notes" or "Do not show again"

"View Release Notes" → "Release Notes" or "What's New"
"Do not show again" → "Don't Show" or "Hide Next Time"

or any other proposal

**Comment by kattekrab** [comment]
#9798 Duplicate
