### ISSUE TITLE
Move Help page content to a Dropdown

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9407]
### Is your enhancement related to a problem? Please describe

Part of [Epic](https://github.com/containers/podman-desktop/issues/9077), there are a lot useful links hidden away in the help page. We want to give quicker acess to those resources by moving them into a context menu instead. 

### Describe the solution you'd like

Keep only 1 icon and move all the options into a menu. As it is a menu it also allows us to add a text label which will help our users understand what the icons mean. 

Check the [Epic](https://github.com/containers/podman-desktop/issues/9077) to see what the content of the help menu should be.

**Comment by dgolovin** [comment]
@Firewall what UI element should I use for implementation? It could be native menu or DropDownMenu from podman UI package. I assume I should use latter because it is is also used in authentication buddy item.

**Comment by Firewall** [comment]
If we are already using one of them in the other navigation(authentication buddy) I would use the same one indeed to stay consistent.
