### ISSUE TITLE
bug(layer explorer): tree issue

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9410]
### Bug description

Today I was using the file explorer to find why the instructlab image is so large, and I found a visual glitch with the tree explorer when we reach some depth.

https://github.com/user-attachments/assets/bb256506-29f1-4c70-8072-26c95821389a

### Operating system

fedora 40

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. reach any depth above 4

### Additional context

The problem is coming from the following line

https://github.com/containers/podman-desktop/blob/8f80bf47418f99ba118d8c865da5a13594de21a1/packages/renderer/src/lib/image/FilesystemLayerView.svelte#L69

and

https://github.com/containers/podman-desktop/blob/8f80bf47418f99ba118d8c865da5a13594de21a1/packages/renderer/src/lib/image/FilesystemLayerView.svelte#L80

Using `ml-${margin}` will not work, because tailwindcss do not create value when they are not available at compile time, therefore for `margin === 10`, it do not create the corresponding class. Leading to css not applied

**Comment by feloy** [comment]
Thanks for the explanation about tailwind, I was not understanding why it was not working.

The problem is also raised in https://github.com/containers/podman-desktop-extension-layers-explorer/issues/82, not sure which one to keep

**Comment by axel7083** [comment]
This is a problem on the code in podman-desktop, not the responsability of the extension, we can close the one on the explorer layers

**Comment by benoitf** [comment]
adding unplanned
