### ISSUE TITLE
Tasks on status bar should show progress

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#9418]
### Is your enhancement related to a problem? Please describe

The new task progress on the status bar is awesome (thanks @axel7083!) but it doesn't show progress for long running tasks.

https://github.com/user-attachments/assets/24aa19a7-349d-46d7-87d7-a797488d8d6a

### Describe the solution you'd like

Tasks that have incremental progress (e.g. 7%, 10%, 25%...) show up correctly in the task manager, but on the status bar they are indeterminate/animated. The incremental progress should show up correctly in the status bar.

**Comment by axel7083** [comment]
assigning myself for next sprint
