### ISSUE TITLE
Certificate error when installing Compose

### ISSUE THREAD

**Issue by josealbertocoronado** [containers/podman-desktop#9440]
### Bug description

Hi. 
Apologies if this is a duplicate, after some search I can't find any entry with the same issue.

I'm getting an error when installing Compose due to my company certificate
The exact error is `"HttpError: Unable to get local issuer certificate"`.

This is where I get it: 
![Image](https://github.com/user-attachments/assets/be2f85a1-c1b3-49bf-a48d-c62269f50381)

Please note I've already installed the certificate inside the podman machine following these steps: https://podman-desktop.io/docs/podman/adding-certificates-to-a-podman-machine. Which works. I'm able to pull images.

So my issue is purely when installing Compose in Podman Desktop.
Thanks in advance.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

1. Install Podman Desktop (clean laptop, nothing else installed related to Docker)
2. Create a podman machine
3. Install certificate inside podman machine. That allows to pull images.
4. Try to run Compose. It throws this error:
        * exec: "docker-compose": executable file not found in %PATH%
        * exec: "podman-compose": executable file not found in %PATH%
5. Try to install Compose via Podman Desktop.

**Comment by benoitf** [comment]
hello @josealbertocoronado do you see some errors in the logs

could you click on the light bulb in the status bar then the logs tab

and when you try to install compose (to see the call that is missing the certificate)

also you confirm that the certificate is installed on your local computer (not only inside the machine)

**Comment by josealbertocoronado** [comment]
Hi @benoitf , thanks for answering.

Yeah, the certificate is installed in my machine too.
Checking logs I can't see anything related to it. I've just run it again and this is what I see in logs (nothing related apparently):
![Image](https://github.com/user-attachments/assets/c5a989f2-5c52-447e-b1e9-17f53c6b7caa)

Tbh, I think it can be simply my company is blocking the http call to the compose url, however I would need to find out what that url is so I can ask them to whitelist it. Any idea how I can find it? 
Is it maybe this url? https://github.com/docker/compose/releases.
That's where I'm pointed to when I follow instructions to install compose manually from this doc (at the very bottom): https://podman-desktop.io/docs/compose/setting-up-compose

**Comment by ScrewTSW** [comment]
@josealbertocoronado Hello. It seems like this bug is not directly related to Podman Desktop.
I have two questions I'd like to ask you:
* Have you tried to manually download and install compose on your system? If yes, what was the outcome?
* Did you try to ask your company IT admins to whitelist the docker compose releases URL?

I'm afraid there's not much more we can do for you without having answers for these two questions.

**Comment by josealbertocoronado** [comment]
Yeah, talking to IT team and indeed looks like something definitely our end. I get the same when downloading directly from docker compose github repo.

Apologies for the hassle. Feel free to close this.
