### ISSUE TITLE
Failed to resolve entry for package "@podman-desktop/ui-svelte".

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9441]
### Bug description

When running `pnpm watch` on the main, I am spam with errors (podman desktop still boot and works fine)

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. checkout main
2. pnpm watch

### Relevant log output

```
X [ERROR] Failed to resolve entry for package "@podman-desktop/ui-svelte". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

  The plugin "vite:dep-scan" was triggered by this import

    script:C:/Users/axels/Documents/github/redhat/podman-desktop/packages/renderer/src/lib/preferences/PreferencesRendering.svelte?id=0:68:7:
      68 │ import '@podman-desktop/ui-svelte'

```

**Comment by axel7083** [comment]
Seems to only happen if I delete the `packages/**/dist` folders, then pnpm watch

**Comment by deboer-tim** [comment]
Not sure I'm missing something - shouldn't there be a:
  1.5 `pnpm install`
and does that help?

**Comment by axel7083** [comment]
Closing as I haven't see it in a while
