### ISSUE TITLE
View release notes button leads to 404 on Mac OS

### ISSUE THREAD

**Issue by hasys** [containers/podman-desktop#9447]
### Bug description

Hello I found a small UI bug. When I click on View release notes  button in this dialogue (see picture) I navigated to https://github.com/containers/podman-desktop/releases/tag/vv1.13.2 which is 404. Looks like there is vv1.13.2 instead of v1.13.2 . When I remove the second v I can see the log

![Image](https://github.com/user-attachments/assets/7f7a4ac9-9c7d-407e-b6e0-5fa8d7c88405)

### Operating system

Mac OS

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

I see a notification about a new release when I click Update button I can see the dialog with links to 404.

![Image](https://github.com/user-attachments/assets/0c105f8b-8198-4ddc-a523-ef61c31a4ca7)

**Comment by odockal** [comment]
@SoniaSandler hey, I have added this issue into this sprint if you do not mind. Feel free to adjust accordingly.
