### ISSUE TITLE
Review kubernetesExecIntoContainer telemetry

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#9467]
### Is your enhancement related to a problem? Please describe

The kubernetesExecIntoContainer event is triggered a lot, but it tends to be very sporadic and looking at the unique users it's relatively low compared to similar events.

### Describe the solution you'd like

Investigate a little deeper. I noticed that the event is triggered every time you go to the Terminal tab on a pod, I think the volume is primarily caused by users switching in and out of the tab. We could trigger it only the first time you enter (or at least first time for each new pod), only send it once per instance, etc.

**Comment by jeffmaury** [comment]
Analysing the source code and the situation is even worse: each time the tab is selected, a new shell is created into the container. Probably need to cache at the Kubernetes client level
