### ISSUE TITLE
Creating a kind cluster in e2e tests is unstable on CI on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9483]
### Bug description

Creating a kind cluster e2e test/code seems to be not working properly resulting in some e2e tests to be skipped.

ref: https://github.com/containers/podman-desktop-e2e/actions/runs/11432503318

### Operating system

Windows

### Installation Method

None

### Version

next (development version)

**Comment by amisskii** [comment]
This issue is related to https://github.com/containers/podman-desktop/issues/9490
