### ISSUE TITLE
Add `pulling an image` to the task manager

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9484]
### Is your enhancement related to a problem? Please describe

When you pull an image you can see the progress at the top of the image list screen however it can sometimes take a while. If you switch to another page you don't really see the progress anymore. 

### Describe the solution you'd like

Add the image pulling progress to the task manager. That way you can see the progress everywhere.

**Comment by benoitf** [comment]
I think it's a dup of https://github.com/containers/podman-desktop/issues/5810 (being also dup of others)

**Comment by Firewall** [comment]
For sure, should have searched first!
