### ISSUE TITLE
Provider Type button starts Kind cluster creation instead of dropdown selection

### ISSUE THREAD

**Issue by amisskii** [containers/podman-desktop#9490]
### Bug description

The Provider Type combobox on the Kind Cluster Creation page has been changed from a `<select>` HTML element to a `<button>`. Currently, when clicking the button, it triggers the Kind cluster creation process instead of providing a dropdown to select the provider type. 

This change could potentially affect other pages that share the same mock or component used in this page. 

https://github.com/user-attachments/assets/02e6e1e8-30bd-4ff2-ae89-676e4658f02d

### Operating system

Windows 10/11, Fedora 40

### Installation Method

None

### Version

next (development version)

**Comment by deboer-tim** [comment]
Took a quick look, oddly looks like opening the dropdown is triggering the form submission. Will investigate further.
