### ISSUE TITLE
Silent / Unattended Install for Windows

### ISSUE THREAD

**Issue by eidottermihi** [containers/podman-desktop#950]
### Is your enhancement related to a problem? Please describe

To provide Podman Desktop in a managed Windows client environment (like in most corporate environments), it is necessary that Podman Desktop can be installed in an "unattended" fashion.

### Describe the solution you'd like

A way to install Podman Desktop from CLI in an unattended fashion.

### Additional context

Docker Desktop provides a feature like this, it is documented in the docs: https://docs.docker.com/desktop/install/windows-install/#install-from-the-command-line

**Comment by eidottermihi** [comment]
probably relates to epic #302

**Comment by benoitf** [comment]
@eidottermihi you mean a silent installation ?
you could give `/S` flag to the installer

**Comment by eidottermihi** [comment]
> @eidottermihi you mean a silent installation ? you could give `/S` flag to the installer

yes, silent/unattended install. Then I will give it a try with `/S`!

Are there any more parameters / flags which can be passed to the installer?

**Comment by benoitf** [comment]
I think these one as well:
https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon

**Comment by eidottermihi** [comment]
@benoitf thanks, I've tried wit `/S` and the installer just shows a progress dialog but finishes installation of Podman Desktop successfully without user interaction.

Is there a way to directly install podman itself when running the installer? Right now I had to click on "Install Podman" in the UI, which then prompts for administrator access. This would be a problem in my environment, because developers are not granted administrator rights on their Windows machines.

Another solution I could think of would be installing podman "silently" before installing Podman Desktop (following instructions here: https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md#installing-podman ). Podman Desktop should pickup a already present installation of podman and use this installation, correct?

also: do you mind adding the `/S` argument to the docs here? -> https://github.com/containers/podman-desktop/blob/main/website/docs/Installation/windows-install.md#installing-podman-desktop-on-windows (I'm happy to provide a PR for this).

**Comment by benoitf** [comment]
There is no direct way for now to install podman itself when running the installer.
Your workaround proposal should work (install podman silently before Podman Desktop). And yes Podman Desktop will pick up existing installation. You might want to create a podman machine as well if there is none as well.


If you can file a PR, it would be very nice

Also if you're interested in providing a blog post or some documentation on how you're able to install Podman Desktop from an administrator point of view that would be awesome.

**Comment by benoitf** [comment]
@eidottermihi should we close the issue ?

**Comment by eidottermihi** [comment]
yes, now it's included in the docs. So I feel free to close ;) 

regarding a blog post documenting a managed installation from an administrator point of view I will reach out to you once it's done!
