### ISSUE TITLE
We repeat "extension" a lot in catalog page

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#9508]
### UX Description

In the catalog page, we repeat the word extension a lot (4 times each section).

IMHO we should just say "Compose" instead of "Compose extension" and same with the other extensions in the list.

![Image](https://github.com/user-attachments/assets/2ce93209-93f8-45f3-802a-ebe8f9bddc90)

### Request type

None

**Comment by benoitf** [comment]
UX team did that on purpose to not say that it's compose or kind that is being installed but the extension

**Comment by deboer-tim** [comment]
+1 to the design never saying 'Kind' without the word 'extension', but this repetition still gets me too. e.g. this screen has the word 'extension' 18 times (!).

Maybe we could treat this as a design review for "do we really need to include the name and 'built-in' twice on every card?" We don't really do this anywhere else, and removing some of the duplication would make the UI cleaner.
