### ISSUE TITLE
Improve titles of some tasks

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9536]
### Is your enhancement related to a problem? Please describe

With the tasks now showing on the statusbar we are exposing the titles of tasks more often. A few of these can be improved.

A couple of examples are:
1. `Create Container provider` when you are creating a new Podman Machine.  Should `Creating Podman Machine` 
3. `Stop podman-machine-default` -> `Stopping podman-machine-default`
4. `Start podman-libkrun` -> `Starting podman-machine-default`
5. `Create Kubernetes provider` (no difference between creating `kind` cluster or `minikube` cluster). Ideally this would be `Creating Kind provider` `Creating MiniKube provider`
6. When building an image the name is just `Build`. Can we make it `Building image <image-name>`?
We are also missing some:
1. When you pull an image, there is no message

### Describe the solution you'd like

Update the texts

**Comment by slemeur** [comment]
On this issue, we would like to see if we can extract all the different messages we are sending as notification. So we can then review them.

**Comment by SoniaSandler** [comment]
Those are the ones that I found:

- `Build ${imageName}`
- `Export container`
- `Import container`
- `Save images`
- `Load images`
- `Update ${tool.name} to v${version}`
- `Install ${tool.name} to v${versionToInstall}`
- `Uninstall ${tool.name} v${tool.version}`
- `Start ${providerConnectionInfo.name}`
- `Stop ${providerConnectionInfo.name}`
- `Create Container provider`
- `Delete ${providerConnectionInfo.name}`
- `Create Kubernetes provider`
- `Downloading ${updateVersion} update`

**Comment by Firewall** [comment]
Thank you @SoniaSandler that helps a lot!

Then I think this is what we should change them too. 
- `Build ${imageName}` -> `Building ${imageName}`
- `Export container` -> `Exporting ${containerName}`
- `Import container` -> `Importing ${containerName}`
- `Save images` -> `Saving image` <- Why is the `images` in plural? Are we saving more than 1 image?
- `Load images` -> `Loading image` <- Why is the `images` in plural? Are we saving more than 1 image?
- `Update ${tool.name} to v${version}` -> `Updating ${tool.name} to v${version}`
- `Install ${tool.name} to v${versionToInstall}` -> `Installing ${tool.name} to v${versionToInstall}`
- `Uninstall ${tool.name} v${tool.version}` -> `Uninstalling ${tool.name} v${tool.version}`
- `Start ${providerConnectionInfo.name}` -> `Starting ${providerConnectionInfo.name}`
- `Stop ${providerConnectionInfo.name}` -> `Stopping ${providerConnectionInfo.name}`
- `Create Container provider` -> `Creating ${containerProviderName} provider`
- `Delete ${providerConnectionInfo.name}` -> `Deleting ${providerConnectionInfo.name}`
- `Create Kubernetes provider` -> `Creating ${kubernetesProviderName} provider`
- `Downloading ${updateVersion} update` -> `Downloading ${updateVersion} update`

**Comment by benoitf** [comment]
please note that the title can be updated at the start, during increment and at the end

is it ok to have completed tasks with their `ing` at the end ?

✅ building quay.io/foo
✅ Saving quay.io/foo

or if completed we need a different wording ?

`✅ podman started`  vs `✅ Starting podman`

**Comment by Firewall** [comment]
@benoitf since in the UI we will have a ✅ infront I don't think we need the different wording.
