### ISSUE TITLE
Running a container which is automatically removed is not cleaned up properly.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#957]
### Bug description

I launch a container with a sh and set the flag to automatically remove the container.

When I exit the container, the window just shows me the container exits, but the container does not get removed from the list.

Also the new container should be at the top of the list. By default the list of containers should be sorted by Age with the newest at the top.

When I launch the container with a TTY, I would expect the App to jump to the terminal screen. Without a TTY maybe jump to the log screen?

Finally I am not seeing anything listed under age on non running containers.

### Operating system

linux

### Version

0.10.0

### Steps to reproduce

Run a create a container, with a TTY and a remove by default.

**Comment by benoitf** [comment]
Hello @rhatdan 

Trying to reproduce the following issue:
> When I exit the container, the window just shows me the container exits, but the container does not get removed from the list.

But on my side the container is removed

https://user-images.githubusercontent.com/436777/211834747-afd9decb-5edd-486b-b033-2e9413f75a47.mp4

**Comment by benoitf** [comment]
closing as not reproduced
