### ISSUE TITLE
Horizontal scroll bar in 'Update available now` dialog

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#9571]
### Bug description

After installing and staring Podman Desktop 1,13,1 dialog `Update Available Now` shows up and it has horizontal scrolling.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Steps to reproduce

Install Podman Desktop 1.13.1

![Image](https://github.com/user-attachments/assets/2188e20c-0c90-4f31-afdb-20ae5fece430)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/9393

**Comment by odockal** [comment]
Yep, closing as dupe.
