### ISSUE TITLE
When creating a container, the Basic command should show the default command to run within the container.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#958]
### Bug description

I often override the command to run in an image, so I need to be able to do this in the basic command.

This should be displayed as an entrypoint and cmd.

The defaults can be queried from the selected container image.

### Operating system

Linux

### Version

0.10.0

### Steps to reproduce

Go to containers and select create a container from an image.

**Comment by guraltsev** [comment]
I agree. Currently, the workaround is that if you run the container from cli and specify the command to execute there, then podman remembers it and on next run it runs the command you ran it with last time.

**Comment by jeffmaury** [comment]
Reopening because can't create containers based on nginx image

**Comment by benoitf** [comment]
@jeffmaury should we close this issue ?
