### ISSUE TITLE
Introduce categories for feedback

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#9582]
### Is your enhancement related to a problem? Please describe

In the feedback form, we should be able to differentiate the different categories of feedback

### Describe the solution you'd like

Categories: 
- Address words to developers (default)
- Feature request
- Bug

Mockup:
![Image](https://github.com/user-attachments/assets/28876b4a-b20d-4934-bd7b-9cbdb347e177)

**Comment by feloy** [comment]
@slemeur, in your idea, do the fields below the Category change when the Category is changed?

**Comment by slemeur** [comment]
In this issue, no, the Category will be an additional field.

Later on, https://github.com/containers/podman-desktop/issues/9584 and https://github.com/containers/podman-desktop/issues/9583 will differentiate the fields in the form based on the category.
