### ISSUE TITLE
Differentiate the feedback form for bug reports

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#9584]
### Is your enhancement related to a problem? Please describe

Bugs reported in the feedback form are not always actionable. We would like to be able to follow-up and use facilitate tracking those issues (as well as making them public)

### Describe the solution you'd like

Follow the mockup:
![Image](https://github.com/user-attachments/assets/495ad050-fa31-48c4-856f-6ecc50bdabfb)

(Automatic gathering of the system information will be done in another issue)

**Comment by SoniaSandler** [comment]
@slemeur is the bug report going to send anything as a feedback, or just open a preview on GitHub? It looks like in the mockup there is no submit/send feedback option

**Comment by slemeur** [comment]
If it's a bug, we want to be able to follow-up and eventually ask for more details to help identifying the issue. 
We will not send the feedback anymore, just help into the creation of the issue on github. 

For the telemetry, I think we still do want to see the impacts of that changes. Would be nice if we could send an event when the user is choosing the bug report category.

**Comment by SoniaSandler** [comment]
@slemeur do we want the telemetry event to be when choosing the bug category from the dropdown or maybe when the `preview on github` button is clicked from within the bug template?

**Comment by slemeur** [comment]
I'd say the two - the idea would be to be able to check if people are going through the entire flow or if they abandon while reporting their issue.
