### ISSUE TITLE
Enable gathering system information and enabled extensions when reporting bugs

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#9585]
### Is your enhancement related to a problem? Please describe

To improve bug reporting and troubleshooting, let's explore enabling the automatic collection of system information and relevant logs when users encounter issues. This would facilitate the resolution process.

### Describe the solution you'd like

Add checkboxes to:
- gather information from the system 
- gather logs 
- collect enabled extensions

Similarly to the following mockup:

![Image](https://github.com/user-attachments/assets/8df65d21-bde2-4035-b95c-62de2bcb1cc4)

**Comment by axel7083** [comment]
Depends on the followings
-  https://github.com/podman-desktop/podman-desktop/pull/9954
- https://github.com/podman-desktop/podman-desktop/pull/10000
- https://github.com/podman-desktop/podman-desktop/pull/9975

**Comment by axel7083** [comment]
Let's split that

- [ ] collect system info
  - [x] https://github.com/podman-desktop/podman-desktop/pull/10098 (backend)
  - [x] https://github.com/podman-desktop/podman-desktop/pull/10116 (frontend)
- [ ] collect logs (truncate ?) hard to know

**Comment by axel7083** [comment]
There is a hard limit (2028) to the size of an URL, we cannot provide the logs through the query parameters, because this is way too big (we could try to truncate, but I am not sure this is the solution). We could try to collect the errors ? But this is a pretty complicated task as we would need to parse etc.

**Comment by slemeur** [comment]
As the ability to gather all the logs is technically not possible without using a 3party service to store them - we will consider that this issue will be solved once those tickets are done:

- [x] https://github.com/podman-desktop/podman-desktop/pull/10276
- [x] https://github.com/podman-desktop/podman-desktop/pull/10098
- [x] https://github.com/podman-desktop/podman-desktop/pull/10116

**Comment by axel7083** [comment]
Thanks @slemeur I rename the issue

**Comment by axel7083** [comment]
Closing as all sub-issues completed
