### ISSUE TITLE
Docs: Adding an "architecture" document regarding extensions

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#9593]
### Is your enhancement related to a problem? Please describe

As per: https://github.com/containers/podman-desktop/pull/9540/files#r1812787335

Having an architecture on how an extension works would be beneficial to have.

### Describe the solution you'd like

Architecture document outlining how extensions hook into Podman Desktop.

**Comment by cdrage** [comment]
![Image](https://github.com/user-attachments/assets/42913a02-4088-4c05-88ad-c4544dacd1d6)

@slemeur For this document, are we just explaining / expanding on how we explain it via diagram on the https://podman-desktop.io/extend page?

**Comment by cdrage** [comment]
![Image](https://github.com/user-attachments/assets/42913a02-4088-4c05-88ad-c4544dacd1d6)

@slemeur For this document, I'm assuming that you'd like to convert what we have on the website into a more standardized doc to go beside all our other extension documents?

**Comment by slemeur** [comment]
Yeah, it would be nice to have a general overview of the extensions for Podman Desktop in our documentation. 
We already have nice onboarding documentation - but we are missing a bit of introduction to how they technically work. Especially on this page: https://podman-desktop.io/docs/extensions 

I was looking at this page: https://code.visualstudio.com/api which nicely guides the developer into the other piece of documentation that are available. 

So providing a nice technical introduction about the extensions, what's the architecture is designed and then driving the reader into the other piece of documentation would be nice.

**Comment by cdrage** [comment]
> Yeah, it would be nice to have a general overview of the extensions for Podman Desktop in our documentation. We already have nice onboarding documentation - but we are missing a bit of introduction to how they technically work. Especially on this page: https://podman-desktop.io/docs/extensions
> 
> I was looking at this page: https://code.visualstudio.com/api which nicely guides the developer into the other piece of documentation that are available.
> 
> So providing a nice technical introduction about the extensions, what's the architecture is designed and then driving the reader into the other piece of documentation would be nice.

Ah I see, I'll work on improving https://podman-desktop.io/docs/extensions then.

We do have https://podman-desktop.io/docs/extensions/developing but that's more of a developer-oriented point of view. I'll add more information to https://podman-desktop.io/docs/extensions similar to how visualstudio does it too.

Thanks!
