### ISSUE TITLE
The Initialize and start button and associated section are no longer displayed on the dashboard

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#9603]
### Bug description

Currently the `Initialize and start` button and the associated section are no longer displayed on the Dashboard when opening Podman Desktop from the main branch.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Start PD from main branch.
2. Make sure there are no podman machines available on the system.
3. Go to the Dashboard.
4. Notice that the `Initialize and start` button and associated section are no longer displayed.

**Comment by benoitf** [comment]
~~regression introduced by https://github.com/containers/podman-desktop/pull/9598~~

**Comment by benoitf** [comment]
so I should have done something wrong about my investigation this morning, it's not related to svelte

created the PR
