### ISSUE TITLE
replace isMac,IsWindows,isLinux utility functions by the one provided by the extension API in podman extension

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#9617]
### Is your enhancement related to a problem? Please describe

the podman extension has an utility methods duplicating the extension API, we should remove the one from the utility file

### Describe the solution you'd like

remove is* methods

**Comment by axel7083** [comment]
This is something I see a lot in a lot of places, I am assigning myself for next sprint (if that's okey), as this is a subject I think is important as it makes the test a bit harder to make, since we have a mixte of process.env and extensionApi.env

**Comment by cdrage** [comment]
Closed by accident in #10044
