### ISSUE TITLE
Proxy settings do not take effect when switched to system or disabled

### ISSUE THREAD

**Issue by Indekkusu545** [containers/podman-desktop#9625]
### Bug description

Proxy settings do not take effect when switched to system or disabled. After restart, only the first setting is valid.

https://github.com/user-attachments/assets/2d74256e-15ec-4ee5-a41d-e8262f4492eb

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.3

### Steps to reproduce

1. Set system proxy setting to `127.0.0.1:7890`
2. Select `System` in Podman Desktop -> Setting -> Proxy
3. Restart podman desktop
4. Push `Update` in Podman Desktop -> Setting -> Proxy. This will set env `http_proxy=http:127.0.0.1:7890` in the config file.
5. Select Proxy configuration to `Manual`. Change Web Proxy (HTTP) to `http:127.0.0.1:7891` and push `Update`. This will set env `http_proxy=http:127.0.0.1:7891` in the config file.
6. Select Proxy configuration to `System` and push `Update`. This did not change the config file.
7. Select Proxy configuration to `Disabled` and push `Update`. This did not change the config file.

**Comment by xbabalov** [comment]
Is this issue related/resulting in https://github.com/containers/podman-desktop/issues/9622?

**Comment by staylet** [comment]
Thanks to @jeffmaury  for the previous work on this issue.

However, I'm still experiencing the same problem in the recent version: setting the Proxy to "**Disabled**" in the user interface does not take effect.

**Bug description**

1. When I temporarily enable the proxy environment via **Settings > Proxy**, select "**Manual**", input values, and click **Update**, both of the following configuration files are updated correctly:

    - `~/.config/containers/containers.conf` (Host)

    - `/etc/systemd/system.conf.d/default-env.conf` (Podman machine)

    After rebooting the Podman machine, the proxy environment works as expected. 

2. However, when I try to **disable** the proxy environment by selecting "**Disabled**" in **Settings > Proxy** and clicking **Update**, the changes do not take effect. After rebooting the Podman machine, the proxy settings are still present.

**Operating system**
macOS Sequoia 15.5

**Installation Method**
Installed via Homebrew, with auto-update enabled.

**Version**
Podman Desktop v1.19.1

**Additional context**
Occasionally, I can work around this issue by setting the Proxy mode back to "**Manual**", clearing all the fields, and clicking **Update**. After rebooting the Podman machine, the proxy is effectively removed. However, this makes the "**Disabled**" option seem unreliable or possibly non-functional.

Would appreciate confirmation whether this is a regression or an intended behavior change. Let me know if logs or more information are needed.

Thanks!

**Comment by KiraYoushikage** [comment]
> Thanks to [@jeffmaury](https://github.com/jeffmaury) for the previous work on this issue.
> 
> However, I'm still experiencing the same problem in the recent version: setting the Proxy to "**Disabled**" in the user interface does not take effect.
> 
> **Bug description**
> 
> 1. When I temporarily enable the proxy environment via **Settings > Proxy**, select "**Manual**", input values, and click **Update**, both of the following configuration files are updated correctly:
>    
>    * `~/.config/containers/containers.conf` (Host)
>    * `/etc/systemd/system.conf.d/default-env.conf` (Podman machine)
>    
>    After rebooting the Podman machine, the proxy environment works as expected.
> 2. However, when I try to **disable** the proxy environment by selecting "**Disabled**" in **Settings > Proxy** and clicking **Update**, the changes do not take effect. After rebooting the Podman machine, the proxy settings are still present.
> 
> **Operating system** macOS Sequoia 15.5
> 
> **Installation Method** Installed via Homebrew, with auto-update enabled.
> 
> **Version** Podman Desktop v1.19.1
> 
> **Additional context** Occasionally, I can work around this issue by setting the Proxy mode back to "**Manual**", clearing all the fields, and clicking **Update**. After rebooting the Podman machine, the proxy is effectively removed. However, this makes the "**Disabled**" option seem unreliable or possibly non-functional.
> 
> Would appreciate confirmation whether this is a regression or an intended behavior change. Let me know if logs or more information are needed.
> 
> Thanks!

I have encountered this problem at the version Podman Desktop v1.19.2 too.
