### ISSUE TITLE
Should Kubernetes page show navigations submenu when cluster is not reachable

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#9646]
### Is your enhancement related to a problem? Please describe

When the cluster is not reachable, we are still able to navigate between the kube resources page (dashboard, node, deployment), this is a bit weird, as the cluster is not reachable.. ?

### Describe the solution you'd like

When the cluster is not reachable we could remove the sub navigation bar, and display the connection error at the center of the Kubernetes page, just like when the kubeconfig is empty and we display the list of extensions compatible.

### Additional context

Cc @cdrage @deboer-tim any opinion?

**Comment by deboer-tim** [comment]
I think I still lean towards showing the pages. Partially because e.g. if I'm looking at Deployments and then lose connection / restart Kind I wouldn't want the page to switch, or if it switched it wouldn't be natural to come back.

FWIW I had the same question when you start from scratch. We don't show the nav in that case, but I think it's different because there are no contexts yet.

**Comment by axel7083** [comment]
I will add this to the UX call !

**Comment by axel7083** [comment]
Here is an old mockup I made long time ago after opening https://github.com/containers/podman-desktop/issues/8341

![Image](https://github.com/user-attachments/assets/ee7220d4-ce80-4e15-872a-47dc184c241b)

I think there is room for improvement, as the dashboard do not clearly show that the cluster is not reachable, 

![Image](https://github.com/user-attachments/assets/97e08141-c95c-42cc-a465-f937e0c48fb9)

And each individual resources have a refresh button

![Image](https://github.com/user-attachments/assets/55c7532a-2431-49db-904b-8eed8460c895)

**Comment by axel7083** [comment]
As per UX call (31/10/24) we decide to make a more generic ticket https://github.com/containers/podman-desktop/issues/9701
