### ISSUE TITLE
native wayland support

### ISSUE THREAD

**Issue by ttys3** [containers/podman-desktop#97]
### Bug description

 segmentation fault when run with `--enable-features=UseOzonePlatform --ozone-platform=wayland` under Wayland

```
./container-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland                
[3021240:0413/151604.744455:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[3021300:0413/151604.750604:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1]    3021240 segmentation fault (core dumped)  ./container-desktop --enable-features=UseOzonePlatform 
```

### Operating system

Arch Linux

### Version

next (development version)

### Steps to reproduce

go to https://github.com/containers/podman-desktop/releases

download latest build:
https://github.com/containers/podman-desktop/releases/download/v0.0.202204130637-51e5089/container-desktop-0.0.202204130637-51e5089.tar.gz

### Relevant log output

```shell
./container-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland                
[3021240:0413/151604.744455:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[3021300:0413/151604.750604:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1]    3021240 segmentation fault (core dumped)  ./container-desktop --enable-features=UseOzonePlatform 
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
@ttys3 is is working without these extra parameters ?

**Comment by benoitf** [comment]
ok so it's related to https://github.com/electron/electron/issues/32436

**Comment by ttys3** [comment]
yes. I tried with a simple and dirty fix up, it works now:

![image](https://user-images.githubusercontent.com/41882455/163127163-b1573745-f300-4d8c-bd55-47b8b5148db6.png)

**Comment by benoitf** [comment]
@ttys3 can you try the linux binary from the pull request https://github.com/containers/podman-desktop/pull/98

click on https://github.com/containers/podman-desktop/actions/runs/2159772805#artifacts and click on `artifacts` and then scroll at the bottom

And try this linux binary (it's using latest electron build that should include the wayland fix)

direct link: https://github.com/containers/podman-desktop/suites/6104460121/artifacts/211926094

**Comment by ttys3** [comment]
@benoitf only update to electron 17.x latest is not enough, user will not able to move the window.

I put some code: https://github.com/ttys3/podman-desktop/commit/1aaac05941ebb12ddd15131ae04d77c075498d3e

Electron can now be built with Wayland support.

One problem is that it does not support drawing a title bar for any applications using it.

according to: https://github.com/microsoft/vscode/issues/124202#issuecomment-847827357

> This is a well known issue. Gnome under Wayland does not support server side decorations, which is a problem for all Electron apps that don't implement client side decorations (which VSCode does).

ref: https://github.com/electron/electron/issues/27016

**Comment by ttys3** [comment]
electron added Wayland window decorations in this PR https://github.com/electron/electron/pull/29618

the latest tag include this commit is [v18.0.0-alpha.1](https://github.com/electron/electron/releases/tag/v18.0.0-alpha.1)

**Comment by ttys3** [comment]
related commit and issue:

https://github.com/microsoft/vscode/commit/648b352b480c51d2a62092230348b54a1c830ec9

https://github.com/electron/electron/issues/27016

https://github.com/microsoft/vscode/issues/124202#issuecomment-847827357

https://github.com/microsoft/vscode/issues/109176

https://github.com/electron/electron/pull/29618

**Comment by benoitf** [comment]
ok so `17.4.0` is not enough.

**Comment by ttys3** [comment]
@benoitf  need plus these hack (https://github.com/ttys3/podman-desktop/commit/1aaac05941ebb12ddd15131ae04d77c075498d3e):

```javascript
    browserWindowConstructorOptions.titleBarStyle = 'hidden';
    if (!isMac) {
	  browserWindowConstructorOptions.frame = false;
    }
```

**Comment by ttys3** [comment]
> @ttys3 is is working without these extra parameters ?

Without these extra parameters, yes,  it works under Wayland using the legacy `XWayland` protocol.

**Comment by benoitf** [comment]
@ttys3 if you can confirm with Linux artifact from https://github.com/containers/podman-desktop/actions/runs/2160842336

direct tar.gz link : https://github.com/containers/podman-desktop/suites/6107239982/artifacts/212097393

I tried and it was working on my side:
![image](https://user-images.githubusercontent.com/436777/163172123-e19b399c-51e7-47b5-9472-c09c15b8bb5f.png)

**Comment by ttys3** [comment]
@benoitf confirmed, it works good

**Comment by benoitf** [comment]
Thanks
