### ISSUE TITLE
Cannot create libkrun podman machine - selected option for a dropdown not respected when submitting the form

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9706]
### Bug description

On Mac OS when I try to create podman machine using libkrun, it actually creates apple HV.

https://github.com/user-attachments/assets/5a603964-2baa-445f-b9b9-07c2733f94fc

### Operating system

Mac OS 14

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

Option 1.
1. Install podman desktop on Mac OS
2. Install Podman (5.2.5)
3. Create Podman Machine with LibKRun provider
4. Assert: Machine exists on Resources page, there is Libkrun value shown
Actual result: Machine is created but it is AppleHV VM Type. One can check via cli as well.

Option 2.
0. DO NOT HAVE DOCKER INSTALLED
1. Install podman Desktop, podman, minikube
2. Create and start podman machine (any)
3. Create Minikube cluster with default values (driver == `podman`)
4. Assert: Cluster is created
Actual result: `Exiting due to PROVIDER_DOCKER_NOT_FOUND: The 'docker' provider was not found: exec: "docker": executable file not found in $PATH, install Docker ...`

### Additional context

I think that it is related to any dropdown in the podman Desktop, not only Podman Machine. 

Possible related PR, issues: https://github.com/containers/podman-desktop/pull/9537, https://github.com/containers/podman-desktop/pull/9458

**Comment by odockal** [comment]
Another Example of the failure is creating a minikube cluster. There is default `podman` value for driver field. But it is not used at all, the error message we got there:
```
Exiting due to PROVIDER_DOCKER_NOT_FOUND: The 'docker' provider was not found: exec: "docker": executable file not found in $PATH, install Docker ...
```
This message exactly aligned when I try on cli in the env. where I have only podman: `minikube start --driver=docker`

When I try to switch a value in the driver dropdown, nothing changes. So the value is not propagated at all.

**Comment by SoniaSandler** [comment]
@odockal I think that the issue might be with/or related to https://github.com/containers/podman-desktop/blob/c632348acfe03a686e583926cf2d57688ed6ec1e/packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte#L342
The dropdown value are updating in `configurationValues` in the same file, but for some reason they don't show up when using `new FormData()`. I'm not sure how this method works, so I don't know what might be wrong with the dropdown items.

**Comment by odockal** [comment]
@SoniaSandler The latest changes in PR (thanks for fix!) shows that the problem was in that the hidden select element did not have `name` attribute.
