### ISSUE TITLE
Error encountered when trying to create minikube cluster in Podman Desktop

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#9707]
### Bug description

It seems that currently it's not possible to create a minikube cluster from PD do to the following error being thrown:

`Error: Failed to create minikube cluster. * Exiting due to PROVIDER_DOCKER_NOT_FOUND: The 'docker' provider was not found: exec: "docker": executable file not found in $PATH * Suggestion: Install Docker * Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/`

![Image](https://github.com/user-attachments/assets/ac58c84f-ec29-43b1-953f-ee172d74bb0d)

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

1. Install PD 1.14 version.
2. Install minikube PD extension.
3. Go to Settings -> Resources and try to create a new minikube cluster.
4. See that the error from above is thrown.

NOTE: Creating the minikube cluster in the terminal using minikube cli works fine.

### Relevant log output

* minikube v1.32.0 on Darwin 15.0.1 (arm64)

* Using the docker driver based on user configuration

* Exiting due to PROVIDER_DOCKER_NOT_FOUND: The 'docker' provider was not found: exec: "docker": executable file not found in $PATH
* Suggestion: Install Docker
* Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by odockal** [comment]
This issue has the same root cause as #9706.

**Comment by afbjorklund** [comment]
The suggested CLI workaround should be OK, until the next release when the dropdown is fixed (#9708).
