### ISSUE TITLE
Ability to browse images on remote repositories

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#971]
### Is your enhancement related to a problem? Please describe

Today, to start a container, we need to pull an image.

But then we need to know the exact name of this image.

### Describe the solution you'd like

I would like to be able to browse images and select one to pull or create a container from there.

### Additional context

https://github.com/containers/podman-desktop/issues/759

**Comment by feloy** [comment]
As discussed in https://github.com/containers/podman-desktop/pull/7875, the requirements are more important, as we also want to browse the images of a registry, independently of any container engine

**Comment by feloy** [comment]
Searching and listing images in an image registry is done using the `/v1/search` and `/v2/_catalog` of the Registry API.

Go implementation (for reference): https://github.com/containers/image/blob/main/docker/docker_client.go#L355

Node.js implementations:
- https://github.com/TritonDataCenter/node-docker-registry-client
-

**Comment by benoitf** [comment]
I think we've some code in `image-registry.ts` (to handle token used to communicate with the API) (so probably it should go to this location)
