### ISSUE TITLE
tty tab not visible / empty

### ISSUE THREAD

**Issue by fabrice-aeschbacher** [containers/podman-desktop#9718]
### Bug description

With v1.13.2 and higher, the Tty tab is empty.

Example with v1.13.3: 
![Image](https://github.com/user-attachments/assets/cd8ed39d-cd79-4357-b329-3891e7acb048)

 
Same with v1.12.0: 

![Image](https://github.com/user-attachments/assets/04d2724d-adcd-4dbd-b5c5-f938a2b35b46)

### Operating system

Debian 12

### Installation Method

wget https://github.com/containers/podman-desktop/releases/download/v1.13.3/podman-desktop-1.13.3.tar.gz  
tar xvf podman-desktop-1.13.3.tar.gz

### Version

1.13.3

### Steps to reproduce

podman run --name my-container -it -d debian:latest

**Comment by feloy** [comment]
It seems that the problem has been introduced with the commit https://github.com/containers/podman-desktop/commit/ca3aafced7efc4e393651da553b37fddc80b5d02
I'll look exactly what causes the problem in the changes of the commit
