### ISSUE TITLE
Manipulation of Compose CLI tool installed by Podman Desktop via CLI tools Page has errors

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9763]
### Bug description

There is multiple problems with compose after its installation. I can install it via CLI tools, and Compose onboarding, but then I cannot really upgrade, downgrade or uninstall it depending on how ti was installed. Check the recording.

https://github.com/user-attachments/assets/7d79fa8b-8e9c-4083-b8f1-6acf0a00b84d

### Operating system

Mac OS 14 M2

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

Compose installed by CLI tool:
1. Install compose via CLI tools (one version older than latest - 2.30.1)
2. Assert: Compose is installed correctly system wide
3. Try to upgrade
4. assert: upgrade is successful
Actual result: Unable to update Compose to version 2.30.2 -> In the Task: `error: cannot updat undefined version 2.30.1 to 2.30.2 as it was not installed by podman-desktop`
5. Uninstall compose via Cli  tools
6. Assert: compose uninstalled

Compose Installed by Compose onboarding (2.30.2):
1. Install compose via onboarding
2. Assert: compose is installed correctly
3. Open Cli tools
4. Assert: Compose 2.30.2 is identified correctly
5. assert: there is option to upgrade/downgrade
Actual result: there is only option to update
6. try to update compose
7. assert: you can update (?! downgrade I suppose) compose
Actual result: Unable to update Compose to version 2.30.2 -> in the task: `error: cannot update docker-compose: No cli tool installed`
8. Uninstall compose via CLI tools
9. Assert: compose is uninstalled
Actual result: `error: cannot uninstall docker-compose: No version detected`

**Comment by dgolovin** [comment]
@odockal could you add steps how did you install docker-compose using CLI?

I can install previous version 2.30.2 (latest is 2.30.3) with homebrew, but the name of installed cli is `docker-compose@2.30.2, so it does not interfere with one installed during onboarding.

**Comment by odockal** [comment]
> [@odockal](https://github.com/odockal) could you add steps how did you install docker-compose using CLI?
> 
> I can install previous version 2.30.2 (latest is 2.30.3) with homebrew, but the name of installed cli is `docker-compose@2.30.2, so it does not interfere with one installed during onboarding.

Sure, it is CLI tools Page in Podman Desktop. 
Settings -> CLI Tools -> find Compose section and install it through there
