### ISSUE TITLE
Cannot push image manifest with two underlying images

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9765]
### Bug description

I was building a simple alpine image on both architectures (amd and arm). I have image manifest that I did not named when building properly (I just used `alpine-local` with intention to edit the image name later) and if I try to push it, I am getting an error, since I am trying to push `localhost/alpine-local` image. 

https://github.com/user-attachments/assets/417ca69d-80a9-4a03-bd9c-bcf44c783d55

Also, the push manifest dialog is not properly sized and text/error is overflowing.

### Operating system

Mac OS

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

1. Build an image using some simple containerfile
2. Name image `my-alpine`
3. Build on both architectures
4. Assert: image manifest is created and two underlying image are listed there
5. Log into some registry
6. Push Manifest
7. Assert: Manifest is pushed
Actual result: error pushing manifest, see recording

### Additional context

I believe that we just need to add an option to rename the image manifest.

**Comment by cdrage** [comment]
The error is normal as it's trying to push to localhost (since you didn't add a name). Same thing happens on the CLI.

However... the text overflowing is not normal :( I'll open up a UX/UI issue for this.

**Comment by odockal** [comment]
@cdrage But I cannot rename the image/manifest. Then I cannot really push it.

**Comment by cdrage** [comment]
> @cdrage But I cannot rename the image/manifest. Then I cannot really push it.

Ahh, should we open up an issue instead adding feature for renaming a manifest? That could be done on CLI but not PD at the moment.

**Comment by odockal** [comment]
@cdrage So we need to open it on podman side, right? What is the command on cli? do you recall from the top of your head? I would open an issue then there.
