### ISSUE TITLE
Podman Machine create sliders are not visible when having both HyperV and WSL dropdown present

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9767]
### Bug description

Have both WSL and hyperV features enabled and podman desktop started with admin rights. Open Create new Machine and then try to noticed the sliders that should be available for hyperv option once it is selected in the dropdown. 

![Image](https://github.com/user-attachments/assets/c3c335ca-d70c-405e-ba3e-3f0d43608653)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Additional context

When I have only a hyperv feature enabled, I can see the sliders.

**Comment by xbabalov** [comment]
Trying to change any input field will update the UI.
