### ISSUE TITLE
Podman Desktop does not respond when azure-kubelogin installed

### ISSUE THREAD

**Issue by xvrlsc** [containers/podman-desktop#9778]
### Bug description

When I have azure-kubelogin installed on my computer, Podman Dekstop is totally frozen. It does not open at all. And the icon of Podman Desktop is unclickable and displays "Podman Desktop is initialized"

### Operating system

Windows 11, Windows 10, macOS Sequoia 15.1

### Installation Method

Chocolatey (Windows)

### Version

1.13.2

### Steps to reproduce

Stop Podman Desktop.
Install azure-kubelogin (via chocolatey)
Reboot
Start Podman Desktop.

To make it work again, you just need to stop podman desktop, uninstall azure-kubelogin and restart podman-desktop. It works directly.

**Comment by feloy** [comment]
I suspect the kubeclient in Podman Desktop to try to "resolve" the authentication parts of the kubeconfig file with azure-kubelogin, and entering either in an infinite loop, or waiting for some input. It may be the same with other cloud providers kube auth extensions.

Thanks for the report, we will try to reproduce the problem.

**Comment by odockal** [comment]
Adding a link to something similar we have already seen, so related issue: https://github.com/podman-desktop/podman-desktop/issues/8486

**Comment by feloy** [comment]
dup of #9879
