### ISSUE TITLE
Toast task tile is empty after some actions like deleting or stopping a podman machine

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9779]
### Bug description

Only a successful toast task tile appears without any information about the action/task origin, ie. when I stop and the delete the podman machine.

![Image](https://github.com/user-attachments/assets/97c367fe-00d4-40b9-8778-c8c84b0bdff6)

### Operating system

Mac OS 14

### Installation Method

None

### Version

1.14.0

### Steps to reproduce

1. Create and start the podman machine
2. enable Task toast in preferences
3. Stop the machine
4. delete the machine
5. Assert: More precise toasts are shown
Actual: empty toasts

**Comment by slemeur** [comment]
I don't think they are empty, I can see the labels, but the colors is white so almost impossible to see

**Comment by odockal** [comment]
Oh, you are right, there is some text indeed. Did not notice that.
