### ISSUE TITLE
Unable to read "built-in extension" on Extensions page UI

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#9789]
### Bug description

Unsure which commit yet, but looks like it doesn't show correctly anymore in light mode. 

 ![Image](https://github.com/user-attachments/assets/9398358f-41ea-4092-8772-c51fc514db20)

### Operating system

mac m1

### Installation Method

None

### Version

1.13.3

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/9772

**Comment by feloy** [comment]
closing as a dup of #9772
