### ISSUE TITLE
terminal unresponsive when restarting a container

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#9794]
### Bug description

When on a terminal page for a container, if I press the "restart container", the terminal reappears, but is unresponsive.

I need to go to another page and come back to the terminal to make it work again.

https://github.com/user-attachments/assets/6097c86d-78ec-46dd-9ca2-2e4100a77c56

The problem seems very similar to #9771 (except using restart button instead of stop + start), but the root cause seems different, as the PR #9793 does not fix this problem

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/9771

**Comment by feloy** [comment]
> looks like a dup of [#9771](https://github.com/containers/podman-desktop/issues/9771)

I don't think, I updated the message with more details
