### ISSUE TITLE
Minor UI glitch - Update Notification Window Content is too wide and causes scrolling

### ISSUE THREAD

**Issue by kattekrab** [containers/podman-desktop#9798]
### Bug description

Running on MacOS Sonoma 14

Minor UI glitch - Update Notification Window Content is too wide and causes scrolling
![Image](https://github.com/user-attachments/assets/0c0e9b5c-0da3-4e63-8acc-1d6a67c9e34c)

### Operating system

macOS Sonoma 14.7.1

### Installation Method

Installer from website/GitHub releases

### Version

1.13.3

### Steps to reproduce

Not sure I can reproduce it, have not tried, just grabbed a screenie to show you. 
Feel free to close won't fix if not enough info here, I just thought it might be useful to show this behaviour.

**Comment by benoitf** [comment]
Thanks for the report @kattekrab 

It's fixed in the upcoming 1.14 release 

Duplicating https://github.com/containers/podman-desktop/issues/9393
