### ISSUE TITLE
Task popup should reflect selected dark/light theme

### ISSUE THREAD

**Issue by gastoner** [containers/podman-desktop#9869]
### Bug description

![image](https://github.com/user-attachments/assets/672d243c-4269-4dee-9858-f2dedeac5f47)

### Operating system

Win, WSL Linux

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

E.g. create machine => popup will show

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
might be a dup of https://github.com/podman-desktop/podman-desktop/issues/9779
