### ISSUE TITLE
Remove `Troubleshooting` and `Share your feedback` button from the statusbar

### ISSUE THREAD

**Issue by Firewall** [containers/podman-desktop#9900]
### Is your enhancement related to a problem? Please describe

As part of this [Epic](https://github.com/podman-desktop/podman-desktop/issues/9077) we changed the help menu to be a popup menu instead of a seperate page. This also included adding the troubleshooting and share your feedback buttons. Since these are now duplicate and we are in an effort to simplify the statusbar, the `Troubleshooting` and `Share your feedback` buttons can be removed. 

### Describe the solution you'd like

Remove the `Troubleshooting` and `share your feedback` buttons from the statusbar.

**Comment by Firewall** [comment]
> IMHO I would separate the removal of other icons from this PR. Scope is too big.
> First: add things/rework only help and get feedback, second: remove things, not do too many things at once.
> 
> The title of the issue or the PR is to move help page to a dropdown, not removing bulb and share feedback icons, so as a reviewer, it's not doing what is said, so I'm requesting changes.
> 
> About the content, it looks like the original intent was to reduce the number of clicks while here I would do extra clicks.(if bulb and report feedback direct action icons are moved)
> 
> But my point is that to click on useful links, I would have to move the cursor far way from the first click it looks like it'll do the opposite of what it was describing (looks like import links are on the top while clicking on a menu from the bottom I expect the opposite)

[Feedback from](https://github.com/podman-desktop/podman-desktop/pull/9867#issuecomment-2475806441) @benoitf 

> About the content, it looks like the original intent was to reduce the number of clicks while here I would do extra clicks.(if bulb and report feedback direct action icons are moved)

We have seen it quite often that users don't make the connection between the `light bulb` icon and troubleshooting. Having it in a menu where we can also add a text label can help with that. 

This also helps reduce the amount of icons in total that are on the statusbar thus removing the amount of icons a user will need to hover over to understand what they mean. 

> But my point is that to click on useful links, I would have to move the cursor far way from the first click it looks like it'll do the opposite of what it was describing (looks like import links are on the top while clicking on a menu from the bottom I expect the opposite)

It might be an extra click, but now users won't need to hover and wait for some time to understand what the `light bulb means`.

**Comment by benoitf** [comment]
> We have seen it quite often that users don't make the connection between the light bulb icon and troubleshooting. Having it in a menu where we can also add a text label can help with that.

it's a shortcut, when you're using the product everyday it's helpful. If you're new, clicking on the help menu you'll see the entry.

> This also helps reduce the amount of icons in total that are on the statusbar thus removing the amount of icons a user will need to hover over to understand what they mean.

It's not taking much place compare to adding provider's name. Also note that all users are not newcomers.

>It might be an extra click, but now users won't need to hover and wait for some time to understand what the light bulb means.

It's discoverability. People will see the full entries in the help menu.
Also probably less people will click on report feedback. Useful content will be drowned in too many entries

**Comment by Firewall** [comment]
We decided during the UX call that we won't do this for now. We can re-open in the future if we want.
