### ISSUE TITLE
Forms aren't aligned in create container

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#991]
### Is your enhancement related to a problem? Please describe

Within creating a container, there are sections where it's not consistent in alignment such as the front page.

See below:
![Screenshot 2022-12-07 at 2 21 32 PM](https://user-images.githubusercontent.com/6422176/206276035-55b0cbd5-c51a-4c7c-979a-f0e979f31541.png)
![Screenshot 2022-12-07 at 2 20 46 PM](https://user-images.githubusercontent.com/6422176/206276038-4661f040-0e76-4b94-bdf7-e5741a8fd6bf.png)

### Describe the solution you'd like

`p-2` / `m-2` within tailwindcss to fix the indenting / or the equivalent change.

**Comment by benoitf** [comment]
closing as won't fix as it's more than one year that issue has been created
