### ISSUE TITLE
Preferences -> Update and Light Mode Preferences Dropdown values are switching

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9917]
### Bug description

Update Preference string dropdown button offering in the preferences offers only options from Light mode.

![Image](https://github.com/user-attachments/assets/c24995e5-8225-41f6-8974-642da4359b9d)

Screencast:
https://github.com/user-attachments/assets/4e060e25-6e3b-4e96-bb1b-24ebba2d16fb

### Operating system

Windows 10

### Installation Method

None

### Version

1.14.0

### Steps to reproduce

1. Open Preferences -> appearance
2. Set the value to System or other (requires some playing)
3. Open Preferences -> Update Section
4. Check values on dropdown
5. Assert: startup/never
Actual: System, dark, light

It also works vice versa, if value is changed in update, the dropdown values changed in appearance.

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
I don't reproduce on my end

main branch:
![Image](https://github.com/user-attachments/assets/97e321b8-7623-43aa-9ac0-2ac7977fe42a)

1.14.1
![Image](https://github.com/user-attachments/assets/c5623896-16f6-45cb-916f-687c213af28d)

**Comment by odockal** [comment]
I can see it on Linux and Windows (both 1.14.1). I can confirm it does not affect Mac OS.

**Comment by benoitf** [comment]
looks like an issue of the Dropdown component, assigning @deboer-tim

**Comment by odockal** [comment]
We have also dupe of crc-extension: https://github.com/crc-org/crc-extension/issues/410

**Comment by jeffscottbrown** [comment]
> I don't reproduce on my end

In my environment I am seeing that if I navigate straight to the "Update" preference pane then I see the incorrect options in the drop down.  If I visit some other preference pane first and then go to "Update", I see the correct options.
