### ISSUE TITLE
reduce verbosity of logs of kubernetes cluster check

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#9942]
### Is your enhancement related to a problem? Please describe

Restarting a podman machine is not restarting the kind cluster for example

But then I'm spammed by messages like

```
1:08:57 PM [main] Trying to watch routes on the kubernetes context named "kind-kind-cluster" but got a connection refused, retrying the connection in 12s. Error: HTTP-Code: 404
Message: Unknown API Status Code!
Body: "404 page not found\n"
Headers: {"audit-id":"1ce03285-409e-41fc-b342-abd9559ab4f1","cache-control":"no-cache, private","connection":"close","content-length":"19","content-type":"text/plain; charset=utf-8","date":"Mon, 18 Nov 2024 12:08:57 GMT","x-content-type-options":"nosniff","x-kubernetes-pf-flowschema-uid":"b67a024d-e8ba-4244-8501-65ecf379f8b4","x-kubernetes-pf-prioritylevel-uid":"5224af8a-5433-4022-9a72-aa2b6140d6cc"})
```

It's blocked at 12s anyway, I think it would went to 60s but it's a different issue

It's too verbose. It containers headers, message and body fields. At this level of data, I expect only seeing that the cluster is not reachable and that it'll try soon.

### Describe the solution you'd like

reduce the logs. Should be only one sentence

**Comment by benoitf** [comment]
we could also remove entirely this and only keep it at the trace level 

starting normally Podman Desktop with a stopped cluster is producing 100lines in few seconds

another option would be that if it has not changed since the last check, we don't display that we're doing again the check (again and again)

**Comment by benoitf** [comment]
or display the Backoff options in the troubleshooting tab of Podman Desktop where I could try different options, etc

**Comment by feloy** [comment]
These messages will be removed/reworked by the issues in the epic https://github.com/podman-desktop/podman-desktop/issues/9818
